### ISSUE TITLE
[BUG]Windows系统关闭应用窗口后，再从任务栏打开响应非常慢 

### ISSUE THREAD

**Issue by ForestL18** [clash-verge-rev/clash-verge-rev#100]
**Describe the bug**
Windows上关闭窗口后再从任务栏打开响应很慢，基本是2秒左右

**To Reproduce**
每次关闭窗口从任务栏打开的时候都会很慢

**Expected behavior**
点击任务栏图标即点即开

**Screenshots**
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/45709305/95e307a8-53bf-4ca9-b31c-ae3a3b495065)

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/45709305/0d4cf8d3-9258-49cd-9338-b22386c31390)

**Information**

- OS: Windows 10 22H2
- Clash Verge Version: 1.4.3
- Clash Core: Clash Meta

**Additional context**
和这个[issue](https://github.com/clash-verge-rev/clash-verge-rev/issues/12)里面的老哥情况完全一样

我已经尝试重装了最新的webview2

我的cpu是12400F，gpu是3060ti，性能用来运行这个程序问题应该不大

**Comment by MystiPanda** [comment]
webview2启动需要时间，直接显示窗口会导致窗口闪烁一下未加载的白色，前作者为了解决这个问题使用的逻辑是创建窗口后添加了888ms的延迟，后续会想办法优化一下。

**Comment by MystiPanda** [comment]
提交issue之后我们都能看到，这里不是群组，没有必要在issue里面再次@。

**Comment by ForestL18** [comment]
> 提交issue之后我们都能看到，这里不是群组，没有必要在issue里面再次@。

好的，我这里@只是想告诉上个issue的回答者，之后反馈问题我会注意，谢谢了
