### ISSUE TITLE
[BUG]运行 ./clash-verge时报错

### ISSUE THREAD

**Issue by godofpp** [clash-verge-rev/clash-verge-rev#1000]
### 问题描述 / Describe the bug

运行./clash-verge是报错：./clash-verge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./clash-verge)

### 复现步骤 / To Reproduce

ros@ros-virtual-machine:~/clash_1.6.2/usr/bin$ ./clash-verge 
./clash-verge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./clash-verge)

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu18.04

### 日志 / Log

不会看

**Comment by xishang0128** [comment]
@godofpp https://www.google.com/search?q=%2Flib%2Fx86_64-linux-gnu%2Flibc.so.6%3A+version+%60GLIBC_2.28%27+not+found
