### ISSUE TITLE
[BUG] Windows7下报错0xc0000005

### ISSUE THREAD

**Issue by trjtr6kiy7tk** [clash-verge-rev/clash-verge-rev#1004]
### 问题描述 / Describe the bug

在Windows7环境下运行时，报错：应用程序无法正常启动(0xc0000005)。
v1.6.0以下版本均可正常启动，不报错。
已安装WebView2。

### 复现步骤 / To Reproduce

1.在Windows7环境下，将Clash Verge版本升级到v1.6.1及以上版本。
2.运行Clash verge。
3.弹出错误提示框，显示：应用程序无法正常启动(0xc0000005)。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 7

### 日志 / Log

软件未成功启动 无法生成日志

**Comment by MystiPanda** [comment]
@trjtr6kiy7tk Clash Verge不会对Win7提供任何专门的适配，请搜索错误码自行解决。
