### ISSUE TITLE
[Feature] 在系统代理中自定义代理时保留默认的绕过本地IP规则

### ISSUE THREAD

**Issue by EricCorleone** [clash-verge-rev/clash-verge-rev#1006]
### 功能描述 / Feature description

在系统代理中自定义代理绕过会导致默认的绕过本地IP规则消失，而且即使再删掉自己填的IP和域名也不会恢复，意味着一旦需要自定义绕过的IP或者域名，就必须手动补上类似“192.168..”之类的本地IP规则，挺麻烦的。
![屏幕截图 2024-05-11 090846](https://github.com/clash-verge-rev/clash-verge-rev/assets/55615178/ae30bab6-cb7d-46b3-bfde-f0e856f7d917)
是否可以改为将默认的绕过本地IP规则保留在输入框里可供编辑，而不是一输入就直接被覆盖掉？

### 使用场景 / Use case

当用户需要自定义代理绕过的时候，可以直接在默认的绕过本地IP规则下面添加自己的规则，而不是直接覆盖掉默认的规则。

**Comment by tang-zack** [comment]
目前也发现了这个问题 希望优化一下

**Comment by longshihui** [comment]
同样的问题

**Comment by Joker2Yue** [comment]
也发现了这个问题，建议优化

**Comment by tang-zack** [comment]
**貌似以;号隔开 好像不得行**，需要以,号隔开才生效。但是看到教程上设置也是用的;号隔开的，这就比较疑惑了！

**Comment by dongchengjie** [comment]
> **貌似以;号隔开 好像不得行**，需要以,号隔开才生效。但是看到教程上设置也是用的;号隔开的，这就比较疑惑了！

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/12ac8958-2d4b-4a1c-97d8-4d6e494a02f0)

**Comment by wufei-cloud** [comment]
为什么我的配置了系统代理的内容，浏览器访问还是不通呢
![屏幕截图 2024-12-03 121523](https://github.com/user-attachments/assets/d83fc260-2d80-4d51-8198-1238afa30965)
