### ISSUE TITLE
[Feature] DOMAIN-SUFFIX,myabb.com,myproxy1(这里如何实现多个proxy自动切换？)

### ISSUE THREAD

**Issue by nogoo** [clash-verge-rev/clash-verge-rev#1007]
### 功能描述 / Feature description

比如我在merge文件中加入：
prepend-rules:
DOMAIN-SUFFIX,myabb.com,myproxy1

myproxy能提供多个选择,比如可以写成myproxy1/myproxy2 等类似，因为如果切换订阅，这里的myproxy1 可能没有，会报错not found myproxy1 ，此时希望能切换到myproxy2 如果存在

### 使用场景 / Use case

比如我在merge文件中加入：
prepend-rules:
DOMAIN-SUFFIX,myabb.com,myproxy1

如果切换到另外一个订阅，这里的myproxy1 可能没有，会报错not found myproxy1,希望支持多个选择

或者是我不清楚怎么使用，还望告知实现方式，谢谢

**Comment by dongchengjie** [comment]
暂时支持不了😅 后续会改进执行链和配置关联
