### ISSUE TITLE
[BUG] MacOS下控制中心不显示图标，且关闭后无法打开

### ISSUE THREAD

**Issue by middle-chunjie** [clash-verge-rev/clash-verge-rev#1008]
### 问题描述 / Describe the bug

安装之后可以正常打开，但是程序坞并不会显示，而且在将界面关闭之后软件就会进入后台，此时无法通过任何方式重新将界面打开。只能将后台删除之后重新运行。

### 复现步骤 / To Reproduce

1. 安装
2. 打开软件（查看程序坞）
3. 关闭软件（查看后台）

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.4

### 日志 / Log

None

**Comment by wonfen** [comment]
在任务栏有图标。没听懂你说的。
