### ISSUE TITLE
[BUG] 当TUN Mode打开时，无法通过Merge或Script设置dns.enable为false

### ISSUE THREAD

**Issue by ISNing** [clash-verge-rev/clash-verge-rev#1009]
### 问题描述 / Describe the bug

因为有些内网域名的需求，在上游设置了smartdns分流，希望能够直接使用上游的dns服务

### 复现步骤 / To Reproduce

Merge:
```yaml
dns:
    enable: false
```
Script:
```js
const dnsConfig = {
  "enable": false
};

function main(config) {
  config["dns"] = dnsConfig;
  return config;
}
```
两种方式都尝试过，但在TUN打开的情况下均未生效

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

No Log

**Comment by dongchengjie** [comment]
TUN强制开启DNS

**Comment by ISNing** [comment]
> TUN强制开启DNS

那么是否有办法不开启呢，或者是自动代理到上游dns

**Comment by dongchengjie** [comment]
> > TUN强制开启DNS
> 
> 那么是否有办法不开启呢，或者是自动代理到上游dns

将DNS服务器设置成上游DNS就行了，你不改的话DNS配置有默认值

**Comment by ISNing** [comment]
好的，谢谢您的帮助
