### ISSUE TITLE
直连steam下载使win11cup负载异常

### ISSUE THREAD

**Issue by lly0010** [clash-verge-rev/clash-verge-rev#101]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information**

- OS: [e.g. macOS]
- Clash Verge Version: [e.g. 1.3.4]
- Clash Core: [e.g. Clash or Clash Meta]

**Additional context**

**Comment by wonfen** [comment]
需要更多信息，截图等等。

**Comment by lly0010** [comment]
![eddcfaa7d0bb25fac41c6f7e1878c12](https://github.com/clash-verge-rev/clash-verge-rev/assets/104768330/b3cff459-58a9-47fb-a045-85382afd6894)
zuigh最高到过70%没截图到

**Comment by lly0010** [comment]
![屏幕截图 2023-12-09 105942](https://github.com/clash-verge-rev/clash-verge-rev/assets/104768330/e081520e-08e7-4157-aca1-d5739b42a2f1)
截图到了非常卡电脑

**Comment by lly0010** [comment]
![屏幕截图 2023-12-09 110129](https://github.com/clash-verge-rev/clash-verge-rev/assets/104768330/5cafcc3a-09eb-4d4a-8d99-9c2211b07a0a)
cpu直接跑满了

**Comment by MystiPanda** [comment]
看一下日志

**Comment by TobyLi223** [comment]
我也碰到了这个问题，不过是在ny上碰到的，载入JS后就会这样，感觉是内核问题，也不知道怎么反馈

**Comment by lly0010** [comment]
![屏幕截图 2023-12-09 110931](https://github.com/clash-verge-rev/clash-verge-rev/assets/104768330/63352a09-2dc5-4ffd-836d-0f0d3b6f764e)
日志一直跳

**Comment by lly0010** [comment]
![屏幕截图 2023-12-11 160055](https://github.com/clash-verge-rev/clash-verge-rev/assets/104768330/fcbf03e6-512f-42b5-bc37-5ec0aa179953)
内存占用也异常了

**Comment by kaigedong** [comment]
我也有CPU占用高的问题。Linux下，日志等级开启为“Debug”模式，但日志中，没有可疑的输出。内存占用也不高。

![20231227_17h42m15s_grim](https://github.com/clash-verge-rev/clash-verge-rev/assets/38344234/579bc53d-c1a6-4806-9a38-cb4d9d236574)
