### ISSUE TITLE
[Feature] 建议优化软件图标

### ISSUE THREAD

**Issue by vcs6481712** [clash-verge-rev/clash-verge-rev#1010]
### 功能描述 / Feature description

感觉现在的图标不太美观,希望可以好好优化一下

### 使用场景 / Use case

桌面图标,及任务栏图标

**Comment by EarOfWheat** [comment]
”设置-界面设置“可以自定义图标

verge可能有自己的风格（虽然我觉得clash for windows更好看

**Comment by thirking** [comment]
其实简单一点也挺好的，比如：https://clash.razord.top/

**Comment by jmui114** [comment]
> 其实简单一点也挺好的，比如：https://clash.razord.top/

这个对于代理组与代理节点进行了撞色区分真的太直观了，尤其是像我这种多机场多代理组嵌套的用户来说，简直不要太舒服，后续打算就通过这个来管控了😄😄

**Comment by zoze0** [comment]
![QQ20240513-123238](https://github.com/clash-verge-rev/clash-verge-rev/assets/20562449/1e98e522-24e6-4e2f-8b8d-3fafba3fc90e)

比其他图标小一圈
