### ISSUE TITLE
[BUG] 26100.2下无法打开面板

### ISSUE THREAD

**Issue by rpzone** [clash-verge-rev/clash-verge-rev#1012]
### 问题描述 / Describe the bug

点击任务栏的图标之后，无法展示控制面板，且此时任务栏的图标消失。

### 复现步骤 / To Reproduce

任务栏图标，点击右键，选择控制面板。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10.0.2600.2

### 日志 / Log

NO

**Comment by dongchengjie** [comment]
https://clash-verge-rev.github.io/faq/windows.html#_2
