### ISSUE TITLE
[Feature] 希望能够增加一个CFW的“parsers"功能，以便更加灵活的处理规则。 

### ISSUE THREAD

**Issue by asnfohsdgfbkxcv** [clash-verge-rev/clash-verge-rev#1014]
### 功能描述 / Feature description

增加配置文件的预处理，同CFW的parsers、surge的模块等功能类似。

### 使用场景 / Use case

灵活的处理托管类的脚本，增加自定义规则的同时不影响托管订阅更新。。

**Comment by dongchengjie** [comment]
https://clash-verge-rev.github.io/guide/script.html
