### ISSUE TITLE
[BUG] 代理组滑倒底之后，代理组列表会抖动

### ISSUE THREAD

**Issue by kfgNfbxR** [clash-verge-rev/clash-verge-rev#1017]
### 问题描述 / Describe the bug

代理组滑倒底之后 手放开，代理组列表会抖动
![演示 (2)](https://github.com/clash-verge-rev/clash-verge-rev/assets/17379227/3f227516-c6c2-4430-967a-ffe4fc8bc14b)

### 复现步骤 / To Reproduce

版本：v1.6.2
代理组条数：21
代理组滑倒底之后 手放开，列表会上下抖动几次

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11

### 日志 / Log

无

**Comment by wonfen** [comment]
请尝试最新alpha版

**Comment by kfgNfbxR** [comment]
新版本可以
