### ISSUE TITLE
[Feature]如何设置域名及IP的白名单. 

### ISSUE THREAD

**Issue by pro911** [clash-verge-rev/clash-verge-rev#1019]
### 功能描述 / Feature description

有没有哪里可以设置域名和ip的白名单,例如我想让 *.baidu.com 直接连接.

### 使用场景 / Use case

很多域名是内部路由,或者一些不需要翻墙访问过慢的域名设置.

**Comment by TeslaLyon** [comment]
请问找到解决办法了吗？
