### ISSUE TITLE
[BUG] 服务安装失败/Tun 模式开启失败

### ISSUE THREAD

**Issue by xlh8394** [clash-verge-rev/clash-verge-rev#102]
2023-12-08 15:53:30 ERROR - failed to connect to the Clash Verge Service
2023-12-08 15:53:48 ERROR - failed to install service with status 1

**Comment by xlh8394** [comment]
系统代理是可以正常翻墙的，始终打不开tun模式

**Comment by wonfen** [comment]
使用管理员模式运行软件，或者打开服务模式。

**Comment by xlh8394** [comment]
试过管理员模式打开也是这样

**Comment by MystiPanda** [comment]
管理员权限运行一下安装目录下resources目录下的uninstall-service.exe就可以了

**Comment by xlh8394** [comment]
> 管理员权限运行一下安装目录下resources目录下的uninstall-service.exe就可以了

可以了，非常感谢。
