### ISSUE TITLE
[Feature] 代理页面改善建议

### ISSUE THREAD

**Issue by Back-T0** [clash-verge-rev/clash-verge-rev#1021]
### 功能描述 / Feature description

这样的布局能更加有效地呈现信息( 或许还能更优雅 ):
![5f559d47b90c2aecd05429f055d2538](https://github.com/clash-verge-rev/clash-verge-rev/assets/78223825/ba365b39-a81a-4dfc-9398-d54cd6971ab3)

相比于原来的:
![289f8b04a46156f52b1c11ae798a646](https://github.com/clash-verge-rev/clash-verge-rev/assets/78223825/4c97d50b-14eb-4abb-beb7-f02741eea6e9)

原来的设计, 在策略组内节点比较多的情况下, 切换选中策略组的时候需要频繁滚动鼠标( 虽然可以通过拖动滚动条快速回到顶部, 但还是有点麻烦 )
![1ec7e6a603f842e3a8dc9f0c4d3d4b0](https://github.com/clash-verge-rev/clash-verge-rev/assets/78223825/d82ff793-1ff9-4ccf-9927-58fd76f46616)

大多数情况下都是窗口的宽度大, 然而当用户使用窄宽度的时候, 原来的布局是正确的
但是要将展开的策略组始终顶置, 因为这样可以快速收起
![3805da8056abff41b96a38890319321](https://github.com/clash-verge-rev/clash-verge-rev/assets/78223825/adaa0080-eba8-42f9-8e78-8aa2f9793a51)

### 使用场景 / Use case

建议只是基于个人的使用感受,  感谢开发者的辛勤付出

**Comment by UbiVPN** [comment]
感覺原來的佈局要簡潔些，你這個太雜亂了

**Comment by dongchengjie** [comment]
如果真的动过这里的代码就知道，难实现的不是效果，是性能💀
上百个就略卡了，几百个的哪种给卡懵逼，这还是限制后的结果

**Comment by KKFantasy** [comment]
这个设计看起来相当不错，很实用，不过如果像楼上开发者所说对性能影响的话，那就只能牺牲UI了。

**Comment by lbcake** [comment]
> 这个设计看起来相当不错，很实用，不过如果像楼上开发者所说对性能影响的话，那就只能牺牲UI了。

现在 性能占用就很高了。    内存占用 待机状态 150M+    还不算切换页面  来回切换页面直接200M+   内存占用高  （就是把内核20M占用减去   内存占用 还是稍高）

**Comment by junlongzzz** [comment]
怎么说呢，作为GUI程序，我还是那个观点，保持核心功能的稳定性优先，这个建议是不错，但如上所说牺牲过大的话，大可不必
