### ISSUE TITLE
[Feature] 可否做一个流媒体解锁检测模块

### ISSUE THREAD

**Issue by duannian9527** [clash-verge-rev/clash-verge-rev#1022]
### 功能描述 / Feature description

流媒体解锁检测模块

### 使用场景 / Use case

翻翻墙后端测评结果时效性低，本地检测解锁情况，会更方便使用

**Comment by dongchengjie** [comment]
你知道有多少流媒体吗，不是你在用就是常见的，我看那个流媒体检测脚本的有几十个站点，每个国家都有，每个检测机制不一样。这样搞弄得像什么盗版视频网站似的
