### ISSUE TITLE
[BUG] 卸载服务显示IO error in winapi call TUN无法使用

### ISSUE THREAD

**Issue by Shanwer** [clash-verge-rev/clash-verge-rev#1024]
### 问题描述 / Describe the bug

参考了很多关于TUN的issue都没有解决，后来尝试把系统内深信服的EasyConnect卸干净了在尝试还是无果，但是发现运行uninstall service有一行提示不知道是什么，搜索这个提示没有找到相关内容所以来提issue了
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/16631550/f7ff4903-ce36-41ce-af78-bf8001be699a)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/16631550/44a9a039-d646-423f-89e6-69f65564ae05)

### 复现步骤 / To Reproduce

使用管理员权限运行unistall service，在运行install service，用管理员权限打开clash verge，先启用服务模式再启用TUN模式无法联网

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 23H2

### 日志 / Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/16631550/5496bdb0-e417-413f-8795-c4be96461cd9)
[2024-05-15-2345.log](https://github.com/clash-verge-rev/clash-verge-rev/files/15323945/2024-05-15-2345.log)

**Comment by Shanwer** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/16631550/cafe8c91-57a5-4fb9-8e4b-5554d3dcced1)
在开关tun模式的时候还发现有这个🤔

**Comment by wonfen** [comment]
看样子是系统出故障了，修复一下windows

**Comment by Shanwer** [comment]
> 看样子是系统出故障了，修复一下windows
谢谢，我明天用sfc scan试一下

**Comment by Shanwer** [comment]
> 看样子是系统出故障了，修复一下windows

跑了一遍，开启了之后在网络适配器中还是没有虚拟网卡，不知道是不是和zerotier或者虚拟机啥的冲突了

**Comment by Shanwer** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/16631550/d73028e6-743a-49f9-9e3e-2166830b7edd)
观察到存在大量连接，CPU占用很高，但无法墙内外都无法连接网络，参考了这两个issue切换到alpha内核也不行
#https://github.com/MetaCubeX/mihomo/issues/1178
#947

**Comment by Shanwer** [comment]
看了下#1037 ，我去翻了下设备管理器，有一条错误消息我在虚拟机上看不到
