### ISSUE TITLE
github无法代理[bug] 

### ISSUE THREAD

**Issue by LazyCat2333** [clash-verge-rev/clash-verge-rev#1025]
### 问题描述 / Describe the bug

使用系统代理链接后，其他的网站都能代理，唯独github报错，无法连接，我换了其他节点也是这样。

### 复现步骤 / To Reproduce

直接连接就会这样

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11

### 日志 / Log

![IMG_20240516_105233_150](https://github.com/clash-verge-rev/clash-verge-rev/assets/91608930/ea907315-5de6-4395-be6e-d72014f84004)
![IMG_20240516_105234_833](https://github.com/clash-verge-rev/clash-verge-rev/assets/91608930/66528c44-eb94-43df-82f7-1fb4a13db9d9)
![IMG_20240516_105236_888](https://github.com/clash-verge-rev/clash-verge-rev/assets/91608930/c6507006-f306-45bd-a9ac-32ced0773abe)

**Comment by rebecca554owen** [comment]
@LazyCat2333 这是选择全局的吗？
看起来不是走规则。

**Comment by MystiPanda** [comment]
@LazyCat2333 https://clash-verge-rev.github.io/faq/other.html#watt-toolkit-steam

**Comment by LazyCat2333** [comment]
是系统host的问题，已经解决了
