### ISSUE TITLE
clash在第三方终端中没有自动设置https_proxy环境变量

### ISSUE THREAD

**Issue by lamb007** [clash-verge-rev/clash-verge-rev#1027]
### 问题描述 / Describe the bug

开启系统代理后，在系统自带终端中使用wget等工具发起的http请求会通过代理，在使用第三方终端后，如wezterm、alacritty，均未通过代理，打印https_proxy变量，只有自带终端中有输出
![Snipaste_2024-05-15_14-43-43](https://github.com/clash-verge-rev/clash-verge-rev/assets/98157643/a5d3e32b-1fa8-45cc-9ec7-f6a27ca10667)
在第三方终端中手动export https_proxy后才可以使用代理
在浏览器等应用可以正常使用代理

### 复现步骤 / To Reproduce

使用wezterm等第三方终端

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

pop!_os22.04(基于ubuntu)

### 日志 / Log

[2024-05-17-1148.log](https://github.com/clash-verge-rev/clash-verge-rev/files/15343656/2024-05-17-1148.log)

**Comment by wonfen** [comment]
这个你需要研究下第三方终端的代理设置是否遵循这种环境变量配置。
