### ISSUE TITLE
[BUG] 规则 DOMAIN-SUFFIX 无效

### ISSUE THREAD

**Issue by tnnevol** [clash-verge-rev/clash-verge-rev#103]
客户端版本 Clash.Verge_1.4.3_aarch64.dmg

<img width="592" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/28475939/52b79e13-cbf7-4e39-9cf9-32ed56a2a5c1">
<img width="1231" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/28475939/21f54544-2bc4-4ed9-bbb2-e1d0a542c05d">
<img width="1211" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/28475939/0020f9bd-e176-46e2-9711-30ece033b99e">
在 clashX 中可以识别

**Comment by Hayxi** [comment]
域名触发了 DNS 解析命中 `GEOIP,CN`

将此 `DOMAIN-SUFFIX` 规则移至之上

**Comment by wonfen** [comment]
2楼解答了，请检查clash配置。
