### ISSUE TITLE
[Feature] 希望在侧边栏加上一个全局的“系统代理”开关

### ISSUE THREAD

**Issue by shadowmelds** [clash-verge-rev/clash-verge-rev#1032]
### 功能描述 / Feature description

希望在侧边栏加上一个全局的“系统代理”开关

### 使用场景 / Use case

自认为开关系统代理是 Clash 最常用的功能之一，一般日常操作 Clash 最常用的就是切换节点和开关系统代理这两个操作。但是这个操作还不够便捷。

**Comment by shadowmelds** [comment]
> 不，你需要改一下自己的使用习惯。
> 
> 用分流规则模式无须反复开关系统代理，随系统启动，保持打开。可以做到无缝国内外浏览。

有些应用程序比如暴雪战网，打开之前必须要关闭代理，否则就是无法连接至战网。虽然这种我一般也是托盘图标右键关闭代理了。但是我觉得Clash主界面有个开关还是比较方便的。

**Comment by Ten-Shine** [comment]
如果在侧边栏加上一个全局的“系统代理”开关，那么开关代理依然要打开软件主页面，我感觉右键托盘图标已经很方便了。

侧边栏是用来切换页面的吧，如果添加一个按钮会显得很怪。
并且有的人不是使用`系统代理`而是使用`TUN模式`，那么侧边栏的系统代理会显得肿瘤。

为何不设置一个热键来开关系统代理呢？
