### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jarkeet** [clash-verge-rev/clash-verge-rev#1033]
### 问题描述 / Describe the bug

1、开始clash verge
2、更新配置文件后，所有节点报Timeout
日志中提示 error: dns resolve failed: couldn't find ip

crash verge版本： v1.6.2

### 复现步骤 / To Reproduce

<img width="947" alt="71339146BA7B722BC4ABEF6211DA3B80" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/5320996/dead1c57-141e-4336-83ac-347a229efcde">

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

10.15.7 catallina

### 日志 / Log

05-18 23:13:30WARNING
[TCP] dial 祢豆子 (match DomainKeyword/google) 127.0.0.1:50327 --> www.google.com:443 error: couldn't find ip
05-18 23:13:36WARNING
[TCP] dial 祢豆子 (match DomainKeyword/github) 127.0.0.1:50339 --> www.github.com:443 error: couldn't find ip
05-18 23:13:36WARNING
[TCP] dial 祢豆子 (match Match/) 127.0.0.1:50328 --> mirror.ghproxy.com:443 error: lookup invalid IP: no such host
05-18 23:13:39INFO
[TCP] 127.0.0.1:50368 --> www.apple.com:443 match DomainSuffix(apple.com) using DIRECT
05-18 23:13:40WARNING
[TCP] dial 祢豆子 (match Match/) 127.0.0.1:50328 --> mirror.ghproxy.com:443 error: couldn't find ip
05-18 23:13:41WARNING
[TCP] dial 祢豆子 (match DomainKeyword/google) 127.0.0.1:50366 --> www.google.com:443 error: couldn't find ip
05-18 23:13:41WARNING
[TCP] dial 祢豆子 (match Domain/ocsp.apple.com) 127.0.0.1:50367 --> ocsp.apple.com:80 error: couldn't find ip
05-18 23:13:45WARNING
[TCP] dial 祢豆子 (match Domain/ocsp.apple.com) 127.0.0.1:50374 --> ocsp.apple.com:80 error: couldn't find ip

**Comment by dongchengjie** [comment]
找机场，DNS配置也能下发错？

**Comment by jarkeet** [comment]
> 找机场，DNS配置也能下发错？

咋解决呢，dns换了好几个，还是不行。这是机场的问题，不是crash软件问题是吗？

**Comment by jarkeet** [comment]
> 找机场，DNS配置也能下发错？

咋解决呢，dns换了好几个，还是不行。这是机场的问题，不是crash软件问题是吗？
