### ISSUE TITLE
[Feature] 请求添加打开局域网连接的时候询问是否通过防火墙

### ISSUE THREAD

**Issue by ngo5** [clash-verge-rev/clash-verge-rev#1034]
### 功能描述 / Feature description

clash verge打开局域网连接不会询问是否通过防火墙，设置手机Wi-Fi后没有互联网访问，需要手动到Windows设置把内核通过防火墙才行。

能不能像clash nyanpasu打开局域网连接的时候提示询问会是否通过防火墙。
![屏幕截图 2024-05-19 022638](https://github.com/clash-verge-rev/clash-verge-rev/assets/111275866/07741b4d-68bd-4309-9759-b30e19693813)

### 使用场景 / Use case

如题

**Comment by wonfen** [comment]
这个是windows自己的提示，和软件无关。
