### ISSUE TITLE
[Feature] 在规则中直接添加新规则

### ISSUE THREAD

**Issue by alan42521** [clash-verge-rev/clash-verge-rev#1036]
### 功能描述 / Feature description

在cfw中，有图形化的界面可以直接添加规则，而clash verge只能通过修改配置文件来添加，希望clash verge也能通过图形界面快捷添加规则
![捕获](https://github.com/clash-verge-rev/clash-verge-rev/assets/108172351/14cab065-7a1f-4011-a3d0-e19f76f1036a)

### 使用场景 / Use case

在需要给一些网站专门配置规则时

**Comment by Xuu6770** [comment]
不仅如此，添加完以后还不会立刻生效，还要在`订阅`界面点击`重新激活订阅`，就有点麻烦。

事实上我更希望能添加一个“本地规则优先”的功能，就比如我在本地添加一个`microsoft.com`走代理的规则，无论机场本身的规则对`microsoft.com`如何处理，Clash 都应该以我本地的规则优先。

谢谢。

**Comment by mtvktvcn** [comment]
附议~~~

**Comment by lipanzjzs** [comment]
> 不仅如此，添加完以后还不会立刻生效，还要在`订阅`界面点击`重新激活订阅`，就有点麻烦。
> 
> 事实上我更希望能添加一个“本地规则优先”的功能，就比如我在本地添加一个`microsoft.com`走代理的规则，无论机场本身的规则对`microsoft.com`如何处理，Clash 都应该以我本地的规则优先。
> 
> 谢谢。

这个功能在clash里就没好好实现过，各种类产品都超级麻烦

**Comment by bububuhe** [comment]
macOS 系统
直接修改规则，更新订阅文件时，修改内容会被覆盖，有解决办法吗？

**Comment by Xuu6770** [comment]
> > 不仅如此，添加完以后还不会立刻生效，还要在`订阅`界面点击`重新激活订阅`，就有点麻烦。
> > 事实上我更希望能添加一个“本地规则优先”的功能，就比如我在本地添加一个`microsoft.com`走代理的规则，无论机场本身的规则对`microsoft.com`如何处理，Clash 都应该以我本地的规则优先。
> > 谢谢。
> 
> 这个功能在clash里就没好好实现过，各种类产品都超级麻烦

不好实现是不是因为每条规则都要指定一个`proxy-groups`，但是每家机场的配置文件中的`proxy-groups`的`name`又不一样？

↑ 我不确定，只是我自己真么想的。

我在 iOS 上使用 Quantumult X 的时候就可以添加自定义规则并且决定其是否要走代理， Quantumult X 对于每条自定规则都提供 3 个策略：

1. PROXY
2. DIRECT
3. REJECT

例如我想让`bing.com`走代理的话，我就将这条规则的策略设定成`PROXY`就行了，无论我使用哪家机场， Quantumult X 都会`bing.com`走代理，但是我也不知道它是怎么实现这个功能的。😢

**Comment by Xuu6770** [comment]
> macOS 系统 直接修改规则，更新订阅文件时，修改内容会被覆盖，有解决办法吗？

Windows 也一样的，你修改的是机场提供的配置文件，修改后只在本地生效，你一更新订阅，程序又从云端获取最新的配置文件，故而覆盖了。

这个功能只能说机场有心的话就会自己提供，我之前用过一个机场就是可以在网站里自定义规则。

**Comment by bububuhe** [comment]
https://github.com/yanue/V2rayU.git 
我现在在用这个，这个可以添加 pac 规则而不会覆盖。

**Comment by feige888** [comment]
> macOS 系统 直接修​​改规则，更新订阅文件时，修改内容会被覆盖，有解决办法吗？
订阅-新建一个merge-然后在prepend-rules: [] 下面复制你刚才写的规则进去-保存-右键启用    这样更新订阅后规则也还在了

**Comment by feige888** [comment]
> macOS 系统 直接修​​改规则，更新订阅文件时，修改内容会被覆盖，有解决办法吗？

订阅-右上角新建一个merge-然后在prepend-rules: []下面复制你刚才写的规则进去-保存-右键启用这样更新订阅后规则也还好

**Comment by caibirda** [comment]
> 不仅如此，添加完以后还不会立刻生效，还要在`订阅`界面点击`重新激活订阅`，就有点麻烦。
> 
> 事实上我更希望能添加一个“本地规则优先”的功能，就比如我在本地添加一个`microsoft.com`走代理的规则，无论机场本身的规则对`microsoft.com`如何处理，Clash 都应该以我本地的规则优先。
> 
> 谢谢。

参考'feige888'的方法，亲测有用

**Comment by feige888** [comment]
> > macOS 系统 直接修改规则，更新订阅文件时，修改内容会被覆盖，有解决办法吗？
> 
> Windows 也一样，你修改的是机场提供的配置文件，修改后只在本地生效，你一更新订阅，程序又从云端获取最新的配置文件，故而覆盖了。
> 
> 这个功能只能说机场有心的话就会自己提供，在我使用一个机场之前就可以在网站里自定义规则。

点订阅-右上角新建一个merge-然后复制下面代码过去

# Merge Template for clash verge
# The `Merge` format used to enhance profile

prepend-rules:
- DOMAIN,www.baidu.com,DIRECT
- DOMAIN,www.hao123.com,DIRECT
prepend-proxies:

prepend-proxy-groups:

append-rules:

append-proxies:

append-proxy-groups:
里面的网站自己换成你不想走代理的网址就行了
保存-右键启用 -右上角激活订阅 这样更新订阅后规则也还在了
![微信截图_20240705125513](https://github.com/clash-verge-rev/clash-verge-rev/assets/92505897/50bd2abd-d4f9-483c-bda0-51bc7f3f299b)
