### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by visiLi** [clash-verge-rev/clash-verge-rev#1038]
### 功能描述 / Feature description

**新版托盘图标，建议去掉背景色。使用纯色。**
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/42717403/621361c5-30e8-4ba8-a2a9-952e3bdad34d)

### 使用场景 / Use case

托盘。

**Comment by MystiPanda** [comment]
Mac 版本在界面设置中可以切换单色/彩色图标，其他系统单色托盘图标区别不明显，如果需要，在 tg 频道提供了单色图标可以自行下载替换。

**Comment by visiLi** [comment]
嗯。我已经加入TG频道，那在哪里获取链接呢
