### ISSUE TITLE
[BUG] v1.6.2 和 1.6.2 alpha 版本 windows 7 下启动报错 0xc0000005 应用程序错误

### ISSUE THREAD

**Issue by szkzn** [clash-verge-rev/clash-verge-rev#1041]
### 问题描述 / Describe the bug

从 1.6.0 x64 便携版 更新到 1.6.2 和 1.6.2 alpha 版本，启动程序直接报错
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/30108874/60f95629-5ca4-4aea-a6eb-369171ba7487)

使用了 go v1.20 编译的  v1.8.5 clash-meta 内核、v1.8.3 clash-meta 内核 启动仍然报错

windows 事件查看器显示
弹出应用程序: Clash Verge.exe - 应用程序错误: 应用程序无法正常启动(0xc0000005)。请单击“确定”关闭应用程序。 

### 复现步骤 / To Reproduce

环境: 
下载 v1.6.2 便携版或者 v1.6.2 alpha 便携版
clash core: go120-v1.8.3/go120-v1.8.5（手动替换自带的核心）
自行安装好 edgewebview2 v109（win7 支持的最后一个版本）
双击启动 Clash Verge.exe，随后报错

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 7 x64 专业版 sp1

### 日志 / Log

clash verge 在启动阶段就抛出异常，自身未记录到任何日志
检查 %userprofile%\.config\clash-verge\logs 路径，未产生任何日志文件
windows 事件查看器相关信息
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/30108874/9b0654ee-ff2e-4bb8-b597-c1eec01225b8)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/30108874/af87a14c-6cf5-48ef-893b-50dc77f2b6d6)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/30108874/e9f0c149-ef30-49d4-85c0-81c41630119e)

**Comment by Dystnine** [comment]
1.6.1就有这个问题了，可不止1.6.2

**Comment by minusmulticoloredper** [comment]
问题在Rust身上，Rust把对Windows7的支持单独做成了一个Target，但是目前rust的维护者没有测试过它，且这个Target无法直接添加。
https://doc.rust-lang.org/beta/rustc/platform-support/win7-windows-msvc.html

**Comment by minusmulticoloredper** [comment]
问题在Rust身上，在1.77.2版本之后放弃了对Windows7的主要支持并把它单独做成了一个Target，但是目前rust的维护者没有测试过它，且这个Target无法直接添加。
https://doc.rust-lang.org/beta/rustc/platform-support/win7-windows-msvc.html

**Comment by minusmulticoloredper** [comment]
问题在Rust身上，在1.77.2版本之后放弃了对Windows7的主要支持并把它单独做成了一个Target，但是目前Rust的维护者没有测试过它，且这个Target无法直接添加。
https://doc.rust-lang.org/beta/rustc/platform-support/win7-windows-msvc.html

**Comment by minusmulticoloredper** [comment]
> 尴尬了？打字时才发现，这个项目删库了!! 很遗憾经过检查，不只是删库，而是开发者的 GitHub 账户也删除了，paypal 的赞助收款链接也失效了，太可惜了

互联网档案馆中有相关的页面存档，可以在互联网档案馆中下载。
https://web.archive.org/web/20240721010304/https://github.com/vxiiduu/VxKex

github中也有类似的项目，我不确定他是继续开发的项目还是仅存档的项目。
https://github.com/i486/VxKex

**Comment by minusmulticoloredper** [comment]
> 尴尬了？打字时才发现，这个项目删库了!! 很遗憾经过检查，不只是删库，而是开发者的 GitHub 账户也删除了，paypal 的赞助收款链接也失效了，太可惜了

互联网档案馆中有相关的页面存档，可以在互联网档案馆中下载。
https://web.archive.org/web/20240721010304/https://github.com/vxiiduu/VxKex

github中也有类似的项目，我不确定它是继续开发的项目还是仅存档的项目。
https://github.com/i486/VxKex
