### ISSUE TITLE
[BUG] 1.6.2版本Win10下彻底无法启动，显示“拒绝访问”，随后闪退

### ISSUE THREAD

**Issue by user-pc3kvn1850** [clash-verge-rev/clash-verge-rev#1049]
### 问题描述 / Describe the bug

之前一直可以正常使用，最近安装了一个cfosspeed，这个软件安装过程中好像会安装webview2，装完后最近clash verge变得无法启动，一启动就弹出这个报错画面，然后就闪退了，系统托盘里无clash verge图标。现在无论exe安装版还是便携版，都彻底无法使用clash verge rev了，求帮助。已卸载clash verge多次，重新安装也无法解决。

![clash crash](https://github.com/clash-verge-rev/clash-verge-rev/assets/1773534/c0596bdf-4eba-433b-a8a3-a9d66b7f135e)

![clash01](https://github.com/clash-verge-rev/clash-verge-rev/assets/1773534/25a0da8a-4da6-43e7-91ca-6e9e3a3da0bf)

![clash02](https://github.com/clash-verge-rev/clash-verge-rev/assets/1773534/944dd80e-3cc1-45d8-83e4-4178e2c2c895)

### 复现步骤 / To Reproduce

双击启动 Clash Verge.exe，随后报错

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10 v1809 x64

### 日志 / Log

无法启动，无法导出日志

**Comment by snakem982** [comment]
换个不在C盘的安装目录，右键以管理员身份运行试试

**Comment by user-pc3kvn1850** [comment]
卸载掉又重新下载exe安装包重新安装了下，发现我之前下错安装包了，把arm64看成amd版本了，之前错装成了这个“Clash.Verge_1.6.2_arm64-setup.exe”，现在重新下载”Clash.Verge_1.6.2_x64-setup.exe“安装完后，无问题了，可以正常启动clash verge了，并且正常运行。
