### ISSUE TITLE
Macos telegram 客户端无法链接

### ISSUE THREAD

**Issue by wa008** [clash-verge-rev/clash-verge-rev#1050]
### 问题描述 / Describe the bug

使用 Clash X Pro 打开增强模式之后，可以链接telegram，但 clash-verge-rev 中没有增强模型的选项

### 复现步骤 / To Reproduce

Macos 默认无法连接 telegram

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

13.3.1 (22E261)

### 日志 / Log

telegram 客户端显示一直 Connecting

**Comment by Ethan0x0000** [comment]
尝试把telegram的IP段加到规则里

**Comment by wa008** [comment]
> 尝试把telegram的IP段加到规则里

这治标不治本吧
我也装了其他版本的 Clash 可以先用着

clash-verge-rev 存在类似于其他版本"增强模式"的功能吗

**Comment by xishang0128** [comment]
@wa008 增强模式=tun

**Comment by wa008** [comment]
> @wa008 增强模式=tun

tun模式依赖服务模式，服务模式打开时提示 "“io.github.clashverge.helper” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information."
有什么东西需要更新了

**Comment by xishang0128** [comment]
@wa008 内核管理,授权内核,可以不用服务模式

**Comment by wa008** [comment]
> > @wa008 增强模式=tun
> 
> tun模式依赖服务模式，服务模式打开时提示 "“io.github.clashverge.helper” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information." 有什么东西需要更新了

@xishang0128  在设置里面打开一下这个文件就可以了，我打开了服务模式，问题解决了，谢谢。

主要不知道怎么授权内核，没有傻瓜式的教程，哈哈哈

**Comment by wa008** [comment]
> @wa008 内核管理,授权内核,可以不用服务模式

服务模式只能解决一次，重启就失效了，需要重新操作。

你说的授权内核是指授予Mac全部的磁盘访问权限吗？

**Comment by xishang0128** [comment]
> > @wa008 内核管理,授权内核,可以不用服务模式
> 
> 服务模式只能解决一次，重启就失效了，需要重新操作。
> 
> 你说的授权内核是指授予Mac全部的磁盘访问权限吗？

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/95160953/37c7cc89-260c-4e6c-a098-2c6186bb56f5)

**Comment by LouisYaaaaa** [comment]
在telegram中设置一下本机代理(Proxy)就可以了：
socket5
127.0.0.1
端口看一下自己的clash

**Comment by YIMOzzc** [comment]
我设置了 telegram的代理  但是T的代理一直显示连接中 其他应用和网页是正常的。
