### ISSUE TITLE
[Feature] 可以加一个更新本地配置文件的功能吗

### ISSUE THREAD

**Issue by shykt235** [clash-verge-rev/clash-verge-rev#1052]
### 功能描述 / Feature description

给本地配置文件加入关联能供，如果导入的配置文件发生更改可以跟随变化

### 使用场景 / Use case

场景是使用脚本来整合订阅，然后输出了配置文件，直接本地导入来使用。所以定时执行以下更新订阅并整合的操作，而clash似乎是直接把原本配置文件拷一份配置文件这样，这样的话每次更新后都得删掉原本的，再重新导入一份，可以设置个关联之类的吗？？

**Comment by dongchengjie** [comment]
你不知道输出覆盖profiles中的本地配置文件吗？更新间隔是干嘛使的？可以对本地配置文件生效重新读取
