### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Cosmosgit42** [clash-verge-rev/clash-verge-rev#1058]
### 问题描述 / Describe the bug

打开软件之后，在菜单栏出现两个图标，其中一个白色的覆盖在最左侧的mac图标上，点击后在右侧的黑色图标上呼出菜单，重装也取消不了

### 复现步骤 / To Reproduce

打开clash就会出现两个图标

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS sonoma 14.1.1

### 日志 / Log

none

**Comment by Cosmosgit42** [comment]
刚发现左上角覆盖在🍎上的白色图标不是固定在菜单栏上的，就只是出现在左上角，每次打开程序就会出现，是我电脑问题还是软件的问题？求解答

**Comment by Cosmosgit42** [comment]
![Uploading IMG_5674.jpeg…]()

**Comment by passwhl** [comment]
![Uploading QQ_1732513944241.png…]()
一样的
