### ISSUE TITLE
[BUG] 左上角出现白色猫图标

### ISSUE THREAD

**Issue by Cosmosgit42** [clash-verge-rev/clash-verge-rev#1059]
### 问题描述 / Describe the bug

打开软件，除了正常出现的黑色图标外，左上角还会出现白色图标，点击白色图标会在黑色图标处呼出选项。卸载重装或者升级系统都没用
![Uploading IMG_5674.jpeg…]()

### 复现步骤 / To Reproduce

打开软件就会出现

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS sonoma14.5

### 日志 / Log

none

**Comment by test4uninstall** [comment]
打开软件之后出现原神图标？怎么办啊？
