### ISSUE TITLE
后续会考虑出安卓版吗？

### ISSUE THREAD

**Issue by flight025** [clash-verge-rev/clash-verge-rev#1064]
### 功能描述 / Feature description

我很喜欢你们改进的clash verge,几乎只要转换下，就能支持任何协议，请问吧考虑过出安卓版吗？

### 使用场景 / Use case

主要是推出安卓版，我必定支持。

**Comment by lbcake** [comment]
不会推出 app版本    请自己关闭issues。

**Comment by flight025** [comment]
额

**Comment by test4uninstall** [comment]
请使用ClashMetaForAndroid
https://github.com/MetaCubeX/ClashMetaForAndroid

**Comment by dq77** [comment]
> 请使用ClashMetaForAndroid https://github.com/MetaCubeX/ClashMetaForAndroid

这个CMFA真不咋地

**Comment by Ahaohaohao** [comment]
@Jimes3518 0元购 🙃
