### ISSUE TITLE
[BUG] Wireguard协议无法访问Google、Youtube等，提示连接失败/证书错误（变成Facebook证书了）

### ISSUE THREAD

**Issue by JedSunCN** [clash-verge-rev/clash-verge-rev#1066]
### 问题描述 / Describe the bug

RT，使用clash-v添加wireguard协议，使用浏览器switchyomega将流量转发至clash-v端口，访问Google、Youtube等会出现连接失败/证书错误的情况，但是访问GitHub等又正常。老版clashforwindows没有这个问题。

### 复现步骤 / To Reproduce

添加wireguard协议，使用浏览器switchyomega将流量转发至clash-v端口，访问访问Google、Youtube等。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 23H2

### 日志 / Log

05-26 10:41:22INFO
Initial configuration complete, total time: 9ms
05-26 10:41:22INFO
RESTful API listening at: 127.0.0.1:9097
05-26 10:41:22INFO
Sniffer is closed
05-26 10:41:22INFO
HTTP proxy listening at: 127.0.0.1:18967
05-26 10:41:22INFO
SOCKS proxy listening at: 127.0.0.1:18966
05-26 10:41:22INFO
Mixed(http+socks) proxy listening at: 127.0.0.1:18965
05-26 10:41:22INFO
Start initial Compatible provider 节点选择
05-26 10:41:22INFO
Start initial Compatible provider default
05-26 10:41:22INFO
Start initial Compatible provider 直连
05-26 11:31:54INFO
[TCP] 127.0.0.1:9014 --> www.google.com:443 using GLOBAL
05-26 11:32:14INFO
[TCP] 127.0.0.1:9017 --> www.github.com:443 using GLOBAL
05-26 11:32:15INFO
[TCP] 127.0.0.1:9018 --> github.com:443 using GLOBAL
05-26 11:32:17INFO
[TCP] 127.0.0.1:9019 --> avatars.githubusercontent.com:443 using GLOBAL

**Comment by xishang0128** [comment]
wg工作在三层,域名会在本地解析,请确保wg以及dns配置正确
这是错误配置导致的,而不是bug
