### ISSUE TITLE
[Feature] Provide adjustment options for old version icons under windows

### ISSUE THREAD

**Issue by Parsifa1** [clash-verge-rev/clash-verge-rev#1067]
### 功能描述 / Feature description

As title
The old version of the icon will look more harmonious in the tray
The function of customizing the tray icon cannot achieve good results
Hopefully the ability to use legacy tray icons will be provided
It’s okay if you dont want so (just a tiny request

### 使用场景 / Use case

in tray

**Comment by dongchengjie** [comment]
Find old icons from the commit history  and customize them: `Settings` -> `Layout Settings`.
Choose any icons you prefer and change them according to your preferences.
