### ISSUE TITLE
连接选项卡里可以添加一个上传、下载流量总量的统计吗？

### ISSUE THREAD

**Issue by xsycyan** [clash-verge-rev/clash-verge-rev#107]
现在连接选项卡里只有每一条的流量，可不可以添加一个总的使用流量统计的功能，类似于这样的
![微信截图_20231208221247](https://github.com/clash-verge-rev/clash-verge-rev/assets/31643583/756d263c-4c5b-437c-a550-ab560c1b50e5)

**Comment by wonfen** [comment]
无计划，可以在明细里查看。
