### ISSUE TITLE
[BUG] Windows 11 24H2 无法正常使用Verge

### ISSUE THREAD

**Issue by Ne0W0r1d** [clash-verge-rev/clash-verge-rev#1070]
### 问题描述 / Describe the bug

如题所示，订阅正常，代理页、连接页、规则页、日志页均为空白，由于已经撤回23H2，暂时无法提交截图

### 复现步骤 / To Reproduce

直接升级Windows 11 24H2，然后打开Clash Verge

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26100.560

### 日志 / Log

[2024-05-26-2122.log](https://github.com/clash-verge-rev/clash-verge-rev/files/15447700/2024-05-26-2122.log)

**Comment by MystiPanda** [comment]
#1068

**Comment by Ne0W0r1d** [comment]
Nope，我目前就是1.6.4版本，不显示任何的节点
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/93416867/1f82db3b-5d6b-4ee6-9efe-7b52287d96b8)

**Comment by Ne0W0r1d** [comment]
> #1068
Nope。目前我就是1.6.4版本
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/93416867/682a7e47-1d07-4ba4-bc1f-d64a1301cdf7)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/93416867/c17a6f2e-8a89-4122-b113-119296b0438b)
[2024-05-26-2306.log](https://github.com/clash-verge-rev/clash-verge-rev/files/15448080/2024-05-26-2306.log)

**Comment by xiaorong61** [comment]
我遇到类似问题，升级到 24h2 后，nekobox windows 无法使用，关闭 win bbr2 后成功了。
你或许可以试试。

**Comment by kanao7** [comment]
> 我遇到类似问题，升级到 24h2 后，nekobox windows 无法使用，关闭 win bbr2 后成功了。 你或许可以试试。

我去，真是这个原因导致的，亏我还重装系统😱

**Comment by wiilon** [comment]
> 我遇到类似问题，升级到 24h2 后，nekobox windows 无法使用，关闭 win bbr2 后成功了。 你或许可以试试。

搞定了 还真是这个问题

**Comment by Huozhe-Siqu** [comment]
> bbr2 后成功了。 你或许可以试试

确实可用

**Comment by llc-robin** [comment]
我去，确实是这个问题。BBR2的问题。用什么软件都是这个问题。clash for windows verge都存在这个问题

**Comment by wonfen** [comment]
> 我去，确实是这个问题。BBR2的问题。用什么软件都是这个问题。clash for windows verge都存在这个问题

用最新2.0 rc6，已经解决了这个问题。
