### ISSUE TITLE
[BUG] Merge Template for Clash Verge 功能失效 

### ISSUE THREAD

**Issue by wzgrx** [clash-verge-rev/clash-verge-rev#1071]
### 问题描述 / Describe the bug

1.merge规则写了www.1000qm.vip直链，启用merge还是走代理

### 复现步骤 / To Reproduce

1.merge规则写了www.1000qm.vip直链，启用merge还是走代理
prepend-rules: []

DOMAIN,www.1000qm.vip,全局直连
DOMAIN,www.1000qm.vip:80,全局直连
prepend-proxies: []
prepend-proxy-groups: []

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

05-20 23:02:16INFO
[TCP] 127.0.0.1:5249 --> [www.1000qm.vip:80](http://www.1000qm.vip/) match Match using 🇺🇸

**Comment by dongchengjie** [comment]
文档叫你看语法文档你看了吗

**Comment by wzgrx** [comment]
> 文档叫你看语法文档你看了吗

看了，按照语法写的，还是没有用

**Comment by dongchengjie** [comment]
你看了个锤子
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/99244bda-c32b-4f45-9136-7fb9aa023501)

**Comment by wzgrx** [comment]
- DOMAIN-SUFFIX,usserver.serverapi.org,DIRECT
 空格-DOMAIN-SUFFIX,usserver.serverapi.org,DIRECT
不就这样，还怎么写？

> 你看了个锤子 ![image](https://private-user-images.githubusercontent.com/37543964/333886481-99244bda-c32b-4f45-9136-7fb9aa023501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzQwMjksIm5iZiI6MTcxNjczMzcyOSwicGF0aCI6Ii8zNzU0Mzk2NC8zMzM4ODY0ODEtOTkyNDRiZGEtYzMyYi00ZjQ1LTkxMzYtN2ZiOWFhMDIzNTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE0Mjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZDQ4N2E5MjdjZmFkMmJhZWUxNTBkMDc1OGFiNWQ1NzAwODRhMzNhYzU5MmI0MDY3M2FmNjYxNmZkMDU4NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q5_hD2XV_Fn50hjCtbVamKypafIChORTbohx5h6mICY)

  - DOMAIN-SUFFIX,usserver.serverapi.org,DIRECT
 空格-DOMAIN-SUFFIX,usserver.serverapi.org,DIRECT
不就这样，还怎么写？

**Comment by dongchengjie** [comment]
你这样写编辑器难道不是红色的吗？ 这么明显的中括号
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/69d0cb88-7ff6-4da7-a3d8-9f21ac8f47c5)

**Comment by wzgrx** [comment]
> 你这样写编辑器难道不是红色的吗？ 这么明显的中括号 ![image](https://private-user-images.githubusercontent.com/37543964/333886858-69d0cb88-7ff6-4da7-a3d8-9f21ac8f47c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzQyNjAsIm5iZiI6MTcxNjczMzk2MCwicGF0aCI6Ii8zNzU0Mzk2NC8zMzM4ODY4NTgtNjlkMGNiODgtN2ZmNi00ZGE3LWEzZDgtOWYyMWFjOGY0N2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE0MzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNTg4ZDliNDdjZWExY2ZmZDRkN2NiOTExNDk1MmE3MGQ0ZjRlM2MwZjEzYzQ3NDQ4NzIwM2I2ODc3ODYzOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t_FrSeqCCQKyTpap0XDTYYAKgVm2CpFK4Q1401yjrkQ)

![Snipaste_2024-05-26_22-33-55](https://github.com/clash-verge-rev/clash-verge-rev/assets/39661556/e2582283-9aaf-42fd-bece-b1e1438b60ef)

-空格DOMAIN-SUFFIX,usserver.serverapi.org,DIRECT
这样？

**Comment by wzgrx** [comment]
`prepend-rules:
  - DOMAIN-SUFFIX,baidu.com,🇯🇵6日本-东部优化(hy2)
  - DOMAIN-SUFFIX,google.com,🇰🇷9韩国-全网优化(hy2)
  - DOMAIN-SUFFIX,youtube.com,♻️自动选择
  - IP-CIDR,10.11.12.0/24,DIRECT,no-resolve

prepend-proxies: []

prepend-proxy-groups: []

append-rules: []

append-proxies: []

append-proxy-groups: []`

完全按照文档复制粘贴的，还是没有用啊
