### ISSUE TITLE
[BUG] 反馈一个bug，classical规则不能识别数量

### ISSUE THREAD

**Issue by Troray** [clash-verge-rev/clash-verge-rev#1072]
### 问题描述 / Describe the bug

win11，v1.6.2
嗯，标题表达好像不是很清楚，看下面的截图和规则文件的后缀名。
刚才重新修正规则集时，发现list类型的文件，在软件中不显示条目数量，而yaml文件则能正常显示，但是两种文件类型都是能正常下载到本地的。
![Snipaste_2024-05-27_01-01-20](https://github.com/clash-verge-rev/clash-verge-rev/assets/16841721/af4cc74c-7049-464f-aa63-55f8fdad04f1)
![Snipaste_2024-05-27_01-03-21](https://github.com/clash-verge-rev/clash-verge-rev/assets/16841721/436b6cf9-7212-4d03-9de2-a2a4e0e3765e)

```
...

# 奈飞影视
 netflix-domain: {<<: *d, path: ./ruleset/netflix-domain.list, url: https://ghproxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.list}
 
 netflix-ip: {<<: *i, path: ./ruleset/netflix-ip.list, url: https://ghproxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.list}

# 迪士尼+
 disney-domain: {<<: *d, path: ./ruleset/disney-domain.yaml, url: https://ghproxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/disney.yaml}

# Emby
 emby-classical: {<<: *c, path: ./ruleset/emby-classical.yaml, url: https://ghproxy.com/https://raw.githubusercontent.com/Repcz/Tool/X/Stash/Rules/Emby.yaml}

...
```

### 复现步骤 / To Reproduce

由于每个人配置文件不同，无法提供统一的复现步骤。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

-

**Comment by Troray** [comment]
更新到v1.6.4，问题依旧。

**Comment by xishang0128** [comment]
https://wiki.metacubex.one/config/rule-providers/content/
