### ISSUE TITLE
[Feature] 代理界面的当前节点、延迟测速这一行，希望滚动的时候能fixed

### ISSUE THREAD

**Issue by zhaoaaaaa5** [clash-verge-rev/clash-verge-rev#1074]
### 功能描述 / Feature description

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/17667815/9a77dd7e-b2de-40e2-a6f6-3ce1c007dc84)
第二排滚动时增加一个fixed功能

### 使用场景 / Use case

如果窗口较小，节点比较多的话，第二排滚动后就隐藏不见，此时想要定位到自己所选节点需要滚动到顶部，点击当前节点才能定位到。操作很是不方便。

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/792
