### ISSUE TITLE
[Feature]托盘右键直接显示代理组可选节点

### ISSUE THREAD

**Issue by LeEssSay** [clash-verge-rev/clash-verge-rev#1076]
### 功能描述 / Feature description

像clashwindows一样，托盘右键直接显示代理组可选节点。比较方便切换节点。

### 使用场景 / Use case

当前节点挂了的时候比较方便直接切换，不用打开客户端。

**Comment by Brian2Z** [comment]
还可以更进一步：参考surge for mac，代理组的节点列表最上是“测速”，按下测速后，在每个节点上显示测速结果

**Comment by MystiPanda** [comment]
不做
