### ISSUE TITLE
[Feature] 能否支持以配置系统的hosts文件中的地址，DIRECT

### ISSUE THREAD

**Issue by zapjone** [clash-verge-rev/clash-verge-rev#1078]
### 功能描述 / Feature description

指定hosts文件进行规则过滤

### 使用场景 / Use case

指定/etc/hosts文件，配置为不经过代理。这样后续在hosts文件中增加的ip项都不会经过了。

**Comment by dongchengjie** [comment]
[use-system-hosts](https://wiki.metacubex.one/config/dns/#use-system-hosts)

https://clash-verge-rev.github.io/faq/other.html#watt-toolkit-steam-steamcommunity-302
