### ISSUE TITLE
[BUG] Connections界面中的按时间排序功能无效

### ISSUE THREAD

**Issue by ForestL18** [clash-verge-rev/clash-verge-rev#108]
### Describe the bug

在Connections界面中的按时间排序功能有问题，无论是按ASC还是DESC，都无法正确按照连接的的存在时间来排序。
会出现存在时间长的连接和短的连接混杂排列，可见下图所示。

### To Reproduce

每次使用这个功能均可重现

### Platform

Windows

### System Version

Windows 10 22H2

### Software Version

1.4.3

### Additional Information
DESC
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/45709305/a714b42c-fec9-4f5a-b338-d43fef31fb38)

ASC
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/45709305/ce918c84-fd7b-42df-a01b-cb46b2d2a184)

**Comment by alanwang776** [comment]
它的排序全是按字母顺序排的

**Comment by ForestL18** [comment]
今天更新我试了下发现时间排序没起作用，于是上来看了下代码，发现只针对中文做了优化。🤣
有时间的话麻烦开发者稍微适配下英文吧。

**Comment by MystiPanda** [comment]
> 今天更新我试了下发现时间排序没起作用，于是上来看了下代码，发现只针对中文做了优化。🤣 有时间的话麻烦开发者稍微适配下英文吧。

还真是，忘了这茬了

**Comment by MystiPanda** [comment]
现在这种显示格式不太方便排序，而且没有了具体的时间数据之后排序并不精确，下个版本我改成HH:mm:ss这样的显示格式吧

**Comment by MystiPanda** [comment]
修复了，看了看文档，原来有更优雅的办法

**Comment by ForestL18** [comment]
> 修复了，看了看文档，原来有更优雅的办法

辛苦大佬了。

还有个关于UI的小建议，就是关于connections界面最下方的滚动条实在太细了，每次想点击的时候很难点到，还容易误点击为调整窗口大小，希望把下颌骨滚动条调粗一些，便于点击。

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/45709305/daef215b-9e09-4ffb-bbbf-27cc184b5249)
