### ISSUE TITLE
Ubuntu 24.04无法使用[BUG] 

### ISSUE THREAD

**Issue by damieai** [clash-verge-rev/clash-verge-rev#1081]
### 问题描述 / Describe the bug

无论是deb还是appimage文件均无法使用,即使安装缺少的依赖,依旧不可运行

### 复现步骤 / To Reproduce

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/103806899/0c696f81-4a0d-40d6-b4d7-4031552f25ee)

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/103806899/4409609a-9e2c-49c4-8d5c-ade64074f413)

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu 24.04

### 日志 / Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/103806899/a76eac4d-b6d2-4045-9060-50713c6fff4b)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/103806899/2c8120a5-57b6-413e-88dc-b2b8ba1fc07d)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/103806899/89d15c4c-f663-4291-ac5d-62fda3ac49ee)

**Comment by mcwindy** [comment]
Duplicated #866

**Comment by dongchengjie** [comment]
https://clash-verge-rev.github.io/faq/linux.html
