### ISSUE TITLE
[BUG] 下了个假的1.6.4 AppImage

### ISSUE THREAD

**Issue by wencan** [clash-verge-rev/clash-verge-rev#1082]
### 问题描述 / Describe the bug

从 https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.6.4 下了AppImage
文件名中的版本号的确是1.6.4
运行，新版提示还在，再看设置里的版本号，还是1.6.2

反复试了好几遍，每次都能重现
不信邪的我，又下载了压缩包，还是一样的问题

### 复现步骤 / To Reproduce

同问题描述

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

fedora

### 日志 / Log

无

**Comment by rebecca554owen** [comment]
@wencan tag都不一样，不可能。
