### ISSUE TITLE
[BUG] 笔记本双网卡使用TUN模式终端无法上网

### ISSUE THREAD

**Issue by witt-bit** [clash-verge-rev/clash-verge-rev#1085]
### 问题描述 / Describe the bug

相同的操作系统，相同的软件版本，笔记本存在问题，`TUN`模式打开后，终端直接没有网络，但浏览器和其他软件可以正常使用

第一张动图
1.关闭TUN模式
2.浏览器正常访问百度，不能访问谷歌（谷歌一直在加载中）
3.命令行中，可以ping百度，谷歌不通，`yay`更新命令可以正常使用

![1](https://github.com/clash-verge-rev/clash-verge-rev/assets/52407727/b9577b99-e198-4def-ae36-3232e46cf421)

第二张动图
1.打开`TUN`模式
2.浏览器正常访问百度，和谷歌
3.命令行中，ping任何地址不通，`yay`系统更新命令也不通
![2](https://github.com/clash-verge-rev/clash-verge-rev/assets/52407727/63d275e1-154c-413c-bcce-b200a4bffc30)

### 复现步骤 / To Reproduce

1.打开`TUN`模式
2.终端命令行发起HTTP调用

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Manjaro 24.0.0 Wynsdey

### 日志 / Log

日志界面没有任何日志

**Comment by xishang0128** [comment]
在linux下,tun不会处理ICMP,使用ping测试是无意义的

**Comment by jasper-ops** [comment]
找到meta的虚拟网卡，将它共享给你的真实网卡出口，然后再关掉共享，就可以了，就是打开共享，再关掉共享就可以了，这个共享的出口网卡要是你的真实出口网卡

**Comment by flyhunterl** [comment]
> 找到meta的虚拟网卡，将它共享给你的真实网卡出口，然后再关掉共享，就可以了，就是打开共享，再关掉共享就可以了，这个共享的出口网卡要是你的真实出口网卡

！！~！！感谢啊
