### ISSUE TITLE
[BUG] 若在1.6.4前的版本开启开机启动，更新安装1.6.4后导致开机启动开关失效

### ISSUE THREAD

**Issue by refined-fish** [clash-verge-rev/clash-verge-rev#1086]
### 问题描述 / Describe the bug

若在1.6.4前版本的clash中，例如1.6.2版本启用设置中的开机启动功能，更新安装1.6.4后原有1.6.2的开机启动条目将仍然存在且无法删除，即使卸载1.6.4的clash也无法删除。这将导致1.6.4版本的开机启动设置开关失效，无论怎么设置1.6.4都会被1.6.2残留的启动条目开机启动，也就是变成强制开机启动。实测可以通过再次安装1.6.2版本，关闭开机启动设置项后再更新来解决问题。经过尝试未能通过注册表搜索clash条目找到该条残留的启动设置。

### 复现步骤 / To Reproduce

1. 安装1.6.2版本clash
2. 开启1.6.2版本clash开机启动
3. 升级1.6.4版本clash，并关闭开机启动功能
4. 重启电脑，可以发现clash被强制启动，打开任务管理器“启动”页面可以发现仍然有clash条目

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 23H2 22631.3593

### 日志 / Log

不涉及clash内核，且涉及卸载安装过程，难以提供日志，如有需要日志，可能需要开发人员的指导来获取日志

**Comment by MystiPanda** [comment]
https://clash-verge-rev.github.io/faq/windows.html#_3

**Comment by AnyWAT** [comment]
绿色免费的 Autoruns 可管理系统开机启动、服务等，定位注册表。。。
