### ISSUE TITLE
[Feature] 电脑关机时自动关闭代理

### ISSUE THREAD

**Issue by xuqiangwinter** [clash-verge-rev/clash-verge-rev#1087]
### 功能描述 / Feature description

clash在运行期间并且开启代理的时候，电脑关机时希望clash可以自动清理系统代理。

### 使用场景 / Use case

clash在运行期间并且开启代理的时候，有时候电脑关机前忘记退出软件，再启动电脑时由于软件未启动，而代理还开着导致无法正常上网。

**Comment by wonfen** [comment]
建议设置随系统启动；不会有这个烦恼了

**Comment by ruiy326** [comment]
曾经在CFW（删库的那个）中看到这个建议，解决办法是把系统代理方式从http换成pac。
