### ISSUE TITLE
Linux 安装咨询

### ISSUE THREAD

**Issue by lebron-2016** [clash-verge-rev/clash-verge-rev#109]
您好，请问在ubuntu20.04系统使用需要安装那个文件呢？

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/80045218/723963ac-2468-4c9e-8851-5afd51ed154d)

直接下载后解压安装包就可以使用吗？

**Comment by MystiPanda** [comment]
下载 clash-verge_1.4.3_amd64.deb, 然后在文件所在位置执行
```bash
sudo apt-get install ./clash-verge_1.4.3_amd64.deb
```

**Comment by lebron-2016** [comment]
> 下载 clash-verge_1.4.3_amd64.deb, 然后在文件所在位置执行
> 
> ```shell
> sudo apt-get install ./clash-verge_1.4.3_amd64.deb
> ```

您好请问如何打开可视化界面呢？已运行上面那条指令
