### ISSUE TITLE
[BUG] Windows 11 出现 Meta 无法访问 Internet

### ISSUE THREAD

**Issue by wildwind2000** [clash-verge-rev/clash-verge-rev#1091]
### 问题描述 / Describe the bug

Windows 11 23H2 (22631.3593) 系统，Clash-Verge 升级到 1.6.4 版本，右下角网络图标出现 Meta 无法访问 Internet，此时各种客户端程序都无法访问互联网（例如 QQ 等程序），但浏览器访问国内国外一切正常。

### 复现步骤 / To Reproduce

以上问题存在的条件是Tun 模式选择 System 或 Mixed，改成 GVisor 后客户端都可以正常访问互联网了。
这时修改Tun 网卡名称 Meta 为其它名字，例如 Meta1，即便在 System 或 Mixed 模式，依然都一切正常了。
改回 Meta 名字，客户端又访问不了互联网了。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 23H2 (22631.3593)

### 日志 / Log

无

**Comment by myh66** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/53999290/6599709b-7f60-4dfc-8b25-93b6048a7208)
我这样就没网了1.6.4和1.6.5都不行

**Comment by wildwind2000** [comment]
现在的解决方案就是改一个新的 TUN 网卡名称

**Comment by myh66** [comment]
> 现在的解决方案就是改一个新的 TUN 网卡名称

我改了也没用在这里没有创建网卡
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/53999290/e09267f2-a354-444e-93f2-9bd35a928ce3)

**Comment by wildwind2000** [comment]
可以试试管理员模式启动这个程序，再在里面换网卡名称。

**Comment by myh66** [comment]
> 可以试试管理员模式启动这个程序，再在里面换网卡名称。

我解决了把传入那个什么的网络适配器删了就行了，Mate也行

**Comment by singer1026** [comment]
我也遇到这个问题
win11 中只要启用服务模式后 创建了Meta的网络连接  但是右下角的小地球就显示Meta 无法访问 Internet
然后qq就掉线了，浏览器到是正常上网。
verge 版本：v1.7.3

**Comment by physics-undergraduate** [comment]
好像是verge2.4.1版本更新了吗，之前上一个版本要更新时，我的订阅就错误更新。现在没更新，开VPN就显示Meta连接了
