### ISSUE TITLE
系统代理设置打开弹窗后，点击保存无法关闭。这个状态下右下角软件图标右键，选退出，软件会卡死

### ISSUE THREAD

**Issue by nsnans** [clash-verge-rev/clash-verge-rev#1093]
### 问题描述 / Describe the bug

1、系统代理设置打开弹窗后，点击保存无法关闭。
2、在上面的状态下，右下角软件图标右键，选退出，软件会卡死，无法退出。只能通过任务管理器结束任务

### 复现步骤 / To Reproduce

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/68949154/91ec853e-2497-4818-afad-ad6fe66ebade)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/68949154/996984f9-39f0-4d4b-bde2-58e6d6565daa)

# 第一个复现
- 打开弹窗后，直接按保存，正常关闭
- 当设置下面代码时，会报错，然后就卡死了，后面不管怎么点保存都关闭不了
- 这时候可以点取消关闭，但是重新打开弹窗再把代码删了，还是一样点保存没有反应

> [!WARNING]
> 试了二十多次，只要两三次报错后可以点保存，其余都会卡死

```
a.*；https://abs-aavs.*；
```

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/68949154/8a876e73-2267-4917-add6-961264ee276c)

# 第二个复现就算在第一个状态下，点保存没任何反应情况下。
右下角软件图标右键，选退出，软件会卡死

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 ，版本：23H2

### 日志 / Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/68949154/9ce3ff87-5e6b-45d4-9775-1292a7dd5405)
开发者工具和日志没有相关报错

**Comment by wonfen** [comment]
试试吧https删了，代理绕过只保留域名
