### ISSUE TITLE
[BUG] 最新版本，macOS下系统代理开关不起作用。

### ISSUE THREAD

**Issue by hugbio** [clash-verge-rev/clash-verge-rev#1094]
### 问题描述 / Describe the bug

 最新版本1.6.4，macOS下系统代理开关不起作用。已经执行了sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app问题依旧。系统还保留安装的ClashX，不知道这个影不影响

### 复现步骤 / To Reproduce

开关系统代理。看系统的网络设置的代理设置。所有开关都是关的。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.2.1 (23C71)

### 日志 / Log

我看日志中没有相关日志，是否需要更改日志配置。请告诉我

**Comment by hugbio** [comment]
我是第一次安装使用。

**Comment by wonfen** [comment]
有些mac系统修改系统代理需要管理员权限，原因未知。
这种情况下只能手动修改，或者用浏览器代理插件。

**Comment by fengbird** [comment]
我电脑系统是Ventura 13.3的也遇到了相同的情况，仅开系统代理开关不起作用，已经执行了sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app问题依旧，看系统的网络设置的代理设置。所有开关都是关的。
开启了TUN模式后才可以使用代理上网

**Comment by wonfen** [comment]
https://clash-verge-rev.github.io/faq/macos.html#apple-app

参考下这里的解决方法反馈一下

**Comment by hugbio** [comment]
看了一下。直接全局关闭密码保护会不会不安全？也会直接放行其他应用。我看其他的代理客户端在设置系统代理时，第一次会请求添加类似系统辅助权限，这个能否参考？

**Comment by double12gzh** [comment]
> https://clash-verge-rev.github.io/faq/macos.html#apple-app
> 
> 参考下这里的解决方法反馈一下

这个也没有解决我的问题。我使用的是 Mac Apple M2 Pro。
另外，我也尝试过https://github.com/clash-verge-rev/clash-verge-rev/issues/238#issuecomment-2002695694，同时也是无果，在执行 off 时会报错

```bash
[root@localhost] sudo networksetup -listnetworks
An asterisk (*) denotes that a network service is disabled.
Thunderbolt Bridge
Wi-Fi

[root@localhost] sudo networksetup -setwebproxystate Wi-Fi off
** Error: Unable to commit changes to network database.
```

**Comment by lajidonggua** [comment]
我也有这个问题，请问现在有解决办法了吗

**Comment by wonfen** [comment]
> 我也有这个问题，请问现在有解决办法了吗

https://clash-verge-rev.github.io/faq/macos.html#apple-app

参考下这里的解决方法反馈一下

**Comment by lajidonggua** [comment]
> > 我也有这个问题，请问现在有解决办法了吗
> 
> https://clash-verge-rev.github.io/faq/macos.html#apple-app
> 
> 参考下这里的解决方法反馈一下

按这个方法
系统偏好设置 -> 安全性与隐私 -> 高级，关闭 访问系统范围偏好设置需要输入管理员密码 （不同系统版本的名称略有差异），点击 完成 。

还是不行。 需要当前用户为管理员才没问题。。。所以目前还是无法在 非管理员用户上开启系统代理，只能用 tun 模式

**Comment by Wegt-meoh** [comment]
命令行使用管理员权限运行clash verge就可以了，没管理员权限脚本修改不了网络的proxy

**Comment by poplark** [comment]
系统设置 => 网络 里面有没有其他 PPPoE 的服务，把它删掉就可以了
<img width="494" alt="image" src="https://github.com/user-attachments/assets/c4d0e29e-dfe7-4f7b-9ffb-d7da1325cce7">
我这里存在  PPPoE 的服务时，查看 wifi 的详细信息，弹出的都是 PPPoE 的详细信息，看上去是 macOS 的 bug

**Comment by wonfen** [comment]
试试最新2.0 rc6版本，如果还有问题请开新issue

**Comment by Similarityoung** [comment]
> 系统设置 => 网络 里面有没有其他 PPPoE 的服务，把它删掉就可以了 <img alt="image" width="494" src="https://private-user-images.githubusercontent.com/9588298/379094380-c4d0e29e-dfe7-4f7b-9ffb-d7da1325cce7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQzMTU2NTUsIm5iZiI6MTc1NDMxNTM1NSwicGF0aCI6Ii85NTg4Mjk4LzM3OTA5NDM4MC1jNGQwZTI5ZS1kZmU3LTRmN2ItOWZmYi1kN2RhMTMyNWNjZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDgwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA4MDRUMTM0OTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTk0NWE3NTlhYmEwNTNhYWUzMmE2NjY0MjI1OWY0MGViNmU1NDY3NmM3ZTA4ZmEzNzg5MmFmYjVkZDRmYmZlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Op83ByD3ygCEke9fIWVzZNC_PMhawbLHYbIQ7WzMzFs"> 我这里存在 PPPoE 的服务时，查看 wifi 的详细信息，弹出的都是 PPPoE 的详细信息，看上去是 macOS 的 bug

谢谢，我也是这个问题，估计是之前删 clash pro 的时候，删除软件没清理干净导致的。

**Comment by QixingJiang** [comment]
> 系统设置 => 网络 里面有没有其他 PPPoE 的服务，把它删掉就可以了 <img alt="image" width="494" src="https://private-user-images.githubusercontent.com/9588298/379094380-c4d0e29e-dfe7-4f7b-9ffb-d7da1325cce7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzUyMTgwNDQsIm5iZiI6MTc3NTIxNzc0NCwicGF0aCI6Ii85NTg4Mjk4LzM3OTA5NDM4MC1jNGQwZTI5ZS1kZmU3LTRmN2ItOWZmYi1kN2RhMTMyNWNjZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA0MDNUMTIwMjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTBkYzQwMTViYjQxZjM5MTE0ZTM1MTVhNWVkYmJjNDhmMGFiODk0ZDYyODc2NDU2MDQ1ZGY4Mzk2ZDg0ZjA2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ZvdH7NUOcCLszUNlZOmAX1Hq919d3LCj7IX302MB3Tg"> 我这里存在 PPPoE 的服务时，查看 wifi 的详细信息，弹出的都是 PPPoE 的详细信息，看上去是 macOS 的 bug

搞了好久，终于解决了，感谢，把其他的服务全删了就好了，怀疑就是其他各种比如ClashX，FLClash删除的时候没删干净
