### ISSUE TITLE
[BUG] win11家庭版，开了TUN模式退出clash verge后无法上网，手动关闭系统代理，也是不行，只能运行clash verge打开tun模式才能上网

### ISSUE THREAD

**Issue by xyufe** [clash-verge-rev/clash-verge-rev#1095]
### 问题描述 / Describe the bug

win11家庭版，开了TUN模式退出clash verge后无法上网

### 复现步骤 / To Reproduce

win11家庭版，开了TUN模式退出clash verge后无法上网，手动关闭TUN模式和电脑系统代理，也是不行，任何浏览器都都上不了网，还有一些需要用到网络的软件也是不能正常使用，但是微信聊天软件能正常使用。
但是重新运行clash verge打开tun模式整个电脑网络都正常，只要关闭clash verge就不行，请问这是一个bug吗？还是win11家庭版系统问题?

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11家庭

### 日志 / Log

05-30 00:08:31INFO
[TCP] 127.0.0.1:41915 --> beacons4.gvt2.com:443 using GLOBAL
05-30 00:08:31INFO
[TCP] 127.0.0.1:41917 --> update-drcn.platform.hicloud.com:443 using GLOBAL
05-30 00:08:32INFO
[TCP] 127.0.0.1:41919 --> assets.msn.cn:443 using GLOBAL
05-30 00:08:34INFO
[TCP] 127.0.0.1:41921 --> v20.events.data.microsoft.com:443 using GLOBAL
05-30 00:08:41INFO
[TCP] 127.0.0.1:41923 --> update-drcn.platform.hicloud.com:443 using GLOBAL
05-30 00:08:41INFO
[TCP] 127.0.0.1:41925 --> beacons4.gvt2.com:443 using GLOBAL
05-30 00:08:48INFO
[TCP] 127.0.0.1:41927 --> google.com:443 using GLOBAL
05-30 00:08:51INFO
[TCP] 127.0.0.1:41933 --> assets.msn.cn:443 using GLOBAL
05-30 00:08:51INFO
[TCP] 127.0.0.1:41935 --> update-drcn.platform.hicloud.com:443 using GLOBAL
05-30 00:08:52INFO
[TCP] 127.0.0.1:41937 --> beacons5.gvt2.com:443 using GLOBAL
05-30 00:09:01INFO
[TCP] 127.0.0.1:41940 --> update-drcn.platform.hicloud.com:443 using GLOBAL
05-30 00:09:02INFO
[TCP] 127.0.0.1:41942 --> beacons5.gvt2.com:443 using GLOBAL
05-30 00:09:05INFO
[TCP] 127.0.0.1:41945 --> oauth-login.platform.hicloud.com:443 using GLOBAL
05-30 00:09:07INFO
[TCP] 127.0.0.1:41947 --> google.com:443 using GLOBAL
05-30 00:09:08INFO
[TCP] 127.0.0.1:41949 --> oauth-login.platform.hicloud.com:443 using GLOBAL

**Comment by MQMQgo** [comment]
应该是fakeip的原因：TUN模式默认使用fakeip，你在开启tun后应用发起dns请求时clash会返回假的ip，你的应用未必遵循clash设定的ttl，所以在关闭tun后依旧会采用clash返回的假ip，进而导致无法上网。而微信聊天应该是直接用的服务器ip而不是域名，没有dns的过程所以不受影响。关闭tun模式后清空系统的dns缓存应该可以解决问题。

**Comment by leopardciaw** [comment]
Windows11也是这样，刚开始是正常的。

**Comment by hanhuiyan** [comment]
同问这个问题

**Comment by hanhuiyan** [comment]
> 应该是fakeip的原因：TUN模式默认使用fakeip，你在开启tun后应用发起dns请求时clash会返回假的ip，你的应用未必遵循clash设定的ttl，所以在关闭tun后依旧会采用clash返回的假ip，进而导致无法上网。而微信聊天应该是直接用的服务器ip而不是域名，没有dns的过程所以不受影响。关闭tun模式后清空系统的dns缓存应该可以解决问题。

这个是不是只要清空一次dns的缓存，下次就不会遇见这个问题了呀

**Comment by MQMQgo** [comment]
这是由fakeip的工作原理决定的，每次你开启tun+fakeip后如果要关闭tun都需要清空DNS缓存。你可以选择不用tun模式，或者使用tun+redir host

**Comment by baoyichi** [comment]
这个问题什么时候能修复啊？mac m1的也这样，关掉Tun模式，什么网都没有

**Comment by Artrajz** [comment]
我的电脑情况是，启动一次tun之后再关闭，部分网站就无法访问了，比如b站。按照 @MQMQgo 所说清空DNS缓存，我使用`ipconfig /flushdns`也无法恢复正常，请问有什么解决办法吗？

**Comment by EnderAvaritia** [comment]
> 我的电脑情况是，启动一次tun之后再关闭，部分网站就无法访问了，比如b站。按照 @MQMQgo 所说清空DNS缓存，我使用`ipconfig /flushdns`也无法恢复正常，请问有什么解决办法吗？

先ping一下试试？你那可能不是dns的问题

**Comment by Artrajz** [comment]
> 先ping一下试试？你那可能不是dns的问题

`ping bilibili.com` 通过。但是chrome和edge都无法直接访问b站，必须要打开系统代理或者tun模式才能访问，这会是什么问题呢？

**Comment by EnderAvaritia** [comment]
> > 先ping一下试试？你那可能不是dns的问题
> 
> `ping bilibili.com` 通过。但是chrome和edge都无法直接访问b站，必须要打开系统代理或者tun模式才能访问，这会是什么问题呢？

首先确定不是dns的问题，但是具体是啥问题，信息不足

**Comment by yhgalaxy** [comment]
我是ping不通显示的192开头的fakeip，启动应用但是不开代理就会上不了网。

**Comment by naniccc** [comment]
同样的问题，我有一个软件就是这个问题，必须在tun模式才能上网，退出就没网，这个tun模式好奇怪哦，重置系统网络也不行，按照楼上说的ipconfig /flushdns也不行，目前无解

**Comment by komgmeng** [comment]
我今日也出现这个问题了，不过是必须代理模式才能正常进入bilibili和一些网站，有一些不需要，基本所有方法都试了，然后我的解决办法是先关闭代理设置，然后在浏览器设置里 上面的搜索设置里输入dns，然后将【使用安全的 DNS 指定如何查找网站的网络地址】关闭。然后看一看可不可以正常进入网站，然后重新开启就可以了，实测是好用的，我也去清除过dns，重启过电脑和路由器，然后也去网络设置里关闭了代理都不好使，不知道能不能帮到同样问题的大家

**Comment by wslqy** [comment]
之前我也遇到了这个问题，我是在浏览器网络安全那块设置了一下，后来就好了，你可以试试，具体操作再搜索下。

**Comment by zx09** [comment]
> 之前我也遇到了这个问题，我是在浏览器网络安全那块设置了一下，后来就好了，你可以试试，具体操作再搜索下。

什么地方的浏览器网络安全 能说清楚一些吗 我也遇到这个问题

**Comment by wslqy** [comment]
> > 之前我也遇到了这个问题，我是在浏览器网络安全那块设置了一下，后来就好了，你可以试试，具体操作再搜索下。
> 
> 什么地方的浏览器网络安全 能说清楚一些吗 我也遇到这个问题

我现在也忘记了，但是我又去搜索了一下，和这个说的大差不差，就是安全DNS。

![Image](https://github.com/user-attachments/assets/783795c9-0734-4a5c-b4ec-14fe87556ac6)
