### ISSUE TITLE
[BUG] 在【订阅】界面，选中某个订阅，右键-打开文件，没有任何反应

### ISSUE THREAD

**Issue by Postroggy** [clash-verge-rev/clash-verge-rev#1096]
### 问题描述 / Describe the bug

 在【订阅】界面，选中某个订阅，右键-打开文件，没有任何反应。 期望的操作结果是：在资源管理器中，跳转到订阅文件。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/53985742/25a3d451-4945-43f0-bccc-141dfb291225)

### 复现步骤 / To Reproduce

【订阅】- 选中某个订阅 - 右键 - 打开文件

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

与内核log无关，是GUI本身的bug。

**Comment by dongchengjie** [comment]
期望的结果是以默认的yaml关联程序打开，优先使用VSCODE
如果打不开，就是你没有设置电脑关联的yaml文件默认打开程序

**Comment by rebecca554owen** [comment]
@Postroggy 你的期望是 打开文件目录，这里的字眼描述是 用某个默认程序打开yml文件，如果想要编辑，可以直接点击编辑文件。
