### ISSUE TITLE
[BUG] MacOS 10.15.7 打开面板白屏

### ISSUE THREAD

**Issue by Ardin963** [clash-verge-rev/clash-verge-rev#1099]
### 问题描述 / Describe the bug

MacOS 10.15.7 打开面板白屏，电脑变得有点卡
系统版本：MacOS 10.15.7
处理器：intel i7
软件版本：1.6.4
<img width="880" alt="截屏2024-05-31 06 18 11" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/59965293/0c3c56b5-0eb8-448d-b3dc-c9342ce3d5f7">

### 复现步骤 / To Reproduce

Intel版本的macbook重新打开一次

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

MacOS 10.15.7

### 日志 / Log

2024-05-31 06:08:53 ERROR - unset system dns failed: 4

**Comment by Ardin963** [comment]
![Uploading 截屏2024-05-31 06.19.14.png…]()

**Comment by Ardin963** [comment]
<img width="987" alt="截屏2024-05-31 06 19 14" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/59965293/47936934-50e0-4432-967e-8e8ac09c312e">

**Comment by dongchengjie** [comment]
用最新的alpha版本
