### ISSUE TITLE
[BUG] MAC系统上，pycharm无法通过局域网连接使用代理，clash必须开系统代理才行

### ISSUE THREAD

**Issue by xmhwws** [clash-verge-rev/clash-verge-rev#1101]
### 问题描述 / Describe the bug

pycharm设置http代理如下
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/42903751/2ff68647-664a-4d7e-8564-58141809a7f6)

但是在代码里面运行：
```
import requests

url = 'https://ipinfo.io/json'
response = requests.get(url=url).json()
print(f'获取到代理ip->{response}')
```

clash选全局模式，梯子有用的情况下；
补充：pycharm设置http代理还是socks代理，还是设置无代理，都不影响下面的结果：
如果clash不开系统代理，代码输出的仍旧是国内ip；
只有clash开系统代理，代码输出的才是梯子的ip；

clash已开启局域网连接：
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/42903751/88247661-91e9-45a3-bb7e-7fe5b63a344f)

clash版本：最新版v1.6.4

### 复现步骤 / To Reproduce

pycharm在代码里面运行：
```
import requests

url = 'https://ipinfo.io/json'
response = requests.get(url=url).json()
print(f'获取到代理ip->{response}')
```

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

13.3 (22E252)

### 日志 / Log

这个应该不需要clash日志

**Comment by MystiPanda** [comment]
pycharm 的代理设置又不会对你的代码生效

**Comment by dongchengjie** [comment]
给我整不会了哈😃你配置IDE的client使用代理，跟request的client有啥关系

**Comment by xmhwws** [comment]
> 给我整不会了哈😃你配置IDE的client使用代理，跟request的client有啥关系

我不了解这块；
跟request的client应该有关系吧：clash开系统代理，pycharm运行的代码里面就能用代理了

**Comment by xmhwws** [comment]
> IDE设置的代理只和IDE层面的功能有关（比如插件，账号之类的）；而你写的代码是由操作系统执行的，所以“开启系统代理”=让你的操作系统执行代码的时候走clash的代理。
> 
> 如果你不想开启系统代理，但是又想request函数走代理的话你就得在这个request函数中配置代理相关的部分，让操作系统执行你代码的时候走你填入的配置。

受教了，感谢
