### ISSUE TITLE
[BUG]1.4.3启动后不能加载出配置好的订阅

### ISSUE THREAD

**Issue by Phospherus6089** [clash-verge-rev/clash-verge-rev#111]
### Describe the bug

①启动1.4.3后，有时配置好的订阅显示不出来，查看“规则“，里面是空白。
②节点测速非常慢，数值显示不出来。
换回1.3.8版后，一切正常。

### To Reproduce

启动1.4.3后
切换到规则，里面有时有规则，有时是空白，
在代理节点界面，点击测速，测速非常慢，数值显示不出来。订阅的节点是没有问题的，换回1.3.8版本后，节点测速正常。

### Platform

Windows

### System Version

win10

### Software Version

1.4.3

**Comment by MystiPanda** [comment]
使用的都是meta内核吗？

**Comment by Phospherus6089** [comment]
用的meta内核

**Comment by wonfen** [comment]
无进一步反馈，关闭了。
