### ISSUE TITLE
[BUG] 1.6.4新版更新订阅后，为proxy-group手动选择的规则会重置

### ISSUE THREAD

**Issue by wjfu99** [clash-verge-rev/clash-verge-rev#1113]
### 问题描述 / Describe the bug

更新1.6.4版本后，clash verge无法记住规则组之前手动选择的规则。
回退至版本1.6.2后恢复正常。

### 复现步骤 / To Reproduce

1. 随意选择一个规则组，任选一个下属的规则（除了默认之外的规则）
2. 更新profile
3. 发现刚刚选定的下属规则已被重置为默认规则

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5

### 日志 / Log

[2024-06-02-1711.log](https://github.com/user-attachments/files/15524761/2024-06-02-1711.log)

**Comment by Joneedhome** [comment]
v1.6.6版本的同样问题，自定义的直连网站和需要代理的网站，手动写入yaml配置文件，无法生效，会被重置为初始的yaml
