### ISSUE TITLE
[BUG] macOS应用无签名

### ISSUE THREAD

**Issue by i0ntempest** [clash-verge-rev/clash-verge-rev#1116]
### 问题描述 / Describe the bug

应用无签名，导致默认情况下Apple Silicon Mac无法启动应用，以及Homebrew Cask[不接收此应用](https://github.com/Homebrew/homebrew-cask/pull/175581)
解决方法很简单，至少Homebrew只需要软件有有效签名而不管是什么签名，所以本地adhoc签一下就足够了，不需要给苹果交钱。

### 复现步骤 / To Reproduce

```
$ codesign --verify --verbose /Applications/Clash\ Verge.app/
/Applications/Clash Verge.app/: code has no resources but signature indicates they must be present
```

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5

### 日志 / Log

N/A

**Comment by wonfen** [comment]
好，我研究研究。

**Comment by MystiPanda** [comment]
为什么 zap trash 里面要写 ClashX

**Comment by i0ntempest** [comment]
可以的话尽快出个release，好让Homebrew那边接收

**Comment by i0ntempest** [comment]
Well， 要么是我记错了要么是他们现在的检测更严了。。。adhoc签名现在过不了Homebrew他们的检测了。他们的理由是这种签名在不关闭gatekeeper的情况下依然打不开。想上Homebrew的话看来必须给苹果交钱了买证书了。

**Comment by MystiPanda** [comment]
已经签名了，下个版本就可以继续提交 homebrew 了
