### ISSUE TITLE
[Feature] 新增规则集订阅

### ISSUE THREAD

**Issue by AidenLee1994** [clash-verge-rev/clash-verge-rev#1119]
### 功能描述 / Feature description

类似于singbox一样，可以让用户自定义第三方规则集，可以从公开的规则中进行订阅添加

### 使用场景 / Use case

机场提供的配置文件规则不够足，自己写规则又很麻烦，想添加已有的规则也没法直接添加

**Comment by dongchengjie** [comment]
https://clash-verge-rev.github.io/guide/merge.html
