### ISSUE TITLE
[Feature] 热键功能修正为非独占模式

### ISSUE THREAD

**Issue by LittleArray** [clash-verge-rev/clash-verge-rev#1120]
### 功能描述 / Feature description

1. 将热键修正为非独占模式
2. 添加按键冲突提醒

### 使用场景 / Use case

在某些应用中需要用到相同的热键,而clash占用热键后其他应用就捕获不到该热键

**Comment by MystiPanda** [comment]
要用全局快捷键自然会有冲突的问题，设置个不冲突的不就好了。
