### ISSUE TITLE
[Feature] 希望更改代理开关位置

### ISSUE THREAD

**Issue by xylogs** [clash-verge-rev/clash-verge-rev#1121]
### 功能描述 / Feature description

一个不成熟的建议：
最频繁使用的开关按钮建议放在一级页面，如图
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/45510005/b4921e48-5ffe-4d5a-9eec-59dc30e2563b)

### 使用场景 / Use case

如图
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/45510005/b4921e48-5ffe-4d5a-9eec-59dc30e2563b)

**Comment by chenbihao** [comment]
打开是代理页，可以直接切换到直连... 不就ok了吗 hh

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/21167262/b9550092-7d4a-4c53-ba7d-26dd4a95d7af)
