### ISSUE TITLE
[BUG] 系统唤醒后监控数值不更新

### ISSUE THREAD

**Issue by kingofotaku** [clash-verge-rev/clash-verge-rev#1122]
### 问题描述 / Describe the bug

每次系统从睡眠/休眠中唤醒后流量/内存监控数值就会卡死不再更新，必须重启一下软件才能恢复正常。虽然不影响功能正常使用，但还是略感不便。

### 复现步骤 / To Reproduce

在打开cvr后睡眠再唤醒

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

23h2/22631.3592

### 日志 / Log

无

**Comment by wonfen** [comment]
webview或tauri底层问题，无解决方案。
