### ISSUE TITLE
[BUG] MACOS菜单栏出现双图标

### ISSUE THREAD

**Issue by lkf2432** [clash-verge-rev/clash-verge-rev#1123]
### 问题描述 / Describe the bug

MACOS菜单栏出现两个图标，在左上角苹果标志旁边同时存在第二个图标，点击时可触发右侧正常图标的点击行为。软件关闭后两个图标同时消失。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/48993944/e4234594-215c-4741-afa6-20ad75d95279)

1.5.9版也存在此问题

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/48993944/a57c5365-b177-451d-9567-e9383726faa8)

### 复现步骤 / To Reproduce

正常启动程序即可出现双图标

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5

### 日志 / Log

无错误日志

**Comment by dongchengjie** [comment]
https://clash-verge-rev.github.io/faq/macos.html#macos_1
