### ISSUE TITLE
[BUG] 1.6.5代理组图标丢失不见

### ISSUE THREAD

**Issue by ERCB** [clash-verge-rev/clash-verge-rev#1125]
### 问题描述 / Describe the bug

更新1.6.5版本后，原来代理组图标不见了。

![WX20240604-155720](https://github.com/clash-verge-rev/clash-verge-rev/assets/2218697/109aa1e1-b5c6-47dc-af78-ded78ba318ff)

但查看应用目录中icons/cache/下原来的图标缓存是存在的。

![WX20240604-160011](https://github.com/clash-verge-rev/clash-verge-rev/assets/2218697/93751400-3365-45d9-a0dc-c6a21fbbb692)

### 复现步骤 / To Reproduce

直接在1.6.4版本应用界面直接升级后出现该问题，再次下载安装包覆盖安装升级也是这样。

其他测试：重启clash、重启应用、更新订阅配置也是这样。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

M2芯片 MacOS 14.5 (23F79)

### 日志 / Log

![WX20240604-160457](https://github.com/clash-verge-rev/clash-verge-rev/assets/2218697/78df1558-3de3-4373-8915-7181cb517e64)

帖子字数限制，日志只能截图提交

**Comment by dongchengjie** [comment]
操作失误，已修复等更新
