### ISSUE TITLE
[BUG] 更新clash verge报错，无法更新

### ISSUE THREAD

**Issue by cilicilis** [clash-verge-rev/clash-verge-rev#1126]
### 问题描述 / Describe the bug

Object.hasOwn is not a function. (In '0bject.hasOwn(n,_.from)', 'object.hasOwn' is undefined)
 Error Stack
J5tatauri://localhost/assets/index-Xn nHTZk.js:1448:4621587Vq@tauri://localhost/assets/index-Xn nHTZk.js:39:84357Dme@tauri://localhost/assets/index-Xn nHTZk.js:41:139675xmeatauri://localhost/assets/index-Xn nHTZk.js:41:135376UPeatauri://localhost/assets/index-Xn nHTZk is:41:135299RAatauri://localhost/assets/index-Xn nHTZk.js:41:135148aWatauri://localhost/assets/index-Xn nHTZk.js:41:131494Fne@tauri://localhost/assets/index-Xn nHTZk.js:41:132300Fnealnative codelVv@tauri://localhost/assets/index-Xn nHTZk.is:39:70588KPeatauri://localhost/assets/index-Xn nHTZk.js:41:136886S0atauri://localhost/assets/index-Xn nHTZk.js:41:135869yme@tauri://localhost/assets/index-Xn nHTZk.js:41:131292ymealnative code]Satauri://localhost/assets/index-Xn nHTZk.js:26:20079Eatauri://localhost/assets/index-Xn nHTZk.js:26:20441

### 复现步骤 / To Reproduce

更新clash verge报错，无法更新

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

intel芯片

### 日志 / Log

Object.hasOwn is not a function. (In '0bject.hasOwn(n,_.from)', 'object.hasOwn' is undefined)
 Error Stack
J5tatauri://localhost/assets/index-Xn nHTZk.js:1448:4621587Vq@tauri://localhost/assets/index-Xn nHTZk.js:39:84357Dme@tauri://localhost/assets/index-Xn nHTZk.js:41:139675xmeatauri://localhost/assets/index-Xn nHTZk.js:41:135376UPeatauri://localhost/assets/index-Xn nHTZk is:41:135299RAatauri://localhost/assets/index-Xn nHTZk.js:41:135148aWatauri://localhost/assets/index-Xn nHTZk.js:41:131494Fne@tauri://localhost/assets/index-Xn nHTZk.js:41:132300Fnealnative codelVv@tauri://localhost/assets/index-Xn nHTZk.is:39:70588KPeatauri://localhost/assets/index-Xn nHTZk.js:41:136886S0atauri://localhost/assets/index-Xn nHTZk.js:41:135869yme@tauri://localhost/assets/index-Xn nHTZk.js:41:131292ymealnative code]Satauri://localhost/assets/index-Xn nHTZk.js:26:20079Eatauri://localhost/assets/index-Xn nHTZk.js:26:20441

**Comment by carterywx** [comment]
same here

**Comment by cilicilis** [comment]
没看懂怎么解决这个问题
