### ISSUE TITLE
[Feature] 更新对话框增加发布页链接

### ISSUE THREAD

**Issue by quantumfallout** [clash-verge-rev/clash-verge-rev#1129]
### 功能描述 / Feature description

在提示更新的对话框内，加入[发布页](https://github.com/clash-verge-rev/clash-verge-rev/releases)的链接

### 使用场景 / Use case

由于便携版需要自行下载更新包替换，在更新的对话框内增加链接可以少点几下鼠标（懒

**Comment by wonfen** [comment]
软件右上角有连接

**Comment by lbcake** [comment]
> ### 功能描述 / Feature description
> 在提示更新的对话框内，加入[发布页](https://github.com/clash-verge-rev/clash-verge-rev/releases)的链接
> 
> ### 使用场景 / Use case
> 由于便携版需要自行下载更新包替换，在更新的对话框内增加链接可以少点几下鼠标（懒

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/26319880/b85c3a10-2e61-4d26-a170-c825e8e58226)
