### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by speadernike** [clash-verge-rev/clash-verge-rev#1131]
### 问题描述 / Describe the bug

Clash Verge 偶现 CPU 占用率过高（每过一段时间就会出现），重启之后解决

### 复现步骤 / To Reproduce

<img width="291" alt="clash" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/111223799/1b357e6c-95f1-4152-98f9-7259bc0ba7fe">

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Sonoma 14.5 (23F79)

### 日志 / Log

没有及时保存日志，抱歉

**Comment by wonfen** [comment]
出现的时候从活动监视器看

**Comment by erich2s** [comment]
我也遇到了类似的问题，是clash-meta内核CPU占用突然升高，怪不得我说怎么我的M1 Pro看个youtube都能发烫

![CleanShot 2024-06-06 at 13 56 55@2x](https://github.com/clash-verge-rev/clash-verge-rev/assets/53571741/50dcb21f-8195-4693-b3b0-876c0fa62f7e)

![CleanShot 2024-06-06 at 13 57 18@2x](https://github.com/clash-verge-rev/clash-verge-rev/assets/53571741/88a12a04-dd82-4ea0-b575-6d5b369a5b6a)

![CleanShot 2024-06-06 at 13 58 51@2x](https://github.com/clash-verge-rev/clash-verge-rev/assets/53571741/c963d511-358b-4c46-bed5-b1312b6233b3)

**Comment by speadernike** [comment]
你的 pro 有风扇还算好的，我的 air 没风扇，就一会儿就烧到 90 多度了哈哈哈哈。

不过这个问题是偶尔会出现的问题，问题不大，发现了及时重启 Clash Verge 就行了。

我使用半年以来，只遇到过三次，第一次遇到是在几个月之前，当时在这个软件项目的一个issue里边，我看见同样有人遇到这个问题，下面一个开发者说这个可能是流量图显示的问题，然后我就在设置里把这个图显给关闭了，后面很长一段时间都没出现这个问题了，结果更新最新版软件（v1.6.5）之后几个小时内再次出现了这个问题（截止目前使用正常）
