### ISSUE TITLE
[BUG] 不支持Reality协议

### ISSUE THREAD

**Issue by majiang4960** [clash-verge-rev/clash-verge-rev#1133]
### 问题描述 / Describe the bug

<img width="748" alt="微信图片_20240606022622" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/40627024/051241e6-8280-4928-9ee7-610571453da4">

### 复现步骤 / To Reproduce

<img width="748" alt="微信图片_20240606022622" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/40627024/3c55ad5d-148f-4884-b2d7-d6fc2eaa4acb">

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11

### 日志 / Log

连不上，全冒红

**Comment by xishang0128** [comment]
连不上不等于不支持,其他的都连的上
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/95160953/5c87ff9b-96ff-4215-8ea3-71b2f6566b4f)
