### ISSUE TITLE
[BUG] ubuntu 选项卡切换卡死 (AppImage only)

### ISSUE THREAD

**Issue by YuHuanTin** [clash-verge-rev/clash-verge-rev#1134]
### 问题描述 / Describe the bug

频繁切换选项卡将会导致选项卡卡死

### 复现步骤 / To Reproduce

![PixPin_2024-06-06_11-15-55](https://github.com/clash-verge-rev/clash-verge-rev/assets/51024916/782fce52-d159-42e9-852c-96d712618298)

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

OS: Ubuntu 20.04 focal Kernel: x86_64 Linux 5.15.0-107-generic DE: GNOME 3.36.5

### 日志 / Log

无日志产生
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/51024916/b4ea1fff-65a6-45ad-bf7a-2ff3d05e4eb0)

**Comment by dongchengjie** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/cc2ca307-024c-496b-9813-dafa3fbe0e0a)
