### ISSUE TITLE
[BUG] 规则模式 所有IP 全部Error 全局模式正常使用

### ISSUE THREAD

**Issue by Little1Git** [clash-verge-rev/clash-verge-rev#1135]
### 问题描述 / Describe the bug

开启全局模式后,电脑休眠了一晚上,电脑唤醒后全局模式ip都能连上,换规则模式ip都 秒Error ,重启电脑仍然这样

### 复现步骤 / To Reproduce

开全局模式 休眠一晚上 全局模式 切换 规则模式 全部Error

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

[TCP] 127.0.0.1:13554 --> beacons5.gvt3.com:443 using GLOBAL
06-06 15:36:12INFO
[TCP] 127.0.0.1:13927(ctfmon.exe) --> go.microsoft.com:443 match DomainSuffix(microsoft.com) using DIRECT
06-06 15:36:46INFO
[TCP] 127.0.0.1:14278(chrome.exe) --> collector.github.com:443 match DomainKeyword(github) using Best VPN![🇰🇷7韩国春川集群-联通/移动(新协议)]
06-06 15:36:46INFO
[TCP] 127.0.0.1:14280(chrome.exe) --> collector.github.com:443 match DomainKeyword(github) using Best VPN![🇰🇷7韩国春川集群-联通/移动(新协议)]
06-06 15:36:48INFO
[TCP] 127.0.0.1:14302(chrome.exe) --> www.reddit.com:443 match Match using Best VPN![🇰🇷7韩国春川集群-联通/移动(新协议)]

**Comment by luziyi** [comment]
same issue

**Comment by glaw1984** [comment]
根本没有人来解决
