### ISSUE TITLE
[BUG] AppImage的版本号问题

### ISSUE THREAD

**Issue by wencan** [clash-verge-rev/clash-verge-rev#1136]
### 问题描述 / Describe the bug

之前我反馈，AppImage换用新版之后，程序显示的版本号还是旧版，还是可以看到新版提醒。
https://github.com/clash-verge-rev/clash-verge-rev/issues/1082
刚刚用最新的版本1.6.5试了，问题依旧
然后，我重启了系统，再打开AppImage，看到了最新的版本号！

### 复现步骤 / To Reproduce

1. 启动旧版AppImage，然后关闭。这时删除旧版AppImage文件，并不影响下面的步骤
2. 启动新版AppImage，这时显示的版本号还是旧版
3. 重启系统，再打开新版AppImage，显示新版号

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

fedora 40

### 日志 / Log

无

**Comment by wonfen** [comment]
换deb或者rpm
