### ISSUE TITLE
[BUG] 拓展配置文件rule选项出现，会出现外网无法访问的情况

### ISSUE THREAD

**Issue by shesio** [clash-verge-rev/clash-verge-rev#1143]
### 问题描述 / Describe the bug

rules:
  - DOMAIN,hamibot.com,DIRECT  在merge的配置中添加如上规则，主配置的rule可能会失效会失效

### 复现步骤 / To Reproduce

# Merge Template for clash verge
# The `Merge` format used to enhance profile

dns:
  use-hosts: true
  enable: true
  prefer-h3: true
  listen: 127.0.0.1:53
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 114.114.114.114
  enhanced-mode: redir-host
  nameserver-policy:
    '+.internal.crop.com': '10.0.0.1'
  nameserver:
    - https://1.1.1.1/dns-query    
    - https://223.5.5.5/dns-query
  fallback:
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://1.1.1.1/dns-query    
    - https://223.5.5.5/dns-query

  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
rules:
  - DOMAIN,hamibot.com,DIRECT

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

可能只是我的配置不对？？

**Comment by dongchengjie** [comment]
https://clash-verge-rev.github.io/guide/merge.html
