### ISSUE TITLE
[BUG] thread 'main' panicked on fedora 40

### ISSUE THREAD

**Issue by ByteAKA8bit** [clash-verge-rev/clash-verge-rev#1144]
### 问题描述 / Describe the bug

Fedora Linux 40 (Workstation Edition)
Linux 6.8.11-300.fc40.x86_64
gnome 46
AMD Ryzen™ 7 4800U

稳定版本和Alpha版本都会崩溃
点击图标打不开,使用命令行运行提示:thread 'main' panicked

### 复现步骤 / To Reproduce

使用命令行运行:clash-verge
或者点击桌面图标

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Fedora Linux 40 (Workstation Edition)

### 日志 / Log

thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libappindicator-sys-0.7.3/src/lib.rs:41:5:
Failed to load ayatana-appindicator3 or appindicator3 dynamic library
libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
libappindicator3.so.1: cannot open shared object file: No such file or directory
libayatana-appindicator3.so: cannot open shared object file: No such file or directory
libappindicator3.so: cannot open shared object file: No such file or directory
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

**Comment by ByteAKA8bit** [comment]
安装的是Alpha版本 clash-verge-1.6.5-1.x86_64.rpm

**Comment by picasuo** [comment]
zypper install libayatana-appindicator3-1
通过终端安装了这个解决了问题，软件成功运行起来了。

**Comment by itstudygeen** [comment]
> sudo zypper install libayatana-appindicator3-1 通过终端安装了这个，软件成功运行起来了。

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/23158585/f6c7dd6a-5372-47d3-a763-bbd8d2e9fb2a)
