### ISSUE TITLE
[BUG] 导入订阅时显示error sending request for url

### ISSUE THREAD

**Issue by Amadeus-67** [clash-verge-rev/clash-verge-rev#1145]

**Comment by dongchengjie** [comment]
第一次看到给机场域名打码不给token打码的 你漏了你知不知道
给你删掉了😅 能正常导入啊 你已经用了308MB流量，是正常了嘛
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/0983a3c7-c46b-4427-b437-ca9afe984003)
