### ISSUE TITLE
[BUG] 在linux中无法安装服务，错误提示：failed to install service with status126

### ISSUE THREAD

**Issue by phons** [clash-verge-rev/clash-verge-rev#1147]
### 问题描述 / Describe the bug

在linux系统下像开启tun模式需要安装服务，但是安装服务报错

### 复现步骤 / To Reproduce

使用的clash-verge_1.6.5_amd64.AppImage，双击运行

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

kali

### 日志 / Log

无

**Comment by phons** [comment]
<img width="394" alt="55125698ec470911ff48851ff42be635" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/26040869/8da76667-fa9d-408a-86fd-eb3ec474d71e">
<img width="394" alt="06198d9839c52a540e37074dfe0547e0" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/26040869/9908d159-8c79-4eb1-9ba5-22e921c40f45">

**Comment by xishang0128** [comment]
appimage就是这样子的,自行安装deb等
