### ISSUE TITLE
[Feature] 连接页面  增加一个显示进程数量

### ISSUE THREAD

**Issue by lbcake** [clash-verge-rev/clash-verge-rev#1152]
### 功能描述 / Feature description

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/26319880/75c4fef0-4792-4a3c-96b8-27de730c2661)

像cfw那样   显示出 进程的总数量     可以更好的知道情况

### 使用场景 / Use case

显示出 进程的总数量     可以更好的知道情况  后续选择性进行操作等。

**Comment by MystiPanda** [comment]
我觉得没用
