### ISSUE TITLE
[BUG] 编译错误信息：Unable to update https://github.com/Pylogmon/tauri?branch=1.x#9c0b6496

### ISSUE THREAD

**Issue by LinuxResearcher** [clash-verge-rev/clash-verge-rev#1154]
### 问题描述 / Describe the bug

编译时遇到错误，错误信息如下：
```
  Updating git repository `https://github.com/Pylogmon/tauri`

error: failed to get `tauri` as a dependency of package `clash-verge v1.6.5 (/home/arch/下载/clash-verge-rev-1.6.5/src-tauri)`

Caused by:

  failed to load source for dependency `tauri`

Caused by:
  Unable to update https://github.com/Pylogmon/tauri?branch=1.x#9c0b6496

Caused by:
  object not found - no match for id (9c0b64965560b28c3d06963494a3e0d2e1bae9f4); class=Odb (9); code=NotFound (-3)
       Error failed to build app: failed to build app
```
我如果把src-tauri/Cargo.lock中的tauri下载地址改为

```source = "git+https://github.com/Pylogmon/tauri?branch=1.x#8b66174f0d04d440d32a15ae52ed9771fedc005e"```

则能够正常编译。

### 复现步骤 / To Reproduce

1.在package.json中添加
```
,
  "pnpm": {
    "overrides": {
      "rollup": "npm:@rollup/wasm-node"
    }
  }
```
2.修改scripts/check.mjs
```
const META_ALPHA_MAP = {
  "win32-x64": "mihomo-windows-amd64-compatible",
  "win32-ia32": "mihomo-windows-386",
  "win32-arm64": "mihomo-windows-arm64",
  "darwin-x64": "mihomo-darwin-amd64-compatible",
  "darwin-arm64": "mihomo-darwin-arm64",
  "linux-x64": "mihomo-linux-amd64-compatible",
  "linux-ia32": "mihomo-linux-386",
  "linux-arm64": "mihomo-linux-arm64",
  "linux-arm": "mihomo-linux-armv7",
  "linux-riscv64": "mihomo-linux-riscv64",
-  "linux-loong64": "mihomo-linux-loong64",
+  "linux-loong64": "mihomo-linux-loong64-abi2",
};
```
3.git init
4.pnpm install
5.pnpm run check
6.cargo tauri build

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Loong Arch Linux

### 日志 / Log

[arch@XA61200 clash-verge-rev-1.6.5]$ git init
提示：使用 'master' 作为初始分支的名称。这个默认分支名称可能会更改。要在新仓库中
提示：配置使用初始分支名，并消除这条警告，请执行：
提示：
提示：	git config --global init.defaultBranch <名称>
提示：
提示：除了 'master' 之外，通常选定的名字有 'main'、'trunk' 和 'development'。
提示：可以通过以下命令重命名刚创建的分支：
提示：
提示：	git branch -m <name>
已初始化空的 Git 仓库于 /home/arch/下载/clash-verge-rev-1.6.5/.git/
[arch@XA61200 clash-verge-rev-1.6.5]$ pnpm install
 WARN  Ignoring broken lockfile at /home/arch/下载/clash-verge-rev-1.6.5: Lockfile /home/arch/下载/clash-verge-rev-1.6.5/pnpm-lock.yaml not compatible with current pnpm
 WARN  GET https://registry.npmjs.org/react-error-boundary error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/undici-types error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/tunnel error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@babel%2Ftraverse error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@babel%2Fplugin-syntax-private-property-in-object error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@babel%2Fparser error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@babel%2Fhelpers error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/globals error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/micromark-util-symbol error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
Packages: +522
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 555, reused 516, downloaded 6, added 522, done

> clash-verge@1.6.5 prepare /home/arch/下载/clash-verge-rev-1.6.5
> husky install

husky - Git hooks installed

dependencies:
+ @dnd-kit/core 6.1.0
+ @dnd-kit/sortable 8.0.0
+ @dnd-kit/utilities 3.2.2
+ @emotion/react 11.11.4
+ @emotion/styled 11.11.5
+ @juggle/resize-observer 3.4.0
+ @mui/icons-material 5.15.19
+ @mui/lab 5.0.0-alpha.149 (5.0.0-alpha.170 is available)
+ @mui/material 5.15.19
+ @mui/x-data-grid 6.20.1 (7.6.2 is available)
+ @tauri-apps/api 1.5.6
+ @types/json-schema 7.0.15
+ ahooks 3.8.0
+ axios 1.7.2
+ dayjs 1.11.5 (1.11.11 is available)
+ i18next 23.11.5
+ lodash-es 4.17.21
+ meta-json-schema 1.18.5-alpha4
+ monaco-editor 0.49.0
+ monaco-yaml 5.2.0
+ nanoid 5.0.7
+ react 18.3.1
+ react-dom 18.3.1
+ react-error-boundary 3.1.4 (4.0.13 is available)
+ react-hook-form 7.51.5
+ react-i18next 13.5.0 (14.1.2 is available)
+ react-markdown 9.0.1
+ react-router-dom 6.23.1
+ react-transition-group 4.4.5
+ react-virtuoso 4.7.11
+ recoil 0.7.7
+ swr 1.3.0 (2.2.5 is available)
+ tar 6.2.1 (7.2.0 is available)
+ types-pac 1.0.2

devDependencies:
+ @actions/github 5.1.1 (6.0.0 is available)
+ @tauri-apps/cli 1.5.14
+ @types/fs-extra 9.0.13 (11.0.4 is available)
+ @types/js-cookie 3.0.6
+ @types/lodash-es 4.17.12
+ @types/react 18.3.3
+ @types/react-dom 18.3.0
+ @types/react-transition-group 4.4.10
+ @vitejs/plugin-legacy 5.4.1
+ @vitejs/plugin-react 4.3.0
+ adm-zip 0.5.14
+ cross-env 7.0.3
+ fs-extra 11.2.0
+ https-proxy-agent 5.0.1 (7.0.4 is available)
+ husky 7.0.4 (9.0.11 is available)
+ node-fetch 3.3.2
+ prettier 2.8.8 (3.3.1 is available)
+ pretty-quick 3.3.1 (4.0.0 is available)
+ sass 1.77.4
+ terser 5.31.1
+ typescript 5.4.5
+ vite 5.2.13
+ vite-plugin-monaco-editor 1.1.0
+ vite-plugin-svgr 4.2.0

The dependency was already listed in devDependencies.
If you want to make it a prod dependency, then move it manually.

Done in 1m 32s
[arch@XA61200 clash-verge-rev-1.6.5]$ pnpm run check

> clash-verge@1.6.5 check /home/arch/下载/clash-verge-rev-1.6.5
> node scripts/check.mjs

Latest alpha version: alpha-0d4e57c
Latest release version: v1.18.5
[INFO]: download finished "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-loong64-abi2-alpha-0d4e57c.gz"
[INFO]: "clash-meta-alpha" gunzip finished
[INFO]: "clash-meta-alpha" chmod binary finished
[INFO]: download finished "https://github.com/MetaCubeX/mihomo/releases/download/v1.18.5/mihomo-linux-loong64-abi2-v1.18.5.gz"
[INFO]: "clash-meta" gunzip finished
[INFO]: "clash-meta" chmod binary finished
[INFO]: download finished "https://github.com/clash-verge-rev/clash-verge-service/releases/download/loongarch64-unknown-linux-gnu/install-service"
[INFO]: install-service finished
[INFO]: download finished "https://github.com/clash-verge-rev/clash-verge-service/releases/download/loongarch64-unknown-linux-gnu/clash-verge-service"
[INFO]: clash-verge-service finished
[INFO]: download finished "https://github.com/clash-verge-rev/clash-verge-service/releases/download/loongarch64-unknown-linux-gnu/uninstall-service"
[INFO]: uninstall-service finished
[INFO]: download finished "https://github.com/clash-verge-rev/set-dns-script/releases/download/script/set_dns.sh"
[INFO]: set_dns.sh finished
[INFO]: download finished "https://github.com/clash-verge-rev/set-dns-script/releases/download/script/unset_dns.sh"
[INFO]: unset_dns.sh finished
[INFO]: download finished "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
[INFO]: Country.mmdb finished
[INFO]: download finished "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
[INFO]: geosite.dat finished
[INFO]: "/home/arch/下载/clash-verge-rev-1.6.5/src-tauri/resources/clash-verge-service" chmod finished
[INFO]: "/home/arch/下载/clash-verge-rev-1.6.5/src-tauri/resources/install-service" chmod finished
[INFO]: "/home/arch/下载/clash-verge-rev-1.6.5/src-tauri/resources/uninstall-service" chmod finished
[INFO]: download finished "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
[INFO]: geoip.dat finished
[arch@XA61200 clash-verge-rev-1.6.5]$ cargo tauri build
     Running beforeBuildCommand `pnpm run web:build`

> clash-verge@1.6.5 web:build /home/arch/下载/clash-verge-rev-1.6.5
> tsc && vite build

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
vite v5.2.13 building for production...
✓ 14686 modules transformed.
../dist/assets/azcli-legacy--SYhQ320.js                 1.19 kB │ gzip:     0.51 kB
../dist/assets/javascript-legacy-B1icKF7n.js            1.30 kB │ gzip:     0.68 kB
../dist/assets/ini-legacy-B68U7Hkr.js                   1.44 kB │ gzip:     0.72 kB
../dist/assets/csp-legacy-ePkp0E2s.js                   1.76 kB │ gzip:     0.71 kB
../dist/assets/pla-legacy-DmR2AFzX.js                   2.02 kB │ gzip:     0.83 kB
../dist/assets/scheme-legacy-BZUETqBd.js                2.11 kB │ gzip:     1.00 kB
../dist/assets/flow9-legacy-wNjdBBbf.js                 2.15 kB │ gzip:     1.03 kB
../dist/assets/sb-legacy-Bcb-YOF1.js                    2.17 kB │ gzip:     1.01 kB
../dist/assets/bat-legacy-82ve9yKU.js                   2.19 kB │ gzip:     1.04 kB
../dist/assets/dockerfile-legacy--eYKEN7p.js            2.21 kB │ gzip:     0.85 kB
../dist/assets/pascaligo-legacy-BYcwfaNh.js             2.34 kB │ gzip:     1.09 kB
../dist/assets/lua-legacy-CEpbBHlL.js                   2.46 kB │ gzip:     1.10 kB
../dist/assets/cameligo-legacy-DEWSff6f.js              2.53 kB │ gzip:     1.14 kB
../dist/assets/graphql-legacy-Xdl2RQni.js               2.60 kB │ gzip:     1.20 kB
../dist/assets/objective-c-legacy-blNDlPan.js           2.74 kB │ gzip:     1.24 kB
../dist/assets/xml-legacy-D2pc24lC.js                   2.75 kB │ gzip:     1.14 kB
../dist/assets/lexon-legacy-ClVIfTje.js                 2.78 kB │ gzip:     1.11 kB
../dist/assets/bicep-legacy-DPxJZC_b.js                 2.83 kB │ gzip:     1.11 kB
../dist/assets/sparql-legacy-Ps73agVf.js                2.89 kB │ gzip:     1.34 kB
../dist/assets/mips-legacy-Cn071s6b.js                  2.92 kB │ gzip:     1.26 kB
../dist/assets/go-legacy-6FkeAlL1.js                    3.00 kB │ gzip:     1.32 kB
../dist/assets/sophia-legacy-DKy-Iy07.js                3.10 kB │ gzip:     1.38 kB
../dist/assets/typespec-legacy-Cjhx1Spv.js              3.11 kB │ gzip:     1.24 kB
../dist/assets/m3-legacy-DLKb735h.js                    3.16 kB │ gzip:     1.49 kB
../dist/assets/qsharp-legacy-DMoPUjvq.js                3.28 kB │ gzip:     1.54 kB
../dist/assets/fsharp-legacy-D316rMwu.js                3.32 kB │ gzip:     1.49 kB
../dist/assets/pascal-legacy-4c6bLdjP.js                3.34 kB │ gzip:     1.58 kB
../dist/assets/shell-legacy-Cx0n9cmz.js                 3.41 kB │ gzip:     1.39 kB
../dist/assets/r-legacy-DOACZhPk.js                     3.47 kB │ gzip:     1.46 kB
../dist/assets/java-legacy-BY76Y2H6.js                  3.56 kB │ gzip:     1.57 kB
../dist/assets/powershell-legacy-BzXgY-hm.js            3.61 kB │ gzip:     1.55 kB
../dist/assets/cypher-legacy-3_-sjjVA.js                3.73 kB │ gzip:     1.61 kB
../dist/assets/kotlin-legacy-DOe8kfmk.js                3.78 kB │ gzip:     1.65 kB
../dist/assets/redis-legacy-CezfYskY.js                 3.90 kB │ gzip:     1.66 kB
../dist/assets/tcl-legacy-CZbq5CKI.js                   3.91 kB │ gzip:     1.54 kB
../dist/assets/coffee-legacy-Cvw-6k5K.js                3.93 kB │ gzip:     1.49 kB
../dist/assets/hcl-legacy-DcYzvDNk.js                   3.93 kB │ gzip:     1.67 kB
../dist/assets/python-legacy-mn6a5hBG.js                3.96 kB │ gzip:     1.76 kB
../dist/assets/markdown-legacy-njqbWy2u.js              4.15 kB │ gzip:     1.56 kB
../dist/assets/less-legacy-D_cd8YRo.js                  4.24 kB │ gzip:     1.59 kB
../dist/assets/restructuredtext-legacy-BrtXrZHA.js      4.24 kB │ gzip:     1.55 kB
../dist/assets/apex-legacy-PD6XWPv-.js                  4.29 kB │ gzip:     1.94 kB
../dist/assets/liquid-legacy-mbDr_-v9.js                4.30 kB │ gzip:     1.83 kB
../dist/assets/yaml-legacy-zb45JLZT.js                  4.35 kB │ gzip:     1.68 kB
../dist/assets/rust-legacy-DkS0Q09z.js                  4.50 kB │ gzip:     2.00 kB
../dist/assets/dart-legacy-BiV6SxOi.js                  4.59 kB │ gzip:     1.82 kB
../dist/assets/css-legacy-DWdnFMRF.js                   4.85 kB │ gzip:     1.56 kB
../dist/assets/csharp-legacy-fd-SKRRs.js                4.86 kB │ gzip:     1.91 kB
../dist/assets/pug-legacy-DdTWwZso.js                   5.17 kB │ gzip:     1.83 kB
../dist/assets/mdx-legacy-BugeGnMZ.js                   5.19 kB │ gzip:     1.62 kB
../dist/assets/msdax-legacy-DhruNd1w.js                 5.25 kB │ gzip:     2.14 kB
../dist/assets/swift-legacy-BG0JVN1P.js                 5.25 kB │ gzip:     2.20 kB
../dist/assets/html-legacy-BZGS3k7I.js                  5.38 kB │ gzip:     1.57 kB
../dist/assets/cpp-legacy-CmMnJQ5R.js                   5.64 kB │ gzip:     2.26 kB
../dist/assets/ecl-legacy-Cyf0JL93.js                   5.68 kB │ gzip:     2.43 kB
../dist/assets/typescript-legacy-B9pqG3XD.js            5.74 kB │ gzip:     2.32 kB
../dist/assets/vb-legacy-D-SjsEdD.js                    6.13 kB │ gzip:     2.24 kB
../dist/assets/twig-legacy-DJAV53iE.js                  6.32 kB │ gzip:     1.71 kB
../dist/assets/scss-legacy-Ca6C3RZX.js                  6.75 kB │ gzip:     1.92 kB
../dist/assets/handlebars-legacy-WUkEJzVa.js            7.12 kB │ gzip:     1.78 kB
../dist/assets/julia-legacy-C0LQMlHX.js                 7.44 kB │ gzip:     2.81 kB
../dist/assets/scala-legacy-BJ1__GMz.js                 7.66 kB │ gzip:     2.27 kB
../dist/assets/st-legacy-ClFNB2Ax.js                    7.74 kB │ gzip:     2.42 kB
../dist/assets/systemverilog-legacy-D8K5uavO.js         7.94 kB │ gzip:     2.92 kB
../dist/assets/postiats-legacy-BTe8q32C.js              8.20 kB │ gzip:     2.60 kB
../dist/assets/php-legacy-B_k75kop.js                   8.37 kB │ gzip:     2.24 kB
../dist/assets/wgsl-legacy-CusjMbY-.js                  8.37 kB │ gzip:     2.79 kB
../dist/assets/perl-legacy-DBk5-6HM.js                  8.60 kB │ gzip:     3.28 kB
../dist/assets/ruby-legacy-DNq1i_QF.js                  8.85 kB │ gzip:     2.74 kB
../dist/assets/razor-legacy-DyO6bDJJ.js                 9.13 kB │ gzip:     2.46 kB
../dist/assets/protobuf-legacy-Bld_73Tl.js              9.38 kB │ gzip:     2.24 kB
../dist/assets/clojure-legacy-BF7HLhpr.js               9.98 kB │ gzip:     3.78 kB
../dist/assets/elixir-legacy-CKIldoo_.js               10.60 kB │ gzip:     2.69 kB
../dist/assets/sql-legacy-Ckflczp0.js                  10.64 kB │ gzip:     4.03 kB
../dist/assets/mysql-legacy-8As4aiPM.js                11.61 kB │ gzip:     4.24 kB
../dist/assets/redshift-legacy-Bm14qMg_.js             12.14 kB │ gzip:     4.50 kB
../dist/assets/pgsql-legacy-Dce-DlCL.js                13.80 kB │ gzip:     4.67 kB
../dist/assets/abap-legacy-DRMP8M_-.js                 14.50 kB │ gzip:     5.52 kB
../dist/assets/freemarker2-legacy-B6zDMYuV.js          16.43 kB │ gzip:     4.27 kB
../dist/assets/powerquery-legacy-BR7JnoBy.js           17.28 kB │ gzip:     5.05 kB
../dist/assets/solidity-legacy-C05KVeN_.js             18.94 kB │ gzip:     4.63 kB
../dist/assets/tsMode-legacy-VGq9q4sA.js               22.61 kB │ gzip:     6.29 kB
../dist/assets/cssMode-legacy-B9aiMd84.js              32.74 kB │ gzip:     8.78 kB
../dist/assets/htmlMode-legacy-DvvU4gKr.js             33.26 kB │ gzip:     8.90 kB
../dist/assets/polyfills-legacy-Dnmj0RMH.js            33.31 kB │ gzip:    13.61 kB
../dist/assets/jsonMode-legacy-C274TI-w.js             38.65 kB │ gzip:    10.97 kB
../dist/assets/index-legacy-DYBbXla0.js             5,117.71 kB │ gzip: 1,330.77 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
../dist/index.html                               3.17 kB │ gzip:     1.28 kB
../dist/assets/logo-yCaNqQic.ico                48.58 kB
../dist/assets/codicon-B16ygVZF.ttf             80.19 kB
../dist/assets/Twemoji.Mozilla-Cf7TwsdM.ttf  1,454.53 kB
../dist/assets/index-C14Vm9_t.css              131.86 kB │ gzip:    21.21 kB
../dist/assets/azcli-CIONJYq1.js                 1.09 kB │ gzip:     0.46 kB
../dist/assets/javascript-zbtG3T9e.js            1.19 kB │ gzip:     0.62 kB
../dist/assets/ini-BscO_0vf.js                   1.35 kB │ gzip:     0.67 kB
../dist/assets/csp-BK5qlsQ9.js                   1.67 kB │ gzip:     0.67 kB
../dist/assets/pla-BUVXxyGx.js                   1.93 kB │ gzip:     0.79 kB
../dist/assets/scheme-DkJ87xtR.js                2.01 kB │ gzip:     0.95 kB
../dist/assets/flow9-BKFjllYO.js                 2.06 kB │ gzip:     0.98 kB
../dist/assets/sb-5vPrUWN-.js                    2.08 kB │ gzip:     0.96 kB
../dist/assets/bat-C9Lf3IiR.js                   2.09 kB │ gzip:     1.00 kB
../dist/assets/dockerfile-fYe1jRYc.js            2.12 kB │ gzip:     0.81 kB
../dist/assets/pascaligo-Dcwo06z5.js             2.25 kB │ gzip:     1.05 kB
../dist/assets/lua-DLZgaSX1.js                   2.37 kB │ gzip:     1.06 kB
../dist/assets/cameligo-v1zEsXLu.js              2.43 kB │ gzip:     1.10 kB
../dist/assets/graphql-k0EsSqLB.js               2.51 kB │ gzip:     1.16 kB
../dist/assets/objective-c-B_h_kxCB.js           2.65 kB │ gzip:     1.19 kB
../dist/assets/xml-DciMIjFo.js                   2.67 kB │ gzip:     1.10 kB
../dist/assets/lexon-BXW1vGDt.js                 2.68 kB │ gzip:     1.07 kB
../dist/assets/sparql-BTJymgeb.js                2.80 kB │ gzip:     1.30 kB
../dist/assets/bicep-Ce1Avi-y.js                 2.81 kB │ gzip:     1.11 kB
../dist/assets/mips-DcG9r2vI.js                  2.83 kB │ gzip:     1.21 kB
../dist/assets/go-DzbHtIm4.js                    2.90 kB │ gzip:     1.28 kB
../dist/assets/sophia-z0tjJxhY.js                3.01 kB │ gzip:     1.34 kB
../dist/assets/m3-CLtYU2dl.js                    3.06 kB │ gzip:     1.44 kB
../dist/assets/typespec-C3XU_mKp.js              3.10 kB │ gzip:     1.23 kB
../dist/assets/qsharp-BHSA_OC9.js                3.18 kB │ gzip:     1.49 kB
../dist/assets/fsharp-ETo-tsZt.js                3.23 kB │ gzip:     1.45 kB
../dist/assets/pascal-Bc-8SB3K.js                3.24 kB │ gzip:     1.53 kB
../dist/assets/shell-BHhUv290.js                 3.32 kB │ gzip:     1.34 kB
../dist/assets/r-DBvxNhD8.js                     3.38 kB │ gzip:     1.42 kB
../dist/assets/java-CtY9ZHW8.js                  3.47 kB │ gzip:     1.53 kB
../dist/assets/powershell-CCS0rx-A.js            3.52 kB │ gzip:     1.51 kB
../dist/assets/cypher-Bl5_yQjz.js                3.63 kB │ gzip:     1.56 kB
../dist/assets/kotlin-DTDxWyre.js                3.69 kB │ gzip:     1.61 kB
../dist/assets/redis-mBNZiS5I.js                 3.80 kB │ gzip:     1.62 kB
../dist/assets/tcl-CjHYkh5E.js                   3.82 kB │ gzip:     1.50 kB
../dist/assets/coffee-DNMvp8RP.js                3.84 kB │ gzip:     1.45 kB
../dist/assets/hcl-Cq9v6if3.js                   3.84 kB │ gzip:     1.62 kB
../dist/assets/python-BUDxUi91.js                3.88 kB │ gzip:     1.73 kB
../dist/assets/markdown-7fQo6M4U.js              4.03 kB │ gzip:     1.52 kB
../dist/assets/restructuredtext-45Xf76JB.js      4.14 kB │ gzip:     1.50 kB
../dist/assets/less-b9nCQjlL.js                  4.15 kB │ gzip:     1.55 kB
../dist/assets/apex-CW6wsJgM.js                  4.20 kB │ gzip:     1.90 kB
../dist/assets/liquid-CszaSsp1.js                4.24 kB │ gzip:     1.79 kB
../dist/assets/yaml-CntGJGX5.js                  4.27 kB │ gzip:     1.65 kB
../dist/assets/rust-BChN5uNh.js                  4.41 kB │ gzip:     1.95 kB
../dist/assets/dart-BVA93hyX.js                  4.50 kB │ gzip:     1.78 kB
../dist/assets/css-D9urSYBf.js                   4.76 kB │ gzip:     1.52 kB
../dist/assets/csharp-BoWmgZhk.js                4.77 kB │ gzip:     1.87 kB
../dist/assets/pug-Dg4O54Js.js                   5.07 kB │ gzip:     1.78 kB
../dist/assets/mdx-DftLDQC-.js                   5.13 kB │ gzip:     1.58 kB
../dist/assets/msdax-DN__iVzl.js                 5.16 kB │ gzip:     2.09 kB
../dist/assets/html-BVI4wmTf.js                  5.29 kB │ gzip:     1.53 kB
../dist/assets/swift-BwlyOzQq.js                 5.42 kB │ gzip:     2.20 kB
../dist/assets/cpp-DEDKHd-B.js                   5.55 kB │ gzip:     2.22 kB
../dist/assets/ecl-Bxo8QmCt.js                   5.59 kB │ gzip:     2.38 kB
../dist/assets/typescript-7_hguQdf.js            5.67 kB │ gzip:     2.30 kB
../dist/assets/vb-BjPEumh4.js                    6.04 kB │ gzip:     2.19 kB
../dist/assets/twig-CmYTg8Iu.js                  6.22 kB │ gzip:     1.66 kB
../dist/assets/scss-BHRp1i8N.js                  6.66 kB │ gzip:     1.88 kB
../dist/assets/handlebars-DDHPXksd.js            7.05 kB │ gzip:     1.75 kB
../dist/assets/julia-DOes61nN.js                 7.34 kB │ gzip:     2.77 kB
../dist/assets/scala-BQOorN7X.js                 7.56 kB │ gzip:     2.22 kB
../dist/assets/st-DZS1F9ME.js                    7.64 kB │ gzip:     2.38 kB
../dist/assets/systemverilog-DJsb8r0W.js         7.85 kB │ gzip:     2.88 kB
../dist/assets/wgsl-C5rqL2_T.js                  7.89 kB │ gzip:     2.92 kB
../dist/assets/postiats-DSt55phJ.js              8.10 kB │ gzip:     2.55 kB
../dist/assets/php-CH5O-_gG.js                   8.27 kB │ gzip:     2.20 kB
../dist/assets/perl-BnGpdHsN.js                  8.50 kB │ gzip:     3.24 kB
../dist/assets/ruby-BUaz8-i0.js                  8.75 kB │ gzip:     2.70 kB
../dist/assets/razor-0zeqB2f9.js                 9.05 kB │ gzip:     2.42 kB
../dist/assets/protobuf-XSUI3tfN.js              9.29 kB │ gzip:     2.20 kB
../dist/assets/clojure-DgNu_ptH.js               9.89 kB │ gzip:     3.74 kB
../dist/assets/elixir-BbUoe7nZ.js               10.50 kB │ gzip:     2.65 kB
../dist/assets/sql-BFyYaP5s.js                  10.54 kB │ gzip:     3.98 kB
../dist/assets/mysql-05d2lfAy.js                11.52 kB │ gzip:     4.19 kB
../dist/assets/redshift-gtd9hS2x.js             12.05 kB │ gzip:     4.46 kB
../dist/assets/pgsql-DfVleuq_.js                13.71 kB │ gzip:     4.63 kB
../dist/assets/abap-DR3EPHcA.js                 14.41 kB │ gzip:     5.47 kB
../dist/assets/freemarker2-eJ0-38mi.js          16.68 kB │ gzip:     4.28 kB
../dist/assets/powerquery-2KNS9mh4.js           17.19 kB │ gzip:     5.00 kB
../dist/assets/solidity-BFcLIl1x.js             18.84 kB │ gzip:     4.58 kB
../dist/assets/tsMode-Cxj6vk-W.js               22.57 kB │ gzip:     6.46 kB
../dist/assets/cssMode-BzYLoNDs.js              33.63 kB │ gzip:     8.89 kB
../dist/assets/htmlMode-CoV8XmGX.js             34.19 kB │ gzip:     9.01 kB
../dist/assets/jsonMode-Cb37vUR_.js             39.71 kB │ gzip:    11.09 kB
../dist/assets/polyfills-BtSuengk.js           113.04 kB │ gzip:    44.62 kB
../dist/assets/index-Dg_qEEeA.js             5,060.30 kB │ gzip: 1,358.21 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 2m 28s
    Updating crates.io index
    Updating git repository `https://github.com/Pylogmon/tauri`
error: failed to get `tauri` as a dependency of package `clash-verge v1.6.5 (/home/arch/下载/clash-verge-rev-1.6.5/src-tauri)`

Caused by:
  failed to load source for dependency `tauri`

Caused by:
  Unable to update https://github.com/Pylogmon/tauri?branch=1.x#9c0b6496

Caused by:
  object not found - no match for id (9c0b64965560b28c3d06963494a3e0d2e1bae9f4); class=Odb (9); code=NotFound (-3)
       Error failed to build app: failed to build app

**Comment by MystiPanda** [comment]
fixed
