### ISSUE TITLE
[Feature] 在订阅中添加自由排序功能

### ISSUE THREAD

**Issue by henrysion** [clash-verge-rev/clash-verge-rev#1156]
### 功能描述 / Feature description

在订阅中可以使用鼠标拖动任意订阅文件，使其改变排序。

### 使用场景 / Use case

在拥有多个订阅文件的情况下将常用的订阅文件按优先等级自由排序。

**Comment by dongchengjie** [comment]
现在就可以排序，那6个点的图标就是

**Comment by AnyWAT** [comment]
至少V1.6.5可以自由拖动。
