### ISSUE TITLE
[BUG] deepin 20.9 社区版无法打开面板，没办法设置

### ISSUE THREAD

**Issue by githkm** [clash-verge-rev/clash-verge-rev#1158]
### 问题描述 / Describe the bug

你好，我使用的是deepin 2023  深度社区版2023系统，安装后无法打开面板，不能进行后续的设置，可以适配下吗？非常感谢。

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

deepin 2023

### 日志 / Log

无

**Comment by githkm** [comment]
更正下，是deepin 20.9

**Comment by MystiPanda** [comment]
麻烦终端启动提供报错日志

**Comment by githkm** [comment]
Downloads$ ./clash-verge_1.6.5_amd64.AppImage 

(clash-verge:6045): GLib-GObject-CRITICAL **: 22:19:56.995: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(clash-verge:6045): dbind-WARNING **: 22:19:57.006: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Could not determine the accessibility bus address

(clash-verge:6045): GLib-GObject-WARNING **: 22:19:57.494: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'

(WebKitWebProcess:6100): GLib-GObject-CRITICAL **: 22:19:57.670: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(WebKitWebProcess:6100): GLib-GObject-WARNING **: 22:19:57.967: g_object_set_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".

**Comment by MystiPanda** [comment]
不是有deb吗，用什么appimage

**Comment by githkm** [comment]
~$ clash-verge 

(clash-verge:20810): dbind-WARNING **: 22:42:06.074: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Could not determine the accessibility bus address

(clash-verge:20810): GLib-GObject-WARNING **: 22:42:06.286: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'

(WebKitWebProcess:20855): GLib-GObject-WARNING **: 22:42:06.537: g_object_set_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".

**Comment by wanstu** [comment]
这个问题怎么解决的
我也遇到了

```bash
wanstu@wanstu-PC:~$ clash-verge

(clash-verge:5294): GLib-GObject-CRITICAL **: 09:06:34.709: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(clash-verge:5294): GLib-GObject-CRITICAL **: 09:06:34.709: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(clash-verge:5294): dbind-WARNING **: 09:06:34.716: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
[Config] Initial config
[Config] 生成运行时配置成功
[Config] 开始验证配置
[Config] 生成临时配置文件用于验证
[Config] 开始验证配置文件: /home/wanstu/.local/share/io.github.clash-verge-rev.clash-verge-rev/clash-verge-check.yaml
[Config] 使用内核: verge-mihomo
[Config] 验证目录: /home/wanstu/.local/share/io.github.clash-verge-rev.clash-verge-rev
[Config] -------- 验证结果 --------
[Config] 验证成功
[Config] -------- 验证结束 --------
[Config] 配置验证成功
[Core] 服务可用，直接使用服务模式
[Core] Running core by service
[Window] Creating window
[Window] Creating new application window

(WebKitWebProcess:5400): GLib-GObject-CRITICAL **: 09:06:35.153: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(WebKitWebProcess:5400): GLib-GObject-CRITICAL **: 09:06:35.153: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed
[Window] Window created successfully
[Window] 标记前端UI已准备就绪，开始处理启动错误队列
[Timer] Initializing timer...
[System] Initial hotkeys
[Hotkey] Initializing hotkeys with enable: true
[Hotkey] No hotkeys configured
[Hotkey] Attempting to register hotkey: Control+Q for function: quit
[Hotkey] Successfully registered hotkey Control+Q for quit
[Hotkey] Unregister hotkey Control+Q

(clash-verge:5294): libayatana-appindicator-WARNING **: 09:06:35.901: Unable to connect to the Notification Watcher: GDBus.Error:org.deepin.dde.DBus.Error.Unnamed: notifier item has been registered
```
