### ISSUE TITLE
[BUG] 這個「代理繞過」或者「PAC模式」究竟有沒有生效

### ISSUE THREAD

**Issue by YheonYeung** [clash-verge-rev/clash-verge-rev#1159]
### 一開始用PAC模式看B站直播，直播間讀得很慢。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/63342274/8f258d3e-4f28-44bf-a571-f44648525e31)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/63342274/bd990068-d995-4771-93b6-c3badc4d3173)

### 然後加了繞過。又有新問題。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/63342274/df604d57-5fdf-4c51-bb68-4099e507a845)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/63342274/62bb9cbe-164e-4be6-867e-6642db5cfd5a)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/63342274/82e736a6-6fb8-43f8-90b6-0d95c4407906)
### 這個訂閱是有幾個bilibili的
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/63342274/f18654e5-d9e4-4b12-8819-182bccaf687c)

### 還有，PAC模式剛才連圖片都沒成功傳到github。discord更不用說，PAC模式根本打不開。
根本不能正常使用

### 复现步骤 / To Reproduce

代理繞過添加bilibili.com
或者使用PAC模式
看B站直播

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

不懂

**Comment by YheonYeung** [comment]
好撚巴閉？回應都唔撚回應，就直接關。你至少都教下我怎麼能正常用。

**Comment by lbcake** [comment]
> 好撚巴閉？回應都唔撚回應，就直接關。你至少都教下我怎麼能正常用。

香港人吗？  说话客气点

**Comment by YheonYeung** [comment]
> > 好撚巴閉？回應都唔撚回應，就直接關。你至少都教下我怎麼能正常用。
> 
> 香港人吗？ 说话客气点

一定要香港人先畀講廣東話？我有使用問題，不單止沒有解決。一句不回就直接關。至少幫我這種白痴講一下怎麼解決吧。

**Comment by MystiPanda** [comment]
没有任何日志我不可能给你解决任何问题，提交 issue 的注意事项写的很明白你需要先看文档，否则我会直接关闭 issue，但是你所说的内容明显没有看过文档，所以我认为这是一个不符合规范的 issue 我把它直接关闭我觉得没有任何问题。
