### ISSUE TITLE
[Feature]protable安装包可以把配置文件放在原来的位置吗

### ISSUE THREAD

**Issue by limitwhy** [clash-verge-rev/clash-verge-rev#116]
### Is your feature request related to a problem? Please describe.

不然每次更新我哦都要手动复制配置文件

### Describe the solution you'd like

把配置文件放在原来的位置

### Describe alternatives you've considered

无

**Comment by MystiPanda** [comment]
把.config文件夹删了就可以

**Comment by MystiPanda** [comment]
便携版和安装版没有任何区别，软件是用过检测软件所在目录有没有.config/PORTABLE文件来决定是否把配置文件放在软件所在目录的
