### ISSUE TITLE
[BUG] linux版的clash verge 的hysteria2 节点无法连接

### ISSUE THREAD

**Issue by cksdxz1007** [clash-verge-rev/clash-verge-rev#1164]
### 描述

在Linux版的Clash Verge中，hysteria2节点无法连接。相同的配置在Windows版的Clash Verge中工作正常。

### 环境

- **操作系统:** Ubuntu 22.04
- **Clash Verge版本:** 1.6.5
- **Clash Meta内核版本:** 1.18.5 meta

### 复现步骤 / To Reproduce

![unknown_001](https://github.com/clash-verge-rev/clash-verge-rev/assets/21142070/38334db4-d682-4012-84c4-b3459ef405b0)

### 重现步骤

1. 在Ubuntu 22.04上配置Clash Verge中的hysteria2节点。
2. 尝试使用配置的节点进行连接。
3. 注意到连接失败。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

ubuntu 22.04

### 预期行为

hysteria2节点应该能够成功连接，正如在相同网络环境下Windows版的Clash Verge中一样。

### 实际行为

在Linux版的Clash Verge中，hysteria2节点连接失败。

### 其他信息

- 相同的hysteria2节点配置在相同网络环境下的Windows版Clash Verge中工作正常。
- 问题似乎仅出现在Linux版本中。

**Comment by PuerNya** [comment]
@cksdxz1007 请提供日志

**Comment by wonfen** [comment]
感觉是你的节点问题；可以用项目推荐的机场试试，他家都是hy2节点
