### ISSUE TITLE
[BUG] TUN模式与ADGuard兼容性问题

### ISSUE THREAD

**Issue by z1298808165** [clash-verge-rev/clash-verge-rev#1166]
### 问题描述 / Describe the bug

开机自启或手动切换tun模式后ADGuard的广告拦截会失效，需要手动关闭再打开ADGuard的启用开关后 ADGuard的广告拦截功能才能再生效

### 复现步骤 / To Reproduce

1.ADGuard：开启开机自启、打开广告拦截器，clash-verge-rev：开启TUN模式、开启开机自启
2.重启电脑
3.访问有广告的网页

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

无

**Comment by z1298808165** [comment]
> 不懂原理就不要两个一起用，不就DNS劫持冲突嘛，还扯到兼容性上去了，咋不说把所有代理软件都开开生效的不是你想要的那个

哈哈哈，抱歉，可能描述有误，本意是看看有没有可能能解决这个问题~   一开始想将DNS的enable设置为false看看可不可行，但重新激活订阅后 当前的配置中DNS仍是true，无法设置为false，所以提了这个issues想请教下~

**Comment by z1298808165** [comment]
对了，如果ADGuard是后启动的，那么两个软件可以同时使用的，不会产生冲突

**Comment by z1298808165** [comment]
> TUN模式强制启用DNS，你如果想共存就想办法阻止AD的DNS劫持（只监听端口，不修改路由），并把配置中的DNS设置为AD监听的端口 或者把AD装到路由器里

好的好的，多谢！我之前想的是看能不能延迟ADGuard的自启，改变自启顺序😄

**Comment by Maasea** [comment]
**UPDATE**

adguard会通过local.adguard.org 插入js来注入页面。local.adguard.org 本质上并不是一个有效域名，adguard 通过劫持该域名来实现注入。但是该域名经过clash 后，可能会走代理、或是被fake-ip影响无法正确注入。

所以可以添加以下配置来使得 local.adguard.org 的注入保持生效，

1. 在fake-ip中增加过滤
```YAML
dns:
  # 你的配置
  fake-ip-filter:
    - 'local.adguard.org'  # 增加 +
```

2. 在分流中增加规则

```YAML
- DOMAIN,local.adguard.org,DIRECT
```

关于 local.adguard.org 可以查看 [官方说明](https://adguard.com/kb/zh-CN/general/https-filtering/local-adguard-com-domain/)

----


~~我最近也在解决这个问题。~~

~~总的来说有两种方式：~~
~~- 使用 Adguard 的代理模式，将所有流量通过代理的方式转发过滤，而不是劫持流量。~~
~~- 强制 Adguard 和 clash 的启动顺序。~~

~~## 使用 Adguard 代理模式~~

~~**开启方法**：~~

~~1. 打开 Adguard -> 设置 -> 网络~~
~~2. 找到 流量过滤 一栏，将 启用流量过滤 取消勾选，将 Adguard 作为 HTTP 代理勾选上（根据提示重启系统）~~
~~3. 打开 window 系统的代理服务器设置 (127.0.0.1:49037)~~
~~4. Clash 只开启 TUN 模式，不要开启系统代理（为了防止clash的系统代理地址覆盖 Adgaurd 地址）~~

~~**优点**：~~

~~1. 对于clash配置的侵入性小，兼容性好，clash 和 adguard 均独立运行没有冲突~~
~~2. 配置和操作简单~~

~~**缺点**：~~

~~1. 部分不遵循系统代理的程序，无法经过 Adguard （但考虑到 Adgaurd 大多为浏览器过滤广告，影响不大）~~
~~2. 配置完系统代理后，如果 Adguard 启动失败可能造成无法访问互联网的情况（实际情况下很少发生）~~
~~3. 所有经过Adguard 代理的程序，PROCESS-NAME 都会变成 Adgaurd，这意味着基于PROCESS-NAME的规则会失效~~

~~> 也可以为需要去广告的应用单独配置代理，比如配合 Proxifier~~
~~> 没有将 Adguard 设置为 clash 前置代理的原因是：需要修改大量配置文件，使配置看起来相当复杂以及一些其他的兼容性问题~~

~~## 配置 clash 和 Adgaurd 启动顺序~~

~~**开启方法**：~~

~~这里我是将 clash 内核作为系统服务运行，所以可以用 sc 命令将 clash 作为 adgaurdSvc 的依赖，这样adguardSvc 每次启动都会依赖于 clash~~

~~**优点**：~~

~~1. 由于没有在系统层配置代理服务器，所以adguard 启动失败也不会造成网络中断~~
~~2. 只要 Adguard 中配置的应用都可以进行广告过滤~~

~~**缺点**：~~

~~1. 属于非常规兼容手段，当同时开启 Adgaurd 和 clash TUN 流量劫持时，会出现冲突（大量端口的监听和转发）~~
~~2. 配置麻烦~~
~~3. 操作麻烦，每次重启Clash 内核都会重启 AdguardSvc （因为 AdguardSvc  依赖 Clash）~~

~~> 不使用延迟启动是因为延迟启动的时机很迷，导致刚开机浏览时会出现广告~~

**Comment by z1298808165** [comment]
> 我最近也在解决这个问题。
> 
> 总的来说有两种方式：
> 
> * 使用 Adguard 的代理模式，将所有流量通过代理的方式转发过滤，而不是劫持流量。
> * 强制 Adguard 和 clash 的启动顺序。
> 
> ## 使用 Adguard 代理模式
> **开启方法**：
> 
> 1. 打开 Adguard -> 设置 -> 网络
> 2. 找到 流量过滤 一栏，将 启用流量过滤 取消勾选，将 Adguard 作为 HTTP 代理勾选上（根据提示重启系统）
> 3. 打开 window 系统的代理服务器设置 (127.0.0.1:49037)
> 4. Clash 只开启 TUN 模式，不要开启系统代理（为了防止clash的系统代理地址覆盖 Adgaurd 地址）
> 
> **优点**：
> 
> 1. 对于clash配置的侵入性小，兼容性好，clash 和 adguard 均独立运行没有冲突
> 2. 配置和操作简单
> 
> **缺点**：
> 
> 1. 部分不遵循系统代理的程序，无法经过 Adguard （但考虑到 Adgaurd 大多为浏览器过滤广告，影响不大）
> 2. 配置完系统代理后，如果 Adguard 启动失败可能造成无法访问互联网的情况（实际情况下很少发生）
> 3. 所有经过Adguard 代理的程序，PROCESS-NAME 都会变成 Adgaurd，这意味着基于PROCESS-NAME的规则会失效
> 
> > 也可以为需要去广告的应用单独配置代理，比如配合 Proxifier
> > 没有将 Adguard 设置为 clash 前置代理的原因是：需要修改大量配置文件，使配置看起来相当复杂以及一些其他的兼容性问题
> 
> ## 配置 clash 和 Adgaurd 启动顺序
> **开启方法**：
> 
> 这里我是将 clash 内核作为系统服务运行，所以可以用 sc 命令将 clash 作为 adgaurdSvc 的依赖，这样adguardSvc 每次启动都会依赖于 clash
> 
> **优点**：
> 
> 1. 由于没有在系统层配置代理服务器，所以adguard 启动失败也不会造成网络中断
> 2. 只要 Adguard 中配置的应用都可以进行广告过滤
> 
> **缺点**：
> 
> 1. 属于非常规兼容手段，当同时开启 Adgaurd 和 clash TUN 流量劫持时，会出现冲突（大量端口的监听和转发）
> 2. 配置麻烦
> 3. 操作麻烦，每次重启Clash 内核都会重启 AdguardSvc （因为 AdguardSvc  依赖 Clash）
> 
> > 不使用延迟启动是因为延迟启动的时机很迷，导致刚开机浏览时会出现广告

十分感谢，不过目前我使用最新版clash-verge的服务模式开启TUN模式后，Adgaurd 和 clash-verge 都正常使用了，两者都是设置的开机自启，不知道是不是后面 clash-verge 更新的原因

**Comment by AllForLandlord** [comment]
@Maasea 您好，最近我也在处理这个问题，能请问您第一种方法里取消勾选“启用流量过滤”的理由吗？是不是这个启用流量过滤和HTTP代理这两种方法只应该同时使用其中一种？
我查阅资料还发现一种作法，在advanced setting里开或关“Use redirect driver mode”，这个方法我还没试

**Comment by Maasea** [comment]
启动流量过滤和代理二选一即可。

但是流量代理会遇到Adguard 启动失败的场景，即使我在上文中提及很少出现，但体验下来出现的频率略高。所以该方法我也弃用了。因为如果出现就会让系统完全无法上网。

Use redirect driver mode 应该是没有作用的。因为兼容性导致Adguard没有正确劫持网络，配置可能并不生效。

我的使用场景是使用Adguard后台服务，不启动主程序。（我尝试了很多配置项，没找到通过配置项让两者兼容的方法），所以安装了浏览器插件 Adguard 助手（你可以在Adguard 桌面版设置里找到该插件然后直接安装），当Adguard 助手呈灰色时候，表明Adguard未正确工作，可以在浏览器中直接使用该插件唤起Adguard 而不用手动打Adguard程序。
好处：每次开机需要用插件拉一次Adguard，后续都可以正常工作
坏处：每次开机可能需要点一次

@AllForLandlord

**Comment by AllForLandlord** [comment]
@Maasea 感谢回复。如果这么麻烦的话我感觉不如用浏览器插件算了，不折腾了
昨天看到一个主题说adguard应用版不如插件版，而且插件版还免费。
https://www.v2ex.com/t/1093315

**Comment by Maasea** [comment]
对于官方宣称的好处是，Adguard桌面版不会受到chrome浏览器升级MV3的影响，以及YouTube广告检测，并额外附赠userscript功能。

如果你还没买，我也不太建议购入。

**Comment by AllForLandlord** [comment]
> 对于官方宣称的好处是，Adguard桌面版不会受到chrome浏览器升级MV3的影响，以及YouTube广告检测，并额外附赠userscript功能。
> 
> 如果你还没买，我也不太建议购入。

我已经买了好几年了哈哈哈，只不过最近刚发现这个问题，以前一直以为广告拦截是生效的，看来是心理作用，哈哈哈哈。就当支持作者好了

**Comment by cjjdaq** [comment]
我遇到的问题时候同一个配置文件在ClashVerge1.7.7可以使用clash tun和adguard共存，不用在意哪个先启动哪个后启动，但更新到2.03后再开启tun，adguard就完全失去了拦截作用。我用了1.7.7下的旧内核替换也是同样情况，目前只能先退回1.7.7旧版本。

**Comment by chengnan049** [comment]
> [@Maasea](https://github.com/Maasea?rgh-link-date=2025-01-19T08%3A32%3A47.000Z) 感谢回复。如果这么麻烦的话我感觉不如用浏览器插件算了，不折腾了 昨天看到一个主题说adguard应用版不如插件版，而且插件版还免费。 [v2ex.com/t/1093315](https://www.v2ex.com/t/1093315)

我目前没有碰到不兼容的情况，如果你很在乎速度，那么不建议你用AdGuard Windows，建议你使用uBlock Origin，因为AdGuard 扩展没有优点
根据 [v2ex](https://www.v2ex.com/t/1093315?p=1#r_15597527) 的回复，你可以申请Beta免费许可证

**Comment by cjjdaq** [comment]
> > [@Maasea](https://github.com/Maasea?rgh-link-date=2025-01-19T08%3A32%3A47.000Z) 感谢回复。如果这么麻烦的话我感觉不如用浏览器插件算了，不折腾了 昨天看到一个主题说adguard应用版不如插件版，而且插件版还免费。 [v2ex.com/t/1093315](https://www.v2ex.com/t/1093315)
> 
> 我目前没有碰到不兼容的情况，如果你很在乎速度，那么不建议你用AdGuard Windows，建议你使用uBlock Origin，因为AdGuard 扩展没有优点 根据 [v2ex](https://www.v2ex.com/t/1093315?p=1#r_15597527) 的回复，你可以申请Beta免费许可证

后续版本又可以和tun兼容了。打开过滤回环连接即可。插件版用不了replace替换功能。而且win版也不存在卡住速度慢的问题。
加条规则即可。
- DOMAIN-SUFFIX,local.adguard.org,直链

**Comment by emptylight370** [comment]
经过测试，在系统代理模式下启用AdGuard的过滤环回连接可以过滤，不过好像偶尔会遇到一点问题。
可以在AdGuard的设置-网络-过滤应用列表中加入Clash Verge Rev安装目录下的`verge-mihomo.exe`和`verge-mihomo-alpha.exe`，之后关掉过滤环回连接，这样也能过滤广告，不过过滤器日志所有连接都是显示从mihomo出去的。
TUN模式未经测试。

**Comment by xurdy** [comment]
> 我最近也在解决这个问题。
> 
> 总的来说有两种方式：
> 
> * 使用 Adguard 的代理模式，将所有流量通过代理的方式转发过滤，而不是劫持流量。
> * 强制 Adguard 和 clash 的启动顺序。
> 
> ## 使用 Adguard 代理模式
> **开启方法**：
> 
> 1. 打开 Adguard -> 设置 -> 网络
> 2. 找到 流量过滤 一栏，将 启用流量过滤 取消勾选，将 Adguard 作为 HTTP 代理勾选上（根据提示重启系统）
> 3. 打开 window 系统的代理服务器设置 (127.0.0.1:49037)
> 4. Clash 只开启 TUN 模式，不要开启系统代理（为了防止clash的系统代理地址覆盖 Adgaurd 地址）
> 
> **优点**：
> 
> 1. 对于clash配置的侵入性小，兼容性好，clash 和 adguard 均独立运行没有冲突
> 2. 配置和操作简单
> 
> **缺点**：
> 
> 1. 部分不遵循系统代理的程序，无法经过 Adguard （但考虑到 Adgaurd 大多为浏览器过滤广告，影响不大）
> 2. 配置完系统代理后，如果 Adguard 启动失败可能造成无法访问互联网的情况（实际情况下很少发生）
> 3. 所有经过Adguard 代理的程序，PROCESS-NAME 都会变成 Adgaurd，这意味着基于PROCESS-NAME的规则会失效
> 
> > 也可以为需要去广告的应用单独配置代理，比如配合 Proxifier
> > 没有将 Adguard 设置为 clash 前置代理的原因是：需要修改大量配置文件，使配置看起来相当复杂以及一些其他的兼容性问题
> 
> ## 配置 clash 和 Adgaurd 启动顺序
> **开启方法**：
> 
> 这里我是将 clash 内核作为系统服务运行，所以可以用 sc 命令将 clash 作为 adgaurdSvc 的依赖，这样adguardSvc 每次启动都会依赖于 clash
> 
> **优点**：
> 
> 1. 由于没有在系统层配置代理服务器，所以adguard 启动失败也不会造成网络中断
> 2. 只要 Adguard 中配置的应用都可以进行广告过滤
> 
> **缺点**：
> 
> 1. 属于非常规兼容手段，当同时开启 Adgaurd 和 clash TUN 流量劫持时，会出现冲突（大量端口的监听和转发）
> 2. 配置麻烦
> 3. 操作麻烦，每次重启Clash 内核都会重启 AdguardSvc （因为 AdguardSvc  依赖 Clash）
> 
> > 不使用延迟启动是因为延迟启动的时机很迷，导致刚开机浏览时会出现广告

如果使用 Adguard 代理模式，DNS流量也能被adguard代理？

**Comment by Nikkiiw** [comment]
我遇到了开启TUN模式后，某些网站打开缓慢的问题，从WFP改用SocketFilter解决

**Comment by qqyc** [comment]
> 我遇到了开启TUN模式后，某些网站打开缓慢的问题，从WFP改用SocketFilter解决

实测sockfilter会影响电脑微信语音通话，而且排除微信的进程似乎也影响，目前没什么解决办法，可能还需要向adguard那边反馈

**Comment by CPCer** [comment]
为了解决 `WARNING [TCP] dial DIRECT (match RuleSet/private_domain) 198.18.0.1:62563 --> local.adguard.org:443 error: dial tcp 94.140.14.247:443: connectex: The requested address is not valid in its context.` ，把 `local.adguard.org` 指向 `127.0.0.1` 时，会出现 #7564 访问本地网络问题，取消后恢复

**Comment by chengnan049** [comment]
> 为了解决 `WARNING [TCP] dial DIRECT (match RuleSet/private_domain) 198.18.0.1:62563 --> local.adguard.org:443 error: dial tcp 94.140.14.247:443: connectex: The requested address is not valid in its context.` ，把 `local.adguard.org` 指向 `127.0.0.1` 时，会出现 [#7564](https://github.com/clash-verge-rev/clash-verge-rev/issues/7564) 访问本地网络问题，取消后恢复

我认为应该设置 local 为直连并
```
fake-ip-filter:
  - injections.adguard.org
  - local.adguard.org
nameserver-policy:
  injections.adguard.org: system
  local.adguard.org: system
```
