### ISSUE TITLE
[BUG] windows11 拨号连接，系统代理

### ISSUE THREAD

**Issue by tangguojuju** [clash-verge-rev/clash-verge-rev#1169]
### 问题描述 / Describe the bug

windows11 拨号连接，系统代理无法识别

### 复现步骤 / To Reproduce

1. 打开clash verge 1.4.7 软件 在windows11上
2. 设置订阅
3. 选择节点
4. 开启系统代理
5. 点击系统代理小图标，（ 显示 当前系统代理开启状态为 false）
![9900380ef1d8ca398ed7d80371c8e626](https://github.com/clash-verge-rev/clash-verge-rev/assets/87310772/7bcfb360-783b-4c4f-b79a-c27041e7a863)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11

### 日志 / Log

06-11 22:06:38INFO
Start initial Compatible provider 三毛机场
06-11 22:06:38INFO
Start initial Compatible provider default
06-11 22:09:47INFO
[TCP] 127.0.0.1:49679 --> www.msftconnecttest.com:80 using GLOBAL
06-11 22:09:52WARNING
[TCP] dial GLOBAL 127.0.0.1:49683 --> edge.microsoft.com:443 error: context deadline exceeded
06-11 22:09:53WARNING
[TCP] dial GLOBAL 127.0.0.1:49700 --> functional.events.data.microsoft.com:443 error: context deadline exceeded
06-11 22:09:56WARNING
[TCP] dial GLOBAL 127.0.0.1:49724 --> functional.events.data.microsoft.com:443 error: context deadline exceeded

**Comment by AnyWAT** [comment]
试了V1.6.5后再报？
不正是有这样那样的问题，才从V1.4.7到了V1.6.5？

**Comment by dongchengjie** [comment]
文档搜宽带

**Comment by tangguojuju** [comment]
> 试了V1.6.5后再报？ 不正是有这样那样的问题，才从V1.4.7到了V1.6.5？

下了一个V1.6.5的 解决了系统代理的问题，但是打开谷歌没反应，测试这里却正常
![eed4ef2d-6531-4c93-9e75-64b6b2acc2ec](https://github.com/clash-verge-rev/clash-verge-rev/assets/87310772/d56128a5-4b37-4174-87f9-4e437158defd)

**Comment by tangguojuju** [comment]
> 试了V1.6.5后再报？ 不正是有这样那样的问题，才从V1.4.7到了V1.6.5？

下了一个V1.6.5的 解决了系统代理的问题，但是打开谷歌没反应，测试这里却正常
![eed4ef2d-6531-4c93-9e75-64b6b2acc2ec](https://github.com/clash-verge-rev/clash-verge-rev/assets/87310772/d56128a5-4b37-4174-87f9-4e437158defd)

**Comment by AnyWAT** [comment]
不会是浏览器管理代理的扩展设置或选择不正确？

**Comment by tangguojuju** [comment]
> 文档搜宽带

是指拨号上网改英文的那个嘛，这个改好了

**Comment by tangguojuju** [comment]
> 不会是浏览器管理代理的扩展设置或选择不正确？ 貌似最佳：为避免影响操作系统，一般不开启系统代理。浏览器采用代理扩展，配置能自定义切换规则的情景模式，任何网址是走直接连接还是走代理完全由你自己裁决。 此时还可以运行其它代理，一个。。。另一个。。。再一个又有何妨？
windows11上的浏览器是刚下的，应该没有配置扩展设置；
我在windows10上下了一个，同样的配置，windows10可以用

**Comment by rookie-zlf** [comment]
我连接校园网clash verge不能翻墙也是这个问题吗？

**Comment by malagebidi** [comment]
`[TCP] 127.0.0.1:49679 --> [www.msftconnecttest.com:80](http://www.msftconnecttest.com/) using GLOBAL`
这条微软的探测域名应该走直连

**Comment by Charlotte4177** [comment]
我的拨号是后来改名的，无论是哪种模式都显示未开启系统代理，但V2RayN可以用。你写个教程叫我重新建立连接，我试了，没用。什么时候修一下，感觉V2RayN没clash verge Rev的好用，但是PPPoE不给连，我只能暂且等着修复，这段时间用着V2RayN了

**Comment by Charlotte4177** [comment]
> `[TCP] 127.0.0.1:49679 --> [www.msftconnecttest.com:80](http://www.msftconnecttest.com/) using GLOBAL` 这条微软的探测域名应该走直连

就是看看本机能不能访问广域网，这有啥，没影响

**Comment by JefferyW1** [comment]
用插件吧  Proxy SwitchyOmega   ；指定端口；

**Comment by wonfen** [comment]
> 用插件吧 Proxy SwitchyOmega ；指定端口；

2.0版本已经可以设置了
