### ISSUE TITLE
拨号连接无法使用tun模式

### ISSUE THREAD

**Issue by fdgfxz** [clash-verge-rev/clash-verge-rev#117]
### Describe the bug

已安装服务模式，测试wifi可以开启tun正常科学上网，拨号连接开启tun后生成meta虚拟网卡显示无连接，同时无法上网，cfw使用同内核同节点可以使用tun模式科学上网

### To Reproduce

拨号上网状态下开启tun

### Platform

Windows

### System Version

win11专业版23h2

### Software Version

1.4.4

### Log

打开tun后没有日志

**Comment by wonfen** [comment]
暂时没有环境复现，建议换个环境再尝试下，排除windows的故障。

**Comment by wonfen** [comment]
无进一步反馈，关闭了。
