### ISSUE TITLE
[BUG] 连接界面，会话无法显示进程信息

### ISSUE THREAD

**Issue by Perter1999** [clash-verge-rev/clash-verge-rev#1171]
### 问题描述 / Describe the bug

问题：开启clash verge并启用常规的系统代理后，连接界面中，每个会话都无法显示进程相关信息
尝试：使用最新的稳定版本1.6.5，更换了aplha内核，使用管理员权限运行clash verge
![Snipaste_2024-06-12_05-58-48](https://github.com/clash-verge-rev/clash-verge-rev/assets/55939736/e64b599c-cfe5-4154-a3e7-4ec47c2a3114)

### 复现步骤 / To Reproduce

直接打开clash verge即可复现故障

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

版本	Windows 11 专业工作站版 版本	23H2  操作系统版本	22631.3593 体验	Windows Feature Experience Pack 1000.22700.1003.0

### 日志 / Log

[2024-06-12-0545.log](https://github.com/user-attachments/files/15795134/2024-06-12-0545.log)

**Comment by dongchengjie** [comment]
并不是所有的进程都能拿到进程信息，内核ws推送了什么这里就展示什么，拿不到那就是空，你若真想深究就去内核那边问
