### ISSUE TITLE
[BUG] Windows1.6.6setup卡巴斯基报毒

### ISSUE THREAD

**Issue by BoBppy** [clash-verge-rev/clash-verge-rev#1175]
### 问题描述 / Describe the bug

卡巴斯基文件反病毒检测到病毒后自动阻止并清除了安装程序，而1.6.5并没有出现此问题。仅测试了Clash.Verge_1.6.6_x64-setup.exe和对应的上一版本。

### 复现步骤 / To Reproduce

应用内更新或者release下载的都报毒，不过暂停卡巴斯基后，更新完成再扫描安装的组件并没有报毒。应该是误报吧，打包方式变了吗，或者是因为kill service的原因？总之我是相信应该是没毒的

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11 23h2 22631.3672

### 日志 / Log

结果说明: 已删除
类型: 木马
名称: PDM:Trojan.Win32.Generic.nblk
威胁级别: 高
对象类型: 进程
对象路径: C:\Users\\AppData\Local\Temp\.tmpfRCwXG
对象名称: Clash Verge_1.6.6_x64-setup.exe
MD5: B774A1D8502F226AFAA8316DB65CD4F0

**Comment by AtkinsonWen** [comment]
![Uploading 463ab3a32513e639391a606db19fc4c0.png…]()

**Comment by AutisticShark** [comment]
Similar issues with the x86 setup & portable packages:

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/14369594/1343e36b-40d1-4fae-bdb3-c2590a3632bd)

https://www.virustotal.com/gui/file/8150e896be88a8c5205b94f8630199e70285f42c5ae458d75fb9e211900cc70f

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/14369594/c9869bc5-ec5f-4da4-9680-1599bdddd0e6)

https://www.virustotal.com/gui/file/a34b0b147621743284e2f685d1bd98daf7f1d459fd0ca14b7e36b66902ad07fe

If the included mihomo core has not been updated, I wonder what's causing this malware detection.

**Comment by MystiPanda** [comment]
想知道就自己去读代码，看看哪些改动导致了报毒，反正我懒得管。

**Comment by dongchengjie** [comment]
1.6.5到1.6.6这段时间，卡巴斯基不能更新它的数据库吗，我用火绒就没这事

**Comment by dengweiqiang** [comment]
是的，我也遇到这样的情况了，暂时回退到了1.6.5版本，看了一下commit，感觉是更新依赖的问题？

**Comment by checker999** [comment]
下载了一个便携版 发现不报毒 可能是安装包的 依赖 报毒的
