### ISSUE TITLE
[BUG] 1.66版本被卡巴斯基(kaspersky)报毒

### ISSUE THREAD

**Issue by Mixlining** [clash-verge-rev/clash-verge-rev#1176]
### 问题描述 / Describe the bug

下载1.66版本windows x64安装包后被卡巴斯基报毒,如下:
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/91776353/cef89cd6-9c95-4d88-9ed7-1dd42e043708)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/91776353/86758dfe-9b4f-441d-be64-d0aad00356b7)

### 复现步骤 / To Reproduce

下载windows x64安装包,卡巴斯基报毒

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

19045.4412

### 日志 / Log

无

**Comment by X-unable** [comment]
![IMG_8348](https://github.com/clash-verge-rev/clash-verge-rev/assets/59173937/2089f5e0-23ae-43a5-a650-3d5aaa57a679)

**Comment by CSYuq1** [comment]
一样，都不敢用了

**Comment by xishang0128** [comment]
软件不会针对杀毒软件开发,用别怕怕别用

**Comment by YaTechie** [comment]
这是被误判了，可以自己编译的时候加一个管理员权限级别就好了
