### ISSUE TITLE
[BUG] 软件内更新(安装版)，安装后并不是自定义路径，而是变为默认的C:\Program Files\Clash Verge\..

### ISSUE THREAD

**Issue by litmowise** [clash-verge-rev/clash-verge-rev#1177]
### 问题描述 / Describe the bug

1.6.5版本软件内更新到1.6.6版本会导致自定义安装路径变为默认路径(D:\SoftwareApps\Clash Verge\.. ---> C:\Program Files\Clash Verge\..)，1.6.5之前版本软件内更新则不会有这个问题。

### 复现步骤 / To Reproduce

安装版软件内正常更新

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

22631.3737

### 日志 / Log

无

**Comment by dongchengjie** [comment]
1.6.5版本及以前安装在 非C盘的默认安装位置 的用户，不要使用应用内更新到1.6.6，而是手动下载安装包重新选择安装位置。
由于安装器更换了publisher，和注册表里旧的项匹配不上，也就查询不到之前已安装的位置，就会认为你之前没有安装过，便会安装到C盘中。如果桌面已经有了快捷方式便不会再生成快捷方式，便会出现两个版本共存，但是打开桌面的快捷方式指向了老版本，提示又有新版本的问题
