### ISSUE TITLE
开启tun模式后可以访问google、youtube，但ip地址仍然是国内[BUG] 

### ISSUE THREAD

**Issue by excavate** [clash-verge-rev/clash-verge-rev#1178]
### 问题描述 / Describe the bug

开启tun模式后可以访问google、youtube，但ip地址仍然是国内

### 复现步骤 / To Reproduce

配置网卡为meta1后分别在system、Gvisor和mixed模式下启用tun，可以访问Google、youtube但ip地址还是国内的
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/48313294/88c460a6-36fa-4e04-adda-0ac98e9e3842)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10    19045.4412

### 日志 / Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/48313294/88c460a6-36fa-4e04-adda-0ac98e9e3842)

**Comment by test4uninstall** [comment]
是规则模式还是全局模式？如果是规则模式则属于正常现象。

**Comment by excavate** [comment]
> 是规则模式还是全局模式？如果是规则模式则属于正常现象。

是规则模式这样，全局模式会显示代理ip

那请教大佬一下，tun模式不是通过所有流量走虚拟网卡吗？它还会受到规则模式的规则限制吗？

**Comment by test4uninstall** [comment]
> > 是规则模式还是全局模式？如果是规则模式则属于正常现象。
> 
> 是规则模式这样，全局模式会显示代理ip
> 
> 那请教大佬一下，tun模式不是通过所有流量走虚拟网卡吗？它还会受到规则模式的规则限制吗？

只要代理组是规则模式，那么国内到国内流量则不会被代理，自动设置全局路由是让所有流量都通过虚拟网卡。

**Comment by test4uninstall** [comment]
> > 是规则模式还是全局模式？如果是规则模式则属于正常现象。
> 
> 是规则模式这样，全局模式会显示代理ip
> 
> 那请教大佬一下，tun模式不是通过所有流量走虚拟网卡吗？它还会受到规则模式的规则限制吗？

只要代理组是规则模式，那么国内到国内流量则不会被代理，自动设置全局路由是让所有流量都通过虚拟网卡，分流则交给mihomo。

**Comment by test4uninstall** [comment]
> 只要代理组是规则模式，那么国内到国内流量则不会被代理，自动设置全局路由是让所有流量都通过虚拟网卡，分流则交给mihomo。

只要代理组是规则模式，那么国内到国内流量则不会被代理，自动设置全局路由是让所有流量都通过虚拟网卡.
虚拟网卡负责把所有流量路由到mihomo core，至于是直连还是代理出去则交给mihomo core。

**Comment by excavate** [comment]
> > > 是规则模式还是全局模式？如果是规则模式则属于正常现象。
> > 
> > 
> > 是规则模式这样，全局模式会显示代理ip
> > 那请教大佬一下，tun模式不是通过所有流量走虚拟网卡吗？它还会受到规则模式的规则限制吗？
> 
> 只要代理组是规则模式，那么国内到国内流量则不会被代理，自动设置全局路由是让所有流量都通过虚拟网卡，分流则交给mihomo。

了解了，谢谢大佬
