### ISSUE TITLE
[Feature] 无桌面版本的可以安装吗

### ISSUE THREAD

**Issue by HuDaTou** [clash-verge-rev/clash-verge-rev#1179]
### 功能描述 / Feature description

没有桌面版本的

### 使用场景 / Use case

Ubuntu22.04

**Comment by dongchengjie** [comment]
[mihomo](https://github.com/MetaCubeX/mihomo)

**Comment by test4uninstall** [comment]
建议直接使用mihomo core

**Comment by test4uninstall** [comment]
建议直接运行mihomo core

**Comment by AllenDun** [comment]
如何直接运行mihomo core，命令行：mihomo core?

**Comment by test4uninstall** [comment]
clash-meta.exe -d "工作路径" -f "yaml配置文件"

**Comment by test4uninstall** [comment]
> 如何直接运行mihomo core，命令行：mihomo core?

clash-meta.exe -d "工作路径" -f "yaml配置文件"

**Comment by test4uninstall** [comment]
https://github.com/MetaCubeX/mihomo/discussions/1316

**Comment by test4uninstall** [comment]
Clash Verge Rev只是提供了mihomo core的GUI，要进行代理还是要调用mihomo core。
如果想要命令行运行，请直接使用mihomo core。

**Comment by test4uninstall** [comment]
Clash Verge Rev只是提供了mihomo core的GUI，要进行代理还是要调用mihomo core。
如果想要纯命令行运行，请直接使用mihomo core。
