### ISSUE TITLE
[BUG] The kernel fails to get permission on the latest macOS

### ISSUE THREAD

**Issue by liouxy** [clash-verge-rev/clash-verge-rev#1180]
### 问题描述 / Describe the bug

An error occurs when clicking grant in the Clash core settings.
`0:190: execution error: chown:
/Applications/Clash
Verge.app/Contents/MacOS/clash-meta:
Operation not permittedchmod: Unable to change file mode on /Applications/Clash
Verge.app/Contents/MacOS/clash-meta:
Operation not permitted (1)`

<img width="800" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/10026756/6f421ef9-9c8d-495d-8415-54eefe71d078">

### 复现步骤 / To Reproduce

Click grant in the Clash core settings.

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.0

### 日志 / Log

0:190: execution error: chown:
/Applications/Clash
Verge.app/Contents/MacOS/clash-meta:
Operation not permittedchmod: Unable to change file mode on /Applications/Clash
Verge.app/Contents/MacOS/clash-meta:
Operation not permitted (1)

**Comment by LeifDong** [comment]
有同样的问题。

**Comment by RexToUESTC** [comment]
same question

**Comment by GHJDgg** [comment]
升级最新版本能解决吗？

**Comment by wonfen** [comment]
> 升级最新版本能解决吗？

2.0版解决了这个问题。
