### ISSUE TITLE
[BUG] 代理绕过设置没办法输入域名通配符

### ISSUE THREAD

**Issue by lonwern** [clash-verge-rev/clash-verge-rev#1181]
### 问题描述 / Describe the bug

Windows系统，1.6.6版本的代理绕过设置无法输入域名通配符，如`*.somedomain.com`，按照微软的[官方文档](https://learn.microsoft.com/zh-cn/troubleshoot/developer/browsers/connectivity-navigation/use-proxy-servers-with-ie#more-information)是支持通配符的。

### 复现步骤 / To Reproduce

系统代理设置输入`*.somedomain.com`，点击保存。

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/5079364/70db95f8-3e6b-45a9-b1d4-5b0f4f34a530)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10

### 日志 / Log

.

**Comment by hhuzzz** [comment]
我也遇到了

**Comment by wonfen** [comment]
已知问题，后续修复。

**Comment by fuwuqi298** [comment]
用 [PAC](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file) 吧，PAC 好用

**Comment by qiaolugithub** [comment]
用*xxxx.com 而不是*.xxxx.com
