### ISSUE TITLE
运行配置中出现 黄色 ~ 是啥意思？

### ISSUE THREAD

**Issue by Sfssup** [clash-verge-rev/clash-verge-rev#1183]
![微信截图_20240612090415.png](https://github.com/clash-verge-rev/clash-verge-rev/assets/32392479/21214e4e-5635-4bfe-80cd-37b2757d8267)

![微信截图_20240612090507.png](https://github.com/clash-verge-rev/clash-verge-rev/assets/32392479/fbc53939-fcf8-4586-addc-04af1420e167)

**Comment by WAN8023** [comment]
无效的写法

**Comment by dongchengjie** [comment]
> > 无效的写法
> 
> 好吧，看了下确实是无效配置
> 可是，这不科学啊
> 域名嗅探部分是Clash.meta那边文档里的默认配置
> GEOSITE规则在手机上规则是显示的，有180+（好像）

米家的那个不是标准的域名，但它用的确实是那个，扫描家居设备通信用的。正则限制的是域名的正则，那个是个特例无视就好
