### ISSUE TITLE
[Feature] Ubuntu22.04打开Tun模式跳过认证

### ISSUE THREAD

**Issue by Frost-Mactavish** [clash-verge-rev/clash-verge-rev#1184]
### 功能描述 / Feature description

每次打开Tun模式都需要三次认证，输入三次root密码，比较麻烦，是否可以直接跳过？
![截图 2024-06-13 00-07-40](https://github.com/clash-verge-rev/clash-verge-rev/assets/54988497/e675dd58-e2aa-4f31-b2f1-b661ce5aeacd)
![截图 2024-06-13 00-07-36](https://github.com/clash-verge-rev/clash-verge-rev/assets/54988497/30426c47-5b12-4a8b-8d77-f278e018370f)
![截图 2024-06-13 00-07-30](https://github.com/clash-verge-rev/clash-verge-rev/assets/54988497/9498d402-cabb-452e-92b6-c443b68b6734)

### 使用场景 / Use case

Ubuntu22.04
Clash Verge 1.6.6，Tun模式

**Comment by Frost-Mactavish** [comment]
刚安装好Clash Verge时，默认设置下打开Tun模式无效。在**设置-Clash内核**中授权后，才弹出上述的认证。认证完之后Tun模式才算成功启动

**Comment by xishang0128** [comment]
这是不是软件能处理的,特权申请都会经过发行版的管理器,可以尝试将user设置为NOPASSSWD:ALL
