### ISSUE TITLE
[BUG] 1.66 windows_64位安装包 卡巴斯基报毒

### ISSUE THREAD

**Issue by checker999** [clash-verge-rev/clash-verge-rev#1186]
### 问题描述 / Describe the bug

![1718241175339](https://github.com/clash-verge-rev/clash-verge-rev/assets/49055215/046d0b23-fe36-4231-8507-381333aabba4)
如图卡巴斯基 会对1.66版本报毒

### 复现步骤 / To Reproduce

下载1.66 windows64位安装包 无需安装直接报毒

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

无日志 未安装既报毒

**Comment by wonfen** [comment]
向卡吧死机提交一下，误报。

**Comment by hackerhui** [comment]
@checker999 我已经提交样本了，现在已经不报了
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/42575324/b5cadf3f-9662-4d56-b3ea-e11117aa6144)
开源软件一般没什么担心的

**Comment by C-racker** [comment]
360也报毒
