### ISSUE TITLE
新增一个 Discussions？[Feature] 

### ISSUE THREAD

**Issue by fuwuqi298** [clash-verge-rev/clash-verge-rev#1189]
### 功能描述 / Feature description

讨论交流 没TG号，考虑开一个 [Discussions](https://github.com/clash-verge-rev/clash-verge-rev/discussions)？

### 使用场景 / Use case

使用交流

另外个人感觉 clash-verge-rev logo 没之前的好看，现在的看着有点邪性...

**Comment by dongchengjie** [comment]
readme中写的清清楚楚，怎么就没tg号了
