### ISSUE TITLE
[BUG]开了tun模式玩守望先锋

### ISSUE THREAD

**Issue by limitwhy** [clash-verge-rev/clash-verge-rev#119]
### Describe the bug

为什么测试的延迟是40多ms,到了游戏里变成300多ms了，我也不知道是游戏服务器的原因还是这个的原因

### To Reproduce

打开clash然后登录steam的ow2

### Platform

Windows

### System Version

w11

### Software Version

1.4.4

**Comment by JohnCanny52** [comment]
游戏建议用加速器比较稳

**Comment by MystiPanda** [comment]
unified-delay开与不开的差距很大的。

**Comment by divingdragonwzy** [comment]
> > unified-delay开与不开测出来的数据差距很大的，但是不影响你游戏内的实际延迟。
> 
> 确实是有问题的，可能这个不是专业的加速器没针对做优化吧，有可能dns的问题，连到奇怪的服务器了。我也不清楚。用netch延迟比这个低好几倍，不过netch的效果也不太好。而且我看了一下，把ow2的服务器连到巴西了。不300ms才怪

我也遇到了同样的问题，开了clash的tun模式被分配到巴西了，但节点是日本的。用v2rayN的就没问题，很好奇是什么原因
