### ISSUE TITLE
[BUG] MacOS v1.6.6 内核授权 提示没权限

### ISSUE THREAD

**Issue by niphor** [clash-verge-rev/clash-verge-rev#1190]
### 问题描述 / Describe the bug

MacOS v1.6.6 内核授权 提示没权限
之前的版本都好的

### 复现步骤 / To Reproduce

打开软件，进入->设置->内核选择, 点击授权，输入密码
报错

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5

### 日志 / Log

![WX20240613-093555@2x](https://github.com/clash-verge-rev/clash-verge-rev/assets/927255/1fbe0e8f-506f-4b86-8c27-080e1d1eb953)

**Comment by wonfen** [comment]
暂未找到原因，可能是签名导致的；先用服务模式用着。

**Comment by speadernike** [comment]
同样的问题，同样的报错，目前内核无法启用，tun 模式就用不了，只能用系统代理模式了

**Comment by niphor** [comment]
@speadernike 
你可以先手动 `chown root:admin` 和 `chmod +sx` 授权一下

**Comment by MystiPanda** [comment]
用服务模式

**Comment by speadernike** [comment]
> @speadernike 你可以先手动 `chown root:admin` 和 `chmod +sx` 授权一下


<img width="762" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/111223799/fd3bc9ec-b2f5-4c87-9ad2-011129c1989c">

这个在终端陆续输入sudo chown root:admin "/Applications/Clash Verge.app"
sudo chmod +sx "/Applications/Clash Verge.app"后再次打开 Clash 进行授权内核操作，还是报错了。
<img width="1380" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/111223799/58d334e2-99b4-4287-92fe-3c8f0d4d9d07">

好在这个Mac 上的这个版本可以安装服务模式了，打开服务模式，就可以不授权内核启用 tun 模式：
<img width="580" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/111223799/0bc96f0c-ec44-4704-949b-28fb430293ca">

**Comment by speadernike** [comment]
截图的时候误操作把服务模式关了，正常是要打开状态才能使用

**Comment by niphor** [comment]
@speadernike  
额 我说的手动，是指：手动用命令去授权`clash-meta` 或者 `clash-meta-alpha` 二进制文件
不是去改app的权限，相当于 界面上点击”授权“

**Comment by JDIYYST** [comment]
> @speadernike 额 我说的手动，是指：手动用命令去授权`clash-meta` 或者 `clash-meta-alpha` 二进制文件 不是去改app的权限，相当于 界面上点击”授权“

这样确实可以，进到应用目录下 Contents/MacOS ，chown root:admin 和 chmod +sx 授权后，再去应用中点击授权就不会报错了，重启应用后也可以正常使用 tun 模式

**Comment by chenzhiguo** [comment]
这个Bug太大了

**Comment by mikukko** [comment]
更新到1.6.6遇到同样的问题，通过终端命令授权后可以使用了
```bash
sudo chown root:admin /Applications/Clash\ Verge.app/Contents/MacOS/clash-meta
sudo chmod +sx /Applications/Clash\ Verge.app/Contents/MacOS/clash-meta
```

**Comment by ooQAQooo** [comment]
> 更新到1.6.6遇到同样的问题，通过终端命令授权后可以使用了
> 
> ```shell
> sudo chown root:admin /Applications/Clash\ Verge.app/Contents/MacOS/clash-meta
> sudo chmod +sx /Applications/Clash\ Verge.app/Contents/MacOS/clash-meta
> ```

显示：不允许操作
chown: /Applications/Clash Verge.app/Contents/MacOS/clash-meta: Operation not permitted
chmod: Unable to change file mode on /Applications/Clash Verge.app/Contents/MacOS/clash-meta: Operation not permitted

**Comment by smartcat999** [comment]
之前就版本不需要 为啥升级之后需要这么高权限呢

**Comment by oleolema** [comment]
大佬，我执行报错了，不应该呀
```
chown: /Applications/Clash Verge.app/Contents/MacOS/verge-mihomo: Operation not permitted
chmod: Unable to change file mode on /Applications/Clash Verge.app/Contents/MacOS/verge-mihomo: Operation not permitted
```

**Comment by rj9676564** [comment]
新版更换 mihomo 
执行命令需要改成 
`
sudo chown root:admin verge-mihomo
sudo chmod +sx ./verge-mihom
`
如果使用alpha 内耗
`
sudo chown root:admin ./verge-mihomo-alpha
sudo chmod +sx ./verge-mihom-alpha
`
