### ISSUE TITLE
Linux centos安装clash verge提示依赖缺失error: Failed dependencies

### ISSUE THREAD

**Issue by ytanck** [clash-verge-rev/clash-verge-rev#1192]
### 问题描述 / Describe the bug

error: Failed dependencies
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/69585768/73b9615e-ef7f-4a8c-8498-0af2e9165826)

### 复现步骤 / To Reproduce

[root@VM-16-13-centos clash]# ls
clash-verge-1.6.6-1.x86_64.rpm
[root@VM-16-13-centos clash]# rpm -ivh clash-verge-1.6.6-1.x86_64.rpm

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

centos7.9    3.10.0-1160.99.1.el7.x86_64

### 日志 / Log

error: Failed dependencies:
	libayatana-appindicator3.so.1()(64bit) is needed by clash-verge-0:1.6.6-1.x86_64
	libwebkit2gtk-4.0.so.37()(64bit) is needed by clash-verge-0:1.6.6-1.x86_64
	libgtk-3.so.0()(64bit) is needed by clash-verge-0:1.6.6-1.x86_64

**Comment by wonfen** [comment]
问下gpt就解决了。

**Comment by saodis** [comment]
提个建议，建议维护者可以直接关闭不是 cvr 的问题。争取把遗留的问题处理掉就可以了，新特性次之。个人认为 cfw 这个软件做的蛮成功的，每什么大问题。

**Comment by RESTART1230** [comment]
安装依赖就行了
rpm包名和deb的会有点不同

**Comment by dear7575** [comment]
我在centos 安装也是出现这个缺少依赖的问题，就是个无底洞，你下A依赖安装就提示需要B依赖。。。这块还是太菜了，有会的大佬教教吗？非常感谢

**Comment by Mieluoxxx** [comment]
wget https://rpmfind.net/linux/openmandriva/cooker/repository/x86_64/main/release/lib64ayatana-appindicator3_1-0.5.93-1-omv2390.x86_64.rpm

https://rpmfind.net/linux/openmandriva/5.0/repository/x86_64/main/release/lib64webkit2gtk4.0-2.42.2-1-omv2390.x86_64.rpm

**Comment by RESTART1230** [comment]
> ![image](https://private-user-images.githubusercontent.com/69585768/341366798-a9106933-427e-4a12-ac59-d5604523eb14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4ODMyNDIsIm5iZiI6MTcxODg4Mjk0MiwicGF0aCI6Ii82OTU4NTc2OC8zNDEzNjY3OTgtYTkxMDY5MzMtNDI3ZS00YTEyLWFjNTktZDU2MDQ1MjNlYjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDExMjkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0Yjc1N2MyOGZhOTM2YzhjNDY0NzUyNTFkZTE3ZDE2MGNmNzQ2MmI3NmRmY2RhOWRlNWQwODNhOWExNDAwMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B9sze5dWwyJ1J_hHIkUyjV9NKzOrAJcqXT7r2nDtAUw) 无底洞，你安装A依赖就提示需要B依赖。。。

安装错依赖了

**Comment by Mieluoxxx** [comment]
无底洞依赖，还是直接把appimage解出来吧

**Comment by ytanck** [comment]
> 无底洞依赖，还是直接把appimage解出来吧

也会提示依赖缺失

**Comment by dear7575** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/69585768/341366798-a9106933-427e-4a12-ac59-d5604523eb14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4ODMyNDIsIm5iZiI6MTcxODg4Mjk0MiwicGF0aCI6Ii82OTU4NTc2OC8zNDEzNjY3OTgtYTkxMDY5MzMtNDI3ZS00YTEyLWFjNTktZDU2MDQ1MjNlYjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDExMjkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0Yjc1N2MyOGZhOTM2YzhjNDY0NzUyNTFkZTE3ZDE2MGNmNzQ2MmI3NmRmY2RhOWRlNWQwODNhOWExNDAwMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B9sze5dWwyJ1J_hHIkUyjV9NKzOrAJcqXT7r2nDtAUw)无底洞，你安装A依赖就提示需要B依赖。。。
> 
> 安装错误依赖了
> 
> libwebkit2gtk4.0 在CentOS里面就是这个https://centos.pkgs.org/9-stream/centos-appstream-x86_64/webkit2gtk3-2.44.2-1.el9.x86_64.rpm.html

centos7 也可以使用这个包吗？

**Comment by Mieluoxxx** [comment]
> 依赖

AppImage环境都是单独打包好的也会有依赖缺失？看看xxx.appimage --appimage-extract的运行结果

**Comment by ytanck** [comment]
xxx.appimage --appimage-extract的运行结果
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/69585768/9c4757e4-1be6-411f-98cb-ea5d9de273d6)
squashfs-root文件夹里面的AppRun结果
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/69585768/371c8490-e15c-4726-bf35-593df838b059)

**Comment by ytanck** [comment]
> > > ![图像](https://private-user-images.githubusercontent.com/69585768/341366798-a9106933-427e-4a12-ac59-d5604523eb14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4ODMyNDIsIm5iZiI6MTcxODg4Mjk0MiwicGF0aCI6Ii82OTU4NTc2OC8zNDEzNjY3OTgtYTkxMDY5MzMtNDI3ZS00YTEyLWFjNTktZDU2MDQ1MjNlYjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDExMjkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0Yjc1N2MyOGZhOTM2YzhjNDY0NzUyNTFkZTE3ZDE2MGNmNzQ2MmI3NmRmY2RhOWRlNWQwODNhOWExNDAwMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B9sze5dWwyJ1J_hHIkUyjV9NKzOrAJcqXT7r2nDtAUw)无底洞，你安装A依赖就提示需要B依赖。。。
> > 
> > 
> > 安装错误依赖了
> > libwebkit2gtk4.0 在CentOS里面就是这个https://centos.pkgs.org/9-stream/centos-appstream-x86_64/webkit2gtk3-2.44.2-1.el9.x86_64.rpm.html
> 
> centos7 也可以使用这个包吗？

一样的提示

**Comment by itstudygeen** [comment]
一样，就是无底洞，我提的issues被关闭了

**Comment by liucx1201** [comment]
一样，就是无底洞 安装不了 centos7.9

**Comment by xuya227939** [comment]
我丢，大佬们如何解决？这依赖无底洞阿，centos 正确安装依赖的口径是什么？求指点

**Comment by EUHTWT-2USYyn** [comment]
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install libayatana-appindicator
改成yum 然后你再试试看
