### ISSUE TITLE
[BUG] ubuntu 24.04下安装clash-verge_1.6.6_amd64.deb 依赖缺失 libwebkit2gtk-4.0-37

### ISSUE THREAD

**Issue by wys929** [clash-verge-rev/clash-verge-rev#1193]
### 问题描述 / Describe the bug

ubuntu 24.04下安装clash-verge_1.6.6_amd64.deb 依赖缺失 libwebkit2gtk-4.0-37。
但是系统内已经自带libwebkit2gtk-4.1。能修改依赖到libwebkit2gtk-4.1吗？

### 复现步骤 / To Reproduce

sudo dpkg -i ./clash-verge_1.6.6_amd64.deb
正在选中未选择的软件包 clash-verge。
(正在读取数据库 ... 系统当前共安装有 312967 个文件和目录。)
准备解压 ./clash-verge_1.6.6_amd64.deb  ...
正在解压 clash-verge (1.6.6) ...
dpkg: 依赖关系问题使得 clash-verge 的配置工作不能继续：
 clash-verge 依赖于 libwebkit2gtk-4.0-37；然而：
  未安装软件包 libwebkit2gtk-4.0-37。

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

ubuntu 24.04

### 日志 / Log

sudo dpkg -i clash-verge_1.6.6_amd64.deb
(正在读取数据库 ... 系统当前共安装有 312986 个文件和目录。)
准备解压 clash-verge_1.6.6_amd64.deb  ...
正在解压 clash-verge (1.6.6) 并覆盖 (1.6.6) ...
dpkg: 依赖关系问题使得 clash-verge 的配置工作不能继续：
 clash-verge 依赖于 libwebkit2gtk-4.0-37；然而：
  未安装软件包 libwebkit2gtk-4.0-37。

dpkg: 处理软件包 clash-verge (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
正在处理用于 desktop-file-utils (0.27-2build1) 的触发器 ...
在处理时有错误发生：
 clash-verge

**Comment by dongchengjie** [comment]
安装[文档中](https://clash-verge-rev.github.io/faq/linux.html)提供的deb依赖，不建议使用高版本，有反应称高版本依赖无法打开界面

**Comment by zhangxs-go** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/54925441/424022e6-3506-45de-8f47-33cc88770a5f)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/54925441/f0fe102a-0846-44d5-956d-bb4b77582a6f)

debian testing也会报这个错，

**Comment by liyuhaolol** [comment]
> 安装[文档中](https://clash-verge-rev.github.io/faq/linux.html)提供的deb依赖，不建议使用高版本，有反应称高版本依赖无法打开界面

24.04既然已经是官方确定的LTS长期支持版本了，为啥咱们的项目不去兼容24.04呢？是因为兼容了24.04就没法向下兼容了么？

**Comment by RESTART1230** [comment]
> > 安装[文档中](https://clash-verge-rev.github.io/faq/linux.html)提供的deb依赖，不建议使用高版本，有反应称高版本依赖无法打开界面
> 
> 24.04既然已经是官方确定的LTS长期支持版本了，为啥咱们的项目不去兼容24.04呢？是因为兼容了24.04就没法向下兼容了么？

https://github.com/tauri-apps/tauri/issues/6151
上游问题

**Comment by shynur** [comment]
Fedora 40:

> clash-verge: symbol lookup error: /lib64/libwebkit2gtk-4.0.so.37: undefined symbol: gst_video_info_dma_drm_from_caps

有没有什么 workaround?

**Comment by Riczzoe** [comment]
> Fedora 40:
> 
> > clash-verge: symbol lookup error: /lib64/libwebkit2gtk-4.0.so.37: undefined symbol: gst_video_info_dma_drm_from_caps
> 
> 有没有什么 workaround?

dnf 更新一下就好了

**Comment by coolinkdadwasdawd** [comment]
为什么我的Clash V关机后重开可以连接一会网，但是过一会就连接不上外网了？

**Comment by Addition2000** [comment]
我也是～～请问解决了没有？谢谢鸭！

**Comment by yuanyingzhang532** [comment]
linux 桌面版 ubuntu 24.lts安装 clash-verge
提示libwebkit2gtk-4.0-37 没有安装

解决步骤
1 cd /etc/apt/ 
  sudo cp sources.list sources.list.old  
2 sudo vim sources.list
3 国内添加阿里源和网易云
deb http://mirrors.aliyun.com/ubuntu/ jammy main restricted universe multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ jammy main restricted universe multiverse
deb http://mirrors.aliyun.com/ubuntu/ jammy-security main restricted universe multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ jammy-security main restricted universe multiverse
deb http://mirrors.aliyun.com/ubuntu/ jammy-updates main restricted universe multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ jammy-updates main restricted universe multiverse
deb http://mirrors.aliyun.com/ubuntu/ jammy-proposed main restricted universe multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ jammy-proposed main restricted universe multiverse
deb http://mirrors.aliyun.com/ubuntu/ jammy-backports main restricted universe multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ jammy-backports main restricted universe multiverse

deb http://mirrors.163.com/ubuntu/ jammy main restricted universe multiverse
deb http://mirrors.163.com/ubuntu/ jammy-security main restricted universe multiverse
deb http://mirrors.163.com/ubuntu/ jammy-updates main restricted universe multiverse
deb http://mirrors.163.com/ubuntu/ jammy-proposed main restricted universe multiverse
deb http://mirrors.163.com/ubuntu/ jammy-backports main restricted universe multiverse
deb-src http://mirrors.163.com/ubuntu/ jammy main restricted universe multiverse
deb-src http://mirrors.163.com/ubuntu/ jammy-security main restricted universe multiverse
deb-src http://mirrors.163.com/ubuntu/ jammy-updates main restricted universe multiverse
deb-src http://mirrors.163.com/ubuntu/ jammy-proposed main restricted universe multiverse
deb-src http://mirrors.163.com/ubuntu/ jammy-backports main restricted universe multiverse

4 sudo apt-get update
5 sudo apt-get upgrade

以  上基本可以解决

**Comment by aresbit** [comment]
国内添加阿里源和网易云 安装失败需要再执行 sudo apt --fix-broken install
