### ISSUE TITLE
[BUG] 每次点击切换系统代理不生效，需要回到订阅，手动使用一次订阅，才会让系统代理的按钮生效

### ISSUE THREAD

**Issue by wujun4code** [clash-verge-rev/clash-verge-rev#1194]
### 问题描述 / Describe the bug

怀疑是设置页面点击切换的时候，并没有立刻调用保存设置的函数，直到下一次强制切换订阅，才真正去保存的设置。有没有一种可能增加一个再设置页面增加一个保存按钮，这样也可以节省性能，不至于每次操作一个 toggle 就保存一次配置，然后每次修改配置成功之后，弹窗显示几个关键开关当前的状态

> 设置保存成功，当前设置如下
系统代理：开
服务模式：开
Tun 模式：关
开机启动：开

谢谢。

### 复现步骤 / To Reproduce

- 先在设置页面点击，启用系统代理
- 查看 windows 系统代理，发现并没有启用
- 然后回到 clash verge 界面，点击订阅，手动使用一次任意的订阅
- 直到弹窗出现 订阅已切换
- 再回到 windows 系统设置页面就可以看到 代理已开启

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 Enterprise -23H2 -22631.3593

### 日志 / Log

暂无。

**Comment by AnyWAT** [comment]
Win 10 便携版（V1.6.5-1.6.6），右键系统托盘图标切换到系统代理，图标变色，查看 windows 系统代理已启用。

**Comment by wujun4code** [comment]
@AnyWAT 我这么操作之后，图标也变色了，
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/5119542/2211bd05-9da7-4100-ab6e-7ed9337b0ac7)

但是我去 windows 系统设置里面查看

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/5119542/572320d3-e5a9-410e-a66e-b04bf90e443d)

依旧没有设置成功。

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/5119542/4c5cc2b0-354c-45da-a0ba-6d8ed0887993)

而且我发现必须是 [管理员]权限启动 clash verge 才可以按照我 bug 描述的步骤设置系统代理。

**Comment by AnyWAT** [comment]
我的是 Win10x64 用户账户控制（UAC）是降了一级的
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37962734/d0c3bb12-a141-4aaf-b2d9-c78bb26b7b79)

**Comment by wujun4code** [comment]
我卸载了整个 clash verge 出现了一个问题，我再也无法开启系统代理了，我在卸载之前关掉了系统代理，然后我发现一直有一个后台在修改我的系统代理，如下

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/5119542/ba9cf078-2e4e-41c6-8c99-b49409f98546)
修改完之后，我关掉设置界面，但是重新打开，它又回到了这个状态
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/5119542/adf721c1-6d2c-48d7-97a5-89e6386df587)

求如何禁止这种行为？

**Comment by MystiPanda** [comment]
clash verge 卸载不会有任何残留，你应该检查是否有其他软件冲突

**Comment by wujun4code** [comment]
@MystiPanda 幸亏是专业选手，我通过如下方式排查，最终确认了是注册表的遗留问题。

### ProxyServer, ProxyEnable 注册表遗留

```powershell
 Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Internet Settings' -Name ProxyServer, ProxyEnable


ProxyServer  : 127.0.0.1:7890
ProxyEnable  : 0
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Interne
               t Settings
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion
PSChildName  : Internet Settings
PSProvider   : Microsoft.PowerShell.Core\Registry
```

然后需要手动删除 如上 2 个注册表的值。

### 删除 ProxySettingsPerUser

```powershell
 Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings' -Name ProxySettingsPerUser


ProxySettingsPerUser : 0
PSPath               : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
PSParentPath         : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\CurrentVersion
PSChildName          : Internet Settings
PSProvider           : Microsoft.PowerShell.Core\Registry
```

### 最后删除 dns

> 如果你的 clash 配置里面启用的 dns，那么这一步也需要执行，否则 127.0.0.1 会一直被注册表当作你的 dns server

```
 Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\*' -Name 'NameServer'
```
根据如上查到的所有 dns server 仔细肉眼排查出 `127.0.0.1` 然后找到对应注册表，给他删除。

这才算彻底清理完毕，不是 clash verge 的问题，是特么 windows 脑残的设定，历史遗留问题。这个注册表坑爹害人。

**Comment by wujun4code** [comment]
所以，如果你多次卸载 和 重装 clash verge 以及原版的 clash for windows 都有可能会出现这个问题，这个帖子还是有参考价值的。

**Comment by MystiPanda** [comment]
clash verge 没有动过 HKEY_LOCAL_MACHINE 下的注册表，大概率是cfw残留的

**Comment by DeAthBo** [comment]
我也有同样的问题,点击系统代理,但是没有开启成功,我排查我这并没有这些注册表
**不过我用着你教的切换订阅,退出重进方法开启成功.**
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/34346682/2c8a39d3-7b66-481f-afb4-889a7c03a9c6)
关于1.6.5->1.6.6,我这一直覆盖安装升级不成功,(我默认安装在C盘),所以卸载了1.6.5再安装1.6.6,配置啥的还都还在,然后就有这个点击系统代理的问题了

**Comment by AnyWAT** [comment]
免费绿色的 Autoruns 可定位系统开机自启、服务等的文件及注册表，或许能找出问题？
