### ISSUE TITLE
[BUG] Mac上退出当前App之后，不会删除已经设置在系统上代理，导致电脑网络不可用

### ISSUE THREAD

**Issue by coulsontl** [clash-verge-rev/clash-verge-rev#1195]
### 问题描述 / Describe the bug

如题：在Mac上退出当前App之后，不会清除已经设置在系统上代理，导致电脑网络不可用

### 复现步骤 / To Reproduce

必现

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

12.7.5 (21H1222) Intel版本

### 日志 / Log

无

**Comment by summerwind6** [comment]
win的版本也是的，刚开始还以为电脑坏了

**Comment by xzhang8102** [comment]
TUN模式开启之后，关闭TUN，卸载服务，退出cvr，重启Mac，也不能上网

**Comment by xzhang8102** [comment]
> TUN模式开启之后，关闭TUN，卸载服务，退出cvr，重启Mac，也不能上网

按照[文档faq](https://clash-verge-rev.github.io/faq/macos.html#macos)修改了设置之后，又把系统服务重新安装了，现在正常了

**Comment by wzrzt** [comment]
我试验出来的，先关掉TUN，打开系统代理，然后关上系统代理，再退出，就没事了

**Comment by flyflas** [comment]
建议使用tun模式，卡系统代理其他客户端也都有这种情况。

**Comment by Nioy** [comment]
我也遇到了，开启服务模式之后，推掉cvr，不能正常上网了

**Comment by Nioy** [comment]
> 我试验出来的，先关掉TUN，打开系统代理，然后关上系统代理，再退出，就没事了

按照你这个反式试了，也不行

**Comment by Nioy** [comment]
> 建议使用tun模式，卡系统代理其他客户端也都有这种情况。

这样的话，这个软件只能一直开着了

**Comment by wonfen** [comment]
试试最新版，应该已经修复了。如果还不行请开新issue
