### ISSUE TITLE
[BUG] 软件内无法更新软件

### ISSUE THREAD

**Issue by martjay** [clash-verge-rev/clash-verge-rev#1196]
### 问题描述 / Describe the bug

即使我已经开了全局模式，仍然无法在软件内实现更新

### 复现步骤 / To Reproduce

希望解决问题

![Snipaste_2024-06-14_08-03-19](https://github.com/clash-verge-rev/clash-verge-rev/assets/44982189/69eabc1b-c0b7-4ebe-bc03-7977a27e0f43)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 11 X64

### 日志 / Log

不知道怎么发

**Comment by ValueXu** [comment]
看起来像代理挂了
