### ISSUE TITLE
[BUG] 无法更新。

### ISSUE THREAD

**Issue by meinaOfficial** [clash-verge-rev/clash-verge-rev#1199]
### 问题描述 / Describe the bug

对于非默认安装位置的用户，按照更新日志里面手动下载安装包，根据提示选择安装前卸载，无法正常卸载。导致无法安装新版本。

### 复现步骤 / To Reproduce

希望推出新的安装包

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 x64

### 日志 / Log

无

**Comment by wonfen** [comment]
因为换了publisher，自动升级无法识别到之前安装的路径。卸载重装即可。以后不会有问题。

**Comment by Jimmy20220531** [comment]
友情提示：直接在电脑系统里的“程序和功能”选中卸载旧版本，不要选择“删除用户数据”。然后按照原路径安装新版本，这样打开新版本后各项设置全部保留。
