### ISSUE TITLE
[BUG] 在线Web UI[metacubexd]无法连接和解决

### ISSUE THREAD

**Issue by LennoC** [clash-verge-rev/clash-verge-rev#1200]
### 问题描述 / Describe the bug

首次通过软件配置自带的`https://d.metacubex.one/#?hostname=%host&port=%port&secret=%secret`无法正常连接在线metacubex面板，会一直提示Failed to fetch。yacd在线面板则正常使用。
Win10+Chrome 108(cent broswer)
#### 解决方案：
搜索issue发现有同样情况，此时尝试在hostname那里填入完整的`http://127.0.0.1`或者ui后端地址填入`http://127.0.0.1:9097`，则能正常连接，此后因为有cookies有没有加http都能正常使用在线面板了。
#### 建议：
默认配置的hostname那里修改为`hostname=http://%host&port=%port&secret=%secret`
同时建议使用Cloudflare Pages: `https://metacubexd.pages.dev` 该面板一直随代码发布更新，原来的`GH Pages Custom Domain: http://d.metacubex.one/` 停留在1.129一直未更新。

### 复现步骤 / To Reproduce

清除metacube面板的cookies和缓存，hostname只写`127.0.0.1`，我这里环境100%复现无法登入，提示failed to fetch.
按上所说解决方案则正常使用。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10

### 日志 / Log

无

**Comment by dongchengjie** [comment]
用这个
```
https://metacubex.github.io/metacubexd/#/setup?http=true&hostname=%host&port=%port&secret=%secret
```

**Comment by LennoC** [comment]
> 用这个
> 
> ```
> https://metacubex.github.io/metacubexd/#/setup?http=true&hostname=%host&port=%port&secret=%secret
> ```

建议将默认的配置更换。

**Comment by dongchengjie** [comment]
> > 用这个
> > ```
> > https://metacubex.github.io/metacubexd/#/setup?http=true&hostname=%host&port=%port&secret=%secret
> > ```
> 
> 建议将默认的配置更换。

你再仔细看看issue？？？

**Comment by zhangm365** [comment]
我的 mihomo 服务启动正常，但是通过这个访问一直报错 Failed to fetch：
https://metacubex.github.io/metacubexd/#/setup?http=true&hostname=%host&port=%port&secret=%secret

**Comment by dongchengjie** [comment]
> 我的 mihomo 服务启动正常，但是通过这个访问一直报错 Failed to fetch： https://metacubex.github.io/metacubexd/#/setup?http=true&hostname=%host&port=%port&secret=%secret

t

检查浏览器插件，ublock origin的规则会默认很多拦截面板的请求

**Comment by zhangm365** [comment]
> > 我的 mihomo 服务启动正常，但是通过这个访问一直报错 Failed to fetch： https://metacubex.github.io/metacubexd/#/setup?http=true&hostname=%host&port=%port&secret=%secret
> 
> t
> 
> 检查浏览器插件，例如ublock origin的规则会默认很多拦截面板（包括xd、rd等）的请求

我把插件都关掉了，还是报错 Failed to fetch。
请问 mihomo 这个服务是正常的吧？
```bash
curl -H "Authorization: Bearer 123456" http://127.0.0.1:9090
{"hello":"mihomo"}
```
