### ISSUE TITLE
请问下项目克隆后进行打包，报错：path matching sidecar/clash-meta-aarch64-apple-darwin not found.是什么原因，怎么解决呢？

### ISSUE THREAD

**Issue by fxzer** [clash-verge-rev/clash-verge-rev#1204]
### 问题描述 / Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/68853957/bea199d5-42f3-4592-8e04-64c6a52a48d8)

### 复现步骤 / To Reproduce

gc git@github.com:clash-verge-rev/clash-verge-rev.git
cd  clash-verge-rev
pnpm i
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
tauri build

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

 OS: macOS Sonoma 14.5 arm64

### 日志 / Log

error: failed to run custom build command for `clash-verge v1.6.6 (/Users/fxzer/n/clash-verge-rev/src-tauri)`

Caused by:
  process didn't exit successfully: `/Users/fxzer/n/clash-verge-rev/src-tauri/target/debug/build/clash-verge-183d7660da110d1e/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rustc-cfg=dev
  path matching sidecar/clash-meta-aarch64-apple-darwin not found.
warning: build failed, waiting for other jobs to finish...
 ELIFECYCLE  Command failed with exit code 101.

**Comment by wonfen** [comment]
不好好看文档

**Comment by fxzer** [comment]
大佬，文档实在没翻到，麻烦给个链接，谢谢🙏

**Comment by AnyWAT** [comment]
屏幕右上方的 Wiki？

**Comment by dongchengjie** [comment]
contributing你看没？npm run check啊
