### ISSUE TITLE
[BUG] steamdeck无法使用

### ISSUE THREAD

**Issue by kabutoki** [clash-verge-rev/clash-verge-rev#1205]
### 问题描述 / Describe the bug

steamdeck无法使用tun模式并且无法使用 rpm deb格式之前的 appimage倒是可以打开 但是不能授权和走流量
https://clash-verge-rev.github.io/install.html这里的看了过不让安装

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

 steamos

### 日志 / Log

06-15 02:58:57ERROR
Start Redir server error: operation not permitted
06-15 02:58:57ERROR
Start TProxy server error: operation not permitted
06-15 03:01:53ERROR
Start Redir server error: operation not permitted
06-15 03:01:53ERROR
Start TProxy server error: operation not permitted

**Comment by bigsaltyfishes** [comment]
这个不是 BUG，你应该整个 AppImage 以 root 运行，当然我不推荐这么做，你可以手动安装服务，然后以服务模式启动内核。
这个 issue 里面有说明提权的问题：https://github.com/AppImage/AppImageKit/issues/146
