### ISSUE TITLE
[BUG] Windows端 ,开启TUN模式,每次重启电脑,或者重新开启TUN, 总是会先断网,过个10几秒才重新联网,导致一些开机启动的应用程序例如:onedrive,icloud,需要反复登录,希望能解决一下!!!

### ISSUE THREAD

**Issue by AQRyan66** [clash-verge-rev/clash-verge-rev#1209]
### 问题描述 / Describe the bug

[BUG] Windows端 ,开启TUN模式,每次重启电脑,或者重新开启TUN, 总是会先断网,过个10几秒才重新联网,导致一些开启启动的应用程序例如:onedrive,icloud,需要反复登录,希望能解决一下!!!

### 复现步骤 / To Reproduce

[BUG] 

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11

### 日志 / Log

无

**Comment by AnyWAT** [comment]
？试试用休眠替代关机，即使休眠后掉电，一旦上电开机驻留程序很快恢复。

**Comment by AQRyan66** [comment]
> ？ 试试用休眠替代关机，即使休眠后掉电，一旦上电开机驻留程序很快恢复。

我是双系统，经常要来回切换，所以没有休眠的场景，问题出在开启TUN会切换网卡，切换网卡的时候断网时间太长了，导致的登录服务需要重新登录

**Comment by LeanC0de** [comment]
铁铁你的Windows系统开启tun模式以后任务栏会显示小地球（无法连接互联网）吗？好奇是不是只有我的会这样：）

**Comment by AQRyan66** [comment]
> 铁铁你的Windows系统开启tun模式以后任务栏会显示小地球（无法连接互联网）吗？好奇是不是只有我的会这样：）

就是我描述的断网
