### ISSUE TITLE
[BUG] Linux下关闭GUI后内存不会释放

### ISSUE THREAD

**Issue by Littleweisheit** [clash-verge-rev/clash-verge-rev#121]
### Describe the bug

Win上关闭UI后内存占用很小，但是linux上没有释放GUI的内存

### To Reproduce

点击关闭窗口

### Platform

Linux

### System Version

Linux

### Software Version

1.4.4

### Log

![图片](https://github.com/clash-verge-rev/clash-verge-rev/assets/11383988/896ec1c6-c79b-452a-aa02-9f62b914ede2)

**Comment by wonfen** [comment]
用最新版试试。

**Comment by wonfen** [comment]
无进一步反馈，关闭了。

**Comment by Littleweisheit** [comment]
最新版测试仍然存在，安装的是amd64.deb的版本。系统是debian+kde。

**Comment by MystiPanda** [comment]
似乎是Tauri上游的问题
