### ISSUE TITLE
[BUG] 在安装后首次启动提示使用了Tun模式, 但是又没有开启服务, 导致启动失败

### ISSUE THREAD

**Issue by guan-mian** [clash-verge-rev/clash-verge-rev#1210]
### 问题描述 / Describe the bug

在使用1.6.6安装版或压缩包版本启动失败，会提示使用了Tun模式，但没有开启服务，不知道是否是因为本机的其他Clash使用了Tun模式导致，但是在关闭其他Clash的Tun模式后还是会有这个提示
![启动报错](https://github.com/clash-verge-rev/clash-verge-rev/assets/79733820/bf0e6db5-43d0-48db-896d-e5f9fc6345ad)

### 复现步骤 / To Reproduce

每次启动都是这样的提示

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

23H2

### 日志 / Log

，

**Comment by guan-mian** [comment]
1.6.5版本正常启动，并且从1.6.5升级后也是正常，只有单独下载1.6.6版本会出现这个问题

**Comment by AnyWAT** [comment]
> 从1.6.5升级后也是正常
> 使用1.6.6安装版或压缩包版本

一台机器上整2-3个同一程序，有啥必要？尤其是稀里糊涂都不知道是哪个的服务在运行的时候。。。
应该是升级后正常的服务一直在运行。
简单粗暴，要么保留升级的那个，卸载删除其它的；要么启动升级的，关闭并卸载服务，再启动其它的。

**Comment by ikaoda** [comment]
> > 从1.6.5升级后也是正常
> > 使用1.6.6安装版或压缩包版本
> 
> 一台机器上整2-3个同一程序，有啥必要？尤其是稀里糊涂都不知道是哪个的服务在运行的时候。。。 应该是升级后正常的服务一直在运行。 简单粗暴，要么保留升级的那个，卸载删除其它的；要么启动升级的，关闭并卸载服务，再结束整个程序，然后启动其它的。

我是直接卸载之前版本后，安装Clash Verge Rev Alpha版出现的这个问题，打开就弹出这个提示，无法启动程序。

**Comment by AnyWAT** [comment]
莫非卸载旧版并没有卸载掉相关的服务？
Win10 的任务管理器可检查是否存在孤立的 clash-XXX.exe 服务进程。。。
绿色免费的 Autoruns 可管理 Windows 系统的开机启动、服务。。。并直接定位注册表

**Comment by MystiPanda** [comment]
alpha 版本最新添加的禁止管理员权限启动的功能，没有考虑管理员用户组，后续会调整的，用不了的话用正式版就行

**Comment by rebecca554owen** [comment]
@MystiPanda 等待发布新版本。

**Comment by guan-mian** [comment]
> > 从1.6.5升级后也是正常
> > 使用1.6.6安装版或压缩包版本
> 
> 一台机器上整2-3个同一程序，有啥必要？尤其是稀里糊涂都不知道是哪个的服务在运行的时候。。。 应该是升级后正常的服务一直在运行。 简单粗暴，要么保留升级的那个，卸载删除其它的；要么启动升级的，关闭并卸载服务，再结束整个程序，然后启动其它的。

之前那个有一些问题, 偶尔会出现没有网络的问题, 后来发现是Tun服务莫名其妙被卸载过

**Comment by AnyWAT** [comment]
W10 系统没有诸如360、管家之流的国产，便携版正常着呢。
