### ISSUE TITLE
[Feature] 加入一键测试速度&流媒体检测的功能

### ISSUE THREAD

**Issue by dong-dong6** [clash-verge-rev/clash-verge-rev#1212]
### 功能描述 / Feature description

类似于v2的测速，流媒体检测可以放一下，测速是值得添加的

### 使用场景 / Use case

新加节点时进行简单测试

**Comment by rebecca554owen** [comment]
@dong-dong6 流媒体检测自行写脚本吧，一直需要维护更新。

**Comment by dong-dong6** [comment]
但是测速功能是值得添加的

**Comment by dongchengjie** [comment]
#1022
