### ISSUE TITLE
[BUG] 长时间开着clash verge rev就会出现关不掉的情况

### ISSUE THREAD

**Issue by loveznk** [clash-verge-rev/clash-verge-rev#1218]
### 问题描述 / Describe the bug

长时间开着clash verge rev就会出现关不掉的情况，必须通过结束进程才能强制关掉

### 复现步骤 / To Reproduce

![photo_2024-06-16_16-47-19](https://github.com/clash-verge-rev/clash-verge-rev/assets/107742038/739d34fb-cadb-46e2-bda4-23f8c53a2b99)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 专业版

### 日志 / Log

![photo_2024-06-16_16-47-19](https://github.com/clash-verge-rev/clash-verge-rev/assets/107742038/47b03bf2-3738-4bb3-af8b-a5bd39312af1)

**Comment by AnyWAT** [comment]
Windows 设置——应用，应用和功能，修改进而更新：
msedgewebview2.exe 版本 126.0.2592.56

**Comment by loveznk** [comment]
> Windows 设置——应用，应用和功能，修改进而更新： msedgewebview2.exe 版本 126.0.2592.56

谢谢解答。我之前也以为是这个问题，所以我更新到了最新版本，但是问题依然存在。
![微信截图_20240616174207](https://github.com/clash-verge-rev/clash-verge-rev/assets/107742038/3e7bce88-cc74-4c4a-98d4-f07fd5b8d41d)

**Comment by AnyWAT** [comment]
系统太忙了？试试：
Windows 设置——应用——启动：关闭不必需的
Windows 设置——隐私——后台应用：关闭不必需的

**Comment by huangyy126** [comment]
桌面右下角的图标，右击勾选系统代理或关闭系统代理，长时间没有反应，图标颜色也没变；（系统win10）

**Comment by huangyy126** [comment]
1.66版本——桌面右下角的图标，右击勾选系统代理或关闭系统代理，长时间没有反应，图标颜色也没变；而且右击退出不了，只能在任务管理器中结束应用（系统win10，虽然电脑较旧，但其他软件大多没有问题）

**Comment by AnyWAT** [comment]
12、3年前的兼容机仍正常呢。
系统上没有国产诸如360、管家之流？

**Comment by huangyy126** [comment]
1.66版本——偶尔出现——桌面右下角的图标，右击勾选系统代理或关闭系统代理，长时间没有反应，图标颜色也没变；而且右击退出不了，只能在任务管理器中结束应用——（win10，可能和电脑里的360卫士极速版有关吧，导致软件有时卡死没反应，使用时咱还是尽量先关闭这类软件吧）

**Comment by loveznk** [comment]
> 12、3年前的兼容机仍正常呢。 系统上没有国产诸如360、管家之流？

没有安装360、管家，装的是火绒，安装原版win11系统后测试了几天，现在没有出现之前的情况了。感觉还是之前装的系统有问题。

**Comment by huangyy126** [comment]
1.66版本——偶尔出现——桌面右下角的图标，右击勾选系统代理或关闭系统代理，长时间没有反应，图标颜色也没变；而且右击退出不了，只能在任务管理器中结束应用（退出360卫士极速版之后，还是偶尔发生此类现象，也可能和我老旧的电脑有关吧，但以前的Clash for Windows又是一直正常的）

**Comment by loveznk** [comment]
> 1.66版本——偶尔出现——桌面右下角的图标，右击勾选系统代理或关闭系统代理，长时间没有反应，图标颜色也没变；而且右击退出不了，只能在任务管理器中结束应用（退出360卫士极速版之后，还是偶尔发生此类现象，也可能和我老旧的电脑有关吧，但以前的Clash for Windows又是一直正常的）

是的，我之前出现的情况和你一模一样，直到我安装了原版windows系统才解决，我估计是咱们用的修改或者精简系统的缘故吧。你可以安装原版windows系统试试，看能否解决这个问题。

**Comment by wonfen** [comment]
我们发现有一部分原因是因为写了错误的系统代理绕过导致的；使用最新的alpha版本，对系统代理不规范的写法做了约束。

**Comment by AnyWAT** [comment]
Clash.Verge_1.6.6_x64_portable：
Alpha 版本较 v1.6.6 缺失了这2个？

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37962734/0f54e881-df83-4233-93c1-1cf8cf98c38a)

clash-verge-service.exe Alpha 版本内存如下图，v1.6.6 貌似不到 800K

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37962734/c08af903-f949-4d86-bc23-d080dbfa2b95)

**Comment by MystiPanda** [comment]
@AnyWAT 不要在别人issue下面乱回复好吗，有问题自己开issue

**Comment by musuwer** [comment]
我也遇到了这个问题，之前使用都没有，最近突然这样点击关闭没反应
