### ISSUE TITLE
[BUG] 最新分支编译打包报错

### ISSUE THREAD

**Issue by Lins** [clash-verge-rev/clash-verge-rev#1221]
### 问题描述 / Describe the bug

 最新分支编译打包报错

### 复现步骤 / To Reproduce

按照步骤安装rust、node 等。
安装NSIS ,且加入环境变量 C:\Program Files (x86)\NSIS
同时下载nsis_tauri_utils.dll 插件放入 C:\Program Files (x86)\NSIS\Plugins\x86-unicode 目录和C:\Program Files (x86)\NSIS\Plugins\x86-ansi ，以及C:\Program Files (x86)\NSIS\Plugins\。
编译打包报错。看下面日志

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

     Running makensis.exe to produce F:\VSCodeProject\clash-verge-rev\src-tauri\target\release\bundle\nsis\Clash Verge_1.6.6_x64-setup.exe
Plugin function not found, cannot call nsis_tauri_utils::RunAsUser
Error in script "F:\VSCodeProject\clash-verge-rev\src-tauri\target\release\nsis\x64\installer.nsi" on line 332 -- aborting creation process
       Error failed to bundle project: `系统找不到指定的文件。 (os error 2)`
 ELIFECYCLE  Command failed with exit code 1.

**Comment by dongchengjie** [comment]
```
cargo install --git https://github.com/tauri-apps/tauri --branch 1.x tauri-cli
```
