### ISSUE TITLE
[BUG] centos7和centos8系统都出现安装缺少依赖的问题

### ISSUE THREAD

**Issue by itstudygeen** [clash-verge-rev/clash-verge-rev#1223]
### 问题描述 / Describe the bug

1.6.6版本会出现缺少依赖的问题
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/23158585/56a80ea6-51c7-4f0b-af8d-8f9438d49b51)

1.6.5版本会出现安装显示###的问题
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/23158585/ae4083aa-3b2d-4845-8777-4eac588d5274)

### 复现步骤 / To Reproduce

rpm -ivh clash-verge-1.6.5-1.x86_64.rpm

rpm -ivh clash-verge-1.6.6-1.x86_64.rpm

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

CentOS-7-x86_64-2009

### 日志 / Log

rpm -ivh clash-verge-1.6.6-1.x86_64.rpm 
error: Failed dependencies:
	libayatana-appindicator3.so.1()(64bit) is needed by clash-verge-0:1.6.6-1.x86_64

**Comment by wonfen** [comment]
自己装依赖： https://github.com/clash-verge-rev/clash-verge-rev/issues/1144#issuecomment-2156026736

**Comment by 491561009** [comment]
> 自己装依赖： https://github.com/clash-verge-rev/clash-verge-rev/issues/1144#issuecomment-2156026736

我在centos8上遇到了同样的问题，使用yum安装了libappindicator-gtk3.x86_64后还是没有解决

**Comment by LilZhang** [comment]
same issue

**Comment by taurusduan** [comment]
提供的方法毫无作用！

**Comment by Yeashin-Fu** [comment]
我也尝试了各种方式按照依赖，并不奏效

系统版本 CentOS-7-x86_64-2009
