### ISSUE TITLE
设置系统设置里面的绕过代理设置，提示无效的代理绕过格式[BUG] 

### ISSUE THREAD

**Issue by xzchsia** [clash-verge-rev/clash-verge-rev#1225]
### 问题描述 / Describe the bug

设置系统设置里面的绕过代理设置，提示无效的代理绕过格式[BUG] 
因为单位内网连接（连接需要登录个人账号密码方式），开启了1.6.6最新版本，使用了狗狗加速的配置文件，访问单位的网站，会出现连接失败，想着设置绕过代理方式来进行直连，发现提示这个错误。

### 复现步骤 / To Reproduce

如上描述

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10

### 日志 / Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/22785554/6de1e85c-6c6c-45ee-a19a-bb2ad9d82a20)

[TCP] dial 🎯 全球直连 (match DomainSuffix/cn) 127.0.0.1:8912(msedge.exe) --> www.zjiet.edu.cn:80 error: connect failed: dial tcp 183.129.134.118:80: i/o timeout\nconnect failed: dial tcp [2001:da8:e03a::c0a8:25b]:80: connectex: A socket operation was attempted to an unreachable network.
[TCP] dial 🎯 全球直连 (match DomainSuffix/cn) 127.0.0.1:9062(msedge.exe) --> i.zjiet.edu.cn:443 error: connect failed: dial tcp 122.224.251.76:443: i/o timeout
06-17 10:36:33WARNING
[TCP] dial 🎯 全球直连 (match DomainSuffix/cn) 127.0.0.1:9077(msedge.exe) --> i.zjiet.edu.cn:443 error: connect failed: dial tcp 122.224.251.76:443: i/o timeout
06-17 10:36:33INFO
[TCP] 127.0.0.1:9080(msedge.exe) --> edge.microsoft.com:443 match DomainKeyword(microsoft) using Ⓜ️ 微软服务[DIRECT]

**Comment by MystiPanda** [comment]
alpha已经修了

**Comment by xzchsia** [comment]
收到，谢谢

**Comment by MrtianYs** [comment]
[校验正则](https://github.com/clash-verge-rev/clash-verge-rev/blob/17765bdba9dcd6a714f6399feb22505fb7fd79cb/src/components/setting/mods/sysproxy-viewer.tsx)
@MystiPanda 
127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,*.crashlytics.com,<local> 这个校验也过不了

**Comment by MrtianYs** [comment]
> alpha已经修了

`javascript
// 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,*.crashlytics.com,<local>
`
这种校验也不行
