### ISSUE TITLE
[Feature] 有计划支持webdav网盘功能吗？

### ISSUE THREAD

**Issue by efeire** [clash-verge-rev/clash-verge-rev#1227]
### 功能描述 / Feature description

支持webdav协议存放配置文件

### 使用场景 / Use case

因为有多台机器使用同一套配置文件，一台机器修改了某个配置，其他机器希望也能同步修改。

**Comment by wonfen** [comment]
你把配置存放文件夹设置为自动同步可以实现你想要的功能。

**Comment by liouxy** [comment]
webdav 的文件是不是可以直接拿到类似 http://192.168.0.1/abc/d.yaml 这样的链接哦

**Comment by wonfen** [comment]
已完成。
