### ISSUE TITLE
[BUG] 系统代理中，代理绕过兼容有问题

### ISSUE THREAD

**Issue by gitlayzer** [clash-verge-rev/clash-verge-rev#1230]
### 问题描述 / Describe the bug

在设置代理绕过时，关于 * 兼容性出现了问题

### 复现步骤 / To Reproduce

比如我想绕过 *.aliyun.com，此时点击保存会出现无效的代理模式绕过
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/77761224/8c5af114-db98-4881-a237-fdebce085a55)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

v1.6.6

### 日志 / Log

None

**Comment by AlphaAnother** [comment]
确实有这个问题，我设置不绕过192.168.*和10.*，但是当前绕过还是有这俩，删掉后重新开关系统代理又回来了。

**Comment by TullyMonster** [comment]
似乎也无法处理域名中有连接符的情况，如：`cc-api-data.adobe.io`

**Comment by SukkaW** [comment]
Duplicated #1225 
Already fixed in ae784cb985dfd89e3555005ad348e779e92c6874

**Comment by gitlayzer** [comment]
> 确实有这个问题，我设置不绕过192.168.*和10.*，但是当前绕过还是有这俩，删掉后重新开关系统代理又回来了。

确实 alpha 版本已经修复

**Comment by AlphaAnother** [comment]
> > 确实有这个问题，我设置不绕过192.168._和10._，但是当前绕过还是有这俩，删掉后重新开关系统代理又回来了。
> 
> 确实 alpha 版本已经修复

你使用的是什么版本？我是x64正常安装版，alpha版本下载的应该是95c23a9这个commit的，不管是安装还是rar抽出来直接运行，实测还是会覆盖bypass设置。
