### ISSUE TITLE
[BUG] 特定节点检测无法正确使用配置文件内的检测链接以验证状态

### ISSUE THREAD

**Issue by AlphaAnother** [clash-verge-rev/clash-verge-rev#1232]
### 问题描述 / Describe the bug

我有几个节点作为不同办公地点的内网隧道，通过配置规则在代理组里切换来进入各个内网。在配置文件里我设置它们的健康检测链接为国内的地址，但是在使用中它们被程序默认的四个1覆盖了，而四个1并非一直可以直连，这就导致这几个内网隧道节点可以正常使用时，健康检测却时不时显示为error。

### 复现步骤 / To Reproduce

如上，在一个国内节点上使用延迟检测即可复现。如果效果不好可以把默认检测链接改为四个八。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11 23H2 22631.3737

### 日志 / Log

健康检测并没有日志。

**Comment by dongchengjie** [comment]
程序并不会覆盖配置文件的测试地址，也不会影响health check，他只充当client的作用
