### ISSUE TITLE
[BUG]  Idea 中谷歌翻译功能无法代理

### ISSUE THREAD

**Issue by 944508663** [clash-verge-rev/clash-verge-rev#1233]
### 问题描述 / Describe the bug

使用本软件开启规则代理，无法代理idea 软件里的谷歌翻译

### 复现步骤 / To Reproduce

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/50687732/d2982e66-f90a-4ccb-ac18-4287cc7940d5)
软件设置为规则代理，日志里面没有关于谷歌翻译的地址
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/50687732/43cea073-52b7-457b-902c-0aca0701f932)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/50687732/f49e82d6-b98b-4c9e-8468-3c969007a4ec)

然而，使用v2rayN 却可以正常代理
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/50687732/8d252d43-9ea8-42b3-baa4-71804455335f)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

null

**Comment by wonfen** [comment]
添加相关的代理规则，用机场的话，找机场。

**Comment by dongchengjie** [comment]
IDE默认就不走系统代理，用TUN
一不贴IDE代理配置，二不贴clash服务状态，三不贴日志
说v2可以结果你看你贴了个什么 多的不说自个想办法 行业素养

**Comment by aflyingnoob** [comment]
设置里面http proxy里面写上 127.0.0.1 7897代理

**Comment by tagnpeng** [comment]
**问题描述 / Describe the bug**
clash设置
<img width="840" alt="image" src="https://github.com/user-attachments/assets/2709bd34-b073-4962-901c-e8c9d98991c7">
<img width="840" alt="image" src="https://github.com/user-attachments/assets/e9dce918-a1bb-4719-8242-b0333feeed5c">

idea设置
<img width="982" alt="image" src="https://github.com/user-attachments/assets/12e5f86d-a01f-4b38-95c7-f4672df7a888">

**复现步骤 / To Reproduce**
<img width="232" alt="image" src="https://github.com/user-attachments/assets/faefad82-d77a-4a98-b3a4-287547d1283e">


**相关日志**
在我运行翻译软件的时候日志中是有对翻译进行代理,但是不知为何翻译错误,切到另外的代理软件却可以正常代理,不是很懂,如果有需要我提供其他信息的话可以回复我,谢谢
<img width="789" alt="image" src="https://github.com/user-attachments/assets/a3904a8b-ce06-4dda-988f-6e0c231c5b8f">

**操作系统 / OS**
mac m1

**操作系统版本 / OS Version**
14.6.1 (23G93)
