### ISSUE TITLE
[BUG] 左上角重复图标

### ISSUE THREAD

**Issue by fxzer** [clash-verge-rev/clash-verge-rev#1234]
### 问题描述 / Describe the bug

<img width="1512" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/68853957/31b992c3-371e-488e-956d-0648fd1f4138">

### 复现步骤 / To Reproduce

把图标设置为彩色后，看的更明显

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

 OS: macOS Sonoma 14.5 arm64

### 日志 / Log

 xxx

**Comment by dongchengjie** [comment]
https://clash-verge-rev.github.io/faq/macos.html#macos_1

**Comment by nmweizi** [comment]
同样问题，版本Sonoma 14.5，用下面的方法不管用，还是图标重叠

```
问题原因: macOS Sonoma 的系统 BUG。
解决方案: 系统偏好设置 -> 显示器，调整一下显示器分辨率，然后再调回去。
```
