### ISSUE TITLE
[BUG] 关于订阅的问题

### ISSUE THREAD

**Issue by gitlayzer** [clash-verge-rev/clash-verge-rev#1235]
### 问题描述 / Describe the bug

我的订阅一直在使用一个节点，但是在机场流量监控中，却看到了两个节点在使用流量，并且这个订阅我只在 Clash 中使用了，是 Clash 有什么机制嘛？附图

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/77761224/ff8d3f96-27df-4a31-a64a-14552a79a825)

### 复现步骤 / To Reproduce

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/77761224/9f95c21e-69e8-4fd7-a3af-7bb3814d4a5f)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

v1.6.6-alpha

### 日志 / Log

。。。

**Comment by wonfen** [comment]
没有什么机制，找找机场的问题。
