### ISSUE TITLE
[BUG] 自定义托盘图标，设置后与原图差别特别大

### ISSUE THREAD

**Issue by yzxzz** [clash-verge-rev/clash-verge-rev#1236]
### 问题描述 / Describe the bug

自定义托盘图标，设置后与原图差别特别大

### 复现步骤 / To Reproduce

1.打开面板-设置-界面设置-常规托盘图标/系统代理托盘图标/tun模式托盘图标
2.浏览-选择图标文件

目前测试下来macOS无此问题，仅在Windows10和Windows11 系统上发现，图片格式选择ico和png都试过都有此现象

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

系统：Windows11  10.0.26100.712

### 日志 / Log

截图如下：
<img width="1170" alt="图片" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/40624194/381af693-95ab-4d99-9434-ac4ac554e1c1">

这里提供原图文件
![图片](https://github.com/clash-verge-rev/clash-verge-rev/assets/40624194/b797299c-3625-443d-96da-63d25f0f909b)

**Comment by dongchengjie** [comment]
https://www.bilibili.com/video/BV1bw41117xL/
糊不糊受图片分辨率、屏幕DPI、显示缩放影响。
macos上，使用了Retina显示技术，加上采用统一屏幕缩放机制，减少了应用程序在不同分辨率下显示不一致。windows上就拉跨了点。
在你那边模糊的图，我这边就清晰的很。你可以尝试转换成ico，但不一定有效。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/c88dc433-4a8e-4188-bc07-ad8fad1cf6ce)

**Comment by yzxzz** [comment]
转换为ico格式后依旧不理想
<img width="1183" alt="图片" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/40624194/d806f176-98a5-4d34-9207-e9a9eb023d75">

看效果感觉是被压成16色的图像了

显示设备分辨率1920*1080 缩放100%

**Comment by windwhim** [comment]
我也有遇到此问题，请问一下后来解决了吗，下面是替换后的效果：
![image](https://github.com/user-attachments/assets/dce821de-51a0-46a8-adce-97b51c5c3e6c)
由于限制，无法上传ico格式图标，设置时已经将该png图片转为256*256大小ico
![clash_yellow](https://github.com/user-attachments/assets/319e5b9e-1913-4a30-9d5f-6486f474fd8e)

**Comment by homer365** [comment]
512✖512转换成ico以后，还是显示特别小，还不如网上下载的64*64的ico大 

<img width="70" height="74" alt="Image" src="https://github.com/user-attachments/assets/9488d860-59a6-4451-9225-f8eac1c5b614" />  

<img width="74" height="62" alt="Image" src="https://github.com/user-attachments/assets/73a33917-69a3-426a-996c-7d40d4fe2ad6" />

**Comment by homer365** [comment]
512✖512转换成ico以后，发现是 256 ✖ 256 的蓝猫，但大小不如64*64的红色猫，ico的显示有些问题吧
