### ISSUE TITLE
[Feature] 希望可以在添加订阅的时候可以配置自定义socks5或http代理

### ISSUE THREAD

**Issue by 0x8001** [clash-verge-rev/clash-verge-rev#1237]
### 功能描述 / Feature description

希望可以在添加订阅的时候可以配置自定义socks5或http代理
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/117440557/24b05ce7-c200-4d8b-b8ad-08150918f101)

### 使用场景 / Use case

现在很多规则都是在GitHub上，当配置文件没有下载的时候并不能启动代理，然后下载Provider又需要代理，这时会陷入死循环，只能去找个没有规则的代理先连上下载配置

**Comment by MystiPanda** [comment]
clash 启动之后 provider 下载会自动走 clash 代理的，没有启动之前，你设置代理又有什么用呢，既然你已经有可以设置的代理了，那下载 GitHub 上的文件还会有问题吗

**Comment by MystiPanda** [comment]
这种情况你应该考虑使用反代来加速下载，比如 mirror.ghproxy.com，jsdelivr 之类的

**Comment by AnyWAT** [comment]
试试：[GitHub Hosts](https://github.com/ineo6/hosts)
