### ISSUE TITLE
[BUG] 按住Ctrl+J会调出浏览器下载弹窗

### ISSUE THREAD

**Issue by bellongyan** [clash-verge-rev/clash-verge-rev#1239]
### 问题描述 / Describe the bug

在使用的过程中，如果使用Ctrl+J的快捷键会调出浏览器中的下载页的弹窗，虽然是基于Tauri开发，但是应该可以设置为不触发的吧

### 复现步骤 / To Reproduce

在应用的任意页面按住Ctrl+J的快捷键便会出现浏览器的下载弹窗，如图所示

![Snipaste_2024-06-19_22-40-01](https://github.com/clash-verge-rev/clash-verge-rev/assets/42709091/caf737bd-284e-450a-b297-d6f63c92547d)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

22H2

### 日志 / Log

无

**Comment by AnyWAT** [comment]
Ctrl shift S 呢？
貌似因 WebView2 也与 Microsoft Edge 的快捷键匹配？

**Comment by bellongyan** [comment]
> Ctrl shift S 呢？ 貌似因 WebView2 也与 Microsoft Edge 的快捷键匹配？ 使用了 WebView2 的迷雾通也有 Ctrl+J 的弹窗，但 MSN 天气却没有。

刚刚试了一下，我这里没有反应，目前我这只发现了Ctrl+J的快捷键会触发
