### ISSUE TITLE
[BUG] ACL4SSR 似乎会导致 Clash-verge 无法与内核（？）通信？

### ISSUE THREAD

**Issue by ShionKanagawa** [clash-verge-rev/clash-verge-rev#124]
### Describe the bug

如题，这个问题目前是可以在 Linux 上接近 100% 复现。
使用 ACL4SSR：https://acl4ssr-sub.github.io/ 转换现有的订阅。
转换配置选择默认即可，会导致 Clash-verge 的代理页无法读取到当前选中的订阅中的任何节点，表现为：显示上次选中的可用订阅（如果没有任何正常的订阅，则会显示为空白页），且模式切换按钮处于无法选中的状态。

可能相关的 issue ：https://github.com/zzzgydi/clash-verge/issues/857
https://github.com/zzzgydi/clash-verge/issues/739#issuecomment-1689478945

注：使用 YACD 是可以正常使用当前选中的经过 ACL4SSR 转换后的订阅的。

### To Reproduce

将 Clash 订阅放入 ACL4SSR 中转换（应该不能有 HY2?），再使用 clash-verge 进行订阅。
而后切换到转换后的订阅，打开代理页面，会无法选择节点且无法切换模式，或者显示为空白页。

### Platform

Linux

### System Version

ArchLinux (Linux-zen 6.6.5)

### Software Version

1.4.4

### Log

[2023-12-11-1640.log](https://github.com/clash-verge-rev/clash-verge-rev/files/13633092/2023-12-11-1640.log)
[2023-12-11-1639.log](https://github.com/clash-verge-rev/clash-verge-rev/files/13633094/2023-12-11-1639.log)

### Additional Information

目前我仅在 ACL4SSR+Clash-verge 下会遇到这个情况。
常规订阅+Clash Verge 或者 ACL4SSR+其他 Clash GUI 均正常。

**Comment by MystiPanda** [comment]
这块我也不是很懂

**Comment by ShirokaneShizuku** [comment]
测试了一下，没法在 Windows 下复现，应该是只有 Linux 上有这个怪问题。

**Comment by XTTGO** [comment]
> 测试了一下，没法在 Windows 下复现，应该是只有 Linux 上有这个怪问题。

MAC也会

**Comment by ShirokaneShizuku** [comment]
> > 测试了一下，没法在 Windows 下复现，应该是只有 Linux 上有这个怪问题。
> 
> MAC也会

那目前还就只有 Windows 没问题。
看起来只能慢慢对规则进行排查了？
