### ISSUE TITLE
[Feature] 建议提供使用系统自带窗口的功能

### ISSUE THREAD

**Issue by oodzchen** [clash-verge-rev/clash-verge-rev#1240]
### 功能描述 / Feature description

目前在Linux上的KDE桌面上会出现两层窗口按钮，可以考虑针对KDE平台关闭自带的窗口按钮，或者直接提供相关选项让用户自行关闭。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/9650699/5cb0a1d5-027b-4b4d-b567-2153ee48e9d7)

### 使用场景 / Use case

在KDE桌面上打开Clash Verge Rev的时候可关闭内置窗口按钮

**Comment by silascript** [comment]
？？KDE这么奇葩的吗？幸好我是Gnome~

**Comment by ShionKanagawa** [comment]
这个实际上是 KDE 的问题啦，我暂时是修改 KDE 设置中对 clash-verge-rev 的窗口规则：
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/102428923/eec3e0b5-84c1-4d66-ae30-b88d70d425e8)

**Comment by oodzchen** [comment]
@ShionKanagawa KDE 的扩展性不用怀疑的，只看愿不愿意适配而已，像 telegram 客户端就提供了选项，可以选择用 tg 自定义的按钮，也可以换成跟系统一致的。不过经你这么一提醒，我想起来可以关闭外窗口边框，直接在窗口上鼠标右键，选择“More Actions > No Titlebar and Frame ”就行，感谢。

**Comment by MystiPanda** [comment]
倒也不用说 KDE 多好，隐藏标题栏的逻辑代码里肯定是写了的，在 KDE x11 下是正常的，只有在 KDE wayland 下不生效，具体是 KDE 的问题还是 tauri 的问题我也不知道，telegram 的客户端 qt 写的，qt 的各种 api 在 KDE 下肯定是正常的，但是 tauri 使用 gtk 的窗口，只能说 KDE 在 wayland 下对于 gtk 的支持不好咯。

**Comment by oodzchen** [comment]
@MystiPanda 看起来是 [wayland 的问题](https://github.com/tauri-apps/tauri/issues/6162#issuecomment-1423304398)，不过如果能提供关闭内置窗口按的选项就更好了，我个人更倾向于让应用程序窗口装饰根系统整体风格保持一致。

**Comment by witt-bit** [comment]
> @MystiPanda 看起来是 [wayland 的问题](https://github.com/tauri-apps/tauri/issues/6162#issuecomment-1423304398)，不过如果能提供关闭内置窗口按钮的选项就更好了，我个人更倾向于让应用程序窗口装饰根系统整体风格保持一致。

这个有计划吗？我其他应用的三大按钮都在左侧，clash-verge在右侧

**Comment by oodzchen** [comment]
@witt-bit 可以用一个小 hack 来解决，把仓库克隆到本地，修改[这一行代码](https://github.com/clash-verge-rev/clash-verge-rev/blob/main/src/assets/styles/layout.scss#L99)，把`display: flex`改成`display: none`，这样可以隐藏程序自带的按钮，然后安装依赖后运行`pnpm build`，自行构建二进制文件，替换原来的程序文件即可。这就是开源项目的好处，可以从源码级别按照自己的喜好进行定制。
