### ISSUE TITLE
[BUG] Windows11 系统开启Tun模式后部分应用无法联网

### ISSUE THREAD

**Issue by LeanC0de** [clash-verge-rev/clash-verge-rev#1242]
### 问题描述 / Describe the bug

Windows 11开启tun模式后无论状态栏显示小地球（无法连接Internet），大部分软件可以正常通过代理上网但是OneDrive这类软件（通过系统API判断是否联网的软件？）无法联网，尝试更改Tun网卡名称和Tun模式堆栈还有开关严格路由也无济于事。（难道是我的配置或者节点问题嘛？换了其它机场订阅也不行，不太懂怎么配置DNS什么的）

### 复现步骤 / To Reproduce

开启tun模式后即可复现。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 Pro OS build 22631.3737

### 日志 / Log

WARNING
[TUN] default interface changed by monitor, => Wi-Fi
INFO
[TUN] Tun adapter listening at: GVisor([198.18.0.1/30],[]), mtu: 1500, auto route: true, ip stack: gVisor
WARNING
[TCP] dial 🖥 Microsoft (match DomainSuffix/microsoft.com) 198.18.0.1:7903(OneDrive.exe) --> self.events.data.microsoft.com:443 error: connect failed: dial tcp 20.189.173.10:443: i/o timeout

**Comment by AnyWAT** [comment]
> 难道是我的配置或者节点问题嘛？换了其它机场订阅也不行，不太懂

+1

采用的便携版，[共享节点](https://github.com/Alvin9999/new-pac)，（有线网络）基本正常。

**Comment by LeanC0de** [comment]
> > 难道是我的配置或者节点问题嘛？换了其它机场订阅也不行，不太懂
> 
> +1
> 
> 采用的便携版，[共享节点](https://github.com/Alvin9999/new-pac)，（有线网络）基本正常。

铁铁你的也是一连接就会显示小地球（无网络连接）嘛，感觉是Windows最新系统的问题。

**Comment by AnyWAT** [comment]
> > （有线网络）基本正常。
> 
> 铁铁你的也是一连接就会显示小地球（无网络连接）嘛

基本正常还能是小地球？

**Comment by AnyWAT** [comment]
> Windows 11开启tun模式后无论状态栏显示小地球（无法连接Internet）

试试？检查系统组件的完整性并修复：https://answers.microsoft.com/zh-hans/windows/forum/all/%E8%BD%AF%E4%BB%B6%E8%BF%90%E8%A1%8C%E4%B8%AD/7d0d0e86-a00d-4077-ae53-a017c67e1aa5

**Comment by LeanC0de** [comment]
> > Windows 11开启tun模式后无论状态栏显示小地球（无法连接Internet）
> 
> 试试？检查系统组件的完整性并修复：https://answers.microsoft.com/zh-hans/windows/forum/all/%E8%BD%AF%E4%BB%B6%E8%BF%90%E8%A1%8C%E4%B8%AD/7d0d0e86-a00d-4077-ae53-a017c67e1aa5

嘿嘿重装系统后好了
