### ISSUE TITLE
[BUG] 系统代理中，代理绕过还是有问题

### ISSUE THREAD

**Issue by AlphaAnother** [clash-verge-rev/clash-verge-rev#1243]
### 问题描述 / Describe the bug

现在在程序的系统代理设置里不管设置什么，都会启用默认绕过地址，在代理绕过设置里新增地址，也只会在默认绕过配置后面加上新增的几条，不像之前能够直接控制绕过设置了。

### 复现步骤 / To Reproduce

在2a4b605这个commit的alpha版本下测试可以正常复现。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11 22631.3737

### 日志 / Log

![屏幕截图 2024-06-21 093945](https://github.com/clash-verge-rev/clash-verge-rev/assets/17845460/3e1cee10-ccce-4a41-9c70-ea566d25e176)

**Comment by AnyWAT** [comment]
根据
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37962734/e709f131-0b7f-4c29-b3a6-3e7e0f9fd63a)
貌似楼主的设置有问题？
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37962734/21e27fdc-d43a-41d3-b03f-6826c152f035)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37962734/3b26c34e-0704-4be1-aa28-3bee6af04b63)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37962734/d2404940-521f-4531-8641-e47ef091fe70)
A=C=7890 ？

**Comment by wonfen** [comment]
什么奇奇怪怪的结论，被cfw毒害不浅，参考这个方案：
https://github.com/clash-verge-rev/clash-verge-rev/issues/1194#issuecomment-2172417507

**Comment by AlphaAnother** [comment]
> 有点看不明白，你是有需要接管的内网ip段？

有啊 我在各个公司的网络下放了隧道 用代理组手动切换去哪个地方的内网

**Comment by AlphaAnother** [comment]
> 什么奇奇怪怪的结论，被cfw毒害不浅，参考这个方案： [#1194 (comment)](https://github.com/clash-verge-rev/clash-verge-rev/issues/1194#issuecomment-2172417507)

没用 这个地址下面没有proxy相关项

**Comment by AlphaAnother** [comment]
> @AlphaAnother 暂时可以先使用pac模式
> 
> ```js
> // 代理与直连重复 域名/IP 段的话优先代理
> // 代理
> const proxyList = [
>   '192.168.10.*'
> ];
> 
> // 直连
> const directList = [
>   'localhost','127.*','192.168.*','10.*'
> ];
> 
> //================================================================//
> 
> const proxy = 'PROXY 127.0.0.1:%mixed-port%; SOCKS5 127.0.0.1:%mixed-port%;';
> const direct = 'DIRECT';
> 
> function shExpMatchList(host, list){
>   return list.some(item => shExpMatch(host, item));
> }
> 
> function FindProxyForURL(url, host) {
>   if (shExpMatchList(host, proxyList)) return proxy;
>   if (shExpMatchList(host, directList)) return direct;
> 
>   return proxy;
> }
> ```

多谢 暂时先用pac了

**Comment by AlphaAnother** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/commit/183f0f6c4259e07014bb79715e7e844204e314a7
搜索了下，好像就是代码写死了默认绕过列表，上方的新增只能在尾巴加新的。可不可以加个开关？开关=true的时候DEFAULT_BYPASS不加入，只处理custom_bypass。
