### ISSUE TITLE
[BUG] 热键设置

### ISSUE THREAD

**Issue by iibob** [clash-verge-rev/clash-verge-rev#1245]
### 问题描述 / Describe the bug

设置快捷键时，只要组合键中有 option（对应 Windows 系统中 Alt 键），再带上字母就会使字母变成特殊符号。
如 option O 会在软件界面中显示为 ALT ø，导致设置好的快捷键无效（按下 option O，无效。）

经过测试，只要不带 option 的组合键，就没问题；或者不使用英文字母的组合键

### 复现步骤 / To Reproduce

点击导航栏设置  → 点击“热键设置” → 点击“打开/关闭系统代理”后方的输入框 → 按下 option（不松开）再按下O
此时输入框内显示：ALT ø

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

13.6.6

### 日志 / Log

另外请求一个功能，按下 command Q 可退出本程序。希望作者考虑添加，感谢。
因为我发现退出程序的唯一方式是点击菜单栏中的图标，在弹出的窗口中再点击“退出”才能退出。

**Comment by dongchengjie** [comment]
meta +q是特意移除的，在mac上在相当于altf+4会导致ui进程被kill，而内核进程残留，致使下次启动会出问题

**Comment by iibob** [comment]
> meta +q是特意移除的，在mac上在相当于altf+f4会导致ui进程被kill，而内核进程残留，致使下次启动会出问题

哦哦，好的了解了。

**Comment by dongchengjie** [comment]
另外，opetion + key 的组合输入特殊字符是macos自带输入法的问题，自行切换KeyboardLayout或使用其他输入法

**Comment by iibob** [comment]
> 另外，option + key 的组合输入特殊字符是macos自带输入法的问题，自行切换KeyboardLayout或使用其他输入法

你好，我刚测试过 搜狗、微信、自带英文、自带中文拼音输入法，在中文或者英文输入状态下，按下 option O，均显示为 ALT ø，依然导致热键失效。


目前已使用不带 option 的组合键当作热键，如果其他设备无法复现，可能是我系统的问题了。

**Comment by dongchengjie** [comment]
> > 另外，option + key 的组合输入特殊字符是macos自带输入法的问题，自行切换KeyboardLayout或使用其他输入法
> 
> 你好，我刚测试过 搜狗、微信、自带英文、自带中文拼音输入法，在中文或者英文输入状态下，按下 option O，均显示为 ALT ø，依然导致热键失效。
> 
> 目前已使用不带 option 的组合键当作热键，如果其他设备无法复现，可能是我系统的问题了。

【键盘】->【输入法】，新增一个【简体中文】的【简体笔画】就可以

**Comment by iibob** [comment]
> 【键盘】->【输入法】，新增一个【简体中文】的【简体笔画】就可以，其他没有映射特殊字符的也可以，特殊字符并不固定而是根据语种对应键盘布局配置来的。 https://clash-verge-rev.github.io/faq/macos.html#macos-optionalt

感谢能够重视的我反馈，也很高兴能为文档添砖加瓦。


根据您提供的解决方法，我使用【简体中文】的【简体笔画】可解决我的疑问。
但按下后会出现输入框，此时需点击 “保存” 按钮，即可正常使用热键进行操作。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/10295975/230e3b1a-2b2a-415b-8c93-71e72558e941)


如果使用【简体中文】的【简体五笔】，会出现如下情况：
按下 option 与任意字母的组合键，均会显示为 ALT DEAD
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/10295975/44ee2049-1ed4-419b-a0b6-01aa9d8c56a1)


另外，根据您的提示， 我测试了Mac上所有的输入法，发现只有【Unicode 十六进制输入 】在按下 option 键时，没有出现特殊字符，但在本程序的热键设置界面，依然会显示为 ALT DEAD


其实到这里，我的问题已经解决了，目前的问题只是有点小瑕疵而已，并不影响程序的正常工作。
感谢大佬们为此项目无私贡献。
