### ISSUE TITLE
[BUG] 开启TUN模式后断网, 所有TCP连接失败

### ISSUE THREAD

**Issue by Mion354D** [clash-verge-rev/clash-verge-rev#1246]
### 问题描述 / Describe the bug

开启TUN模式后断网
TUN模式设置: 
![telegram-cloud-photo-size-5-6316437385675652618-y](https://github.com/clash-verge-rev/clash-verge-rev/assets/7450570/e4b6cdf5-a3dc-4b2b-96b7-ea0274415f2c)
app 版本: 1.6.6
操作系统:  macOS Sonoma 14.1 (23B74)
服务模式: 开启并显示已激活
使用的内核:
![telegram-cloud-photo-size-5-6316437385675652656-y](https://github.com/clash-verge-rev/clash-verge-rev/assets/7450570/18bcce0f-8591-41ac-8fd5-01c940122d53)

### 复现步骤 / To Reproduce

在给定环境下开启TUN即可断网

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.1 (23B74)

### 日志 / Log

访问被分流到代理的日志: 
![telegram-cloud-photo-size-5-6316437385675652619-y](https://github.com/clash-verge-rev/clash-verge-rev/assets/7450570/49d2c5f9-cfea-4c43-bd6f-c1cd4df10df1)
访问大陆直连的日志:
![telegram-cloud-photo-size-5-6316437385675652620-y](https://github.com/clash-verge-rev/clash-verge-rev/assets/7450570/13a0e61e-500d-48e7-8e9f-a8916477839d)

**Comment by MengNianxiaoyao** [comment]
有没有在防火墙放行内核？

**Comment by Mion354D** [comment]
> 有没有在防火墙放行内核？

没有启用防火墙

**Comment by xvzhenduo** [comment]
看#244
