### ISSUE TITLE
[BUG] ping局域网地址显示延迟低于1ms

### ISSUE THREAD

**Issue by sjhsbhqf** [clash-verge-rev/clash-verge-rev#1248]
### 问题描述 / Describe the bug

Reply from 192.168.1.1: bytes=32 time<1ms TTL=64
Reply from 192.168.11.1: bytes=32 time<1ms TTL=64
Reply from 192.168.1.1: bytes=32 time<1ms TTL=64
Reply from 192.168.1.1: bytes=32 time<1ms TTL=64
Reply from 192.168.1.1: bytes=32 time<1ms TTL=64
Reply from 192.168.1.11: bytes=32 time<1ms TTL=64

### 复现步骤 / To Reproduce

ping局域网地址的时候，显示延迟低于1ms，之前的cfw开启tun模式也是这个问题。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 

### 日志 / Log

Reply from 192.168.1.1: bytes=32 time<1ms TTL=64
Reply from 192.168.11.1: bytes=32 time<1ms TTL=64
Reply from 192.168.1.1: bytes=32 time<1ms TTL=64
Reply from 192.168.1.1: bytes=32 time<1ms TTL=64
Reply from 192.168.1.1: bytes=32 time<1ms TTL=64
Reply from 192.168.1.11: bytes=32 time<1ms TTL=64

**Comment by dongchengjie** [comment]
这是特性，多的不解释

**Comment by sjhsbhqf** [comment]
> 这是特性，多的不解释

特性的话应该可以关吧。不然我不知道这个主机我是否能连通，因为即使实际联不通，还是显示小于1ms

**Comment by dongchengjie** [comment]
特点，特点行了吧

**Comment by sjhsbhqf** [comment]
> 特点，特点行了吧

这...........负面特点，简称缺陷

**Comment by xishang0128** [comment]
内核不支持icmp代理,所以会直接回应icmp,有需要自行排除网段

**Comment by BitEnswer** [comment]
@sjhsbhqf 内核不支持ICMP代理，这意味着当发送ICMP包（如ping请求）时，这些包并不会被代理软件转发到实际的目标网络地址。相反，这些请求可能会被代理软件直接回应，因此你看到的延迟非常低（低于1毫秒），这只是因为回应是本地生成的，而不是真实的网络延迟
你可尝试通过手动排除网段解决

**Comment by sjhsbhqf** [comment]
> @sjhsbhqf 内核不支持ICMP代理，这意味着当发送ICMP包（如ping请求）时，这些包并不会被代理软件转发到实际的目标网络地址。相反，这些请求会被代理软件直接回应，因此你看到的延迟非常低（低于1毫秒），这只是因为回应是本地生成的，而不是真实的网络延迟 你可尝试通过手动排除网段解决

谢谢大哥！还有前面的大哥

**Comment by sjhsbhqf** [comment]
> @sjhsbhqf 内核不支持ICMP代理，这意味着当发送ICMP包（如ping请求）时，这些包并不会被代理软件转发到实际的目标网络地址。相反，这些请求会被代理软件直接回应，因此你看到的延迟非常低（低于1毫秒），这只是因为回应是本地生成的，而不是真实的网络延迟 你可尝试通过手动排除网段解决

大哥，我TUN设置里面添加了下面这几行：

```
  route-exclude-address:
  - 192.168.0.0/16
  - 198.18.0.34/24
  - fc00::/7
 
  inet4-route-exclude-address:
  - 192.168.0.0/16
  - 198.18.0.34/24
```

直接ping这个被排除的ip地址198.18.0.34，成功绕过。

但是我发现手动编辑很麻烦，tun模式的配置支持直接用一个在线配置文件url吗？

能不能让tun的设置那里，添加一个ruleset url的输入框？？

**Comment by BitEnswer** [comment]
@sjhsbhqf 也许可以通过URL配置，但是注意到网域上的订阅转换似乎都没有提供此功能，你大概率需要自行搭建配置服务器。
TUN模式配置可以从远程URL动态加载规则集，以简化配置过程。
你可以查询Mihomo内核文档
wiki.metacubex.one
来了解怎么做。
