### ISSUE TITLE
[BUG]  Mac 1.6.6版本又开始出现更新订阅自动重设系统DNS设置的问题

### ISSUE THREAD

**Issue by suyanjun1987** [clash-verge-rev/clash-verge-rev#1250]
### 问题描述 / Describe the bug

之前解决的这一问题在1.6.6版本又出现了。更新订阅后，会自动清空系统设置里的DNS设置的问题，导致电脑上不了网。

### 复现步骤 / To Reproduce

每次更新订阅后，会自动清空系统设置里的DNS设置。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Mac OS 14.5

### 日志 / Log

06-22 14:33:37INFO
Start initial configuration in progress
06-22 14:33:37INFO
Geodata Loader mode: memconservative
06-22 14:33:37INFO
Geosite Matcher implementation: succinct
06-22 14:33:37INFO
Initial configuration complete, total time: 2ms
06-22 14:33:37INFO
Sniffer is closed
06-22 14:33:37INFO
Start initial provider Disney

**Comment by zhaotuo0815** [comment]
请问要怎么解决呢？我电脑现在不连VPN都用不了edge浏览器

**Comment by suyanjun1987** [comment]
> 请问要怎么解决呢？我电脑现在不连VPN都用不了edge浏览器

暂时的解决方案：更新完订阅，自己再手动重新设置一遍DNS；或者配置一个Merge，在merge的配置里的defalut-nameserver和nameserver里加入你自己的DNS解析地址。第二种方案有的时候也不太好使，可能偶尔出现上不了网的情况。

**Comment by deckvig** [comment]
强烈建议做成一个可配置的开关。在内网环境下的工作场景每次都需要手动调整一次 DNS，十分麻烦

**Comment by GetemJay** [comment]
麻烦问下这个问题解决了么

**Comment by suyanjun1987** [comment]
> 麻烦问下这个问题解决了么

解决了。更新最新版本。

**Comment by RayWangQvQ** [comment]
当前最新版本1.7.7依然未解决

**Comment by wonfen** [comment]
> 当前最新版本1.7.7依然未解决

用最新的2.0 alpha版本
