### ISSUE TITLE
[Feature] 恢复Appimage版本

### ISSUE THREAD

**Issue by klx1204** [clash-verge-rev/clash-verge-rev#1251]
### 功能描述 / Feature description

恢复appimage格式版本

### 使用场景 / Use case

Steamdeck、国产ARM64设备、树莓派，有些系统自带包管理器没有提供安装包，第三方管理器又受到网络条件限制，appimage方便又好用

**Comment by chinanoahli** [comment]
确实

**Comment by MystiPanda** [comment]
不会提供，实在需要可以自己编译打包
