### ISSUE TITLE
[BUG] 使用Clash Verge(META内核)，对端为IPV6，WireGuard协议下，网速过慢。

### ISSUE THREAD

**Issue by JedSunCN** [clash-verge-rev/clash-verge-rev#1252]
### 问题描述 / Describe the bug

RT，使用IPV6连接WG节点时候，ClashVerge性能表现过于糟糕。使用speed.cloudflare.com测速，使用WG客户端连接速度34.4Mbps，而使用ClashVerge只有2.19Mbps。

### 复现步骤 / To Reproduce

使用IPV6连接WG节点

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 23H2

### 日志 / Log

06-22 21:29:09INFO
[TCP] 127.0.0.1:8359 --> i.ytimg.com:443 using GLOBAL
06-22 21:29:10INFO
[TCP] 127.0.0.1:8372 --> rr5---sn-5hne6nz6.googlevideo.com:443 using GLOBAL
06-22 21:29:11INFO
[TCP] 127.0.0.1:8367 --> rr1---sn-5hne6nz6.googlevideo.com:443 using GLOBAL
06-22 21:29:11INFO
[TCP] 127.0.0.1:8366 --> rr1---sn-5hne6nz6.googlevideo.com:443 using GLOBAL
06-22 21:29:12INFO
[TCP] 127.0.0.1:8387 --> accounts.youtube.com:443 using GLOBAL
06-22 21:29:14INFO
[TCP] 127.0.0.1:8377 --> jnn-pa.googleapis.com:443 using GLOBAL
06-22 21:29:15WARNING
[TCP] dial GLOBAL 127.0.0.1:8384 --> www.gstatic.com:443 error: context deadline exceeded
06-22 21:29:15INFO
[TCP] 127.0.0.1:8397 --> www.gstatic.com:443 using GLOBAL
06-22 21:29:18INFO
[TCP] 127.0.0.1:8398 --> yt3.ggpht.com:443 using GLOBAL
06-22 21:29:25INFO
[TCP] 127.0.0.1:8414 --> jnn-pa.googleapis.com:443 using GLOBAL

**Comment by dongchengjie** [comment]
你这不是门儿清嘛，搁这里发牢骚也没用啊😅

**Comment by JedSunCN** [comment]
> 你这不是门儿清嘛，搁这里发牢骚也没用啊😅

主要是感觉比IPV4端点慢多了，以至于有点怀疑是不是我ClashVerge哪里配置有问题🤣

**Comment by dongchengjie** [comment]
wg内核最后一次更新是5天前，你自个去试吧，和verge没什么关系
