### ISSUE TITLE
[BUG] mac上Tun模式做透明网关，"局域网连接"功能无效

### ISSUE THREAD

**Issue by smilingpoplar** [clash-verge-rev/clash-verge-rev#1253]
### 问题描述 / Describe the bug

以前用ClashX Pro，开启TUN和局域网连接就能把mac作为透明网关，clash-verge-rev无法达成。
用`sysctl net.inet.ip.forwarding`查看，输出`net.inet.ip.forwarding: 0`，说明ip转发功能未打开。
还需手动运行`sudo sysctl -w net.inet.ip.forwarding=1`。

手动打开ip转发在mac重启后也失效，要在重启后也生效还需使用LaunchDaemon。
看下ClashX Pro，`grep -r 'net.inet.ip.forwarding=1' /Applications/ClashX\ Pro.app`，输出
```
grep: /Applications/ClashX Pro.app/Contents/Library/LaunchServices/com.west2online.ClashXPro.ProxyConfigHelper: binary file matches
```
而 `grep -r 'net.inet.ip.forwarding=1' /Applications/Clash\ Verge.app`，输出为空。

### 复现步骤 / To Reproduce

在mac的clash-verge-rev打开TUN和局域网连接，将手机wifi的路由地址和DNS地址设为电脑ip，无法上网。

### 操作系统 / OS

MacOS 14.5

**Comment by jaoyina** [comment]
关注，我还在用ClashX Pro，希望有个好的替代。

**Comment by dream2333** [comment]
一样，windows也复现了这个问题

**Comment by xishang0128** [comment]
编辑/etc/sysctl.conf
增加net.inet.ip.forwarding=1

**Comment by smilingpoplar** [comment]
Mac上编辑`/etc/sysctl.conf`不起作用，要用LaunchDaemon。比如，

`$ vi /Library/LaunchDaemons/clash.ip-forwarding.plist`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>clash.ip-forwarding</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/sbin/sysctl</string>
        <string>-w</string>
        <string>net.inet.ip.forwarding=1</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
```

```
$ sudo launchctl load /Library/LaunchDaemons/clash.ip-forwarding.plist
$ sudo launchctl start clash.ip-forwarding.plist
```

**Comment by jaoyina** [comment]
> Mac上编辑`/etc/sysctl.conf`不起作用，可用LaunchDaemon。比如，
> 
> ```
> $ vi /Library/LaunchDaemons/clash.ip-forwarding.plist
> ```
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
>     <key>Label</key>
>     <string>clash.ip-forwarding</string>
>     <key>ProgramArguments</key>
>     <array>
>         <string>/usr/sbin/sysctl</string>
>         <string>-w</string>
>         <string>net.inet.ip.forwarding=1</string>
>     </array>
>     <key>RunAtLoad</key>
>     <true/>
> </dict>
> </plist>
> ```
> 
> ```
> $ sudo launchctl load /Library/LaunchDaemons/clash.ip-forwarding.plist
> $ sudo launchctl start clash.ip-forwarding.plist
> ```

这是每次启动系统自动加载的意思？

**Comment by hittaaa** [comment]
我遇到相同情况，原因是MAC没有开启IP地址转发，

但是新问题来了，DNS还是需要手动设置，DNS转发开启还没头绪。

wonfen ***@***.***> 于2024年10月21日周一 08:55写道：

**Comment by 188751671** [comment]
我也出现了这个问题,  而且用sudo sysctl -w net.inet.ip.forwarding=1 开启后,  使用该Clash网关的设备  网速变得异常缓慢
