### ISSUE TITLE
[BUG] 基于ubuntu的linux mint安装失败

### ISSUE THREAD

**Issue by richsun-crypto** [clash-verge-rev/clash-verge-rev#1254]
### 问题描述 / Describe the bug

环境:
Distributor ID:	Linuxmint
Description:	Linux Mint 21.3
Release:	21.3
Codename:	virginia    
deb方式安装的时候出现异常:
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/25789351/daab198b-8252-47cb-9c61-a84ed315252c)

### 复现步骤 / To Reproduce

下载amd64.deb包,双击安装,前期能看见在部署文件,最终出现异常,重复下载及安装出现一样的问题

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Linux Mint 21.3

### 日志 / Log

没有日志

**Comment by MystiPanda** [comment]
报错不是说的很清楚吗，有冲突，把旧的clash-verge卸载了就好了
