### ISSUE TITLE
[Feature] 状态栏图标不够协调

### ISSUE THREAD

**Issue by jszjgqq** [clash-verge-rev/clash-verge-rev#1256]
### 功能描述 / Feature description

整体看状态栏的图标，偏大了点，不够协调。

### 使用场景 / Use case

<img width="459" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/2629994/0ba99308-0096-428e-aca3-bc91d74f76d2">

如上图，图标明显偏大了点。

**Comment by wonfen** [comment]
不喜欢自己换

**Comment by jszjgqq** [comment]
> 不喜欢自己换

具体方法是？

**Comment by AnyWAT** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37962734/ee17efa3-1c3d-4a36-8d36-7504679ef246)
