### ISSUE TITLE
[Feature] 请求给保持default bypass加个开关

### ISSUE THREAD

**Issue by AlphaAnother** [clash-verge-rev/clash-verge-rev#1259]
### 功能描述 / Feature description

上一个issue：https://github.com/clash-verge-rev/clash-verge-rev/issues/1243
搜索了下，好像就是[代码](https://github.com/clash-verge-rev/clash-verge-rev/commit/183f0f6c4259e07014bb79715e7e844204e314a7)写死了默认绕过列表，上方的新增只能在尾巴加新的。可不可以加个开关？开关=true的时候DEFAULT_BYPASS不加入，只处理custom_bypass。

### 使用场景 / Use case

我在不同地方放了隧道代理，自己维护了clash配置，在策略组里面手动切换直连当前内网/通过隧道接入其他内网，原来的bypass设置就是把现在的配置删除192.168.*;和10.*。现在keep default bypass的情况下我只能改成pac模式使用，无法使用系统代理模式。请求给keep default bypass加个开关，只使用custom_bypass。

**Comment by AlphaAnother** [comment]
1.7.1版本确认已实现，非常感谢！

**Comment by xiaoQQya** [comment]
始终使用默认绕过关闭并且代理绕过配置为空的情况下，还是会使用默认代理绕过，如下图：

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/46475319/9dcf1019-56e3-475c-bc2b-c0b22be22859)

**Comment by AnyWAT** [comment]
代理绕过设置：
添加
<local>
保存即可——代理绕过配置为空——Win 10 系统网络代理设置处验证。
