### ISSUE TITLE
[BUG]使用clash verge rev连接github会提示隐私设置错误，您的连接不是私密连接

### ISSUE THREAD

**Issue by jingouwangzi** [clash-verge-rev/clash-verge-rev#126]
### Describe the bug

之前使用clash for windows，连接github等都是正常的，今天换成clash verge rev打开github会提示隐私设置错误，您的连接不是私密连接
浏览器会提示证书无效
证书信息：颁发对象：公用名s.e55fad.nigirocloud.com，组织未包含在证书中，组织单位未包含在证书中
颁发者：公用名R3，组织Let's Encrypt，组织单位未包含在证书中

### To Reproduce

直接打开软件，添加订阅，设置好代理服务器，然后上github，就会出现以上提示（与clash for windows一样的设置）

### Platform

Windows

### System Version

windows11 23H2

### Software Version

1.4.4

**Comment by jingouwangzi** [comment]
浏览器会提示证书无效

**Comment by wonfen** [comment]
检查你的网络是不是被dns劫持了。
