### ISSUE TITLE
[Feature]  关于刷新订阅，每次会重置节点的问题

### ISSUE THREAD

**Issue by rnb3ds** [clash-verge-rev/clash-verge-rev#1263]
### 功能描述 / Feature description

有个功能可以优化一下不？

1. 点订阅 -> 点刷新 (订阅)
2. 在代理中, 选择设置过的代理节点,  会重置

这样好麻烦, 每次点一下刷新订阅, 代理节点要重新配置选择

### 使用场景 / Use case

1. 点订阅 -> 点刷新 (订阅)
2. 在代理中, 选择设置过的代理节点,  会重置

这样好麻烦, 每次点一下刷新订阅, 代理节点要重新配置选择

**Comment by aflyingnoob** [comment]
是不是没假
profile:
  store-selected: true

**Comment by rnb3ds** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by rnb3ds** [comment]
> 是不是没假 profile: store-selected: true

找不到这个选项。

**Comment by aflyingnoob** [comment]
> > 是不是没假 profile: store-selected: true
> 
> 找不到这个选项。

新建 merge里面写上
profile:
 store-selected: true

**Comment by rnb3ds** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/20226005/1da1178c-9166-4f54-a3db-bbe62b63b516)

你好，请问是这样吗？但我试了下， 还是不行呢

**Comment by aflyingnoob** [comment]
都没蓝线没激活，右键启用，
profile:
【这里加个空格】store-selected: true

**Comment by rnb3ds** [comment]
试了下，还是不行

![snipaste_2024-06-25_16-47-23](https://github.com/clash-verge-rev/clash-verge-rev/assets/20226005/bd974991-6938-437d-8516-cb75a2dcce3d)
设置了，也添加了空格

![snipaste_2024-06-25_16-47-46](https://github.com/clash-verge-rev/clash-verge-rev/assets/20226005/48d8f4fb-f9f8-48e9-95b7-43a664172bb9)
激活了配置，点一下刷新订阅后


![snipaste_2024-06-25_16-48-57](https://github.com/clash-verge-rev/clash-verge-rev/assets/20226005/80d89065-be13-43dd-8782-c4f208381fc8)
节点又变成默认的

**Comment by aflyingnoob** [comment]
> 试了下，还是不行
> 
> ![snipaste_2024-06-25_16-47-23](https://private-user-images.githubusercontent.com/20226005/342652129-bd974991-6938-437d-8516-cb75a2dcce3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDU3OTUsIm5iZiI6MTcxOTMwNTQ5NSwicGF0aCI6Ii8yMDIyNjAwNS8zNDI2NTIxMjktYmQ5NzQ5OTEtNjkzOC00MzdkLTg1MTYtY2I3NWEyZGNjZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA4NTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ODY0Mjk1OGI1N2QyZjQwNzU2Mzc3NTAwNmY5N2MzNjczNmYzMmZkNWJkNWUyOWQwOWNkYWU2YWYyMmRlOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.adK2basyZ4P3vNxcWnpRhF4Q0LrWlZyoxOjaEpK6oGA) 设置了，也添加了空格
> 
> ![snipaste_2024-06-25_16-47-46](https://private-user-images.githubusercontent.com/20226005/342652308-48d8f4fb-f9f8-48e9-95b7-43a664172bb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDU3OTUsIm5iZiI6MTcxOTMwNTQ5NSwicGF0aCI6Ii8yMDIyNjAwNS8zNDI2NTIzMDgtNDhkOGY0ZmItZjlmOC00OGU5LTk1YjctNDNhNjY0MTcyYmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA4NTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNjQ4ZTI3YTE0Nzc3MmMxYWQ3YzhiMzhjMjNmMjU1ZWQxNWNiNDk3OWRiOTY4NDFiODdlMDE5MTZhZDEyZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-mIQhxnEslpeasDnWRGJrZ_FZ546p8nFvy6V1Q_2BWA) 激活了配置，点一下刷新订阅后
> 
> ![snipaste_2024-06-25_16-48-57](https://private-user-images.githubusercontent.com/20226005/342652403-80d89065-be13-43dd-8782-c4f208381fc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDU3OTUsIm5iZiI6MTcxOTMwNTQ5NSwicGF0aCI6Ii8yMDIyNjAwNS8zNDI2NTI0MDMtODBkODkwNjUtYmUxMy00M2RkLTg3ODItYzRmMjA4MzgxZmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA4NTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZGM1NzIyZjAwYTUzNzg1MWE1MjlhNGYxMjNlZTJhNjZmZTdjMDUwODBkNGVhY2M0ZjgwYTc2Y2RmNzA4M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.83U-JwsxoKm7zrJnRcNZc2rz7UyGyxpNyZgp5InmPmA) 节点又变成默认的

无语子，是在你双击那个merge后写了再保存，你现在写的地方是描述给文件起名字

**Comment by rnb3ds** [comment]
![Uploading snipaste_2024-06-25_16-56-51.png…]()


哈哈，我第一次使用， 不好意思啊大佬，这下应该是配置正确了吧

**Comment by rnb3ds** [comment]
![snipaste_2024-06-25_16-56-51](https://github.com/clash-verge-rev/clash-verge-rev/assets/20226005/566937e9-26e2-4d3e-90ad-bf37a847674d)

哈哈，我第一次使用， 不好意思啊大佬，这下应该是配置正确了吧
