### ISSUE TITLE
[Feature] url-test能否添加cloudfare拦截检测

### ISSUE THREAD

**Issue by aflyingnoob** [clash-verge-rev/clash-verge-rev#1264]
### 功能描述 / Feature description

现在的urltest只能保证节点是活的，但是更多的情况是不关心延迟的几毫秒，而是烦弹出cloudfare验证的繁琐过程，能否检测到cloudfare后节点延迟变999排后面

### 使用场景 / Use case

chatgpt经常弹cloudfare

**Comment by SukkaW** [comment]
请使用 Mihomo 的 [`health-check.expecred-status`](https://wiki.metacubex.one/config/proxy-providers/?h=health+check#health-checkexpected-status)

Cloudflare 的 CAPTCHA 页的状态码非 200。
