### ISSUE TITLE
我在ubuntu中更新到1.6.6后文字错乱，之前1.6.5版本没有这个问题 

### ISSUE THREAD

**Issue by maike009** [clash-verge-rev/clash-verge-rev#1265]
### 问题描述 / Describe the bug

![Snipaste_2024-06-25_18-46-11](https://github.com/clash-verge-rev/clash-verge-rev/assets/164895145/c2d99635-bdec-409b-b173-f5fbc37bed82)

### 复现步骤 / To Reproduce

打开就有

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

ubuntu22.04LTS

### 日志 / Log

no
![Snipaste_2024-06-25_18-46-11](https://github.com/clash-verge-rev/clash-verge-rev/assets/164895145/bc9f604f-9363-4eec-b1e1-3dd1da651778)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/164895145/53d63f28-a391-4e48-b5a7-1419aa86fbbc)

**Comment by wonfen** [comment]
检查一下系统字体

**Comment by maike009** [comment]
> 检查一下系统字体

系统字体能有什么问题吗，这个是错乱了吧

**Comment by wonfen** [comment]
检查是否开了分辨率缩放

**Comment by hustler-not-chatty** [comment]
猜测是 Linux 的 WebKit 只缩放了字体，但是没有缩放其他元素，你是不是在辅助功能里开字体缩放了？

**Comment by wonfen** [comment]
无进一步反馈，关闭
