### ISSUE TITLE
[BUG]VMess协议无法使用

### ISSUE THREAD

**Issue by jackyzonewen** [clash-verge-rev/clash-verge-rev#127]
### Describe the bug

原来使用的Clash Verge 1.3.8的版本，切换到1.4.4后，无法使用VMess协议的节点，切回去后正常

### To Reproduce

旧版本配置导入到新版本

### Platform

MacOS

### System Version

macOS 12.6

### Software Version

1.4.4

**Comment by jackyzonewen** [comment]
无奈用回了1.3.8版本的clash verge

**Comment by wonfen** [comment]
这个是metacore的问题，之前就发现了，请到meta那边反馈。

**Comment by wonfen** [comment]
无进一步反馈，关闭了。
