### ISSUE TITLE
[BUG] 重启开机之后需要手动开启服务模式

### ISSUE THREAD

**Issue by sjhsbhqf** [clash-verge-rev/clash-verge-rev#1270]
### 问题描述 / Describe the bug

重启开机之后需要手动开启服务模式

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/41407099/8a37f3b1-29ba-4bd6-a481-0a10485e1535)

### 复现步骤 / To Reproduce

1、软件设置开机自启
2、开启服务模式
3、电脑重启开机后，打开cvr，发现服务模式是灰色的
4、重启软件后服务模式恢复

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

NONE

**Comment by Carolove7** [comment]
建议检查服务和启动项，我昨天出现了“服务模式”变灰的情况，关闭防火墙后恢复

**Comment by Carolove7** [comment]
![a2c6f8258aea77e8281364de3a915ff2](https://github.com/clash-verge-rev/clash-verge-rev/assets/109721920/563a20ed-a7d4-4452-aa63-4fa029b87744)
看看这里√没有

**Comment by sjhsbhqf** [comment]
> ![a2c6f8258aea77e8281364de3a915ff2](https://private-user-images.githubusercontent.com/109721920/345440078-563a20ed-a7d4-4452-aa63-4fa029b87744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTM1NTgsIm5iZiI6MTcyMDAxMzI1OCwicGF0aCI6Ii8xMDk3MjE5MjAvMzQ1NDQwMDc4LTU2M2EyMGVkLWE3ZDQtNDQ1Mi1hYTYzLTRmYTAyOWI4Nzc0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMzI3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmUwNjRjYzE3YjNiNTQ5MTJiYWQ2MWViNTFmOTRlZWY5OTZkYWRhOTNjOTY0ZTdjYmRiNGQ1NWUzYWUyMzQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TuU3UZwPIWofcMEeA0WxsaU5OesPwKqvaGshPHR96lE) 看看这里√没有

嗐，我当时是彻底把防火墙关掉了

**Comment by sjhsbhqf** [comment]
@Carolove7 好的谢谢你的方案 我到时候如果还不行就试试这个

**Comment by sjhsbhqf** [comment]
我已经解决了这个问题，需要在防火墙里，设置通过clash meta内核的所有程序。

如下所示，其中有4个相关程序，我全部设置通过防火墙，然后重启机器就不需要再安装服务模式了

```
(base) PS C:\Program Files\Clash Verge> ls


    目录: C:\Program Files\Clash Verge


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        2024-06-29     13:02                meta-backup
d-----        2024-07-07     12:57                resources
-a----        2024-07-15     21:11       15064576 Clash Verge.exe
-a----        2024-06-29     13:02       26649600 clash-meta-alpha.exe
-a----        2024-05-19     16:50       26621440 clash-meta.exe
-a----        2024-07-15     22:51         418556 uninstall.exe
-a----        2024-07-15     13:17       26665472 verge-mihomo-alpha.exe
-a----        2024-07-01     23:04       26664960 verge-mihomo.exe
```

**Comment by agassiz** [comment]
我的 macos 电脑也是这样，重启后需要手动启动 服务模式，有那位知道什么原因，怎么解决的

**Comment by liaozd** [comment]
ubuntu 24.04也是，我需要手动点一下“启动"
