### ISSUE TITLE
v1.6.6代理绕过设置*.baidu.com提示无效的代理绕过[BUG] 

### ISSUE THREAD

**Issue by wzlee** [clash-verge-rev/clash-verge-rev#1271]
### 问题描述 / Describe the bug

v1.6.6代理绕过设置*.baidu.com提示无效的代理绕过

### 复现步骤 / To Reproduce

v1.6.6代理绕过设置*.baidu.com提示无效的代理绕过

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 10

### 日志 / Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/4182865/e13f2e81-4d89-4d87-97b2-32f124dfb76c)

**Comment by rebecca554owen** [comment]
@wzlee *baidu.com

**Comment by lakevilladom** [comment]
> alpha版已经修复,可以先用 https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha

试了这个版本，是有bug，还是我的规则有问题(图一OK,图二报错)
![QQ截图20240627145034](https://github.com/clash-verge-rev/clash-verge-rev/assets/22128667/23d32a78-152c-418e-9f87-a7838d3e9825)

![QQ截图20240627144930](https://github.com/clash-verge-rev/clash-verge-rev/assets/22128667/d2183877-af33-4580-bf9a-b2f9e1ca896b)

**Comment by lakevilladom** [comment]
> @lakevilladom 不要换行
![QQ截图20240627145442](https://github.com/clash-verge-rev/clash-verge-rev/assets/22128667/08152a9b-fc94-4c6d-ac8a-94fa2f06defc)
还是报错
建议考虑换行情况，毕竟是编辑框，换行编辑起来更友好

**Comment by lakevilladom** [comment]
> > > @lakevilladom 不要换行
> > > ![QQ截图20240627145442](https://private-user-images.githubusercontent.com/22128667/343662677-08152a9b-fc94-4c6d-ac8a-94fa2f06defc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzQxNzgsIm5iZiI6MTcxOTQ3Mzg3OCwicGF0aCI6Ii8yMjEyODY2Ny8zNDM2NjI2NzctMDgxNTJhOWItZmM5NC00YzZkLWFjOGEtOTRmYTJmMDZkZWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA3Mzc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxOTI0NzIwMTg0MzY1ZWVlNzhhNmZjNDBiMzRhNzQ0MzliNWMyMmM3ZGRkMmM5YzEzMWM4YWY0ZGY4NTI4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RRnPpNuPcOLCUpQd_jVd1UHulXNtQZfhx3vPq-iDMGM)
> > > 还是报错
> > > 建议考虑换行情况，毕竟是编辑框，换行编辑起来更友好
> 
> *.coding是域名？ 写法要符合系统代理的绕过规范（Fully Qualified Domain Name），请查阅mircosoft文档。

![111](https://github.com/clash-verge-rev/clash-verge-rev/assets/22128667/5245d7e9-b92b-472e-b9fa-8b759df9e3e3)

这样呢
