### ISSUE TITLE
[BUG] 使用Tun模式，基于域名的规则失效

### ISSUE THREAD

**Issue by yimmr** [clash-verge-rev/clash-verge-rev#1273]
### 问题描述 / Describe the bug

Tun模式下，基于域名的分流规则失效，连接日志只有IP，没有域名记录。
切换到代理模式下是正常的。
安装了最新版clash verge，试过卸载重置应用也没解决。
系统使用wifi网络、配置了dns doh，但是删除dns也没解决。

### 复现步骤 / To Reproduce

 开启Tun模式，关闭代理模式。

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/49950265/5f8eda56-089d-4cfe-8669-169acc881485)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/49950265/904b3e3c-1003-4e3a-8540-4ca420601400)

**Comment by yimmr** [comment]
补充：连接日志中，极少数偶尔会出现一两条域名记录，很少见。chrome浏览器关闭安全浏览也未解决

**Comment by dongchengjie** [comment]
你这个any:853是什么情况？没劫持到，使用本地的53解析了dns然后真实ip入站了

**Comment by wonfen** [comment]
楼上说得很清楚了，你的配置有问题
