### ISSUE TITLE
[Feature] tun模式默认覆盖系统dns设置增加自定义或使用eth0/dhcpdns选项

### ISSUE THREAD

**Issue by utopeadia** [clash-verge-rev/clash-verge-rev#1274]
### 功能描述 / Feature description

tun模式自动调整系统DNS配置能否设置为自定义DNS或者使用eth0/dhcpdns，在一些需要认证的网络环境中，连接外网的前提是认证授权，这一步操作是在内网完成的，需要使用内网解析服务器发送信息，当使用223.5.5.5时，则无法授权登录，关闭tun模式的情况下经过试验在最新的mac中无法将设置恢复，这也导致每次使用网络首先需要手动调整网络设置，带有极大不便，增加一个手动设置项或者使用默认dns确实可以解决问题

### 使用场景 / Use case

需要内网授权访问外网的场景

**Comment by xishang0128** [comment]
@utopeadia 设置内核的dns,因为系统dns理应由内核接管以恢复域名

**Comment by xishang0128** [comment]
@utopeadia https://clash-verge-rev.github.io/guide/merge.html

**Comment by utopeadia** [comment]
> @utopeadia 设置配置文件的dns,因为系统dns理应由软件接管以恢复域名

 目前我的解决方法也是单独设备merge了DNS，不过感觉还是保留DNS会优雅一些，或者至少增加一个关闭tun模式恢复DNS的配置，其实后者是最大的问题

**Comment by xishang0128** [comment]
@utopeadia 我记得关tun或者退出软件是会恢复的

**Comment by utopeadia** [comment]
> 退

按理说是这样的，但是在我的mac这里经常出现关闭失败的情况（系统版本14.5，应用版本最新release）

**Comment by utopeadia** [comment]
> @utopeadia 我记得关tun或者退出软件是会恢复的

按理说是这样的，但是在我的mac这里经常出现关闭失败的情况（系统版本14.5，应用版本最新release）,我不确定是个例还是普遍现象，从代码看退出逻辑是合理无误的，我继续持续关注这个情况

**Comment by shiyan14712** [comment]
> > @utopeadia 我记得关tun或者退出软件是会恢复的
> 
> 按理说是这样的，但是在我的mac这里经常出现关闭失败的情况（系统版本14.5，应用版本最新release）,我不确定是个例还是普遍现象，从代码看退出逻辑是合理无误的，我继续持续关注这个情况

Macbook Air M2 Apple Silicon 系统版本 Sonoma 14.6可以复现BUG，校园网环境/认证网络环境关闭TUN Mode之后需要手动重置DNS中的223,5,5,5才能获取内网DNS。

**Comment by wonfen** [comment]
> > > @utopeadia 我记得关tun或者退出软件是会恢复的
> > 
> > 
> > 按理说是这样的，但是在我的mac这里经常出现关闭失败的情况（系统版本14.5，应用版本最新release）,我不确定是个例还是普遍现象，从代码看退出逻辑是合理无误的，我继续持续关注这个情况
> 
> Macbook Air M2 Apple Silicon 系统版本 Sonoma 14.6可以复现BUG，校园网环境/认证网络环境关闭TUN Mode之后需要手动删掉223.5.5.5的配置项，才能正常访问网络。

使用2.0版这个问题在2.0版中修复了
