### ISSUE TITLE
[Feature]退出应用时关闭系统代理，或者给弹窗提示关闭系统代理

### ISSUE THREAD

**Issue by KilianShen** [clash-verge-rev/clash-verge-rev#1275]
### 功能描述 / Feature description

退出应用时关闭系统代理，或者给弹窗提示关闭系统代理

### 使用场景 / Use case

如果退出后不关闭会无法使用网络

**Comment by MengNianxiaoyao** [comment]
要开自动关闭系统代理啊，有这个功能的

**Comment by KilianShen** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/86402559/9daeea0b-563d-4958-b8df-dbe048f5cca2)
这个吗？

**Comment by AnyWAT** [comment]
日志最后：

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37962734/d637be74-436b-43a8-bc67-41f91f0cfe0e)

**Comment by MystiPanda** [comment]
正常退出是可以自动关闭的，但是你直接关机程序没法执行这些操作。
