### ISSUE TITLE
[Feature] 多机场融合、分流配置方法

### ISSUE THREAD

**Issue by sjhsbhqf** [clash-verge-rev/clash-verge-rev#1277]
### 功能描述 / Feature description

真的非常抱歉，我折腾了一天，凌晨还没搞好，所以想在此求助一下各位大佬。本来想根据“软件指示”在TG群组求助，后来我想是留一下痕迹，让后面的用户很方便根据相同的需求来配置和解决问题。总之，真的是打扰了！！！

我参考的配置文件如下：

[作者：liuran001 - gist - mihomo (Clash Meta) 懒人配置](https://gist.github.com/liuran001/5ca84f7def53c70b554d3f765ff86a33)
[作者：AG - mihomo-config with emoji | Notion Blog](https://ag.cn.eu.org/article/aeecbcc8-b290-4a2f-8025-62742c02260e) 

按道理都是正常的，参考的是meta内核的配置文件。我只是修改了其中的rule-set和机场订阅相关条目。

在软件里新建local配置，然后本地文件选择这个配置文件，我发现没有任何代理节点信息，

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/41407099/f3130f88-bd7a-4fae-9ff8-e39b52b7dfe1)

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/41407099/721e97dd-c16d-48f3-b998-312eb43fc115)

在软件里编辑文件的时候，显示一大堆波浪线和标红。

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/41407099/4bde105f-7ca5-486c-b391-d9efbd5243e6)

实在不清楚咋解决了，按道理这个clash verge rev就是用meta内核，可以用这个配置文件吧？？

### 使用场景 / Use case

多机场融合、自定义分流配置

**Comment by dongchengjie** [comment]
第一行的true直接绷不住

**Comment by sjhsbhqf** [comment]
> 第一行的true直接绷不住

谢谢大佬的提示，我还以为那个博客给的配置文件直接修改机场链接啥的就能直接用呢，原来开头要加一些基本配置项。

我把开头的true理解为了注释掉true才是启用，大错特错了！

另外我还有如下错误需要检讨自己：

1. format的取值不能是txt（而应该是text），这个当时太困了没仔细对照文档
2. yaml配置文件的缩进是通过两个空格实现，而不是缩进
3. proxy-providers里面，一定要配置path

谢谢大佬，我关闭此issue了
