### ISSUE TITLE
[Feature] 升级动态库依赖以支持Ubuntu24.04

### ISSUE THREAD

**Issue by Avenger-285714** [clash-verge-rev/clash-verge-rev#1280]
### 功能描述 / Feature description

    当前的clash-verge 1.6.6版本依赖动态库`libwebkit2gtk-4.0.so.37`和`libjavascriptcoregtk-4.0.so.18`，而这两个版本的动态库在Ubuntu24.04中已被启用，目前取而代之的分别是`libwebkit2gtk-4.1.so.0.13.6`和`libjavascriptcoregtk-4.1.so.0.5.6`。

    即，在安装deb包时会提示依赖不满足：`clash-verge : 依赖: libwebkit2gtk-4.0-37 但无法安装它`,其在Ubuntu24.04中对应的软件包名为`libwebkit2gtk-4.1-0`。
![截图 2024-06-30 18-29-01](https://github.com/clash-verge-rev/clash-verge-rev/assets/60058876/e31a5deb-5ad4-45e3-b7dd-405025b304cf)

    已尝试创建软链接把clash-verge需要的库重定向到当前的系统的新版本的库，并强行修改debian依赖规则重新打包安装，但clash-verge依然无法运行：`libsoup-ERROR **: 18:12:49.955: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.`
![截图 2024-06-30 18-29-42](https://github.com/clash-verge-rev/clash-verge-rev/assets/60058876/2ccc0f4e-f50e-4c76-ac93-42c448680f36)

### 使用场景 / Use case

希望在Ubuntu24.04中正常使用clash-verge。

**Comment by Avenger-285714** [comment]
> “而这两个版本的动态库在Ubuntu24.04中已被启用”

弃用x

**Comment by dongchengjie** [comment]
https://clash-verge-rev.github.io/faq/linux.html#ubuntu-2404

**Comment by Avenger-285714** [comment]
> https://clash-verge-rev.github.io/faq/linux.html#ubuntu-2404

thanks. 原来如此

**Comment by Avenger-285714** [comment]
问题已解决。虽然升级依赖还是早晚的事，但是看来开发者已经知道这个情况了。谢谢大家

**Comment by xishang0128** [comment]
这是tauri依赖的,不是软件能决定的
