### ISSUE TITLE
[BUG] 托盘事件选择显示主窗口时，在深色模式下双击启动会有白色闪屏

### ISSUE THREAD

**Issue by AiKirito** [clash-verge-rev/clash-verge-rev#1282]
### 问题描述 / Describe the bug

托盘事件选择显示主窗口，在深色模式下双击托盘图标启动会有白色闪屏，选择其它功能则不会有白色闪屏

### 复现步骤 / To Reproduce

在设置中将托盘事件选择显示主窗口，关闭主窗口，双击托盘会闪屏，单击托盘不会，而选择其它托盘事件也不会

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

无

**Comment by AnyWAT** [comment]
在系统托盘双击程序图标，没像其它程序不理你已经不错。。。不被判定为非法操作，仅从白到。。。闪屏——能否珍惜下鼠标键，只是单击一下下？哈哈哈
