### ISSUE TITLE
无法选择订阅

### ISSUE THREAD

**Issue by Waylon-jwu** [clash-verge-rev/clash-verge-rev#1286]
### 问题描述 / Describe the bug

无法选择订阅

### 复现步骤 / To Reproduce

proxy 35:ss 195.15.243.171:2048initialize error: unknown method:chacha20-poly1305
订阅链接：https://sub.xeton.dev/sub?target=clash&url=https://9527521.xyz/config/Vn0XxLiUG5ozc7T6&insert=false&config=config/ACL4SSR_Mini.ini

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10

### 日志 / Log

07-02 17:07:28 INFO
TCP]198.18.0.1:3046 -->login.live.com:443 doesn't match any rule using DIRECT
07-02 17:07:28 INFO
[TCP]198.18.0.1:3050 -->183.47.121.104:80 doesn't match any rule using DIRECT
07-02 17:07:28 INFO
[TCP]198.18.0.1:3051 -->183.60.8.69:8080 doesn't match any rule using DIRECT
07-02 17:07:28 INFO
ITCP]198.18.0.1:3054 -->123.151.48.193:443 doesn't match any rule usingDIRECT
07-02 17:07:29 INFO[TCP]198.18.0.1:3062 --> login.live.com:443 doesn't match any rule using DIRECT
07-02 17:07:30 INFOITCP]198.18.0.1:3070--> prod-eastasia.access-point.coudmessaging.edge.microsoft.com:443 doesn't match any rule usingDIRECT
07-02 17:07:30 INFO[TCP]198.18.0.1:3072--> prod-eastasia.access-point.cloudmessaging.edge.microsoft.com:443 doesn't match any rule usingDIRECT

**Comment by dongchengjie** [comment]
内核不支持该加密方法，免费的节点脏是正常的，手动剔除吧
