### ISSUE TITLE
[BUG] 1.7.0 更新订阅会导致profiles目录下多出好多1K的yaml和js

### ISSUE THREAD

**Issue by ztjal** [clash-verge-rev/clash-verge-rev#1289]
### 问题描述 / Describe the bug

只要一点订阅的更新，在\.config\io.github.clash-verge-rev.clash-verge-rev\profiles下边就会多出好多1K的yaml和js文件，再点击又会再生成，无限生成……

### 复现步骤 / To Reproduce

点订阅的更新

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

无必要。

**Comment by xishang0128** [comment]
@ztjal 这是新功能所需要的,而且并不会无限生成

**Comment by armful5862** [comment]
这个功能有一个问题，如果我订阅失败了依旧会创建

**Comment by ztjal** [comment]
> @ztjal 这是新功能所需要的,而且并不会无限生成

就是“无限生成”，一点就成生，再点再生成，继续点继续生成，无限！！！！！！

**Comment by xishang0128** [comment]
@ztjal 请证明无限生成

**Comment by yagaostar** [comment]
是不是无限的不知道，但是我点了十几二十次就有500多个文件了
![c145a4e226581f465796c58279a20cde](https://github.com/clash-verge-rev/clash-verge-rev/assets/151999949/3b091825-0bea-49b3-ad6e-247ba4dc6e83)

**Comment by ztjal** [comment]
> @ztjal 请证明无限生成

你自己“多”点几下更新就知道了。

**Comment by xishang0128** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/assets/95160953/cc150df5-ee9e-40af-bd61-6816461c17f3

事实证明并没有"无限生成"

**Comment by linxiazhixi** [comment]
我试了下，开始添加订阅时候没注意，看到你问题后我去看，确实有1k的yaml和js，然后我把他们删了，再次更新订阅，没有产生新的1k文件。。。只有新添加订阅时候会产生5个1k文件，删掉就好了

**Comment by yagaostar** [comment]
用别的电脑重新试了一下，如果升级到新版本之后没有重新导入订阅的话，点更新订阅就会重复生成配置文件

**Comment by AnyWAT** [comment]
更新到 V1.7.0 后在软件订阅处删除全部订阅，再删除文件夹 profiles 下除 Merge.yaml 与 Script.js 外的其它文件，然后重新订阅导入。貌似——
假如订阅数为 N，则上述文件夹下的总文件总数为：(5+1)*N+2

**Comment by ztjal** [comment]
> 用别的电脑重新试了一下，如果升级到新版本之后没有重新导入订阅的话，点更新订阅就会重复生成配置文件

不够，\.config\io.github.clash-verge-rev.clash-verge-rev\profiles.yaml文件已经被污染了，之前点的更新多的话，会有有大量的

- uid: mWI6yTYABmdh
  type: merge
  name: null
  file: mWI6yTYABmdh.yaml
  updated: 1719943300
- uid: s45NqYtkcxvf
  type: script
  name: null
  file: s45NqYtkcxvf.js
  updated: 1719943300

只能用备份的旧版配置文件再重新搞一次，保证没多余数据污染配置文件。

**Comment by ztjal** [comment]
总结一下旧版升1.7.0的订阅配置问题：

因新版增加了局部概念，profiles.yaml对应增加了配置，如：

- uid: gOGlCwDIh97K
  type: groups
  name: null
  file: gOGlCwDIh97K.yaml
  updated: 1719948004

    merge: mv9s61oNcVZX
    script: srXhui0GEzUd
    rules: rYrKtkSjfNSD
    proxies: pwCztDPKwdhD
    groups: gOGlCwDIh97K

但，局部的配置目前只能以新增订阅的形式同时添加。
旧版订阅点更新的话，因没有profiles的对应项目，导致文件不断增加，profiles也会写入，导致污染了配置文件。
当前修BUG的建议也很简单，对订阅更新增加新东西merge，script，rules，proxies，groups的判断，反正明白人也不用多说了。
