### ISSUE TITLE
[BUG] 内网开启代理, 即使是直连也无法访问目标地址

### ISSUE THREAD

**Issue by chenjiangui** [clash-verge-rev/clash-verge-rev#129]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/18565140/40d8a147-fde1-46e0-b9be-bf390fcd4521)
1. 打开代理 选择直连模式就无法访问内网的地址, 该地址在公网无法被解析
2. 启用规则模式 添加 rules: xxxxx direct 可以访问成功
3. 用merge配置 append rules: xxxxx direct 无法访问成功

### To Reproduce

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/18565140/40d8a147-fde1-46e0-b9be-bf390fcd4521)
1. 打开代理 选择直连模式就无法访问内网的地址, 该地址在公网无法被解析
2. 启用规则模式 添加 rules: xxxxx direct 可以访问成功
3. 用merge配置 append rules: xxxxx direct 无法访问成功

### Platform

MacOS

### System Version

macOS 13.5.2 (22G91)

### Software Version

1.4.4

**Comment by chenjiangui** [comment]
1. 经测试是订阅的DNS配置与内网的DNS冲突, 所以merge 的 direct会失效
2. 直连模式估计自带了个默认的DNS, 也会有问题

有办法忽略DNS 或者 merge的时候覆盖DNS配置吗

**Comment by S-T-eve** [comment]
如果没记错，可以去杂项设置把clash字段过滤给关闭了，然后在Merge里写完整的dns段，Merge内的能覆盖原始的dns段

**Comment by chenjiangui** [comment]
> 如果没记错，可以去杂项设置把clash字段过滤给关闭了，然后在Merge里写完整的dns段，Merge内的能覆盖原始的dns段

感谢, closed

**Comment by zbrnwpu** [comment]
> 如果没记错，可以去杂项设置把clash字段过滤给关闭了，然后在Merge里写完整的dns段，Merge内的能覆盖原始的dns段

这个具体怎么设置哈？能解释得再详细么 @chenjiangui @S-T-eve
