### ISSUE TITLE
[BUG] v1.7.0版无法使用锚点格式配置

### ISSUE THREAD

**Issue by Troray** [clash-verge-rev/clash-verge-rev#1291]
### 问题描述 / Describe the bug

在v1.6.6(含)之前，我一直使用的都是免安装版，且使用同一个配置一直很正常。以前每次更新免安装版我都是下载解压覆盖。

在v1.7.0发布后，我同样下载免安装版解压覆盖，发现无法正常运行，双击即闪退。

然后，换了一个路径，解压后，可以正常打开了，但是，当我把配置文件(锚点)拖入并选择后，立即闪退。

之后，尝试使用普通clash配置文件，发现可以正常使用，但是当选择锚点配置的配置文件后，就闪退了。且没有报错日志。

我使用的配置文件和 [这个](https://raw.githubusercontent.com/Coldvvater/Mononoke/master/Clash/Config/Evolve.yaml)差不多，也用这个尝试过，均无法正常使用。

### 复现步骤 / To Reproduce

如描述

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

无报错相关日志

**Comment by beckyeeky** [comment]
正常升级后发现相同问题
卸载清空配置文件后再次导入依旧闪退

**Comment by capsulae** [comment]
> 正常升级后发现相同问题 卸载清空配置文件后再次导入依旧闪退

一样的问题

**Comment by wonfen** [comment]
试试1.7.2
