### ISSUE TITLE
[BUG] 1.7.0 Merge 中 prepend-* 规则无效

### ISSUE THREAD

**Issue by 1wingedangel** [clash-verge-rev/clash-verge-rev#1292]
### 问题描述 / Describe the bug

更新到 1.7.0 之后，无论是全局的扩展配置还是订阅的扩展配置，clash verge 会把 prepend-* 系列的扩展规则直接覆写在 clash 配置文件里，而不是插入到如rules、proxy-groups 的开头部分。

### 复现步骤 / To Reproduce

* 新建订阅
* 右键，设置扩展配置
* 写入 prepend-rules 规则
* 保存
* 查看运行时订阅，发现在yaml里插入的规则直接作为 prepend-rules 写入到了配置文件里，而不是插入到rules开头

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

无

**Comment by lunyang** [comment]
Mac端，1.7.0同样的问题，prepend-rules不生效

**Comment by SamuNatsu** [comment]
似乎 1.7.0 把 Merge 规则改成了直接合并到配置文件，因此像是 prepend-* 或者 append-* 这种特殊规则不会进行处理了

可能以后只能通过 Script 来实现特定位置的规则合并了

感觉这不是一个特别好的更新

**Comment by nogoo** [comment]
同问，以前的扩展配置，拷贝进1.70的全局扩展配置，无效！！！！

**Comment by vayocc** [comment]
> 同问，以前的扩展配置，拷贝进1.70的全局扩展配置，无效！！！！

同，求解

**Comment by oreeke** [comment]
现在规则只能通过前端“编辑规则”配置..有点不方便

**Comment by reboothit** [comment]
> 现在规则只能通过前端“编辑规则”配置..有点不方便
local 订阅才可以“编辑规则”
remote订阅不可以
怎么办呢？

**Comment by reboothit** [comment]
> 现在规则只能通过前端“编辑规则”配置..有点不方便

local 订阅才可以“编辑规则”
remote订阅不可以
怎么办呢？

**Comment by Luciennnnnnn** [comment]
<img width="732" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/20135317/250b6c31-3dd3-4420-9674-dbd982b09d99">
我编辑规则还会报错

**Comment by 1wingedangel** [comment]
在这个问题没有解决之前，可能会对特定网络环境的网络访问造成影响，我先在这里贴一个 script 版的 Workaround：

```js
const YYYYRules = [
  'GEOSITE,zhihu,YYYY', 
  'GEOSITE,bilibili,YYYY'
];
const YYYYProxy = [
  {
    name:'YYYY',
    type:'select',
    proxies:['Domestic','Proxy']
}

];

function main(config) {
  config['rules'] = [...YYYYRules,...config['rules']];
  config['proxy-groups'] = [...YYYYProxy,...config['proxy-groups']];
  return config;
}
```
这样就能实现 rules 和 proxy-groups的插入。其他插入的情况大家可以去问问gpt或者其他AI模型来解决。

**Comment by oreeke** [comment]
> > 现在规则只能通过前端“编辑规则”配置..有点不方便
> 
> local 订阅才可以“编辑规则” remote订阅不可以 怎么办呢？

需要重新导入一下订阅

**Comment by troublewind** [comment]
profiles目录还会生成一堆1kb的空模板yaml，不懂什么作用

**Comment by QIN2DIM** [comment]
@Luciennnnnnn 全局扩展配置有个配置了 profile 的 demo config，这个配置的写法是有问题的，会直接报错。打开控制台可以看到满屏的 `Uncaught (in promise) failed to get the profile item "uid:"`，把这个全局配置全删掉用脚本去做 prepend / append rules 的操作

**Comment by QIN2DIM** [comment]
以下是一个 做 prepend-rules 和 prepend-proxy-groups 全局扩展脚本 demo

```typescript
// Define main function (script entry)
function main(config) {
    const prependRules = [
        "DOMAIN-SUFFIX,csdn.net,DIRECT",
        "DOMAIN-SUFFIX,xiaohongshu.com,DIRECT",
        "DOMAIN-SUFFIX,mail.qq.com,DIRECT",
        "DOMAIN-SUFFIX,xueqiu.com,DIRECT"
    ];

    const prependProxyGroups = [
        // {
        //     name: "ChatGPT",
        //     type: "select",
        //     proxies: ["YOUR_PROXY"]
        // },
        {}
    ];

    return {
        ...config,
        rules: [...prependRules, ...(config.rules || [])],
        "proxy-groups": [...prependProxyGroups, ...(config['proxy-groups'] || [])]
    };
}
```

**Comment by RainyH2O** [comment]
扩展配置都应该加个开关吧，保存了不能临时停用不如以前灵活。

**Comment by vayocc** [comment]
根据上面大佬的配置，我也贴一个我比葫芦画瓢的，如果又更好的配置请告诉我
// Define main function (script entry)
const prependRules = [
  'DOMAIN-SUFFIX,openai.com,🐟漏网之鱼',
  'DOMAIN-SUFFIX,chat.openai.com,🐟漏网之鱼',
  'DOMAIN-SUFFIX,auth0.openai.com,🐟漏网之鱼',
  'DOMAIN-SUFFIX,platform.openai.com,🐟漏网之鱼',
  'DOMAIN,openaiapi-site.azureedge.net,🐟漏网之鱼',
  'DOMAIN,chatgpt.com,🐟漏网之鱼',
  'DOMAIN,auth.openai.com,🐟漏网之鱼',
  'DOMAIN,netflix.com,🐟漏网之鱼'
];
const directRules = [
  'DOMAIN-SUFFIX,cn.bing.com,DIRECT',
  'DOMAIN-SUFFIX,amazonaws.cn,DIRECT',
  'DOMAIN-SUFFIX,amazonaws.com.cn,DIRECT'
];

const appendProxyGroups = [
  {
    name: '🐟漏网之鱼',
    type: 'select',
    'include-all-proxies': true,
    filter: '(?i)坡|SG|新加坡|美|US|美国|日|JP|日本|GPT'
  }
];


function main(config) {
  config['rules'] = [...directRules,...prependRules,...config['rules']];
  config['proxy-groups'] = [...appendProxyGroups,...config['proxy-groups']];
  return config;
}

**Comment by vayocc** [comment]
根据上面大佬的配置，我也贴一个我比葫芦画瓢的，如果又更好的配置请告诉我
`// Define main function (script entry)
const prependRules = [
  'DOMAIN-SUFFIX,openai.com,🐟漏网之鱼',
  'DOMAIN-SUFFIX,chat.openai.com,🐟漏网之鱼',
  'DOMAIN-SUFFIX,auth0.openai.com,🐟漏网之鱼',
  'DOMAIN-SUFFIX,platform.openai.com,🐟漏网之鱼',
  'DOMAIN,openaiapi-site.azureedge.net,🐟漏网之鱼',
  'DOMAIN,chatgpt.com,🐟漏网之鱼',
  'DOMAIN,auth.openai.com,🐟漏网之鱼',
  'DOMAIN,netflix.com,🐟漏网之鱼'
];
const directRules = [
  'DOMAIN-SUFFIX,cn.bing.com,DIRECT',
  'DOMAIN-SUFFIX,amazonaws.cn,DIRECT',
  'DOMAIN-SUFFIX,amazonaws.com.cn,DIRECT'
];

const appendProxyGroups = [
  {
    name: '🐟漏网之鱼',
    type: 'select',
    'include-all-proxies': true,
    filter: '(?i)坡|SG|新加坡|美|US|美国|日|JP|日本|GPT'
  }
];


function main(config) {
  config['rules'] = [...directRules,...prependRules,...config['rules']];
  config['proxy-groups'] = [...appendProxyGroups,...config['proxy-groups']];
  return config;
}
`

**Comment by vayocc** [comment]
根据上面大佬的配置，我也贴一个我比葫芦画瓢的，如果又更好的配置请告诉我
```js
// Define main function (script entry)
const prependRules = [
  'DOMAIN-SUFFIX,openai.com,🐟漏网之鱼',
  'DOMAIN-SUFFIX,chat.openai.com,🐟漏网之鱼',
  'DOMAIN-SUFFIX,auth0.openai.com,🐟漏网之鱼',
  'DOMAIN-SUFFIX,platform.openai.com,🐟漏网之鱼',
  'DOMAIN,openaiapi-site.azureedge.net,🐟漏网之鱼',
  'DOMAIN,chatgpt.com,🐟漏网之鱼',
  'DOMAIN,auth.openai.com,🐟漏网之鱼',
  'DOMAIN,netflix.com,🐟漏网之鱼'
];
const directRules = [
  'DOMAIN-SUFFIX,cn.bing.com,DIRECT',
  'DOMAIN-SUFFIX,amazonaws.cn,DIRECT',
  'DOMAIN-SUFFIX,amazonaws.com.cn,DIRECT'
];

const appendProxyGroups = [
  {
    name: '🐟漏网之鱼',
    type: 'select',
    'include-all-proxies': true,
    filter: '(?i)坡|SG|新加坡|美|US|美国|日|JP|日本|GPT'
  }
];


function main(config) {
  config['rules'] = [...directRules,...prependRules,...config['rules']];
  config['proxy-groups'] = [...appendProxyGroups,...config['proxy-groups']];
  return config;
}

```

**Comment by htfcuddles** [comment]
同样问题，1.7版本后Merge中的prepend-* 或者 append-* 规则失效了，但Wiki中还是显示支持的。需要在Gui中右键订阅，点击规则-高级来代替。

**Comment by hgaogao** [comment]
全局扩展配置的参数现在还支持那些呢？要去哪里看文档？

**Comment by Phinsin666** [comment]
@QIN2DIM 感谢，我是套用别人的本地配置的，结果新版本取消了merge，使用你的脚本配置添加部分网站进行直连/代理很好用

**Comment by cqhtyi** [comment]
@vayocc 参考您的配置，找ChatGPT进一步修改了一下，并增加了修复 sub.xeton.dev订阅会报“MATCH,,🐟 漏网之鱼,dns-failed”的错误。

`function main(config) {
  const prependRules = [
    'DOMAIN-SUFFIX,gstatic.com,🐟 漏网之鱼',
    'DOMAIN-SUFFIX,openai.com,🎯 自定义',
    'DOMAIN-SUFFIX,chat.openai.com,🎯 自定义',
    'DOMAIN-SUFFIX,auth0.openai.com,🎯 自定义',
    'DOMAIN-SUFFIX,platform.openai.com,🎯 自定义',
    'DOMAIN,openaiapi-site.azureedge.net,🎯 自定义',
    'DOMAIN,chatgpt.com,🎯 自定义',
    'DOMAIN,auth.openai.com,🎯 自定义',
    'DOMAIN,netflix.com,🎯 自定义'
  ];

  const directRules = [
    'DOMAIN-SUFFIX,cn.bing.com,DIRECT',
    'DOMAIN-SUFFIX,amazonaws.cn,DIRECT',
    'DOMAIN-SUFFIX,amazonaws.com.cn,DIRECT'
  ];

  const appendProxyGroups = [
    {
      name: '🎯 自定义',
      type: 'select',
      'include-all-proxies': true,
      filter: '(?i)坡|SG|新加坡|美|US|美国|日|JP|日本|GPT'
    }
  ];

  // 检查并过滤掉不需要的规则
  const filteredRules = config.rules.includes("MATCH,,🐟 漏网之鱼,dns-failed")
    ? config.rules.filter(rule => rule !== "MATCH,,🐟 漏网之鱼,dns-failed")
    : config.rules;

  // 检查是否存在 "MATCH,🐟 漏网之鱼" 规则
  const hasMatchRule = filteredRules.includes("MATCH,🐟 漏网之鱼");

  // 定义新的规则数组
  const rules = [
    ...prependRules,  // 添加 prependRules 到最前面
    ...directRules,   // 添加 directRules 到前面
    ...filteredRules, // 将过滤后的规则展开并添加到新的规则数组中
  ];

  // 如果不存在 "MATCH,🐟 漏网之鱼" 规则，则在末尾添加
  if (!hasMatchRule) {
    rules.push("MATCH,🐟 漏网之鱼");
  }

  // 更新 config 对象中的 rules 属性
  config.rules = rules;

  // 更新 config 对象中的 proxy-groups 属性
  config['proxy-groups'] = [...appendProxyGroups, ...config['proxy-groups']];

  // 返回更新后的 config 对象
  return config;
}
`
