### ISSUE TITLE
[BUG] 旧本地模板闪退

### ISSUE THREAD

**Issue by kindle939393** [clash-verge-rev/clash-verge-rev#1295]
### 问题描述 / Describe the bug

[config.txt](https://github.com/user-attachments/files/16076742/config.txt)
文件在这里，一点就闪退，然后就打不开了。安装回旧版本后正常

### 复现步骤 / To Reproduce

导入文件就这样

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

1

**Comment by LaolunsiG** [comment]
windows10同上

**Comment by huaxing211** [comment]
win11同上，不能导入订阅文件，闪退！

**Comment by zhangweilan** [comment]
@LaolunsiG 一样，点击使用后就闪退

**Comment by wonfen** [comment]
试试1.7.2

**Comment by kindle939393** [comment]
新版本已解决
