### ISSUE TITLE
[BUG] 1.7.0以上的版本不能设置系统代理、Tun模式和不能上网

### ISSUE THREAD

**Issue by lgf5090** [clash-verge-rev/clash-verge-rev#1296]
### 问题描述 / Describe the bug

1.7.0以上的版本不能设置系统代理、Tun模式和不能上网，在面板可以设置，但是托盘图标右键不可以设置（点击没有打上勾）。 1.6.6版本是没有问题的。
![PixPin_2024-07-03_11-33-13](https://github.com/clash-verge-rev/clash-verge-rev/assets/170180789/0c08043d-388c-4352-9b55-e137b46c9c92)

### 复现步骤 / To Reproduce

安装完成后分别在控制面板和系统托盘图标进行设置。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

24H2 (OS 内部版本 26100.1000)

### 日志 / Log

没有日志

**Comment by wonfen** [comment]
日志？这点信息无法判断

**Comment by WinteWu** [comment]
是不是内核升级导致的？我升级后也是各种报错，已经降级到1.6了

**Comment by leic4u** [comment]
同样的问题。开启 tun 模式提示成功了，但没有创建网卡，没有成功接管到流量。

**Comment by xingchen-FL** [comment]
同样的问题，TUN模式里面，GVisor、 Mixed、system模式都试过了，内核切换也试过了，没有接管流量

**Comment by carterywx** [comment]
同样的问题，我这里GVisor可以用 ，但System和Mixed都是TCP连接失败。换回v1.18.5 Meta一切正常。

**Comment by leic4u** [comment]
貌似是因为网卡名称从 Meta 更换为 Mihomo 导致的问题。

必须要干净卸载，清理掉配置文件后，重新安装服务模式，就可以正常启动 TUN 模式了。

**Comment by person2217** [comment]
补个我的同样问题日志
[2024-07-08-0856.log](https://github.com/user-attachments/files/16123303/2024-07-08-0856.log)
[2024-07-08-0858.log](https://github.com/user-attachments/files/16123304/2024-07-08-0858.log)
[2024-07-08-0849.log](https://github.com/user-attachments/files/16123305/2024-07-08-0849.log)

**Comment by person2217** [comment]
补充，刚我没装服务模式，现在tun模式正常。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/106829332/345f94c3-5d62-40ad-9390-047e3b6401fe)
全局模式，规则模式的系统代理用不了

**Comment by whiskerside** [comment]
<img width="615" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/101848978/5d0b54cf-03b7-4ea7-a41f-3e170491eaa7">
这样是工作的

**Comment by person2217** [comment]
> <img alt="image" width="615" src="https://private-user-images.githubusercontent.com/101848978/346569710-5d0b54cf-03b7-4ea7-a41f-3e170491eaa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDM2MjksIm5iZiI6MTcyMDQ0MzMyOSwicGF0aCI6Ii8xMDE4NDg5NzgvMzQ2NTY5NzEwLTVkMGI1NGNmLTAzYjctNGVhNy1hNDFmLTNlMTcwNDkxZWFhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMjU1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjIxYjRiNmZjM2NlOGU5ZmEwODA3N2E5YmNkOTFkNWVkZGUyNzM4NjU3NWU4MzdiMmQyZGFiODcxMDlkOWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a1G6G_7Vcf03kOh4Pjuas7uK0l8uWy0YsVzRB39bVrw"> 这样是工作的

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/106829332/94caf3f2-a0d8-49ff-844a-5a7e49fa76e8)
![Uploading image.png…]()
我的是这样设置，这里改为meta或者Mihomo，我都tun模式都可以正常使用。但系统代理模式都不能正常使用。

**Comment by person2217** [comment]
我的问题已解决：软件更新过后，clash-verge-rev的系统代理不能覆盖浏览中自带的vpn插件设置。导致问题出现。

**Comment by dragonheartcra** [comment]
> 我的问题已解决：软件更新过后，clash-verge-rev的系统代理不能覆盖浏览中自带的vpn插件设置。导致问题出现。

所以最后是如何解决的,我也无法开启系统代理

**Comment by person2217** [comment]
> > 我的问题已解决：软件更新过后，clash-verge-rev的系统代理不能覆盖浏览中自带的vpn插件设置。导致问题出现。
> 
> 所以最后是如何解决的,我也无法开启系统代理

简而言之，6.x版本中，即使我浏览器有代理插件，但还是会优先clash verge-rev的代理，而更新到7.x版本后现在优先浏览器插件代理，让我误认为clash有问题。关闭浏览器代理插件即可。

**Comment by person2217** [comment]
![image](https://github.com/user-attachments/assets/1e55bc3f-8ac9-49a9-87c1-1ab41d804dc9)
我是忘记了这个插件也是代理。我正常tun模式正常
