### ISSUE TITLE
[BUG] 右键订阅 ->编辑代理组实际内容是加到节点proxies里了

### ISSUE THREAD

**Issue by ansemz** [clash-verge-rev/clash-verge-rev#1297]
### 问题描述 / Describe the bug

右键订阅 -> 编辑代理组，增加自己定义的proxygroup。但是发现内容实际加到节点proxies部分了。
右键订阅 -> 编辑代理组和右键订阅 -> 编辑节点，显示的内容也是一样。

### 复现步骤 / To Reproduce

右键订阅 -> 编辑代理组，增加自定义的代理组，比如type: url-test，会提示type不正确，查看生效的配置，发现增加的内容在节点部分。右键订阅 -> 编辑节点，也可能看到编辑代理组增加的内容。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 23h2，macos 12.7.5

### 日志 / Log

2024-07-03 11:31:29 ERROR - proxy 52: unsupport proxy type: url-test

**Comment by MystiPanda** [comment]
@ansemz alpha 已经修了
