### ISSUE TITLE
[Feature] 批量导入prepend/append规则

### ISSUE THREAD

**Issue by BrandonStudio** [clash-verge-rev/clash-verge-rev#1299]
### 功能描述 / Feature description

允许对指定配置文件批量导入前置/后置规则

### 使用场景 / Use case

1.6版本中，可以使用Merge配置，在其中定义Prepend-rules，该配置可以轻易地复制粘贴，从而实现批量导入导出
1.7版本中，取消了单项Merge配置，并且取消了merge配置中的prepend-rules，只能一个一个添加规则，费时费力。而且若一个规则集需要应用到多个配置，需要反复一个一个添加

**Comment by excavate** [comment]
我也有此问题，同一个prepend规则想应用于多个订阅应该怎么写
