### ISSUE TITLE
请教如何使用自定义规则

### ISSUE THREAD

**Issue by monsoon585** [clash-verge-rev/clash-verge-rev#13]
原来在CFW里用的自定义规则，导入clash-verge-rev后报错，请教应该如何设置，谢谢！
我的操作如下：

在订阅里新建一个Local file，导入在CFW里使用的设置文件
![2023-11-25_213615](https://github.com/wonfen/clash-verge-rev/assets/152015276/3fa67174-8a14-43f4-a530-47284c0cd2c0)

设置文件内容如下：
[l47XSBdm9xMP.txt](https://github.com/wonfen/clash-verge-rev/files/13464379/l47XSBdm9xMP.txt)

软件报错
![2023-11-25_213701](https://github.com/wonfen/clash-verge-rev/assets/152015276/20090ac6-abf3-4219-a855-de4a3ce7e581)

**Comment by it-glen** [comment]
你的proxy-providers写的有问题吧
![image](https://github.com/wonfen/clash-verge-rev/assets/73119626/32168359-bfaa-4ef0-866b-79870935ba07)

**Comment by monsoon585** [comment]
> 你的proxy-providers写的有问题吧 ![image](https://private-user-images.githubusercontent.com/73119626/285628272-32168359-bfaa-4ef0-866b-79870935ba07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTgwMzEsIm5iZiI6MTcwMDk5NzczMSwicGF0aCI6Ii83MzExOTYyNi8yODU2MjgyNzItMzIxNjgzNTktYmZhYS00ZWYwLTg2NmItNzk4NzA5MzViYTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDExMjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZmQ3NTc5MGYyNDQ2NjA1NTFlOTQ4MDQzODMzNDg5NDc2OGE0NmQyOGY4YzYyOGI0Mjg5NDdhMWQ4YzY3YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cqaOX9XxPF0qw7Z0T4VehLiUaX5R5ctrFbcPrUoSp3A) url后面填上你的订阅链接，或者类型改成file

还是报错
是需要自己新建一个provider1.yaml文件吗‪
比如我在这个目录新建了一下C:\Users\monsoon\.config\clash-verge\proxy_providers\AMY.yaml
这个文件里是要自己写代码吗

**Comment by it-glen** [comment]
那你就把订阅链接填上，path改成相对路径 ./proxy_providers/名字随便.yaml，他会自动下载这个文件，不用自己创建

**Comment by it-glen** [comment]
> > 你的proxy-providers写的有问题吧 ![image](https://private-user-images.githubusercontent.com/73119626/285628272-32168359-bfaa-4ef0-866b-79870935ba07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTgwMzEsIm5iZiI6MTcwMDk5NzczMSwicGF0aCI6Ii83MzExOTYyNi8yODU2MjgyNzItMzIxNjgzNTktYmZhYS00ZWYwLTg2NmItNzk4NzA5MzViYTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDExMjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZmQ3NTc5MGYyNDQ2NjA1NTFlOTQ4MDQzODMzNDg5NDc2OGE0NmQyOGY4YzYyOGI0Mjg5NDdhMWQ4YzY3YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cqaOX9XxPF0qw7Z0T4VehLiUaX5R5ctrFbcPrUoSp3A) url后面填上你的订阅链接，或者类型改成file
> 
> 还是报错 是需要自己新建一个provider1.yaml文件吗‪ 比如我在这个目录新建了一下C:\Users\monsoon.config\clash-verge\proxy_providers\AMY.yaml 这个文件里是要自己写代码吗

那你就把订阅链接填上，path改成相对路径 ./proxy_providers/名字随便.yaml，他会自动下载这个文件，不用自己创建

**Comment by monsoon585** [comment]
> > > 你的proxy-providers写的有问题吧 ![image](https://private-user-images.githubusercontent.com/73119626/285628272-32168359-bfaa-4ef0-866b-79870935ba07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTgwMzEsIm5iZiI6MTcwMDk5NzczMSwicGF0aCI6Ii83MzExOTYyNi8yODU2MjgyNzItMzIxNjgzNTktYmZhYS00ZWYwLTg2NmItNzk4NzA5MzViYTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDExMjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZmQ3NTc5MGYyNDQ2NjA1NTFlOTQ4MDQzODMzNDg5NDc2OGE0NmQyOGY4YzYyOGI0Mjg5NDdhMWQ4YzY3YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cqaOX9XxPF0qw7Z0T4VehLiUaX5R5ctrFbcPrUoSp3A) url后面填上你的订阅链接，或者类型改成file
> > 
> > 
> > 还是报错 是需要自己新建一个provider1.yaml文件吗‪ 比如我在这个目录新建了一下C:\Users\monsoon.config\clash-verge\proxy_providers\AMY.yaml 这个文件里是要自己写代码吗
> 
> 那你就把订阅链接填上，path改成相对路径 ./proxy_providers/名字随便.yaml，他会自动下载这个文件，不用自己创建

我就是这么干的，因为在CFW里我也是这么干的，没问题，现在在这个软件里就报错。。。

**Comment by it-glen** [comment]
> > > > 你的proxy-providers写的有问题吧 ![image](https://private-user-images.githubusercontent.com/73119626/285628272-32168359-bfaa-4ef0-866b-79870935ba07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTgwMzEsIm5iZiI6MTcwMDk5NzczMSwicGF0aCI6Ii83MzExOTYyNi8yODU2MjgyNzItMzIxNjgzNTktYmZhYS00ZWYwLTg2NmItNzk4NzA5MzViYTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDExMjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZmQ3NTc5MGYyNDQ2NjA1NTFlOTQ4MDQzODMzNDg5NDc2OGE0NmQyOGY4YzYyOGI0Mjg5NDdhMWQ4YzY3YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cqaOX9XxPF0qw7Z0T4VehLiUaX5R5ctrFbcPrUoSp3A) url后面填上你的订阅链接，或者类型改成file
> > > 
> > > 
> > > 还是报错 是需要自己新建一个provider1.yaml文件吗‪ 比如我在这个目录新建了一下C:\Users\monsoon.config\clash-verge\proxy_providers\AMY.yaml 这个文件里是要自己写代码吗
> > 
> > 
> > 那你就把订阅链接填上，path改成相对路径 ./proxy_providers/名字随便.yaml，他会自动下载这个文件，不用自己创建
> 
> 我就是这么干的，因为在CFW里我也是这么干的，没问题，现在在这个软件里就报错。。。

我用你这个配置文件就没问题
![image](https://github.com/wonfen/clash-verge-rev/assets/73119626/479246f6-fbf4-4d35-ba31-d8c0255bbe35)

**Comment by monsoon585** [comment]
> > > > > 你的proxy-providers写的有问题吧 ![image](https://private-user-images.githubusercontent.com/73119626/285628272-32168359-bfaa-4ef0-866b-79870935ba07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTgwMzEsIm5iZiI6MTcwMDk5NzczMSwicGF0aCI6Ii83MzExOTYyNi8yODU2MjgyNzItMzIxNjgzNTktYmZhYS00ZWYwLTg2NmItNzk4NzA5MzViYTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDExMjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZmQ3NTc5MGYyNDQ2NjA1NTFlOTQ4MDQzODMzNDg5NDc2OGE0NmQyOGY4YzYyOGI0Mjg5NDdhMWQ4YzY3YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cqaOX9XxPF0qw7Z0T4VehLiUaX5R5ctrFbcPrUoSp3A) url后面填上你的订阅链接，或者类型改成file
> > > > 
> > > > 
> > > > 还是报错 是需要自己新建一个provider1.yaml文件吗‪ 比如我在这个目录新建了一下C:\Users\monsoon.config\clash-verge\proxy_providers\AMY.yaml 这个文件里是要自己写代码吗
> > > 
> > > 
> > > 那你就把订阅链接填上，path改成相对路径 ./proxy_providers/名字随便.yaml，他会自动下载这个文件，不用自己创建
> > 
> > 
> > 我就是这么干的，因为在CFW里我也是这么干的，没问题，现在在这个软件里就报错。。。
> 
> 我用你这个配置文件就没问题 ![image](https://private-user-images.githubusercontent.com/73119626/285653135-479246f6-fbf4-4d35-ba31-d8c0255bbe35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMDQ3NDYsIm5iZiI6MTcwMTAwNDQ0NiwicGF0aCI6Ii83MzExOTYyNi8yODU2NTMxMzUtNDc5MjQ2ZjYtZmJmNC00ZDM1LWJhMzEtZDhjMDI1NWJiZTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDEzMTQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNTQ5MzI2NzNkYzUzNDQyYTRjZDk5ZDQ2ZmFlM2E5YzNlNGQ5YzI1NzNhMjRlYmY0ZTNiOGEyNjA0NDI2OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iK3mM1KHkbOc-vGrbf7umj4Mp3Ka-8_xq4MZl40CZKk)

太诡异了，那我再检查下，谢谢老兄！
