### ISSUE TITLE
[BUG] hysteria2链接在最新的2个需要重新导入订阅的版本失效了

### ISSUE THREAD

**Issue by xwgodxwgod** [clash-verge-rev/clash-verge-rev#1303]
### 问题描述 / Describe the bug

hysteria2链接在最新的2个需要重新导入订阅的版本失效了
在升级前正常
vmess和trojan正常

### 复现步骤 / To Reproduce

直接覆盖升级，重新导入用同一个配置文件

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11

### 日志 / Log

无

**Comment by wonfen** [comment]
无日之无截图无bug

**Comment by xwgodxwgod** [comment]
> 无日志无截图无bug

hysteria2链接升级前能打开网页，升级后网页打不开了
