### ISSUE TITLE
[BUG] 升级到1.7.2后，已经重新导入配置，启动tun 模式时 报错了

### ISSUE THREAD

**Issue by agassiz** [clash-verge-rev/clash-verge-rev#1304]
### 问题描述 / Describe the bug

我看内核换名了，我也启动了服务模式，就是不行

### 复现步骤 / To Reproduce

删除本地的，重新下载安装还是不行

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

13.6.7

### 日志 / Log

日志内容：
07-03 14:41:27ERROR
Start DNS server error: listen udp 0.0.0.0:5353: bind: address already in use
07-03 14:41:27WARNING
[TUN] Unsupported tunName(Mihomo) in darwin, force regenerate by ourselves.
07-03 14:41:27WARNING
[TUN] default interface changed by monitor, => en0

**Comment by leic4u** [comment]
我倒没报错，一切都提示正常，但没有成功创建网卡，没有接管到系统流量。

**Comment by lanytcc** [comment]
我刚升级也是，导致我用回旧版了，但是今天重新装上，我打开软件等了好大一会才操作的，然后就没问题了

**Comment by leic4u** [comment]
> 我倒没报错，一切都提示正常，但没有成功创建网卡，没有接管到系统流量。

貌似是因为网卡名称从 Meta 更换为 Mihomo 导致的问题。

必须要干净卸载，清理掉配置文件后，重新安装服务模式，就可以正常启动 TUN 模式了。

**Comment by fllesser** [comment]
<img width="574" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/64878354/5bb949ab-aacf-4684-a5f8-1d3597f68234">

**Comment by fllesser** [comment]
<img width="574" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/64878354/bdbe66d3-4409-4587-96a2-712a3cfd778b">
我也用不了tun，不过和你日志不太一样

**Comment by fllesser** [comment]
你们解决了吗

**Comment by agassiz** [comment]
先更新要到最新的 alpha ,问题就解决了，先临时用 alpha 版本，目前一切正常

**Comment by fangguangyang** [comment]
> <img alt="image" width="574" src="https://private-user-images.githubusercontent.com/64878354/346251882-bdbe66d3-4409-4587-96a2-712a3cfd778b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDE3OTcsIm5iZiI6MTcyMTEwMTQ5NywicGF0aCI6Ii82NDg3ODM1NC8zNDYyNTE4ODItYmRiZTY2ZDMtNDQwOS00NTg3LTk2YTItNzEyYTNjZmQ3NzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDAzNDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YmQ1YTc4NmZhODYzYzU3MWE5MWM5NmYyMmM1Yjk0YTA5MWQzOTdiYmVlNTNiZGM1OTg1NDdiZmM5MzExYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JfZ8kMd3HWWh-tIq7GSdbcpi5RZBNvV-CD3FzhNaAVQ"> 我也用不了tun，不过和你日志不太一样

我也是报这个错，你解决了没
