### ISSUE TITLE
[Feature] 【更新所有订阅】不要更新【更新间隔】为0的订阅

### ISSUE THREAD

**Issue by banshaobao** [clash-verge-rev/clash-verge-rev#1305]
### 功能描述 / Feature description

【更新所有订阅】不要更新【更新间隔】为0的订阅。就是因为不想更新才设置了【更新间隔】为0。想更新的时候会手动点击【更新】按钮。

### 使用场景 / Use case

就是因为不想更新才设置了【更新间隔】为0。想更新的时候会手动点击【更新】按钮。

**Comment by MystiPanda** [comment]
不想更新那你不要设置间隔好不好啊

**Comment by banshaobao** [comment]
> 不想更新那你不要设置间隔好不好啊

没有设置间隔

**Comment by banshaobao** [comment]
> 不想更新那你不要设置间隔好不好啊

没有设置间隔

**Comment by MystiPanda** [comment]
我才明白你是什么意思，这需求有点刁钻了，更新间隔是给自动更新用的，你都手动点击更新全部了，没有理由不更新

**Comment by banshaobao** [comment]
有10个订阅，其中4个【更新间隔】为0。想更新剩下的6个订阅，现在只能一个一个点。确实有点麻烦
