### ISSUE TITLE
订阅编辑规则无法写YAML注释了[BUG] 

### ISSUE THREAD

**Issue by GIT-GAZZ** [clash-verge-rev/clash-verge-rev#1308]
### 问题描述 / Describe the bug

订阅编辑规则-高级模式（非可视化），在这里无法写YAML注释了，规则比较多时，我需要在每个规则上写注释，方便后面修改配置

### 复现步骤 / To Reproduce

订阅编辑规则-高级模式（非可视化），在这里无法写YAML注释了，规则比较多时，我需要在每个规则上写注释，方便后面修改配置

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

无需日志

**Comment by archzi** [comment]
用脚本不好么？

**Comment by LLorangeve** [comment]
> 用脚本不好么？

配置文件好分多个文件，脚本不太好分

**Comment by RichardLuo0** [comment]
额 我也有一样的问题 给关了什么意思。。。

**Comment by MystiPanda** [comment]
不是bug，与可视化数据同步，没法保留注释

**Comment by xishang0128** [comment]
@RichardLuo0 使用脚本即可使用注释

**Comment by RichardLuo0** [comment]
> @RichardLuo0 使用脚本即可使用注释

脚本的话稍微麻烦一点 而且关键是我原先写好的东西还得改 日积月累很长一个文件呢😥

**Comment by xishang0128** [comment]
@RichardLuo0 原本的yaml转脚本很简单,  https://github.com/clash-verge-rev/clash-verge-rev/issues/1311#issuecomment-2213466442

**Comment by RichardLuo0** [comment]
我的建议是能不能做成类似vscode里的launch.json 左下角 就有个“添加配置”，他好像就是就能正常处理各种情况

> @RichardLuo0 使用脚本即可使用注释

**Comment by Kiritocyz** [comment]
> @RichardLuo0 原本的yaml转脚本很简单, [#1311 (comment)](https://github.com/clash-verge-rev/clash-verge-rev/issues/1311#issuecomment-2213466442)

是的，我分享了一个全局脚本模板，我还以为没人看😭

**Comment by RichardLuo0** [comment]
但是有没有能保留注释的yaml to json转换器啊

> @RichardLuo0 原本的yaml转脚本很简单, [#1311 (comment)](https://github.com/clash-verge-rev/clash-verge-rev/issues/1311#issuecomment-2213466442)
