### ISSUE TITLE
[BUG] 1.7.2缩放窗口大小卡顿后闪退

### ISSUE THREAD

**Issue by ZhhHugoChang** [clash-verge-rev/clash-verge-rev#1309]
### 问题描述 / Describe the bug

1.7.2缩放窗口大小卡顿后闪退

### 复现步骤 / To Reproduce

1.7.2缩放窗口大小卡顿后闪退，100%复现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win10

### 日志 / Log

无

**Comment by wonfen** [comment]
无法复现，发日志和视频

**Comment by sgtalh4381** [comment]
Windows 11 does not have this issue.

**Comment by wbbo** [comment]
复现步骤
1. 订阅步骤
2. 可能需要多个订阅(我是5个)
3. 拖住右下角 一顿操作就会卡住

https://github.com/clash-verge-rev/clash-verge-rev/assets/32349896/ca4219d2-bcfe-405f-89ab-ce314969e8e5

@wonfen

**Comment by wbbo** [comment]
> 复现步骤
> 
> 1. 进入订阅
> 2. 可能需要多个订阅(我是5个)
> 3. 拖住右下角 一顿操作就会卡住
> 
>  video_2024-07-03_17-10-21.mp4 
> @wonfen

Windows11 64

**Comment by wbbo** [comment]
> > > 复现步骤
> > > 
> > > 1. 进入订阅
> > > 2. 可能需要多个订阅(我是5个)
> > > 3. 拖住右下角 一顿操作就会卡住
> > > 
> > > video_2024-07-03_17-10-21.mp4
> > > @wonfen
> > 
> > 
> > Windows11 64
> 
> 同Win11，版本23H2 22631.3668，使用带EdgeWebView2的版本，如此操作了一分多钟也无法复现

我试过设置界面/代理/规则/测试 不会卡, 但是在订阅界面很容易就卡住然后闪退

**Comment by ZhhHugoChang** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/assets/30371886/63ba9cd1-278d-46ca-8ae5-2a1e55247564

@wonfen

**Comment by wdy3334** [comment]
windows 11   21h2
1.7.3
无论哪个订阅界面还是其他界面，缩放窗口时都很稳定的闪退

**Comment by MystiPanda** [comment]
试试 alpha 版本

**Comment by wdy3334** [comment]
@MystiPanda 感谢指导，我试试
