### ISSUE TITLE
[BUG] Mac OS 无法打开面板

### ISSUE THREAD

**Issue by abzdocker** [clash-verge-rev/clash-verge-rev#1315]
### 问题描述 / Describe the bug

MacOS M2 芯片 1.7.2版本，无法打开面板，点击app图标没反应，状态栏也没有图标。

### 复现步骤 / To Reproduce

开起TUN 服务模式，使用一段时间后就会出现。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5

### 日志 / Log

无法提供日志。

**Comment by zxq1002** [comment]
我也遇到了，怎么解决知道吗

**Comment by huber1234** [comment]
> 我也遇到了，怎么解决知道吗

开发者的意思是不会修复这个，状态栏图标有些时候是被刘海遮住了，建议用网页版的dashboard控制。

**Comment by zxq1002** [comment]
> > 我也遇到了，怎么解决知道吗
> 
> 开发者的意思是不会修复这个，状态栏图标有些时候是被刘海遮住了，建议用网页版的dashboard控制。

我的距离刘海有很大的空间，不像是被遮挡的

**Comment by wonfen** [comment]
什么软件版本？
