### ISSUE TITLE
【所有订阅共用一个规则如何实现】订阅的右键菜单-编辑规则中prepend写了该规则在对应订阅中生效的。写到全局扩展配置中，不生效

### ISSUE THREAD

**Issue by studentluo** [clash-verge-rev/clash-verge-rev#1316]
### 问题描述 / Describe the bug

V1.7.2所有订阅共用一个规则如何实现，旧版本写到merge中prepend-rules中即可
prepend:
  ###  EPIC规则
  - PROCESS-NAME, EpicWebHelper.exe,DIRECT
  - PROCESS-NAME,EpicGamesLauncher.exe,DIRECT

### 复现步骤 / To Reproduce

所有订阅共用一个规则如何实现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11

### 日志 / Log

prepend:

  ###  EPIC规则
  - PROCESS-NAME, EpicWebHelper.exe,DIRECT
  - PROCESS-NAME,EpicGamesLauncher.exe,DIRECT

**Comment by PctAIGM** [comment]
应该只能用全局脚本来改写

**Comment by zhangzc2012s** [comment]
请问你解决了吗，我的也不生效

**Comment by PctAIGM** [comment]
```

function main(config) {
  let rules = [
    "PROCESS-NAME,EpicWebHelper.exe,DIRECT",
    "PROCESS-NAME,EpicGamesLauncher.exe,DIRECT",
    ...config.rules
  ]
  config.rules = rules 
  return config;
}

```

把这个放到扩展脚本里即可

**Comment by wildwind2000** [comment]
全局扩展配置应该是做这件事的，只是不知道怎么配置。

**Comment by studentluo** [comment]
实测可行 有用
________________________________

**Comment by actforjason** [comment]
> ```
> 
> function main(config) {
>   let rules = [
>     "PROCESS-NAME,EpicWebHelper.exe,DIRECT",
>     "PROCESS-NAME,EpicGamesLauncher.exe,DIRECT",
>     ...config.rules
>   ]
>   config.rules = rules 
>   return config;
> }
> ```
> 
> 把这个放到扩展脚本里即可

但是好像会变卡

**Comment by Momumu** [comment]
规则加订阅的方式目前能实现吗？

**Comment by dhay3** [comment]
> ```
> 
> function main(config) {
>   let rules = [
>     "PROCESS-NAME,EpicWebHelper.exe,DIRECT",
>     "PROCESS-NAME,EpicGamesLauncher.exe,DIRECT",
>     ...config.rules
>   ]
>   config.rules = rules 
>   return config;
> }
> ```
> 
> 把这个放到扩展脚本里即可

这个会把订阅地址里的规则给覆盖掉。。

**Comment by Victor9578** [comment]
> > ```
> > 
> > function main(config) {
> >   let rules = [
> >     "PROCESS-NAME,EpicWebHelper.exe,DIRECT",
> >     "PROCESS-NAME,EpicGamesLauncher.exe,DIRECT",
> >     ...config.rules
> >   ]
> >   config.rules = rules 
> >   return config;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 把这个放到扩展脚本里即可
> 
> 这个会把订阅地址里的规则给覆盖掉。。

不要删除 ...config.relus

**Comment by eryajf** [comment]
> 但是全局扩展脚本访问外网时好像会变卡

+1 对比实测下来，确实在这里加规则，每次加载页面都要延迟一两秒。但是目前使用最新1.7.7版本的，貌似只有这一个方案。如果直接加到订阅规则里，订阅更新之后，自定义配置会被覆盖。

**Comment by zhangguanzhang** [comment]
![image](https://github.com/user-attachments/assets/cf43f0a7-ba62-4db9-b1b9-c76a4282e7db)

**Comment by Tychristine** [comment]
@zhangguanzhang https://blog.tyasaka.xyz
