### ISSUE TITLE
[BUG] 1.7.2版本TUN模式TUN Stack不能用mix和system

### ISSUE THREAD

**Issue by Shengyis** [clash-verge-rev/clash-verge-rev#1318]
### 问题描述 / Describe the bug

安装service后打开service mode, 再打开tun mode, 默认tun stack: gvisor工作正常, 切换称mixed或system, 保存就不能上网了. 

### 复现步骤 / To Reproduce

tun stack 切换成 mixed 或 system, 保存

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

切换到mix后
07-03 23:22:30INFO
Start initial configuration in progress
07-03 23:22:30INFO
Geodata Loader mode: memconservative
07-03 23:22:30INFO
Geosite Matcher implementation: succinct
07-03 23:22:30INFO
Initial configuration complete, total time: 35ms
07-03 23:22:30INFO
Sniffer is closed
07-03 23:22:30WARNING
[TUN] default interface changed by monitor, => Wi-Fi
07-03 23:22:31INFO
[TUN] Tun adapter listening at: Mihomo([198.18.0.1/30],[fdfe:dcba:9876::1/126]), mtu: 1500, auto route: true, auto redir: false, ip stack: Mixed

**Comment by moshangssh** [comment]
防火墙是不是开着的?试着关掉

如果关掉防火墙ok的话,出站放行一下内核就行了

**Comment by Shengyis** [comment]
非常感谢, 确实, TUN网卡是public, 默认防火墙拦截了

**Comment by LightMu** [comment]
感谢，防火墙高级设置里sing-tun规则，高级里的配置文件勾上公用就解决了
