### ISSUE TITLE
[BUG]MACOS下，日志silent不生效

### ISSUE THREAD

**Issue by zhanpeng1996** [clash-verge-rev/clash-verge-rev#132]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/38784558/75b55980-2102-4f7a-b5b6-993a84875aeb)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/38784558/74ab0ce9-a5c3-48ac-b2ff-eebfe92aec3a)
ru'tu如图

### To Reproduce

如题

### Platform

MacOS

### System Version

13.6.1 (22G313)

### Software Version

1.4.4

**Comment by wonfen** [comment]
设置后重启软件了吗？

**Comment by zhanpeng1996** [comment]
> 设置后重启软件了吗？

重启过了

**Comment by starlifezzz** [comment]
+1。这个问题好几个版本都是。并且把杂项设置里面的也关了，依然无效
![截屏2023-12-14 18 34 59](https://github.com/clash-verge-rev/clash-verge-rev/assets/32615040/ca7b1340-b523-4e94-a827-87837ca8bf29)
![截屏2023-12-14 18 35 30](https://github.com/clash-verge-rev/clash-verge-rev/assets/32615040/2d49c13d-e137-4d86-8ef1-094562d09ccf)
![截屏2023-12-14 18 36 30](https://github.com/clash-verge-rev/clash-verge-rev/assets/32615040/9d25be03-0589-4f7a-8b61-62e0e89ebc90)
