### ISSUE TITLE
[Feature] 引入 Winget Releaser 以支持 Winget 自动更新

### ISSUE THREAD

**Issue by Dragon1573** [clash-verge-rev/clash-verge-rev#1322]
### 功能描述 / Feature description

在 _GitHub Workflows_ 中引入 [Winget Releaser](https://github.com/marketplace/actions/winget-releaser) ，在新版本 Tag 发布时，与自动化编译构建同步触发提交新版本元信息到 `winget` 软件源。

- 关联 #1162
- 关联 #718
- 关联 #607

### 使用场景 / Use case

1. 引入此 _GitHub Action_ 能够让此应用程序包在发布后第一时间同步提交至 `winget` 仓库进行元信息审核；
2. 由 **Publisher** 亲自维护的 package manifests 会获得优先特权，更容易被 Merge ；
3. 全自动化流水线发布新版本元信息，极大程度避免元信息过期和版本收录滞后。

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> 此行为可能需要修改 `.github/workflows/` 下配置文件，请保留此 Issue ，我愿意为此 Issue 开发相关 PR 🙏🏼

**Comment by KaranocaVe** [comment]
good job
