### ISSUE TITLE
新版本会造成surge 无法代理

### ISSUE THREAD

**Issue by lxtx528** [clash-verge-rev/clash-verge-rev#1324]
### 问题描述 / Describe the bug

1.6.2以后的版本开启后会造成surge的代理开关失效，必须在网络设置里手动关闭代理三项（HTTP,HTTPS和socks代理），然后重新打开surge开能正常使用，望能够得到解决。

### 复现步骤 / To Reproduce

不管是先打开的surge还是clash verge都会造成这种情况，感觉不兼容了，1.6.2之前并没有这种情况。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

10.15.7

### 日志 / Log

无

**Comment by lxtx528** [comment]
在此反复尝试了，先开始clash verge 不会有事，先开启surge（开启了代理）在开启clash verge(clash不打开代理开关的情况下）surge也无法关闭代理。需要重复最上面的步骤必须在网络设置里手动关闭代理三项（HTTP,HTTPS和socks代理），然后重新打开surge开能正常使用，望能够得到解决。

**Comment by Yamooya** [comment]
我也遇到了打开Verge程序（没开启代理）后，其他代理软件失效，希望改进。
