### ISSUE TITLE
[BUG] 1.7.2之前在Merge文件中编写的prepend-rules规则在1.7.2版本无效

### ISSUE THREAD

**Issue by witt-bit** [clash-verge-rev/clash-verge-rev#1325]
### 问题描述 / Describe the bug

在1.7.2之前使用Merge类型的配置，编写了prepend-rules规则

升级1.7.2后由于Merge类型的配置被删除，将内容复制到了订阅右键菜单的拓展配置中，无效

通过js改为右键菜单中的拓展脚本配置后生效

### 复现步骤 / To Reproduce

右键菜单编写prepend-rules规则拓展配置无效

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

无

**Comment by witt-bit** [comment]
参考https://github.com/clash-verge-rev/clash-verge-rev/issues/1316，改为拓展脚本后生效

**Comment by xishang0128** [comment]
https://clash-verge-rev.github.io/guide/extend.html

**Comment by guo0001jian** [comment]
> 参考[ISSUE改为拓展脚本后生效](https://github.com/clash-verge-rev/clash-verge-rev/issues/1316)

此办法有效，看来自定义规则的功能只能在脚本中实现了。
