### ISSUE TITLE
[BUG] 服务模式不能正确启动

### ISSUE THREAD

**Issue by eachann1024** [clash-verge-rev/clash-verge-rev#1328]
### 问题描述 / Describe the bug

我只是想安装个 arc 浏览器, 在登录的时候 , 使用 tun 好像还是没有成功代理到

### 复现步骤 / To Reproduce

![Image_2024-07-04_14-18-40](https://github.com/clash-verge-rev/clash-verge-rev/assets/43348055/6bde0b1f-226e-43c1-bbbf-f3f462cfcb3b)

1. 通过手动管理员安装
2. 服务出现了 clash相关的服务, 但是并不能启动
3. 卸载了服务,卸载了 clash 软件 重装都是不行

![Image_2024-07-04_17-09-34](https://github.com/clash-verge-rev/clash-verge-rev/assets/43348055/2e3c182d-3174-4c8d-9111-c7591b27c511)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12490F
    Memory: 10.55 GB / 31.81 GB
  Binaries:
    Node: 18.20.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.3.0 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.81)
    Internet Explorer: 11.0.22621.3527

**Comment by jiangying000** [comment]
我升级1.7.5以后也有同样的问题
无法启动服务模式,按那个按钮动画转一圈,但没有任何效果
