### ISSUE TITLE
[Feature] 如何在树莓派4B安装

### ISSUE THREAD

**Issue by Pluviophile225** [clash-verge-rev/clash-verge-rev#133]
### Is your feature request related to a problem? Please describe.

下载了arm64版本，显示depency is not satisfiable：openssl 但是已经安装了openssl

### Describe the solution you'd like

希望可以给一个树莓派版本的支持。

### Describe alternatives you've considered

希望可以给一个树莓派版本的支持。

**Comment by wonfen** [comment]
用最新版试试，已经吧rusttls替换为了openssl

**Comment by wonfen** [comment]
无进一步反馈，关闭了。
