### ISSUE TITLE
[BUG] 解压便携版本出错

### ISSUE THREAD

**Issue by onnoozzo** [clash-verge-rev/clash-verge-rev#1330]
### 问题描述 / Describe the bug

下载解压Clash.Verge_1.7.2_x64_fixed_webview2_portable.zip 会出现图片中的问题
解压软件7zip 24.07
用win10自带的zip解压可以。确定不是压缩包损坏
![PixPin_2024-07-04_21-50-37](https://github.com/clash-verge-rev/clash-verge-rev/assets/134776969/fa289e76-8ec4-4425-91a0-946a32fdfd43)

### 复现步骤 / To Reproduce

直接解压就是这样

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

WIN10 LTSC 2021

### 日志 / Log

如图
![Uploading PixPin_2024-07-04_21-50-37.png…]()

**Comment by MystiPanda** [comment]
既然不是压缩包的问题为什么不给7zip提issue

**Comment by onnoozzo** [comment]
你说得对。我蛮发下，可以看下是什么名字还是文件触发了这个问题
