### ISSUE TITLE
[Feature] 1.7.2 的扩展配置和扩展脚本执行顺序可以拖动来自定义执行顺序吗

### ISSUE THREAD

**Issue by watchingfun** [clash-verge-rev/clash-verge-rev#1332]
### 功能描述 / Feature description

扩展配置和扩展脚本执行顺序可以拖动来自定义执行顺序吗？  其实我想要的就是扩展配置里能使用 扩展脚本里定义的代理组名称，还有rules不被脚本覆盖掉

### 使用场景 / Use case

在之前我是这么用script和merge的，先用script 把任意机场定义的代理节点按我的规则进行重新分组，覆盖机场的规则，然后在merge写我自定义的规则，因为yaml可读性比 js 好，而且我merge里只写rules，比js里写方便定位；

目前1.7.2 是全局扩展配置先于全局扩展脚本执行，导致我扩展用不了脚本里定义的代理组名称，而且定义的规则会被脚本覆盖掉

**Comment by wonfen** [comment]
已改为全局扩展
