### ISSUE TITLE
[BUG] 新版本设置代理绕过提示格式错误

### ISSUE THREAD

**Issue by pnoker** [clash-verge-rev/clash-verge-rev#1335]
### 问题描述 / Describe the bug

新版下设置代理绕过提示格式错误，例如这样就提示无效格式
```
127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,*.crashlytics.com,<local>,*.huawei.com,*.huawei.net
```
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/7984783/2afccd32-c1de-4bad-8656-93b8bdd5e741)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/7984783/eecae03c-87b1-4b86-90d8-1d6094fe1781)

### 复现步骤 / To Reproduce

1. 打开面板
2. 设置
3. 系统代理
4. 代理绕过设置

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/7984783/de571024-cd0c-4059-908d-71feec3a78d8)

5. 点击 ‘保存’

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/7984783/0ca2b098-6b0d-4597-90eb-d1d28e008e71)

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Mac OS 14.5

### 日志 / Log

无

**Comment by KendrickKan** [comment]
同样遇到这个问题

**Comment by AdySnowflake** [comment]
格式错误，应使用分号。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/163967164/020b50d6-5fee-4ab0-afd7-99b2836205b4)

**Comment by MystiPanda** [comment]
不是哥们，人家是 Mac，问题确实存在，不要乱回复好吗，给你回复隐藏了咋还追着评论呢

**Comment by AdySnowflake** [comment]
这个问题我在Windows下面也能复现，我只是基于我的角度给出了一个可以在Windows版本下规避错误的可能，等待他人在Mac环境下测试。同时我认为这不是bug，只是目前CIDR不受支持。

**Comment by MystiPanda** [comment]
Windows 系统确实不支持 cidr，Mac 是支持的，他的问题在于.local 域名

**Comment by AdySnowflake** [comment]
抱歉，是我的问题，我会删除之前的comment。想问一下，mac也可以直接使用","进行隔断吗？Windows下只能使用“;” ,否则报错。

**Comment by pnoker** [comment]
牛，升级1.7.3解决了，感谢

**Comment by YeungHoiChiu** [comment]
1.7.5又出现了？
![image](https://github.com/user-attachments/assets/5cbc231d-d284-457d-b376-631f9437f958)
![image](https://github.com/user-attachments/assets/db32cda6-6c9b-4091-9144-8a667cf28dac)
