### ISSUE TITLE
[Feature] 希望能提供禁用脚本的选项，提升性能

### ISSUE THREAD

**Issue by wocanbe** [clash-verge-rev/clash-verge-rev#1339]
### 功能描述 / Feature description

能通过配置实现功能的情况下，全局脚本默认开启，会影响性能，希望能提供关闭脚本的配置项。

### 使用场景 / Use case

window,MACOS

**Comment by wocanbe** [comment]
我提供不了数据，只有描述。更新新版本后，游戏本风扇经常转，看CPU占用维持在7%以上(CPU13900KF)，有时候还会假死，点击没反应，无法上谷歌。我是一名前端开发者，猜测是这个脚本影响的。已经降到1.6.6，cpu占用在3%以下。

**Comment by PctAIGM** [comment]
应该跟脚本没关系，脚本是生成最终yaml的时候才生效，生成后就没用了。
可能是其他问题导致。

**Comment by wocanbe** [comment]
嗯
