### ISSUE TITLE
[Feature] 可以给个自定义加密dns请求远程代理查询的功能吗

### ISSUE THREAD

**Issue by ghost** [clash-verge-rev/clash-verge-rev#134]
### Is your feature request related to a problem? Please describe.

就是nameserver那一项的配置，我知道会导致延迟高。可以给个自定义选项吗，可以打开或者关闭远程dns查询

### Describe the solution you'd like

给个自定义选项吗，可以打开或者关闭远程dns查询

### Describe alternatives you've considered

无

**Comment by wonfen** [comment]
这个在clash配置文件中定义就可以了啊
