### ISSUE TITLE
[BUG] 升级1.7.2后，重新订阅，但是代理组为空

### ISSUE THREAD

**Issue by chenbihao** [clash-verge-rev/clash-verge-rev#1340]
### 问题描述 / Describe the bug

升级1.7.2后，重新订阅，但是代理组为空

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/21167262/23b2b9fe-8bf6-4341-b7ed-80f29d2a83a2)

编辑订阅那里是能看到组的
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/21167262/8b164fa3-5732-481f-9d00-647f0036c885)

### 复现步骤 / To Reproduce

会不会是跟我配置全局配置有关系？

我最开始是把之前的prepend-rules: 放到全局配置这里，然后发现不生效我就给删了

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/21167262/c3759883-2432-4f37-907a-2c00cdba4586)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

暂无，可以配合

**Comment by MystiPanda** [comment]
> 怎么这几版bug这么多啊。。。发版太着急了吧都没检查？

没屁放了就滚蛋，你指望我给你做几轮测试，爱用用不爱用死远点

**Comment by MystiPanda** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/21167262/23b2b9fe-8bf6-4341-b7ed-80f29d2a83a2) 

看你的图片你订阅没有启用吧，订阅页面点击订阅启用一下

**Comment by ruiy326** [comment]
> > 怎么这几版bug这么多啊。。。发版太着急了吧都没检查？
> 
> 没屁放了就滚蛋，你指望我给你做几轮测试，爱用用不爱用死远点

我倒觉得这次大更新挺好，之前不会给特定订阅加规则，切换订阅还得关merge，现在倒是蛮轻松的，我不开TUN模式，很少开系统代理，都在Firefox和steam里设置代理服务器。折腾的少，所以没遇到bug。clash-verge-rev是目前我最喜欢的持续更新的clash客户端，感谢开发者。

**Comment by Tychristine** [comment]
@ruiy326 熊猫佬的攻击力还有提升空间

**Comment by NormanMises** [comment]
> > 怎么这几版bug这么多啊。。。发版太着急了吧都没检查？
> 
> 没屁放了就滚蛋，你指望我给你做几轮测试，爱用用不爱用死远点

不是，哥，我感激你们开发者们，身边人也都在用；
但这一版是软件内也没说要完全卸载再更新，我直接软件内自动更新的，更完 切换订阅 代理组就空了，这你自己开发完了不看一眼代理组有没有吗。。。😂基础功能都寄了啊，
完全卸载了重装才正常，卸载之前还得手动备份订阅链接，很折腾啊。。。🥲

**Comment by xihuai18** [comment]
> > > 怎么这几版bug这么多啊。。。发版太着急了吧都没检查？
> > 
> > 
> > 没屁放了就滚蛋，你指望我给你做几轮测试，爱用用不爱用死远点
> 
> 不是，哥，我感激你们开发者们，身边人也都在用； 但这一版是软件内也没说要完全卸载再更新，我直接软件内自动更新的，更完 切换订阅 代理组就空了，这你自己开发完了不看一眼代理组有没有吗。。。😂基础功能都寄了啊， 完全卸载了重装才正常，卸载之前还得手动备份订阅链接，很折腾啊。。。🥲

免费的能用就行 😂

**Comment by chenbihao** [comment]
重新安装解决
