### ISSUE TITLE
[BUG] macOS上的菜单栏图标看起来有些过大了

### ISSUE THREAD

**Issue by keelewang** [clash-verge-rev/clash-verge-rev#1341]
### 问题描述 / Describe the bug

clash verge的菜单栏图标与其他的比起来似乎有些偏大
<img width="433" alt="SCR-20240706-izav" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/78184805/d2f4198c-6aaa-4962-9821-bfcce32fab0c">

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5

### 日志 / Log

无

**Comment by cethink** [comment]
嗯，我也觉得大了点
