### ISSUE TITLE
[BUG] 开启 局域网连接 无效

### ISSUE THREAD

**Issue by JokerBoom** [clash-verge-rev/clash-verge-rev#1342]
### 问题描述 / Describe the bug

局域网无法共享代理；查看电脑网络端口服务，发现没有绑定IP地址。多网卡，多ip环境。

### 复现步骤 / To Reproduce

多网卡，多ip环境。上一版本正常，软件重装过也无效。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11 

### 日志 / Log

无

**Comment by Wilson2003** [comment]
+1，手机设置通过电脑代理不能翻墙，v1.7.3不行，以前版本都可以。

**Comment by AnyWAT** [comment]
V1.7.3 便携版 Win10x64PRO下的手机正常哦

**Comment by wonfen** [comment]
和软件无关，检查你们的本地网络联通情况。
