### ISSUE TITLE
[BUG] Tun模式下向日葵远程不了了

### ISSUE THREAD

**Issue by nssiwi** [clash-verge-rev/clash-verge-rev#1344]
### 问题描述 / Describe the bug

开启Tun模式后，向日葵远程电脑后无法登入远程电脑，日志如下：
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/20717483/ad01ea57-d457-4688-8787-c9c16375f756)

### 复现步骤 / To Reproduce

开启Tun模式，远程向日葵

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 23H2 22631.3737

### 日志 / Log

`07-06 18:54:01INFO
[TCP] 198.18.0.1:56649 --> api-std.sunlogin.oray.com:443 match RuleSet(direct) using DIRECT
07-06 18:54:03WARNING
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:56655 --> 1336740647-409653000lsab6ac479.rc03.oray.com:443 error: no ip address
07-06 18:54:03WARNING
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:56655 --> 1336740647-409653000lsab6ac479.rc03.oray.com:443 error: dns resolve failed: couldn't find ip`

**Comment by nssiwi** [comment]
不好意思，排查发现是我脚本的问题

**Comment by kdqiu** [comment]
> 不好意思，排查发现是我脚本的问题

请问您是配置上的哪个部分？我也遇到了类似问题
