### ISSUE TITLE
[BUG] 每次开机后无网络

### ISSUE THREAD

**Issue by ZYong9908** [clash-verge-rev/clash-verge-rev#1345]
### 问题描述 / Describe the bug

目前： 
- tun模式：关
- 服务模式：关
- 系统代理：开
- 开机自启：开
- 静默启动：开

表现：每次开机后表现为无网络，程序ui显示异常，具体可看下图，log为空，cmd(未添加环境变量)ping测试网络正常，浏览器访问内外网都不通。重启clash-verge-rev后一切恢复正常

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/44081531/dc8c9352-9ebf-42d0-a41e-bc2c5720fc2d)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/44081531/75289ac4-5a81-46a7-9f39-ff645b9068db)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/44081531/2c84fa41-6245-40a4-85c8-4d9e79a71188)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/44081531/62fa97dc-0bd1-4ade-ba62-0c2eeef629a1)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/44081531/eb5946e4-cef3-4d5e-9e27-05d93940460e)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/44081531/c3cf7185-84c9-4ad4-be18-0eea6c0b60e8)

### 复现步骤 / To Reproduce

本机100%复现，其他复现方式未知

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

相关log为空

**Comment by ZYong9908** [comment]
补充：
重装应用无效;
发现日志：
```
2024-07-08 20:38:51 ERROR - 系统找不到指定的文件。 (os error 2)
2024-07-08 20:38:51 ERROR - error sending request for url (http://127.0.0.1:33211/unset_dns)

```
在更多中单独重启clash或重启应用无效，只有右键退出再手动打开可以正常

**Comment by freddymuch** [comment]
具有完全一致的情况，并且从版本v1.7.3后出现该情况

**Comment by ZYong9908** [comment]
已测试，非偶发，另有pc升级1.7.3后出现相同情况

**Comment by xclidongbo** [comment]
嗯。一毛一样。报错也一样。

**Comment by xclidongbo** [comment]
重装1.7.3就好了。但重启后，错误依旧。

**Comment by x1207349263** [comment]
一样的问题，从之前的版本就遇到了，也是每次开机出问题，重启应用可以解决

**Comment by freddymuch** [comment]
注意到重启后右下角托盘图标显示为老图标，并且完全重新安装1.7.3后，不再复现。推测是升级过程中新旧文件更替问题

**Comment by x1207349263** [comment]
> 注意到重启后右下角托盘图标显示为老图标，并且完全重新安装1.7.3后，不再复现。推测是升级过程中新旧文件更替问题

确实，前天重装后，到现在已经没有复现过来，谢谢你！

**Comment by lyf571321556** [comment]
error sending request for url (http://127.0.0.1:33211/unset_dns)

**Comment by namerzhang** [comment]
error sending request for url (http://127.0.0.1:33211/unset_dns)
也是这个问题，无法启动，1.7.5版

**Comment by namerzhang** [comment]
2024-08-13 11:36:53 ERROR - error sending request for url (http://127.0.0.1:33211/unset_dns)
无法启动无法使用，1.7.5版。一开始只是界面不能显示，现在完全没法用了

**Comment by BugBubbles** [comment]
1.7.7版本，也是相同的问题，反复重启都不行，甚至退出都卡死，必须用任务管理器强制退出。过一会把cache.db删了后再重启才行的。
