### ISSUE TITLE
[BUG] 从1.7.2版更新至1.7.3版后，代理延迟测试正常，但连接不成功（上/下行速率均为0）/ After updating from 1.7.2 to 1.7.3, the proxy latency test is normal, but the connection is unsuccessful (both up/down rates are 0)

### ISSUE THREAD

**Issue by mtuwei** [clash-verge-rev/clash-verge-rev#1348]
### 问题描述 / Describe the bug

1. 从1.7.2版更新至1.7.3版后，代理延迟测试正常，但连接不成功（上/下行速率均为0）/ After updating from 1.7.2 to 1.7.3, the proxy latency test is normal, but the connection is unsuccessful (both up/down rates are 0)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/32591958/695f84ec-96e5-4536-ab8a-a617cfd42c3c)
2. 之前从1.6.+ 更新至1.7.2版，未重新导入配置文件，但仍能正常使用 / Previously updated from version 1.6.+ to 1.7.2 without reimporting the configuration file, but still works fine.
3. 尝试过卸载1.7.3版（包括配置数据），然后重新安装1.7.3/1.7.2两个版本，但上述第1点中的问题依然存在。/ Tried uninstalling version 1.7.3 (including configuration data) and then reinstalling both versions 1.7.3/1.7.2, but the problem in point 1 above persists.
4. 另外，改用CFW_V0.20.39，同样的配置文件，代理延迟和连接均正常。Also, Using the CFW_V0.20.39 with the same URL, proxy latency and connection are normal.

### 复现步骤 / To Reproduce

/

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 Insider Preview 10.0.26120.461

### 日志 / Log

[2024-07-07-0953.log](https://github.com/user-attachments/files/16117909/2024-07-07-0953.log)

**Comment by zhonghb** [comment]
有没有开启系统代理成功

**Comment by mtuwei** [comment]
> 有没有开启系统代理成功

谢谢您的回复。我这边的情况是这样：通过配置浏览器插件SwitchyOmega实现KXSW。因此，默认并未开启系统代理。

在您的提示下，我能够成功开启系统代理（如下图），但并未解决上面的问题。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/32591958/266114f6-685e-4629-ac86-e6e9df587466)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/32591958/d89ebdc8-2e0a-4cd6-926f-5cb539dd8b71)

还麻烦您进一步给予帮助，谢谢！

**Comment by AnyWAT** [comment]
> 成功开启系统代理
> 浏览器插件SwitchyOmega

点击 SwitchyOmega 图标，启用“系统代理”或禁用插件均可。

> 1. 代理延迟测试正常，但连接不成功

不会仅仅是插件的代理协议、代理端口设置问题？

**Comment by mewinners** [comment]
有类似问题 但是跟楼主不一样的是 我的并不是完全不能访问 而是时不时会抽风一段时间 然后会自动恢复

**Comment by mtuwei** [comment]
> > 成功开启系统代理
> > 浏览器插件SwitchyOmega
> 
> 点击 SwitchyOmega 图标，启用“系统代理”或禁用插件均可。
> 
> > 1. 代理延迟测试正常，但连接不成功
> 
> 不会仅仅是插件的代理协议、代理端口设置问题？

谢谢回复。按您的提示，将SwitchyOmega选项设置为“系统代理”后，确实能够“成功连接”了。

另，下面两个截图分别是我这边ClashVerge和SwitchyOmega中【代理协议端口】设置的截图。能否再请问您这个设置存在的问题是？以及如何解决？谢谢！

![image](https://github.com/user-attachments/assets/f16d50c4-1cd8-4319-adf1-b8b4b7705146)
![image](https://github.com/user-attachments/assets/a47a4c06-4dea-4ec3-8766-f88c301a7466)

**Comment by AnyWAT** [comment]
![image](https://github.com/user-attachments/assets/9f5897b7-d8d4-4fe5-8851-d9bca051ce92)

8584
8585
后面的开关打开，才能使用。

**Comment by mtuwei** [comment]
> ![image](https://private-user-images.githubusercontent.com/37962734/348069360-9f5897b7-d8d4-4fe5-8851-d9bca051ce92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTEwNzIsIm5iZiI6MTcyMDc1MDc3MiwicGF0aCI6Ii8zNzk2MjczNC8zNDgwNjkzNjAtOWY1ODk3YjctZDhkNC00ZmU1LTg4NTEtZDliY2EwNTFjZTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDAyMTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3Zjk2MTUyMmE3NzE3NDIwNDVhYmY3YzliMzVlMjBjMWE2M2I3NWVhZjNhNmJlYjZmNmJmYjZiMjI1N2Y1MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ouFVwUrFwjXHugxe2F71T7ejTEIAjwLVCap00to46A)
> 
> 8584 8585 后面的开关打开，才能使用。

谢谢提示，不好意思😂
