### ISSUE TITLE
[BUG] V1.7.3 和 V1.7.2 仍然被 kaspersky（卡巴斯基）报毒，并且强制删除

### ISSUE THREAD

**Issue by Edge-coordinates** [clash-verge-rev/clash-verge-rev#1349]
### 问题描述 / Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/68896486/150f3e20-156a-4d8a-bd65-b072c6fb3ced)

下载/安装程序被卡巴斯基识别为病毒（木马），报毒并强制删除，主要是新版本仍然存在问题，故提出Issue，而且，有的时候，卡巴斯基还会删除 已安装的程序中的一些文件（我没有多次测试，所以不确定）

谢谢

### 复现步骤 / To Reproduce

使用程序的自动更新安装新版本，在卡巴斯基激活的时候下载/安装程序

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows10专业版 22H2 2023/7/23 19045.4598 Windows Feature Experience Pack 1000.19060.1000.0

### 日志 / Log

无

**Comment by lbcake** [comment]
卸载卡巴斯基

**Comment by Edge-coordinates** [comment]
> 卸载卡巴斯基

这确实是吾目前采用的解决方案，不过吾辈仍然想知道本问题能否得到更好的解决，比如彻底终结（包括后续版本）卡巴斯基的报错

当然，我也好奇这个报毒是怎样导致的，如果能够写在文档中是最好的，谢谢佬们了

**Comment by vibbow** [comment]
报毒行为是从 v1.6.6 及更高版本 才出现的，之前版本是正常的。

以及只是报了安装包的行为，如果下载绿色版运行是没问题的。

**Comment by Edge-coordinates** [comment]
> 报毒行为是从 v1.6.6 及更高版本 才出现的，之前版本是正常的。
> 
> 以及只是报了安装包的行为，如果下载绿色版运行是没问题的。

好的，谢谢。

**Comment by Starfallan** [comment]
r误报的问题应该已经解决了啊，更新一下最新的病毒数据库试下

**Comment by igoby** [comment]
> r误报的问题应该已经解决了啊，更新一下最新的病毒数据库试下

并没有，今天我试了试，应用内更新还是报毒

**Comment by Starfallan** [comment]
> > r误报的问题应该已经解决了啊，更新一下最新的病毒数据库试下
> 
> 并没有，今天我试了试，应用内更新还是报毒

我在回你的时候刚装1.7.3一切正常
![PixPin_2024-07-04_11-08-24](https://github.com/clash-verge-rev/clash-verge-rev/assets/36763490/ebef7750-2378-4e11-a010-2afb3876ce6b)
