### ISSUE TITLE
[Feature]URLTest can select manually

### ISSUE THREAD

**Issue by forsignup** [clash-verge-rev/clash-verge-rev#135]
### Is your feature request related to a problem? Please describe.

None

### Describe the solution you'd like

group type of url-test  can select manually, [ref](https://github.com/MetaCubeX/clash-verge/commit/d1cf61c49f7d80bb747c53dae20bc51ce6ca39aa)

### Describe alternatives you've considered

None

**Comment by wonfen** [comment]
非预期功能，url test的正常逻辑应该就是自动选择延迟最低那个。如果手动选择了，那还test干嘛？

**Comment by forsignup** [comment]
> 非预期功能，url test的正常逻辑应该就是自动选择延迟最低那个。如果手动选择了，那还test干嘛？

有时候url-test的结果不符合预期（比如延迟测试结果波动较大），想要人工干预。

**Comment by wonfen** [comment]
人工干预就在其他分组下选节点就行了啊。
如果这里改为可以手动选节点，下次测试以后还是这个手动的选择，那测试的意义何在？
