### ISSUE TITLE
[BUG] 请教一下Win11 反复报病毒怎么处理

### ISSUE THREAD

**Issue by xihuai18** [clash-verge-rev/clash-verge-rev#1350]
### 问题描述 / Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/23721828/b33420ac-a050-4301-b5db-bb2ee2da78f1)

### 复现步骤 / To Reproduce

更新到1.72及以后版本发现的，运行这个威胁之后过两天又会再报一次，请问这个问题有什么办法

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

2024-07-07 15:32:44 ERROR - 无法成功完成操作，因为文件包含病毒或潜在的垃圾软件。 (os error 225)

**Comment by MystiPanda** [comment]
你要不要看看关于报毒的issue提了多少了，烦不烦

**Comment by xihuai18** [comment]
> 你要不要看看关于报毒的issue提了多少了，烦不烦

看过了，我这个跟已有的不太一样才发的，他们是setup.exe报毒，我这个是装完了被杀了😂

**Comment by MystiPanda** [comment]
> 运行这个威胁

什么叫运行这个威胁，不能直接忽略吗

**Comment by xihuai18** [comment]
> > 运行这个威胁
> 
> 什么叫运行这个威胁，不能直接忽略吗

打错字了，*允许*这个威胁，我刚刚更新到了1.7.3等两天看看会不会被杀

**Comment by MystiPanda** [comment]
我的defender没报过，手动扫描了一遍也没报

**Comment by xihuai18** [comment]
更新：1.7.3 defender不会报毒
