### ISSUE TITLE
[BUG] 新版Merge自定义规则失效

### ISSUE THREAD

**Issue by 2575757** [clash-verge-rev/clash-verge-rev#1351]
### 问题描述 / Describe the bug

![PixPin_2024-07-07_17-52-50](https://github.com/clash-verge-rev/clash-verge-rev/assets/39446535/8a9fad88-2ea0-4f65-949e-fbb05ec5f941)

### 复现步骤 / To Reproduce

我不知道是哪里格式不对，更新前是可用的，更新后失效了

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11

### 日志 / Log

![PixPin_2024-07-07_17-52-50](https://github.com/clash-verge-rev/clash-verge-rev/assets/39446535/bd0857d1-52c5-417c-85cc-f91d21b622c6)

**Comment by xishang0128** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.7.2  但凡看一下更小日志

**Comment by 2575757** [comment]
请问这个更新订阅后会不会失效呢

**Comment by 2575757** [comment]
> https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.7.2 但凡看一下更小日志

好吧不会失效，谢谢您的解答
