### ISSUE TITLE
[BUG] Ubuntu 24.0.4 中缺少依赖 libwebkit2gtk-4.0-37

### ISSUE THREAD

**Issue by GuoJiaxing1997** [clash-verge-rev/clash-verge-rev#1352]
### 问题描述 / Describe the bug

Ubuntu 24.0.4 中缺少依赖 libwebkit2gtk-4.0-37
安装时提示缺少此依赖，且无法手动下载到此包

### 复现步骤 / To Reproduce

依赖缺失

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu 24.0.4

### 日志 / Log

无

**Comment by withesse** [comment]
https://clash-verge-rev.github.io/faq/linux.html#ui

**Comment by GuoJiaxing1997** [comment]
> https://clash-verge-rev.github.io/faq/linux.html#ui

thanks!

**Comment by luyuan9870** [comment]
sudo apt install ./libwebkit2gtk-4.0-37_2.43.3-1_amd64.deb 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
您也许需要运行“apt --fix-broken install”来修正上面的错误。
下列软件包有未满足的依赖关系：
 libwebkit2gtk-4.0-37 : 依赖: libjavascriptcoregtk-4.0-18 (= 2.43.3-1) 但无法安装它
E: 有未能满足的依赖关系。请尝试不指明软件包的名字来运行“apt --fix-broken install”(也可以指定一个解决办法)。
