### ISSUE TITLE
[BUG] Tun模式不支持terminal (macOS sonoma)翻墙

### ISSUE THREAD

**Issue by dutry** [clash-verge-rev/clash-verge-rev#1356]
### 问题描述 / Describe the bug

Tun模式下不支持terminal (macOS sonoma)翻墙，我用代码`curl cip.cc`来测试了

### 复现步骤 / To Reproduce

我用代码`curl cip.cc`运行，显示依然是自己的本地IP

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Sonoma 14.5

### 日志 / Log

没有任何日志层面的bug，只是终端不支持Tun翻墙

**Comment by rebecca554owen** [comment]
@dutry 单独设置终端走代理

**Comment by dutry** [comment]
@rebecca554owen 
试了一下，在.zshrc添加：
```
function proxy_on() {
    export http_proxy=http://127.0.0.1:7897
    export https_proxy=$http_proxy
    echo -e "终端代理已开启。"
}

function proxy_off(){
    unset http_proxy https_proxy
    echo -e "终端代理已关闭。"
}
```
source之后开启proxy_on，然后测试了还是不行。

**Comment by cytown** [comment]
嗯，新版本去掉了授权内核的功能，导致没法使用tun模式了

**Comment by dutry** [comment]
@cytown 请问您知道最后一个支持Tun的版本吗？

**Comment by MystiPanda** [comment]
开服务模式就好了，不看更新日志的吗

**Comment by cytown** [comment]
> @cytown 请问您知道最后一个支持Tun的版本吗？

不是问题，要到面板里面卸载服务模式，再安装，就可以了。

**Comment by fastfading** [comment]
服务模式是什么？怎么开？我半天都没找到。
