### ISSUE TITLE
[BUG] Windows x64 客户端 最大化最小化按钮是同一个

### ISSUE THREAD

**Issue by EV1LG0D** [clash-verge-rev/clash-verge-rev#136]
### Describe the bug

最大化最小化之后，按钮是同一个。

### To Reproduce

点击右上角最大化按钮。

### Platform

Windows

### System Version

Windows 11 23H2

### Software Version

1.4.4

**Comment by wonfen** [comment]
没问题啊，就是一个

**Comment by EV1LG0D** [comment]
不是啊，你看看Windows里面任何一个软件，最大化和最小化的图标是不一样的，这个是框架里面写死的东西吗，不好改就算了。

**Comment by EV1LG0D** [comment]
![圖片](https://github.com/clash-verge-rev/clash-verge-rev/assets/18423666/3286244d-b2fd-4966-82b2-af2f94fd9cf3)
![圖片](https://github.com/clash-verge-rev/clash-verge-rev/assets/18423666/2d40d8bb-f0d4-4c5f-ad3f-7ba72bc9b617)

**Comment by EV1LG0D** [comment]
![圖片](https://github.com/clash-verge-rev/clash-verge-rev/assets/18423666/4bd0b6da-5521-47b0-8790-3fb1d13fc460)
![圖片](https://github.com/clash-verge-rev/clash-verge-rev/assets/18423666/f6b35fe8-4b59-49d3-bc7b-d992cca7db8d)

**Comment by MystiPanda** [comment]
修了
