### ISSUE TITLE
希望可以为 Releases 中的其他二进制提供完整性验证

### ISSUE THREAD

**Issue by goddaneel** [clash-verge-rev/clash-verge-rev#1360]
### 功能描述 / Feature description

希望可以为 Releases 中的其他二进制，即 deb、rpm包提供完整性验证，如 sha512

### 使用场景 / Use case

防止篡改传播。
之前使用 appimage 包，可以通过 minisign 进行校验，但现在 appimage 已不再发布，希望可以为其他linux包提供校验文件。

**Comment by wonfen** [comment]
确保在官方发布页下载

**Comment by goddaneel** [comment]
> 确保在官方发布页下载


主要是保证下载文件的完整性，其次才是防止恶意传播等
