### ISSUE TITLE
[BUG] 全局扩展配置中的配置项不起作用

### ISSUE THREAD

**Issue by ZZH-Finalize** [clash-verge-rev/clash-verge-rev#1362]
### 问题描述 / Describe the bug

本来在全局扩展配置中的如下配置, 将会把一些通用的规则添加到所有的订阅中, 但更新版本到v1.7.3之后, 这些配置便不再有效
```YAML
prepend-rule-providers:
  - DOMAIN-KEYWORD, tencent, DIRECT
  - DOMAIN-KEYWORD, outlook, DIRECT
  - DOMAIN-KEYWORD, qq, DIRECT
  - DOMAIN-KEYWORD, bilibili, DIRECT
  - DOMAIN-REGEX, cn\..*, DIRECT
  - DOMAIN-REGEX, .*\.cn, DIRECT
  - PROCESS-NAME, PhoneExperienceHost.exe, DIRECT
  - PROCESS-NAME, YourPhoneAppProxy.exe, DIRECT
  - PROCESS-NAME, wemeetapp.exe, DIRECT
  - PROCESS-NAME, WinStore.App.exe, DIRECT
```

**Comment by xishang0128** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.7.2 但凡看一下更新日志

**Comment by ZZH-Finalize** [comment]
> https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.7.2 但凡看一下更新日志

这是1.7.2的更新日志, 这些配置在1.7.2工作正常

**Comment by ZZH-Finalize** [comment]
在具体的某个订阅文件右键->扩展配置里加入如下配置后, 仍然无法工作, 与更新日志说明不符
```YAML
prepend-rules:
# 前置规则集(v1.6.2已移除)
# prepend-rule-providers:
  - DOMAIN-SUFFIX, asmrgay.com, DIRECT
  - DOMAIN-SUFFIX, asmr.pw, DIRECT
  - DOMAIN-SUFFIX, asmr.121231234.xyz, DIRECT
  - DOMAIN-KEYWORD, tencent, DIRECT
  - DOMAIN-KEYWORD, outlook, DIRECT
  - DOMAIN-KEYWORD, qq, DIRECT
  - DOMAIN-KEYWORD, bilibili, DIRECT
  - DOMAIN-REGEX, cn\..*, DIRECT
  - DOMAIN-REGEX, .*\.cn, DIRECT
  - PROCESS-NAME, PhoneExperienceHost.exe, DIRECT
  - PROCESS-NAME, YourPhoneAppProxy.exe, DIRECT
  - PROCESS-NAME, wemeetapp.exe, DIRECT
  - PROCESS-NAME, WinStore.App.exe, DIRECT
```

**Comment by xishang0128** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/95160953/f698a9ee-34be-4466-a35e-39696dbfaee6)

**Comment by ZZH-Finalize** [comment]
> ![image](https://private-user-images.githubusercontent.com/95160953/346896309-f698a9ee-34be-4466-a35e-39696dbfaee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTY2MDAsIm5iZiI6MTcyMDUxNjMwMCwicGF0aCI6Ii85NTE2MDk1My8zNDY4OTYzMDktZjY5OGE5ZWUtMzRiZS00NDY2LWEzNWUtMzk2OTZkYmZhZWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA5MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5YjI1NjRhZTc0NjIzMDBjMmI4Njc1Mzg0ZGMwNjlmZGZjY2M1YzIwMWY2OTNiMGFjNTlmNTBhNjE2ZGRmOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DHhvP9LBMS35lxLZLSF2LDP0dsKGRrgDYhEqtWEQn5Q)

意思是这里的扩展配置同时包括右键扩展配置和全局扩展配置? 那这样改的话扩展配置里还能做些什么呢? 设置dns ipv6这些跟UI界面上的设置不是重复了吗

**Comment by MystiPanda** [comment]
去看看内核文档配置文件有多少可配置项

**Comment by ZZH-Finalize** [comment]
> 去看看内核文档配置文件有多少可配置项

也就是说现在只能对所有的订阅应用全局的内核配置项? 但是不能把相同的规则应用到多个订阅, 必须一个一个手动复制过去?

**Comment by FlyInWind1** [comment]
算了。用js脚本加吧。虽然麻烦了很多。。。。
