### ISSUE TITLE
[Feature] 局域网连接 显示IP

### ISSUE THREAD

**Issue by ZBrettonYe** [clash-verge-rev/clash-verge-rev#1365]
### 功能描述 / Feature description

希望能直接在设置页面显示本地的局域网IP。这样可以帮助小白快速完成局域网连接。

### 使用场景 / Use case

本地switch连电脑clash, 为了获取windows本地还需要跑cmd指令来获取本地IP，配合端口使用。有一定的学习成本

**Comment by Chen017** [comment]
yes 这样就不用翻设置了 超级方便 原来的CFW也是这样的

**Comment by MystiPanda** [comment]
48f7c15
