### ISSUE TITLE
[BUG] 双击安装没有反应

### ISSUE THREAD

**Issue by munan56** [clash-verge-rev/clash-verge-rev#1368]
### 问题描述 / Describe the bug

双击安装没有反应

初始安装日期:     2022/10/5, 21:20:32
系统启动时间:     2024/7/10, 10:57:05
系统制造商:       LENOVO
系统型号:         20TAA001CD
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。

安装
Clash.Verge_1.7.3_x64-setup.exe
管理员身份安装也没有反应

### 复现步骤 / To Reproduce

双击安装没有反应

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

22H2/22621.3880

### 日志 / Log

无，日志文件在哪里

**Comment by munan56** [comment]
未被防火墙拦截

**Comment by wonfen** [comment]
系统问题
