### ISSUE TITLE
Not warned about change in configuration path

### ISSUE THREAD

**Issue by Anasmusculus** [clash-verge-rev/clash-verge-rev#137]
On Linux x86_64, the upgrade from 1.4.3 to 1.4.4 moved the config files from `$HOME/.local/share/io.github.clash_verge_rev.clash_verge_rev` to `$HOME/.local/share/io.github.clash-verge-rev.clash-verge-rev`. Not quite sure why this is necessary, and I think it is better to warning users about this change.

**Comment by wonfen** [comment]
嗯，这个是之前改错了，以后不会变了。
