### ISSUE TITLE
[BUG] merge 配置消失并且完全无法使用

### ISSUE THREAD

**Issue by xenonz95** [clash-verge-rev/clash-verge-rev#1370]
### 问题描述 / Describe the bug

更新前的多级嵌套merge配置实际上已经在我的应用场景中调试得比较好用了。然而似乎在更新后不仅完全取消了支持，而且无法自动迁移配置，变得很难使用，在我的使用场景中完全无法自动化了。希望可以恢复支持，回滚功能或者同时提供两种merge的用法都可以

### 复现步骤 / To Reproduce

从旧版本更新即会发生

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5 (23F79)

### 日志 / Log

无

**Comment by wonfen** [comment]
把配置文件迁移到新的环境就行了。

**Comment by xenonz95** [comment]
有迁移的说明或者文档吗？我看新的配置里只有我不认识的两个键，我把我的配置直接贴进去发现也没有预期的效果。
另外我有的时候确实需要多个配置文件级联，根据需要开启部分扩展配置，所以我觉得之前的功能还是很有用的，还是希望保留。此外之前的级联配置文件如果还要继续做的话，有点小建议：就是merge配置出错的时候要是输出错误信息就比较好，目前的版本是变成无事发生

**Comment by PctAIGM** [comment]
老版本更适合你，没必要强上新版本

**Comment by WAN8023** [comment]
可以尝试将原本merge文件中的配置分别转移到对应的文件中。我们的文件名不一样，注意区分。

![image](https://github.com/user-attachments/assets/291d8cb7-b7e8-4f36-8d61-a9cef6990e89)

新版本好像丢弃了原本merge中的一些参数，比如`prepend-rules`，`prepend-proxies`等。

也可以直接在软件中编辑，效果一样

![2024-07-13_21-28-50](https://github.com/user-attachments/assets/73fba6cb-28c3-4e82-b9fe-a10211929194)

**Comment by Ximu-Luya** [comment]
> ![2024-07-13_21-28-50](https://private-user-images.githubusercontent.com/82212659/348474503-73fba6cb-28c3-4e82-b9fe-a10211929194.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzM5NTQsIm5iZiI6MTcyMjQzMzY1NCwicGF0aCI6Ii84MjIxMjY1OS8zNDg0NzQ1MDMtNzNmYmE2Y2ItMjhjMy00ZTgyLWI5ZmUtYTEwMjExOTI5MTk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEzNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMTI0Nzg2MjFlNWEyYjExZDU2OWVlMjkyNjQwNDM4ZDcyOTdlMTFmNmRiN2RjODhkYTQ2NmJiYmZmY2U3NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KClnQcfzsUcOzWtdVEu8RV3qB0iwTNLgERKkAixMfo8) [ ![2024-07-13_21-28-50](https://private-user-images.githubusercontent.com/82212659/348474503-73fba6cb-28c3-4e82-b9fe-a10211929194.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzM5NTQsIm5iZiI6MTcyMjQzMzY1NCwicGF0aCI6Ii84MjIxMjY1OS8zNDg0NzQ1MDMtNzNmYmE2Y2ItMjhjMy00ZTgyLWI5ZmUtYTEwMjExOTI5MTk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEzNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMTI0Nzg2MjFlNWEyYjExZDU2OWVlMjkyNjQwNDM4ZDcyOTdlMTFmNmRiN2RjODhkYTQ2NmJiYmZmY2U3NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KClnQcfzsUcOzWtdVEu8RV3qB0iwTNLgERKkAixMfo8) ](https://private-user-images.githubusercontent.com/82212659/348474503-73fba6cb-28c3-4e82-b9fe-a10211929194.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzM5NTQsIm5iZiI6MTcyMjQzMzY1NCwicGF0aCI6Ii84MjIxMjY1OS8zNDg0NzQ1MDMtNzNmYmE2Y2ItMjhjMy00ZTgyLWI5ZmUtYTEwMjExOTI5MTk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEzNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMTI0Nzg2MjFlNWEyYjExZDU2OWVlMjkyNjQwNDM4ZDcyOTdlMTFmNmRiN2RjODhkYTQ2NmJiYmZmY2U3NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KClnQcfzsUcOzWtdVEu8RV3qB0iwTNLgERKkAixMfo8) [ ](https://private-user-images.githubusercontent.com/82212659/348474503-73fba6cb-28c3-4e82-b9fe-a10211929194.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzM5NTQsIm5iZiI6MTcyMjQzMzY1NCwicGF0aCI6Ii84MjIxMjY1OS8zNDg0NzQ1MDMtNzNmYmE2Y2ItMjhjMy00ZTgyLWI5ZmUtYTEwMjExOTI5MTk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEzNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMTI0Nzg2MjFlNWEyYjExZDU2OWVlMjkyNjQwNDM4ZDcyOTdlMTFmNmRiN2RjODhkYTQ2NmJiYmZmY2U3NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KClnQcfzsUcOzWtdVEu8RV3qB0iwTNLgERKkAixMfo8)

确实新版本1.7.x中merge参数的`prepend-rules`这些失效了，不论是单配置的扩展配置，还是全局扩展配置中，都无法生效。

动图内的方法对我有效

**Comment by Ghost-chu** [comment]
> > ![2024-07-13_21-28-50](https://private-user-images.githubusercontent.com/82212659/348474503-73fba6cb-28c3-4e82-b9fe-a10211929194.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzM5NTQsIm5iZiI6MTcyMjQzMzY1NCwicGF0aCI6Ii84MjIxMjY1OS8zNDg0NzQ1MDMtNzNmYmE2Y2ItMjhjMy00ZTgyLWI5ZmUtYTEwMjExOTI5MTk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEzNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMTI0Nzg2MjFlNWEyYjExZDU2OWVlMjkyNjQwNDM4ZDcyOTdlMTFmNmRiN2RjODhkYTQ2NmJiYmZmY2U3NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KClnQcfzsUcOzWtdVEu8RV3qB0iwTNLgERKkAixMfo8)
> >       
> >         [
> >           
> >             ![2024-07-13_21-28-50](https://private-user-images.githubusercontent.com/82212659/348474503-73fba6cb-28c3-4e82-b9fe-a10211929194.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzM5NTQsIm5iZiI6MTcyMjQzMzY1NCwicGF0aCI6Ii84MjIxMjY1OS8zNDg0NzQ1MDMtNzNmYmE2Y2ItMjhjMy00ZTgyLWI5ZmUtYTEwMjExOTI5MTk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEzNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMTI0Nzg2MjFlNWEyYjExZDU2OWVlMjkyNjQwNDM4ZDcyOTdlMTFmNmRiN2RjODhkYTQ2NmJiYmZmY2U3NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KClnQcfzsUcOzWtdVEu8RV3qB0iwTNLgERKkAixMfo8)
> >           
> >         ](https://private-user-images.githubusercontent.com/82212659/348474503-73fba6cb-28c3-4e82-b9fe-a10211929194.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzM5NTQsIm5iZiI6MTcyMjQzMzY1NCwicGF0aCI6Ii84MjIxMjY1OS8zNDg0NzQ1MDMtNzNmYmE2Y2ItMjhjMy00ZTgyLWI5ZmUtYTEwMjExOTI5MTk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEzNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMTI0Nzg2MjFlNWEyYjExZDU2OWVlMjkyNjQwNDM4ZDcyOTdlMTFmNmRiN2RjODhkYTQ2NmJiYmZmY2U3NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KClnQcfzsUcOzWtdVEu8RV3qB0iwTNLgERKkAixMfo8)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/82212659/348474503-73fba6cb-28c3-4e82-b9fe-a10211929194.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzM5NTQsIm5iZiI6MTcyMjQzMzY1NCwicGF0aCI6Ii84MjIxMjY1OS8zNDg0NzQ1MDMtNzNmYmE2Y2ItMjhjMy00ZTgyLWI5ZmUtYTEwMjExOTI5MTk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEzNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMTI0Nzg2MjFlNWEyYjExZDU2OWVlMjkyNjQwNDM4ZDcyOTdlMTFmNmRiN2RjODhkYTQ2NmJiYmZmY2U3NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KClnQcfzsUcOzWtdVEu8RV3qB0iwTNLgERKkAixMfo8)
> 
> 确实新版本1.7.x中merge参数的`prepend-rules`这些失效了，不论是单配置的扩展配置，还是全局扩展配置中，都无法生效。
> 
> 动图内的方法对我有效，谢谢 @WAN8023

确认有相同问题

**Comment by Ptilopsis01** [comment]
> 可以尝试将原本merge文件中的配置分别转移到对应的文件中。我们的文件名不一样，注意区分。
> 
> ![image](https://private-user-images.githubusercontent.com/82212659/348474236-291d8cb7-b7e8-4f36-8d61-a9cef6990e89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MjI1NjksIm5iZiI6MTcyNDUyMjI2OSwicGF0aCI6Ii84MjIxMjY1OS8zNDg0NzQyMzYtMjkxZDhjYjctYjdlOC00ZjM2LThkNjEtYTljZWY2OTkwZTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDE3NTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NTEyOTlmMmQxZGY2ZjY5N2E1ZWY2ZDIyZmFjNmFhODIxZTVmODc5OGFmMTUxMmM4ODY0OGJlYzFlOGRlMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xyBUHoIzAUZuJYOMIfxG11AhfUH3itUR8hG9ZlN_u1g)
> 
> 新版本好像丢弃了原本merge中的一些参数，比如`prepend-rules`，`prepend-proxies`等。
> 
> 也可以直接在软件中编辑，效果一样
> 
> ![2024-07-13_21-28-50](https://private-user-images.githubusercontent.com/82212659/348474503-73fba6cb-28c3-4e82-b9fe-a10211929194.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MjI1NjksIm5iZiI6MTcyNDUyMjI2OSwicGF0aCI6Ii84MjIxMjY1OS8zNDg0NzQ1MDMtNzNmYmE2Y2ItMjhjMy00ZTgyLWI5ZmUtYTEwMjExOTI5MTk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDE3NTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1Mjk5NGFmZmY4NzlmMTA2MTU4ZTZhNjVhMGZmMzZlMTQyY2JlMmRlNTIwMWY2Y2FkMzQ4YzUzMGEwNGU5YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y2jETBp--G5mLxOjF3r7e3OdPJkdOv-hlrwQdB1_v3o) [ ![2024-07-13_21-28-50](https://private-user-images.githubusercontent.com/82212659/348474503-73fba6cb-28c3-4e82-b9fe-a10211929194.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MjI1NjksIm5iZiI6MTcyNDUyMjI2OSwicGF0aCI6Ii84MjIxMjY1OS8zNDg0NzQ1MDMtNzNmYmE2Y2ItMjhjMy00ZTgyLWI5ZmUtYTEwMjExOTI5MTk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDE3NTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1Mjk5NGFmZmY4NzlmMTA2MTU4ZTZhNjVhMGZmMzZlMTQyY2JlMmRlNTIwMWY2Y2FkMzQ4YzUzMGEwNGU5YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y2jETBp--G5mLxOjF3r7e3OdPJkdOv-hlrwQdB1_v3o) ](https://private-user-images.githubusercontent.com/82212659/348474503-73fba6cb-28c3-4e82-b9fe-a10211929194.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MjI1NjksIm5iZiI6MTcyNDUyMjI2OSwicGF0aCI6Ii84MjIxMjY1OS8zNDg0NzQ1MDMtNzNmYmE2Y2ItMjhjMy00ZTgyLWI5ZmUtYTEwMjExOTI5MTk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDE3NTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1Mjk5NGFmZmY4NzlmMTA2MTU4ZTZhNjVhMGZmMzZlMTQyY2JlMmRlNTIwMWY2Y2FkMzQ4YzUzMGEwNGU5YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y2jETBp--G5mLxOjF3r7e3OdPJkdOv-hlrwQdB1_v3o) [ ](https://private-user-images.githubusercontent.com/82212659/348474503-73fba6cb-28c3-4e82-b9fe-a10211929194.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MjI1NjksIm5iZiI6MTcyNDUyMjI2OSwicGF0aCI6Ii84MjIxMjY1OS8zNDg0NzQ1MDMtNzNmYmE2Y2ItMjhjMy00ZTgyLWI5ZmUtYTEwMjExOTI5MTk0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDE3NTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1Mjk5NGFmZmY4NzlmMTA2MTU4ZTZhNjVhMGZmMzZlMTQyY2JlMmRlNTIwMWY2Y2FkMzQ4YzUzMGEwNGU5YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y2jETBp--G5mLxOjF3r7e3OdPJkdOv-hlrwQdB1_v3o)

感谢，这个方法有效

**Comment by Ptilopsis01** [comment]
感谢，上面的方法有效
