### ISSUE TITLE
[BUG] clash verge 为什么开了代理会导致notion上传图片失败

### ISSUE THREAD

**Issue by eachann1024** [clash-verge-rev/clash-verge-rev#1372]
### 问题描述 / Describe the bug

代理选择本地, 香港 , 新加坡都不行

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/43348055/7fba13fc-9df4-4f55-a08a-57b0875a8791)

---

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/43348055/e4edc875-0727-42cb-8349-bf5c9eb879f5)

---

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/43348055/1f177855-0e2d-462c-9f17-ea0af6df45d1)

### 复现步骤 / To Reproduce

同时 arc 浏览器也有这个问题, 即使开了代理选择本地, 香港 , 新加坡,美国都是一样, 登录按钮都点不了

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

  System:     OS: Windows 11 10.0.22631     CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12490F     Memory: 10.55 GB / 31.81 GB   Binaries:     Node: 18.20.2 - C:\Program Files\nodejs\node.EXE     Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD     npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD     pnpm: 9.3.0 - ~\AppData\Local\pnpm\pnpm.CMD   Browsers:     Edge: Chromium (126.0.2592.81)     Internet Explorer: 11.0.22621.3527

### 日志 / Log

日志 0 kb

**Comment by wonfen** [comment]
检查你机场的问题。

**Comment by eachann1024** [comment]
> 检查你机场的问题。

检查过了，确认是没有问题 而且我还有备用的机场，也是用的唯云家的

**Comment by dongchengjie** [comment]
上传图片和notion有啥关系，上传也是上传到图床啊，很多公司的图床都不带有app名称字样，或者甚至是买的云服务提供商的，你得先确认这个

**Comment by weekenlwk** [comment]
@wonfen 最后有找到原因吗？我发现直连反而可以上传图片，连接代理图片一直是preparing

**Comment by dongorigin** [comment]
相同问题，关闭代理就可以上传，打开代理就不能上传

**Comment by irx999** [comment]
这不是分流问题吗

**Comment by kirbyr2** [comment]
Let me share my solution. The underlying issue is that Notion uses a file/image hosting server that is different from its own domain. Due to traffic routing rules, the Notion server and the file server were accessed via different IPs, which caused the upload to fail.

Solution: Enable direct connection and upload an image. Then, check the network requests sent by the Notion app in the log. Make sure all requests are routed through the same IP.

Below are some common Notion-related domains. You can use these as a reference:
```yaml
  - DOMAIN,http-inputs-notion.splunkcloud.com
  - DOMAIN-SUFFIX,notion-static.com
  - DOMAIN-SUFFIX,notion.com
  - DOMAIN-SUFFIX,notion.new
  - DOMAIN-SUFFIX,notion.site
  - DOMAIN-SUFFIX,notion.so
  - DOMAIN-SUFFIX,notionusercontent.com
  - DOMAIN-SUFFIX,unsplash.com
  - DOMAIN-SUFFIX,amazonaws.com
```

**Comment by dongorigin** [comment]
现象，关闭代理可以上传，打开代理无法上传，所以问题和 Notion 的部分网络请求被代理有关。  
根据 @kirbyr2 的思路，我尝试将 Notion 相关域名都直接，也不行，因为国内网络无法访问 Notion 一些服务。  
所以我只将 Notion 图片上传的域名改为直连，其他域名保持代理，得到最简规则如下
```
 - DOMAIN,http-inputs-notion.splunkcloud.com,DIRECT
 - DOMAIN-SUFFIX,amazonaws.com,DIRECT
```

全局扩展脚本参考
```js
/**
 * 配置中的规则"config.rules"是一个数组，通过新旧数组合并来添加
 * @param prependRule 添加的数组
 */
const prependRule = [
 "DOMAIN,http-inputs-notion.splunkcloud.com,DIRECT",
 "DOMAIN-SUFFIX,amazonaws.com,DIRECT",
];
function main(config) {
  // 把旧规则合并到新规则后面(也可以用其它合并数组的办法)
  let oldrules = config["rules"];
  config["rules"] = prependRule.concat(oldrules);
  return config;
}
```
