### ISSUE TITLE
merge只能配置rules无法使用prepend-rules和append-rules 

### ISSUE THREAD

**Issue by xiaheixiaohuo** [clash-verge-rev/clash-verge-rev#1374]
### 问题描述 / Describe the bug

merge只能配置rules无法使用prepend-rules和append-rules ,只有rules生效但是规则里面只有rule配置的ip才能访问其他都无法使用

### 复现步骤 / To Reproduce

配置merge文件

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

无。。。。

**Comment by xishang0128** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.7.2 但凡看一下更新日志

**Comment by yd-yin** [comment]
> 请使用 右键订阅 -> 编辑规则/编辑节点/编辑代理组 来代替

这个看起来是针对不同的订阅分别设定规则
那还有办法做全局的prepend吗？

**Comment by dongchengjie** [comment]
> > 请使用 右键订阅 -> 编辑规则/编辑节点/编辑代理组 来代替
> 
> 这个看起来是针对不同的订阅分别设定规则 那还有办法做全局的prepend吗？

暂时只有全局脚本可以做到

**Comment by yd-yin** [comment]
> > > 请使用 右键订阅 -> 编辑规则/编辑节点/编辑代理组 来代替
> > 
> > 
> > 这个看起来是针对不同的订阅分别设定规则 那还有办法做全局的prepend吗？
> 
> 暂时只有全局脚本可以做到

多谢回复，刚看了https://github.com/clash-verge-rev/clash-verge-rev/issues/1311 大佬们的讨论，我是真纯小白，不会写脚本，希望用简单yaml的全局prepend功能也可以回归

**Comment by LemonCANDY42** [comment]
> > > > 请使用 右键订阅 -> 编辑规则/编辑节点/编辑代理组 来代替
> > > 
> > > 
> > > 这个看起来是针对不同的订阅分别设定规则 那还有办法做全局的prepend吗？
> > 
> > 
> > 暂时只有全局脚本可以做到
> 
> 多谢回复，刚看了#1311 大佬们的讨论，我是真纯小白，不会写脚本，希望用简单yaml的全局prepend功能也可以回归
> 
> BTW，如果右键的可视化和yaml的prepend同时存在，会带来什么问题吗？

+1，同希望简单yaml的全局prepend功能可以回归
