### ISSUE TITLE
设置了高等级的日志输出级别 仍会输出低于设置级别的日志

### ISSUE THREAD

**Issue by Muu-yo** [clash-verge-rev/clash-verge-rev#1375]
### 问题描述 / Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/92625353/15086737-0ae4-44d3-a815-a3f57ce0d4e5)
设置日志等级未 silent 后 仍然会输出 error 级别的日志
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/92625353/31c64062-495f-407c-b15e-124c91038c27)

另外如果可以的话 可否允许log目录可以自定义路径

### 复现步骤 / To Reproduce

设置日志等级未 Silent

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

如图

**Comment by xishang0128** [comment]
设置的是内核的,这是应用的输出

**Comment by Muu-yo** [comment]
> 如果可以的话 **可否允许log目录可以自定义路径**

如果可以的话 可否允许log目录可以自定义路径

**Comment by xishang0128** [comment]
> > 设置的是内核的,这是应用的输出
> 
> 如果可以的话 可否允许log目录可以自定义路径

这无关该issues主题,如有需求,另外开
