### ISSUE TITLE
[BUG] mac系统状态栏图标重叠

### ISSUE THREAD

**Issue by mintmilk** [clash-verge-rev/clash-verge-rev#1378]
### 问题描述 / Describe the bug

<img width="168" alt="截屏2024-07-11 上午12 40 37" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/26186964/6fb8822e-83d1-4ab1-880d-5fc6da91cbcb">
如图所示，状态栏图标和apple的loge重叠了😂，求大大修复。

### 复现步骤 / To Reproduce

macbook m1版本

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macos m1

### 日志 / Log

无需日志

**Comment by xishang0128** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/95160953/eb4aa8ce-8b7a-412c-a117-8c2480a517cb)

https://clash-verge-rev.github.io/faq/macos.html#macos_1

**Comment by mintmilk** [comment]
抱歉抱歉
