### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jasonsuuy** [clash-verge-rev/clash-verge-rev#1379]
### 问题描述 / Describe the bug

订阅失败，提示词the remote profile data is invalid yaml

### 复现步骤 / To Reproduce

是不是不支持我的订阅地址？？但是这个订阅是有效的啊我在小火箭上面能用，用的是justmysocks的机场。请问该怎么修改地址？？"https://jmssub.net/members/getsub.php?service=xxxxxxxxx"   格式是这样的。我查看了URL Schemes页面但是没找到对应的解决办法。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 11

### 日志 / Log
2024-07-11 02:50:44 ERROR - the remote profile data is invalid yaml
2024-07-11 02:50:53 ERROR - the remote profile data is invalid yaml
2024-07-11 03:07:58 ERROR - builder error for url (clash://install-config?url=%3Chttps://jmssub.net/members/getsub.php?service=xxxxxxxxxxxxxxxxxxxxxx)

**Comment by AnyWAT** [comment]
> ERROR - the remote profile data is invalid yaml

貌似格式是这样的：
“https。。。。。。xxx.yaml”

**Comment by xishang0128** [comment]
请确保你的提供商提供的是clash的yaml格式订阅,这里不负责提供商导致的问题

**Comment by yonee77** [comment]
转成clash格式

**Comment by bigben446** [comment]
> ### 问题描述 / Describe the bug
> 订阅失败，提示词the remote profile data is invalid yaml
> 
> ### 复现步骤 / To Reproduce
> 是不是不支持我的订阅地址？？但是这个订阅是有效的啊我在小火箭上面能用，用的是justmysocks的机场。请问该怎么修改地址？？"https://jmssub.net/members/getsub.php?service=xxxxxxxxx" 格式是这样的。我查看了URL Schemes页面但是没找到对应的解决办法。
> 
> ### 操作系统 / OS
> Windows
> 
> ### 操作系统版本 / OS Version
> windows 11
> 
> ### 日志 / Log
> 2024-07-11 02:50:44 ERROR - the remote profile data is invalid yaml 2024-07-11 02:50:53 ERROR - the remote profile data is invalid yaml 2024-07-11 03:07:58 ERROR - builder error for url (clash://install-config?url=%3Chttps://jmssub.net/members/getsub.php?service=xxxxxxxxxxxxxxxxxxxxxx)

搜了一下，根据这个教程把搬瓦工配置改成clash的yaml格式搞定了
https://vpsgongyi.com/p/2387/
