### ISSUE TITLE
打开主仪表板经常是缩小的状态

### ISSUE THREAD

**Issue by taswsz** [clash-verge-rev/clash-verge-rev#138]
### Describe the bug

windows 11 22631, 打开软件后关闭使其回到托盘，过一会儿再打开，窗口就会很小，全挤到屏幕中间

### To Reproduce

无准确步骤

### Platform

Windows

### System Version

windows 11 22631.2715

### Software Version

1.4.4

**Comment by MystiPanda** [comment]
已知bug，已经修复，下个版本就好了。
