### ISSUE TITLE
[BUG] ubuntu 24.04 安装缺失依赖后，依旧无法运行

### ISSUE THREAD

**Issue by znygithub** [clash-verge-rev/clash-verge-rev#1382]
### 问题描述 / Describe the bug

电脑是11 代 i7  英伟达 3080Ti，系统是 ubuntu 24.04 LTS
安装依赖后，软件前端白屏，无法操作

### 复现步骤 / To Reproduce

![WechatIMG213](https://github.com/clash-verge-rev/clash-verge-rev/assets/98650439/578e3d28-d148-4156-ba99-b805c1a1608e)

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

 ubuntu 24.04 LTS

### 日志 / Log

无

**Comment by wonfen** [comment]
为何还再安装1.3.8版？

**Comment by tianchengdemo** [comment]
根版本 老不老 没关系 就是不支持 新的一样不支持

**Comment by wonfen** [comment]
> 根版本 老不老 没关系 就是不支持 新的一样不支持

不知道你在犟些什么，新版本做了支持和优化的：
https://clash-verge-rev.github.io/faq/linux.html

**Comment by znygithub** [comment]
**装了最新版，问题已经解决啦！**当时不知道为啥下了旧版的，anyway，这个 issue 可以 close 啦
