### ISSUE TITLE
[BUG] 更新到1.7.3版本后无法通过局域网连接到代理

### ISSUE THREAD

**Issue by blufish1234** [clash-verge-rev/clash-verge-rev#1383]
### 问题描述 / Describe the bug

更新到1.7.3版本后无法通过局域网连接到代理

### 复现步骤 / To Reproduce

1. 在Clash Verge中开启局域网连接
2. 在局域网中的其他设备上设置代理服务器并填写正确的地址和端口
3. 尝试在该设备上打开Google.com
4. 出现错误

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 专业版 22H2 19045.4651

### 日志 / Log

（同时也无法在日志中看到来自设置过代理伺服器的主机的ip地址）
[2024-07-11-2239.log](https://github.com/user-attachments/files/16186443/2024-07-11-2239.log)

**Comment by AnyWAT** [comment]
试试将“乙太網路”改名英文？

**Comment by blufish1234** [comment]
> 试试将“乙太網路”改名英文？

改的是哪个？

**Comment by AnyWAT** [comment]
![image](https://github.com/user-attachments/assets/ae44b91b-ac62-442d-939b-a45ea5b71007)

**Comment by blufish1234** [comment]
> Win10 下的便携版正常。 试试将“乙太網路”改名英文（爬墙之谜）？

但我不是便携版啊

**Comment by AnyWAT** [comment]
一般便携版正常，安装版应正常？
爬墙之谜：
1、网络名称不要用中文
2、有便携版一般不用安装版
。。。。。。

**Comment by MystiPanda** [comment]
检查防火墙，别听这人瞎咧咧

**Comment by mContext** [comment]
改防护墙没用的话可以试试 **订阅-->全局扩展配置** 里面把几个默认的配置覆盖一下
``` config
# Profile Enhancement Merge Template for Clash Verge
port: 7890
socks-port: 9920
allow-lan: true
bind-address: 0.0.0.0
mode: rule
log-level: silent
external-controller: 127.0.0.1:9090
profile:
  store-selected: true

dns:
  use-system-hosts: false
```

**Comment by miracle859** [comment]
> windows设置-->更新和安全-->windows安全中心-->防火墙和网络保护-->允许应用通过防火墙，把旧的clash meta删了，再添加clash verge安装文件夹里的verge-mihomo.exe进去，原因就是作者把内核改名了，防火墙这块却没改

这个是正解, 把安装文件夹里所有的EXE加入允许通过防火墙

**Comment by ZerOri** [comment]
一样的问题，不过我的情况是 专用网络 没有勾选

![Image](https://github.com/user-attachments/assets/7af7966a-de87-4628-94d9-8d40a317d5a5)

**Comment by ZeChengME** [comment]
<img width="665" height="465" alt="Image" src="https://github.com/user-attachments/assets/44f50d60-944b-4234-b1e5-3ceac6ca4c39" />

我也遇到了，局域网无法访问的问题，最后发现只添加verge-mihomo还不行，又添加了后面那个verge-mihomo-alpha就好了。

**Comment by classmatezhu** [comment]
> <img alt="Image" width="665" height="465" src="https://private-user-images.githubusercontent.com/74135001/467862840-44f50d60-944b-4234-b1e5-3ceac6ca4c39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM4ODUyMjcsIm5iZiI6MTc1Mzg4NDkyNywicGF0aCI6Ii83NDEzNTAwMS80Njc4NjI4NDAtNDRmNTBkNjAtOTQ0Yi00MjM0LWIxZTUtM2NlYWM2Y2E0YzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzMwVDE0MTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MGM4MGE0ZWU3MzRmYWEwNmM3ODlkMjVmYmEzMjNjMzNiNmZlNTYwMjUyYmEwODY2ZTAyOWMzMjQ3NDhhZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CvzERraU0oFKLrplsZxkYtr4Lsn_M1rgvkA5Mx1ea7k">
> 我也遇到了，局域网无法访问的问题，最后发现只添加verge-mihomo还不行，又添加了后面那个verge-mihomo-alpha就好了。

我只添加verge-mihomo就好了，不太清楚原理

**Comment by Dragon1573** [comment]
> > 我也遇到了，局域网无法访问的问题，最后发现只添加 `verge-mihomo` 还不行，又添加了后面那个 `verge-mihomo-alpha` 就好了
> 
> 我只添加 `verge-mihomo` 就好了，不太清楚原理

@classmatezhu 的 CVR 实例可能配置的使用 Mihomo 正式版内核，而 @ZeChengME 可能自己手动调过 CVR 的内核设置切换为 Alpha 版本内核。

放行防火墙时最好同步确认一下 `verge-mihomo` 和 `verge-mihomo-alpha` 显示的进程路径与实际 CVR 实例是否一致。对于卸载换路径重装的情况可能会在此处有多个重复放行条目，但实际文件路径不一致，你以为放行了但实际并没有。

**Comment by krexersm-sys** [comment]
一定要亲手把安装路径里的verge-mihomo再添加一遍!!!不要看到防火墙里有verge-mihomo就觉得已经是添加好了。
