### ISSUE TITLE
1.7.3版本代理连接时断时连 [BUG] 

### ISSUE THREAD

**Issue by mewinners** [clash-verge-rev/clash-verge-rev#1385]
### 问题描述 / Describe the bug

使用1.7.3连接代理，时不时就会断开网络。
具体表现是，在clash里面Clash Verge Rev里面，测试节点延迟是可以通的，延迟不到200，然后走代理就是不能访问网络，Clash Verge Rev里面的测试网络链接那四个网站也全部timeout。
然而，过会儿问题就不存在了，就又能正常访问了。

### 复现步骤 / To Reproduce

代理模式是全局，未开系统代理
浏览器switchyomega设置的端口与clash里面的混合端口相同，并且下面两个端口都是打开状态
开了服务模式，未开tun模式

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

22631.3880

### 日志 / Log
图里面是连接不上的时候的日志
![image](https://github.com/user-attachments/assets/6757389f-b5f4-4823-8fff-4ea46bb1c097)
[2024-07-12-0857.log](https://github.com/user-attachments/files/16188963/2024-07-12-0857.log)

**Comment by wonfen** [comment]
检查下是否开启了ipv6，代理插件设置socks5代理

**Comment by mewinners** [comment]
确实开启了ipv6，是这个原因造成的吗？那我什么时候应该开，什么时候不应该开呢？
目前我这个出问题的电脑网络环境确实只有ipv4，我另外还有一个电脑是ipv4和ipv6都有的，clash里面也是开启了ipv6，那个好像没有遇到这个问题

代理插件是socks5代理

**Comment by wonfen** [comment]
如果网络有ipv6，但是设置中没有打开ipv6，会导致Ipv6流量没有被代理，等于是直连访问失败。

**Comment by mewinners** [comment]
> 如果网络有ipv6，但是设置中没有打开ipv6，会导致Ipv6流量没有被代理，等于是直连访问失败。

呃 那我这是啥问题啊

**Comment by wonfen** [comment]
> > 如果网络有ipv6，但是设置中没有打开ipv6，会导致Ipv6流量没有被代理，等于是直连访问失败。
> 
> 呃 那我这是啥问题啊

也就是网络有ipv6就打开ipv6，没有就关闭

**Comment by mewinners** [comment]
> > > 如果网络有ipv6，但是设置中没有打开ipv6，会导致Ipv6流量没有被代理，等于是直连访问失败。
> > 
> > 
> > 呃 那我这是啥问题啊
> 
> 也就是网络有ipv6就打开ipv6，没有就关闭

emmm  在这个只有ipv4没有ipv6的网络环境下，我之前有尝试 在1.7.3的版本上，关闭ipv6，问题依旧存在
然后我退回了1.7.2，就暂时没有发现这个问题了 而且我也是开着ipv6的

**Comment by weareware** [comment]
我还以为只有我一个人遇到了这个问题，我认为不是ipv6，同情况，而且我的ipv6是关闭的，就是会忽然断网，连百度都连不上

**Comment by mewinners** [comment]
> 我还以为只有我一个人遇到了这个问题，我认为不是ipv6，同情况，而且我的ipv6是关闭的，就是会忽然断网，连百度都连不上

我目前退回了1.7.2  暂时再遇到这个问题了 但是 偶尔网会突然很慢 打开网页挺久

**Comment by AkibaZhang** [comment]
1.7.5同样有bug   电脑有v6地址  verge内ipv6选项开启  依然间歇性断网 但节点可正常测出延迟 开关tun模式恢复

**Comment by TechFa** [comment]
1.7.5同样的问题

**Comment by lkyu-ly** [comment]
same problem on v1.7.5. This has been ignoring me for a long time.

**Comment by lkyu-ly** [comment]
> 1.7.5同样有bug 电脑有v6地址 verge内ipv6选项开启 依然间歇性断网 但节点可正常测出延迟 开关tun模式恢复

我这里则是无论tun和系统代理都有时通时断的问题，重选代理节点/ 切换模式/重启代理可以大概率好使一小段时间，随后又不正常了，日志里面大量的 i/o time out

**Comment by lkyu-ly** [comment]
提供一个问题出现的可能，仅为猜测：[端口耗尽](https://learn.microsoft.com/zh-cn/troubleshoot/windows-client/networking/tcp-ip-port-exhaustion-troubleshooting)，点击可以查看官方给出的排查方式
时通时断是因为系统在大约4分钟后使端口被释放，得以复用，但是为何会高速打开大量端口尚不明确，在我自己的机器上进行若干种测试，基本都指向了端口耗尽这一问题。包括：
- 观察到处于 `TIME_WAIT` 状态的大量端口
- 打开事件查看器，在系统日志下查找明确指示当前状态的事件：事件 ID 4227、事件 ID 4231
- 新连接无法建立，报错明显指向“无可用端口”这一事实

![image](https://github.com/user-attachments/assets/d4ff62e5-eddb-416a-ba52-5728537b5431)

**Comment by liuchengts** [comment]
最新版本1.7.7也有这个问题，头疼

**Comment by chuerFeng** [comment]
所以有最终解决办法吗
