### ISSUE TITLE
[BUG] 开启代理之后bilibili经常关闭连接，偶尔还会出现502错误。

### ISSUE THREAD

**Issue by Heavensward** [clash-verge-rev/clash-verge-rev#1386]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/d1ae6664-0bf0-41d9-8813-0c427138a400)

如图所示，浏览器为Edge最新版，只要开着代理上B站就会发生上述错误，且只有B站会出现这种情况。尝试过用浏览器隐私模式，但没有效果，证明不是浏览器扩展的问题。然后又试了试全局DIRECT模式，错误依旧，说明不是代理规则的问题。出现错误后关闭系统代理刷新即可恢复，不关代理的话需要刷新很多次才行。

### 复现步骤 / To Reproduce

用edge浏览器开代理浏览B站。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 23H2 22631.3880

### 日志 / Log

[2024-07-12-1323.log](https://github.com/user-attachments/files/16189039/2024-07-12-1323.log)

**Comment by wonfen** [comment]
检查ipv6是否开启。

**Comment by reaisheji** [comment]
一样的问题，怎么解决？打算卸载了，旧的clash用的好好的，这个新的，间歇性断网。

**Comment by sgds24** [comment]
![image](https://github.com/user-attachments/assets/e69fe7dd-0c75-4e67-8177-9f7e47a5b671)

**Comment by Heavensward** [comment]
> 检查ipv6是否开启。

Clash设置里面开启IPv6以后有所改善，但偶尔还是会出现错误。

**Comment by TechFa** [comment]
同样的问题，不仅仅是b站

**Comment by BobbyCatty** [comment]
同样的问题……

**Comment by Srcphy** [comment]
一样的问题

**Comment by maizhouzi** [comment]
一样的问题，网站打开经常502，即使规则是直连的也如此，总要刷新一遍，而且越来越频繁，已经影响正常上网了

**Comment by Suhuan-zhen** [comment]
现在的最新版也有这个问题，用全局模式并制定好节点后访问一些国内网站也是 503只能用规则模式
