### ISSUE TITLE
[BUG] 代理绕过设置，软件卡死

### ISSUE THREAD

**Issue by jsonvot** [clash-verge-rev/clash-verge-rev#1387]
### 问题描述 / Describe the bug

配置系统代理的代理绕过设置，在输入法中文模式，按下分号，软件卡死

### 复现步骤 / To Reproduce

配置系统代理的代理绕过设置，在输入法中文模式，按下分号

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

没有

**Comment by wonfen** [comment]
无法复现，需要日志。

**Comment by railzy** [comment]
我现在自定义代理绕过设置如下
`
localhost;127.*;192.168.*;localhost.ptlogin2.qq.com;dps.baidu.com;epicgames*;portal.189free.cn;dmx.upc.ubisoft.com;uplaypc-s-ubisoft.cdn.ubi.com;*.local;*.taobao.com;*.tmall.com
`
点击设置gui会卡死
