### ISSUE TITLE
[BUG] 最新版能订阅成功，但是没有任何节点

### ISSUE THREAD

**Issue by geniusNFIL** [clash-verge-rev/clash-verge-rev#1388]
### 问题描述 / Describe the bug

![2](https://github.com/user-attachments/assets/dc3c7dcd-f488-4875-8789-3b76e5b3b07d)
选择使用订阅，就提示这个，我卸载后重装，还是提示这个。
yaml: line 977: could not find expected ':‘

日志也显示为空

### 复现步骤 / To Reproduce

最新的版1.7.3，
![3](https://github.com/user-attachments/assets/82e6f335-ac1d-4656-8f61-807cea808112)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 22631.3880

### 日志 / Log

日志也显示的空
![1](https://github.com/user-attachments/assets/be3ac887-2041-4c7a-88e2-f840c4bf40b8)

**Comment by xjzh123** [comment]
这种情况下，理论上来说，可能是你的订阅内容有问题，你是否可以访问订阅地址，查看yaml文件中977行附近的内容，并且检查是否存在语法错误？

**Comment by geniusNFIL** [comment]
我查看了，代码总共就到500多行，没到900多行
![5](https://github.com/user-attachments/assets/f7362b45-3c6d-48e9-b460-307d730ec9ac)

**Comment by lvgitt** [comment]
MacOS版有同样问题

**Comment by NeoSnape** [comment]
同问题 订阅后代理页面没东西

**Comment by wonfen** [comment]
tg发订阅连接我试试 @wonfen_bot
严重怀疑是你机场的问题。

**Comment by ChaNg1o1** [comment]
我也是这个问题

**Comment by cjhxc** [comment]
1.7.5同样问题

**Comment by wonfen** [comment]
> 1.7.5同样问题

你们电脑上是不是安装了某些“防泄密”的安全软件？

**Comment by cjhxc** [comment]
> > 1.7.5同样问题
> 
> 你们电脑上是不是安装了某些“防泄密”的安全软件？

我关了bbr2就好了

**Comment by Ataraxy33** [comment]
刚解决 订阅成功之后代理页面不显示的话 在订阅页面点一下导入订阅的名字 显示切换订阅成功就好了

**Comment by geniusNFIL** [comment]
更新到：1.7.5版本后，问题解决
将之前安装的版本，如果是安装版，就卸载干净，如果是便携版，就直接一键删除，清理回收站，彻底删除，然后下载最新的安装版，进行安装，然后重新订阅，问题解决。（目前我是这样解决了，看以后会不会重复出现）

**Comment by mg7905** [comment]
是不是不支持24h2？我是升到24h2后出现的这个问题

**Comment by Kfkcome** [comment]
> MacOS版有同样问题

是的 我也是有这个问题？老哥知道怎么解决吗？

**Comment by xgaoga** [comment]
升级24h2之后出现同样问题，反复卸载重整无效。关闭bbr2就好了。

**Comment by denissyk2004** [comment]
> 升级24h2之后出现同样问题，反复卸载重整无效。关闭bbr2就好了。

这么关闭？我看了网上的几个命令发现我默认就没打开过。

**Comment by xgaoga** [comment]
> > 升级24h2之后出现同样问题，反复卸载重整无效。关闭bbr2就好了。
> 
> 这么关闭？我看了网上的几个命令发现我默认就没打开过。

https://bbs.pcbeta.com/viewthread-1964652-1-1.html
参考这个

**Comment by denissyk2004** [comment]
> > > 升级24h2之后出现同样问题，反复卸载重整无效。关闭bbr2就好了。
> > 
> > 
> > 这么关闭？我看了网上的几个命令发现我默认就没打开过。
> 
> https://bbs.pcbeta.com/viewthread-1964652-1-1.html 参考这个

检测了一下bbr是没有打开的，用360上网修复了一下就好了

**Comment by xiaozhao2000** [comment]
我也有同样问题，反复重装，更换外部监听端口。也没有解决，有什么其他办法吗
![image](https://github.com/user-attachments/assets/83b73113-77df-4347-9a28-5bba1a20656c)
![image](https://github.com/user-attachments/assets/cf2d66e2-d2b6-480a-9264-a3bada9a061d)

**Comment by daxigua112** [comment]
> > > 升级24h2之后出现同样问题，反复卸载重整无效。关闭bbr2就好了。
> > 
> > 
> > 这么关闭？我看了网上的几个命令发现我默认就没打开过。
> 
> https://bbs.pcbeta.com/viewthread-1964652-1-1.html 参考这个

感谢，关掉bbr2解决了

**Comment by linyan9817** [comment]
> 我也有同样问题，反复重装，更换外部监听端口。也没有解决，有什么其他办法吗 ![image](https://private-user-images.githubusercontent.com/177085016/359827703-83b73113-77df-4347-9a28-5bba1a20656c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjQ3ODgsIm5iZiI6MTcyNjEyNDQ4OCwicGF0aCI6Ii8xNzcwODUwMTYvMzU5ODI3NzAzLTgzYjczMTEzLTc3ZGYtNDM0Ny05YTI4LTViYmExYTIwNjU2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwNzAxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzJjZWI1ZDFlOGMzNzJhYjJjY2JiM2ZiMTIzZmQyNjUyOTg0NmM2ZjU0YjYzNDgyODYwMmUyZjFlYjg5OGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5_ko53z7f2DQcxwppSWlNriPqCp32TvzC-xGF7BxxHs) ![image](https://private-user-images.githubusercontent.com/177085016/359827742-cf2d66e2-d2b6-480a-9264-a3bada9a061d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjQ3ODgsIm5iZiI6MTcyNjEyNDQ4OCwicGF0aCI6Ii8xNzcwODUwMTYvMzU5ODI3NzQyLWNmMmQ2NmUyLWQyYjYtNDgwYS05MjY0LWEzYmFkYTlhMDYxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwNzAxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWU0OTVhMTYzZWMwYmVkNGJhYTYzMDQ2YWJmNDI4MmJkNTQxMjc2ZTAwOWI2ZjFlNTU1ZDcxMmQ4M2YyY2RiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JWnHFyiTjtDETo2ZfWWPgyaWTJTVPE_ICeRb5V5_Axo)

我的是yaml解析出问题，同一个链接，试了这里的1.7.7, 1.7.0, 1.6.6, 1.6.5, 1.5.11版本都有yaml解析错误
最后还是用回zzzgydi/clash-verge的1.2.3版本才成功了

**Comment by denissyk2004** [comment]
> > 我也有同样问题，反复重装，更换外部监听端口。也没有解决，有什么其他办法吗
> 
> 我的是yaml解析出问题，同一个链接，试了这里的1.7.7, 1.7.0, 1.6.6, 1.6.5, 1.5.11版本都有yaml解析错误 最后还是用回zzzgydi/clash-verge的1.2.3版本才成功了
> 
> 然后按照上面说的查过了我本来也没有开bbr这些

我换了你说的版本也没用，我三台电脑唯独办公机有问题，怀疑是不是企业内部修改了什么东西造成的。

**Comment by clsddy** [comment]
> 破案了！关闭Windows防火墙后立马就好了。

怎么关
