### ISSUE TITLE
[BUG] 热键无法识别小键盘数字

### ISSUE THREAD

**Issue by Aldrice** [clash-verge-rev/clash-verge-rev#1392]
### 问题描述 / Describe the bug

设置热键为`LCTRL+小键盘8`时，会被程序识别为`LCTRL+普通8`，只有按后者才能起作用，而前者不行。建议区分大键盘数字键和小键盘数字键，并且将前者命名为`8`，后者命名为`Num8`

### 复现步骤 / To Reproduce

N/A

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows10 22H2专业版

### 日志 / Log

_由于日志有大量个人隐私内容，故只提供关联日志项_
2024-07-13 07:52:49 INFO - register hotkey CTRL+8 toggle_system_proxy
2024-07-13 07:52:56 INFO - register hotkey CTRL+7 open_or_close_dashboard

**Comment by dongchengjie** [comment]
https://github.com/tauri-apps/tauri/issues/7543#issuecomment-1855992236
