### ISSUE TITLE
MAC OS版本请求在托盘图标中显示网速 & 增加切换节点选项

### ISSUE THREAD

**Issue by Ethanfuyz** [clash-verge-rev/clash-verge-rev#1393]
### 功能描述 / Feature description

MAC OS版本请求在托盘图标中显示网速 & 增加切换节点选项
参考ClashX Pro
<img width="459" alt="Screenshot 2024-07-13 at 1 11 41 pm" src="https://github.com/user-attachments/assets/ade074d6-2a08-42a3-b180-0a24d80a7935">

### 使用场景 / Use case

MAC OS状态栏

**Comment by MystiPanda** [comment]
不做

**Comment by Half-A-Turnip** [comment]
做的和狗屎一样，当然不做了

**Comment by arShen6** [comment]
> 做的和狗屎一样，当然不做了

我发现这个说话口气很牛的人已经很久没有提代码了，是不是给裁了， 还是换号了
