### ISSUE TITLE
[BUG] verge修改配置导致分流失效

### ISSUE THREAD

**Issue by Horange321** [clash-verge-rev/clash-verge-rev#1398]
### 问题描述 / Describe the bug

同样的配置文件（没有加扩展配置，已经删光了），直接喂给 clash 内核，正常使用。
在 verge 中，所有流量都报 `xxx doesn't match anything, using DIRECT`，导致无法连接。
但是开启`全局`模式能正常使用。
因此，我怀疑是 verge 在整合配置文件时出了错，导致所有流量都走`DIRECT`。我也检查了配置文件，但并没有发现什么问题

### 复现步骤 / To Reproduce

更新后就这样了，两台电脑都是。
每次都能发生，不需要任何额外操作。

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Arch Linux KDE. 从 aur 安装: clash-verge-rev-bin

### 日志 / Log

`google.com doesn't match anything, using DIRECT`

**Comment by wonfen** [comment]
在订阅菜单点右上角“查看运行时配置“检查你的配置文件。

**Comment by Horange321** [comment]
> 在订阅菜单点右上角“查看运行时配置“检查你的配置文件。

又重新排查了一遍。只要我在全局扩展配置中加了 `rules`，订阅里的 `rules` 就全部失效了。
这是我配置有问题吗？

**Comment by MengNianxiaoyao** [comment]
> 又重新排查了一遍。只要我在全局扩展配置中加了 `rules`，订阅里的 `rules` 就全部失效了。 这是我配置有问题吗？

不能这样加，会直接覆盖订阅的`rules`，正确的做法应该是在订阅菜单里右键启用的订阅文件，然后选择`编辑规则`

**Comment by Horange321** [comment]
> > 又重新排查了一遍。只要我在全局扩展配置中加了 `rules`，订阅里的 `rules` 就全部失效了。 这是我配置有问题吗？
> 
> 不能这样加，会直接覆盖订阅的`rules`，正确的做法应该是在订阅菜单里右键启用的订阅文件，然后选择`编辑规则`

但是我看这样改的话，每更新一次订阅就全部失效了

**Comment by utopeadia** [comment]
> > > 又重新排查了一遍。只要我在全局扩展配置中加了 `rules`，订阅里的 `rules` 就全部失效了。 这是我配置有问题吗？
> > 
> > 
> > 不能这样加，会直接覆盖订阅的`rules`，正确的做法应该是在订阅菜单里右键启用的订阅文件，然后选择`编辑规则`
> 
> 但是我看这样改的话，每更新一次订阅就全部失效了

如果需要更新订阅的话我的建议是直接维护一套远程规则

**Comment by MystiPanda** [comment]
> 如果需要更新订阅的话我的建议是直接维护一套远程规则

编辑规则不会被覆盖，直接编辑订阅文件才会被覆盖
