### ISSUE TITLE
[Feature]请问在merge类型Profile中如何做负载均衡？

### ISSUE THREAD

**Issue by sagasm** [clash-verge-rev/clash-verge-rev#14]
我试了cfw的方法没成功，配置如下：
append-proxy-groups:
    - name: ⚖️ 负载均衡-散列
          type: load-balance
          url: 'http://www.google-analytics.com/generate_204'
          interval: 300
          strategy: consistent-hashing
        - name: ⚖️ 负载均衡-轮询
          type: load-balance
          url: 'http://www.google-analytics.com/generate_204'
          interval: 300
          strategy: round-robin
    commands:
        - proxy-groups.⚖️ 负载均衡-散列.proxies=[]proxyNames
        - proxy-groups.0.proxies.0+⚖️ 负载均衡-散列
        - proxy-groups.⚖️ 负载均衡-轮询.proxies=[]proxyNames
        - proxy-groups.0.proxies.0+⚖️ 负载均衡-轮询

**Comment by abrclano** [comment]
建议使用script类型，可以比较灵活的实现自定义分组功能，这是我的配置，可以参考一下 https://github.com/abrclano/Self-use-Rules/tree/main/Clash.verge
