### ISSUE TITLE
[BUG]设置更新间隔后，订阅没有在预设的更新间隔更新

### ISSUE THREAD

**Issue by zhengyongtao** [clash-verge-rev/clash-verge-rev#140]
### Describe the bug

我在配置了更新间隔1440min之后，订阅并没有在24小时的时候进行更新
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/23188362/a2bcd5ce-9c05-4159-be29-5f6fd31a7b7e)

### To Reproduce

配置如下图
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/23188362/81c4304d-ea96-4f92-a9cc-ce2c5fc019bc)

### Platform

MacOS

### System Version

macOS 14.2

### Software Version

v1.4.4

**Comment by wonfen** [comment]
是以软件运行的时间计算的。你设置一个小间隔时间试试。

**Comment by sgrtye** [comment]
> 是以软件运行的时间计算的。你设置一个小间隔时间试试。

Clash Verge应该是使用的自然时间计算的吧 那有没有可能把这个也改成自然时间呢 不然设长了轻度用户无法更新 设短了重度用户更新的又太频繁了。

或者添加一个打开软件自动更新的设置选项

**Comment by sagasm** [comment]
感觉应该用一个定时比如2秒查询计算一次更新间隔比较合理, 因为有的机器经常会睡眠, 会导致更新间隔过长

**Comment by cheneyxx** [comment]
我也觉得应该改成 clash for windows 那样自动更新

**Comment by MystiPanda** [comment]
后续会优化
