### ISSUE TITLE
[BUG] can't initial GeolP: can't download MMDB: Get \https://github. com/MetaCubeX/meta- rule S- dat/releases/dow nload/latest/geoip.meta db

### ISSUE THREAD

**Issue by yingjiuliwhite** [clash-verge-rev/clash-verge-rev#1401]
### 问题描述 / Describe the bug

右击订阅选择使用时 报出这个错误  环境win11 
![image-20240715201105506](https://github.com/user-attachments/assets/1e0d1a09-8894-459a-8b7d-62bcb9e8e262)

### 复现步骤 / To Reproduce

双击软件 - 订阅 - 右击某个订阅 -使用

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

无

**Comment by yingjiuliwhite** [comment]
虽然过一会 连接中能看到节点了, 但是很慢, 每次都需要1分钟左右 才能看到节点..............

**Comment by yuanyao66** [comment]
新版本切换订阅有问题

**Comment by wonfen** [comment]
你的机场和配置文件有问题。配置文件都写不好的机场还是别用了吧。

**Comment by yingjiuliwhite** [comment]
感谢解答了
我导入的时候用的 机场提供的地址 导入的 配置文件里头确实没东西 可能确实是机场的问题&nbsp; 可能我换种导入方式就好了

**Comment by UiShigure** [comment]
回退到 1.7.3 就没问题

**Comment by shulng** [comment]
可以去用1.7.5

**Comment by xiongchen2012** [comment]
1.7.5应该修复了。

**Comment by shiny** [comment]
最新版还是有这个问题

**Comment by Dragon1573** [comment]
> 最新版还是有这个问题

可以借助 Global Extend Config 切换这个配置项使用的 URL ，比如换成 Fastly JSDelivr 。

**Comment by shiny** [comment]
> > 最新版还是有这个问题
> 
> 可以借助 Global Extend Config 切换这个配置项使用的 URL ，比如换成 Fastly JSDelivr 。

我提示的是 ASN.mmdb 无法下载，尝试把 ASN.mmdb 放目录里也未生效。
干脆把规则里的 IP-ASN 规则直接移除了。然后就可以了

```yaml
  # Telegram
  - IP-ASN,62014,选择代理,no-resolve
  - IP-ASN,59930,选择代理,no-resolve
  - IP-ASN,44907,选择代理,no-resolve
  - IP-ASN,211157,选择代理,no-resolve
```
