### ISSUE TITLE
[Feature] 建议增加点击Logo快速重启应用的功能

### ISSUE THREAD

**Issue by Maozai-Teng** [clash-verge-rev/clash-verge-rev#1402]
### 功能描述 / Feature description

cfw有一个很有趣也很有用的小彩蛋功能，就是点击Logo区域可以快速的重启应用。
软件平时会遇到莫名其妙的小bug，每次都需要去右下角的图标右键重启太麻烦了。
开发组也可以在Logo区域设置这么一个功能，点按（怕误触就弄成双击，但cfw那边用起来其实不会）就能快速重启应用。
![QQ截图20240715204458](https://github.com/user-attachments/assets/c4d9ad32-6048-4ac9-ada8-d7e2ec4af35d)

### 使用场景 / Use case

让重启更方便快捷，提升用户使用体验。

**Comment by devioa** [comment]
我也觉得，当初用CFW的时候点这个快速重启就很方便，特别是在调试订阅配置的时候

**Comment by MystiPanda** [comment]
不做
