### ISSUE TITLE
[BUG] 开启Tun后拓展配置的DNS设置无效

### ISSUE THREAD

**Issue by zhuceney** [clash-verge-rev/clash-verge-rev#1403]
### 问题描述 / Describe the bug

开启Tun后，TUN默认的DNS配置会覆盖拓展配置的DNS设置，无法使用其他的DNS解析。

### 复现步骤 / To Reproduce

我在全局拓展配置中添加了
dns:
nameserver:
  - 223.5.5.5
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query  
  - 8.8.8.8
  - 1.1.1.1
 仅使用系统代理时能够正常使用上述DNS。但启用TUN模式后，当前配置会增加一段 
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 8.8.8.8
  fallback: []
  导致配置失效，在log中也直接通过114进行dns查询，而使用系统代理则正常。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

这是使用系统代理，不开启TUN的DNS解析：
time="2024-07-15T21:14:24.4108693+08:00" level=debug msg="[Rule] use default rules"
time="2024-07-15T21:14:24.4124309+08:00" level=debug msg="[DNS] resolve cn.bing.com from tls://223.5.5.5:853"
time="2024-07-15T21:14:24.4124309+08:00" level=debug msg="[DNS] resolve cn.bing.com from https://doh.pub:443/dns-query"
time="2024-07-15T21:14:24.4898934+08:00" level=debug msg="[DNS] cn.bing.com --> [202.89.233.101 202.89.233.100] A from tls://223.5.5.5:853"

开启TUN后，
time="2024-07-15T21:35:31.8678026+08:00" level=debug msg="[Rule] use default rules"
time="2024-07-15T21:35:31.8688376+08:00" level=debug msg="[DNS] resolve login.live.com from udp://8.8.8.8:53"
time="2024-07-15T21:35:31.8688376+08:00" level=debug msg="[DNS] resolve login.live.com from udp://223.5.5.5:53"
time="2024-07-15T21:35:31.8688376+08:00" level=debug msg="[DNS] resolve login.live.com from udp://114.114.114.114:53"
time="2024-07-15T21:35:31.8835575+08:00" level=debug msg="[DNS] login.live.com --> [40.126.35.18 40.126.35.21 20.190.163.19] A from udp://114.114.114.114:53"

**Comment by LD-KiLLer** [comment]
我这边虽然没有发现这个问题，可能是因为我设置了`nameserver-policy`和`default-nameserver`。

但是，我将`enhanced-mode`设置成`redir-host`，并没有在配置文件中申明`fake-ip-range`和`fake-ip-filter`字段，Clash Verge会自动在当前运行配置中添加`fake-ip-range`和`fake-ip-filter`字段。使用`nslookup`查询DNS地址，也变成了`fake-ip-range`里的地址段。

这就导致我的整个DNS配置出问题，会把自有域名给解析出2个IP地址（已套CDN）

我现在是只能在配置文件里申明了`fake-ip-range`和`fake-ip-filter`字段
```
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*'
```
