### ISSUE TITLE
[BUG] 能否将Windows搜索界面的clash verge图标统一

### ISSUE THREAD

**Issue by KamenRevice** [clash-verge-rev/clash-verge-rev#1404]
### 问题描述 / Describe the bug

Windows搜索出来的图标仍旧是之前的clash图标
![微信截图_20240716100644](https://github.com/user-attachments/assets/af4bc4c3-fd1b-4481-b201-bea39549467f)

### 复现步骤 / To Reproduce

如上面描述

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows10 22H2

### 日志 / Log

无

**Comment by ruiy326** [comment]
兄弟，这是你windows系统的问题，清除一下缩略图缓存，然后重启资源管理器。

**Comment by KamenRevice** [comment]
> 兄弟，这是你windows系统的问题，清除一下缩略图缓存，然后重启资源管理器。

用了几种工具清理缩略图缓存和图标缓存，都不可以，搜索出来依旧是原来的图标

**Comment by xuanyuan0408** [comment]
> > 兄弟，这是你windows系统的问题，清除一下缩略图缓存，然后重启资源管理器。
> 
> 用了几种工具清理缩略图缓存和图标缓存，都不可以，搜索出来依旧是原来的图标

`del /A "%userprofile%\AppData\Local\IconCache.db" 2>nul & taskkill /f /im explorer.exe & start explorer.exe`

在PowerShell 里面输入
