### ISSUE TITLE
[BUG] linux下服务模式无法安装

### ISSUE THREAD

**Issue by FlysoftBeta** [clash-verge-rev/clash-verge-rev#1406]
### 问题描述 / Describe the bug

更新1.7.5后服务服务模式无法安装，经检查是install-service没有执行权限。
即使赋予其执行权限，显示安装成功，安装按钮仍显示安装而不是卸载，tun模式无法使用。
同时原来clash内核旁的齿轮内的授权按钮也消失了，不知是否是有意为之。

### 复现步骤 / To Reproduce

安装1.7.5

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

archlinux wayland

### 日志 / Log

[2024-07-16-1042.log](https://github.com/user-attachments/files/16242517/2024-07-16-1042.log)

可以看到日志底部显示 failed to connect to the clash verge service

**Comment by april211** [comment]
遇到一样的问题，回退到1.7.4恢复正常。

**Comment by poplar-at-twilight** [comment]
遇到了同样的问题

>Operating System: openSUSE Tumbleweed 20240712
KDE Plasma Version: 6.1.2
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.2
Kernel Version: 6.9.7-1-default (64-bit)
Graphics Platform: Wayland

**Comment by MystiPanda** [comment]
alpha版本已经修复

**Comment by hrzhu** [comment]
我這邊 1.7.6 還是不能安裝服務，最後一個工作的版本是 1.7.4
