### ISSUE TITLE
[BUG] 卸载程序被卡巴斯基检测为木马自动删除

### ISSUE THREAD

**Issue by Arteiimis** [clash-verge-rev/clash-verge-rev#141]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/94288976/3e25c9bb-1d64-4743-b517-c2156f72951e)

### To Reproduce

今天下午打开电脑显示删除了

### Platform

Windows

### System Version

windows 10 10.0.19045

### Software Version

1.4.4

**Comment by wonfen** [comment]
建议用在线杀毒上传此文件检测一下。

**Comment by lwd-temp** [comment]
参考 https://support.kaspersky.com/common/error/other/15332 向 Kaspersky 提交报告。

**Comment by EliDoves** [comment]
我靠，同样的遭遇，1.43和1.45都会报毒、还有那个openaitranslator 0.30版本也被卡巴斯基杀掉。直接几乎把系统搞崩溃那种程度，，，我还重装了一次系统，装上卡巴斯基之后还是报毒

**Comment by Arteiimis** [comment]
> 参考 https://support.kaspersky.com/common/error/other/15332 向 Kaspersky 提交报告。

已经上报卡巴斯基.

**Comment by EliDoves** [comment]
> > 参考 https://support.kaspersky.com/common/error/other/15332 向 Kaspersky 提交报告。
> 
> 已经上报卡巴斯基.

我昨天也上报了，现在弄好了，你的恢复了吗

**Comment by Arteiimis** [comment]
> > > 参考 https://support.kaspersky.com/common/error/other/15332 向 Kaspersky 提交报告。
> > 
> > 
> > 已经上报卡巴斯基.
> 
> 我昨天也上报了，现在弄好了，你的恢复了吗

已经好了，我把安装文件夹放到排除项外面然后额外扫了一遍文件夹也不报毒了，但是没收到卡巴斯基回邮件，不知道是不是官方修好了，我先把这个issue关了吧
