### ISSUE TITLE
[BUG] Error: clash-verge-rev: SHA256 mismatch

### ISSUE THREAD

**Issue by hasayakey** [clash-verge-rev/clash-verge-rev#1410]
### 问题描述 / Describe the bug

通过homebrew 升级 clash-verge-rev 1.7.3 -> 1.7.5 失败
Error: clash-verge-rev: SHA256 mismatch
Expected: 8268db2a3c45f910aa9092e3ac5a44876cbf139398bc5604ab362f35c764f9ab
  Actual: ab8e4436493188bc22eead0e67e56fc7281df61868a50d0696aa7b4ea7133947

### 复现步骤 / To Reproduce

brew update && brew install clash-verge-rev --cask

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5 (23F79)

### 日志 / Log

==> Upgrading 1 outdated package:
clash-verge-rev 1.7.3 -> 1.7.5
==> Upgrading clash-verge-rev
==> Downloading https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v1.7.5/Clash.Verge_1.7.5_aarch64.dmg
Already downloaded: /Users/edy/Library/Caches/Homebrew/downloads/bd25149d26d67aa774fc415791f0a7763160744645eeedcc8eb5dc55364c21e1--Clash.Verge_1.7.5_aarch64.dmg
==> Purging files for version 1.7.5 of Cask clash-verge-rev
Error: clash-verge-rev: SHA256 mismatch
Expected: 8268db2a3c45f910aa9092e3ac5a44876cbf139398bc5604ab362f35c764f9ab
  Actual: ab8e4436493188bc22eead0e67e56fc7281df61868a50d0696aa7b4ea7133947
    File: /Users/edy/Library/Caches/Homebrew/downloads/bd25149d26d67aa774fc415791f0a7763160744645eeedcc8eb5dc55364c21e1--Clash.Verge_1.7.5_aarch64.dmg
To retry an incomplete download, remove the file above.

**Comment by arthurqiao** [comment]
I'm having the same issue when upgrading

**Comment by MystiPanda** [comment]
1.7.5重新打包了，等homebrew更新checksum就好了
