### ISSUE TITLE
可否设置2个端口，一个用于规则模式，一个用于全局模式

### ISSUE THREAD

**Issue by haai-team** [clash-verge-rev/clash-verge-rev#1413]
### 功能描述 / Feature description

建议设置2个端口，比如一个7897用于规则模式，一个7898用于全局模式。

### 使用场景 / Use case

家里一台电脑上部署了Clash Verge Rev，其他电脑上的浏览器安装了代理插件（比如SwitchyOmega)，
平时使用代理插件访问规则模式的7897端口，如果发现某个网站访问不了，想在浏览器插件上切换到全局模式的7898端口，这样可不用登录那台部署了Clash Verge Rev的电脑切换规则模式到全局模式。

**Comment by itheabyss** [comment]
这个建议好，看了文档还是不知怎么搞

**Comment by minusmulticoloredper** [comment]
目前只能通过开启两个Clash内核，使用两个不同的配置文件，以达到这种效果。

**Comment by qixing-jk** [comment]
> @haai-team 可以使用扩展配置增加，参考文档 https://wiki.metacubex.one/config/inbound/listeners/

意思就是新增一个listener，然后配置他的proxy，不使用任何规则，这样就可以实现这个端口全局代理或者直连之类的了
https://wiki.metacubex.one/config/inbound/listeners/#proxy

**Comment by PichurChill** [comment]
请问后来有实现嘛，我也遇到了一样的情况 @haai-team

**Comment by haai-team** [comment]
又搞了台电脑，部署了两套Clash Verge Rev.

**Comment by PichurChill** [comment]
> 又搞了台电脑，部署了两套Clash Verge Rev.

hh好吧
