### ISSUE TITLE
[BUG] 1.7.5卡巴斯基报毒

### ISSUE THREAD

**Issue by kuyin** [clash-verge-rev/clash-verge-rev#1415]
### 问题描述 / Describe the bug

更新1.7.5后报毒

### 复现步骤 / To Reproduce

如上

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 11 23H2

### 日志 / Log

今天，2024/7/16   22:49:47;对象已删除;A Clash Meta GUI based on tauri.;Clash Verge.exe;D:\Program   Files\Clash Verge;13472;WYJ\wyj35;活动用户;已删除:   PDM:Trojan.Win32.Bazon.a;已删除;PDM:Trojan.Win32.Bazon.a;木马;高;确切;clash   verge.exe;clash verge.exe;d:\program files\clash verge;进程;
--
今天，2024/7/16 22:49:13;检测到恶意对象;A Clash   Meta GUI based on tauri.;Clash Verge.exe;D:\Program Files\Clash   Verge;13472;WYJ\wyj35;活动用户;检测到:   PDM:Trojan.Win32.Bazon.a;检测到;PDM:Trojan.Win32.Bazon.a;木马;高;确切;clash   verge.exe;clash verge.exe;d:\program files\clash verge;进程;数据库
今天，2024/7/16 22:49:13;对象将在重启后删除;A Clash   Meta GUI based on tauri.;Clash Verge.exe;D:\Program Files\Clash   Verge;18060;WYJ\wyj35;活动用户;将在重启后删除:   PDM:Trojan.Win32.Bazon.a;将在重启后删除;PDM:Trojan.Win32.Bazon.a;木马;高;确切;clash   verge.exe;clash verge.exe;d:\program files\clash verge;进程;
今天，2024/7/16 22:48:38;检测到恶意对象;A Clash   Meta GUI based on tauri.;Clash Verge.exe;D:\Program Files\Clash   Verge;18060;WYJ\wyj35;活动用户;检测到:   PDM:Trojan.Win32.Bazon.a;检测到;PDM:Trojan.Win32.Bazon.a;木马;高;确切;clash   verge.exe;clash verge.exe;d:\program files\clash verge;进程;数据库
今天，2024/7/16 22:48:38;回滚已完成;A Clash Meta   GUI based on tauri.;Clash Verge.exe;D:\Program Files\Clash   Verge;24276;WYJ\wyj35;活动用户;回滚应用程序的操作:   PDM:Trojan.Win32.Bazon.a;回滚应用程序的操作;PDM:Trojan.Win32.Bazon.a;木马;高;确切;clash   verge.exe;clash verge.exe;d:\program files\clash verge;进程;
今天，2024/7/16 22:48:38;对象将在重启后删除;A Clash   Meta GUI based on tauri.;Clash Verge.exe;D:\Program Files\Clash   Verge;24276;WYJ\wyj35;活动用户;将在重启后删除:   PDM:Trojan.Win32.Bazon.a;将在重启后删除;PDM:Trojan.Win32.Bazon.a;木马;高;确切;clash   verge.exe;clash verge.exe;d:\program files\clash verge;进程;
今天，2024/7/16 22:48:38;对象已删除;A Clash Meta   GUI based on tauri.;Clash Verge.exe;D:\Program Files\Clash   Verge;24276;WYJ\wyj35;活动用户;已删除:   PDM:Trojan.Win32.Bazon.a;已删除;PDM:Trojan.Win32.Bazon.a;木马;高;确切;Clash   Verge.lnk;Clash Verge.lnk;C:\Users\wyj35\AppData\Roaming\Microsoft\Internet   Explorer\Quick Launch\User Pinned\TaskBar;文件;
今天，2024/7/16 22:48:38;对象已删除;A Clash Meta   GUI based on tauri.;Clash Verge.exe;D:\Program Files\Clash   Verge;24276;WYJ\wyj35;活动用户;已删除:   PDM:Trojan.Win32.Bazon.a;已删除;PDM:Trojan.Win32.Bazon.a;木马;高;确切;Clash   Verge.lnk;Clash Verge.lnk;C:\Users\Public\Desktop;文件;
今天，2024/7/16 22:48:08;进程已终止;A Clash Meta   GUI based on tauri.;Clash Verge.exe;D:\Program Files\Clash   Verge;24276;WYJ\wyj35;活动用户;已终止:   PDM:Trojan.Win32.Bazon.a;已终止;PDM:Trojan.Win32.Bazon.a;木马;高;确切;Clash   Verge.exe;Clash Verge.exe;D:\Program Files\Clash Verge;进程;
今天，2024/7/16 22:48:08;检测到恶意对象;A Clash   Meta GUI based on tauri.;Clash Verge.exe;D:\Program Files\Clash   Verge;24276;WYJ\wyj35;活动用户;检测到:   PDM:Trojan.Win32.Bazon.a;检测到;PDM:Trojan.Win32.Bazon.a;木马;高;确切;clash   verge.exe;clash verge.exe;d:\program files\clash verge;进程;数据库

**Comment by yumaoss** [comment]
最新版本被卡巴斯基删除了

**Comment by guxiaoyong** [comment]
这个是误杀吗？

**Comment by Starfallan** [comment]
请更新卡巴斯基反病毒数据库，误报问题在最新数据库已经修复
