### ISSUE TITLE
[Feature] macos可以添加在导航栏显示网速的feature吗？

### ISSUE THREAD

**Issue by Nioy** [clash-verge-rev/clash-verge-rev#1418]
### 功能描述 / Feature description

<img width="448" alt="image" src="https://github.com/user-attachments/assets/03aaf163-cf32-4989-aa42-6de58dd3b1e4">
类似这样的ui

### 使用场景 / Use case

显示实时网速，知道我的代理是否在正常工作

**Comment by MZHSDSG** [comment]
windows also need ,plz

**Comment by Azhi-ux** [comment]
mac强烈希望加上
