### ISSUE TITLE
[BUG]测试延迟延迟出现

### ISSUE THREAD

**Issue by ngo5** [clash-verge-rev/clash-verge-rev#142]
### Describe the bug

正常情况下测试延迟，已经测好的节点会先显示出来，没测好的节点会有三个点显示测试中。

但切换到**其他页面**再切回**代理界面**，测试延迟需要**等待所有节点**都测好才会显示。

把节点收起再点击测试延迟又会恢复正常。

### To Reproduce

打开verge，点击测试延迟（测完所有节点），切换到其他页面再切回代理页面，点击测试延迟就会出现测完所有节点才会显示延迟的bug。

视频演示：https://files.catbox.moe/zkd4tb.mp4

### Platform

Windows

### System Version

Windows 10 22H2

### Software Version

v1.4.4

**Comment by wonfen** [comment]
看了下你这个测速出现error的应该是属于一个分组(url-test)，这个分组下的测速没有全部完成的情况，再次点击测速当然不会进行测速。
你点击这个分组的测速以后，向下拉，看看是不是这个分组下的所有节点都在测速？

**Comment by ngo5** [comment]
> 查看下你这个测速出现错误的应该是属于一个包(url-test)，这个包下的测速没有全部完成的情况，再次点击测速当然不会进行测速。你点击这个包的测速以后， 向下拉，看看是不是这个分组下的所有节点都在测速？

点击延迟测试后确实在测试，但是不会显示那三个点加载过程，是等待一会直接出现测试结果，不会有那三个点的测试动画。

收回节点列表再拉开节点列表，点击延迟测试，测试过程恢复出现三个点测试过程。

**Comment by wonfen** [comment]
抱歉，有点没听懂；感觉问题不大，先这样用着吧。

**Comment by ngo5** [comment]
> 抱歉，有点没听懂；感觉问题不大，先这样用着吧。

我说了这么多，就是延迟测试的动画消失了意思……

-----------------

延迟测试有动画过程：

https://github.com/clash-verge-rev/clash-verge-rev/assets/111275866/85e50729-2fc1-40fa-911b-6e000d774d2f

-----------------

延迟测试没动画过程（节点直接出现测试结果）：

https://github.com/clash-verge-rev/clash-verge-rev/assets/111275866/561e58a6-11e4-4c92-b29c-947cc1737ebf
