### ISSUE TITLE
[Feature] 默认测试延迟能否添加支持IPv6的链接

### ISSUE THREAD

**Issue by ecyecy** [clash-verge-rev/clash-verge-rev#1421]
### 功能描述 / Feature description

默认的 http://1.1.1.1 只支持IPv4，不支持IPv6，能否修改为：https://cp.cloudflare.com/generate_204 或 https://www.gstatic.com/generate_204 或添加其他支持IPv6访问的链接

https://github.com/clash-verge-rev/clash-verge-rev/blob/c4abc3ade365a8f81f061130d576d6ea93ae5e56/src-tauri/src/core/clash_api.rs#L45C1-L45C30

### 使用场景 / Use case

添加默认延迟测试对IPv6的支持

**Comment by utopeadia** [comment]
可以自行通过配置文件修改啊
