### ISSUE TITLE
希望能增加一个parsers功能，能预编译订阅链接

### ISSUE THREAD

**Issue by xingxin1590** [clash-verge-rev/clash-verge-rev#1423]
### 功能描述 / Feature description

能够通过parsers功能预编译订阅链接，不会导致每次更新订阅链接之后，之前自定义修改的配置文件格式化

### 使用场景 / Use case

更新订阅链接不会导致自定义配置文件格式化
![Screenshot_20240718_005621_com easy abroad](https://github.com/user-attachments/assets/8024022b-454d-4eb9-9cb0-71844325d767)

**Comment by yixiuge301** [comment]
集美 解决了吗？

**Comment by xingxin1590** [comment]
> 集美 解决了吗？

作者说用的脚本和verge一样可以实现，只是方法需要你自己看文档学一下

**Comment by xuanyuan0408** [comment]
是脚本模式 自行编译啊 一样的 我都自己编译的
