### ISSUE TITLE
[Feature]可否增加延迟测试方式选择 

### ISSUE THREAD

**Issue by guangmingLQ** [clash-verge-rev/clash-verge-rev#1424]
### 功能描述 / Feature description

unified-delay参数可以在设置里直接设置（可选）

### 使用场景 / Use case

可以更直观的体现服务器直观的延迟

**Comment by wonfen** [comment]
本来就可以，看杂项设置。
找到后自己关issue

**Comment by MystiPanda** [comment]
？我怎么不知道有

**Comment by MystiPanda** [comment]
不打算做，全局扩展配置里自己写就行

```yaml
unified-delay: true
```
