### ISSUE TITLE
[BUG]  启动后不显示界面

### ISSUE THREAD

**Issue by yukaichao** [clash-verge-rev/clash-verge-rev#1426]
### 问题描述 / Describe the bug

安装后，启动不显示界面，状态栏正常显示图标。

### 复现步骤 / To Reproduce

cpu为nvidia的nx板，安装后启动后状态栏有图标，但是界面没有显示，没有日志打印
![2024-07-18 11-01-27屏幕截图](https://github.com/user-attachments/assets/aa4eb737-16d2-482c-b9d3-d994e52008f5)

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

ubuntu 20.04.6 arm

### 日志 / Log

无

**Comment by ruiy326** [comment]
可能是开了静默启动

**Comment by yukaichao** [comment]
> 可能是开了静默启动

不是这个问题，点击图标也打不开，第一次安装后界面就打不开了，也没日志打印

**Comment by LWQ2EDU** [comment]
遇到了一样的问题，我的是Nvidia orin nano

**Comment by shtse8** [comment]
Same issue here.

**Comment by alex-miniset** [comment]
Same issue here.

**Comment by yijianpeng** [comment]
Same issue here.

**Comment by iorileslie** [comment]
只是没显示界面，鼠标事件都还在，对照windows相应位置，盲点，把密钥粘进去，导入，右键右上角图标设置规则

**Comment by dancininmyheart** [comment]
去/usr/bin找到应用，然后用命令行启动，后面加上--no-sandbox
我是这样解决的

**Comment by wushenhaoyu** [comment]
解决了吗？

**Comment by wonfen** [comment]
> 去/usr/bin找到应用，然后用命令行启动，后面加上--no-sandbox

去/usr/bin找到应用，然后用命令行启动，后面加上--no-sandbox

**Comment by 13760209346** [comment]
> > 去/usr/bin找到应用，然后用命令行启动，后面加上--no-sandbox
> 
> 去/usr/bin找到应用，然后用命令行启动，后面加上--no-sandbox

这个方法我在orin ubuntu20.04上面试了，不管了，用如下方法亲测管用：
终端输入这个启动试试：WEBKIT_DISABLE_COMPOSITING_MODE=1 clash-verge

**Comment by xietianshu** [comment]
你们的方法我都试了，可是还是不管用，看日志好像是桌面和这个冲突了？:

12月 07 15:49:33 wbr-desktop rtkit-daemon[1623]: Failed to make ourselves RT: Operation not permitted
12月 07 15:49:56 wbr-desktop systemd[2642]: gnome-launched-gnome-control-center.desktop-4711.scope: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit UNIT has successfully entered the 'dead' state.
12月 07 15:51:03 wbr-desktop kernel: cpufreq: cpu0,cur:1569000,set:1420800,set ndiv:111
12月 07 15:51:17 wbr-desktop kernel: cpufreq: cpu0,cur:1565000,set:1420800,set ndiv:111
12月 07 15:51:26 wbr-desktop gnome-shell[2865]: ../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
12月 07 15:51:28 wbr-desktop gnome-shell[2865]: ../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
12月 07 15:51:28 wbr-desktop gnome-shell[2865]: ../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
12月 07 15:51:30 wbr-desktop kernel: cpufreq: cpu0,cur:1278000,set:1420800,set ndiv:111
12月 07 15:51:32 wbr-desktop pkexec[8634]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
12月 07 15:51:32 wbr-desktop pkexec[8634]: wbr: Executing command [USER=root] [TTY=unknown] [CWD=/home/wbr] [COMMAND=/usr/lib/update-notifier/package-system-locked]
12月 07 15:52:01 wbr-desktop systemd[2642]: Started VTE child process 8660 launched by gnome-terminal-server process 3682.
-- Subject: UNIT 单元已结束启动
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- UNIT 单元已结束启动。
-- 
-- 启动结果为“done”。
~
