### ISSUE TITLE
[BUG] 规则集太多时无法匹配到规则

### ISSUE THREAD

**Issue by Luna-CY** [clash-verge-rev/clash-verge-rev#1429]
### 问题描述 / Describe the bug

我使用wgetcloud订阅，规则集常规情况下7000+，添加可选策略组后规则集过万，使用clash verge rev时部分主机无法匹配到规则出现直连的情况，在wgetcloud客服的见一下尝试使用clashx pro工具则没有问题

![WX20240718-215352@2x](https://github.com/user-attachments/assets/e6cf17b4-13c2-4bdf-ad9e-4991e78260d6)
![WX20240718-215703@2x](https://github.com/user-attachments/assets/9609fcd1-0323-4084-bcdf-0d49267a418f)

### 复现步骤 / To Reproduce

安装最新版clash verge rev(v1.7.5)
添加WgetCloud订阅
访问chatgpt.com

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5

### 日志 / Log

07-18 21:52:07INFO
[TCP] 198.18.0.1:63047(Microsoft Edge Helper) --> chatgpt.com:443 match Match using 🐟 漏网之鱼[🇸🇬 新加坡 01]
07-18 21:52:08INFO
[TCP] 198.18.0.1:63085(Microsoft Edge Helper) --> ab.chatgpt.com:443 match Match using 🐟 漏网之鱼[🇸🇬 新加坡 01]
07-18 21:52:08INFO
[TCP] 198.18.0.1:63099(Microsoft Edge Helper) --> ab.chatgpt.com:443 match Match using 🐟 漏网之鱼[🇸🇬 新加坡 01]
07-18 21:52:08INFO
[TCP] 198.18.0.1:63101(Microsoft Edge Helper) --> chatgpt.com:443 match Match using 🐟 漏网之鱼[🇸🇬 新加坡 01]
07-18 21:52:09INFO
[UDP] 198.18.0.1:64987(Microsoft Edge Helper) --> ab.chatgpt.com:443 doesn't match any rule using DIRECT
07-18 21:52:46INFO
[TCP] 198.18.0.1:63265(Microsoft Edge Helper) --> chatgpt.com:443 match Match using 🐟 漏网之鱼[🇸🇬 新加坡 01]
07-18 21:53:00INFO
[UDP] 198.18.0.1:64987(Microsoft Edge Helper) --> ab.chatgpt.com:443 doesn't match any rule using DIRECT

**Comment by wonfen** [comment]
检查你规则的载入顺序。

**Comment by Luna-CY** [comment]
> 检查你规则的载入顺序。和多少无关。

第一张截图，列表中ab.chatgpt.com出现了多次，第一个没有匹配到规则集，但是下边的都匹配到了，这会跟载入顺序有关系吗？载入顺序还会动态变更吗？

**Comment by Luna-CY** [comment]
好像是proxy没有打开udp标志的问题，我发现无法匹配的都是udp，我尝试确认一下
