### ISSUE TITLE
[Feature]需要在tun模式中支持修改nameserver和fake-ip-filter

### ISSUE THREAD

**Issue by feileb** [clash-verge-rev/clash-verge-rev#143]
### Is your feature request related to a problem? Please describe.

有的程序使用fake ip无法使用，cfw的tun设置中可以修改fake-ip-filter，修改后就可以了

### Describe the solution you'd like

tun模式支持配置nameserver和fake-ip-filter

### Describe alternatives you've considered

现在只能手动修改

**Comment by wonfen** [comment]
你的意思是加一个fake-ip-filter的功能？

**Comment by feileb** [comment]
如果在界面上可以直接配置，就方便一些，我现在直接修改配置文件也可以实现，但是更新订阅后，需要再修改

**Comment by MystiPanda** [comment]
可以使用Merge操作

**Comment by MystiPanda** [comment]
https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86

**Comment by feileb** [comment]
> https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86

谢谢，这个是我需要的功能，我去试试
