### ISSUE TITLE
[BUG] 自动更新订阅失败

### ISSUE THREAD

**Issue by FUKUA2010** [clash-verge-rev/clash-verge-rev#1431]
### 问题描述 / Describe the bug

设定每10分钟使用系统代理更新一次订阅链接，但是时间到之后，并没有更新。

### 复现步骤 / To Reproduce

如上。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win10

### 日志 / Log

无

**Comment by xxmmllqqqqccqq** [comment]
我也有一样的问题，设置更新间隔为24小时，使用内核代理更新，就从来没有更新过，近期的版本才出现这个问题，以前老版本没有问题

**Comment by wonfen** [comment]
手动更新是否正常？检查一下机场的订阅链接是否有问题？

**Comment by xxmmllqqqqccqq** [comment]
手动可以正常更新，我自己写的规则放在gist上的

**Comment by aorigami** [comment]
一样，自动更新不了，手动更新才行。clash for windows就没这个毛病
