### ISSUE TITLE
[Feature] Mac下图标小了点

### ISSUE THREAD

**Issue by cethink** [clash-verge-rev/clash-verge-rev#1433]
### 功能描述 / Feature description

图标小了点，再大一丢丢就好了，再往下一点就和谐了
<img width="288" alt="Snipaste_2024-07-19_14-55-12" src="https://github.com/user-attachments/assets/36dca488-d8e9-4d38-ae41-387a2f760ed2">

### 使用场景 / Use case

。

**Comment by wonfen** [comment]
改进了
