### ISSUE TITLE
在测试版MacOS Sequoia系统中出现与先前版本一样顶栏图标重合的问题[BUG] 

### ISSUE THREAD

**Issue by TimeLyr1c** [clash-verge-rev/clash-verge-rev#1435]
### 问题描述 / Describe the bug

在Beta版Mac OS Sequoia启动clash verge之后顶栏图标会出现在notch左侧而并非文档中提到的左上角，切换分辨率后图标会消失，重新启动应用后才会再次出现。当其他应用的顶栏长度过大时会与verge图标重合。

### 复现步骤 / To Reproduce

关闭Verge之后重新启动就会出现

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Mac OS Sequoia

### 日志 / Log

<img width="598" alt="截屏2024-07-20 10 38 41" src="https://github.com/user-attachments/assets/aa5e2706-1f17-4dcf-a34c-6de50e3a083f">

**Comment by LUDA0831** [comment]
升级到正式版15之后也出现这个问题,软件升级到2.0问题依旧.
![image](https://github.com/user-attachments/assets/fc3318bf-139c-4b95-af29-a1278ae0dc5f)

**Comment by wenzi7777** [comment]
<img width="147" alt="Screenshot 2024-09-23 at 5 54 30 PM" src="https://github.com/user-attachments/assets/5e505b1d-5d09-4ee9-9e02-3474df71e28d">
the same

**Comment by tongjiann** [comment]
看一下[官方文档](https://www.clashverge.dev/faq/macos.html#macos_1)中的解决方案

**Comment by TimeLyr1c** [comment]
重新调整分辨率后没有用处，有时候依然会重叠甚至消失（实际是藏在刘海后面），目前我用的解决办法是按住command拖拽，有时候有用
