### ISSUE TITLE
[BUG] error: context deadline exceeded

### ISSUE THREAD

**Issue by reoLantern** [clash-verge-rev/clash-verge-rev#1438]
### 问题描述 / Describe the bug

在代理界面测速，所有节点都timeout。在日志中看到，error: context deadline exceeded。
在我的另一台设备上，我同样使用了clash verge 1.7.5版本，和相同的订阅链接，但是没有出现这个情况。
![image](https://github.com/user-attachments/assets/538a82cb-156e-4de2-8ae1-79b9bc85fa1c)

### 复现步骤 / To Reproduce

目前，我不知道这个问题因为什么出现......

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11, 23H2

### 日志 / Log

[2024-07-20-2126.log](https://github.com/user-attachments/files/16321247/2024-07-20-2126.log)

**Comment by wtbsw** [comment]
这个问题解决了吗，我电脑上还是有这个问题

**Comment by reoLantern** [comment]
> 这个问题解决了吗，我电脑上还是有这个问题

我这里后来问题自己消失了... 盲猜是电脑时间和网络时间不同步。
