### ISSUE TITLE
[Feature]建议在mac/linux上添加权限申请

### ISSUE THREAD

**Issue by starlifezzz** [clash-verge-rev/clash-verge-rev#144]
### Is your feature request related to a problem? Please describe.

感谢开发者的付出，希望可以解决在mac和linux下用tun模式每次需要授权内核权限的问题，mac在手动chmod后可以使用，但linux下chmod a+x 或chmod +x 会导致yaml文件找不到

### Describe the solution you'd like

希望在第一次打开软件后给予meta权限

### Describe alternatives you've considered

现在 mac下手动加权是买问题的，mac下原先的clashx pro也一直是可以的，从来没在每次打开专门授权过

**Comment by wonfen** [comment]
看下FAQ： https://github.com/clash-verge-rev/clash-verge-rev/issues/125

`mac/linux请在设置的clash内核点开⚙️，点"授权"`

**Comment by starlifezzz** [comment]
> 看下FAQ： #125
> 
> `mac/linux请在设置的clash内核点开⚙️，点"授权"`

这个是知道的。在mac下我是点了也无效，linux下是每次开tun都要去点一 次
![图片](https://github.com/clash-verge-rev/clash-verge-rev/assets/32615040/2930769b-aad6-43de-899f-88122d40dc16)

**Comment by wonfen** [comment]
用最新版试试看呢？

**Comment by starlifezzz** [comment]
> 用最新版试试看呢？

我更换新版1.45在mac和linux下只输一次密码可以了。
