### ISSUE TITLE
[BUG] 我卸载了edge游览器和一些相关组件后，就无法打开运行了

### ISSUE THREAD

**Issue by pengwangzai** [clash-verge-rev/clash-verge-rev#1440]
### 问题描述 / Describe the bug

我卸载了edge游览器和一些相关组件后，就无法打开运行了，打开软件然后过几秒就闪退，全程没有界面只有任务栏的小图标有显示，我无法确定是我删除edge造成的，在没删除之前是可以使用的，我删除之后重启了一次就无法运行了

### 复现步骤 / To Reproduce

使用geek强制卸载edge和edge update 已经另外一个edge相关的组件

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

暂无

**Comment by Tychristine** [comment]
@pengwangzai 有没有一种可能，这并非是CVR 的“BUG”，你怕不是卸载了 WebView2

**Comment by pengwangzai** [comment]
> @pengwangzai没有一个可能，这不是CVR的“BUG”，你恐怕不是卸载了WebView2

有可能，我貌似是卸载了这个

**Comment by ppoool** [comment]
@Tychristine 为什么我有webview2和楼主问题一样啊

**Comment by pengwangzai** [comment]
> @Tychristine 为什么我有webview2和楼主问题一样啊

我是重新安装了一下edge游览器和相关组件然后下载最新版clash-verge-rev就能使用了
