### ISSUE TITLE
[BUG] proxy group 自动选择（URL-Test）不生效，默认选中第一个节点

### ISSUE THREAD

**Issue by sixrui** [clash-verge-rev/clash-verge-rev#1441]
### 问题描述 / Describe the bug

在开启软件之后，proxy-group 的自动选择（URT-Test）未能生效，其默认选中了第一个节点，在设定的测试间隔interval后也不会测速，一直无测速信息。在此情况下，需手动点击测速操作，而后自动选择功能方可生效。

似乎只有引用Proxy-provider的proxy group才会这样。

![image](https://github.com/user-attachments/assets/53508cff-f594-4bf8-8b87-f8a58726649d)

### 复现步骤 / To Reproduce

Proxy-group采用USE 引用proxy-provider 提供的节点，类型为UR-Test
关闭软件后再打开软件，Proxy-group默认均选中第一个节点，不会进行自动测速切换，等待一段时间后也不会。

![image](https://github.com/user-attachments/assets/228a2712-09aa-4852-bdcc-da524e2b1719)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11 23H2

### 日志 / Log

07-21 17:16:31INFO
[TCP] mihomo --> a.ppconverter.eu.org:443 match Match using PROXY[加拿大 A - 基础VIP节点]
07-21 17:16:31INFO
[TCP] mihomo --> a.ppconverter.eu.org:443 match Match using PROXY[加拿大 A - 基础VIP节点]
07-21 17:16:32INFO
Start initial Compatible provider PROXY
07-21 17:16:32INFO
Start initial Compatible provider Spotify
07-21 17:16:32INFO
Start initial Compatible provider OneDrive
07-21 17:16:32INFO
Start initial Compatible provider default
07-21 17:16:32INFO
Start initial Compatible provider Microsoft
07-21 17:16:32INFO
Start initial Compatible provider YOUTUBE
07-21 17:16:32INFO
Start initial Compatible provider AI
07-21 17:16:32INFO
Start initial Compatible provider Notion
07-21 17:16:33INFO
Load ASN file: C:\Users\lorry\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev/ASN.mmdb

**Comment by programmer-zheng** [comment]
同样的问题，已经使用的是最新版本，换成老版的clash verge（非当前项目） ，问题解决

**Comment by flytam** [comment]
老版本是多老的版本
