### ISSUE TITLE
[BUG] macos 开启tun模式之后，再关闭tun模式，不会把前配置的dns设置还原

### ISSUE THREAD

**Issue by Nioy** [clash-verge-rev/clash-verge-rev#1447]
### 问题描述 / Describe the bug

macos14.5 开启tun模式之后，再关闭tun模式，不会把前配置的dns设置还原

### 复现步骤 / To Reproduce

![1](https://github.com/user-attachments/assets/ea62cc49-d967-482c-9e92-029e0ea6b5a5)
没开启tun模式之前，我的dns配置
![2](https://github.com/user-attachments/assets/c80cf457-293e-421a-a2d0-c8ac1f1d8afd)
开启之后，dns被replace掉了
![3](https://github.com/user-attachments/assets/b3348350-5212-4848-9eca-8273dce5de59)
关闭之后，我之前的dns配置没有被还原

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5

### 日志 / Log

none

**Comment by MystiPanda** [comment]
使用最新的alpha版本，然后重新安装服务模式试试
