### ISSUE TITLE
[BUG] 安装cvr后出现了奇怪的公司内网dns解析问题

### ISSUE THREAD

**Issue by 1394225561** [clash-verge-rev/clash-verge-rev#1451]
### 问题描述 / Describe the bug

1. 安装cvr到应用程序后，没有使用tun模式
2. 关闭系统代理，退出软件，甚至卸载软件，公司内网的域名都无法ping通、无法浏览器成功访问
3. 访问公司内网有前置的网管配置要求：
    DHCP获取IP默认为：172.16.5.XXX，如果是其它网段的IP，请手动修改IP为172.16.5.XXX。
    子网掩码：255.255.254.0  网关：172.16.5.254  **首选DNS：172.16.6.107**
4. 公司内网域名有两套：**6段的域名：172.16.6.252 => github.yj.com；172.16.6.145 => deploy.yj.com**。18段的域名：172.16.18.68 => yunpan.yj.com
5. 现在的问题是**18段的域名可以正常ping、浏览器访问，所有6段的都不通**，使用cvr之前，内网域名访问都是通的
6. traceroute 6段的域名，显示dns解析正常，但是浏览器无法访问
![image](https://github.com/user-attachments/assets/705dc73f-a2a2-49fd-a03a-6f7724e35601)
7. nslookup 6段内网域名，如下：
![image](https://github.com/user-attachments/assets/ab99893f-1871-41a4-91da-ca7a7f97e66d)

卸载cvr后，本地配置hosts，也无法访问6段的域名

### 复现步骤 / To Reproduce

1. 安装cvr到Applications
2. 启动代理、取消代理
3. 访问公司内网域名，失败
不知道是否无意中修改了系统文件
在线等，急

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5

### 日志 / Log

暂无

**Comment by yukkodesu** [comment]
macOS的wifi里面，已连接右边的详细信息按钮，打开看看dns，clash verge rev会莫名其妙把dns改成223.5.5.5也不改回来，要手动改回来

**Comment by 1394225561** [comment]
> macOS的wifi里面，已连接右边的详细信息按钮，打开看看dns，clash verge rev会莫名其妙把dns改成223.5.5.5也不改回来，要手动改回来

是正常的，是首选dns

![image](https://github.com/user-attachments/assets/678193d3-7bf3-4c0d-95b7-b1f50ad7fe75)

![image](https://github.com/user-attachments/assets/e0469620-3672-469b-9567-a2146c80a8dd)

**Comment by MystiPanda** [comment]
检查一下系统代理设置，如果没有异常的话应该考虑是不是其他原因导致的，没有开 tun 的情况下 verge 并不会修改除系统代理以外的其他设置

**Comment by 1394225561** [comment]
> 检查一下系统代理设置，如果没有异常的话应该考虑是不是其他原因导致的，没有开 tun 的情况下 verge 并不会修改除系统代理以外的其他设置

是的，不排除是cvr之外的原因。
现在我知识范围内的排查手段都试过了，找不到原因

不过我有在没关闭代理的情况下访问了这几个6段的内网域名，失败后，反应过来没关代理
然后关闭了代理再次访问，就直接拒绝访问了
不知道是否跟这种误操作有关

因为刚刚试了下一个年久不用的6网段域名（昨天没访问过它），发现可以正常访问
是不是跟导入的代理证书有关，证书的某些配置，把昨天那几个6网段的域名拉黑了或者别的类似操作
导致现在域名无法访问，dns解析虽然成功了
对网络的知识很少 已经黔驴技穷了

**Comment by MystiPanda** [comment]
verge 并没有导入证书的操作

**Comment by 1394225561** [comment]
> verge 并没有导入证书的操作

不好意思 表述不准确，导入订阅
![image](https://github.com/user-attachments/assets/986c2525-e8cd-478a-a329-423807d3fabb)

**Comment by 1394225561** [comment]
> verge 并没有导入证书的操作



好像真的是订阅证书的问题。。。。。。。

这个订阅里有一个“漏网之鱼”的配置项，应该是开启该订阅代理的情况下，如果没有匹配到代理策略，就会走漏网之鱼的配置。

然后我尝试了下：
切到该订阅，然后把一个不开代理能访问的内网域名，在开启代理的情况下访问了一下，再关闭代理，就访问不了了。。。。。
走“漏网之鱼”访问的域名，在关闭代理后，就再也访问不通了
这咋办

![image](https://github.com/user-attachments/assets/a48f793f-57ba-4505-92cf-3271310e0068)
![image](https://github.com/user-attachments/assets/74b258ca-e29d-4d3d-8983-2fa9039f93b3)

**Comment by wonfen** [comment]
规则都写不好的机场建议别用了吧

**Comment by 1394225561** [comment]
> 规则都写不好的机场建议别用了吧

是的 拉黑了，不用了。可是现在该咋搞哦。。。。。

（这个是我无聊 跟着github学的 花1$ 挂域名 搞的一年期限的订阅

另一个是花钱买的比较靠谱的订阅）

**Comment by morganzhh** [comment]
升级后有类似的问题，没找到解决方法，对于某些抽风的域名，在全局扩展配置里面加静态了
 dns:
  nameserver-policy:
    "*.XXX.cn": "11.33.104.239"
    "mail.ABC.com": "11.32.144.239"


> > 规则都写不好的机场建议别用了吧
> 
> 是的 拉黑了，不用了。可是现在该咋搞哦。。。。。
> 
> （这个是我无聊 跟着github学的 花1$ 挂域名 搞的一年期限的订阅
> 
> 另一个是花钱买的比较靠谱的订阅）
