### ISSUE TITLE
[Feature] MacOS 显示优化

### ISSUE THREAD

**Issue by xuanxiaoyu69** [clash-verge-rev/clash-verge-rev#1452]
### 功能描述 / Feature description

1. 状态栏增加网络上下行速度
2. 未启用与启用代理后的图标变化太小，建议启用为黑，未启用为灰，更好分辨

### 使用场景 / Use case

MacOS

**Comment by jidaojiuyou** [comment]
第一点功能同求

**Comment by ShiinaWong** [comment]
2同求、单色模式下托盘的代理开启与否看不出差别，得设置成彩色才能看出来
![开启代理](https://github.com/user-attachments/assets/e004874b-ee04-4ef5-b517-5826de4711d3)
![未开启代理](https://github.com/user-attachments/assets/66fd7d15-662a-464e-ba72-e6af709d1516)

**Comment by hiwanz** [comment]
我mac15.1.1下启动未启用的托盘图标没有变化

**Comment by wonfen** [comment]
改进了
