### ISSUE TITLE
[BUG] 能够加载机场订阅但是无法联网Start DNS server error: listen udp 0.0.0.0:53: bind: permission denied

### ISSUE THREAD

**Issue by CCahead** [clash-verge-rev/clash-verge-rev#1455]
### 问题描述 / Describe the bug

普通用户：能够正常加载机场订阅，但是无法联网；
提权后能够下载订阅但是无法使用订阅，显示failed to save file"/tmp/clash-verge-check.yaml"

### 复现步骤 / To Reproduce

检查过53端口占用情况，没有其他进程监听

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

ubuntu22.04

### 日志 / Log

[2024-07-23-2117.log](https://github.com/user-attachments/files/16349486/2024-07-23-2117.log)

**Comment by Sherry0010** [comment]
在非sudo用户下同样遇到了这个情况，安装软件的那个用户倒是能够正常运行，请问您解决了吗（ubuntu22.04）

**Comment by CCahead** [comment]
没有解决，转战mihomo了

> 在非sudo用户下同样遇到了这个情况，安装软件的那个用户倒是能够正常运行，请问您解决了吗（ubuntu22.04）

**Comment by CCahead** [comment]
> 在非sudo用户下同样遇到了这个情况，安装软件的那个用户倒是能够正常运行，请问您解决了吗（ubuntu22.04）

但我感觉也算解决了？（内核是一样的）。就是我把clash需要的geo信息手工导入进去，就可以上网了。（dns还是由systemd-resolved.service监听）
