### ISSUE TITLE
[Feature] 在代理窗口的节点处增加一个可以屏蔽超时节点的小按钮

### ISSUE THREAD

**Issue by xingxin1590** [clash-verge-rev/clash-verge-rev#1458]
### 功能描述 / Feature description

在代理窗口的节点处增加一个可以屏蔽超时节点的小按钮

### 使用场景 / Use case

![image](https://github.com/user-attachments/assets/d6900517-a31f-4469-87a2-3609e787ad83)

**Comment by Layouwen** [comment]
这个按延迟排序, 不是会把 Error 放最后吗
![image](https://github.com/user-attachments/assets/ac3ed8f1-80ce-4cca-85f1-653a2fff21db)

**Comment by wonfen** [comment]
挂那么多节点的机场说明该换了。

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/979
