### ISSUE TITLE
[Feature]能否把规则页面也设计成连接页面那样的表格形式

### ISSUE THREAD

**Issue by sagasm** [clash-verge-rev/clash-verge-rev#146]
### Is your feature request related to a problem? Please describe.

连接页面

### Describe the solution you'd like

采用和连接那样的表格形式,也支持sort, filter

### Describe alternatives you've considered

无

**Comment by wonfen** [comment]
这样做的意义是啥？现在的过滤搜索不能满足需求么？

**Comment by sagasm** [comment]
1. 界面更统一.
2. 文字缩一堆不美观.
3. 可以按类型(domain, domain-suffix等),  代理组搜索和分类.
