### ISSUE TITLE
[BUG] 用户密码如有特殊符号会导致服务安装失败

### ISSUE THREAD

**Issue by gfunc** [clash-verge-rev/clash-verge-rev#1460]
### 问题描述 / Describe the bug

安装服务时需提供 sudo 密码，如果密码中带有 `&` 符号会导致运行失败，需要 escape 例如&等特殊符号

### 复现步骤 / To Reproduce

设置 -> 服务模式 -> 安装

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15

### 日志 / Log

无

**Comment by AndyChen1024** [comment]
今天下载出现同样问题，密码中带有$，无法安装，修改了密码去掉了$之后，安装了服务模式
