### ISSUE TITLE
[BUG] 启用系统代理和窗口自适应问题

### ISSUE THREAD

**Issue by rickywu** [clash-verge-rev/clash-verge-rev#1464]
### 问题描述 / Describe the bug

启用系统代理，访问国内域名超时，日志中没有匹配记录，关闭系统代理后必须重启verge才能正常访问
启用系统代理时，微信不受影响

另外屏幕横向拼接两个应用时，verge窗口占50%，无法完整显示所有内容，没有自适应窗口 2k分辨率五缩放

### 复现步骤 / To Reproduce

启用系统代理，重启系统，浏览器访问

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

无匹配日志

**Comment by cassielchu** [comment]
应该是dns设置问题，修改一下配置文件就行了
