### ISSUE TITLE
[BUG]  Ubuntu 24.04 上编辑配置文件的窗口是透明的

### ISSUE THREAD

**Issue by whp98** [clash-verge-rev/clash-verge-rev#1465]
### 问题描述 / Describe the bug

Ubuntu 24.04 上编辑配置文件的窗口是透明的

### 复现步骤 / To Reproduce

![image](https://github.com/user-attachments/assets/c6f43609-3512-4421-af11-43829140a5aa)

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

ubuntu24.04

### 日志 / Log

不需要

**Comment by wonfen** [comment]
无法复现，听哦你的具体环境信息。

**Comment by whp98** [comment]
请问需要那些信息，这是内核信息和显示环境 还有发行版

`uname -a`
```
Linux xxxx 6.8.0-39-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
echo $XDG_SESSION_TYPE 
```
x11
```

cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

**Comment by whp98** [comment]
实测2.0已经解决
