### ISSUE TITLE
[BUG] 代理跳过设置输入框里，100.7* 被视为非法

### ISSUE THREAD

**Issue by alecthw** [clash-verge-rev/clash-verge-rev#1469]
### 问题描述 / Describe the bug

代理跳过设置输入框里，`100.7*` 被视为非法，这应该是一个合法的输入。经测试， `100.10*` 是一个合法输入。

### 复现步骤 / To Reproduce

输入`100.7*`，输入框显示红色，输入不合法

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

-

**Comment by wonfen** [comment]
10* 不是标准写法，请看到mircsoft文档： https://learn.microsoft.com/en-us/previous-versions/troubleshoot/browsers/connectivity-navigation/use-proxy-servers-with-ie
