### ISSUE TITLE
因为功能实在太好用，所以希望能添加扫码分享，与扫码添加节点功能，这样对小白使用就更为方便了

### ISSUE THREAD

**Issue by MINGERTAI** [clash-verge-rev/clash-verge-rev#1470]
### 功能描述 / Feature description

因为功能实在太好用，所以希望能添加扫码分享，与扫码添加节点功能，这样对小白使用就更为方便了

### 使用场景 / Use case

添加扫码分享，与扫码添加节点功能

**Comment by minusmulticoloredper** [comment]
请直接分享订阅链接

**Comment by minusmulticoloredper** [comment]
请直接分享订阅链接或配置文件
