### ISSUE TITLE
[BUG] debian sid仍然有libwebkit2gtk依赖问题

### ISSUE THREAD

**Issue by TurnOffNOD** [clash-verge-rev/clash-verge-rev#1472]
### 问题描述 / Describe the bug

在debian sid下，dpkg -i安装deb包，有libwebkit2gtk依赖问题。

```
dpkg: dependency problems prevent configuration of clash-verge:
 clash-verge depends on libwebkit2gtk-4.0-37; however:
  Package libwebkit2gtk-4.0-37 is not installed.
```

debian sid下是有libwebkit2gtk这个包的，版本是`libwebkit2gtk-4.1-0`。

还是希望尽快修复依赖的问题吧

### 复现步骤 / To Reproduce

下载deb包，dpkg -i安装即可。

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

debian sid，发帖时apt update并且dist-upgrade过了

### 日志 / Log

```
~/AppInstallers$ sudo dpkg -i clash-verge_1.7.5_amd64.deb 
Selecting previously unselected package clash-verge.
(Reading database ... 285103 files and directories currently installed.)
Preparing to unpack clash-verge_1.7.5_amd64.deb ...
Unpacking clash-verge (1.7.5) ...
dpkg: dependency problems prevent configuration of clash-verge:
 clash-verge depends on libwebkit2gtk-4.0-37; however:
  Package libwebkit2gtk-4.0-37 is not installed.

dpkg: error processing package clash-verge (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.18-1) ...
Processing triggers for mailcap (3.72) ...
Errors were encountered while processing:
 clash-verge
```

**Comment by sAkuraOfficial** [comment]
#解决方法

## 出现了什么问题?
ubuntu24.04版本不再支持旧的包

## 下载以下两个包
https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libwebkit2gtk-4.0-37_2.43.3-1_amd64.deb

https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libjavascriptcoregtk-4.0-18_2.43.3-1_amd64.deb

## 执行命令
```sh
sudo apt-get install ./libwebkit2gtk-4.0-37_2.43.3-1_amd64.deb 
sudo apt-get install ./libjavascriptcoregtk-4.0-18_2.43.3-1_amd64.deb 
sudo apt-get install ./clash-verge_1.6.6_amd64.deb 
```

**Comment by krystal-cao** [comment]
> # 解决方法
> ## 出现了什么问题?
> ubuntu24.04版本不再支持旧的包
> 
> ## 下载以下两个包
> https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libwebkit2gtk-4.0-37_2.43.3-1_amd64.deb
> 
> https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libjavascriptcoregtk-4.0-18_2.43.3-1_amd64.deb
> 
> ## 执行命令
> ```shell
> sudo apt-get install ./libwebkit2gtk-4.0-37_2.43.3-1_amd64.deb 
> sudo apt-get install ./libjavascriptcoregtk-4.0-18_2.43.3-1_amd64.deb 
> sudo apt-get install ./clash-verge_1.6.6_amd64.deb 
> ```

事实上debian testing和sid前两个包也有一连串的依赖不满足

**Comment by krystal-cao** [comment]
wget http://ftp.cn.debian.org/debian/pool/main/d/dav1d/libdav1d6_1.0.0-2+deb12u1_amd64.deb
wget http://ftp.cn.debian.org/debian/pool/main/r/rust-rav1e/librav1e0_0.5.1-6_amd64.deb
wget http://ftp.cn.debian.org/debian/pool/main/s/svt-av1/libsvtav1enc1_1.4.1+dfsg-1_amd64.deb
wget http://ftp.cn.debian.org/debian/pool/main/liba/libavif/libavif15_0.11.1-1_amd64.deb
wget http://ftp.cn.debian.org/debian/pool/main/w/webkit2gtk/libjavascriptcoregtk-4.0-18_2.44.2-1~deb12u1_amd64.deb
wget http://ftp.cn.debian.org/debian/pool/main/w/webkit2gtk/libwebkit2gtk-4.0-37_2.44.2-1~deb12u1_amd64.deb
wget https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v1.7.5/clash-verge_1.7.5_amd64.deb
这些包按顺序装一下试试应该就可以了，都是debian stable的包，如果还提示缺少依赖，去https://packages.debian.org/search?searchon=names&keywords=libdav搜一下对应的依赖，下载stable里的

**Comment by TurnOffNOD** [comment]
> # 解决方法
> ## 出现了什么问题?
> 
> ubuntu24.04版本不再支持旧的包
> ## 下载以下两个包
> 
> https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libwebkit2gtk-4.0-37_2.43.3-1_amd64.deb
> 
> https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libjavascriptcoregtk-4.0-18_2.43.3-1_amd64.deb
> ## 执行命令
> 
> ```shell
> sudo apt-get install ./libwebkit2gtk-4.0-37_2.43.3-1_amd64.deb 
> sudo apt-get install ./libjavascriptcoregtk-4.0-18_2.43.3-1_amd64.deb 
> sudo apt-get install ./clash-verge_1.6.6_amd64.deb 
> ```

其实不应该这么解决，不同源的包混用，容易引起依赖冲突，影响整个系统。

**Comment by TurnOffNOD** [comment]
> wget http://ftp.cn.debian.org/debian/pool/main/d/dav1d/libdav1d6_1.0.0-2+deb12u1_amd64.deb wget http://ftp.cn.debian.org/debian/pool/main/r/rust-rav1e/librav1e0_0.5.1-6_amd64.deb wget http://ftp.cn.debian.org/debian/pool/main/s/svt-av1/libsvtav1enc1_1.4.1+dfsg-1_amd64.deb wget http://ftp.cn.debian.org/debian/pool/main/liba/libavif/libavif15_0.11.1-1_amd64.deb wget http://ftp.cn.debian.org/debian/pool/main/w/webkit2gtk/libjavascriptcoregtk-4.0-18_2.44.2-1~deb12u1_amd64.deb wget http://ftp.cn.debian.org/debian/pool/main/w/webkit2gtk/libwebkit2gtk-4.0-37_2.44.2-1~deb12u1_amd64.deb wget https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v1.7.5/clash-verge_1.7.5_amd64.deb 这些包按顺序装一下试试应该就可以了，都是debian stable的包，如果还提示缺少依赖，去 [这里](https://packages.debian.org/search?searchon=names&keywords=libdav) 搜一下对应的依赖，下载stable里的

源混用，是产生依赖冲突的好方法……

**Comment by rikonaka** [comment]
同样的问题，Ubuntu 24.04 在树莓派5上...

```bash
# sudo apt install ./clash-verge_1.7.5_arm64.deb  
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'clash-verge' instead of './clash-verge_1.7.5_arm64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clash-verge : Depends: libwebkit2gtk-4.0-37 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by sAkuraOfficial** [comment]
> 同样的问题，Ubuntu 24.04 在树莓派5上...
> 
> ```shell
> > sudo apt install ./clash-verge_1.7.5_arm64.deb  
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Note, selecting 'clash-verge' instead of './clash-verge_1.7.5_arm64.deb'
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  clash-verge : Depends: libwebkit2gtk-4.0-37 but it is not installable
> E: Unable to correct problems, you have held broken packages.
> ```

https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libjavascriptcoregtk-4.0-18_2.43.3-1_arm64.deb

https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libwebkit2gtk-4.0-37_2.43.3-1_arm64.deb

**Comment by rikonaka** [comment]
> > 同样的问题，Ubuntu 24.04 在树莓派5上...
> > ```shell
> > > sudo apt install ./clash-verge_1.7.5_arm64.deb  
> > Reading package lists... Done
> > Building dependency tree... Done
> > Reading state information... Done
> > Note, selecting 'clash-verge' instead of './clash-verge_1.7.5_arm64.deb'
> > Some packages could not be installed. This may mean that you have
> > requested an impossible situation or if you are using the unstable
> > distribution that some required packages have not yet been created
> > or been moved out of Incoming.
> > The following information may help to resolve the situation:
> > 
> > The following packages have unmet dependencies:
> >  clash-verge : Depends: libwebkit2gtk-4.0-37 but it is not installable
> > E: Unable to correct problems, you have held broken packages.
> > ```
> 
> https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libjavascriptcoregtk-4.0-18_2.43.3-1_arm64.deb
> 
> https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libwebkit2gtk-4.0-37_2.43.3-1_arm64.deb

可以了，感谢大佬

**Comment by building-blocks-g** [comment]
> # 解决方法
> ## 出现了什么问题?
> ubuntu24.04版本不再支持旧的包
> 
> ## 下载以下两个包
> https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libwebkit2gtk-4.0-37_2.43.3-1_amd64.deb
> 
> https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libjavascriptcoregtk-4.0-18_2.43.3-1_amd64.deb
> 
> ## 执行命令
> ```shell
> sudo apt-get install ./libwebkit2gtk-4.0-37_2.43.3-1_amd64.deb 
> sudo apt-get install ./libjavascriptcoregtk-4.0-18_2.43.3-1_amd64.deb 
> sudo apt-get install ./clash-verge_1.6.6_amd64.deb 
> ```

是的，这个方案是可以解决这个问题的，但是不知道是不是我机器的问题，安装之后关机，重启等动画没有了，卡死在桌面上，必须等到90s后才能关机。

**Comment by TurnOffNOD** [comment]
> # 解决方法
> ## 出现了什么问题?
> 
> ubuntu24.04版本不再支持旧的包
> ## 下载以下两个包
> 
> https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libwebkit2gtk-4.0-37_2.43.3-1_amd64.deb
> 
> https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libjavascriptcoregtk-4.0-18_2.43.3-1_amd64.deb
> ## 执行命令
> 
> ```shell
> sudo apt-get install ./libwebkit2gtk-4.0-37_2.43.3-1_amd64.deb 
> sudo apt-get install ./libjavascriptcoregtk-4.0-18_2.43.3-1_amd64.deb 
> sudo apt-get install ./clash-verge_1.6.6_amd64.deb 
> ```

debian sid现在不是包的依赖冲突：

```
$ sudo apt install ./AppInstallers/clash-verge_1.7.5_amd64.deb
......（省略）
Unsatisfied dependencies:
 libsvtav1enc2 : Conflicts: libsvtav1enc1 but 1.4.1+dfsg-1 is to be installed
```

这个`libsvtav1enc1`是`libwebkit2gtk-4.0.37`的依赖的依赖。

**Comment by TurnOffNOD** [comment]
更新：现在的clash verge rev alpha，版本号2.0.0的是可以在debian sid上正常使用的。
