### ISSUE TITLE
[BUG] 切换订阅之后会断连，必须开关代理后才能重新连接上网

### ISSUE THREAD

**Issue by xingxin1590** [clash-verge-rev/clash-verge-rev#1473]
### 问题描述 / Describe the bug

切换订阅之后会断连，必须开关代理后才能重新连接上网

### 复现步骤 / To Reproduce

进行切换订阅之后，发现网络波动为0
![image](https://github.com/user-attachments/assets/59a84b6e-17d2-4b39-96ba-35b18436ab09)
![image](https://github.com/user-attachments/assets/68a7d0df-40f2-4bb5-a138-eb0b73cc9e4e)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

1.7.5

### 日志 / Log

![image](https://github.com/user-attachments/assets/ff8d9d10-d22d-40aa-8765-63ae2622b8db)
图中日志信息为上一个订阅的日志信息，后面那个订阅没有产生日志信息

**Comment by wonfen** [comment]
这个是你机场的配置问题吧，切换订阅的时候选到了不可用的节点上了。

**Comment by xingxin1590** [comment]
> 这个是你机场的配置问题吧，切换订阅的时候选到了不可用的节点上了。

机场配置？这跟机场配置有什么关系，我自己写的规则，难道自动选择也跟机场配置有关？
