### ISSUE TITLE
[BUG] 软件导致Win11蓝屏

### ISSUE THREAD

**Issue by fromXin** [clash-verge-rev/clash-verge-rev#1475]
### 问题描述 / Describe the bug

我开着TUN模式在玩英雄联盟，突然蓝屏，蓝屏代码:UNEXPECTED_KERNEL_MODE_TRAP。

我去微软社区提问，并上传了dump文件，社区的人告诉我是verge-mihomo.exe这个进程出了问题。
这里是微软社区我的提问的[链接](https://answers.microsoft.com/zh-hans/windows/forum/all/%E8%93%9D%E5%B1%8F%E9%97%AE%E9%A2%98%E6%88%91/0ef2a5d5-f29a-41e2-b81d-959134b28c55)。

我的Clash Verge版本为:1.7.5，内核为1.18.6Mihomo

这里是Dump文件的[链接](https://drive.google.com/file/d/1gfn6-jdVbt9U84y-3ooqU8AN8B8AwjFx/view?usp=sharing)。

重启电脑后，Clash Verge正常使用，电脑也正常使用，我重连游戏完成了对局。

### 复现步骤 / To Reproduce

偶发性问题，只发生了这一次，无法复现。

我当时的详细情况是，开着TUN模式在玩国服英雄联盟，在对局中途蓝屏了。

我对我的订阅添加了扩展规则和代理组（使用Clash Verge的内置编辑工具:右键订阅信息 -> 选择编辑规则/编辑代理组）。

添加的规则并不涉及英雄联盟。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11专业版 23H2 22631.3880

### 日志 / Log

2024-07-25 19:13:01 INFO - register hotkey CTRL+= toggle_system_proxy
2024-07-25 19:13:01 INFO - register hotkey CTRL+- toggle_tun_mode

下面应该是蓝屏之后重启电脑后，Clash Verge自动启动生成的日志

2024-07-25 22:10:05 INFO - register hotkey CTRL+= toggle_system_proxy
2024-07-25 22:10:05 INFO - register hotkey CTRL+- toggle_tun_mode

只是快捷键绑定，没别的

**Comment by xishang0128** [comment]
@fromXin 无法稳定复现等于无法修复,请自行关闭

**Comment by yuyuyurui** [comment]
我也遇到了这个问题。我在观看浏览器国内直播。clash是系统代理 未用TUN模式。蓝屏代码为RIVER_IRQL_NOT_LESS_OR_EQUAL (d1) netio.sys.. 蓝屏文件显示verge-mihomo.exe导致。 已不是第一次发生。共计三次。两次在用网页 一次在英雄联盟。   
机器是笔记本 cpu是13代Hx。不知是否有关。  不能稳定复现，目前不知触发原因。

**Comment by lewis5253** [comment]
我也遇到了相似的问题，也是clash导致电脑蓝屏，请问楼主是怎么解决的？

**Comment by yuyuyurui** [comment]
> 我也遇到了相似的问题，也是clash导致电脑蓝屏，请问楼主是怎么解决的？

你用adguard 或者内存超频了吗

**Comment by yuyuyurui** [comment]
> ### 问题描述 / Describe the bug
> 我开着TUN模式在玩英雄联盟，突然蓝屏，蓝屏代码:UNEXPECTED_KERNEL_MODE_TRAP。
> 
> 我去微软社区提问，并上传了dump文件，社区的人告诉我是verge-mihomo.exe这个进程出了问题。 这里是微软社区我的提问的[链接](https://answers.microsoft.com/zh-hans/windows/forum/all/%E8%93%9D%E5%B1%8F%E9%97%AE%E9%A2%98%E6%88%91/0ef2a5d5-f29a-41e2-b81d-959134b28c55)。
> 
> 我的Clash Verge版本为:1.7.5，内核为1.18.6Mihomo
> 
> 这里是Dump文件的[链接](https://drive.google.com/file/d/1gfn6-jdVbt9U84y-3ooqU8AN8B8AwjFx/view?usp=sharing)。
> 
> 重启电脑后，Clash Verge正常使用，电脑也正常使用，我重连游戏完成了对局。
> 
> ### 复现步骤 / To Reproduce
> 偶发性问题，只发生了这一次，无法复现。
> 
> 我当时的详细情况是，开着TUN模式在玩国服英雄联盟，在对局中途蓝屏了。
> 
> 我对我的订阅添加了扩展规则和代理组（使用Clash Verge的内置编辑工具:右键订阅信息 -> 选择编辑规则/编辑代理组）。
> 
> 添加的规则并不涉及英雄联盟。
> 
> ### 操作系统 / OS
> Windows
> 
> ### 操作系统版本 / OS Version
> Win11专业版 23H2 22631.3880
> 
> ### 日志 / Log
> 2024-07-25 19:13:01 INFO - register hotkey CTRL+= toggle_system_proxy 2024-07-25 19:13:01 INFO - register hotkey CTRL+- toggle_tun_mode
> 
> 下面应该是蓝屏之后重启电脑后，Clash Verge自动启动生成的日志
> 
> 2024-07-25 22:10:05 INFO - register hotkey CTRL+= toggle_system_proxy 2024-07-25 22:10:05 INFO - register hotkey CTRL+- toggle_tun_mode
> 
> 只是快捷键绑定，没别的

你使用adguard或者内存超频了吗

**Comment by fromXin** [comment]
> 我也遇到了相似的问题，也是clash导致电脑蓝屏，请问楼主是怎么解决的？

没解决的，就那一次，后面一直没发生过了，现在更到最新版一直没发生过了

**Comment by fromXin** [comment]
> > 我也遇到了相似的问题，也是clash导致电脑蓝屏，请问楼主是怎么解决的？
> 
> 
> 
> 你用adguard 或者内存超频了吗

没有，电脑性能参数均为出厂默认设置

**Comment by lewis5253** [comment]
> > 我也遇到了相似的问题，也是clash导致电脑蓝屏，请问楼主是怎么解决的？
> 
> 你用adguard 或者内存超频了吗

adguard有在用，内存是两条16g内存开了xmp后频率到3600，请问蓝屏是和这两个因素有关吗？蓝屏还是会时不时出现，clash更新到最新也没用，求解决方法

**Comment by yuyuyurui** [comment]
> > > 我也遇到了相似的问题，也是clash导致电脑蓝屏，请问楼主是怎么解决的？
> > 
> > 
> > 你用adguard 或者内存超频了吗
> 
> adguard有在用，内存是两条16g内存开了xmp后频率到3600，请问蓝屏是和这两个因素有关吗？蓝屏还是会时不时出现，clash更新到最新也没用，求解决方法

adguard 设置里网络有个wfp网络驱动程序  我把那个关了以后 还没蓝屏过

**Comment by lewis5253** [comment]
> > > > 我也遇到了相似的问题，也是clash导致电脑蓝屏，请问楼主是怎么解决的？
> > > 
> > > 
> > > 你用adguard 或者内存超频了吗
> > 
> > 
> > adguard有在用，内存是两条16g内存开了xmp后频率到3600，请问蓝屏是和这两个因素有关吗？蓝屏还是会时不时出现，clash更新到最新也没用，求解决方法
> 
> adguard 设置里网络有个wfp网络驱动程序 我把那个关了以后 还没蓝屏过

感谢回复，我修改设置试一下，看后续还会不会蓝屏

**Comment by cangxige** [comment]
LOL感觉与代理会有冲突，我开代理玩游戏有时候客户端会进不去，有时候也会蓝屏，应该是网络驱动等冲突
