### ISSUE TITLE
[BUG]  macOS下，打开后概率性会在左上角显示多余图标

### ISSUE THREAD

**Issue by yanceysong** [clash-verge-rev/clash-verge-rev#1477]
### 问题描述 / Describe the bug

<img width="129" alt="image" src="https://github.com/user-attachments/assets/753a0860-7c27-42af-b7ab-7cf60fdc84dd">
会这样显示，并且点击左上角会默认在另外一个logo展开 如下图
<img width="1397" alt="image" src="https://github.com/user-attachments/assets/5fdb2257-0fb5-4f2d-a7f4-f3f046107683">

### 复现步骤 / To Reproduce

打开软件就会复现，无论是否开代理

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS 14.5

### 日志 / Log

null

**Comment by huina1621** [comment]
https://clash-verge-rev.github.io/faq/macos.html#macos_1
