### ISSUE TITLE
[BUG] 服务模式无法安装

### ISSUE THREAD

**Issue by Meonthb** [clash-verge-rev/clash-verge-rev#148]
### Describe the bug

无法安装服务模式，错误信息如图所示：
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/60881723/62a544c4-66c5-4217-8cff-f165d737229a)

### To Reproduce

即使重启后也不行。

### Platform

Windows

### System Version

23H2 22631.2861

### Software Version

v1.4.5

**Comment by moranno** [comment]
最新版已经修复了这个问题，尝试重新下载安装。

**Comment by Meonthb** [comment]
已经是最新版1.4.5，且已经尝试过卸载重装，但仍然无法安装服务模式。

**Comment by wonfen** [comment]
你下载的是32位还是64位？

**Comment by bigbaldy1128** [comment]
我也刚下载了1.4.5版本，一样的问题

**Comment by MystiPanda** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/152463842/b6740398-3c6c-4ea0-abc8-93c904833d1f)

**Comment by bigbaldy1128** [comment]
> ![image](https://private-user-images.githubusercontent.com/152463842/290990475-b6740398-3c6c-4ea0-abc8-93c904833d1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NzU3NzQsIm5iZiI6MTcwMjc3NTQ3NCwicGF0aCI6Ii8xNTI0NjM4NDIvMjkwOTkwNDc1LWI2NzQwMzk4LTNjNmMtNGVhMC1hYmM4LTkzYzkwNDgzM2QxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwMTExMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzdjODNlOTRjNWQ4NzJhNDg3ODQwZTRjZjE1NTAyM2MzZTA0Y2QxZWI4YzkzNmVmM2ZjMDU3ZGY0ZmJhYjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-Kw_tWVG_sXsN_r12f_5hgzgg9i9DCZe4Xx2bCHtTxg)

解决了，非常感谢
