### ISSUE TITLE
[Feature] 支持ubuntu 24.o4

### ISSUE THREAD

**Issue by shingle2302** [clash-verge-rev/clash-verge-rev#1481]
### 功能描述 / Feature description

ubuntu已删除libwebkit2gtk-4.0-37

### 使用场景 / Use case

ubuntu 24.04安装clash_verge,
安装提示
正在选中未选择的软件包 clash-verge。
(正在读取数据库 ... 系统当前共安装有 232235 个文件和目录。)
准备解压 clash-verge_1.7.5_amd64.deb  ...
正在解压 clash-verge (1.7.5) ...
dpkg: 依赖关系问题使得 clash-verge 的配置工作不能继续：
 clash-verge 依赖于 libwebkit2gtk-4.0-37；然而：
  未安装软件包 libwebkit2gtk-4.0-37。

**Comment by jackbizhz** [comment]
Having the same issue here. Ubuntu 24.04 LTS.

**Comment by Hayakee** [comment]
我的建议是看一下常见问题。
https://clash-verge-rev.github.io/faq/linux.html

**Comment by shingle2302** [comment]
> Having the same issue here. Ubuntu 24.04 LTS.
回复了，看下这个

https://clash-verge-rev.github.io/faq/linux.html

**Comment by jackbizhz** [comment]
> > Having the same issue here. Ubuntu 24.04 LTS.
> > 回复了，看下这个
> 
> https://clash-verge-rev.github.io/faq/linux.html

Better not follow this way
