### ISSUE TITLE
[BUG] 系统代理，代理绕过设置不好使

### ISSUE THREAD

**Issue by liusheng613** [clash-verge-rev/clash-verge-rev#1482]
### 问题描述 / Describe the bug

将需要绕过代理的网站添加到代理绕过设置后相关网站仍然走代理。已经重启clash与clash内核，当前绕过也显示了添加的网站。用的是*.xxx.com,语法检查正常

### 复现步骤 / To Reproduce

将需要绕过代理的网站添加到代理绕过设置后相关网站仍然走代理。已经重启clash与clash内核，当前绕过也显示了添加的网站。用的是*.xxx.com,语法检查正常

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

localhost;127.*;192.168.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;<local>;*.liaoxuefeng.com
TCP] 127.0.0.1:55639 --> liaoxuefeng.com:443 match Match using 飞鸟云[新加坡|06直连Hysteria2]

**Comment by MystiPanda** [comment]
*.liaoxuefeng.com 又匹配不到 liaoxuefeng.com

**Comment by xuanyuan0408** [comment]
多了解一下域名格式！为什么不设置成 DOMAIN-KEYWORD,liaoxuefeng,🚀节点选择

**Comment by liusheng613** [comment]
我理解的正常*.xxx按照正则表达式能匹配上，不过去掉*. 之后确实好使了，我再研究下，谢谢各位！

**Comment by liusheng613** [comment]
没看到 DOMAIN-KEYWORD这种规则在clash-verge中哪里可以设置，我是在代理绕过设置里加的直连域名

**Comment by xuanyuan0408** [comment]
> 没看到 DOMAIN-KEYWORD这种规则在clash-verge中哪里可以设置，我是在代理绕过设置里加的直连域名

注意：v1.7.5
        订阅>节点配置>编辑规则> 选择 “DOMAIN-KEYWORD” 填写你要域名中间部分  上到下检测 最上面检测最快！

**Comment by xuanyuan0408** [comment]
> 我理解的正常*.xxx按照正则表达式能匹配上，不过去掉*. 之后确实好使了，我再研究下，谢谢各位！

分流规则，跟这个匹配不上的！

**Comment by xuanyuan0408** [comment]
> 我理解的正常*.xxx按照正则表达式能匹配上，不过去掉*. 之后确实好使了，我再研究下，谢谢各位！

规则不一样，所有不是通用的！

**Comment by liusheng613** [comment]
> > 我理解的正常*.xxx按照正则表达式能匹配上，不过去掉*. 之后确实好使了，我再研究下，谢谢各位！
> 
> 规则不一样，所以不是通用的！



> > 没看到 DOMAIN-KEYWORD这种规则在clash-verge中哪里可以设置，我是在代理绕过设置里加的直连域名
> 
> 注意：v1.7.5 订阅>节点配置>编辑规则> 选择 “DOMAIN-KEYWORD” 填写你要域名中间部分 上到下检测 最上面检测最快！

谢谢，学到了一招
