### ISSUE TITLE
[BUG] 点击延迟测试后，程序会直接闪退

### ISSUE THREAD

**Issue by eastjoe** [clash-verge-rev/clash-verge-rev#1486]
### 问题描述 / Describe the bug

点击延迟测试后，程序会直接闪退，版本：1.7.5

回退到1.7.3版本后，没这个问题

### 复现步骤 / To Reproduce

点击延迟测试，无论是全局还是单个线路，都会闪退，程序直接关闭掉

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 22H2

### 日志 / Log

无日志

**Comment by Tychristine** [comment]
@eastjoe 什么 issue 日志都不报
