### ISSUE TITLE
[BUG] Ubuntu22.04似乎无法多用户使用

### ISSUE THREAD

**Issue by Sherry0010** [clash-verge-rev/clash-verge-rev#1487]
### 问题描述 / Describe the bug

在ubuntu22.04服务器中，一个用户安装并打开了之后，其他用户点击图标无反应。不知道是否有在ubuntu系统上多用户使用的方式。非常感谢回答！

### 复现步骤 / To Reproduce

安装软件的用户推出软件后，另外用户能够打开软件，但无法更新订阅，显示failed to save file "/tmp/clash-verge-check.yaml"

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

ubuntu22.04

### 日志 / Log

07-28 23:54:59INFO
Start initial configuration in progress
07-28 23:54:59INFO
Geodata Loader mode: memconservative
07-28 23:54:59INFO
Geosite Matcher implementation: succinct
07-28 23:54:59INFO
Initial configuration complete, total time: 0ms
07-28 23:54:59INFO
RESTful API listening at: 127.0.0.1:9097
07-28 23:54:59INFO
Sniffer is closed
07-28 23:54:59INFO
Mixed(http+socks) proxy listening at: 127.0.0.1:33799
07-28 23:54:59INFO
Start initial Compatible provider default
![image](https://github.com/user-attachments/assets/55f60bd9-edc3-4883-9813-5afc60cdb843)

**Comment by wonfen** [comment]
限制了单实例运行。
