### ISSUE TITLE
[BUG] 重启clash后，dock栏上的图标消失，并且无法翻墙。

### ISSUE THREAD

**Issue by Raineett** [clash-verge-rev/clash-verge-rev#1489]
### 问题描述 / Describe the bug

在我的mac上，一般情况下，启动clash后，dock栏会出现图标，并且图标下面会有小黑点（说明应用已被打开）。但是在因为clash更新或重启电脑等原因重启clash后，dock栏上的图标会消失，此时无论是规则代理还是全局代理均无法翻墙上网，诸如GitHub、油管等网站均无法反问。
例外地，在我尝试卸载重装后，这次打开clash后dock栏中自始就没有出现过图标，仅在菜单栏显示了图标，此时clash反而可以正常使用，翻墙访问没有出现过问题。
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/b89f67ff-00e4-4b09-a76e-3f354763db95">

### 复现步骤 / To Reproduce

【并非稳定发生】因为clash更新或重启电脑等事由重启clash。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Sonoma 14.5

### 日志 / Log

[2024-07-29-1028.log](https://github.com/user-attachments/files/16407040/2024-07-29-1028.log)

**Comment by wonfen** [comment]
本来就没有dock图标，用顶部图标。

**Comment by yuut2017** [comment]
你解决了吗？我也碰到这样的情况，可以使用但是顶部菜单栏没有监控图标。求解决方法！

**Comment by Raineett** [comment]
> 你解决了吗？我也碰到这样的情况，可以使用但是顶部菜单栏没有监控图标。求解决方法！

我的情况其实和你相反，我是dock栏上没有图标，但是菜单栏上一直都有图标。根据开发者的回复，dock栏上本来就应该没有图标的，所以我这边目前没有什么问题了。
你可以试着发起一个issue，问一下开发者。

**Comment by yuut2017** [comment]
> > 你解决了吗？我也碰到这样的情况，可以使用但是顶部菜单栏没有监控图标。求解决方法！
> 
> 我的情况其实和你相反，我是dock栏上没有图标，但是菜单栏上一直都有图标。根据开发者的回复，dock栏上本来就应该没有图标的，所以我这边目前没有什么问题了。 你可以试着发起一个issue，问一下开发者。

我想是因为我最近使用的应用软件太多导致顶部菜单栏位不够，整理了菜单栏后问题已经解决了，非常感谢！

**Comment by pengweizhong** [comment]
> 本来就没有dock图标，用顶部图标。

怎么屏蔽图标不让其显示呢
