### ISSUE TITLE
[BUG] win10 企业版 19045.3693 无法打开软件面板

### ISSUE THREAD

**Issue by cheneyxx** [clash-verge-rev/clash-verge-rev#149]
### Describe the bug

win10 企业版 19045.3693 无法打开软件面板

### To Reproduce

管理员运行安装也不行 1.4.4 版本也打不开软件面板

### Platform

Windows

### System Version

win10 企业版

### Software Version

1.4.5

**Comment by wonfen** [comment]
看FAQ
https://github.com/clash-verge-rev/clash-verge-rev/issues/125
