### ISSUE TITLE
[BUG] 开启服务模式和TUN模式后，电脑断网

### ISSUE THREAD

**Issue by TonyKingWJX** [clash-verge-rev/clash-verge-rev#1490]
### 问题描述 / Describe the bug

当我开启服务模式和TUN模式后，电脑无网络连接，节点延迟为Error，任何网站都无法访问，Mihomo网卡IPV4显示无internet访问权限。

### 复现步骤 / To Reproduce

关闭系统代理，打开服务模式，打开TUN模式，然后电脑断网。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26120.1330

### 日志 / Log

[2024-07-28-1241.log](https://github.com/user-attachments/files/16407196/2024-07-28-1241.log)

**Comment by Snowflake-Pink** [comment]
Same issue. Some times can be fixed after reboot. It might be reproduced by game accelerator(Xunyou) in my environment.

**Comment by Snowflake-Pink** [comment]
But system proxy can work.

**Comment by xuanyuan0408** [comment]
DNS配置问题
替换，我给的DNS配置试试！
`dns:
 enable: true
 listen: :53
 nameserver:
   - 114.114.114.114
   - 223.5.5.5
 fallback:
   - 8.8.8.8`

**Comment by CNO501** [comment]
#244 这里有暂时的解决方案

**Comment by TonyKingWJX** [comment]
> #244 这里有暂时的解决方案

亲测有用

**Comment by crybest** [comment]
#244 亲测有用，但是问题还是没有解决啊

**Comment by XstormLeigh** [comment]
我真得很好奇你们是如何通过244有用的？！forward我也干了，脚本我也写了，可是根本没啥用啊，TUN还是不好使，开启就断网。

**Comment by TonyKingWJX** [comment]
> 我真得很好奇你们是如何通过244有用的？！forward我也干了，脚本我也写了，可是根本没啥用啊，TUN还是不好使，开启就断网。

首先启用服务模式，然后打开TUN模式，去到控制面板，网络和Internet——网络和共享中心——连接Mihomo——属性——共享，把允许其他网络用户通过此计算机的 Internet 连接来连接(N)勾上，点击确定，然后再打开属性——共享，取消勾选允许其他网络用户通过此计算机的 Internet 连接来连接(N)，确定。这时候TUN模式就正常了，只要电脑不关机都能正常使用，关机了就得重新来一遍就能用了。目前我并未找到彻底解决方法。

**Comment by GuangGu0** [comment]
我这边关闭个人热点就正常了，开热点tun模式全部没网

**Comment by fantasy467** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/244 确实有用，但每次重启都要搞，这问题至今依然没人能解决吗

**Comment by PLUS-WAVE** [comment]
+1，每次都要重新搞很麻烦

**Comment by ghost** [comment]
解决了

![Image](https://github.com/user-attachments/assets/65f96c59-fa3c-4b75-b302-ae727fa4d8b6)

**Comment by ghost** [comment]
> [#244](https://github.com/clash-verge-rev/clash-verge-rev/issues/244) 确实有用，但每次重启都要搞，这问题至今依然没人能解决吗

看我的截图

![Image](https://github.com/user-attachments/assets/ba8daef3-37e2-4765-b49f-d724f2feb652)
改完就解决了

**Comment by TonyKingWJX** [comment]
> > [#244](https://github.com/clash-verge-rev/clash-verge-rev/issues/244) 确实有用，但每次重启都要搞，这问题至今依然没人能解决吗
> 
> 看我的截图
> 
> ![Image](https://github.com/user-attachments/assets/ba8daef3-37e2-4765-b49f-d724f2feb652)改完就解决了

我重新装了一下系统，正常了

**Comment by jack20211101** [comment]
设置一个加密DNS问题解决

**Comment by pibigstar** [comment]
> 设置一个加密DNS问题解决

老哥，怎么搞的？

**Comment by jack20211101** [comment]
> > 设置一个加密DNS问题解决
> 
> 老哥，怎么搞的？

<img width="595" height="919" alt="Image" src="https://github.com/user-attachments/assets/ddea60c1-a419-42c1-86e4-592197739080" />

这是win11 我用的腾讯和阿里的 也可以网上找

**Comment by xiaoweikay** [comment]
我也遇到了  很烦 都没解决问题

**Comment by TonyKingWJX** [comment]
> 我也遇到了 很烦 都没解决问题

首先启用服务模式，然后打开TUN模式，去到控制面板，网络和Internet——网络和共享中心——连接Mihomo——属性——共享，把允许其他网络用户通过此计算机的 Internet 连接来连接(N)勾上，点击确定，然后再打开属性——共享，取消勾选允许其他网络用户通过此计算机的 Internet 连接来连接(N)，确定。这时候TUN模式就正常了，只要电脑不关机都能正常使用，关机了就得重新来一遍就能用了。我重装系统以后就没遇到过了。

**Comment by xiaoweikay** [comment]
> > 我也遇到了 很烦 都没解决问题
> 
> 首先启用服务模式，然后打开TUN模式，去到控制面板，网络和Internet——网络和共享中心——连接Mihomo——属性——共享，把允许其他网络用户通过此计算机的 Internet 连接来连接(N)勾上，点击确定，然后再打开属性——共享，取消勾选允许其他网络用户通过此计算机的 Internet 连接来连接(N)，确定。这时候TUN模式就正常了，只要电脑不关机都能正常使用，关机了就得重新来一遍就能用了。我重装系统以后就没遇到过了。

这个方法确实行 但是治标不治本 每次重启就得弄一次 还是不知道究竟啥原因。。。

**Comment by xiaoweikay** [comment]
> > 我也遇到了很烦没有解决的问题
> 
> 首先启用服务模式，然后打开TUN模式，去控制面板，网络和Internet——网络和共享中心——连接Mihomo——属性——共享，把其他网络用户通过这台计算机的Internet连接来连接(N)勾上，点击确定，然后再打开属性——共享，取消勾选允许其他网络用户通过这台计算机的Internet连接来连接（N），确定。这个时候TUN模式就正常了，只要电脑不关机就不能正常使用，关机了就得重新来一遍就可以用了。我重装系统以后还没遇到过。

https://github.com/clash-verge-rev/clash-verge-rev/issues/2400#issuecomment-2571591961 可以看看这个删除一个东西就行
