### ISSUE TITLE
[BUG] 在MAC下开机自启，有几率不能加载订阅的节点

### ISSUE THREAD

**Issue by Kfkcome** [clash-verge-rev/clash-verge-rev#1492]
### 问题描述 / Describe the bug

在MAC下开机自启，有几率不能加载订阅的节点，并且不能联网，重新选择订阅也不行，必须要重启软件才可以，
![截屏2024-07-29 20 41 36](https://github.com/user-attachments/assets/ab41edf4-20c0-4d91-b264-cb273c159e70)

以前的版本没有这个问题，是最近几个版本才有的

### 复现步骤 / To Reproduce

使用开机自启功能，然后开机后就有几率不能加载订阅的节点![截屏2024-07-29 20 41 36](https://github.com/user-attachments/assets/097d9da1-06a3-4dca-a1f1-3d5053e232c8)

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

MACOS 14.5 (23F79)

### 日志 / Log

如果需要可以提供

**Comment by SilkageNet** [comment]
不仅是mac，windows也会存在这个情况。

**Comment by mike8689** [comment]
tun模式下会这样，是clash内核没有加载 ，要重启clash内核才能用，代理模式我好像没有遇到过， 等待修复bug吧

**Comment by Kfkcome** [comment]
> tun模式下会这样，是clash内核没有加载 ，要重启clash内核才能用，代理模式我好像没有遇到过， 等待修复bug吧

没有，我就是代理模式，没用tun模式

**Comment by SilkageNet** [comment]
> 不仅是mac，windows也会存在这个情况。

感觉是权限问题，我将其从系统盘换到非系统盘就没出现该情况了。
