### ISSUE TITLE
[Feature] 提供开关以禁用/隐藏全局扩展配置、脚本

### ISSUE THREAD

**Issue by ixff** [clash-verge-rev/clash-verge-rev#1493]
### 功能描述 / Feature description

因为之前手搓的配置文件，这部分功能已经靠mihomo提供的字段实现了，所以gui上的功能对于我这种情况就没必要了。

### 使用场景 / Use case

希望能提供一个开关，禁用全局扩展配置、脚本，或者在“订阅”tab中隐藏。

**Comment by junlongzzz** [comment]
全局扩展/脚本配置里面不写内容不就没影响了吗

**Comment by 5iux** [comment]
主题设置-编辑css
`.css-1hw29i9{display: none;}
.css-ku6q14{display: none;}`
