### ISSUE TITLE
[BUG] [UI] Ubuntu 下界面显示适配全局缩放率 200%

### ISSUE THREAD

**Issue by bu2zhouzhu** [clash-verge-rev/clash-verge-rev#1497]
### 问题描述 / Describe the bug

**环境**：
- 27寸4K显示器
- Kubuntu 22.04.4 LTS
- 系统设置 - 显卡与显示器 - 显示器适配，全局缩放率设置为 200%
- sudo dpkg -i clash-verge_1.7.5_amd64.deb

**问题**：
clash-verge 显示效果不好，文字很大，有的地方无法看到完整的文字内容，如图所示：
![image](https://github.com/user-attachments/assets/96e8e3bc-5a80-428e-a3ec-11db9130a6e1)

同样的 200% 全局缩放率下，其它软件的显示都是正常的。下图是与系统文件浏览器Dolphin的对比：
![image](https://github.com/user-attachments/assets/d7720214-9df4-4697-aea1-a0699a340ae3)

### 复现步骤 / To Reproduce

**环境**：
- 27寸4K显示器
- Kubuntu 22.04.4 LTS
- 系统设置 - 显卡与显示器 - 显示器适配，全局缩放率设置为 200%
- sudo dpkg -i clash-verge_1.7.5_amd64.deb
- clash-verge 启动应用，查看界面显示

**期望**：
界面文字尺寸正常，文字没有遮挡、截断，可以看到完整内容

**实际**：
界面文字尺寸过大，部分文字会被截断，无法看到完整内容

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Kubuntu 22.04.4 LTS

### 日志 / Log

NA. UI 问题无需日至。参考问题描述中的截图

**Comment by bu2zhouzhu** [comment]
可能也不算 Bug，算 Feature 吧。4K 显示器应该比较普及了吧，麻烦适配一下。

**Comment by xuanyuan0408** [comment]
没有适配，win7之前也是一样的！谁都不会想到 4k显示器 安装win7😁

**Comment by xuanyuan0408** [comment]
你打开强制系统缩放 试试

**Comment by xuanyuan0408** [comment]
百度 Windows应用系统强制缩放

**Comment by PctAIGM** [comment]
主题设置-编辑css，看能不能调小字体

**Comment by bu2zhouzhu** [comment]
> 主题设置-编辑css，看能不能调小字体

我应该写什么内容呢，我不懂 css..
