### ISSUE TITLE
[BUG] geodata-mode无法启动

### ISSUE THREAD

**Issue by Meonthb** [clash-verge-rev/clash-verge-rev#150]
### Describe the bug

若配置文件中有geodata-mode: ture一行，则无法加载配置文件，错误信息如图所示：
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/60881723/713c9b0b-d47b-4481-b0a0-c5a33878b4c4)
但在旧版clash-verge(1.3.8)中是可以的。

### To Reproduce

无论内核是选择clash meta还是clash meta alpha都会同样报错。

### Platform

Windows

### System Version

23H2 22631.2861

### Software Version

v1.4.5

**Comment by MystiPanda** [comment]
true，不是ture，麻烦把单词拼对
