### ISSUE TITLE
[BUG] WINDOWS任务栏图标一段时间后变模糊

### ISSUE THREAD

**Issue by PeppaTom** [clash-verge-rev/clash-verge-rev#1502]
### 问题描述 / Describe the bug

在WINDOWS平台中， 打开软件后一段时间（大约3-4小时后），任务栏托盘的图标会变得模糊，变暗，如图所示：
![屏幕截图 2024-07-31 005734](https://github.com/user-attachments/assets/3873981b-4f62-4966-9486-0dc3995e144f)

### 复现步骤 / To Reproduce

打开软件后不需要特殊操作，使用一段时间就会出现，且每次必定出现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

WINDOWS10 22H2 19045.4651

### 日志 / Log

[2024-07-30-2008.log](https://github.com/user-attachments/files/16435338/2024-07-30-2008.log)

**Comment by wonfen** [comment]
应该是windows自身缩放的问题，你是不是用了多显示器，每个显示器的DPI都不一样？

**Comment by PeppaTom** [comment]
> 应该是windows自身缩放的问题，你是不是用了多显示器，每个显示器的DPI都不一样？

感谢回复！

我没有用多显示器，只有一个显示器，设置了200%的缩放
