### ISSUE TITLE
[BUG] 电脑重启后节点列表空白，代理功能失效 重启clash verge rev恢复正常

### ISSUE THREAD

**Issue by AkihaZhang** [clash-verge-rev/clash-verge-rev#1504]
解决方案：https://github.com/clash-verge-rev/clash-verge-rev/issues/1504#issuecomment-2277213525
简单说：有老版本没有卸载干净。

### 问题描述 / Describe the bug

[BUG] 电脑重启后节点列表空白，代理功能失效 重启clash verge rev恢复正常
[
![屏幕截图 2024-07-31 114841](https://github.com/user-attachments/assets/561735dd-8f11-41ef-b5fd-11aa837b3a0e)
![屏幕截图 2024-07-31 114834](https://github.com/user-attachments/assets/b04c59c8-d9c2-43f9-9843-2cc2958e2230)
![屏幕截图 2024-07-31 114824](https://github.com/user-attachments/assets/98663579-4bcc-4bde-8951-8c6206719d34)
](url)

### 复现步骤 / To Reproduce

开机自启 开启tun模式 重启有几率出现前面描述的情况 clash verge rev版本1.7.5     mihomo内核版本 1.18.7

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

[2024-07-31-1127.log](https://github.com/user-attachments/files/16436037/2024-07-31-1127.log)

**Comment by xuanyuan0408** [comment]
根据报错，是你本地网络无法拉取配置！可能本地没有配置缓存

**Comment by AkihaZhang** [comment]
> 根据报错，是你本地网络无法获取配置！可能本地没有配置服务器
似乎是内核没有正常启动 刚才翻看其他的issue发现有相同的问题

**Comment by xuanyuan0408** [comment]
换一下 Mihomo Alpha 试试

> > 根据报错，是你本地网络无法获取配置！可能本地没有配置服务器
> > 似乎是内核没有正常启动 刚才翻看其他的issue发现有相同的问题

换一下 Mihomo Alpha 试试

**Comment by AkihaZhang** [comment]
> > > 根据报错，是你本地网络无法获取配置！可能本地没有配置服务器
> > > 好像是内核没有启动正常刚才翻看其他的问题发现有相同的问题
> 
> 换一下 Mihomo Alpha 看看

已经换了 尝试重启暂时正常 不过这是偶发性故障 不能100%复现

**Comment by xuanyuan0408** [comment]
> > > > 根据报错，是你本地网络无法获取配置！可能本地没有配置服务器
> > > > 好像是内核没有启动正常刚才翻看其他的问题发现有相同的问题
> > 
> > 
> > 换一下 Mihomo Alpha 看看
> 
> 已经换了 尝试重启暂时正常 不过这是偶发性故障 不能100%复现

我猜应该是后台内核没有关闭干净，你可以试试！毕竟gui调用 gui关了 内核还是开启的！

**Comment by AkihaZhang** [comment]
> > > > > 根据报错，是你本地网络无法获取配置！可能本地没有配置服务器
> > > > > 好像是内核没有启动正常刚才翻看其他的问题发现有相同的问题
> > > 
> > > 
> > > 换一下 Mihomo Alpha 看看
> > 
> > 
> > 已经换了 尝试重启暂时正常 不过这是偶发性故障 不能100%复现
> 
> 我猜应该是后台内核没有关闭干净，你可以试试！毕竟gui调用 gui关了 内核还是开启的！

只有Windows开机会出现这种情况平时使用不会

**Comment by xuanyuan0408** [comment]
> > > > > > 根据报错，是你本地网络无法获取配置！可能本地没有配置服务器
> > > > > > 好像是内核没有启动正常刚才翻看其他的问题发现有相同的问题
> > > > 
> > > > 
> > > > 换一下 Mihomo Alpha 看看
> > > 
> > > 
> > > 已经换了 尝试重启暂时正常 不过这是偶发性故障 不能100%复现
> > 
> > 
> > 我猜应该是后台内核没有关闭干净，你可以试试！毕竟gui调用 gui关了 内核还是开启的！
> 
> 只有Windows开机会出现这种情况平时使用不会

这样啊！可能是阶段性的bug！那就不是gui问题了！

**Comment by maxoyed** [comment]
我也有这个问题

**Comment by mike8689** [comment]
tun模式下会这样，是clash内核没有加载 ，要重启clash内核才能用，代理模式我好像没有遇到过， 等待修复bug吧

**Comment by qxbug** [comment]
自从上次更新后就有这个问题，我设置的开机自启，更新完上个版本以后，开机自启都是加载不了配置，都得重启软件

**Comment by JackloveJam** [comment]
还有一种可能，多版本共存导致的。我亲自遇到过。
之前一个版本提示过，新版本会自动安装到C盘，而之前自己安装的目录和自动安装的目录不一致。
并且开机自启的那个版本不是桌面图标对应路径的版本。
简单来说，就是 早些时候自己手动下载安装了一个旧版本，在安装新版本后，旧版本没有卸载清理，导致开机后运行的软件版本不是桌面图标较新版本。

这个时候任务管理器杀掉程序，再从桌面图标打开时就看到有订阅节点的版本了。

**Comment by sidpku** [comment]
我发现每次电脑开机的时候，打开clash verge都会出现clash内核为-的情况，但在任务管理器中有运行。在任务管理器中将内核杀掉，内核就能重启，clash verge才能正常使用

**Comment by hijos** [comment]
我也会遇到这个问题，不过不是开机重启后，是我前一天晚上睡觉了把电脑设置为睡眠，第二天早上起床后就会出现节点列表空白，然后由于我开启了“局域网连接”功能，手机也上不了网。于是我每天早上都需要手动点一下“重启Clash”。

**Comment by JackloveJam** [comment]
> 我也会遇到这个问题，不过不是开机重启后，是我前一天晚上睡觉了把电脑设置为睡眠，第二天早上起床后就会出现节点列表空白，然后由于我开启了“局域网连接”功能，手机也上不了网。 于是我每天早上都需要手动点一下“重启Clash”。 最近连着几个版本都存在这个问题，包括最新版。

那还不如搞到路由器里 😂

**Comment by hijos** [comment]
> > 我也会遇到这个问题，不过不是开机重启后，是我前一天晚上睡觉了把电脑设置为睡眠，第二天早上起床后就会出现节点列表空白，然后由于我开启了“局域网连接”功能，手机也上不了网。 于是我每天早上都需要手动点一下“重启Clash”。 最近连着几个版本都存在这个问题，包括最新版。
> 
> 那还不如搞到路由器里 😂

没研究过软路由，暂时也懒得搞

**Comment by styshoo** [comment]
![err](https://github.com/user-attachments/assets/53219a62-0de2-43ec-aed9-84a5ea7f8305)
[2024-08-30-1634.log](https://github.com/user-attachments/files/16814451/2024-08-30-1634.log)
一样，尝试去激活订阅，就会报文件不存在。

**Comment by elefly** [comment]
一样的问题，有一定概率内核不会自己启动，设置界面里面“Clash内核”那一项是空白的，需要手动选择内核才可以使用

**Comment by styshoo** [comment]
把订阅的配置删除后，再重新添加订阅，竟然就修复了。有一点神奇，有相同问题的可以试一试。

> ![err](https://private-user-images.githubusercontent.com/11631265/363107985-53219a62-0de2-43ec-aed9-84a5ea7f8305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTI3NjMsIm5iZiI6MTcyNTYxMjQ2MywicGF0aCI6Ii8xMTYzMTI2NS8zNjMxMDc5ODUtNTMyMTlhNjItMGRlMi00M2VjLWFlZDktODRhNWVhN2Y4MzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA4NDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYWM0YTZiNzFjNzcxZWU4MGZiYzdjMjVmMDVhNmY4NGE0ZDIzODRjM2Y2OWYxOTIxMDVlZjE3ZmRhZDExZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eUMkWuLl6SqSm7HlNKucF-HxQFLNk237y80hPr_3n7A) [2024-08-30-1634.log](https://github.com/user-attachments/files/16814451/2024-08-30-1634.log) 一样，尝试去激活订阅，就会报文件不存在。

**Comment by gubei404** [comment]
我也是有这样的问题，还有
yaml:unmarshal errors:\n line 1268:cannot unmarshal !!seq intomap[string]map[string]interface
这个报错

**Comment by PingZi-Wing** [comment]
麻了，折腾半天，今天我重启也遇到这个问题了。内核首次能启动代理，但退出重开就显示“-”了，点重启clash也没用。老版本应该卸载干净的，卸载完成后我特意用everything搜索clash、mihomo清理下的，没啥用。先转去用Flclash

**Comment by gubei404** [comment]
> 麻了，折腾半天，今天我重启也遇到这个问题了。内核首次能启动代理，但退出重开就显示“-”了，点重启clash也没用。老版本应该卸载干净的，卸载完成后我特意用everything搜索clash、mihomo清理下的，没啥用。先转去用Flclash

我也是你这个问题，重启了两遍玄学解决了

**Comment by yixiuge301** [comment]
现象一样，不过我这单纯是卡了。。。过一会就好，这软件性能确实有提升空间。

笔记本是 i5-8265U、512 nvme、16G、win10

**Comment by hijos** [comment]
> 破案了，关闭Windows防火墙后立马就好了。

请问具体如何关闭？

**Comment by CXZS-Git** [comment]
我这边遇到了类似的问题，现已解决。不能保证对所有类似情况都生效，但有尝试的价值。

### 环境
笔记本电脑搭载 Windows11 Pro Build 22631，笔记本同时通过无线网卡和 USB 连接的 Android 上网，按照路由表，优先使用 USB 连接上网。

### 问题症状
- Clash启动后节点列表空白，对设置中的“Clash”小节进行改动时右上角提示“error sending request for url http://127.0.0.1:9097/configs”。
- 清空配置文件甚至重新安装Clash都无法解决，同时，其他类似客户端也无法运行，报错是“configure tun interface : Access is denied”。
- 打开控制面板的网络和共享中心页面极度缓慢，几乎不可用。

### 解决方法
使用管理员权限打开CMD，执行“netsh winsock reset”，然后根据提示重启电脑。

### 其他
Windows防火墙放行或直接关闭也可以尝试一下，我是在尝试关闭防火墙之后用“netstat -nao | findstr 9097”命令发现内核并没有监听这个端口才想到重置winsock。
9097是设置里“Clash Setting”小节的“External”设定的控制端口。

**Comment by avalon-plan** [comment]
估计是电脑少了“edge Webview2 Runtime”Win10出现这个问题可以看下 MicrosoftEdgeWebView2RuntimeInstallerX64这个应用安装了没，百度单独下载一个就解决
