### ISSUE TITLE
[Feature] 请从`rule-providers`添加对`.mrs`格式的支持

### ISSUE THREAD

**Issue by kingsmanvn1x32** [clash-verge-rev/clash-verge-rev#1510]
### 功能描述 / Feature description

请从`rule-providers`添加对`.mrs`格式的支持

### 使用场景 / Use case

请从`rule-providers`添加对`.mrs`格式的支持
![Screenshot_2024-08-01-18-42-28-502_com foxdebug acode-edit](https://github.com/user-attachments/assets/bfdea037-ff75-4f6c-bcbf-bedb7f4633f8)

**Comment by xishang0128** [comment]
![Uploading image.png…]()
