### ISSUE TITLE
[BUG] install-service 在openrc下不能用, Install-service doesn't work under openrc

### ISSUE THREAD

**Issue by felis-zhu** [clash-verge-rev/clash-verge-rev#1513]
### 问题描述 / Describe the bug

Install-service doesn't work under openrc, since it uses systemctl commands which doesn't work under openrc

### 复现步骤 / To Reproduce

Use artix linux and install the package, then run the install-service and observe

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Artix Linux

### 日志 / Log

thread 'main' panicked at src/install.rs:98:10
Failed to execute 'systemctl status' command.: 0s { code: 2, kind: NotFound, message: "No such file or directory"}

**Comment by wonfen** [comment]
试试最新2.0 rc6版，应该已经修复了。如果还不行请开新issue 。
