### ISSUE TITLE
请问 编辑节点是干嘛的，机场里有1倍率2倍率，我想让自动选择只选1倍率里最快的，这样怎么实现啊

### ISSUE THREAD

**Issue by flylj999** [clash-verge-rev/clash-verge-rev#1515]
### 功能描述 / Feature description

是在编辑节点功能里吗，我看左边有前置后置 还有添加url，不明白都是干嘛的

### 使用场景 / Use case

是在编辑节点功能里吗，我看左边有前置后置 还有添加url，不明白都是干嘛的

**Comment by infrost** [comment]
首先倍率这个计费方式不是所有机场都提供的，项目不会提供这个功能的实现。
但是clash提供了外部控制器的api，你可以通过编程实现。
思路如下，
获取所有的节点，以及延迟，存放在一个`延迟表`中。每隔n分钟刷新这个表，刷新表后从表中读取延迟最低的节点且含有"1x"字样的，切换。

**Comment by asda88chen** [comment]
我也想要有这样的 请问能实现吗

**Comment by 4SM** [comment]
更新订阅的时候排除2倍率。但不知道怎么写？以前 clash for windows 很简单，现在看了官方文档都不会写。

**Comment by infrost** [comment]
看到很多人有这个需求，拿我以前的代码改了一改实现了一下，提供打包好的`.exe`文件
具体的代码有非常详细的注释，可以作为官方api用例的补充实践以供参考。
有问题来我项目里提issue，喜欢可以点个star

[ClashAutoNode项目地址](https://github.com/infrost/ClashAutoNode)

![Image](https://github.com/user-attachments/assets/177a0e9a-fb19-4c1a-b9f2-b5ec1fed6ff1)
