### ISSUE TITLE
[BUG] base64 的订阅链接不能直接导入么？

### ISSUE THREAD

**Issue by yixiuge301** [clash-verge-rev/clash-verge-rev#1518]
### 问题描述 / Describe the bug

base64 不能用么？

![image](https://github.com/user-attachments/assets/80284cda-91c9-4fba-9812-3ce12c6a09f2)

![image](https://github.com/user-attachments/assets/fc3979b1-114b-4e06-a939-ee692f1ab54d)

浏览器是可以打开这个订阅链接的，base64 解码后，用订阅转换转为可读的 yaml 文件，就可以了。

### 复现步骤 / To Reproduce

复制机场订阅链接，cvr 导入订阅链接

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

请求失败
![image](https://github.com/user-attachments/assets/b5141c23-b4a6-494c-b66b-7c9685260f5e)

**Comment by wonfen** [comment]
你这个是机场连接挂了

**Comment by yixiuge301** [comment]
> 你这个是机场连接挂了

订阅链接浏览器可以打开，什么原因呢

**Comment by yixiuge301** [comment]
【导入】应该是没走代理。使用新建，打开内核代理更新可以。
![image](https://github.com/user-attachments/assets/defb52db-e0b1-40e0-931b-4f3acc1f57a0)

**Comment by yixiuge301** [comment]
找了个机场
```http
https://cloudfox.club/api/v1/client/subscribe?token=c54c0b8aed7840860b647976147a2648
```
clash-verge-rev app
![image](https://github.com/user-attachments/assets/fe8f09de-d810-4a46-b5b3-358a87115fbb)
edge
![image](https://github.com/user-attachments/assets/c2db3063-b4ed-47ac-b306-028daed8a652)

**Comment by daitou05** [comment]
应用应该是走的直连，没走 mihomo 内核。

@wonfen 方便找时间看看？是走直连的，还是建议走代理
