### ISSUE TITLE
[BUG] “订阅”--右击某项--打开文件，毫无反应。

### ISSUE THREAD

**Issue by HarlockHomes** [clash-verge-rev/clash-verge-rev#1519]
### 问题描述 / Describe the bug

Windows 10,11,server 2019
windows系统里文件类型里 .yaml 已经关联 Emeditor 文本文件编辑器。
![image](https://github.com/user-attachments/assets/4ac91c15-402f-4fe7-a65b-19ab047c114f)
![image](https://github.com/user-attachments/assets/b1833929-729e-49d9-b1fe-e410df1c0d20)

### 复现步骤 / To Reproduce

“订阅”--右击某项--打开文件，毫无反应。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10，11，2019

### 日志 / Log

无

**Comment by xuanyuan0408** [comment]
改成记事本打开 试试

**Comment by HarlockHomes** [comment]
已解决，
之前用clash，yml文件没有此故障。这次却需要在Emeditor里新建文件关联。如图：
![image](https://github.com/user-attachments/assets/6a969a77-df63-419c-81f6-e01574fe57ea)

**Comment by HarlockHomes** [comment]
> 改成记事本打开 试试

试过关联成 notepad 和 notepad ++ 都是正常的。
