### ISSUE TITLE
[BUG] Windows create profile error

### ISSUE THREAD

**Issue by sgrtye** [clash-verge-rev/clash-verge-rev#152]
### Describe the bug

When creating a new profile using the subscription URL, the system prompts for an update interval in minutes; however, this information is not retained and requires resetting with each profile.

### To Reproduce

1. Create a new remote profile
2. Set subscription URL and update interval
3. Check if the update interval is correctly stored

### Platform

Windows

### System Version

Windows 11

### Software Version

Latest

**Comment by wonfen** [comment]
正常的，每个Profile是需要分别设置更新时间。

**Comment by sgrtye** [comment]
> 正常的，每个Profile是需要分别设置更新时间。

@wonfen 我意思是 在创建profile的时候填写了更新时间 但是没有保存上 只能重新添加

**Comment by MystiPanda** [comment]
确实存在问题

**Comment by sgrtye** [comment]
在新版本中这个问题似乎已经被解决了。
