### ISSUE TITLE
[BUG] clash退出后service程序不会关闭

### ISSUE THREAD

**Issue by EnderAvaritia** [clash-verge-rev/clash-verge-rev#1520]
### 问题描述 / Describe the bug

我也不知道这是干啥用的，更新的时候退出clash，然后发现它不会关闭
![图片](https://github.com/user-attachments/assets/44ddcf04-456f-4d6c-9760-684b82ba0ab8)

### 复现步骤 / To Reproduce

右键菜单，退出clash

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10 22H2

### 日志 / Log

不知道怎么保存这种日志

**Comment by wonfen** [comment]
服务模式当然会保持运行，不然怎么叫“服务”？
