### ISSUE TITLE
[BUG] 订阅自动更新失败

### ISSUE THREAD

**Issue by blackappleD** [clash-verge-rev/clash-verge-rev#1521]
### 问题描述 / Describe the bug

1. 订阅自动更新失败（偶现）
2. 订阅更新成功，但是proxies字段数组为空，不知道是节点列表加载失败了，还是网络原因没有获取到这部分数据？
3. 更新成功，节点列表加载成功，但几分钟过后，节点列表全部消失；

### 复现步骤 / To Reproduce

1. 如图设置更新间隔
![image](https://github.com/user-attachments/assets/43fbef95-2801-4553-ba89-93c6d3e1fd4e)
2. 等待自动更新，此时会有问题描述中的三种情况（截图是第三种情况）：
   ①偶现的订阅更新失败（此订阅连接直连可以访问）
   ②订阅更新成功，但是proxies字段数组为空
   ③节点更新成功，几分钟后节点列表消失：
![image](https://github.com/user-attachments/assets/3ed3be77-f205-43cb-a89f-e0ebcf5bbb2f)
![image](https://github.com/user-attachments/assets/e1d166a5-c0a0-4a15-8145-05021c34b4a7)
![image](https://github.com/user-attachments/assets/a05f981b-8726-4484-b4c3-f4ba6e385098)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

[2024-08-05-0821.log](https://github.com/user-attachments/files/16491905/2024-08-05-0821.log)

**Comment by wonfen** [comment]
这个是机场订阅不稳定导致的，为显示空的时候机场配置文件下发的内容为空。

订阅都做不好的机场还是别用了。

**Comment by blackappleD** [comment]
> 这个是机场订阅不稳定导致的，为显示空的时候机场配置文件下发的内容为空。
> 
> 订阅都做不好的机场还是别用了。

你好 请问1.7.7版本是不是解决这个问题了？

**Comment by blackappleD** [comment]
> 这个是机场订阅不稳定导致的，为显示空的时候机场配置文件下发的内容为空。
> 
> 订阅都做不好的机场还是别用了。

主要是我在机场群里问过这个问题，有一些情况跟我一样，他们都是使用clashverge的，一部分用v2ray貌似没有问题....

**Comment by wonfen** [comment]
> > 这个是机场订阅不稳定导致的，为显示空的时候机场配置文件下发的内容为空。
> > 订阅都做不好的机场还是别用了。
> 
> 主要是我在机场群里问过这个问题，有一些情况跟我一样，他们都是使用clashverge的，一部分用v2ray貌似没有问题....

这句话听不懂？这个是机场订阅不稳定导致的，为显示空的时候机场配置文件下发的内容为空。
v2ray用的又不是clash的配置文件，机场会根据你的软件下发不同的配置。

用clash的时候，下发失败
用v2ray的时候，下发成功

订阅都做不好的机场还是别用了。

**Comment by blackappleD** [comment]
> > > 这个是机场订阅不稳定导致的，为显示空的时候机场配置文件下发的内容为空。
> > > 订阅都做不好的机场还是别用了。
> > 
> > 
> > 主要是我在机场群里问过这个问题，有一些情况跟我一样，他们都是使用clashverge的，一部分用v2ray貌似没有问题....
> 
> 这句话听不懂？这个是机场订阅不稳定导致的，为显示空的时候机场配置文件下发的内容为空。 v2ray用的又不是clash的配置文件，机场会根据你的软件下发不同的配置。
> 
> 用clash的时候，下发失败 用v2ray的时候，下发成功
> 
> 订阅都做不好的机场还是别用了。

哟 脾气这么大？升级1.7.7就没问题了呢 ，那不就是软件问题么? 看看1.7.7 修复日志写的什么？真不知道有什么好犟的 服了
![image](https://github.com/user-attachments/assets/65e0cb96-9dce-4169-8aee-ed15d63a7889)

**Comment by wonfen** [comment]
> > > > 这个是机场订阅不稳定导致的，为显示空的时候机场配置文件下发的内容为空。
> > > > 订阅都做不好的机场还是别用了。
> > > 
> > > 
> > > 主要是我在机场群里问过这个问题，有一些情况跟我一样，他们都是使用clashverge的，一部分用v2ray貌似没有问题....
> > 
> > 
> > 这句话听不懂？这个是机场订阅不稳定导致的，为显示空的时候机场配置文件下发的内容为空。 v2ray用的又不是clash的配置文件，机场会根据你的软件下发不同的配置。
> > 用clash的时候，下发失败 用v2ray的时候，下发成功
> > 订阅都做不好的机场还是别用了。
> 
> 哟 脾气这么大？升级1.7.7就没问题了呢 ，那不就是软件问题么? 看看1.7.7 修复日志写的什么？真不知道有什么好犟的 服了 ![image](https://private-user-images.githubusercontent.com/36764324/363820718-65e0cb96-9dce-4169-8aee-ed15d63a7889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzEwNjgsIm5iZiI6MTcyNTMzMDc2OCwicGF0aCI6Ii8zNjc2NDMyNC8zNjM4MjA3MTgtNjVlMGNiOTYtOWRjZS00MTY5LThhZWUtZWQxNWQ2M2E3ODg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAyMzI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMTY3ODg1ZWFjODUzNzU0NjM2M2NkMTg4N2VmNDFmZDM2NmEwMTk1ZDNhYjhiYTA2YjBlOWIwNGEyOWM1YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HbON5bi9Y3ckDLaPv2kDZZQshOurzcRV-WPMzaDchuE)

1.7.7修复的内容和你的这个问题无关；你可以再观察一下，如果下次还出现没有节点的情况，可以编辑订阅，看看里面有没有内容。

**Comment by blackappleD** [comment]
> > > > > 这个是机场订阅不稳定导致的，为显示空的时候机场配置文件下发的内容为空。
> > > > > 订阅都做不好的机场还是别用了。
> > > > 
> > > > 
> > > > 主要是我在机场群里问过这个问题，有一些情况跟我一样，他们都是使用clashverge的，一部分用v2ray貌似没有问题....
> > > 
> > > 
> > > 这句话听不懂？这个是机场订阅不稳定导致的，为显示空的时候机场配置文件下发的内容为空。 v2ray用的又不是clash的配置文件，机场会根据你的软件下发不同的配置。
> > > 用clash的时候，下发失败 用v2ray的时候，下发成功
> > > 订阅都做不好的机场还是别用了。
> > 
> > 
> > 哟 脾气这么大？升级1.7.7就没问题了呢 ，那不就是软件问题么? 看看1.7.7 修复日志写的什么？真不知道有什么好犟的 服了 ![image](https://private-user-images.githubusercontent.com/36764324/363820718-65e0cb96-9dce-4169-8aee-ed15d63a7889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzEwNjgsIm5iZiI6MTcyNTMzMDc2OCwicGF0aCI6Ii8zNjc2NDMyNC8zNjM4MjA3MTgtNjVlMGNiOTYtOWRjZS00MTY5LThhZWUtZWQxNWQ2M2E3ODg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAyMzI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMTY3ODg1ZWFjODUzNzU0NjM2M2NkMTg4N2VmNDFmZDM2NmEwMTk1ZDNhYjhiYTA2YjBlOWIwNGEyOWM1YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HbON5bi9Y3ckDLaPv2kDZZQshOurzcRV-WPMzaDchuE)
> 
> 1.7.7修复的内容和你的这个问题无关；你可以再观察一下，如果下次还出现没有节点的情况，可以编辑订阅，看看里面有没有内容。

好的，感谢回答
