### ISSUE TITLE
[BUG] 安装服务模式提示failed to install service with status 1

### ISSUE THREAD

**Issue by sbzhaopeng** [clash-verge-rev/clash-verge-rev#1522]
### 问题描述 / Describe the bug

已尝试管理员模式运行uninstall-service，再管理员模式运行install-service。管理员模式运行uninstall-service和install-service均闪退。注册表的clash-verge-service路径正确。尝试过卸载重新安装，仍未解决。

### 复现步骤 / To Reproduce

已尝试管理员模式运行uninstall-service，再管理员模式运行install-service。管理员模式运行uninstall-service和install-service均闪退。注册表的clash-verge-service路径正确。尝试过卸载重新安装，仍未解决。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 22631.3880

### 日志 / Log

2024-08-05 15:42:14 ERROR - failed to connect to the Clash Verge Service
2024-08-05 15:42:14 ERROR - failed to install service with status 1
2024-08-05 15:42:17 ERROR - failed to connect to the Clash Verge Service
2024-08-05 15:42:34 ERROR - failed to install service with status 1
2024-08-05 15:42:36 ERROR - failed to connect to the Clash Verge Service
2024-08-05 15:42:37 ERROR - failed to connect to the Clash Verge Service
2024-08-05 15:42:41 ERROR - failed to connect to the Clash Verge Service

**Comment by xuanyuan0408** [comment]
查看教程手册 谢谢

**Comment by sbzhaopeng** [comment]
> 查看教程手册 谢谢

到 内核目录 中找到 uninstall-service.exe，以管理员权限执行。

这个操作已经试过了。

**Comment by xuanyuan0408** [comment]
那就使用 geek 强制删除，再重新安装！

**Comment by sbzhaopeng** [comment]
> 那就使用 geek 强制删除，再重新安装！

依旧不行，同样的错误提示

**Comment by sbzhaopeng** [comment]
![屏幕截图 2024-08-06 154234](https://github.com/user-attachments/assets/9cdf986e-e1a9-4f6d-a618-cec55049a8a4)
服务列表中有Clash Verge Service，可执行文件的路径正确指向\resources\clash-verge-service.exe。但是服务模式仍提示未安装

**Comment by touchsky-real** [comment]
我也是这个问题，重装电脑后再重新安装clash就说无法安装服务

**Comment by touchsky-real** [comment]
> 我也是这个问题，重装电脑后再重新安装clash就说无法安装服务

试了几次后，开机发现clash服务模式已经安装好了

**Comment by levy258** [comment]
run     \Clash Verge\resources\install-service.exe

**Comment by vonaxs** [comment]
哈喽，我遇到了这个问题。弄了很久
最后是右键exe，选择“以管理员身份运行”。 解决问题

**Comment by Syzblue** [comment]
我现在也有同样的问题

**Comment by sunheyi6** [comment]
> 我现在也有同样的问题

我是重复安装几次不知道怎么就好了 有点神奇

**Comment by longxiaotian799** [comment]
> 哈喽，我遇到了这个问题。弄了很久 最后是右键exe，选择“以管理员身份运行”。 解决问题

对的这样就行，谢谢

**Comment by MagicalAstrogy** [comment]
报错 `IPC Path not ready` 同样可以通过 uninstall 方式解决。

**Comment by SakuraLoveForever** [comment]
> 哈喽，我遇到了这个问题。弄了很久 最后是右键exe，选择“以管理员身份运行”。 解决问题

确实这样就解决了
