### ISSUE TITLE
[BUG] 无法安装，提示无法终止

### ISSUE THREAD

**Issue by vansto** [clash-verge-rev/clash-verge-rev#1524]
### 问题描述 / Describe the bug

无法安装，提示无法终止

### 复现步骤 / To Reproduce

运行1.7.5_x64安装包

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

21H2

### 日志 / Log

<img width="374" alt="PixPin_2024-08-06_04-05-20" src="https://github.com/user-attachments/assets/44f84347-d8f0-4b9a-b984-7bed71eda395">

**Comment by wonfen** [comment]
重启电脑，卸载老版本再安装试试。
