### ISSUE TITLE
[BUG] 死循环请求单个节点 (当开启 mobile hotspot热点)

### ISSUE THREAD

**Issue by lovitus** [clash-verge-rev/clash-verge-rev#1525]
### 问题描述 / Describe the bug

当win10开启 移动热点以后, 会死循环请求某个随机节点, 
截图的 8866为一个节点, 实际是只要开热点,就会爆刷类似的日志,但是节点不是固定的.
![image](https://github.com/user-attachments/assets/ecc4e050-415a-4985-bbf0-9bb4ee4a6575)

### 复现步骤 / To Reproduce

![image](https://github.com/user-attachments/assets/59b0e0d7-44a5-4c4f-b2ae-320b52a80f1f)
![image](https://github.com/user-attachments/assets/b902f68e-3536-4391-ac70-32faddb2250a)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10 22H2

### 日志 / Log

截图上面已经提供. 
只要是电脑开热点, 不管是否有设备连接, 都会死循环. 网络异常和部分无法访问. 电脑风扇起飞.
可能是上游问题, 希望 clash verge rev的开发者们能够帮忙. 谢谢

**Comment by lovitus** [comment]
mimoho用的是最新的内核, 一分钟前刚更新, 问题也是一样的

**Comment by wonfen** [comment]
这个问题建议到内核那边反馈下，没看懂是为什么

**Comment by lovitus** [comment]
> 这个问题建议到内核那边反馈下，没看懂是为什么

上游开发者好像没那么友好。
但是感谢你的回复。谢谢
