### ISSUE TITLE
[BUG]切换配置文件可能会导致cpu异常

### ISSUE THREAD

**Issue by limitwhy** [clash-verge-rev/clash-verge-rev#153]
### Describe the bug

切换不同的配置文件可能会导致cpu异常

### To Reproduce

tun模式下切换不同的配置文件

### Platform

Windows

### System Version

w11

### Software Version

1.4.5

**Comment by wonfen** [comment]
cpu什么异常？

**Comment by MystiPanda** [comment]
你还在这说的理所当然的，你issue里面说了吗？

**Comment by wonfen** [comment]
建议还是升级下CPU。无从排查。
