### ISSUE TITLE
[BUG] Mac os安装服务模式输入密码时报错

### ISSUE THREAD

**Issue by lengf233** [clash-verge-rev/clash-verge-rev#1535]
### 问题描述 / Describe the bug

Mac os安装服务模式输入密码时报错

### 复现步骤 / To Reproduce

1、点击安装
<img width="800" alt="image" src="https://github.com/user-attachments/assets/e2f27c58-06c4-4bc7-8e84-08684954f2fa">
2、输入密码：asdfghjkl;'
3、显示报错
<img width="800" alt="image" src="https://github.com/user-attachments/assets/b06d6d18-199e-4631-95d0-c9f5a39af722">

会不会是单引号导致的问题呢？没有做转意处理

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5 (23F79)

### 日志 / Log

2024-08-08 16:06:12 ERROR - failed to install service with error: Password:Sorry, try again.
Password:
sudo: no password was provided
sudo: 1 incorrect password attempt

2024-08-08 16:06:12 ERROR - failed to connect to the Clash Verge Service
2024-08-08 16:06:14 ERROR - failed to connect to the Clash Verge Service
2024-08-08 16:06:18 ERROR - failed to install service with error: bash: -c: line 0: unexpected EOF while looking for matching `''
bash: -c: line 1: syntax error: unexpected end of file

2024-08-08 16:06:18 ERROR - failed to connect to the Clash Verge Service
2024-08-08 16:06:20 ERROR - failed to connect to the Clash Verge Service

**Comment by lengf233** [comment]
好的谢谢，我更改密码已经解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月8日(周四) 下午5:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [clash-verge-rev/clash-verge-rev] [BUG] Mac os安装服务模式输入密码时报错 (Issue #1535)




 
试试 终端输入
 
sudo clash-verge --service install

**Comment by xuanyuan0408** [comment]
> 好的谢谢，我更改密码已经解决了
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2024年8月8日(周四) 下午5:14
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [clash-verge-rev/clash-verge-rev] [BUG] Mac os安装服务模式输入密码时报错 (Issue #1535)
> 
> 
> 
> 
>  
> 试试 终端输入
>  
> sudo clash-verge --service install
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可能是有特殊字符！

**Comment by wonfen** [comment]
使用最新的alpha版本已经修复了这个问题

**Comment by Thesoul20** [comment]
> 使用最新的alpha版本已经修复了这个问题

在Linux arm64 下，即使密码输入正确，也同样安装不了服务模式。

输入密码后会提示安装成功：
![image](https://github.com/user-attachments/assets/ef670844-5f74-40b9-b4df-eb9042b2f797)

之后开启Tun模式时又会提示没有安装成功：
![image](https://github.com/user-attachments/assets/df50d6e8-96d4-4a83-86bd-4419fac08d3e)
