### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by cdxiaodong** [clash-verge-rev/clash-verge-rev#1537]
### 功能描述 / Feature description

只能监听127.0.0.1 7890吗 什么时候支持监听0.0.0.0 7890

### 使用场景 / Use case

只能监听127.0.0.1 7890吗 什么时候支持监听0.0.0.0 7890

**Comment by xuanyuan0408** [comment]
配置加这行到配置文件中

`bind-address: '*'`

**Comment by cdxiaodong** [comment]
谢谢
