### ISSUE TITLE
[Feature] 测试功能中的图标和名称支持自动填写

### ISSUE THREAD

**Issue by qixing-jk** [clash-verge-rev/clash-verge-rev#1539]
## 名称自动填写
可直接使用测试链接的域名部分或者域名部分的二级域名，如www.baidu.com直接使用baidu的部分

## 图标自动获取
使用 **图标API** 的形式自动获取，内置或者让用户自定义图标API
如：
https://www.apple.com/favicon.ico （网站一般的图标位置）
https://api.faviconkit.com/google.com
https://icons.duckduckgo.com/ip3/google.com.ico
从 **测试地址** 到 **图标API的图标链接** 执行自动转换，即可自动获取拿到网站图标

ps：
- 可能还是内置转换规则比较容易，用户自定义编写，比较容易实现的方式也只有正则替换吧 https://icons.duckduckgo.com/ip3/google.com.ico 比如转换到这种图标链接
- 希望支持多图标地址都进行尝试获取，使用获取的到的，因为不是每个图标API都能正确获取到网站图标

### 使用场景 / Use case

这样网站测试就可以快速添加，只需要添加必须的网站测试链接就好了，而不需要去找网站图标地址和填写名称

**Comment by wonfen** [comment]
实现成本太高，收益小，增加软件复杂性，不准备实现。
