### ISSUE TITLE
[Feature] 希望可以增加状态栏网速显示

### ISSUE THREAD

**Issue by goxq** [clash-verge-rev/clash-verge-rev#154]
### Is your feature request related to a problem? Please describe.

增加状态栏网速显示

### Describe the solution you'd like

增加状态栏网速显示

### Describe alternatives you've considered

增加状态栏网速显示

**Comment by wonfen** [comment]
有的啊，左下角。

**Comment by goxq** [comment]
@wonfen 有吗？Mac版，左下角？

**Comment by moranno** [comment]
这个：
<img width="736" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/77610980/ee43b106-2f17-4aa7-9927-8a356718adbd">

**Comment by wonfen** [comment]
这个：
<img width="736" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/96291150/591f2381-a5d2-4e82-b740-a6150b5d48f8">

**Comment by goxq** [comment]
@wonfen 这个不是在状态栏呀

**Comment by sgricky** [comment]
同求状态栏网速显示（可参考CfWindows）。

**Comment by creaplus** [comment]
![企业微信截图_2b01a7e1-d185-4db2-86dd-74d25e4e1297](https://github.com/clash-verge-rev/clash-verge-rev/assets/17270460/f98fbdb1-83c0-412f-b5b9-11651fbfab5b)
类似右边这个

**Comment by chalme** [comment]
@goxq @creaplus @sgricky 
自行装相关软件就可以了。 istat 可以支持，对于mac

**Comment by goxq** [comment]
> @goxq @creaplus @sgricky 自行装相关软件就可以了。 istat 可以支持，对于mac

确实，感谢。
