### ISSUE TITLE
[BUG] 偶现代理中断，节点全空，提示版本更新，更新后正常（更新版本相同）。

### ISSUE THREAD

**Issue by unever** [clash-verge-rev/clash-verge-rev#1540]
### 问题描述 / Describe the bug

如题，偶尔会出现代理中断，查看Clash Verge，节点全空，此时提示版本更新，更新后正常。当前版本1.7.5版本，已经遇到了3次，都是提示更新1.7.5，更新后正常。

### 复现步骤 / To Reproduce

无法稳定复现，正常使用过程中偶尔就突然发生。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

日志目前是正常的，如果需要下次出问题时会留意保存日志。

**Comment by wonfen** [comment]
检查是否启动了多个内核进程；建议删除老版本重新安装。
