### ISSUE TITLE
[BUG] 多个网卡连接至同一个网络，同时开启tun模式，隔十几秒就会出现间接性的断流

### ISSUE THREAD

**Issue by jcfun** [clash-verge-rev/clash-verge-rev#1542]
### 问题描述 / Describe the bug

多个网卡连接至同一个网络（例如同时使用网线和Wi-Fi、连接两根网线、两个无线网卡连接两个Wi-Fi等情况），如果这时开启tun模式，电脑就将会出现间接性的断流。不开启tun模式或者多个网卡连接的都为不同的网络则不会出现这个问题。
![image](https://github.com/user-attachments/assets/da3bf145-fe9c-4a1a-b0e5-7c1a406e77da)
![image](https://github.com/user-attachments/assets/20491ba2-dac1-49f4-80f3-d08fbefe3674)

### 复现步骤 / To Reproduce

多个网卡连接至同一个网络，同时开启tun模式

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Arch Linux -- 6.10.3-zen1-2-zen (64-bit)

### 日志 / Log

time="2024-08-10T17:14:39.34297427+08:00" level=info msg="Start initial configuration in progress"
time="2024-08-10T17:14:39.343994099+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-08-10T17:14:39.344011251+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-08-10T17:14:39.347248403+08:00" level=info msg="Initial configuration complete, total time: 4ms"
time="2024-08-10T17:14:39.347384508+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9097"
time="2024-08-10T17:14:39.359985115+08:00" level=info msg="Sniffer is closed"
time="2024-08-10T17:14:39.360072298+08:00" level=info msg="DNS server listening at: 127.0.0.1:8853"
time="2024-08-10T17:14:39.360139354+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:7897"
time="2024-08-10T17:14:39.360376157+08:00" level=warning msg="[TUN] default interface changed by monitor,  => enp4s0"
time="2024-08-10T17:14:39.36261519+08:00" level=info msg="[TUN] Tun adapter listening at: Mihomo([198.18.0.1/30],[fdfe:dcba:9876::1/126]), mtu: 1500, auto route: true, auto redir: false, ip stack: gVisor"
time="2024-08-10T17:14:39.364049316+08:00" level=info msg="Start initial Compatible provider 📢 谷歌 FCM"
time="2024-08-10T17:14:39.3640732+08:00" level=info msg="Start initial Compatible provider 🚀 节点选择"
time="2024-08-10T17:14:39.36407844+08:00" level=info msg="Start initial Compatible provider Ⓜ️ 微软云盘"
time="2024-08-10T17:14:39.36408385+08:00" level=info msg="Start initial Compatible provider 🌏 国内媒体"
time="2024-08-10T17:14:39.364088098+08:00" level=info msg="Start initial Compatible provider 🛑 广告拦截"
time="2024-08-10T17:14:39.364092917+08:00" level=info msg="Start initial Compatible provider 🎥 Netflix"
time="2024-08-10T17:14:39.364096855+08:00" level=info msg="Start initial Compatible provider 📺 哔哩哔哩"
time="2024-08-10T17:14:39.364101303+08:00" level=info msg="Start initial Compatible provider 🎯 全球直连"
time="2024-08-10T17:14:39.364105371+08:00" level=info msg="Start initial Compatible provider 🎮 游戏平台"
time="2024-08-10T17:14:39.364109939+08:00" level=info msg="Start initial Compatible provider 🌍 国外媒体"
time="2024-08-10T17:14:39.364114077+08:00" level=info msg="Start initial Compatible provider 🍃 应用净化"
time="2024-08-10T17:14:39.364118585+08:00" level=info msg="Start initial Compatible provider 📲 Telegram"
time="2024-08-10T17:14:39.364122513+08:00" level=info msg="Start initial Compatible provider Ⓜ️ 微软服务"
time="2024-08-10T17:14:39.364126921+08:00" level=info msg="Start initial Compatible provider 📹 YouTube"
time="2024-08-10T17:14:39.364131009+08:00" level=info msg="Start initial Compatible provider 🍎 苹果服务"
time="2024-08-10T17:14:39.364135587+08:00" level=info msg="Start initial Compatible provider 😺 GitHub"
time="2024-08-10T17:14:39.364139715+08:00" level=info msg="Start initial Compatible provider 📺 巴哈姆特"
time="2024-08-10T17:14:39.364144293+08:00" level=info msg="Start initial Compatible provider 🎶 网易音乐"
time="2024-08-10T17:14:39.364148311+08:00" level=info msg="Start initial Compatible provider 📺 EMBY"
time="2024-08-10T17:14:39.364152609+08:00" level=info msg="Start initial Compatible provider default"
time="2024-08-10T17:14:39.364156486+08:00" level=info msg="Start initial Compatible provider 🐟 漏网之鱼"
time="2024-08-10T17:14:39.364160875+08:00" level=info msg="Start initial Compatible provider 🎥 Disney+"
time="2024-08-10T17:14:44.733915701+08:00" level=info msg="Load MMDB file: /home/jcfun/.local/share/io.github.clash-verge-rev.clash-verge-rev/Country.mmdb"
time="2024-08-10T17:14:49.735073166+08:00" level=warning msg="[TCP] dial 🐟 漏网之鱼 (match Match/) 198.18.0.1:51954(chrome, uid=1000) --> 20.205.243.168:443 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:14:49.735392814+08:00" level=warning msg="[TCP] dial 🐟 漏网之鱼 (match Match/) 198.18.0.1:52838(chrome, uid=1000) --> 140.82.113.22:443 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:14:49.73542252+08:00" level=warning msg="[TCP] dial 📢 谷歌 FCM (match IPCIDR/108.177.125.188/32) 198.18.0.1:42266 --> 108.177.125.188:5228 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:14:49.735425095+08:00" level=warning msg="[TCP] dial 🐟 漏网之鱼 (match Match/) 198.18.0.1:35680(chrome, uid=1000) --> 140.82.114.25:443 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:14:50.037049871+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:58638(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:14:50.288746818+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:58640(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:14:50.338391561+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:58656(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:14:50.338423371+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:58642(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:14:50.338484636+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:58668(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:14:50.338494264+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:58678(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:14:50.900201278+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:36858(chrome, uid=1000) --> 112.83.140.14:443 error: connect failed: dial tcp 112.83.140.14:443: i/o timeout"
time="2024-08-10T17:14:51.150969347+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:36862(chrome, uid=1000) --> 112.83.140.14:443 error: connect failed: dial tcp 112.83.140.14:443: i/o timeout"
time="2024-08-10T17:14:51.201517288+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:36868(chrome, uid=1000) --> 112.83.140.14:443 error: connect failed: dial tcp 112.83.140.14:443: i/o timeout"
time="2024-08-10T17:14:54.37944082+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:57072(chrome, uid=1000) --> 221.15.71.64:443 error: connect failed: dial tcp 221.15.71.64:443: i/o timeout"
time="2024-08-10T17:14:54.630165867+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:57086(chrome, uid=1000) --> 221.15.71.64:443 error: connect failed: dial tcp 221.15.71.64:443: i/o timeout"
time="2024-08-10T17:14:54.735787732+08:00" level=warning msg="[TCP] dial 📢 谷歌 FCM (match IPCIDR/108.177.125.188/32) 198.18.0.1:42282 --> 108.177.125.188:5228 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:14:54.735860007+08:00" level=warning msg="[TCP] dial 🐟 漏网之鱼 (match Match/) 198.18.0.1:52844(chrome, uid=1000) --> 140.82.113.22:443 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:14:54.735869515+08:00" level=warning msg="[TCP] dial 🐟 漏网之鱼 (match Match/) 198.18.0.1:51968(chrome, uid=1000) --> 20.205.243.168:443 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:14:54.735871198+08:00" level=warning msg="[TCP] dial 🐟 漏网之鱼 (match Match/) 198.18.0.1:35696(chrome, uid=1000) --> 140.82.114.25:443 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:14:55.351152772+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:58688(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:14:55.602581292+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:58692(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:14:55.652275161+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:58726(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:14:55.65231172+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:58704(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:14:55.652304767+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:58718(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:14:55.652307111+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:58696(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:14:55.880829969+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:36876(chrome, uid=1000) --> 112.83.140.14:443 error: connect failed: dial tcp 112.83.140.14:443: i/o timeout"
time="2024-08-10T17:14:56.214043299+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:36892(chrome, uid=1000) --> 112.83.140.14:443 error: connect failed: dial tcp 112.83.140.14:443: i/o timeout"
time="2024-08-10T17:14:56.463560987+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:36904(chrome, uid=1000) --> 112.83.140.14:443 error: connect failed: dial tcp 112.83.140.14:443: i/o timeout"
time="2024-08-10T17:14:56.514129651+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:36910(chrome, uid=1000) --> 112.83.140.14:443 error: connect failed: dial tcp 112.83.140.14:443: i/o timeout"
time="2024-08-10T17:14:59.615363934+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:33398(chrome, uid=1000) --> 112.83.140.14:443 error: connect failed: dial tcp 112.83.140.14:443: i/o timeout"
time="2024-08-10T17:14:59.692407285+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:35326(chrome, uid=1000) --> 221.15.71.64:443 error: connect failed: dial tcp 221.15.71.64:443: i/o timeout"
time="2024-08-10T17:14:59.737653991+08:00" level=warning msg="[TCP] dial 🐟 漏网之鱼 (match Match/) 198.18.0.1:53230(chrome, uid=1000) --> 142.251.42.238:443 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:14:59.737756743+08:00" level=warning msg="[TCP] dial 📢 谷歌 FCM (match IPCIDR/108.177.125.188/32) 198.18.0.1:40782 --> 108.177.125.188:443 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:14:59.737767874+08:00" level=warning msg="[TCP] dial 🐟 漏网之鱼 (match Match/) 198.18.0.1:34894(chrome, uid=1000) --> 140.82.114.25:443 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:14:59.904167368+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:60796(qq, uid=1000) --> 113.240.75.252:443 error: connect failed: dial tcp 113.240.75.252:443: i/o timeout"
time="2024-08-10T17:14:59.943348353+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:35338(chrome, uid=1000) --> 221.15.71.64:443 error: connect failed: dial tcp 221.15.71.64:443: i/o timeout"
time="2024-08-10T17:15:00.664537806+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:38264(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:15:01.192731059+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:33402(chrome, uid=1000) --> 112.83.140.14:443 error: connect failed: dial tcp 112.83.140.14:443: i/o timeout"
time="2024-08-10T17:15:01.529172766+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:38278(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:15:01.830591153+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:38286(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:15:02.079010648+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:38292(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:15:02.834750788+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:38294(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:15:04.675463799+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:38306(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:15:04.737970457+08:00" level=warning msg="[TCP] dial 📢 谷歌 FCM (match IPCIDR/108.177.125.188/32) 198.18.0.1:40794 --> 108.177.125.188:443 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:15:04.738076255+08:00" level=warning msg="[TCP] dial 🐟 漏网之鱼 (match Match/) 198.18.0.1:53242(chrome, uid=1000) --> 142.251.42.238:443 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:15:04.738090161+08:00" level=warning msg="[TCP] dial 🐟 漏网之鱼 (match Match/) 198.18.0.1:34898(chrome, uid=1000) --> 140.82.114.25:443 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:15:04.927378385+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:33412(chrome, uid=1000) --> 112.83.140.14:443 error: connect failed: dial tcp 112.83.140.14:443: i/o timeout"
time="2024-08-10T17:15:05.976769243+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:38312(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:15:06.842520193+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:38328(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:15:07.143034534+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:38334(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:15:07.390698855+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:38340(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:15:08.148254758+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:46162(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:15:09.738440979+08:00" level=warning msg="[TCP] dial 🐟 漏网之鱼 (match Match/) 198.18.0.1:42836(chrome, uid=1000) --> 140.82.114.25:443 error: cba83dae-2803-4e70-b504-1c3d2929eafb-hk-a.cdn.boats:30001 connect error: dns resolve failed: couldn't find ip"
time="2024-08-10T17:15:09.989041766+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/cn) 198.18.0.1:46164(chrome, uid=1000) --> 221.204.56.90:443 error: connect failed: dial tcp 221.204.56.90:443: i/o timeout"
time="2024-08-10T17:15:10.222716173+08:00" level=info msg="[TCP] 198.18.0.1:46174(chrome, uid=1000) --> 221.204.56.90:443 match GeoIP(cn) using 🎯 全球直连[DIRECT]"
time="2024-08-10T17:15:10.414966264+08:00" level=info msg="[TCP] 198.18.0.1:46172(chrome, uid=1000) --> 221.204.56.90:443 match GeoIP(cn) using 🎯 全球直连[DIRECT]"
time="2024-08-10T17:15:10.486782087+08:00" level=info msg="[TCP] 198.18.0.1:38792(chrome, uid=1000) --> 112.83.140.11:443 match GeoIP(cn) using 🎯 全球直连[DIRECT]"
time="2024-08-10T17:15:10.543979+08:00" level=info msg="[TCP] 198.18.0.1:46188(chrome, uid=1000) --> 221.204.56.90:443 match GeoIP(cn) using 🎯 全球直连[DIRECT]"
time="2024-08-10T17:15:10.544036989+08:00" level=info msg="[TCP] 198.18.0.1:46212(chrome, uid=1000) --> 221.204.56.90:443 match GeoIP(cn) using 🎯 全球直连[DIRECT]"
time="2024-08-10T17:15:10.678778102+08:00" level=info msg="[TCP] 198.18.0.1:38794(chrome, uid=1000) --> 112.83.140.11:443 match GeoIP(cn) using 🎯 全球直连[DIRECT]"
time="2024-08-10T17:15:10.799075334+08:00" level=info msg="[TCP] 198.18.0.1:46196(chrome, uid=1000) --> 221.204.56.90:443 match GeoIP(cn) using 🎯 全球直连[DIRECT]"
time="2024-08-10T17:15:10.997228478+08:00" level=info msg="[TCP] 198.18.0.1:42852(chrome, uid=1000) --> 140.82.114.25:443 match Match using 🐟 漏网之鱼[剩余流量：212.78 GB]"
time="2024-08-10T17:15:11.820070662+08:00" level=info msg="[TCP] 198.18.0.1:42860(chrome, uid=1000) --> 140.82.114.25:443 match Match using 🐟 漏网之鱼[剩余流量：212.78 GB]"

**Comment by h4rvey-g** [comment]
请教一下，双网卡连接两个不同的网络应该如何设置TUN和网卡，来做到负载均衡？谢谢
