### ISSUE TITLE
[BUG] 不支持最新版的Ubuntu24.04

### ISSUE THREAD

**Issue by fengzhoujingshui** [clash-verge-rev/clash-verge-rev#1543]
### 问题描述 / Describe the bug

在终端打开时，提示缺少libweb2gtk-4.0.38，但Ubuntu24.04只有libweb2gtk-4.1.0的包

### 复现步骤 / To Reproduce

目前最新版Ubuntu和alpha版本的软件，终端运行clash-verge

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu24.04

### 日志 / Log

Ubuntu下连不了github

**Comment by huina1621** [comment]
https://clash-verge-rev.github.io/faq/linux.html#ubuntu-2404
