### ISSUE TITLE
[BUG] Vivaldi Sync无法通过代理更新同步

### ISSUE THREAD

**Issue by cchx0000** [clash-verge-rev/clash-verge-rev#1546]
### 问题描述 / Describe the bug

用Clash Verge通过自建Hy2代理，其他上网功能一切正常，唯独Vivaldi浏览器Sync功能无法工作。查看日志发现Clash Verge正常发送请求，但是Vivaidi显示bifrost.vivaldi.net连接不上。
换成Hy2原生客户端工作正常，不是服务器问题。

### 复现步骤 / To Reproduce

用Clash Verge导入hy2服务器配置，使用规则连接
安装Vivaldi浏览器，登录账号，使用Sync同步

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win 11 IoT LTSC, LDME 6

### 日志 / Log

08-11 15:52:58info
[TCP] 127.0.0.1:58462 --> bifrost.vivaldi.com:443 match DomainSuffix(vivaldi.com) using xgCloud[Hysteria1]
08-11 15:53:02info
[TCP] 127.0.0.1:58498 --> bifrost.vivaldi.com:443 match DomainSuffix(vivaldi.com) using xgCloud[Hysteria1]
08-11 15:54:17info
[TCP] 127.0.0.1:58616 --> bifrost.vivaldi.com:443 match DomainSuffix(vivaldi.com) using xgCloud[Hysteria1]
08-11 15:54:47info
[TCP] 127.0.0.1:58622 --> bifrost.vivaldi.com:443 match DomainSuffix(vivaldi.com) using xgCloud[Hysteria1]
08-11 15:59:58info
[TCP] 127.0.0.1:58767 --> bifrost.vivaldi.com:443 match DomainSuffix(vivaldi.com) using xgCloud[Hysteria1]

**Comment by wonfen** [comment]
日志没看出问题，检查节点连通性和规则匹配。
