### ISSUE TITLE
[BUG] V1.7.5 出现【无效代理绕过格式】

### ISSUE THREAD

**Issue by EastUp** [clash-verge-rev/clash-verge-rev#1547]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/78b39b00-b6f2-4720-baa0-ace4fa43c587)

### 复现步骤 / To Reproduce

设置->系统代理->代理绕过设置

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 专业版

### 日志 / Log

出现【无效代理绕过格式】

**Comment by EastUp** [comment]
![image](https://github.com/user-attachments/assets/7c6c5c62-3fe3-4624-9f7c-b761dbd44f26)

**Comment by senwong** [comment]
好像要用英文逗号 or 分号分割~~

**Comment by EastUp** [comment]
> 好像要用英文逗号 or 分号分割~~
试过了 v1.7.5版本上还是不行

**Comment by EastUp** [comment]
原因：不支持下划线[_]的域名绕过。已经处理
