### ISSUE TITLE
[Feature] 请求提供是否允许图标在菜单栏显示的操作

### ISSUE THREAD

**Issue by pengweizhong** [clash-verge-rev/clash-verge-rev#1548]
### 功能描述 / Feature description

因为一些原因，我需要在顶部菜单栏不展示clash图标，因此是否能够添加类似“隐藏菜单栏”的实现？  
目前发现这里就挺好的：  
![image](https://github.com/user-attachments/assets/abbca944-d5a1-4c0e-92bc-6bf7b5cce38a)  
以上，谢谢。

### 使用场景 / Use case

需要隐藏该图标，因为不便公众展示。

**Comment by wonfen** [comment]
没有计划，不准备实现。

**Comment by pengweizhong** [comment]
额
