### ISSUE TITLE
[BUG] 代理规则失效

### ISSUE THREAD

**Issue by fujikang** [clash-verge-rev/clash-verge-rev#1549]
### 问题描述 / Describe the bug

1、clash不能正确识别代理规则去代理域名。我公司的域名有内网解析和外网解析的两套，例如intra.baidu.com是通过hosts文件，hosts文件内容为
172.18.111.13 intra.baidu.com 指向公司的内网服务器的
inter.baidu.com是正常的公网解析，然后我在rule里面配置了， 
 - IP-CIDR,10.109.0.0/16,inter,no-resolve
 - IP-CIDR,10.111.0.0/16,inter,no-resolve
 - IP-CIDR,172.18.0.0/16,intra,no-resolve
 - IP-CIDR,172.26.0.0/16,intra,no-resolve
 偶尔会出现，公网的域名可以访问，内网的域名访问不了。
 但是直接通过ip访问，是可以正常访问的。
 日志文件显示
 [TCP] dial 🎯 全球直连 (match DomainSuffix/cn) 127.0.0.1:54731(Google Chrome Helper) --> intra.baidu.com:80 error: dns resolve failed: couldn't find ip

 clash Verga版本v1.7.5

### 复现步骤 / To Reproduce

1、hosts文件配置好内网域名和ip的关系
2、clash Verga配置好rule
3、分别访问内网域名和外网域名，外网域名正常访问，内网域名提示找不到ip

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Sonoma

### 日志 / Log

 [TCP] dial 🎯 全球直连 (match DomainSuffix/cn) 127.0.0.1:54731(Google Chrome Helper) --> intra.baidu.com:80 error: dns resolve failed: couldn't find ip

**Comment by PctAIGM** [comment]
https://wiki.metacubex.one/config/dns/#use-system-hosts

```
## use-system-hosts
是否查询系统 hosts，默认 true
```

看看这个配置是true还是false

**Comment by fujikang** [comment]
<img width="544" alt="image" src="https://github.com/user-attachments/assets/f8ebb707-ba52-4a62-b79a-46ab660acd8f">
这里测试了内网域名正常，但是chrome就是不正常

**Comment by fujikang** [comment]
刚才又测试了一下换了浏览器，正常，但是有个问题，就算我换了浏览器，打开了网站，但是，clash里面日志看不到。是因为配置了use-system-hosts所以这个域名不会被代理吗？我看用IP访问，是正常可以看到日志，并且走了我配置的内网节点的

**Comment by fujikang** [comment]
use-system-hosts把这个配置加上以后，一切正常了。但是有个问题就是，关了tun模式，所有公司的代理就都不正常了，Google之类的正常
