### ISSUE TITLE
[Feature]希望可以添加订阅界面不同订阅的拖动排序

### ISSUE THREAD

**Issue by m13819277846** [clash-verge-rev/clash-verge-rev#155]
### Is your feature request related to a problem? Please describe.

订阅界面的订阅信息是按照导入排序的，但是不方便进行排序修改，希望能增加对订阅信息的拖动排序

### Describe the solution you'd like

希望能增加对订阅信息的拖动排序

### Describe alternatives you've considered

希望能增加对订阅信息的拖动排序

**Comment by MystiPanda** [comment]
你用的什么版本？

**Comment by shitouuuuu** [comment]
拖拽6筒就可以移动profile，1.44开始用就有了。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/55572093/677e9c9a-ca4d-451f-b857-8ecddf7c84e4)

**Comment by m13819277846** [comment]
> 拖拽6筒就可以移动profile，1.44开始用就有了。 ![image](https://private-user-images.githubusercontent.com/55572093/291458593-677e9c9a-ca4d-451f-b857-8ecddf7c84e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODU3MDYsIm5iZiI6MTcwMjk4NTQwNiwicGF0aCI6Ii81NTU3MjA5My8yOTE0NTg1OTMtNjc3ZTljOWEtY2E0ZC00NTFmLWI4NTctOGVjZGRmN2M4NGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDExMzAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZjk1NjI1MzFlNzMxZDQwZDgxNTVlYTc5NTZiNTFhZTFhODU0MWVkMWZhYTViMWQzZGJjZjAwYTI2ZTVmMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pj2xoyGTmSo_JL4edY1537Qc7vpzTHCgofIXtEbqUUc)

哦哦好的，我没注意，不好意思啊

**Comment by m13819277846** [comment]
> 拖拽6筒就可以移动profile，1.44开始用就有了。 ![image](https://private-user-images.githubusercontent.com/55572093/291458593-677e9c9a-ca4d-451f-b857-8ecddf7c84e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODU3MDYsIm5iZiI6MTcwMjk4NTQwNiwicGF0aCI6Ii81NTU3MjA5My8yOTE0NTg1OTMtNjc3ZTljOWEtY2E0ZC00NTFmLWI4NTctOGVjZGRmN2M4NGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDExMzAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZjk1NjI1MzFlNzMxZDQwZDgxNTVlYTc5NTZiNTFhZTFhODU0MWVkMWZhYTViMWQzZGJjZjAwYTI2ZTVmMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pj2xoyGTmSo_JL4edY1537Qc7vpzTHCgofIXtEbqUUc)

哦哦好的，我没注意，不好意思啊
