### ISSUE TITLE
[BUG] TUN模式关闭以后不会还原我的DNS设置

### ISSUE THREAD

**Issue by zhengyongtao** [clash-verge-rev/clash-verge-rev#1550]
### 问题描述 / Describe the bug

当我打开TUN模式的时候，我的系统DNS会被强制修改为223.5.5.5，但是关闭TUN模式后，我的系统DNS并没有被还原
![image](https://github.com/user-attachments/assets/6b824451-6747-4198-a874-448cb393d1cd)

### 复现步骤 / To Reproduce

1. 打开TUN模式
2. 打开网络设置，发现DNS被修改为223.5.5.5
3. 关闭TUN模式
4. 打开网络设置，发现DNS没有被还原

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5

### 日志 / Log

time="2024-08-12T15:02:09.379876+08:00" level=info msg="Start initial configuration in progress"
time="2024-08-12T15:02:09.381019+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-08-12T15:02:09.38104+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-08-12T15:02:09.382868+08:00" level=info msg="Initial configuration complete, total time: 2ms"
time="2024-08-12T15:02:09.385684+08:00" level=info msg="Sniffer is closed"
time="2024-08-12T15:02:09.387006+08:00" level=info msg="Start initial Compatible provider Proxies"
time="2024-08-12T15:02:09.38703+08:00" level=info msg="Start initial Compatible provider YouTube"
time="2024-08-12T15:02:09.38704+08:00" level=info msg="Start initial Compatible provider Bilibili"
time="2024-08-12T15:02:09.387048+08:00" level=info msg="Start initial Compatible provider Bahamut"
time="2024-08-12T15:02:09.387056+08:00" level=info msg="Start initial Compatible provider OpenAI"
time="2024-08-12T15:02:09.387063+08:00" level=info msg="Start initial Compatible provider TW"
time="2024-08-12T15:02:09.38707+08:00" level=info msg="Start initial Compatible provider SG"
time="2024-08-12T15:02:09.387078+08:00" level=info msg="Start initial Compatible provider Final"
time="2024-08-12T15:02:09.38709+08:00" level=info msg="Start initial Compatible provider Microsoft"
time="2024-08-12T15:02:09.387107+08:00" level=info msg="Start initial Compatible provider Disney"
time="2024-08-12T15:02:09.387118+08:00" level=info msg="Start initial Compatible provider Netflix"
time="2024-08-12T15:02:09.387126+08:00" level=info msg="Start initial Compatible provider Spotify"
time="2024-08-12T15:02:09.387133+08:00" level=info msg="Start initial Compatible provider PayPal"
time="2024-08-12T15:02:09.387139+08:00" level=info msg="Start initial Compatible provider default"
time="2024-08-12T15:02:09.387146+08:00" level=info msg="Start initial Compatible provider US"
time="2024-08-12T15:02:09.387167+08:00" level=info msg="Start initial Compatible provider Steam"
time="2024-08-12T15:02:09.38721+08:00" level=info msg="Start initial Compatible provider Google"
time="2024-08-12T15:02:09.387221+08:00" level=info msg="Start initial Compatible provider Apple"
time="2024-08-12T15:02:09.387229+08:00" level=info msg="Start initial Compatible provider Telegram"
time="2024-08-12T15:02:09.387238+08:00" level=info msg="Start initial Compatible provider JP"
time="2024-08-12T15:02:09.387247+08:00" level=info msg="Start initial Compatible provider HK"
time="2024-08-12T15:02:12.434803+08:00" level=info msg="Start initial configuration in progress"
time="2024-08-12T15:02:12.435876+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-08-12T15:02:12.43591+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-08-12T15:02:12.437638+08:00" level=info msg="Initial configuration complete, total time: 2ms"
time="2024-08-12T15:02:12.440484+08:00" level=info msg="Sniffer is closed"
time="2024-08-12T15:02:12.441743+08:00" level=info msg="Start initial Compatible provider JP"
time="2024-08-12T15:02:12.441781+08:00" level=info msg="Start initial Compatible provider PayPal"
time="2024-08-12T15:02:12.441791+08:00" level=info msg="Start initial Compatible provider Steam"
time="2024-08-12T15:02:12.44182+08:00" level=info msg="Start initial Compatible provider Disney"
time="2024-08-12T15:02:12.441851+08:00" level=info msg="Start initial Compatible provider US"
time="2024-08-12T15:02:12.441956+08:00" level=info msg="Start initial Compatible provider TW"
time="2024-08-12T15:02:12.441971+08:00" level=info msg="Start initial Compatible provider HK"
time="2024-08-12T15:02:12.441979+08:00" level=info msg="Start initial Compatible provider Bahamut"
time="2024-08-12T15:02:12.441987+08:00" level=info msg="Start initial Compatible provider Spotify"
time="2024-08-12T15:02:12.441995+08:00" level=info msg="Start initial Compatible provider Final"
time="2024-08-12T15:02:12.442001+08:00" level=info msg="Start initial Compatible provider Netflix"
time="2024-08-12T15:02:12.442007+08:00" level=info msg="Start initial Compatible provider YouTube"
time="2024-08-12T15:02:12.442013+08:00" level=info msg="Start initial Compatible provider SG"
time="2024-08-12T15:02:12.442024+08:00" level=info msg="Start initial Compatible provider Proxies"
time="2024-08-12T15:02:12.442033+08:00" level=info msg="Start initial Compatible provider Google"
time="2024-08-12T15:02:12.442039+08:00" level=info msg="Start initial Compatible provider OpenAI"
time="2024-08-12T15:02:12.442053+08:00" level=info msg="Start initial Compatible provider default"
time="2024-08-12T15:02:12.442085+08:00" level=info msg="Start initial Compatible provider Telegram"
time="2024-08-12T15:02:12.442097+08:00" level=info msg="Start initial Compatible provider Apple"
time="2024-08-12T15:02:12.442109+08:00" level=info msg="Start initial Compatible provider Bilibili"
time="2024-08-12T15:02:12.442117+08:00" level=info msg="Start initial Compatible provider Microsoft"
time="2024-08-12T15:02:17.666529+08:00" level=info msg="Start initial configuration in progress"
time="2024-08-12T15:02:17.667514+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-08-12T15:02:17.66754+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-08-12T15:02:17.66932+08:00" level=info msg="Initial configuration complete, total time: 2ms"
time="2024-08-12T15:02:17.671982+08:00" level=info msg="Sniffer is closed"
time="2024-08-12T15:02:17.672121+08:00" level=warning msg="[TUN] Unsupported tunName(Mihomo) in darwin, force regenerate by ourselves."
time="2024-08-12T15:02:17.672408+08:00" level=warning msg="[TUN] default interface changed by monitor,  => en0"
time="2024-08-12T15:02:17.675452+08:00" level=info msg="[TUN] Tun adapter listening at: utun8([198.18.0.1/30],[]), mtu: 1500, auto route: true, auto redir: false, ip stack: gVisor"
time="2024-08-12T15:02:17.67698+08:00" level=info msg="Start initial Compatible provider Bilibili"
time="2024-08-12T15:02:17.677012+08:00" level=info msg="Start initial Compatible provider OpenAI"
time="2024-08-12T15:02:17.677021+08:00" level=info msg="Start initial Compatible provider YouTube"
time="2024-08-12T15:02:17.67703+08:00" level=info msg="Start initial Compatible provider HK"
time="2024-08-12T15:02:17.677041+08:00" level=info msg="Start initial Compatible provider Telegram"
time="2024-08-12T15:02:17.677048+08:00" level=info msg="Start initial Compatible provider Disney"
time="2024-08-12T15:02:17.677058+08:00" level=info msg="Start initial Compatible provider Netflix"
time="2024-08-12T15:02:17.677065+08:00" level=info msg="Start initial Compatible provider Spotify"
time="2024-08-12T15:02:17.677095+08:00" level=info msg="Start initial Compatible provider Bahamut"
time="2024-08-12T15:02:17.677126+08:00" level=info msg="Start initial Compatible provider Google"
time="2024-08-12T15:02:17.677149+08:00" level=info msg="Start initial Compatible provider PayPal"
time="2024-08-12T15:02:17.67716+08:00" level=info msg="Start initial Compatible provider US"
time="2024-08-12T15:02:17.677197+08:00" level=info msg="Start initial Compatible provider SG"
time="2024-08-12T15:02:17.677233+08:00" level=info msg="Start initial Compatible provider JP"
time="2024-08-12T15:02:17.677252+08:00" level=info msg="Start initial Compatible provider Proxies"
time="2024-08-12T15:02:17.677273+08:00" level=info msg="Start initial Compatible provider Steam"
time="2024-08-12T15:02:17.677322+08:00" level=info msg="Start initial Compatible provider default"
time="2024-08-12T15:02:17.677339+08:00" level=info msg="Start initial Compatible provider TW"
time="2024-08-12T15:02:17.677355+08:00" level=info msg="Start initial Compatible provider Final"
time="2024-08-12T15:02:17.677366+08:00" level=info msg="Start initial Compatible provider Microsoft"
time="2024-08-12T15:02:17.677374+08:00" level=info msg="Start initial Compatible provider Apple"
time="2024-08-12T15:02:21.709052+08:00" level=info msg="Start initial configuration in progress"
time="2024-08-12T15:02:21.710031+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-08-12T15:02:21.710069+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-08-12T15:02:21.71299+08:00" level=info msg="Initial configuration complete, total time: 3ms"
time="2024-08-12T15:02:21.714652+08:00" level=info msg="Sniffer is closed"
time="2024-08-12T15:02:21.718509+08:00" level=info msg="Start initial Compatible provider US"
time="2024-08-12T15:02:21.718551+08:00" level=info msg="Start initial Compatible provider Telegram"
time="2024-08-12T15:02:21.718563+08:00" level=info msg="Start initial Compatible provider Spotify"
time="2024-08-12T15:02:21.718576+08:00" level=info msg="Start initial Compatible provider Steam"
time="2024-08-12T15:02:21.718589+08:00" level=info msg="Start initial Compatible provider Microsoft"
time="2024-08-12T15:02:21.718598+08:00" level=info msg="Start initial Compatible provider Disney"
time="2024-08-12T15:02:21.718604+08:00" level=info msg="Start initial Compatible provider Bahamut"
time="2024-08-12T15:02:21.718611+08:00" level=info msg="Start initial Compatible provider PayPal"
time="2024-08-12T15:02:21.718617+08:00" level=info msg="Start initial Compatible provider YouTube"
time="2024-08-12T15:02:21.718625+08:00" level=info msg="Start initial Compatible provider default"
time="2024-08-12T15:02:21.718632+08:00" level=info msg="Start initial Compatible provider TW"
time="2024-08-12T15:02:21.718638+08:00" level=info msg="Start initial Compatible provider HK"
time="2024-08-12T15:02:21.718651+08:00" level=info msg="Start initial Compatible provider Proxies"
time="2024-08-12T15:02:21.718657+08:00" level=info msg="Start initial Compatible provider Netflix"
time="2024-08-12T15:02:21.718679+08:00" level=info msg="Start initial Compatible provider Final"
time="2024-08-12T15:02:21.718716+08:00" level=info msg="Start initial Compatible provider Google"
time="2024-08-12T15:02:21.718728+08:00" level=info msg="Start initial Compatible provider Apple"
time="2024-08-12T15:02:21.718735+08:00" level=info msg="Start initial Compatible provider SG"
time="2024-08-12T15:02:21.718767+08:00" level=info msg="Start initial Compatible provider JP"
time="2024-08-12T15:02:21.718833+08:00" level=info msg="Start initial Compatible provider OpenAI"
time="2024-08-12T15:02:21.718852+08:00" level=info msg="Start initial Compatible provider Bilibili"

**Comment by ychy00001** [comment]
一样。。。自己设置的都没了

**Comment by xgblack** [comment]
同样遇到了

**Comment by medz** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/blob/632c32addbea495cbb573a43e41fc920e294ad2b/src-tauri/src/enhance/tun.rs#L62

Please remove the harmful code. TUN mode does not require DNS support. In addition, as an open source software, you should not let everyone have the same DNS preference as you in the software. For example, I am keen on 1.1.1.1 to eliminate all Alibaba DNS. 114.114.114 is a notorious DNS that injects advertisements or is abused by DNS confusion. I mainly work abroad and use this tool to access the Chinese network normally.

Your DNS settings make my entire network unavailable!

**Comment by medz** [comment]
```typescript
const dns = {
  "default-nameserver": [
    "1.1.1.1",
    "1.0.0.1",
    "2606:4700:4700::1111",
    "2606:4700:4700::1001",
    "119.29.29.29",
    "2402:4e00::",
  ],
  nameserver: [
    "https://cloudflare-dns.com/dns-query",
    "https://doh.pub/dns-query",
  ],
};

function main(config, profileName) {
  config.dns = {
    ...config.dns,
    ...dns,
  };

  return config;
}
```

Guys, this can be fixed with a global script

**Comment by zhengyongtao** [comment]
这个问题的本质是关闭TUN模式开关后应当采用unset操作将dns还原，而它没有这么做。

**Comment by eronez** [comment]
also encounter this issue on Ubuntu 24.04.
DNS should be restored as previous (or just remove `nameserver 192.18.0.2`?) when disable tun mode.

**Comment by genequ** [comment]
Same problem, v1.7.7 + macOS Sequoia.
This is annoying, e.g, have to remove the DNS '223.5.5.5' manually to use company's DNS.
