### ISSUE TITLE
[BUG] Prepend-rules 不生效

### ISSUE THREAD

**Issue by Jenichia** [clash-verge-rev/clash-verge-rev#1551]
### 问题描述 / Describe the bug

Verge Version: v1.7.5
Clash Core: v1.18.6 Mihomo

照着[这个网址](https://clash-verge-rev.github.io/guide/merge.html#loyalsoldier)最下面的视频教程做了，该替换的地方都替换了，只修改了全局配置文件，其他地方没动，但是所有前置规则都没生效。
<img width="651" alt="20240812_220302" src="https://github.com/user-attachments/assets/5452345c-cd7b-4e2e-a685-93bc229ce98b">
规则集都有成功更新，包括配置文件也重新激活了，但前置规则不是应该显示在最上面么，为啥我这最上面还是订阅自带的规则。

### 复现步骤 / To Reproduce

[这个网站](https://clash-verge-rev.github.io/guide/merge.html#loyalsoldier)的视频教程。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 23H2

### 日志 / Log

空

**Comment by eeetechen** [comment]
同问题，prepend-rules: 以及 append-rules:  都不生效。
无论在全局扩展配置，还是在订阅的扩展配置

**Comment by Jenichia** [comment]
> 同问题，prepend-rules: 以及 append-rules: 都不生效。
> 无论在全局扩展配置，还是在订阅的扩展配置

好了你也不用问了，我知道哪里的问题了。你去看 1.7.1 版本的发布页，里面有说明，看完你就懂了。另外我使用的教程是在【历史归档】分类底下，部分已经失效了。我是跳版本更新的所以不知道这里的改动，真tm成前朝遗老了。

**Comment by eeetechen** [comment]
刚刚从关闭的issue里面找了一圈懂了，在配置文件的右键编辑规则对吧。我也找到了，但是这样就无法编辑一份本地配置应用所有机场，实在是不方便啊。

**Comment by Jenichia** [comment]
`rule-providers` 字段还是可以放在全局扩展配置中的，分开放的话可能方便不同的策略组吧，毕竟不同订阅策略组不一定相同，切换策略组还得修改全局扩展配置才能生效，也挺麻烦的。这样每个订阅单独设定倒是可以一劳永逸，就算你所有订阅策略组都一样也没什么不方便，复制粘贴几次的事情。

**Comment by PctAIGM** [comment]
> `rule-providers` 字段还是可以放在全局扩展配置中的，分开放的话可能方便不同的策略组吧，毕竟不同订阅策略组不一定相同，切换策略组还得修改全局扩展配置才能生效，也挺麻烦的。这样每个订阅单独设定倒是可以一劳永逸，就算你所有订阅策略组都一样也没什么不方便，复制粘贴几次的事情。

注意：如果机场订阅有用到rule-providers，则不能放到全局扩展配置，否则会覆盖机场的rule-providers

**Comment by PctAIGM** [comment]
刚试了下，rule-providers不会覆盖，记错了。rules才会覆盖。

**Comment by h1075335917** [comment]
> > 同问题，prepend-rules: 以及 append-rules: 都不生效。
> > 无论在全局扩展配置，还是在订阅的扩展配置
> 
> 好了你也不用问了，我知道哪里的问题了。你去看 1.7.1 版本的发布页，里面有说明，看完你就懂了。另外我使用的教程是在【历史归档】分类底下，部分已经失效了。我是跳版本更新的所以不知道这里的改动，真tm成前朝遗老了。

前朝遗老加1，还好看到了

**Comment by Naylenv** [comment]
prepend-rules 挺方便的，现在除了一个一个添加，有没有写配置文件定义路由规则的方式呢？

**Comment by Jenichia** [comment]
> prepend-rules 挺方便的，现在除了一个一个添加，有没有写配置文件定义路由规则的方式呢？ 我目前是这样解决的： [#1437 (comment)](https://github.com/clash-verge-rev/clash-verge-rev/issues/1437#issuecomment-2297924785)

<img width="600" alt="20241008_203931" src="https://github.com/user-attachments/assets/5a78bfef-d2ef-42c8-a8b1-4684127fca64">

**Comment by Naylenv** [comment]
> > prepend-rules 挺方便的，现在除了一个一个添加，有没有写配置文件定义路由规则的方式呢？ 我目前是这样解决的： [#1437 (comment)](https://github.com/clash-verge-rev/clash-verge-rev/issues/1437#issuecomment-2297924785)
> 
> <img alt="20241008_203931" width="600" src="https://private-user-images.githubusercontent.com/87779111/374561217-5a78bfef-d2ef-42c8-a8b1-4684127fca64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTUyNzEsIm5iZiI6MTcyODM5NDk3MSwicGF0aCI6Ii84Nzc3OTExMS8zNzQ1NjEyMTctNWE3OGJmZWYtZDJlZi00MmM4LWE4YjEtNDY4NDEyN2ZjYTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEzNDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5Y2RmYzAxMWJiNjk1Mjg2YmI5YzljOTEwYzgxZmFkZTIwYmEyZjk0NGE2OTQ3ZjE3MmU2ZDUwNzEzZjJhY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x7Uc6ZJyD_2BIfuauYOr6PB7deqS9NttkxHU254YNTs">

👍🏻赞
