### ISSUE TITLE
[BUG] TUN模式显示，Mihomo无法访问Internet

### ISSUE THREAD

**Issue by likecreep** [clash-verge-rev/clash-verge-rev#1552]
### 问题描述 / Describe the bug

1.7.5
tun模式下，one drive显示无网络连接，win11地球显示： Mihomo无法访问Internet。
微软商店在开启了 UMP工具后，能够正常浏览，但是无法登录账号，显示无法连接到internet。

显示设备 SWD\Wintun\在启动时出现问题。

Mihomo网卡状态显示， 无Internet访问权限。

但是除此之外，设备能够正常上网，即使关闭系统代理，也可以正常连接外网。

不知道是哪里的问题。

### 复现步骤 / To Reproduce

开启服务模式后再开启tun模式。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

设备 SWD\Wintun\在启动时出现问题。

驱动程序名称: oem21.inf
服务: wintun
低层筛选程序: 
高层筛选程序: 
问题: 0x0
问题状态: 0xC00000E5

**Comment by kusiru** [comment]
修改以下注册表值：

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet

EnableActiveProbing：修改为1



重启clash
