### ISSUE TITLE
[BUG] 将Clash日志级别调整为Debug之后，GUI的日志模块并没有显示Debug日志

### ISSUE THREAD

**Issue by 52comfortable** [clash-verge-rev/clash-verge-rev#1553]
### 问题描述 / Describe the bug

将Clash日志级别调整为Debug之后，GUI的日志模块并没有显示Debug日志
但是日志文件中其实是有Debug日志的
![image](https://github.com/user-attachments/assets/1dd233f4-b5c8-4ba7-9958-22db6f757303)
![image](https://github.com/user-attachments/assets/a86b15f7-e2e4-4aa2-84cf-ee4d28dbe820)

### 复现步骤 / To Reproduce

将Clash日志级别调整为Debug之后,重启应用

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10

### 日志 / Log

time="2024-08-13T09:13:55.9202598+08:00" level=debug msg="[DNS] resolve puv.tt.browser.360.cn A from https://120.53.53.53:443/dns-query"
time="2024-08-13T09:13:55.92776+08:00" level=debug msg="[DNS] puv.tt.browser.360.cn --> [] AAAA from https://223.5.5.5:443/dns-query"
time="2024-08-13T09:13:55.92776+08:00" level=debug msg="[DNS] puv.tt.browser.360.cn --> [180.163.246.123 101.198.2.155] A from https://223.5.5.5:443/dns-query"
time="2024-08-13T09:13:55.9335953+08:00" level=debug msg="[DNS] puv.tt.browser.360.cn --> [] AAAA from https://120.53.53.53:443/dns-query"
time="2024-08-13T09:13:55.9629829+08:00" level=info msg="[TCP] 127.0.0.1:51767 --> puv.tt.browser.360.cn:80 match RuleSet(direct) using DIRECT"
time="2024-08-13T09:14:30.2326146+08:00" level=debug msg="Auth success from 127.0.0.1:51814 -> "
time="2024-08-13T09:14:30.2326146+08:00" level=debug msg="[Rule] use default rules"
time="2024-08-13T09:14:30.2326146+08:00" level=debug msg="[DNS] cache hit s.hk1.niceduck.me --> [120.241.177.155] A, expire at 2024-08-13 09:14:07"
time="2024-08-13T09:14:30.2328895+08:00" level=debug msg="[DNS] cache hit s.hk1.niceduck.me --> [] AAAA, expire at 2024-08-13 09:21:37"
time="2024-08-13T09:14:30.2328895+08:00" level=debug msg="[DNS] resolve s.hk1.niceduck.me A from https://223.5.5.5:443/dns-query"
time="2024-08-13T09:14:30.2328895+08:00" level=debug msg="[DNS] resolve s.hk1.niceduck.me A from https://120.53.53.53:443/dns-query"
time="2024-08-13T09:14:30.2393869+08:00" level=debug msg="[DNS] s.hk1.niceduck.me --> [120.241.177.155] A from https://223.5.5.5:443/dns-query"
time="2024-08-13T09:14:30.2447887+08:00" level=info msg="[TCP] 127.0.0.1:51814 --> activity.windows.com:443 match RuleSet(proxy) using NiceDuck[【1x】隧道丨香港 01]"
time="2024-08-13T09:14:37.2710909+08:00" level=debug msg="Auth success from 127.0.0.1:51889 -> "
time="2024-08-13T09:14:37.2712368+08:00" level=debug msg="[Rule] use default rules"
time="2024-08-13T09:14:37.2712368+08:00" level=debug msg="[DNS] resolve badjs.weixinbridge.com AAAA from https://223.5.5.5:443/dns-query"
time="2024-08-13T09:14:37.2712368+08:00" level=debug msg="[DNS] resolve badjs.weixinbridge.com AAAA from https://120.53.53.53:443/dns-query"
time="2024-08-13T09:14:37.2712368+08:00" level=debug msg="[DNS] resolve badjs.weixinbridge.com A from https://223.5.5.5:443/dns-query"
time="2024-08-13T09:14:37.2712368+08:00" level=debug msg="[DNS] resolve badjs.weixinbridge.com A from https://120.53.53.53:443/dns-query"
time="2024-08-13T09:14:37.2777756+08:00" level=debug msg="[DNS] badjs.weixinbridge.com --> [101.226.99.155] A from https://223.5.5.5:443/dns-query"
time="2024-08-13T09:14:37.2777756+08:00" level=debug msg="[DNS] badjs.weixinbridge.com --> [2402:4e00:36:2fff::8a] AAAA from https://223.5.5.5:443/dns-query"
time="2024-08-13T09:14:37.3073838+08:00" level=info msg="[TCP] 127.0.0.1:51889 --> badjs.weixinbridge.com:443 match RuleSet(direct) using DIRECT"
time="2024-08-13T09:15:05.1385127+08:00" level=debug msg="Auth success from 127.0.0.1:51906 -> "
time="2024-08-13T09:15:05.1387024+08:00" level=debug msg="[Rule] use default rules"
time="2024-08-13T09:15:05.1387024+08:00" level=debug msg="[DNS] cache hit push2.eastmoney.com --> [114.80.72.121] A, expire at 2024-08-13 09:11:29"
time="2024-08-13T09:15:05.1387024+08:00" level=debug msg="[DNS] cache hit push2.eastmoney.com --> [2409:8c1e:5b70:2:5000:1000:0:72] AAAA, expire at 2024-08-13 09:12:00"
time="2024-08-13T09:15:05.1387024+08:00" level=debug msg="[DNS] resolve push2.eastmoney.com A from https://223.5.5.5:443/dns-query"
time="2024-08-13T09:15:05.1387024+08:00" level=debug msg="[DNS] resolve push2.eastmoney.com A from https://120.53.53.53:443/dns-query"
time="2024-08-13T09:15:05.1387024+08:00" level=debug msg="[DNS] resolve push2.eastmoney.com AAAA from https://223.5.5.5:443/dns-query"
time="2024-08-13T09:15:05.1387024+08:00" level=debug msg="[DNS] resolve push2.eastmoney.com AAAA from https://120.53.53.53:443/dns-query"
time="2024-08-13T09:15:05.1517016+08:00" level=debug msg="[DNS] push2.eastmoney.com --> [61.152.229.70] A from https://120.53.53.53:443/dns-query"
time="2024-08-13T09:15:05.1517016+08:00" level=debug msg="[DNS] push2.eastmoney.com --> [2400:3200:1300::8e7] AAAA from https://120.53.53.53:443/dns-query"
time="2024-08-13T09:15:05.1699313+08:00" level=info msg="[TCP] 127.0.0.1:51906 --> push2.eastmoney.com:443 match RuleSet(direct) using DIRECT"

**Comment by wonfen** [comment]
重启GUI没？

**Comment by 52comfortable** [comment]
> 重启GUI没？

重启了

**Comment by dududuK** [comment]
我也有这个问题，不显示debug日志

**Comment by dududuK** [comment]
> 重启GUI没？

日志实时滚动时不会出现debug日志，我把日志暂停后再开启，会出现之前没显示的debug日志。
