### ISSUE TITLE
[BUG] 无法连接我本地的127.0.0.1上面的隧道服务

### ISSUE THREAD

**Issue by cdxiaodong** [clash-verge-rev/clash-verge-rev#1554]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/cea8d871-e1f8-4ba4-8b16-4d04367c1c4b)
无法连接我本地的127.0.0.1上面的隧道服务  这个服务我通过其他插件是确定可以使用的

### 复现步骤 / To Reproduce

新增一个内网监听隧道 然后clash连接这个隧道即可

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

无法连接 故而没有日志

**Comment by wonfen** [comment]
你这个版本都不是最新版。
