### ISSUE TITLE
[BUG] 狗狗加速几分钟断一次，这么差，能不能不推荐?

### ISSUE THREAD

**Issue by zhuwei** [clash-verge-rev/clash-verge-rev#1556]
### 问题描述 / Describe the bug

用了半个月，实在受不了。忍不下去了

### 复现步骤 / To Reproduce

随便复现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

无

**Comment by nxtreaming** [comment]
自己做中继会改善网络稳定性。

**Comment by zhuwei** [comment]
@nxtreaming 没懂，你是说再租个vps？

**Comment by zhuwei** [comment]
实在受不了。用的这么多个，没一个比狗狗加速更差的了。

**Comment by shang106121** [comment]
+1 确实很差

**Comment by LUOSUH** [comment]
@zhuwei 都翻出来了自己要有点意识，而且 CVR 群里早就换了一家了，根本没在推了。而且这是“推荐”，不是强制你消费。谁给赞助就推谁，最终用哪家是你自己决定的 这也能提个issue？？

**Comment by zhuwei** [comment]
@LUOSUH 上面翻出来的啊。没翻出来的话我都给忘了。早没用了。很抱歉，你说的群我不太清楚。
另外再强调一下。我写的中文是“非要推荐狗狗加速”， 写的是“推荐”。
之前用的狗狗也是花钱的，不是免费的。如果是免费的，那我肯定一句话都不说(毕竟免费和收费是有区别的)。
最后我是给的我真心建议，因为跟我也没啥关系，用哪个都是要花钱

**Comment by ilovelxy** [comment]
> > +1 确实很差
> 
> 我已经换了。不知道作者怎么想的，非要推荐狗狗加速，把自己的招牌砸了。直接放弃了clash-verge-rev

现在用哪个了？

**Comment by rardz** [comment]
+1 差的匪夷所思
狗狗加速，垃圾中的战斗狗，
