### ISSUE TITLE
[BUG] 编辑规则之后，规则并未生效。

### ISSUE THREAD

**Issue by eeetechen** [clash-verge-rev/clash-verge-rev#1557]
### 问题描述 / Describe the bug

我在已有issue以编辑规则，规则不生效等关键词搜索并未发现相关issue。
desc:
在代理订阅文件中添加规则但是在实际访问中并未匹配到规则。
添加了规则，以acl4ssr 规则模板
```
  - 'DOMAIN-SUFFIX,aivisionplus.top,🎯 全球直连'
```
<img width="930" alt="截屏2024-08-13 17 25 30" src="https://github.com/user-attachments/assets/5bdd2390-0b44-447f-867d-cc6ff6bde2e3">
已经添加进入规则，并且点击小火苗刷新配置
---
但是仍然没有匹配或者生效
<img width="930" alt="截屏2024-08-13 17 24 25" src="https://github.com/user-attachments/assets/be537c34-e04b-4f11-b372-799c2cca86e5">
网页表现为打不开，

clash verge 中的连接界面详情
```
主机: next.aivisionplus.top:443
下载量: 16.8 KB
上传量: 1006 B
下载速度: 0 B/s
上传速度: 0 B/s
链路: 🐟 漏网之鱼 / 🚀 节点选择 / 🇨🇳 [v1] 台湾・02
规则: Match
进程:
连接时间: 1 分钟前
源地址: 127.0.0.1:53543
目标地址: 104.21.84.234
类型: HTTPS(tcp)
```

### 复现步骤 / To Reproduce

在代理订阅文件中添加
```
  - 'DOMAIN-SUFFIX,aivisionplus.top,🎯 全球直连'
```
然后打开[网站](https://next.aivisionplus.top/)

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

ventura 13.6.7

### 日志 / Log

在日志文件中搜索"aivisionplus.top",并未捕获到相关日志.

**Comment by Jenichia** [comment]
看上去你的 `MATCH` 规则跑到你这条 `DOMAIN-SUFFIX` 前面去了。

**Comment by eeetechen** [comment]
在今天，无论是否添加规则，全部都走直连了
