### ISSUE TITLE
[Feature] 自定义界面颜色下可读性不高

### ISSUE THREAD

**Issue by AkisuzuLightz** [clash-verge-rev/clash-verge-rev#156]
### Is your feature request related to a problem? Please describe.

在某些配色方案下，前后景的对比度太低。

### Describe the solution you'd like

希望能够独立设置背景颜色。

### Describe alternatives you've considered

或者加大自动计算的背景颜色 其明度对比（深色主题下更深浅色主题下更浅）。

**Comment by wonfen** [comment]
截个图看看啥自定义颜色可读性不高？

**Comment by AkisuzuLightz** [comment]
> 截个图看看啥自定义颜色可读性不高？

![屏幕截图 2023-12-18 033545](https://github.com/clash-verge-rev/clash-verge-rev/assets/148188885/23d2b039-bc3d-40fe-a4bd-af1f88a154f0)
![屏幕截图 2023-12-18 033545](https://github.com/clash-verge-rev/clash-verge-rev/assets/148188885/f193cacd-d281-4b2c-a4a5-2bf56930e768)
![屏幕截图 2023-12-18 033644](https://github.com/clash-verge-rev/clash-verge-rev/assets/148188885/bcaf005f-6cb4-4782-8910-8e8f2909662e)

不同场景下的识读性问题原因各自不同。为了举例便利，这里用了50%红色和25%红色的不符合一般设计原则的主题色。

1 处是不宜采用首要重点色，应当同 4 处一致处理。

2和3较为典型，背景色拥有一定的饱和度而且与主题色同色相，是一种比较和谐的设计，但在这种情况下和见面元素比较含混。

稍理想的的解决方案是使用100%的黑色和78.5%的深灰色作为背景色。这就需要改进算法或者允许用户自行设定。

第三张图片展现了另外一个问题，第二级菜单的背景色似乎与用户的设定完全无关。

大半夜还来回复，真是辛苦了(o^^o)。

**Comment by MystiPanda** [comment]
作为一款工具软件，自定义主题考虑不了那么多，只能是你来设置一个比较合理的主题色，在深色模式下设置这么暗的红色作为主题色本身就不合理，如果你设置主题色为#ff0000的话整体观感还是非常协调的。

**Comment by wonfen** [comment]
对...配色方面还是需要自己多调整多尝试，找到最合适的。
