### ISSUE TITLE
[BUG] 图标在桌面分辨率变化后不清晰

### ISSUE THREAD

**Issue by zzzqqiu** [clash-verge-rev/clash-verge-rev#1560]
### 问题描述 / Describe the bug

打CS2的时候发现的，如果改变CS2游戏分辨率和桌面分辨率不一致，结束游戏后Clash图标会变得很糊
![QQ20240813-230039](https://github.com/user-attachments/assets/5e6b8f29-3f03-4e43-95b9-0a0dd2381881)

### 复现步骤 / To Reproduce

同上

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10

### 日志 / Log

无相关日志

**Comment by wonfen** [comment]
windows分辨率缩放的bug吧。
