### ISSUE TITLE
[BUG] steam下载会导致内核程序异常高占用

### ISSUE THREAD

**Issue by u2shana** [clash-verge-rev/clash-verge-rev#1561]
### 问题描述 / Describe the bug

电脑整体CPU占用100%，其中verge-mihomo.exe占用非常高
看日志，在不断地刷规则

### 复现步骤 / To Reproduce

PUBG更新出现这种情况特别多

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

![QQ_1723632739557](https://github.com/user-attachments/assets/51dd23bc-f450-4af7-adcd-e5112a47d763)

**Comment by wonfen** [comment]
这个GUI无关，建议到内核那边反馈。
