### ISSUE TITLE
[BUG] can't initial GeoIP: can't download MMDB: Get "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb": EOF

### ISSUE THREAD

**Issue by Ye-BH** [clash-verge-rev/clash-verge-rev#1562]
### 问题描述 / Describe the bug

linux服务器，在个人用户目录下安装运行 1.7.5 版本，导入订阅后单击左键/右键使用，报错 can't initial GeoIP: can't download MMDB，代理页面中无法看到节点。
<img width="435" alt="b9462eae957778a898f34b3a733298f" src="https://github.com/user-attachments/assets/a9f18f0e-ac1c-40cd-96ab-7e1f15bb16c0">
尝试手动下载该文件，放在`~/clash-verge/usr/lib/clash-verge/resources`目录下，仍然会报相同错误无法下载。
1.7.5 alpha 版本、1.7.3、1.6.6 测试均有这个问题。

### 复现步骤 / To Reproduce

左键单击订阅使用

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu 22.04

### 日志 / Log

can't initial GeoIP: can't download MMDB: Get "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb": EOF

**Comment by wonfen** [comment]
你这个是网络连接有问题了；检查你的本地连接和配置文件中定义的geoip下载连接。
