### ISSUE TITLE
[BUG] 不关闭软件直接关机代理开关不会自动关闭

### ISSUE THREAD

**Issue by xygd555** [clash-verge-rev/clash-verge-rev#1563]
### 问题描述 / Describe the bug

不关闭软件直接关机，代理不会自动关闭，下次开机时代理依旧是开启的，而clash此时没用运行提供服务，导致网页不能访问，希望可以解决这个问题

### 复现步骤 / To Reproduce

11

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11

### 日志 / Log

11

**Comment by CMEPCBHG** [comment]
懒得骂你

**Comment by xygd555** [comment]
> 懒得骂你

你装nm大尾巴狼呢

**Comment by eronez** [comment]
Task Scheduler, add a "At startup" task to execute this
```CMD
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyEnable /t REG_DWORD /d 0 /f 
```
