### ISSUE TITLE
[Feature] 希望支持导入多个ss、ssr、vmess、trojan等节点信息

### ISSUE THREAD

**Issue by jarvis8284** [clash-verge-rev/clash-verge-rev#1565]
### 功能描述 / Feature description

ss、ssr、vmess、trojan节点信息

### 使用场景 / Use case

可以自由的根据链接动态导入具体的节点信息

**Comment by wonfen** [comment]
没听懂，导入的节点难道不是机场下发的吗？

**Comment by xuweijie123** [comment]
你好博主，我的意思是
节点导入的规则链接。现在只能导入clash的订阅连接，如果想订阅ss/V2Ray就需要将连接转换一下才行，没办法做到类似Shadowrocket 用户可以使用 ss、ssr 、 v2ray 等链接导入规则

参考仓库：https://github.com/tindy2013/subconverter.git

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/2270
