### ISSUE TITLE
[BUG] 订阅链接导入成功，但代理页面为空

### ISSUE THREAD

**Issue by HedgeSage** [clash-verge-rev/clash-verge-rev#1567]
### 问题描述 / Describe the bug

这个问题之前有用户反馈过：
普遍是说在windows11下因为拥塞控制算法启用bbr2导致的；
我是在windows10上遇到的，并且已经确认是cubic而不是bbr2。

### 复现步骤 / To Reproduce

1. 安装最新版本(其实老版本也一样)
2. 导入订阅链接
3. 点击代理页面
4. 展示为空

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows10

### 日志 / Log

N/A(稍后补充)

**Comment by wonfen** [comment]
和bbr没关系，检查内核是否启动

**Comment by wonfen** [comment]
> win11 24h2也有这个问题，能更新订阅，但是连接不了代理

检查内核是否启动，是否有多个进程，之前的版本是否删除干净，是否有残留内核进程。

**Comment by winloud** [comment]
> win11 24h2也有这个问题，能更新订阅，但是连接不了代理

是的。关闭BBR2就可以了。

**Comment by wonfen** [comment]
> > win11 24h2也有这个问题，能更新订阅，但是连接不了代理
> 
> 是的。关闭BBR2就可以了。

我这边打开bbr测试也正常啊，没发现和bbr有什么直接关联。

**Comment by lidonghai** [comment]
好家伙，让我研究好久，原来是BBR的问题。

> > win11 24h2也有这个问题，能更新订阅，但是连接不了代理
> 
> 是的。关闭BBR2就可以了。

**Comment by cancundeyingzi** [comment]
+1bbr的问题,
PS C:\Users\17658> netsh int tcp set supplemental template=Compat congestionprovider=CUBIC
确定。

PS C:\Users\17658> netsh int tcp set supplemental template=DatacenterCustom congestionprovider=CUBIC
确定。

PS C:\Users\17658> netsh int tcp set supplemental template=Datacenter congestionprovider=CUBIC
确定。

PS C:\Users\17658> netsh int tcp set supplemental template=InternetCustom congestionprovider=CUBIC
确定。
