### ISSUE TITLE
[BUG] 开启Tun模式，Windows错误报告占满磁盘

### ISSUE THREAD

**Issue by GitHubCloud** [clash-verge-rev/clash-verge-rev#1568]
### 问题描述 / Describe the bug

开启Tun模式，不久后发现C盘占满，用CCleaner扫描发现Windows错误报告占大多数

### 复现步骤 / To Reproduce

- Tun模式关闭，错误报告为空
![image](https://github.com/user-attachments/assets/c2e7c0f9-8d26-418e-a2b0-388dee520734)
- 打开Tun模式，错误报告迅速增长
![image](https://github.com/user-attachments/assets/0fbd820b-c3fe-4eac-a8f9-820997af82b8)
![image](https://github.com/user-attachments/assets/21f1a8f1-8a37-49bb-b0b4-c0b65e24fbe4)
![image](https://github.com/user-attachments/assets/f5f069e9-2b7e-4bd1-b9ee-4b7e3d55cbd5)
- 关闭Tun模式后扫描，错误报告文件有294个
![image](https://github.com/user-attachments/assets/127ff465-9421-45a5-8897-d540fce58aa5)
- 关闭Tun模式后3分钟，错误报告文件数量不变
![image](https://github.com/user-attachments/assets/bd8a7102-3ea4-43e4-b19f-fef04e8e47f2)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11 22621

### 日志 / Log

无

**Comment by wonfen** [comment]
这个和tun模式有啥关系？
