### ISSUE TITLE
**idea翻译插件问题 / 无法翻译成功**

### ISSUE THREAD

**Issue by tagnpeng** [clash-verge-rev/clash-verge-rev#1569]
**问题描述 / Describe the bug**
clash设置
<img width="840" alt="image" src="https://github.com/user-attachments/assets/2709bd34-b073-4962-901c-e8c9d98991c7">
<img width="840" alt="image" src="https://github.com/user-attachments/assets/e9dce918-a1bb-4719-8242-b0333feeed5c">

idea设置
<img width="982" alt="image" src="https://github.com/user-attachments/assets/12e5f86d-a01f-4b38-95c7-f4672df7a888">

**复现步骤 / To Reproduce**
<img width="232" alt="image" src="https://github.com/user-attachments/assets/faefad82-d77a-4a98-b3a4-287547d1283e">

**相关日志**
在我运行翻译软件的时候日志中是有对翻译进行代理,但是不知为何翻译错误,切到另外的代理软件却可以正常代理,不是很懂,如果有需要我提供其他信息的话可以回复我,谢谢
<img width="789" alt="image" src="https://github.com/user-attachments/assets/a3904a8b-ce06-4dda-988f-6e0c231c5b8f">

**操作系统 / OS**
mac m1

**操作系统版本 / OS Version**
14.6.1 (23G93)

_Originally posted by @tagnpeng in https://github.com/clash-verge-rev/clash-verge-rev/issues/1233#issuecomment-2291043660_

**Comment by tagnpeng** [comment]
进行上述设置后重启电脑就好了🤣

**Comment by Kareless1215** [comment]
是谁教你系统代理和tun模式一起打开的

**Comment by tagnpeng** [comment]
> 是谁教你系统代理和tun模式一起打开的
<img width="862" alt="image" src="https://github.com/user-attachments/assets/038a8b56-dad3-4215-94ab-77f7cf610c4d">
所以我是看见不行所以在乱设置的
