### ISSUE TITLE
如何对某个特定网站设置想用的线路

### ISSUE THREAD

**Issue by yuyistar** [clash-verge-rev/clash-verge-rev#157]
### Is your feature request related to a problem? Please describe.

想用gemini，但必须用美国线路，可是美国线路速度较慢，平时都用其他线路，现在我都是用切换节点的办法解决。如何设置让某个网站用某个线路呢

### Describe the solution you'd like

没有找到快速设置方法，是否可以增加一个

### Describe alternatives you've considered

是不是可以通过改配置文件实现，但我不会。能否说一下方法

**Comment by Jason1737** [comment]
配置分流规则

**Comment by wonfen** [comment]
建议学一学clash的规则编写方法。

**Comment by yuyistar** [comment]
已经学完了。搞定
