### ISSUE TITLE
[BUG] DIRECT项不执行测速

### ISSUE THREAD

**Issue by utopeadia** [clash-verge-rev/clash-verge-rev#1573]
### 问题描述 / Describe the bug

同被关闭issus: https://github.com/clash-verge-rev/clash-verge-rev/issues/1483
可能这个ISSUS写的不太明白导致误解，当测速节点中存在普通节点和DIRECT时，只会对普通节点测速而不会对DIRECT进行测速。

### 复现步骤 / To Reproduce

执行测速

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

软件逻辑issus，非配置bug

**Comment by wonfen** [comment]
是因为你的网络到 http://1.1.1.1 不通，可以在设置里杂项设置里修改测试地址。

**Comment by utopeadia** [comment]
> 是因为你的网络到 http://1.1.1.1 不通，可以在设置里杂项设置里修改测试地址。

不是网络的问题，手动配置了本地测试，仍然会跳过，DIRECT没有执行测速
![image](https://github.com/user-attachments/assets/1c1728d6-2a64-4e9a-8673-de7aff857577)
![image](https://github.com/user-attachments/assets/17320272-e1fc-4d8f-8289-d52dfa4e431e)

**Comment by dongchengjie** [comment]
这是特意这么做的

**Comment by yixiuge301** [comment]
> 是因为你的网络到 http://1.1.1.1 不通，可以在设置里杂项设置里修改测试地址。

默认是 `http://1.1.1.1` 么？这个地址被滥用了，有的会被局域网防火墙拦截重定向，这种还好能通，有的环境直接不通。

我填 url 可以不？比如
```http
http://connect.rom.miui.com/generate_204

http://wifi.vivo.com.cn/generate_204
```

**Comment by utopeadia** [comment]
> 这是特意这么做的

比较好奇这样做的目的是啥，有啥功能需要复用这个逻辑吗？我觉得应该从配置文件角度排除DIRECT出现在不想被测速的url-test组，而需要对DIRECT测速的组进行忠实测速。这样clash就可以作为分流软件而非单纯翻墙软件实现一些随网络变化切换的任务

**Comment by alexallen1** [comment]
我也想不明白为什么要用1.1.1.1.

之前用老版本猫全部正常的，在verge全部超时

**Comment by infstellar** [comment]
挖坟，今天同样的场景遇到了DIRECT不测速导致url test不能回退到DIRECT的问题，纯mihomo内核没有这个问题。

**Comment by wabxn514** [comment]
> 挖坟，今天同样的场景遇到了DIRECT不测速导致url test不能回退到DIRECT的问题，纯mihomo内核没有这个问题。

用 CVR 2.5.2+ mihomo 1.19.29 ，测速链接换成 http://www.gstatic.com/generate_204 ，也是一样的 ，direct 也是不参与测速。
CVR 这样做 是基于什么考量 ？
