### ISSUE TITLE
[BUG] 测试图标修改问题

### ISSUE THREAD

**Issue by QAbot-zh** [clash-verge-rev/clash-verge-rev#1574]
### 问题描述 / Describe the bug

测试中添加了一个不支持的 svg 后打开测试页面就会报错，不知道从界面的哪里可以修复，也尝试进入应用目录里的 verge.yaml 删除对应的 svg ，仍然报错，并且 verge.yaml 里 svg 会被恢复（可能是从数据库或者别的配置文件里恢复的？）

### 复现步骤 / To Reproduce

测试里的图标添加一个不支持的svg字符串

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10

### 日志 / Log

报错截图：
![image](https://github.com/user-attachments/assets/4b8734d3-48e6-4a36-a807-cc7603de5bab)

**Comment by wonfen** [comment]
在设置里打开应用目录，删除里面的所有文件。
