### ISSUE TITLE
[BUG] windows11使用以太网时开启代理会变慢/无法使用，而使用wlan开启代理则不会问题

### ISSUE THREAD

**Issue by roaminger** [clash-verge-rev/clash-verge-rev#1576]
### 问题描述 / Describe the bug

使用wlan开启代理没用任何问题，但如果只使用以太网时开启代理会变慢/无法使用，节点延迟测试均变成error，直连的网络均会报warn。代理的网络也会非常卡顿，仅使用以太网会出现此问题，只要关掉代理就能正常使用bilibili和github
![image](https://github.com/user-attachments/assets/368f520d-4c87-44e9-80e8-21302d1e2d43)
![image](https://github.com/user-attachments/assets/26978fcf-9d59-468e-a623-7162e5739297)

未开启代理时节点延迟正常：
![image](https://github.com/user-attachments/assets/9dbd3df6-85bd-48d2-a83e-68b452ef7f36)
开启代理后节点延迟：
![image](https://github.com/user-attachments/assets/0474cb01-ad59-4af0-9ffe-e1e34219e0da)

### 复现步骤 / To Reproduce

只使用以太网时开启代理

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11 专业版 22631.4037

### 日志 / Log

08-17 05:06:48warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/hdslb.com) 127.0.0.1:62851(chrome.exe) --> i1.hdslb.com:443 error: connect failed: dial tcp 106.63.21.198:443: i/o timeout dial tcp 106.63.21.191:443: i/o timeout dial tcp 106.63.21.249:443: i/o timeout
08-17 05:06:49warning
[TCP] dial 节点选择 (match Match/) 127.0.0.1:62860(chrome.exe) --> cloudapi.bytedance.net:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:06:51warning
[TCP] dial DIRECT (match DomainKeyword/baidu) 127.0.0.1:62866(chrome.exe) --> sp1.baidu.com:443 error: connect failed: dial tcp 220.181.38.149:443: i/o timeout dial tcp 220.181.38.150:443: i/o timeout
08-17 05:06:52warning
[TCP] dial 谷歌服务 (match DomainKeyword/google) 127.0.0.1:62870(chrome.exe) --> content-autofill.googleapis.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:06:53warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/hdslb.com) 127.0.0.1:62872(chrome.exe) --> i1.hdslb.com:443 error: connect failed: dial tcp 106.63.21.198:443: i/o timeout dial tcp 106.63.21.191:443: i/o timeout dial tcp 106.63.21.249:443: i/o timeout
08-17 05:06:53warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.com) 127.0.0.1:62874(chrome.exe) --> data.bilivideo.com:443 error: connect failed: dial tcp 122.228.237.139:443: i/o timeout dial tcp 122.228.237.168:443: i/o timeout dial tcp 218.92.137.98:443: i/o timeout dial tcp 222.188.43.119:443: i/o timeout dial tcp 222.188.43.122:443: i/o timeout dial tcp 58.220.44.51:443: i/o timeout dial tcp 61.147.106.163:443: i/o timeout dial tcp 61.147.106.217:443: i/o timeout
08-17 05:06:54warning
[TCP] dial 节点选择 (match Match/) 127.0.0.1:62881(chrome.exe) --> cloudapi.bytedance.net:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:06:55warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.cn) 127.0.0.1:62885(chrome.exe) --> xy27x128x216x20xy.mcdn.bilivideo.cn:486 error: dns resolve failed: context deadline exceeded
08-17 05:06:55warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.cn) 127.0.0.1:62896(chrome.exe) --> xy27x128x216x20xy.mcdn.bilivideo.cn:486 error: dns resolve failed: all DNS requests failed, first error: requesting https://doh.pub:443/dns-query?dns=AAABAAABAAAAAAAAEXh5Mjd4MTI4eDIxNngyMHh5BG1jZG4JYmlsaXZpZGVvAmNuAAABAAE: Get "https://doh.pub:443/dns-query?dns=AAABAAABAAAAAAAAEXh5Mjd4MTI4eDIxNngyMHh5BG1jZG4JYmlsaXZpZGVvAmNuAAABAAE": connect failed: dial tcp 1.12.12.12:443: i/o timeout dial tcp 120.53.53.53:443: i/o timeout
08-17 05:06:55warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.cn) 127.0.0.1:22676(chrome.exe) --> xy27x128x216x20xy.mcdn.bilivideo.cn:486 error: dns resolve failed: all DNS requests failed, first error: requesting https://doh.pub:443/dns-query?dns=AAABAAABAAAAAAAAEXh5Mjd4MTI4eDIxNngyMHh5BG1jZG4JYmlsaXZpZGVvAmNuAAABAAE: Get "https://doh.pub:443/dns-query?dns=AAABAAABAAAAAAAAEXh5Mjd4MTI4eDIxNngyMHh5BG1jZG4JYmlsaXZpZGVvAmNuAAABAAE": connect failed: dial tcp 1.12.12.12:443: i/o timeout dial tcp 120.53.53.53:443: i/o timeout
08-17 05:06:56warning
[TCP] dial 谷歌服务 (match DomainKeyword/google) 127.0.0.1:62888(chrome.exe) --> content-autofill.googleapis.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:06:56warning
[TCP] dial DIRECT (match DomainKeyword/baidu) 127.0.0.1:62894(chrome.exe) --> sp1.baidu.com:443 error: connect failed: dial tcp 220.181.38.149:443: i/o timeout dial tcp 220.181.38.150:443: i/o timeout
08-17 05:06:57warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.cn) 127.0.0.1:62896(chrome.exe) --> xy27x128x216x20xy.mcdn.bilivideo.cn:486 error: dns resolve failed: context deadline exceeded
08-17 05:06:57warning
[TCP] dial 节点选择 (match Match/) 127.0.0.1:62897(chrome.exe) --> github.githubassets.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:06:57warning
[TCP] dial 节点选择 (match Match/) 127.0.0.1:62899(chrome.exe) --> collector.github.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:06:57warning
[TCP] dial DIRECT (match DomainKeyword/baidu) 127.0.0.1:62903(chrome.exe) --> chat.baidu.com:443 error: connect failed: dial tcp 124.237.177.112:443: i/o timeout
08-17 05:06:57warning
[TCP] dial DIRECT (match DomainKeyword/baidu) 127.0.0.1:62907(chrome.exe) --> chat.baidu.com:443 error: connect failed: dial tcp 124.237.177.112:443: i/o timeout
08-17 05:06:57warning
[TCP] dial 谷歌服务 (match DomainKeyword/google) 127.0.0.1:62909(chrome.exe) --> content-autofill.googleapis.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:06:58warning
[TCP] dial 节点选择 (match Match/) 127.0.0.1:22659(chrome.exe) --> collector.github.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:06:58warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.com) 127.0.0.1:22662(chrome.exe) --> data.bilivideo.com:443 error: connect failed: dial tcp 122.228.237.139:443: i/o timeout dial tcp 122.228.237.168:443: i/o timeout dial tcp 218.92.137.98:443: i/o timeout dial tcp 222.188.43.119:443: i/o timeout dial tcp 222.188.43.122:443: i/o timeout dial tcp 58.220.44.51:443: i/o timeout dial tcp 61.147.106.163:443: i/o timeout dial tcp 61.147.106.217:443: i/o timeout
08-17 05:06:59warning
[TCP] dial 节点选择 (match Match/) 127.0.0.1:22664(chrome.exe) --> github.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:06:59warning
[TCP] dial 节点选择 (match Match/) 127.0.0.1:22670(chrome.exe) --> cloudapi.bytedance.net:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:06:59warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.cn) 127.0.0.1:22676(chrome.exe) --> xy27x128x216x20xy.mcdn.bilivideo.cn:486 error: dns resolve failed: context deadline exceeded
08-17 05:07:00warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.cn) 127.0.0.1:22682(chrome.exe) --> xy27x128x216x20xy.mcdn.bilivideo.cn:486 error: dns resolve failed: context deadline exceeded
08-17 05:07:00warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.cn) 127.0.0.1:22692(chrome.exe) --> xy27x128x216x20xy.mcdn.bilivideo.cn:486 error: dns resolve failed: all DNS requests failed, first error: connect failed: dial tcp 223.6.6.6:853: i/o timeout
08-17 05:07:00warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.cn) 127.0.0.1:22730(chrome.exe) --> xy27x128x216x20xy.mcdn.bilivideo.cn:486 error: dns resolve failed: all DNS requests failed, first error: connect failed: dial tcp 223.6.6.6:853: i/o timeout
08-17 05:07:01warning
[TCP] dial 谷歌服务 (match DomainKeyword/google) 127.0.0.1:22683(chrome.exe) --> content-autofill.googleapis.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:07:02warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.com) 127.0.0.1:22687(chrome.exe) --> d1--cn-gotcha204.bilivideo.com:443 error: dns resolve failed: context deadline exceeded
08-17 05:07:02warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.com) 127.0.0.1:22732(chrome.exe) --> d1--cn-gotcha204.bilivideo.com:443 error: dns resolve failed: all DNS requests failed, first error: connect failed: dial tcp 223.6.6.6:853: i/o timeout
08-17 05:07:02warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.cn) 127.0.0.1:22692(chrome.exe) --> xy27x128x216x20xy.mcdn.bilivideo.cn:486 error: dns resolve failed: context deadline exceeded
08-17 05:07:02warning
[TCP] dial 节点选择 (match Match/) 127.0.0.1:22693(chrome.exe) --> github.githubassets.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:07:02warning
[TCP] dial 节点选择 (match Match/) 127.0.0.1:22697(chrome.exe) --> collector.github.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:07:02warning
[TCP] dial DIRECT (match DomainKeyword/baidu) 127.0.0.1:22702(chrome.exe) --> chat.baidu.com:443 error: connect failed: dial tcp 124.237.177.112:443: i/o timeout
08-17 05:07:02warning
[TCP] dial DIRECT (match DomainKeyword/baidu) 127.0.0.1:22704(chrome.exe) --> chat.baidu.com:443 error: connect failed: dial tcp 124.237.177.112:443: i/o timeout
08-17 05:07:02warning
[TCP] dial 谷歌服务 (match DomainKeyword/google) 127.0.0.1:22711(chrome.exe) --> content-autofill.googleapis.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:07:03warning
[TCP] dial 节点选择 (match Match/) 127.0.0.1:22713(chrome.exe) --> collector.github.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:07:03warning
[TCP] dial 谷歌服务 (match DomainKeyword/google) 127.0.0.1:22715(chrome.exe) --> content-autofill.googleapis.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:07:04warning
[TCP] dial 节点选择 (match Match/) 127.0.0.1:22721(chrome.exe) --> github.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:07:04warning
[TCP] dial 节点选择 (match Match/) 127.0.0.1:22727(chrome.exe) --> cloudapi.bytedance.net:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:07:04warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.cn) 127.0.0.1:22730(chrome.exe) --> xy27x128x216x20xy.mcdn.bilivideo.cn:486 error: dns resolve failed: context deadline exceeded
08-17 05:07:04warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.com) 127.0.0.1:22732(chrome.exe) --> d1--cn-gotcha204.bilivideo.com:443 error: dns resolve failed: context deadline exceeded
08-17 05:07:07warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.com) 127.0.0.1:22746(chrome.exe) --> d1--cn-gotcha204.bilivideo.com:443 error: dns resolve failed: context deadline exceeded
08-17 05:07:07warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.com) 127.0.0.1:22772(chrome.exe) --> d1--cn-gotcha204.bilivideo.com:443 error: dns resolve failed: all DNS requests failed, first error: connect failed: dial tcp 223.5.5.5:853: i/o timeout
08-17 05:07:07warning
[TCP] dial 谷歌服务 (match DomainKeyword/google) 127.0.0.1:22750(chrome.exe) --> content-autofill.googleapis.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:07:08warning
[TCP] dial 谷歌服务 (match DomainKeyword/google) 127.0.0.1:22757(chrome.exe) --> content-autofill.googleapis.com:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:07:09warning
[TCP] dial 节点选择 (match Match/) 127.0.0.1:22763(chrome.exe) --> cloudapi.bytedance.net:443 error: yes.cnmjcn.net:16617 connect error: connect failed: dial tcp 116.162.172.120:16617: i/o timeout
08-17 05:07:09warning
[TCP] dial 哔哩哔哩 (match DomainSuffix/bilivideo.com) 127.0.0.1:22772(chrome.exe) --> d1--cn-gotcha204.bilivideo.com:443 error: dns resolve failed: context deadline exceeded

**Comment by wonfen** [comment]
检查下你的本地连接，是否用了tun模式？

**Comment by roaminger** [comment]
无论打开或者关闭clash verge的tun模式，无论使用全局规则还是直连，只要是使用以太网，在观看bilibili直播时一打开系统代理就会卡住，切换成无线就不会有问题

**Comment by wonfen** [comment]
怎么看都像你电脑的问题。

**Comment by roaminger** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1502#issuecomment-1308725276 因为网络适配器里无线是英文名的wifi名，网线是中文名”以太网“，改成英文就可以连接了！

**Comment by roaminger** [comment]
使用网线连接和无线连接工作方式不一样，同样使用直连，无线的延迟是20ms，网线的延迟是60ms（不开代理就是10-20ms），而且直连网线速度非常不稳定，无线一直是跑满的
