### ISSUE TITLE
[BUG] 开启Vscode Remote无法使用

### ISSUE THREAD

**Issue by Zrzzzz** [clash-verge-rev/clash-verge-rev#1577]
### 问题描述 / Describe the bug

开启一个remote连接，流量不会走clash verge

### 复现步骤 / To Reproduce

如上

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11

### 日志 / Log

无

**Comment by wonfen** [comment]
检查配置和分流规则。
