### ISSUE TITLE
[BUG] 无法正常打开，有闪退现象，可能是因为误删文件

### ISSUE THREAD

**Issue by DreamersPrime** [clash-verge-rev/clash-verge-rev#1578]
### 问题描述 / Describe the bug

因删除了一些文件，现在一打开就立刻闪退，无任何提示，windows报错日志如下

### 复现步骤 / To Reproduce

不详

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10

### 日志 / Log

Version=1
EventType=BEX64
EventTime=133683828093277963
ReportType=2
Consent=1
UploadTime=133683828626089757
ReportStatus=100
ReportIdentifier=8b0f054a-49ed-45ed-824f-4abb86a7f561
IntegratorReportIdentifier=39492470-2243-4a88-b221-cc63095d7ddd
Wow64Host=34404
NsAppName=Clash Verge.exe
AppSessionGuid=00000b8c-0001-0078-b06e-0fbcbbf0da01
TargetAppId=W:0006e0481780991bfad78dfea8a3e9d0234700000000!000055993b7bf59aa6931cf30bbfbc9cab36822ddafb!Clash Verge.exe
TargetAppVer=2024//07//30:01:17:36!0!Clash Verge.exe
BootId=4294967295
TargetAsId=567
UserImpactVector=48
IsFatal=1
EtwNonCollectReason=1
Response.type=4
Sig[0].Name=应用程序名
Sig[0].Value=Clash Verge.exe
Sig[1].Name=应用程序版本
Sig[1].Value=1.7.5.0
Sig[2].Name=应用程序时间戳
Sig[2].Value=66a83f30
Sig[3].Name=故障模块名称
Sig[3].Value=Clash Verge.exe
Sig[4].Name=故障模块版本
Sig[4].Value=1.7.5.0
Sig[5].Name=故障模块时间戳
Sig[5].Value=66a83f30
Sig[6].Name=异常偏移
Sig[6].Value=0000000000633b96
Sig[7].Name=异常代码
Sig[7].Value=c0000409
Sig[8].Name=异常数据
Sig[8].Value=0000000000000007
DynamicSig[1].Name=OS 版本
DynamicSig[1].Value=10.0.19045.2.0.0.256.48
DynamicSig[2].Name=区域设置 ID
DynamicSig[2].Value=2052
DynamicSig[22].Name=其他信息 1
DynamicSig[22].Value=6aa6
DynamicSig[23].Name=其他信息 2
DynamicSig[23].Value=6aa6e254b9211f0ecccf844dc09c50d1
DynamicSig[24].Name=其他信息 3
DynamicSig[24].Value=f39b
DynamicSig[25].Name=其他信息 4
DynamicSig[25].Value=f39b92d57f15decb362bac59ce82a2b1
UI[2]=D:\Clash Verge\Clash Verge.exe
LoadedModule[0]=D:\Clash Verge\Clash Verge.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\SYSTEM32\apphelp.dll
LoadedModule[5]=C:\Windows\System32\user32.dll
LoadedModule[6]=C:\Windows\System32\win32u.dll
LoadedModule[7]=C:\Windows\System32\GDI32.dll
LoadedModule[8]=C:\Windows\System32\gdi32full.dll
LoadedModule[9]=C:\Windows\System32\msvcp_win.dll
LoadedModule[10]=C:\Windows\System32\ucrtbase.dll
LoadedModule[11]=C:\Windows\System32\ws2_32.dll
LoadedModule[12]=C:\Windows\System32\RPCRT4.dll
LoadedModule[13]=C:\Windows\System32\shell32.dll
LoadedModule[14]=C:\Windows\System32\advapi32.dll
LoadedModule[15]=C:\Windows\System32\msvcrt.dll
LoadedModule[16]=C:\Windows\System32\sechost.dll
LoadedModule[17]=C:\Windows\System32\bcrypt.dll
LoadedModule[18]=C:\Windows\System32\ole32.dll
LoadedModule[19]=C:\Windows\System32\combase.dll
LoadedModule[20]=C:\Windows\System32\crypt32.dll
LoadedModule[21]=C:\Windows\System32\oleaut32.dll
LoadedModule[22]=C:\Windows\System32\psapi.dll
LoadedModule[23]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.4355_none_60b8b9eb71f62e16\comctl32.dll
LoadedModule[24]=C:\Windows\SYSTEM32\pdh.dll
LoadedModule[25]=C:\Windows\SYSTEM32\dwmapi.dll
LoadedModule[26]=C:\Windows\SYSTEM32\iphlpapi.dll
LoadedModule[27]=C:\Windows\SYSTEM32\secur32.dll
LoadedModule[28]=C:\Windows\SYSTEM32\powrprof.dll
LoadedModule[29]=C:\Windows\SYSTEM32\wininet.dll
LoadedModule[30]=C:\Windows\SYSTEM32\uxtheme.dll
LoadedModule[31]=C:\Windows\SYSTEM32\CRYPTBASE.DLL
LoadedModule[32]=C:\Windows\SYSTEM32\SSPICLI.DLL
LoadedModule[33]=C:\Windows\System32\IMM32.DLL
LoadedModule[34]=C:\Windows\SYSTEM32\UMPDC.dll
LoadedModule[35]=C:\Windows\System32\bcryptprimitives.dll
LoadedModule[36]=C:\Windows\SYSTEM32\windows.storage.dll
LoadedModule[37]=C:\Windows\SYSTEM32\Wldp.dll
LoadedModule[38]=C:\Windows\System32\SHCORE.dll
LoadedModule[39]=C:\Windows\System32\shlwapi.dll
LoadedModule[40]=C:\Windows\system32\mswsock.dll
LoadedModule[41]=C:\Windows\System32\MSCTF.dll
LoadedModule[42]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[43]=C:\Windows\System32\clbcatq.dll
LoadedModule[44]=C:\Windows\system32\explorerframe.dll
LoadedModule[45]=C:\Windows\system32\dataexchange.dll
LoadedModule[46]=C:\Windows\system32\d3d11.dll
LoadedModule[47]=C:\Windows\system32\dcomp.dll
LoadedModule[48]=C:\Windows\system32\dxgi.dll
LoadedModule[49]=C:\Windows\system32\twinapi.appcore.dll
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=19045
OsInfo[3].Key=ubr
OsInfo[3].Value=4651
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=2052
OsInfo[7].Key=geoid
OsInfo[7].Value=45
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=222803507
OsInfo[15].Key=osinsty
OsInfo[15].Value=2
OsInfo[16].Key=iever
OsInfo[16].Value=11.3636.19041.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=8096
OsInfo[19].Key=svolsz
OsInfo[19].Value=120
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=191206
OsInfo[22].Key=bldtm
OsInfo[22].Value=1406
OsInfo[23].Key=bldbrch
OsInfo[23].Value=vb_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.19041.4651.amd64fre.vb_release.191206-1406
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=MD:283BAEF,ME:2E3922F,ME:2E30985,MD:2E30A2A
OsInfo[34].Key=fconid
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
File[0].CabName=WERInternalMetadata.xml
File[0].Path=WER4606.tmp.WERInternalMetadata.xml
File[0].Flags=327682
File[0].Type=5
File[0].Original.Path=\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4606.tmp.WERInternalMetadata.xml
FriendlyEventName=已停止工作
ConsentKey=BEX64
AppName=A Clash Meta GUI based on tauri.
AppPath=D:\Clash Verge\Clash Verge.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=BCC4EE82C055A96CC3F5032CD9C74BC5
MetadataHash=369852363

**Comment by wonfen** [comment]
重新安装试试
