### ISSUE TITLE
kde waland模式出现两个程序控制按钮

### ISSUE THREAD

**Issue by Alantemper** [clash-verge-rev/clash-verge-rev#1579]
### 问题描述 / Describe the bug

opensuse风滚草，在kde6.14上，会出现kde自带的窗口标题栏和边框，导致出现两个“最小化”“最大化”“关闭”按钮。![IMG_20240818_093422.png](https://github.com/user-attachments/assets/4d7967d9-b3cd-446d-a7ce-a19a2203f6e1)

### 复现步骤 / To Reproduce

在kde6 wayland模式下打开应用程序

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

opensuse tumbleweed 20240816   桌面环境:kde6 Qt6.7.2 Wayland模式 

### 日志 / Log

无

**Comment by wonfen** [comment]
正常的，无须理会。

**Comment by Alantemper** [comment]
> 正常的，无须理会。

所以为什么会这样呢，xorg(x11)环境就没有这个问题
