### ISSUE TITLE
[BUG] 启动几小时后，系统代理无法启动

### ISSUE THREAD

**Issue by geilige** [clash-verge-rev/clash-verge-rev#1581]
### 问题描述 / Describe the bug

win10，打开软件几个小时，右下角选择系统代理，不生效，且图标不改变；打开界面，勾选系统代理，切换菜单，照样无效

### 复现步骤 / To Reproduce

win10，打开软件几个小时

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

无

**Comment by lonznt** [comment]
哎？ 我还真没碰到过这种奇怪的现象。

**Comment by nv100** [comment]
我在Win11也遇到类似问题，有时是一打开软件就发生，明明点了开启代理，但实际并未开启代理，想退出重启也不行，必须在任务管理器中强制关闭clash verge rev进程，重启电脑可解决此问题。另外Linux上无此问题。

**Comment by lhjgege** [comment]
我时常遇到只要开启代理时间久了就就会很卡，时常出现切换代理图标不会改变，点击退出应用也没反应。要到任务管理器去关闭进程。

**Comment by wonfen** [comment]
检查是否安装了其他代理软件导致的冲突。

**Comment by Bigjjdick** [comment]
我遇到一个很奇怪的问题，我原本是win10升级win11后使用某机场，使用有规则显示”initial rule provider openai error，使用无规则就能正常上网（全局代理）。使用过程中ytb等都没问题，但是一会过后会出现阅览器打开新标签随便搜索内容会出现无法访问此页面似乎关闭了连接。然后再次打开ytb的时候会出现你没有联网请检查网络连接，此时telegram和X事故正常的。其他的全都打不开

**Comment by younijiuhao876** [comment]
可以上网吗，跑裸核看看。

**Comment by Canda15** [comment]
> 可以上网吗，跑裸核看看。

可以继续用，只不过无法切换，无法退出clash。
#1110
