### ISSUE TITLE
[BUG] Fedora dnf check   Error: Check discovered 2 problem(s)

### ISSUE THREAD

**Issue by pp1992m** [clash-verge-rev/clash-verge-rev#1582]
### 问题描述 / Describe the bug

The package works well. But when run "dnf check", dnf will report problems.
sudo dnf check
clash-verge-1.7.6-1.x86_64 has installed conflict "clash-verge": clash-verge-1.7.6-1.x86_64
clash-verge-1.7.6-1.x86_64 is obsoleted by clash-verge-1.7.6-1.x86_64
Error: Check discovered 2 problem(s)

### 复现步骤 / To Reproduce

Install rpm package, and run "sudo dnf check"

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Fedora 40  Lxqt

### 日志 / Log

sudo dnf check
clash-verge-1.7.6-1.x86_64 has installed conflict "clash-verge": clash-verge-1.7.6-1.x86_64
clash-verge-1.7.6-1.x86_64 is obsoleted by clash-verge-1.7.6-1.x86_64
Error: Check discovered 2 problem(s)

**Comment by wonfen** [comment]
这个不是报和之前安装的冲突了么？

**Comment by pp1992m** [comment]
> 这个不是报和之前安装的冲突了么？
但第一次安装也有这个问题，彻底删除然后重新安装也有这个问题。安装本身没有问题和报错，但是“dnf check"会报错，会不会是rpm打包的问题？
