### ISSUE TITLE
[BUG] 每次更新都安装到C盘

### ISSUE THREAD

**Issue by xjzyy** [clash-verge-rev/clash-verge-rev#1583]
### 问题描述 / Describe the bug

每次更新都安装到C盘

### 复现步骤 / To Reproduce

每次更新都安装到C盘

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

每次更新都安装到C盘

**Comment by wonfen** [comment]
之前老版本的便携版有这个问题，最新版已经修复。
检查是否有注册表残留。
