### ISSUE TITLE
为什么切换订阅很慢

### ISSUE THREAD

**Issue by wangzainn** [clash-verge-rev/clash-verge-rev#1585]
### 问题描述 / Describe the bug

clash-verge-rev是1.7.6

总体感觉这个软件都偏慢，打开也慢，切换订阅一直转圈，有点慢。

之前用的clash for windows，今天换clash-verge-rev，相比这个慢不少。有办法优化一下么

另外这个名字可以改一个，比如订阅配置、编辑订阅等等，编辑信息老点错了。个人感觉名称不是很望文生义，也可能我刚用，不熟。
![image](https://github.com/user-attachments/assets/de0a0514-df91-42f6-ab9c-24415d6553e8)

### 复现步骤 / To Reproduce

正常使用，打开软件，点菜单。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 latest

### 日志 / Log

无

**Comment by wonfen** [comment]
切换订阅慢的原因是配置文件里载入了远程文件(geodata等)，需要等远程文件下载完成才会切换完成。

**Comment by deepinsc2020** [comment]
你回退到1.6.6版本后就快了，1.7版本是各种慢

**Comment by yixiuge301** [comment]
> 切换订阅慢的原因是配置文件里载入了远程文件(geodata等)，需要等远程文件下载完成才会切换完成。

仅是因为下载完成才切换完成么？

那有没有可能把 “远程文件(geodata等)” 缓存一下，像所说的 geodata 这种是所有共用的配置吧，换订阅不用每次都下载。对于如果订阅里有引用规则要下载的，那也是首次需要下载，后面就用缓存的。

所有缓存文件定时更新，总之尽可能的提速呢。

**Comment by daitou05** [comment]
@wonfen 为啥任务栏打开也很慢嘞，点这个图标打开应用感觉反应迟钝
![image](https://github.com/user-attachments/assets/6423ff9e-eddb-4441-aa70-06fd6a7b73fb)

**Comment by woodenpi** [comment]
同样的问题，win10系统 1.7.7版本，切换订阅、转换各种状态，比如开启/关闭tun，开关服务模式，开关系统代理，切换内核等等，都会卡一会儿，切换订阅时还有转圈提示，其他的也没有提示，此时如果做了别的操作会有报错的可能，希望后续版本可以优化这个问题

**Comment by tonyzhou777** [comment]
> 你回退到1.6.6版本后就快了，1.7版本是各种慢

确实，目前只能回退到1.6.6版本，秒切订阅。

希望作者能改进。
