### ISSUE TITLE
[BUG] 1.7.6 for macOS 在查看连接信息时界面大小超出可视范围

### ISSUE THREAD

**Issue by Xuu6770** [clash-verge-rev/clash-verge-rev#1586]
### 问题描述 / Describe the bug

在`连接` Tab 中查看某个进程的连接信息时，若进程名称过长，则会出现窗口的宽度超出可视范围的情况。
<img width="1278" alt="截屏2024-08-18" src="https://github.com/user-attachments/assets/a8dd21b0-d52d-4ba8-b96f-124f147c6f04">

### 复现步骤 / To Reproduce

在`连接` Tab 中选择某个名称过长的进程。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS Sonoma 14.6.1

### 日志 / Log

并非功能性故障，是否可以不提供日志？

**Comment by wonfen** [comment]
这部分UI没有做换行处理，以后慢慢改进。

**Comment by wonfen** [comment]
今天测试了下，没问题啊，会自动换行：
<img width="972" alt="image" src="https://github.com/user-attachments/assets/fc373d5d-c4f7-4b60-8ec4-b55c49d38e37">

**Comment by Xuu6770** [comment]
> 今天测试了下，没问题啊，会自动换行： <img alt="image" width="972" src="https://private-user-images.githubusercontent.com/96291150/360012258-fc373d5d-c4f7-4b60-8ec4-b55c49d38e37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjMwNjUsIm5iZiI6MTcyNDMyMjc2NSwicGF0aCI6Ii85NjI5MTE1MC8zNjAwMTIyNTgtZmMzNzNkNWQtYzRmNy00YjYwLThlYzQtYjU1YzQ5ZDM4ZTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwMzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZDk2NWYxYTExNDQwNzlhZTE4NWRiMzA3ZTQwNDU4YTE4NzczZDU5NWY2Y2JiNjk1M2VhMzZkYTdmYWQyOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cnJADG0099_HLvCqwG8S0oyY0MqGF9y641HNv35y0dA">

我今天更新了 1.7.7 ，还是会这样，具体的域名和进程名称如图所示：
![截屏2024-08-22 18 32 16](https://github.com/user-attachments/assets/816ada6e-1817-4200-a89a-9fb3c4e00ab9)
为了能完整展示，我把 app 最大化了，但是缩小后仍然会出现上面的问题😭
不过也不影响使用，大佬有空的时候再看看就好了，辛苦了，谢谢。
