### ISSUE TITLE
[BUG] 热键设置无效

### ISSUE THREAD

**Issue by Typhoon-git** [clash-verge-rev/clash-verge-rev#1587]
### 问题描述 / Describe the bug

设置tun模式热键 按键无效

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 23H2 22631.4037

### 日志 / Log

无

**Comment by wonfen** [comment]
无法复现，检查是否与其他热键设置冲突。
