### ISSUE TITLE
[BUG]局域网无法连接7890端口

### ISSUE THREAD

**Issue by dankor5** [clash-verge-rev/clash-verge-rev#159]
### Describe the bug

求教各位大佬，我好多软件包括手机无法直接连接7890端口求教怎么解决，连接就显示远程主机拒绝连接

### To Reproduce

我换回Clash Verge [zzzgydi]大佬的老版本又可以连接，但是新版这个无法连接。

### Platform

Windows

### System Version

windows,安卓

### Software Version

1.4.5

**Comment by wonfen** [comment]
新版本换端口了，看设置里有端口显示。是7897

**Comment by dankor5** [comment]
感谢大佬解答，自己实在太愚笨了。近在眼前的问题都没有注意。实在不好意思。
