### ISSUE TITLE
[BUG] 英文模式下托盘图标中 Current Profile 为空

### ISSUE THREAD

**Issue by Ins1nuatE** [clash-verge-rev/clash-verge-rev#1592]
### 问题描述 / Describe the bug

英文模式下托盘图标中 Current Profile 为空

### 复现步骤 / To Reproduce

必现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 23H2

### 日志 / Log

None

**Comment by wonfen** [comment]
fix: https://github.com/clash-verge-rev/clash-verge-rev/commit/aa8f6f4ad689fe96754ae3eb6ee341901fb0288b
