### ISSUE TITLE
[BUG] 系统代理无法关闭

### ISSUE THREAD

**Issue by earthmoon** [clash-verge-rev/clash-verge-rev#1593]
### 问题描述 / Describe the bug

您好，
在设置中可以将系统代理关闭，但是其他再跳回设置，仍旧显示系统代理是开启状态。
谢谢！

### 复现步骤 / To Reproduce

详见该视频
https://1drv.ms/v/s!AkYaWBjatjEIgplhpr4cXbqdZnGNwg?e=snZtg5

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 24H2

### 日志 / Log

我该怎么导出这个log？

**Comment by wonfen** [comment]
检查是否安装了其他代理软件导致冲突。

**Comment by earthmoon** [comment]
确实安装了。谢谢！
