### ISSUE TITLE
[BUG] 安装新版本的时候，提示无法终止Clash Verge。请关闭后重试，我已经确认Clash Verge已经不再运行

### ISSUE THREAD

**Issue by coolbreeze1093** [clash-verge-rev/clash-verge-rev#1596]
### 问题描述 / Describe the bug

正常更新程序的时候提示程序正在运行，无法安装。
然后我把程序结束，手动下载安装包进行安装依然提示正在运行。
手动卸载已安装的Clash Verge，提示Clash Verge正在运行无法卸载。
手动删除Clash Verge的安装文件夹，然后关机重启，安装新版本依然提示Clash Verge正在运行。

### 复现步骤 / To Reproduce

正常更新程序，或者手动安装新的程序

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 23H2

### 日志 / Log

![微信截图_20240820092442](https://github.com/user-attachments/assets/55447777-b295-40aa-8543-3cb352dc22b1)
![image](https://github.com/user-attachments/assets/a7cc42d4-1a02-4e16-bb0a-c3f3535fa068)

**Comment by wonfen** [comment]
检查是否有老版本的进程残留。

**Comment by coolbreeze1093** [comment]
主要是哪些进程名称，进程里面已经没有clash相关的字眼了

**Comment by coolbreeze1093** [comment]
找到问题了，有一个Clash Verge.exe，打开详细信息才会看到，而且不能结束

**Comment by coolbreeze1093** [comment]
找到问题了，有一个Clash Verge.exe，打开详细信息才会看到，而且不能结束，点结束会报拒绝访问

**Comment by coolbreeze1093** [comment]
安装火绒以后，这个问题就解决了

**Comment by adamchatgpt3** [comment]
请问安装火绒之后如何解决的

**Comment by ShadowEmbrace** [comment]
删除所有卫士之类的软件之后再试，反正我没有任何卫士之类的东西，就用win10自带防火墙一切正常

> 请问安装火绒之后如何解决的

**Comment by Yinzuoka** [comment]
大佬请问这个该怎么办呢

**Comment by LFG12** [comment]
我也遇到了这个问题

**Comment by coolbreeze1093** [comment]
我记得当时是安装了杀毒软件，然后修复了一下电脑就好了

Foggy ***@***.***> 于2025年11月4日周二 17:01写道：

**Comment by Aphrodite-deepblue** [comment]
蛙趣兄弟，下了个火绒，那个进程真的就自己没了，现在终于是装回来了，爱你~

**Comment by Aphrodite-deepblue** [comment]
> 我也遇到了这个问题

哥们，下个火绒，然后用火绒排查一遍之后就重启，直接ok

**Comment by userHanlh** [comment]
更简单的方式，直接重启，不要打开clash，直接到github安装clash

**Comment by Chasing-Aurora** [comment]
虚拟网卡，系统代理，开机自启，静默启动 先四个全关闭
然后在 services.msc中关闭Clash Verge Service
在任务管理器“详细信息”关闭下面三个：
clash-verge.exe
clash-verge-service.exe
verge-mihomo.exe
就可以啦⭐
