### ISSUE TITLE
[Feature] rule-providers支持mrs格式文件

### ISSUE THREAD

**Issue by Become-ILLUSORY** [clash-verge-rev/clash-verge-rev#1597]
### 功能描述 / Feature description

  ai:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/ai.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/ai.mrs"
    interval: 86400
    
    
    
    目前不支持mrs

### 使用场景 / Use case

  ai:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/ai.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/ai.mrs"
    interval: 86400
    
    
    
    目前不支持mrs

**Comment by xishang0128** [comment]
目前支持
