### ISSUE TITLE
怎么配置全局规则

### ISSUE THREAD

**Issue by wcxxxxx** [clash-verge-rev/clash-verge-rev#160]
因为公司内网域名有点特殊，开启规则模式后，内网域名还是走代理了

比如:内网域名为baidu.lo，我怎么设置baidu.lo不走代理

**Comment by shitouuuuu** [comment]
[PASS](https://wiki.metacubex.one/config/proxy-groups/built-in/#pass)[¶](https://wiki.metacubex.one/config/proxy-groups/built-in/#pass)
绕过,会使匹配规则时跳过此规则


rules:
- DOMAIN,baidu.lo,PASS

**Comment by wcxxxxx** [comment]
> [PASS](https://wiki.metacubex.one/config/proxy-groups/built-in/#pass)[¶](https://wiki.metacubex.one/config/proxy-groups/built-in/#pass) 绕过，会使匹配规则时跳过此规则
> 
> 并且最好靠前放下面条规则。
> 
> 规则：
> 
> * 域名，baidu.lo，PASS

请问在那个文件里进行更改呀

**Comment by shitouuuuu** [comment]
> > [PASS](https://wiki.metacubex.one/config/proxy-groups/built-in/#pass)[¶](https://wiki.metacubex.one/config/proxy-groups/built-in/#pass) 绕过，会使匹配规则时跳过此规则
> > 并且最好靠前放下面条规则。
> > 规则：
> > 
> > * 域名，baidu.lo，PASS
> 
> 请问在那个文件里进行更改呀

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/55572093/4c2178f8-41c7-4659-a8f4-80e459568b96)

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/55572093/98df5a5d-1875-4391-ae89-fa7a7f529863)

**Comment by wcxxxxx** [comment]
> > > [PASS](https://wiki.metacubex.one/config/proxy-groups/built-in/#pass)[¶](https://wiki.metacubex.one/config/proxy-groups/built-in/#pass) 绕过，会使匹配规则时跳过此规则
> > > 并且最好靠前放下面条规则。
> > > 规则：
> > > 
> > > * 域名，baidu.lo，PASS
> > 
> > 
> > 请问在那个文件里进行更改呀
> 
> ![image](https://private-user-images.githubusercontent.com/55572093/292159746-4c2178f8-41c7-4659-a8f4-80e459568b96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTE2MzQsIm5iZiI6MTcwMzE1MTMzNCwicGF0aCI6Ii81NTU3MjA5My8yOTIxNTk3NDYtNGMyMTc4ZjgtNDFjNy00NjU5LWE4ZjQtODBlNDU5NTY4Yjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA5MzUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOTFlYWRjMzcxM2UwNzc2OWViMzA2NGQ2NzBlN2Y2MjViMWFiNzEzN2ZlNDcxYzc5YzJiZThiOWE1ZjNlZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kLgw_hamw72nMUVtUg2uZYeFY9PcqS8w6fj0-AXsl3I)
> 
> ![image](https://private-user-images.githubusercontent.com/55572093/292160149-98df5a5d-1875-4391-ae89-fa7a7f529863.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTE2MzQsIm5iZiI6MTcwMzE1MTMzNCwicGF0aCI6Ii81NTU3MjA5My8yOTIxNjAxNDktOThkZjVhNWQtMTg3NS00MzkxLWFlODktZmE3YTdmNTI5ODYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA5MzUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MjI3NjdhNzBiNmI3OTMzNTFmMmFkMGY5NzQzOWNkMGFmNzk5ZjgwNWMxMWI2ZDA2ZDJmZjJlNTk2NDdjMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eAJFBtvdCX59SAkkS-p7qGOOseeLa0nGlUqmFu8WOg8)

我是使用订阅地址，这样得话更新后就没了

**Comment by shitouuuuu** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/55572093/e305d2c8-6120-4e53-b24d-d8266a17f4cc)

新建一个merge配置，不怕更新刷走。
direct可以的话用direct吧。
写在prepend-proxies:下面

参考[Merge 合并处理](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86)
