### ISSUE TITLE
Clash无法导入cloudflare Pages节点

### ISSUE THREAD

**Issue by dddsxk** [clash-verge-rev/clash-verge-rev#1603]
### 问题描述 / Describe the bug

![屏幕截图 2024-08-21 111628](https://github.com/user-attachments/assets/3c3f4905-f0c1-4029-99c1-67f44b8a4166)

### 复现步骤 / To Reproduce

在pages里复制clash订阅地址

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

![Uploading 屏幕截图 2024-08-21 111628.jpg…]()

**Comment by wonfen** [comment]
检查你的订阅配置文件。

**Comment by dddsxk** [comment]
是个vless，为什么不行

**Comment by Louis24** [comment]
> 是个vless，为什么不行

我知道了 哈哈哈
