### ISSUE TITLE
[BUG] Linux 64，安装clash verge rev后无可视化显示

### ISSUE THREAD

**Issue by linqing-Hu** [clash-verge-rev/clash-verge-rev#1604]
### 问题描述 / Describe the bug

`dpkg -i `正常安装 `clash-verge_1.7.6_amd64.deb`后，出现`clash`图标，但点击后无反应。

### 复现步骤 / To Reproduce

1. 安装: ` sudo dpkg -i clash-verge_1.7.6_amd64.deb `
2. 报错，补充依赖项:  
`sudo apt update`
`sudo apt -y install libayatana-indicator3-7 libayatana-appindicator3-1`
3. 继续安装，正常运行:  ` sudo dpkg -i clash-verge_1.7.6_amd64.deb `

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

18.04 LTS

### 日志 / Log

依赖报错：`忘截图了。。。但安装依赖后正常安装了`
现在的问题：clash图标点击后无反应。

**Comment by dancininmyheart** [comment]
去/usr/bin找到应用，然后用命令行启动，后面加上--no-sandbox
我是这样解决的
