### ISSUE TITLE
[BUG] 用有线网没问题，一连wifi，csdn就打不开了不知道怎么回事，退出clash verge后又可以。。。

### ISSUE THREAD

**Issue by Dontla** [clash-verge-rev/clash-verge-rev#1605]
### 问题描述 / Describe the bug

有线网没问题，一连wifi，csdn就打不开了不知道怎么回事，退出clash verge后又可以。。。

### 复现步骤 / To Reproduce

有线网没问题，一连wifi，csdn就打不开了不知道怎么回事，退出clash verge后又可以。。。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

无

**Comment by fyhzc** [comment]
重启clash：不关软件但内核重启
重启应用：重启软件

**Comment by younijiuhao876** [comment]
其他网站有问题没有？可能跟代理没关系，也许是运营商和csdn之间的问题。
之前手机流量csdn打不开，宽带的链路就行，都是电信，都没开代理。csdn说dns问题，其实没问题，流量的时候也解析出dns了，把图发给客服后，没声音了。。。

**Comment by JackloveJam** [comment]
这明显就是DNS解析的问题。
如果你连WiFi有问题，那就给它手动设置DNS地址。包括clash里的DNS也可以修改看看使用效果。
---
>前不久设置的国外DNS，导致我WeGame登陆LOL都是连接失败😅

**Comment by Dontla** [comment]
> 其他网站有问题没有？可能跟代理没关系，也许是运营商和csdn之间的问题。 之前手机流量csdn打不开，宽带的链路就行，都是电信，都没开代理。csdn说dns问题，其实没问题，流量的时候也解析出dns了，把图发给客服后，没声音了。。。

有，百度也有问题，其他网站我倒没太注意，因为我用的最频繁的是百度和csdn，我的笔记本（连的wifi）上一开启clash verge这俩网站就要请求很久才会有响应，关掉clash verge就好了，变正常。我的台式电脑连的有线网没问题，不知道为啥

**Comment by yuan051227-ops** [comment]
为什么我的clash用有线网的时候打不开系统代理，但是用无线网的时候就可以呢，我的版本是最新的，我也按照使用文档里面的去下载了运行库，还是不行
