### ISSUE TITLE
[BUG] clash-verge-rev 应用内网络连接不走代理的吗？

### ISSUE THREAD

**Issue by yixiuge301** [clash-verge-rev/clash-verge-rev#1608]
### 问题描述 / Describe the bug

更新发现好慢
![image](https://github.com/user-attachments/assets/dafb6325-1051-4fe0-acef-f7fbfd312326)
![image](https://github.com/user-attachments/assets/fc6dda7d-31f5-4671-8117-381c29483483)
![image](https://github.com/user-attachments/assets/ed2bdf00-6834-4a48-b3ef-69067e561b86)

浏览器下载满速（宽带20Mbps）
![image](https://github.com/user-attachments/assets/9e4a4e04-0e52-42bb-94da-5e956c186e9f)

之前订阅导入不了，看着也是网络的问题，浏览器可以打开订阅链接 https://github.com/clash-verge-rev/clash-verge-rev/issues/1518

### 复现步骤 / To Reproduce

更新客户端

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log
![image](https://github.com/user-attachments/assets/a597150d-81ff-4919-a9c0-64612f1bf349)

**Comment by yixiuge301** [comment]
更新时，连接这个位置能显示对应的连接么？
![image](https://github.com/user-attachments/assets/c1e421bb-4bab-4970-837a-d5254ace9a50)

**Comment by fyhzc** [comment]
右下角，系统代理打勾。全局模式打勾。再更新。让更新走代理

**Comment by yixiuge301** [comment]
> 右下角，系统代理打勾。全局模式打勾。再更新。让更新走代理

你要不要再看一遍问的是啥

**Comment by Xuu6770** [comment]
我也很纳闷，开系统代理没用，开 TUN 也没用。

**Comment by daitou05** [comment]
到发布页下载再安装吧。不过这个设计逻辑有点问题，既然都用这个了应用了，为什么要多此一举用镜像站呢？至少我个人倾向访问直链

**Comment by yixiuge301** [comment]
> 我也很纳闷，开系统代理没用，开 TUN 也没用。

开tun应该是可以的吧，我没试过。tun 不是接管了出口网卡的所有流量，走代理了吗，看内核日志了没。

**Comment by utopeadia** [comment]
> 我也很纳闷，开系统代理没用，开 TUN 也没用。

tun严格路由试试

**Comment by wonfen** [comment]
因为项目流量太大，ghproxy把本项目屏蔽了，已经改了：https://github.com/clash-verge-rev/clash-verge-rev/commit/d45929c604ef66985429c21fd350bc2a7f3d87d5

**Comment by younijiuhao876** [comment]
> 因为项目流量太大，ghproxy把本项目屏蔽了，已经改了：[d45929c](https://github.com/clash-verge-rev/clash-verge-rev/commit/d45929c604ef66985429c21fd350bc2a7f3d87d5)

应用内的连接是不走内核代理么，才考虑用镜像站？
