### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 942041294** [clash-verge-rev/clash-verge-rev#161]
### Describe the bug

从1.4.4升级到1.4.5的时候，提示无法终止那个服务，我任务管理器强制关闭之后，安装上1.4.5后，点代理模式怎么都上不了网，我把我能找到的带clash的都删干净了，还是无法代理，但是我的WIN10电脑就可以正常更新到1.4.5

### To Reproduce

无法再现

### Platform

Windows

### System Version

W11 23H2 22631.2861

### Software Version

1.4.5

**Comment by wonfen** [comment]
看FAQ：https://github.com/clash-verge-rev/clash-verge-rev/issues/125

**Comment by 942041294** [comment]
> 看FAQ：#125

哎，里面没有类似的问题，可以连上代理但是网页显示ERR_CONNECTION_CLOSED，其他软件订阅都正常

**Comment by 942041294** [comment]
> 看FAQ：#125

我注意到，浏览器无法使用，但是软件的代理都正常，chrome和edge都上不去网了

**Comment by wonfen** [comment]
现在问题解决了么？

**Comment by 942041294** [comment]
> 现在问题解决了么？
我之前描述不对，是代理之后访问google.com失败，提示ERR_CONNECTION_CLOSED
但是Clash for Flutter这款软件就可以正常访问谷歌
