### ISSUE TITLE
[Feature] “订阅” -> "全局扩展脚本"， 目前可以本地编辑，希望可以支持订阅方式

### ISSUE THREAD

**Issue by wjx0912** [clash-verge-rev/clash-verge-rev#1612]
### 功能描述 / Feature description

因为有多台电脑：每次这个脚本编辑后，需要手动拷贝到其它电脑上。过程很痛苦。
希望能支持订阅方式，比如设置到gist网址，然后xx分钟同步一次。
万分感谢

（“订阅” -> "全局扩展配置"：这个希望也能订阅）

### 使用场景 / Use case

rt

**Comment by PctAIGM** [comment]
mihomo-party 完全满足你的需求

**Comment by wonfen** [comment]
目前支持webdav备份
