### ISSUE TITLE
[BUG] 通过winget的更新工作不正常

### ISSUE THREAD

**Issue by KaranocaVe** [clash-verge-rev/clash-verge-rev#1616]
### 问题描述 / Describe the bug

使用winget从1.7.6更新到1.7.7的过程中，居然弹出来clash verge的卸载程序，继续就是卸载成功，然后就没有下文了

### 复现步骤 / To Reproduce

winget update ClashVergeRev.ClashVergeRev

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

23H2

### 日志 / Log

NULL

**Comment by wonfen** [comment]
建议正常下载安装，winget没有精力做完整测试。
