### ISSUE TITLE
[BUG] clash内核疑似内存泄漏

### ISSUE THREAD

**Issue by Ptilopsis01** [clash-verge-rev/clash-verge-rev#1619]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/5af42657-d733-4e0b-a822-fea08c83b2d6)
如图所示，内存占用在开启代理后会持续上涨且几乎未发现下降，重启clash内核后下降至正常水平，然后又开始持续上涨

### 复现步骤 / To Reproduce

如上所述

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 26100.1586

### 日志 / Log

[2024-08-24-0238.zip](https://github.com/user-attachments/files/16732617/2024-08-24-0238.zip)

**Comment by wonfen** [comment]
到内核那边提：https://github.com/MetaCubeX/mihomo
