### ISSUE TITLE
[BUG]mac osx14.2 设置系统代理失败

### ISSUE THREAD

**Issue by alphavip** [clash-verge-rev/clash-verge-rev#162]
### Describe the bug

终端启动报这个错
** Error: The parameters were not valid.
** Error: Unable to find item in network database.
** Error: The parameters were not valid.
** Error: Unable to find item in network database.
** Error: The parameters were not valid.
** Error: Unable to find item in network database.
** Error: Unable to find item in network database.

### To Reproduce

因为设置不了代理所以终端启动看看报错
/Applications/Clash\ Verge.app/Contents/MacOS/Clash\ Verge
然后报错
** Error: The parameters were not valid.
** Error: Unable to find item in network database.
** Error: The parameters were not valid.
** Error: Unable to find item in network database.
** Error: The parameters were not valid.
** Error: Unable to find item in network database.
** Error: Unable to find item in network database.

### Platform

MacOS

### System Version

14.2

### Software Version

1.4.3

**Comment by starlifezzz** [comment]
最新版都1.4.5了，更新再试试呗

**Comment by alphavip** [comment]
研究了一下应该是set_proxy的时候回去的service名字不对，自己把网络里的网卡名字重新改了
