### ISSUE TITLE
[BUG] 文档页面的SSL证书是不是过期了，打不开？https://www.clashverge.dev/

### ISSUE THREAD

**Issue by huangzhuohua** [clash-verge-rev/clash-verge-rev#1624]
### 问题描述 / Describe the bug

Chrome浏览器打不开https://www.clashverge.dev/

### 复现步骤 / To Reproduce

Chrome浏览器打开https://www.clashverge.dev/，显示
您的连接不是私密连接
攻击者可能会试图从 www.clashverge.dev 窃取您的信息（例如：密码、通讯内容或信用卡信息）。[了解详情](chrome-error://chromewebdata/#)
net::ERR_CERT_COMMON_NAME_INVALID

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

https://www.clashverge.dev/

**Comment by wonfen** [comment]
现在应该可以了。

**Comment by wangzainn** [comment]
直接用 `https://clash-verge-rev.github.io` 不更好么，不用 301 过去，多一种选择。

**Comment by huangzhuohua** [comment]
可以了
