### ISSUE TITLE
[Feature] 还原prepend-proxies等行为的标准实现

### ISSUE THREAD

**Issue by hanepudding** [clash-verge-rev/clash-verge-rev#1627]
### 功能描述 / Feature description

希望在merge文件（现称“拓展配置”）中，还原1.6.x版本下的“prepend-proxies”“prepend-proxy-groups”等标准行为实现。

### 使用场景 / Use case

当前的“图形化配置界面”只能插入订阅链接，无法插入自行创建的节点，以及无法对节点信息进行修改微调，尤其是不支持wireguard等节点的导入。追求图形化本身而降低了灵活性，并非好的实践。

题外话，原版clash verge的windows版本安装目录在用户空间而无需管理员权限；clash verge rev版本开始安装在Program Files目录而需要管理员权限（会UAC警报），但我并未看出这么做的必要性。

**Comment by wangzainn** [comment]
安装在 `Program Files` 目录，目的是为所有用户安装么？至少 windows 没有多用户场景，没多大必要

**Comment by yutouyes** [comment]
坦白说rev的一些偏好可能需要尊重一下，比如说作者对便携版的不满是比较明显的，我之前使用的v2ray、ss、ssr都提供的便携版，应用内更新也没有问题，但是rev这边一直不支持便携版的检测更新，并且呼吁大家不要用便携版，我个人不太理解原因。只不过兼容我节点的客户端就这个了，所以只能respect

**Comment by wangzainn** [comment]
> 坦白说rev的一些偏好可能需要尊重一下，比如说作者对便携版的态度是比较明显的，我之前使用的v2ray、ss、ssr都提供的便携版，应用内更新也没有问题，但是rev这边一直不支持便携版的检测更新，并且呼吁大家不要用便携版，我个人不太理解原因。只不过兼容我节点的客户端就这个了，所以只能respect

哪里哦，应用内更新刚还看到一个 issue 说有问题 https://github.com/clash-verge-rev/clash-verge-rev/issues/1608

看代码是又换了一个 镜像站，应该是自己套的 cf。搞不懂，更新直接走内核直连 GitHub 不是更简单。看着像应用的所有连接默认是直连的，从订阅更新那单独做一个按钮走代理更新大概能猜出来。cfw 我印象中是默认走代理的，导入订阅没失败过。有些维护者对 cfw 好像有点意见，说有些人被“毒害的不轻”😂

我简单用，没用 tun 那些，用便携版没啥问题，挺好的。

**Comment by yutouyes** [comment]
> > 坦白说rev的一些偏好可能需要尊重一下，比如说作者对便携版的态度是比较明显的，我之前使用的v2ray、ss、ssr都提供的便携版，应用内更新也没有问题，但是rev这边一直不支持便携版的检测更新，并且呼吁大家不要用便携版，我个人不太理解原因。只不过兼容我节点的客户端就这个了，所以只能respect
> 
> 哪里哦，应用内更新刚还看到一个 issue 说有问题 #1608
> 
> 看代码是又换了一个 镜像站，应该是自己套的 cf。搞不懂，更新直接走内核直连 GitHub 不是更简单。看着像应用的所有连接默认是直连的，从订阅更新那单独做一个按钮走代理更新大概能猜出来。cfw 我印象中是默认走代理的，导入订阅没失败过。有些维护者对 cfw 好像有点意见，说有些人被“毒害的不轻”😂
> 
> 我简单用，没用 tun 那些，用便携版没啥问题，挺好的。

啊，我是说的这个
![image](https://github.com/user-attachments/assets/0da558e8-5dd4-4f8c-b461-02bf3f98c50b)
按我前面提的其他工具来看，包括v2也支持tun，它便携版更新也没啥问题，便携版应该足够有权限更新自己的。
正常来说绿色软件应该是更简洁的，不需要再制作一个安装引导程序，直接使用就可以了，看[#387](https://github.com/clash-verge-rev/clash-verge-rev/issues/387) 维护者说出于简洁的原因不加入应用内更新，但是这个功能还能比安装引导臃肿么。并且安装版有应用内更新功能，便携版是去掉了这部分的代码还是有这个功能但专门做了屏蔽？无论是哪种解释都有点多此一举，我个人不太理解。

**Comment by wangzainn** [comment]
> > > 坦白说rev的一些偏好可能需要尊重一下，比如说作者对便携版的态度是比较明显的，我之前使用的v2ray、ss、ssr都提供的便携版，应用内更新也没有问题，但是rev这边一直不支持便携版的检测更新，并且呼吁大家不要用便携版，我个人不太理解原因。只不过兼容我节点的客户端就这个了，所以只能respect
> > 
> > 
> > 哪里哦，应用内更新刚还看到一个 issue 说有问题 #1608
> > 看代码是又换了一个 镜像站，应该是自己套的 cf。搞不懂，更新直接走内核直连 GitHub 不是更简单。看着像应用的所有连接默认是直连的，从订阅更新那单独做一个按钮走代理更新大概能猜出来。cfw 我印象中是默认走代理的，导入订阅没失败过。有些维护者对 cfw 好像有点意见，说有些人被“毒害的不轻”😂
> > 我简单用，没用 tun 那些，用便携版没啥问题，挺好的。
> 
> 啊，我是说的这个 ![image](https://private-user-images.githubusercontent.com/17039457/361239420-0da558e8-5dd4-4f8c-b461-02bf3f98c50b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTgwODMsIm5iZiI6MTcyNDU5Nzc4MywicGF0aCI6Ii8xNzAzOTQ1Ny8zNjEyMzk0MjAtMGRhNTU4ZTgtNWRkNC00ZjhjLWI0NjEtMDJiZjNmOThjNTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE0NTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYmViY2FmOWIzYmVjMDBhNDFiZWM0YmJjY2EwNjc2N2RiNzVlYTZlYWY2NWRmMjhkYzFlYTExNmEwZTZkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ODTVBhe6PfSyhaEzrMqgmINzJ2UWnSSkrWe6qhCgBik) 按我前面提的其他工具来看，包括v2也支持tun，它便携版更新也没啥问题，便携版应该足够有权限更新自己的。 正常来说绿色软件应该是更简洁的，不需要再制作一个安装引导程序，直接使用就可以了，看[#387](https://github.com/clash-verge-rev/clash-verge-rev/issues/387) 维护者说出于简洁的原因不加入应用内更新，但是这个功能还能比安装引导臃肿么。并且安装版有应用内更新功能，便携版是去掉了这部分的代码还是有这个功能但专门做了屏蔽？无论是哪种解释都有点多此一举，我个人不太理解。

哦哦，没注意了，刚好前面看到那个 issue

你去看下 sing-box，这个好像也还可以，目前生态不是很完善，我不太会用，用过伊朗大哥写的 hiddify，有点问题。我也是迫于 cfw 不支持有些协议，有个机场刚好是 hy2，只能先用这个顶着。

**Comment by wonfen** [comment]
> 但是rev这边一直不支持便携版的检测更新，并且呼吁大家不要用便携版，我个人不太理解原因。

因为便携版应用内更新无法通过注册表找到原始安装路径，只能更新到默认路径 C:\Program files\... 所以会导致出现多个程序。出现冲突。

> 但是这个功能还能比安装引导臃肿么

安装引导是必须有，再加一套检测逻辑就更麻烦，维护成本高。

> 更新直接走内核直连 GitHub 不是更简单。

因为国内直连github几乎不可用。

> 看着像应用的所有连接默认是直连的。

目前tauri的socks5系统代理在win11下有bug，更新的时候可以打开tun模式。
https://github.com/tauri-apps/tauri/issues/10037
