### ISSUE TITLE
[BUG] Mac M3 v14.1 安装包提示已损坏

### ISSUE THREAD

**Issue by bopresslte** [clash-verge-rev/clash-verge-rev#163]
### Describe the bug

Mac M3 安装包提示已损坏

### To Reproduce

Mac M3 安装包提示已损坏

### Platform

MacOS

### System Version

14.1

### Software Version

1.4.5

**Comment by cheneyxx** [comment]
sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app

**Comment by bopresslte** [comment]
> sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app

Nice. solved.
