### ISSUE TITLE
[Feature] 给 macOS 版添加对 Alt+Tab 快捷键的支持

### ISSUE THREAD

**Issue by foobarjohnny** [clash-verge-rev/clash-verge-rev#1634]
### 功能描述 / Feature description

本软件的 Windows 版是支持用 Alt+Tab 在 Browser 和 clash-verge-rev 之间进行切换, 希望 macOS 版也能支持.

### 使用场景 / Use case

在 Browser 和 clash-verge-rev 之间来回进行切换时.

**Comment by foobarjohnny** [comment]
Clash for windows 的 macOS 版是支持的, 可以参考一下.

**Comment by JackloveJam** [comment]
![image](https://github.com/user-attachments/assets/d192882c-53e6-49e9-975d-28bde4f46649)
少侠何不尝试下，专属快捷键呼出。😎
alt+tab 组合键 如果开的窗口多了，恐怕还没快捷键呼出的快。
>扩展：（在Windows系统中，使用 win + 1/2/3/4/5 切换窗口也很方便）

**Comment by foobarjohnny** [comment]
用热键控制的 "打开/关闭面板" 在 Browser 和 ClashVergeRev 之间做反复的来回切换时, 没有从  ClashVergeRev 切换到 Browser 的热键, 只能靠鼠标点击切换到 Browser, 比无脑用单一热键 ALT+TAB 就能做来回切换的用户体验差远了.

**Comment by foobarjohnny** [comment]
隔壁的 App 通过 dock 已经实现本功能了, 可以参考一下.

https://github.com/libnyanpasu/clash-nyanpasu/issues/178#issuecomment-2322791151

**Comment by foobarjohnny** [comment]
隔壁的 App 通过 dock 已经实现本功能了, 可以参考一下.

https://github.com/libnyanpasu/clash-nyanpasu/issues/178
