### ISSUE TITLE
[Feature] 建议把 Profiles 页面中, 作为选中指示的 "蓝色竖条" 换成 "绿色竖条"

### ISSUE THREAD

**Issue by foobarjohnny** [clash-verge-rev/clash-verge-rev#1635]
### 功能描述 / Feature description

建议把 Profiles 页面中, 作为选中指示的 "蓝色竖条" 换成 "绿色竖条"

### 使用场景 / Use case

在室外的强光环境下, 电脑屏幕上的 "蓝色竖条" 很难辨认, 建议换成容易辨认的 "绿色竖条".

可以参考 Clash for Windows
从

<img width="709" alt="PIC01" src="https://github.com/user-attachments/assets/437b01bf-9c14-41ca-8ecf-2d5f2d20127d">

换成

![PIC02](https://github.com/user-attachments/assets/827d96ff-9ee6-480c-8166-b6c57edeeecd)

**Comment by eronez** [comment]
css injection is all you need

**Comment by foobarjohnny** [comment]
> css injection is all you need

我不懂怎么写这个的 css injection, 你有样例吗 ? 谢谢

**Comment by eronez** [comment]
@foobarjohnny 
Theme Setting -> Primary Color -> #00FF00 -> SAVE
justify any color setting as what u want

**Comment by JackloveJam** [comment]
![image](https://github.com/user-attachments/assets/26c57e06-9b88-45d4-93e2-8900eb99a3d9)
![image](https://github.com/user-attachments/assets/52a56e36-278e-4e68-86d3-51af17e24fd9)
修改这个色值即可

**Comment by foobarjohnny** [comment]
搞定, 谢谢两位.
