### ISSUE TITLE
[Feature] 建议图标调整为以前版本或者换个新的简约图标，粉色icon有点违和

### ISSUE THREAD

**Issue by hyymaidou** [clash-verge-rev/clash-verge-rev#1636]
### 功能描述 / Feature description

换成以前的小蓝猫

### 使用场景 / Use case

图标

**Comment by eronez** [comment]
u can change icon as what u want
![image](https://github.com/user-attachments/assets/f6195ea4-a3d1-44cb-9210-6575138ad6d1)
