### ISSUE TITLE
[BUG] XTLS Vision server responded unknown UUID : XXXXXX

### ISSUE THREAD

**Issue by flygger** [clash-verge-rev/clash-verge-rev#164]
### Describe the bug

XTLS Vision server responded unknown UUID

### To Reproduce

Clash Meta Alpha内核，提示升级内核

### Platform

MacOS

### System Version

macOS Sonoma 14.2

### Software Version

1.4.5

### Log

12-19 13:41:30WARNING
To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+
12-19 13:41:30WARNING
To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+
12-19 13:41:30WARNING
To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+
12-19 13:41:30WARNING
To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+
12-19 13:41:30WARNING
To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+
12-19 13:44:22ERROR
XTLS Vision server responded unknown UUID: 48545450-2f31-2e31-2033-6f76

**Comment by wonfen** [comment]
这个是core的日志，找找你服务端问题。
