### ISSUE TITLE
[BUG] Ctrl + \ 作为开启/关闭系统代理的快捷键时，该快捷键不起作用

### ISSUE THREAD

**Issue by DusKing1** [clash-verge-rev/clash-verge-rev#1640]
### 问题描述 / Describe the bug

Hi 我这里无法使用 Ctrl + \ 作为 开启/关闭系统代理的快捷键

### 复现步骤 / To Reproduce

将 开启/关闭系统代理的快捷键 设置为 Ctrl + \，然后尝试通过该快捷键开启或关闭系统代理

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 11

### 日志 / Log

这个没有

**Comment by JackloveJam** [comment]
很有意思的一个发现。
我在1.7.6 1.7.7分别测试了这个按键，确实无法奏效。并且这个组合键在Win11 Win10 也没特别作用。
（在未搞清这个组合键不生效之前，楼主不妨可以尝试使用其他组合键 例如 Ctrl + / ，Ctrl + ] 等等。自测它们是可行的，可能也符合你的按键习惯）

**Comment by Hrefrain** [comment]
i don't have this problem
version: v0.20.39
is it not possible to modify System Proxy's shotcut?
path: Settings -> Shortcuts -> System Proxy
