### ISSUE TITLE
[BUG] 左边会出现一个图标

### ISSUE THREAD

**Issue by catch6** [clash-verge-rev/clash-verge-rev#1641]
### 问题描述 / Describe the bug

<img width="10000" alt="image" src="https://github.com/user-attachments/assets/c3f2e2ed-4483-4172-a7c6-c0aa22ee2c37">

### 复现步骤 / To Reproduce

<img width="168" alt="image" src="https://github.com/user-attachments/assets/cdc4922a-95e7-4d29-84bf-2359a753cfa9">

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.6.1

### 日志 / Log

2024-08-27 09:47:21 INFO - reset proxy to the original proxy
2024-08-27 09:47:21 INFO - reset proxy to the original proxy

**Comment by wonfen** [comment]
什么图标？

**Comment by catch6** [comment]
@wonfen MAC菜单栏最左边也有个clash的icon图标，图片很小，可能看不是很清楚
![image](https://github.com/user-attachments/assets/daf570f7-8eb0-496c-b059-3e913ecbb283)

**Comment by wonfen** [comment]
发issue前，麻烦看一下文档
https://www.clashverge.dev/faq/macos.html#macos_1

**Comment by hootigger** [comment]
<img width="1311" alt="image" src="https://github.com/user-attachments/assets/a49d7d09-f1c1-4edc-841a-8dd0f2540d67">
左边图标,影响苹果菜单 点击,产生原因不知道, 我覆盖安装最新1.7.7 就有 应该是必现.的 M1 max设备.下载的  arm64的dmg包

**Comment by wonfen** [comment]
> <img alt="image" width="1311" src="https://private-user-images.githubusercontent.com/23418191/363000658-a49d7d09-f1c1-4edc-841a-8dd0f2540d67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODUwNjEsIm5iZiI6MTcyNDk4NDc2MSwicGF0aCI6Ii8yMzQxODE5MS8zNjMwMDA2NTgtYTQ5ZDdkMDktZjFjMS00ZWRjLTg0MWEtOGRkMGYyNTQwZDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAyMjYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZWQxYjc4YTU2M2UxMTQyMmIwMTY0YmIwYzE0MDU1ZDNlMjYxODg3YzY1Njc0MmYwY2I4NjhlNDM5Yjk5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TEMnx6My4eBzNwhROMpLrGzkXcL6376PlTwGONcQmmc"> 左边图标,影响苹果菜单 点击,产生原因不知道, 我覆盖安装最新1.7.7 就有 应该是必现.的 M1 max设备.下载的 arm64的dmg包

逆天，对回复视而不见
发issue前，麻烦看一下文档
https://www.clashverge.dev/faq/macos.html#macos_1

**Comment by hootigger** [comment]
我的问题,不好意思.  我下意识以为你说的是 发issue不规范.  正好遇到这个问题,查看到了这个issue 就回复了下.  

> > <img alt="image" width="1311" src="https://private-user-images.githubusercontent.com/23418191/363000658-a49d7d09-f1c1-4edc-841a-8dd0f2540d67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODUwNjEsIm5iZiI6MTcyNDk4NDc2MSwicGF0aCI6Ii8yMzQxODE5MS8zNjMwMDA2NTgtYTQ5ZDdkMDktZjFjMS00ZWRjLTg0MWEtOGRkMGYyNTQwZDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAyMjYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZWQxYjc4YTU2M2UxMTQyMmIwMTY0YmIwYzE0MDU1ZDNlMjYxODg3YzY1Njc0MmYwY2I4NjhlNDM5Yjk5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TEMnx6My4eBzNwhROMpLrGzkXcL6376PlTwGONcQmmc"> 左边图标,影响苹果菜单 点击,产生原因不知道, 我覆盖安装最新1.7.7 就有 应该是必现.的 M1 max设备.下载的 arm64的dmg包
> 
> 逆天，对回复视而不见 发issue前，麻烦看一下文档 https://www.clashverge.dev/faq/macos.html#macos_1

**Comment by hootigger** [comment]
@catch6 你用上述文档提到的切换分辨率方式 有效吗?我的无效.

**Comment by catch6** [comment]
> @catch6 你用上述文档提到的切换分辨率方式 有效吗?我的无效.

我的自己好了，不知道做了啥操作
