### ISSUE TITLE
[BUG] 规则模式貌似有问题

### ISSUE THREAD

**Issue by Im-SAMW** [clash-verge-rev/clash-verge-rev#1642]
### 问题描述 / Describe the bug

规则模式中配置 www.baidu.com 不走代理，但是节点网络不好时，仍然会打不开百度

### 复现步骤 / To Reproduce

添加域名 baidu.com 为直连，然后找个延迟高（或失败）的节点，打开百度，第一次大概率打不开；

目前不能100%复现，但复现的概率还是挺高的；

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS 13.6.9

### 日志 / Log

无

**Comment by Dontla** [comment]
我的也是这样，我打开直连模式，访问百度等国内网站有时会失败，大部分要等待很久，关掉clash verge就好了

**Comment by wonfen** [comment]
检查你们机场的配置规则；规则都写不好的机场，还是别用了吧

**Comment by daitou05** [comment]
> 检查你们机场的配置规则；规则都写不好的机场，还是别用了吧

多推荐几个机场，像 cfw 那样挂上广告，哈哈哈

**Comment by duucck** [comment]
换回 v1.7.5，新版有这个问题。

**Comment by wonfen** [comment]
> 换回 v1.7.5，新版有这个问题。

别乱说，和版本没关系，检查你机场的规则

**Comment by duucck** [comment]
> > 换回 v1.7.5，新版有这个问题。
> 
> 别乱说，和版本没关系，检查你机场的规则

我不用机场规则，用的开源规则加我自己写得，从来没出过问题。更到 v1.7.6 版本时，bilibili 加载出了问题，看链接走的是 Direct，但就是不正常。换回 v1.7.5，一切正常，规则这玩意儿配好了基本就很少动的。

**Comment by wonfen** [comment]
> > > 换回 v1.7.5，新版有这个问题。
> > 
> > 
> > 别乱说，和版本没关系，检查你机场的规则
> 
> 我不用机场规则，用的开源规则加我自己写得，从来没出过问题。更到 v1.7.6 版本时，bilibili 加载出了问题，看链接走的是 Direct，但就是不正常。换回 v1.7.5，一切正常，规则这玩意儿配好了基本就很少动的。

首先规则都全部由内核加载；其次1.7.5到1.7.7仅仅是修正了一些小bug。你可以自己翻一下代码

**Comment by KuiyuanFu** [comment]
> > > > 换回 v1.7.5，新版有这个问题。
> > > 
> > > 
> > > 别乱说，和版本没关系，检查你机场的规则
> > 
> > 
> > 我不用机场规则，用的开源规则加我自己写得，从来没出过问题。更到 v1.7.6 版本时，bilibili 加载出了问题，看链接走的是 Direct，但就是不正常。换回 v1.7.5，一切正常，规则这玩意儿配好了基本就很少动的。
> 
> 首先规则都全部由内核加载；其次1.7.5到1.7.7仅仅是修正了一些小bug。你可以自己翻一下代码

我也是知乎图片加载失败，我退回了1.7.5就正常了，不知道什么原因

**Comment by PctAIGM** [comment]
> 我也是知乎图片加载失败，我退回了1.7.5就正常了，不知道什么原因

退回旧版本的时候，是不是内核也降级了？

**Comment by KuiyuanFu** [comment]
> > 我也是知乎图片加载失败，我退回了1.7.5就正常了，不知道什么原因
> 
> 退回旧版本的时候，是不是内核也降级了？

不清楚，感觉不是版本的问题了，1.7.5也出现同样问题。我换了另一个客户端，现在好用了一点，看看会不会出现相同问题吧。
