### ISSUE TITLE
[BUG] log-level 无法修改

### ISSUE THREAD

**Issue by Ptilopsis01** [clash-verge-rev/clash-verge-rev#1643]
### 问题描述 / Describe the bug

如题，文档中说log-level无法通过merge文件覆盖，但即使在app的杂项设置中修改log-level为debug，当前配置中依然为info，且即使重启app也无效

### 复现步骤 / To Reproduce

如上所述

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 26100.1586

### 日志 / Log

[2024-08-27-1813.log](https://github.com/user-attachments/files/16760496/2024-08-27-1813.log)

**Comment by WangLeoX** [comment]
在配置文件中改行不行呢？我刚从CFW切换到CVR, 也注意到了这个问题，因为它产生了48M的日志。
不过CVR 的配置，我只能在软件界面右键点【编辑文件修改】 我搜索都找不到和界面同名的（.yaml)文件。
后来再看它的CONFIG.YAML 发现它把界面文件的内容拆解了，重新归类并分散写入软件中的几个固定(.yaml)文件中了，这真是很奇怪的设置。 直接对我手搓配置形成极大的不便。

我打算回去用旧版CV看看

**Comment by Ptilopsis01** [comment]
“当前配置”的界面是只读的，改不了

**Comment by WangLeoX** [comment]
> “当前配置”的界面是只读的，改不了

[常见问题](https://github.com/clash-verge-rev/clash-verge-rev/issues/125)
再它这个页面搜索日志看看，他们似乎提到了这个改日志的方法。
我猜就是要找到配置文件来改写的。

**Comment by Ptilopsis01** [comment]
不用，是我傻逼了，要改的是设置界面ipv6下面那个选项
