### ISSUE TITLE
[BUG] 每次重启电脑后很多软件都无法连接到网络。

### ISSUE THREAD

**Issue by NOWorEVER** [clash-verge-rev/clash-verge-rev#1646]
### 问题描述 / Describe the bug

不管怎么开关，都没办法正常连接，退出软件才能解决网络问题。
不管是规则模式还是直连模式

### 复现步骤 / To Reproduce

不管怎么开关，都没办法正常连接，退出软件才能解决网络问题。
不管是规则模式还是直连模式

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 专业版 22H2  19045.4780

### 日志 / Log

2024-08-28 09:51:19 ERROR - error sending request for url (http://127.0.0.1:33211/unset_dns)

**Comment by Nephren-Ruq-Insania** [comment]
你在重启前关闭这个软件啊，或者把它设置开机自启

**Comment by NOWorEVER** [comment]
> 你在重启前关闭这个软件啊，或者把它设置开机自启

我就是设置的开机自启，反正就是开机后一堆软件上不去，QQ，微信之类的。都会网络错误。得关闭代理功能，然后退出软件。过一会再开启就好了。

**Comment by daitou05** [comment]
设置开机自启，可以缓解。但这个 clash-verge-rev 自启挺慢的，也有十几秒的断网。

**Comment by crosspacific** [comment]
能否添加一个退出软件自动关闭代理的功能。

**Comment by wonfen** [comment]
> 能否添加一个退出软件自动关闭代理的功能。

正常关闭软件会自动关闭系统代理的。如果直接重启的话，进程直接被杀了，自然也无法触发操作关闭系统代理

**Comment by styshoo** [comment]
应该是软件的bug，升级到v1.7.5就会出现这个问题。感觉是缺少了某个配置文件，导致启动电脑后，第一次打开clash时，代理页面都是全空的，订阅页面点击重新激活所有订阅会提示文件不存在。
解决方法就是关闭软件，再重新打开就好了。
我试试重新完全卸载软件，再安装，看看结果如何。

**Comment by wonfen** [comment]
> 应该是软件的bug，升级到v1.7.5就会出现这个问题。感觉是缺少了某个配置文件，导致启动电脑后，第一次打开clash时，代理页面都是全空的，订阅页面点击重新激活所有订阅会提示文件不存在。 解决方法就是关闭软件，再重新打开就好了。 我试试重新完全卸载软件，再安装，看看结果如何。

看样子是你电脑中安装了多个版本，尝试完全卸载其他版本，再安装最新版
