### ISSUE TITLE
[BUG] CUP 占用极高（130%）

### ISSUE THREAD

**Issue by waveiron** [clash-verge-rev/clash-verge-rev#1647]
### 问题描述 / Describe the bug

下载一个文件，30MB/s，cpu 占用如下：

![CleanShot 2024-08-28 at 14 12 24@2x](https://github.com/user-attachments/assets/937bce01-7beb-4c6b-8730-394ef5a2a91a)

重启没有用

### 复现步骤 / To Reproduce

比如说从 dropbox 下载个大文件

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.6.1

### 日志 / Log

-

**Comment by wonfen** [comment]
这不正常的吗？和你的CPU有关系，另外这是内核的占用，和GUI无关

**Comment by Nnaking** [comment]
我也有这样的问题
