### ISSUE TITLE
[BUG] 本机域名无法在命令行请求

### ISSUE THREAD

**Issue by shuifa** [clash-verge-rev/clash-verge-rev#1649]
### 问题描述 / Describe the bug

终端中执行以下命令
1、设置终端代理
```bash
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
```
2、请求本地域名
```bash
curl -v https://orb.local
```
3、命令输出
```bash
* Uses proxy env variable https_proxy == 'http://127.0.0.1:7890'
* Trying 127.0.0.1:7890...
* Connected to 127.0.0.1 (127.0.0.1) port 7890
* CONNECT tunnel: HTTP/1.1 negotiated
* allocate connect buffer
* Establish HTTP proxy tunnel to orb.local:443
> CONNECT orb.local:443 HTTP/1.1
> Host: orb.local:443
> User-Agent: curl/8.7.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* CONNECT phase completed
* CONNECT tunnel established, response 200
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* Recv failure: Connection reset by peer
* LibreSSL/3.3.6: error:02FFF036:system library:func(4095):Connection reset by peer
* Closing connection
curl: (35) Recv failure: Connection reset by peer
```

不使用代理可以请求到。
```bash
curl https://orb.local/index.php --noproxy orb.local
404 page not found
```

查看相关错误日志

### 复现步骤 / To Reproduce

同描述中步骤

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.6.1 (23G93)

### 日志 / Log

[warn] [TCP] dial failed error=couldn't find ip: orb.local proxy=DIRECT lAddr=127.0.0.1:61786 rAddr=orb.local:443 rule=DomainSuffix rulePayload=local

**Comment by wonfen** [comment]
clash会把根据配置文件把域名送给远程dns或本地host，需要查看你的配置文件规则。

**Comment by shuifa** [comment]
> clash会把根据配置文件把域名送给远程dns或本地host，需要查看你的配置文件规则。

<img width="434" alt="image" src="https://github.com/user-attachments/assets/30474b72-7c8b-476d-812d-399f561580ac">
已经设置了排除 *.local 域的域名了，我看上面的日志的规则也是走到了 rulePayload=local 本地这个。不知道为什么解析不了

**Comment by wonfen** [comment]
> 日志的规则也是走到了 rulePayload=local

那说明走了规则，没有走你上面配置的代理绕过。
用了tun模式？

**Comment by shuifa** [comment]
> tun模式

是的用的 Enhanced Mode 这个模式，这个会影响本机域名的解析吗，但是我浏览器访问本机域名又是正常的

**Comment by wonfen** [comment]
> > tun模式
> 
> 是的用的 Enhanced Mode 这个模式，这个会影响本机域名的解析吗，但是我浏览器访问本机域名又是正常的

verge没有Enhanced Mode这个奇怪的叫法。没法回答其他软件的问题。

**Comment by shuifa** [comment]
> > > tun模式
> > 
> > 
> > 是的用的 Enhanced Mode 这个模式，这个会影响本机域名的解析吗，但是我浏览器访问本机域名又是正常的
> 
> verge没有Enhanced Mode这个奇怪的叫法。没法回答其他软件的问题。

就是创建虚拟网卡的模式。叫法不一样
