### ISSUE TITLE
[Feature] URL Scheme 支持 & 自动订阅名称

### ISSUE THREAD

**Issue by SummonHIM** [clash-verge-rev/clash-verge-rev#165]
### Is your feature request related to a problem? Please describe.

None

### Describe the solution you'd like

像[CFW 文档](https://web.archive.org/web/20230805125358/https://docs.cfw.lbyczf.com/contents/urlscheme.html)中的URL Scheme一样，通过 clash://install-config?url=xxx 来导入订阅

自动订阅名称就是将content-disposition的filename设为订阅的名称，和CFW文档描述的一样

### Describe alternatives you've considered

None

**Comment by MystiPanda** [comment]
URL Scheme有计划，订阅名称现在就是这样的呀

**Comment by SummonHIM** [comment]
> URL Scheme有计划，订阅名称现在就是这样的呀

我刚刚试了一下确实是，但是使用subconverter转换后就不行了。

**Comment by MystiPanda** [comment]
请求头中的content-disposition字段是机场给的，转换后估计不带这东西了吧。

**Comment by SummonHIM** [comment]
> 请求头中的content-disposition字段是机场给的，转换后估计不带这东西了吧。

是不带，但是可以使用subconverter的参数来指定filename的（[文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E8%B0%83%E7%94%A8%E5%9C%B0%E5%9D%80-%E8%BF%9B%E9%98%B6)）。

实际会返回
```
attachment; filename="<UTF8原文应该是。我浏览器显示乱码>"; filename*=utf-8''<utf8 url encode>
```

**Comment by MystiPanda** [comment]
好像就是因为filename中的乱码导致的解析失败，一般来说机场返回的内容只包含filename和filename*中的其中一个，clash verge没有考虑同时包含两者的情况，已经修复。

**Comment by SummonHIM** [comment]
> 好像就是因为filename中的乱码导致的解析失败，一般来说机场返回的内容只包含filename和filename*中的其中一个，clash verge没有考虑同时包含两者的情况，已经修复。

编译测试完发现可以了。多谢大佬！
