### ISSUE TITLE
[Feature] 可以做个纯命令行的版本嘛

### ISSUE THREAD

**Issue by QAQ-cmd** [clash-verge-rev/clash-verge-rev#1651]
### 功能描述 / Feature description

服务器不接屏幕的，希望直接命令行操作

### 使用场景 / Use case

无屏幕的情况下

**Comment by it-glen** [comment]
那你直接跑内核不就完了

**Comment by QAQ-cmd** [comment]
> 那你直接跑内核不就完了

怎么跑？

**Comment by WangLeoX** [comment]
我确实记得这玩意儿本来最开始就只有命令行的，是后来才慢慢的开发了各种客户端。

那就是说可能命令行版本早就存在，只是用法失传了

**Comment by wonfen** [comment]
看文档啊

**Comment by Tychristine** [comment]
> ### 功能描述 / Feature description
> 
> 服务器不接屏幕的，希望直接命令行操作
> 
> ### 使用场景 / Use case
> 
> 无屏幕的情况下

看Mihomo 文档，直接跑内核，记得端口开认证

**Comment by QAQ-cmd** [comment]
OK
