### ISSUE TITLE
[BUG]   切换订阅之后  或者电脑从睡眠启动会 出现代理配置失效 , 需要重新开关系统代理 

### ISSUE THREAD

**Issue by Super1Windcloud** [clash-verge-rev/clash-verge-rev#1652]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/cec953a4-cd15-431f-8c01-5e78cdc6e805)

### 复现步骤 / To Reproduce

![image](https://github.com/user-attachments/assets/043c6680-c6ae-4c95-b6bb-a86ae82e38ed)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11 

### 日志 / Log

![image](https://github.com/user-attachments/assets/cc5b6845-24e1-4656-9c59-a4e5ab7a09b3)

**Comment by wonfen** [comment]
检查系统中是否安装了其他代理软件？把系统代理的设置修改了
