### ISSUE TITLE
[Feature]  clash -verge 似乎不支持Trojan协议, 希望大佬能够适配更多内核

### ISSUE THREAD

**Issue by Super1Windcloud** [clash-verge-rev/clash-verge-rev#1653]
### 功能描述 / Feature description

 不是节点的问题,  v2ray 就能够正常使用 

![image](https://github.com/user-attachments/assets/eb8d4827-c8ba-4159-88e8-2d34690291ad)
 
![image](https://github.com/user-attachments/assets/650d7c28-dd2e-4848-a37a-144e1028368a)

### 使用场景 / Use case

![image](https://github.com/user-attachments/assets/b9ba73bb-30e7-41ae-aa3e-c41c0cf237b2)

**Comment by wonfen** [comment]
目测你机场配置文件的问题

**Comment by lbcake** [comment]
手动单点error 测速  延迟就正常了 100+   200 +

**Comment by lbcake** [comment]
> 当然是支持的。 目测你机场配置文件的问题，延迟那么高。 另外把其他代理软件关了再试试

![image](https://github.com/user-attachments/assets/42ecfd22-0eb6-409c-9a8b-f83479d726cc)

**Comment by lbcake** [comment]
> 当然是支持的。 目测你机场配置文件的问题，延迟那么高。 另外把其他代理软件关了再试试

![image](https://github.com/user-attachments/assets/f2801ebb-37c0-4469-918d-817600b5b0c8)

**Comment by Super1Windcloud** [comment]
hysteria 之外协议还是用 v2ray 吧

**Comment by yixiuge301** [comment]
你为啥不更新，支持协议这个跟内核有关，内核是支持的。

有看过说显示 error，但实际可用，如果是 就不必太在意。

你可以去 mihomo 那边去搜一下 issue，我印象中有看到过。

**Comment by HaggaiChen** [comment]
![Snipaste_2024-09-06_15-30-17](https://github.com/user-attachments/assets/3466d10a-4d82-4cf3-a472-8beab4d6d049)
支持的
