### ISSUE TITLE
[Feature] macOS 上添加对快捷键  Command+Q 来直接退出程序的支持

### ISSUE THREAD

**Issue by foobarjohnny** [clash-verge-rev/clash-verge-rev#1655]
### 功能描述 / Feature description

既然通过菜单项的 Quit 可以干净的退出, 那么理论上把 Command+Q 绑定到该菜单项上, 也应该能干净的退出.

可以参考隔壁的 Clash Nyanpasu

### 使用场景 / Use case

在打开 Dashboard 页面的情况下, 不需要用鼠标点击菜单项中的 Quit, 而是用 Command+Q 可以直接退出.

**Comment by wonfen** [comment]
2.0版已实现此功能，请测试

**Comment by kenxjc** [comment]
目前好像这个全局键是个全局设置，导致其他程序 cmd+Q 的时候先退出 clash verge

**Comment by kenxjc** [comment]
> 2.0版已实现此功能，请测试

目前好像这个全局键是个全局设置，导致其他程序 cmd+Q 的时候先退出 clash verge

**Comment by cxl253386709** [comment]
> 2.0版已实现此功能，请测试

有bug，其他程序的command + Q全部失效了

**Comment by supreme429** [comment]
> > 2.0版已实现此功能，请测试
> 
> 有bug，其他程序的command + Q全部失效了

我也遇到同样的问题

**Comment by supreme429** [comment]
似乎如果不打开clash的界面 就不会触发这个bug

**Comment by foobarjohnny** [comment]
我这里没有上述的 Bug, Command+Q 工作正常, 对别的 App 没有影响.

**Comment by kenxjc** [comment]
> 似乎如果不打开clash的界面 就不会触发这个bug

我不打开 clash 控制面板，也会有这个问题

**Comment by foobarjohnny** [comment]
> 系统版本是多少哇
我的 M1 macOS Version 14.6.1 和 Intel macOS Version 11.7.10 上都正常工作.
