### ISSUE TITLE
[Feature] 添加服务模式下，在后台运行的功能

### ISSUE THREAD

**Issue by Odriver** [clash-verge-rev/clash-verge-rev#1656]
### 功能描述 / Feature description

在服务模式下提供使用命令 `clash-verge --nogui` 无 gui 启动 clash verge 的功能

### 使用场景 / Use case

在 Linux 系统下不使用 gui 的情况，如果使用 `clash-verge` 启动应用，会报错 `cannot open display:`，ssh 场景下启动 clash 不方便。

**Comment by wonfen** [comment]
看文档：https://www.clashverge.dev/faq/linux.html#ui
