### ISSUE TITLE
[Feature] 点击任务栏弹出主界面速度慢

### ISSUE THREAD

**Issue by Stasert39** [clash-verge-rev/clash-verge-rev#1658]
### 功能描述 / Feature description

点击任务栏弹出主界面速度慢，clash for windows可以做到点一下立刻出现窗口，verge就需要等加载1秒左右，希望可以优化

### 使用场景 / Use case

使操作更流畅

**Comment by wonfen** [comment]
建议重新安装下webview2试试，在任何环境下都无法复现你说的问题。

**Comment by Stasert39** [comment]
重装了，似乎依然不行，我上传了一个视频，不知道这个速度是否正常

https://github.com/user-attachments/assets/5ebf8d9d-2a9e-4064-87d7-21e1bff1032b

**Comment by wonfen** [comment]
> 重装了，似乎依然不行，我上传了一个视频，不知道这个速度是否正常
> 
>  IMG_2471.mov

这个速度正常，因为不显示界面的时候，为了保持高效和减少内存占用；GUI相关进程没有运行，只有内核在运行

**Comment by yixiuge301** [comment]
> 重装了，似乎依然不行，我上传了一个视频，不知道这个速度是否正常
> 
>  IMG_2471.mov

我的比你慢多了，改天录个视频。

**Comment by wonfen** [comment]
用最新版，已经改进了。
