### ISSUE TITLE
[Feature] 希望在代理组那里添加一个“显示/隐藏超时节点”

### ISSUE THREAD

**Issue by mozhumao** [clash-verge-rev/clash-verge-rev#1659]
### 功能描述 / Feature description

![111](https://github.com/user-attachments/assets/cf5bee9c-f941-49e7-a42e-5115ea4c070d)
类似Clash.for.Windows这个功能“显示/隐藏超时节点 ，这样超过百个节点并且有很多节点超时把超时节点隐藏，ui界面
看起来就舒服很多了。

### 使用场景 / Use case

显示/隐藏超时节点

**Comment by WangLeoX** [comment]
这个打开订阅文件，编辑yaml 就可以做到啊， type写 url-test ,然后延迟规定为300，超过300的都不会显示

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/979
