### ISSUE TITLE
[Feature]更新GeoData能否优先使用clash配置文件中的geox-url字段指定的URL下载

### ISSUE THREAD

**Issue by DanielZWX** [clash-verge-rev/clash-verge-rev#166]
### Is your feature request related to a problem? Please describe.

当前版本，更新GeoData使用的是内置地址下载。

### Describe the solution you'd like

能否优先使用clash配置文件中的geox-url字段指定的URL下载；如没有这个字段，则使用内置地址

### Describe alternatives you've considered

能否优先使用clash配置文件中的geox-url字段指定的URL下载；如没有这个字段，则使用内置地址

**Comment by MystiPanda** [comment]
现在不是这样吗？

**Comment by F-Lee** [comment]
估计接下来会有很多人报GeoIP的问题。
软件安装后没有自带GeoIP，启动会去github.com下载geoip.dat和geosite.dat，偏偏我们这的移动网络无法正常访问github，所以就陷入一个死循环，没有geoip，代理节点就无法正常显示使用，节点无法用就去不了github。
我是去其它地方找来geoip.dat和geosite.dat放到io.github.clash-verge-rev.clash-verge-rev目录下才能正常使用。
有没有可能软件打包时带上geoip相关文件保个底？

**Comment by MystiPanda** [comment]
软件是自带的，我不知道你说的这是什么情况

**Comment by LzNOHentai** [comment]
> 现在不是这样吗？

刚好我这里也遇到一个更新GeoData的问题，请教一下是什么情况。
我使用的是TUN模式，所有上网功能都一切正常，唯独更新GeoData失败，不知道为什么。
配置文件里的链接我用的是这个Country.mmdb：
https://gcore.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/Country.mmdb
![Screenshot 2023-12-23 093443](https://github.com/clash-verge-rev/clash-verge-rev/assets/22359967/97f24281-9227-4a06-809c-5b9827a799e9)

**Comment by MystiPanda** [comment]
这个问题我也遇到过，不知道如何复现，看起来好像是mmdb文件被占用没法写入，但是更新成功的时候好像都是没有更新mmdb，这部分功能是内核实现的，建议给内核提交issue。

**Comment by LzNOHentai** [comment]
> 这个问题我也遇到过，不知道如何复现，看起来好像是mmdb文件被占用没法写入，但是更新成功的时候好像都是没有更新mmdb，这部分功能是内核实现的，建议给内核提交issue。

`[REST-API] update GEO databases failed: can't save MMDB database file: open C:\Users\abc\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev/Country.mmdb: The requested operation cannot be performed on a file with a user-mapped section open.`
1.4.11版本更新geodata出现如下提示，使用的是mmdb。

**Comment by Misaka09982** [comment]
1.5.1版本更新geodata是应用自带的链接，而不是配置文件里的自定义链接，每次启动都提示geo缺少相关词条，启动后用metacubexd面板更新则是配置文件里的自定义链接。希望软件能给出geodata的自定义设置

**Comment by h4rvey-g** [comment]
目前软件使用的Geodata是[MetaCubeX/meta-rules-dat](https://github.com/MetaCubeX/meta-rules-dat)，和[Loyalsoldier/v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat)还是有部分不兼容的条目。而每次软件更新后会覆盖原来的Geodata，导致使用Loyalsoldier/v2ray-rules-dat的用户需要在每次更新应用后再手动更新Geodata。希望能在软件更新后自动按照配置里的Geodata源更新一下。
