### ISSUE TITLE
[Feature] The subscription conversion function can preferentially process the subscription content when obtaining the subscription content and then keep it to verify whether the content is legitimate.

### ISSUE THREAD

**Issue by ipsfsw** [clash-verge-rev/clash-verge-rev#1660]
### 功能描述 / Feature description

Refer to this software:
2. https://github.com/GUI-for-Cores/GUI.for.Clash : The functionality that includes the subscription transformation also has some triggers to modify the configuration.
Official plugin: 
![PixPin_2024-09-02_06-27-48](https://github.com/user-attachments/assets/c20f6ad2-0427-4493-b7e9-789ecda2d1b1)
Self-written plugin for converting illegal content ： 
![PixPin_2024-09-02_06-28-09](https://github.com/user-attachments/assets/05e7ff82-c428-4976-a03a-07339188123a)

Hope developers can consider the relevant features, thank you!!!

At the same time, I also know that the developer has developed the function of modifying the configuration of the software script, but this function cannot modify the configuration before obtaining the subscription, so I hope the author can add a relevant function to process the subscription content when obtaining the subscription. Instead of having verified that the content is illegal and cannot be saved or processed, only the saved legal content is processed.
The existing features are: Get subscription content -> Determine if the content is legitimate -> Process with global script if it is legitimate -> Save.
The general steps are: Get the subscription content -> Process the subscription content (requested function)-> Determine whether the content is legitimate -> If it is legitimate, process it with a global script -> Save.

### 使用场景 / Use case

Plugins developed by developers for subscription content conversion. v2ray -> clash

**Comment by wonfen** [comment]
你的需求是把机场下发错的配置软件转换成可以用的吗？

**Comment by ipsfsw** [comment]
> 你的需求是把机场下发错的配置软件转换成可以用的吗？

是的。

**Comment by wonfen** [comment]
暂无计划
