### ISSUE TITLE
[BUG] 使用JavaScript编辑config.rules不生效。

### ISSUE THREAD

**Issue by Kane-Kuroneko** [clash-verge-rev/clash-verge-rev#1661]
### 问题描述 / Describe the bug

使用js编辑config.rules不生效，无论将rules改为任何合法值最终生成的yaml中依然是config原本的rules规则
对proxy-groups , proxies的修改均有效,唯独rules无效

### 复现步骤 / To Reproduce

1. 修改script.js , log最终返回的config.rules
2. 点击火苗重新激活订阅
3. 查看console和yaml文件 , 最终yaml的rules与return的config.rules不一致 , yaml的rules还是自带的那份.
![image](https://github.com/user-attachments/assets/1a44e247-6a16-4606-b3f6-c7275d53d259)
![image](https://github.com/user-attachments/assets/2e79e679-4919-49fb-858c-9c74de95ead5)
![image](https://github.com/user-attachments/assets/5c331e99-c2ac-40fb-b930-a1cc90fba54d)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11 23H2 专业工作站

### 日志 / Log

日志没有异常

**Comment by wonfen** [comment]
一般不生效都是因为脚本没有写好导致的。再检查一遍脚本。

**Comment by PctAIGM** [comment]
为啥要加export，你不会是聪nyanpasu的例子复制过来的吧？

**Comment by Kane-Kuroneko** [comment]
> 一般不生效都是因为脚本没有写好导致的。再检查一遍脚本。

我反复测试过多遍 , 就算用一个纯的config.rules = [] 都不会生效. 你可以自己试试



> 为啥要加export，你不会是聪nyanpasu的例子复制过来的吧？

因为我用webpack打包了,用的是打包后的代码运行. 图上贴的是打包前

**Comment by PctAIGM** [comment]
> > 一般不生效都是因为脚本没有写好导致的。再检查一遍脚本。
> 
> 我反复测试过多遍 , 就算用一个纯的config.rules = [] 都不会生效. 你可以自己试试
> 
> > 为啥要加export，你不会是聪nyanpasu的例子复制过来的吧？
> 
> 因为我用webpack打包了,用的是打包后的代码运行. 图上贴的是打包前

那你应该贴你生成后的代码，你这截图的代码也没看到哪来修改了rules

**Comment by Kane-Kuroneko** [comment]
> > > 一般不生效都是因为脚本没有写好导致的。再检查一遍脚本。
> > 
> > 我反复测试过多遍 , 就算用一个纯的config.rules = [] 都不会生效. 你可以自己试试
> > 
> > > 为啥要加export，你不会是聪nyanpasu的例子复制过来的吧？
> > 
> > 因为我用webpack打包了,用的是打包后的代码运行. 图上贴的是打包前
> 
> 那你应该贴你生成后的代码，你这截图的代码也没看到哪来修改了rules

哥们我不想说话难听，但回复技术问题可以带点脑子吗？console.log打印的对象和控制台输出的数组是看不到？我那么复杂和庞大的打包后文件要贴出来给你看？！

**Comment by Kane-Kuroneko** [comment]
好吧 , 我知道问题在哪了。 在`订阅->右键编辑文件`这里, 显示的是从server上下载的原始yaml , 而非经过script修改后的。如果要看修改的后文件则必须去`设置->当前配置`。这个GUI设计比较容易误导人， 我会再开个issue来建议优化为更友好的用户界面
![image](https://github.com/user-attachments/assets/95a5f06e-0f5d-40f3-9e90-217614d5c7eb)

**Comment by PctAIGM** [comment]
> > > > 一般不生效都是因为脚本没有写好导致的。再检查一遍脚本。
> > > 
> > > 
> > > 我反复测试过多遍 , 就算用一个纯的config.rules = [] 都不会生效. 你可以自己试试
> > > > 为啥要加export，你不会是聪nyanpasu的例子复制过来的吧？
> > > 
> > > 
> > > 因为我用webpack打包了,用的是打包后的代码运行. 图上贴的是打包前
> > 
> > 
> > 那你应该贴你生成后的代码，你这截图的代码也没看到哪来修改了rules
> 
> 哥们我不想说话难听，但回复技术问题可以带点脑子吗？console.log打印的对象和控制台输出的数组是看不到？我那么复杂和庞大的打包后文件要贴出来给你看？！

你有脑子就不会这样提issue了
