### ISSUE TITLE
[Feature] 自定义Windows系统代理格式

### ISSUE THREAD

**Issue by ixff** [clash-verge-rev/clash-verge-rev#1664]
### 功能描述 / Feature description

请求增加Windows上自定义系统代理格式的功能，比如 http=http://{ip}:{http_port};https=http://{ip}:{http_port}

### 使用场景 / Use case

clash verge rev在Windows上的系统代理格式是 **127.0.0.1:port** 的形式，在一些情况下会遇到问题，比如 https://github.com/2dust/v2rayN/issues/2065

**Comment by wonfen** [comment]
系统代理的设置是通过windows自身的api实现的，哪里来的设置一说？

如果你说的是环境变量的话，可以复制出来自行修改。

**Comment by wonfen** [comment]
> > 系统代理的设置是通过windows自身的api实现的，哪里来的设置一说？
> > 如果你说的是环境变量的话，可以复制出来自行修改。
> 
> 没看懂你什么意思。 这个问题cfw/v2rayn/nekoray都修复了，上边链接里有v2rayn作者的回复。

<img width="179" alt="image" src="https://github.com/user-attachments/assets/23b1145b-b6a4-4604-917c-8efdce7f5e04">

目前windows下复制出的环境变量是这样的格式：
```
$env:HTTP_PROXY="http://127.0.0.1:7897"; $env:HTTPS_PROXY="http://127.0.0.1:7897"
```
放到Powershell中执行即可代理命令行的程序。
有什么问题？
