### ISSUE TITLE
[BUG] Tun代理和系统代理都没有正常启动

### ISSUE THREAD

**Issue by Asahina-Mafuyu** [clash-verge-rev/clash-verge-rev#1665]
### 问题描述 / Describe the bug

换了一个新的订阅之后依旧还是和以前一样用的TUN代理但是没有正常启动。
![微信图片_20240902214505](https://github.com/user-attachments/assets/558e1133-e5d4-4f3a-8c29-4dbdc606433d)
![微信图片_20240902214513](https://github.com/user-attachments/assets/e2098ef2-f6e3-4889-b3c6-45b82da03373)

### 复现步骤 / To Reproduce

旧订阅过期来换一个新订阅正常打开启用TUN模式和开启服务，但是没有正常运作

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

暂无

**Comment by Asahina-Mafuyu** [comment]
但是在旧的windows版本可以正常使用

**Comment by wonfen** [comment]
啥都不提供怎么判断问题？

**Comment by eronez** [comment]
what's your tun stack? And any log?
