### ISSUE TITLE
[BUG] 代理信息自动消失，重启才能解决。

### ISSUE THREAD

**Issue by maorui2k** [clash-verge-rev/clash-verge-rev#1667]
### 问题描述 / Describe the bug

Calsh Verge 1.7.7版本。
运行一段时间后，就会出现这样的问题。规则、全局、直连，都没有任何显示。浏览器无法访问网站，感觉是系统代理服务已经失效。重启客户端能解决，但这个问题经常出现，还没什么规律。
![1725329668650](https://github.com/user-attachments/assets/5655f8ab-b226-4385-9038-40c8d6e093d8)

### 复现步骤 / To Reproduce

不知道具体步骤，经常是使用中突然就出现。也没对界面或者功能进行过操作。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win 10

### 日志 / Log

收集了一下日志最后的部分。
Service log:
time="2024-09-02T10:28:24.8033511+08:00" level=debug msg="re-creating the http client due to requesting https://101.101.101.101:443/dns-query: Get \"https://101.101.101.101:443/dns-query?dns=AAABAAABAAAAAAAAA3d3dwlqZXRicmFpbnMDY29tAAAcAAE\": context deadline exceeded"
time="2024-09-02T10:28:24.8033511+08:00" level=debug msg="[https://101.101.101.101:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-09-02T10:28:24.8033511+08:00" level=debug msg="re-creating the http client due to requesting https://9.9.9.11:5053/dns-query: Get \"https://9.9.9.11:5053/dns-query?dns=AAABAAABAAAAAAAAA3d3dwlqZXRicmFpbnMDY29tAAAcAAE\": context deadline exceeded"
time="2024-09-02T10:28:24.8033511+08:00" level=debug msg="[https://9.9.9.11:5053/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-09-02T10:28:24.8033511+08:00" level=debug msg="re-creating the http client due to requesting https://101.101.101.101:443/dns-query: Get \"https://101.101.101.101:443/dns-query?dns=AAABAAABAAAAAAAABXN5cmJwA2NkbgRub2RlAWEIZGRuc2tldHEDeHl6AAAcAAE\": context deadline exceeded"
time="2024-09-02T10:28:24.8033511+08:00" level=debug msg="re-creating the http client due to requesting https://9.9.9.11:5053/dns-query: Get \"https://9.9.9.11:5053/dns-query?dns=AAABAAABAAAAAAAABXN5cmJwA2NkbgRub2RlAWEIZGRuc2tldHEDeHl6AAAcAAE\": context deadline exceeded"
time="2024-09-02T10:28:24.803894+08:00" level=debug msg="[https://9.9.9.11:5053/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-09-02T10:28:24.8033511+08:00" level=debug msg="[https://101.101.101.101:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-09-02T10:28:24.8039164+08:00" level=debug msg="re-creating the http client due to requesting https://9.9.9.11:5053/dns-query: Get \"https://9.9.9.11:5053/dns-query?dns=AAABAAABAAAAAAAAA3d3dwlqZXRicmFpbnMDY29tAAAcAAE\": context deadline exceeded"
time="2024-09-02T10:28:24.8039164+08:00" level=debug msg="re-creating the http client due to requesting https://101.101.101.101:443/dns-query: Get \"https://101.101.101.101:443/dns-query?dns=AAABAAABAAAAAAAAA3d3dwlqZXRicmFpbnMDY29tAAAcAAE\": context deadline exceeded"
time="2024-09-02T10:28:24.8039164+08:00" level=debug msg="[https://101.101.101.101:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-09-02T10:28:24.8039164+08:00" level=debug msg="[https://9.9.9.11:5053/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-09-02T10:28:24.8039164+08:00" level=debug msg="re-creating the http client due to requesting https://101.101.101.101:443/dns-query: Get \"https://101.101.101.101:443/dns-query?dns=AAABAAABAAAAAAAABXN5cmJwA2NkbgRub2RlAWEIZGRuc2tldHEDeHl6AAAcAAE\": context deadline exceeded"
time="2024-09-02T10:28:24.8039164+08:00" level=debug msg="re-creating the http client due to requesting https://9.9.9.11:5053/dns-query: Get \"https://9.9.9.11:5053/dns-query?dns=AAABAAABAAAAAAAABXN5cmJwA2NkbgRub2RlAWEIZGRuc2tldHEDeHl6AAAcAAE\": context deadline exceeded"
time="2024-09-02T10:28:24.8039164+08:00" level=debug msg="[https://9.9.9.11:5053/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-09-02T10:28:24.8039164+08:00" level=debug msg="[https://101.101.101.101:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-09-02T10:28:26.8782531+08:00" level=debug msg="re-creating the http client due to requesting https://9.9.9.11:5053/dns-query: Get \"https://9.9.9.11:5053/dns-query?dns=AAABAAABAAAAAAAABXRyYWNrAmxjBXF1YXJrAmNuAAAcAAE\": connect failed: dial tcp 9.9.9.11:5053: i/o timeout"
time="2024-09-02T10:28:26.8787441+08:00" level=debug msg="[https://9.9.9.11:5053/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-09-02T10:28:26.8787441+08:00" level=debug msg="re-creating the http client due to requesting https://101.101.101.101:443/dns-query: Get \"https://101.101.101.101:443/dns-query?dns=AAABAAABAAAAAAAABXRyYWNrAmxjBXF1YXJrAmNuAAAcAAE\": context deadline exceeded"
time="2024-09-02T10:28:26.8787441+08:00" level=debug msg="[https://101.101.101.101:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-09-02T10:28:26.8787441+08:00" level=debug msg="re-creating the http client due to requesting https://101.101.101.101:443/dns-query: Get \"https://101.101.101.101:443/dns-query?dns=AAABAAABAAAAAAAABXRyYWNrAmxjBXF1YXJrAmNuAAAcAAE\": context deadline exceeded"
time="2024-09-02T10:28:26.8787441+08:00" level=debug msg="[https://101.101.101.101:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-09-02T10:28:30.1678854+08:00" level=debug msg="Auth success from 127.0.0.1:2731 -> "
time="2024-09-02T10:28:30.1678854+08:00" level=debug msg="[Rule] use default rules"

另一个log，本次出问题前只有1行。
2024-09-03 09:53:06 INFO - running timer task `RJjvQlu6RmiG`

**Comment by maorui2k** [comment]
刚发现servicce日志是前一天的，应该也没什么关系。

**Comment by maorui2k** [comment]
我试过彻底删除clash，重新安装。但问题依旧。

**Comment by wonfen** [comment]
一般是这个问题： https://www.clashverge.dev/faq/other.html#_5

**Comment by maorui2k** [comment]
> 我试过彻底删除clash，重新安装。但问题依旧。

不应该是这个，Bind只会在启动时候出现。我是使用当中突然出现的。

**Comment by wonfen** [comment]
> > 我试过彻底删除clash，重新安装。但问题依旧。
> 
> 不应该是这个，Bind只会在启动时候出现。我是使用当中突然出现的。

有没有可能在使用过程当中突然启动了另外一个软件导致端口冲突？

**Comment by maorui2k** [comment]
> > > 我试过彻底删除clash，重新安装。但问题依旧。
> > 
> > 
> > 不应该是这个，Bind只会在启动时候出现。我是使用当中突然出现的。
> 
> 有没有可能在使用过程当中突然启动了另外一个软件导致端口冲突？ 出现问题的时候按文档的说明修改一下端口，看看能不能恢复。

除非是Clash verge自己重新bind，别的软件不可能的。我刚试过改端口号。

**Comment by maorui2k** [comment]
刚刚又出现了新的情况。这次代理列表没消失，但是点击规则/全局/直连，界面不切换。
检查了一下bind情况，clash verge的确实丢了，没有监听端口。但也没有其他程序bind同一个端口。
我打开了debug日志，但没有记录。

**Comment by maorui2k** [comment]
确认是verge-mihomo.exe崩溃了。怎么能查看日志？

**Comment by wonfen** [comment]
> 确认是verge-mihomo.exe崩溃了。怎么能查看日志？

https://www.clashverge.dev/guide/log.html

**Comment by yanpkuer** [comment]
目前有解决办法嘛？我也出现这个情况，基本上只能重启

**Comment by y-noah** [comment]
一样的问题，重启，重装也不能保证100%解决该问题

**Comment by y-noah** [comment]
> 一般是这个问题： https://www.clashverge.dev/faq/other.html#_5

尝试重新设置端口了，问题依然存在
