### ISSUE TITLE
[Feature] 面板失去焦点后自动关闭

### ISSUE THREAD

**Issue by YexuanXiao** [clash-verge-rev/clash-verge-rev#1669]
### 功能描述 / Feature description

添加面板失去焦点后自动关闭的功能

### 使用场景 / Use case

面板不需要常驻桌面，因此大部分情况下为了节约系统资源，避免Webview在后台运行，需要手动在右上角关闭面板。
而此功能可以大大简化该操作的复杂性。

**Comment by wonfen** [comment]
暂无计划。
