### ISSUE TITLE
[BUG]重新安装verge会出现文件占用[添加/重新安装组件]

### ISSUE THREAD

**Issue by ngo5** [clash-verge-rev/clash-verge-rev#167]
### Describe the bug

似乎是卸载的文件没有卸载干净导致。

![屏幕截图 2023-12-20 140244](https://github.com/clash-verge-rev/clash-verge-rev/assets/111275866/12e967e3-f35b-4eb9-9e82-af95728d97eb)
![屏幕截图 2023-12-20 135915](https://github.com/clash-verge-rev/clash-verge-rev/assets/111275866/d1d2a388-d277-43f8-bf27-4dbcf74c6de4)

### To Reproduce

卸载完成clash-meta.exe并没有删除，导致重新安装的时候显示占用。

### Platform

Windows

### System Version

Windows10 22H2

### Software Version

v1.4.5

**Comment by wzsthehill** [comment]
卸载时并没有taskkill clash-meta.exe，任务管理器结束进程点重试就好了

**Comment by wonfen** [comment]
目前版本已经解决。

**Comment by ngo5** [comment]
> 目前版本已经解决。

我新版v1.5.6又试了试，还是出现这个问题。

clash verge运行中重新安装会出现占用，关闭clash verge再重新安装就不会出现占用。

![批注 2024-03-10 143712](https://github.com/clash-verge-rev/clash-verge-rev/assets/111275866/c84bde23-da02-4123-ae28-f41a2b3ba5de)
