### ISSUE TITLE
[BUG] 订阅+增加自建节点&自建代理组，自建的不显示在“代理”中

### ISSUE THREAD

**Issue by iceelee** [clash-verge-rev/clash-verge-rev#1671]
### 问题描述 / Describe the bug

升级后，原merge配置丢失，随后看官方更新说明，在已有一个订阅后，需要再增加一个自建的节点，在全局扩展配置中增加以下配置
proxy-providers:
>jp:
>>type: http
>>url: https://vpn.xxxxxx.com
>>port: 12443
>>password: Pf4zccUlC8W
    
prepend-proxy-groups:
>`-` name: "自建"
>>type: select
>>proxies:
>>>`-` jp
      
按以上配置增加后，语法没有报错，但“代理”中看不到这个代理组。

### 复现步骤 / To Reproduce

升级前能正常使用的配置
append-proxy-providers:
>`-` name: jp
>>type: trojan
>>servers: vpn.xxxxxx.com
>>port: 12443
>>password: Pf4zccUlC8W
    
append-proxy-groups:
>`-` name: "自建"
>>type: select
>>proxies:
>>>`-` jp

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版

### 日志 / Log

无

**Comment by Hinlavic** [comment]
升级后的那个`jp`是`proxy-providers`，要放在`use`下，而不是`proxies`。

**Comment by wonfen** [comment]
> 升级后的那个`jp`是`proxy-providers`，要放在`use`下，而不是`proxies`。

按这个方法排查你的写法。

**Comment by iceelee** [comment]
> 升级后的那个`jp`是`proxy-providers`，要放在`use`下，而不是`proxies`。

谢谢大佬回复，没太理解你说的use是什么意思，语法文档连接404：https://wiki.metacubex.one/config/syntax/#_5

按上面的方法添加后，主界面右上角会多出一个“代理集合”按扭，点看能看到我添加的自建代理，但无法选中使用
![image](https://github.com/user-attachments/assets/bfacde0b-371b-474d-880d-0941b0e728eb)

**Comment by Hinlavic** [comment]
[proxy-groups configuration - mihomo docs](https://wiki.metacubex.one/en/config/proxy-groups/#:~:text=proxies%3A%0A%20%20%2D%20DIRECT%0A%20%20%2D%20ss%0A%20%20use%3A%0A%20%20%2D%20provider1%0A%20%20%2D%20provider1)
```yaml
prepend-proxy-groups:
- name: "自建"
  type: select
  use:
  - jp
```

**Comment by hysyyds** [comment]
> > 升级后的那个`jp`是`proxy-providers`，要放在`use`下，而不是`proxies`。
> 
> 谢谢大佬回复，没太理解你说的use是什么意思，语法文档连接404：https://wiki.metacubex.one/config/syntax/#_5
> 
> 按我上面提问的方法添加后，主界面右上角会多出一个“代理集合”按扭，点看能看到我添加的自建代理，但无法选中使用 ![image](https://private-user-images.githubusercontent.com/18380546/364253198-bfacde0b-371b-474d-880d-0941b0e728eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDc2OTYsIm5iZiI6MTcyNzYwNzM5NiwicGF0aCI6Ii8xODM4MDU0Ni8zNjQyNTMxOTgtYmZhY2RlMGItMzcxYi00NzRkLTg4MGQtMDk0MWIwZTcyOGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDEwNTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhODk0NTE1NzcwNzIxOTZmYjBlMjUwMTQzNWM5NzE0MTcxZDgzNmNiYjA2NTU3MDA0MjIzYjcyZGQyZjgwODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xV5j2uwtaFz-71FRQ4g94r_JL6Bez-yuXG6IurpYyEM)

同样的问题，请问解决了吗？
