### ISSUE TITLE
[BUG] 2.0.0代理列表为空,

### ISSUE THREAD

**Issue by QQ804218** [clash-verge-rev/clash-verge-rev#1673]
### 问题描述 / Describe the bug

2.0.0代理列表为空,

### 复现步骤 / To Reproduce

打开后代理列表为空,更新后还是一样.

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 27695

### 日志 / Log

无

**Comment by wonfen** [comment]
还再开发，没发布。
