### ISSUE TITLE
[BUG] 为什么2024版本的kali上使用不了，有一个依赖包找不到

### ISSUE THREAD

**Issue by maike009** [clash-verge-rev/clash-verge-rev#1674]
### 问题描述 / Describe the bug

[BUG] 为什么2024版本的kali上使用不了，有一个依赖包找不到，libwebkit2gtk-4.0-37就是这个

### 复现步骤 / To Reproduce

安装时报错

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

kalilinux2024

### 日志 / Log

缺少依赖libwebkit2gtk-4.0-37

**Comment by wonfen** [comment]
看文档： https://www.clashverge.dev/faq/linux.html
