### ISSUE TITLE
tun模式下+EasyConnect VPN开启的情况下，无法访问国内网站[BUG] 

### ISSUE THREAD

**Issue by zjn1234** [clash-verge-rev/clash-verge-rev#1675]
### 问题描述 / Describe the bug

开启tun模式，然后使用EasyConnect软件登录公司vpn（公司vpn对应的服务器只有内网，没有外网），然后浏览器只能访问国外的网站，无法访问国内的网站，设置全局代理的话，国内的网站也可以访问

### 复现步骤 / To Reproduce

开启tun模式，然后使用EasyConnect软件登录公司vpn（公司vpn对应的服务器只有内网，没有外网），然后浏览器只能访问国外的网站，无法访问国内的网站，设置全局代理的话，国内的网站也可以访问

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Ventura 13.6.6

### 日志 / Log

只是提示连接超时，无反应。怀疑是不是国内的网站走了公司的vpn

**Comment by wonfen** [comment]
这要看你的easyconnect和tun的路由优先级哪个高了，请自行排查

**Comment by zjn1234** [comment]
@wonfen  执行curl 命令返回结果如下：

`curl www.baidu.com -v                                                                                        52 ✘  5s   15:45:28 
*   Trying 198.18.0.47:80...
* Connected to www.baidu.com (198.18.0.47) port 80
> GET / HTTP/1.1
> Host: www.baidu.com
> User-Agent: curl/8.4.0
> Accept: */*
>
* Empty reply from server
* Closing connection
curl: (52) Empty reply from serve`

这说明应该是先走的clash的tun吧。但是无响应

**Comment by wonfen** [comment]
目测是先走了tun，然后tun出去又被easy conn接管了；因为你用的是fakeip模式，出去以后没有经过clash内核，直接进入了easy conn的虚拟网卡，导致路由失败。
你这个场景下就用系统代理吧。

**Comment by zjn1234** [comment]
手动指定流量出口interface-name这个问题就没有了，很奇怪。难道是自动识别不准？走国内直接路由到了另一个utun
