### ISSUE TITLE
[BUG] Ubuntu24.04 tun功能不正常

### ISSUE THREAD

**Issue by yanyan1716330643** [clash-verge-rev/clash-verge-rev#1676]
### 问题描述 / Describe the bug

1.已经成功安装并能正常使用
libwebkit2gtk-4.0-37的问题已经手动解决和修复
参考https://github.com/clash-verge-rev/clash-verge-rev/issues/1472 sAkuraOfficial的回复手动解决了
2.tun功能安装提示成功且启用禁用没有异常
软件界面：
![图片](https://github.com/user-attachments/assets/f143b9b5-9ee9-44a0-b051-81590cc7f8c9)
ifconfig终端显示：
![图片](https://github.com/user-attachments/assets/c812f956-43e5-4144-b0e6-b1e30dc0bd53)
ping baidu.com已经显示走了tun网络，但是不通
sudo ufw status 防火墙也是关闭的，而且
```
# /etc/sysctl.conf - Configuration file for setting system variables
# See /etc/sysctl.d/ for additional system variables.
# See sysctl.conf (5) for information.
#

#kernel.domainname = example.com

# Uncomment the following to stop low-level messages on console
#kernel.printk = 3 4 1 3

###################################################################
# Functions previously found in netbase
#

# Uncomment the next two lines to enable Spoof protection (reverse-path filter)
# Turn on Source Address Verification in all interfaces to
# prevent some spoofing attacks
#net.ipv4.conf.default.rp_filter=1
#net.ipv4.conf.all.rp_filter=1

# Uncomment the next line to enable TCP/IP SYN cookies
# See http://lwn.net/Articles/277146/
# Note: This may impact IPv6 TCP sessions too
#net.ipv4.tcp_syncookies=1

# Uncomment the next line to enable packet forwarding for IPv4
#net.ipv4.ip_forward=1

# Uncomment the next line to enable packet forwarding for IPv6
#  Enabling this option disables Stateless Address Autoconfiguration
#  based on Router Advertisements for this host
#net.ipv6.conf.all.forwarding=1


###################################################################
# Additional settings - these settings can improve the network
# security of the host and prevent against some network attacks
# including spoofing attacks and man in the middle attacks through
# redirection. Some network environments, however, require that these
# settings are disabled so review and enable them as needed.
#
# Do not accept ICMP redirects (prevent MITM attacks)
#net.ipv4.conf.all.accept_redirects = 0
#net.ipv4.conf.default.accept_redirects = 0
# _or_
# Accept ICMP redirects only for gateways listed in our default
# gateway list (enabled by default)
 net.ipv4.conf.all.secure_redirects = 1
#
# Do not send ICMP redirects (we are not a router)
# net.ipv4.conf.all.send_redirects = 0
#
# Log Martian Packets
net.ipv4.conf.all.log_martians = 1
#

###################################################################
# Magic system request Key
# 0=disable, 1=enable all, >1 bitmask of sysrq functions
# See https://www.kernel.org/doc/html/latest/admin-guide/sysrq.html
# for what other values do
#kernel.sysrq=438
net.ipv4.ip_forward=1
```

### 复现步骤 / To Reproduce

对比windows版本的，windows的是好的。Ubuntu24.04 上必现

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu24.04

### 日志 / Log

#log 正常的
09-04 13:11:16INFO
[TCP] 127.0.0.1:52526 --> collector.github.com:443 match DomainKeyword(github) using 悠兔[剩余流量：128.52 GB]
09-04 13:11:22INFO
[TCP] 127.0.0.1:52542 --> www.google.com:443 match DomainKeyword(google) using 悠兔[剩余流量：128.52 GB]
09-04 13:11:22INFO
[TCP] 127.0.0.1:52554 --> github.com:443 match DomainKeyword(github) using 悠兔[剩余流量：128.52 GB]
09-04 13:11:24INFO
[TCP] 127.0.0.1:40290 --> avatars.githubusercontent.com:443 match DomainKeyword(github) using 悠兔[剩余流量：128.52 GB]

**Comment by wonfen** [comment]
目前的主流正向代理协议不支持imcp协议代理，当然不通了。

你说的不正常是指什么不正常？

**Comment by yanyan1716330643** [comment]
> 目前的主流正向代理协议不支持imcp协议代理，当然不通了。
> 
> 你说的不正常是指什么不正常？

哦哦多谢，我这边因为做区块链相关开发，区块链client底层协议层ping不通的就不能使用他底层的原始客户端。如：
不使用代理模式情况下  ping baidu.com/ping google.com/api.devnet.solana.com 只有百度能通
不使用tun模式情况下开代理 ping baidu.com 可以/ping google.com 可以/api.devnet.solana.com 不可以（但是能http协议通）
windows在使用tun情况下开代理 ping baidu.com/ping google.com/api.devnet.solana.com 都可以
Ubuntu24.04在使用tun情况下开代理 ping baidu.com/ping google.com/api.devnet.solana.com 都不可以
所以我这边需求就是想绕过GFW的神秘力量，想在Ubuntu24.04的操作系统上正常开启tun

**Comment by Royal520** [comment]
![Screenshot_20240905_221647](https://github.com/user-attachments/assets/639e42b3-a02e-4820-a4a0-882d7cf4b1a7)
我ping的通，但是docker pull 还是会超时

**Comment by Royal520** [comment]
windows 上确实都正常，Linux上有时候没有正确接管流量，把tun和服务模式重启一下可以解决。
![Screenshot_20240905_222002](https://github.com/user-attachments/assets/137e0a84-f436-44b5-94ab-35f0a9db67a7)

**Comment by yanyan1716330643** [comment]
尝试过重启，以及别的方式折腾。因为Ubuntu24.04当时装软件的时候就不是很顺，比如libwebkit2gtk-4.0-37等问题，所以感觉还是哪里不兼容导致什么问题的。目前也不是很急，强依赖tun模式的项目在windows上搭建环境了。以后再等等更新，现在用24.04还不是主力军。其实现在除了tun模式有问题，其他都是正常的。开发需要，不然也就不反馈这个问题了，给一样问题的人有个参考吧。如果只是用24.04用 参考https://github.com/clash-verge-rev/clash-verge-rev/issues/1472 sAkuraOfficial的回复手动解决了
