### ISSUE TITLE
[BUG] Linux also need to "unset dns"

### ISSUE THREAD

**Issue by eronez** [clash-verge-rev/clash-verge-rev#1678]
### 问题描述 / Describe the bug

Ubuntu dns does not restore after disable TUN mode.
clash-verge-service only unset dns for MacOS
https://github.com/clash-verge-rev/clash-verge-service/blob/e74e419f004275cbf35a427337d3f8c771408f07/src/service/web.rs#L137

### 复现步骤 / To Reproduce

1. Start Clash verge  
2. Enable TUN mode(/etc/resolv.conf 198.18.0.2 added)
3. Disable TUN mode(/etc/resolv.conf 198.18.0.2 still exists, `sudo systemctl restart systemd-resolved.service` can flush resolv.conf and 198.18.0.2 deleted)

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu 24.04

### 日志 / Log

after enable TUN mode
`level=debug msg="[DNS] system dns update to [198.18.0.2 192.168.2.1]"`
after disable TUN mode
no correspond log

**Comment by wonfen** [comment]
试试2.0版，应该已经解决了这个问题。

**Comment by eronez** [comment]
The issue has been identified.

Upstream [sing-tun](https://github.com/SagerNet/sing-tun/blob/dev/tun_linux.go) does not execute `resolvectl revert tunName` when closing TUN.

If anyone encounters this, you can manually build mihomo with https://github.com/SagerNet/sing-tun/pull/64. (Tested and works well.)
