### ISSUE TITLE
[BUG] 关闭app后，重启电脑无法上网

### ISSUE THREAD

**Issue by vtheone** [clash-verge-rev/clash-verge-rev#1679]
### 问题描述 / Describe the bug

我开启了TUN模式和系统代理，关闭app后，重启电脑无法上网，用火绒扫描发现是IE代理错误，修复后才能正常上网

### 复现步骤 / To Reproduce

开启app，使用规则模式，关闭后，过段时间再重启电脑，无法上网

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 10

### 日志 / Log

没有

**Comment by wonfen** [comment]
在开启系统代理的情况下，重启电脑系统代理不会被关闭。
你把软件设置为开机启动。
