### ISSUE TITLE
[BUG]1.4.3之后开机自启无效

### ISSUE THREAD

**Issue by rmwxxwmr** [clash-verge-rev/clash-verge-rev#168]
### Describe the bug

开机自启设置无效,需要手动打开软件

### To Reproduce

设置开机自启,重启电脑软件没有启动

### Platform

Windows

### System Version

win11 23h2

### Software Version

1.4.3+

**Comment by MystiPanda** [comment]
重新设置即可，另外不要在管理员权限运行的时候设置开机启动。
