### ISSUE TITLE
[BUG] 订阅的定时自动更新无效

### ISSUE THREAD

**Issue by KKKayleX** [clash-verge-rev/clash-verge-rev#1680]
### 问题描述 / Describe the bug

在订阅 - 编辑配置中，默认设置了 1440 分钟的更新间隔，但实际未生效
![image](https://github.com/user-attachments/assets/5db7e494-c4d9-4da8-a2c7-213e78e33c76)
![image](https://github.com/user-attachments/assets/9b7c0416-ca2f-4384-8ec0-2e49bea5b39f)

### 复现步骤 / To Reproduce

1、右键某个订阅，打开编辑配置
2、确认更新间隔的时间
3、达到配置的更新间隔后发现该订阅未自动更新

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10

### 日志 / Log

No response

**Comment by wonfen** [comment]
是以软件运行时间计算的。

**Comment by KKKayleX** [comment]
好的谢谢，如果可以按现实时间计算的话可能会更符合直觉些

**Comment by BotswanaD** [comment]
> 是以软件运行时间计算的。

我也有这种困惑，觉得目前的自动更新策略挺难受的，已经把更新频率设置成60分钟了，但是还是可能几天才更新一次
