### ISSUE TITLE
[BUG] 20.04.1-Ubuntu缺少libayatana-appindicator3-1依赖

### ISSUE THREAD

**Issue by ZxnSnowy** [clash-verge-rev/clash-verge-rev#1681]
### 问题描述 / Describe the bug

正在选中未选择的软件包 clash-verge:i386。
(正在读取数据库 ... 系统当前共安装有 213724 个文件和目录。)
准备解压 .../clash-verge_1.7.7_i386.deb  ...
正在解压 clash-verge:i386 (1.7.7) ...
dpkg: 依赖关系问题使得 clash-verge:i386 的配置工作不能继续：
 clash-verge:i386 依赖于 libayatana-appindicator3-1.
 clash-verge:i386 依赖于 libwebkit2gtk-4.0-37.
 clash-verge:i386 依赖于 libgtk-3-0.

dpkg: 处理软件包 clash-verge:i386 (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
正在处理用于 gnome-menus (3.36.0-1ubuntu1) 的触发器 ...
正在处理用于 desktop-file-utils (0.24-1ubuntu3) 的触发器 ...
正在处理用于 mime-support (3.64ubuntu1) 的触发器 ...
在处理时有错误发生：
 clash-verge:i386

### 复现步骤 / To Reproduce

sudo dpkg -i clash-verge_1.7.7_i386.deb

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Linux os-super-Server 5.15.0-113-generic #123~20.04.1-Ubuntu SMp Wed Jun 12 17:33:13 UTC 2024 x86 64 x86_64 x86 64 GNU/Linux

### 日志 / Log

正在选中未选择的软件包 clash-verge:i386。
(正在读取数据库 ... 系统当前共安装有 213724 个文件和目录。)
准备解压 .../clash-verge_1.7.7_i386.deb  ...
正在解压 clash-verge:i386 (1.7.7) ...
dpkg: 依赖关系问题使得 clash-verge:i386 的配置工作不能继续：
 clash-verge:i386 依赖于 libayatana-appindicator3-1.
 clash-verge:i386 依赖于 libwebkit2gtk-4.0-37.
 clash-verge:i386 依赖于 libgtk-3-0.

dpkg: 处理软件包 clash-verge:i386 (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
正在处理用于 gnome-menus (3.36.0-1ubuntu1) 的触发器 ...
正在处理用于 desktop-file-utils (0.24-1ubuntu3) 的触发器 ...
正在处理用于 mime-support (3.64ubuntu1) 的触发器 ...
在处理时有错误发生：
 clash-verge:i386

**Comment by ZxnSnowy** [comment]
(正在读取数据库 ... 系统当前共安装有 213741 个文件和目录。)
准备解压 .../clash-verge_1.7.7_amd64.deb  ...
正在解压 clash-verge (1.7.7) 并覆盖 (1.7.7) ...
dpkg: 依赖关系问题使得 clash-verge 的配置工作不能继续：
 clash-verge 依赖于 libayatana-appindicator3-1；然而：
  未安装软件包 libayatana-appindicator3-1。

dpkg: 处理软件包 clash-verge (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
正在处理用于 gnome-menus (3.36.0-1ubuntu1) 的触发器 ...
正在处理用于 desktop-file-utils (0.24-1ubuntu3) 的触发器 ...
正在处理用于 mime-support (3.64ubuntu1) 的触发器 ...
在处理时有错误发生：
 clash-verge

**Comment by julyfire-wang** [comment]
sudo apt --fix-broken install

**Comment by id7729** [comment]
我遇到了和你一样的问题，请问你解决了吗？

**Comment by wagh311** [comment]
我也遇到了一样的问题

**Comment by SummrWhit** [comment]
https://shishengmi.com/2024/06/11/2024/06/%E8%A7%A3%E5%86%B3verge%E5%AE%89%E8%A3%85%E9%97%AE%E9%A2%98/
这个可以解决

**Comment by wagh311** [comment]
> https://shishengmi.com/2024/06/11/2024/06/%E8%A7%A3%E5%86%B3verge%E5%AE%89%E8%A3%85%E9%97%AE%E9%A2%98/ 这个可以解决

好的，谢谢
