### ISSUE TITLE
[Feature] openharmony

### ISSUE THREAD

**Issue by 001SM** [clash-verge-rev/clash-verge-rev#1682]
### 功能描述 / Feature description

问一下什么时候开发鸿蒙应用版本啊，我真的很需要这东西

### 使用场景 / Use case

鸿蒙原生应用的clash

**Comment by eronez** [comment]
`U need it` does not mean `lots of people need it`.

**Comment by 001SM** [comment]
> `U need it`并不意味着 。`lots of people need it`

Just because you don't need it doesn't mean tens of millions of users don't need it

**Comment by eronez** [comment]
> > `U need it`并不意味着 。`lots of people need it`
> 
> Just because you don't need it doesn't mean tens of millions of users don't need it

Have you ever seriously looked into Clash Verge Rev?

"A Clash Meta GUI based on Tauri (Windows, MacOS, Linux)"

This means:

1. Clash Verge is just a GUI, not the core mihomo. If you want to use Clash Verge on OpenHarmony, you need to port mihomo to the OpenHarmony platform. No mihomo, no Clash Verge.
2. Clash Verge uses Tauri. Does the OpenHarmony platform support Rust? No Tauri, no Clash Verge.
3. Tauri currently only supports Windows, MacOS, and Linux. OpenHarmony is not on the supported list, so Clash Verge cannot be implemented on this platform.

Additionally, OpenHarmony has different versions using different kernels, which you did not specify. 

Support for OpenHarmony by Clash Verge might be possible in the future, but certainly not now.

**Comment by 001SM** [comment]
> > > `U need it`并不意味着 。`lots of people need it`
> > 
> > 
> > 仅仅因为您不需要它并不意味着数千万用户不需要它
> 
> 你有没有认真研究过 Clash Verge Rev？
> 
> “基于 Tauri 的 Clash 元 GUI（Windows、MacOS、Linux）”
> 
> 这意味着：
> 
> 1. Clash Verge 只是一个 GUI，而不是核心 mihomo。如果你想在 OpenHarmony 上使用 Clash Verge，你需要将 mihomo 移植到 OpenHarmony 平台。没有 mihomo，没有 Clash Verge。
> 2. Clash Verge 使用 Tauri。OpenHarmony 平台支持 Rust 吗？没有 Tauri，没有 Clash Verge。
> 3. Tauri 目前仅支持 Windows、MacOS 和 Linux。OpenHarmony 不在支持列表中，因此 Clash Verge 无法在此平台上实施。
> 
> 此外，OpenHarmony 具有不同的版本，使用不同的内核，这些内核您没有指定。
> 
> Clash Verge 对 OpenHarmony 的支持可能在未来成为可能，但现在肯定不是。

Thank you for your suggestion, I will provide the problem to the relevant software for adaptation, according to the Hongmeng system architecture is the Hongmeng microkernel to connect the Linux driver and runtime, and there is a high probability that you can use Linux to make software

**Comment by BA489** [comment]
> > > `U need it`并不意味着 。`lots of people need it`
> > 
> > 
> > Just because you don't need it doesn't mean tens of millions of users don't need it
> 
> Have you ever seriously looked into Clash Verge Rev?
> 
> "A Clash Meta GUI based on Tauri (Windows, MacOS, Linux)"
> 
> This means:
> 
> 1. Clash Verge is just a GUI, not the core mihomo. If you want to use Clash Verge on OpenHarmony, you need to port mihomo to the OpenHarmony platform. No mihomo, no Clash Verge.
> 2. Clash Verge uses Tauri. Does the OpenHarmony platform support Rust? No Tauri, no Clash Verge.
> 3. Tauri currently only supports Windows, MacOS, and Linux. OpenHarmony is not on the supported list, so Clash Verge cannot be implemented on this platform.
> 
> Additionally, OpenHarmony has different versions using different kernels, which you did not specify.
> 
> Support for OpenHarmony by Clash Verge might be possible in the future, but certainly not now.

Thank you for being open to the idea. Yes for OpenHarmony, there is Linux kernel default as the standard system kernel as a base, however that can be customised by OEMs with their own kernels. But that's pretty much standard using OpenHarmony standard system for traditional normal computing with big RAM resources, 4GB and up.
