### ISSUE TITLE
[Feature] 希望添加自定义github代理功能

### ISSUE THREAD

**Issue by Sora39831** [clash-verge-rev/clash-verge-rev#1684]
### 功能描述 / Feature description

希望可以自定义github的代理，不然直连github几乎无法更新
比如：https://www.ghproxy.cn/https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v1.7.7/Clash.Verge_1.7.7_x64-setup.exe

### 使用场景 / Use case

更新时使用github代理获取releases

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/commit/d45929c604ef66985429c21fd350bc2a7f3d87d5
