### ISSUE TITLE
[BUG] MacOS出现工具栏图标BUG

### ISSUE THREAD

**Issue by CMEPCBHG** [clash-verge-rev/clash-verge-rev#1685]
### 问题描述 / Describe the bug

MacOS最新版，百分百复现。在苹果logo处出现这样的图标
![截屏2024-09-04 10 43 39](https://github.com/user-attachments/assets/0bbf69d3-4309-43cb-b841-914c39371c94)

### 复现步骤 / To Reproduce

只要是运行就能看见

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

MacOS 14.6.1

### 日志 / Log

刚刚重启了客户端，所以客户端中无日志

**Comment by wonfen** [comment]
看文档 https://www.clashverge.dev/faq/macos.html#macos_1
