### ISSUE TITLE
[Feature] 建议增加配置导入/导出功能。

### ISSUE THREAD

**Issue by qq11109071** [clash-verge-rev/clash-verge-rev#1686]
### 功能描述 / Feature description

每次重新安装CLASH软件、每次重新安装系统时，都需要重新配置！建议增加配置导入/导出功能。当然如果加入配置上传到服务器并进行同步配置。那就更完美了。。。

### 使用场景 / Use case

每次重新安装CLASH软件、每次重新安装系统时，都需要重新配置！

**Comment by DockerCS** [comment]
便携版就可以呀

**Comment by qq11109071** [comment]
portable或许是一个选择，但对我来说不是一个好的选择。因为我用的是脚本检测更新自动后台更新的。

**Comment by Jenichia** [comment]
帮顶，一个 JSON 文件就能搞定的东西，希望尽快实装。

**Comment by wonfen** [comment]
目前支持webdav同步配置
