### ISSUE TITLE
[BUG] 打开clash verge访问国内网站比如百度csdn等就会卡，有时访问不上，开启直连模式也没用，退出clash verge就好了，这是为啥？另一台电脑不会这样。。。

### ISSUE THREAD

**Issue by Dontla** [clash-verge-rev/clash-verge-rev#1687]
### 问题描述 / Describe the bug

打开clash verge访问国内网站比如百度csdn等就会卡，有时访问不上，无论开始规则模式还是开启直连模式都一样，退出clash verge就好了。。。

### 复现步骤 / To Reproduce

打开clash verge

访问国内网站比如百度csdn

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

[TCP] dial DIRECT (match DomainSuffix/microsoft.com) 127.0.0.1:59528(svchost.exe) --> 1d.tlu.dl.delivery.mp.microsoft.com:80 error: connect failed: dial tcp 20.219.237.180:80: i/o timeout connect failed: dial tcp [240e:968:1000:2::1a]:80: connectex: The requested address is not valid in its context.
09-06 22:19:51INFO
[UDP] 198.18.0.1:63405(verge-mihomo.exe) --> 45.11.104.186:443 match Match using 狗狗加速.com[🇮🇳14印度-移动/南方联通(hy2)]
09-06 22:19:54INFO
[UDP] 198.18.0.1:59140(verge-mihomo.exe) --> 45.11.104.186:443 match Match using 狗狗加速.com[🇮🇳14印度-移动/南方联通(hy2)]
09-06 22:20:00INFO
[UDP] 198.18.0.1:60863(verge-mihomo.exe) --> 45.11.104.186:443 match Match using 狗狗加速.com[🇮🇳14印度-移动/南方联通(hy2)]
09-06 22:20:20INFO
[UDP] 198.18.0.1:50518(verge-mihomo.exe) --> 45.11.104.186:443 match Match using 狗狗加速.com[🇮🇳14印度-移动/南方联通(hy2)]
09-06 22:20:26INFO
[TCP] 127.0.0.1:59600(msedge.exe) --> api.github.com:443 match DomainKeyword(github) using 狗狗加速.com[🇮🇳14印度-移动/南方联通(hy2)]
09-06 22:20:26WARNING
[TCP] dial DIRECT (match DomainSuffix/microsoft.com) 127.0.0.1:59591(svchost.exe) --> 1d.tlu.dl.delivery.mp.microsoft.com:80 error: connect failed: dial tcp 20.219.237.180:80: i/o timeout connect failed: dial tcp [240e:968:1000:2::1a]:80: connectex: The requested address is not valid in its context.
09-06 22:20:26WARNING
[TCP] dial DIRECT (match DomainSuffix/microsoft.com) 127.0.0.1:59594(svchost.exe) --> 1d.tlu.dl.delivery.mp.microsoft.com:80 error: connect failed: dial tcp 20.219.237.180:80: i/o timeout connect failed: dial tcp [240e:968:1000:2::1a]:80: connectex: The requested address is not valid in its context.
09-06 22:20:28INFO
[TCP] 127.0.0.1:59601(msedge.exe) --> api.vc.bilibili.com:443 match DomainSuffix(bilibili.com) using DIRECT
09-06 22:20:36WARNING
[TCP] dial DIRECT (match DomainSuffix/microsoft.com) 127.0.0.1:59612(svchost.exe) --> 1d.tlu.dl.delivery.mp.microsoft.com:80 error: connect failed: dial tcp 20.219.237.180:80: i/o timeout connect failed: dial tcp [240e:968:1000:2::1a]:80: connectex: The requested address is not valid in its context.
09-06 22:20:49INFO
[UDP] 198.18.0.1:63658(verge-mihomo.exe) --> 37.252.249.233:443 match Match using 狗狗加速.com[🇮🇳14印度-移动/南方联通(hy2)]
09-06 22:20:50INFO
[UDP] 198.18.0.1:63659(verge-mihomo.exe) --> 37.252.249.233:443 match Match using 狗狗加速.com[🇮🇳14印度-移动/南方联通(hy2)]
09-06 22:20:53INFO
[UDP] 198.18.0.1:52533(verge-mihomo.exe) --> 37.252.249.233:443 match Match using 狗狗加速.com[🇮🇳14印度-移动/南方联通(hy2)]
09-06 22:20:55INFO
[TCP] 127.0.0.1:59643(msedge.exe) --> sdk.rum.aliyuncs.com:443 match GeoIP(cn) using DIRECT
09-06 22:20:56INFO
[TCP] 127.0.0.1:59641(msedge.exe) --> g.csdnimg.cn:443 match DomainSuffix(cn) using DIRECT
09-06 22:20:56INFO
[TCP] 127.0.0.1:59673(msedge.exe) --> bizapi.csdn.net:443 match DomainSuffix(csdn.net) using DIRECT

**Comment by JackloveJam** [comment]
我怀疑是因为你本机手动设置过DNS
之前有过类似经历

**Comment by Dontla** [comment]
> 我怀疑是因为你本机手动设置过DNS 之前有过类似经历

可能是之前那家店的wifi的原因，我在这个酒店也是连wifi，发现没有问题，不知道之前那家店wifi做了什么

**Comment by kingFighter** [comment]
> 我怀疑是因为你本机手动设置过DNS 之前有过类似经历

@JackloveJam 谢谢
确实改为`自动获得DNS服务器地址`就OK了，但为什么之前手动设置DNS:
1. 未使用clash不卡
2. 使用clash及直连就卡了

#1和#2的ip及手动设置的dns都不变，也不应该是cdn之类的原因呀

**Comment by song9998** [comment]
我的正好相反， 打开国内的网站网速正常， 打开Facbook，上传图片都总是失败， 刷新页面页卡。 相当于国内网站正常，国外网站能打开，但是非常卡，特别是发送图片和视频。 这是什么情况
