### ISSUE TITLE
第1255行代码报错

### ISSUE THREAD

**Issue by gubei404** [clash-verge-rev/clash-verge-rev#1689]
### 问题描述 / Describe the bug

![1725682186419](https://github.com/user-attachments/assets/dc6d6547-36d5-45eb-8ddc-cfc9d5ff7067)
在打开电脑后更新订阅，打开关闭tun，服务模式都是报这行1255代码的错误，所有代理是空的，链接，规则，日志三个页面也什么也没有

### 复现步骤 / To Reproduce

所有方式都报错

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11  23H2

### 日志 / Log

[2024-09-07-1154.zip](https://github.com/user-attachments/files/16914329/2024-09-07-1154.zip)

**Comment by wonfen** [comment]
是否安装了什么安全软件？保密软件之类的？

**Comment by gubei404** [comment]
> 是否安装了什么安全软件？保密软件之类的？

没有，我重启电脑后恢复了。暂时不清楚什么原因导致的。
