### ISSUE TITLE
[BUG]内核无法加载，导致软件无法使用

### ISSUE THREAD

**Issue by wenruoa** [clash-verge-rev/clash-verge-rev#169]
### Describe the bug

打开软件后，内核不显示，手动切换Meta和Alpha依然无法加载成功，导致软件主界面不显示任何节点，也无法正常使用
![PixPin_2023-12-20_15-36-31](https://github.com/clash-verge-rev/clash-verge-rev/assets/34326682/374c0339-b274-46c2-8df2-c6484e2ade92)

### To Reproduce

正常双击打开软件，内核一直加载失败。重启电脑偶尔会解决该问题，但不是每次都可以解决。

### Platform

Windows

### System Version

win11专业版 22H2

### Software Version

1.4.5

**Comment by wonfen** [comment]
在软件目录下直接运行clash-meta.exe看看能否运行？

**Comment by wenruoa** [comment]
> 在软件目录下直接运行clash-meta.exe看看能否运行？

还是会出现描述的问题，现在临时的解决方式是不停的切换内核和重启内核，直到把内核切换出来就能用了，另外发现在alpha内核下软件不可用，只能meta内核可以正常使用

**Comment by wonfen** [comment]
现在最新版还有这个问题吗？

**Comment by wenruoa** [comment]
> 现在最新版还有这个问题吗？

问题依旧。电脑CPU是AMD的R7 5800H，是否与此相关呢？另一台intel i5 9300的电脑就从未遇到过这个问题。现在还是只能频繁重启内核才能临时解决。关掉软件后再打开（即使不重启电脑）这个问题依旧频繁出现。
好消息是现在切换到alpha内核也可以用，之前不行。
我可以收集下日志提供给你，如果有需要的话。
