### ISSUE TITLE
[BUG] 规则代理中GeoData优先级高于自定义规则中Rule的优先级

### ISSUE THREAD

**Issue by KVM-Explorer** [clash-verge-rev/clash-verge-rev#1690]
### 问题描述 / Describe the bug

- Windows Clash Verge Rev 1.7.7 
- 已阅读文档
- 新版本未解决问题

在规则代理模式下，配置自定义规则全局拓展配置，部分生效流量正常转发到代理服务器，但是部分网站没有走代理，而是走的直连，怀疑可能和GeoData的优先级有关。全局代理下工作正常

### 复现步骤 / To Reproduce

这里提供一个复现例子，在全局Merge规则中引入如下规则
```
prepend-rules:
  - DOMAIN-SUFFIX,themoviedb.org,节点选择
  - DOMAIN-SUFFIX,ghcr.io,节点选择
  - DOMAIN-SUFFIX,byr.pt,节点选择
  - DOMAIN-SUFFIX,jianguoyun.com,节点选择
```
其中themoviedb和ghcr正常转发到节点选择的代理server，但是jianguoyun依然是DIRECT连接,并且使用规则方面采用GeoIP规则，期望应该按照自定义规则走代理

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 23H2

### 日志 / Log

正常转发的流量
![image](https://github.com/user-attachments/assets/77d245ac-c584-4a3e-8313-fbe44d77d352)

未能转发的流量
![1725696246088](https://github.com/user-attachments/assets/14e5cddb-bcf8-4b7d-8064-66a4ddc6a733)

**Comment by JoeJoeyMa** [comment]
请问有解决办法吗，尝试ruleProviders和置顶规则还是不能修改优先级

**Comment by vipcxj** [comment]
你搞错原因了，真正原因更加离谱，prepend-rules的功能被删除了，所以你的配置是假的，加了特技的，压根没生效的~ 看了另一个issue才知道

**Comment by KVM-Explorer** [comment]
prepend-rules 功能issue和临时配置方法见 #1437
