### ISSUE TITLE
[BUG] clash导入大量结点导致内存溢出

### ISSUE THREAD

**Issue by shiny6667** [clash-verge-rev/clash-verge-rev#1691]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/240d37da-f53e-4ff1-a042-d18d5239b404)

### 复现步骤 / To Reproduce

导入订阅后呈现图片效果

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

none

**Comment by wonfen** [comment]
没有条件测试

**Comment by shiny6667** [comment]
[510节点.txt](https://github.com/user-attachments/files/16924826/510.txt)
这个节点转换成clash订阅后就内存溢出

**Comment by shiny6667** [comment]
> 没有条件测试
[510节点.txt](https://github.com/user-attachments/files/16924826/510.txt)
这个节点转换成clash订阅后就内存溢出
