### ISSUE TITLE
[BUG] Linux下的TUN模式无法使用

### ISSUE THREAD

**Issue by TritiumXs** [clash-verge-rev/clash-verge-rev#1692]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/699f97fb-cbc3-4bd2-80b6-13f8f49de344)
![image](https://github.com/user-attachments/assets/e3297cb8-49e6-4c0a-8ff1-9986a1b665df)
![image](https://github.com/user-attachments/assets/e6cacb96-f37a-4893-bf64-0232cae9da78)
Service Mode已经安装，并且TUN模式已开启，Mihomo虚拟网卡也已经出现。此时的配置文件没有任何问题（Verge中测试延迟全绿，可以通过浏览器Proxy访问Google），但是无法通过Terminal使用TUN透明代理

此外 还有一点信息 就是在ping google时，verge的connections标签中并没有出现google.com这个网址

### 复现步骤 / To Reproduce

- Linux Kernel: 6.10.8-arch1-1
- Rootfs: ArchLinux 截至Issue提交前的最新版本

1. 使用`yay -Sy clash-verge`安装最新版clash-verge
2. 安装Service Mode并开启TUN模式
3. 尝试在终端ping google.com

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Kernel: 6.10.8; Rootfs: ArchLinux

### 日志 / Log

日志中没有出现大于INFO级别的log

**Comment by eronez** [comment]
LMAO

**Comment by Thesoul20** [comment]
这个问题已经遗留很久了，Linux 上已经很长都没有正常使用Tun 模式了。并且自从更新到v1.7.5版本之后也不能正常使用全局模式了。

**Comment by commis** [comment]
可以尝试检查一下路由：ip route
如何 Mihomo没有加入默认路由，可以手动添加一下，如下：
sudo ip route add default dev Mihomo

不好的是每次开启TUN都需要做这个操作。

**Comment by SeasyecN** [comment]
> 可以尝试检查一下路由：ip route 如何 Mihomo没有加入默认路由，可以手动添加一下，如下： sudo ip route add default dev Mihomo
> 
> 不好的是每次开启TUN都需要做这个操作。



这个有效，但是经常导致内核崩溃，我不知道为什么
