### ISSUE TITLE
[BUG] 最新 alpha 2.0.0 覆盖升级后不显示代理节点

### ISSUE THREAD

**Issue by duyraven** [clash-verge-rev/clash-verge-rev#1695]
### 问题描述 / Describe the bug

如题，代理正常工作但是不显示代理节点

![image](https://github.com/user-attachments/assets/1fb3853b-402d-4b96-a7a1-3f4745282013)

### 复现步骤 / To Reproduce

旧版本覆盖升级 1.7.6>2.0.0

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 23H2 22631.4037

### 日志 / Log

[2024-09-09-0919.log](https://github.com/user-attachments/files/16924379/2024-09-09-0919.log)

**Comment by wonfen** [comment]
请测试今天最新的版本

**Comment by KUAPT** [comment]
> 请测试今天最新的版本

经测试覆盖安装今天的版本问题解决
