### ISSUE TITLE
[Feature] 请问有没有纯命令行版？ubuntu系统没有gui

### ISSUE THREAD

**Issue by lehaifeng000** [clash-verge-rev/clash-verge-rev#1696]
### 功能描述 / Feature description

希望能出一个linux命令行版本，比如可以通过命令clash-verge -i xxx.yaml来启动一个进程

### 使用场景 / Use case

我的ubuntu作为服务器，没有gui，没法用现在的版本

**Comment by jsonza6** [comment]
https://github.com/MetaCubeX/mihomo 
建议直接用内核

**Comment by eronez** [comment]
> A Clash Meta GUI based on Tauri (Windows, MacOS, Linux)

GUI !!!

**Comment by AkihaZhang** [comment]
那你用shellcrash不就行了吗

**Comment by Darkatse** [comment]
为什么不直接用docker
https://hub.docker.com/r/metacubex/mihomo

**Comment by lehaifeng000** [comment]
我找到解决办法了
nohup xvfb-run clash-verge &

**Comment by oximi123** [comment]
> 我找到解决办法了 nohup xvfb-run clash-verge &

请问这个应该如何配置config.yaml呢

**Comment by Tychristine** [comment]
> > 我找到解决办法了 nohup xvfb-run clash-verge &
> 
> 请问这个应该如何配置config.yaml呢

配置在内核文档 见 -[配置-虚空终端](https://wiki.metacubex.one/config)

**Comment by oximi123** [comment]
> > > 我找到解决办法了 nohup xvfb-run clash-verge &
> > 
> > 
> > 请问这个应该如何配置config.yaml呢
> 
> 配置在内核文档 见 -[配置-虚空终端](https://wiki.metacubex.one/config)

我的意思是，安装了这个软件之后去哪里替换config.yaml呢？

**Comment by oximi123** [comment]
> @oximi123 找你购买的订阅； shell如下脚本，请求配置文件; curl -o config.yaml https://(你的订阅链接) -A clash-verge/2.0.0 使用指定的user-Agent去请求服务端下发配置文件, -o参数用于输出config文件

感谢

**Comment by lehaifeng000** [comment]
> > 我找到解决办法了 nohup xvfb-run clash-verge &
> 
> 请问这个应该如何配置config.yaml呢
我是第一次启动，先不加xvfb-run，直接启动会有gui出来，配置好yaml，以后启动再加上这个 ，就不会出gui了

**Comment by MuYanustc** [comment]
> > > 我找到解决办法了 nohup xvfb-run clash-verge &
> > 
> > 
> > 请问这个应该如何配置config.yaml呢
> > 我是第一次启动，先不加xvfb-run，直接启动会有gui出来，配置好yaml，以后启动再加上这个 ，就不会出gui了

没有xvfb-run 没有root咋办....只找到安装了 clash-verge-service 和clash-verge，不知道咋启动。ssh连的服务器
