### ISSUE TITLE
[Feature] 支持流量自动更新

### ISSUE THREAD

**Issue by Davidasx** [clash-verge-rev/clash-verge-rev#1697]
### 功能描述 / Feature description

对于流量限额的订阅，建议增加流量自动更新功能，每隔一段时间（几分钟）自动爬取一次流量，让用户每次查看时都可以看到较新的流量，而不是必须手动刷新。
另外，可以在流量即将耗尽时警告用户。

### 使用场景 / Use case

有流量限额的订阅。

**Comment by Davidasx** [comment]
对于一些有流量限额而且自动导入的订阅，是会显示流量使用情况的。
![image](https://github.com/user-attachments/assets/a59a4c78-eb3f-42f6-a582-0c82c2214f5c)

**Comment by Davidasx** [comment]
我指的自动导入是，在订阅网站上按一个按钮后扫一个二维码，自动将内容传给Clash的那种订阅

**Comment by HozumiMoa** [comment]
把更新间隔调短一点就行了吧，又不是没这个功能

**Comment by Davidasx** [comment]
好的


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月10日 10:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [clash-verge-rev/clash-verge-rev] [Feature] 支持流量自动更新 (Issue #1697) |

把更新间隔调短一点就行了吧，又不是没这个功能
