### ISSUE TITLE
[BUG]延迟测试无效

### ISSUE THREAD

**Issue by eeviriyi** [clash-verge-rev/clash-verge-rev#170]
### Describe the bug

延迟无法测试

### To Reproduce

点击延迟测试（如 google.com）时所有节点都显示「Error」，但是网页可以正常访问。

### Platform

Windows

### System Version

Windows11 23H2

### Software Version

1.4.5

**Comment by wonfen** [comment]
截图看看你怎么填写的延迟测试地址？感觉是写错了。

**Comment by MystiPanda** [comment]
需要把协议头也带上，http://google.com 或者 https://google.com
