### ISSUE TITLE
[BUG] 在MacOS上，“VPN与过滤条件“中，无法看到Clash程序

### ISSUE THREAD

**Issue by Accademia** [clash-verge-rev/clash-verge-rev#1700]
### 问题描述 / Describe the bug

 在MacOS上，“VPN与过滤条件“中，无法看到Clash程序。我的另一个VPN程序Stash就能看到

如图
![image](https://github.com/user-attachments/assets/bfc2aefa-c783-473d-af8c-d34a7c080298)

### 复现步骤 / To Reproduce

正常安装后，就可复现，无需特别操作

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

最新版

### 日志 / Log

无需

**Comment by wonfen** [comment]
因为2个软件的实现原理不一样。stash等是调用系统自身的vpn接口实现的代理。
可以自行多了解一下。
