### ISSUE TITLE
[BUG] Tun实现方式有问题

### ISSUE THREAD

**Issue by BlueDolphin9527** [clash-verge-rev/clash-verge-rev#1701]
### 问题描述 / Describe the bug

1.7.7版本win10 19044.3803，Tun模式打开Kindle提示网络无法连接，系统代理下就正常。尝试换了机场自带的配置文件和喜多 郁代的配置文件（他在他的电脑上使用相同的配置打开Kindle就没问题）都一样无法连接。我们折腾了很久，猜测应该是Tun实现的方式有问题。因为可能在别人的PC上无法复现，可以随时联系我远程。我的TG，https://t.me/bluedolphin9527

### 复现步骤 / To Reproduce

只要一打开Kindle，点击同步按钮就会出现。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

19044.3803

### 日志 / Log

[2024-09-10-1953.log](https://github.com/user-attachments/files/16944520/2024-09-10-1953.log)

**Comment by wonfen** [comment]
有没有可能Kindle的这个软件必须绑定物理网口？打印下路由表看看。

**Comment by BlueDolphin9527** [comment]
![image](https://github.com/user-attachments/assets/0de56879-ff17-4081-a0ed-02574555b1d8)
你看下

**Comment by dylanhz** [comment]
我也遇到了类似的问题。TUN 模式翻不出去，系统代理就没问题。
Win 10 1.7.7 版本和 Win 11 1.6.x 版本都存在这个问题，换 CFW 的 TUN 也没问题。
需要更多信息可以联系我提供。
