### ISSUE TITLE
[BUG] 托盘图标无法更改 2.0.0

### ISSUE THREAD

**Issue by GreenDreenAct** [clash-verge-rev/clash-verge-rev#1705]
### 问题描述 / Describe the bug

更改托盘图标无反应

### 复现步骤 / To Reproduce

https://github.com/user-attachments/assets/ccf2dd9f-3077-4c58-a1aa-a49b4be8c56b

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11专业版 23h2

### 日志 / Log

[2024-09-11-1638.log](https://github.com/user-attachments/files/16960671/2024-09-11-1638.log)

**Comment by jayzqj** [comment]
不禁图标无法更改，2.0.0安装后，一打开直接是全屏的。手动调小后，关闭了，下次重新打开又是全屏了
