### ISSUE TITLE
发现声称是 Clash-verge-rev 官网高仿引流网站

### ISSUE THREAD

**Issue by goddaneel** [clash-verge-rev/clash-verge-rev#1707]
如题：https://clashvergerev.com/

**Comment by cornradio** [comment]
![image](https://github.com/user-attachments/assets/d2a534ef-f005-45c6-ab29-cfae849490af)
我觉得还行 
1. 它网站做的不丑
2. 下载链接指向 官方github

**Comment by goddaneel** [comment]
> ![image](https://github.com/user-attachments/assets/d2a534ef-f005-45c6-ab29-cfae849490af)
> 我觉得还行 
> 1. 它网站做的不丑
> 2. 下载链接指向 官方github 

仅仅这两点并不足以让他允许它自称官网，几个很重要的问题：

1. 并未得到开发者授权，而自称“官方”（该字样已删除（clash-verge-rev无此字样，但其他几个有）
2. 插入大量广告与机场引流
3. 下载界面不止指向 GitHub，还指向了一个私有镜像：https://dl.p6p.net/clash-verge/

**Comment by wonfen** [comment]
这种仿冒网站就别去他们的网站下载了。不知道是否夹带的私货。
