### ISSUE TITLE
[Feature] 备份与恢复 WebDAV

### ISSUE THREAD

**Issue by pure-white-ice-cream** [clash-verge-rev/clash-verge-rev#1708]
### 功能描述 / Feature description

类似于FlClash的多端远程同步（备份恢复）
![QQ20240912-144202](https://github.com/user-attachments/assets/8e793574-ff15-44c4-b24a-e34fc52bafa0)

### 使用场景 / Use case

可以随时备份，在其他设备上快速恢复熟悉的设置和订阅

**Comment by wonfen** [comment]
已完成
