### ISSUE TITLE
[BUG] clash verge 不遵守geoip规则

### ISSUE THREAD

**Issue by Youjin1985** [clash-verge-rev/clash-verge-rev#1709]
### 问题描述 / Describe the bug

虽然我有 cn GeoIP DIRECT，所有链接是通过代理的，不敢用微信

### 复现步骤 / To Reproduce

开系统代理，访问 speedtest.cn

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

sonoma 14.6.1

### 日志 / Log

09-12 22:40:16INFO
Start initial configuration in progress
09-12 22:40:16WARNING
To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+
09-12 22:40:16WARNING
To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+
09-12 22:40:16WARNING
To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+
09-12 22:40:16WARNING
To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+
09-12 22:40:16INFO
Geodata Loader mode: memconservative
09-12 22:40:16INFO
Geosite Matcher implementation: succinct
09-12 22:40:16INFO
Initial configuration complete, total time: 2ms
09-12 22:40:16INFO
RESTful API listening at: 127.0.0.1:9097
09-12 22:40:16INFO
Sniffer is closed
09-12 22:40:16INFO
Mixed(http+socks) proxy listening at: 127.0.0.1:7897
09-12 22:40:16INFO
Start initial Compatible provider Servers
09-12 22:40:16INFO
Start initial Compatible provider default

**Comment by Youjin1985** [comment]
DOMAIN 规则也无效……
同样的订阅在windows/V2rayN 没有这个问题，请解决

**Comment by wonfen** [comment]
请检查你的订阅配置文件，规则都是由内核处理的。是否遵守要看配置文件里是如何写的。
