### ISSUE TITLE
[BUG]error sending request for url (http://127.0.0.1:9091/configs): error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)

### ISSUE THREAD

**Issue by DogMing** [clash-verge-rev/clash-verge-rev#171]
### Describe the bug

系统：window11 23H2
版本：1.4.5
问题：import clash 配置文件 select 启动的时候报错：
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/28433915/c4ec1a4a-e5c8-4a5e-8f7e-9dcf18494d58)
日志中有一个 error: error sending request for url
(http://127.0.0.1:9091/configs): error
trying to connect: tcp connect error: No
connection could be made because the
target machine actively refused it. (os
error 10061)

导致无法启动

我之前安装好了 1.3.8 版本，没有卸载，直接安装新的之后出现的问题，然后我卸载了 1.3.8 和 1.4.5 重新安装 1.4.5 也出现同样的问题，无法启动

### To Reproduce

再1.3.8版本启动的过程中，安装1.4.5 ，然后卸载1.3.8，重新在1.4.5中import clash profile. 选择import 的profile, 报错

### Platform

Windows

### System Version

23H2

### Software Version

1.4.5

### Log

error sending request for url
(http://127.0.0.1:9091/configs): error
trying to connect: tcp connect error: No
connection could be made because the
target machine actively refused it. (os
error 10061)

**Comment by DogMing** [comment]
我更新以下，今天早上我打开我电脑后又可以正常启动了，一切看上去什么都没发生的样子。很迷。 重启大法好

**Comment by wonfen** [comment]
这类奇怪的问题就重启吧。
