### ISSUE TITLE
[BUG] macOS安装服务模式时报错

### ISSUE THREAD

**Issue by szyellow** [clash-verge-rev/clash-verge-rev#1710]
### 问题描述 / Describe the bug

服务模式点击安装时，报错，详细请看图片

### 复现步骤 / To Reproduce

服务模式点击安装时，报错，详细请看图片

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.6.1

### 日志 / Log

![Uploading mmexport1726187881585.png…]()

**Comment by wonfen** [comment]
图片和日志呢？
