### ISSUE TITLE
[BUG] ./clash-verge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./clash-verge)

### ISSUE THREAD

**Issue by zl1344** [clash-verge-rev/clash-verge-rev#1711]
### 问题描述 / Describe the bug

ubuntu18.04安装后无法启动
./clash-verge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./clash-verge)

### 复现步骤 / To Reproduce

clash-verge

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

ubuntu18.04

### 日志 / Log

./clash-verge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./clash-verge)

**Comment by czp0204** [comment]
same. 蹲一下

**Comment by Bryan2333** [comment]
应该是系统glibc版本过低导致的，毕竟ubuntu18.04比较旧了

**Comment by zl1344** [comment]
除了安装高版本glibc和升级ubuntu之外，还有其他方法吗？

**Comment by zl1344** [comment]
除了安装高版本glibc和升级ubuntu之外，还有其他方法吗？ @Bryan2333

**Comment by Bryan2333** [comment]
> 除了安装高版本glibc和升级ubuntu之外，还有其他方法吗？ @Bryan2333

也许你可以尝试自己编译？我不知道这样行不行

**Comment by zl1344** [comment]
> > 除了安装高版本glibc和升级ubuntu之外，还有其他方法吗？ @Bryan2333
> 
> 也许你可以尝试自己编译？我不知道这样行不行

我试一下

**Comment by zl1344** [comment]
> > 除了安装高版本glibc和升级ubuntu之外，还有其他方法吗？ @Bryan2333
> 
> 也许你可以尝试自己编译？我不知道这样行不行

怎么编译啊，好像不是用C++写的

**Comment by bitGrayFalcon** [comment]
最好不要动系统自带的glibc，就算你使用20的源安装了高版本的glibc，问题可能会得到解决，但是高版本的软件源可能会导致系统崩溃

**Comment by Smart-SangGe** [comment]
可以嘗試下載一個2.28的libc，然後通過LD_PRELOAD=/path/to/your/libc.so ./clash-verge來手動指定。但是不保證程序会不会依赖其他的什么。

**Comment by czp0204** [comment]
安装了2.28的Glbic 有时候能用有时候不行，系统暂时没出现什么问题

**Comment by zl1344** [comment]
> 可以嘗試下載一個2.28的libc，然後通過LD_PRELOAD=/path/to/your/libc.so ./clash-verge來手動指定。但是不保證程序会不会依赖其他的什么。

谢谢，我会试一下的

**Comment by zl1344** [comment]
> 安装了2.28的Glbic 有时候能用有时候不行，系统暂时没出现什么问题

大佬，怎么安装的，求教程
