### ISSUE TITLE
[BUG] 无法与docker服务同时运行

### ISSUE THREAD

**Issue by Yerosius** [clash-verge-rev/clash-verge-rev#1712]
### 问题描述 / Describe the bug

如题，在使用Clash-verge-rev时，无法与已经运行的docker容器运行，否则会无法访问容器。

### 复现步骤 / To Reproduce

如题，在使用Clash-verge-rev时，无法与已经运行的docker容器运行，否则会无法访问容器。

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ububtu24.04LTS

### 日志 / Log

.

**Comment by wonfen** [comment]
检查你的配置文件和网络。以及tun模式。
