### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by zjydingding** [clash-verge-rev/clash-verge-rev#1713]
### 功能描述 / Feature description

macos上左上角和右上角都会出现clash verge的图标，正常应该是只出现在右上角的，但是左上角apple标志处也会出现一个。
如图，圈出来的两个图标。macos版本是14.3
![5ef8ae038fb022b521464a2c80bb6d0e](https://github.com/user-attachments/assets/3de72f2a-6709-4347-828c-ed6dfb0c92a8)

### 使用场景 / Use case

打开软件就会出现

**Comment by wonfen** [comment]
看文档： https://www.clashverge.dev/faq/macos.html#macos_1
