### ISSUE TITLE
[BUG] Windows On Arm can't install "Servcie mode"

### ISSUE THREAD

**Issue by sherlongqu** [clash-verge-rev/clash-verge-rev#1714]
### 问题描述 / Describe the bug

![Screenshot 2024-09-13 214948](https://github.com/user-attachments/assets/bb02642e-afc2-421f-9604-b8bdba2e3a43)

### 复现步骤 / To Reproduce

When i connect a proxy server,and i want to install the service mode, i get a error:"VCRUNTIME140.dll was not found"

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 Pro 23H2

### 日志 / Log

failed to install service with status
-1073741515

**Comment by wonfen** [comment]
安装vcruntime啊。
