### ISSUE TITLE
[BUG] 扩展配置叫Merge功能却是覆盖

### ISSUE THREAD

**Issue by Royal520** [clash-verge-rev/clash-verge-rev#1715]
### 问题描述 / Describe the bug

1.添加全局扩展配置或单个订阅的扩展配置
2.会覆盖调原来的规则

### 复现步骤 / To Reproduce

#在扩展配置中添加
rule-providers:
  Royal_520:
    type: http
    behavior: domain
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/Royal520/clash-rules-lite/proxy-rules.yaml
    path: ./Rules/Royal520_proxy

rules:
  - RULE-SET,Royal_520,GitHub
![Screenshot_20240914_000924](https://github.com/user-attachments/assets/b0cc778e-a495-4f1f-b9c0-3dbe15ff5620)

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Linux Mint 21.1

### 日志 / Log

# Profile Enhancement Merge Template for Clash Verge
rule-providers:
  Royal_520:
    type: http
    behavior: domain
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/Royal520/clash-rules-lite/proxy-rules.yaml
    path: ./Rules/Royal520_proxy

rules:
  - RULE-SET,Royal_520,GitHub

**Comment by wonfen** [comment]
什么叫覆盖掉原来的规则？原来的什么规则？

你期望的机制是什么样的？

**Comment by Royal520** [comment]
原来配置：
![Screenshot_20240918_204957](https://github.com/user-attachments/assets/db568679-0495-466c-9629-a1b730c89b2a)
原来的规则：
![Screenshot_20240918_205517](https://github.com/user-attachments/assets/c77ec0e5-a194-42b4-8411-4b7726162764)
全局merge配置后：
![Screenshot_20240918_205615](https://github.com/user-attachments/assets/daceca39-aef7-4605-8841-2a1bbd5b02aa)
![Screenshot_20240918_205615](https://github.com/user-attachments/assets/dda911a4-9a5c-47be-b3cf-bfd5bd615f9f)
可见原来的路有规则被全局的merge规则覆盖掉了
期望能够把全局的加入到已有的后面不会，而不是覆盖调如加一个rule-providers: 或加一个  - RULE-SET,Royal_520,GitHub

**Comment by jn-jia** [comment]
您好！我也有类似的疑问：
1. 如果直接在订阅链接的配置文件中添加rule-providers和相应的rules，是否会被链接配置文件的自动更新所覆盖掉？
2. 如果想要在扩展配置（Merge配置）中添加rule-providers和相应的rules，应该怎么添加，是否支持？
如果有了解的话，麻烦帮忙告诉我一下，十分感谢！

**Comment by Diane-Best** [comment]
唔  倒是挺希望能直接覆盖原来的规则的！

**Comment by euvre** [comment]
> 唔 倒是挺希望能直接覆盖原来的规则的！

那为什么不直接写在原来的规则里？

**Comment by cdwmhcc** [comment]
是的，存在这个问题。我的订阅源中有自带的规则，全局扩展配置当前标记的是 Merge，我以为是合并的。然后在全局扩展配置中添加一些定制的规则会覆盖订阅源中自带的规则。希望可以修正。

**Comment by PctAIGM** [comment]
1.7 之后的久这样，看看文档
现在的做法：
 每个订阅里面配置一遍
或者
 写js脚本

**Comment by cdwmhcc** [comment]
> 1.7 之后的久这样，看看文档

认真看过文档的，不看文档就来提交问题是对开发者的不尊重，只是我应该是没有能很好的理解。文档中这样描述的：
> v1.7.x 版本的 Merge配置 改名为 扩展配置 ，且prepend/append功能移动至订阅右键菜单中的可视化编辑器中实现（例如：prepend-rules移动至订阅右键菜单的 编辑规则 中的 prepend）。扩展配置仅用于配置项覆写/合并。
> 根据文件类型，扩展可分为 配置 和 脚本 。配置 使用 yaml 对配置进行覆写/合并， 脚本 使用 javascript 对配置进行更加灵活的调整。

这里面还是有写合并，所以才会有这个疑问。

![image](https://github.com/user-attachments/assets/48255c72-2b91-4dc5-b1f4-10c1395eb61e)
包括这个扩展也是覆盖，这总归是理解上的歧义。如果是覆写就不会有理解上的问题了。

不过你说的用 js 脚本确实没有问题，可以读取订阅的文件，然后合并，麻烦一些。

**Comment by SuperBug-RhysLiu** [comment]
同,想找个全局能追加的地方..
