### ISSUE TITLE
[BUG] 使用proxy-providers Clash所有节点 手动测速均Error

### ISSUE THREAD

**Issue by Forgo7ten** [clash-verge-rev/clash-verge-rev#1717]
### 问题描述 / Describe the bug

我使用proxy-providers来配置自己的规则：[配置文件模板](https://gist.github.com/Forgo7ten/3a86036a013b2098b78ecb1491e26f4b)
在windows与macos中的ClashVerge1.7.7中，手动测速均出现全error，但实际上节点是可以使用的，自动测速正常，也可以正常上网，只是手动测速会error。
Clash启动时，自动测速运行正常。但一旦手动测速之后，测速一直是error、只能重启。

Clash重新启动时（还没有速度）：
![image](https://github.com/user-attachments/assets/6fe41459-cf7b-459b-b5f2-6da906ad8d65)
等待几秒后，会出现测速：
![image](https://github.com/user-attachments/assets/b970aa6d-16d9-4aee-af9c-abc9799735cb)
手动测速后出现Error
![image](https://github.com/user-attachments/assets/659f8081-4029-42f8-9f84-83d76b5b1423)

其他尝试：
1. 关闭clash内置dns
2. 切换proxy-providers的health-check url为apple.com

均手动测速失败

正式内核v1.18.7 Mihomo与预览版alpha-c4660e1 Mihomo均已尝试，均会出现该问题。

直接使用机场的订阅地址，不使用用proxy-providers，可以正常手动更新。

**同样的规则文件**，手机版Android使用的Clash Meta for Android 2.11.0.Meta Alpha-e33d4a4-240912没有问题，可以正常手动测速。所以我怀疑是ClashVerge的问题？麻烦看一下 感谢~

### 复现步骤 / To Reproduce

1. 使用[配置文件模板](https://gist.github.com/Forgo7ten/3a86036a013b2098b78ecb1491e26f4b)，填入自己代理的proxy-providers
2. 打开ClashVerge，选择该配置文件
4. 手动测速，节点全部出现error

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

版本  Windows 11 专业版 22H2 22621.2428

### 日志 / Log

没有发现测速相关的日志

**Comment by zzgpku** [comment]
差不多类似，同样的机场配置，原来用的免安装版，节点全部超时，然后换成安装版后就可以用了。现在安装版又全部超时了，但同样配置同一文件同一局域网在安卓端clash可以用。已清除DNS缓存也不行。
