### ISSUE TITLE
有的vps连接一段时间以后会中断

### ISSUE THREAD

**Issue by zql666999** [clash-verge-rev/clash-verge-rev#1718]
### 问题描述 / Describe the bug

有的vps连接一段时间以后会中断，必须去订阅哪里再次点击使用或者重启电脑才能重新连接。

### 复现步骤 / To Reproduce

有的vps连接一段时间以后会中断，必须去订阅哪里再次点击使用或者重启电脑才能重新连接。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

有的vps连接一段时间以后会中断，必须去订阅哪里再次点击使用或者重启电脑才能重新连接。

**Comment by wonfen** [comment]
信息不足，无法判断。

**Comment by zql666999** [comment]
> 信息不足，无法判断。
连接一段时间以后，设置里面clash 内核哪里会变成-，相当于内核不见，需要重新启动内核就又可以连接，这是什么问题呢？

**Comment by wonfen** [comment]
看描述是内核挂了，看日志有没有报错，反馈到 https://github.com/MetaCubeX/mihomo/issues

**Comment by zql666999** [comment]
> 看描述是内核挂了，看日志有没有报错，反馈到https://github.com/MetaCubeX/mihomo/issues

已经提交日志信息，看日志有很多报错。

**Comment by zql666999** [comment]
1 订阅哪里时间间隔使用默认的0时，内核不会崩溃，代理哪里连接会自动断开，需要刷新订阅哪里使用或者重新启动，才能恢复正常连接。
2 订阅哪里时间间隔使用默认的1时，内核会崩溃，代理哪里什么也没有，设置里面内核bian-，需要重新启动内核或者重新启动，才能恢复正常连接。
