### ISSUE TITLE
[BUG]规则内自定义的 hosts 没有生效

### ISSUE THREAD

**Issue by mashirozx** [clash-verge-rev/clash-verge-rev#172]
### Describe the bug

之前用的 v1.3.8 是默认通过规则文件内配置的 hosts 解析域名的，但是更新到 v1.4.5 以后，自定义的 hosts 无效了，需要手动在 /etc/hosts 下添加

### To Reproduce

```
hosts:
    kubernetes.docker.internal: 127.0.0.1
    raw.githubusercontent.com: 185.199.110.133
```
<img width="1624" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/16148054/8eef8296-ffe6-4bf7-9ed2-21bee41072e8">
<img width="376" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/16148054/8f92edf0-c7d9-498e-a042-e0770ae56d21">

### Platform

MacOS

### System Version

14.1.2

### Software Version

1.4.5

**Comment by wonfen** [comment]
这部分是meta内核处理的，你尝试下直接使用内核运行配置文件看看能生效吗？

**Comment by zou2699** [comment]
确实不生效

**Comment by wonfen** [comment]
那就是内核问题了，试试最新版的1.18.1内核可以用了没？

**Comment by zou2699** [comment]
> 那就是内核问题了，试试最新版的 1.18.1 内核可以用了没？

1.18.1 和最新的 alpha 版本在 tun 模式依旧不生效

**Comment by mashirozx** [comment]
我的生效了
<img width="630" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/16148054/adf692d3-85db-488d-b47c-dff2f8e07e4d">
<img width="615" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/16148054/3b33b19c-7eaf-4ff6-bc6a-4d542819abdb">

**Comment by zou2699** [comment]
tun 模式下，chrome会走配置的hosts，但是在terminal下使用 curl等命令还是不行。

**Comment by zou2699** [comment]
> > tun 模式下，chrome会走配置的hosts，但是在terminal下使用 curl等命令还是不行。
> 
> 是什么系统

macos

**Comment by mashirozx** [comment]
> > > tun 模式下，chrome会走配置的hosts，但是在terminal下使用 curl等命令还是不行。
> > 
> > 
> > 是什么系统
> 
> macos

试一下点点这个授权按钮
<img width="912" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/16148054/10b129fa-ec33-495d-9d4d-c08cb972ee8d">

**Comment by zou2699** [comment]
> > > > tun 模式下，chrome会走配置的hosts，但是在terminal下使用 curl等命令还是不行。
> > > 
> > > 
> > > 是什么系统
> > 
> > 
> > macos
> 
> 试一下点点这个授权按钮 <img alt="image" width="912" src="https://private-user-images.githubusercontent.com/16148054/307204515-10b129fa-ec33-495d-9d4d-c08cb972ee8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTQxMjgsIm5iZiI6MTcwODY1MzgyOCwicGF0aCI6Ii8xNjE0ODA1NC8zMDcyMDQ1MTUtMTBiMTI5ZmEtZWMzMy00OTVkLTlkNGQtYzA4Y2I5NzJlZThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAyMDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYjkxOTc3NDA0YWYxNGJkYWY4ZmRjNmFjNzIwYmU0ZWNkYmYzOTlhMmFlYjE1ODNiZjdmYTM5ZjI0OWY0ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ZKmGFworC_1xo1FIXS2kJoH86DXV7dKCT2hCX2s__s">

已授权，网络代理都是正常的，只有hosts在tun模式下不生效，很奇怪。

**Comment by mashirozx** [comment]
> > > > > tun 模式下，chrome会走配置的hosts，但是在terminal下使用 curl等命令还是不行。
> > > > 
> > > > 
> > > > 是什么系统
> > > 
> > > 
> > > macos
> > 
> > 
> > 试一下点点这个授权按钮 <img alt="image" width="912" src="https://private-user-images.githubusercontent.com/16148054/307204515-10b129fa-ec33-495d-9d4d-c08cb972ee8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTQxMjgsIm5iZiI6MTcwODY1MzgyOCwicGF0aCI6Ii8xNjE0ODA1NC8zMDcyMDQ1MTUtMTBiMTI5ZmEtZWMzMy00OTVkLTlkNGQtYzA4Y2I5NzJlZThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAyMDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYjkxOTc3NDA0YWYxNGJkYWY4ZmRjNmFjNzIwYmU0ZWNkYmYzOTlhMmFlYjE1ODNiZjdmYTM5ZjI0OWY0ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ZKmGFworC_1xo1FIXS2kJoH86DXV7dKCT2hCX2s__s">
> 
> 已授权，网络代理都是正常的，只有hosts在tun模式下不生效，很奇怪。

刚刚试了我这边是能生效的，curl 和 git 下 clash 内配的 hosts 都能生效

**Comment by mashirozx** [comment]
试一下你 curl 能请求 Google 吗

**Comment by zou2699** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/20203592/343cc2e3-6d61-43b0-a693-636396229648)

dig  查询都是对的， curl就是不行，dns cache？

**Comment by mashirozx** [comment]
不太懂了 23333

**Comment by zou2699** [comment]
看上去像是dns的配置的问题，目前networksetup -getdnsservers  Ethernet 返回空，clash x pro会返回虚拟的dns地址

**Comment by mashirozx** [comment]
这里不少 clash x 的仓库吧…
