### ISSUE TITLE
[BUG] windows系统代理无法通过热键切换

### ISSUE THREAD

**Issue by deuteros-gex** [clash-verge-rev/clash-verge-rev#1726]
### 问题描述 / Describe the bug

Windows11 24H2 26100.1742
程序版本 Clash.Verge_2.0.0_arm64-setup.nsis.zip

Windows10 22H2 19045.4780
程序版本 Clash.Verge_2.0.0_x64-setup.nsis.zip

两个版本组合都做过测试

### 复现步骤 / To Reproduce

1、在 设置 - Verge设置 - 热键设置 中分别为Tun模式、系统代理各自设置快捷键ctrl+shift+p和ctrl+alt+p
2、使用ctrl+shift+p，可以成功打开或关闭tun模式
3、但使用ctrl+alt+p，系统代理的状态无非被正常切换，具体表现为：明明只按了一次快捷键，但系统代理状态却快速地连续切换了两次

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26100.1742

### 日志 / Log

[VERGE日志.txt](https://github.com/user-attachments/files/17011726/VERGE.txt)
行数太多，尝试着截取了从我开始操作后半分钟内的日志。

**Comment by wonfen** [comment]
最新版已经修复了这个问题，请下载测试。
