### ISSUE TITLE
[BUG] uwp应用在开启tun模式后无法联网

### ISSUE THREAD

**Issue by lly778** [clash-verge-rev/clash-verge-rev#1729]
### 问题描述 / Describe the bug

开启tun模式后，其他应用都能正常连接，但是uwp应用无法联网。
![image](https://github.com/user-attachments/assets/4856911a-3e5b-4eb7-9551-e9b94039c809)

而正常开启系统代理后，uwp应用可以联网。
![image](https://github.com/user-attachments/assets/ec436bbe-fd56-4f4b-bfc3-515f0e2da655)

### 复现步骤 / To Reproduce

开启tun模式后，不开系统代理，打开uwp应用。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 家庭中文版 23H2 22631.4169

### 日志 / Log

暂无

**Comment by lly778** [comment]
感觉是tun模式，uwp应用的流量没被接管，日志里也没有路由的记录

**Comment by HozumiMoa** [comment]
Clash 设置里不是有个 UWP 工具吗

**Comment by lly778** [comment]
> Clash 设置里不是有个 UWP 工具吗

tun模式不需要弄这个的，系统代理才要
