### ISSUE TITLE
[Feature]控制进程是否走代理

### ISSUE THREAD

**Issue by sf467** [clash-verge-rev/clash-verge-rev#173]
### Is your feature request related to a problem? Please describe.

解决windows端tun模式不能像安卓端vpn服务那样控制应用是否走代理

### Describe the solution you'd like

根据mihomo文档，可以看到有关进程规则的字段解释
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/121373973/68294cbd-7e3f-4416-8b7f-2c677477f204)
设想制作一个界面，通过扫描任务管理器，或者别的方法，或者当前运行中的所有进程的名字。
然后在进程名字后面做一个开关，或者一个用来填写策略组的空白，这个页面对应着一段规则配置，然后再实时将这段配置合并到主配置文件中，或者像merge类型的配置文件或者cfw的mixin那样，在内存中与主配置混合然后执行。

### Describe alternatives you've considered

额外做这么一个转换器，将ui界面转换成一段rules配置

**Comment by MystiPanda** [comment]
这个你直接在规则里面写就好了呀

**Comment by crossgg** [comment]
谢谢，是可以直接写在规则里面实现。
但想问下能不能添加一个本地规则来实现呢？
因为如果是在线订阅的，订阅更新了 规则就被覆盖掉没了。

**Comment by sf467** [comment]
> 谢谢，是可以直接写在规则里面实现。 但想问下能不能添加一个本地规则来实现呢？ 因为如果是在线订阅的，订阅更新了 规则就被覆盖掉没了。

写merge里啊
