### ISSUE TITLE
[BUG] 软件老是卡住

### ISSUE THREAD

**Issue by CMEPCBHG** [clash-verge-rev/clash-verge-rev#1736]
### 问题描述 / Describe the bug

软件在用了一段时间后，直接卡住没反应，无法呼出主界面、点击任务栏按钮没反应。

### 复现步骤 / To Reproduce

只要使用时长足够，就会出现。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows10 19045.4412

### 日志 / Log

软件卡死，只能从任务管理器强制关闭，关闭后无卡死前的日志。

**Comment by miguellords** [comment]
maybe this will help
https://bit.ly/3XQLHlH

you may need to install the c compiler

**Comment by CMEPCBHG** [comment]
> 什么版本？

1.7.7

**Comment by CMEPCBHG** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1110#issuecomment-2171031775

**Comment by CMEPCBHG** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1110
