### ISSUE TITLE
[BUG] 关闭主界面，鼠标悬浮在托盘后会异常退出

### ISSUE THREAD

**Issue by lkpopo** [clash-verge-rev/clash-verge-rev#1737]
### 问题描述 / Describe the bug

软件异常退出

### 复现步骤 / To Reproduce

关闭主界面，将鼠标悬浮在托盘处停留，软件会异常退出
![image](https://github.com/user-attachments/assets/dcd0a986-e342-486f-878f-99f6ee2b3a48)
![image](https://github.com/user-attachments/assets/cb136649-0462-4c8a-9f04-92f1f5005cb9)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

![image](https://github.com/user-attachments/assets/de6d7f2d-7132-4114-a275-ed1388a92ec6)

**Comment by lkpopo** [comment]
> 的

最新release x86 64都有这个情况，9.19下载得

**Comment by wonfen** [comment]
> > 的
> 
> 最新release x86 64都有这个情况，9.19下载得

最新的release是1.7.7还是2.0.0 啊？

**Comment by lkpopo** [comment]
> > > 的
> > 
> > 
> > 最新release x86 64都有这个情况，9.19下载得
> 
> 最新的release是1.7.7还是2.0.0 啊？
> 
> 尝试重新卸载安装一下最新版的webview2试试吧。

2.0.0的版本

**Comment by Kiritocyz** [comment]
我发现好像是测速未完成，直接关闭界面，后台会掉

**Comment by LevineWoo** [comment]
我也是最新的版本，20号下载的，也是一样托盘无了。

**Comment by lkpopo** [comment]
我将单击托盘时间禁用就好了，可能是单击显示主界面跟显示冲突了，不然就是主界面关的时候重复关闭 异常了

**Comment by LevineWoo** [comment]
> 我将单击托盘时间禁用就好了，可能是单击显示主界面跟显示冲突了，不然就是主界面关的时候重复关闭 异常了

托盘时间这个在哪里禁用啊？

**Comment by LevineWoo** [comment]
> 我将单击托盘时间禁用就好了，可能是单击显示主界面跟显示冲突了，不然就是主界面关的时候重复关闭 异常了

我试了禁用托盘事件，还是复现了，不仅这样，在主界面按ESC 100%程序退了。

**Comment by lkpopo** [comment]
> > 我将单击托盘时间禁用就好了，可能是单击显示主界面跟显示冲突了，不然就是主界面关的时候重复关闭 异常了
> 
> 我试了禁用托盘事件，还是复现了，不仅这样，在主界面按ESC 100%程序退了。

是的，我用了一段时间还是异常退出了，等修复吧

**Comment by Kiritocyz** [comment]
> > > 我将单击托盘时间禁用就好了，可能是单击显示主界面跟显示冲突了，不然就是主界面关的时候重复关闭 异常了
> > 
> > 
> > 我试了禁用托盘事件，还是复现了，不仅这样，在主界面按ESC 100%程序退了。
> 
> 是的，我用了一段时间还是异常退出了，等修复吧

管理员说等上游修复，可能这是tauri的问题

**Comment by wonfen** [comment]
> > 我将单击托盘时间禁用就好了，可能是单击显示主界面跟显示冲突了，不然就是主界面关的时候重复关闭 异常了
> 
> 我试了禁用托盘事件，还是复现了，不仅这样，在主界面按ESC 100%程序退了。

按住esc似乎是触发了webview的退出程序逻辑（等同与按ctrl+w）；并不算bug。

而关闭窗口导致的程序崩溃是上游tauri问题，等上游修复：https://github.com/tauri-apps/tauri/issues/10546
