### ISSUE TITLE
有用google earth pro的吗，是我配置不对还是什么原因？

### ISSUE THREAD

**Issue by thinker3** [clash-verge-rev/clash-verge-rev#174]
操作系统是macOS，同样的配置文件，用翻墙路由器可以正常使用google earth pro，但用clash-verge就不能。

**Comment by thinker3** [comment]
tun模式没有授权造成的，而且还会一直Refresh clash config.

**Comment by wonfen** [comment]
授权一下试试看？

**Comment by wonfen** [comment]
无更多反馈，关闭。
