### ISSUE TITLE
[BUG] failed to put configs with status "426"

### ISSUE THREAD

**Issue by quangsuengsuoe** [clash-verge-rev/clash-verge-rev#1740]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/7e4e8c76-58b3-45a2-a296-fd22656afe06)
如图，我使用的是1.7.7的x64版本，在点击使用代理规则时出现此错误。
【我做过哪些尝试】
1.卸载了重装，还是出现此问题
2.删除订阅，也会出现此问题，订阅删不掉
3.卸载重装，不拉取订阅，直接安装服务模式并开启Tun，也报此错误
4.安装老版本1.3.8可以正常使用
【可能的问题】
我的系统安装过多个Clash版本，但我已经在控制面板中卸载

### 复现步骤 / To Reproduce

1.安装1.7.7 x64 win版本
2.拉取订阅脚本(可以找我要脚本链接帮助复现)
3.右键点击该订阅，在菜单点击使用
4.报“426”

联系邮箱：dearchar@qq.com

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

版本	Windows 10 专业版 版本号	22H2 安装日期	‎2024/‎8/‎23 操作系统内部版本	19045.4894 体验	Windows Feature Experience Pack 1000.19060.1000.0

### 日志 / Log

Clash 的Log中有一条Error，希望有帮助

09-20 10:50:10error
External controller listen error: listen tcp 127.0.0.1:9097: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by wonfen** [comment]
端口冲突了，检查是否安装了多次，有多个进程/实例。
尝试在设置中，clash设置，外部控制，修改端口。

**Comment by Jordan-Haidee** [comment]
```powershell
failed to put configs with status '400'
```
遇到了同样的问题，修改外部端口后仍然不正常

**Comment by Jordan-Haidee** [comment]
测试了一下，使用`全局扩展脚本`后再切换订阅，就会出现这个错误。

**Comment by Tychristine** [comment]
@Jordan-Haidee 因为脚本写错了

**Comment by Jordan-Haidee** [comment]
> @Jordan-Haidee 因为脚本写错了
![image](https://github.com/user-attachments/assets/48ecc62b-5d50-41aa-ab68-89483b17b2e2)
我查看了脚本控制台输出，暂时没发现错误，输出是正常的。

**Comment by Jordan-Haidee** [comment]
> > @Jordan-Haidee 因为脚本写错了

![image](https://private-user-images.githubusercontent.com/85778126/397923396-48ecc62b-5d50-41aa-ab68-89483b17b2e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODA0MjQsIm5iZiI6MTczNDc4MDEyNCwicGF0aCI6Ii84NTc3ODEyNi8zOTc5MjMzOTYtNDhlY2M2MmItNWQ1MC00MWFhLWFiNjgtODk0ODNiMTdiMmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDExMjIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMTcyYTg5YWY5MTMxNTNmZDgzMjM3ODA4MGJmOTk1OGUwZjQ4ZTRhNGMwOTcxMGViYjljNWZkODgyYjI0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nStORjNNc43LNe0Hq1T9dvU1ovcKOmJbHfqFxtAB-bc)
我查看了脚本控制台输出，暂时没发现错误，输出是正常的。

**Comment by huankong233** [comment]
> ```powershell
> failed to put configs with status '400'
> ```
> 
> 遇到了同样的问题，修改外部端口后仍然不正常

我也遇到了相同的错误，但是只有那一个订阅会提示400
