### ISSUE TITLE
[Feature] 为什么直连没有延时？

### ISSUE THREAD

**Issue by yixiuge301** [clash-verge-rev/clash-verge-rev#1741]
### 问题描述 / Describe the bug

为什么 clash verge rev 不显示直连的延时？测试地址都是 `http://connect.rom.miui.com/generate_204`
web ui
![image](https://github.com/user-attachments/assets/de6c1ce2-730d-42e2-989e-54f5e1a843ac)
clash verge rev
![image](https://github.com/user-attachments/assets/b3fe3734-92c6-4986-9171-2568f04b9e11)

### 复现步骤 / To Reproduce

代理 菜单，选择全局，填上测试地址，延时测试，看直连。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows10

### 日志 / Log

无

**Comment by Kiritocyz** [comment]
DIRECT好像一直没有显示延时，但是你把它放进url-test的代理组里，就可以测出延时了

**Comment by yixiuge301** [comment]
> DIRECT好像一直没有显示延时，但是你把它放进url-test的代理组里，就可以测出延时了

那还是改成都能显示延时吧
