### ISSUE TITLE
[Feature] 如何添加全局自定义规则？

### ISSUE THREAD

**Issue by murazi** [clash-verge-rev/clash-verge-rev#1744]
### 功能描述 / Feature description

1. 我有20多个订阅，如果我要为一个网站添加自定义规则，我需要向20个订阅分别添加规则？
2. 不同的订阅规则也不一样，他们的规则结尾通常是以自己服务器名字作为规则定义的

我希望可以统一下规范，至少不要让不同订阅的规则写法不同
规则结尾简单点，Direct，Proxy，Global这样
或者把添加规则UI化

### 使用场景 / Use case

windows10

**Comment by Kiritocyz** [comment]
你可以参考这个😘
https://github.com/Kiritocyz/Clash

**Comment by murazi** [comment]
> 你可以参考这个😘 https://github.com/Kiritocyz/Clash

谢谢，不过已经更新最新版了，发现可以全局规则了，而且订阅也支持UI添加规则了，希望可以把这个UI添加可以安排到全局规则里，因为我基本不会在订阅里添加规则，订阅太多太麻烦了。

问题基本解决，关闭反馈，感谢作者的软件分享~

**Comment by suifeng998** [comment]
访问Apple中国进不去（换了别的规则可以），而且访问还有部分可以国内直连的网站经常打不开

**Comment by Fxskyzz** [comment]
> > 你可以参考这个😘 https://github.com/Kiritocyz/Clash
> 
> 谢谢，不过已经更新最新版了，发现可以全局规则了，而且订阅也支持UI添加规则了，希望可以把这个UI添加可以安排到全局规则里，因为我基本不会在订阅里添加规则，订阅太多太麻烦了。
> 
> 问题基本解决，关闭反馈，感谢作者的软件分享~

![Image](https://github.com/user-attachments/assets/78ab1f98-aadb-49ab-9fcb-e40ed794abe4)
![Image](https://github.com/user-attachments/assets/a3d4f1ae-aeed-45d6-896f-0488072ca244)
你好，请教一下我先配置这条规则，配置域名后缀是ut.cn的都不走代理为什么无法生效。应该怎么配置呢

**Comment by Kiritocyz** [comment]
> > > 你可以参考这个😘 https://github.com/Kiritocyz/Clash
> > 
> > 
> > 谢谢，不过已经更新最新版了，发现可以全局规则了，而且订阅也支持UI添加规则了，希望可以把这个UI添加可以安排到全局规则里，因为我基本不会在订阅里添加规则，订阅太多太麻烦了。
> > 问题基本解决，关闭反馈，感谢作者的软件分享~
> 
> ![Image](https://github.com/user-attachments/assets/78ab1f98-aadb-49ab-9fcb-e40ed794abe4) ![Image](https://github.com/user-attachments/assets/a3d4f1ae-aeed-45d6-896f-0488072ca244) 你好，请教一下我先配置这条规则，配置域名后缀是ut.cn的都不走代理为什么无法生效。应该怎么配置呢

系统代理是否开启了呢，在连接里看一下这个域名的连接情况（看看走哪去了）

**Comment by keyboard2005** [comment]
没看懂, 这不还是要一条条自己加吗? 怎么倒入规则配置?

**Comment by Dragon1573** [comment]
> 没看懂, 这不还是要一条条自己加吗? 怎么倒入规则配置?

你可以自己引入 `rule-providers` ，由外部提供规则

**Comment by keyboard2005** [comment]
> > 没看懂, 这不还是要一条条自己加吗? 怎么倒入规则配置?
> 
> 你可以自己引入 `rule-providers` ，由外部提供规则

嗯 通过这个解决了, 你回复好快 谢谢你快速回复
