### ISSUE TITLE
[BUG] 2.0版本，鼠标左键托盘，也会出现右键托盘菜单。

### ISSUE THREAD

**Issue by Kiritocyz** [clash-verge-rev/clash-verge-rev#1746]
### 问题描述 / Describe the bug

如题

### 复现步骤 / To Reproduce

如题

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

![image](https://github.com/user-attachments/assets/1380ada5-930b-4fc0-894b-b92531aebba6)

**Comment by wonfen** [comment]
已知问题，影响不大，看看能否优化一下。

**Comment by ilovelxy** [comment]
+1
