### ISSUE TITLE
[BUG] Arch linux无法显示面板

### ISSUE THREAD

**Issue by Alantemper** [clash-verge-rev/clash-verge-rev#1748]
### 问题描述 / Describe the bug

** (clash-verge:1661): WARNING **: 22:00:00.011: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.

### 复现步骤 / To Reproduce

终端运行clash-verge,报错

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Arch linux kde6.1.5 wayland

### 日志 / Log

** (clash-verge:1661): WARNING **: 22:00:00.011: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.

**Comment by moheng233** [comment]
这个问题是因为更新了`webkit2gtk:2.46.0-1`导致的，使用`pacman`降级`webkit2gtk`到上一个版本可以修复问题
问题原因排查是`webkit2gtk`更新后导致的排版问题

**Comment by Alantemper** [comment]
> 这个问题是因为更新了`webkit2gtk:2.46.0-1`导致的，使用`pacman`降级`webkit2gtk`到上一个版本可以修复问题
> 问题原因排查是`webkit2gtk`更新后导致的排版问题

降级后问题依旧

**Comment by CheeseSilly** [comment]
同样有这个问题，退级到 webkit2gtk-2.44.4-1用了不起作用，添加环境变量`WEBKIT_DISABLE_COMPOSITING_MODE=1
WEBKIT_DISABLE_DMABUF_RENDERER=1`也无济于事

**Comment by Orion-zhen** [comment]
+1, 降级不起作用

**Comment by zwhao77** [comment]
同样有这个问题,退级到`webkit2gtk-2.44.4-1`后终端运行时报错
```
clash-verge: error while loading shared libraries: libjxl.so.0.10: cannot open shared object file: No such file or directory
```
如果要退级到`webkit2gtk-2.44.4-1`，可能还需要退级到`libjxl.so.0.10`。

由于退级到`libjxl.so.0.10.0`影响太广，我尝试先直接创建了`libjxl.so.0.10`到`libjxl.so.0.11.0`的硬连接（直接创建连接不是合适的解决方法）。创建连接后clash-verge能够运行并显示面板，但是通过终端运行仍有报错,打开面板时

```
** (clash-verge:164983): WARNING **: 23:37:54.437: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
```
关闭面板时
```
Unhandled network process message 'NetworkStorageManager_DisconnectFromStorageArea'
```
由于直接设置链接可能出现其他问题，我后续设置了Web UI来控制Clash,删除了`libjxl.so.0.10`的连接并将`webkit2gtk`更新回最新版本，此时clash-verge能够工作，但显示的面板为完全空白。

**Comment by Orion-zhen** [comment]
> 同样有这个问题,退级到`webkit2gtk-2.44.4-1`后终端运行时报错
> ```
> clash-verge: error while loading shared libraries: libjxl.so.0.10: cannot open shared object file: No such file or directory
> ```
> 如果要退级到`webkit2gtk-2.44.4-1`，可能还需要退级到`libjxl.so.0.10`。
> 
> 由于退级到`libjxl.so.0.10.0`影响太广，我尝试先直接创建了`libjxl.so.0.10`到`libjxl.so.0.11.0`的硬连接（直接创建连接不是合适的解决方法）。创建连接后clash-verge能够运行并显示面板，但是通过终端运行仍有报错,打开面板时
> 
> ```
> ** (clash-verge:164983): WARNING **: 23:37:54.437: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
> ```
> 关闭面板时
> ```
> Unhandled network process message 'NetworkStorageManager_DisconnectFromStorageArea'
> ```
> 由于直接设置链接可能出现其他问题，我后续设置了Web UI来控制Clash,删除了`libjxl.so.0.10`的连接并将`webkit2gtk`更新回最新版本，此时clash-verge能够工作，但显示的面板为完全空白。

请问能讲解如何在没有gui发情况下启用webui并进行配置吗？

**Comment by zwhao77** [comment]
> > 同样有这个问题,退级到`webkit2gtk-2.44.4-1`后终端运行时报错
> > ```
> > clash-verge: error while loading shared libraries: libjxl.so.0.10: cannot open shared object file: No such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果要退级到`webkit2gtk-2.44.4-1`，可能还需要退级到`libjxl.so.0.10`。
> > 由于退级到`libjxl.so.0.10.0`影响太广，我尝试先直接创建了`libjxl.so.0.10`到`libjxl.so.0.11.0`的硬连接（直接创建连接不是合适的解决方法）。创建连接后clash-verge能够运行并显示面板，但是通过终端运行仍有报错,打开面板时
> > ```
> > ** (clash-verge:164983): WARNING **: 23:37:54.437: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 关闭面板时
> > ```
> > Unhandled network process message 'NetworkStorageManager_DisconnectFromStorageArea'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 由于直接设置链接可能出现其他问题，我后续设置了Web UI来控制Clash,删除了`libjxl.so.0.10`的连接并将`webkit2gtk`更新回最新版本，此时clash-verge能够工作，但显示的面板为完全空白。
> 
> 请问能讲解如何在没有gui的情况下启用webui并进行配置吗？

我是通过上述提到的临时创建连接的方式临时打开gui并进行配置的，不过如果没有修改过相关配置，clash-verge默认监听的可能是 `127.0.0.1:9097` 且无需密码。因此直接打开 https://yacd.metacubex.one/?hostname=127.0.0.1&port=9097 可能能够直接进入webui。

如果能够启动clash-verge并且能够看到托盘图标，在托盘右键菜单-打开目录-应用目录 所打开的目录中(在我的电脑上，这个目录是`~/.local/share/io.github.clash-verge-rev.clash-verge-rev`)的`clash-verge.yaml` 和 `config.yaml` 中的 `external-controller`和 `secret` 应该是配置webui监听地址和密码的项，同时修改这两个文件中的相关项并重启clash-verge能够起到修改webui监听地址和密码的效果，但我无法确定对于配置webui是否足够。

**Comment by Orion-zhen** [comment]
感谢, 已经配置好了

**Comment by dengxutian** [comment]
把系统改成英文可以显示前端，但是切换回中文就是空白的。

**Comment by LeonLeeLi** [comment]
根据上一层说的，使用LANG=en_US clash-verge时可以显示面板，暂时把.desktop文件改改用着吧，等到webkit2gtk修复吧

**Comment by Yunak** [comment]
> 根据上一层说的，使用LANG=en_US clash-verge时可以显示面板，暂时把.desktop文件改改用着吧，等到webkit2gtk修复吧

![image](https://github.com/user-attachments/assets/7653721e-85d1-45c3-abbc-51b930eb1d46)
实测可以

**Comment by nicangtianws** [comment]
> > 根据上一层说的，使用LANG=en_US clash-verge时可以显示面板，暂时把.desktop文件改改用着吧，等到webkit2gtk修复吧
> 
> ![image](https://private-user-images.githubusercontent.com/16012667/374789657-7653721e-85d1-45c3-abbc-51b930eb1d46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjU3NTEsIm5iZiI6MTcyOTI2NTQ1MSwicGF0aCI6Ii8xNjAxMjY2Ny8zNzQ3ODk2NTctNzY1MzcyMWUtODVkMS00NWMzLWFiYmMtNTFiOTMwZWIxZDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE1MzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NThhMTkyMWFhZWNlMGZlYzY3YjJkYWY0Y2VjZDgwYzU0NGZjNTNmOWI5MGU2MDMyOWZlOTMyNTkzODhlYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.63OU772-_fLFZ1QcmrGkCKQnhVdqgQSlRkpgfptBuv0) 实测可以

thx

**Comment by pluto0x0** [comment]
> 根据上一层说的，使用LANG=en_US clash-verge时可以显示面板，暂时把.desktop文件改改用着吧，等到webkit2gtk修复吧

XFCE中似乎无法解决
