### ISSUE TITLE
[BUG] 无法正常访问YouTube等网站

### ISSUE THREAD

**Issue by dave813-me** [clash-verge-rev/clash-verge-rev#1750]
### 问题描述 / Describe the bug

安装Apha2.0.0版本后,操作页面一切正常,就是主页面左下方的上传速度和下载速度显示都是0,线条一直没有波动,不管所选的节点是什么,即使节点可用(延迟时间430),所以导致了无法访问外网,这种情况一直持续了好几天,clash verge rev 1,7.7版本也是如此.

### 复现步骤 / To Reproduce

<img width="1251" alt="截屏2024-09-22 00 12 57" src="https://github.com/user-attachments/assets/1a2e5282-7979-49a1-94cc-42b12d1705fb">
<img width="1251" alt="截屏2024-09-22 00 24 21" src="https://github.com/user-attachments/assets/dfe4e804-9053-460c-af58-726bd9311f7a">

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

MacOS Sequoia 15.1beta

### 日志 / Log

<img width="1251" alt="截屏2024-09-22 00 13 55" src="https://github.com/user-attachments/assets/39cf85a7-1926-428a-a9be-46d67850940d">
<img width="1251" alt="截屏2024-09-22 00 14 51" src="https://github.com/user-attachments/assets/4eaeadac-c30d-4dca-b974-b67e187a7bbf">
<img width="1251" alt="截屏2024-09-22 00 23 40" src="https://github.com/user-attachments/assets/d72e2f83-4616-4d30-9fb6-e2e2876a7be3">

**Comment by wonfen** [comment]
检查你的配置文件，从日志来看，是服务器节点配置的问题

**Comment by dave813-me** [comment]
请问具体怎么操作

**Comment by ShiyangDi-star** [comment]
我这个显示可以，但是还是不行哦
