### ISSUE TITLE
[BUG] 新建配置，使用内核代理更新开关状态保存不了

### ISSUE THREAD

**Issue by yixiuge301** [clash-verge-rev/clash-verge-rev#1753]
### 问题描述 / Describe the bug

新建订阅，【使用内核代理更新】保存不了，要保存后再【编辑信息】，才可以

版本信息
![image](https://github.com/user-attachments/assets/9d75d915-3a33-40c8-bf59-e67d1cfbe82d)

### 复现步骤 / To Reproduce

新建订阅
![image](https://github.com/user-attachments/assets/d1d8fdc3-d132-452a-b886-068867302293)
编辑刚新建的配置
![image](https://github.com/user-attachments/assets/9b5bb26b-bc3c-4e65-839b-999abe257795)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11

### 日志 / Log

无

**Comment by Coralsakura** [comment]
大佬，可以 问问勾选使用系统代理更新，和内核代理更新与不勾选有什么区别吗

**Comment by yixiuge301** [comment]
> 大佬，可以 问问勾选使内核代理更新与不勾选有什么区别吗

就字面意思
