### ISSUE TITLE
[BUG] Clash Verge本体不被系统代理

### ISSUE THREAD

**Issue by AllForLandlord** [clash-verge-rev/clash-verge-rev#1754]
### 问题描述 / Describe the bug

Clash Verge本体不被系统代理，导致订阅链接被墙的话无法更新。换用TUN模式后可以正常代理Clash应用本体来更新订阅。

### 复现步骤 / To Reproduce

打开系统代理，更新被墙的订阅，无法更新。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11

### 日志 / Log

无

**Comment by HozumiMoa** [comment]
不是有通过代理更新订阅的选项吗

**Comment by AllForLandlord** [comment]
> 不是有通过代理更新订阅的选项吗

噢噢，谢谢，看到了
