### ISSUE TITLE
[Feature] command+Q 退出 clash 目前是全局快捷键，希望调整为只有开启主界面的时候才有这个快捷键

### ISSUE THREAD

**Issue by kenxjc** [clash-verge-rev/clash-verge-rev#1756]
### 功能描述 / Feature description

command+Q 退出 clash 目前是全局快捷键，在其他 app 界面按下 command+Q 会先退出 clash verge，不确定这个是 bug 还是功能设计

系统是 MacOS Sequoia

### 使用场景 / Use case

退出程序

**Comment by scopewu** [comment]
是不是提出这项提议，导致 #1770 问题。`command+Q` 是 macOS 系统行为不应该进行干预。如果是由此而来，可以尝试回退。
