### ISSUE TITLE
[BUG]没有那个文件或目录（os error 2) 

### ISSUE THREAD

**Issue by htqx** [clash-verge-rev/clash-verge-rev#176]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/42466118/ddc850aa-73cf-406f-a941-2cfe91f0b490)

我是arch linux 用户，昨天更新完毕后出现配置丢失，重新订阅，修改配置提示：没有那个文件或目录（os error 2) 错误。

### To Reproduce

1. 更新
2. 配置完全丢失
3. 重新订阅
4. 修改配置时提示

### Platform

Linux

### System Version

Linux arch-pc-lv3 6.6.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 14 Dec 2023 03:45:42 +0000 x86_64 GNU/Linux

### Software Version

v1.4.5

**Comment by WinteWu** [comment]
可以使用一下命名暂时解决
`
tar zcvf  clash-verge-rev.tar.gz .local/share/io.github.clash-verge-rev.clash-verge-rev  && 
cp -rf .config/clash-verge/* .local/share/io.github.clash-verge-rev.clash-verge-rev
`
然后重启

**Comment by htqx** [comment]
> 可以使用一下命令暂时解决，猜测是配置文件位置有更新或者忘记修改了 `tar zcvf clash-verge-rev.tar.gz .local/share/io.github.clash-verge-rev.clash-verge-rev && cp -rf .config/clash-verge/* .local/share/io.github.clash-verge-rev.clash-verge-rev` 然后重启一下clash-verge

确实看到以前的配置，但是「代理]也没有内容，[连接]也没有内容，[规则]也没有内容，单击订阅任意一个配置，同样的错误提示。

**Comment by howiieyu** [comment]
same issue
