### ISSUE TITLE
[BUG] TUN模式下微信发送、接受图片、文件缓慢甚至失败

### ISSUE THREAD

**Issue by howardhey** [clash-verge-rev/clash-verge-rev#1762]
### 问题描述 / Describe the bug

在开启TUN模式的情况下，使用微信程序接受或发送图片、文件时，市场出现速度非常慢，甚至发送失败的情况，该问题除我之外，也有其他人遇到过，并且一直没有随着版本更新而解决。

### 复现步骤 / To Reproduce

使用TUN-GVisor即出现该问题。
已经手动添加了WeChat.exe强制DIRECT的规则，且在规则页面中可以看到已经在顶部生效，但还是会遇到如上问题。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11Pro

### 日志 / Log

09-23 21:33:21info
[TCP] [fdfe:dcba:9876::1]:8850(WeChat.exe) --> [2409:8702:4860:10::4d]:8080 match ProcessName(WeChat.exe) using DIRECT
09-23 21:33:22info
[TCP] [fdfe:dcba:9876::1]:8852(WeChat.exe) --> [2409:8c54:871:1004::18]:8080 match ProcessName(WeChat.exe) using DIRECT
09-23 21:33:22info
[TCP] [fdfe:dcba:9876::1]:8856(WeChat.exe) --> [2409:8c54:1050:44::14]:80 match ProcessName(WeChat.exe) using DIRECT
09-23 21:33:23info
[TCP] [fdfe:dcba:9876::1]:8854(WeChat.exe) --> [2409:8c54:871:4001::28]:80 match ProcessName(WeChat.exe) using DIRECT
09-23 21:34:43info
[TCP] [fdfe:dcba:9876::1]:8986(WeChat.exe) --> [2402:4e00:1620:1611:0:9cb4:cd00:bcfc]:80 match ProcessName(WeChat.exe) using DIRECT

**Comment by howardhey** [comment]
> 没记错的话，应该是dns分流和fake-ip的问题，把日志等级调成debug查一下

感谢您的回答，但我还是不太能理解，这个问题也不是总会出现，有概率会遇到，能麻烦您更详细说一下如何操作吗，非常谢谢！

**Comment by cjlhll** [comment]
解决了吗？clash verge 一直把wechat的域名解析为ip了，导致分流不生效，我在openwrt上的clash就正常解析的是wechat.com域名，分流就没问题。

**Comment by Tychristine** [comment]
@cjlhll 你自己的问题，说明Mihomo Core没有劫持到DNS，全是你的系统DNS解析完了才转发给Mihomo代理流量。MacOS下需要设置系统DNS为非LAN网

**Comment by cjlhll** [comment]
> @cjlhll 你自己的问题，说明Mihomo Core没有劫持到DNS，全是你的系统DNS解析完了才转发给Mihomo代理流量。MacOS下需要设置系统DNS为非LAN网

别的域名都是正常呢。就wechat的不正常。我是windows。

**Comment by cjlhll** [comment]
> @cjlhll 你自己的问题，说明Mihomo Core没有劫持到DNS，全是你的系统DNS解析完了才转发给Mihomo代理流量。MacOS下需要设置系统DNS为非LAN网

我的windows是手动设置ip的，公司网络，如何指向dns为clash verge呢？

**Comment by Mark-Wu2003** [comment]
@Tychristine 大佬你好，我可以向你请教一下macos的配置吗，blog.tyasaka.xyz似乎打不开

**Comment by Tychristine** [comment]
@Mark-Wu2003 
域名弃用了，配置文件基础模板已移动至cvr官网上

**Comment by Mark-Wu2003** [comment]
@Tychristine 所以最好直接fake-ip-filter里把微信剔除掉吗

**Comment by Mark-Wu2003** [comment]
我想再顺便问一下，我是这样如下设置TUN的，并在GUI界面里的 tun-dns填了198.18.0.2，但是一旦这样设置会导致网络经常连接不上，请问是198.18.0.2有问题吗。谢谢您！
tun: 
  enable: true
  stack: system
  dns-hijack:
    - '198.18.0.2:53'
    - 'tcp://198.18.0.2:53'

> [@Mark-Wu2003](https://github.com/Mark-Wu2003) 域名弃用了，配置文件基础模板已移动至cvr官网上

**Comment by haytoo** [comment]
解决了吗兄弟们？我是 MacOS，开了 tun 虚拟网卡模式，微信图片收发都很痛苦～

**Comment by szkane** [comment]
兄弟们，试试在全局覆写中增加TUN exclude process，以下是 MacOS 的示例

```
tun:
  exclude-process:
    - WeChatAppEx Helper
    - WeChat
 rules:
    - PROCESS-NAME,WeChat,DIRECT
    - PROCESS-NAME,WeChatAppEx Helper,DIRECT
```

**Comment by haytoo** [comment]
> 兄弟们，试试在全局覆写中增加TUN exclude process，以下是 MacOS 的示例
> 
> ```
> tun:
>   exclude-process:
>     - WeChatAppEx
>     - WeChat
> ```
好兄弟，谢谢你。你的思路解决了我的问题

**Comment by robin12jbj** [comment]
> 兄弟们，试试在全局覆写中增加TUN exclude process，以下是 MacOS 的示例
> 
> ```
> tun:
>   exclude-process:
>     - WeChatAppEx Helper
>     - WeChat
>  rules:
>     - PROCESS-NAME,WeChat,DIRECT
>     - PROCESS-NAME,WeChatAppEx Helper,DIRECT
> ```

多谢

**Comment by Sartner** [comment]
看看是不是开了ipv6，关了试一下

**Comment by Petrichor-Dusk** [comment]
关ipv6可行

**Comment by YangYongAn** [comment]
> 看看是不是开了ipv6，关了试一下

好使了，是 bug 吗

@作者

**Comment by Slinetrac** [comment]
> 是 bug 吗

可能是上游 mihomo 内核的 ipv6 回退处理有 bug。

**Comment by mylovesaber** [comment]
我发现微信无法发图，但是文字正常发送，观察clash verge的日志：
```c
12-17 15:19:44warning
[TCP] dial 🔗 全局直连 (match RuleSet/cncidr) [fdfe:dcba:9876::1]:63761(Weixin.exe) --> [240e:97c:2f:4001::31]:80 error: connect failed: dial tcp [240e:97c:2f:4001::31]:80: connectex: A socket operation was attempted to an unreachable network.
```
看起来是微信要走ipv6然后不可访问导致，公司网络没有ipv6，因此我对【全局扩展脚本】做了调整（这个配置是顶层配置，不是某个函数中的嵌套配置）：
```js
// DNS配置
const dnsConfig = {
    "enable": true,
    "listen": "0.0.0.0:1053",
    // "ipv6": true,
    "ipv6": false,
    "prefer-h3": false,
    "respect-rules": true,
    "use-system-hosts": false,
    "cache-algorithm": "arc",
    "enhanced-mode": "fake-ip",
    "fake-ip-range": "198.18.0.1/16",
    "fake-ip-filter": [
        // 本地主机/设备
        "+.lan",
        "+.local",
        // // Windows网络出现小地球图标
        "+.msftconnecttest.com",
        "+.msftncsi.com",
        // QQ快速登录检测失败
        "localhost.ptlogin2.qq.com",
        "localhost.sec.qq.com",
        // 微信快速登录检测失败
        "localhost.work.weixin.qq.com"
    ],
    "default-nameserver": ["223.5.5.5", "1.2.4.8"],
    "nameserver": [...foreignNameservers],
    "proxy-server-nameserver": [...domesticNameservers],
    "direct-nameserver": [...domesticNameservers],
    "direct-nameserver-follow-policy": false,
    "nameserver-policy": {
        "geosite:cn": domesticNameservers
    }
};
```
将ipv6显式指定false，保存退出后刷新订阅，微信再点发图片就可以发出去了

**Comment by T97-coffee** [comment]
> 兄弟们，试试在全局覆写中增加TUN exclude process，以下是 MacOS 的示例
> 
> ```
> tun:
>   exclude-process:
>     - WeChatAppEx Helper
>     - WeChat
>  rules:
>     - PROCESS-NAME,WeChat,DIRECT
>     - PROCESS-NAME,WeChatAppEx Helper,DIRECT
> ```

非常好用，windows把-去掉也可以了
```
tun:
  exclude-process:
    WeChatAppEx Helper
    WeChat
rules:
    PROCESS-NAME,WeChat,DIRECT
    PROCESS-NAME,WeChatAppEx Helper,DIRECT
```

**Comment by wenyuantc** [comment]
我关掉ipv6就可以了

**Comment by linlianhao11-stack** [comment]
关闭IPV6就可以了。不知道为什么

**Comment by Dagsi** [comment]
> 兄弟们，试试在全局覆写中增加TUN exclude process，以下是 MacOS 的示例
> 
> ```
> tun:
>   exclude-process:
>     - WeChatAppEx Helper
>     - WeChat
>  rules:
>     - PROCESS-NAME,WeChat,DIRECT
>     - PROCESS-NAME,WeChatAppEx Helper,DIRECT
> ```

好像Mihomo不支持exclude process

**Comment by kevinh458** [comment]
> > 兄弟们，试试在全局覆写中增加TUN exclude process，以下是 MacOS 的示例
> > ```
> > tun:
> >   exclude-process:
> >     - WeChatAppEx Helper
> >     - WeChat
> >  rules:
> >     - PROCESS-NAME,WeChat,DIRECT
> >     - PROCESS-NAME,WeChatAppEx Helper,DIRECT
> > ```
> 
> 非常好用，windows把-去掉也可以了
> 
> ```
> tun:
>   exclude-process:
>     WeChatAppEx Helper
>     WeChat
> rules:
>     PROCESS-NAME,WeChat,DIRECT
>     PROCESS-NAME,WeChatAppEx Helper,DIRECT
> ```

我直接粘贴到配置里 就会导致我的clash 无法访问外网了 请问一下大佬是这么配置的吗

<img width="684" height="406" alt="Image" src="https://github.com/user-attachments/assets/5cafac4a-71ef-46ad-aa89-27dbb3e87549" />

**Comment by PLFJY** [comment]
> > > 兄弟们，试试在全局覆写中增加TUN exclude process，以下是 MacOS 的示例
> > > ```
> > > tun:
> > >   exclude-process:
> > >     - WeChatAppEx Helper
> > >     - WeChat
> > >  rules:
> > >     - PROCESS-NAME,WeChat,DIRECT
> > >     - PROCESS-NAME,WeChatAppEx Helper,DIRECT
> > > ```
> > 
> > 
> > 非常好用，windows把-去掉也可以了
> > ```
> > tun:
> >   exclude-process:
> >     WeChatAppEx Helper
> >     WeChat
> > rules:
> >     PROCESS-NAME,WeChat,DIRECT
> >     PROCESS-NAME,WeChatAppEx Helper,DIRECT
> > ```
> 
> 我直接粘贴到配置里 就会导致我的clash 无法访问外网了 请问一下大佬是这么配置的吗
> 
> <img alt="Image" width="684" height="406" src="https://private-user-images.githubusercontent.com/45650311/566132679-5cafac4a-71ef-46ad-aa89-27dbb3e87549.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM5MTA0OTIsIm5iZiI6MTc3MzkxMDE5MiwicGF0aCI6Ii80NTY1MDMxMS81NjYxMzI2NzktNWNhZmFjNGEtNzFlZi00NmFkLWFhODktMjdkYmIzZTg3NTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzE5VDA4NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwOTA5NDVmYTMwNzY1ZTVmOTgxYmU5YWI2NGIyMGIyYTU0NGRjNTRkYTYyMDRjNDJkYzVkZTAxOTRjNDM3YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ALlioYLZIXI1xQHr-S5IOhev34bNCJpHanF8a36GtM0">

rules那里不能直接粘贴，你需要利用扩展脚本，这样子是会覆盖掉你机场配置给你的rules的，clash本身就是基于rules驱动的

**Comment by kevinh458** [comment]
> > > > 兄弟们，试试在全局覆写中增加TUN exclude process，以下是 MacOS 的示例
> > > > ```
> > > > tun:
> > > >   exclude-process:
> > > >     - WeChatAppEx Helper
> > > >     - WeChat
> > > >  rules:
> > > >     - PROCESS-NAME,WeChat,DIRECT
> > > >     - PROCESS-NAME,WeChatAppEx Helper,DIRECT
> > > > ```
> > > 
> > > 
> > > 非常好用，windows把-去掉也可以了
> > > ```
> > > tun:
> > >   exclude-process:
> > >     WeChatAppEx Helper
> > >     WeChat
> > > rules:
> > >     PROCESS-NAME,WeChat,DIRECT
> > >     PROCESS-NAME,WeChatAppEx Helper,DIRECT
> > > ```
> > 
> > 
> > 我直接粘贴到配置里 就会导致我的clash 无法访问外网了 请问一下大佬是这么配置的吗
> > <img alt="Image" width="684" height="406" src="https://private-user-images.githubusercontent.com/45650311/566132679-5cafac4a-71ef-46ad-aa89-27dbb3e87549.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM5MTA0OTIsIm5iZiI6MTc3MzkxMDE5MiwicGF0aCI6Ii80NTY1MDMxMS81NjYxMzI2NzktNWNhZmFjNGEtNzFlZi00NmFkLWFhODktMjdkYmIzZTg3NTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzE5VDA4NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwOTA5NDVmYTMwNzY1ZTVmOTgxYmU5YWI2NGIyMGIyYTU0NGRjNTRkYTYyMDRjNDJkYzVkZTAxOTRjNDM3YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ALlioYLZIXI1xQHr-S5IOhev34bNCJpHanF8a36GtM0">
> 
> rules那里不能直接粘贴，你需要利用扩展脚本，这样子是会覆盖掉你机场配置给你的rules的，clash本身就是基于rules驱动的

<img width="868" height="637" alt="Image" src="https://github.com/user-attachments/assets/23d3a39e-579b-4c68-91ba-e257e4fd9503" />

这样配置虽然不会影响vpn上网了但是微信仍然不能收发图片 大佬知道为什么吗

**Comment by PLFJY** [comment]
> > > > > 兄弟们，试试在全局覆写中增加TUN exclude process，以下是 MacOS 的示例
> > > > > ```
> > > > > tun:
> > > > >   exclude-process:
> > > > >     - WeChatAppEx Helper
> > > > >     - WeChat
> > > > >  rules:
> > > > >     - PROCESS-NAME,WeChat,DIRECT
> > > > >     - PROCESS-NAME,WeChatAppEx Helper,DIRECT
> > > > > ```
> > > > 
> > > > 
> > > > 非常好用，windows把-去掉也可以了
> > > > ```
> > > > tun:
> > > >   exclude-process:
> > > >     WeChatAppEx Helper
> > > >     WeChat
> > > > rules:
> > > >     PROCESS-NAME,WeChat,DIRECT
> > > >     PROCESS-NAME,WeChatAppEx Helper,DIRECT
> > > > ```
> > > 
> > > 
> > > 我直接粘贴到配置里 就会导致我的clash 无法访问外网了 请问一下大佬是这么配置的吗
> > > <img alt="Image" width="684" height="406" src="https://private-user-images.githubusercontent.com/45650311/566132679-5cafac4a-71ef-46ad-aa89-27dbb3e87549.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM5MTA0OTIsIm5iZiI6MTc3MzkxMDE5MiwicGF0aCI6Ii80NTY1MDMxMS81NjYxMzI2NzktNWNhZmFjNGEtNzFlZi00NmFkLWFhODktMjdkYmIzZTg3NTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzE5VDA4NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwOTA5NDVmYTMwNzY1ZTVmOTgxYmU5YWI2NGIyMGIyYTU0NGRjNTRkYTYyMDRjNDJkYzVkZTAxOTRjNDM3YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ALlioYLZIXI1xQHr-S5IOhev34bNCJpHanF8a36GtM0">
> > 
> > 
> > rules那里不能直接粘贴，你需要利用扩展脚本，这样子是会覆盖掉你机场配置给你的rules的，clash本身就是基于rules驱动的
> 
> <img alt="Image" width="868" height="637" src="https://private-user-images.githubusercontent.com/45650311/566136702-23d3a39e-579b-4c68-91ba-e257e4fd9503.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM5MTE5NjYsIm5iZiI6MTc3MzkxMTY2NiwicGF0aCI6Ii80NTY1MDMxMS81NjYxMzY3MDItMjNkM2EzOWUtNTc5Yi00YzY4LTkxYmEtZTI1N2U0ZmQ5NTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzE5VDA5MTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ODMzNGMxOTRjNDNlMzJkZjQ0NThhZmQyZWNhMWFjN2FlNWZmZWI1MTNlMzE3M2E5MmJlOWMxODViNjljNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.amvbSOqEMgpNBk8FCvEGsd3cBtLakvKfC9Uy7ZiBPuk">
> 这样配置虽然不会影响vpn上网了但是微信仍然不能收发图片 大佬知道为什么吗

给你个建议，直接把ipv6关上，你的mihomo会欺骗微信让微信以为你有ipv6，实则没有，但是mihomo并没有很好的处理这个行为，然后就发不出去了

**Comment by bytegz** [comment]
> 兄弟们，试试在全局覆写中增加TUN exclude process，以下是 MacOS 的示例
> 
> ```
> tun:
>   exclude-process:
>     - WeChatAppEx Helper
>     - WeChat
>  rules:
>     - PROCESS-NAME,WeChat,DIRECT
>     - PROCESS-NAME,WeChatAppEx Helper,DIRECT
> ```

完美解决！

**Comment by tvrpdfe** [comment]
综合上述各位的回答，经过我测试给出如下的扩展脚本，实测是可以的，重点就是增加的tun字段
```
function main(config) {
  // 把旧规则合并到新规则后面(也可以用其它合并数组的办法)
  let oldrules = config["rules"];
  config["rules"] = prependRule.concat(oldrules);
  config["tun"] = {
    "exclude-process": ["Weixin.exe", "Weixin"]
  };
  return config;
}
```

**Comment by nikonikoCW** [comment]
设置里关掉IPV6就好了
