### ISSUE TITLE
[Feature] MacOS能不能加一个取消dock栏中图标等功能

### ISSUE THREAD

**Issue by FanBigFan** [clash-verge-rev/clash-verge-rev#1763]
### 功能描述 / Feature description

MacOS能不能加一个取消dock栏中图标等功能

### 使用场景 / Use case

MacOS能不能加一个取消dock栏中图标等功能

**Comment by Ins1nuatE** [comment]
支持，希望静默启动的时候可以不显示 dock 图标

**Comment by wonfen** [comment]
本来就没有显示dock
