### ISSUE TITLE
[BUG] TUN模式导致部分应用程序异常

### ISSUE THREAD

**Issue by maysilence** [clash-verge-rev/clash-verge-rev#1766]
### 问题描述 / Describe the bug

应该是从1.7版本开始，TUN模式下科学上网没问题，但是很多应用程序就无法正常使用，目前已知的：lx-music-desktop，女神异闻录5X的启动器，表现为显示连接超时，必须关掉TUN模式之后才可以使用，后来换回之前的Clash-For-Windows，开启TUN模式，无论是科学上网还是这几个程序都可以正常使用，还请尽快解决，谢谢。

### 复现步骤 / To Reproduce

打开Clash-Verge的TUN模式，lx-music-desktop里随便搜索音乐，返回结果为空，关闭TUN模式，正常返回搜索结果，退出Clash-Verge，开启Clash-For-Windows，开启TUN模式，lx-music-desktop搜索音乐，正常返回结果。P5X同理，开始Verge的TUN之后显示连接超时，无法正常进入游戏，关闭TUN模式或启动CFW的TUN模式之后，可以正常更新并进入游戏。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11

### 日志 / Log

[TCP] 198.18.0.1:49419(P5XGame.exe) --> clientlog.wanmei.com:80 match ProcessName(P5XGame.exe) using DIRECT
09-24 12:58:37info
[TCP] 198.18.0.1:50463(lx-music-desktop.exe) --> search.kuwo.cn:80 match ProcessName(lx-music-desktop.exe) using DIRECT
09-24 12:58:37info
[TCP] 198.18.0.1:50462(lx-music-desktop.exe) --> songsearch.kugou.com:443 match ProcessName(lx-music-desktop.exe) using DIRECT

**Comment by liuchengts** [comment]
我最近用这个客户端 版本是1.7.7 发现 tun模式经常中断，日志显示本地socks断开再连接。唉 搞的我很难受

**Comment by maysilence** [comment]
> 我最近用这个客户端 版本是1.7.7 发现 tun模式经常中断，日志显示本地socks断开再连接。唉 搞的我很难受

我感觉是TUN模式占用了一些常用端口导致的，实在受不了了，换了mihomo party，目前一切正常
