### ISSUE TITLE
[Feature] 增加快捷键；改进菜单栏ui

### ISSUE THREAD

**Issue by Tinymacs** [clash-verge-rev/clash-verge-rev#1768]
### 功能描述 / Feature description

1.7.7 Macos 15.0
 改进macOS版的菜单栏ui，让我能清晰地区分我当前是否打开了代理（比如说在打开代理时，猫咪是深色的，关闭代理时，猫咪是浅色透明的
<img width="177" alt="截屏2024-09-24 18 11 33" src="https://github.com/user-attachments/assets/7517b2dd-c3c8-4c58-a5dc-e1671641b378">

### 使用场景 / Use case

让我能瞟一眼菜单栏的小猫图标，就能清楚知道我当前是否打开了代理

**Comment by yujucun** [comment]
自己改吧，哥们

**Comment by chasonyu** [comment]
![image](https://github.com/user-attachments/assets/a1daefee-7d8b-4feb-b1a8-70ad9aa85a14)
设置成这样就行了。不过是彩色图标，开启是橙色，不开启是紫色

**Comment by Tinymacs** [comment]
> ![image](https://private-user-images.githubusercontent.com/49679565/372596708-a1daefee-7d8b-4feb-b1a8-70ad9aa85a14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDMzMDksIm5iZiI6MTcyNzg0MzAwOSwicGF0aCI6Ii80OTY3OTU2NS8zNzI1OTY3MDgtYTFkYWVmZWUtN2Q4Yi00ZmViLWIxYTgtNzBhZDlhYTg1YTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA0MjMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZjZhNDM4MDZmNTU3MzY0NmZhN2FkNjZhNGI1ZGM4MDBhZGQ1NWUzOGM1MjJhNjE4MDc5ZjFlNjdiYzU5OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tDPWMl3r3dylyc5iTqt654N8cE4URF_ahepfF_b8TJo) 设置成这样就行了。不过是彩色图标，开启是橙色，不开启是紫色

感谢！我发现您图片里最后一行“常规托盘图标”就可以用来修改显示在mac菜单栏的图标，上传自己的png图片文件即可，系统代理图标也是这么改的
