### ISSUE TITLE
[BUG] tun模式关闭, dns未被重置回原来的，仍是233.5.5.5

### ISSUE THREAD

**Issue by erlangzhang** [clash-verge-rev/clash-verge-rev#1769]
### 问题描述 / Describe the bug

tun模式关闭, dns未被重置回原来的，仍是223.5.5.5
能否控制tun模式不修改系统dns呢

### 复现步骤 / To Reproduce

tun模式关闭, dns未被重置回原来的，仍是223.5.5.5

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.4

**Comment by Ru7z** [comment]
同上。DNS被修改后，bypass对于公司内的域名解析也会失效。
