### ISSUE TITLE
[Feature] 设置代理默认排序

### ISSUE THREAD

**Issue by yixiuge301** [clash-verge-rev/clash-verge-rev#1772]
### 功能描述 / Feature description

应用可以设置这个默认排序方式吗？我想默认以延时排序，没找到哪里可以设置。
![image](https://github.com/user-attachments/assets/b9a0205a-1e50-447f-9a43-32a459bb98f9)

### 使用场景 / Use case

只关心延时排序，代理组手动选择代理时，更方便选择低的延时+想要的国家节点

**Comment by wonfen** [comment]
就是你选的这个
