### ISSUE TITLE
[BUG] 突然闪退 日志如下

### ISSUE THREAD

**Issue by 873589028** [clash-verge-rev/clash-verge-rev#1774]
### 问题描述 / Describe the bug

运行中突然闪退

### 复现步骤 / To Reproduce

 鼠标移动到右下角图标就消失了

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

19045.2364

### 日志 / Log

2024-09-26 07:02:38 ERROR - thread 'tokio-runtime-worker' panicked at C:\Users\runneradmin/.cargo\registry\src\index.crates.io-6f17d22bba15001f\wry-0.43.1\src\webview2\mod.rs:1001:5:
PostMessage failed ; is the messages queue full?
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by wonfen** [comment]
已知问题，等底层库修复。
https://github.com/tauri-apps/tauri/issues/11120

**Comment by Webster96** [comment]
同样问题，几十个人反馈了

**Comment by wonfen** [comment]
2.0_rc1版本做了处理；下载最新版测试。
