### ISSUE TITLE
[BUG] 安装服务模式时出现“VCRUNTIME140.dll is missing”

### ISSUE THREAD

**Issue by bellongyan** [clash-verge-rev/clash-verge-rev#1775]
### 问题描述 / Describe the bug

我在给电脑重装系统后，安装[Clash Verge Rev](https://github.com/clash-verge-rev/clash-verge-rev)并安装服务模式时弹窗提示“VCRUNTIME140.dll is missing”，自行前往微软官网下载[Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/zh-cn/download/details.aspx?id=48145)得以解决。

如果能在安装服务模式时检查用户电脑没有“VCRUNTIME140.dll”后引导到官网下载可降低下载到病毒文件的风险，或者在应用安装的时候自带这个dll避免用户电脑缺少对应的dll无法使用服务模式。

> After reinstalling the system on my computer, I installed [Clash Verge Rev](https://github.com/clash-verge-rev/clash-verge-rev) and installed the service mode. When I installed the service mode, a pop-up window prompted "VCRUNTIME140.dll is missing". Go to Microsoft's official website to download [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/zh-cn/download/details.aspx?id=48145) to solve the problem.
> 
> If you can check that the user's computer does not have "VCRUNTIME140.dll" when installing the service mode and then boot to the official website for download, you can reduce the risk of downloading virus files, or you can bring this dll when installing the application to avoid the user's computer lacking the corresponding dll and being unable to use the service. model.

### 复现步骤 / To Reproduce

1. 重装电脑
2. 安装Clash Verge Rev
3. 安装服务模式

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 22H2 Build 19045

### 日志 / Log

无

**Comment by wonfen** [comment]
底层基本运行库，一般正常系统都会自带。
