### ISSUE TITLE
[BUG] Intel 芯片的 Mac，服务模式安装无效，无法打开 Tun 模式

### ISSUE THREAD

**Issue by wungjyan** [clash-verge-rev/clash-verge-rev#1776]
### 问题描述 / Describe the bug

如图，点击安装了“服务模式”，也提示了安装成功，但是打开 Tun 模式时，依旧报错

提示安装成功：
<img width="577" alt="Snipaste_2024-09-26_15-27-31" src="https://github.com/user-attachments/assets/1207fe07-d615-4102-a3f8-0364ca5f3929">

打开 Tun 模式失败：
<img width="417" alt="Snipaste_2024-09-26_15-27-40" src="https://github.com/user-attachments/assets/f5af6754-d89b-4090-afae-9c3a18f94c0b">

之前电脑使用1.7.7 版本是可以的，后来重新安装过几次系统，包括手动安装系统和自动升级系统，之后就不能有效安装服务模式了。测试了 1.7.6，1.7.7 和新的2.0.0都不行。测试Mac系统有 14 和 15，都不行。

### 复现步骤 / To Reproduce

使用 Intel 芯片的 Mac 安装使用

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.0

### 日志 / Log

<img width="577" alt="Snipaste_2024-09-26_15-27-31" src="https://github.com/user-attachments/assets/5b76e3bd-1bed-406c-ae8f-be82a9d2f632">

<img width="417" alt="Snipaste_2024-09-26_15-27-40" src="https://github.com/user-attachments/assets/ae3e6991-eeb9-42ce-a018-16338559bf16">

**Comment by wonfen** [comment]
日志？

**Comment by wonfen** [comment]
试试最新的alpha版本，应该已经解决了这个问题。

**Comment by HenryLuoCN** [comment]
经过测试，现在的版本已经支持了。
![image](https://github.com/user-attachments/assets/8e73f32e-cfad-4a6e-a29a-44e1308564d6)

**Comment by wungjyan** [comment]
> 经过测试，现在的版本已经支持了。 ![image](https://private-user-images.githubusercontent.com/72094520/374476214-8e73f32e-cfad-4a6e-a29a-44e1308564d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NTI3MzksIm5iZiI6MTcyODQ1MjQzOSwicGF0aCI6Ii83MjA5NDUyMC8zNzQ0NzYyMTQtOGU3M2YzMmUtY2ZhZC00YTZlLWEyOWEtNDRlMTMwODU2NGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA1NDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMjdiNjdmMmEzZmEzZDZlMGE2MGUxMTA3OGE4NDIyMjk1OWUzZjllODBiMzBhNjViMWY1ZTMzYjk4YTY5ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gaEP3GXxRl8P1QqitaB2j9kg5890ThyErcBKMpsAGrA)



你是哪个版本，我试了最新的还是不行
<img width="569" alt="image" src="https://github.com/user-attachments/assets/0289625b-fb93-4d8d-958e-59aee2be9228">
