### ISSUE TITLE
[BUG] 在ubuntu下，通过源码编译后启动的。后来卸载以后ubuntu系统中所有浏览器都无法连接网络了。但是其他的不受影响。

### ISSUE THREAD

**Issue by rockjl** [clash-verge-rev/clash-verge-rev#1778]
### 问题描述 / Describe the bug

[BUG] 在ubuntu下，通过源码编译后启动的。后来卸载以后ubuntu系统中所有浏览器都无法连接网络了。但是其他的不受影响。

### 复现步骤 / To Reproduce

[BUG] 在ubuntu下，通过源码编译后启动的。后来卸载以后ubuntu系统中所有浏览器都无法连接网络了。但是其他的不受影响。

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

24.04

### 日志 / Log

[BUG] 在ubuntu下，通过源码编译后启动的。后来卸载以后ubuntu系统中所有浏览器都无法连接网络了。但是其他的不受影响。

**Comment by wonfen** [comment]
检查系统代理设置
