### ISSUE TITLE
[BUG]我操你妈的b

### ISSUE THREAD

**Issue by ghost** [clash-verge-rev/clash-verge-rev#178]
### Describe the bug

这么多人反馈cpu异常，你他妈开发你妈的b呢。在这里狗叫。我玩你妈的b。你把尼玛木马放里面了，cpu异常。狗日的玩意，说话yygq,我强奸你mm了。不能开发就别开发，隔着打广告买东西，还他妈不好好做。cnm的，内核跟你开发的一样。臭傻狗，套个外壳还尼玛的出丑。你他妈是把尼玛木马放里面了吗，cpu异常不解决，我操你妈妈的

### To Reproduce

操尼玛可以重现

### Platform

Windows

### System Version

nima11

### Software Version

nimab

**Comment by lanyi233** [comment]
樂

**Comment by wonfen** [comment]
换个设备试试看。那么多人用，其他人都没问题。

**Comment by dubiao** [comment]
世上真的有这种人，刷新认知了。

**Comment by sonderscode** [comment]
可以看出来，素质和能力无关，同时，控制情绪也是一种能力，很明显这位爷没有

**Comment by ae86yyk** [comment]
不过确实有问题，我打开软件cpu就100%，不是clash100%，而是其他软件cpu都升高了，关闭软件瞬间就好了。

**Comment by zhangasd1** [comment]
你在说你妈呢，不喜欢用别用，开发你妈逼，拿你妈逼翻墙，给你妈逼翻烂，你牛逼你伟大，我和你妈生你爸。哈哈哈哈，没屁眼的儿子
