### ISSUE TITLE
[Feature] 同时指定域名及域名后的路径

### ISSUE THREAD

**Issue by Meng-Sang** [clash-verge-rev/clash-verge-rev#1781]
### 功能描述 / Feature description

访问https://www.douyin.com/video/路径能直连
访问https://www.douyin.com/aweme/路径时能够请求代理

### 使用场景 / Use case

https://www.douyin.com/aweme/ 爬虫频繁请求会被封锁该路径请求，但是不影响其他请求使用，现在需要使用代理获取该请求

**Comment by yixiuge301** [comment]
你既然会写 爬虫 为什么还能问出这种问题

**Comment by Meng-Sang** [comment]
不好意思啊，对代理和爬虫这一块都不太精通，只是自己尝试时遇到的问题
