### ISSUE TITLE
[BUG] 订阅遵守配置文件中设定的 external-controller 对应的 secret

### ISSUE THREAD

**Issue by ipfans** [clash-verge-rev/clash-verge-rev#1783]
### 问题描述 / Describe the bug

订阅遵守配置文件中设定的 `external-controller` 对应的 `secret`，导致存在越权访问安全漏洞。

检测方法：https://mikewang000000.github.io/ClashScan/

### 复现步骤 / To Reproduce

1. 配置文件设置了 `external-controller` 和 `secret`。
2. WebUI 未使用默认的 `secret`，可以无密码访问接口。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.0

### 日志 / Log

...

**Comment by wonfen** [comment]
请在软件里设置：https://github.com/clash-verge-rev/clash-verge-rev/issues/1792

**Comment by ipfans** [comment]
@wonfen 无论是否支持软件中设置，遵循原有配置文件都是一个重要的原则吧

**Comment by wonfen** [comment]
> @wonfen 无论是否支持软件中设置，遵循原有配置文件都是一个重要的原则吧
不，很多机场都会把监听IP设置为0.0.0.0，导致暴露到公网。

而软件的设置只是监听本地访问，在同一个局域网下都能访问；不用过分本地进行的端口扫描。
个人人为，这种“安全隐患”不高于在电脑内安装国产软件；因为有先例tencent/360会扫描本机的clash代理软件

**Comment by ipfans** [comment]
@wonfen 这种主要是担心远程的泄露风险，换句话说使用浏览器就可以抓取你的代理信息和当前访问站点。

对于国产软件，开不开放端口并不是什么问题：我有足够的权限可以访问本地的文件系统，根本无需获取端口就可以获取信息，你在给予高级别权限的时候是需要知道潜在风险的。但现在的问题是可以在一个较低权限的基础上（比如网页的沙盒环境中）获取到高级别权限获取到的内容。

如果担心 extenal-controller 导致多余的开放，至少应该遵循密码设定，保证最基础的安全，而不是因为我觉得没有意义就选择丢弃最基础的安全防护

**Comment by wonfen** [comment]
> @wonfen 这种主要是担心远程的泄露风险，换句话说使用浏览器就可以抓取你的代理信息和当前访问站点。

那是使用本机浏览器访问本机端口才能获取；你可以试试在同一个局域网下使用另一台电脑扫描试试。

> 如果担心 extenal-controller 导致多余的开放，至少应该遵循密码设定，保证最基础的安全，而不是因为我觉得没有意义就选择丢弃最基础的安全防护

这个可以有。

**Comment by xishang0128** [comment]
> 抓取你的代理信息

这是不可能的,api仅展示节点名称等基础信息

**Comment by ipfans** [comment]
@xishang0128 但是不是只有泄露了具体的 ip、端口和密码才叫泄露信息...

**Comment by MikeWang000000** [comment]
ClashScan 作者在此处回复。

考虑到 Clash 订阅的特性，服务商下发的不安全配置，不能优先于本地软件的配置，这个是可以理解的。
现在的问题在于，本地的默认配置也不够安全。对于 clash-verge-rev，可行的方案有：
 - 默认随机端口+随机secret；
 - 禁止设置空secret，原本的空secret配置由随机密码替代。

---

对于订阅与本地配置冲突的解决方案也有：
 - 拉取订阅配置时，将 yaml 中 `external-controller` 与 `secret` 等配置修改为本地值后，再保存本地；
 - 应用配置时，一律遵守 yaml 配置文件配置。


以上是个人的一些建议。不过解决默认空密码的优先级应该高一些，无论如何，默认应设置一个随机的密码，这可以最简单的规避大多数的安全问题。

**Comment by zmaplex** [comment]
> > 抓取你的代理信息
> 
> 这是不可能的,api仅展示节点名称等基础信息

还暴露正在代理的网站域名

**Comment by yixiuge301** [comment]
逻辑不就应该这样吗，以应用的配置为准，覆盖订阅的配置。

不然你用 UI 的意义在哪里呢；还有一个，订阅配置是你可控的，不然一更新订阅，配置就可能改了

可以改进的地方，我觉得是，应用默认要设置一个随机的 secret。像 cfw 当时爆出漏洞后就默认设置了，这样可以确保安全，有兜底。
