### ISSUE TITLE
[BUG] 闲置时，clash verge自动退出

### ISSUE THREAD

**Issue by winstonleee** [clash-verge-rev/clash-verge-rev#1784]
### 问题描述 / Describe the bug

闲置时，clash verge自动退出

### 复现步骤 / To Reproduce

不进行翻墙活动，clash verge会自动关闭

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

09-28 22:57:45error
Start HTTP server error: listen tcp :10809: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
09-28 22:57:45error
Start HTTP server error: listen tcp :10809: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
09-28 22:57:45error
Start SOCKS server error: listen tcp :10808: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
09-28 22:57:45error
Start Mixed(http+socks) server error: listen tcp :7897: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
09-28 22:57:46info
Load MMDB file: C:\\Users\\furiosa\\AppData\\Roaming\\io.github.clash-verge-rev.clash-verge-rev/Country.mmdb

**Comment by DuaneDu** [comment]
可能是因为注册了esc键为全局退出热键导致的。

**Comment by DuaneDu** [comment]
2024-09-29 15:37:24 INFO - register hotkey Control+Q quit
2024-09-29 15:37:24 INFO - register hotkey Escape quit

**Comment by witt-bit** [comment]
在alpha版本，Linux环境下，也出现这个问题，但我不确定是不是没有网络通过,推出的时间不确定

**Comment by Iuleoo** [comment]
最新的Alpha版本，我 Windows 也会自动退出

**Comment by wzxmer** [comment]
> 最新的Alpha版本，我 Windows 也会自动退出

+1，我也会，包括电脑休眠后唤醒时，会发现自动退出了

**Comment by wonfen** [comment]
什么软件版本？

**Comment by JohnsonGond** [comment]
同样发现这个情况，clash的版本是2.0.0

**Comment by CMEPCBHG** [comment]
> 什么软件版本？

别什么版本了好吗？这个问题都多少人提过了？之前是卡住，现在直接自己退出了，但是任务栏图标还在，当我用鼠标指过去，它就消失，完全就是卡死+闪退。

**Comment by mxl2498** [comment]
+1我看奈飞呢  看着看着clash掉了 哈哈哈 2.0.0版本  系统Windows 10 企业版 LTSC 21H2

**Comment by FDUZS** [comment]
同样，最新稳定版 1.7.7
经常休眠唤醒后用着用着就连不上网（包括大陆网站也打不开）了，但是任务栏图标还显示
右键选择重启 app 后图标消失，此时重新启动 app 网络恢复

**Comment by Vincentqyw** [comment]
同样会遇到这个问题，具体是如果按下`ESC` 键后软件就会自动退出。版本信息如下：
![image](https://github.com/user-attachments/assets/6bae5fe4-1c35-474c-8188-58068885fd95)

**Comment by LevineWoo** [comment]
今天更新的版本仍然会有这个问题。

**Comment by wonfen** [comment]
已知问题，等底层库修复。
https://github.com/tauri-apps/tauri/issues/11120

**Comment by lionelqian** [comment]
在使用时也会被杀后台，而且不是概率事件

**Comment by Clexus** [comment]
我发现好像是莫名其妙监听了esc键，不按没事，按了就直接关掉，而且那个窗口里的esc键原功能也不会生效，只有切换一次窗口才行

**Comment by Webster96** [comment]
我也是，我问了几个人也是这样，在后台闪退

**Comment by Meteorsss** [comment]
metoo

**Comment by RingoCaviar** [comment]
win10 verge版本2.0.0  我觉得问题就跟上面人描述的一样 监听了esc，我目前有个解决办法 就是打开主界面之后点击最小化，不让他到托盘就不会自动退出了。
I hope this issue will be fixed soon.

**Comment by wonfen** [comment]
> win10 verge版本2.0.0 我觉得问题就跟上面人描述的一样 监听了esc，我目前有个解决办法 就是打开主界面之后点击最小化，不让他到托盘就不会自动退出了。 I hope this issue will be fixed soon.

已经修复了，下载最新版。

**Comment by lizilong1993** [comment]
v2.4.2版本仍然存在该bug

**Comment by toxic-19** [comment]
用着用着就自己退出了，一般都是等到无法访问，才发现自动退出了

<img width="2880" height="1659" alt="Image" src="https://github.com/user-attachments/assets/7e18a1e0-e2fa-42d6-a643-531f1a9772bd" />
