### ISSUE TITLE
[BUG] 重启系统后无法上网，并且关闭了”使用代理服务器“也没有用

### ISSUE THREAD

**Issue by crazyMessi** [clash-verge-rev/clash-verge-rev#1785]
### 问题描述 / Describe the bug

重启前没有关闭clash。重启系统后无法上网，并且关闭了”使用代理服务器“也没有用
![image](https://github.com/user-attachments/assets/5c902ebb-b4bd-4db3-8078-7b574d6cf5a3)

打开clash for window，并打开系统代理，依旧无法上网；
启用开机自启，重启系统，依旧无法上网
浏览器始终显示”检查代理服务器和防火墙“

### 复现步骤 / To Reproduce

使用"系统代理”模式，重启系统

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

window11

### 日志 / Log

02:07:30 INF [API] listening addr=127.0.0.1:2278
02:07:30 INF inbound create success inbound=mixed addr=127.0.0.1:7890 network=tcp
02:07:30 INF inbound create success inbound=mixed addr=127.0.0.1:7890 network=udp
02:08:13 INF [TCP] connected, doesn't match any rule lAddr=127.0.0.1:2580 rAddr=bl6pap004.storage.live.com:443 proxy=DIRECT
02:08:13 INF [TCP] connected, doesn't match any rule lAddr=127.0.0.1:2582 rAddr=bl6pap004.storage.live.com:443 proxy=DIRECT
02:08:17 WRN [TCP] dial failed error=dial tcp4 47.238.235.12:443: connectex: No connection could be made because the target machine actively refused it. proxy=DIRECT lAddr=127.0.0.1:2589 rAddr=www.51simer.com:443
02:08:17 WRN [TCP] dial failed error=dial tcp4 47.238.235.12:443: connectex: No connection could be made because the target machine actively refused it. proxy=DIRECT lAddr=127.0.0.1:2588 rAddr=www.51simer.com:443
02:08:18 INF [TCP] connected, doesn't match any rule lAddr=127.0.0.1:2605 rAddr=edge.microsoft.com:443 proxy=DIRECT
02:08:18 INF [TCP] connected, doesn't match any rule lAddr=127.0.0.1:2607 rAddr=edge.microsoft.com:443 proxy=DIRECT
02:08:19 WRN [TCP] dial failed error=dial tcp4 74.125.197.84:443: i/o timeout proxy=DIRECT lAddr=127.0.0.1:2584 rAddr=accounts.google.com:443
02:08:19 WRN [TCP] dial failed error=dial tcp4 47.238.235.12:443: connectex: No connection could be made because the target machine actively refused it. proxy=DIRECT lAddr=127.0.0.1:2599 rAddr=www.51simer.com:443
02:08:19 WRN [TCP] dial failed error=dial tcp4 47.238.235.12:443: connectex: No connection could be made because the target machine actively refused it. proxy=DIRECT lAddr=127.0.0.1:2597 rAddr=www.51simer.com:443
02:08:21 WRN [TCP] dial failed error=dial tcp4 142.251.211.238:443: i/o timeout proxy=DIRECT lAddr=127.0.0.1:2593 rAddr=clients2.google.com:443
02:08:22 WRN [TCP] dial failed error=dial tcp4 47.238.235.12:443: connectex: No connection could be made because the target machine actively refused it. proxy=DIRECT lAddr=127.0.0.1:2614 rAddr=www.51simer.com:443
02:08:22 WRN [TCP] dial failed error=dial tcp4 47.238.235.12:443: connectex: No connection could be made because the target machine actively refused it. proxy=DIRECT lAddr=127.0.0.1:2615 rAddr=www.51simer.com:443
02:08:24 WRN [TCP] dial failed error=dial tcp4 74.125.197.84:443: i/o timeout proxy=DIRECT lAddr=127.0.0.1:2610 rAddr=accounts.google.com:443
02:08:24 WRN [TCP] dial failed error=dial tcp4 47.238.235.12:443: connectex: No connection could be made because the target machine actively refused it. proxy=DIRECT lAddr=127.0.0.1:2624 rAddr=www.51simer.com:443
02:08:24 WRN [TCP] dial failed error=dial tcp4 47.238.235.12:443: connectex: No connection could be made because the target machine actively refused it. proxy=DIRECT lAddr=127.0.0.1:2625 rAddr=www.51simer.com:443
02:08:24 WRN [TCP] dial failed error=dial tcp4 142.251.33.74:443: i/o timeout proxy=DIRECT lAddr=127.0.0.1:2612 rAddr=content-autofill.googleapis.com:443

**Comment by wonfen** [comment]
重启电脑前，关闭系统代理了吗？

**Comment by crazyMessi** [comment]
> 重启电脑前，关闭系统代理了吗？
第一次没有关闭。联不上网后，试过先关闭系统代理后重启。

**Comment by crazyMessi** [comment]
破案了,和clash没有关系
