### ISSUE TITLE
[BUG] 全局配置中dns.enable=false只有每次编辑以后才生效

### ISSUE THREAD

**Issue by arbor-95** [clash-verge-rev/clash-verge-rev#1786]
### 问题描述 / Describe the bug

**目的：** 
使用局域网内的DNS服务器及本地hosts配置。
**问题：**
当通过“全局扩展配置”做以下配置，在软件重启后，导致局域网dns配置的域名解析和本地hosts配置的域名解析失效。
```
dns:
 enable: false
```

### 复现步骤 / To Reproduce

100%复现。
1、修改“全局扩展配置”
```
dns:
 enable: false
```
2、测试本地hosts配置的局域网内域名解析正常。测试局域网内DNS服务器域名解析正常。

3、重启软件

4、本地hosts配置的域名解析失败。局域网内DNS服务器域名解析失败。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 11

### 日志 / Log

无日志

**Comment by eronez** [comment]
Could you provide detailed configuration and logs?

Click this
![image](https://github.com/user-attachments/assets/f7c399fa-e8a8-47dd-8458-99386e80cacc)
when u have changed Global extend config, and when u have restarted clash verge rev.

And focus on TUN and DNS parts.

**Comment by arbor-95** [comment]
Thanks for your reply. These are screenshots of configuration files:

- Before change Global extend config
![image](https://github.com/user-attachments/assets/8289337e-2835-4d21-b44b-1e3eb6117651)

- After change Global extend config
![image](https://github.com/user-attachments/assets/863c4328-ad37-42b0-a3d5-398a9e18dbbb)

- After change Global extend config and **restart** clash verge rev
![image](https://github.com/user-attachments/assets/63cc2a62-3bbb-4299-b723-71d23218d4ef)

It seems that the configuration file is the same before and after restarting

**Comment by eronez** [comment]
Any log?
Clash verge rev version
Mihomo verison
