### ISSUE TITLE
[BUG] 代理请求机制需要优化

### ISSUE THREAD

**Issue by kenneth55555** [clash-verge-rev/clash-verge-rev#1788]
### 问题描述 / Describe the bug

下载一个4.6G的文件，中途clash日志普遍报错“unexpected status: 429 Too Many Requests”，即便这个代理任然可以用，但经常出现代理节点用着用着就失效了。麻烦优化代理请求机制，规避请求频繁问题

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

无

**Comment by wonfen** [comment]
代理请求是由下载客户端决定的。客户端发多少请求，节点/代理就要处理多少请求。

**Comment by kenneth55555** [comment]
了解了，要是有个限制网速功能，应该能完美解决，10m/s的下载速度，三两下就被拉黑了。win和路由器本身可以设置，但都不够便捷，某些路由器限速功能会破坏网络稳定性
