### ISSUE TITLE
[BUG] 在开启tun模式下设置dns enable: fasle 但是查看当前配置还是 enable: true

### ISSUE THREAD

**Issue by BBplux** [clash-verge-rev/clash-verge-rev#1789]
### 问题描述 / Describe the bug

在订阅文件中设置dns enable: fasle 但是查看当前配置还是 enable: true

### 复现步骤 / To Reproduce

新建本地配置文件设置dns 的enable为false，但查看配置文件还是 true

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10

### 日志 / Log

无

**Comment by lucienshawls** [comment]
开启TUN模式必定要开dns的吧，软件会默认覆盖这一条配置的

**Comment by eronez** [comment]
If tun is enabled, dns is needed to resolve domain.
This is NOT a bug, but a feature.
