### ISSUE TITLE
[BUG]启用clash后出现大量未知来源的上行流量

### ISSUE THREAD

**Issue by fatinghenji** [clash-verge-rev/clash-verge-rev#179]
### Describe the bug

启用clash后出现大量未知来源的上行流量

### To Reproduce

启用clash

### Platform

Windows

### System Version

22631.2861

### Software Version

1.4.5

### Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/37131177/f3467ebb-5d83-4f60-a17c-a4de327c1408)

**Comment by MystiPanda** [comment]
开启Tun了吗？看一下日志？

**Comment by MystiPanda** [comment]
看了下都是俄罗斯IP，是不是卡巴斯基在上传什么东西

**Comment by wonfen** [comment]
用这个软件看看是什么程序在发起对外链接:
https://www.nirsoft.net/utils/network_traffic_view.html

**Comment by fatinghenji** [comment]
> 用这个软件看看是什么程序在发起对外链接: https://www.nirsoft.net/utils/network_traffic_view.html

没找到这些链接？可能是我使用姿势不对？

**Comment by fatinghenji** [comment]
证实：该上传流量为卡巴斯基（
