### ISSUE TITLE
[Feature] 是否升级tauri V2并修复窗口管理器不一致问题

### ISSUE THREAD

**Issue by witt-bit** [clash-verge-rev/clash-verge-rev#1790]
### 功能描述 / Feature description

[tauri](https://github.com/tauri-apps/tauri/releases/tag/tauri-v2.0.0-rc.16)即将发布V2版本，其中《在 Windows / Linux / Mac下 Window Button 和标题栏表现不一致》的问题已经被修复,是否有计划升级适配

### 使用场景 / Use case

与其他软件操作不协调

**Comment by wonfen** [comment]
请测试alpha 2.0.0版本。已经升级适配tauri 2

**Comment by witt-bit** [comment]
> 请测试alpha 2.0.0版本。已经升级适配tauri 2

已经安装使用，窗口没有变化,跟1.X版本一样，我之前提过这个问题


https://github.com/clash-verge-rev/clash-verge-rev/issues/868

在tauri 2上https://github.com/EcoPasteHub/EcoPaste已经适配，没有任何问题

**Comment by wonfen** [comment]
> > 请测试alpha 2.0.0版本。已经升级适配tauri 2
> 
> 已经安装使用，窗口没有变化,跟1.X版本一样，我之前提过这个问题
> 
> #868
> 
> 在tauri 2上[https://github.com/EcoPasteHub/EcoPaste已经适配，没有任何问题](https://github.com/EcoPasteHub/EcoPaste%E5%B7%B2%E7%BB%8F%E9%80%82%E9%85%8D%EF%BC%8C%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E9%97%AE%E9%A2%98)

再麻烦截图看下，具体是哪里不协调有问题？

**Comment by 1111mp** [comment]
@wonfen 请问一下升级到tauri 2.0版本之后是不准备支持`linux arm64`系统吗？ 因为我看 alpha 中已经没有关于`linux arm64` 的下载入口文件，然后我也去看了一下github workflow的alpha的action的配置文件，好像也没有关于`linux arm64`的编译配置。

**Comment by witt-bit** [comment]
> > > 请测试alpha 2.0.0版本。已经升级适配tauri 2
> > 
> > 
> > 已经安装使用，窗口没有变化,跟1.X版本一样，我之前提过这个问题
> > #868
> > 在tauri 2上[EcoPasteHub/EcoPaste已经适配，没有任何问题](https://github.com/EcoPasteHub/EcoPaste%E5%B7%B2%E7%BB%8F%E9%80%82%E9%85%8D%EF%BC%8C%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E9%97%AE%E9%A2%98)
> 
> 再麻烦截图看下，具体是哪里不协调有问题？

GoogleChrome
![image](https://github.com/user-attachments/assets/c3f3ff74-24f1-43a1-a392-d2eb735f1421)

VsCode
![image](https://github.com/user-attachments/assets/5a044268-b3a1-46ff-9186-4c5804686500)

EcoPaste
也是基于tauri https://github.com/EcoPasteHub/EcoPaste
![image](https://github.com/user-attachments/assets/4571ed43-4d9e-4ab8-aa3a-c6d7efa2ab46)


Clash Verge
![image](https://github.com/user-attachments/assets/0a7e4667-2080-413d-95b9-755ace4ad987)

**Comment by 0xarch** [comment]
WM 相关不应该是在于 Clash Verge (& other Tauri-based) 没有正确报告自己是无边框窗口之类的问题吗，
这些截图展现的问题似乎是 Clash Verge 使用客户端自定义边框(CSD)而不是 KWin 提供的窗口边框(SSD)？或者 CSD 控制按钮和 KWin 提供的 SSD 控制按钮不在同一侧？

**Comment by witt-bit** [comment]
> WM 相关不应该是在于 Clash Verge (& other Tauri-based) 没有正确报告自己是无边框窗口之类的问题吗， 这些截图展现的问题似乎是 Clash Verge 使用客户端自定义边框(CSD)而不是 KWin 提供的窗口边框(SSD)？或者 CSD 控制按钮和 KWin 提供的 SSD 控制按钮不在同一侧？

tauri V2 已经可以支持了系统级别的窗口边框,不需要自己绘制了，建议还是采用tauri默认
