### ISSUE TITLE
[BUG] 白天菜单栏图标 显示错误

### ISSUE THREAD

**Issue by wenbingzhang** [clash-verge-rev/clash-verge-rev#1791]
### 问题描述 / Describe the bug

<img width="80" alt="image" src="https://github.com/user-attachments/assets/d6fc4460-74fc-4695-85f3-fdceb3514d85">

### 复现步骤 / To Reproduce

在macos启动app

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

12.7.6

### 日志 / Log

[2024-09-30-1312.log.zip](https://github.com/user-attachments/files/17184354/2024-09-30-1312.log.zip)

**Comment by wonfen** [comment]
你觉得应该显示什么呢？

**Comment by wenbingzhang** [comment]
> 你觉得应该显示什么呢？
这个是老版本显示的图标
<img width="84" alt="image" src="https://github.com/user-attachments/assets/67ee082f-ca22-4366-b873-b2c7fa97202c">

**Comment by wonfen** [comment]
我看了下其他软件都也都统一是白色的，没问题啊

**Comment by wenbingzhang** [comment]
浅色模式 应该是显示的黑色，深色模式下才显示白色
