### ISSUE TITLE
[Feature] 默认关闭对外接口

### ISSUE THREAD

**Issue by calibura** [clash-verge-rev/clash-verge-rev#1792]
### 功能描述 / Feature description

![image](https://github.com/user-attachments/assets/16237abf-de71-44dc-ba8a-9486fa00ff89)
 原因是
https://mikewang000000.github.io/ClashScan

### 使用场景 / Use case

默认没有需求不应该开启

**Comment by wonfen** [comment]
这个端口是用来控制clash api的，也就是UI和内核的交互；
未来meta内核会加入unixsocket；到时候就不需要暴露端口了
