### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by happytbs** [clash-verge-rev/clash-verge-rev#1798]
### 问题描述 / Describe the bug

订阅可以正常添加，连接也正常，就是代理的选择界面为空白
报错为：error sending request for url
(http:/127.0.0.1:9097/configs)

### 复现步骤 / To Reproduce

打开clashverge
更新订阅
报错
![image](https://github.com/user-attachments/assets/62bd4ee9-3098-4fc6-a567-e5d8c885c5b9)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11

### 日志 / Log

[2024-10-01-0826.log](https://github.com/user-attachments/files/17199008/2024-10-01-0826.log)

**Comment by CharlesSong** [comment]
请教下，咋解决的？

**Comment by wonfen** [comment]
> 请教下，咋解决的？

下载最新alpha2.0版

**Comment by avalon-plan** [comment]
Win10出现这个问题可以看下 MicrosoftEdgeWebView2RuntimeInstallerX64这个应用安装了没，百度单独下载一个就解决
