### ISSUE TITLE
MAC:  AMD64 processors with v3 microarchitecture support.

### ISSUE THREAD

**Issue by proxsi** [clash-verge-rev/clash-verge-rev#180]
### Describe the bug

Log shows:

This PROGRAM can only be run on AMD64 processors with v3 microarchitecture support.

### To Reproduce

Download the mac build, install on intel mac Core 2 Duo such as a macbook pro mid-2009, running 10.5.9 Catalina by DosDude workaround.

### Platform

MacOS

### System Version

10.15.7

### Software Version

10.15.7

### Log

This PROGRAM can only be run on AMD64 processors with v3 microarchitecture support.

### Additional Information

Here is a similar issue I found through a google search:

https://github.com/kubernetes/minikube/issues/15213

apparently it would need to compile with golang set as v2, and the build would work for me.

Well I am not sure I can build from source by myself, but I would be appreciating help witht this if you would make a mac build or help with making a build avaialble for older macs. 

Cheers

P.S:
Thanks for all contributing to this project, Its popularity makes it obviously succesful.

**Comment by MystiPanda** [comment]
This is an error from the meta core. You only need to download the corresponding version of the meta core and replace the clash-meta and clash-meta-alpha in the core directory.

https://github.com/MetaCubeX/mihomo/releases/tag/v1.17.0

You need to download this 
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/152463842/c4afc19b-6be8-44f7-a626-a50fbc2fae1d)

**Comment by wonfen** [comment]
你的系统版本也有点老，升级到11试试。

**Comment by proxsi** [comment]
The core is indeed the problem, thanks for shedding the light on the true issue.
 And yes my macbook is indeed old and unfortunately can't be updated past 10.15.7 ( that I know of)

Apparently I would need that specific meta core, so called "Compatible" where GOAMD64=V1, that is stil being made for Windows and Linux, but no longer for Macs (darwin), where GOAMD is compiled with the flag GOAMD64=V3  and exclusively V3 and prompting the clash-verge-rev error:

"This PROGRAM can only be run on AMD64 processors with v3 microarchitecture support."

 My next step is to  try to compile the mihomo core from source with make set to GOAMD64=v1 instead of v3

**make darwin-amd64-compatible**

should trigger:
	GOARCH=amd64 GOOS=darwin GOAMD64=v1 

That's where I am.  "Make" got stuck downloading a required go package "blake3". I need to dig into go and source that package to github instead of http://lukechampine.com/ which is down or possibly now exclusively on github.

Thanks all

**Comment by MystiPanda** [comment]
As far as I know `mihomo-darwin-amd64-cgo-v1.17.0.gz`  is compiled using `GOAMD64=v1`, you can download this directly

**Comment by proxsi** [comment]
Thanks for your comment.
Apparently the mihomo-darwin-amd64-cgo-v1.17.0.gz is a GOAMD64=v3, because it triggered the error in clash-verge-rev:
"This PROGRAM can only be run on AMD64 processors with v3 microarchitecture support." 



The good news is I got it to work with my custom core. Both CGO and not-CGO work. They are quite big ( 30mb each). I don't remember what flag during compile time can reduce the core to about 10 mb.

So here is what I did:

in Mihomo1.17 source:
I changed in "Makefile" CGO_ENABLED to 1 so it looks like below (CGO is not necessary though)


GOBUILD=CGO_ENABLED=1 go build -tags with_gvisor -trimpath -ldflags '-X "github.com/metacubex/mihomo/constant.Version=$(VERSION)" \
		-X "github.com/metacubex/mihomo/constant.BuildTime=$(BUILDTIME)" \
		-w -s -buildid='

then executed:

**make darwin-amd64-compatible**


where darwin-amd64-compatible is defined as such in Makefile:
darwin-amd64-compatible:
	GOARCH=amd64 GOOS=darwin GOAMD64=v1 $(GOBUILD) -o $(BINDIR)/$(NAME)-$@

The GOAMD64=v1  is what makes it work on my older mac.


Then my Clash Verge Rev works like a charm.
Thanks again!

**Comment by proxsi** [comment]
[mihomo1-17-darwin-amd64-compatible-CGO.zip](https://github.com/clash-verge-rev/clash-verge-rev/files/13766763/mihomo1-17-darwin-amd64-compatible-CGO.zip)

**Comment by MystiPanda** [comment]
I don't know if you just downloaded the wrong file, Since I saw someone in the telegram group download cgo version to solve the same problem, so I think it was compiled using v1 flag. If it's convenient, I suggest you try this file again, Because the Update of clash verge rev overwrites the old core, This means that you need to manually recompile the core for each version, and if the cgo version is compatible, I'll use it as the default core.

**Comment by MystiPanda** [comment]
Or you can submit issue to the mihomo team and have them compile a compatible version

**Comment by proxsi** [comment]
Yes it's the next step isn't it.
Based on the success fixing Clash Verge Rev,  I was trying to also fix ClashX_Meta which also displayed an issue on my older mac.
Based on your feedback that it was a core issue for Clash Verge Reg,  I changed ClashX_Meta to the same V1 core, but it hangs the interface.
Maybe they don't use the Mihomo core at ClashX_Meta. 
So before I contact Mihomo, I wanted to know what caused all these apps like Verge and ClashX_Meta to use non-compatible cores.
But maybe I will only get more clues after contacting Mihomo, as you suggested.

**Comment by proxsi** [comment]
As an update, I have tried the cores released for mihomo 1.18  for darwin, none of them are compatible with older macs AMDv1

You are right I have to compile a new core at every release to support my old mac Darwin. No way around this.

Here is the Mihomo 1.18 I compiled and built as compatible:
[mihomo-1.18-darwin-compatible.zip](https://github.com/clash-verge-rev/clash-verge-rev/files/13910258/mihomo-1.18-darwin-compatible.zip)

Thanks for clash-verge-rev 1.4.7

**Comment by MystiPanda** [comment]
You can submit an issue to the mihomo repository and request that they continue to provide compatible versions.
