### ISSUE TITLE
[Feature] 隐藏托盘图标

### ISSUE THREAD

**Issue by 704009905** [clash-verge-rev/clash-verge-rev#1800]
### 功能描述 / Feature description

添加隐藏托盘图标的功能

### 使用场景 / Use case

1. 保持干净的任务栏, 即使托盘图标展开菜单也不显示图标
2. 配置Clash Verge完成之后无需再次打开, 也避免误触或者未授权的操作
3. 一些场景展示时避免出现Clash Verge(虽然目前可以修改托盘图标)

**Comment by wonfen** [comment]
之前讨论过，后面觉得不太好，不符合操作逻辑和常规的直觉。没有想到更好的解决方法，暂时搁置

**Comment by realpg** [comment]
> 之前讨论过，后面觉得不太好，不符合操作逻辑和常规的直觉。没有想到更好的解决方法，暂时搁置

很多桌面应用程序有一种功能, 叫"老板键", 可以参考一下

用热键快速隐藏一切痕迹
