### ISSUE TITLE
[BUG]  ss2022连接问题

### ISSUE THREAD

**Issue by jinbasex** [clash-verge-rev/clash-verge-rev#1803]
### 问题描述 / Describe the bug

同一网路下的两台电脑 都是win10 19045.2673 出现了一台能连接ss2022 一台不能的情况
可以连接的机器  使用clash verge rev 版本是 1.6.4 meta内核是1.18.5
另一台机器之前都是用软路由  然后今天使用 clash verge rev1.7.7 内核1.18.7 却无法连接所有的ss2022协议
其他协议  trojan  普通的ss 是正常的 vless 也会时不时能连接 但vless 可能是落地性能不好
但可以明确的是  软路由和另一台机器能正常ss2022 只有这台机器不行

已经尝试过降级 低版本的软件 和 手动更换更低的内核 都无法连接

### 复现步骤 / To Reproduce

直接安装 1.7.7版本后出现上述现象

尝试降级应用和内核均无果

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10 19045.2673

### 日志 / Log

2024-10-02 16:35:22 INFO - reset proxy to the original proxy
2024-10-02 16:35:22 INFO - reset proxy to the original proxy

**Comment by wonfen** [comment]
检查网络和节点问题，verge只是GUI，不处理协议和连接
