### ISSUE TITLE
[BUG] 代理监听失败，设置了端口，也开启了局域网连接，但始终连接失败

### ISSUE THREAD

**Issue by Seifon** [clash-verge-rev/clash-verge-rev#1808]
### 问题描述 / Describe the bug

设置了代理，但是访问github还是提示：Proxy CONNECT aborted
windows和Mac Os都存在这样的问题。使用ClashX就没有这个问题，望修复

![图片](https://github.com/user-attachments/assets/eafaefd5-a096-4524-b047-f195aa79f125)
![图片](https://github.com/user-attachments/assets/d569ceb4-0661-4d28-a654-02492fe9756f)
![图片](https://github.com/user-attachments/assets/15448f25-13e6-49bb-b3db-1a0a46906a70)
![图片](https://github.com/user-attachments/assets/b32afc5c-18c3-4f33-88d4-3ce9fb97b5f9)
![图片](https://github.com/user-attachments/assets/329e5113-70c1-45f9-af43-5f2af4f951fa)

### 复现步骤 / To Reproduce

![图片](https://github.com/user-attachments/assets/eafaefd5-a096-4524-b047-f195aa79f125)
![图片](https://github.com/user-attachments/assets/d569ceb4-0661-4d28-a654-02492fe9756f)
![图片](https://github.com/user-attachments/assets/15448f25-13e6-49bb-b3db-1a0a46906a70)
![图片](https://github.com/user-attachments/assets/80dfc0c4-cd21-40ec-ad6f-84e4bb13e224)
![图片](https://github.com/user-attachments/assets/329e5113-70c1-45f9-af43-5f2af4f951fa)

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15

### 日志 / Log
![图片](https://github.com/user-attachments/assets/b32afc5c-18c3-4f33-88d4-3ce9fb97b5f9)

**Comment by 12471220** [comment]
是把MacOS作为代理服务端使用吗?
