### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by hjhu** [clash-verge-rev/clash-verge-rev#1809]
### 问题描述 / Describe the bug

我退出verge之后就没有网络了

### 复现步骤 / To Reproduce

打开verge网络连接正常
退出verge 所用网络连接全部断开
重启无法解决

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

13.6.9

### 日志 / Log

none

**Comment by luzihao1234** [comment]
你是不是在系统设置代理了

**Comment by wonfen** [comment]
系统代理关了吗？
