### ISSUE TITLE
mac版本的 安装成功之后，填写配置，代理不显示节点，貌似无法切换到meta核心，如何解决？[BUG]

### ISSUE THREAD

**Issue by moneyfly1** [clash-verge-rev/clash-verge-rev#181]
### Describe the bug

mac版本的 安装成功之后，填写配置，代理不显示节点，貌似无法切换到meta核心，如何解决？

### To Reproduce

mac版本的 安装成功之后，填写配置，代理不显示节点，貌似无法切换到meta核心，如何解决？

### Platform

MacOS

### System Version

12

### Software Version

1.4.5

### Log

mac版本的 安装成功之后，填写配置，代理不显示节点，貌似无法切换到meta核心，如何解决？

### Additional Information

mac版本的 安装成功之后，填写配置，代理不显示节点，貌似无法切换到meta核心，如何解决？

**Comment by MystiPanda** [comment]
设置，内核，手动切换或重启内核，不行的话看一下日志。

**Comment by jianmim** [comment]
同样碰到这个问题，现在只能开启TUN模式使用没有问题

**Comment by wonfen** [comment]
下载最新版试试？

**Comment by wonfen** [comment]
无进一步反馈，关闭。
