### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by proxsi** [clash-verge-rev/clash-verge-rev#1811]
### 问题描述 / Describe the bug

There is a duplicate Clash Verge Rev Logo superimposed on the Apple Logo of the top menu bar. Therefore I can't open Apple Menu, it opens the Clash Verge Rev Menu instead.

### 复现步骤 / To Reproduce

Launch Clash Verge Rev.
Look into the menu bar.
There is a duplicate Clash Verge Rev Logo superimposed on the Apple Logo. Therefore I can't open Apple Menu, it opens the Clash Verge Rev Menu instead.

Look at the top left of the picture describing the problem:
![Clash Verge Rev - Duplicate Menu Bar Logo](https://github.com/user-attachments/assets/d44b0f21-5545-4e8e-887b-ea3d9ffaa6f2)

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.0 

### 日志 / Log

N/A

**Comment by wonfen** [comment]
看文档
