### ISSUE TITLE
[BUG] MacOS  dock栏不显示Clash的图标

### ISSUE THREAD

**Issue by wxc1216** [clash-verge-rev/clash-verge-rev#1812]
### 功能描述 / Feature description

[Feature] MacOS  dock栏不显示Clash的图标

### 使用场景 / Use case

[Feature] MacOS  dock栏不显示Clash的图标

**Comment by wonfen** [comment]
作为工具软件，没有显示的必要，有意隐去的（而且显示的话还有bug）
