### ISSUE TITLE
[BUG] 2.0 版本导致 MacBook 的 command + Q 快捷键失效

### ISSUE THREAD

**Issue by luzihao1234** [clash-verge-rev/clash-verge-rev#1814]
### 问题描述 / Describe the bug

Mac 电脑的退出程序快捷键 Command + Q 失效

### 复现步骤 / To Reproduce

我是MacBook Air M3，2.0版本，用着用着就会出现这种情况

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.0.1 (24A348)

### 日志 / Log

暂无

**Comment by shuaiyyy** [comment]
同样的问题，因此用回1.7.7了

**Comment by dalaogo** [comment]
我也遇到了同样的问题

**Comment by wxc1216** [comment]
我只有这个版本可以用Command + Q，此前版本都不能用

**Comment by luzihao1234** [comment]
> 我只有这个版本可以用Command + Q，此前版本都不能用

我的意思是2.0版本可能导致全局Command + Q失效，不光是这个软件里面

**Comment by oldwinter** [comment]
同样发现此问题。我定位了好久，你咋发现是因为clash导致的cmd q快捷键失效的。

**Comment by luzihao1234** [comment]
> 同样发现此问题。我定位了好久，你咋发现是因为clash导致的cmd q快捷键失效的。

挨个关运行的软件，关一个试一下，关完clash就好了

**Comment by KevinXC5** [comment]
刚打开的时候不会导致cmd+q失效，打开窗口后不知道点了哪个菜单后就会失效了

**Comment by rjwang1982** [comment]
15.1 Beta版(24B5055e) ,verge v2.2.0，同样就此问题，⌘ Q 全局失效，退出 verge 就好了。

**Comment by Link-blb** [comment]
相同的问题🙋

**Comment by luzihao1234** [comment]
> 我也遇上了,verge是最新的2.0,截止2024.10.15,command+q失灵,我还以为是macOS系统的问题,系统版本是14.7,M2芯片.

开源主已经退回到1.77了，你也退吧

**Comment by Link-blb** [comment]
> 试试ctrl+q呢？ 具体什么软件关不掉？

全局失效，该快捷键影响操作习惯，已经版本回退到1.7.7

**Comment by wonfen** [comment]
> > 试试ctrl+q呢？ 具体什么软件关不掉？
> 
> 全局失效，该快捷键影响操作习惯，已经版本回退到1.7.7

之前的2.0alpha版本是有这个问题，但后面修复了。

**Comment by zh217** [comment]
@wonfen f7b1da75576e26ff7566f9dcdc58242da2b7e9bb版本并未修复

打开面板，再关掉，多试几次，command-q就失效了
并不是打开软件立刻就失效的
失效之后只要打开面板然后最小化而不是关闭则command-q又可以工作了

**Comment by lovelock** [comment]
我也遇到这个问题，刚开始是发现Firefox无法关闭标签页（CMD+W），差点就把它refresh了，还好搜了一下，关了果然就好了，而且它还在疯狂吃CPU。

**Comment by tiannh7** [comment]
我最近也频发这个问题，才发现是clash导致的

**Comment by icecliffs** [comment]
same issue，很不理解为什么会占用到 command + w 和 command + q，解决方法就是把软件关了就好了

**Comment by yultang** [comment]
I also encounter the same problem.

MacOS version: 15.7 (24G222)

Hardware: Macbook Air M4

ClashVerge version: 2.4.2

**Comment by OldDream** [comment]
关闭全局热键就好了

**Comment by jiweiyeah** [comment]
把 clash verge 设置里面全局热键关闭就可以了
