### ISSUE TITLE
[Question]订阅更新是用系统代理还是内核代理阿？

### ISSUE THREAD

**Issue by Rimesal** [clash-verge-rev/clash-verge-rev#1819]
<img width="316" alt="2024-10-7 15-2-13" src="https://github.com/user-attachments/assets/cb622376-3132-4973-ad35-42f0a63299ae">

请问这里是选择系统代理还是内核代理阿？小白不太懂两者区别，能讲一下吗（不过默认好像是都不用选？）

**Comment by HozumiMoa** [comment]
能直连就不需要开代理更新

**Comment by wonfen** [comment]
更新正常的时候无须选择。
