### ISSUE TITLE
[BUG]Monterey 12.7.2 系统代理失败

### ISSUE THREAD

**Issue by cheneyxx** [clash-verge-rev/clash-verge-rev#182]
### Describe the bug

打开系统代理的时候 Mac 系统设置网络代理选项里不会自动勾选网页代理那些选项

### To Reproduce

卸载重装没用 换了 clashx.meta 正常

### Platform

MacOS

### System Version

Monterey 12.7.2

### Software Version

1.4.5

**Comment by wonfen** [comment]
无进一步反馈，关闭。
