### ISSUE TITLE
[BUG] IPV6节点不支持

### ISSUE THREAD

**Issue by assassinliujie** [clash-verge-rev/clash-verge-rev#1820]
### 问题描述 / Describe the bug

同一个订阅链接，同一个节点，在V2RAYN上可以正常使用IPV6节点，但是在clash上就是error，调试发现是因为非域名解析的ipv6地址配置文件里会自带一个[]，但是clash在解析ipv6地址的时候会在外面再加一个[]，导致最后访问的地址是[[]]建议统一配置文件

### 复现步骤 / To Reproduce

导入包含ipv6地址的通用的配置文件，即可发现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 11

### 日志 / Log

10-08 09:06:13warning
[TCP] dial GLOBAL 127.0.0.1:49517 --> incoming.telemetry.mozilla.org:443 error: [[2400:6180:0:d0::d32:e001]]:5872 connect error: address [[2400:0000]]:5872: missing port in address

**Comment by Cptzzzzz** [comment]
请问你解决了这个问题吗，我也遇到了ipv6节点ERROR的情况

**Comment by p1aintiff** [comment]
> 请问你解决了这个问题吗，我也遇到了ipv6节点ERROR的情况

手动改配置文件的节点信息
在proxies字段里
