### ISSUE TITLE
[BUG] 添加规则时出现浏览器的搜索建议

### ISSUE THREAD

**Issue by bellongyan** [clash-verge-rev/clash-verge-rev#1821]
### 问题描述 / Describe the bug

添加规则页面出现浏览器的搜索建议
<img width="450" alt="PixPin_2024-10-08_09-01-31" src="https://github.com/user-attachments/assets/aaa920ce-22e8-40c4-b83f-cd89a058c8a1">

### 复现步骤 / To Reproduce

1. 在订阅页面选中订阅文件
2. 对订阅文件的规则进行编辑
3. 在输入框进行输入时出现搜索建议（***不能稳定复现***）

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 专业版 22H2 19045.4957

### 日志 / Log

无

**Comment by wonfen** [comment]
正常的，本啦就是webview的前端框架；等以后有空研究下能否屏蔽吧。

**Comment by bellongyan** [comment]
> 正常的，本来就是webview的前端框架；等以后有空研究下能否屏蔽吧。

我看[Disable Windows WebView autocompleting text fields "Saved data" #7120](https://github.com/tauri-apps/tauri/discussions/7120)中提到给`<input>属性`添加`autocomplete="off"`就可以关闭，查到React[`<input>`](https://zh-hans.react.dev/reference/react-dom/components/input)组件有`autocomplete`属性，但是我对前端的了解不多，没有找到在哪里修改
