### ISSUE TITLE
[Feature]  在安装包中添加geo和country文件

### ISSUE THREAD

**Issue by sanzo-mlgb** [clash-verge-rev/clash-verge-rev#1824]
### 功能描述 / Feature description

如题，在初次使用的时候，导入订阅链接后会在线下载geo和country文件，但是在白名单地区会因为无法下载导致订阅导入失败，需要从其他地方下载/复制这些文件才能导入。此问题出现在windows和linux版上

### 使用场景 / Use case

白名单地区无法下载geo和country文件导致订阅无法导入

**Comment by wonfen** [comment]
本来就会包括以下文件。

const resolveMmdb = () =>
  resolveResource({
    file: "Country.mmdb",
    downloadURL: `https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb`,
  });
const resolveGeosite = () =>
  resolveResource({
    file: "geosite.dat",
    downloadURL: `https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat`,
  });
const resolveGeoIP = () =>
  resolveResource({
    file: "geoip.dat",
    downloadURL: `https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat`,
  });
