### ISSUE TITLE
[BUG] provider 下扩展脚本无法获取到具体代理

### ISSUE THREAD

**Issue by lppsuixn** [clash-verge-rev/clash-verge-rev#1825]
### 问题描述 / Describe the bug

扩展脚本给到的config，不是拉取节点后的。无法获取到proxies.

### 复现步骤 / To Reproduce

扩展脚本给到的config，不是拉取节点后的。无法获取到proxies.

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

扩展脚本给到的config，不是拉取节点后的。无法获取到proxies.

**Comment by wonfen** [comment]
听不懂你在说什么。
