### ISSUE TITLE
[BUG] 关闭系统代理时网速很慢

### ISSUE THREAD

**Issue by Dasha484** [clash-verge-rev/clash-verge-rev#1826]
### 问题描述 / Describe the bug

为什么我开启系统代理时网速正常，关闭系统代理时网速会很慢，但是当我退出clash verge时网速又恢复正常？

### 复现步骤 / To Reproduce

打开系统代理，网速正常；关闭系统代理，网速变慢；退出clash，网速正常

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows

### 日志 / Log

10-08 20:01:09info
[TCP] 127.0.0.1:54993 --> nav-edge.smartscreen.microsoft.com:443 match DomainSuffix(microsoft.com) using DIRECT
10-08 20:01:10info
[TCP] 127.0.0.1:54997 --> avatars.githubusercontent.com:443 match DomainKeyword(github) using 三分机场[🇯🇵日本-ipv6入口-03]
10-08 20:01:10info
[TCP] 127.0.0.1:54995 --> github.githubassets.com:443 match DomainKeyword(github) using 三分机场[🇯🇵日本-ipv6入口-03]
10-08 20:01:10info
[TCP] 127.0.0.1:54999 --> cn.bing.com:443 match DomainSuffix(bing.com) using 三分机场[🇯🇵日本-ipv6入口-03]
10-08 20:01:11info
[TCP] 127.0.0.1:55006 --> edge.microsoft.com:443 match DomainSuffix(microsoft.com) using DIRECT
10-08 20:01:11info
[TCP] 127.0.0.1:55009 --> collector.github.com:443 match DomainKeyword(github) using 三分机场[🇯🇵日本-ipv6入口-03]

**Comment by wonfen** [comment]
检查下系统代理的设置是否被其他软件修改了？

**Comment by Dasha484** [comment]
> 检查下系统代理的设置是否被其他软件修改了？

可以说一下具体怎么操作吗，或者怎么恢复？

**Comment by wonfen** [comment]
使用问题请自行研究
