### ISSUE TITLE
[BUG] 开机启动时报错-无法找到入口

### ISSUE THREAD

**Issue by liuzhuoyan0210** [clash-verge-rev/clash-verge-rev#1828]
### 问题描述 / Describe the bug

开机自启时，大概率出现
![图片](https://github.com/user-attachments/assets/17267350-766e-4036-8a80-5c641ef1f134)

### 复现步骤 / To Reproduce

启用开机自启，系统代理，静默启动，IPV6，重新启动大概率出现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

19045.4957

### 日志 / Log

日志未生成

**Comment by wonfen** [comment]
无法复现，什么版本？什么环境？
盲猜是操作系统问题。

**Comment by Lzy0986** [comment]
重装软件
