### ISSUE TITLE
[BUG] kali无法加载代理

### ISSUE THREAD

**Issue by dadvlingd** [clash-verge-rev/clash-verge-rev#1829]
### 问题描述 / Describe the bug

kali导入订阅后，无法在代理里面找到节点
安装命令如下
udo dpkg -i Clash.Verge_2.0.0_amd64.deb

### 复现步骤 / To Reproduce

1、导入订阅
<img width="699" alt="image" src="https://github.com/user-attachments/assets/b2c22273-9dde-4944-b526-ff2dc5a934fa">
2、代理为空
<img width="669" alt="image" src="https://github.com/user-attachments/assets/82b59dd4-8de0-4a45-8697-eb96179bc686">
3、编辑节点显示已经加载

<img width="709" alt="image" src="https://github.com/user-attachments/assets/82c9c982-08e1-483d-b300-dbd3c61f80d4">

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

kali2024

### 日志 / Log

日志被清除了

**Comment by wonfen** [comment]
内核启动起来了吗？

**Comment by dadvlingd** [comment]
<img width="518" alt="image" src="https://github.com/user-attachments/assets/696ca66d-008e-4d7c-906b-b17d11c21b5c">
这个去哪里手工下载

**Comment by wonfen** [comment]
geoip是内置的，是不是配置文件定义了另一个不存在的geoip导致软件需要去下载？换个机场试试。

**Comment by dadvlingd** [comment]
两个机场都是这个问题

**Comment by gexin1** [comment]
我的也是这样 突然就不显示了 更换到`v2.0.0`版本还是不显示

**Comment by gexin1** [comment]
打开开发者工具报错
![image](https://github.com/user-attachments/assets/bbae84e4-f815-467d-8ed2-66869d80c715)
