### ISSUE TITLE
[Feature] 是否能增加支持鸿蒙next版本

### ISSUE THREAD

**Issue by 1426860561** [clash-verge-rev/clash-verge-rev#1832]
### 功能描述 / Feature description

请求增加鸿蒙next版本

### 使用场景 / Use case

鸿蒙next

**Comment by jasonOzq** [comment]
you pas yige shabi

**Comment by jasonOzq** [comment]
> 对于近日有人提议开发鸿蒙Next版本的行为，我们予以强烈谴责。这不仅是对技术创新的无知挑战，更是对全球科技秩序的公然挑衅。鸿蒙生态自诞生以来，所追求的并非普惠的技术进步，而是通过垄断和封闭性体系，强化数字鸿沟，削弱用户的自主权，甚至威胁信息安全。
> 
> 任何试图推动这一体系进一步演化的举措，实质上是将开发者和用户引向一个封闭、无透明度、且难以逃脱的数字陷阱。此种行为，严重背离了科技发展的初衷，不仅扼杀了技术创新，更侵犯了人类基本自由与数字权利。
> 
> 我们强烈呼吁全球开发者共同抵制这一荒谬提议，共同捍卫开放、公平和透明的数字生态，坚决对抗任何形式的技术霸权和数字暴政。任何对鸿蒙Next的支持，都是对自由社会和人类尊严的公然蔑视，甚至涉嫌构成对人类数字权利的侵犯，这在道德层面是不可饶恕的，在历史上也将为世人所不齿。

you pas yige shabi

**Comment by ybybwdwd** [comment]
> 对于近日有人提议开发鸿蒙Next版本的行为，我们予以强烈谴责。这不仅是对技术创新的无知挑战，更是对全球科技秩序的公然挑衅。鸿蒙生态自诞生以来，所追求的并非普惠的技术进步，而是通过垄断和封闭性体系，强化数字鸿沟，削弱用户的自主权，甚至威胁信息安全。
> 
> 任何试图推动这一体系进一步演化的举措，实质上是将开发者和用户引向一个封闭、无透明度、且难以逃脱的数字陷阱。此种行为，严重背离了科技发展的初衷，不仅扼杀了技术创新，更侵犯了人类基本自由与数字权利。
> 
> 我们强烈呼吁全球开发者共同抵制这一荒谬提议，共同捍卫开放、公平和透明的数字生态，坚决对抗任何形式的技术霸权和数字暴政。任何对鸿蒙Next的支持，都是对自由社会和人类尊严的公然蔑视，甚至涉嫌构成对人类数字权利的侵犯，这在道德层面是不可饶恕的，在历史上也将为世人所不齿。

建议也抵制下ios

**Comment by joeyluan** [comment]
> 对于近日有人提议开发鸿蒙Next版本的行为，我们予以强烈谴责。这不仅是对技术创新的无知挑战，更是对全球科技秩序的公然挑衅。鸿蒙生态自诞生以来，所追求的并非普惠的技术进步，而是通过垄断和封闭性体系，强化数字鸿沟，削弱用户的自主权，甚至威胁信息安全。
> 
> 任何试图推动这一体系进一步演化的举措，实质上是将开发者和用户引向一个封闭、无透明度、且难以逃脱的数字陷阱。此种行为，严重背离了科技发展的初衷，不仅扼杀了技术创新，更侵犯了人类基本自由与数字权利。
> 
> 我们强烈呼吁全球开发者共同抵制这一荒谬提议，共同捍卫开放、公平和透明的数字生态，坚决对抗任何形式的技术霸权和数字暴政。任何对鸿蒙Next的支持，都是对自由社会和人类尊严的公然蔑视，甚至涉嫌构成对人类数字权利的侵犯，这在道德层面是不可饶恕的，在历史上也将为世人所不齿。

感觉这义正言辞的态度，和国内的小粉红一样的恶心，和他们的屁股一样的歪。你相关先呼吁抨击谷歌的安卓和GMS，一开始打着开源的幌子来扩展生态，做大做强了就限制这个限制那个，我想如果不是谷歌，华为根本不会做这个鸿蒙。谷歌的行为才是对全球科技秩序的公然挑战，这才叫垄断，懂不？

**Comment by halo2829** [comment]
> > 对于近日有人提议开发鸿蒙Next版本的行为，我们予以强烈谴责。这不仅是对技术创新的无知挑战，更是对全球科技秩序的公然挑衅。鸿蒙生态自诞生以来，所追求的并非普惠的技术进步，而是通过垄断和封闭性体系，强化数字鸿沟，削弱用户的自主权，甚至威胁信息安全。
> > 任何试图推动这一体系进一步演化的举措，实质上是将开发者和用户引向一个封闭、无透明度、且难以逃脱的数字陷阱。此种行为，严重背离了科技发展的初衷，不仅扼杀了技术创新，更侵犯了人类基本自由与数字权利。
> > 我们强烈呼吁全球开发者共同抵制这一荒谬提议，共同捍卫开放、公平和透明的数字生态，坚决对抗任何形式的技术霸权和数字暴政。任何对鸿蒙Next的支持，都是对自由社会和人类尊严的公然蔑视，甚至涉嫌构成对人类数字权利的侵犯，这在道德层面是不可饶恕的，在历史上也将为世人所不齿。
> 
> 感觉这义正言辞的态度，和国内的小粉红一样的恶心，和他们的屁股一样的歪。你相关先呼吁抨击谷歌的安卓和GMS，一开始打着开源的幌子来扩展生态，做大做强了就限制这个限制那个，我想如果不是谷歌，华为根本不会做这个鸿蒙。谷歌的行为才是对全球科技秩序的公然挑战，这才叫垄断，懂不？

不知道谁破防了在幽默点踩（

**Comment by Andy-Landers** [comment]
> > 对于近日有人提议开发鸿蒙Next版本的行为，我们予以强烈谴责。这不仅是对技术创新的无知挑战，更是对全球科技秩序的公然挑衅。鸿蒙生态自诞生以来，所追求的并非普惠的技术进步，而是通过垄断和封闭性体系，强化数字鸿沟，削弱用户的自主权，甚至威胁信息安全。
> > 任何试图推动这一体系进一步演化的举措，实质上是将开发者和用户引向一个封闭、无透明度、且难以逃脱的数字陷阱。此种行为，严重背离了科技发展的初衷，不仅扼杀了技术创新，更侵犯了人类基本自由与数字权利。
> > 我们强烈呼吁全球开发者共同抵制这一荒谬提议，共同捍卫开放、公平和透明的数字生态，坚决对抗任何形式的技术霸权和数字暴政。任何对鸿蒙Next的支持，都是对自由社会和人类尊严的公然蔑视，甚至涉嫌构成对人类数字权利的侵犯，这在道德层面是不可饶恕的，在历史上也将为世人所不齿。
> 
> 建议也抵制下ios

Clash Verge rev似乎也并没有提供iOS版本客户端吧，不知道你想要强调什么🤣

**Comment by ybybwdwd** [comment]
> > > 对于近日有人提议开发鸿蒙Next版本的行为，我们予以强烈谴责。这不仅是对技术创新的无知挑战，更是对全球科技秩序的公然挑衅。鸿蒙生态自诞生以来，所追求的并非普惠的技术进步，而是通过垄断和封闭性体系，强化数字鸿沟，削弱用户的自主权，甚至威胁信息安全。
> > > 任何试图推动这一体系进一步演化的举措，实质上是将开发者和用户引向一个封闭、无透明度、且难以逃脱的数字陷阱。此种行为，严重背离了科技发展的初衷，不仅扼杀了技术创新，更侵犯了人类基本自由与数字权利。
> > > 我们强烈呼吁全球开发者共同抵制这一荒谬提议，共同捍卫开放、公平和透明的数字生态，坚决对抗任何形式的技术霸权和数字暴政。任何对鸿蒙Next的支持，都是对自由社会和人类尊严的公然蔑视，甚至涉嫌构成对人类数字权利的侵犯，这在道德层面是不可饶恕的，在历史上也将为世人所不齿。
> > 
> > 
> > 建议也抵制下ios
> 
> Clash Verge rev似乎也并没有提供iOS版本客户端吧，不知道你想要强调什么🤣

`任何对鸿蒙Next的支持` 是看不到这句话吗

**Comment by Remonli** [comment]
让别人实名给你开发梯子软件，怕不是有什么大病吧？

**Comment by QinSisuo** [comment]
用鸿蒙的爱国者能不能别用GitHub别用代理软件啊🤓

**Comment by xiaoduozhou** [comment]
意思就是你恨国咯， 满脑子政治的蛀虫。 说一个让你破防的消息，clash鸿蒙版 已经有人开发了， git上下载下来侧载就能安装

**Comment by xiaoduozhou** [comment]
> 用鸿蒙的爱国者能不能别用GitHub别用代理软件啊🤓

意思就是你恨国咯， 满脑子政治的蛀虫。 说一个让你破防的消息，clash鸿蒙版 已经有人开发了， git上下载下来侧载就能安装

**Comment by LiDevil** [comment]
> 对于近日有人提议开发鸿蒙Next版本的行为，我们予以强烈谴责。这不仅是对技术创新的无知挑战，更是对全球科技秩序的公然挑衅。鸿蒙生态自诞生以来，所追求的并非普惠的技术进步，而是通过垄断和封闭性体系，强化数字鸿沟，削弱用户的自主权，甚至威胁信息安全。
> 
> 任何试图推动这一体系进一步演化的举措，实质上是将开发者和用户引向一个封闭、无透明度、且难以逃脱的数字陷阱。此种行为，严重背离了科技发展的初衷，不仅扼杀了技术创新，更侵犯了人类基本自由与数字权利。
> 
> 我们强烈呼吁全球开发者共同抵制这一荒谬提议，共同捍卫开放、公平和透明的数字生态，坚决对抗任何形式的技术霸权和数字暴政。任何对鸿蒙Next的支持，都是对自由社会和人类尊严的公然蔑视，甚至涉嫌构成对人类数字权利的侵犯，这在道德层面是不可饶恕的，在历史上也将为世人所不齿。

你洋爹的谷歌商店搞垄断，还有ios系统还没法从其他地方下载，你不批判下？洋孝子还高潮上了，还得翻墙啊，不然找不到你们这样的乐子来增加生活的乐趣

**Comment by binge6** [comment]
鸿蒙 next 版 ClashMeta：https://github.com/likuai2010/ClashMeta/releases
侧载工具：https://github.com/likuai2010/auto-installer
需要保持开发者模式才可用

卓易通 支持安装 apk， 大部分 需要翻墙使用的app也基本是卓易通安装 apk 方式使用啊，所以 ClashMeta for Android 基本够用了，所有翻墙行为在卓易通的 Android 容器中进行都是能满足的

**Comment by PeiHaigang** [comment]
> 对于近日有人提议开发鸿蒙Next版本的行为，我们予以强烈谴责。这不仅是对技术创新的无知挑战，更是对全球科技秩序的公然挑衅。鸿蒙生态自诞生以来，所追求的并非普惠的技术进步，而是通过垄断和封闭性体系，强化数字鸿沟，削弱用户的自主权，甚至威胁信息安全。
> 
> 任何试图推动这一体系进一步演化的举措，实质上是将开发者和用户引向一个封闭、无透明度、且难以逃脱的数字陷阱。此种行为，严重背离了科技发展的初衷，不仅扼杀了技术创新，更侵犯了人类基本自由与数字权利。
> 
> 我们强烈呼吁全球开发者共同抵制这一荒谬提议，共同捍卫开放、公平和透明的数字生态，坚决对抗任何形式的技术霸权和数字暴政。任何对鸿蒙Next的支持，都是对自由社会和人类尊严的公然蔑视，甚至涉嫌构成对人类数字权利的侵犯，这在道德层面是不可饶恕的，在历史上也将为世人所不齿。

你是受了多大刺激，意淫出这么大一个阴谋论？要说技术霸权，你美爹说第一全球没有敢说自己进前十。整天咋咋呼呼，被这个监控，被那个跟踪，被害妄想症晚期了吧。你以为你是谁啊，一个DS还自己真把自己当什么人物了。

**Comment by TurnOffNOD** [comment]
> > 对于近日有人提议开发鸿蒙Next版本的行为，我们予以强烈谴责。这不仅是对技术创新的无知挑战，更是对全球科技秩序的公然挑衅。鸿蒙生态自诞生以来，所追求的并非普惠的技术进步，而是通过垄断和封闭性体系，强化数字鸿沟，削弱用户的自主权，甚至威胁信息安全。
> > 任何试图推动这一体系进一步演化的举措，实质上是将开发者和用户引向一个封闭、无透明度、且难以逃脱的数字陷阱。此种行为，严重背离了科技发展的初衷，不仅扼杀了技术创新，更侵犯了人类基本自由与数字权利。
> > 我们强烈呼吁全球开发者共同抵制这一荒谬提议，共同捍卫开放、公平和透明的数字生态，坚决对抗任何形式的技术霸权和数字暴政。任何对鸿蒙Next的支持，都是对自由社会和人类尊严的公然蔑视，甚至涉嫌构成对人类数字权利的侵犯，这在道德层面是不可饶恕的，在历史上也将为世人所不齿。
> 
> 建议也抵制下ios

人家好像没说不抵制吧……
