### ISSUE TITLE
VPN works with browser but not with software on MacBook?

### ISSUE THREAD

**Issue by sirackerman** [clash-verge-rev/clash-verge-rev#1835]
I have clash verge set up in my MacBook with a valid subscription.  I can access unblocked internet without any problem in browsers but software like WhatsApp and can't access internet. It's as if the vpn connection only works with the browser but not with the installed softwares ? How can I fix this? are they any settings I have to change?

**Comment by wonfen** [comment]
try tun on TUN mode

**Comment by sirackerman** [comment]
It works now. Thank you!
