### ISSUE TITLE
[BUG] 长时间挂在后台软件会卡住，无法打开或关闭代理，重启clash无效，需要重启应用

### ISSUE THREAD

**Issue by erycon-labs** [clash-verge-rev/clash-verge-rev#1838]
### 问题描述 / Describe the bug

之前用clash就有这个问题，但clash后来修复了，verge也有一样的问题，用了半年了一直能碰到过

### 复现步骤 / To Reproduce

挂在后台3小时以上不使用，稳定出现这个bug，再开代理就开不开了，任务栏颜色都不会变

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

暂无

**Comment by wonfen** [comment]
试试最新的2.0版。
