### ISSUE TITLE
[Feature] 复制环境变量优化

### ISSUE THREAD

**Issue by lunarf1ame** [clash-verge-rev/clash-verge-rev#1839]
### 功能描述 / Feature description

将复制环境变量功能中的地址换成本机IP地址而不是127.0.0.1

### 使用场景 / Use case

有时局域网内其他主机使用时会非常方便，不用手动再去查询本机IP地址

**Comment by wonfen** [comment]
使用本机地址并不是优雅的解决方案，一个是软件获取本机地址，如果有多个网卡的情况下不是那么方便；另外一个是使用本机地址可能会带来其他不可预知的问题

**Comment by zymouse** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/pull/2734
