### ISSUE TITLE
[BUG]无法查看代理

### ISSUE THREAD

**Issue by SR-MyStar** [clash-verge-rev/clash-verge-rev#184]
### Describe the bug

系统：Arch Linux x86_64
内核：Linux 6.6.7-zen1-1-zen
桌面：Hyprland
使用内核：archlinuxcn/clash-meta-alpha-git 20231222.r0.gf9c51de5-1
使用软件：archlinuxcn/clash-verge 1.4.5-3
症状：代理界面无法打开，报错：
![2023-12-23-22-05-41-window](https://github.com/clash-verge-rev/clash-verge-rev/assets/139795416/78cfab55-f713-4ab1-9104-cb84eeb6ba5c)

### To Reproduce

1.点击`设置>Clash内核>重启内核`（虽然使用的是clash-meta-alpha-git包，但此包提供的二进制文件为clash-meta所以重启的是clash-meta内核）
提示`没有那个文件或目录（os error2）`
![2023-12-23-22-12-54-window](https://github.com/clash-verge-rev/clash-verge-rev/assets/139795416/99a84e9e-2300-4739-8d52-9efb93fd5a43)
2.重启clash-verge
开启后代理界面为空，什么也不显示
![2023-12-23-22-10-30-window](https://github.com/clash-verge-rev/clash-verge-rev/assets/139795416/d45590ad-6965-4876-b55a-fa04623b04be)
3.进入`设置>Clash内核`
发现此时选中的是clash-meta-alpha版内核
![2023-12-23-22-11-24-window](https://github.com/clash-verge-rev/clash-verge-rev/assets/139795416/f3e321dc-f43f-487b-8731-ad3f09a18eba)
4.选中clash-meta内核
选中成功
![2023-12-23-22-11-29-window](https://github.com/clash-verge-rev/clash-verge-rev/assets/139795416/0c9f47e2-dfad-4655-8f20-d575488f1025)
5.授权clash-meta内核
6.回到代理界面
发现报错
![2023-12-23-22-05-41-window](https://github.com/clash-verge-rev/clash-verge-rev/assets/139795416/0315122e-5361-47a9-abee-f53c00725208)

### Platform

Linux

### System Version

Arch Linux x86_64

### Software Version

archlinuxcn/clash-verge 1.4.5-3

### Log

![2023-12-23-22-05-41-window](https://github.com/clash-verge-rev/clash-verge-rev/assets/139795416/acf11710-e3bb-4da6-bfa9-83659257031c)

**Comment by wonfen** [comment]
感觉是 Hyprland 桌面环节奇怪的依赖或者兼容性问题。换个桌面环节试试看。

**Comment by SR-MyStar** [comment]
以一种非常奇葩的方式解决了——在Web端展开所有节点并测速
