### ISSUE TITLE
[BUG] TUN 模式开关不生效

### ISSUE THREAD

**Issue by chenx-dust** [clash-verge-rev/clash-verge-rev#1840]
### 问题描述 / Describe the bug

在 GUI 中关闭 TUN 模式开关后，当前配置中 `tun.enable` 依然为 `true` 。

![image](https://github.com/user-attachments/assets/86cb441f-a618-4b96-b739-ee58b243e474)
![image](https://github.com/user-attachments/assets/dd4b03a4-49a0-44ad-baab-b46de1dead05)

### 复现步骤 / To Reproduce

在 Fri Oct 11 22:24:49 CST 2024 构建的 Alpha 版本中可以复现。

1. 在“设置”、“系统设置”中关闭 TUN 模式开关；
2. 在“设置”、“Verge 设置”、“当前配置”中确认 `tun.enable` 依然为 `true` 。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 24H2 Professional (zh_CN)

### 日志 / Log

未发现相关 Log

**Comment by wonfen** [comment]
试试最新的2.0_rc1般，对tun模式和服务模式的逻辑做了巨大调整优化。

**Comment by chenx-dust** [comment]
问题依然存在
![image](https://github.com/user-attachments/assets/75a07e69-14c7-430e-856a-71f11908f978)
![image](https://github.com/user-attachments/assets/7bd0d2e1-82b5-4dd5-a97d-661c7971981c)

如无法复现，我可以尝试使用干净系统重新配置，或是提供最小复现配置以供测试

**Comment by wonfen** [comment]
会不会是你的机场的配置文件里默认就有enable: true ?

**Comment by chenx-dust** [comment]
> 会不会是你的机场的配置文件里默认就有enable: true ?

这是我自己写的配置，确实默认设置为 true 。但之前版本的行为与这不同，之前版本会覆盖该选项。

**Comment by wonfen** [comment]
如果默认配置中有相关设置，说明提供商（机场）希望用户按此方式使用。verge会首先准守配置文件；这样处理有什么不妥吗？

**Comment by chenx-dust** [comment]
我认为是不妥的
从软件功能上，verge 作为核心前端，应当有方便用户二次自定义配置的能力，应当以自身应用配置覆盖原有配置。
从惯例上，从以前的 Clash for Windows 到 OpenClash ，再到先前版本的 Clash Verge ，都是以覆盖的形式工作的。
从实用意义上，如果配置托管商提供了不符合用户需求的配置，提供用户自行更改的功能也是非常有意义的。

**Comment by wonfen** [comment]
有道理，下个版本实现

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/commit/caf4ee68630f33150dd0bd0efd435dfd5c1b45b0
修复了
