### ISSUE TITLE
[BUG] 当我使用软件时无法使用ipv6，这可能是什么原因引起的

### ISSUE THREAD

**Issue by yonjiegaoshou** [clash-verge-rev/clash-verge-rev#1841]
### 问题描述 / Describe the bug

就如通标题表示的那样，无法使用ipv6（软件开启系统代理时） 

### 复现步骤 / To Reproduce

这是不开启系统代理
![屏幕截图 2024-10-12 041910](https://github.com/user-attachments/assets/6ba034fe-73f6-4a03-a16f-4a0e711c9312)

这是开启系统代理
![屏幕截图 2024-10-12 041734](https://github.com/user-attachments/assets/7271842d-cdea-4d60-adc9-45cab40fcea1)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows

### 日志 / Log

无

**Comment by wonfen** [comment]
这要看你的节点是否支持IPV6啊
