### ISSUE TITLE
[BUG] TUN模式与IPv6冲突

### ISSUE THREAD

**Issue by epiglottis-cartilage** [clash-verge-rev/clash-verge-rev#1842]
### 问题描述 / Describe the bug

当启用IPv6时再开启TUN**提示成功**，但日志报错且不可用（找不到虚拟网卡）。
先启用TUN再开启IPv6**提示成功**，**日志无报错**且IPv6不可用。
单独使用均正常。

- [x] 已根据报错信息以管理员身份启动但无效。
- [x] 尝试重装（最新1.7.7），重启，重置

### 复现步骤 / To Reproduce

无特殊步骤

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 Pro, OS build 22621.4317

### 日志 / Log

error
Start TUN listening error: configure tun interface: set ipv6 dns: Access is denied.

**Comment by wonfen** [comment]
试试最新的2.0_rc1版；我这边没法复现。
