### ISSUE TITLE
[Feature] Macos菜单栏图标旁增加显示上传下载实时流量

### ISSUE THREAD

**Issue by zhangfan822** [clash-verge-rev/clash-verge-rev#1843]
### 功能描述 / Feature description

MacOs 菜单栏图标旁增加显示上传下载实时流量

### 使用场景 / Use case

启用代理后，在菜单栏图标旁增加显示上传下载实时流量

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1860
