### ISSUE TITLE
[BUG] win系统安装问题

### ISSUE THREAD

**Issue by zesai** [clash-verge-rev/clash-verge-rev#1844]
### 问题描述 / Describe the bug

提示
<img width="469" alt="image" src="https://github.com/user-attachments/assets/ddf271ec-075f-4a1d-876c-e3de50145ed6">

### 复现步骤 / To Reproduce

安装时弹窗

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

7

### 日志 / Log

安装时弹窗

**Comment by wonfen** [comment]
不支持win7对自己好一点，升级一下系统吧

**Comment by Archer-czl** [comment]
> 不支持win7对自己好一点，升级一下系统吧
请问现在还有没有支持win7的版本，帮导师的工作电脑（由于不可抗力不能重装系统QAQ）装1.5.11的版本，安装后订阅代理那里为空，点击使用订阅，报错且没有错误信息

**Comment by Dragon1573** [comment]
> 请问现在还有没有支持 Windows 7 的版本

`v1.x` 系列可以尝试，但早已 EoL ，一切问题我们不再负责。

> 安装后订阅代理那里为空，点击使用订阅，报错且没有错误信息

对应的 Mihomo Core 版本可能也不支持订阅提供的节点协议。Clash Verge Rev / Mihomo Core 之间没有必然联系，可以尝试另外升级 Mihomo Core 版本，旧 CVR 配合新 Core 没准能用。
