### ISSUE TITLE
[BUG] 多个节点套用相同的反代 cf ip 和端口，使用 clash verge rev 进行延迟测试时，节点经常性会 tcp 阻断，但过一会儿又可以用了，使用 v2rayN 和 GUI.for.SingBox 没有这个问题

### ISSUE THREAD

**Issue by xtfree** [clash-verge-rev/clash-verge-rev#1846]
### 问题描述 / Describe the bug

多个节点套用相同的反代 cf ip 和端口，使用 clash verge rev 进行延迟测试时，节点经常性会 tcp 阻断，但过一会儿又可以用了，使用 v2rayN 和 GUI.for.SingBox 没有这个问题

### 复现步骤 / To Reproduce

no

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 23H2

### 日志 / Log

no

**Comment by wonfen** [comment]
有没有尝试在杂项设置里面换一个测速地址？

**Comment by xtfree** [comment]
> 有没有尝试在杂项设置里面换一个测速地址？

试过了，没用的

**Comment by wonfen** [comment]
建议携带日志到内核mihomo那边反馈

**Comment by mizb** [comment]
你把clash配置中的dns改为一个试试，不要开启多个。。
