### ISSUE TITLE
[BUG] 测延迟会用当前连接的网络去测，正常应该用本地网络

### ISSUE THREAD

**Issue by ChaselDutt** [clash-verge-rev/clash-verge-rev#1847]
### 问题描述 / Describe the bug

测延迟会用当前连接的网络去测，正常应该用本地网络

### 复现步骤 / To Reproduce

测延迟会用当前连接的网络去测，正常应该用本地网络

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

测延迟会用当前连接的网络去测，正常应该用本地网络

**Comment by wonfen** [comment]
没听懂，描述清楚一些

**Comment by wonfen** [comment]
无进一步反馈；关闭
