### ISSUE TITLE
[BUG] macOS下非管理员账户设置代理不成功

### ISSUE THREAD

**Issue by ee2k** [clash-verge-rev/clash-verge-rev#1849]
### 问题描述 / Describe the bug

clash verge 1.7.7，在macOS下用非管理员账号设置代理不能使用，但是用管理员账号可以使用。见截图。
<img width="471" alt="Screen Shot 2024-10-14 at 4 37 14 AM" src="https://github.com/user-attachments/assets/7d2e3233-e07f-42ba-aed4-4cf49f8514a6">
<img width="483" alt="Screen Shot 2024-10-14 at 4 36 33 AM" src="https://github.com/user-attachments/assets/14f383fa-8f63-4f5c-b09e-56e274cbaeca">

### 复现步骤 / To Reproduce

macOS上用非管理员账号和管理员账号分别测试可见结果。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

12.7.6

### 日志 / Log

暂无。

**Comment by wonfen** [comment]
看文档： https://www.clashverge.dev/faq/macos.html#macos

**Comment by wonfen** [comment]
还可以试试2.0版；通过服务模式应该解决了这个问题。

**Comment by ee2k** [comment]
设置需要管理员密码来访问系统级设置在macOS 12.7.6上不起作用，原来ClashX没有这个问题。等2.0发布～
