### ISSUE TITLE
[BUG]无法打开客户端界面

### ISSUE THREAD

**Issue by Maybe404** [clash-verge-rev/clash-verge-rev#185]
### Describe the bug

![微信图片_20231224100554](https://github.com/clash-verge-rev/clash-verge-rev/assets/149344521/99c1d65a-eb56-4ace-abf2-589e6c01c722)

### To Reproduce

点击任务栏图标后，客户端界面为隐形

### Platform

Windows

### System Version

win11

### Software Version

1.4.5

**Comment by MystiPanda** [comment]
Duplicate #92
