### ISSUE TITLE
[BUG] 同样软件浙江电信宽带全部超时，浙江移动联通宽带可以用

### ISSUE THREAD

**Issue by levi2799** [clash-verge-rev/clash-verge-rev#1850]
### 问题描述 / Describe the bug

![QQ20241014-121127](https://github.com/user-attachments/assets/ae283e6f-cde7-4ace-8b12-f5e60bc5e512)
![QQ20241014-121218](https://github.com/user-attachments/assets/b82639b7-3b00-45fa-bf1c-0b078f0a6e26)
同样的软件，我家里有3条宽带

连上浙江电信（有些教育网也有这样的问题）的，全部超时，但是如果内核换成测试版，外网就正常访问，内网就用不了

连上浙江移动或者联通的宽带，一切正常

同样用浙江电信的宽带，用v2rayN这个软件，同样的线路，他们的软件可以用

### 复现步骤 / To Reproduce

这个问题是开始发生在8月底开始的，以前浙江电信也是可以正常使用的

个人感觉好像跟DNS的解析有关

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10,11

### 日志 / Log

10-14 12:26:53warning
[TCP] dial 雷雨笔谈 (match IPCIDR/91.108.56.0/22) 127.0.0.1:56723 --> 91.108.56.165:80 error: zvip158.igpop.cn:30158 connect error: dns resolve failed: all DNS requests failed, first error: requesting https://dns.twnic.tw:443/dns-query: Get "https://dns.twnic.tw:443/dns-query?dns=AAABAAABAAAAAAAAB3p2aXAxNTgFaWdwb3ACY24AAAEAAQ": connect failed: dial tcp 101.101.101.101:443: i/o timeout (resErr:<nil>)
10-14 12:26:53warning
[TCP] dial 雷雨笔谈 (match IPCIDR/91.108.56.0/22) 127.0.0.1:56729 --> 91.108.56.165:80 error: zvip158.igpop.cn:30158 connect error: dns resolve failed: all DNS requests failed, first error: requesting https://dns.twnic.tw:443/dns-query: Get "https://dns.twnic.tw:443/dns-query?dns=AAABAAABAAAAAAAAB3p2aXAxNTgFaWdwb3ACY24AAAEAAQ": connect failed: dial tcp 101.101.101.101:443: i/o timeout (resErr:<nil>)
10-14 12:26:53warning
[TCP] dial 雷雨笔谈 (match IPCIDR/91.108.56.0/22) 127.0.0.1:56722 --> 91.108.56.165:443 error: zvip158.igpop.cn:30158 connect error: dns resolve failed: all DNS requests failed, first error: requesting https://dns.twnic.tw:443/dns-query: Get "https://dns.twnic.tw:443/dns-query?dns=AAABAAABAAAAAAAAB3p2aXAxNTgFaWdwb3ACY24AAAEAAQ": connect failed: dial tcp 101.101.101.101:443: i/o timeout (resErr:<nil>)
10-14 12:26:53warning
[TCP] dial 雷雨笔谈 (match IPCIDR/149.154.160.0/20) 127.0.0.1:56730 --> 149.154.167.92:443 error: zvip158.igpop.cn:30158 connect error: dns resolve failed: all DNS requests failed, first error: requesting https://dns.twnic.tw:443/dns-query: Get "https://dns.twnic.tw:443/dns-query?dns=AAABAAABAAAAAAAAB3p2aXAxNTgFaWdwb3ACY24AAAEAAQ": connect failed: dial tcp 101.101.101.101:443: i/o timeout (resErr:<nil>)

**Comment by drama8888** [comment]
+1

**Comment by levi2799** [comment]
> +1

你也有这个问题吗？好像有些教育网也会有这个问题，浙江电信是8月底才开始的

**Comment by wonfen** [comment]
从日志来看是机场配置文件部分DNS有问题，全部解析失败了，v2ray可以用的原因是没有使用机场提供的配置文件。

配置文件都写不好的机场建议还是别用了。

**Comment by levi2799** [comment]
> 从日志来看是机场配置文件部分DNS有问题，全部解析失败了，v2ray可以用的原因是没有使用机场提供的配置文件。
> 
> 配置文件都写不好的机场建议还是别用了。

那为什么同样的配置文件，在浙江移动或者联通的宽带下可以用呢，我也觉得奇怪，^_^

**Comment by wonfen** [comment]
> > 从日志来看是机场配置文件部分DNS有问题，全部解析失败了，v2ray可以用的原因是没有使用机场提供的配置文件。
> > 配置文件都写不好的机场建议还是别用了。
> 
> 那为什么同样的配置文件，在浙江移动或者联通的宽带下可以用呢，我也觉得奇怪，^_^

电信屏蔽了这些配置文件里的DNS呗。

**Comment by SoHugePenguin** [comment]
> > +1
> 
> 你也有这个问题吗？好像有些教育网也会有这个问题，浙江电信是8月底才开始的

就是最近发生的事情感觉，校园网和家庭网络（我家电信，别的不知道）里都用不了，数据网络及其热点共享可以使用。不过我最近发现一个很简单的解决方案，只需要把dns模块全删了即可 (才不是因为我菜 XD）

![image](https://github.com/user-attachments/assets/f5f246c6-dffc-4c4f-bc36-55d1ab83a3de)

删完后重启订阅，你会发现问题解决了。

![image](https://github.com/user-attachments/assets/0cd5ea50-efc2-4f2f-8c27-a7e2cf413042)

![image](https://github.com/user-attachments/assets/2f5ccb35-fc30-4abc-86ae-7e1050de4443)

我研究了几个小时，感觉是vless或者tls的问题 (wireshark一堆红色报文没得说)，在shadowsock这套配置其实是可以的，所以我认为问题十有八九出在内核代码的实现连接vless,tls这类代理上(我猜的)。

但是既然能直接删掉dns全部让他自己来，我就不深究源码了<才不是没学过rust :(>，简单看了一下，源码测速那边是没问题的，连接上代理后，以代理的身份来访问cf的204空白页面测速，测速本身没有问题，我敢肯定是出在连接上。

我这套dns其实也是抄的别人的，这dns配置讲实话一般情况也用不到，原来那个机场用的自动选择和故障转移。我抄的那个配置还一堆warn报错，还不如删掉。如果本人开始学习rust也许会深究源码，现在用用得了。（每次打开clash要先打开v2rayN可把我气死了，终于解决了）,或者直接用v2rayN，但是我个人更喜欢clash。

最后总结，这个问题目测一般会出现在自己搭建的机场上，看过来都是vless出问题，估计啥时候更新多出来的奇妙bug吧...
