### ISSUE TITLE
[BUG] 2.0.0 添加或更新订阅时报错，同时代理无法加载（页面为空）

### ISSUE THREAD

**Issue by id9502** [clash-verge-rev/clash-verge-rev#1851]
### 问题描述 / Describe the bug

添加远程或本地订阅后，更新订阅必定报错，代理更新失败列表为空

### 复现步骤 / To Reproduce

添加远程或本地订阅后，更新订阅

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Debian testing

### 日志 / Log

“error sending request for url (http://127.0.0.1:9097/configs)”

**Comment by wonfen** [comment]
需要更多App日志

**Comment by id9502** [comment]
> 需要更多App日志；从表现上来看，原因是内核通信失败；要具体排查是内核没有成功启动还是其他原因

在命令行里执行发现报错：《/usr/bin/sh: 1: /usr/lib/Clash: not found》
分析应该是由于服务启动失败导致，程序启动时，会尝试请求sudo权限执行《/usr/bin/sh -c /usr/lib/Clash Verge/resources/uninstall-service》，但是其中的空格似乎没有做转义，导致sh尝试在Clash后截断了指令。

**Comment by wonfen** [comment]
试试最新的2.0版本，转义的问题修了。

**Comment by noodles500kg** [comment]
mac版本的也是这个问题

**Comment by wonfen** [comment]
> mac版本的也是这个问题

下载最新的版本，应该已经修复了。

**Comment by id9502** [comment]
> > mac版本的也是这个问题
> 
> 下载最新的版本，应该已经修复了。

最新版（2.0.0-rc1）更新后报错变为
/usr/bin/sh: 1: /usr/lib/Clash Verge/resources/install-service: Permission denied

**Comment by Tychristine** [comment]
> > > mac版本的也是这个问题
> > 
> > 
> > 下载最新的版本，应该已经修复了。
> 
> 最新版（2.0.0-rc1）更新后报错变为 /usr/bin/sh: 1: /usr/lib/Clash Verge/resources/install-service: Permission denied

日志表示安装服务模式时没有正确获取到root授权
