### ISSUE TITLE
[BUG] 刷新订阅会报403

### ISSUE THREAD

**Issue by JarvisMarkDown** [clash-verge-rev/clash-verge-rev#1856]
### 问题描述 / Describe the bug

![Uploading 截屏2024-10-15 10.02.53.png…]()

### 复现步骤 / To Reproduce

![Uploading 截屏2024-10-15 10.02.53.png…]()

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

17.7

### 日志 / Log

![Uploading 截屏2024-10-15 10.15.44.png…]()

**Comment by wonfen** [comment]
图片挂了，听描述是内核没有正常启动。

**Comment by JarvisMarkDown** [comment]
可以加个v吗 我给您发下图片

**Comment by JarvisMarkDown** [comment]
zgp295994612 麻烦您加下哈

**Comment by wonfen** [comment]
> zgp295994612 麻烦您加下哈

加微信？送人头？

**Comment by JarvisMarkDown** [comment]
都试过了 还是不行

**Comment by JarvisMarkDown** [comment]
代理组页全是error

**Comment by wonfen** [comment]
> 代理组页全是error

内核没启动当然error了，系统问题，建议找机场客服。

**Comment by JarvisMarkDown** [comment]
怎么找啊 麻烦指条明路

**Comment by wonfen** [comment]
你用的哪家机场，去机场网站找客服啊。

**Comment by JarvisMarkDown** [comment]
好了 原来是XFLTD他们维护 然后需要重新导入订阅
