### ISSUE TITLE
[BUG] 程序订阅使用报错error sending request for url (http:/127.0.0.1:9097/con figs)

### ISSUE THREAD

**Issue by zcmwlaq** [clash-verge-rev/clash-verge-rev#1858]
### 问题描述 / Describe the bug

error sending request for url
(http:/127.0.0.1:9097/con figs)

### 复现步骤 / To Reproduce

程序第一次使用添加订阅后，点击使用订阅，然后报错error sending request for url
(http:/127.0.0.1:9097/con figs)

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

ubuntu22.04

### 日志 / Log

2024-10-15 20:16:09 ERROR - error sending request for url (http://127.0.0.1:33211/unset_dns)
2024-10-15 20:16:28 ERROR - error sending request for url (http://127.0.0.1:33211/unset_dns)
2024-10-15 20:16:40 ERROR - error sending request for url (http://127.0.0.1:33211/unset_dns)

**Comment by wonfen** [comment]
软件版本？看描述像内核没正常通信、或者订阅文件有问题。

**Comment by rurumuri** [comment]
我也遇到了这个问题，和  #1851 现象类似，可能是同样的原因？

### 软件版本 / Software Version
[Clash Verge Rev Alpha](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha) ，包含目前最新的 [Clash.Verge-2.0.0-rc.1](https://github.com/clash-verge-rev/clash-verge-rev/releases/download/alpha/Clash.Verge_2.0.0-rc.1_amd64.deb)

### 问题描述 / Describe the bug
**从旧版本 1.7.5 更新**到 2.0.0 后，启动程序后面板的 代理 界面空白，调整“规则/全局/直连”或者切换订阅、进行订阅更新等操作均无法完成，并提示：

error sending request for url
(http:/127.0.0.1:9097/configs)

### 复现步骤 / To Reproduce
如上所描述。

### 操作系统 / OS
Linux

### 操作系统版本 / OS Version
Linux misaka-11688 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### 日志 / Log

```
2024-10-16 15:55:28 INFO - running timer task `RNedGD6ta5xX`
2024-10-16 15:55:28 INFO - error sending request for url (http://127.0.0.1:9097/configs)
2024-10-16 15:55:28 INFO - error sending request for url (http://127.0.0.1:9097/configs)
2024-10-16 15:55:29 INFO - error sending request for url (http://127.0.0.1:9097/configs)
2024-10-16 15:55:29 INFO - error sending request for url (http://127.0.0.1:9097/configs)
```

---

以下是我的排查和解决方案：

### 排查和解决方案

首先猜测是客户端和 Clash 内核之间无法通信。

手动执行 `/usr/lib/Clash Verge/resources/clash-verge-service` 后重启客户端发现能正常工作，猜测是服务问题。

检查 `clash-verge-service.service` 状态，发现
```
● clash-verge-service.service - Clash Verge Service helps to launch Clash Core.
     Loaded: loaded (/etc/systemd/system/clash-verge-service.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2024-10-16 16:46:33 CST; 1s ago
    Process: 33213 ExecStart=/usr/lib/Clash Verge/resources/clash-verge-service (code=exited, status=203/EXEC)
   Main PID: 33213 (code=exited, status=203/EXEC)
        CPU: 5ms
```

检查 `/etc/systemd/system/clash-verge-service.service` 文件，发现
```
[Unit]
Description=Clash Verge Service helps to launch Clash Core.
After=network-online.target nftables.service iptables.service

[Service]
Type=simple
ExecStart=/usr/lib/Clash Verge/resources/clash-verge-service
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

注意到 `ExecStart=/usr/lib/Clash Verge/resources/clash-verge-service` 缺少空格转义导致无法访问服务可执行文件，加引号修正为 `ExecStart="/usr/lib/Clash Verge/resources/clash-verge-service"`，而后重启 `clash-verge-service.service` 服务和 Clash Verge Rev 客户端，即可正常工作。

### 其他问题

尝试手工执行 `/usr/lib/Clash Verge/resources/install-service` 和 `/usr/lib/Clash Verge/resources/uninstall-service` 无效；

此外注意到目前最新版本的客户端软件启动时会要求 root 权限并执行这两个可执行文件。
![Screenshot from 2024-10-16 15-55-16](https://github.com/user-attachments/assets/d459efab-9b21-41d7-8a4c-f8e0029addb1)
![Screenshot from 2024-10-16 15-55-24](https://github.com/user-attachments/assets/bbc8b18a-df57-46b5-a02f-a4bcb468ac2c)
不过没有解决问题。

注：我电脑上的两个可执行文件的 md5 为：

```
d64f06d59b82bd8f43331b86f40d54cc  install-service
244b4ae236acb8bfaa817817f55e6740  uninstall-service
```

两个文件是 ELF 可执行文件而非脚本，我不清楚其内部实现是否有问题，或是客户端更新的逻辑有问题。我没有尝试彻底删除所有文件并重装最新版软件。

**Comment by wonfen** [comment]
感谢反馈，已经在调试了。

**Comment by michaelGuo1204** [comment]
@rurumuri 1.7.7+Ubuntu2404 也遇上了类似的问题, 修改service文件后可以解决, 感谢!

**Comment by wonfen** [comment]
试试最新的alpha版本，刚刚修复了

**Comment by An0nymous0** [comment]
> 最新的alpha

这个版本也有同样的问题

**Comment by pluto0x0** [comment]
> > 最新的alpha
> 
> 这个版本也有同样的问题

rc5遇到同样问题，将`/usr/bin/install-service` `/usr/bin/uninstall-service` `/usr/bin/clash-verge-service` 添加执行权限解决，应该是内核无法启动的问题。修复后启动没有root权限认证对话框。

**Comment by wonfen** [comment]
> > > 最新的alpha
> > 
> > 
> > 这个版本也有同样的问题
> 
> rc5遇到同样问题，将`/usr/bin/install-service` `/usr/bin/uninstall-service` `/usr/bin/clash-verge-service` 添加执行权限解决，应该是内核无法启动的问题。修复后启动没有root权限认证对话框。

老版本完全卸载，重新安装最新版rc5，看看是否会弹出安装服务的密码框？

**Comment by yzholic** [comment]
error sending request for url
(http:/127.0.0.1:9097/configs?force=true)
遇到了同样的问题
