### ISSUE TITLE
[BUG] alpha版本2.0.0无法安装“服务模式”

### ISSUE THREAD

**Issue by legolasNg** [clash-verge-rev/clash-verge-rev#1859]
### 问题描述 / Describe the bug

1、alpla版本无法安装服务模式，点击安装会弹出“installer not found”
2、在/usr/lib/clash-verge/resources目录下没有任何文件
3、在/usr/lib/Clash\ Verge/resources目录下有clash-verge-service文件

### 复现步骤 / To Reproduce

打开clash-verge，点击设置->服务模式->安装->输入root密码，弹出“installer not found”

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Fedora 41

### 日志 / Log

没有相关日志

**Comment by wonfen** [comment]
2.0版本的服务模式已经集成到了首次运行安装了，有没有下载最新版？

**Comment by legolasNg** [comment]
> 2.0版本的服务模式已经集成到了首次运行安装了，有没有下载最新版？

下载最新的alpha版本，问题已经解决了。谢谢！
