### ISSUE TITLE
[BUG] ERROR - error sending request for url (http://127.0.0.1:9097/configs)

### ISSUE THREAD

**Issue by ctyytc** [clash-verge-rev/clash-verge-rev#1861]
### 问题描述 / Describe the bug

安装了 [Clash.Verge_2.0.0-rc.1_aarch64.dmg](https://github.com/clash-verge-rev/clash-verge-rev/releases/download/alpha/Clash.Verge_2.0.0-rc.1_aarch64.dmg) 后，打开应用无法使用，代理页面为空

下面是在配置页面控制台打开开发者工具后看到的报错：
<img width="1440" alt="Clash Verge Error" src="https://github.com/user-attachments/assets/cd94d697-72f6-46a7-83ce-a712a361cbda">

### 复现步骤 / To Reproduce

打开就报错

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.0.1 (24A348)

### 日志 / Log

2024-10-16 09:47:58 ERROR - error sending request for url (http://127.0.0.1:9097/configs)
2024-10-16 09:48:22 ERROR - failed to connect to the Clash Verge Service

**Comment by wonfen** [comment]
首次运行会提示输入密码安装服务，是不是跳过了？导致内核没有启动。

**Comment by ctyytc** [comment]
> 首次运行会提示输入密码安装服务，是不是跳过了？导致内核没有启动。

@wonfen 我通过菜单和配置页面，反复重启了APP和内核，都无效。之前的Alpha版本都是好的，这个rc1覆盖后就不行了，目前回退了版本就好了

**Comment by JayLXL** [comment]
Ubuntu 24.04.1 LTS 也出现了相同报错，无法使用

**Comment by myChinesePYL** [comment]
我本来也不行，但是我想了一下，报错是因为无法将数据发送到http://127.0.0.1:9097/configs，可能是因为verge-mihomo(-alpha)监听的端口不是9097，所以我就尝试运行verge-mihomo --help命令看看有什么办法可以让verge-mihomo(-alpha)监听9097端口，最后我找到了这条命令"   verge-mihomo -ext-ctl 127.0.0.1:9097   "，最后解决了，已经能识别到了![截图_2024-10-19_11-35-26](https://github.com/user-attachments/assets/940c76e8-7e0c-4d06-a4fb-c0e422999d71)

**Comment by kingkongdog** [comment]
> 首次运行会提示输入密码安装服务，是不是跳过了？导致内核没有启动。

我这边也是这个报错。首次运行时并没有提示输入用户密码。我是黑苹果 13.6.6，之前安装过 clash-verge。

**Comment by wonfen** [comment]
试试最新的alpha版本；刚修复了
