### ISSUE TITLE
[BUG] Tun模式，规则无效

### ISSUE THREAD

**Issue by zyz** [clash-verge-rev/clash-verge-rev#1862]
### 问题描述 / Describe the bug

1.设置：安装服务，开启服务，开启Tun模式
2.代理：选择规则（默认就是规则）
3.订阅：右键->编辑规则
   输入域名
   点击添加前置规则
4.访问直连规则的域名还要经过代理，而不是直连

### 复现步骤 / To Reproduce

1.工具
   Clash Verge 1.7.7
   系统代理：off
   Tun模式：on
2.代理
   2.1.规则、全局、直连。选择【规则】
   2.2.自动选择
3.订阅
   当前订阅->右键编辑规则。如下
prepend:
  - 'DOMAIN,tsanghi.com,DIRECT'
  - 'DOMAIN,usdcny.net,DIRECT'
  - 'DOMAIN,qq.com,DIRECT'
  - 'DOMAIN,nowapi.com,DIRECT'
  - 'DOMAIN,12306.cn,DIRECT'
  - 'DOMAIN,jyshare.com,DIRECT'
  - 'DOMAIN,zhihu.com,DIRECT'
  - 'DOMAIN,baidu.com,DIRECT'
  - 'DOMAIN,cnblogs.com,DIRECT'
  - 'DOMAIN,gitee.com,DIRECT'
  - 'DOMAIN,47.97.254.231,DIRECT'
  - 'DOMAIN,donet5.com,DIRECT'
  - 'DOMAIN,csdn.net,DIRECT'
append: []
delete: []
4.访问直连规则的域名还要经过代理，而不是直连

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 23H2

### 日志 / Log

10-16 09:58:05WARNING
[TCP] dial DIRECT (match Domain/gitee.com) 198.18.0.1:58067 --> gitee.com:443 error: connect failed: dial tcp 180.76.198.77:443: i/o timeout dial tcp 180.76.198.225:443: i/o timeout

**Comment by PctAIGM** [comment]
`dial DIRECT (match Domain/gitee.com) `

日志不是说了直连了吗

**Comment by wonfen** [comment]
非GUI问题，检查规则顺序，确认真有问题到内核那边反馈。

**Comment by zyz** [comment]
退出clash工具，访问正常，都是前置规则了，如果是规则顺序问题，要怎么设置？

**Comment by wonfen** [comment]
> 退出clash工具，访问正常，都是前置规则了，如果是规则顺序问题，要怎么设置？ ping gitee.com IP=180.76.198.225 [TCP] dial DIRECT (match Domain/gitee.com) 198.18.0.1:58067 198.18.0.1:58067这个是什么？直连应该是我本地IP直连而不是经过代理IP直连吧？ 中国的域名，不开启clash工具，访问正常，经过clash工具，直连出现timeout超时

今天遇到2个规则问题了，都是ACL4SSR规则的问题；花了我几个小时排查规则：

https://github.com/clash-verge-rev/clash-verge-rev/issues/1880#issuecomment-2423687655
https://github.com/clash-verge-rev/clash-verge-rev/issues/1911#issuecomment-2432904952
