### ISSUE TITLE
[BUG] alpha版本无法自启动

### ISSUE THREAD

**Issue by z1298808165** [clash-verge-rev/clash-verge-rev#1863]
### 问题描述 / Describe the bug

我两台电脑中，台式机正常，但笔记本无论如何都无法开机自启，即使创建快捷方式放入到启动中也无法开机启动

### 复现步骤 / To Reproduce

开启→未自启，需手动运行

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

开机无法自启不知道提供哪里的日志

**Comment by wonfen** [comment]
软件版本？我这里2.0_rc1无法复现。

**Comment by z1298808165** [comment]
> 软件版本？我这里2.0_rc1无法复现。

今天也更新了v2.0.0-rc.1，刚刚重启了也是没有自启动

**Comment by wonfen** [comment]
> > 软件版本？我这里2.0_rc1无法复现。
> 
> 今天也更新了v2.0.0-rc.1，刚刚重启了也是没有自启动

我这边换了几台电脑都可以，检查下你的系统问题吧。

**Comment by z1298808165** [comment]
> > > 软件版本？我这里2.0_rc1无法复现。
> > 
> > 
> > 今天也更新了v2.0.0-rc.1，刚刚重启了也是没有自启动
> 
> 我这边换了几台电脑都可以，检查下你的系统问题吧。

卸载+清除用户数据，然后重新安装到另一个路径可以了，现在能正常自启动了

**Comment by leon12138** [comment]
我这边也出现了同样的问题，也试着添加到了自启目录，还是启动不了，同样是笔记本，我是amd处理器，不知道会不会是这个兼容问题

**Comment by z1298808165** [comment]
> 我这边也出现了同样的问题，也试着添加到了自启目录，还是启动不了，同样是笔记本，我是amd处理器，不知道会不会是这个兼容问题

我也是AMD的笔记本，你可以尝试完全卸载，然后换一个目录安装
