### ISSUE TITLE
[BUG] 无法打开

### ISSUE THREAD

**Issue by Hgexia** [clash-verge-rev/clash-verge-rev#1864]
### 问题描述 / Describe the bug

Clash.Verge_2.0.0-rc.1_x64版本，英特尔芯片Mac无法打开，秒退

### 复现步骤 / To Reproduce

直接无法启动，秒退

### 操作系统 / OS

mac

### 操作系统版本 / OS Version

13.6 (22G120)

### 日志 / Log

[clash-verge-2024-10-16-104407.zip](https://github.com/user-attachments/files/17388547/clash-verge-2024-10-16-104407.zip)

**Comment by wonfen** [comment]
到下面目录看下app的日志：
'/Users/你的用户名/Library/Application Support/io.github.clash-verge-rev.clash-verge-rev/logs'

**Comment by 928422955** [comment]
可以通过热键设置打开/关闭面板，临时解决这个bug

**Comment by wonfen** [comment]
> 可以通过热键设置打开/关闭面板，临时解决这个bug

到底是什么问题，我这边没法复现啊，没法复现怎么修。

**Comment by kingkongdog** [comment]
一样，我这边是黑苹果 13.6 版本，打开 alpha 版本，能看到顶部工具栏有白色的小猫图标，点击它，选打开，app 就退出了。

**Comment by wonfen** [comment]
> 一样，我这边是黑苹果 13.6 版本，打开 alpha 版本，能看到顶部工具栏有白色的小猫图标，点击它，选打开面板，app 就退出了。

试试今天编译的最新版，这个问题应该修复了。

**Comment by wonfen** [comment]
无进一步反馈；关闭
