### ISSUE TITLE
[BUG] Linux 订阅

### ISSUE THREAD

**Issue by bsccw** [clash-verge-rev/clash-verge-rev#1865]
### 问题描述 / Describe the bug

在安装了Clash.Verge_2.0.0-rc.1_amd64.deb
出现 程序无法正常订阅
2024-10-16 12:59:40 ERROR - error sending request for url (http://127.0.0.1:9097/configs

### 复现步骤 / To Reproduce

重新订阅就会重复出现

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu 24.04 LTS

### 日志 / Log

[2024-10-16-1256.log](https://github.com/user-attachments/files/17389411/2024-10-16-1256.log)

**Comment by rurumuri** [comment]
问题似乎和 #1861、 #1858、 #1851 是一样的？
请尝试我的解决方案 https://github.com/clash-verge-rev/clash-verge-rev/issues/1858#issuecomment-2416198724

**Comment by wonfen** [comment]
已知2.0版问题，正在修复。

**Comment by wonfen** [comment]
试试最新版的build；应该修复了
