### ISSUE TITLE
[Feature] 自动更新订阅问题

### ISSUE THREAD

**Issue by macrocodea** [clash-verge-rev/clash-verge-rev#1866]
### 功能描述 / Feature description

clash verge 只有在首次启动软件时才会触发自动更新。
对于一些不喜欢关机的用户说很苦恼；
能不能引入“闲时更新”

### 使用场景 / Use case

就是用户空闲（比如连接数较低，或者看视频时，又或者是鼠标长时间不移动）的时候，自动更新；

**Comment by noodles500kg** [comment]
那个不是在订阅里面自己填写隔多少个小时自动更新订阅吗？有这个功能啊

**Comment by huina0912** [comment]
在配置条目右击就能看到啦

**Comment by macrocodea** [comment]
> 那个不是在订阅里面自己填写隔多少个小时自动更新订阅吗？有这个功能啊 ![image](https://private-user-images.githubusercontent.com/30250562/377305304-bd8453ba-0ab9-43fa-af40-bf6cc4596221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzIzNDYsIm5iZiI6MTcyOTE3MjA0NiwicGF0aCI6Ii8zMDI1MDU2Mi8zNzczMDUzMDQtYmQ4NDUzYmEtMGFiOS00M2ZhLWFmNDAtYmY2Y2M0NTk2MjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEzMzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMTg1YjZmYWNkOTIyZDRiNzRmMzU2MzY1ZWYzYWNiMTZiYTE2MDliZjZjMjkyYTdkN2FmNmNmYjhmMDFmNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IYU1ZORvwq5TS0nFu1MG-jUHDjibZfJluXDm75l4YLk)

我知道有更新间隔，但是时间到了并不会强制触发自动更新，而是需要关闭软件再启动时才会检查更新！
也就是自动更新的触发条件是，启动软件时检查！
所以才建议推出“闲时更新”；

**Comment by WENMINGZHUFAN** [comment]
> > 那个不是在订阅里面自己填写隔多少个小时自动更新订阅吗？有这个功能啊 ![image](https://private-user-images.githubusercontent.com/30250562/377305304-bd8453ba-0ab9-43fa-af40-bf6cc4596221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzIzNDYsIm5iZiI6MTcyOTE3MjA0NiwicGF0aCI6Ii8zMDI1MDU2Mi8zNzczMDUzMDQtYmQ4NDUzYmEtMGFiOS00M2ZhLWFmNDAtYmY2Y2M0NTk2MjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEzMzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMTg1YjZmYWNkOTIyZDRiNzRmMzU2MzY1ZWYzYWNiMTZiYTE2MDliZjZjMjkyYTdkN2FmNmNmYjhmMDFmNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IYU1ZORvwq5TS0nFu1MG-jUHDjibZfJluXDm75l4YLk)
> 
> 我知道有更新间隔，但是时间到了并不会强制触发自动更新，而是需要关闭软件再启动时才会检查更新！ 也就是自动更新的触发条件是，启动软件时检查！ 所以才建议推出“闲时更新”； 对于不喜欢关机的用户来说，只要软件不关闭再启动就意味着永远不会触发更

**Comment by WENMINGZHUFAN** [comment]
不是因为软件，应该是使用没有成功用代理更新订阅，在规则中把verge的进程加入代理就可以实现正常更新

**Comment by BotswanaD** [comment]
> 不是因为软件，应该是使用没有成功用代理更新订阅，在规则中把verge的进程加入代理就可以实现正常更新

我应该具体怎么做呢？不太明白怎么操作

**Comment by China-Uncle** [comment]
同样的困扰.不知道怎么自动更新

**Comment by shejialun** [comment]
我也遇到相同问题了，没有进展吗？

**Comment by Hina1337** [comment]
应该勾选项 是否开启定时更新

**Comment by shejialun** [comment]
> 应该勾选项 是否开启定时更新

请问在哪里设置？谢谢

**Comment by Hina1337** [comment]
> > 应勾选项是否开启定时更新
> 
> 请问在哪里设置？谢谢

![Image](https://github.com/user-attachments/assets/b8c808cf-e5bf-45bd-aa44-f5c9b7d69a5a)
打开  使用系统代理更新 就没有定时更新了

**Comment by shejialun** [comment]
> > > 应勾选项是否开启定时更新
> > 
> > 
> > 请问在哪里设置？谢谢
> 
> ![Image](https://github.com/user-attachments/assets/b8c808cf-e5bf-45bd-aa44-f5c9b7d69a5a) 打开 使用系统代理更新 就没有定时更新了

首先我使用的是tun模式，其次这个选项我没开
你意思开了这个选项后，我设置任意更新间隔的时间是不生效的，只能手动更新？

**Comment by China-Uncle** [comment]
这样设置有时候是可以自动更新的，如果发现不能自动更新了就需要把软件关掉然后重新打开，它又会自动更新了，目前不知道什么原因会导致它的自动更新停止。
