### ISSUE TITLE
[BUG] 全局模式下,无法展开代理组,无法选择其他节点

### ISSUE THREAD

**Issue by hoooou** [clash-verge-rev/clash-verge-rev#1868]
### 问题描述 / Describe the bug
使用版本:便携版1.7.5
![image](https://github.com/user-attachments/assets/ba921f85-6e22-48e6-8573-db6907e268e2)
正常情况下应该这样:
![image](https://github.com/user-attachments/assets/257c016c-a07c-40cb-a9e3-caad5e6397b5)

### 复现步骤 / To Reproduce

切换全局模式

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win 11

### 日志 / Log

暂无

**Comment by wonfen** [comment]
机场配置文件的问题；配置文件都写不好的机场还是别用了。

**Comment by hoooou** [comment]
> 机场配置文件的问题；配置文件都写不好的机场还是别用了。

哈哈,好吧,这个配置文件是我自己写的=_=

**Comment by gatspy** [comment]
我是全局模式下 都没分组 是咋搞的
