### ISSUE TITLE
[Feature] 能否添加自定义规则以及预配置编辑

### ISSUE THREAD

**Issue by CODE-7z** [clash-verge-rev/clash-verge-rev#187]
### Is your feature request related to a problem? Please describe.

很多机场的规则对于自身使用上不一定符合

### Describe the solution you'd like

添加个自定义规则的GUI，以及添加个预配置，防止机场更新顶替掉自己的自定义规则

### Describe alternatives you've considered

。

**Comment by MystiPanda** [comment]
https://clash-verge-rev.github.io/guide.html#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86
