### ISSUE TITLE
[BUG] 用户界面耗用大量CPU、GPU（Linux，WebKitWebProcess）

### ISSUE THREAD

**Issue by JubilantJerry** [clash-verge-rev/clash-verge-rev#1875]
### 问题描述 / Describe the bug

打开Clash Verge (v1.7.7) 的用户界面UI开着就会用大量CPU、GPU。
界面关着，让Clash Verge 后台运行，就没事。让窗口最小化也没事。
用大量计算资源的进程叫WebKitWebProcess。

https://github.com/user-attachments/assets/1d30f515-7950-4202-8466-32a74f43f85d

### 复现步骤 / To Reproduce

打开Clash Verge界面

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu 20.04 LTS

### 日志 / Log

没找到跟这个问题相关的日志内容

**Comment by wonfen** [comment]
试试最新的2.0版

**Comment by JubilantJerry** [comment]
我的系统（Ubuntu 20.04 LTS）装不了 2.0.0-rc.1，报错：Dependency is not satisfiable: libwebkit2gtk-4.1-0

**Comment by shellyfun** [comment]
ubuntu 24.04, clash verge 2.4.3出现同样问题，不知道怎么解决

**Comment by JustinL-QQ** [comment]
Clash Verge 2.4.5 on Ubuntu desktop 24.04.2 also has this problem! How can i get rid of it? thanks!
