### ISSUE TITLE
[BUG] ubuntu系统下关闭clash-verge之后，代理的设置还在。重启系统也无法彻底清除系统配置。

### ISSUE THREAD

**Issue by rockjl** [clash-verge-rev/clash-verge-rev#1876]
### 问题描述 / Describe the bug

ubuntu系统下关闭clash-verge之后，通过printenv命令查看，还是可以查看到
http_proxy=http://127.0.0.1:7897/
https_proxy=http://127.0.0.1:7897/
all_proxy=socks://127.0.0.1:7897/
HTTP_PROXY=http://127.0.0.1:7897
HTTPS_PROXY=http://127.0.0.1:7897
ALL_PROXY=socks://127.0.0.1:7897/

我找遍了系统的所有文件，都没有找到是在哪一个配置文件设置的。
重启系统后还是这个样子（未安装clash-verge服务）。无法彻底清除系统配置。

### 复现步骤 / To Reproduce

ubuntu系统下关闭clash-verge之后，通过printenv命令查看，还是可以查看到
http_proxy=http://127.0.0.1:7897/
https_proxy=http://127.0.0.1:7897/
all_proxy=socks://127.0.0.1:7897/
HTTP_PROXY=http://127.0.0.1:7897
HTTPS_PROXY=http://127.0.0.1:7897
ALL_PROXY=socks://127.0.0.1:7897/

我找遍了系统的所有文件，都没有找到是在哪一个配置文件设置的。
重启系统后还是这个样子（未安装clash-verge服务）。无法彻底清除系统配置。

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

ubuntu24.04

### 日志 / Log

ubuntu系统下关闭clash-verge之后，通过printenv命令查看，还是可以查看到
http_proxy=http://127.0.0.1:7897/
https_proxy=http://127.0.0.1:7897/
all_proxy=socks://127.0.0.1:7897/
HTTP_PROXY=http://127.0.0.1:7897
HTTPS_PROXY=http://127.0.0.1:7897
ALL_PROXY=socks://127.0.0.1:7897/

我找遍了系统的所有文件，都没有找到是在哪一个配置文件设置的。
重启系统后还是这个样子（未安装clash-verge服务）。无法彻底清除系统配置。

**Comment by wonfen** [comment]
这个是环境变量的代理，应该是你自己手动设置的吧？

软件没有控制环境变量的代理。

**Comment by rockjl** [comment]
> 这个是环境变量的代理，应该是你自己手动设置的吧？
> 
> 软件没有控制环境变量的代理。

我从没有修改过任何的系统代理设置。否则我怎么可能回去说我在任何一个地方都找不到是哪一个配置文件设置的呢？
如果我真的会改，我一定会在/etc/profile或者.~/bashrc这些文件里边修改。但是我并没有这么作。我自己从未动过。
是安装clash-verge这个软件以后出现的问题。软件启动以后代理功能的确可以使用。关闭软件后重启系统，包括删除软件。都无法解决这个问题。这些配置还是会被printenv或者env等命令打印出来。我已经用尽了办法还是无法找到clash-verge这个软件到底在哪里设置的这些系统变量。

**Comment by supuo** [comment]
Windows也一样。希望Clash退出时自动清楚系统代理。

**Comment by wonfen** [comment]
> > 这个是环境变量的代理，应该是你自己手动设置的吧？
> > 软件没有控制环境变量的代理。
> 
> 我从没有修改过任何的系统代理设置。否则我怎么可能回去说我在任何一个地方都找不到是哪一个配置文件设置的呢？ 如果我真的会改，我一定会在/etc/profile或者.~/bashrc这些文件里边修改。但是我并没有这么作。我自己从未动过。 是安装clash-verge这个软件以后出现的问题。软件启动以后代理功能的确可以使用。关闭软件后重启系统，包括删除软件。都无法解决这个问题。这些配置还是会被printenv或者env等命令打印出来。我已经用尽了办法还是无法找到clash-verge这个软件到底在哪里设置的这些系统变量。

因为软件就没有自动设置的功能，当然找不到了；不知道你在纠结什么？
如果有这个设置就是通过其他方式设置上的。比如曾经复制过环境变量，到命令行执行过。

**Comment by wonfen** [comment]
> Windows也一样。希望Clash退出时自动清楚系统代理。

有这个功能，在关闭软件的时候会自动清除系统代理。但如果你直接重启电脑，没有走关闭软件的流程，软件进程是直接被kill，则无法清除系统代理。

**Comment by lzy-Jolly** [comment]
你好，借楼请教一下，有没有webui，我在ubuntu远程服务器上用，ubuntu没有安装ui，之前用clash for linux那个项目不支持hy2，现在想换这个项目，有点不太明白。

**Comment by beatlesforever** [comment]
> 这个是环境变量的代理，应该是你自己手动设置的吧？
> 
> 软件没有控制环境变量的代理。

这个确实是clash影响的。

**Comment by touxingmaochan** [comment]
在Ubuntu中退出代理不会关闭设置中的网络代理开关，手动关一下

**Comment by soyoshio** [comment]
在设置中关闭网络代理再重新打开
