### ISSUE TITLE
[Feature] 适配一下 uos国产统信操作系统

### ISSUE THREAD

**Issue by KiligFei** [clash-verge-rev/clash-verge-rev#1878]
### 功能描述 / Feature description

目前uos国产操作系统使用 arm64.deb格式的，rc那个版本暂时没有提供这个格式的，1.7.7那个版本安装后无法显示界面，只有托盘

### 使用场景 / Use case

uos国产系统

**Comment by wonfen** [comment]
有的，再看看。
