### ISSUE TITLE
[Feature] 订阅链接能否支持 file:/// 协议?

### ISSUE THREAD

**Issue by kokutoukiritsugu** [clash-verge-rev/clash-verge-rev#1879]
### 功能描述 / Feature description

file:///D:/OneDrive/clash.yml

订阅类似这种本地文件的链接
文件通过网盘同步

各种浏览器都是支持这种访问本地文件的
![Snipaste_2024-10-19_08-45-30](https://github.com/user-attachments/assets/cea2b480-35ef-4c9d-9732-7ec0bd93cda9)

### 使用场景 / Use case

因为有些网盘外链被封禁无法使用

**Comment by wonfen** [comment]
订阅连接放网盘里？订阅连接难道不是机场提供？

**Comment by kokutoukiritsugu** [comment]
自建的 没地方放链接啊
自己搭链接的话 注册域名啥的
所以就放网盘完事了
