### ISSUE TITLE
[Feature]作者大大，可否在代理组向下滚动时悬浮标题？

### ISSUE THREAD

**Issue by black23eep** [clash-verge-rev/clash-verge-rev#188]
### Is your feature request related to a problem? Please describe.

在向下翻页时会不能清晰确定当前代理组是哪个，添加一个如vscode中stickyscroll的功能

### Describe the solution you'd like

让代理组标题悬浮在当前代理组的范围。

当向下滚动时让当前代理组标题悬浮在顶部

这样能清晰知道当前代理组是哪一个

### Describe alternatives you've considered

或者添加一键折叠所有代理组的功能

**Comment by lzg45963** [comment]
用外部控制面板选择节点

**Comment by Inside-yourself** [comment]
用外部控制面板选择节点

**Comment by wonfen** [comment]
你说哪个标题？截图看看
