### ISSUE TITLE
[BUG] 导入订阅会切换到第一个订阅

### ISSUE THREAD

**Issue by tangwenlongNO1** [clash-verge-rev/clash-verge-rev#1881]
### 问题描述 / Describe the bug

导入订阅后会切换到列表第一个配置文件

### 复现步骤 / To Reproduce

导入一个新订阅

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

22H2 19045.5011

### 日志 / Log

无

**Comment by wonfen** [comment]
已知bug；2.0版修复了。
