### ISSUE TITLE
[BUG] tun模式下节点全部使用不了

### ISSUE THREAD

**Issue by longge889** [clash-verge-rev/clash-verge-rev#1885]
### 问题描述 / Describe the bug

系统代理下节点正常使用，打开tun模式节点全部失效
![1729429472873](https://github.com/user-attachments/assets/f9c93467-f9e9-4ccd-9ce9-39db0160dd54)

### 复现步骤 / To Reproduce

系统代理下节点正常使用，打开tun模式节点全部失效
![1729429472873](https://github.com/user-attachments/assets/bbc4b9aa-9ab9-4577-90d4-709b1a87985f)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11

### 日志 / Log

10-20 21:52:33info
[TCP] 127.0.0.1:64880 --> mainnet.skalenodes.com:443 using GLOBAL
10-20 21:52:33info
[TCP] 127.0.0.1:64881 --> server.crystalcave.world3.ai:443 using GLOBAL

**Comment by wonfen** [comment]
检查配置文件；参考：
https://github.com/clash-verge-rev/clash-verge-rev/issues/1880

**Comment by longge889** [comment]
昨天用不了，今天早上打开又全部正常了，我什么设置都没改，就是有时候正常，有时候用不了，不知道哪里问题，我是这方面小白，有又没大佬通俗易懂的说下怎么解决，跪谢~

**Comment by jdjxk** [comment]
自行添加DNS配置段
