### ISSUE TITLE
[BUG] win11 v2.0.0-rc2版本，快捷键导致软件自动关闭

### ISSUE THREAD

**Issue by ilovelxy** [clash-verge-rev/clash-verge-rev#1888]
### 问题描述 / Describe the bug

在verge中设置关闭/打开面板的快捷键为ctrl+i,然后按几次ctrl+i反复打开与关闭面板，大概在按下第2-3次的时候verge会自己退出

### 软件版本 / Verge Version

v2.0.0-rc.2

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 23h2

### 日志 / Log

无

**Comment by wonfen** [comment]
已知上游问题，有方法绕过，等下次更新。

**Comment by wonfen** [comment]
在上游未修复之前，打开关闭快捷键功能改为最小化和恢复窗口。
