### ISSUE TITLE
[BUG] 有个小问题，左键点击，会闪一下点右键的菜单

### ISSUE THREAD

**Issue by yixiuge301** [clash-verge-rev/clash-verge-rev#1890]
### 问题描述 / Describe the bug

单击左键，会闪一下点右键的菜单，实际并没有单击右键

第二次单击右键，其他都是左键盘点击
![20241021_102006](https://github.com/user-attachments/assets/f96fe94f-23d0-48ab-a14c-283a0c87045f)

### 软件版本 / Verge Version

Clash.Verge_2.0.0-rc.2_x64

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

无

**Comment by wonfen** [comment]
以后慢慢修

**Comment by liyinred** [comment]
同样有这个bug (win11 24H2)

**Comment by lllxh** [comment]
同样有问题，保留这个issue吧

**Comment by wonfen** [comment]
修复了。
