### ISSUE TITLE
[BUG] bash 命令行导入环境变量后无法ping通google

### ISSUE THREAD

**Issue by normalbut** [clash-verge-rev/clash-verge-rev#1891]
### 问题描述 / Describe the bug

bash 命令行导入环境变量：export https_proxy=http://127.0.0.1:7897 http_proxy=http://127.0.0.1:7897 all_proxy=socks5://127.0.0.1:7897
然后命令行指令无法实现代理：用的ping www.google.com进行的测试

### 软件版本 / Verge Version

v1.5.11

### 复现步骤 / To Reproduce

开的是规则模式、系统代理和Tun模式

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

ubuntu20.04

### 日志 / Log

无

**Comment by wonfen** [comment]
不再接受1.x版本的反馈。请下载2.0版本。
另外，你的问题是ping，目前的所有正向代理，无法代理icmp协议，所以都无法ping。
