### ISSUE TITLE
[BUG]  "可使用 Ctrl(cmd)+Q 快捷键退出程序"，在热键设置里没有相关设置，并且也没有实际效果，还会占用到其他软件的热键设置。

### ISSUE THREAD

**Issue by Azhc** [clash-verge-rev/clash-verge-rev#1894]
### 问题描述 / Describe the bug

 "可使用 Ctrl(cmd)+Q 快捷键退出程序"，在热键设置里没有相关设置，热键设置全部为空，但程序还是占用这个快捷键，并且也没有实际效果，还会占用到其他软件的热键设置。

### 软件版本 / Verge Version

Clash.Verge_2.0.0-rc.2

### 复现步骤 / To Reproduce

热键。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11 24H2

### 日志 / Log

1

**Comment by cxl253386709** [comment]
同样的问题

**Comment by wonfen** [comment]
这个是之前很多人要求添加的程序默认的退出快捷键功能；无需设置。

**Comment by Azhc** [comment]
额。。这个是不是改成配置项可自定义好一点。。其他常用软件的快捷键就是这个。。

**Comment by wonfen** [comment]
> 额。。这个是不是改成配置项可自定义好一点。。其他常用软件的快捷键就是这个。。

最近版本已经修复了之前全局生效的bug。只有窗口在最前面激活状态才会触发退出。

**Comment by Azhc** [comment]
> > 额。。这个是不是改成配置项可自定义好一点。。其他常用软件的快捷键就是这个。。
> 
> 最近版本已经修复了之前全局生效的bug。只有窗口在最前面激活状态才会触发退出。

我刚更新了，窗口在最前面激活状态是可以退出了，但是其他程序在前台时候，使用快捷键还是失效的，退出clash后就好了。

**Comment by wonfen** [comment]
> > > 额。。这个是不是改成配置项可自定义好一点。。其他常用软件的快捷键就是这个。。
> > 
> > 
> > 最近版本已经修复了之前全局生效的bug。只有窗口在最前面激活状态才会触发退出。
> 
> 我刚更新了，窗口在最前面激活状态是可以退出了，但是其他程序在前台时候，使用快捷键还是失效的，退出clash后就好了。

“但是其他程序在前台时候，使用快捷键还是失效的”

什么快捷键是失效的？

**Comment by Azhc** [comment]
> > > > 额。。这个是不是改成配置项可自定义好一点。。其他常用软件的快捷键就是这个。。
> > > 
> > > 
> > > 最近版本已经修复了之前全局生效的bug。只有窗口在最前面激活状态才会触发退出。
> > 
> > 
> > 我刚更新了，窗口在最前面激活状态是可以退出了，但是其他程序在前台时候，使用快捷键还是失效的，退出clash后就好了。
> 
> “但是其他程序在前台时候，使用快捷键还是失效的”
> 
> 什么快捷键是失效的？有没有检查是否和其他程序的快捷键有冲突？

Ctrl(cmd)+Q这个，我是在用vs2022时候发现的，其他程序也退出了，只有verge和vs2022时候就会失效，退出verge就正常了。所以我觉得这个是不是可以放到热键设置里面可以自定义比较好。

**Comment by YasinMorgan** [comment]
是的，比如我后台挂着clash，前台玩着游戏，然后有个技能的快捷键是Ctrl+Q，那这个技能就按不出来，快捷键失效。
确实建议自定义热键比较好。

**Comment by coronanimo** [comment]
同样有这个BUG，导致DOTA2里面Ctrl+Q升级不了技能
