### ISSUE TITLE
[BUG] Debian12无法启动

### ISSUE THREAD

**Issue by AXFOX** [clash-verge-rev/clash-verge-rev#1895]
### 问题描述 / Describe the bug

xfox@JiaoLong5-76s:~$ clash-verge
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.5/src/app.rs:1132:11:
Failed to setup app: error encountered during setup hook: 没有那个文件或目录 (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
已放弃（核心已转储）

### 软件版本 / Verge Version

https://github.com/clash-verge-rev/clash-verge-rev/releases/download/alpha/Clash.Verge_2.0.0-rc.2_amd64.deb
今天下午3:31。

### 复现步骤 / To Reproduce

apt 卸载1.7.7再安装Clash.Verge_2.0.0-rc.2_amd64.deb 启动

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Debian12 KDE Wayland

### 日志 / Log

xfox@JiaoLong5-76s:~$ clash-verge
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.5/src/app.rs:1132:11:
Failed to setup app: error encountered during setup hook: 没有那个文件或目录 (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
已放弃（核心已转储）

**Comment by wonfen** [comment]
修复了，下载最新版试试。
