### ISSUE TITLE
[BUG] tun模式启动后无法连接网络

### ISSUE THREAD

**Issue by liuhuo23** [clash-verge-rev/clash-verge-rev#1896]
### 问题描述 / Describe the bug

启动tun模式下，电脑无法链接网络，包括无法访问百度

### 软件版本 / Verge Version

2.0.rc.2

### 复现步骤 / To Reproduce

启动tub模式

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15

### 日志 / Log

fail install service

**Comment by wonfen** [comment]
检查配置文件规则。之前有人反馈用了ACL4SSR规则有问题：

https://github.com/clash-verge-rev/clash-verge-rev/issues/1880
