### ISSUE TITLE
[BUG]  mac 双重图标并且图标漂移

### ISSUE THREAD

**Issue by AldousShou** [clash-verge-rev/clash-verge-rev#1898]
### 问题描述 / Describe the bug

mac 中存在多个菜单栏图标，并且图标位置影响正常 mac 使用
左边的图标能够正常激活功能，但是会概率挡住 apple 键
<img width="202" alt="image" src="https://github.com/user-attachments/assets/36474908-8396-41b2-a15e-4c2ff649110b">
<img width="306" alt="image" src="https://github.com/user-attachments/assets/b4096393-c6db-414d-8d62-eb09e6e7418e">

### 软件版本 / Verge Version

2.0.0

### 复现步骤 / To Reproduce

不需要

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.0.1

### 日志 / Log

[2024-10-21-1651.log](https://github.com/user-attachments/files/17458060/2024-10-21-1651.log)

**Comment by wonfen** [comment]
看文档： https://www.clashverge.dev/faq/macos.html#macos_1
