### ISSUE TITLE
[BUG]TUN模式无法开启

### ISSUE THREAD

**Issue by jcfun** [clash-verge-rev/clash-verge-rev#190]
### Describe the bug

Arch Linux下使用appimage包无法授权clash-meta内核导致tun模式无法开启
![2023-12-26_14-35](https://github.com/clash-verge-rev/clash-verge-rev/assets/58456995/4d2bc2d4-46b2-4b30-bc73-fc6867ddaf5d)
![2023-12-26_14-36](https://github.com/clash-verge-rev/clash-verge-rev/assets/58456995/965d8024-1544-4602-a7b7-65c8a2deb36e)

使用aur中的clash-verge-rev-bin包可以正常开启tun模式，但是代理组显示空白界面且“局域网连接”和“IPv6”功能无法打开，显示：Network Error
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/58456995/dd956850-67b1-43b5-ac92-9c4f3b752833)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/58456995/b071a908-e7f2-4a2a-bdef-6d737efc7561)

### To Reproduce

无

### Platform

Linux

### System Version

6.6.8-zen1-1-zen (64-bit)

### Software Version

1.4.5

**Comment by jcfun** [comment]
aur中的包clash-verge和本项目都是无法显示代理组，检查没有发现端口占用等问题。而直接为clash-meta添加权限的方法，因为appimage好像使用的是内置的clash-meta内核，因此也无法生效

**Comment by MystiPanda** [comment]
aur的包我测试可以正常使用

**Comment by wonfen** [comment]
从日志提示看没有权限也是一个原因。现在这个问题如何了？

**Comment by wonfen** [comment]
无近一步反馈，关闭。
