### ISSUE TITLE
[BUG]  真是奇怪的BUG  ,    用着用着突然所有流量全部无法转发了,   等我退出class verge 进程,  重新打开就又好了 ,无法复现

### ISSUE THREAD

**Issue by Super1Windcloud** [clash-verge-rev/clash-verge-rev#1903]
### 问题描述 / Describe the bug

[BUG]  真是奇怪的BUG  ,    用着用着突然所有流量全部无法转发了,   等我退出class verge 进程,  重新打开就又好了 ,无法复现

### 软件版本 / Verge Version

[BUG]  真是奇怪的BUG  ,    用着用着突然所有流量全部无法转发了,   等我退出class verge 进程,  重新打开就又好了 ,无法复现

### 复现步骤 / To Reproduce

[BUG]  真是奇怪的BUG  ,    用着用着突然所有流量全部无法转发了,   等我退出class verge 进程,  重新打开就又好了 ,无法复现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11     

### 日志 / Log

[BUG]  真是奇怪的BUG  ,    用着用着突然所有流量全部无法转发了,   等我退出class verge 进程,  重新打开就又好了 ,无法复现

**Comment by Super1Windcloud** [comment]
软件界面重新开关代理也是无效的  ,很是费解 ,让我感到非常困惑!!!

**Comment by Super1Windcloud** [comment]
那一瞬间我都慌了, 还以为网卡出问题了

**Comment by wonfen** [comment]
提供的内容不全，无法判断。按要求提供完整信息后重开issue
