### ISSUE TITLE
[BUG] DNS设置中ipv6: false设置不生效

### ISSUE THREAD

**Issue by Ptilopsis01** [clash-verge-rev/clash-verge-rev#1906]
### 问题描述 / Describe the bug

如题，我在全局配置文件中设置了dns，其中将ipv6设置为了false，且设置界面中也未启用ipv6，但更新后发现该规则未生效，在日志中可以看到很多ipv6的连接，导致很多网址访问时的规则失效
![image](https://github.com/user-attachments/assets/5644e6d4-f731-4e70-a90a-ccc256c32feb)

### 软件版本 / Verge Version

2.0.0 alpha-rc2

### 复现步骤 / To Reproduce

如上所述

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 26100.2152

### 日志 / Log

[2024-10-22-0048.log](https://github.com/user-attachments/files/17464533/2024-10-22-0048.log)

**Comment by wonfen** [comment]
这部分由内核处理，GUI不做干预，2个排查方法：
打开软件设置，查看“当前配置”（为内核运行时配置），检查规则是否被加载。

最佳实践为：
使用fakeip模式，打开软件设置的ipv6，这样基本可以保证不会出现这样ipv6走了直连的问题。
