### ISSUE TITLE
[BUG] GeoIP 优先级异常

### ISSUE THREAD

**Issue by Ptilopsis01** [clash-verge-rev/clash-verge-rev#1907]
### 问题描述 / Describe the bug

不确定和#1906 哪个才是真正的原因，所以再提一个
例如我在规则里包含了bing.com使用某个代理组的配置，但实际访问或使用curl测试时发现日志中均显示的是GeoIP（CN），然后导向了直连，并没有经过我的配置文件查找

### 软件版本 / Verge Version

2.0.0 alpha-rc2

### 复现步骤 / To Reproduce

如上所述

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 26100.2152

### 日志 / Log

[2024-10-22-0059.log](https://github.com/user-attachments/files/17464868/2024-10-22-0059.log)

**Comment by wonfen** [comment]
检查配置文件规则，规则由上到下匹配。规则部分由内核处理。
