### ISSUE TITLE
[BUG] 全局配置被合并后，配置值缺少引号

### ISSUE THREAD

**Issue by shuifa** [clash-verge-rev/clash-verge-rev#1910]
### 问题描述 / Describe the bug

<img width="502" alt="global" src="https://github.com/user-attachments/assets/27283c9e-2b3a-4289-bf19-4dc1be3bfb8b">
<img width="483" alt="image" src="https://github.com/user-attachments/assets/bfc4c72c-f0c4-4e90-89ba-c820ea22d9f6">
如图所示，配置合并后少了引号。我看配置规则有通配符需要使用引号包裹

### 软件版本 / Verge Version

1.7.7

### 复现步骤 / To Reproduce

1、全局配置增加配置，值使用引号
2、查看当前配置

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

版本15.0.1 (24A348)

### 日志 / Log

无

**Comment by Tychristine** [comment]
自动单引号了；你更新了再看看吧
#### 全局配置示例
![image](https://github.com/user-attachments/assets/3248b7de-5848-4ef9-b52b-d3d7b68a6cc9)

#### Runtime效果
![image](https://github.com/user-attachments/assets/c8525d87-9f35-44e7-a1c2-6a6575c5ab8b)

OS Windows11 Pro 26100 x64
Verge Rev Version:  afde7e4

**Comment by shuifa** [comment]
> https://helm.sh/zh/docs/chart_template_guide/yaml_techniques/#yaml%E4%B8%AD%E7%9A%84%E5%AD%97%E7%AC%A6%E4%B8%B2
> 
> 没引号也符合yaml规范，能解析没报错就行

*,+或者.  是否是配置文件的特殊符号，用来解析的，比如我看文档好像&可以引用，*可以解析值，所以有特殊符号的应该还是需要引号的

**Comment by Tychristine** [comment]
@shuifa #1887 表示不再接受1.x版本的反馈。建议用PreReleases升级以后再说

**Comment by shuifa** [comment]
升级最新版本可以解决
