### ISSUE TITLE
[BUG] DNS劫持服务未正常启用

### ISSUE THREAD

**Issue by Ptilopsis01** [clash-verge-rev/clash-verge-rev#1911]
### 问题描述 / Describe the bug

如题所述，此前在#1906 #1907 中提到的问题现在个人怀疑是因为DNS劫持未正常启用，因为在日志中所有的记录显示均为IP直连

### 软件版本 / Verge Version

2.0.0 alpha-rc2

### 复现步骤 / To Reproduce

如上所述，备份profile文件夹和profile.yaml文件后完全删除1.7.7版本，再安装2.0版本并将备份文件复制到配置文件夹，启动软件并调整设置

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 26100.2152

### 日志 / Log

[2024-10-22-0128.log](https://github.com/user-attachments/files/17473402/2024-10-22-0128.log)

**Comment by wonfen** [comment]
1.7.7相同配置工作正常？

**Comment by Ptilopsis01** [comment]
> 1.7.7相同配置工作正常？

是的，1.7.7中配置文件可以正常生效

**Comment by wonfen** [comment]
试试在网卡设置中添加一个223.5.5.5的DNS：
设置方法: https://www.alidns.com/knowledge?type=SETTING_DOCS#user_windows

**Comment by Ptilopsis01** [comment]
> 试试在网卡设置中添加一个223.5.5.5的DNS： 设置方法: https://www.alidns.com/knowledge?type=SETTING_DOCS#user_windows

我理解是dns服务应该直接把所有dns请求都劫持了，那系统dns设置应该不会有任何影响吧

**Comment by wonfen** [comment]
> > 试试在网卡设置中添加一个223.5.5.5的DNS： 设置方法: https://www.alidns.com/knowledge?type=SETTING_DOCS#user_windows
> 
> 我理解是dns服务应该直接把所有dns请求都劫持了，那系统dns设置应该不会有任何影响吧

2.0和1.7唯一改动可能导致问题的地方就是不再强制修改系统dns；你先试试手动设置dns；记得反馈。

**Comment by Ptilopsis01** [comment]
试了一下还是不行，日志里全是显示的IP直连，并且在我把dns服务的ipv6和设置中的ipv6都关掉的情况下，仍然可以在日志里看到大量的ipv6地址，此外在tun设置里开启严格路由会导致无法联网（但测速正常）

**Comment by Ptilopsis01** [comment]
> tg联系我远程看看吧 @wonfen_bot

OK，已经发消息了

**Comment by Ptilopsis01** [comment]
经排查是ACL规则集的原因，可能和内核版本更新有关，换用其他代理规则可解决

**Comment by Ptilopsis01** [comment]
好像还是不太对，我用1.7.7版本更新到了最新的内核，规则解析仍然是正常的，感觉不太像完全是规则或者内核的原因

**Comment by wonfen** [comment]
> 2.0和1.7唯一改动可能导致问题的地方就是不再强制修改系统dns；你先试试手动设置dns

再试试这个：

2.0和1.7唯一改动可能导致问题的地方就是不再强制修改系统dns；你先试试手动设置dns的情况

**Comment by Ptilopsis01** [comment]
> > 2.0和1.7唯一改动可能导致问题的地方就是不再强制修改系统dns；你先试试手动设置dns
> 
> 再试试这个：
> 
> 2.0和1.7唯一改动可能导致问题的地方就是不再强制修改系统dns；你先试试手动设置dns的情况

这个我之前试过了，没用

**Comment by wonfen** [comment]
> 我靠解决了，dns配置里必须要手动设置enable: true，旧版本在tun模式下我记得文档里写的是自动覆盖该配置的

这个true的问题修复了。
