### ISSUE TITLE
[BUG] 生成的clash-verge.yaml文件缩进层次不对

### ISSUE THREAD

**Issue by sagasm** [clash-verge-rev/clash-verge-rev#1913]
### 问题描述 / Describe the bug

 生成的clash-verge.yaml部分文本如下:
```yaml
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
```
是否能生成带缩进的格式:
```yaml
  fake-ip-filter:
    - +.lan
    - +.local
    - +.msftconnecttest.com
    - +.msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - localhost.work.weixin.qq.com
```
不然用编辑器查看时大纲是错误的.

### 软件版本 / Verge Version

clash verge v2.0.0-rc.2

### 复现步骤 / To Reproduce

打开配置目录, 用编辑器打开clash-verge.yaml

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10 22H2

### 日志 / Log

无

**Comment by lbb00** [comment]
应用启动时会强制格式化 config.yaml，缩进也是错误的，并且会丢失注释。
这对使用版本控制管理配置不友好。

**Comment by wonfen** [comment]
文件处理是由标准版库处理的，没法修改缩进了，而且这个缩进也很标准，没有问题。
至于注释的问题，也没想到好方法保留，因为配置文件需要进行几轮处理加工（包括全局脚本，全局扩展，以及一堆功能覆写）

没有缩进会导致什么问题呢？用什么编辑器查看时大纲是错误的？

**Comment by Tychristine** [comment]
![image](https://github.com/user-attachments/assets/dc23a263-c2b5-4f41-8386-354269abf244)
如图所示，`YAML`扩展语法检查没有检出语法错误
`Mihomo Core`也没有警告或直接抛出错误,并且运行状况良好

**这个issue似乎以一种奇怪的方式"解决了"?**
