### ISSUE TITLE
[BUG] The TUN mode doesn't work normally

### ISSUE THREAD

**Issue by Nerooo-g** [clash-verge-rev/clash-verge-rev#1918]
### 问题描述 / Describe the bug

When I launch the Clash Verge, the Tun mode starts automatically and cannot be turned off through either the UI panel or the taskbar icon. Additionally, switching the kernel does not resolve the issue.

### 软件版本 / Verge Version

2.0.0 RC2, October 22nd at 3:07 AM EST.

### 复现步骤 / To Reproduce

Please refer to **[Describe the bug]**

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 27729.1000

### 日志 / Log

I already uninstalled it, however, this problem occurred from the RC1 version.

**Comment by Tychristine** [comment]
The field [Tun.enable.true] in custom profile, so Clash Verge REV didn't Override this field as default.
keep it turn off by default

```yaml
tun:
  enable: false
```

**Comment by Nerooo-g** [comment]
> The field [Tun.enable.true] in custom profile, so Clash Verge REV didn't Override this field as default. keep it turn off by default
> 
> ```yaml
> tun:
>   enable: false
> ```

Thank you for your response. I discovered that my script was causing the issue.
