### ISSUE TITLE
[BUG]系统代理开关UI延迟很大

### ISSUE THREAD

**Issue by FtyLollipop** [clash-verge-rev/clash-verge-rev#192]
### Describe the bug

开启/关闭系统代理时，UI的状态刷新很慢，最长可能要20秒才会刷新（任务栏图标颜色、图标右键菜单）

这么久了一直这样，真的没有其他人遇到？？？

### To Reproduce

开启/关闭系统代理

### Platform

Windows

### System Version

Windows 11 22621.2861

### Software Version

1.4.5

**Comment by FtyLollipop** [comment]
得

**Comment by MrRohwei** [comment]
我的也有这个问题，是什么情况啊？

**Comment by MrRohwei** [comment]
> > 我的也有这个问题，是什么情况啊？
> 
> 我已经换回cfw了，用了一圈还是cfw最好用

cfw配置过滤的时候只能一个一个配置，不支持*.xxx.com
