### ISSUE TITLE
[Feature] 开机暂未自启动clash时系统无法访问互联网

### ISSUE THREAD

**Issue by Amamiya23** [clash-verge-rev/clash-verge-rev#1921]
### 功能描述 / Feature description

如果使用了clash作为系统代理，windows开机后因为需要一步一步加载启动项目，当clash还没完成加载时，这时系统是没网的，无法连接网络，只有加载出clash后才正常访问网络。因此我建议：
1. 在软件中添加“设置高优先级的功能”，类似于wallpapaer engine如图所示的功能。
![ui32_4NkQkfq7Gc](https://github.com/user-attachments/assets/b87288ad-0d85-4ec8-9021-0c9fe6a89fba)

2. 可以添加一个更简单的功能，关机时自动关闭代理，开机时自动开启代理

### 使用场景 / Use case

设置系统代理后。windows开机后再clash没有启动的前十几秒是无法访问互联网的，这对体验的影响非常糟糕，无异于开机时间延长了十几秒！

**Comment by Tychristine** [comment]
系统关机命令是直接kill进程
正确的关闭操作是 "右键托盘图标->退出"
或者在ClashVergeREV的**设置页面**点击**exit(退出)项**;
开机无网络是由于不正确操作造成的, 这点在 [官网-常见问题](https://www.clashverge.dev/faq/windows.html#clash)当中有提到;
已知ClashVergeRev在**正常退出时会自动清除**代理环境

**Comment by Amamiya23** [comment]
按照官网的方法关闭系统代理的话，那岂不是也无法使用clash了，哈哈

**Comment by Tychristine** [comment]
@Amamiya23 意思是你开机无网络是由于ClashVergeREV的进程异常结束造成的；
要避免无网络就正常退出Verge

**Comment by Amamiya23** [comment]
> @Amamiya23 意思是你开机无网络是由于ClashVergeREV的进程异常结束造成的； 要避免无网络就正常退出Verge

这样显然过于麻烦了，可以考虑加入新功能解决，不如总不能每次关机前关闭clash verge吧

**Comment by VincentAdamNemessisX** [comment]
那应该考虑搞一个服务来识别电脑关机，然后通过正常方式调用clash verge的退出指令来达到这样的目的

**Comment by Amamiya23** [comment]
> 那应该考虑搞一个服务来识别电脑关机，然后通过正常方式调用clash verge的退出指令来达到这样的目的

其实重点不在于这个，重点是开启后clash自启动慢，占用代理导致系统没网。因此可以重点放在提升clash启动优先级这件事上。

**Comment by CodingOctocat** [comment]
其实就应该添加一个简单的后台服务，关机/开机时清除代理环境。

**Comment by Tychristine** [comment]
@CodingOctocat 有这样的功能，只需要你右键托盘菜单点击退出，或者在 GUI-设置-退出
这样就完全清除此前设置的代理环境了

**Comment by CodingOctocat** [comment]
@Tychristine 偶尔会忘记，我试着用 C#或脚本实现个服务看看，程序就是为了偷懒🤣

**Comment by ilyfairy** [comment]
希望能增强一下`退出软件自动关闭代理`,  
v2rayN 在系统正常关机的时候是能关闭系统代理的(除非断电),  
clash-verge-rev 在每次正常关机的时候并不会关闭代理

**Comment by ilyfairy** [comment]
> 希望能增强一下`退出软件自动关闭代理`, v2rayN 在系统正常关机的时候是能关闭系统代理的(除非断电), clash-verge-rev 在每次正常关机的时候并不会关闭代理

如果是 C#/WPF 的话, 有个 System.Windows.Application.SessionEnding 事件, 能够在关机的时候触发  
https://learn.microsoft.com/zh-cn/dotnet/api/system.windows.application.sessionending

**Comment by BlueSkyClouds** [comment]
我每次开机都需要 关闭自启的clash再重新手动启用一次 才能连上网络，开机自动启动打开 配置全部没了

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1558

重复关闭
