### ISSUE TITLE
[BUG] MacOS下托盘图标未正确适配背景颜色

### ISSUE THREAD

**Issue by s235784** [clash-verge-rev/clash-verge-rev#1923]
### 问题描述 / Describe the bug

深色背景时，图标为白色显示正常
<img width="176" alt="image" src="https://github.com/user-attachments/assets/32251326-0c4c-423b-b145-6def85db2188">

浅色背景时，clash图标应与其他图标一样渲染为黑色
<img width="178" alt="image" src="https://github.com/user-attachments/assets/f0a85f61-c4b4-489c-9542-c05503458145">

该问题在更新至2.0后出现。
已确认未配置自定义图标，且“托盘图标”选择为“单色图标”。

### 软件版本 / Verge Version

Clash Verge 2.0.0-rc.3

### 复现步骤 / To Reproduce

1. 打开Clash Verge
2. 开启托盘图标

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.0.1

### 日志 / Log

\-

**Comment by s235784** [comment]
[197f9fd](https://github.com/clash-verge-rev/clash-verge-rev/commit/197f9fd964d6164bf9cec0a2ce6eb3347c90803d)中修复了不变色的问题，但是系统代理模式和TUN模式下图标不会改变
<img width="171" alt="image" src="https://github.com/user-attachments/assets/7b0dfaff-1550-4d77-a970-68c9a081f1fb">
<img width="176" alt="image" src="https://github.com/user-attachments/assets/27d74ac5-4cda-484d-99ae-700e29caab55">

**Comment by wonfen** [comment]
> [197f9fd](https://github.com/clash-verge-rev/clash-verge-rev/commit/197f9fd964d6164bf9cec0a2ce6eb3347c90803d)中修复了不变色的问题，但是系统代理模式和TUN模式下图标不会改变 <img alt="image" width="171" src="https://private-user-images.githubusercontent.com/25566339/380035373-7b0dfaff-1550-4d77-a970-68c9a081f1fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MjE5OTIsIm5iZiI6MTcyOTkyMTY5MiwicGF0aCI6Ii8yNTU2NjMzOS8zODAwMzUzNzMtN2IwZGZhZmYtMTU1MC00ZDc3LWE5NzAtNjhjOWEwODFmMWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA1NDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZjJjODZjMTZhNzAzNDVjMWFmM2Q5MjA3ZDZhMmI2ODY5OGJmZDZkMjRkZjE3YzY3MmU1MjU5ZGZkZTg5NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t0obsCVqlV_Jy0nZR6V2jS-hJ3EeXOk67AdHrkM1y5U"> <img alt="image" width="176" src="https://private-user-images.githubusercontent.com/25566339/380035428-27d74ac5-4cda-484d-99ae-700e29caab55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MjE5OTIsIm5iZiI6MTcyOTkyMTY5MiwicGF0aCI6Ii8yNTU2NjMzOS8zODAwMzU0MjgtMjdkNzRhYzUtNGNkYS00ODRkLTk5YWUtNzAwZTI5Y2FhYjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA1NDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyOTljODBmNmE0MDdhNzgwZjMyZWQwNWEzMjA3NzBhMDI2OTU2NGY2MWFlYjJmZDExZWYxYzc1NGE3ZTA5MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xYjhF1yWPLvRx-bWEjOb-tM1hK4U0UTVIQVMCQqpX4s">

研究了下tauri似乎不支持能变色的情况下，还可以切换显示图标，两个功能只能取其一。

**Comment by downerxl** [comment]
> > [197f9fd](https://github.com/clash-verge-rev/clash-verge-rev/commit/197f9fd964d6164bf9cec0a2ce6eb3347c90803d)中修复了不变色的问题，但是系统代理模式和TUN模式下图标不会改变 <img alt="image" width="171" src="https://private-user-images.githubusercontent.com/25566339/380035373-7b0dfaff-1550-4d77-a970-68c9a081f1fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MjE5OTIsIm5iZiI6MTcyOTkyMTY5MiwicGF0aCI6Ii8yNTU2NjMzOS8zODAwMzUzNzMtN2IwZGZhZmYtMTU1MC00ZDc3LWE5NzAtNjhjOWEwODFmMWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA1NDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZjJjODZjMTZhNzAzNDVjMWFmM2Q5MjA3ZDZhMmI2ODY5OGJmZDZkMjRkZjE3YzY3MmU1MjU5ZGZkZTg5NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t0obsCVqlV_Jy0nZR6V2jS-hJ3EeXOk67AdHrkM1y5U"> <img alt="image" width="176" src="https://private-user-images.githubusercontent.com/25566339/380035428-27d74ac5-4cda-484d-99ae-700e29caab55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MjE5OTIsIm5iZiI6MTcyOTkyMTY5MiwicGF0aCI6Ii8yNTU2NjMzOS8zODAwMzU0MjgtMjdkNzRhYzUtNGNkYS00ODRkLTk5YWUtNzAwZTI5Y2FhYjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA1NDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyOTljODBmNmE0MDdhNzgwZjMyZWQwNWEzMjA3NzBhMDI2OTU2NGY2MWFlYjJmZDExZWYxYzc1NGE3ZTA5MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xYjhF1yWPLvRx-bWEjOb-tM1hK4U0UTVIQVMCQqpX4s">
> 
> 研究了下tauri似乎不支持能变色的情况下，还可以切换显示图标，两个功能只能取其一。

这个确实有，RC1这个TUN模式图标切换还是好的，RC4不行了。

**Comment by wonfen** [comment]
> 这个确实有，RC1这个TUN模式图标切换还是好的，RC4不行了。

因为rc1只显示白色图标。

**Comment by downerxl** [comment]
> > 这个确实有，RC1这个TUN模式图标切换还是好的，RC4不行了。
> 
> 因为rc1只显示白色图标。

目前看是逻辑有点问题，系统代理打开后不管tun模式开不开，都不会显示tun图标了，关掉系统代理后正厂。

**Comment by s235784** [comment]
> > > 这个确实有，RC1这个TUN模式图标切换还是好的，RC4不行了。
> > 
> > 
> > 因为rc1只显示白色图标。
> 
> 目前看是逻辑有点问题，系统代理打开后不管tun模式开不开，都不会显示tun图标了，关掉系统代理后正常。

你仔细读一下这句话吧 “研究了下tauri似乎不支持能变色的情况下，还可以切换显示图标，两个功能只能取其一。”

**Comment by downerxl** [comment]
> > > > 这个确实有，RC1这个TUN模式图标切换还是好的，RC4不行了。
> > > 
> > > 
> > > 因为rc1只显示白色图标。
> > 
> > 
> > 目前看是逻辑有点问题，系统代理打开后不管tun模式开不开，都不会显示tun图标了，关掉系统代理后正常。
> 
> 你仔细读一下这句话吧 “研究了下tauri似乎不支持能变色的情况下，还可以切换显示图标，两个功能只能取其一。”

![recording](https://github.com/user-attachments/assets/74dd7003-b968-4dc3-b4af-8d81c8a4c41f)
这样是否能表达我的意思。至少这个图标切换的逻辑与V1时不一样了。

**Comment by s235784** [comment]
> > > > > 这个确实有，RC1这个TUN模式图标切换还是好的，RC4不行了。
> > > > 
> > > > 
> > > > 因为rc1只显示白色图标。
> > > 
> > > 
> > > 目前看是逻辑有点问题，系统代理打开后不管tun模式开不开，都不会显示tun图标了，关掉系统代理后正常。
> > 
> > 
> > 你仔细读一下这句话吧 “研究了下tauri似乎不支持能变色的情况下，还可以切换显示图标，两个功能只能取其一。”
> 
> 这样是否能表达我的意思。至少这个图标切换的逻辑与V1时不一样了。

懂了，是在彩色图标下的切换问题。建议单开个issue

**Comment by downerxl** [comment]
> > > > > > 这个确实有，RC1这个TUN模式图标切换还是好的，RC4不行了。
> > > > > 
> > > > > 
> > > > > 因为rc1只显示白色图标。
> > > > 
> > > > 
> > > > 目前看是逻辑有点问题，系统代理打开后不管tun模式开不开，都不会显示tun图标了，关掉系统代理后正常。
> > > 
> > > 
> > > 你仔细读一下这句话吧 “研究了下tauri似乎不支持能变色的情况下，还可以切换显示图标，两个功能只能取其一。”
> > 
> > 
> > 这样是否能表达我的意思。至少这个图标切换的逻辑与V1时不一样了。
> 
> 懂了，是在彩色图标下的切换问题。建议单开个issue

我提个pr吧。
