### ISSUE TITLE
[BUG] CPU占用异常

### ISSUE THREAD

**Issue by s235784** [clash-verge-rev/clash-verge-rev#1924]
### 问题描述 / Describe the bug

在**某些**情况下，clash verge ui会占用大量CPU资源，且无法释放，只能通过重启软件解决。

<img width="932" alt="image" src="https://github.com/user-attachments/assets/9bca1630-91eb-4e86-b481-09f9d9ff842d">

<img width="786" alt="image" src="https://github.com/user-attachments/assets/3f4f3e2b-8dbe-414f-8834-8ece4ec88cbd">

### 软件版本 / Verge Version

Clash Verge 2.0.0-rc.3

### 复现步骤 / To Reproduce

该问题没有找到稳定复现的方法，目前已发现的可能复现该问题的情况：

- 打开Clash Verge，打开主界面，随后关闭主界面
- 打开Clash Verge，打开主界面并保持打开状态

该问题在1.x版本中也有出现，但出现概率很低。更新至2.0后出现次数明显增多，且有时能复现多次。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.0.1

### 日志 / Log

[2024-10-25-0135.log](https://github.com/user-attachments/files/17510830/2024-10-25-0135.log)

第一行为我手动点击关闭窗口按钮，到561行我手动退出软件，期间cpu占用持续异常。

**Comment by wonfen** [comment]
我们开发机就是mac，无法复现。
怀疑是你的系统是否安装了某些安全软件与webview/tauri底层冲突。

**Comment by s235784** [comment]
> 我们开发机就是mac，无法复现。 怀疑是你的系统是否安装了某些安全软件与webview/tauri底层冲突。

没有安装任何安全软件

**Comment by wonfen** [comment]
或者你的配置文件、图标、样式修改等等自定义配置触发了某种罕见bug，实在难以排查。

建议重新安装，不修改任何默认配置；只用我们首页推荐的机场订阅导入，试试看能否稳定复现。

**Comment by wonfen** [comment]
复现了，排查ing

**Comment by wonfen** [comment]
没有找到稳定复现的方法，昨天偶然出现了一次；在开发环境下，再也无法复现了。

**Comment by wy0606** [comment]
开机自动启动后cpu占用极高+1

**Comment by wonfen** [comment]
> 开机自动启动后cpu占用极高+1

什么系统？能否稳定复现，截图看看cpu占用。

**Comment by wb4646684** [comment]
macOS 15.0.1使用Clash Verge 2.0.0-rc.4发现同样问题，重启后CPU恢复正常。

**Comment by wonfen** [comment]
> macOS 15.0.1使用Clash Verge 2.0.0-rc.4发现同样问题，重启后CPU恢复正常。

下载最新编译的rc4试试，尝试修复了一下

**Comment by wb4646684** [comment]
> > macOS 15.0.1使用Clash Verge 2.0.0-rc.4发现同样问题，重启后CPU恢复正常。>>下载最新编译的rc4试试，尝试修复了一下![上传图像.png...]（）感谢，已经下载使用中，有问题我在反馈～

**Comment by wb4646684** [comment]
感谢，已更新最新rc4，有问题我在反馈~

> > macOS 15.0.1使用Clash Verge 2.0.0-rc.4发现同样问题，重启后CPU恢复正常。
> 
> 下载最新编译的rc4试试，尝试修复了一下

**Comment by s235784** [comment]
> > macOS 15.0.1使用Clash Verge 2.0.0-rc.4发现同样问题，重启后CPU恢复正常。
> 
> 下载最新编译的rc4试试，尝试修复了一下

使用最新编译的rc4，打开UI界面然后关闭，在重复几次后问题复现

**Comment by wb4646684** [comment]
> > > macOS 15.0.1使用Clash Verge 2.0.0-rc.4发现同样问题，重启后CPU恢复正常。
> > 
> > 
> > 下载最新编译的rc4试试，尝试修复了一下
> 
> 使用最新编译的rc4，打开UI界面然后关闭，在重复几次后问题复现

刚下载的rc4版本，使用这个方式也可以稳定复现

**Comment by maiqingqiang** [comment]
![image](https://github.com/user-attachments/assets/8bb7f9d0-28b7-44c0-882c-2126927034ad)

2024-10-29 14:00:00左右下载的最新rc4  也是cpu占用高

**Comment by Anz-03** [comment]
我刚刚也遇到了这个问题，CPU占用率非常高，然后电脑烫得很，目前是 rc3

**Comment by wonfen** [comment]
RC5尝试修复了，把关闭窗口的逻辑用最小化替换了。同时优化了窗口管理的逻辑。请测试。

**Comment by s235784** [comment]
> RC5尝试修复了，把关闭窗口的逻辑用最小化替换了。同时优化了窗口管理的逻辑。请测试。

用最小化确实是个避免出现这个问题的思路，但是又带来了另外一个问题dock栏会有个窗口关不掉😇
<img width="212" alt="image" src="https://github.com/user-attachments/assets/0ed9ea19-e54a-4121-b587-8f1ce248bd59">

**Comment by wonfen** [comment]
@wb4646684 @s235784 
在tauri底层bug未解决之前
https://github.com/tauri-apps/tauri/issues/11516
https://github.com/tauri-apps/tauri/issues/11120
最小化是最优解了。

**Comment by shcw0405** [comment]
昨天遇到了同样的问题，也是在mac上，v2.4.1版本，重启之后就好了

**Comment by Dragon1573** [comment]
> v2.4.1版本，重启之后就好了

Bro 我们已经 `v2.4.3+autobuild` 了， `v2.4.2` 已事实弃用。
