### ISSUE TITLE
[BUG] 微信聊天中无法正常接收发送图片文件

### ISSUE THREAD

**Issue by Kim22158** [clash-verge-rev/clash-verge-rev#1926]
### 问题描述 / Describe the bug

如题，TUN和系统代理模式下，微信无法正常发送和接收图片文件

### 软件版本 / Verge Version

1.7.7和2.0

### 复现步骤 / To Reproduce

现在抓到错误是 USE OF CLODE NETWORK CONNECTION

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

现在抓到错误是 USE OF CLODE NETWORK CONNECTION

**Comment by hanyaxxx** [comment]
配置是什么样的, 看看连接走的代理ip

**Comment by Tychristine** [comment]
你在群里说是用**全局模式**导致的，这符合预期，因为[微信]本不需要被代理；
暂时关闭
