### ISSUE TITLE
[BUG] debsig: Origin Signature check failed. This deb might not be signed.

### ISSUE THREAD

**Issue by softboy99** [clash-verge-rev/clash-verge-rev#1928]
### 问题描述 / Describe the bug

debian install error：debsig: Origin Signature check failed. This deb might not be signed.

### 软件版本 / Verge Version

1.7.7

### 复现步骤 / To Reproduce

dpkg -i ***.deb

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

debian

### 日志 / Log

no

**Comment by wonfen** [comment]
不再接受1.x版本反馈，请下载alpha 2.0版。有问题重开issue
