### ISSUE TITLE
[Feature]不支持geo-auto-update, geo-update-interval

### ISSUE THREAD

**Issue by bbi8** [clash-verge-rev/clash-verge-rev#193]
### Is your feature request related to a problem? Please describe.

geo-auto-update: true
geo-update-interval: 24
这两参数在Clash字段选项中不显示，无法勾选
文档地址:
https://wiki.metacubex.one/config/general/#geo_2

### Describe the solution you'd like

增加参数支持

### Describe alternatives you've considered

增加参数支持

**Comment by MystiPanda** [comment]
好的，后续会添加，现在你也可以先在杂项设置中关闭字段过滤使用。

**Comment by bbi8** [comment]
> 好的，后续会添加，现在你也可以先在杂项设置中关闭字段过滤使用。

试过了，关闭字段过滤后运行时订阅中还是没有这两配置，订阅配置中是有的。
