### ISSUE TITLE
[BUG] Windows11 下 v2.0.0-rc3 托盘点击事件 会调起功能菜单

### ISSUE THREAD

**Issue by shin-kosaki** [clash-verge-rev/clash-verge-rev#1930]
### 问题描述 / Describe the bug

托盘点击事件（左键）会调起托盘右键菜单

### 软件版本 / Verge Version

v2.0.0-rc3 

### 复现步骤 / To Reproduce

托盘点击事件（左键）会调起托盘右键菜单

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

22631.4317

### 日志 / Log

*

**Comment by Tychristine** [comment]
@shin-kosaki 重复 issue via #1890
