### ISSUE TITLE
[BUG] Debian12 无法启动2.0A rc3 老毛病

### ISSUE THREAD

**Issue by AXFOX** [clash-verge-rev/clash-verge-rev#1931]
### 问题描述 / Describe the bug

和[ISSUE 1895](https://github.com/clash-verge-rev/clash-verge-rev/issues/1895)一样的问题

### 软件版本 / Verge Version

RC3
Created at Sat Oct 26 09:16:21 CST 2024. 

### 复现步骤 / To Reproduce

xfox@JiaoLong5-76s:~/Downloads$ sudo apt install ./Clash.Verge_2.0.0-rc.3_amd64.deb 
正在读取软件包列表... 完成正在分析软件包的依赖关系树... 完成正在读取状态信息... 完成                 
注意，选中 'clash-verge' 而非 './Clash.Verge_2.0.0-rc.3_amd64.deb'
下列软件包是自动安装的并且现在不需要了：  libjavascriptcoregtk-4.0-18 libwebkit2gtk-4.0-37
使用'sudo apt autoremove'来卸载它(它们)。下列软件包将被升级：  clash-verge
升级了 1 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。需要下载 0 B/45.4 MB 的归档。解压缩后会消耗 4,966 kB 的额外空间。获取:1 /home/xfox/Downloads/Clash.Verge_2.0.0-rc.3_amd64.deb clash-verge amd64 2.0.0-rc.3 [45.4 MB]
(正在读取数据库 ... 系统当前共安装有 327723 个文件和目录。)
准备解压 .../Clash.Verge_2.0.0-rc.3_amd64.deb  ...
正在解压 clash-verge (2.0.0-rc.3) 并覆盖 (1.7.7) ...
正在设置 clash-verge (2.0.0-rc.3) ...
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
正在处理用于 mailcap (3.70+nmu1) 的触发器 ...
xfox@JiaoLong5-76s:~/Downloads$ clash-verge
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.5/src/app.rs:1132:11:
Failed to setup app: error encountered during setup hook: 没有那个文件或目录 (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
已放弃（核心已转储）

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Debian12 KDE wayland

### 日志 / Log

xfox@JiaoLong5-76s:~/Downloads$ sudo apt install ./Clash.Verge_2.0.0-rc.3_amd64.deb 
正在读取软件包列表... 完成正在分析软件包的依赖关系树... 完成正在读取状态信息... 完成                 
注意，选中 'clash-verge' 而非 './Clash.Verge_2.0.0-rc.3_amd64.deb'
下列软件包是自动安装的并且现在不需要了：  libjavascriptcoregtk-4.0-18 libwebkit2gtk-4.0-37
使用'sudo apt autoremove'来卸载它(它们)。下列软件包将被升级：  clash-verge
升级了 1 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。需要下载 0 B/45.4 MB 的归档。解压缩后会消耗 4,966 kB 的额外空间。获取:1 /home/xfox/Downloads/Clash.Verge_2.0.0-rc.3_amd64.deb clash-verge amd64 2.0.0-rc.3 [45.4 MB]
(正在读取数据库 ... 系统当前共安装有 327723 个文件和目录。)
准备解压 .../Clash.Verge_2.0.0-rc.3_amd64.deb  ...
正在解压 clash-verge (2.0.0-rc.3) 并覆盖 (1.7.7) ...
正在设置 clash-verge (2.0.0-rc.3) ...
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
正在处理用于 mailcap (3.70+nmu1) 的触发器 ...
xfox@JiaoLong5-76s:~/Downloads$ clash-verge
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.5/src/app.rs:1132:11:
Failed to setup app: error encountered during setup hook: 没有那个文件或目录 (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
已放弃（核心已转储）

亦尝试过先卸载1.7.7再安装，问题不变。

**Comment by wonfen** [comment]
我们专门安装了debain 12测试过，无法复现你的问题
![image](https://github.com/user-attachments/assets/95a76d0e-4625-402d-a65c-7db8de3fe663)

**Comment by AXFOX** [comment]
我很乐意提供其他有关我的运行环境的信息，如果对Debug有帮助的话。

**Comment by wonfen** [comment]
> 我很乐意提供其他有关我的运行环境的信息，如果对Debug有帮助的话。

你用虚拟机安装一个纯净的debain12试试。

**Comment by AXFOX** [comment]
> > 我很乐意提供其他有关我的运行环境的信息，如果对Debug有帮助的话。
> 
> 你用虚拟机安装一个纯净的debain12试试。
![image](https://github.com/user-attachments/assets/c70d2cf9-ac7a-4d6f-a712-156f42feb745)
如图，Debian12.6 KDE live 直接安装rc4，无法启动。

**Comment by pluto0x0** [comment]
Archlinux中遇到相同问题，经排查问题是无法使用xdg-mime注册MIME条目。安装`xdg-utils`包解决。

**Comment by wonfen** [comment]
> > > 我很乐意提供其他有关我的运行环境的信息，如果对Debug有帮助的话。
> > 
> > 
> > 你用虚拟机安装一个纯净的debain12试试。
> > ![image](https://private-user-images.githubusercontent.com/57279704/380368123-c70d2cf9-ac7a-4d6f-a712-156f42feb745.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODA3NTEsIm5iZiI6MTczMDA4MDQ1MSwicGF0aCI6Ii81NzI3OTcwNC8zODAzNjgxMjMtYzcwZDJjZjktYWM3YS00ZDZmLWE3MTItMTU2ZjQyZmViNzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAxNTQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYTZjNTAwZTQ0NjQ4NzE2MWZiOGRiYjE3MTFiOWYyODQxNjczYTU5NmVhYzYwMWYwYTU0OTQ3MzA1ZjE3MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6bJSDPC_23WDQhN_qgZ8T825u-VyJhTbS0E4mg127F4)
> > 如图，Debian12.6 KDE live 直接安装rc4，无法启动。

你试试用sudo运行，看看有没有报错

**Comment by AXFOX** [comment]
> > > > 我很乐意提供其他有关我的运行环境的信息，如果对Debug有帮助的话。
> > > 
> > > 
> > > 你用虚拟机安装一个纯净的debain12试试。
> > > ![image](https://private-user-images.githubusercontent.com/57279704/380368123-c70d2cf9-ac7a-4d6f-a712-156f42feb745.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODA3NTEsIm5iZiI6MTczMDA4MDQ1MSwicGF0aCI6Ii81NzI3OTcwNC8zODAzNjgxMjMtYzcwZDJjZjktYWM3YS00ZDZmLWE3MTItMTU2ZjQyZmViNzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAxNTQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYTZjNTAwZTQ0NjQ4NzE2MWZiOGRiYjE3MTFiOWYyODQxNjczYTU5NmVhYzYwMWYwYTU0OTQ3MzA1ZjE3MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6bJSDPC_23WDQhN_qgZ8T825u-VyJhTbS0E4mg127F4)
> > > 如图，Debian12.6 KDE live 直接安装rc4，无法启动。
> 
> 你试试用sudo运行，看看有没有报错

xfox@JiaoLong5-76s:~$ sudo clash-verge
[sudo] xfox 的密码：thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.6/src/app.rs:1132:11:
Failed to setup app: error encountered during setup hook: 没有那个文件或目录 (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
已放弃
rc5错误相同，我去试试上面安装xdg-utils的方式。
Debian下的错误和xdg-utils应该没什么关系，因为xdg-utils已经安装了
xdg-utils/stable,stable,now 1.1.3-4.1 all [已安装，自动]
  desktop integration utilities from freedesktop.org

**Comment by wonfen** [comment]
rc7修复了。
如果还有问题请新开issue。
