### ISSUE TITLE
[BUG] alpha 的版本不提示更新的么？

### ISSUE THREAD

**Issue by yixiuge301** [clash-verge-rev/clash-verge-rev#1933]
### 问题描述 / Describe the bug

现在安装的是 rc2，但 github 这边已经 rc4 了

### 软件版本 / Verge Version

Clash.Verge_2.0.0-rc.2_x64-setup

### 复现步骤 / To Reproduce

安装 Clash.Verge_2.0.0-rc.2_x64-setup

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

无

**Comment by wonfen** [comment]
alpha通道需要自己更新
