### ISSUE TITLE
[BUG] alpha版本会占用Ctrl+Q键，按下Ctrl+Q是退出，而且无法修改。

### ISSUE THREAD

**Issue by YasinMorgan** [clash-verge-rev/clash-verge-rev#1936]
### 问题描述 / Describe the bug

alpha版本会占用Ctrl+Q键，按下Ctrl+Q是退出，而且无法修改。1.7.7没有问题。

### 软件版本 / Verge Version

version: Clash.Verge_2.0.0-rc.4_x64-setup.exe 
download time: 2024/10/26 15:20

### 复现步骤 / To Reproduce

Just Ctrl+Q.

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win10 Pro 22H2

### 日志 / Log

[2024-10-26-1544.log](https://github.com/user-attachments/files/17529496/2024-10-26-1544.log)

**Comment by Tychristine** [comment]
#1737
https://github.com/tauri-apps/tauri/issues/10546
#1894 
#1756
#1770 
#1814 
#1888 
#1886
