### ISSUE TITLE
[BUG] 2.0.0 RC3版本卸载后，重新安装1.7.7无法启用服务模式

### ISSUE THREAD

**Issue by codetang-2417** [clash-verge-rev/clash-verge-rev#1937]
### 问题描述 / Describe the bug

安装2.0.0 RC3后可正常使用，但重启电脑后打开clash-verge，提示输入密码运行install.service，
![image](https://github.com/user-attachments/assets/fbbf0f02-007c-4fed-ae67-216a258bbc23)

输入密码后将显示无法连接clash，看不到代理界面，并且没有clash内核版本显示。
![image](https://github.com/user-attachments/assets/d79701a9-52bb-4b09-bd77-9ebbaecf097c)

然后卸载 2.0.0 RC3，再次安装1.7.7，就无法启动服务模式了，安装成功后，界面没有变化。
![image](https://github.com/user-attachments/assets/03658860-5120-451d-a805-50a0942a94fe)

### 软件版本 / Verge Version

archlinux
aur/clash-verge-rev-alpha-bin 2.0.0-23 (+1 0.01) 
    Continuation of Clash Verge | A Clash Meta GUI based on Tauri | Alpha Version

### 复现步骤 / To Reproduce

安装2.0.0 RC3后可正常使用，但重启电脑后打开clash-verge，提示输入密码运行install.service，
![image](https://github.com/user-attachments/assets/fbbf0f02-007c-4fed-ae67-216a258bbc23)

输入密码后将显示无法连接clash，看不到代理界面，并且没有clash内核版本显示。
![image](https://github.com/user-attachments/assets/d79701a9-52bb-4b09-bd77-9ebbaecf097c)

然后卸载 2.0.0 RC3，再次安装1.7.7，就无法启动服务模式了，安装成功后，界面没有变化。
![image](https://github.com/user-attachments/assets/03658860-5120-451d-a805-50a0942a94fe)

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Kernel: 6.1.112-1-MANJARO KDE: Plasma 6.1.5 

### 日志 / Log

无法将log等级调整为debug，显示网络错误。
![image](https://github.com/user-attachments/assets/05b936d8-d42b-4968-a1ec-52c1e18bf3fe)

**Comment by codetang-2417** [comment]
手动找到install-service后，sudo install-service，解决安装失败问题。

**Comment by codetang-2417** [comment]
应该是打包的时候没有给运行权限，导致clash-verge-service无法运行，手动给权限后正常。
![image](https://github.com/user-attachments/assets/4603f49f-a01f-4d46-91ee-0da9698eb508)

**Comment by wonfen** [comment]
试试最新的构建，应该修复了这个问题。

**Comment by wonfen** [comment]
无反馈，关闭。
