### ISSUE TITLE
[Feature]请问，可否在后续版本中添加置顶功能？

### ISSUE THREAD

**Issue by shixinwu** [clash-verge-rev/clash-verge-rev#194]
### Is your feature request related to a problem? Please describe.

当前不支持类似Windows任务管理器的“置于顶层”的功能。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/25983787/755c5943-b1eb-4679-8d2d-ab8b3bead1a3)

### Describe the solution you'd like

后期能否增加此功能？将应用置顶，避免被遮挡，方便查看“连接”信息。

### Describe alternatives you've considered

no

**Comment by MystiPanda** [comment]
已添加
