### ISSUE TITLE
[BUG] 无法使用逗号(comma)“,”作为热键、快捷键

### ISSUE THREAD

**Issue by lyy1423** [clash-verge-rev/clash-verge-rev#1940]
### 问题描述 / Describe the bug

无法使用逗号“,”作为热键。
我想使用ALT+,作为开启\关闭面板的开关，但无法使能；单独使用,也无法使能；更改配置文件并设置只读模式也无法使能。

### 软件版本 / Verge Version

v2.0.0-rc.4

### 复现步骤 / To Reproduce

但除了逗号以外全都可以正常使能。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

WINDOWS11

### 日志 / Log

无需日志。

**Comment by sooflowercool** [comment]
我遇到了热键无反应的问题，连按好几次都无法开启系统代理，需要手动开启系统代理后，再按热键才能恢复。软件版本及操作系统如上！

**Comment by wonfen** [comment]
修复了。
