### ISSUE TITLE
[BUG] Ubuntu24.04导入订阅后，代理界面空白

### ISSUE THREAD

**Issue by JayLXL** [clash-verge-rev/clash-verge-rev#1941]
### 问题描述 / Describe the bug

Ubuntu24.04下导入订阅后，代理界面空白，且无法正常使用

### 软件版本 / Verge Version

[Clash.Verge_2.0.0-rc.4_amd64.deb](https://github.com/clash-verge-rev/clash-verge-rev/releases/download/alpha/Clash.Verge_2.0.0-rc.4_amd64.deb)

### 复现步骤 / To Reproduce

导入订阅，打开系统代理选项，进入代理界面

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Ubuntu24.04.1TLS

### 日志 / Log

https://gist.github.com/d15c471c393e3bfc5c35d0d718efb8be.git

**Comment by staywilliam** [comment]
我尝试了rc2和rc4两个版本都有这个bug

**Comment by wonfen** [comment]
> 我尝试了rc2和rc4两个版本都有这个bug

我这边没法复现，没有导入订阅前，代理页面截图看看

**Comment by JayLXL** [comment]
> > 我尝试了rc2和rc4两个版本都有这个bug
> 
> 我这边没法复现，没有导入订阅前，代理页面截图看看

我后来用了1.7.7版本，能够正常使用。然后为了复现，我重新安装了rc4版本，结果发现这个bug消失了？？这个是之前用的时候的截图
![Uploading 9e4b4cb92259b16c8ab71deea473ef9.png…]()

**Comment by staywilliam** [comment]
> > 我尝试了rc2和rc4两个版本都有这个bug
> 
> 我这边没法复现，没有导入订阅前，代理页面截图看看

我重新进行了观察，我观察到的情况是：在初次安装时，代理的界面有直接连接等按钮，但是首次导入订阅后，再进入代理的界面纯空白，如图。
![粘贴的图像](https://github.com/user-attachments/assets/9e3766d4-5cea-4561-9952-b4a140369988)
我认为重要的一点是，我之前没有观察到，它是有报错的，主要报错内容是: "can't download MMDB"。我想如果这两件事是有关联的话，这应该不算是一个bug

**Comment by cinder023** [comment]
我在ubuntu22.04虚拟机上也碰到了这个问题但我的clash版本是1.7.7，你是如何解决的

**Comment by wonfen** [comment]
> 在初次安装时，代理的界面有直接连接等按钮

说明内核成功连接了，还可以观察设置菜单里是否显示内核版本号。

> can't download MMDB

盲猜是你的机场配置有问题；导致导入后内核崩溃配置失效等情况。

**Comment by JayLXL** [comment]
> > https://gist.github.com/d15c471c393e3bfc5c35d0d718efb8be.git
> 
> 从你的日志中没有看到任何报错。
> 
> 再检查下内核日志。
> 
> > 在初次安装时，代理的界面有直接连接等按钮
> 
> 说明内核成功连接了，还可以观察设置菜单里是否显示内核版本号。
> 
> > can't download MMDB
> 
> 盲猜是你的机场配置有问题；导致导入后内核崩溃配置失效等情况。

谢谢，不知道是不是和某些配置的初始化有关，因为安装1.7.7能正常使用，之后再安装2.0rc4，也可以使用了。下面是之前内核的报错，不太懂是不是机场配置的问题
```txt
time="2024-10-27T19:48:01.283459329+08:00" level=info msg="Start initial configuration in progress"
time="2024-10-27T19:48:01.28411413+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-10-27T19:48:01.284125501+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-10-27T19:48:01.28441875+08:00" level=info msg="Can't find MMDB, start download"
time="2024-10-27T19:49:31.285696806+08:00" level=error msg="can't initial GeoIP: can't download MMDB: context deadline exceeded"
time="2024-10-27T19:49:31.28580014+08:00" level=fatal msg="Parse config error: rules[515] [GEOIP,CN,DIRECT] error: can't download MMDB: context deadline exceeded"
```

**Comment by wonfen** [comment]
上面这些报错只是无法下载mmdb的网络异常（无法连接下载）看不出问题。
