### ISSUE TITLE
[BUG]  普通模式非Tun下为什么所有的网站都走代理？

### ISSUE THREAD

**Issue by meteorlad** [clash-verge-rev/clash-verge-rev#1943]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/8697232d-5feb-4334-bcaa-7a7b1067609f)
如上图设置，访问 ip138.com 检测代理是 proxy的地址，设置为tun后就可以分流
ping 的情况下也是都走代理
![image](https://github.com/user-attachments/assets/a2c1b1ac-05d4-4236-8875-9891acbac954)

### 软件版本 / Verge Version

2.0.0
1.7.7

### 复现步骤 / To Reproduce

安装 1.7.7 或者 2.0.0 导入订阅，开启系统代理，访问 https://www.ip138.com 

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

暂无

**Comment by meteorlad** [comment]
为什么分流突然无效？

**Comment by wonfen** [comment]
检查你的配置文件。目前的正向代理都不会代理icmp协议，ping没有意义；如果你发现ping也被代理了，肯定是开启了真VPN。
