### ISSUE TITLE
[BUG] rule-providers 下载失败

### ISSUE THREAD

**Issue by neo-fan** [clash-verge-rev/clash-verge-rev#1944]
### 问题描述 / Describe the bug

配置文件中的 rule-providers会下载失败 导致配置的分流规则无法正常使用
![image](https://github.com/user-attachments/assets/caf5bfa9-d217-4192-bfa6-fb95adbf2c92)
![image](https://github.com/user-attachments/assets/cb7cfc39-3deb-4ec2-ab2f-2f0de9f970a4)

### 软件版本 / Verge Version

v2.00-rc.4 2024/10/28 9:10下载

### 复现步骤 / To Reproduce

激活配置文件即可复现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 24H2

### 日志 / Log
[2024-10-28-0919.txt](https://github.com/user-attachments/files/17536222/2024-10-28-0919.txt)

**Comment by wonfen** [comment]
非bug，自己替换国内可用的地址。

**Comment by neo-fan** [comment]
找到原因了 我的DNS配置文件 proxy-server-nameserver 一开始只配置了DOH 竟然不支持。
加了普通的dns地址就行了
 ![image](https://github.com/user-attachments/assets/9d696c59-7dcb-4d69-aeac-6e6ff39381dc)

**Comment by hezhongfeng** [comment]
@neo-fan 请问你这个 rule-providers 是在哪个文件配置的？

**Comment by neo-fan** [comment]
> @neo-fan 请问你这个 rule-providers 是在哪个文件配置的？

全局配置文件配置覆盖的

**Comment by hezhongfeng** [comment]
能说下具体的文件名吗？
<img width="739" alt="image" src="https://github.com/user-attachments/assets/0f72a26c-7260-430d-a068-aea4e41712c1">

**Comment by neo-fan** [comment]
> 能说下具体的文件名吗？ <img alt="image" width="739" src="https://private-user-images.githubusercontent.com/12163050/393676681-0f72a26c-7260-430d-a068-aea4e41712c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MTYxNzUsIm5iZiI6MTczMzcxNTg3NSwicGF0aCI6Ii8xMjE2MzA1MC8zOTM2NzY2ODEtMGY3MmEyNmMtNzI2MC00MzBkLWEwNjgtYWVhNGU0MTcxMmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAzNDQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZGIzYjA2OWNiYzUwNGJmZDkyMzgwNzNiYmM2NWZjYjBkOGRkNjMyZmQ5NjgxYWJhYmE4MWRjYjdkMDcyZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3lkDOWyeiLD7k9UdXjwKleViRHro53SkkW2l3tQqusk">

![image](https://github.com/user-attachments/assets/ee2fc70b-c9ec-4357-b0e3-f2b90da6bb4a)
[script.txt](https://github.com/user-attachments/files/18057008/script.txt)
具体内容在附件

**Comment by hezhongfeng** [comment]
收到，谢谢。
