### ISSUE TITLE
[BUG] CentOS 安装Clash.Verge-2.0.0-rc.4-1.x86_64.rpm 缺少依赖

### ISSUE THREAD

**Issue by haimian467** [clash-verge-rev/clash-verge-rev#1948]
### 问题描述 / Describe the bug

系统版本：CentOS 7.9.2009 x86_64
安装版本：Clash.Verge-2.0.0-rc.4-1.x86_64.rpm
报错如下：
错误：软件包：clash-verge-2.0.0-rc.4-1.x86_64 (/Clash.Verge-2.0.0-rc.4-1.x86_64)
          需要：libayatana-appindicator3.so.1()(64bit)
错误：软件包：clash-verge-2.0.0-rc.4-1.x86_64 (/Clash.Verge-2.0.0-rc.4-1.x86_64)
          需要：libwebkit2gtk-4.1.so.0()(64bit)
 您可以尝试添加 --skip-broken 选项来解决该问题
 您可以尝试执行：rpm -Va --nofiles --nodigest
centos 官方库不存在如上依赖

### 软件版本 / Verge Version

Clash.Verge-2.0.0-rc.4-1.x86_64.rpm

### 复现步骤 / To Reproduce

安装命令：sudo yum localinstall ./Clash.Verge-2.0.0-rc.4-1.x86_64.rpm

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

CentOS 7.9.2009 x86_64

### 日志 / Log

[root@localhost v2ray]# sudo yum localinstall ./Clash.Verge-2.0.0-rc.4-1.x86_64.rpm
已加载插件：fastestmirror, langpacks
正在检查 ./Clash.Verge-2.0.0-rc.4-1.x86_64.rpm: clash-verge-2.0.0-rc.4-1.x86_64
./Clash.Verge-2.0.0-rc.4-1.x86_64.rpm 将被安装
正在解决依赖关系
--> 正在检查事务
---> 软件包 clash-verge.x86_64.0.2.0.0-rc.4-1 将被 安装
--> 正在处理依赖关系 libayatana-appindicator3.so.1()(64bit)，它被软件包 clash-verge-2.0.0-rc.4-1.x86_64 需要
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: repo.jing.rocks
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
--> 正在处理依赖关系 libwebkit2gtk-4.1.so.0()(64bit)，它被软件包 clash-verge-2.0.0-rc.4-1.x86_64 需要
--> 解决依赖关系完成
错误：软件包：clash-verge-2.0.0-rc.4-1.x86_64 (/Clash.Verge-2.0.0-rc.4-1.x86_64)
          需要：libayatana-appindicator3.so.1()(64bit)
错误：软件包：clash-verge-2.0.0-rc.4-1.x86_64 (/Clash.Verge-2.0.0-rc.4-1.x86_64)
          需要：libwebkit2gtk-4.1.so.0()(64bit)
 您可以尝试添加 --skip-broken 选项来解决该问题
 您可以尝试执行：rpm -Va --nofiles --nodigest

**Comment by haimian467** [comment]
跪求依赖或解决办法

**Comment by wonfen** [comment]
7.9版本会不会太老了一点？用最新的9试试

**Comment by haimian467** [comment]
> 7.9版本会不会太老了一点？用最新的9试试

有可能吧，本地小主机，不折腾了，躺平

**Comment by wonfen** [comment]
> 同求，大佬我也遇到centos7安装缺依赖，希望大佬发个解决方法

7太老了，升级到9试试。

**Comment by mgenl** [comment]
直接使用mihomo内核(原Clash Meta内核) https://github.com/MetaCubeX/mihomo

**Comment by QYG2297248353** [comment]
```
# dnf install clash_verge.rpm --nobest
上次元数据过期检查：2:27:46 前，执行于 2024年11月30日 星期六 18时42分51秒。
错误：
 问题: 冲突的请求
  - nothing provides libwebkit2gtk-4.1.so.0()(64bit) needed by clash-verge-2.0.1-1.x86_64 from @commandline
(尝试添加 '--skip-broken' 来跳过无法安装的软件包)
# yum list installed | grep webkit2gtk
webkit2gtk3.x86_64                               2.46.3-1.el9_5                   @appstream       
webkit2gtk3-devel.x86_64                         2.46.3-1.el9_5                   @appstream       
webkit2gtk3-jsc.x86_64                           2.46.3-1.el9_5                   @appstream       
webkit2gtk3-jsc-devel.x86_64                     2.46.3-1.el9_5                   @appstream 
```

**Comment by xiongzegang** [comment]
> 7.9版本会不会太老了一点？用最新的9试试

使用Rocky Linux release 9.5安装报错如下：
dnf install Clash.Verge-2.0.2-1.x86_64.rpm
Last metadata expiration check: 0:33:10 ago on Tue Dec  3 20:38:48 2024.
Error:
 Problem: conflicting requests
  - nothing provides libwebkit2gtk-4.1.so.0()(64bit) needed by clash-verge-2.0.2-1.x86_64 from @commandline
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by QYG2297248353** [comment]
> 使用Rocky Linux release 9.5安装报错如下： dnf install Clash.Verge-2.0.2-1.x86_64.rpm Last metadata expiration check: 0:33:10 ago on Tue Dec 3 20:38:48 2024. Error: Problem: conflicting requests
> 
> * nothing provides libwebkit2gtk-4.1.so.0()(64bit) needed by clash-verge-2.0.2-1.x86_64 from @commandline
>   (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

AlmaLinux 9 也一样，没办法，装不了
9的发行库里没有这玩意， libwebkit2gtk 和 tauri 官网都看过了，没得办法，似乎只能试试自编译这一条路
没用过 tauri 看看哪位大佬能想想办法

**Comment by QYG2297248353** [comment]
https://github.com/tauri-apps/tauri/issues/9662
参考
![image](https://github.com/user-attachments/assets/75b8ee5f-de0b-43dd-8fcf-24a964a71a1a)

**Comment by SchrodingerFish** [comment]
sudo dnf install ./Clash.Verge-2.0.2-1.x86_64.rpm
上次元数据过期检查：1:09:15 前，执行于 2024年12月05日 星期四 11时52分57秒。
错误：
 问题: 冲突的请求
  - nothing provides libwebkit2gtk-4.1.so.0()(64bit) needed by clash-verge-2.0.2-1.x86_64 from @commandline
(尝试添加 '--skip-broken' 来跳过无法安装的软件包 或 '--nobest' 来不只使用软件包的最佳候选)

CentOS Stream 9 依赖有问题

**Comment by ilanni2460** [comment]
Rocky Linux release 9.3

也是报错：
`
 yum -y install Clash.Verge-2.0.2-1.x86_64.rpm
Repository remi-safe is listed more than once in the configuration
Last metadata expiration check: 0:23:50 ago on Monday, December 30, 2024 PM04:32:03.
Error: 
 Problem: conflicting requests
  - nothing provides libwebkit2gtk-4.1.so.0()(64bit) needed by clash-verge-2.0.2-1.x86_64 from @commandline
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

`

**Comment by zhutmost** [comment]
AlmaLinux9 （约等于RHEL 9）
同样的问题，2.2.2版本

**Comment by szmcdull** [comment]
所以clash-verge-rev的rpm包是用哪个发行版打包的，Fedora？

**Comment by alrcatraz** [comment]
目前对于AlmaLinux9.6这个问题依然存在。有考虑发行appimage或者flatpak吗？

**Comment by Dragon1573** [comment]
> 所以 Clash Verge Rev 的 `rpm` 包是用哪个发行版打包的？

Clash Verge Rev 实际对外发行的预编译二进制文件统一使用 GitHub Workflows 进行构建，而 GitHub 对于 Linux 构建环境仅提供 Ubuntu 。

构建过程中的详细信息可以在 Actions 面板里进入 Workflows / Jobs 日志看到，里面有提及具体使用的 Runner Image 版本。

**Comment by Dragon1573** [comment]
> 有考虑发行 Appimage 或者 Flatpak 吗？

没有，其他发行形式 Collaborators 们尝试过，Appimage 与 Flatpak 形式在实际使用上会有其他问题，所以相关版本也没有被发布上传。

目前官方发行方式仅提供 Windows NSIS `exe` 安装向导、macOS `dmg` 安装镜像、Debian 系 `deb` 安装包和 RedHat 系 `rpm` 安装包。包管理器层面只有 Windows WinGet 的新版本推送是由官方 Workflows 自动化实现的。

Arch 系 AUR 版本是社区成员提供的非官方发行方式，其构建基础来自官方 `deb` 版本。
