### ISSUE TITLE
[BUG] 在新版WSL2 Mirrored Networking Mode下开启tun模式存在网络访问问题

### ISSUE THREAD

**Issue by lsyzc** [clash-verge-rev/clash-verge-rev#1949]
### 问题描述 / Describe the bug

在新版WSL2 Mirrored Networking Mode下开启tun模式 执行sudo apt update 时Could not connect to archive.ubuntu.com:80 (198.18.0.58)113: No route to host) [IP: 198.18.0.58 80]  关闭tun模式恢复正常
怀疑与 Mirrored Networking Mode 与 fake-ip-range不兼容

### 软件版本 / Verge Version

V1.7.7

### 复现步骤 / To Reproduce

![image](https://github.com/user-attachments/assets/8aec0c8a-e034-494e-9f4e-2dfe7dad4ad0)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 11

### 日志 / Log

[2024-10-29-1854.log](https://github.com/user-attachments/files/17556281/2024-10-29-1854.log)

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1887

这个问题请到mihomo内核那边反馈: https://github.com/MetaCubeX/mihomo/issues
