### ISSUE TITLE
[Feature] Light Mode support, 轻量模式支持

### ISSUE THREAD

**Issue by akdriver** [clash-verge-rev/clash-verge-rev#1952]
### 功能描述 / Feature description

Are there any plans to add a light mode feature: completely exit the GUI program and keep only the Clash Meta kernel program？是否有计划增加一个轻量模式的功能：完全退出GUI程序，仅保留Clash Meta内核程序。

### 使用场景 / Use case

Only the kernel program is kept, which greatly saves memory space and is more stable.
仅保留内核程序，极大的节省内存空间，也更具稳定性。

**Comment by Tychristine** [comment]
You may want to find Mihomo Project: https://github.com/MetaCubeX/mihomo
And Clash Verge REV is based on Mihomo Core.

**Comment by akdriver** [comment]
I think maybe you didn't understand what I mean, I certainly know how Mihomo and Clash Verge Rev work.
What I expected is to add a function to Clash Verge Rev: while exiting Clash Verge RevGUI process, keep Mihomo process working normally in the background.
我想也许你没有明白我的意思，我当然知道MIHOMO和CLASH VERGE REV如何工作。
我期盼的是，在Clash verge Rev GUI 添加一个功能: 退出Clash verge Rev GUI的同时，保留Mihomo进程在后台正常工作。

**Comment by akdriver** [comment]
> You may want to find Mihomo Project: https://github.com/MetaCubeX/mihomo And Clash Verge REV is based on Mihomo Core.

I think maybe you didn't understand what I mean, I certainly know how Mihomo and Clash Verge Rev work.
What I expected is to add a function to Clash Verge Rev: while exiting Clash Verge RevGUI process, keep Mihomo process working normally in the background.
我想也许你没有明白我的意思，我当然知道MIHOMO和CLASH VERGE REV如何工作。
我期盼的是，在Clash verge Rev GUI 添加一个功能: 退出Clash verge Rev GUI的同时，保留Mihomo进程在后台正常工作。

**Comment by Tychristine** [comment]
Read your first description "and keep only the Clash Meta kernel program", you only want to be running `Mihomo Core`.
The CVR worker threads cannot exit completely, as determined by the `Tauri framework`.
> You want to separate the GUI program from the core? There's some Web-UI Controller.
> https://www.clashverge.dev/friendship.html#web-ui
