### ISSUE TITLE
[BUG] 订阅的扩展配置和全局扩展配置

### ISSUE THREAD

**Issue by VincentAdamNemessisX** [clash-verge-rev/clash-verge-rev#1953]
### 问题描述 / Describe the bug

订阅的扩展配置中关于rules,dns及其他配置好像跟修改规则功能的写法不一样，能不能出个demo专门写一下示例规则，比如覆盖原有订阅中的某些配置，追加到原有配置的列表中，从原有订阅中删除某些项
不然的话它们的优先级是不一样的，扩展规则写了也白写

### 软件版本 / Verge Version

1.7.7

### 复现步骤 / To Reproduce

订阅的扩展配置中加入以下信息：
+ rules:
  - 'DOMAIN-KEYWORD,bing,InfiniPort'
  - 'DOMAIN-KEYWORD,microsoft,InfiniPort'
  - 'DOMAIN-SUFFIX,microsoft.com,InfiniPort'
  - 'DOMAIN-SUFFIX,microsoftonline.com,InfiniPort'
 由于原有订阅配置文件中存在相同或优先级更高的规则，所以这里写的规则并不能生效
 需要在订阅的修改规则中移除原配置中的规则才能正常生效

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11 23H2 22631.4317

### 日志 / Log

无

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1887

添加到前置规则中才会优先处理。
