### ISSUE TITLE
[BUG] 订阅修改规则为PASS没有用，还是会走代理

### ISSUE THREAD

**Issue by VincentAdamNemessisX** [clash-verge-rev/clash-verge-rev#1954]
### 问题描述 / Describe the bug

在订阅的修改规则中添加了指定域名PASS（前置后置都加了），但是看日志发现它并没有正常PASS掉这些域名，反而接着让它走代理了

### 软件版本 / Verge Version

1.7.7

### 复现步骤 / To Reproduce

在订阅的修改规则中添加了指定域名PASS（前置后置都加）

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11 23H2 22631.4317

### 日志 / Log

10-30 13:45:39info
[TCP] 127.0.0.1:53189 --> dozzle-dev-2.xxx.dev:443 match Match using InfiniPort[🇺🇸 US 01 E]
10-30 13:45:39info
[TCP] 127.0.0.1:53188 --> dozzle-dev-2.xxx.dev:443 match Match using InfiniPort[🇺🇸 US 01 E]

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1887

这部分由内核处理，肯定是规则匹配的问题；检查规则
