### ISSUE TITLE
[BUG] Mac10.13.6's suitable version

### ISSUE THREAD

**Issue by momo1986** [clash-verge-rev/clash-verge-rev#1955]
### 问题描述 / Describe the bug

<img width="590" alt="屏幕快照 2024-10-30 下午3 19 51" src="https://github.com/user-attachments/assets/5cbae16f-cec4-4c2d-87a5-7c715c993ffd">
Hi My system is MAC 10.13.6.

Which package release can I follow?

Thanks a lot for your response.

Regards!
Momo

### 软件版本 / Verge Version

N/A

### 复现步骤 / To Reproduce

N/A

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

10.13.6

### 日志 / Log

No suitable version.

**Comment by wonfen** [comment]
不支持macOS10，至少升级到11
