### ISSUE TITLE
[BUG] 2.0版tun模式下dns模式自动变成了fake-ip

### ISSUE THREAD

**Issue by baraja** [clash-verge-rev/clash-verge-rev#1956]
### 问题描述 / Describe the bug

开启tun模式，运行配置从redir-host变成了fake-ip
即使原订阅文件和扩展配置里都是redir-host

### 软件版本 / Verge Version

2.0 rc5

### 复现步骤 / To Reproduce

原订阅文件里面是：enhanced-mode: redir-host
扩展配置里面也是：enhanced-mode: redir-host
启用tun模式，查看当前运行配置变成了 enhanced-mode: fake-ip

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by wonfen** [comment]
是的，因为tun模式需要配合fake-ip才能更好的工作，性能更高，clashx pro等一系列代理工具也是这么做的

不开fakeip 很容易被DNS劫持， 性能问题等等

**Comment by Rashhz** [comment]
> 是的，因为tun模式需要配合fake-ip才能更好的工作，性能更高，clashx pro等一系列代理工具也是这么做的
> 
> 不开fakeip 很容易被DNS劫持， 性能问题等等

可不可以给一个选择的余地呢大佬，因为有的应用必须得使用redirhost模式，否则会有兼容问题，比如一些跟局域网相关的应用，还有跟远程桌面相关的应用

**Comment by Tychristine** [comment]
@Rashhz 不需要经过TUN的东西就加入 fake-ip-filter , 比如Windows断网小地球`+.msftconnecttest.com`，
我长时间使用Todesk远程桌面，QuicDesk远程桌面，雷神游戏加速器，甚至Qbittorrent做种等等。一直都开着TUN也没有一点问题
调整好配置就一步到位了

**Comment by Rashhz** [comment]
> @Rashhz 不需要经过TUN的东西就加入 fake-ip-filter , 比如Windows断网小地球`+.msftconnecttest.com`， 我长时间使用Todesk远程桌面，QuicDesk远程桌面，雷神游戏加速器，甚至Qbittorrent做种等等。一直都开着TUN也没有一点问题 调整好配置就一步到位了

好的，谢谢，我去试一下

**Comment by Keldos-Li** [comment]
虽然是这么说，但远程服务用tun的fake ip确实会影响……我目前一直使用动态解析的公网ipv6来连接我的主机（被控端），相关的远程和串流软件有Windows App（也就是微软默认的远程桌面RDP协议）、Moonlight（NVIDIA 的 GameStream 协议）。只要我开启tun模式时同时启用ipv6，所有远程服务都会失效，只有不tun代理ipv6才能**被**连接通。相关端口和进程名都写给了规则的DIRECT但是没有用。

目前我是一直关ipv6使用的。可能是因为被控端吗？我并不能在日志或者哪里找到tun代理了哪些地址或端口导致的问题，在发起请求端查看网络日志也只有向主机的ipv6地址发起tcp请求之类，所以不知道怎么写fake ip filter  o(╥﹏╥)o

**Comment by wonfen** [comment]
> 内网调试用的一大堆东西都在更新后出问题了。看了配置才看到自动改成了fake-ip。看来只能保持旧版本了。

老版本1.7的tun模式会修改为fakeip啊

**Comment by JustLookAtNow** [comment]
> [@Rashhz](https://github.com/Rashhz) 不需要经过TUN的东西就加入 fake-ip-filter , 比如Windows断网小地球`+.msftconnecttest.com`， 我长时间使用Todesk远程桌面，QuicDesk远程桌面，雷神游戏加速器，甚至Qbittorrent做种等等。一直都开着TUN也没有一点问题 调整好配置就一步到位了

hi,todesk如何设置，我现在开着tun连todesk过一会就断网

**Comment by xuanyuan0408** [comment]
> > [@Rashhz](https://github.com/Rashhz) 不需要经过TUN的东西就加入 fake-ip-filter , 比如Windows断网小地球`+.msftconnecttest.com`， 我长时间使用Todesk远程桌面，QuicDesk远程桌面，雷神游戏加速器，甚至Qbittorrent做种等等。一直都开着TUN也没有一点问题 调整好配置就一步到位了
> 
> hi,todesk如何设置，我现在开着tun连todesk过一会就断网

```
fake-ip-filter:
  - '+.todesk.com'
```
