### ISSUE TITLE
[BUG] ！linux！在开启静默启动选项后，无法调出ui面板；

### ISSUE THREAD

**Issue by FonzoSong** [clash-verge-rev/clash-verge-rev#1957]
### 问题描述 / Describe the bug

[安装版本](https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v1.7.7/clash-verge-1.7.7-1.x86_64.rpm)
程序能够正常运行，仅仅无法调出UI面板；
使用/usr/bin/clash-verge 直接运行也无法启动UI面板；
重装软件无法解决，由于不知道软件配置文件位置无法彻底删除痕迹；

### 软件版本 / Verge Version

alpha v1.7.7 下载时间为：Wed Oct 30 05:11:09 PM CST 2024

### 复现步骤 / To Reproduce

开启静默启动选项；点击 `X` 关闭面板；然后无法使用点击桌面图标启动UI面板；

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Red Hat Enterprise Linux 9.4 (Plow) GNOME 40.4.0

### 日志 / Log

无法调出面板；没有提供日志路径，故无法提供日志

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1887
