### ISSUE TITLE
[Feature] 便携版怎么没有了

### ISSUE THREAD

**Issue by 2018shawn** [clash-verge-rev/clash-verge-rev#1959]
### 功能描述 / Feature description

便携版有哪些问题可以说说吗？我用着便携版感觉很不错呀！

### 使用场景 / Use case

不方便安装软件或者不喜欢安装软件的人来说便携版很不错。

**Comment by Tychristine** [comment]
默认要求安装服务模式，需要便携版就自己转换；
且便携版需要自己安装服务 `~/resources/install-service(.exe)`
自行转换参考[链接](https://blog.tyasaka.xyz/posts/clash-vergerev-to-portable/#clashvergerev%E8%BD%AC%E6%8D%A2%E5%88%B0%E4%BE%BF%E6%90%BA%E7%89%88)
*不需要打包安装可以自己构建安装*

**Comment by LaoChang2012** [comment]
是一点都不考虑,装有还原系统的电脑啊.

**Comment by Dragon1573** [comment]
> 装有还原系统的电脑

多数带还原功能的设备都只还原系统磁盘，是否尝试过将它们安装在别的磁盘上？

除此之外 [Scoop](https://scoop.sh/) 是由第三方社区支持的、以「绿色免安装」为目标的 Windows 应用程序包管理器，Clash Verge Rev 被收录到了 [Extra Buckets](https://github.com/ScoopInstaller/Extras) 中，可以自己研究一下它们的 [JSON元数据](https://github.com/ScoopInstaller/Extras/blob/master/bucket/clash-verge-rev.json) 来理解 Clash Verge Rev 如何以便携形式安装到系统中。

<img width="1380" height="251" alt="Image" src="https://github.com/user-attachments/assets/6e8fe31a-f328-4c54-8e49-de412256e04b" />
