### ISSUE TITLE
[BUG] 2.0 rc5 某些字段配置不生效

### ISSUE THREAD

**Issue by ChenYueC** [clash-verge-rev/clash-verge-rev#1962]
### 问题描述 / Describe the bug

全局配置 external-controller 自定义127.0.0.1:8090
dns配置  fake-ip-range: 198.18.0.1/16
在查看当前配置后，显示 external-controller: 127.0.0.1:9097、fake-ip-range: 10.96.0.0/16
![image](https://github.com/user-attachments/assets/eae697e5-dce0-4c7b-a083-a32860a1aa37)
![image](https://github.com/user-attachments/assets/df435d12-874e-4888-b401-6502d1a18027)
![image](https://github.com/user-attachments/assets/63df507f-e085-4956-ad16-d07aac115a3d)

### 软件版本 / Verge Version

2.0 rc5

### 复现步骤 / To Reproduce

订阅配置、直接配置字段

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

无

**Comment by wonfen** [comment]
是这样的，软件的内置通信端口和tun模式下的fakeip设置。

**Comment by wtry** [comment]
dns模块下会自动生成一个
 ip-v6: true 
的设置项，这个是不是有问题
