### ISSUE TITLE
[BUG] 每次重启电脑后Service Mode消失，需要重新安装

### ISSUE THREAD

**Issue by erbanku** [clash-verge-rev/clash-verge-rev#1963]
### 问题描述 / Describe the bug

每次重启电脑后Service Mode消失，需要重新安装

### 软件版本 / Verge Version

1.7.7

### 复现步骤 / To Reproduce

重启

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

24H2

### 日志 / Log

N/A

**Comment by Tychristine** [comment]
#1887
