### ISSUE TITLE
[BUG] 2.0.0-rc.5 开启tun后，不自动修改 resolv.conf

### ISSUE THREAD

**Issue by bingoku** [clash-verge-rev/clash-verge-rev#1964]
### 问题描述 / Describe the bug

开启tun后，不自动修改 resolv.conf ，依然还是系统网络默认的dns

### 软件版本 / Verge Version

2.0.0-rc.5 

### 复现步骤 / To Reproduce

cat /etc/resolv.conf | grep nameserver

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

macOS 版本15.1 (24B83)

### 日志 / Log

![image](https://github.com/user-attachments/assets/3a0583c3-9546-421a-ab4e-a162b6d79acc)

**Comment by wonfen** [comment]
使用命令 scutil --dns 查询一下接口dns是否改了。

**Comment by wonfen** [comment]
无进一步反馈，关闭。
