### ISSUE TITLE
[BUG] Win11 24H2下，界面中的多个项目内容均空白

### ISSUE THREAD

**Issue by NV3S** [clash-verge-rev/clash-verge-rev#1966]
### 问题描述 / Describe the bug

尝试了1.7.7和2.0 RC5版本，在升级windows11到 24H2，会出现代理、连接、规则、日志页面空白的情况。（订阅可显示，抓取成功，网络访问也ok，可以看截图）。
重装软件或者软件版本，无果，回退系统到23H恢复正常。

<img width="740" alt="image" src="https://github.com/user-attachments/assets/c79ee076-3c5e-4627-90be-1c4e1a4be8d8">

### 软件版本 / Verge Version

1.7.7
2.0 RC5

### 复现步骤 / To Reproduce

windows11到 24H2，会出现这种情况；
回退系统到23H，问题消失。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 24H2

### 日志 / Log

似乎无需log（也无法显示日志

**Comment by wonfen** [comment]
你这个是服务没有安装;升级到rc5没有弹出服务安装的请求吗？

**Comment by Tychristine** [comment]
# Windows11 26100 BBR2网络bug
这是由于 **Windows11 24H2 26100** 上 *BBR2*网络bug
具体现象为包括但不限于 **远程桌面，游戏加速器，Aria2，Mihomo无法连接**
# 解决方法
**管理员身份启动终端** 逐行执行以下代码后**重启电脑**
```shell
netsh int tcp set supplemental template=internet congestionprovider=CUBIC
netsh int tcp set supplemental template=internetcustom congestionprovider=CUBIC
netsh int tcp set supplemental template=Compat congestionprovider=NewReno
netsh int tcp set supplemental template=Datacenter congestionprovider=CUBIC
netsh int tcp set supplemental template=Datacentercustom congestionprovider=CUBIC 
```

**Comment by Tychristine** [comment]
更多:
#1037 
#1567

**Comment by NV3S** [comment]
> 你这个是服务没有安装;升级到rc5没有弹出服务安装的请求吗？

安装时候跳出的框都点yes了，然后1.7.7的服务我记得是在这个页面，TUN设置的下面。2.0后没有了。
<img width="590" alt="image" src="https://github.com/user-attachments/assets/d8ce9a16-b14d-4a8d-a65c-3ffbac483cd5">

**Comment by NV3S** [comment]
> # Windows11 26100 BBR2网络bug
> 这是由于 **Windows11 24H2 26100** 上 _BBR2_网络bug 具体现象为包括但不限于 **远程桌面，游戏加速器，Aria2，Mihomo无法连接**
> 
> # 解决方法
> **管理员身份启动终端** 逐行执行以下代码后**重启电脑**
> 
> ```shell
> netsh int tcp set supplemental template=internet congestionprovider=CUBIC
> netsh int tcp set supplemental template=internetcustom congestionprovider=CUBIC
> netsh int tcp set supplemental template=Compat congestionprovider=NewReno
> netsh int tcp set supplemental template=Datacenter congestionprovider=CUBIC
> netsh int tcp set supplemental template=Datacentercustom congestionprovider=CUBIC 
> ```

应该是BBR2的锅，回退到CUBIC，以及参照https://github.com/clash-verge-rev/clash-verge-rev/issues/1567的说法，解决了

**Comment by NV3S** [comment]
应该是BBR2的锅，回退到CUBIC，以及参照#1567 的说法，解决了

> # Windows11 26100 BBR2网络bug
> 这是由于 **Windows11 24H2 26100** 上 _BBR2_网络bug 具体现象为包括但不限于 **远程桌面，游戏加速器，Aria2，Mihomo无法连接**
> 
> # 解决方法
> **管理员身份启动终端** 逐行执行以下代码后**重启电脑**
> 
> ```shell
> netsh int tcp set supplemental template=internet congestionprovider=CUBIC
> netsh int tcp set supplemental template=internetcustom congestionprovider=CUBIC
> netsh int tcp set supplemental template=Compat congestionprovider=NewReno
> netsh int tcp set supplemental template=Datacenter congestionprovider=CUBIC
> netsh int tcp set supplemental template=Datacentercustom congestionprovider=CUBIC 
> ```

应该是BBR2的锅，回退到CUBIC，以及参照#1567 的说法，解决了
