### ISSUE TITLE
[BUG] 其他订阅编辑配置，当前的订阅激活一下？

### ISSUE THREAD

**Issue by kty00** [clash-verge-rev/clash-verge-rev#1967]
### 问题描述 / Describe the bug

编辑其他订阅的配置，当前的订阅会转圈一下

### 软件版本 / Verge Version

![image](https://github.com/user-attachments/assets/eaa7eedf-515c-47ff-8250-9915daa94bd4)

### 复现步骤 / To Reproduce

编辑其他订阅的配置（编辑信息），当前激活的订阅会转圈一下，跟激活订阅一样

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10

### 日志 / Log

没有

**Comment by wonfen** [comment]
无法复现，录个视频看看

**Comment by kty00** [comment]
> 无法复现，录个视频看看
![clash](https://github.com/user-attachments/assets/f97ab072-74b3-473f-9e16-1ef7e4b0c61f)

**Comment by wonfen** [comment]
你这2个配置文件的内容有关联？我这里无法复现。转圈载入说明你的配置文件里可能有远程路径，正在下载（加载）远程文件。

**Comment by kty00** [comment]
> 你这2个配置文件的内容有关联？我这里无法复现。转圈载入说明你的配置文件里可能有远程路径，正在下载（加载）远程文件。

没有，就新安装的 app，导入订阅，我这边必现。
找了两个订阅
```http
https://cov.elmagnifico.tech/sub?target=clash&url=vmess%3A%2F%2FeyJhZGQiOiAiZ292LnVrIiwgInYiOiAiMiIsICJwcyI6ICJcdTdmOGVcdTU2ZmQgRmFzdGx5XHU1MTY4XHU3NDAzQW55Y2FzdFx1ODI4Mlx1NzBiOSIsICJwb3J0IjogNDQzLCAiaWQiOiAiNzc4NDg4MjQtOTNiNy00Yjg5LWZmZDAtZTkxYWZmZjQwNmNlIiwgImFpZCI6ICIwIiwgIm5ldCI6ICJ3cyIsICJ0eXBlIjogIiIsICJob3N0IjogInpoZXNoaXNjcC5jb20iLCAicGF0aCI6ICIvNzc4NDg4MjQiLCAidGxzIjogInRscyJ9%7Cvmess%3A%2F%2FeyJhZGQiOiAic2VydmVyMzEuYmVoZXNodGJhbmVoLmNvbSIsICJhaWQiOiAwLCAiaG9zdCI6ICJzZXJ2ZXIzMS5iZWhlc2h0YmFuZWguY29tIiwgImlkIjogIjQxNTQxNDNjLWJiYmEtNDdhNC05Zjc5LWMyZWQwODdjYmNjOSIsICJuZXQiOiAid3MiLCAicGF0aCI6ICIvIiwgInBvcnQiOiA4ODgwLCAicHMiOiAiXHU3ZjhlXHU1NmZkIENsb3VkRmxhcmVcdTgyODJcdTcwYjkiLCAidGxzIjogIiIsICJ0eXBlIjogImF1dG8iLCAic2VjdXJpdHkiOiAiYXV0byIsICJza2lwLWNlcnQtdmVyaWZ5IjogdHJ1ZSwgInNuaSI6ICIifQ%3D%3D%7C&insert=false&emoji=true&list=false&tfo=false&scv=true&fdn=false&sort=false&new_name=true
```

```http
https://cov.elmagnifico.tech/sub?target=clash&url=vmess%3A%2F%2FeyJhZGQiOiAiZ292LnVrIiwgInYiOiAiMiIsICJwcyI6ICJcdTdmOGVcdTU2ZmQgRmFzdGx5XHU1MTY4XHU3NDAzQW55Y2FzdFx1ODI4Mlx1NzBiOSIsICJwb3J0IjogNDQzLCAiaWQiOiAiNzc4NDg4MjQtOTNiNy00Yjg5LWZmZDAtZTkxYWZmZjQwNmNlIiwgImFpZCI6ICIwIiwgIm5ldCI6ICJ3cyIsICJ0eXBlIjogIiIsICJob3N0IjogInpoZXNoaXNjcC5jb20iLCAicGF0aCI6ICIvNzc4NDg4MjQiLCAidGxzIjogInRscyJ9%7Cvmess%3A%2F%2FeyJhZGQiOiAic2VydmVyMzEuYmVoZXNodGJhbmVoLmNvbSIsICJhaWQiOiAwLCAiaG9zdCI6ICJzZXJ2ZXIzMS5iZWhlc2h0YmFuZWguY29tIiwgImlkIjogIjQxNTQxNDNjLWJiYmEtNDdhNC05Zjc5LWMyZWQwODdjYmNjOSIsICJuZXQiOiAid3MiLCAicGF0aCI6ICIvIiwgInBvcnQiOiA4ODgwLCAicHMiOiAiXHU3ZjhlXHU1NmZkIENsb3VkRmxhcmVcdTgyODJcdTcwYjkiLCAidGxzIjogIiIsICJ0eXBlIjogImF1dG8iLCAic2VjdXJpdHkiOiAiYXV0byIsICJza2lwLWNlcnQtdmVyaWZ5IjogdHJ1ZSwgInNuaSI6ICIifQ%3D%3D%7C&insert=false&emoji=true&list=false&tfo=false&scv=true&fdn=false&sort=false&new_name=true
```

**Comment by wonfen** [comment]
无法复现，尝试把配置目录下的所有文件删了；然后再重新安装最新版试试。

**Comment by kty00** [comment]
> 无法复现，尝试把配置目录下的所有文件删了；然后再重新安装最新版试试。


录了一个视频，新装的win10，绝对干净。安装 app 中间停留了一会，视频太大了，这边上传不了，看链接吧。
https://github.com/kty00/tmp/blob/main/QQ20241113-10551-HD.mp4

```http
https://suo.yt/gylYBxz

https://suo.yt/PsvZiJH
```

**Comment by kty00** [comment]
> > 无法复现，尝试把配置目录下的所有文件删了；然后再重新安装最新版试试。
> 
> 录了一个视频，新装的win10，绝对干净。安装 app 中间停留了一会，视频太大了，这边上传不了，看链接吧。 https://github.com/kty00/tmp/blob/main/QQ20241113-10551-HD.mp4
> 
> ```httpspec
> https://suo.yt/gylYBxz
> 
> https://suo.yt/PsvZiJH
> ```

疑问是，为什么编辑第二个订阅，第一个转圈。实际没感知到影响，正常应该是编辑订阅2，不影响订阅1的吧？

**Comment by Tychristine** [comment]
我也无法复现出来，版本是2.0.0-rc.6 Win11 amd64

**Comment by kty00** [comment]
> 修改配置名称确实会重新激活，应该是重载`profile.yaml` 实际不影响使用

编辑信息 所有选项都会影响其他订阅（转圈），按理来说，订阅之间不是互不影响才对么

**Comment by wonfen** [comment]
> > 修改配置名称确实会重新激活，应该是重载`profile.yaml` 实际不影响使用
> 
> 编辑信息 所有选项都会影响其他订阅（转圈），按理来说，订阅之间不是互不影响才对么

原因就是 @Tychristine 说的 重载 profile.yaml ，因为有全局脚本和全局扩展配置，所以所有订阅在  profile.yaml 下有管理，当编辑其他订阅名称的时候， profile.yaml文件被更新，而当前选中的订阅名称发现 profile.yaml 文件被更新，需要重载；是预期行为。
