### ISSUE TITLE
[Feature] linux 无桌面服务

### ISSUE THREAD

**Issue by yuqingli05** [clash-verge-rev/clash-verge-rev#1969]
### 功能描述 / Feature description

Linux 无桌面ui 的服务版本，后台静默运行，使用web ui进行管理。运行在家庭服务器等环境

### 使用场景 / Use case

一个局域网开一个代理服务，适合家庭，小公司等，其他设备系统设置代理即可

**Comment by yuqingli05** [comment]
能在docker 里面部署，建议创建docker 这样方便部署。

**Comment by Tychristine** [comment]
见上游 https://github.com/MetaCubeX/mihomo

**Comment by snail2sky** [comment]
> Collaborator

这是啥、
