### ISSUE TITLE
[Feature] 导入订阅智能一些？

### ISSUE THREAD

**Issue by kty00** [clash-verge-rev/clash-verge-rev#1970]
### 功能描述 / Feature description

机场的订阅间歇性被强，订阅更新有点麻烦

app 能不能默认直连，直连不成功再用走代理？反正就是自己尝试切换模式去更新。这个也适用订阅，默认走直连，不成功再走代理。

### 使用场景 / Use case

被墙的时候，要使用内核代理更新，此时要求代理可用，不然更新不成功；没被墙，可以直连更新

**Comment by kty00** [comment]
换这个之前用 cfw，应该就是这种方式，从来没遇到过订阅失败，更新失败。

**Comment by Tychristine** [comment]
错误的，先把模式切到DIRECT,再做其它事，
自己灵活使用就能处理的问题

**Comment by kty00** [comment]
> 错误的，先把模式切到DIRECT,再做其它事， 自己灵活使用就能处理的问题

如果都要手动去点，那这个跟去订阅的编辑信息里面做设置不是一样。“智能一些” 只是想更方便点。


你们看吧，能做更好，只是建议。

**Comment by Tychristine** [comment]
@kty00 再说，如果是空文件启动CVR，那默认就是给的出站网络就是直连
