### ISSUE TITLE
[BUG] 1.7.7版本，CF节点，默认的1.1.1.1测试连接，全部超时

### ISSUE THREAD

**Issue by alexallen1** [clash-verge-rev/clash-verge-rev#1975]
### 问题描述 / Describe the bug

很容易复现。群体沦陷。默认使用1.1.1.1似乎不是最优选择，特别对于电脑小白不会改1.1.1.1的

### 软件版本 / Verge Version

1.7.7版本

### 复现步骤 / To Reproduce

很容易复现。群体沦陷。默认使用1.1.1.1似乎不是最优选择，特别对于电脑小白不会改1.1.1.1的

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

WINDOWS10

### 日志 / Log

WINDOWS10

**Comment by Tychristine** [comment]
全部超时 CloudFlare 1x4 测试连通性确实没有参考性 ，已在2.0版本中修订过 486ffbd
不再接受 1.x版本的反馈
