### ISSUE TITLE
[BUG] 关于在windows端WSL/Vmware虚拟机内使用docker pull拉取镜像失败的问题

### ISSUE THREAD

**Issue by lucklymore** [clash-verge-rev/clash-verge-rev#1976]
### 问题描述 / Describe the bug

在使用windows端使用clash verge rev代理访问互联网存在VMware workstation 、WSL2 虚拟机环境下，docker pull拉取镜像失败的问题，但是通过curl命令或者直接浏览器访问docker 相关的页面的情况下均正常。通过测试其他VPN（letsVPN）时，发现可以正常访问互联网同时也能docker pull拉取镜像。

docker pull 镜像时出现以下错误
使用docker pull命令时出现的错误信息：
  [root@container ~]# docker pull bitnami/kafka:latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[root@container ~]# docker pull bitnami/kafka:latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

亦或者是：
Oct 27 15:15:05 container dockerd: time="2024-10-27T15:15:05.403590516+08:00" level=error msg="Not continuing with pull after error: Get \"https://registry-1.docker.io/v2/\": EOF" spanID=da5be959cefedc61 traceID=ffb97c59c3855ece621045cfc3bdd272
Oct 27 15:15:05 container dockerd: time="2024-10-27T15:15:05.403689823+08:00" level=error msg="Handler for POST /v1.45/images/create returned error: Get \"https://registry-1.docker.io/v2/\": EOF" spanID=da5be959cefedc61 traceID=ffb97c59c3855ece621045cfc3bdd272
Oct 27 15:15:05 container dockerd: time="2024-10-27T15:15:05.405298491+08:00" level=warning msg="Error getting v2 registry: Get \"https://registry-1.docker.io/v2/\": EOF" spanID=b1d3996147fc0c03 traceID=ffb97c59c3855ece621045cfc3bdd272
Oct 27 15:15:05 container dockerd: time="2024-10-27T15:15:05.405337923+08:00" level=error msg="Not continuing with pull after error: Get \"https://registry-1.docker.io/v2/\": EOF" spanID=b1d3996147fc0c03 traceID=ffb97c59c3855ece621045cfc3bdd272
Oct 27 15:15:05 container dockerd: time="2024-10-27T15:15:05.405419815+08:00" level=error msg="Handler for POST /v1.45/images/create returned error: Get \"https://registry-1.docker.io/v2/\": EOF" spanID=b1d3996147fc0c03 traceID=ffb97c59c3855ece621045cfc3bdd272
Oct 27 15:15:05 container dockerd: time="2024-10-27T15:15:05.407187957+08:00" level=warning msg="Error getting v2 registry: Get \"https://registry-1.docker.io/v2/\": EOF" spanID=b474b17794a1dc14 traceID=ffb97c59c3855ece621045cfc3bdd272
Oct 27 15:15:05 container dockerd: time="2024-10-27T15:15:05.407211881+08:00" level=error msg="Not continuing with pull after error: Get \"https://registry-1.docker.io/v2/\": EOF" spanID=b474b17794a1dc14 traceID=ffb97c59c3855ece621045cfc3bdd272
Oct 27 15:15:05 container dockerd: time="2024-10-27T15:15:05.407316880+08:00" level=error msg="Handler for POST /v1.45/images/create returned error: Get \"https://registry-1.docker.io/v2/\": EOF" spanID=b474b17794a1dc14 traceID=ffb97c59c3855ece621045cfc3bdd272
Oct 27 15:15:21 container dockerd: time="2024-10-27T15:15:21.464887955+08:00" level=debug msg="Calling HEAD /_ping" spanID=0211ae33c6fc867c tra:
![curl访问方式-测试1](https://github.com/user-attachments/assets/30271bfb-774f-451e-b317-6f4320b79b10)
![curl访问方式-测试2](https://github.com/user-attachments/assets/a1004a03-0d83-4969-91d8-3f70dae6d422)
![curl访问方式-测试3](https://github.com/user-attachments/assets/d8c56bc9-9bd1-4359-aad6-a5b94e6b2410)
![curl访问方式-测试4](https://github.com/user-attachments/assets/5745742e-c5cd-4d14-b92d-4407dc068f9c)
![docker pull异常信息](https://github.com/user-attachments/assets/c7f2e2bb-a300-48ac-8419-e54bb613795c)
![通过浏览器访问正常的情况-1](https://github.com/user-attachments/assets/f6924bd0-66a3-4670-a468-b7e1425f19ab)

### 软件版本 / Verge Version

宿主机：windows 11 24h2
  clash verge rev版本信息：clash verge rev 1.7.7或者2.0 rc2
  代理模式配置：tun模式、开启IPV6、局域网连接、端口设置7897、代理方式为规则代理或者全局代理

  虚拟机：VMware workstation pro 17.5.2
  虚拟机客户机系统：centos7
  虚拟机客户机与宿主机的网络配置：nat模式，网段 192.168.10.0 ，宿主机IP 192.168.10.2，虚拟机客户机IP 192.168.10.30
  虚拟机客户机内docker信息：Docker Engine - Community Version: 26.1.4
  客户机内docker proxy 代理信息配置（尝试过不配置、配置的情况下均同样结果无法docker pull）
  /etc/docker/daemon.json--docker daemon配置信息：
        {
        "debug": true,
        "max-concurrent-downloads" : 3,
            "proxies": {
            "http-proxy": "http://192.168.10.2:7897",
            "https-proxy": "https://192.168.10.2:7897"
            }
        }
  /etc/systemd/system/docker.service.d/https-proxy.conf--docker服务配置信息：
        [Service]
        Environment="HTTP_PROXY=http://192.168.10.2:7899"
        Environment="HTTPS_PROXY=https://192.168.10.2:7899"

clash verge 扩展配置信息：
profile:
  store-selected: false
  store-fake-ip: false
find-process-mode: strict
global-client-fingerprint: edge
tcp-concurrent: true
keep-alive-interval: 5
keep-alive-idle: 500
disable-keep-alive: false
dns:
  enable: true
  ipv6: true
  prefer-h3: true
  use-system-hosts: false
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "+.lan"
    - "+.local"
    - "+.docker.io"
    - "+.docker.com"
  nameserver:
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    "+.docker.io" : 
      - https://dns.pub/dns-query
      - https://8.8.4.4/dns-query
    "geosite:cn,private":
      - https://120.53.53.53/dns-query
      - https://223.5.5.5/dns-query
    "geosite:geolocation-!cn":
      - "https://dns.alidns.com/dns-query"

### 复现步骤 / To Reproduce

1、使用VMware虚拟机内ping 或者curl相关网页例如google.com、hub.docker.com、https://registry-1.docker.io/v2/ 请求正常
2、使用docker pull 镜像命令，均失败

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 11 24h2

### 日志 / Log

[2024-11-02-2237-app-log.log](https://github.com/user-attachments/files/17607304/2024-11-02-2237-app-log.log)
[2024-11-02-2237-内核日志.log](https://github.com/user-attachments/files/17607305/2024-11-02-2237-.log)

**Comment by zmc-x** [comment]
I deem you can pull images from mirror of docker hub. But i get into this bug at yesterday in Ubuntu 24.04. I deem this problem is related to the network.

**Comment by lucklymore** [comment]
> I deem you can pull images from mirror of docker hub. But i get into this bug at yesterday in Ubuntu 24.04. I deem this problem is related to the network.

事实上，在windows启用clash verge代理的基础上，我可以在虚拟机客户机内能正常访问网络（google等），但是唯独docker pull总是失败（更多的是连接断开、超时类似错误）。
另外我测试其他VPN工具，例如letsVPN（这个使用的是letsvpn提供的自有客户端），大概分析了下应该也是使用类似tun的模式代理的，这个VPN工具可以正常使用docker pull命令，拉取镜像成功
通过这个测试，可能存在1、我的clashverge /或者其他地方存在配置错误 2、clashverge内核可能对于这种代理存在不支持的情况（多层nat + docker 内部网络等）
您现在有类似的问题，有什么方式可以解决该问题吗

**Comment by wonfen** [comment]
先检查下各环境里的路由表，看下路由是否正确指向了tun

**Comment by lucklymore** [comment]
> 先检查下各环境里的路由表，看下路由是否正确指向了tun

你好，这里应该如何检查，才能知道路由是否指向tun。目前我的网络连接形式是虚拟机客户机（192.168.10.59）-》vmware gateway NAT(192.168.10.1) ->windows宿主机VMnet8(192.168.10.2)（该宿主机同时存在其他虚拟网卡）->clash verge TUN（fake ip range 10.96.0.0）
目前我做了以下检查，不确定是否算是已经指向tun了
虚拟机内客户机--检查
[root@bigdata059 yum.repos.d]# ip route show
default via 192.168.10.1 dev ens33 proto static metric 100 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.10.0/24 dev ens33 proto kernel scope link src 192.168.10.59 metric 100 

windows宿主机--检查
===========================================================================
IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0      192.168.1.1      192.168.1.4     45
          0.0.0.0          0.0.0.0            在链路上         10.96.0.0      0
        10.96.0.0  255.255.255.252            在链路上         10.96.0.0    256
        10.96.0.0  255.255.255.255            在链路上         10.96.0.0    256
        10.96.0.3  255.255.255.255            在链路上         10.96.0.0    256
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
      192.168.1.0    255.255.255.0            在链路上       192.168.1.4    301
      192.168.1.4  255.255.255.255            在链路上       192.168.1.4    301
    192.168.1.255  255.255.255.255            在链路上       192.168.1.4    301
     192.168.10.0    255.255.255.0            在链路上      192.168.10.2    291
     192.168.10.2  255.255.255.255            在链路上      192.168.10.2    291
   192.168.10.255  255.255.255.255            在链路上      192.168.10.2    291
     192.168.15.0    255.255.255.0            在链路上      192.168.15.1    291
     192.168.15.1  255.255.255.255            在链路上      192.168.15.1    291
   192.168.15.255  255.255.255.255            在链路上      192.168.15.1    291
     192.168.20.0    255.255.255.0            在链路上      192.168.20.1    291
     192.168.20.1  255.255.255.255            在链路上      192.168.20.1    291
   192.168.20.255  255.255.255.255            在链路上      192.168.20.1    291
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上       192.168.1.4    301
        224.0.0.0        240.0.0.0            在链路上      192.168.10.2    291
        224.0.0.0        240.0.0.0            在链路上      192.168.20.1    291
        224.0.0.0        240.0.0.0            在链路上      192.168.15.1    291
        224.0.0.0        240.0.0.0            在链路上         10.96.0.0    256
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
  255.255.255.255  255.255.255.255            在链路上       192.168.1.4    301
  255.255.255.255  255.255.255.255            在链路上      192.168.10.2    291
  255.255.255.255  255.255.255.255            在链路上      192.168.20.1    291
  255.255.255.255  255.255.255.255            在链路上      192.168.15.1    291
  255.255.255.255  255.255.255.255            在链路上         10.96.0.0    256

**Comment by blatwo** [comment]
你的虚拟机用的是网桥模式吧，用nat模式试试；网桥模式，你需要转设置docker的代理，可以把你的代理配置发上来看看。

**Comment by lucklymore** [comment]
> 你的虚拟机用的是网桥模式吧，用nat模式试试； 或者这样配置 Environment="HTTP_PROXY=192.168.10.2:7899" Environment="HTTPS_PROXY=192.168.10.2:7899"。

不是网桥，目前是NAT模式，Environment="HTTP_PROXY=192.168.10.2:7899" Environment="HTTPS_PROXY=192.168.10.2:7899"。这个环境变量配置了也不生效，可以正常上网，但是docker pull会失败

**Comment by dongshifei** [comment]
可以尝试给docker增加代理,我是用的是debian12, 使用apt方式安装, 执行 vim /lib/systemd/system/docker.service 新增
Environment="HTTP_PROXY=http://192.168.0.171:7890"
Environment="HTTPS_PROXY=http://192.168.0.171:7890"
我这边尝试是可以的,如果有兴趣,可以尝试一下

**Comment by lucklymore** [comment]
> 可以尝试给docker增加代理,我是用的是debian12, 使用apt方式安装, 执行 vim /lib/systemd/system/docker.service 新增 Environment="HTTP_PROXY=http://192.168.0.171:7890" Environment="HTTPS_PROXY=http://192.168.0.171:7890" 我这边尝试是可以的,如果有兴趣,可以尝试一下

使用docker 代理也不行，目前通过测试的一个暂行得方案是使用镜像加速仓库，但是这个会有白名单问题，如果镜像不在仓库加速白名单，会回退回[https://registry-1.docker.io/v2]，然后会报错，目前检索到得信息是可能是网络上触发sni阻断，导致访问被拦截了，目前没有什么比较好的解决方案

**Comment by Tychristine** [comment]
# 解决方案(Microsoft WSL2)

## 配置`WSL2`网络
新建文件`%USERPROFILE%/.wslconfig`,必须**包含**以下子项
```txt
[wsl2]
networkingMode=mirrored
dnsTunneling=true
autoProxy=true
```
## 开启`TUN mode`
我的实验是仅开启TUN，Docker源是官方镜像

> OS: Windows11 Pro 24H2 26100
> WSL: Debian GNU/Linux 12 (bookworm)
> Kernal: 5.15.153.1-microsoft-standard-WSL2
> CVR: `20d163c`

**Comment by Tychristine** [comment]
@lucklymore 专门切个较慢的proxy来拉取镜像，的确是几百kb每秒。换一个速度立即就跑起来了，不至于拉取失败。就只开了TUN mode

**Comment by tenacioustommy** [comment]
> 可以尝试给docker增加代理,我是用的是debian12, 使用apt方式安装, 执行 vim /lib/systemd/system/docker.service 新增 Environment="HTTP_PROXY=http://192.168.0.171:7890" Environment="HTTPS_PROXY=http://192.168.0.171:7890" 我这边尝试是可以的,如果有兴趣,可以尝试一下

试了一圈，这个好像可以诶，但我还是不太理解我已经设置了全局http_proxy了，也能curl google，但是为何docker pull不行，还得额外设置代理

**Comment by black-desk** [comment]
> > 可以尝试给docker增加代理,我是用的是debian12, 使用apt方式安装, 执行 vim /lib/systemd/system/docker.service 新增 Environment="HTTP_PROXY=http://192.168.0.171:7890" Environment="HTTPS_PROXY=http://192.168.0.171:7890" 我这边尝试是可以的,如果有兴趣,可以尝试一下
> 
> 试了一圈，这个好像可以诶，但我还是不太理解我已经设置了全局http_proxy了，也能curl google，但是为何docker pull不行，还得额外设置代理

你的“全局”是在什么地方设置的，因为linux其实
1. 没有“全局”环境变量这个说法；
2. 有很多东西启动的时候会清空继承来的环境变量。
   比如systemd启动docker服务的时候、sudo的时候

**Comment by black-desk** [comment]
> 可以尝试给docker增加代理,我是用的是debian12, 使用apt方式安装, 执行 vim /lib/systemd/system/docker.service 新增 Environment="HTTP_PROXY=http://192.168.0.171:7890" Environment="HTTPS_PROXY=http://192.168.0.171:7890" 我这边尝试是可以的,如果有兴趣,可以尝试一下

不要直接vim编辑这个配置文件 docker更新以后可能会被覆盖掉 正确的方式是使用systemctl edit docker 命令编辑override文件

**Comment by tenacioustommy** [comment]
> lib/systemd/system/docker.service

就是直接export的，但是docker为何不会默认走系统的代理呢

**Comment by BubblingXuYijie** [comment]
没有遇到这个问题，我是最新的 clash verge 和 vmware pro，net 和 桥接都可以 docker pull，clash verge 是 tun 模式

**Comment by lucklymore** [comment]
> 没有遇到这个问题，我是最新的 clash verge 和 vmware pro，net 和 桥接都可以 docker pull，clash verge 是 tun 模式

方便说下机场的名称吗，我测试下是不是代理的问题，非常感谢了！！

**Comment by BubblingXuYijie** [comment]
bucd，多换换地区就行，有些地区没解锁流媒体什么的，说不定docker也不行，我一般用美国的

**Comment by jackydalong** [comment]
我遇到相同的问题，已解决，如下：
1. host 上 Clash 打开 TUN mode
- <img width="561" alt="image" src="https://github.com/user-attachments/assets/cf4554dc-52d5-4558-b1f0-770262c7a268">


2. VM 里  /etc/resolv.conf 
```
# egrep name /etc/resolv.conf
nameserver 8.8.8.8
nameserver 1.1.1.1
```

3. VM 里 pull image 可以了
```python
$ sudo ctr image pull docker.io/library/nginx:latest
docker.io/library/nginx:latest:                                                   resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:bc5eac5eafc581aeda3008b4b1f07ebba230de2f27d47767129a6a905c84f470:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:bf59355a6d8a42552f258c9ef7327e077309667bbb4d7a410ab891dea95bc3ba: done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:7a3f95c078122f959979fac556ae6f43746c9f32e5a66526bb503ed1d4adbd07:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:6d29a096dd42e5e003949f934fa6b1a3ec8e076dd8cfc2a85a4e750a3639bf7a:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:b2c20fd96d4421f46e1f22bc385514b46b7a0278e8c0cc66ad2d15b20b446946:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:1d6368a7ae7d4114b8cf99df0ecafdcba94eaf8bffb5df31001b4738eae7d929:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:082d73fa4431b591a746b135519656cfb11cee3ca757d8f56000c42b65d33c34:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:08d4c0cc9f6f08c6381eec5e8664fdfe8a2ce854b3230605ce00ca1bf35c1c39:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:4ffee2b99561b86e7e03bf0819172806c21c69624fdf1b5fd56273ae52d6608b:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:81815610209d2f9b04f5a15fd617d8d30974efdbf8e676c1cefee754becc5819:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 34.6s                                                                    total:  65.8 M (1.9 MiB/s)
unpacking linux/arm64/v8 sha256:bc5eac5eafc581aeda3008b4b1f07ebba230de2f27d47767129a6a905c84f470...
done: 1.478168285s
```

**Comment by jackydalong** [comment]
@lucklymore fyi
https://github.com/clash-verge-rev/clash-verge-rev/issues/1976#issuecomment-2487746084

**Comment by lucklymore** [comment]
> 我遇到相同的问题（VirtualBox 里每个ubuntu VM只配置一个NAT 网卡），已解决，如下：
> 
> 1. host 上 Clash 打开 TUN mode
> 
> * <img alt="image" width="561" src="https://private-user-images.githubusercontent.com/20807562/387992416-cf4554dc-52d5-4558-b1f0-770262c7a268.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTU5MTMsIm5iZiI6MTczMjcxNTYxMywicGF0aCI6Ii8yMDgwNzU2Mi8zODc5OTI0MTYtY2Y0NTU0ZGMtNTJkNS00NTU4LWIxZjAtNzcwMjYyYzdhMjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEzNTMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YTQ5OGEyZGU4YmNmOGI4NzA0MWRkMjNkOGE0ZDlhNGI1ZmU3MGY0YjdjNTM0MTA2YzA4OWU2OTNkNzk2YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R10KWGSfWg8m-_Vs6uZq3JlVezqVrI3DwgW1TUpIM2I">
> 
> 2. VM 里  /etc/resolv.conf
> 
> ```
> # egrep name /etc/resolv.conf
> nameserver 8.8.8.8
> nameserver 1.1.1.1
> ```
> 
> 3. VM 里 pull image 可以了
> 
> ```python
> $ sudo ctr image pull docker.io/library/nginx:latest
> docker.io/library/nginx:latest:                                                   resolved       |++++++++++++++++++++++++++++++++++++++|
> index-sha256:bc5eac5eafc581aeda3008b4b1f07ebba230de2f27d47767129a6a905c84f470:    done           |++++++++++++++++++++++++++++++++++++++|
> manifest-sha256:bf59355a6d8a42552f258c9ef7327e077309667bbb4d7a410ab891dea95bc3ba: done           |++++++++++++++++++++++++++++++++++++++|
> config-sha256:7a3f95c078122f959979fac556ae6f43746c9f32e5a66526bb503ed1d4adbd07:   done           |++++++++++++++++++++++++++++++++++++++|
> layer-sha256:6d29a096dd42e5e003949f934fa6b1a3ec8e076dd8cfc2a85a4e750a3639bf7a:    done           |++++++++++++++++++++++++++++++++++++++|
> layer-sha256:b2c20fd96d4421f46e1f22bc385514b46b7a0278e8c0cc66ad2d15b20b446946:    done           |++++++++++++++++++++++++++++++++++++++|
> layer-sha256:1d6368a7ae7d4114b8cf99df0ecafdcba94eaf8bffb5df31001b4738eae7d929:    done           |++++++++++++++++++++++++++++++++++++++|
> layer-sha256:082d73fa4431b591a746b135519656cfb11cee3ca757d8f56000c42b65d33c34:    done           |++++++++++++++++++++++++++++++++++++++|
> layer-sha256:08d4c0cc9f6f08c6381eec5e8664fdfe8a2ce854b3230605ce00ca1bf35c1c39:    done           |++++++++++++++++++++++++++++++++++++++|
> layer-sha256:4ffee2b99561b86e7e03bf0819172806c21c69624fdf1b5fd56273ae52d6608b:    done           |++++++++++++++++++++++++++++++++++++++|
> layer-sha256:81815610209d2f9b04f5a15fd617d8d30974efdbf8e676c1cefee754becc5819:    done           |++++++++++++++++++++++++++++++++++++++|
> elapsed: 34.6s                                                                    total:  65.8 M (1.9 MiB/s)
> unpacking linux/arm64/v8 sha256:bc5eac5eafc581aeda3008b4b1f07ebba230de2f27d47767129a6a905c84f470...
> done: 1.478168285s
> 目前来说这个方案对于我来说还是不生效，还是同样的报错

**Comment by lucklymore** [comment]
> @lucklymore fyi [#1976 (comment)](https://github.com/clash-verge-rev/clash-verge-rev/issues/1976#issuecomment-2487746084)

感谢提供这个方案，想问下你那边是使用哪个代理提供商的产品，我更换另外的代理提供商产品后可以了，从这个方面来看，应该是代理提供商的问题导致的。

**Comment by Aaronchannn** [comment]
我把内核切换成预览版就可以了
![Clip_2024-12-09_15-57-43](https://github.com/user-attachments/assets/985f7fb7-8ff2-444a-a823-241887169826)

**Comment by EZ4BRUCE** [comment]
我升级了新版的 clash verge，然后也是遇到相同的问题，但我最终发现是 tunmode 的dns劫持导致的：

![Image](https://github.com/user-attachments/assets/e5710315-a16d-4c78-a122-87c027ffa771)

把这里置空之后，dns 设置为 8.8.8.8 就行了

![Image](https://github.com/user-attachments/assets/80e58606-bf35-4265-83cc-fd50589428f6)

**Comment by beishangeyu** [comment]
我只有开启 tun 模式才可以拉取镜像, 并且在开启 tun 模式之前, docker 自动给我配置的代理是 127.0.0.1:端口号, 然后开启 tun 模式之后在 wsl 中打 docker info 才会变成 http.docker.internal:端口号, 不清楚是为什么, 但是这样子确实让我可以拉取镜像了

**Comment by joker2018ll** [comment]
> 我升级了新版的 clash verge，然后遇到了类似的问题，docker pull 报错 tls handshakes timeout
> 
> 确认不是梯子的问题，但我最终发现是 tunmode 的dns劫持导致的：
> 
> ![Image](https://github.com/user-attachments/assets/e5710315-a16d-4c78-a122-87c027ffa771)
> 
> 把 tunmode 的 dns 劫持这里置空就行了，不需要修改wsl2的dns (我的，保持原样)
> 
> ```
> # This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
> # [network]
> # generateResolvConf = false
> nameserver 10.255.255.254
> ```
> 
> 与此同时，这是我的wsl config
> 
> ```
> PS C:\Users\ez4br> cat C:\Users\ez4br\.wslconfig
> [experimental]
> autoMemoryReclaim=gradual  # gradual  | dropcache | disabled
> networkingMode=mirrored
> dnsTunneling=true
> firewall=true
> autoProxy=true
> hostAddressLoopback=true
> [wsl2]
> networkingMode=mirrored
> ```

/etc/wsl.conf 这个目录是虚拟机上的嘛，建议最后一个截图，我尝试多次都拉取失败
