### ISSUE TITLE
[BUG] service mode无法安装, resource 文件夹无法产生程序

### ISSUE THREAD

**Issue by Hellonuworld** [clash-verge-rev/clash-verge-rev#1977]
### 问题描述 / Describe the bug

想要把电脑的wifi共享给kindle
按照FAQ流程开启TUN模式后，无法上网，生成的网卡无法正确共享
具体表现：
1.设置里，服务模式右边无小地球
2.记得正确安装后，程序安装目录的resource文件夹内应该会多个service文件，但是我的没有
3.运行正常的话，应该虚拟网卡共享时会让我设置wifi名字，但是我的没有
4.开启TUN后，无法上网

已尝试以下，但是无效：
1.  尝试命令sc delete clash_verge_service
2. 尝试管理员运行程序及 install 与uninstall service 
3. 尝试 geek清理干净重新运行
![image](https://github.com/user-attachments/assets/3ffb4401-a083-4507-8e22-45a947f0fc8b)
![image](https://github.com/user-attachments/assets/9127c444-8198-43a1-94ba-e96cf7c15b46)
![image](https://github.com/user-attachments/assets/c8b0925b-c8f9-4fe1-8b56-6b067df1cb69)

### 软件版本 / Verge Version

V1.7.7

### 复现步骤 / To Reproduce

设置-服务模式

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 专业版22631

### 日志 / Log

11-02 23:38:04warning
[TUN] default interface changed by monitor, => WLAN
11-02 23:38:11warning
[TCP] dial DIRECT (match DomainSuffix/microsoft.com) 127.0.0.1:49305 --> access-point.cloudmessaging.edge.microsoft.com:443 error: dns resolve failed: couldn't find ip
11-02 23:38:11warning
[TCP] dial 龙猫云 - TotoroCloud (match DomainKeyword/google) 127.0.0.1:49301 --> mtalk.google.com:5228 error: lmnode-103ee357.ixd3fh2v5uqlv3z-lmjp.lma1b2.com:50041 connect error: dns resolve failed: couldn't find ip
11-02 23:38:11warning
[TCP] dial 龙猫云 - TotoroCloud (match Match/) 198.18.0.1:61704 --> dns.alidns.com:443 error: lmnode-103ee357.ixd3fh2v5uqlv3z-lmjp.lma1b2.com:50041 connect error: dns resolve failed: couldn't find ip
11-02 23:38:11warning
[TCP] dial DIRECT (match DomainSuffix/microsoft.com) 127.0.0.1:49308 --> access-point.cloudmessaging.edge.microsoft.com:443 error: dns resolve failed: couldn't find ip
11-02 23:38:14warning
[TCP] dial DIRECT (match DomainSuffix/microsoft.com) 198.18.0.1:61723 --> www.microsoft.com:443 error: dns resolve failed: couldn't find ip
11-02 23:38:14warning
[TCP] dial DIRECT (match DomainSuffix/microsoft.com) 198.18.0.1:61719 --> www.microsoft.com:443 error: dns resolve failed: couldn't find ip
11-02 23:38:16warning
[TCP] dial 龙猫云 - TotoroCloud (match DomainKeyword/google) 127.0.0.1:49361 --> mtalk.google.com:5228 error: lmnode-103ee357.ixd3fh2v5uqlv3z-lmjp.lma1b2.com:50041 connect error: dns resolve failed: couldn't find ip
11-02 23:38:16warning
[TCP] dial DIRECT (match DomainSuffix/microsoft.com) 127.0.0.1:49359 --> access-point.cloudmessaging.edge.microsoft.com:443 error: dns resolve failed: couldn't find ip

**Comment by Hellonuworld** [comment]
想起来了，我是那个忧桑的 killer网卡

**Comment by Hellonuworld** [comment]
尝试了下把clash的进程都改为 实时优先级，但是无效。
额外，开启tun后电脑偶发性变得很卡，日志显示也不流畅
[2024-11-02-2352.log](https://github.com/user-attachments/files/17607527/2024-11-02-2352.log)

**Comment by Tychristine** [comment]
用 2.0版本
