### ISSUE TITLE
[BUG] auto选择节点 经常选的很慢的节点，不是最快的

### ISSUE THREAD

**Issue by flylj999** [clash-verge-rev/clash-verge-rev#1978]
### 问题描述 / Describe the bug

 auto选择节点 经常选的很慢的节点，不是最快的

### 软件版本 / Verge Version

1.7.7

### 复现步骤 / To Reproduce

代理选择中，选择自动选择

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

阿打发发来的上课时间发啦卡机

**Comment by Tychristine** [comment]
#1887
