### ISSUE TITLE
[Feature] 請問在PC怎麽讓特定軟件走直連呢

### ISSUE THREAD

**Issue by 39YukiSakura** [clash-verge-rev/clash-verge-rev#1979]
### 功能描述 / Feature description

[文檔](https://www.clashverge.dev/guide/merge.html)說新建merge規則可是我軟件新建沒有這個選項
![微信截图_20241103210600](https://github.com/user-attachments/assets/9f36972c-5d28-4807-abe4-d2c24adb62ab)

### 使用场景 / Use case

想把youdao這個改成直連
![微信截图_20241103210837](https://github.com/user-attachments/assets/077d5e04-2127-45af-a8e4-6c1773712bcf)

**Comment by YhnSoft** [comment]
是编辑下方全局扩展配置而不是新建配置

**Comment by Tychristine** [comment]
```yaml
rules:
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT,no-resolve
 ```

**Comment by 39YukiSakura** [comment]
> 是编辑下方全局扩展配置而不是新建配置

可能我第一次弄這個 不知道對不對 顯示出來是黃色的 而且保存后軟件還是走的代理
![微信截图_20241103215710](https://github.com/user-attachments/assets/7c7e2bae-65fe-4990-be7c-ef23b8e250ce)
![微信截图_20241103215807](https://github.com/user-attachments/assets/abe39c49-3f3a-4dc9-b75b-1954a7f4917b)
