### ISSUE TITLE
[BUG]在 macbook pro 2017 打开TUN模式下面没有服务模式，

### ISSUE THREAD

**Issue by wxdjs** [clash-verge-rev/clash-verge-rev#198]
### Describe the bug

打开1.4.5，发现TUN模式开关下没有服务模式，导致无法安装服务，出现错误

### To Reproduce

重新打开app，重启机器，还是这样

### Platform

MacOS

### System Version

macOS 13.6.3

### Software Version

1.4.5

### Log

[TUN] default interface changed by monitor, =>en0
Start TUN listening error: configure tun interface: Connect:operation not permitted

**Comment by moranno** [comment]
看FAQ: https://github.com/clash-verge-rev/clash-verge-rev/issues/125

服务模式只有win系统需要。

**Comment by wxdjs** [comment]
不好意思，因为在mac上没法打开tun模式，代理模式正常，以为有那个tun模式，

**Comment by moranno** [comment]
看FAQ: https://github.com/clash-verge-rev/clash-verge-rev/issues/125
第三条”mac/linux请在设置的clash内核点开⚙️，点"授权" ”

**Comment by ChasLui** [comment]
> 看FAQ: #125 第三条”mac/linux请在设置的clash内核点开⚙️，点"授权" ”

我每次重启机器都要点一次授权,很麻烦, 没有clash for windows for mac的服务模式好用
