### ISSUE TITLE
[BUG] 外接显示器导致窗口变成一小块长方形的问题

### ISSUE THREAD

**Issue by zsedcbm** [clash-verge-rev/clash-verge-rev#1984]
### 问题描述 / Describe the bug

笔记本显示器1920*1080，软件最小化窗口，当外接或拔出一个4k显示器之后，重新打开软件窗口的就变成很小的一个长方形，无法显示软件内容，需要手动拖拽边缘才能重新变回正常窗口，希望能修复一下该问题。

### 软件版本 / Verge Version

v1.7.7

### 复现步骤 / To Reproduce

1. 打开软件，最小化窗口
2. 外接4k显示器，或者拔出显示器
3. 重新打开软件

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

[2024-11-04-2133.log](https://github.com/user-attachments/files/17618770/2024-11-04-2133.log)

**Comment by wonfen** [comment]
2.0应该修复了。
https://github.com/clash-verge-rev/clash-verge-rev/issues/1887
