### ISSUE TITLE
[BUG] 热键冲突，version：2.0.0，CMD + Q 与Mac默认的退出热键相冲突

### ISSUE THREAD

**Issue by peiliu0408** [clash-verge-rev/clash-verge-rev#1985]
### 问题描述 / Describe the bug

APP默认的退出热键，CMD + Q， 与Mac默认的退出热键相冲突。希望能够通过设置，更改为其它的热键。

### 软件版本 / Verge Version

v2.0.0

### 复现步骤 / To Reproduce

<img width="209" alt="截屏2024-11-05 09 54 29" src="https://github.com/user-attachments/assets/aa1736e4-008e-4c7a-8a49-52289c6d1246">
如上图所示，当软件打开时，mac本身的默认退出热键，cmd + Q，就会被占用，发生冲突。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1

### 日志 / Log

无。

**Comment by wonfen** [comment]
只有当软件窗口在最前的时候才会占用cmd q快捷键，和其他软件一样的逻辑。并不不妥。

如果你那边有问题，说明你下载安装的不是最新版；这个问题之前修复过了。
