### ISSUE TITLE
[Feature] 关于某网页可以检测出使用人在使用clash verge

### ISSUE THREAD

**Issue by whoisec** [clash-verge-rev/clash-verge-rev#1987]
### 功能描述 / Feature description

https://mikewang000000.github.io/ClashScan/ 此网页可以检测出使用clash vege，可以添加相关的功能隐藏吗

### 使用场景 / Use case

交流

**Comment by Tychristine** [comment]
![image](https://github.com/user-attachments/assets/4e34cc5e-7758-4624-bf0a-f7ee33f31b3a)

# 检测不到

**Comment by medz** [comment]
检测原理很简单，从 a-b 范围的 127.0.0.1:[port] 挨个请求。你把外部 GUI 管理 API 关闭即可。

这玩意一点技术含量都没有。

**Comment by sdgsgsdf** [comment]
> 检测原理很简单，从 a-b 范围的 127.0.0.1:[port] 挨个请求。你把外部 GUI 管理 API 关闭即可。
> 
> 这玩意一点技术含量都没有。

大佬怎么关哇

**Comment by whoisec** [comment]
![QQ截图20241105214437](https://github.com/user-attachments/assets/7feb512c-0c9d-4334-abff-9db874728bff)
![QQ截图20241105214507](https://github.com/user-attachments/assets/8a0d7d2e-0b2f-439c-bf75-67b3390db469)
嗯呢 就是不单单此网页吧  这个不知道咋个隐藏啊 用是好用  这是我自己的一个情况

**Comment by whoisec** [comment]
![微信截图_20241105214536](https://github.com/user-attachments/assets/7946b898-9241-4770-b8db-bce967c5c4da)

**Comment by sdgsgsdf** [comment]
> @sdgsgsdf https://wiki.metacubex.one/config/general/#api

是去配置文件里把这个监听地址给删了？还是说注释掉哪一行来关闭哇大佬？

**Comment by Tychristine** [comment]
@sdgsgsdf 不用管，CVR给的默认值是`127.0.0.1:9097` 并无不妥，并且GUI需要此端口与Mihomo Core通信

**Comment by medz** [comment]
> > 检测原理很简单，从 a-b 范围的 127.0.0.1:[port] 挨个请求。你把外部 GUI 管理 API 关闭即可。
> > 这玩意一点技术含量都没有。
> 
> 大佬怎么关哇

<img width="739" alt="image" src="https://github.com/user-attachments/assets/1639942f-c1d1-442a-870b-05f00452926d">
设置，外部控制

**Comment by sdgsgsdf** [comment]
> > > 检测原理很简单，从 a-b 范围的 127.0.0.1:[port] 挨个请求。你把外部 GUI 管理 API 关闭即可。
> > > 这玩意一点技术含量都没有。
> > 
> > 
> > 大佬怎么关哇
> 
> <img alt="image" width="739" src="https://private-user-images.githubusercontent.com/5564821/383174860-1639942f-c1d1-442a-870b-05f00452926d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTUzOTEsIm5iZiI6MTczMDgxNTA5MSwicGF0aCI6Ii81NTY0ODIxLzM4MzE3NDg2MC0xNjM5OTQyZi1jMWQxLTQ0MmEtODcwYi0wNWYwMDQ1MjkyNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMTM1ODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTYxNDg3YTQyZWEyMmY2ODAxN2I2YjVkNTkxOTkwMWI5MDExNGIyNTU1MWUyYzhhNTNmMDU2OTA5NWU2MWY0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.v1vt20mf8jBpr-5Wd7GfM-6W6B0Sg1rUIoZBBX8jdTY"> 设置，外部控制

这不就是默认的设置吗？而且就算删掉了，他也会变回原样哇

**Comment by medz** [comment]
> > > > 检测原理很简单，从 a-b 范围的 127.0.0.1:[port] 挨个请求。你把外部 GUI 管理 API 关闭即可。
> > > > 这玩意一点技术含量都没有。
> > > 
> > > 
> > > 大佬怎么关哇
> > 
> > 
> > <img alt="image" width="739" src="https://private-user-images.githubusercontent.com/5564821/383174860-1639942f-c1d1-442a-870b-05f00452926d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTUzOTEsIm5iZiI6MTczMDgxNTA5MSwicGF0aCI6Ii81NTY0ODIxLzM4MzE3NDg2MC0xNjM5OTQyZi1jMWQxLTQ0MmEtODcwYi0wNWYwMDQ1MjkyNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMTM1ODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTYxNDg3YTQyZWEyMmY2ODAxN2I2YjVkNTkxOTkwMWI5MDExNGIyNTU1MWUyYzhhNTNmMDU2OTA5NWU2MWY0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.v1vt20mf8jBpr-5Wd7GfM-6W6B0Sg1rUIoZBBX8jdTY"> 设置，外部控制
> 
> 这不就是默认的设置吗？而且就算删掉了，他也会变回原样哇

设置密钥，更改为其他冷门端口即可。我特意恢复成默认截图给你的

**Comment by sdgsgsdf** [comment]
> > > > > 检测原理很简单，从 a-b 范围的 127.0.0.1:[port] 挨个请求。你把外部 GUI 管理 API 关闭即可。
> > > > > 这玩意一点技术含量都没有。
> > > > 
> > > > 
> > > > 大佬怎么关哇
> > > 
> > > 
> > > <img alt="image" width="739" src="https://private-user-images.githubusercontent.com/5564821/383174860-1639942f-c1d1-442a-870b-05f00452926d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTUzOTEsIm5iZiI6MTczMDgxNTA5MSwicGF0aCI6Ii81NTY0ODIxLzM4MzE3NDg2MC0xNjM5OTQyZi1jMWQxLTQ0MmEtODcwYi0wNWYwMDQ1MjkyNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMTM1ODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTYxNDg3YTQyZWEyMmY2ODAxN2I2YjVkNTkxOTkwMWI5MDExNGIyNTU1MWUyYzhhNTNmMDU2OTA5NWU2MWY0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.v1vt20mf8jBpr-5Wd7GfM-6W6B0Sg1rUIoZBBX8jdTY"> 设置，外部控制
> > 
> > 
> > 这不就是默认的设置吗？而且就算删掉了，他也会变回原样哇
> 
> 设置密钥，更改为其他冷门端口即可。我特意恢复成默认截图给你的

soga，感谢

**Comment by sdgsgsdf** [comment]
> @sdgsgsdf 不用管，CVR给的默认值是`127.0.0.1:9097` 并无不妥，并且GUI需要此端口与Mihomo Core通信

似乎是哈，如果强制清空，似乎会没办法正常使用
