### ISSUE TITLE
[BUG] 无法安装->无法定位软件包 libwebkit2gtk-4.0-37

### ISSUE THREAD

**Issue by Little1Git** [clash-verge-rev/clash-verge-rev#1988]
### 问题描述 / Describe the bug

Ubuntu 24.04.1 LTS

无法安装->无法定位软件包 libwebkit2gtk-4.0-37

### 软件版本 / Verge Version

apt install ./clash-verge_1.7.7_amd64.deb

### 复现步骤 / To Reproduce

apt install ./clash-verge_1.7.7_amd64.deb 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
注意，选中 'clash-verge' 而非 './clash-verge_1.7.7_amd64.deb'
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 clash-verge : 依赖: libwebkit2gtk-4.0-37 但无法安装它
 
 # lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble

Ubuntu 24.04.1 LTS    

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu 24.04.1 LTS

### 日志 / Log

# apt install ./clash-verge_1.7.7_amd64.deb 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
注意，选中 'clash-verge' 而非 './clash-verge_1.7.7_amd64.deb'
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 clash-verge : 依赖: libwebkit2gtk-4.0-37 但无法安装它
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。
root@qy-OMEN-by-HP-Laptop-15-dc1xxx:/home/qy/下载# apt show libwebkit2gtk-4.0-37
N: 无法定位软件包 libwebkit2gtk-4.0-37
N: 无法按照 glob ‘libwebkit2gtk-4.0-37’ 找到任何软件包
N: 无法定位软件包 libwebkit2gtk-4.0-37
N: 无法按照 glob ‘libwebkit2gtk-4.0-37’ 找到任何软件包
E: 没有发现匹配的软件包
root@qy-OMEN-by-HP-Laptop-15-dc1xxx:/home/qy/下载# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
root@qy-OMEN-by-HP-Laptop-15-dc1xxx:/home/qy/下载# sudo apt update
命中:1 http://mirrors.aliyun.com/ubuntu noble InRelease
获取:2 https://dl.google.com/linux/chrome/deb stable InRelease [1825 B]    
获取:3 http://mirrors.aliyun.com/ubuntu noble-updates InRelease [126 kB]                                    
命中:4 http://mirrors.aliyun.com/ubuntu noble-backports InRelease                    
获取:5 https://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1226 B]
获取:6 http://mirrors.aliyun.com/ubuntu noble-updates/main amd64 Packages [615 kB]                       
获取:7 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]         
获取:8 http://security.ubuntu.com/ubuntu noble-security/main amd64 Components [7228 B]
获取:9 http://security.ubuntu.com/ubuntu noble-security/restricted amd64 Components [212 B]
获取:10 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Components [51.9 kB]
获取:11 http://security.ubuntu.com/ubuntu noble-security/multiverse amd64 Components [208 B]
已下载 929 kB，耗时 3秒 (297 kB/s)  
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
有 4 个软件包可以升级。请执行 ‘apt list --upgradable’ 来查看它们。
root@qy-OMEN-by-HP-Laptop-15-dc1xxx:/home/qy/下载# sudo apt install libwebkit2gtk-4.0-37
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libwebkit2gtk-4.0-37
E: 无法按照 glob ‘libwebkit2gtk-4.0-37’ 找到任何软件包
root@qy-OMEN-by-HP-Laptop-15-dc1xxx:/home/qy/下载# apt show libwebkit2gtk
N: 无法定位软件包 libwebkit2gtk
N: 无法定位软件包 libwebkit2gtk
E: 没有发现匹配的软件包

**Comment by Little1Git** [comment]
求更新

**Comment by wypeng2012** [comment]
https://www.clashverge.dev/faq/linux.html       大哥看这里，有解决方案

**Comment by lanwanc** [comment]
> https://www.clashverge.dev/faq/linux.html       大哥看这里，有解决方案

谨慎安装，安装这些库之后，本地环境的其他库用不了了

**Comment by wonfen** [comment]
请使用2.0版。解决了依赖问题。
