### ISSUE TITLE
[Feature] 安全，不显示订阅链接，避免被盗用

### ISSUE THREAD

**Issue by macrocodea** [clash-verge-rev/clash-verge-rev#1989]
### 功能描述 / Feature description

建议【订阅->编辑信息（编辑配置）】处，像Stash一样，不显示订阅链接，可以有效避免订阅链接被其他人盗用；

如果担心混淆，可以只显示域名，域名后面的URL则可以隐藏；

### 使用场景 / Use case

电脑的使用场景，相较于手机没有那么私密！（手机开屏都需要人脸或者指纹）如果是处在宿舍，电脑没有及时锁屏就有可能被其他人盗取；或者上班电脑，离开工位，通常都不可能每次都记得的点击锁定电脑。所以，希望开发者能够照顾到这一部分的需求。

**Comment by wonfen** [comment]
不准实现，人走锁屏，不在公共电脑上暴露自己的订阅信息是基本安全素养。
