### ISSUE TITLE
Windows平台程序自启动问题

### ISSUE THREAD

**Issue by StevenModin** [clash-verge-rev/clash-verge-rev#199]
平台：Windows 11 22H2
OS版本号：22621.2861
[问题发现]
安装路径：~\AppData\Local\Clash Verge\Clash Verge.exe
因为TUN模式必须以管理员权限启动，所以给程序兼容性设置了管理员模式。
然后软件就无法在开机时自启动了，关闭了管理员权限后又恢复正常。
[再次尝试]
考虑有可能是安装在用户目录的原因，
遂卸载，并以管理员权限安装在C:\Program Files文件夹下，但通过观察安装包执行过程发现，虽然通过管理员权限启动了安装包程序，但其中并没有用到管理员安装选项，后续尝试配置管理员兼容性后，又出现了不能自启动的状况，然后双击程序启动后发生了一次崩溃，崩溃的系统日志如下（其中最后两个选项在给出的日志中为空），之后使用多次暂时没有崩溃状况

错误应用程序名称: Clash Verge.exe，版本: 1.4.4.0，时间戳: 0x657684d9
错误模块名称: ntdll.dll，版本: 10.0.22621.2506，时间戳: 0xbced4b82
异常代码: 0xc0000374
错误偏移量: 0x000000000010c7a9
错误进程 ID: 0x0xC30
错误应用程序启动时间: 0x0x1DA3B4E97B8ADFE
错误应用程序路径: C:\Program Files\Clash Verge\Clash Verge.exe
错误模块路径: C:\Windows\SYSTEM32\ntdll.dll
报告 ID: 85517967-df26-4e4f-b12a-521bbd88f478
错误程序包全名:
错误程序包相对应用程序 ID:

**Comment by wonfen** [comment]
需要随系统启动，可以尝试安装服务模式，无需使用管理员模式运行即可启用tun模式。

**Comment by MystiPanda** [comment]
autoLaunch目前不支持在管理员权限下设置开机启动，常规用法是开启服务模式，不要用管理员权限运行软件，这个问题后续会考虑修复的。

**Comment by efaun** [comment]
可以手动添加启动项
https://answers.microsoft.com/zh-hans/windows/forum/all/windows11%E6%97%A0%E6%B3%95%E4%BB%A5%E7%AE%A1/7f2ec19d-7682-4c00-99f3-ecaf9990130e
