### ISSUE TITLE
[BUG] 在关闭软件后，代理服务器会自动打开

### ISSUE THREAD

**Issue by WilliamZYF98** [clash-verge-rev/clash-verge-rev#1991]
### 问题描述 / Describe the bug

在使用Clash Verge软件后，关闭软件并退出后关闭电脑，第二天打开，发现网络无法连接，在系统设置-网络和Internet-代理中发现“自动设置代理”项下“使用设置脚本”项和“手动设置代理”项下“使用代理服务器”项是打开状态，手动关闭两项后网络恢复正常，但在约几分钟后再次出现断网情况，发现“手动设置代理”项下“使用代理服务器”项再次被打开，再次手动关闭，后续多次出现这种情况，重装Clash Verge甚至卸载后，依然会出现这种情况。

### 软件版本 / Verge Version

1.4.10_x64

### 复现步骤 / To Reproduce

无须复现步骤，直接过几分钟固定出现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11

### 日志 / Log

已经卸载软件

**Comment by itlaohui** [comment]
你是开启过这个吗？
![image](https://github.com/user-attachments/assets/e102a920-8a03-42a4-9e2a-6d8cf5dc73eb)

**Comment by WilliamZYF98** [comment]
> 你是开启过这个吗？ ![image](https://private-user-images.githubusercontent.com/75066134/383897382-e102a920-8a03-42a4-9e2a-6d8cf5dc73eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzIyNTEsIm5iZiI6MTczMDk3MTk1MSwicGF0aCI6Ii83NTA2NjEzNC8zODM4OTczODItZTEwMmE5MjAtOGEwMy00MmE0LTllMmEtNmQ4Y2Y1ZGM3M2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA5MzIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiM2Q4NzkzMTkzMWM1NTE2NzNhZDQxZTY5MjgyOWY2YTJmZmZhM2FmMTEwYjU4YjFlNzBlYTY2YmY2ZDExNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.avdQlZwJJaG0xJMTCNtzBJ7O9HoMt-1irK7x_TcI0WQ)

似乎没有，我重新下载下来看看

**Comment by Tychristine** [comment]
不看1.x 版本的反馈，请更新到2.0.0-rc.5版本再新起 issue
