### ISSUE TITLE
[BUG] 自启动的优先级

### ISSUE THREAD

**Issue by qasd93991** [clash-verge-rev/clash-verge-rev#1994]
### 问题描述 / Describe the bug

在自启动的时候 clash verge 没有 OneDrive 启动快，导致在 OneDrive 启动后一直使用系统代理 127.0.0.1：7890 登录，一直登陆不上（这时候 clash verge 还没有启动，所以登不上），需要 OneDrive 重启一次，才能登上（这时候 clash verge 已经启动，所以 127.0.0.1：7890 是可以登录的）。如果 clash verge 先于 OneDrive 自启动，这样就不会出现这个问题了。使用了 clash.meta（mihomo）其他 GUI 均无此现象（clash 启动滞后）

### 软件版本 / Verge Version

2.0.0-rc5

### 复现步骤 / To Reproduce

如题

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 23H2

### 日志 / Log

无

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1558
重复关闭
