### ISSUE TITLE
[BUG] 系统代理打开几秒后 就会自动关闭 甚至还会直接卡死，要到任务管理器中结束任务

### ISSUE THREAD

**Issue by lpxks** [clash-verge-rev/clash-verge-rev#2000]
### 问题描述 / Describe the bug

系统代理打开几秒后 就会自动关闭 甚至还会直接卡死，要到任务管理器中结束任务

### 软件版本 / Verge Version

1.7.7

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows10

### 日志 / Log

无

**Comment by Tychristine** [comment]
#1881 
不再接受1.x历史版本的issue，更新到最新版本再提
