### ISSUE TITLE
[BUG] msedgewebview2.exe占据了较多的CPU时间

### ISSUE THREAD

**Issue by Chlheng** [clash-verge-rev/clash-verge-rev#2002]
### 问题描述 / Describe the bug

只要点开过GUI，就会在后台驻留6个msedgewebview2.exe进程，其中以下两个进程的CPU时间特别大：
第一个：
"C:\Program Files (x86)\Microsoft\EdgeWebView\Application\130.0.2849.68\msedgewebview2.exe" --type=gpu-process --string-annotations=is-enterprise-managed=no --noerrdialogs --user-data-dir="C:\Users\Chlheng\AppData\Local\io.github.clash-verge-rev.clash-verge-rev\EBWebView" --webview-exe-name=clash-verge.exe --webview-exe-version=2.0.0 --embedded-browser-webview=1 --embedded-browser-webview-dpi-awareness=2 --gpu-preferences=UAAAAAAAAADgAAAEAAAAAAAAAAAAAAAAAABgAAEAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --field-trial-handle=1872,i,13718506722621524279,3442634773335338987,262144 --enable-features=msWebView2EnableDraggableRegions --disable-features=OverscrollHistoryNavigation,msExperimentalScrolling --variations-seed-version --mojo-platform-channel-handle=1860 /prefetch:2 /pfhostedapp:800bc65d754a73e0fc5211f084c6e024f9199e01

第二个：
"C:\Program Files (x86)\Microsoft\EdgeWebView\Application\130.0.2849.68\msedgewebview2.exe" --type=renderer --string-annotations=is-enterprise-managed=no --noerrdialogs --user-data-dir="C:\Users\Chlheng\AppData\Local\io.github.clash-verge-rev.clash-verge-rev\EBWebView" --webview-exe-name=clash-verge.exe --webview-exe-version=2.0.0 --embedded-browser-webview=1 --embedded-browser-webview-dpi-awareness=2 --video-capture-use-gpu-memory-buffer --lang=zh-CN --device-scale-factor=1.25 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=5 --js-flags="--harmony-weak-refs-with-cleanup-some --expose-gc --ms-user-locale=" --time-ticks-at-unix-epoch=-1731205264116808 --launch-time-ticks=6328254120 --field-trial-handle=3556,i,13718506722621524279,3442634773335338987,262144 --enable-features=msWebView2EnableDraggableRegions --disable-features=OverscrollHistoryNavigation,msExperimentalScrolling --variations-seed-version --mojo-platform-channel-handle=3580 /pfhostedapp:800bc65d754a73e0fc5211f084c6e024f9199e01 /prefetch:1

这两个进程是所有待机进程中占用CPU时间最大的。

![2024-11-10_155306](https://github.com/user-attachments/assets/62d4d405-1086-4d48-b0cc-66e2ada5e953)

### 软件版本 / Verge Version

v2.0.0-rc.5

### 复现步骤 / To Reproduce

打开Clash Verge Rev，点开界面（如果选择了静默启动的话），直至出现msedgewebview2.exe进程之后关闭界面，在后台等待一段时间，观察以上提到的两个进程的CPU时间。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 27744.1000

### 日志 / Log

无

**Comment by ZZBSMJ** [comment]
我win10也可以观察到这个现象。

**Comment by kty00** [comment]
这个有啥影响么？我比较关心性能，才是资源占用。性能高，占用较少的资源，这是我喜欢的。

**Comment by wonfen** [comment]
正常的；Verge使用的框架Tauri使用WebView Rendering Library 作为渲染引擎。

**Comment by Chlheng** [comment]
> 使用WebView Rendering Library 作为渲染引擎

使用WebView Rendering Library 作为渲染引擎这个没问题，但这是我见过使用WebView Rendering Library 作为渲染引擎的应用中后台占用率最高的，它的占用率甚至与我用ToDesk作远程控制时ToDesk进程的占用率相当。

**Comment by wonfen** [comment]
> > 使用WebView Rendering Library 作为渲染引擎
> 
> 使用WebView Rendering Library 作为渲染引擎这个没问题，但这是我见过使用WebView Rendering Library 作为渲染引擎的应用中后台占用率最高的，它的占用率甚至与我用ToDesk作远程控制时ToDesk进程的占用率相当。

是不是cpu太老了，都是标准库。也没法优化了。
