### ISSUE TITLE
[BUG] clash失去焦点或切换至后台无法监听快捷键

### ISSUE THREAD

**Issue by ZoroGH** [clash-verge-rev/clash-verge-rev#2004]
### 问题描述 / Describe the bug

设置了开启代理和关闭代理的快捷键，clash verge rev界面在前台显示且焦点在clash软件界面上时，可以使用快捷键来开启或关闭代理，当失焦或者进入后台之后就失效。

我自己的电脑是win11，前几天我用manjaro安装时也出现了这个问题，不过那个是1.7.7版本。

### 软件版本 / Verge Version

v2.0.0-rc.5

### 复现步骤 / To Reproduce

- 设置系统代理快捷键Ctrl + Alt + Q
- 点击clash verge rev界面，尝试切换快捷键，观察是否正常
- 切换到浏览器（别的应用也行）界面，再尝试快捷键
- 最小化clash verge rev到后台，再次尝试

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 23H2

### 日志 / Log

-

**Comment by wonfen** [comment]
因为默认把Ctrl+Q分配给了退出程序，你分配了这2个按键可能触发了某些冲突，随便把Q换掉就好了。

**Comment by ZoroGH** [comment]
感谢，已更改
