### ISSUE TITLE
[BUG] rc5最新版 steam分流直连时 steamcommunity_302代理无效 社区无法访问

### ISSUE THREAD

**Issue by Andynet911** [clash-verge-rev/clash-verge-rev#2005]
### 问题描述 / Describe the bug

steam分流直连时 steamcommunity_302代理无效 社区无法访问 系统代理关上就可以访问

### 软件版本 / Verge Version

Clash.Verge_2.0.0-rc.5_x64

### 复现步骤 / To Reproduce

steam社区分流直连 steamcommunity_302在后台挂着 社区无法访问 系统代理关上就可以访问
换回Clash.Verge_1.7.7系统代理打开访问正常 订阅和规则全部一样

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 24h2

### 日志 / Log

[2024-11-11-2011.log](https://github.com/user-attachments/files/17702199/2024-11-11-2011.log)

**Comment by Tychristine** [comment]
日志空白，且问题无关GUI
好歹给个内核日志吧

**Comment by Tychristine** [comment]
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Steam
拿去自己补好规则

**Comment by Andynet911** [comment]
> 日志空白，且问题无关GUI 好歹给个内核日志吧

[Uploading 2024-11-11-2028.log…]()

**Comment by Andynet911** [comment]
[2024-11-11-2028.log](https://github.com/user-attachments/files/17702364/2024-11-11-2028.log)

**Comment by Tychristine** [comment]
@Andynet911 你的日志没有任何毛病，把Steam分流走`Direct`策略了社区*302*打不开是正常啊。没准商店页面还能`-118`代码呢

**Comment by Andynet911** [comment]
> @Andynet911 你的日志没有任何毛病，把Steam分流走`Direct`策略了社区_302_打不开是正常啊。没准商店页面还能`-118`代码呢

我是clash分流steam直连,然后使用steamcommunity_302这个软件本地反代steam就可以正常访问社区,商店了,但是更新到最新版这个方法就不行了 目前回到1.7.7一切正常
![Snipaste_2024-11-11_21-39-53](https://github.com/user-attachments/assets/30341447-8481-4b07-8248-68ae234a2b3a)
![Snipaste_2024-11-11_21-43-18](https://github.com/user-attachments/assets/b31dc05f-74a3-47c5-a523-696815fb44fc)

**Comment by Andynet911** [comment]
在2.0RC5里面也看不到这条分流后的连接
2.0RC5
![Snipaste_2024-11-11_21-58-16](https://github.com/user-attachments/assets/507b3ed5-b637-4547-9195-b3245239f59c)
1.7.7
![Snipaste_2024-11-11_22-02-17](https://github.com/user-attachments/assets/19b2310a-ec8c-4612-b336-ee882bb9cb9d)

**Comment by Andynet911** [comment]
我把2.0rc5(20d163c) 1.18.10内核换回1.18.9之后解决了

**Comment by Tychristine** [comment]
> [!TIP]
> 提一个最佳方案

在上面我提到的规则库中有 “Steam” 和 "SteamCN" 规则集
在Steam中更改下载设置，把下载地区切换到可直连的地区
```yaml
rules:
  RULE-SET,SteamCN,DIRECT
  RULE-SET,Steam,Proxy
```
同理Clash一招就解决了流畅登录Steam,Epic,EAapp等

**Comment by Andynet911** [comment]
此问题在配置文件中增加即可解决
 use-system-hosts: true

**Comment by u2shana** [comment]
> 此问题在配置文件中dns:下增加 `use-system-hosts: true` 即可解决

遇到同样的问题，你这招我不生效，现在怎么处理的?
