### ISSUE TITLE
[BUG] https://github.com/clash-verge-rev/clash-verge-rev/issues/1553（此bug在最新版中仍然存在）

### ISSUE THREAD

**Issue by AquaSimulacra** [clash-verge-rev/clash-verge-rev#2006]
### 问题描述 / Describe the bug

将Clash日志级别调整为Debug之后，GUI的日志模块并没有显示Debug日志

### 软件版本 / Verge Version

2.0.0 rc5

### 复现步骤 / To Reproduce

将Clash日志级别调整为Debug之后,重启应用

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26100.2161

### 日志 / Log

N/A

**Comment by wonfen** [comment]
GUI的日志需要在杂项设置里调整

**Comment by AquaSimulacra** [comment]
![image](https://github.com/user-attachments/assets/046f0a3c-8b8f-470d-b1f0-dc00a9b1d20e)
![image](https://github.com/user-attachments/assets/e260a60f-3abb-402f-a5c6-bc83c07d69fa)
调整完之后仍然没有显示

**Comment by wonfen** [comment]
发issue的时候就写的很清楚了：
日志文件在“软件左侧菜单”->“设置”->“日志目录”下

软件菜单里的日志只是内核日志
