### ISSUE TITLE
[Feature] 希望增加导出配置的功能

### ISSUE THREAD

**Issue by EnderAvaritia** [clash-verge-rev/clash-verge-rev#2007]
### 功能描述 / Feature description

希望能够增加导出配置的功能，能够导出导入已有的配置信息，同时导出的配置信息可以较为方便的修改，方便在多平台之间迁移

### 使用场景 / Use case

对于有多个平台，多个订阅的情况下，又或者是对每个订阅需要修改一点点信息，目前没有较为方便的处理方式，是否可以将配置文件打包成一个文件或者是别的方式，使得可以在新的平台上快速部署，又或者是在使用订阅转换而订阅转换的网址更换的情况下，可以批量修改订阅信息

**Comment by wonfen** [comment]
2.0已经支持webdav备份

**Comment by EnderAvaritia** [comment]
> 2.0已经支持webdav备份

可以提供保存在本地的功能吗？

**Comment by Tychristine** [comment]
@EnderAvaritia 本地的话,自己用shell写一个脚本就行

**Comment by EnderAvaritia** [comment]
> @EnderAvaritia 本地的话,自己用shell写一个脚本就行

我有个需求，可能很怪，目前有8个常用订阅以及带订阅转换的订阅，订阅转换是自建的，前段时间因为域名问题变了好几次，每次变了之后需要同时改几个域名，都是把前面相同的部分换掉，同时，我有三台电脑，两台win，一台lin，一个一个改实在是太糟心
我还有两个安卓设备，听说2.0.0版本换了全平台的框架，不知道以后会不会上安卓，扩展脚本用的还是挺舒服的，目前在安卓上使用的是cmfa，每次修改配置都得重新拉取并校验，实在是烦，不知道有没有登陆安卓的计划，还是很希望能在安卓上用到的，从电脑迁移到手机能够方便很多

**Comment by EnderAvaritia** [comment]
> > > 2.0已经支持webdav备份
> > 
> > 
> > 可以提供保存在本地的功能吗？
> 
> 打开配置目录自己备份全班文件即可

好吧

**Comment by wonfen** [comment]
> 好吧

已经增加webdav备份功能
