### ISSUE TITLE
[BUG] rc6 怎么默认配置 unified-delay: true？

### ISSUE THREAD

**Issue by yixiuge301** [clash-verge-rev/clash-verge-rev#2009]
### 问题描述 / Describe the bug

在扩展配置定义了 unified-delay: false，但当前配置依然是 true，发现是 app 设置了这个字段

我在 1.7.7 中是没问题的，回退到 rc5，app 也没默认配置这个字段

### 软件版本 / Verge Version

[Clash.Verge_2.0.0-rc.6_x64-setup.exe](https://github.com/clash-verge-rev/clash-verge-rev/releases/download/alpha/Clash.Verge_2.0.0-rc.6_x64-setup.exe)

### 复现步骤 / To Reproduce

安装 app，导入订阅，查看当前配置。
![image](https://github.com/user-attachments/assets/5e857809-692c-411c-a79b-d2221f4b868f)

我建议但凡是app有定义配置的，最好都提供自定义的选项，因为配置默认以 app 为准，那写 script 都无效了。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

无

**Comment by yixiuge301** [comment]
只发现这个，延时低太假了，才发现的。

**Comment by wonfen** [comment]
在clash设置中修改。

**Comment by yixiuge301** [comment]
> 在clash设置中修改。

抱歉，没看到在设置中有设置选项！

**Comment by wonfen** [comment]
用最新版rc6，统一延迟。
<img width="655" alt="image" src="https://github.com/user-attachments/assets/756f7e2d-e778-44c6-aab6-ee3987f0cbab">

**Comment by yixiuge301** [comment]
> 用最新版rc6，统一延迟。 <img alt="image" width="655" src="https://private-user-images.githubusercontent.com/96291150/385566790-756f7e2d-e778-44c6-aab6-ee3987f0cbab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjcxMzIsIm5iZiI6MTczMTQ2NjgzMiwicGF0aCI6Ii85NjI5MTE1MC8zODU1NjY3OTAtNzU2ZjdlMmQtZTc3OC00NGM2LWFhYjYtZWUzOTg3ZjBjYmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAzMDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNjQ1ZDBkZDcyOWQ0ZmRiMmRlOGI2NjU0ODYwZTQ0OWM4NzliZDllZjMzMjJkMWYwMmE1MzI4YjRjNzNjOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bR4e5d5o_eg5T2htiD61i1HEbe-ssvxoBCKL6ENf8gk">

是，最开始没注意能设置，你提到可以设置，去看了下，确实可以设置，感谢。
