### ISSUE TITLE
[BUG] System Stack下， TUN 无法以管理员启动

### ISSUE THREAD

**Issue by Paulgudring** [clash-verge-rev/clash-verge-rev#201]
### Describe the bug

开发者和clash社区里其他成员们，大家新年快乐。

以下是问题描述，其实是一个老问题了，之前的讨论见[Clash Verge Issue #651](https://github.com/zzzgydi/clash-verge/issues/651)

使用system stack，用tun模式打开clash verge，无法建立虚拟网卡，log的报错见下。因为希望能够实现 nat fullcone 所以…… gvisor 只能算过渡之计。

### To Reproduce

控制变量法，有以下几组：

| 管理员权限[^1] | 服务模式 | 防火墙 | tun stack | 情况 |
| ---- | ---- | ---- | ---- | ---- |
| √ | √ |  | system | 正常 |
| √ | √ |  | mixed[^2] | 正常 |
| √ | √ |  | gvisor | 正常 |
| √ |  |  | system | 无法启动 |
| √ |  |  | mixed | 无法启动 |
| √ |  |  | gvisor | 正常 |
| √ |  | √ | system | 无法启动 |
| √ |  | √ | mixed | 无法启动 |
| √ |  | √ | gvisor | 正常 |
| 特别地，使用裸核 cli 运行，√ |  | √ | system | 正常 |

最奇怪的在于，讨论中说到的问题核心是防火墙放行，如果缺少权限的话应该是“permission denied”。实际上使用cli跑裸核甚至无需防火墙放行，正如[`CC0126`](https://github.com/CC0126)所言。那么为了处理这个问题，我重置了防火墙规则，手动加入了meta内核公私网放行的规则，仍然无法在verge使用system stack启动tun。

[^1]: 管理员权限的讨论见原 issue，在原讨论中提到，verge 拉起的进程已经有管理员权限。在此处，防止问题存在，我为 verge、meta 内核都赋予了管理员权限。使用 cli 跑裸核时，我测试了，cli 以管理员运行和 cli+meta 都赋予管理员权限，两者都是可以正常使用 system stack 的。
[^2]: mixed stack tcp 使用 system stack，实际问题是由 system 导致的。

### Platform

Windows

### System Version

windows11

### Software Version

1.4.5+meta-alpha

### Log

```log
ERROR
Start TUN listening error: fix windows firewall for system stack: Error adding Rule: Exception occurred. (<nil>)
```

### Additional Information

原讨论中[`yueyejinghun`](https://github.com/yueyejinghun)有提到“为什么不使用服务模式”，其实是这样的啦，我有一台带出门的笔记本，所以用的便携版verge，这样两台电脑可以通过网盘来同步配置。安装服务模式，在注册表硬编码的情况下，两边对服务的映射不一样。

**Comment by x2nbit** [comment]
同样问题，管理员权限无法使用tun的system stack模式，meta虚拟网卡一闪即逝。
错误提示：level=error msg="Start TUN listening error: fix windows firewall for system stack: Error adding Rule: 发生意外。 (<nil>)"
