### ISSUE TITLE
[BUG] 2.x 最小化时，点托盘图标没反应

### ISSUE THREAD

**Issue by kty00** [clash-verge-rev/clash-verge-rev#2010]
### 问题描述 / Describe the bug

2.x 最小化时，点托盘图标没反应，不弹出 app 窗口

### 软件版本 / Verge Version

rc6

### 复现步骤 / To Reproduce

1. 鼠标左键单击系统托盘的app图标
![image](https://github.com/user-attachments/assets/7d6a9bb5-7874-454b-bf03-e3c15c781e2f)

2. 最小化 app
![image](https://github.com/user-attachments/assets/8a3c17f3-7b0d-4312-abab-c6f87a27213a)

3. 鼠标左键单击系统托盘的app图标
![image](https://github.com/user-attachments/assets/fbc940a0-3a1e-4cc9-9b45-cc0ae2cfabb4)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

没有

**Comment by yixiuge301** [comment]
可能跟这个有关系 https://github.com/clash-verge-rev/clash-verge-rev/issues/1890

**Comment by wonfen** [comment]
最小后以后在任务栏，托盘图标会显示菜单，当然不能通过托盘图标最大化了。
![image](https://github.com/user-attachments/assets/7c5b2b90-67f5-4660-b198-59aa9417af99)

**Comment by kty00** [comment]
> 最小后以后在任务栏，托盘图标会显示菜单，当然不能通过托盘图标最大化了。
> 
> ![image](https://private-user-images.githubusercontent.com/96291150/385876864-ce32b160-b086-4bdf-b907-9c9268ff56c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NDc2MTQsIm5iZiI6MTczMTU0NzMxNCwicGF0aCI6Ii85NjI5MTE1MC8zODU4NzY4NjQtY2UzMmIxNjAtYjA4Ni00YmRmLWI5MDctOWM5MjY4ZmY1NmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAxMjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZDI2ODhjMDliYTdmODAwNjMwNTdiNmJlNWJjYjNmMjhjZTUxZTY4MTQxZmIyNGIyM2I4MWViZWZkNTBlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SlsSFrbMALpNTbDykGpkdu0A-2nDIXYM4CqVLsrPxUI)

不对吧，不是最大化，是弹出窗口。你去用下 1.7.7 稳定版，或者微信。按 “复现步骤” 操作一遍，就知道啦。

**Comment by wonfen** [comment]
修复了，试试最新的alpha构建
