### ISSUE TITLE
[BUG] V2.0 RC6  WebDAV备份报错403

### ISSUE THREAD

**Issue by AlwaysOnline** [clash-verge-rev/clash-verge-rev#2011]
### 问题描述 / Describe the bug

如图，V2.0 RC6  WebDAV备份报错403

![image](https://github.com/user-attachments/assets/acbee49c-bda0-47f6-b14b-e36985c98952)

### 软件版本 / Verge Version

V2.0 RC6

### 复现步骤 / To Reproduce

备份报错

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

24H2

### 日志 / Log

如图

**Comment by wonfen** [comment]
这个是你的webdav服务器报错403了。非verge问题。
