### ISSUE TITLE
[BUG] Mac下 2.0.0-rc.6版本，系统服务常驻内存永不退出

### ISSUE THREAD

**Issue by jaywhj** [clash-verge-rev/clash-verge-rev#2012]
### 问题描述 / Describe the bug

今天下载2.0.0-rc.6 版本，配合测试哈。

之前Mac用户打开clashverge直接崩溃，远程修复后，我总结了一下有可能引起这个问题的源头，发现可能就是这个服务io.github.clashverge.helper 设计得有些不合理造成的：

1. 这个服务 io.github.clashverge.helper 永远不会退出，即使我把clashverge退出了服务也不会停，这就可能会引起部分用户的特别关注，然后强制关闭或无意中禁用，禁用后就会出现之前系列Mac下崩溃的问题，而且卸载重装都打不开。
2. 这个服务是clashverge运行需要的，能理解，但是应该设计成随软件的开关而开关，我看了一下其他同类软件，比如clashX也有这个服务，但是我退出clashX后服务也退出了。 <img width="672" alt="iShot_2024-11-14_07 44 05" src="https://github.com/user-attachments/assets/3dd3f742-03e5-439b-a2bd-7fcb8c80b758">
3. 我在活动监视器中强制杀掉verge服务，也关不掉，应该是设计了自动启动，最后没办法我就用专业卸载软件比如 `App Cleaner & Uninstaller` 把启动服务给关了，然后再测试，就发现跟之前崩溃的原因一模一样，不知道其他崩溃的Mac用户是否也是这个逻辑。我看他们提交的issue，大部分也是服务给禁用了。<img width="798" alt="iShot_2024-11-14_08 25 36" src="https://github.com/user-attachments/assets/75c15d15-c5cf-401e-a526-1e9337ed3c5d">

4. 那就得思考为什么用户会禁用(肯定不是故意)，解问题解源头，把这个修复了应该就没有系列的问题了。当然不修复也不会影响使用，看时间吧，来得及的话发布新版之前给修复了，来不及的话，放到下版本也可以，verge是可以正常使用的。

最后，开发者们，辛苦了，我就有空配合测试，有需要随时沟通，加油。

### 软件版本 / Verge Version

2.0.0-rc.6

### 复现步骤 / To Reproduce

查看活动监视器

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

12.2.1，Apple芯片

### 日志 / Log

不需要

**Comment by wtry** [comment]
#1900  的问题终于解决了，我的就是这个服务被禁用了，每次都要手动开一个终端执行 clash-verge-service 服务，现在增加了set_dns.sh 和 unset_dns.sh 也感觉很怪

**Comment by wonfen** [comment]
因为verge有tun模式，所以需要安装服务常驻。

**Comment by jaywhj** [comment]
> 因为verge有tun模式，所以需要安装服务常驻。你之前对比的clashx没有tun模式，所以不需要服务。

好的，理解。但是我退出verge程序了，还需要安装服务常驻吗？我开verge的时候再开服务呗，我退出的时候，服务逻辑上应该没必要了。
