### ISSUE TITLE
[BUG] 2.0版本的默认测速是不是不太准，怎么什么都显示很低的ping

### ISSUE THREAD

**Issue by flylj999** [clash-verge-rev/clash-verge-rev#2014]
### 问题描述 / Describe the bug

一些节点测出来时绿色，但是速度很差

### 软件版本 / Verge Version

2.0

### 复现步骤 / To Reproduce

默认测速

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

1

**Comment by wonfen** [comment]
clash设置里关闭“统一延迟”
