### ISSUE TITLE
[Feature] 可以上架到Microsoft store吗

### ISSUE THREAD

**Issue by pei92** [clash-verge-rev/clash-verge-rev#2015]
### 功能描述 / Feature description

上架到Microsoft store

### 使用场景 / Use case

在Xbox上访问Microsoft Store下载软件并使用

**Comment by wonfen** [comment]
你是说xbox安装verge ?

**Comment by pei92** [comment]
是的，是不是实现不了？

**Comment by pei92** [comment]
> 你是说xbox安装verge ?

是的，是不是实现不了？
