### ISSUE TITLE
[Feature] 建议将'系统代理'开关放置到'代理'标签页中

### ISSUE THREAD

**Issue by nuitlejour** [clash-verge-rev/clash-verge-rev#2016]
### 功能描述 / Feature description

建议将'系统代理'开关放置到'代理'标签页中
目前的'系统代理'开关在'设置'标签页中, 切换不是很方便, 可以考虑将'系统代理'开关放置在第一页'代理'标签中, 方便切换代理模式. 

### 使用场景 / Use case

切换是否代理时.

**Comment by wonfen** [comment]
以后将改进到dashboard
