### ISSUE TITLE
[Feature] 自动平衡价格流量方案

### ISSUE THREAD

**Issue by Davidasx** [clash-verge-rev/clash-verge-rev#2018]
### 功能描述 / Feature description

请求功能：导入订阅后，用户可以输入该订阅的计费方案，例如流量和价格，随后，客户端自动生成方案，用户可以选择“最佳速度”，“最低价格”和“均衡”模式。

### 使用场景 / Use case

用户有多个订阅，订阅的价格和质量不同，需要平衡时

**Comment by wonfen** [comment]
非核心功能，暂无计划。
