### ISSUE TITLE
[BUG] 经常出现dns resolve failed错误

### ISSUE THREAD

**Issue by parheliamm** [clash-verge-rev/clash-verge-rev#202]
### Describe the bug

```
[TCP] dial 🎯 直连 (match DomainKeyword/baidupcs) 127.0.0.1:56024(BaiduPCS-Go, uid=1000) --> bddx-ct01.baidupcs.com:443 error: dns resolve failed: lookup bddx-ct01.baidupcs.com on 192.168.31.1:53: no such host
```

### To Reproduce

设置打开系统代理，局域网连接
50%以上概率无论连接什么网站都有可能出现上错误，导致连接失败。
一般要re-try多次

### Platform

Linux

### System Version

Debian12

### Software Version

1.4.5

**Comment by wonfen** [comment]
这个和你的clash配置文件有关，dns的处理都是由clash meta core完成的。GUI没有参与处理。

**Comment by parheliamm** [comment]
> 这个和你的clash配置文件有关，dns的处理都是由clash meta core完成的。GUI没有参与处理。

Clash的配置文件，在clashy上使用是正常的。
且为了解决问题，增加了如下规则：
```
  - DOMAIN-KEYWORD,baidupcs,🎯 直连,no-resolve
  - DOMAIN-KEYWORD,baidu,🎯 直连,no-resolve
```
没有效果

**Comment by wonfen** [comment]
clashy用的是什么内核？

**Comment by wonfen** [comment]
无进一步反馈，关闭。
