### ISSUE TITLE
[BUG] win11 更新，然后回退更新，打开ClashVerge闪退

### ISSUE THREAD

**Issue by liuwanshunxi** [clash-verge-rev/clash-verge-rev#2020]
### 问题描述 / Describe the bug

win 11 更新23H ，没有打开过ClashVerge ，回退更新
打开ClashVerge 应用栏闪一下图标，应用没有打开，图标消失

### 软件版本 / Verge Version

1.4.10

### 复现步骤 / To Reproduce

双击ClashVerge

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windown 11

### 日志 / Log

![屏幕截图 2024-11-15 011020](https://github.com/user-attachments/assets/2e0f1244-74b1-4488-aee3-403fbc4412f7)
[Report.zip](https://github.com/user-attachments/files/17753836/Report.zip)

**Comment by Tychristine** [comment]
不接受历史版本反馈，更新到当前最新 2.0.0-rc.6
