### ISSUE TITLE
[BUG] rc5不能在应用内检查更新

### ISSUE THREAD

**Issue by t66369950** [clash-verge-rev/clash-verge-rev#2022]
### 问题描述 / Describe the bug

rc5检查更新要么出错，要么显示最新，只能手动去官网更新

### 软件版本 / Verge Version

v2.0.0 rc5

### 复现步骤 / To Reproduce

点击检查更新

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 LTSC 2021

### 日志 / Log

无

**Comment by Tychristine** [comment]
2.0.0-rc.5已是Pre-Release频道，去检查Release频道的1.7版本，显示版本最新必然是预期情况。更新出错是因为连接github失败无法获取到版本号。

**Comment by yixiuge301** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1933#issuecomment-2439676858
