### ISSUE TITLE
[Feature] 推荐添加一键更新快捷方式；推荐优化检查更新反馈

### ISSUE THREAD

**Issue by t66369950** [clash-verge-rev/clash-verge-rev#2023]
### 功能描述 / Feature description

能否在首页添加快捷方式方便一同更新geodata，mihomo内核，软件本体；
检查时自动通过代理检查避免出错，检查到新版本提示更新，否则显示“已是最新版本”

### 使用场景 / Use case

日常使用

**Comment by wonfen** [comment]
非常用功能，不准备实现。
