### ISSUE TITLE
[BUG] 显示配置成功，但实际上配置失败

### ISSUE THREAD

**Issue by Accademia** [clash-verge-rev/clash-verge-rev#2024]
### 问题描述 / Describe the bug

使用Clash Verga Rec时，经常能碰到因为Yaml书写错误，导致配置未成功。而Clash Verga Rec并不会弹窗说明哪里书写错误，从而极大增加写Yaml的Debug难度。

### 软件版本 / Verge Version

最新版

### 复现步骤 / To Reproduce

比如：

    - name: 🇺🇸.美国
      type: url-test
      tolerance: 10 
      url: http://cp.cloudflare.com/generate_204 
      proxies:
       - 🇺🇸.VPS—[美国]
        - 🇺🇸.Prx—[美国]

上述代码，在Clash Verga Rec中，会显示配置成功。但是，实际上       - 🇺🇸.VPS—[美国]，少了一个空格，所以在配置成功后，Clash识别不到任何配置，界面显示是空的。不仅仅是缩进，有的时候 制表符也会导致lash Verga Rec显示配置成功，但实际上是配置失败（即，Clash识别不到任何配置，界面显示是空的），并且也没有任何弹窗提示。

对比竞品，在Clash for windows中，上述有问题的yaml，就会弹窗提示，第几行第几个字符识别出错，也不会显示配置成功。

所以，希望Clash能够实现更严格的语法检查和弹窗提示。以避免此类问题。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15

### 日志 / Log

无需日志

**Comment by wonfen** [comment]
那么明显的红色波浪线提示看不到？

<img width="519" alt="image" src="https://github.com/user-attachments/assets/281ca0ae-74db-4828-a344-40e2bac564b9">

**Comment by Tychristine** [comment]
CVR本身有语法检查的，编辑完配置够后，在Profile页面右键编辑你的配置。红色波浪线会指出你的语法错误。如果你是Visual Studio Vode等编辑器，安装“yaml”扩展也能获得外部语法检查支持。
