### ISSUE TITLE
[BUG] Windows 2.0.0 rc.6 开启启动异常

### ISSUE THREAD

**Issue by Lion176** [clash-verge-rev/clash-verge-rev#2025]
### 问题描述 / Describe the bug

Windows 2.0.0 rc.6 开启启动异常，Clash Verge服务在运行，但是任务栏图标消失，需要手动启动程序，才会出现。

### 软件版本 / Verge Version

Windows 2.0.0 rc.6

### 复现步骤 / To Reproduce

每次开机都一样

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10

### 日志 / Log

[2024-11-16-1008.log](https://github.com/user-attachments/files/17783031/2024-11-16-1008.log)

**Comment by wonfen** [comment]
日志上看不出异常；尝试重新安装。大概率系统问题。

**Comment by Lion176** [comment]
我重装以后没有这个问题了，感谢回复
