### ISSUE TITLE
[BUG] WebDav备份功能异常

### ISSUE THREAD

**Issue by baimengshi** [clash-verge-rev/clash-verge-rev#2027]
### 问题描述 / Describe the bug

通过WebDAV备份成功后，软件显示暂无备份，实际上已经备份。

### 软件版本 / Verge Version

2.0.0-rc.6

### 复现步骤 / To Reproduce

![2024-11-16 12-22-11](https://github.com/user-attachments/assets/14b422b6-848e-4b95-b396-e5563b7f8e0f)

![2024-11-16 12-24-8](https://github.com/user-attachments/assets/60cdbfe9-eab5-4393-8dca-94f87d0ca2b2)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 21H2

### 日志 / Log

无

**Comment by wonfen** [comment]
点刷新看看是否有？

**Comment by sooflowercool** [comment]
> 点刷新看看是否有？

既然来提issue就不会犯这种低级错误，要不然就是在浪费你们的时间，辛苦修复一下

**Comment by wonfen** [comment]
你这个webdav的网盘如何注册测试？我们使用坚果云和NAS的webdav都没有问题。

**Comment by baimengshi** [comment]
> 你这个webdav的网盘如何注册测试？我们使用坚果云和NAS的webdav都没有问题。

【7Z5FF】Enter this referral code when signing up to get 5GB of FREE InfiniCLOUD storage! https://infini-cloud.net/en/

**Comment by ENiENG** [comment]
实测Yandex的webdav正常。
