### ISSUE TITLE
[BUG] TUN模式导致断网

### ISSUE THREAD

**Issue by fantasy467** [clash-verge-rev/clash-verge-rev#2028]
### 问题描述 / Describe the bug

每次重启系统都需要开关一次网络共享才能解决断网问题，看到很久之前就有人反馈过这个问题了，至今依然没有解决

### 软件版本 / Verge Version

v2.0.0-rc.6

### 复现步骤 / To Reproduce

开启tun模式

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

2024-11-16 20:24:24 INFO - try to run core in service mode
2024-11-16 20:24:24 INFO - start service: {"log_file": "C:\\Users\\sundr\\AppData\\Roaming\\io.github.clash-verge-rev.clash-verge-rev\\logs\\service\\2024-11-16-2024.log", "config_dir": "C:\\Users\\sundr\\AppData\\Roaming\\io.github.clash-verge-rev.clash-verge-rev", "bin_path": "C:\\Program Files\\Clash Verge\\verge-mihomo.exe", "core_type": "verge-mihomo", "config_file": "C:\\Users\\sundr\\AppData\\Roaming\\io.github.clash-verge-rev.clash-verge-rev\\clash-verge.yaml"}

**Comment by wonfen** [comment]
日志上看不出问题，其他也没有这个问题，tun模式由内核处理。
盲猜大概率是系统问题或者路由表的问题。建议先排查系统路由表，虚拟网卡。重装系统等等方式排查问题。

**Comment by Calvaire** [comment]
同样也有这个问题

**Comment by KKFantasy** [comment]
我也遇到了这个问题，开关热点可以恢复，重启电脑后又会再次断网

**Comment by Keldos-Li** [comment]
同样有此问题，只要之前**某次**在Windows中同时启用网络热点共享和Clash的Tun模式后，之后重启后打开Clash（包括其他接管虚拟网口的代理软件）不管是否开启网络共享都会导致Tun模式无法上网，只能在该次重启后重新开关网络共享。

参见之前的issue是：
- https://github.com/clash-verge-rev/clash-verge-rev/issues/244

一个workaround是参照 @MJRT 的这个定时计划任务解决：
https://github.com/clash-verge-rev/clash-verge-rev/issues/244#issuecomment-1966020837

**Comment by faithererer** [comment]
> 同样有这个问题 编辑：已修复，之前只能用gvisor而无法使用system，发现是防火墙的问题，允许应用通过防火墙后能够使用 参考：[MatsuriDayo/NekoBoxForAndroid#122 (comment)](https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/122#issuecomment-1929460403)

仍然无法解决

**Comment by MJRT** [comment]
> 同样有此问题，只要之前**某次**在 Windows 中同时启用网络热点共享和 Clash 的 Tun 模式后，之后重启后打开 Clash（包括其他接管虚拟网口的代理软件）不管是否开启网络共享都会导致 Tun 模式无法上网，只能在该次重启后重新开关网络共享。
> 
> 参见之前的 issue 是：
> 
> * [[BUG] Tun 模式启动后无法连接外网，在适配器里勾选再取消网络共享后恢复正常。 #244](https://github.com/clash-verge-rev/clash-verge-rev/issues/244)
> 
> 一个 workaround 是参照 @MJRT 的这个定时计划任务解决： [#244 (comment)](https://github.com/clash-verge-rev/clash-verge-rev/issues/244#issuecomment-1966020837)

更新下我目前的方法吧, 备份好自己的数据, 然后完全卸载clash和全部的个人数据, 清理所有系统垃圾, 重启后安装1.6.2版本,

在我的电脑上一切正常, 不需要任何额外的操作或者脚本

**Comment by wols-cs** [comment]
一样的问题

**Comment by wonfen** [comment]
已经定位问题，等下个版本尝试。还有问题的重发issue

**Comment by ZhengZhaoxi** [comment]
一样的问题，你解决了吗

**Comment by freeok** [comment]
> 一样的问题，你解决了吗

[mihomo-party](https://github.com/mihomo-party-org/mihomo-party) 完美解决

**Comment by faithererer** [comment]
> > 一样的问题，你解决了吗
> 
> [mihomo-party](https://github.com/mihomo-party-org/mihomo-party) 完美解决

请问mihomo-party这个项目和当前项目是一个类型是吧，我需要放弃卸载当前项目是吧

**Comment by seamus-42** [comment]
同样的问题，重启TCP/IP服务解决了，无法理解

**Comment by GIT-LINCC** [comment]
[clash-tun-断网修复简记-2026-04-01.md](https://github.com/user-attachments/files/26388828/clash-tun-.-2026-04-01.md)
为了彻底解决这个毛病，而不是做一个开机脚本去开关一次网络共享，用codex排查了好久，我本人不是很懂这块，让codex总结了一下在这个文件

在下面这轮对话他给我改动了这些，完美的解决了，可以当做重点参考
这次我需要你重启一次，不是泛泛地“试试看”，而是因为我已经动到了 Windows 网络栈里的注册表对象：

清掉了 6 个确认是孤儿的网络连接项和它们对应的 NetBT 键
把 Netman 改成了 Automatic
当前连接列表已经比之前干净很多，只剩真实接口、Mihomo 和系统自带的几类连接

**Comment by Pythonpa** [comment]
> [clash-tun-断网修复简记-2026-04-01.md](https://github.com/user-attachments/files/26388828/clash-tun-.-2026-04-01.md) 为了彻底解决这个毛病，而不是做一个开机脚本去开关一次网络共享，用codex排查了好久，我本人不是很懂这块，让codex总结了一下在这个文件
> 
> 在下面这轮对话他给我改动了这些，完美的解决了，可以当做重点参考 这次我需要你重启一次，不是泛泛地“试试看”，而是因为我已经动到了 Windows 网络栈里的注册表对象：
> 
> 清掉了 6 个确认是孤儿的网络连接项和它们对应的 NetBT 键 把 Netman 改成了 Automatic 当前连接列表已经比之前干净很多，只剩真实接口、Mihomo 和系统自带的几类连接

你的方法是对的，有可能是因为之前多次安装卸载clash的时候，系统内存在多个旧的 Wintun 孤儿连接（比如本地连接 2/3/4/5），这些是之前卸载残留的幽灵设备，另外，即使没有 Meta Tunnel，但多个 Wintun Userspace Tunnel #N 同样会造成冲突

**Comment by shikkoku** [comment]
> [clash-tun-断网修复简记-2026-04-01.md](https://github.com/user-attachments/files/26388828/clash-tun-.-2026-04-01.md) 为了彻底解决这个毛病，而不是做一个开机脚本去开关一次网络共享，用codex排查了好久，我本人不是很懂这块，让codex总结了一下在这个文件
> 
> 在下面这轮对话他给我改动了这些，完美的解决了，可以当做重点参考 这次我需要你重启一次，不是泛泛地“试试看”，而是因为我已经动到了 Windows 网络栈里的注册表对象：
> 
> 清掉了 6 个确认是孤儿的网络连接项和它们对应的 NetBT 键 把 Netman 改成了 Automatic 当前连接列表已经比之前干净很多，只剩真实接口、Mihomo 和系统自带的几类连接

那堆本地连接* 12不一定是幽灵网络，好像是系统自带的Microsoft Wi-Fi Direct Virtual Adapter、WAN Miniport (IP)那些

**Comment by Pythonpa** [comment]
> > [clash-tun-断网修复简记-2026-04-01.md](https://github.com/user-attachments/files/26388828/clash-tun-.-2026-04-01.md) 为了彻底解决这个毛病，而不是做一个开机脚本去开关一次网络共享，用codex排查了好久，我本人不是很懂这块，让codex总结了一下在这个文件
> > 在下面这轮对话他给我改动了这些，完美的解决了，可以当做重点参考 这次我需要你重启一次，不是泛泛地“试试看”，而是因为我已经动到了 Windows 网络栈里的注册表对象：
> > 清掉了 6 个确认是孤儿的网络连接项和它们对应的 NetBT 键 把 Netman 改成了 Automatic 当前连接列表已经比之前干净很多，只剩真实接口、Mihomo 和系统自带的几类连接
> 
> 那堆本地连接* 12不一定是幽灵网络，好像是系统自带的Microsoft Wi-Fi Direct Virtual Adapter、WAN Miniport (IP)那些

嗯，不同人遇到的问题不同，比如已知OPPO connect那个软件会自己生成一个vgate0这样类似名称的虚拟网卡，然后会干扰clash自动寻找合适的转发网卡，导致开启Tun模式就断网
