### ISSUE TITLE
[BUG] 软件被卡巴斯基识别为病毒

### ISSUE THREAD

**Issue by cgldimo** [clash-verge-rev/clash-verge-rev#2029]
### 问题描述 / Describe the bug

GUI启动后被卡巴斯基强行终止（实际代理正常但无法控制）
![屏幕截图 2024-11-17 102640](https://github.com/user-attachments/assets/b0a6638d-ad29-4214-9379-979220d26bb3)

### 软件版本 / Verge Version

V2.0.0.rc6

### 复现步骤 / To Reproduce

无
启动即被卡巴斯基自动拦截

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 23H2 22631.4460

### 日志 / Log

![image](https://github.com/user-attachments/assets/e6602ddc-debe-45e3-a509-1aba1dd0bfce)

**Comment by wonfen** [comment]
现在更新rc7了，建议把样本提交给卡巴斯基加白。
