### ISSUE TITLE
[Feature] 希望增加Tun Mode按钮对于DNS over HTTPS/TLS支持

### ISSUE THREAD

**Issue by SoranoRinji** [clash-verge-rev/clash-verge-rev#203]
### Is your feature request related to a problem? Please describe.

某些站点由于DNS污染导致TUN Mode无法正确访问，并且打开和关闭Tun Mode会刷新DNS配置

### Describe the solution you'd like

在tun mode开关旁增加配置图标，用来配置nameservers和fallback nameservers

### Describe alternatives you've considered

也可以增加Mixin功能缓解问题

**Comment by RJSackville** [comment]
自己新建个Merge profile不能用吗，把dns配置填进去

**Comment by DanielZWX** [comment]
clash meta 配置文件直接配呀，https://wiki.metacubex.one/example/conf/

**Comment by SoranoRinji** [comment]
> clash meta 配置文件直接配呀，https://wiki.metacubex.one/example/conf/

每次点击Tun Mode按钮或退出/启动Clash Verge的时候配置文件都会刷新

**Comment by RJSackville** [comment]
把dns配置写进一个merge profile然后启用不就行了，启用了就整合进运行配置了

**Comment by wonfen** [comment]
可以用merge profile解决。
