### ISSUE TITLE
[BUG] 开机自启失效

### ISSUE THREAD

**Issue by chenjunjie45** [clash-verge-rev/clash-verge-rev#2031]
### 问题描述 / Describe the bug

2.0版本开了开机自启没效果，rc6,rc7都一样

### 软件版本 / Verge Version

v2.0.0-rc.7

### 复现步骤 / To Reproduce

开启开机自启功能  重启电脑

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

MacOS apple M 13.7.1 (22H221) 

### 日志 / Log

软件没启动

**Comment by wonfen** [comment]
最新构建修复了，试试。如果还有问题请新开issue
