### ISSUE TITLE
[BUG] 重新打开软件，不记录上次软件窗口大小和位置

### ISSUE THREAD

**Issue by Aurora2624** [clash-verge-rev/clash-verge-rev#2032]
### 问题描述 / Describe the bug

重新打开软件，软件不会记录上次软件窗口大小和位置，会重新变为默认大小

### 软件版本 / Verge Version

v2.0.0-rc.6、v2.0.0-rc.7都有此问题，在此之前版本没有

### 复现步骤 / To Reproduce

完全关闭软件，重新打开软件

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

window11 24H2 26100.2314

### 日志 / Log

日志中无记录此问题

**Comment by Hunerk** [comment]
我在群里也提了这个问题，不见处理。

**Comment by wonfen** [comment]
分析应该是tauri窗口插件的bug，只在win下出现，mac没问题
https://github.com/tauri-apps/plugins-workspace

**Comment by yixiuge301** [comment]
上个版本没遇到，rc7 遇到了，必现。

**Comment by wangyan-life** [comment]
似乎在最新构建中已解决，但是关闭进程重启后有一个透明的框会闪烁一下，有点儿奇怪...

**Comment by Aurora2624** [comment]
> 似乎在最新构建中已解决，但是关闭进程重启后有一个透明的框会闪烁一下，有点儿奇怪...

没有解决吧，我刚又重新安装试了一下

**Comment by Aurora2624** [comment]
> 分析应该是tauri窗口插件的bug，只在win下出现，mac没问题 https://github.com/tauri-apps/plugins-workspace

好像是的，确实tauri中也有人提到

**Comment by wangyan-life** [comment]
我用的13小时前的新构建是没问题的，8分钟前又有新构建了你再试试....

**Comment by Aurora2624** [comment]
> 我用的13小时前的新构建是没问题的，8分钟前又有新构建了你再试试....

我重新下载安装了，甚至卸载了一遍，还是没用

**Comment by yixiuge301** [comment]
> > 我用的13小时前的新构建是没问题的，8分钟前又有新构建了你再试试....
> 
> 我重新下载安装了，甚至卸载了一遍，还是没用

我的也还复现。不是特别应用的问题，不影响使用，就这么着吧。

**Comment by xlc520** [comment]
刚刚发布的[v2.0.0](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v2.0.0)版本依旧无法记录上次软件窗口大小和位置

**Comment by tangwenlongNO1** [comment]
确实

**Comment by Leihousuo** [comment]
刚发现2.0.0正式版每次启动都恢复默认窗口大小，测试版没用过，1.7.7没有这个问题

**Comment by Aurora2624** [comment]
作者说了“因 Tauri 2.0 底层 bug，关闭窗口暂时修改为最小化功能”，等Tauri 2.0修复吧

**Comment by fyhdfg** [comment]
软件版本v2.0.1，系统 win11专业版   24H2   26100.2454,问题依然存在

**Comment by wonfen** [comment]
位置可以记住了，大小做了调整。
要记住大小需要等上游修复bug
