### ISSUE TITLE
[Feature] 能否添加一个轮询模式呢？

### ISSUE THREAD

**Issue by M1sIft** [clash-verge-rev/clash-verge-rev#2034]
### 功能描述 / Feature description

希望能出个类似[glider](https://github.com/nadoo/glider)这样的功能，就是轮询
功能：
轮询模式：rr

轮询模式是一种负载均衡算法，它会依次将请求分配到各个服务器上，直至所有服务器被均衡使用。该算法简单易实现，适用于服务器性能差异不大的情况。

简单来说就是IP换的特别快

### 使用场景 / Use case

爬虫

**Comment by xishang0128** [comment]
https://wiki.metacubex.one/config/proxy-groups/load-balance/#strategy
