### ISSUE TITLE
[BUG]   class verge rev 无法显示界面 

### ISSUE THREAD

**Issue by Super1Windcloud** [clash-verge-rev/clash-verge-rev#2035]
### 问题描述 / Describe the bug

# 刚刚更新了 WIndows+加入预览体验计划beta ,   结果更新失败, 一阵折腾 ,强制退出体验计划之后 , 不知道什么原因class verge 
能够正常后台运行,但是无法显示界面,  
# 我看了文档常见问题, 应该不是webview2 的问题, 因为我其他软件都能正常显示, 只有class verge 无法显示 

### 软件版本 / Verge Version

最新版本 1.7.7    

### 复现步骤 / To Reproduce

.

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

无法显示页面

**Comment by Super1Windcloud** [comment]
有没有大佬能够拯救我于水火之中

**Comment by Tychristine** [comment]
关闭 `BBR2`

**Comment by Tychristine** [comment]
不再接受历史版本反馈

**Comment by Super1Windcloud** [comment]
啊 这 ,  我可是Scoop  安装的, 竟然是历史版本 我的天

**Comment by Super1Windcloud** [comment]
你好, 我已经更新到2.0 版本 ,还是无法显示,  是不是WIndows的BUG呀 , 那个Clash nyanpasu  是 打开就崩溃 , 不知道该怎么办了, WIndows 已经是最新版本

**Comment by Tychristine** [comment]
不显示GUI吗？重装`WebView`吧

**Comment by Super1Windcloud** [comment]
好的, 我删除了注册表残余 已经重装好了WebView ,
但是很好奇tauri基于WebView , 为何electron不是基于WebView呢
