### ISSUE TITLE
[BUG] 用了新版的软件, 点击测试没有问题, curl一直443

### ISSUE THREAD

**Issue by YangYingmeng** [clash-verge-rev/clash-verge-rev#2036]
### 问题描述 / Describe the bug

![Uploading image.png…]()

### 软件版本 / Verge Version

Clash.Verge_2.0.0-rc.7_x64-setup.exe

### 复现步骤 / To Reproduce

下载软件订阅后, cmd  
curl https://www.google.com/

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 version: 22H2

### 日志 / Log

![image](https://github.com/user-attachments/assets/60f590c0-6680-47c8-bc6c-51553ad5b8b6)

**Comment by Tychristine** [comment]
@YangYingmeng 搞笑了，日志页面都没有显示google域名，你连代理都没开怎么能连接成功呢？

**Comment by YangYingmeng** [comment]
@Tychristine 请问怎么检查代理开没开了, 我用公司的笔记本同样的操作都没啥问题啊, 我看了下代理这边的配置和脚本都是一致的
 
![image](https://github.com/user-attachments/assets/4e558d8c-2b5a-4702-a57a-2c1ced3f00b2)
![image](https://github.com/user-attachments/assets/26da6fa1-7f8a-41d7-ba91-a783c2bcc36a)

**Comment by Tychristine** [comment]
@YangYingmeng 有一部分应用是不遵循系统代理的，比如Windows Terminal，CVR Settings Copy Environment Variables就是临时解决这个问题的。最简单的方式是直接使用TUN Mode

**Comment by YangYingmeng** [comment]
@Tychristine 感谢, 应用可以用了, 把公司的vpn关了才有日志 估计是走了公司的代理
