### ISSUE TITLE
[BUG] tun模式下浏览器无法打开网页

### ISSUE THREAD

**Issue by alan42521** [clash-verge-rev/clash-verge-rev#2037]
### 问题描述 / Describe the bug

有时候浏览器网页会打不开，日志显示timeout
time="2024-11-17T11:28:37.0933718+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match IPCIDR/10.0.0.0/8) 10.96.0.0:65342 --> 10.13.69.171:51167 error: connect failed: dial tcp 10.13.69.171:51167: i/o timeout"
time="2024-11-17T11:28:39.6145166+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match IPCIDR/10.0.0.0/8) 10.96.0.0:65350 --> 10.13.69.171:51167 error: connect failed: dial tcp 10.13.69.171:51167: i/o timeout"
尝试关掉tun模式再打开，或者把网络断掉再打开，或者重启内核，均无效，改成代理模式倒是正常了

### 软件版本 / Verge Version

v2.0.0-rc.6 16日10:23:54安装

### 复现步骤 / To Reproduce

未知，有时候突然就打不开网页了

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 专业版 22H2

### 日志 / Log

[2024-11-17-2142.log](https://github.com/user-attachments/files/17790699/2024-11-17-2142.log)

**Comment by wonfen** [comment]
节点问题；买个靠谱点的机场吧，比如我们推荐的。

**Comment by alan42521** [comment]
我换了个机场还是没用呀，代理可以tun不行，而且浏览器谷歌edge都不行

**Comment by wonfen** [comment]
> 我换了个机场还是没用呀，代理可以tun不行，而且浏览器谷歌edge都不行

机场配置文件写的有问题
