### ISSUE TITLE
[BUG] MacOS 11 输入密码无效，2.0版本是不支持11了吗

### ISSUE THREAD

**Issue by iwzh** [clash-verge-rev/clash-verge-rev#2038]
### 问题描述 / Describe the bug

安装成功后，第一次输入密码，卡住一会儿就没了了，一直安装不成功

### 软件版本 / Verge Version

2.0rc7

### 复现步骤 / To Reproduce

安装，然后第一次打开要求输入密码，输入后，没反应，移动到状态栏显示忙碌转圈中

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

11.7.10

### 日志 / Log

新安装打不开设置了

**Comment by wonfen** [comment]
应该是支持的，但我们没有macos11的测试环境，请联系我tg远程帮你看看 https://t.me/wonfen_bot

**Comment by wonfen** [comment]
没有联系，无反馈；关闭。
