### ISSUE TITLE
[Feature] 软路由clash上，能实现对设备某一个进程直连吗？

### ISSUE THREAD

**Issue by hung901** [clash-verge-rev/clash-verge-rev#2040]
### 功能描述 / Feature description

软路由clash上，能实现对设备某一个进程直连吗？例如，apple tv的某一个软件。

### 使用场景 / Use case

软路由clash上，能实现对设备某一个进程直连吗？例如，apple tv的某一个软件。

**Comment by Tychristine** [comment]
`Clash Verge REV` 是基于Tauri的GUI桌面程序。仅能在Windows 10/11、MacOS、Linux Desktop上运行
