### ISSUE TITLE
[BUG] v2.0.0-rc.7 界面为深色时右边和下边有一条白线条,

### ISSUE THREAD

**Issue by SilenceZzzZzzz** [clash-verge-rev/clash-verge-rev#2041]
### 问题描述 / Describe the bug

界面为深色时右边和下边有一条白线条
![1731910746076](https://github.com/user-attachments/assets/39cc62cc-b8a1-4dc5-ae40-33e4808c2cbe)

### 软件版本 / Verge Version

v2.0.0-rc.7

### 复现步骤 / To Reproduce

直接打开软件,颜色调整为深色

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10

### 日志 / Log

直接打开软件,颜色调整为深色

**Comment by wonfen** [comment]
无法复现

![image](https://github.com/user-attachments/assets/2d359f51-1157-4e60-8281-ccaa5934dcec)

**Comment by CrayonSSR** [comment]
## 我这也出现了，且能稳定复现
- 关掉再打开窗口会有白边，在右侧跟下侧
- 窗口大小不会记忆，彻底关掉程序再打开会回到首次安装完打开的大小

## 复现流程

### 系统设置：

- Win10 开深色模式
- setup安装的v2.0.0-rc.7

### 操作流程：

1. 点击右上角X，关掉界面(没有退出程序)
![image](https://github.com/user-attachments/assets/c96f9ad9-56b0-4a08-8172-e23bc11a2a05)

2. 点击托盘，小图标【打开主界面】，右侧跟下侧出现白边
![image](https://github.com/user-attachments/assets/ba0f69dc-2805-46f5-bdba-225b9dd45aa4)

3. 此时拖动右侧仅右侧白边会消失，下侧同理(图中下侧白边长度确实没匹配边框，颜色是截图软件问题变淡了)
![image](https://github.com/user-attachments/assets/7b9285ca-21d1-44dd-a258-f90fc8debeaf)

**Comment by wonfen** [comment]
无法复现

![image](https://github.com/user-attachments/assets/5285d2e4-ec8e-4311-8c51-80e45dc90d94)

**Comment by SilenceZzzZzzz** [comment]
![动画](https://github.com/user-attachments/assets/b8bb9afd-e036-471b-9b34-9b8814e6d188)
还是一样稳定复现 
和系统版本有关吗,看你界面边框是圆角 我这边都是直角的

**Comment by SilenceZzzZzzz** [comment]
> 无法复现
> 
> ![image](https://private-user-images.githubusercontent.com/96291150/388187023-5285d2e4-ec8e-4311-8c51-80e45dc90d94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjY0MzUsIm5iZiI6MTczMjE2NjEzNSwicGF0aCI6Ii85NjI5MTE1MC8zODgxODcwMjMtNTI4NWQyZTQtZWM4ZS00MzExLThjNTEtODBlNDVkYzkwZDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA1MTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZjgzOWRmNTFmOTBjMDQxN2EyMDUxM2I1ZTE2Yjc5YWQyZTNjOWJiZmZmM2I2MWQ0ZmQwZDk3ZTEzMWY3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3wTVGymGgYGedpeRD1e5Qz4F9yQsODvzYRMvfU4_Wi4)

![动画](https://github.com/user-attachments/assets/4e993a43-bbb8-494f-8ae6-8a123f177fb7)

还是一样稳定复现
和系统版本有关吗,看你界面边框是圆角 我这边都是直角的

**Comment by wonfen** [comment]
我这无法复现就修不了。我猜可能和系统版本有关，没有什么使用上的影响就忽略吧。

**Comment by Konano** [comment]
稳定复现 +1
