### ISSUE TITLE
[BUG] TUN模式下无法访问外网如google等 系统代理模式下正常使用

### ISSUE THREAD

**Issue by Edwardsakura** [clash-verge-rev/clash-verge-rev#2043]
### 问题描述 / Describe the bug

TUN模式下无法访问外网如google等 见图1234
系统代理模式下正常使用 见图5678
图1
<img width="1148" alt="image" src="https://github.com/user-attachments/assets/6bdc1e9d-4d5f-4598-88bf-3c3fba99ddd8">
图2
<img width="1290" alt="image" src="https://github.com/user-attachments/assets/ba6aa6bc-227d-4983-9c42-56a4af6cfae9">
图3
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/6f70b3fa-ff9c-44e9-ba11-1811e3c2579d">
图4
<img width="1148" alt="image" src="https://github.com/user-attachments/assets/d7932422-26ac-4d12-9048-cb352d6ef51c">
图5
<img width="1148" alt="image" src="https://github.com/user-attachments/assets/38156502-4741-47aa-a943-5cb40d87e48a">
图6
<img width="1290" alt="image" src="https://github.com/user-attachments/assets/fe01653b-8178-4470-8f86-f63d246a7894">
图7
<img width="1491" alt="image" src="https://github.com/user-attachments/assets/48d423ea-2a78-4955-aaf0-8483e6678257">
图8
<img width="1148" alt="image" src="https://github.com/user-attachments/assets/79466fbc-f9d7-48c6-90ef-31d0471d3886">

### 软件版本 / Verge Version

v2.0.0-rc.7 
下载时间 2024.11.18 19:16

### 复现步骤 / To Reproduce

连接TUN模式 访问外网如google等 
无法返回结果
连接系统代理模式
刷新搜索页面即可正常使用

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Sequoia 15.0.1

### 日志 / Log

[2024-11-18-1916.log](https://github.com/user-attachments/files/17799998/2024-11-18-1916.log)

**Comment by wonfen** [comment]
从图4来看是你本地网络到 nextdns的udp443(quic)访问不通，但不会对访问造成影响啊，联系我远程帮你看看吧
https://t.me/@wonfen_bot

**Comment by Edwardsakura** [comment]
群友帮助解决了 
修改系统DNS，修改为非LAN网段可解决 比如119.29.29.29 （我的情况）
谢谢作者回复 也谢谢群友解决@Christine

**Comment by seanZ86** [comment]
怎么修改win11系统dns呢？
