### ISSUE TITLE
[BUG] 覆写的dns配置内容异常

### ISSUE THREAD

**Issue by Ptilopsis01** [clash-verge-rev/clash-verge-rev#2044]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/ca6d2b23-80f9-42a8-a327-78a2a2fb555f)
如图，我的机场不支持ipv6，因此dns设置里ipv6响应设置为false，个人认为这一选项不应该作为覆写内容的一部分

### 软件版本 / Verge Version

2.0.0-rc7

### 复现步骤 / To Reproduce

如上所述

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26100.2448

### 日志 / Log

[2024-11-18-1853.log](https://github.com/user-attachments/files/17800160/2024-11-18-1853.log)

**Comment by Tychristine** [comment]
配置都能写错来，参考文档 [Clash Mihomo](https://wiki.metacubex.one/config/dns/)

没有 `ip-v6` 这个字段，verge不会犯这么明显的错

**Comment by Tychristine** [comment]
补充说明，`Clash Verge REV` 并不会覆写DNS设置，这项功能全部由配置文件决定

**Comment by Ptilopsis01** [comment]
那我建议你们检查下代码，因为我配置文件里压根没有dns，全是我自己手写的，我自己也没这么写

**Comment by Tychristine** [comment]
`CVR` 所覆写的内容均在 `~/io.github.clash-verge-rev.clash-verge-rev/config.yaml`

**Comment by Ptilopsis01** [comment]
可能是tun相关的覆写配置造成的？反正这个肯定不是我自己写的

**Comment by Tychristine** [comment]
@Ptilopsis01 这不就是你的订阅写的配置吗

**Comment by Ptilopsis01** [comment]
不是啊，我的订阅原始文件里没有dns配置的，我自己手写在merge里的部分就是`ipv6: false`

**Comment by Ptilopsis01** [comment]
不是，我不是不知道这个怎么写啊，我意思是这个地方代码有问题凭空多出来了这行啊
