### ISSUE TITLE
[BUG] tun模式DNS劫持失败

### ISSUE THREAD

**Issue by utopeadia** [clash-verge-rev/clash-verge-rev#2046]
### 问题描述 / Describe the bug

tun模式DNS劫持失败，系统DNS仍为DHCPDNS，连接日志中访问记录均为ip记录

### 软件版本 / Verge Version

v2.0.0-rc7

### 复现步骤 / To Reproduce

使用tun模式

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1

### 日志 / Log

time="2024-11-18T23:30:41.879603+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-18T23:30:41.885413+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-11-18T23:30:41.88543+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-11-18T23:30:41.885571+08:00" level=info msg="Finished initial GeoSite rule youtube => , records: 176"
time="2024-11-18T23:30:41.88917+08:00" level=info msg="Finished initial GeoSite rule gfw => 🧬 主要节点, records: 6120"
time="2024-11-18T23:30:41.889238+08:00" level=info msg="Finished initial GeoSite rule cn => 🚁 全球直连, records: 90605"
time="2024-11-18T23:30:41.889363+08:00" level=info msg="Finished initial GeoSite rule cn => dns.fake-ip-filter, records: 90605"
time="2024-11-18T23:30:41.889535+08:00" level=warning msg="replace fallback-filter.geosite with nameserver-policy, it will be removed in the future"
time="2024-11-18T23:30:41.889573+08:00" level=info msg="Finished initial GeoSite rule gfw => dns.fallback-filter.geosite, records: 6120"
time="2024-11-18T23:30:41.889586+08:00" level=info msg="Initial configuration complete, total time: 9ms"
time="2024-11-18T23:30:41.891424+08:00" level=info msg="Sniffer is closed"
time="2024-11-18T23:30:41.891556+08:00" level=error msg="Start TProxy server error: not supported on current platform"
time="2024-11-18T23:30:41.891578+08:00" level=warning msg="[TUN] Unsupported tunName(Mihomo) in darwin, force regenerate by ourselves."
time="2024-11-18T23:30:41.891948+08:00" level=warning msg="[TUN] default interface changed by monitor,  => en0"
time="2024-11-18T23:30:41.894376+08:00" level=info msg="[TUN] Tun adapter listening at: utun5([10.96.0.0/30],[]), mtu: 1500, auto route: true, auto redir: false, ip stack: Mixed"

**Comment by utopeadia** [comment]
手动修改DNS为10.96.0.0后可以正常劫持解析

**Comment by wonfen** [comment]
打开TUN模式的时候软件会自动修改你系统的DNS的，但为何没修改成功呢？发一下日志看看。

**Comment by utopeadia** [comment]
> 打开TUN模式的时候软件会自动修改你系统的DNS的，但为何没修改成功呢？发一下日志看看。

正常来说是这样的，但是我尝试找没找到报错的日志，app日志给了一个successful
2024-11-19 00:11:19 INFO - try to set system dns
2024-11-19 00:11:19 INFO - set system dns successfully
2024-11-19 00:11:19 INFO - try to run core in service mode
2024-11-19 00:11:19 INFO - start service: {"config_file": "/Users/howiewu/Library/Application Support/io.github.clash-verge-rev.clash-verge-rev/clash-verge.yaml", "config_dir": "/Users/howiewu/Library/Application Support/io.github.clash-verge-rev.clash-verge-rev", "log_file": "/Users/howiewu/Library/Application Support/io.github.clash-verge-rev.clash-verge-rev/logs/service/2024-11-19-0011.log", "core_type": "verge-mihomo", "bin_path": "/Applications/Clash Verge.app/Contents/MacOS/verge-mihomo"}
2024-11-19 00:11:33 INFO - try to unset system dns
2024-11-19 00:11:33 INFO - unset system dns successfully
2024-11-19 00:11:34 INFO - try to set system dns
2024-11-19 00:11:34 INFO - set system dns successfully

**Comment by wonfen** [comment]
https://www.clashverge.dev/faq/macos.html#apple-app

检查一下这里的设置。

**Comment by utopeadia** [comment]
<img width="665" alt="image" src="https://github.com/user-attachments/assets/5a3ca04b-b38d-48ed-9b6f-3e55cb272477">
检查了设置，没有找到问题，仍然无法劫持

**Comment by wonfen** [comment]
联系我tg https://t.me/wonfen_bot 帮你远程看看原因。

**Comment by utopeadia** [comment]
已经发了消息---- 回复的原邮件 ***@***.***>发送日期2024年11月19日 ***@***.***>***@***.***>***@***.***>主题Re: [clash-verge-rev/clash-verge-rev] [BUG] tun模式DNS劫持失败 (Issue #2046)联系我tg https://t.me/wonfen_bot 帮你远程看看原因。—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by wonfen** [comment]
已修复 https://github.com/clash-verge-rev/clash-verge-rev/commit/f50b9655aebd323e7a481b0571ce35dc6456053e
