### ISSUE TITLE
[BUG] Win和MacOS下休眠(睡眠)唤醒后TUIC协议无法连接

### ISSUE THREAD

**Issue by iseku** [clash-verge-rev/clash-verge-rev#2047]
### 问题描述 / Describe the bug

Windows和Macos下，系统休眠或睡眠唤醒后TUIC协议无法连接，需要重启应用或内核才能恢复，其它协议未发现异常，老版本存在，现在使用2.0.0rc5也未改善仍存在相同问题。
如果是内核原因，能否在识别到唤醒后自动重启下内核，因为唤醒后其它协议虽然正常但也要延迟十几秒才能连接。

### 软件版本 / Verge Version

2.0.0rc5

### 复现步骤 / To Reproduce

系统正常进入休眠或睡眠后唤醒，进入应用查看代理并测试连接状态

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11 23H2 ，MacOS 15.1

### 日志 / Log

[TCP] dial GitHub (match RuleSet/GitHub) 127.0.0.1:64476(clash-verge) --> www.github.com:443 error: INTERNAL_ERROR (local): write udp [::]:60415->a.b.c.d:443: sendmsg: network is unreachable

**Comment by wonfen** [comment]
这个问题还是反馈到内核那边吧。
怎么识别唤醒？
