### ISSUE TITLE
[Feature] 订阅里增加首页菜单怎么增加

### ISSUE THREAD

**Issue by longdoer** [clash-verge-rev/clash-verge-rev#2048]
### 功能描述 / Feature description

如图订阅里显示首页是 怎么实现的？
![image](https://github.com/user-attachments/assets/fe1c6e67-e4f3-4b6a-9d8f-9ae1e6a19838)

### 使用场景 / Use case

用户链接至官网

**Comment by Tychristine** [comment]
如果`Remote`订阅中 `Response Header` 中存在字段 `profile-web-page-url`，则会显示“首页”

**Comment by longdoer** [comment]
非常感谢

> 如果`Remote`订阅中 `Response Header` 中存在字段 `profile-web-page-url`，则会显示“首页”
