### ISSUE TITLE
[BUG] 点击规则/全局切换时，内核内存占用飙升

### ISSUE THREAD

**Issue by GodLeaveMe** [clash-verge-rev/clash-verge-rev#2049]
### 问题描述 / Describe the bug

在2.0-rc5之后的rc6、rc7都会出现在代理界面点击规则、全局、直连切换时内核内存飙升，有时候甚至会卡死的情况，但是在系统托盘那里切换就不会出现这样的情况，而且在rc5版本是也没有这种情况出现的，不知道是什么原因导致的

### 软件版本 / Verge Version

clash-verge-rev-rc6、clash-verge-rev-rc7

### 复现步骤 / To Reproduce

1.打开应用进入主界面点击代理
2.在代理界面点击规则、全局切换
（下面日志哪里提供rc7版本的视频，rc6录视频了但不上传了）

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 23H2 专业工作站版 

### 日志 / Log

https://github.com/user-attachments/assets/766ace8c-f4a7-4642-a839-c5fd330dd398

**Comment by 1583581232** [comment]
不知道这算不算bug，rc5版本就很正常，不会出现这种情况

**Comment by Tychristine** [comment]
不是，你这是内核的内存啊，又不是GUI程序的

**Comment by GodLeaveMe** [comment]
是内核的内存，但是在Gui界面切换会卡顿，有时候切换不过来卡死
