### ISSUE TITLE
[Feature]内核部分希望能显示选择的内核版本，正式版希望可以像选择开发版内核一样可以在线更新，

### ISSUE THREAD

**Issue by wxdjs** [clash-verge-rev/clash-verge-rev#205]
### Is your feature request related to a problem? Please describe.

可以增加显示选择内核的版本显示，
增加选择正式版内核时可以在线更新
增加更新Geodata时完成时提示更新完成

### Describe the solution you'd like

可以增加显示选择内核的版本显示，
增加选择正式版内核时可以在线更新

### Describe alternatives you've considered

可以增加显示选择内核的版本显示，
增加选择正式版内核时可以在线更新

**Comment by wonfen** [comment]
下个版本完善
