### ISSUE TITLE
[Feature] 负载均衡如何配置

### ISSUE THREAD

**Issue by githubb000** [clash-verge-rev/clash-verge-rev#2051]
### 功能描述 / Feature description

有没有像之前clash配置一样的地方配置全局的负载均衡。

### 使用场景 / Use case

就是当网络请求超时或者被ban自己自动切换下一个节点，轮询或者散列，如果有该如何配置？

**Comment by bimoe** [comment]
@githubb000 配置文件做故障转移 fallback

**Comment by Tychristine** [comment]
https://wiki.metacubex.one/config/proxy-groups/load-balance

**Comment by wlm3201** [comment]
订阅 -> 全局扩展脚本
`function main(config, profileName) {
  let mainGroup = config["proxy-groups"].find(g => g.type === "select");
  config["proxy-groups"].push({
    name: "负载均衡",
    type: "load-balance",
    proxies: [...mainGroup.proxies],
    url: "https://www.gstatic.com/generate_204",
    interval: 300,
    lazy: true,
    strategy: "round-robin",
  });
  mainGroup.proxies.unshift("负载均衡");
  return config;
}`

**Comment by wlm3201** [comment]
订阅 -> 全局扩展脚本

`
function main(config, profileName) {
  let mainGroup = config["proxy-groups"].find(g => g.type === "select");
  config["proxy-groups"].push({
    name: "负载均衡",
    type: "load-balance",
    proxies: [...mainGroup.proxies],
    url: "https://www.gstatic.com/generate_204",
    interval: 300,
    lazy: true,
    strategy: "round-robin",
  });
  mainGroup.proxies.unshift("负载均衡");
  return config;
}
`

**Comment by figw** [comment]
> 订阅 -> 全局扩展脚本
> 
> `function main(config, profileName) { config["proxy-groups"].push({ name: "负载均衡", type: "load-balance", 'include-all-proxies': true, url: "https://www.gstatic.com/generate_204", interval: 300, lazy: true, strategy: "round-robin", }); config["proxy-groups"].find(g => g.type === "select").proxies.unshift("负载均衡"); return config; }}`

正解
