### ISSUE TITLE
[BUG] Mac os 中备份的配置，在 Windows os 中无法恢复

### ISSUE THREAD

**Issue by IMZCC** [clash-verge-rev/clash-verge-rev#2052]
### 问题描述 / Describe the bug

Windows os下无法还原 mac os备份的配置
![PixPin_2024-11-20_14-07-46](https://github.com/user-attachments/assets/a4b41d10-1e88-4881-924d-b96fef844a3d)

### 软件版本 / Verge Version

v2.0.0.rc7

### 复现步骤 / To Reproduce

mac os 中备份配置，windows os中恢复配置，按钮无法选中

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

24H2 26100.2314

### 日志 / Log

自行判断应无需日志

**Comment by Tychristine** [comment]
跨操作系统平台？可能是因为数据文件在不同操作系统上使用不同的换行符吧

**Comment by IMZCC** [comment]
> 跨操作系统平台？可能是因为数据文件在不同操作系统上使用不同的换行符吧

目前是 恢复配置按钮 无法操作，还不是 恢复配置 报错的情况，不知道是不是现阶段还不支持跨平台的恢复操作？

**Comment by wonfen** [comment]
目前是这样设计的，因为mac下的配置文件和win下不同，强制覆盖的话可能带来未知bug。需要做更多测试

**Comment by IMZCC** [comment]
> 目前是这样设计的，因为mac下的配置文件和win下不同，强制覆盖的话可能带来未知bug。需要做更多测试

收到，明白了
