### ISSUE TITLE
[BUG] WebDAV还原配置时，未还原程序内的WebDAV配置

### ISSUE THREAD

**Issue by huxc573** [clash-verge-rev/clash-verge-rev#2054]
### 问题描述 / Describe the bug

WebDAV还原配置时，未还原程序内的WebDAV配置，还原后仍需重新配置。

### 软件版本 / Verge Version

v2.0.0-rc.7

### 复现步骤 / To Reproduce

1.设置-备份设置-填写WebDAV相关信息-备份
2.关闭应用
3.设置-备份设置-还原

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win10  LTSC 2021

### 日志 / Log

无日志输出

**Comment by wonfen** [comment]
目前没有想到安全的实现方法；如果配置备份到远程有安全性问题。

**Comment by Rirmach** [comment]
可否将 webdav 认证信息独立出来不同步？现在每次同步后，之前配置的 webdav 认证信息就全部丢失了
或者允许设置主密码对备份数据加密（例如 WinSCP 的实现方式）？现在因为没有实现配置自动同步和恢复，输入主密码还是比重新配置 webdav 要方便得多

**Comment by wonfen** [comment]
现在webdav地址，用户名，密码都是加密状态，每台设备的密钥都不同，你可以到 verge.yaml 中查看
```
webdav_url: bZQbFgUThAVtUyuHEMd/JQLfByAsr5Dbi8v/RY0g6jN5XHsqPXWYQ9vqg5AWtSdw99t4ypxF7szP
webdav_username: 7N44LT77X0LRpKFS/vDWSEMn70KlflNnhn5KCLYbuaXyNfudu3Becg==
webdav_password: 2tSw6M0mLMwUFCXudeMu13JnOPyeWblKNpCvRpEckn0JOPKVUBoD
```

**Comment by wonfen** [comment]
修复了 https://github.com/clash-verge-rev/clash-verge-rev/commit/2c0a5666fcc0c73c4bcfe2691502c1afcebd792a
