### ISSUE TITLE
[Feature] v2.0.0-Backup setting 是否可以多平台共用备份和恢复？

### ISSUE THREAD

**Issue by Lion176** [clash-verge-rev/clash-verge-rev#2057]
### 功能描述 / Feature description

目前使用版本：v2.0.0-rc.7
Windows备份的配置文件只能在Windows上恢复，Mac的配置文件只能Mac恢复。
如果Windows备份的配置文件，可以恢复到Mac就更好了，这样只要维护一份配置文件，多端通用，也不用借助另外的工具。

### 使用场景 / Use case

同时使用多平台的Clash Verge的时候，通过backup setting在不同平台，备份和恢复配置文件。

**Comment by Tychristine** [comment]
#2052
