### ISSUE TITLE
[BUG] MacOs 15.1.1 无法打开,更新2.0.0后会在任务栏上一直转圈，并且无法显示界面，最后软件闪退

### ISSUE THREAD

**Issue by erdong01** [clash-verge-rev/clash-verge-rev#2062]
### 问题描述 / Describe the bug

无法打开软件
更新2.0.0后会在任务栏上一直转圈，并且无法显示界面，最后软件闪退

### 软件版本 / Verge Version

clash:2.0.0
macOs:15.1.1

### 复现步骤 / To Reproduce

在访达 应用程序 右击 删除旧版clash1.7.7
安装新的clash 2.0.0
点击打开好 任务栏上一直转圈，并且无法显示界面，过半分钟后软件闪退

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log

无法打开 一直转圈圈 无法找到日志

**Comment by wonfen** [comment]
什么是转圈圈？录个视频看看。

**Comment by zdwzdw1983** [comment]
刚刚更新了2.0.0，然后也遇到了你说的这个问题。然后回退回去也是不行，所以怀疑是15.1.1的问题。最后我重启了下系统就可以正常使用。建议试试看能不能解决

**Comment by windobe-falser** [comment]
13.7.1 也出现了同样的问题，退回1.7.7版本后就恢复正常了
更新2.0.0后会在任务栏上一直转圈，并且无法显示界面，最后软件闪退
