### ISSUE TITLE
[BUG] 关闭软件再打开界面会变回初始大小

### ISSUE THREAD

**Issue by gankumangcao** [clash-verge-rev/clash-verge-rev#2066]
### 问题描述 / Describe the bug

![Snipaste_2024-11-23_15-37-22](https://github.com/user-attachments/assets/8fd3d8ba-00c8-4165-aec0-4c04e3080aea)
![Snipaste_2024-11-23_15-15-18](https://github.com/user-attachments/assets/c7ff9fc1-60c5-4efc-97f6-88a60e7de173)
我是卸载旧版清除数据后安装的2.0，2.0软件界面拖拽适合我的大小后任务栏右键退出再桌面重新打开，软件界面会变回初始大小

### 软件版本 / Verge Version

2.0

### 复现步骤 / To Reproduce

拖拽好更大的界面，任务栏右键退出软件再打开软件界面就会变回初始大小

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10专业版 1909

### 日志 / Log

[2024-11-23-1515.log](https://github.com/user-attachments/files/17878929/2024-11-23-1515.log)

**Comment by AblazeSpark** [comment]
为什么不先看看**Releases**呢？
[https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v2.0.0](url)

**Comment by gankumangcao** [comment]
> 为什么不先看看**Releases**呢？ [https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v2.0.0](url)

我的我的
