### ISSUE TITLE
[BUG] 2.0 每次新添加一个订阅，或者修改某个订阅的自动更新时间，第一个订阅就会转圈

### ISSUE THREAD

**Issue by figozhu** [clash-verge-rev/clash-verge-rev#2068]
### 问题描述 / Describe the bug

如果所示：
![issue](https://github.com/user-attachments/assets/c1083a89-a540-4b0a-a2a3-b136c56364b7)

### 软件版本 / Verge Version

2.0.0

### 复现步骤 / To Reproduce

导入一个订阅后，再导入其它订阅，或者修改其它订阅的自动更新时间

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

...

**Comment by wonfen** [comment]
正常的，因为加入了全局配置和全局脚本等功能；更新的时候会修改 clash-verge.yaml 配置文件；程序需要重载配置文件以生效。
