### ISSUE TITLE
[BUG] 2.0版本Linux20.04系统无法安装，提示缺少libwebkit2gtk-4.1-0库

### ISSUE THREAD

**Issue by suibuliunian** [clash-verge-rev/clash-verge-rev#2069]
### 问题描述 / Describe the bug

2.0版本Linux20.04系统无法安装，提示缺少libwebkit2gtk-4.1-0库

### 软件版本 / Verge Version

2.0版本

### 复现步骤 / To Reproduce

dpkg安装即可复现

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

5.15.0-125-generic

### 日志 / Log

![screenshot-20241123-171947](https://github.com/user-attachments/assets/2bc575a1-1cf9-479d-b379-558d1c626378)
![screenshot-20241123-171947](https://github.com/user-attachments/assets/958282d1-170e-4449-9323-541c3f452b23)

**Comment by wonfen** [comment]
用apt ./文件路径  安装

**Comment by WYZ0718** [comment]
解决了吗

**Comment by WYZ0718** [comment]
怎么解决的呀

**Comment by WYZ0718** [comment]
> 用apt ./文件路径 安装

![Uploading 2024-11-24 14-19-46 的屏幕截图.png…]()

**Comment by WYZ0718** [comment]
> 用apt ./文件路径 安装

![Uploading 2024-11-24 14-19-46 的屏幕截图.png…]()

**Comment by WYZ0718** [comment]
![2024-11-24 14-19-46 的屏幕截图](https://github.com/user-attachments/assets/dc146d6e-199d-4e94-be7b-11e84ee3d3f4)

**Comment by WYZ0718** [comment]
> 用apt ./文件路径 安装

![2024-11-24 14-19-46 的屏幕截图](https://github.com/user-attachments/assets/7386fbc2-af36-4f78-ad8f-0fd96e99538e)

**Comment by MicroOps-cn** [comment]
我这个看起来是libwebkit2gtk版本太低，
![image](https://github.com/user-attachments/assets/e8dc7695-8991-4781-8c75-34c83826a51b)

**Comment by WYZ0718** [comment]
嗯呐，我是4.036好像，不是4.1



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月25日 09:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [clash-verge-rev/clash-verge-rev] [BUG] 2.0版本Linux20.04系统无法安装，提示缺少libwebkit2gtk-4.1-0库 (Issue #2069) |

我这个看起来是libwebkit2gtk版本太低，
image.png (view on web)

**Comment by wonfen** [comment]
既然用了linux，就应该有一颗折腾的心，自己去找新版安装吧。

**Comment by suibuliunian** [comment]
确定是libwebkit2gtk库版本的问题，20.04的版本太低，24.04和22.04就没问题

**Comment by Rri-233** [comment]
那怎么解决啊再安装4.1的包吗？？

**Comment by jersonal** [comment]
兄弟这个问题解决了吗，我ubuntu20.04也是一样的问题，目前最高版本就libwebkit2gtk=4.0.37

**Comment by MicroOps-cn** [comment]
docker镜像ubuntu 22.04里面的libwebkit2gtk有4.0和4.1两个版本，所以可以尝试将ubuntu的apt源复制到你本地试试，**但此方法有风险，可能搞崩你的系统，请谨慎尝试**
```bash
cat /etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu/ jammy main restricted
deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted
deb http://archive.ubuntu.com/ubuntu/ jammy universe
deb http://archive.ubuntu.com/ubuntu/ jammy-updates universe
deb http://archive.ubuntu.com/ubuntu/ jammy multiverse
deb http://archive.ubuntu.com/ubuntu/ jammy-updates multiverse
deb http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted
deb http://security.ubuntu.com/ubuntu/ jammy-security universe
deb http://security.ubuntu.com/ubuntu/ jammy-security multiverse
```
![image](https://github.com/user-attachments/assets/b5ec2a6c-f8e6-45b7-8e6f-12d0164cacc7)

**Comment by Rri-233** [comment]
我也没有解决  不知道怎么处理

**Comment by Undefinedefity** [comment]
在 Ubuntu 20.04（Focal Fossa）中，官方软件仓库提供的 libwebkit2gtk 库版本为 4.0 系列，具体为 libwebkit2gtk-4.0-37。 
[启动页](https://launchpad.net/ubuntu/focal/%2Bpackage/libwebkit2gtk-4.0-37?utm_source=chatgpt.com)
目前，Ubuntu 20.04 的官方仓库中尚未提供 libwebkit2gtk-4.1-0 版本。

**Comment by Undefinedefity** [comment]
> 在 Ubuntu 20.04（Focal Fossa）中，官方软件仓库提供的 libwebkit2gtk 库版本为 4.0 系列，具体为 libwebkit2gtk-4.0-37。 [启动页](https://launchpad.net/ubuntu/focal/%2Bpackage/libwebkit2gtk-4.0-37?utm_source=chatgpt.com) 目前，Ubuntu 20.04 的官方仓库中尚未提供 libwebkit2gtk-4.1-0 版本。

很难过，20.04也不算老系统啊，这就不支持了，希望开发大佬能够调整一下支持库

**Comment by tianyindique** [comment]
我也是这个问题，我去官网下了libwebkit2gtk-4.1-0的包，强行安装后出现一大堆依赖问题，最后只能又降回1.7.7版本

**Comment by Chenhui-Guo** [comment]
20.04 还是老老实实用 1.0 版本吧，等大佬编译出能用的

**Comment by tianyindique** [comment]
> > 20.04 还是老老实实用 1.0 版本吧，等大佬编译出能用的
> 
> @Chenhui-Guo Just wanna know that which version of V1.x is available for libwebkit2gtk 4.0.37 since I have just tried 1.7.7 but seems still need 4.1 version;
> 
> Working on Ubuntu 20.04 ![Kazam_screenshot_00020](https://private-user-images.githubusercontent.com/96727833/390683962-95e04b64-6bb6-43bd-8b08-54882d423950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3Nzk4NzUsIm5iZiI6MTczMjc3OTU3NSwicGF0aCI6Ii85NjcyNzgzMy8zOTA2ODM5NjItOTVlMDRiNjQtNmJiNi00M2JkLThiMDgtNTQ4ODJkNDIzOTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA3MzkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NjQzZmRjMjkyMDE0OTJmOTIwZGM0YjczMzg1MGFhYTYzNzdmNGFkMGJhNzRkMDU5ZWFjYzUyZDJjZjRlZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ChKF1sYwHuwdRxiA1joVj3huO3mQj9XtO2zUatPabgA)

Maybe you can try installing it using the command “sudo dpkg -i”
![image](https://github.com/user-attachments/assets/4c2b61ea-c178-42a1-957a-071407d4c2a2)

**Comment by Arthurqi0825** [comment]
> > > 20.04 还是老老实实用 1.0 版本吧，等大佬编译出能用的
> > 
> > 
> > @Chenhui-Guo Just wanna know that which version of V1.x is available for libwebkit2gtk 4.0.37 since I have just tried 1.7.7 but seems still need 4.1 version;
> > Working on Ubuntu 20.04 ![Kazam_screenshot_00020](https://private-user-images.githubusercontent.com/96727833/390683962-95e04b64-6bb6-43bd-8b08-54882d423950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3Nzk4NzUsIm5iZiI6MTczMjc3OTU3NSwicGF0aCI6Ii85NjcyNzgzMy8zOTA2ODM5NjItOTVlMDRiNjQtNmJiNi00M2JkLThiMDgtNTQ4ODJkNDIzOTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA3MzkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NjQzZmRjMjkyMDE0OTJmOTIwZGM0YjczMzg1MGFhYTYzNzdmNGFkMGJhNzRkMDU5ZWFjYzUyZDJjZjRlZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ChKF1sYwHuwdRxiA1joVj3huO3mQj9XtO2zUatPabgA)
> 
> Maybe you can try installing it using the command “sudo dpkg -i” ![image](https://private-user-images.githubusercontent.com/182471529/390687624-4c2b61ea-c178-42a1-957a-071407d4c2a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODAyMTIsIm5iZiI6MTczMjc3OTkxMiwicGF0aCI6Ii8xODI0NzE1MjkvMzkwNjg3NjI0LTRjMmI2MWVhLWMxNzgtNDJhMS05NTdhLTA3MTQwN2Q0YzJhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwNzQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2M4YzE1OWY2YTQ1MWEzNGZjY2MyYzc2YzYwYTExM2EzMGRiYzI1MTFkNzQ4N2VjZTZmZmRlMzljOWVlNmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JuFRg2eDaS5c7JayY2nPT_zrsboovFhUpM3OOLyZ25U)

Thank you for your help 
Here I still have a problem on `dpkg -i` for v1.7.7
And also have problem when install libayatana
![Kazam_screenshot_00021](https://github.com/user-attachments/asset
![Kazam_screenshot_00022](https://github.com/user-attachments/assets/810b7083-1a55-44ba-97ac-1641bae24f5a)
s/6cbcad9d-8d85-4086-a1d2-782bf08cef5f)

**Comment by Undefinedefity** [comment]
@Arthurqi0825 v1.7.7  needs only libwebkit2gtk 4.0.37, but you did not install libwebkit2gkt 4.0.37 based on your prompt picture.
