### ISSUE TITLE
[BUG] 日志界面无显示内容

### ISSUE THREAD

**Issue by Ptilopsis01** [clash-verge-rev/clash-verge-rev#2070]
### 问题描述 / Describe the bug

如题
![image](https://github.com/user-attachments/assets/32b211cc-f6e8-46b8-a93e-5f50771ac121)
![image](https://github.com/user-attachments/assets/7eb2fde1-0190-44fb-8304-dadce0933c53)

### 软件版本 / Verge Version

2.0.0

### 复现步骤 / To Reproduce

正常运行软件，打开日志界面

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26100.2454

### 日志 / Log

[2024-11-23-1732.log](https://github.com/user-attachments/files/17879204/2024-11-23-1732.log)

**Comment by freeNestor** [comment]
mac版本也同样现象，mac m3/macos 15

**Comment by wonfen** [comment]
现在日志的收集逻辑是从选择日志登记开始，收集新的。

检查这里的设置和配置文件中的，从日志来看是密码错了：

<img width="778" alt="image" src="https://github.com/user-attachments/assets/7769a152-4a7e-4cd4-bb86-d25a55c82417">

**Comment by Ptilopsis01** [comment]
这密码是我自己设的啊，而且这个内部日志界面也没有能输密码的地方吧

**Comment by THR-hub** [comment]
> 这密码是我自己设的啊，而且这个内部日志界面也没有能输密码的地方吧

发现原因了，密码里有特殊字符，你这里的%导致bug触发，换个纯数字字母的就行了

**Comment by Ptilopsis01** [comment]
可是我密码里没有%啊，顶多有个+号

**Comment by thomas-rhong** [comment]
> 可是我密码里没有%啊，顶多有个+号 不过符号删掉确实正常了

你的密码是~~已删除~~吧，软件有bug，第一次把+转成%2B变成了~~已删除~~，第二次把%转成了%25变成了~~已删除~~，结果跟原本的对不上了。
@wonfen 暂时没电脑没做验证，猜测是这样的，麻烦修复一下。

**Comment by Ptilopsis01** [comment]
我超哥们你不要把我密码发出来啊，太哈人了😰

**Comment by wonfen** [comment]
修了 https://github.com/clash-verge-rev/clash-verge-rev/commit/5c3f0d5b601beafec1df9a4633b510a80868966e

**Comment by Ptilopsis01** [comment]
> > 可是我密码里没有%啊，顶多有个+号 不过符号删掉确实正常了
> 
> 你的密码是*****+吧，软件有bug，第一次把+转成%2B变成了*****%2B，第二次把%转成了%25变成了*****%252B，结果跟原本的对不上了。 [@wonfen](https://github.com/wonfen) 暂时没电脑没做验证，猜测是这样的，麻烦修复一下。

才发现这条消息还在，麻烦大佬把密码的部分编辑一下吧，谢谢 @thomas-rhong
