### ISSUE TITLE
[BUG] macOS 15.1.1  安装2.0稳定版后仍旧稳定闪退

### ISSUE THREAD

**Issue by swordmitri** [clash-verge-rev/clash-verge-rev#2072]
### 问题描述 / Describe the bug

安装时并未出现任何提示需要操作
安装完启动之后出现osascript想要进行更改并需要输入密码
输入密码后无任何反应
只能看见界面出现一瞬间然后消失
活动监视器的进程随即变成未响应然后消失
安装前已经删除旧的alpha版本
实际上旧的版本也稳定出现此情况
新版与之前的情况并无区别 完全无法使用
![image](https://github.com/user-attachments/assets/481d9814-fdcd-4830-aab7-57b90c28bc5e)

### 软件版本 / Verge Version

Clash Verge Rev v2.0.0

### 复现步骤 / To Reproduce

正常安装dmg文件后启动就会出现 完全无法启动成功

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log

因为无法启动 故没有日志

**Comment by freeNestor** [comment]
我是macos 15.2,  安装2.0版本没出现闪退现象，启动也没出现任何提示，启动能成功。不过我之前用的1.7.7版本，我是手动从application里面移除旧的版本，安装的2.0

**Comment by 2472598444** [comment]
系统版本：Mac OS 12.7.6
处理器：intel
软件版本：2.0
同样复现上述问题：
“安装时并未出现任何提示需要操作
安装完启动之后出现osascript想要进行更改并需要输入密码
输入密码后无任何反应
鼠标放置在系统托盘图标上显示“转圈“
随后出现一瞬间弹窗然后消失（非verge的主面板）
软件闪退系统托盘图标也消失”

重复操作复现同样的问题，清除老版本1.7后重新安装同样无法使用。

**Comment by Colin121316** [comment]
我也 Intel macOS 15.1.1也是2.0稳定闪退

**Comment by wonfen** [comment]
@freeNestor @swordmitri @Colin121316 @2472598444
试试最新的2.0.1版，已知问题都修正过了。
如果还有问题，请联系我tg: https://t.me/wonfen_bot
