### ISSUE TITLE
[BUG] 全局扩展配置中DNS部分配置在启用Tun模式时被更改 导致可能无法上网

### ISSUE THREAD

**Issue by Keldos-Li** [clash-verge-rev/clash-verge-rev#2073]
### 问题描述 / Describe the bug

在全局扩展配置里书写相关的DNS配置，DNS增强模式写为normal：
![image](https://github.com/user-attachments/assets/add00b61-5573-464a-9938-2af67afec1ef)

在使用系统代理时，配置文件会被改为redir-host，这问题不大：
![image](https://github.com/user-attachments/assets/0846ed7c-c40e-4f73-a6d7-02e210943178)

在使用tun模式时，会被强制改为fake-ip，同时启用ipv6：
![image](https://github.com/user-attachments/assets/994811ce-a508-4413-9d30-fe7ee433e2ba)

由于之前的一些问题，若使用fakeip没有清理之前的假ip，会导致浏览器大部分网址完全无法上网，此时无论是直连的还是外网都无法连上。

### 软件版本 / Verge Version

v2.0.0

### 复现步骤 / To Reproduce

开启Tun模式。详见问题描述。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

24H2 26100.2454

### 日志 / Log

-

**Comment by Kryo123456** [comment]
我这里也遇到了锁dns模式的问题，但是tun模式可以正常上网。

**Comment by Ptilopsis01** [comment]
ipv6强制开启这个我之前好像提过，我这机场还不支持v6，开了就会出问题

**Comment by Tychristine** [comment]
@Ptilopsis01 你说说什么问题，你域名没AAAA解析这个选项又不生效。

**Comment by Ptilopsis01** [comment]
> @Ptilopsis01 你说说什么问题，你域名没AAAA解析这个选项又不生效。

有些网站不知道是连到ipv6去了还是怎么回事会打不开，比如copilot.microsoft.com，看日志没看出来
虽然也不能确定一定就是这个选项的问题，但我还是觉得这个选项本来就没必要强制开启

**Comment by Tychristine** [comment]
@Ptilopsis01 这是有必要的，若使用ipv6连接可以改善延迟情况，丢包率等等。而且DNS是并发请求解析A和AAAA记录的，任意一端没有v6就不可能解析成功，自然会选择ipv4。甚至有v6的情况都不一定会选ipv6来连接

**Comment by Ptilopsis01** [comment]
> @Ptilopsis01 这是有必要的，若使用ipv6连接可以改善延迟情况，丢包率等等。而且DNS是并发请求解析A和AAAA记录的，任意一端没有v6就不可能解析成功，自然会选择ipv4。甚至有v6的情况都不一定会选ipv6来连接

意思是说只要软件里不启用ipv6就不会连到ipv6上吗？但是就上面copilot那个网址，我在系统代理或者tun开严格代理的情况下都能正常访问，tun不开严格代理就连不上

**Comment by Keldos-Li** [comment]
经过tg群里的沟通，得知这并不是bug而是有意的改写。

可能无法上网的问题可能是改写后fake ip网段冲突导致的。如果用户使用macOS，之前也可能存在DNS问题。

新的 commit ea5d6f9c46e43586df7ec97a2b12f82972f5a632 之后相关问题应该解决了。

等新版本发布后可以关闭此issue。

**Comment by Keldos-Li** [comment]
经验证 v2.0.1 我在 mac 和 windows 上开启tun模式确实已均能正常上网，现关闭该issue。
