### ISSUE TITLE
建议留下arm64版本

### ISSUE THREAD

**Issue by AisakaChan** [clash-verge-rev/clash-verge-rev#2074]
### 问题描述 / Describe the bug

建议留下arm64版本并继续支持，因为我这边没有任何问题，因为无法联系到你，所以我随便选了个分区。

### 软件版本 / Verge Version

2.0.0

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 arm64

### 日志 / Log

无

**Comment by Tychristine** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v2.0.0/Clash.Verge_2.0.0_arm64-setup.exe
Windows Arm64平台仍然在的。不知道联系方式可以去Telergram Group https://t.me/clash_verge_rev

**Comment by WindowsChan39** [comment]
> https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v2.0.0/Clash.Verge_2.0.0_arm64-setup.exe Windows Arm64平台仍然在的。不知道联系方式可以去Telergram Group https://t.me/clash_verge_rev

哦，我不小心把arm64看成便携版了对不起，原来arm64还支持着呢（（（
