### ISSUE TITLE
[BUG] 导入订阅后代理界面不显示

### ISSUE THREAD

**Issue by moyanj** [clash-verge-rev/clash-verge-rev#2075]
### 问题描述 / Describe the bug

导入一个订阅后不显示，似乎内核崩溃。重启后代理界面为空，有时出现http://127.0.0.1:9097无法访问的错误。
![image](https://github.com/user-attachments/assets/ee2c93bf-3c0c-4400-9076-44131075999e)

### 软件版本 / Verge Version

2.0.0

### 复现步骤 / To Reproduce

1. 进入订阅界面
2. 导入链接https://raw.github.site/xiaoji235/airport-free/refs/heads/main/clash/v2rayshare.txt
3. 打开代理界面（跟没导入之前一样）
4. 重启
5. 打开代理界面（空的）

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Deepin 23 DDE x11

## clash日志
莫名其妙调不了日志等级
```
time="2024-11-23T19:42:24.80878128+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-23T19:42:24.814382163+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-11-23T19:42:24.814460317+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-11-23T19:42:24.836533882+08:00" level=warning msg="MMDB invalid, remove and download"
time="2024-11-23T19:43:54.838748794+08:00" level=error msg="can't initial GeoIP: can't download MMDB: context deadline exceeded"
time="2024-11-23T19:43:54.838884953+08:00" level=fatal msg="Parse config error: rules[3387] [GEOIP,CN,π― ε¨ηη΄θΏ] error: can't download MMDB: context deadline exceeded"

```

**Comment by Tychristine** [comment]
截图上看出来内核已经崩溃了。自己查找一下内核崩溃的原因

**Comment by Frost-Mactavish** [comment]
my ubuntu22.04 has the same issue here, it seems that theres something wrong with the deb amd64 release
everything is just fine when i roll back to version 1.7.7 with kernel updated to mihomo 1.18.10

**Comment by LuceLoong** [comment]
同样问题

**Comment by Kyle91** [comment]
我也遇到了这个问题，Windows系统，开机自启之后就这样了。卸载重装都不行

**Comment by Tychristine** [comment]
@Frost-Mactavish @LuceLoong @Kyle91 Re-Install with root permission.check software directory has same permission include `~/resource`.

**Comment by Dnine7** [comment]
使用root权限安装，控制台报错ws无法连接
![image](https://github.com/user-attachments/assets/69412a2f-1a4d-4f09-ae95-236b43db1a07)

**Comment by moyanj** [comment]
已找到原因：节点名称中含有特殊字符。
更换订阅后但导入后仍然核心崩溃，原因未知，日志无任何异常。重启程序后成功。

核心日志：
![image](https://github.com/user-attachments/assets/a6b23ad0-1e62-4846-bfcd-8ec68397bd90)

**Comment by moyanj** [comment]
> 已找到原因：节点名称中含有特殊字符。 更换订阅后但导入后仍然核心崩溃，原因未知，日志无任何异常。重启程序后成功。
> 
> 核心日志： ![image](https://private-user-images.githubusercontent.com/88998238/389260728-a6b23ad0-1e62-4846-bfcd-8ec68397bd90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NDAyMDMsIm5iZiI6MTczMjQzOTkwMywicGF0aCI6Ii84ODk5ODIzOC8zODkyNjA3MjgtYTZiMjNhZDAtMWU2Mi00ODQ2LWJmY2QtOGVjNjgzOTdiZDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDA5MTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YmZhNTYzMDdjYTA5OGY5MmRiZWQ3NTU2MDBmMjc5NGUwYTJlN2U3MWM3ZTdhZDU5NDY5NDhmZThmZGU4NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wke8R9opUGBTTVTgtTLftYGqEX3bpU63DBS-4AB0ddA)

导入后不重启代理界面无变化

**Comment by Silence-Well** [comment]
如果你使用的是Mac遇到类似的问题，请完整删除软件后，再删除 Application Support/io.github.clash-verge....... 文件夹。重装就可以解决，Windows用户我觉得应该也有类似的配置文件夹位置，完整清空再装。

**Comment by GuilingQiyu** [comment]
> ubuntu24.10 使用root权限安装，控制台报错ws无法连接 ![image](https://private-user-images.githubusercontent.com/107341308/389251482-69412a2f-1a4d-4f09-ae95-236b43db1a07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDE5MTIsIm5iZiI6MTczMjU0MTYxMiwicGF0aCI6Ii8xMDczNDEzMDgvMzg5MjUxNDgyLTY5NDEyYTJmLTFhNGQtNGYwOS1hZTk1LTIzNmI0M2RiMWEwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxMzMzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmFkODA0YmU5MDcxZTVhZmUwZjRiMzgwNDdkMDI4NDZkOTMxMTIxNTdlYmVhOTFhMmU5MzlkNjAyODlhZmMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.djuRBEusXvnv336AY-U0vLDp8Is0OCJXpSNzefteaMc)

同样Ubuntu 24.10, 同样这个问题

**Comment by LuceLoong** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/2105#issuecomment-2497057686

**Comment by shuohao** [comment]
一样 Windows11，更恐怖的是 卸载重装 1.7.7也一样

**Comment by Tychristine** [comment]
@shuohao 猜你的和它们一样配置里写的geo连接不上，导致数据文件不足无法启动内核。昨天群里有位也同时符合这楼的日志情况

**Comment by YFantasyXX** [comment]
现在有解决办法吗？

**Comment by wonfen** [comment]
> 现在有解决办法吗？

打开配置目录，删除所有文件，重启verge，再导入订阅试试

<img width="783" alt="image" src="https://github.com/user-attachments/assets/de668ee6-d35c-4117-a016-4ad6dd8fc761">

**Comment by shuohao** [comment]
> > 现在有解决办法吗？
> 
> 打开配置目录，删除所有文件，重启verge，再导入订阅试试
> 
> <img alt="image" width="783" src="https://private-user-images.githubusercontent.com/96291150/390638345-de668ee6-d35c-4117-a016-4ad6dd8fc761.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3Njc5MzEsIm5iZiI6MTczMjc2NzYzMSwicGF0aCI6Ii85NjI5MTE1MC8zOTA2MzgzNDUtZGU2NjhlZTYtZDM1Yy00MTE3LWEwMTYtNGFkNmRkOGZjNzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA0MjAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZGE2ZjJkN2QwNTI5MzVmNjUyMzQwMTA5MzdjYTEyZDQ4M2ZhNDhkYjVmMDVjMTMyYTU0N2NhN2I0NGJmZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S0rSdFRpWQVuO0VX4cro8eaTL_ewnEUFapAUqyNSLcE">

试过了不行

**Comment by LuceLoong** [comment]
我试了一下，linux上，卸载重装以后，导入配置的时候不要开tun模式，可以正常导入显示，再开启tun模式就能正常使用了，如果开着tun模式导入，就会这样。

**Comment by YFantasyXX** [comment]
> > 现在有解决办法吗？
> 
> 打开配置目录，删除所有文件，重启verge，再导入订阅试试
> 
> <img width="783" alt="image" src="https://github.com/user-attachments/assets/de668ee6-d35c-4117-a016-4ad6dd8fc761">
> 

确实还是不行

**Comment by Tychristine** [comment]
Hi @Frost-Mactavish 
Directory `clash-verge-rev/resources`
```txt
clash-verge-service
install-service
uninstall-service
```
They need root permission necessarily.

**Comment by Frost-Mactavish** [comment]
> Hi @Frost-Mactavish Directory `clash-verge-rev/resources`
> 
> ```
> clash-verge-service
> install-service
> uninstall-service
> ```
> 
> They need root permission necessarily.

![image](https://github.com/user-attachments/assets/472055a5-0a89-4c36-8c44-56f4d951918c)
is this it? didnt find the `clash-verge-rev/resources` directory, but found the listed files under `/usr/bin`

**Comment by Tychristine** [comment]
@FoundTheWOUT 
Yes, this is CVR on linux platform.

**Comment by Frost-Mactavish** [comment]
> @FoundTheWOUT Yes, this is CVR on linux platform.

![image](https://github.com/user-attachments/assets/dbda9730-3386-4199-833c-9de991e90566)
fails anyway

**Comment by FoundTheWOUT** [comment]
∑( 口 ||为什么艾特了我

**Comment by GuilingQiyu** [comment]
导入旧版clash的配置数据就可以用了。
全新安装就会有这个问题

**Comment by wonfen** [comment]
!!使用出现异常的，打开设置-->配置目录 备份 后 删除所有文件 
重启软件，尝试是否正常!！

**Comment by NANYUYIBEI** [comment]
一样，现在2.2.2版本也出现了这个问题

**Comment by yexianglun111** [comment]
解决方法：卸载重新安装
具体步骤：
打开安装目录，使用uninstall.exe卸载(勾选删除数据的选项)
再使用setup.exe重新安装即可

**Comment by ZhuYiXuanNB** [comment]
设置中内核Mihomo和Mihomo Alpha切换即可
