### ISSUE TITLE
[BUG] macOS 切换托盘图标由彩色改为单色时，会变为一个白色圆饼。

### ISSUE THREAD

**Issue by Hellogz** [clash-verge-rev/clash-verge-rev#2078]
### 问题描述 / Describe the bug

切换托盘图标由彩色改为单色时，会变为一个白色圆饼。

### 软件版本 / Verge Version

v2.0.0

### 复现步骤 / To Reproduce

设置->界面设置->托盘图标
由单色图标改为彩色图标再次改为单色图标时，会变为一个白色圆饼。
<img width="620" alt="截屏2024-11-23 20 30 06" src="https://github.com/user-attachments/assets/b969a86b-31bb-4711-a828-9d25dde6eff3">

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.0.1 (24A348)

### 日志 / Log

[2024-11-23-2036.log](https://github.com/user-attachments/files/17879675/2024-11-23-2036.log)

**Comment by Hellogz** [comment]
macOS 升级到 15.1.1 也是一样的。

**Comment by MWanGxC** [comment]
我也是, 而且现在开启了代理后图标的样式也不会有变化了, 之前是有区分的

**Comment by cc-Jimmy** [comment]
我也遇到了，是卸载清理后重装就好了

**Comment by Hellogz** [comment]
无伤大雅。

**Comment by wonfen** [comment]
试试最新的alpha版本，应该修复了。还有问题重发issue
