### ISSUE TITLE
[BUG] 2.0版本在M2芯片macOS 15上崩溃闪退

### ISSUE THREAD

**Issue by brian00715** [clash-verge-rev/clash-verge-rev#2079]
### 问题描述 / Describe the bug

在安装最新2.0版本之前已经完全卸载旧版本，安装完成后打开clash提示安装osascript的密码，随后过了几秒就崩溃闪退
<img width="239" alt="osascript" src="https://github.com/user-attachments/assets/a8ee97c1-ee2f-4c5d-9640-0c60206c0af0">

### 软件版本 / Verge Version

2.0

### 复现步骤 / To Reproduce

安装2.0版clash，打开并输入osascript的密码即可复现

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.0 (24A335)

### 日志 / Log

[2024-11-23-2110.log](https://github.com/user-attachments/files/17879785/2024-11-23-2110.log)

**Comment by xiaotianxt** [comment]
问题相同

**Comment by wonfen** [comment]
已知问题，等下个版本修正。

**Comment by corgy-w** [comment]
+1

**Comment by wonfen** [comment]
@brian00715 @xiaotianxt @corgy-w
2.0.1发布了，修复了这个问题，下载试试。

如果还有问题，请新开issue

**Comment by liangchuying** [comment]
你们有过蹦到mas电脑直接重启的嘛,而且软件不能正常的使用，先打开后最小化在打开就打不开了(进程还是再执行)，需要强制退出，再打开才能操作使用
