### ISSUE TITLE
[BUG] tun模式不能访问docker的端口映射

### ISSUE THREAD

**Issue by mio-19** [clash-verge-rev/clash-verge-rev#208]
### Describe the bug

不能访问本机docker一个容器publish的端口。

### To Reproduce

1. 开一个容器，publish端口8080
2. `curl http://127.0.0.1:8080` 正常显示
3. 开tun模式
4. `curl http://127.0.0.1:8080` 空
5. 关tun模式
6. ``curl http://127.0.0.1:8080` 正常显示

### Platform

Linux

### System Version

Archlinux with linux-lts 6.1.70

### Software Version

1.4.5

**Comment by wonfen** [comment]
没想到是什么问题？请再麻烦楼主测试下是否是docker环节的网络配置问题？

**Comment by wonfen** [comment]
无反馈，关闭。
