### ISSUE TITLE
[BUG] 龙架构编译执行check.mjs失败

### ISSUE THREAD

**Issue by LinuxResearcher** [clash-verge-rev/clash-verge-rev#2080]
### 问题描述 / Describe the bug

龙架构编译提示以下报错：
```
> node scripts/check.mjs

task::verge-mihomo-alpha try 0 == proxyAgent is not a function
task::verge-mihomo try 0 == proxyAgent is not a function
task::verge-mihomo-alpha try 1 == proxyAgent is not a function
task::verge-mihomo try 1 == proxyAgent is not a function
task::verge-mihomo-alpha try 2 == proxyAgent is not a function
task::verge-mihomo try 2 == proxyAgent is not a function
task::verge-mihomo-alpha try 3 == proxyAgent is not a function
task::verge-mihomo try 3 == proxyAgent is not a function
task::verge-mihomo-alpha try 4 == proxyAgent is not a function
task::verge-mihomo try 4 == proxyAgent is not a function
file:///home/deepin/clash-verge-rev/scripts/check.mjs:88
    options.agent = proxyAgent(httpProxy);
                    ^

TypeError: proxyAgent is not a function
    at getLatestAlphaVersion (file:///home/deepin/clash-verge-rev/scripts/check.mjs:88:21)
    at Object.func (file:///home/deepin/clash-verge-rev/scripts/check.mjs:466:7)
    at runTask (file:///home/deepin/clash-verge-rev/scripts/check.mjs:524:18)

Node.js v22.11.0
 ELIFECYCLE  Command failed with exit code 1.
```
很奇怪啊，这周没有改check.mjs，但是我6天前还能正常编译当时的git版本，这周就编不过了。是我的编译环境的问题吗？

### 软件版本 / Verge Version

2.0.0

### 复现步骤 / To Reproduce

正常编译

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

deepin V23

### 日志 / Log

> node scripts/check.mjs

task::verge-mihomo-alpha try 0 == proxyAgent is not a function
task::verge-mihomo try 0 == proxyAgent is not a function
task::verge-mihomo-alpha try 1 == proxyAgent is not a function
task::verge-mihomo try 1 == proxyAgent is not a function
task::verge-mihomo-alpha try 2 == proxyAgent is not a function
task::verge-mihomo try 2 == proxyAgent is not a function
task::verge-mihomo-alpha try 3 == proxyAgent is not a function
task::verge-mihomo try 3 == proxyAgent is not a function
task::verge-mihomo-alpha try 4 == proxyAgent is not a function
task::verge-mihomo try 4 == proxyAgent is not a function
file:///home/deepin/clash-verge-rev/scripts/check.mjs:88
    options.agent = proxyAgent(httpProxy);
                    ^

TypeError: proxyAgent is not a function
    at getLatestAlphaVersion (file:///home/deepin/clash-verge-rev/scripts/check.mjs:88:21)
    at Object.func (file:///home/deepin/clash-verge-rev/scripts/check.mjs:466:7)
    at runTask (file:///home/deepin/clash-verge-rev/scripts/check.mjs:524:18)

Node.js v22.11.0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by wonfen** [comment]
proxyAgent是什么鬼？

**Comment by sudot** [comment]
替换 ```import proxyAgent from "https-proxy-agent";``` 为 ```import { HttpsProxyAgent } from "https-proxy-agent";```

替换 ```proxyAgent(httpProxy);``` 为 ```new HttpsProxyAgent(httpProxy);```

**Comment by LinuxResearcher** [comment]
> 替换 `import proxyAgent from "https-proxy-agent";` 为 `import { HttpsProxyAgent } from "https-proxy-agent";`
> 
> 替换 `proxyAgent(httpProxy);` 为 `new HttpsProxyAgent(httpProxy);`

感谢提供解决方案！我得空就试试！

**Comment by LinuxResearcher** [comment]
> import { HttpsProxyAgent } from "https-proxy-agent";

再次感谢大佬！实测您的方法是非常有效的。
