### ISSUE TITLE
[BUG] MacOS 界面修改系统代理开关无效

### ISSUE THREAD

**Issue by CoEric0** [clash-verge-rev/clash-verge-rev#2086]
### 问题描述 / Describe the bug

<img width="350" alt="image" src="https://github.com/user-attachments/assets/ce9be339-884e-4d8c-aea0-880440f83d68">
<img width="350" alt="image" src="https://github.com/user-attachments/assets/a5fc9076-f4ea-4a25-8afb-2e6124055ab4">

1. 此界面中此按钮实际无效果：系统设置中的网络代理状态（是否启用代理/代理端口号）均不会受其影响，一直保持打开并锁死7890端口状态(除非在设置中手动调整)，但是点击小齿轮进入的设置页面却能正确显示代理状态和端口。
  可以体现为：关闭clash开关，依然保持代理状态，可以访问YouTube网页，日志中能显示分流，clash齿轮设置显示“已代理+正确端口”，系统显示“代理开关打开+正确端口”

2. TUN模式开关貌似正常，curl / ping google 能符合开关变化，ifconfig中无法看到mihomo（设置的网卡名称），日志中显示为代理途径流量（应该）
<img width="639" alt="image" src="https://github.com/user-attachments/assets/b09f4e29-5dbe-4f44-9407-aadae0841806">

4. 菜单栏中图标不再具有变化效果，不知道是不是2.0版本本身更新内容；
<img width="170" alt="image" src="https://github.com/user-attachments/assets/89a4b3aa-6a54-4cb9-9f58-d8d4c090873e">

### 软件版本 / Verge Version

2.0.0

### 复现步骤 / To Reproduce

1. 1.x版本最新版本，直接升级，发现此问题；
2. 完全卸载2.0版本（包括通过软件扫描得到的各类文件）；
3. 重启电脑；
5. 安装2.0版本，问题依旧；
6. 以上所有步骤中未曾一次出现过要求输入密码，未曾出现过“此APP已损坏”提示。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log

切换系统代理开关时无任何日志产生

---

2024-11-24 00:48:17 INFO - try to unset system dns
2024-11-24 00:48:17 INFO - unset system dns successfully
2024-11-24 00:48:17 INFO - try to set system dns
2024-11-24 00:48:17 ERROR - set system dns failed: 14
2024-11-24 00:48:17 INFO - try to run core in service mode
2024-11-24 00:48:17 INFO - start service: {"log_file": "/Users/xxx/Library/Application Support/io.github.clash-verge-rev.clash-verge-rev/logs/service/2024-11-24-0048.log", "config_dir": "/Users/xxx/Library/Application Support/io.github.clash-verge-rev.clash-verge-rev", "bin_path": "/Applications/Clash Verge.app/Contents/MacOS/verge-mihomo", "config_file": "/Users/xxx/Library/Application Support/io.github.clash-verge-rev.clash-verge-rev/clash-verge.yaml", "core_type": "verge-mihomo"}
2024-11-24 00:48:22 INFO - window state restored successfully
2024-11-24 00:48:41 INFO - try to unset system dns
2024-11-24 00:48:41 INFO - unset system dns successfully
2024-11-24 00:48:44 INFO - try to unset system dns
2024-11-24 00:48:44 INFO - unset system dns successfully
2024-11-24 00:48:44 INFO - try to set system dns
2024-11-24 00:48:44 ERROR - set system dns failed: 14

---

以下日志时切换tun模式开关时产生的。
time="2024-11-24T00:53:39.183723+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-24T00:53:39.188316+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-11-24T00:53:39.1884+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-11-24T00:53:39.192158+08:00" level=info msg="Initial configuration complete, total time: 8ms"
time="2024-11-24T00:53:39.194432+08:00" level=info msg="Sniffer is closed"
time="2024-11-24T00:53:39.197738+08:00" level=info msg="Start initial Compatible provider TW"
time="2024-11-24T00:53:39.197789+08:00" level=info msg="Start initial Compatible provider default"
time="2024-11-24T00:53:39.197806+08:00" level=info msg="Start initial Compatible provider HK"
time="2024-11-24T00:53:39.197815+08:00" level=info msg="Start initial Compatible provider Proxies"
time="2024-11-24T00:53:39.197826+08:00" level=info msg="Start initial Compatible provider Google"
time="2024-11-24T00:53:39.197837+08:00" level=info msg="Start initial Compatible provider Microsoft"
time="2024-11-24T00:53:39.19785+08:00" level=info msg="Start initial Compatible provider PayPal"
time="2024-11-24T00:53:39.197864+08:00" level=info msg="Start initial Compatible provider Spotify"
time="2024-11-24T00:53:39.197873+08:00" level=info msg="Start initial Compatible provider Telegram"
time="2024-11-24T00:53:39.197888+08:00" level=info msg="Start initial Compatible provider Bahamut"
time="2024-11-24T00:53:39.197901+08:00" level=info msg="Start initial Compatible provider Final"
time="2024-11-24T00:53:39.19791+08:00" level=info msg="Start initial Compatible provider Steam"
time="2024-11-24T00:53:39.197918+08:00" level=info msg="Start initial Compatible provider Netflix"
time="2024-11-24T00:53:39.197927+08:00" level=info msg="Start initial Compatible provider US"
time="2024-11-24T00:53:39.197938+08:00" level=info msg="Start initial Compatible provider SG"
time="2024-11-24T00:53:39.197947+08:00" level=info msg="Start initial Compatible provider JP"
time="2024-11-24T00:53:39.197955+08:00" level=info msg="Start initial Compatible provider Disney"
time="2024-11-24T00:53:39.197963+08:00" level=info msg="Start initial Compatible provider Bilibili"
time="2024-11-24T00:53:39.197971+08:00" level=info msg="Start initial Compatible provider OpenAI"
time="2024-11-24T00:53:39.197982+08:00" level=info msg="Start initial Compatible provider YouTube"
time="2024-11-24T00:53:39.197992+08:00" level=info msg="Start initial Compatible provider Apple"

**Comment by wonfen** [comment]
问题1检查下是否有其他代理软件锁死了7890，verge的默认端口是7897
问题4图标问题正常，目前是这样。

**Comment by CoEric0** [comment]
> 问题1检查下是否有其他代理软件锁死了7890，verge的默认端口是7897 问题4图标问题正常，目前是这样。

1. 目前mac上只有两个代理软件，确认始终只有clash verge在运行，另一个quanx没有运行；
2. 7890端口是我之前手动调整过；
3. 会是之前卸载过的clashX之类的软件的残留控制吗？或者clash verge的系统授权方面出了问题，毕竟安装过程中没有弹出过一次密码授权提示。

**Comment by wonfen** [comment]
检查下服务顺序，把希望设置的网络服务设置到第一个
![telegram-cloud-photo-size-5-6212914264226774609-w](https://github.com/user-attachments/assets/cb029589-35fa-47a3-8523-1c4610a5388e)
