### ISSUE TITLE
[Feature] Tun 模式无法增加自定义 DNS

### ISSUE THREAD

**Issue by masquevil** [clash-verge-rev/clash-verge-rev#2087]
### 功能描述 / Feature description

Windows 希望可以在开启 Tun 模式时，可以增加自定义的 DNS

### 使用场景 / Use case

我路由器提供的 DNS 是 192.168.31.1，我在这里配置了一些 hosts，实现局域网的一些 DNS 转发。
目前在开启 Tun 模式后，DNS 列表里不包含 192.168.31.1，因此我设置的局域网转发全部失效了。希望可以自定义这部分。

**Comment by Ptilopsis01** [comment]
拓展配置里可以自己加的

**Comment by masquevil** [comment]
![image](https://github.com/user-attachments/assets/55a3a5bc-485d-481b-9393-3b4b18edab87)
加了以后好像还是没有用？
