### ISSUE TITLE
请问2.0怎么找不到便携版了？

### ISSUE THREAD

**Issue by wyjtm** [clash-verge-rev/clash-verge-rev#2089]
### 功能描述 / Feature description

请问2.0怎么找不到便携版了？

### 使用场景 / Use case

我clash verge rev都是装在移动硬盘里带着走的，安装版的配置文件带不走没法用，一直在用便携版

**Comment by EternityMar22** [comment]
你看一下公告 明明有实现声明

**Comment by lanceyliao** [comment]
溜了，转mihomo party的便携版
