### ISSUE TITLE
[Feature] archlinux 希望开机自启的时候可以不用输入密码

### ISSUE THREAD

**Issue by FlyInWind1** [clash-verge-rev/clash-verge-rev#209]
### Is your feature request related to a problem? Please describe.

无

### Describe the solution you'd like

我每次开机，都会提示我输入密码。这个有没有办法避免
![图片](https://github.com/clash-verge-rev/clash-verge-rev/assets/29172747/7c1944df-fca4-4e1a-8c13-6bf28a691c8a)

### Describe alternatives you've considered

无

**Comment by Mr-Spade** [comment]
是不是开启了TUN模式？

先用`whereis clash-meta`查看一下Meta内核的路径，例如是`/usr/bin/clash-meta`，那么就运行：

```
sudo chown root:root /usr/bin/clash-meta
sudo chmod u+s /usr/bin/clash-meta
```

**Comment by FlyInWind1** [comment]
> 是不是开启了TUN模式？
> 
> 先用`whereis clash-meta`查看一下Meta内核的路径，例如是`/usr/bin/clash-meta`，那么就运行：
> 
> ```
> sudo chown root:root /usr/bin/clash-meta
> sudo chmod u+s /usr/bin/clash-meta
> ```

确实开TUN了。我试了chmod u+s ，似乎会导致 clash-meta 无法启动，设置界面的重启内核按钮点了后，并没有成功开启代理

**Comment by ClHg2** [comment]
我是这样解决的：

```bash
#!/bin/bash
sudo chown root /usr/bin/clash-meta
sudo chmod +sx /usr/bin/clash-meta
sudo chown root /usr/bin/clash-meta-alpha
sudo chmod +sx /usr/bin/clash-meta-alpha
```

**Comment by MystiPanda** [comment]
后续会尝试在Linux下支持服务模式

**Comment by FlyInWind1** [comment]
> 我是这样解决的：
> 
> ```shell
> #!/bin/bash
> sudo chown root /usr/bin/clash-meta
> sudo chmod +sx /usr/bin/clash-meta
> sudo chown root /usr/bin/clash-meta-alpha
> sudo chmod +sx /usr/bin/clash-meta-alpha
> ```

我试了，如果 chown root 似乎会导致 clash-meta 无法启动，如果 chown 1000 ，则可以启动，但启用了 tun 模式，却没有效果，还是需要 http_proxy 环境变量才能达到代理效果

**Comment by test482** [comment]
https://aur.archlinux.org/packages/clash-meta-cap-git

**Comment by Chilly-Blaze** [comment]
> > 我是这样解决的：
> > ```shell
> > #!/bin/bash
> > sudo chown root /usr/bin/clash-meta
> > sudo chmod +sx /usr/bin/clash-meta
> > sudo chown root /usr/bin/clash-meta-alpha
> > sudo chmod +sx /usr/bin/clash-meta-alpha
> > ```
> 
> 我试了，如果 chown root 似乎会导致 clash-meta 无法启动，如果 chown 1000 ，则可以启动，但启用了 tun 模式，却没有效果，还是需要 http_proxy 环境变量才能达到代理效果

出现了同样的问题，将包从aur/clash-verge-rev-bin改为archlinuxcn或者aur的clash-verge，接着再使用 `sudo chmod +sx /usr/bin/clash-meta` 重启解决每次启动TUN都需要输密码或者meta核启动不了的问题

但是未解决HTTP流量需要走TUN的问题，仍旧需要设定 `https_proxy` 环境变量，并且即使关闭设置中的`System Proxy`其实也并未关闭系统代理（但是关闭`Tun Mode`却确实关闭了Tun，HTTP/HTTPS流量仍走系统代理）

**Comment by FlyInWind1** [comment]
> 后续会尝试在Linux下支持服务模式

clash-for-windows 的服务模式似乎是这样实现的。
修改配置文件 ~/.config/clash/config.yaml 的内容为
```yaml
external-controller: '0.0.0.0:9090'
```
然后下次clash在启动的时候就会监听 9090 端口，然后不用自己起clash，直接调用 9090 的接口就行。
我想对于 clash-verge 来说，也可以这么做

**Comment by FlyInWind1** [comment]
改配置文件我可以自己手动改，但是似乎clash-verge启动时还是要密码，我猜加个 9090 端口的判断，就可以暂时满足需求了。

**Comment by FlyInWind1** [comment]
> > 后续会尝试在Linux下支持服务模式
> 
> clash-for-windows 的服务模式似乎是这样实现的。 修改配置文件 ~/.config/clash/config.yaml 的内容为
> 
> ```yaml
> external-controller: '0.0.0.0:9090'
> ```
> 
> 然后下次clash在启动的时候就会监听 9090 端口，cfw不用自己起clash，直接调用 9090 的接口就行。 我想对于 clash-verge 来说，也可以这么做

兄弟们，我搞定了，手动修改配置文件后，clash-verge设置的外部控制改成127.0.0.1:9090 然后 setcap -r /usr/bin/clash-meta 就可以了。
我的 clash-meta来自archlinuxcn，其他的版本配置文件可能在 ~/.config/mihomo/config.yaml

**Comment by FlyInWind1** [comment]
按照这个办法启动 clash-verge 后，会有一个问题。这种方式起的 clash-meta，没有任何配置，需要手动刷新一下配置。临时的办法是，将整个 clash-meta 配置文件都写入 config.yaml  ，而不是只写 external-controller ，但这样做更新配置文件是个麻烦事。
还是希望有大佬能兼容一下。
