### ISSUE TITLE
[BUG] 托盘图标未能设置成单色

### ISSUE THREAD

**Issue by s5s5** [clash-verge-rev/clash-verge-rev#2090]
### 问题描述 / Describe the bug

问题如图：
<img width="833" alt="image" src="https://github.com/user-attachments/assets/c97ea0de-240d-469b-b6bd-7f811a18cd06">

预期：
托盘图标显示为单色

实际：
托盘图标显示为彩色

所使用彩色 PNG 图标：
![icons8-soccer-skin-type-3-96](https://github.com/user-attachments/assets/722fb51e-92cf-420d-baea-3285ecedb8b6)

### 软件版本 / Verge Version

Clash.Verge_2.0.0_aarch64.dmg

### 复现步骤 / To Reproduce

设置 ---> 界面设置 ---> 托盘图标：单色图标 ---> 常规托盘图标、系统代理托盘图标、Tun模式托盘图标：选择彩色 PNG 图标

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.7.1 (23H222)

### 日志 / Log

无

**Comment by pangtong886** [comment]
+1

**Comment by Karonolandiis** [comment]
Same problem even though I restarted the app.

**Comment by zhuyjan** [comment]
same problem for me

**Comment by wonfen** [comment]
你都换了图标，当然无法单色了。

**Comment by s5s5** [comment]
在上一个版本，换了图标之后，也可以设置成单色
新的大版本，如果没有特别说明，应该保持原状吗？

**Comment by s5s5** [comment]
> 你都换了图标，当然无法单色了。

在上一个版本，换了图标之后，也可以设置成单色
新的大版本，如果没有特别说明，应该保持原状吗？
