### ISSUE TITLE
[BUG] v2.0.1 版本在未发布情况下，在软件中显示 NEW 图标

### ISSUE THREAD

**Issue by s5s5** [clash-verge-rev/clash-verge-rev#2091]
### 问题描述 / Describe the bug

问题如图：
不能下载 v2.0.1
<img width="830" alt="image" src="https://github.com/user-attachments/assets/cfb65dbc-a45d-41da-b414-4171c5406172">

点 前往发布页，后也找不到可下载文件
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/4438a2ce-dfd2-461a-9043-95998eae1990">

### 软件版本 / Verge Version

Clash.Verge_2.0.0_aarch64.dmg

### 复现步骤 / To Reproduce

如上

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.7.1 (23H222)

### 日志 / Log

无

**Comment by ikun0014** [comment]
@s5s5 那么这是谁的锅呢（

**Comment by EternityMar22** [comment]
那么这是谁的锅呢（

**Comment by wonfen** [comment]
删了，晚点发布
