### ISSUE TITLE
[BUG] 传了一个有问题的svg导致测试无法打开

### ISSUE THREAD

**Issue by jdxia** [clash-verge-rev/clash-verge-rev#2093]
### 问题描述 / Describe the bug

测试图片
```
<svg width="100" height="100" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
    <!-- 身体 -->
    <rect x="20" y="25" width="60" height="60" rx="8" fill="#FF8C00"/>
    
    <!-- 眼睛 -->
    <circle cx="35" cy="45" r="8" fill="white"/>
    <circle cx="65" cy="45" r="8" fill="white"/>
    <circle cx="35" cy="45" r="4" fill="black"/>
    <circle cx="65" cy="45" r="4" fill="black"/>
    
    <!-- 天线 -->
    <line x1="40" y1="25" x2="35" y2="15" stroke="#FF8C00" stroke-width="4" stroke-linecap="round"/>
    <line x1="60" y1="25" x2="65" y2="15" stroke="#FF8C00" stroke-width="4" stroke-linecap="round"/>
    <circle cx="35" cy="15" r="3" fill="#FF8C00"/>
    <circle cx="65" cy="15" r="3" fill="#FF8C00"/>
    
    <!-- 嘴巴 -->
    <path d="M40 65 Q50 75 60 65" stroke="white" stroke-width="3" fill="none"/>
</svg>
```
然后测试那就打不开了
<img width="731" alt="image" src="https://github.com/user-attachments/assets/d9ab6e46-0826-453b-8529-5db1e97104da">

### 软件版本 / Verge Version

 2.0.0

### 复现步骤 / To Reproduce

准备一个测试链接, 然后用上面的svg

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log

没有关于ui的

**Comment by jdxia** [comment]
<img width="915" alt="image" src="https://github.com/user-attachments/assets/5d907be4-c58f-495d-9e26-d10ee3887133">

**Comment by wonfen** [comment]
修复了 https://github.com/clash-verge-rev/clash-verge-rev/commit/746763ed3448a3affa40ded2e76687f5fcdb87dd ，增加了注释的处理。
<img width="235" alt="image" src="https://github.com/user-attachments/assets/63dab941-c5a2-4abe-8452-af4b80b8fcc1">

之前保存的修复方法：
设置，打开 配置目录，编辑 verge.yaml，删掉这个图标的svg
