### ISSUE TITLE
[BUG] 在后台运行时, 明明系统代理关闭了, clash-verge-service.exe仍旧就在运行, Webview也占用了大量的内存. Webview这个功能是否能自主选择关闭开启?

### ISSUE THREAD

**Issue by zq007012** [clash-verge-rev/clash-verge-rev#2096]
### 问题描述 / Describe the bug

[BUG] 在后台运行时, 明明系统代理关闭了, clash-verge-service.exe仍旧就在运行, Webview也占用了大量的内存. Webview这个功能是否能自主选择关闭开启?

### 软件版本 / Verge Version

v2.0.0

### 复现步骤 / To Reproduce

关闭界面后, 任务管理器搜索clash

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

<img width="590" alt="zq007_2024-11-24_165250" src="https://github.com/user-attachments/assets/896fa48b-4545-4e32-a32a-d27ea83c62bf">

**Comment by nulllee** [comment]
[https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v2.0.0](url)
Line 3:"因 Tauri 2.0 底层 bug，关闭窗口暂时修改为最小化功能"
You can close this issue now.
