### ISSUE TITLE
[Feature] 能否支持自定义流量计算？

### ISSUE THREAD

**Issue by Davidasx** [clash-verge-rev/clash-verge-rev#2097]
### 功能描述 / Feature description

请问机场订阅导入时下面的流量是怎么做出来的？
如果自己买的服务器，请问如何实现这个功能？

### 使用场景 / Use case

自己购买服务器且服务器流量超额计费，需要根据订阅流量判断使用方式
一般的机场订阅，导入后都可以查看剩余流量，自己做的节点怎么查看呢？

**Comment by Tychristine** [comment]
官网有说明 https://www.clashverge.dev/guide/url_schemes.html
