### ISSUE TITLE
[BUG] V2.0.0 有严重BUG  1 窗口比例调整好之后 ctrl+Q 退出之后 重新打开软件窗口大小比例被重置了 之前的版本都不会这样  2 在ctrl+Q退出之后 重新打开软件 按设置好的热键（打开软件主页面）就会卡死 打不开完全无响应 必须得在任务管理器中结束进程

### ISSUE THREAD

**Issue by heygudian** [clash-verge-rev/clash-verge-rev#2098]
### 问题描述 / Describe the bug

V2.0.0 有严重BUG

1 窗口比例调整好之后 ctrl+Q 退出之后 重新打开软件窗口大小比例被重置了 之前的版本都不会这样

2 在ctrl+Q退出之后 重新打开软件 按设置好的热键（打开软件主页面）就会卡死 打不开完全无响应 必须得在任务管理器中结束进程

### 软件版本 / Verge Version

2.0

### 复现步骤 / To Reproduce

V2.0.0 有严重BUG

1 窗口比例调整好之后 ctrl+Q 退出之后 重新打开软件窗口大小比例被重置了 之前的版本都不会这样

2 在ctrl+Q退出之后 重新打开软件 按设置好的热键（打开软件主页面）就会卡死 打不开完全无响应 必须得在任务管理器中结束进程

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

V2.0.0 有严重BUG

1 窗口比例调整好之后 ctrl+Q 退出之后 重新打开软件窗口大小比例被重置了 之前的版本都不会这样

2 在ctrl+Q退出之后 重新打开软件 按设置好的热键（打开软件主页面）就会卡死 打不开完全无响应 必须得在任务管理器中结束进程

**Comment by o88369** [comment]
没看更新日志？

**Comment by DoerLorenz** [comment]
啊看完没发现有人回复啊，就关闭啦？

**Comment by Tychristine** [comment]
@DoerLorenz 发行说明里面不是都说了吗，已知的问题等待上游库修复

**Comment by heygudian** [comment]
没有阿 那个帖子不知道怎么就没了 我以为你们删了


y458406
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "clash-verge-rev/clash-verge-rev"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月24日(星期天) 晚上9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [clash-verge-rev/clash-verge-rev] [BUG] V2.0.0 有严重BUG  1 窗口比例调整好之后 ctrl+Q 退出之后 重新打开软件窗口大小比例被重置了 之前的版本都不会这样  2 在ctrl+Q退出之后 重新打开软件 按设置好的热键（打开软件主页面）就会卡死 打不开完全无响应 必须得在任务管理器中结束进程 (Issue #2098)





 
啊看完没发现有人回复啊，就关闭啦？
