### ISSUE TITLE
[Feature] 关于2.0新版建议把root权限请求后置到具体功能层面，而不是初始化的时候

### ISSUE THREAD

**Issue by oodzchen** [clash-verge-rev/clash-verge-rev#2099]
### 功能描述 / Feature description

今天更新了一下软件，重启系统后突然显示两个弹窗，一个要求`/usr/bin/install`的root权限，一个要`/usr/bin/uninstall`的root权限，一开始很疑惑，都不知道从哪儿弹出来的，以为电脑被植入了病毒，调查一番才发现原来是因为给clash-meta-rev设置了开机启动。上github看了下发布日志才知道原来是大版本发布了，不过这个初始化要求权限的操作体验不是很好，容易产生误会，建议只在开启TUN这类功能的时候再请求权限。

### 使用场景 / Use case

开机自动启动

**Comment by wonfen** [comment]
这个是安装服务模的，/usr/bin/uninstall先执行防止以前安装过老版本，先卸载；然后再执行install安装新版本。

服务是为了软件正常开启tun模式必须的。
