### ISSUE TITLE
[Feature]希望替换默认测速链接和增加测速超时设置

### ISSUE THREAD

**Issue by zhanpeng1996** [clash-verge-rev/clash-verge-rev#210]
### Is your feature request related to a problem? Please describe.

1.目前测速的链接，有些机场测速会大面积error，实际是联通状态。
2.有些线路联不通，没有超时设置导致一直在等待。

### Describe the solution you'd like

希望将默认测速链接替换为：http://www.gstatic.com/generate_204
另外增加测速超时设置，感谢大佬！

### Describe alternatives you've considered

希望将默认测速链接替换为：http://www.gstatic.com/generate_204
另外增加测速超时设置，感谢大佬！

**Comment by skymeistar** [comment]
win 11 cpu 占用是不是有些高了

zhanpengli ***@***.***> 于2024年1月4日周四 17:07写道：

**Comment by wonfen** [comment]
默认是测试链接是 http://1.1.1.1 去除了dns解析的过程，更贴近于真实的链接延迟。
如果机场无法访问1.1.1.1建议检查下机场是否对测试地址做了手脚。

另外你也可以手动在杂项设置里修改默认测试地址。
