### ISSUE TITLE
[BUG] 检查更新失败

### ISSUE THREAD

**Issue by AquaSimulacra** [clash-verge-rev/clash-verge-rev#2103]
### 问题描述 / Describe the bug

在检查clash verge rev更新时，会出现如下报错
![image](https://github.com/user-attachments/assets/e003a056-78da-4c62-ab84-f91e3f926c24)

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

/

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26100.2454

### 日志 / Log

/

**Comment by wonfen** [comment]
2.0.0的问题，修复了；下个版本就不会出现了；删除手动安装吧

**Comment by wonfen** [comment]
测试没问题啊

**Comment by AquaSimulacra** [comment]
这个bug可能只是在新发版的那一段时间出现，所以我把它关了。

**Comment by wonfen** [comment]
因为发版的时候升级文件还没有准备齐全，所以检测不到
