### ISSUE TITLE
[Feature] 2.0版能否支持下windows便携版本

### ISSUE THREAD

**Issue by Zeral-Zhang** [clash-verge-rev/clash-verge-rev#2104]
### 功能描述 / Feature description

有软件安装限制环境的 x86 内核的 windows11 电脑，能否继续支持便携版。

### 使用场景 / Use case

公司有软件安装策略，禁止安装非认证软件，2.0 版本可否继续提供便携版的支持。

**Comment by wonfen** [comment]
在另外一台电脑上安装，把主目录复制到公司电脑运行看看是否正常。

**Comment by starsunyzl** [comment]
+1，非常需要便携版且不强制安装服务的版本，现在的2.x即使把安装目录复制到另外的电脑启动时也会强制安装服务，不安装运行不了，不支持这个Feature的话只能无奈放弃此软件了

**Comment by Lucien-Harvey** [comment]
+1，有些情况下无法使用安装的版本，只能使用便携版，能支持一下吗

**Comment by SHENRUN622** [comment]
+1  我的电脑可以正常安装，但是每次运行的时候都要获取权限。公司电脑设置了获取权限需要登陆管理员账号，只能退回1.7使用了

**Comment by Tychristine** [comment]
@SHENRUN622 这是由于环境问题造成的，代理软件修改网络设置是正常的行为，修改系统设置都需要UAC，如果非UAC用户就还是另寻途径吧

**Comment by Zeral-Zhang** [comment]
要是可以安装软件的话为什么还要转换为便携版，那说到底就是2.0版本之后不支持便携版本，如果产品不是为了降低使用者的门槛，为什么要去造轮子。

**Comment by simear2004** [comment]
可以用v2rayN，占用资源非常小，速度也快
