### ISSUE TITLE
[Feature] 希望加入proxy provider时流量显示

### ISSUE THREAD

**Issue by goxq** [clash-verge-rev/clash-verge-rev#211]
### Is your feature request related to a problem? Please describe.

<img width="373" alt="TTIA" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/58415702/665c288a-aac8-451c-91e5-2996d1e2635e">
目前如果在本地config文件中采用proxy provider写法引用服务商url，无法做到流量显示，希望可以加入这个feature

### Describe the solution you'd like

加入proxy provider写法时流量显示feature

### Describe alternatives you've considered

加入proxy provider写法时流量显示feature

**Comment by wonfen** [comment]
如果有多个proxy provider的情况下，显示哪个呢？

**Comment by MystiPanda** [comment]
流量显示基于订阅链接的http header获取，你这种情况无法获取，而且多个provider如何显示也是个问题。

**Comment by goxq** [comment]
@wonfen @MystiPanda 显示这个应该不是问题，就是UI上的事情。而且是可以获取到的吧？手机上的stash就支持proxy provider的流量的显示。

**Comment by Paulgudring** [comment]
@wonfen @MystiPanda 开发者您好。使用provider的流量显示我认为不用放在`profile`一处，更宜放于`proxy column`的`provider`。在这方面，[metacubexd](https://github.com/MetaCubeX/metacubexd)外部api面板提供了例子~

**Comment by wonfen** [comment]
> @wonfen @MystiPanda 开发者您好。使用provider的流量显示我认为不用放在`profile`一处，更宜放于`proxy column`的`provider`。在这方面，[metacubexd](https://github.com/MetaCubeX/metacubexd)外部api面板提供了例子~

截个图看看cubexd是如何显示的？看看能否学习下。

**Comment by Paulgudring** [comment]
> > @wonfen @MystiPanda 开发者您好。使用provider的流量显示我认为不用放在`profile`一处，更宜放于`proxy column`的`provider`。在这方面，[metacubexd](https://github.com/MetaCubeX/metacubexd)外部api面板提供了例子~
> 
> 截个图看看cubexd是如何显示的？看看能否学习下。

去敏化处理之后：

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/81338177/a285feb5-6d9f-427b-a7c7-ea5ddb8addb3)

翻看了[meta wiki on proxy-provider api](https://wiki.metacubex.one/api/#_12)，这些内容是可以通过已有的api获取到的，期待实现啦~

**Comment by MystiPanda** [comment]
已实现
