### ISSUE TITLE
[BUG] 关于UI界面的问题

### ISSUE THREAD

**Issue by cc329928503** [clash-verge-rev/clash-verge-rev#2112]
### 问题描述 / Describe the bug

当打开软件调整好的UI界面的大小后，关闭软件，下次再打开时，UI界面又变成了默认的大小，又需要再重新调整，谢谢。

### 软件版本 / Verge Version

Clash.Verge_2.0.1_x64-setup

### 复现步骤 / To Reproduce

当打开软件调整好的UI界面的大小后，关闭软件，下次再打开时，UI界面又变成了默认的大小，又需要再重新调整，谢谢。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

WIN11

### 日志 / Log

暂无；

**Comment by Tychristine** [comment]
已知问题在发行说明里
