### ISSUE TITLE
[BUG] Windows系统下托盘图标有锯齿，暗黑模式有白边

### ISSUE THREAD

**Issue by siwuxei** [clash-verge-rev/clash-verge-rev#2114]
### 问题描述 / Describe the bug

更新到最新版本后出现了以下两个UI上的问题：
1. 托盘图标有锯齿（如图1所示）
2. 暗黑模式有白边（如图2所示）

图1：托盘图标有锯齿
![image](https://github.com/user-attachments/assets/331f55cb-e677-4783-8ec0-0085a58b58df)

图2：暗黑模式有白边
![image](https://github.com/user-attachments/assets/63dddb5e-6671-4484-aa9b-827b97246315)

### 软件版本 / Verge Version

v2.0.1

### 复现步骤 / To Reproduce

win10系统，屏幕分辨率如下：

![image](https://github.com/user-attachments/assets/26297780-7900-4bf8-b110-a9766b5b8704)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

[2024-11-25-1245.log](https://github.com/user-attachments/files/17897289/2024-11-25-1245.log)

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/2106

**Comment by oreeke** [comment]
win11 2.2.3 目前托盘图标还有锯齿。
