### ISSUE TITLE
如何彻底删除

### ISSUE THREAD

**Issue by jdxia** [clash-verge-rev/clash-verge-rev#2116]
### 问题描述 / Describe the bug

如何彻底删除在mac/windows

### 软件版本 / Verge Version

2.0.0

### 复现步骤 / To Reproduce

如何彻底删除在mac/windows

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log

无

**Comment by songyuc** [comment]
我也想知道在Ubuntu上如何进行“完全删除”；
十分感谢！

**Comment by wonfen** [comment]
> 我也想知道在Ubuntu上如何进行“完全删除”； 十分感谢！

apt remove就行。

mac下手动删除服务。
