### ISSUE TITLE
[Feature] [热键设置]中的[打开/关闭系统代理]在v2.0.1版本中已经不是全局快捷键

### ISSUE THREAD

**Issue by MoverDakkiT** [clash-verge-rev/clash-verge-rev#2117]
### 功能描述 / Feature description

开发者您好，在之前的1.x版本中，[打开/关闭系统代理]是一个全局快捷键，因此，在使用时可以根据任务栏图标颜色快速判断系统代理状态并通过快捷键快速切换是否开启系统代理。在更新之后，这个快捷键只能在主界面使用。

### 使用场景 / Use case

希望能将[打开/关闭系统代理]恢复为全局快捷键

**Comment by wonfen** [comment]
目前也是全局的，你设置的是什么快捷键？补充相关信息。

**Comment by MoverDakkiT** [comment]
> 目前也是全局的，你设置的是什么快捷键？补充相关信息。

您好，我之前的快捷键是ctrl+shift+Q，刚刚测试确实改到别的快捷键就能实现全局切换了，谢谢！
