### ISSUE TITLE
[Feature] 设置<备份设置，UI界面优化建议

### ISSUE THREAD

**Issue by sqcsl-dev** [clash-verge-rev/clash-verge-rev#2119]
### 功能描述 / Feature description

当界面小于988*852时，【备份设置】界面出现不适配的情况，字段显示不完整
![image](https://github.com/user-attachments/assets/c2009317-af02-480b-b2cf-bba1387047fb)

### 使用场景 / Use case

设置<备份设置

**Comment by wonfen** [comment]
修了 https://github.com/clash-verge-rev/clash-verge-rev/commit/564d81fd31772899b8e2ebee82d4981b7615a953
