### ISSUE TITLE
[BUG]  verge-mihomo 进程一直占用上行？？？

### ISSUE THREAD

**Issue by zhz-we** [clash-verge-rev/clash-verge-rev#2122]
### 问题描述 / Describe the bug

verge-mihomo 进程一直占用上行？？？

### 软件版本 / Verge Version

v2.0.1

### 复现步骤 / To Reproduce

启动clash verge 启动后 verge-mihomo.exe进程上行一直占用

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11

### 日志 / Log

![image](https://github.com/user-attachments/assets/95f09d8e-6ad0-473f-9f2a-9d84e7bb98d3)
![image](https://github.com/user-attachments/assets/bdf790fd-c1eb-4ffe-8239-28605beb00b0)

**Comment by wonfen** [comment]
这个内核，检查你哪个软件在上传流量。

**Comment by zhz-we** [comment]
> 这个内核，检查你哪个软件在上传流量。

请问会持续多久呢？

**Comment by wonfen** [comment]
> > 这个内核，检查你哪个软件在上传流量。
> 
> 请问会持续多久呢？

有其他软件在上传流量啊，是不是开了网盘同步什么的？
可以在连接菜单里面查看

**Comment by sdbyhxd** [comment]
![Image](https://github.com/user-attachments/assets/216d76ce-445f-4b91-a606-d4c26521c6c8)什么情况，上行12g

**Comment by FrankKKK1127** [comment]
今天我也出现这个问题了 被迈克菲阻止了链接

<img width="838" height="195" alt="Image" src="https://github.com/user-attachments/assets/b64c6fe0-ee40-4c13-990c-98164b70530c" />

**Comment by 5Breeze** [comment]
好像这个进程被windef收录了

<img width="604" height="785" alt="Image" src="https://github.com/user-attachments/assets/4fd9dedd-af65-4ac9-ac33-122a1e55811d" />

**Comment by harrylee128-code** [comment]
我今天发现这个情况了，一直在上传，可是比你更惨，我软件显示没有上传，你起码还显示了，他是在后台自己偷偷上传的
