### ISSUE TITLE
[Feature] TUN模式需要一个设置DNS及FAKEIP的开关，或在配置中有相关配置的时候不要覆写。

### ISSUE THREAD

**Issue by mikurusos** [clash-verge-rev/clash-verge-rev#2124]
### 功能描述 / Feature description

现在的情况是只要启动tun模式就修改dns到8.8.8.8，同时fakeip固定到198段，根本不管配置文件中是否有相关配置直接覆写。
这导致几个问题，一个是ip冲突的问题，一个是内部dns解析的问题。
之前rc版本的时候可能是bug可能是没覆写成功，-system是能够正常使用的。
建议给一个配置项是否复写。

### 使用场景 / Use case

有很多场景需要 dns : - system的localdns，8.8.8.8等public dns并没有相关的解析记录，会导致出现网络问题。

**Comment by wonfen** [comment]
因为mac启用fakeip模式必须修改dns为非局域网IP，设置8888是为了当内核意外退出时候的fall-back。
