### ISSUE TITLE
[BUG] 节点进行导入使用3x-ui部署的Reality协议导入会错误识别network类型

### ISSUE THREAD

**Issue by yinuan-i** [clash-verge-rev/clash-verge-rev#2126]
### 问题描述 / Describe the bug

订阅里编辑节点进行导入时使用3x-ui部署的Reality协议导入会错误识别为ws，手动改回tcp正常

### 软件版本 / Verge Version

Clash Verge Rev v2.0.1

### 复现步骤 / To Reproduce

订阅里编辑节点进行导入时使用3x-ui部署的Reality协议导入会错误识别network类型
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/a092f415-b9c3-4dcc-b796-2854f1ab1fe5">
这是节点信息，在订阅里编辑节点导入后识别为network识别为ws，测试也是error
<img width="749" alt="image" src="https://github.com/user-attachments/assets/975079d1-b8fe-4649-a3de-b96a384d3d94">
<img width="292" alt="image" src="https://github.com/user-attachments/assets/594c4c35-1594-418d-943e-2f45ca3031c3">

**手动改回tcp后正常**
<img width="218" alt="image" src="https://github.com/user-attachments/assets/08ceacc2-2d20-4e30-9c60-471eb790deb2">
<img width="291" alt="image" src="https://github.com/user-attachments/assets/4759ce8a-cf1d-42af-9ace-bb15ab116f89">

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS15.1.1

### 日志 / Log

节点导入识别问题，无日志

**Comment by wonfen** [comment]
试试 alpha : https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha
如果还有问题，请发新issue
