### ISSUE TITLE
[BUG] 如何修改延迟测试为HTTP延迟

### ISSUE THREAD

**Issue by moelinmtf** [clash-verge-rev/clash-verge-rev#2128]
### 问题描述 / Describe the bug

更新2.0.1版本之后无法将代理页面的延迟测试改为HTTP延迟

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 24H2

### 日志 / Log

无

**Comment by People-11** [comment]
在设置里关掉统一延迟就行
讲个笑话，统一延迟计算出我和WARP节点之间只有1ms
![image](https://github.com/user-attachments/assets/999ee51a-40b4-4ec2-bc9b-62cabd6e03be)

**Comment by wonfen** [comment]
无法？自己设置即可。
