### ISSUE TITLE
[BUG] MACOS TUN 模式下 orb.local 域名(orbstack) 部署的 docker 域名都无法访问，要先关闭 TUN  访问一下域名再开启 TUN才正常

### ISSUE THREAD

**Issue by szkane** [clash-verge-rev/clash-verge-rev#2129]
### 问题描述 / Describe the bug

MACOS TUN 模式下 orb.local 域名(orbstack) 部署的 docker 域名都无法访问，要先关闭 TUN  访问一下域名再开启 TUN才正常

### 软件版本 / Verge Version

V2.0.1

### 复现步骤 / To Reproduce

1. 开启 TUN 后，用 orbstack 随便 run 个 web 项目的 docker
2. 用 orb 提供https 的本地域名访问 docker，显示无法连接
3. 关闭 TUN，再访问，可以了
4. 再开启 TUN

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log
感觉是 github 这个关键词导致的了
![image](https://github.com/user-attachments/assets/8e64dcdc-b0e7-4bfe-a8a4-9c920932e1eb)

**Comment by wonfen** [comment]
疑似内核问题，到内核那边提下 issue 吧 https://github.com/clash-verge-rev/clash-verge-rev/issues/2121#issuecomment-2497289479

**Comment by xzmeng** [comment]
这个是fake-ip没有把 `*.orb.local` 过滤导致的，同样遇到这个问题的朋友到`设置->DNS覆写->Fake IP过滤` 把 `*.orb.local` 加进去就可以了。

虽然默认已经包含了 `*.local` ，但是这个只通配一级域名。

**Comment by j4free** [comment]
我也折腾了好久,之前用小火箭的时候 orbstack 也有这种问题,当时是直接在配置里加条 Hosts 把 *.orb.local 指向了127.0.0.1 . clash verge 我也尝试过从 fake-ip 排除 orb.local ,还是没效果,而且先启动 orbstack 后启动 clash verge 就可以解析,反之不行.最后的解决办法可以参考下:配合fake-ip排除+.orb.local然后虚拟网卡设置->排除自定义网段 : 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
