### ISSUE TITLE
[Feature]希望增加代理路径的节点显示

### ISSUE THREAD

**Issue by wxdjs** [clash-verge-rev/clash-verge-rev#213]
### Is your feature request related to a problem? Please describe.

在代理组A中如果选择了一个代理组B，希望增加显示代理组B选择的节点名称

### Describe the solution you'd like

在代理组A中如果选择了一个代理组B，希望增加显示代理组B选择的节点名称

### Describe alternatives you've considered

在代理组A中如果选择了一个代理组B，希望增加显示代理组B选择的节点名称

**Comment by wonfen** [comment]
没想好如何实现
