### ISSUE TITLE
[BUG] 开启了 静默启动 然后重启软件时 用热键打开面板就卡死 必须要任务管理器结束才行

### ISSUE THREAD

**Issue by heygudian** [clash-verge-rev/clash-verge-rev#2130]
### 问题描述 / Describe the bug

开启了 静默启动 然后重启软件时 用热键打开面板就卡死 必须要任务管理器结束才行 
重启软件时不能直接用热键打开面板不然会卡死无响应 必须要鼠标点一下右下角图标进入面板了之后 才能正常使用热键打开面板

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

开启了 静默启动 然后重启软件时 用热键打开面板就卡死 必须要任务管理器结束才行 
重启软件时不能直接用热键打开面板不然会卡死无响应 必须要鼠标点一下右下角图标进入面板了之后 才能正常使用热键打开面板

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

.

**Comment by wonfen** [comment]
热键不要设置带有ctrl和q

**Comment by heygudian** [comment]
我设置的是shift+f 一样的没用的老板 麻烦优化下吧 软件在退出之后 重新启动 静默模式下 然后直接按快捷键呼出面板 无反应直接卡死 鼠标点也不行 只能任务管理器结束进程




y458406
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "clash-verge-rev/clash-verge-rev"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月26日(星期二) 凌晨0:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [clash-verge-rev/clash-verge-rev] [BUG] 开启了 静默启动 然后重启软件时 用热键打开面板就卡死 必须要任务管理器结束才行 (Issue #2130)





 
热键不要设置带有ctrl和q

**Comment by heygudian** [comment]
> 同样的，我重启也是会卡死，并且没有设置热键怀疑是![image](https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTE4NTAsIm5iZiI6MTczMjYxMTU1MCwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODU5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzg3OGI4NmFhNjNkOWFlZWI1NjY3MDE1OWRjYTIwMjFlYzVlODRkNTNlYzU1MjhlMGY3MjZkMGY2N2Q2MzI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.brahIPmLJV9ClhxVPEiRRuG9a5fSiQI6rEZTCo1xNzU)这个程序没有关闭导致的

是每次重启的话都要关闭吗？如果每次重启都要关闭的话 我还不如不开静默启动呢 没区别甚至更麻烦

**Comment by wonfen** [comment]
> 同样的，我重启也是会卡死，并且没有设置热键怀疑是 ![image](https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTEwNDUsIm5iZiI6MTczMjYxMDc0NSwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDhjYTZkYzdmMTgyNDcyMGVlMGU4YWU1YjVlNDhmODZiNThjNzJhOGNkMmZjOWU0ZWVkMDRkZmZmYmE5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfG6DtN9XodGsxLUfwZU-EWuJl-U6FcFDznlLrqhHM8) 这个程序没有关闭导致的

别乱猜，已经找到问题修复了。

**Comment by heygudian** [comment]
> > 同样的，我重启也是会卡死，并且没有设置热键怀疑是<img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTEwNDUsIm5iZiI6MTczMjYxMDc0NSwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDhjYTZkYzdmMTgyNDcyMGVlMGU4YWU1YjVlNDhmODZiNThjNzJhOGNkMmZjOWU0ZWVkMDRkZmZmYmE5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfG6DtN9XodGsxLUfwZU-EWuJl-U6FcFDznlLrqhHM8">这个程序没有关闭导致的
> 
> 别乱猜，已经找到问题修复了。

没有阿，现在还是没收到最新版本

**Comment by wonfen** [comment]
> > > 同样的，我重启也是会卡死，并且没有设置热键怀疑是 ![image](https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTEwNDUsIm5iZiI6MTczMjYxMDc0NSwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDhjYTZkYzdmMTgyNDcyMGVlMGU4YWU1YjVlNDhmODZiNThjNzJhOGNkMmZjOWU0ZWVkMDRkZmZmYmE5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfG6DtN9XodGsxLUfwZU-EWuJl-U6FcFDznlLrqhHM8) 这个程序没有关闭导致的
> > 
> > 
> > 别乱猜，已经找到问题修复了。
> 
> 什么叫别乱猜？程序正常退出后进程没有终止难道不是问题？傻逼似的

哪里来的疯狗？你是开发还是我是开发？这个是服务，就是在后台运行的，为了保证程序能以管理员权限运行所必须的

**Comment by monster1237** [comment]
> > > 同样的，我重启也是会卡死，并且没有设置热键怀疑是 ![image](https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTEwNDUsIm5iZiI6MTczMjYxMDc0NSwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDhjYTZkYzdmMTgyNDcyMGVlMGU4YWU1YjVlNDhmODZiNThjNzJhOGNkMmZjOWU0ZWVkMDRkZmZmYmE5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfG6DtN9XodGsxLUfwZU-EWuJl-U6FcFDznlLrqhHM8) 这个程序没有关闭导致的
> > 
> > 
> > 
> > 别乱猜，已经找到问题修复了。
> 
> 什么叫别乱猜？程序正常退出后进程没有终止难道不是问题？傻逼似的

就目前这个版本，正常退出程序后，这个进程就是没有正常关闭，只有关闭后我才能重新运行

**Comment by wonfen** [comment]
> > > > 同样的，我重启也是会卡死，并且没有设置热键怀疑是 ![image](https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTEwNDUsIm5iZiI6MTczMjYxMDc0NSwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDhjYTZkYzdmMTgyNDcyMGVlMGU4YWU1YjVlNDhmODZiNThjNzJhOGNkMmZjOWU0ZWVkMDRkZmZmYmE5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfG6DtN9XodGsxLUfwZU-EWuJl-U6FcFDznlLrqhHM8) 这个程序没有关闭导致的
> > > 
> > > 
> > > 别乱猜，已经找到问题修复了。
> > 
> > 
> > 什么叫别乱猜？程序正常退出后进程没有终止难道不是问题？傻逼似的
> 
> 就目前这个版本，正常退出程序后，这个进程就是没有正常关闭，只有关闭后我才能重新运行

说了已经修复了，还嘴硬，去下新版本试试吧
https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha

**Comment by monster1237** [comment]
> > > > 同样的，我重启也是会卡死，并且没有设置热键怀疑是 ![image](https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTEwNDUsIm5iZiI6MTczMjYxMDc0NSwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDhjYTZkYzdmMTgyNDcyMGVlMGU4YWU1YjVlNDhmODZiNThjNzJhOGNkMmZjOWU0ZWVkMDRkZmZmYmE5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfG6DtN9XodGsxLUfwZU-EWuJl-U6FcFDznlLrqhHM8) 这个程序没有关闭导致的
> 
> > > 
> 
> > > 
> 
> > > 别乱猜，已经找到问题修复了。
> 
> > 
> 
> > 什么叫别乱猜？程序正常退出后进程没有终止难道不是问题？傻逼似的
> 
> 
> 
> 哪里来的疯狗？你是开发还是我是开发？这个是服务，就是在后台运行的，为了保证程序能以管理员权限运行所必须的

傻狗你开发怎么了？要不要看看问题是什么，我退出程序后，服务还在运行，你敢说是正常情况？

**Comment by wonfen** [comment]
> > > > > 同样的，我重启也是会卡死，并且没有设置热键怀疑是 ![image](https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTEwNDUsIm5iZiI6MTczMjYxMDc0NSwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDhjYTZkYzdmMTgyNDcyMGVlMGU4YWU1YjVlNDhmODZiNThjNzJhOGNkMmZjOWU0ZWVkMDRkZmZmYmE5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfG6DtN9XodGsxLUfwZU-EWuJl-U6FcFDznlLrqhHM8) 这个程序没有关闭导致的
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 别乱猜，已经找到问题修复了。
> > 
> > 
> > > 
> > 
> > 
> > > 什么叫别乱猜？程序正常退出后进程没有终止难道不是问题？傻逼似的
> > 
> > 
> > 哪里来的疯狗？你是开发还是我是开发？这个是服务，就是在后台运行的，为了保证程序能以管理员权限运行所必须的
> 
> 傻狗你开发怎么了？要不要看看问题是什么，我退出程序后，服务还在运行，你敢说是正常情况？

你理解服务是什么？sb

**Comment by mingcheng** [comment]
> > > > > 同样的，我重启也是会卡死，并且没有设置热键怀疑是 ![image](https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTEwNDUsIm5iZiI6MTczMjYxMDc0NSwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDhjYTZkYzdmMTgyNDcyMGVlMGU4YWU1YjVlNDhmODZiNThjNzJhOGNkMmZjOWU0ZWVkMDRkZmZmYmE5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfG6DtN9XodGsxLUfwZU-EWuJl-U6FcFDznlLrqhHM8) 这个程序没有关闭导致的
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 别乱猜，已经找到问题修复了。
> > 
> > 
> > > 
> > 
> > 
> > > 什么叫别乱猜？程序正常退出后进程没有终止难道不是问题？傻逼似的
> > 
> > 
> > 哪里来的疯狗？你是开发还是我是开发？这个是服务，就是在后台运行的，为了保证程序能以管理员权限运行所必须的
> 
> 傻狗你开发怎么了？要不要看看问题是什么，我退出程序后，服务还在运行，你敢说是正常情况？

纯路人路过，如果你觉得有问题提个 PR 就好了，我们代码说服别人、一起解决问题不就好了，人身攻击算是什么玩意？

**Comment by mingcheng** [comment]
> > > > > 同样的，我重启也是会卡死，并且没有设置热键怀疑是 ![image](https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTEwNDUsIm5iZiI6MTczMjYxMDc0NSwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDhjYTZkYzdmMTgyNDcyMGVlMGU4YWU1YjVlNDhmODZiNThjNzJhOGNkMmZjOWU0ZWVkMDRkZmZmYmE5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfG6DtN9XodGsxLUfwZU-EWuJl-U6FcFDznlLrqhHM8) 这个程序没有关闭导致的
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 别乱猜，已经找到问题修复了。
> > 
> > 
> > > 
> > 
> > 
> > > 什么叫别乱猜？程序正常退出后进程没有终止难道不是问题？傻逼似的
> > 
> > 
> > 哪里来的疯狗？你是开发还是我是开发？这个是服务，就是在后台运行的，为了保证程序能以管理员权限运行所必须的
> 
> 傻狗你开发怎么了？要不要看看问题是什么，我退出程序后，服务还在运行，你敢说是正常情况？

纯路人路过，如果你觉得有问题提个 PR 就好了，我们代码说服别人、一起解决问题不就好了，人身攻击算是什么玩意？

**Comment by HuTao28** [comment]
> > > > > 同样的，我重启也是会卡死，并且没有设置热键怀疑是 ![image](https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTEwNDUsIm5iZiI6MTczMjYxMDc0NSwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDhjYTZkYzdmMTgyNDcyMGVlMGU4YWU1YjVlNDhmODZiNThjNzJhOGNkMmZjOWU0ZWVkMDRkZmZmYmE5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfG6DtN9XodGsxLUfwZU-EWuJl-U6FcFDznlLrqhHM8) 这个程序没有关闭导致的
> > 
> > > > 
> > 
> > > > 
> > 
> > > > 别乱猜，已经找到问题修复了。
> > 
> > > 
> > 
> > > 什么叫别乱猜？程序正常退出后进程没有终止难道不是问题？傻逼似的
> > 
> > 
> > 
> > 哪里来的疯狗？你是开发还是我是开发？这个是服务，就是在后台运行的，为了保证程序能以管理员权限运行所必须的
> 
> 傻狗你开发怎么了？要不要看看问题是什么，我退出程序后，服务还在运行，你敢说是正常情况？

道理很简单：用就别叫，叫就别用
开源开发者不欠你的，也没逼着你用

**Comment by NathonChris** [comment]
> > > > > > 同样的，我重启也是会卡死，并且没有设置热键怀疑是 ![image](https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTEwNDUsIm5iZiI6MTczMjYxMDc0NSwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDhjYTZkYzdmMTgyNDcyMGVlMGU4YWU1YjVlNDhmODZiNThjNzJhOGNkMmZjOWU0ZWVkMDRkZmZmYmE5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfG6DtN9XodGsxLUfwZU-EWuJl-U6FcFDznlLrqhHM8) 这个程序没有关闭导致的
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > 别乱猜，已经找到问题修复了。
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 什么叫别乱猜？程序正常退出后进程没有终止难道不是问题？傻逼似的
> > > 
> > > 
> > > 哪里来的疯狗？你是开发还是我是开发？这个是服务，就是在后台运行的，为了保证程序能以管理员权限运行所必须的
> > 
> > 
> > 傻狗你开发怎么了？要不要看看问题是什么，我退出程序后，服务还在运行，你敢说是正常情况？
> 
> 你理解服务是什么？sb

sb玩意，狗叫什么，亲妈死了？

**Comment by NathonChris** [comment]
> > > > > 同样的，我重启也是会卡死，并且没有设置热键怀疑是 ![image](https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTEwNDUsIm5iZiI6MTczMjYxMDc0NSwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDhjYTZkYzdmMTgyNDcyMGVlMGU4YWU1YjVlNDhmODZiNThjNzJhOGNkMmZjOWU0ZWVkMDRkZmZmYmE5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfG6DtN9XodGsxLUfwZU-EWuJl-U6FcFDznlLrqhHM8) 这个程序没有关闭导致的
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 别乱猜，已经找到问题修复了。
> > 
> > 
> > > 
> > 
> > 
> > > 什么叫别乱猜？程序正常退出后进程没有终止难道不是问题？傻逼似的
> > 
> > 
> > 哪里来的疯狗？你是开发还是我是开发？这个是服务，就是在后台运行的，为了保证程序能以管理员权限运行所必须的
> 
> 傻狗你开发怎么了？要不要看看问题是什么，我退出程序后，服务还在运行，你敢说是正常情况？

sb玩意，狗叫什么？

**Comment by aflyingnoob** [comment]
笑晕 删号了

**Comment by ladieman217** [comment]
笑了

**Comment by xiaohanbao263** [comment]
> > > > > 同样的，我重启也是会卡死，并且没有设置热键怀疑是 ![image](https://private-user-images.githubusercontent.com/113280444/389866186-4229f8d6-2430-4293-abbd-88104c4e42fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTEwNDUsIm5iZiI6MTczMjYxMDc0NSwicGF0aCI6Ii8xMTMyODA0NDQvMzg5ODY2MTg2LTQyMjlmOGQ2LTI0MzAtNDI5My1hYmJkLTg4MTA0YzRlNDJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwODQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDhjYTZkYzdmMTgyNDcyMGVlMGU4YWU1YjVlNDhmODZiNThjNzJhOGNkMmZjOWU0ZWVkMDRkZmZmYmE5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QfG6DtN9XodGsxLUfwZU-EWuJl-U6FcFDznlLrqhHM8) 这个程序没有关闭导致的
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 别乱猜，已经找到问题修复了。
> > 
> > 
> > > 
> > 
> > 
> > > 什么叫别乱猜？程序正常退出后进程没有终止难道不是问题？傻逼似的
> > 
> > 
> > 哪里来的疯狗？你是开发还是我是开发？这个是服务，就是在后台运行的，为了保证程序能以管理员权限运行所必须的
> 
> 傻狗你开发怎么了？要不要看看问题是什么，我退出程序后，服务还在运行，你敢说是正常情况？

😂

**Comment by waxingren** [comment]
什么妖魔鬼怪都有啊

**Comment by bettersao** [comment]
笑晕在电脑前

**Comment by Vincy1230** [comment]
乐 专程来看傻逼

**Comment by CXK-Computer** [comment]
乐

**Comment by Richardleeeeeee** [comment]
😂😂专门来看沙比的啊😂😂

**Comment by VictorChow** [comment]
专门来看😏

**Comment by lslllaneo** [comment]
什么玩意都来github的issue发言了，一点智商和礼貌都没，还是门槛太低了。
