### ISSUE TITLE
[BUG] win11 2.0.1最小化到任务栏后有概率无法打开面板

### ISSUE THREAD

**Issue by utopeadia** [clash-verge-rev/clash-verge-rev#2136]
### 问题描述 / Describe the bug

win11最小化到任务栏后有概率无法打开面板且任务栏右键也无法触发（类似假死），内核正常运行，UI无法使用。需要任务管理器关闭服务后重新打开应用

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

最小化到任务栏后有概率（或者某些没有捕获的操作）触发

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11 24H2

### 日志 / Log

应用日志内没有记录到有效信息，只有启动代理

**Comment by qilang888** [comment]
我也遇到同样的问题，一但假死，连右键都失效，只能任务管理器关闭再重启

**Comment by SQiPower** [comment]
same，昨天遇到同样问题 点击关闭按钮后最小化到任务栏 任务栏里咋点都没反应

**Comment by utopeadia** [comment]
> 最小化任务栏是点关闭按钮还是最小化按钮？

关闭按钮，后台运行在任务栏保留图标

**Comment by Ealsen** [comment]
Me too

**Comment by Tychristine** [comment]
@Ealsen 你是否已打开【静默启动】？
Did you turn on [Silent Start]?

**Comment by Ealsen** [comment]
> @Ealsen 你是否已打开【静默启动】？ Did you turn on [Silent Start]?

Yes.

**Comment by Tychristine** [comment]
@utopeadia @qilang888 @HeartyYF @SQiPower @BiliBiliSmallball @Ealsen 
It looks like it's been fixed on another branch .
I test it on my local machine platform `Windows 11 Pro amd64`.

**Comment by chenzhenpeng** [comment]
我也遇到了，我的是开启自启动，然后就会遇到面板打不开

**Comment by Tychristine** [comment]
@chenzhenpeng It was fixed on `2.0.2.` please download a new from https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha

**Comment by kb5706** [comment]
我也遇到了同样的问题，最小化之后就不能打开UI了。服务仍然正常，但是不能打开面板调整了。只有任务管理器结束任务之后重开。

**Comment by utopeadia** [comment]
> 我也遇到了同样的问题，最小化之后就不能打开UI了。服务仍然正常，但是不能打开面板调整了。只有任务管理器结束任务之后重开。

alpha已经修复了亲，https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha

**Comment by kb5706** [comment]
> > 我也遇到了同样的问题，最小化之后就不能打开UI了。服务仍然正常，但是不能打开面板调整了。只有任务管理器结束任务之后重开。
> 
> alpha已经修复了亲，https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha

已经安装了alpha版本，问题仍然存在。尝试过重启电脑，还是一样。
