### ISSUE TITLE
[Feature]希望能够适配隐藏代理组的功能

### ISSUE THREAD

**Issue by EluneAdore1** [clash-verge-rev/clash-verge-rev#214]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

这个commit，https://github.com/MetaCubeX/mihomo/commit/ffcd672ebf1412de62915b754150f562873579f6
API增加了返回代理组是否可以隐藏的字段
考虑适配吗

### Describe alternatives you've considered

**

**Comment by b1ghawk** [comment]
+1，同样希望可以隐藏代理组。

**Comment by MystiPanda** [comment]
有文档吗，配置文件应该怎么写？
