### ISSUE TITLE
[BUG] 开启TUN模式后，系统无网络，

### ISSUE THREAD

**Issue by zhou12808** [clash-verge-rev/clash-verge-rev#2140]
### 问题描述 / Describe the bug

[BUG] 开启TUN模式后，系统无网络，百度都不能打开，只开系统代理可以上 google.com网络正常

### 软件版本 / Verge Version

最新版V2.0.1

### 复现步骤 / To Reproduce

有安装过astrill 卸载astrill clash 就不能正常试用了。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

widnows 11

### 日志 / Log

11-26 09:42:53debug
[https://dns.twnic.tw:443/dns-query] using HTTP/2 for this upstream: <nil>
11-26 09:42:53debug
re-creating the http client due to requesting https://dns.twnic.tw:443/dns-query: Get "https://dns.twnic.tw:443/dns-query?dns=AAABAAABAAAAAAAAC2xpdmV1cGRhdGUyDGRyaXZlcmdlbml1cwNjb20AABwAAQ": context deadline exceeded
11-26 09:42:53debug
[https://dns.twnic.tw:443/dns-query] using HTTP/2 for this upstream: <nil>
11-26 09:42:53debug
[DNS] dns.alidns.com --> [] AAAA from udp://223.5.5.5:53
11-26 09:42:53debug
[Rule] use default rules
11-26 09:42:53info
[TCP] 198.18.0.1:13442 --> 59.82.122.84:443 match GeoIP(cn) using DIRECT

**Comment by Tychristine** [comment]
配置文件写太烂，日志也未提供相关部分

**Comment by zhou12808** [comment]
> 配置文件写太烂，日志也未提供相关部分

需要那些部分.

**Comment by Tychristine** [comment]
@zhou12808 我猜是DNS部分

**Comment by zhou12808** [comment]
> @zhou12808 我猜是DNS部分
有可能，请教大佬, 怎么修复这个问题呢，

**Comment by Tychristine** [comment]
dns:
  enable: true
  prefer-h3: true
  use-system-hosts: true
  listen: 0.0.0.0:5053
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter:
    - "+.lan"
    - "connect.rom.miui.com"
    - "+.miwifi.com"
    - "+.ntp.org"
    - "+.u-tools.cn"
    - "+.mediatek.com"
    - "+.cfprefer1.xyz"
    - "+.wetab.link"
    - "+.tyasaka.xyz"
    # QQ
    - "localhost.ptlogin2.qq.com"
    - "localhost.sec.qq.com"
    # WeChat
    - "localhost.work.weixin.qq.com"
    - "+.weixin.qq.com"
    - "+.wechat.com"
    # Windows
    - "time.windows.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "+.wpsmail.net"
    - "+.henzanapp.com"
    - "+.pconline.com.cn"
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  proxy-server-nameserver:
    - 8.8.8.8
    - 1.1.1.1
  fallback:
    - 8.8.8.8
    - 1.1.1.1
    - tls://1.0.0.1:853
    - tls://dns.google:853

**Comment by zhou12808** [comment]
> dns: enable: true prefer-h3: true use-system-hosts: true listen: 0.0.0.0:5053 ipv6: true respect-rules: true enhanced-mode: fake-ip fake-ip-filter-mode: blacklist fake-ip-range: 198.18.0.0/15 fake-ip-filter: - "+.lan" - "connect.rom.miui.com" - "+.miwifi.com" - "+.ntp.org" - "+.u-tools.cn" - "+.mediatek.com" - "+.cfprefer1.xyz" - "+.wetab.link" - "+.tyasaka.xyz" # QQ - "localhost.ptlogin2.qq.com" - "localhost.sec.qq.com" # WeChat - "localhost.work.weixin.qq.com" - "+.weixin.qq.com" - "+.wechat.com" # Windows - "time.windows.com" - "+.msftconnecttest.com" - "+.msftncsi.com" - "+.wpsmail.net" - "+.henzanapp.com" - "+.pconline.com.cn" nameserver: - 119.29.29.29 - 223.5.5.5 proxy-server-nameserver: - 8.8.8.8 - 1.1.1.1 fallback: - 8.8.8.8 - 1.1.1.1 - tls://1.0.0.1:853 - tls://dns.google:853

这里应该放到那个位置呢，我是 小白，感谢大佬指导.

**Comment by Tychristine** [comment]
@Jason8996 
如果你只是单纯的因为小地球图标.
> Windows 通过向`msftconnecttest.com`主机发出请求，并以响应返回内容来判断Windows是否已连接互联网.   

只需放行这个连接就行了

![image](https://github.com/user-attachments/assets/db2ff763-f770-419f-9b48-5cca1d9b08c2)

![image](https://github.com/user-attachments/assets/62dc2ba2-08ca-4016-ad38-f0308963bae1)

**Comment by zhou12808** [comment]
> @Jason8996 如果你只是单纯的因为小地球图标.
> 
> > Windows 通过向`msftconnecttest.com`主机发出请求，并以响应返回内容来判断Windows是否已连接互联网.
> 
> 只需放行这个连接就行了
> 
> ![image](https://private-user-images.githubusercontent.com/105919355/389803873-db2ff763-f770-419f-9b48-5cca1d9b08c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDgxNjksIm5iZiI6MTczMjYwNzg2OSwicGF0aCI6Ii8xMDU5MTkzNTUvMzg5ODAzODczLWRiMmZmNzYzLWY3NzAtNDE5Zi05YjQ4LTVjY2ExZDliMDhjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwNzU3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDg3YWZjODc1NGZmNWM2ZjJmNTk0MWRkNDhmY2U4MGQxZjk2YmNhNjA1YzhjMjMxN2M0ODM5MWM0OGI5MjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yheqda6APnLqwVSOliNhW-cDQJ_sm5ljEo9AhJVcKC4)
> 
> ![image](https://private-user-images.githubusercontent.com/105919355/389803911-62dc2ba2-08ca-4016-ad38-f0308963bae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDgxNjksIm5iZiI6MTczMjYwNzg2OSwicGF0aCI6Ii8xMDU5MTkzNTUvMzg5ODAzOTExLTYyZGMyYmEyLTA4Y2EtNDAxNi1hZDM4LWYwMzA4OTYzYmFlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwNzU3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWZjYzkxMDM0YzNkZTY2Zjc3YTEwNzU3MmNhZWMxYzcyNWJlMjUxNmY4YTFkZTM5ZmI3MjkzNDlmNjM0MTc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oR8N5ISY9MvAe3Psz6YKHXPBIhFkKbhG2j3OTcwYJh8)

这个在那里设置呢，我已经重置电脑系统，clash可以正常使用，但是也显示这个无网络的问题
