### ISSUE TITLE
[BUG] MacOS 15.1.1 安装2.0.1之后无法打开  提示The application “Clash Verge” can’t be opened.

### ISSUE THREAD

**Issue by KrisShin** [clash-verge-rev/clash-verge-rev#2141]
### 问题描述 / Describe the bug

MacOS 15.1.1 M1 Pro 安装aarch64 v2.0.1版本之后无法打开  提示 The application “Clash Verge” can’t be opened.

### 软件版本 / Verge Version

v2.0.1

### 复现步骤 / To Reproduce

打开dmg包  将clash verge 复制到Applications文件夹 然后从启动器点击打开 出现弹窗提示  The application “Clash Verge” can’t be opened.

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log

由于无法打开 所以我无法提供日志

**Comment by KrisShin** [comment]
抱歉是我系统的问题

**Comment by Tychristine** [comment]
Mac15 Arm64是没毛病啊，啥情况？

**Comment by AMlhdSan** [comment]
没毛病啊

**Comment by AMlhdSan** [comment]
不是系统的问题：
你这么搞：在终端中先输入：`sudo xattr -dr com.apple.quarantine`，然后打开访达，打开“应用程序”，找到`Clash Verge`，把软件拖到终端里（记得在`sudo xattr -dr com.apple.quarantine`后面打一个空格），回车，输入密码就可以了
![CleanShot 2024-11-26 at 10 49 09@2x](https://github.com/user-attachments/assets/49e84573-0c1a-4e3b-a71a-ae56c1d848d7)

**Comment by KrisShin** [comment]
> MacOS15 Arm64是没毛病啊，啥情况？

我的系统问题  应该是清理垃圾的时候错删了什么缓存  重起就好了

**Comment by KrisShin** [comment]
> 不是系统的问题： 你这么搞：在终端中先输入：`sudo xattr -dr com.apple.quarantine`，然后打开访达，打开“应用程序”，找到`Clash Verge`，把软件拖到终端里（记得在`sudo xattr -dr com.apple.quarantine`后面打一个空格），回车，输入密码就可以了 ![CleanShot 2024-11-26 at 10 49 09@2x](https://private-user-images.githubusercontent.com/151382553/389774193-49e84573-0c1a-4e3b-a71a-ae56c1d848d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1OTMyNzAsIm5iZiI6MTczMjU5Mjk3MCwicGF0aCI6Ii8xNTEzODI1NTMvMzg5Nzc0MTkzLTQ5ZTg0NTczLTBjMWEtNGUzYi1hNzFhLWFlNTZjMWQ4NDhkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMzQ5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2UxMWQ2OTNmNDM1MTlkZmI2ODRlY2I2ZDIzMTA3NzcyYjY2YTEzMjQ3ZjU2NWRkY2NlMWY3OWVkZmJmMzZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D6AxVyLhTjmx6botPrAIPpABJR-wLhA2jpYxgs9fXuI)

我重启系统就好了  应该是清理垃圾的时候删除了什么有用的缓存

**Comment by AMlhdSan** [comment]
哦，这样啊，以后遇到打不开的都可以这样

**Comment by wonfen** [comment]
> 不是系统的问题： 你这么搞：在终端中先输入：`sudo xattr -dr com.apple.quarantine`，然后打开访达，打开“应用程序”，找到`Clash Verge`，把软件拖到终端里（记得在`sudo xattr -dr com.apple.quarantine`后面打一个空格），回车，输入密码就可以了 ![CleanShot 2024-11-26 at 10 49 09@2x](https://private-user-images.githubusercontent.com/151382553/389774193-49e84573-0c1a-4e3b-a71a-ae56c1d848d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1OTM0ODUsIm5iZiI6MTczMjU5MzE4NSwicGF0aCI6Ii8xNTEzODI1NTMvMzg5Nzc0MTkzLTQ5ZTg0NTczLTBjMWEtNGUzYi1hNzFhLWFlNTZjMWQ4NDhkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMzUzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTU0YWJhNWFiMTVjNWQxMWM3MTQ4ZjY5MzMyZGVhMGNhMTViNmQ3YjJlMjVlOWU2OTcxM2YzZDIwMTIyOWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UYkNXfWFoGMWui0a6KZipvHNdXHjUVgR73Rwrwy1Rnc)

别乱教，这个命令现在用不到了。是之前没apple开发者签名时候用的。现在已经申请了apple开发者签名了。

**Comment by AMlhdSan** [comment]
这个一般不回吧

**Comment by AMlhdSan** [comment]
反正用着不就行了吗

**Comment by AMlhdSan** [comment]
> > 不是系统的问题： 你这么搞：在终端中先输入：`sudo xattr -dr com.apple.quarantine`，然后打开访达，打开“应用程序”，找到`Clash Verge`，把软件拖到终端里（记得在`sudo xattr -dr com.apple.quarantine`后面打一个空格），回车，输入密码就可以了 ![CleanShot 2024-11-26 at 10 49 09@2x](https://private-user-images.githubusercontent.com/151382553/389774193-49e84573-0c1a-4e3b-a71a-ae56c1d848d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1OTM0ODUsIm5iZiI6MTczMjU5MzE4NSwicGF0aCI6Ii8xNTEzODI1NTMvMzg5Nzc0MTkzLTQ5ZTg0NTczLTBjMWEtNGUzYi1hNzFhLWFlNTZjMWQ4NDhkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMzUzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTU0YWJhNWFiMTVjNWQxMWM3MTQ4ZjY5MzMyZGVhMGNhMTViNmQ3YjJlMjVlOWU2OTcxM2YzZDIwMTIyOWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UYkNXfWFoGMWui0a6KZipvHNdXHjUVgR73Rwrwy1Rnc)
> 
> 别乱教，这个命令现在用不到了。是之前没apple开发者签名时候用的。现在已经申请了apple开发者签名了。

问题不大

**Comment by AMlhdSan** [comment]
> > 不是系统的问题： 你这么搞：在终端中先输入：`sudo xattr -dr com.apple.quarantine`，然后打开访达，打开“应用程序”，找到`Clash Verge`，把软件拖到终端里（记得在`sudo xattr -dr com.apple.quarantine`后面打一个空格），回车，输入密码就可以了 ![CleanShot 2024-11-26 at 10 49 09@2x](https://private-user-images.githubusercontent.com/151382553/389774193-49e84573-0c1a-4e3b-a71a-ae56c1d848d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1OTM0ODUsIm5iZiI6MTczMjU5MzE4NSwicGF0aCI6Ii8xNTEzODI1NTMvMzg5Nzc0MTkzLTQ5ZTg0NTczLTBjMWEtNGUzYi1hNzFhLWFlNTZjMWQ4NDhkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMzUzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTU0YWJhNWFiMTVjNWQxMWM3MTQ4ZjY5MzMyZGVhMGNhMTViNmQ3YjJlMjVlOWU2OTcxM2YzZDIwMTIyOWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UYkNXfWFoGMWui0a6KZipvHNdXHjUVgR73Rwrwy1Rnc)
> 
> 别乱教，这个命令现在用不到了。是之前没apple开发者签名时候用的。现在已经申请了apple开发者签名了。

能用就行
