### ISSUE TITLE
[BUG] 2.0.1 系统代理-设置代理绕过不生效

### ISSUE THREAD

**Issue by lgbwust** [clash-verge-rev/clash-verge-rev#2142]
### 问题描述 / Describe the bug

1.X版本可以正常代理绕过，但是升级2.0.1之后设置代理绕过不生效

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

系统设置-系统代理-配置代理绕过

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 10

### 日志 / Log

无

**Comment by wonfen** [comment]
我这里是生效，检查你的设置方法，另外日志呢？补充全部信息后重发issue
