### ISSUE TITLE
[BUG] 无法拖拽导入订阅

### ISSUE THREAD

**Issue by TryA9ain** [clash-verge-rev/clash-verge-rev#2143]
### 问题描述 / Describe the bug

点击“订阅”，拖拽 `.yaml` 文件，发现无法像之前的版本拖拽导入订阅

![CleanShot 2024-11-26 at 10 40 18@2x](https://github.com/user-attachments/assets/bc144d43-aefe-4274-82a9-cda3e48caa86)

### 软件版本 / Verge Version

V2.0.1

### 复现步骤 / To Reproduce

点击“订阅”，拖拽 `.yaml` 文件，发现无法像之前的版本拖拽导入订阅

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

**Comment by Tychristine** [comment]
17a8dfb
