### ISSUE TITLE
[BUG] 不支持 TFO ？  

### ISSUE THREAD

**Issue by ChristChen128** [clash-verge-rev/clash-verge-rev#2144]
### 问题描述 / Describe the bug

当订阅中的的代理节点 `tfo: true` 时，节点就会测速失败，网页也打不开。
<img width="627" alt="image" src="https://github.com/user-attachments/assets/ecd68e71-f6e1-4b81-a020-48027d2cda9b">
手动把订阅 proxies 下节点的 `tfo: true` 删掉，测速正常，网页打开正常；
切换成 CFW ，不改订阅，订阅测速正常，网页打开正常；
尝试把软件完全卸载重装，不解决问题

### 软件版本 / Verge Version

Verge 版本：v2.0.1
Clash 内核：v1.18.10 Mihomo

### 复现步骤 / To Reproduce

1. 机场订阅中的 proxies 节点配有 `tfo: true`
2. 更新订阅
3. 测速、打开网页

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macos Sequoia 15.1.1

### 日志 / Log

无

**Comment by wonfen** [comment]
这部分由内核处理，先排查机场是否支持，国内入口是否支持，操作系统是否开启支持。
