### ISSUE TITLE
[BUG] 无法记住界面大小

### ISSUE THREAD

**Issue by wha4up** [clash-verge-rev/clash-verge-rev#2146]
### 问题描述 / Describe the bug

2.0以前的版本在关闭程序后再次打开会保持关闭时的尺寸，2.0版后再次打开是默认固定尺寸。

如果是BUG希望能修复，如果不是BUG希望能增加/恢复“记住界面大小”的功能。

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

关闭程序再次打开

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

24H2

### 日志 / Log

[2024-11-26-1228.log](https://github.com/user-attachments/files/17912692/2024-11-26-1228.log)

**Comment by Tychristine** [comment]
Please refer to the release notes at https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v2.0.1
