### ISSUE TITLE
[BUG] win11 2.0.1打开或关闭tun模式，都会导致网络外网访问断开半分钟甚至更久

### ISSUE THREAD

**Issue by ForMySunny** [clash-verge-rev/clash-verge-rev#2147]
### 问题描述 / Describe the bug

2.0.1打开或关闭tun模式，都会导致网络外网访问断开半分钟甚至更久。特地切换回2.0.0-rc2，没有这个问题

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

打开关闭tun模式

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 24H2

### 日志 / Log

无

**Comment by wonfen** [comment]
疑似内核问题，到内核那边提下 issue 吧 https://github.com/clash-verge-rev/clash-verge-rev/issues/2121#issuecomment-2497289479
