### ISSUE TITLE
[BUG] Mac OS 14 Intel 图标在最左侧重复出现

### ISSUE THREAD

**Issue by hc-advokate** [clash-verge-rev/clash-verge-rev#2148]
### 问题描述 / Describe the bug

应该是之前重复过的问题，请复查一下。这个 2.x 版本测试中就遇到过，但后续的版本修复过，正式版又出现了。

### 软件版本 / Verge Version

2.0.1
MacOS 14.6.1 Intel

### 复现步骤 / To Reproduce

完全删除 CV 文件后，重新安装 2.0.1 版本即可复现。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.6.1

### 日志 / Log

<img width="1715" alt="iShot_2024-11-26_16 23 26" src="https://github.com/user-attachments/assets/8e7e1c1c-9828-4bdf-960a-4f7820be1d43">

**Comment by IrisGitHub** [comment]
+1。clash verge v2.0.1;Apple M1;MacOS v14.3.

**Comment by hc-advokate** [comment]
MacOS 15 不会出现此问题，已验证。

**Comment by wonfen** [comment]
看文档：

https://www.clashverge.dev/faq/macos.html#macos_1
