### ISSUE TITLE
请问centos系统怎么安装呢

### ISSUE THREAD

**Issue by zhongdixiu** [clash-verge-rev/clash-verge-rev#215]

**Comment by tyrantGXY** [comment]
同问，也想知道

**Comment by madoka773** [comment]
源码安装

**Comment by madoka773** [comment]
先安装webkit2gtk4.0 nodejs pnpm cargo rust ， 然后 pnpm i , pnpm check , pnpm build --bundle deb 然后在target release找找就有了，把东西放到root对应的文件夹里就行

**Comment by madoka773** [comment]
```
BuildRequires:  jq
BuildRequires:  cargo
BuildRequires:  wget
BuildRequires:  curl
BuildRequires:  file
BuildRequires:  nodejs
BuildRequires:  pnpm
BuildRequires:  openssl-devel
BuildRequires:  librsvg2-devel
BuildRequires:  webkit2gtk4.0-devel
BuildRequires:  rust-gobject-sys+default-devel
BuildRequires:  rust-pango+default-devel
BuildRequires:  rust-cairo-rs+default-devel 
BuildRequires:  rust-atk-sys+default-devel
BuildRequires:  rust-gdk-sys+default-devel
BuildRequires:  moreutils
BuildRequires:  rust-openssl+default-devel
BuildRequires:  webkit2gtk4.0
BuildRequires:  libappindicator-gtk3
BuildRequires:  libappindicator-gtk3-devel
```

构建需要的依赖，centos里没的话我也没办法

**Comment by madoka773** [comment]
https://github.com/madoka773/fedora/blob/main/clash-nyanpasu/clash-nyanpasu.spec 参考

**Comment by parheliamm** [comment]
Appimage应该可以吧

**Comment by archzi** [comment]
I have attempted to create an RPM package from the source code, but it is not functioning properly in Fedora 39. The issue might be due to Tauri not upgrading its dependencies. I will try testing it on CentOS 8/9 at a later time. you can find the issue ticket in [there ](https://github.com/tauri-apps/tauri/issues/6559)
