### ISSUE TITLE
[BUG] Fadora Gnome 桌面环境启动后无 UI 弹出

### ISSUE THREAD

**Issue by AmarokIce** [clash-verge-rev/clash-verge-rev#2151]
### 问题描述 / Describe the bug

Fadora Gnome 桌面环境启动后无 UI 弹出

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

任意方式启动

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Fedora 41 +  GNOME 47.1.1

### 日志 / Log

(clash-verge:6513): Gtk-CRITICAL **: 17:52:49.436: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by AmarokIce** [comment]
经过数次的卸载，重启，安装后莫名自己好了，虽然不理解原理，但是确实解决了。
这份 Issue 将会关闭。

**Comment by AmarokIce** [comment]
问题依旧，能弹出窗口才是偶然。
开启自启动与静默启动后就无法再次把窗口呼叫出来，每次都会开一个新的背景线程。

**Comment by Tychristine** [comment]
@AmarokIce Try 2.0.2?

**Comment by dear7575** [comment]
window11 也是有这个问题，不知道啥情况

**Comment by AmarokIce** [comment]
> @AmarokIce Try 2.0.2?

问题依旧，但是至少 Dock 上会显示启动了。没有窗口，每次点以下背景程序 +1。
目前发现如果开了静默启动就会这样，不开静默启动就没问题。
这样出现过之后尝试卸载再倒退 177 版本会导致 177 也变成这样，必须卸载后重启再安装 177, 关闭静默启动后卸载更新 20x 恢复正常。

**Comment by AmarokIce** [comment]
今天开 Windows 试了一下，也是一样的问题，静默启动会导致无论何种方式呼叫都不会有窗口，不使用静默启动正常使用。

**Comment by aixiao0621** [comment]
同样的问题以及报错，关闭静默启动后界面可以正常打开

**Comment by MyDataHouse** [comment]
确实是静默启动导致的可以修改 ，C:\Users\你的用户名\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev\verge.yaml 文件, 修改后重启软件
```yaml
enable_silent_start: false
```

**Comment by AmarokIce** [comment]
Windows & Linux 均以再 2.0.2 解决，感激不尽。
