### ISSUE TITLE
[BUG] 卸载重装了好几次，TUN模式无法联网

### ISSUE THREAD

**Issue by poneding** [clash-verge-rev/clash-verge-rev#2152]
### 问题描述 / Describe the bug

之前用的clash verge 版本是 v1.5.11，可以正常使用系统代理和 TUN 模式翻墙。现在新版本 v2.0.0 和 v2.0.1 我都安装使用了，系统代理正常，但是一旦开启 TUN 模式，就无法上网了，所有网络都无法连接，关闭又恢复正常。

### 软件版本 / Verge Version

v2.0.x

### 复现步骤 / To Reproduce

MacOS 15.1.1 安装 Clash Verge v2.0.1，导入订阅地址，开启系统代理，选择规则模式。可以正常翻墙上网。开启TUN模式，无法联网。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log

11-26 18:08:03DEBUG
[DNS] resolve dns.alidns.com AAAA from udp://180.184.1.1:53
11-26 18:08:03DEBUG
[DNS] resolve dns.alidns.com AAAA from udp://119.29.29.29:53
11-26 18:08:03DEBUG
[https://dns.alidns.com:443/dns-query] using HTTP/2 for this upstream: <nil>
11-26 18:08:03DEBUG
[DNS] resolve dns.alidns.com A from udp://223.5.5.5:53
11-26 18:08:03DEBUG
[DNS] resolve dns.alidns.com A from udp://180.184.1.1:53
11-26 18:08:03DEBUG
[DNS] resolve dns.alidns.com A from udp://119.29.29.29:53
11-26 18:08:03DEBUG
re-creating the http client due to requesting https://dns.alidns.com:443/dns-query: Get "https://dns.alidns.com:443/dns-query?dns=AAABAAABAAAAAAAACThoN3J2cW5ldwliaWdtZXllYXIDb3JnAAABAAE": dns resolve failed: couldn't find ip

**Comment by zty0510** [comment]
the same

**Comment by liuhuo23** [comment]
得手动安装服务了， 进入内核目录。 然后sudo 先卸载服务 然后退出 ， 打开的时候就会让输入密码。 你可以试一试

**Comment by Tychristine** [comment]
@liuhuo23 它这里是TUN已经在运行了，并且你看它提供的日志最后一行表示是DNS解析出错误了。可能是配置文件没有写好

**Comment by wonfen** [comment]
疑似内核问题，到内核那边提下 issue 吧 https://github.com/clash-verge-rev/clash-verge-rev/issues/2121#issuecomment-2497289479

**Comment by poneding** [comment]
临时的解决方案：
1. 下载 1.18.9 版本 Mihomo 内核：[mihomo-v1.18.9](https://github.com/MetaCubeX/mihomo/releases/tag/v1.18.9)，解压得到内核程序文件，重命名为 verge-mihomo

2. 进入内核目录，替换 verge-mihomo
<img width="284" alt="image" src="https://github.com/user-attachments/assets/2ca5e2c8-54eb-43b9-ba37-5e469398f010">
<img width="544" alt="image" src="https://github.com/user-attachments/assets/48343ae0-04cc-48ab-81b5-1411ee4f7522">

3. 在内核目录下，按住 Option 键，待显示路径栏后右键点击文件目录，点击在终端打开，输入 `chmod +x verge-mihomo`
<img width="666" alt="image" src="https://github.com/user-attachments/assets/e350f8e4-427b-477f-aa01-7ab4ac4edcc1">
<img width="358" alt="image" src="https://github.com/user-attachments/assets/892d4bfa-ade2-4451-8619-7105d3fdcd2e">
