### ISSUE TITLE
[BUG] 软件内更新失败

### ISSUE THREAD

**Issue by dzzzzzzzzzzy** [clash-verge-rev/clash-verge-rev#2157]
### 问题描述 / Describe the bug

![屏幕截图 2024-11-27 001750](https://github.com/user-attachments/assets/fa5605c8-1ce8-44f0-b4b7-ff9637fa01d8)
软件内更新失败

### 软件版本 / Verge Version

2.0.0

### 复现步骤 / To Reproduce

软件内更新失败

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

软件内更新失败

**Comment by Tychristine** [comment]
阅读发行说明
