### ISSUE TITLE
[BUG][RaspberryPi]树莓派编译报错：error: failed to run custom build command for `clash-verge v1.4.6`

### ISSUE THREAD

**Issue by limuyuan** [clash-verge-rev/clash-verge-rev#216]
### Describe the bug

编译报错 Failed to build
error: failed to run custom build command for `clash-verge v1.4.6 

### To Reproduce

```bash
pnpm i
pnpm run check
pnpm build
```

### Platform

Linux

### System Version

Debian GNU/Linux 12 (bookworm)

### Software Version

1.4.6

### Log

clash-verge-rev $ pnpm build

> clash-verge@1.4.6 build /home/morris/repo/clash-verge-rev
> tauri build

     Running beforeBuildCommand `pnpm run web:build`

> clash-verge@1.4.6 web:build /home/morris/repo/clash-verge-rev
> tsc && vite build

vite v4.5.0 building for production...
✓ 13958 modules transformed.
../dist/index.html                               2.30 kB │ gzip:   0.94 kB
../dist/assets/logo-30296787.ico                33.50 kB
../dist/assets/codicon-71cccbf1.ttf             72.50 kB
../dist/assets/Twemoji.Mozilla-61db6397.ttf  1,454.53 kB
../dist/assets/index-2c490bb6.css               43.77 kB │ gzip:   7.98 kB
../dist/assets/yaml-6dcc1ae8.js                  4.28 kB │ gzip:   1.64 kB
../dist/assets/javascript-7505618b.js            6.72 kB │ gzip:   2.42 kB
../dist/assets/index-c36b69e0.js             3,117.32 kB │ gzip: 872.59 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 46.49s
   Compiling clash-verge v1.4.6 (/home/morris/repo/clash-verge-rev/src-tauri)
   Compiling window-shadows v0.2.2
   Compiling nanoid v0.4.0
   Compiling port_scanner v0.1.5
error: failed to run custom build command for `clash-verge v1.4.6 (/home/morris/repo/clash-verge-rev/src-tauri)`

Caused by:
  process didn't exit successfully: `/home/morris/repo/clash-verge-rev/src-tauri/target/release/build/clash-verge-615833259db46c12/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  path matching sidecar/clash-meta-aarch64-unknown-linux-gnu not found.
warning: build failed, waiting for other jobs to finish...
       Error failed to build app: failed to build app
 ELIFECYCLE  Command failed with exit code 1.

**Comment by MystiPanda** [comment]
编译前先运行pnpm check下载内核等资源

**Comment by limuyuan** [comment]
> 编译前先运行pnpm check下载内核等资源
你好，我在重现步骤里已经写明运行过`pnpm run check`


我又运行了一次，问题依旧，不知是否可以reopen this issue？
morris@pi:~/repo/clash-verge-rev $ pnpm check

> clash-verge@1.4.6 check /home/morris/repo/clash-verge-rev
> node scripts/check.mjs

morris@pi:~/repo/clash-verge-rev $ pnpm build

> clash-verge@1.4.6 build /home/morris/repo/clash-verge-rev
> tauri build

     Running beforeBuildCommand `pnpm run web:build`

> clash-verge@1.4.6 web:build /home/morris/repo/clash-verge-rev
> tsc && vite build

vite v4.5.0 building for production...
✓ 13958 modules transformed.
../dist/index.html                               2.30 kB │ gzip:   0.94 kB
../dist/assets/logo-30296787.ico                33.50 kB
../dist/assets/codicon-71cccbf1.ttf             72.50 kB
../dist/assets/Twemoji.Mozilla-61db6397.ttf  1,454.53 kB
../dist/assets/index-2c490bb6.css               43.77 kB │ gzip:   7.98 kB
../dist/assets/yaml-6dcc1ae8.js                  4.28 kB │ gzip:   1.64 kB
../dist/assets/javascript-7505618b.js            6.72 kB │ gzip:   2.42 kB
../dist/assets/index-c36b69e0.js             3,117.32 kB │ gzip: 872.59 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 48.74s
   Compiling clash-verge v1.4.6 (/home/morris/repo/clash-verge-rev/src-tauri)
error: failed to run custom build command for `clash-verge v1.4.6 (/home/morris/repo/clash-verge-rev/src-tauri)`

Caused by:
  process didn't exit successfully: `/home/morris/repo/clash-verge-rev/src-tauri/target/release/build/clash-verge-615833259db46c12/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  path matching sidecar/clash-meta-aarch64-unknown-linux-gnu not found.
       Error failed to build app: failed to build app
 ELIFECYCLE  Command failed with exit code 1.

**Comment by limuyuan** [comment]
Finally I figured it out....I was using a socks5 proxy, which is not supported.
I will open another issue on this

**Comment by limuyuan** [comment]
Another issue that related to Raspberry Pi: https://github.com/tauri-apps/tauri/issues/4174
The deb can be built, but not for AppImage.'

✓ built in 48.53s
   Compiling tauri-runtime-wry v0.14.2
   Compiling clash-verge v1.4.6 (/home/morris/repo/clash-verge-rev/src-tauri)
   Compiling tauri v1.5.3
    Finished release [optimized] target(s) in 4m 07s
    Bundling clash-verge_1.4.6_arm64.deb (/home/morris/repo/clash-verge-rev/src-tauri/target/release/bundle/deb/clash-verge_1.4.6_arm64.deb)
    Bundling clash-verge_1.4.6_aarch64.AppImage (/home/morris/repo/clash-verge-rev/src-tauri/target/release/bundle/appimage/clash-verge_1.4.6_aarch64.AppImage)
       Error failed to bundle project: error running appimage.sh
 ELIFECYCLE  Command failed with exit code 1.
