### ISSUE TITLE
[BUG] Debian12无法打开界面

### ISSUE THREAD

**Issue by MuggleTan** [clash-verge-rev/clash-verge-rev#2161]
### 问题描述 / Describe the bug

Debian12 Gnome桌面无法打开程序界面

### 软件版本 / Verge Version

Clash.Verge_2.0.1_amd64

### 复现步骤 / To Reproduce

安装完成之后点击无法打开，但是进程中有clash，把clash的进程杀掉之后，用sudo在命令行有概率可以打开，会打印一些日志

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Debian GNU/Linux 12 (bookworm)

### 日志 / Log

(process:12432): dconf-WARNING **: 11:00:41.861: failed to commit changes to dconf: 执行子进程“dbus-launch”失败（没有那个文件或目录）

(process:12443): dconf-WARNING **: 11:00:41.874: failed to commit changes to dconf: 执行子进程“dbus-launch”失败（没有那个文件或目录）

(process:12447): dconf-WARNING **: 11:00:41.886: failed to commit changes to dconf: 执行子进程“dbus-launch”失败（没有那个文件或目录）

(clash-verge:12355): libayatana-appindicator-WARNING **: 11:00:41.925: Unable to get the session bus: 执行子进程“dbus-launch”失败（No such file or directory）

(clash-verge:12355): LIBDBUSMENU-GLIB-WARNING **: 11:00:41.925: Unable to get session bus: 执行子进程“dbus-launch”失败（No such file or directory）

**Comment by wonfen** [comment]
无法复现，刚刚在debian 12 中测试了，正常
![image](https://github.com/user-attachments/assets/c5752774-2d82-442e-adf0-af279ae841c4)

**Comment by lonelyice521** [comment]
刚安装的debian 12, 启动静安模式，开机自启，无法打开托盘。 就像厦门图片
![debian](https://github.com/user-attachments/assets/2ccba514-e4fc-41c0-b271-7f285372ffa6)

**Comment by lonelyice521** [comment]
debian 12 , 软件2.02版本，手动进入 把/.local/io... verge.yml配置里面 静默启动 关闭，重启 恢复正常。

> 刚安装的debian 12, 启动静安模式，开机自启，无法打开托盘。 就像厦门图片 ![debian](https://private-user-images.githubusercontent.com/120197329/390717867-2ccba514-e4fc-41c0-b271-7f285372ffa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODU3MDUsIm5iZiI6MTczMjc4NTQwNSwicGF0aCI6Ii8xMjAxOTczMjkvMzkwNzE3ODY3LTJjY2JhNTE0LWU0ZmMtNDFjMC1iMjcxLTdmMjg1MzcyZmZhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwOTE2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2VmOTBiYmE3YTBhZmFlN2M3Yjk0YzFiZDc5YjQxMGViZDA4MTI2ZTA2ZDUxZGUzYWMxM2Y1NGFiYTIwYzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QUzAN3SHG0-GfVst3qyQOAaCMNOB4jlrruAY3-yIcsY)

**Comment by duchenpaul** [comment]
For detail: in `~/.local/share/io.github.clash-verge-rev.clash-verge-rev/verge.yaml`, edit:
```
enable_silent_start: true -> false
```
