### ISSUE TITLE
[BUG] win11静默启动+开机自启，托盘点击无效

### ISSUE THREAD

**Issue by NAF-EY** [clash-verge-rev/clash-verge-rev#2162]
### 问题描述 / Describe the bug

- 托盘点击无效，不能打开主页面，单击或右键均无反应
- 设置里为默认的**显示主窗口**选项
- 第一次安装版本为2.0rc，没有出现这个bug，后续手动升级2.0出现此bug，卸载安装2.0.1bug依然存在
- 任务管理器关闭所有clash verge进程然后重新打开可以解决，重启电脑后bug会复现，关闭静默启动或开机启动之一都可以解决
- 已关闭快速启动

### 软件版本 / Verge Version

- 2.0.0/2.0.1

### 复现步骤 / To Reproduce

-  打开**静默启动**和**开机自启**，每次重启电脑均会产生

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

24h2 26100.2454

### 日志 / Log

[2024-11-27-1251.log](https://github.com/user-attachments/files/17929272/2024-11-27-1251.log)

**Comment by Tychristine** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/2136#issuecomment-2499658924

**Comment by NAF-EY** [comment]
> [#2136 (comment)](https://github.com/clash-verge-rev/clash-verge-rev/issues/2136#issuecomment-2499658924)

# 我试了一下，Alpha 并没有修复我描述的 bug，不过我发现了 bug 产生的由来，如图
## 如果只开静默启动，开机的时候程序依然会自动打开，此时后台只有一个 clash verge 进程

![只开静默启动](https://github.com/user-attachments/assets/4a827029-dbde-4499-8b44-99fccd695bb3)

## 但如果开机自启和静默启动都打开，此时后台有两个 clash verge 进程，bug 复现

![静默启动+开机启动](https://github.com/user-attachments/assets/ac805135-76ad-4979-9888-df9e1bdff29b)

## 此外如果开机时在 clash verge 自启之前手动打开，这个 bug 也不会出现
