### ISSUE TITLE
[BUG] 2.0.2 .window-state修改了最后两行true 调整好了窗口大小文档又变成了初始化X和Y直接变成0而且不能拖拽 上一个版本不会这样 麻烦开发排查下看看啥问题

### ISSUE THREAD

**Issue by heygudian** [clash-verge-rev/clash-verge-rev#2163]
### 问题描述 / Describe the bug

2.0.2 .window-state修改了最后两行true 调整好了窗口大小文档又变成了初始化X和Y直接变成0而且不能拖拽 上一个版本不会这样 麻烦开发排查下看看啥问题

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

2.0.2 .window-state修改了最后两行true 调整好了窗口大小文档又变成了初始化X和Y直接变成0而且不能拖拽 上一个版本不会这样 麻烦开发排查下看看啥问题

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

.

**Comment by wonfen** [comment]
没听懂你说的哪里？

**Comment by heygudian** [comment]
> 没听懂你说的哪里？上个版本是2.0.1还是1.7.7 ？

不是1.7.7，1.7.7窗口是有记忆的是已经固定的了，是上一个版本2.0.1是可以正常设置的但是热键BUG有问题 这个版本修复了热键BUG了但是这个又出问题了 无法记忆固定了改文件也不行会自动变回初始

鼠标拖动调整好窗口大小后，编辑C:\Users\用户名\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev.window-state.json 文件，
1、将最后两行的 false 改成 true；
2、将 prev_x 改成与 x 数值相同；
3、将 prev_y 改成与 y 相同；
4、保存修改，并将文件属性改成只读。结果类似如下图，一切OK！

**Comment by wonfen** [comment]
修复了

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha
