### ISSUE TITLE
[BUG] 托盘有clash图标但点不开

### ISSUE THREAD

**Issue by cactus20201010** [clash-verge-rev/clash-verge-rev#2164]
### 问题描述 / Describe the bug

win11，2.01版本，静默启动，开机自启，托盘有clash，但是无法打开。关闭MyDockFinder后可以打开，貌似和该软件有冲突。已尝试兼容模式但没有用。之前旧版本时未出现该问题。

### 软件版本 / Verge Version

2.01

### 复现步骤 / To Reproduce

开机，托盘有clash图标但无法点开，关闭MyDockFinder后可以点开clash。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

点不开

**Comment by kb5706** [comment]
我也用了MyDockFinder，安装了最新的aphla版本也是没有办法打开。我还没试过关闭MyDockFinder……

**Comment by kb5706** [comment]
试了关闭了MyDockFinder，在重开就能打开了，alpha版本，这是什么诡异的冲突bug……

**Comment by NAF-EY** [comment]
然而我没有用MyDockFinder也有这个bug

**Comment by kb5706** [comment]
我试了一下，关闭了静默启动的开关，即使使用了MyDockFinder，也是能打开面板的。

**Comment by derekxia1988** [comment]
报错：failed to restore window state: runtime error: failed to receive message from webview。
关闭silent start之后第一次启动应用可以打开界面，关闭之后依然无法打开。
在2.0.2alpha版本问题依然存在。

**Comment by cactus20201010** [comment]
奇怪的bug，刚开始是MyDockFinder打开情况下无法打开clash，关闭MyDockFinder后就能够打开。然后重启电脑后发现关闭MyDockFinder后也无法打开clash了。再然后到现在MyDockFinder打开的情况下也能点开clash了（看前面有人说的关闭了静默启动）。

**Comment by derekxia1988** [comment]
> 报错：failed to restore window state: runtime error: failed to receive message from webview。 关闭silent start之后第一次启动应用可以打开界面，关闭之后依然无法打开。 在2.0.2alpha版本问题依然存在。 Windows版本：Win11 24H2
> 
> 更新：看上去跟MyDockFinder确实有点儿关系，我显示Windows任务栏之后，在Windows任务栏上是正常的。

找到一个办法：在mydockfinder里显示windows任务栏，这个时候就可以打开clash verge的ui，然后再关闭windows任务栏，依然可以显示。

**Comment by NAF-EY** [comment]
#2168 看我评论试试

**Comment by cactus20201010** [comment]
> #2168 看我评论试试
本来昨天我2.01版本clash莫名其妙好了，然后下午看到了你的issue，跟着改了改注册表，结果又出问题了，然后装了卸，卸了装，改注册表，改局域网设置和dns（浏览器上不了网），折腾了一下午，最后选择用回1.7.5版本，笑死，还是等着更稳定的版本我再更新吧

**Comment by cactus20201010** [comment]
> #2168 看我评论试试

本来昨天我2.01版本clash莫名其妙好了，然后下午看到了你的issue，跟着改了改注册表，结果又出问题了，然后装了卸，卸了装，改注册表，改局域网设置和dns（浏览器上不了网），折腾了一下午，最后选择用回1.7.5版本，笑死，还是等着更稳定的版本我再更新吧

**Comment by sofine23** [comment]
我也是，托盘有图标，点不开面板，老版本先卸载再装的2.0.1，win11，可以看到有很多clsah和webview进程，进程杀死之后就可以再重新用
![image](https://github.com/user-attachments/assets/74807ece-93b7-451d-88ec-3775290dd2d0)

**Comment by hsiayuchih** [comment]
我也有这个情况，还以为就我一个这样，原来不是个例那就放心了

**Comment by NAF-EY** [comment]
@sofine23 Alpha新版本已经修复了 #2168
