### ISSUE TITLE
[BUG] Macos下会有两个托盘图标

### ISSUE THREAD

**Issue by ElioFinn** [clash-verge-rev/clash-verge-rev#2166]
### 问题描述 / Describe the bug

<img width="1680" alt="截屏2024-11-27 16 34 01" src="https://github.com/user-attachments/assets/7b3bfe51-34a0-40d6-9de3-03d3cae27f35">
重启/重装后都不会消失

### 软件版本 / Verge Version

v2.0.1

### 复现步骤 / To Reproduce

重新打开

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log

[2024-11-27-1637.log](https://github.com/user-attachments/files/17931416/2024-11-27-1637.log)

**Comment by Tychristine** [comment]
?
https://www.clashverge.dev/faq/macos.html#macos_1
