### ISSUE TITLE
[BUG] win11静默启动+开机自启，托盘图标点击无效

### ISSUE THREAD

**Issue by NAF-EY** [clash-verge-rev/clash-verge-rev#2168]
### 问题描述 / Describe the bug

#  Alpha 版本没有修复我描述的 bug #2162 
- 托盘点击无效，不能打开主页面，单击或右键均无反应

### 软件版本 / Verge Version

- 2.0.0/2.0.1/2.0.2

### 复现步骤 / To Reproduce

- 如果只开静默启动，开机的时候程序依然会自动打开，此时后台只有一个 clash verge 进程，程序正常运行无 bug

![只开静默启动](https://github.com/user-attachments/assets/4a827029-dbde-4499-8b44-99fccd695bb3)

- 但如果开机自启和静默启动都打开，此时后台有两个 clash verge 进程，bug 复现

![静默启动+开机启动](https://github.com/user-attachments/assets/ac805135-76ad-4979-9888-df9e1bdff29b)

- 进一步，如果在 clash verge 正常启动未产生 bug 的状态下又手动打开了 clash verge，bug 复现并且有多个 clash verge 进程，每打开一次会多一个进程

![QQ20241127-184433](https://github.com/user-attachments/assets/0f94da9d-59c6-4734-a2be-aa113748429c)

- 我发现在程序刚开始运行的时候，clash verge 进程图标如图
![QQ20241127-185423](https://github.com/user-attachments/assets/0bbdc96b-a810-4284-a3b3-4f4136179383)
- 如果此时手动再次打开 clash verge 就会出现我上面描述的bug
![QQ20241127-185459](https://github.com/user-attachments/assets/eef6acfd-dbde-4563-ab8d-371ed79429f7)
- 但如果此时先点击托盘弹出主页面，就会变成正常状态下的进程
![QQ20241127-185436](https://github.com/user-attachments/assets/1ec095d5-c0f6-4c4a-9707-6ed22f74e4ed)
- 此时再次手动打开 clash verge 则不会产生bug 而是弹出主页面

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 24H2 26100.2454

### 日志 / Log

[2024-11-27-1824.log](https://github.com/user-attachments/files/17933456/2024-11-27-1824.log)

**Comment by wonfen** [comment]
联系我远程调试 https://t.me/wonfen_bot

**Comment by NAF-EY** [comment]
- 开机启动产生bug的问题已解决，在大佬帮助下看了一下注册表启动项，还残留clash for windows的启动项，导致开机启动了两次verge
- 和我问题相似的朋友如果是开机就托盘图标无响应可以看一下是否安装过 clash for windows 并在注册表中删除启动项即可解决
![025939AE82E8DBB609DD2488F208F5EC](https://github.com/user-attachments/assets/2214a107-73cb-4ae2-9186-c42994f23a40)

**Comment by Tychristine** [comment]
难怪我复现不出来

**Comment by wonfen** [comment]
最alpha已经修复。
