### ISSUE TITLE
[BUG]安装新版本升级，必须手动关掉clash-verge service的进程，否则升级卡住

### ISSUE THREAD

**Issue by tyrantGXY** [clash-verge-rev/clash-verge-rev#217]
### Describe the bug

安装新版本升级，必须手动关掉clash-verge service的进程，否则升级卡住报错

### To Reproduce

升级过程中报错

### Platform

Windows

### System Version

windows 11

### Software Version

v1.4.5

**Comment by htt-ui** [comment]
Describe the bug
安装新版本升级，必须手动关掉clash-verge service的进程，否则升级卡住报错

To Reproduce
升级过程中报错

Platform
Windows

System Version
windows 10

Software Version
v1.4.5

Log
No response

Additional Information
No response

**Comment by Protein-V** [comment]
Describe the bug
1.4.5的旧版本要覆盖安装新的1.4.6时，也因为这个clash-verge service进程打不开而被迫中止更新安装

To Reproduce
升级过程中报错

Platform
Windows

System Version
windows 11

Software Version
v1.4.5

Log
No response

Additional Information
No response

**Comment by MystiPanda** [comment]
1.4.5修复了的，看1.4.5的更新日志啊

**Comment by tyrantGXY** [comment]
并没有修复，1.4.5升级1.4.6还是会出现这个问题。必须手动结束clash verge service才行。我2台电脑都复现了

**Comment by MystiPanda** [comment]
你看1.4.5的更新日志了吗？
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/152463842/5740d58a-135d-47dd-a891-b60c51b84e5b)

**Comment by tyrantGXY** [comment]
关键是我重装了啊，之前卸载的干干净净，重新装的1.4.5然后升级1.4.6又出现这个问题

**Comment by MystiPanda** [comment]
我说的是重装服务，你看清楚好不好
