### ISSUE TITLE
[Feature] windows 安装提供压缩包zip格式

### ISSUE THREAD

**Issue by valord577** [clash-verge-rev/clash-verge-rev#2170]
### 功能描述 / Feature description

windows 安装提供压缩包zip格式

### 使用场景 / Use case

不想使用exe安装 想自己完全控制安装路径

**Comment by Tychristine** [comment]
自行构建可解决

**Comment by valord577** [comment]
@Tychristine 看了取消便携版的说明 感觉`不能自动更新`是主要原因(不知道我有没有理解错)

但对于熟悉开发人员的人来说 每次更新都会看一下更新公告的 有问题才会容易降级 也能自主升级

很怕自动更新之后 带来了一些bug 反过头来要去找原因 提issue提log
