### ISSUE TITLE
[BUG] 关于开启静默启动和开机自启之后，关机重启电脑后表现为代理可行，但无法呼出程序界面

### ISSUE THREAD

**Issue by awkervic** [clash-verge-rev/clash-verge-rev#2178]
### 问题描述 / Describe the bug

第一次安装设置好之后，重启，重启之后，程序可以自动启动，代理也正常，但是左右击点击托盘菜单没有反应。
需要在任务管理器里强制终结进程后再重新打开程序才会恢复正常，才能正常打开窗口。

### 软件版本 / Verge Version

2.02

### 复现步骤 / To Reproduce

全新下载安装后，导入代理配置，设置中开启系统代理，开机自启，静默启动后最小化窗口。然后关机，重启即可复现。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 专业工作站版22H2，内部版本：19045.4894

### 日志 / Log

[logs.zip](https://github.com/user-attachments/files/17942620/logs.zip)

**Comment by Illustar0** [comment]
+1

**Comment by wonfen** [comment]
请测试最新编译的alpha版本，应该已经修复了。
