### ISSUE TITLE
[BUG]1.4.6core error 退回1.4.5正常

### ISSUE THREAD

**Issue by yonee77** [clash-verge-rev/clash-verge-rev#218]
### Describe the bug

[BUG]1.4.6core error 退回1.4.5正常

### To Reproduce

[BUG]1.4.6core error 退回1.4.5正常

### Platform

Windows

### System Version

WINDOWS 7

### Software Version

1.4.6

### Log

[2024-01-10-1434.log](https://github.com/clash-verge-rev/clash-verge-rev/files/13884097/2024-01-10-1434.log)

**Comment by MystiPanda** [comment]
看起来是新版的内核不支持win7了，自己回退一下内核吧。

**Comment by yxszd** [comment]
用新版go120版本替换v1.4.6的core，可以使用，但是更新GeoDate会出现 WARNING:To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+

**Comment by yxszd** [comment]
用go120编译替换v1.4.6的core，可以使用

**Comment by yonee77** [comment]
> 用go120编译替换v1.4.6的core，可以使用

可以了，谢谢
