### ISSUE TITLE
[BUG] 打开clash verge以后能ping通本不应该ping通的机器

### ISSUE THREAD

**Issue by GarraWong** [clash-verge-rev/clash-verge-rev#2180]
### 问题描述 / Describe the bug

在远程服务器关闭了所有的icmp端口，在打开了clash verge的情况下能够ping通该服务器。预期是不能ping通。
一旦关闭clash verge以后，终端里就ping不同该服务器了，符合预期

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

ping一台关闭了icmp端口的远程服务器

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1 (24B83)

### 日志 / Log

11-28 14:24:30DEBUG
[DNS] 45-courier.push.apple.com --> [17.57.145.55 17.57.145.54] A from https://dns.alidns.com:443/dns-query
11-28 14:24:30DEBUG
[DNS] resolve 45-courier.push.apple.com A from tls://8.8.4.4:853
11-28 14:24:30DEBUG
[DNS] resolve 45-courier.push.apple.com A from https://doh.dns.sb:443/dns-query
11-28 14:24:30DEBUG
[DNS] resolve 45-courier.push.apple.com A from https://dns.cloudflare.com:443/dns-query
11-28 14:24:30DEBUG
[DNS] resolve 45-courier.push.apple.com A from https://dns.twnic.tw:443/dns-query
11-28 14:24:30DEBUG
[DNS] cache hit doh.dns.sb --> [103.121.210.210] A, expire at 2024-11-28 14:29:44
11-28 14:24:30DEBUG
[DNS] cache hit dns.cloudflare.com --> [104.16.133.229 104.16.132.229] A, expire at 2024-11-28 14:25:28
11-28 14:24:30DEBUG
[DNS] cache hit doh.dns.sb --> [2403:fbc0:1000::babe] AAAA, expire at 2024-11-28 14:29:02
11-28 14:24:30DEBUG
[DNS] cache hit dns.cloudflare.com --> [2606:4700::6810:85e5 2606:4700::6810:84e5] AAAA, expire at 2024-11-28 14:25:28
11-28 14:55:21DEBUG
[DNS] hijack udp:8.8.8.8:53 from 198.18.0.1:61873
11-28 14:55:21DEBUG
[DNS] cache hit lb._dns-sd._udp.0.64.168.192.in-addr.arpa --> [] PTR, expire at 2024-11-28 14:55:16
11-28 14:55:21DEBUG
[DNS] resolve lb._dns-sd._udp.0.64.168.192.in-addr.arpa PTR from https://dns.alidns.com:443/dns-query
11-28 14:55:21DEBUG
[DNS] resolve lb._dns-sd._udp.0.64.168.192.in-addr.arpa PTR from https://doh.pub:443/dns-query
11-28 14:55:21DEBUG
[DNS] lb._dns-sd._udp.0.64.168.192.in-addr.arpa --> [] PTR from https://dns.alidns.com:443/dns-query

**Comment by Tychristine** [comment]
@GarraWong 请问`Ping`内容返回了什么响应

**Comment by GarraWong** [comment]
> @GarraWong 请问`Ping`内容返回了什么响应
返回的和正常ping通差不多的效果
![image](https://github.com/user-attachments/assets/bfeb46c0-7d53-4d66-9282-657ed0e4e4a6)

**Comment by Tychristine** [comment]
@GarraWong 使用的是`系统代理`还是`Tun Mode`
> 如果你使用`Tun Mode`，则一切连接默认显式的返回fake-ip

**Comment by GarraWong** [comment]
@Tychristine `系统代理` 和`Tun 模式` 均开启了，是否有办法在不改变设置的情况下， 让ping结果返回正常？

**Comment by Tychristine** [comment]
@GarraWong 
如果你需要正常的`Ping`响应结果，请关闭`Tun Mode`
如果你不想要某个域名返回fake-ip，请把它加入 `fake-ip-filter`
如果想在不使用Tun的情况下代理终端，CVR->Settings->Copy Env, 并将环境变量粘贴到终端中
