### ISSUE TITLE
[BUG] 运行pnpm check无法下载

### ISSUE THREAD

**Issue by DeShuiYu** [clash-verge-rev/clash-verge-rev#2181]
### 问题描述 / Describe the bug

运行 pnpm check                                                                                                      

> clash-verge@2.0.0 check /Users/dsy/Desktop/clash-verge-rev
> node scripts/check.mjs

task::verge-mihomo-alpha try 0 == proxyAgent is not a function
task::verge-mihomo try 0 == proxyAgent is not a function
task::verge-mihomo-alpha try 1 == proxyAgent is not a function
task::verge-mihomo try 1 == proxyAgent is not a function
task::verge-mihomo-alpha try 2 == proxyAgent is not a function
task::verge-mihomo try 2 == proxyAgent is not a function
task::verge-mihomo-alpha try 3 == proxyAgent is not a function
task::verge-mihomo try 3 == proxyAgent is not a function
task::verge-mihomo-alpha try 4 == proxyAgent is not a function
task::verge-mihomo try 4 == proxyAgent is not a function
file:///Users/dsy/Desktop/clash-verge-rev/scripts/check.mjs:88
    options.agent = proxyAgent(httpProxy);
                    ^

TypeError: proxyAgent is not a function
    at getLatestAlphaVersion (file:///Users/dsy/Desktop/clash-verge-rev/scripts/check.mjs:88:21)
    at Object.func (file:///Users/dsy/Desktop/clash-verge-rev/scripts/check.mjs:466:7)
    at runTask (file:///Users/dsy/Desktop/clash-verge-rev/scripts/check.mjs:524:18)

Node.js v22.11.0
 ELIFECYCLE  Command failed with exit code 1.

### 软件版本 / Verge Version

version v2.0.1

### 复现步骤 / To Reproduce

1. export https_proxy=http://10.162.7.102:7897 http_proxy=http://10.162.7.102:7897 all_proxy=http://10.162.7.102:7897
2. pnpm i
3. pnpm check

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS Ventura 13.5.1

### 日志 / Log

none

**Comment by DeShuiYu** [comment]
如此修改代码后能够正常运行，最后请clash verge 团队评估 [代理改变.patch](https://github.com/user-attachments/files/17944546/default.patch)

**Comment by Tychristine** [comment]
@DeShuiYu 
https://github.com/clash-verge-rev/clash-verge-rev/actions/runs/12063856369/workflow
CI/CD使用的 `Node Version 20`
我使用`21.7.3` 也能构建

**Comment by DeShuiYu** [comment]
@Tychristine 有试过Node.js v22.11.0版本吗？

**Comment by DeShuiYu** [comment]
> @DeShuiYu https://github.com/clash-verge-rev/clash-verge-rev/actions/runs/12063856369/workflow CI/CD使用的 `Node Version 20` 我使用`21.7.3` 也能构建

你是直连还是走的代理xport http_proxy=这样的

**Comment by Tychristine** [comment]
@DeShuiYu 我是直连的，后台挂着`Tun Mode`

**Comment by DeShuiYu** [comment]
@Tychristine 估计没走options.agent = proxyAgent(httpProxy);这行代码，这行代码上面有个if判断，估计条件为false

**Comment by DeShuiYu** [comment]
@Tychristine 你的估计没走options.agent = proxyAgent(httpProxy);这行代码，这行代码上面有个if判断，估计条件为false

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/2080#issuecomment-2496558948
