### ISSUE TITLE
建议还是保留x64_portable.zip格式下载

### ISSUE THREAD

**Issue by leshanydy2022** [clash-verge-rev/clash-verge-rev#2183]
### 功能描述 / Feature description

建议还是保留x64_portable.zip格式下载

### 使用场景 / Use case

建议还是保留x64_portable.zip格式下载

**Comment by zhangzuwei** [comment]
赞成 +1 ，像我这种强迫症还是用习惯了绿色版本，且绿色版有时候相比安装版比较隐蔽而且更新方便，如果问题不大的话还请相关开发维护者们保留便携版 portable.zip 的下载，谢谢。

**Comment by timiion** [comment]
没有管理员权限，无法安装很难受，赞成保留portable版本。安装提供基于用户的方式，这样不需要管理员权限更合适。

**Comment by Tychristine** [comment]
@timiion 想多了，没有管理员权限是不能注册系统服务的，你也无法启动

**Comment by earthjasonlin** [comment]
便携版可以放u盘里带着走 实在不行可以加个bat之类的来启动 主要是配置可以跟着走

**Comment by timiion** [comment]
> @timiion 想多了，没有管理员权限是不能注册系统服务的，你也无法启动

@Tychristine 只用系统代理功能，不用Tun模式，可以不用注册服务吧。

**Comment by Tychristine** [comment]
@timiion 2.x版本必须又内核继承父进程clash-verge-service服务进程才能启动

**Comment by cauliflowerx** [comment]
建议保留portable绿色版，多台设备使用同步网盘更换版本非常方便，谢谢

**Comment by earthjasonlin** [comment]
> 建议保留portable绿色版，多台设备使用同步网盘更换版本非常方便，谢谢

这个新版本的设置里有WebDAV同步功能

**Comment by cauliflowerx** [comment]
> > 建议保留portable绿色版，多台设备使用同步网盘更换版本非常方便，谢谢
> 
> 这个新版本的设置里有WebDAV同步功能

试过了webdav是备份功能，我说的同步网盘是自动下载云端的软件到本地，切换版本非常简单，把旧版的停用退出，打开新版设置开机启动就可以

**Comment by zxzlf** [comment]
不给便携版也行，能不能在安装包里面把webwiew和主程序解耦？即使我安装目录里面有WebView2.FixedVersion，但是没有在系统里安装webwiew2就不给安装主程序，这就有点难受了，每次更新都要多下100多m的安装包，多写几百m的盘

**Comment by KUYE-OLG** [comment]
好像说是技术上不好实现，要不还是去隔壁项目看看吧

**Comment by Tychristine** [comment]
@zxzlf 
Windows 22H2以后的版本当中 msedgeWebView2将作为系统组件预安装在操作系统中，Win11 22H2以后由系统 WebView2管理器来管理窗口

**Comment by zxzlf** [comment]
> @zxzlf Windows 22H2以后的版本当中 msedgeWebView2将作为系统组件预安装在操作系统中，Win11 22H2以后由系统 WebView2管理器来管理窗口

问题是我这系统里面没有这玩意啊，我也不打算另外再装这个，不是有那个fixed版本么，能不能在检测到安装目录里面有fixed版本的时候直接跳过这一步

**Comment by kakalubi** [comment]
没有管理员权限，都没办法用新版本了。 强烈建议提供一下普通用户权限下的使用功能。
不要注册什么服务，不要TUN模式都行，就是简简单单的web代理功能。

**Comment by Tychristine** [comment]
@kakalubi 自己用Mihomo进行端口转发代理

**Comment by Huiaei** [comment]
+1，公家电脑，安装了怕留痕，每次都是u盘启动的

**Comment by Tychristine** [comment]
@Huiaei 你以为portable就不留痕迹了吗

**Comment by Tychristine** [comment]
# 在解决应用内自动更新的问题前，不会推出Portable便携版

**Comment by Huiaei** [comment]
> @Huiaei 你以为portable就不留痕迹了吗

至少没有安装痕迹，大部分的文件也是保存在软件目录里。安装的话有注册表，软件生成的文件一般也不只存软件目录。而且小痕迹能解释，糊弄糊弄就行了。

**Comment by Tychristine** [comment]
@Huiaei 天真，无论是哪个版本都会在appdata/local, roming两个目录留下数据，即便你是便携版也是一样的。只是少个注册表而已

**Comment by kakalubi** [comment]
> @kakalubi 自己用Mihomo进行端口转发代理

PC上没有管理员权限，所有进程都起不来。 不排斥安装软件，可以接受安装在非系统目录下，但是一定要用Admin权限运行就真没办法用了。
有时间的话，还是希望能考虑一下我们这样的办公用户群体，谢谢，辛苦了！

**Comment by zhangzuwei** [comment]
不过只要未来有推出便携版就行，新版本暂时还没磨好这个可以理解的，麻烦作者和各位维护开发大佬们了，谢谢。

**Comment by Huiaei** [comment]
> @Huiaei 天真，无论是哪个版本都会在appdata/local, roming两个目录留下数据，即便你是便携版也是一样的。只是少个注册表而已

小痕迹无所谓，按照你提供的目录

我在appdata/local中发现了的确有目录，内部存在一个文件夹EBWebView，这个文件夹参考https://github.com/MicrosoftEdge/WebView2Feedback/issues/2023#issuecomment-995218264来说是浏览器内核留下的，尝试删除发现未对程序产生影响，删除后会重新生成

在appdata/roming中未发现相关的目录，可否告知文件路径，我好通过关机脚本来清除这些目录

**Comment by iwalke** [comment]
有一些使用场景。前东家用的深信服的桌面云，重启就还原的，安装的这样不行，每次重启都得安装一遍，不过当时用的 cfw，便携版的。

**Comment by winterli1** [comment]
> 没有管理员权限，都没办法用新版本了。 强烈建议提供一下普通用户权限下的使用功能。 不要注册什么服务，不要TUN模式都行，就是简简单单的web代理功能。

支持这样，需要tun的时候手动开启就行。

**Comment by Tychristine** [comment]
差点忘了，已经在我的分支[christine/clash-verge-rev](https://github.com/Tychristine/clash-verge-rev)上构建便携版了

**Comment by winterli1** [comment]
> 差点忘了，已经在我的分支[christine/clash-verge-rev](https://github.com/Tychristine/clash-verge-rev)上构建便携版了

软件启动的时候自动添加服务吗？

**Comment by shandrive** [comment]
我用回1.7.7 portable了, 又不是不能用

**Comment by shandrive** [comment]
經常重裝系統, 安裝版是比較麻煩,
我用回1.7.7 portable了, 又不是不能用

**Comment by liuyu-f** [comment]
yes
