### ISSUE TITLE
[BUG] MacOS 中开启tun后dns的enhanced-mode会被强制设置为fake-ip模式

### ISSUE THREAD

**Issue by Hades-001** [clash-verge-rev/clash-verge-rev#2185]
### 问题描述 / Describe the bug

MacOS 中开启tun后dns的enhanced-mode会被强制设置为fake-ip模式，无法使用redir-host模式

### 软件版本 / Verge Version

Clash Verge Rev 2.0.1

### 复现步骤 / To Reproduce

tun开启后配置文件中dns的enhanced-mode会被覆盖成fake-ip

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log

无

**Comment by wonfen** [comment]
就是这样设计的；mac下的tun模式设置为fakeip出问题的概率更小。

**Comment by Tychristine** [comment]
@Hades-001 
1. default nameserver :随便写能用的dns,[119.29.29.29,223.5.5.5]甚至-system都可以,一组即可
2. proxy nameserver: 用能解析到节点域名的，比如8.8.8.8, 有需求可加入ipv6DNS
3. nameserver：建议使用两到三组doh，最好是能解析全球的
4. nameserver policy: geosite:cn:使用你最快的dns

**Comment by TomZhang1019** [comment]
> 就是这样设计的；mac下的tun模式设置为fakeip出问题的概率更小。

我在服务端设置了根据域名选择DNS服务器解析, 客户端这里tun模式开启fake-ip后服务器DNS分流就失效了,系统代理模式下使用redir-host就没有问题, 能不能给个选择的余地呢, 让用户手动去配置文件里改一下似乎也不是很麻烦

**Comment by stone2world** [comment]
> 就是这样设计的；mac下的tun模式设置为fakeip出问题的概率更小。

mac fakeip 有问题

kex_exchange_identification: Connection closed by remote host

**Comment by KimChow** [comment]
我在win11也遇到这样的问题，等于说，有一些国外的网站使用tun之后无法解析了，使用系统代理的办法是没有存在这样的问题的。

**Comment by williamszz** [comment]
建议不要强制fake-ip，让用户可以选择。
