### ISSUE TITLE
[BUG] macos每次重启登陆打开提示 “‘osascript’想要进行更改”

### ISSUE THREAD

**Issue by Drom1145** [clash-verge-rev/clash-verge-rev#2187]
### 问题描述 / Describe the bug

无论是正式版还是测试版，在macos每次打开时都会提示“‘osascript’想要进行更改”。关闭开机自启和开启开机自启都会有这个提
只会在电脑重启再登陆时出现
<img width="345" alt="截屏2024-11-28 18 03 41" src="https://github.com/user-attachments/assets/118d8a3c-70ea-470f-b205-5626bece5b6d">

### 软件版本 / Verge Version

前文中正式版为2.0.1，测试版为2.0.2，测试版下载时间为2024年11月28日22：48分

### 复现步骤 / To Reproduce

mac重启，重新登陆并打开（或者开启自启），会发现上述问题

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macos版本15.1.1 (24B91)

### 日志 / Log

只是重复申请权限，并非错误，没有收集到日志当中

**Comment by Tychristine** [comment]
理论上安装时第二次输入的密码，是为service授权root，这样启动就不会要求授权了呀
可是正常安装？

**Comment by wonfen** [comment]
是不是有什么清理软件把服务停了，删了？

**Comment by Drom1145** [comment]
> 是不是有什么清理软件把服务停了，删了？

我电脑上只有广告清理，为了避免可能性我测试，和它并没有关系

**Comment by Drom1145** [comment]
> 是不是有什么清理软件把服务停了，删了？

我电脑上只有广告清理，为了避免可能性我停用后测试，但和它并没有关系

**Comment by Drom1145** [comment]
> 理论上安装时第二次输入的密码，是为service授权root，这样启动就不会要求授权了呀 可是正常安装？

不能完全肯定是否正确安装，但至少是拖进系统“应用程序”文件夹后操作的。对于授权root，提示osascript后并没有要求给予root权限

**Comment by Drom1145** [comment]
> 理论上安装时第二次输入的密码，是为service授权root，这样启动就不会要求授权了呀 可是正常安装？

是按照大多数应用需求，拖进系统“应用程序”文件夹后操作的。对于授权root，提示osascript后并没有要求给予root权限

**Comment by wonfen** [comment]
联系我tg https://t.me/wonfen_bot 远程排查一下

**Comment by wonfen** [comment]
远程看了，用户电脑上有公司安装的安全软件挡了

**Comment by jaoyina** [comment]
我也碰到这个问题，我自己电脑，所以没有公司装的软件。以前老版本没这个问题。

**Comment by Mapleshade20** [comment]
我也碰到了这个问题，每次开机都会弹，电脑没有装安全软件

**Comment by wonfen** [comment]
> 我也碰到了这个问题，每次开机都会弹，电脑没有装安全软件 v2.0.2

那可以正常使用吗？如果不能正常使用联系我TG https://t.me/wonfen_bot

**Comment by Mapleshade20** [comment]
> > 我也碰到了这个问题，每次开机都会弹，电脑没有装安全软件 v2.0.2
> 
> 那可以正常使用吗？如果不能正常使用联系我TG https://t.me/wonfen_bot

经排查问题已解决，启用 Login Items - Allow In Background 中的 "won fen" 项即可。我之前禁用了它是因为不知道它是干嘛的，还以为是卸载过的pulsesecure留下的垃圾，刚才用 `sudo sfltool dumpbtm` 一看发现它是 clash verge 的附属项目

**Comment by A-Kui** [comment]
> > > 我也碰到了这个问题，每次开机都会弹，电脑没有装安全软件 v2.0.2
> > 
> > 
> > 那可以正常使用吗？如果不能正常使用联系我TG https://t.me/wonfen_bot
> 
> 经排查问题已解决，启用 Login Items - Allow In Background 中的 "won fen" 项即可。我之前禁用了它是因为不知道它是干嘛的，还以为是卸载过的pulsesecure留下的垃圾，刚才用 `sudo sfltool dumpbtm` 一看发现它是 clash verge 的附属项目

🐂🍺 终于解决了
![image](https://github.com/user-attachments/assets/0ac34594-22de-4123-97c6-f28773c2a269)

**Comment by babybboy** [comment]
依然有这个问题，楼上的方法看了下，都是打开或者设置好的，但开机就是弹窗提示输入密码，能正常用，就是很麻烦，每次开机输入两次密码。

v2.0.3 （PS 升级到最新版，点击任务栏里的图标，不显示展开菜单，而是直接就打开仪表盘了，而且 osascript 的开机密码依然在）

<img width="280" alt="Image" src="https://github.com/user-attachments/assets/b2ca9d1d-2c83-4720-ab16-058c7f6c048d" />

**Comment by Drom1145** [comment]
> 还是有这个问题，楼上的方法看了下，都是打开或者设置好的，但是开机就是弹窗提示输入密码，能正常用，就是很麻烦，每次开机输入两次密码。
> 
> v2.0.3 （PS升级到最新版本，点击任务栏里的图标，不显示展开菜单，而是直接打开仪表盘了，而且osascript的开机密码依然在）
> 
> <img alt="图像" width="280" src="https://private-user-images.githubusercontent.com/7479989/421434736-b2ca9d1d-2c83-4720-ab16-058c7f6c048d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE4NjUwODUsIm5iZiI6MTc0MTg2NDc4NSwicGF0aCI6Ii83NDc5OTg5LzQyMTQzNDczNi1iMmNhOWQxZC0yYzgzLTQ3MjAtYWIxNi0wNThjN2Y2YzA0OGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTNUMTExOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2U0NmFiMGY2NThjMDYyODYyMTQzYzk4ODlhMWVkN2Y3NGNlNTJhYzAzYzEyOTY1MDA5ZDY5ZjRhZmI3MTFiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VkpH6niohNe0uvN-9R3xfhsUlWtxYwFpGpEnhzqTHcA"> <img alt="图像" width="473" src="https://private-user-images.githubusercontent.com/7479989/421435083-cdfd4217-5574-4879-989c-b2707ec9b9d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE4NjUwODUsIm5iZiI6MTc0MTg2NDc4NSwicGF0aCI6Ii83NDc5OTg5LzQyMTQzNTA4My1jZGZkNDIxNy01NTc0LTQ4NzktOTg5Yy1iMjcwN2VjOWI5ZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTNUMTExOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzI4Mjg5ZGQ1MGRkMWVmYTdjYjJkMTE3NjE0MGZlYjcwMDhhZWRhY2E3MDA2Y2JkMjg3ZTRjOWM3ZWMyYjBmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ER6jsruC3yRFntsAgW6zLaEP9VFH2JzCNs1tVpjtZpY"> <img alt="图像" width="715" src="https://private-user-images.githubusercontent.com/7479989/421434969-2a25bbef-3820-4ba3-8b30-8881cb7edc2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE4NjUwODUsIm5iZiI6MTc0MTg2NDc4NSwicGF0aCI6Ii83NDc5OTg5LzQyMTQzNDk2OS0yYTI1YmJlZi0zODIwLTRiYTMtOGIzMC04ODgxY2I3ZWRjMmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTNUMTExOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2QxNmQ0YzExYjczZDMxYzYzOTRlMWU5ZGQzMTk0YTgyNmZlNTY3MTcwYjg0YTc5YTBhZDQ3M2M1NzRlYmZmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AKRtwq9eAwL6D1_m9sLMnDKVsMiu6z74FO7f9qrkulc">

自己去开个楼吧，我到现在也没遇到提供不了帮助

**Comment by Forence1999** [comment]
> sudo sfltool dumpbtm

类似的 VPN （mihomo party） 出现了弹窗，开机启动和它下面的允许后台运行中所有相关的权限都给到，就解决了。

感谢感谢～
