### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by morii-water** [clash-verge-rev/clash-verge-rev#219]
### Describe the bug

tun模式问题：
先打开服务模式后（active再）打开tun模式
发现三个问题
1.适配器里未出现虚拟网卡
2.出现断网问题，无法上网
3.无法关闭tun模式，关闭后，切换软件页面后回到设置后发现仍然开启

### To Reproduce

实战没有解决办法或者思路，求助一下

### Platform

Windows

### System Version

win10

### Software Version

谷歌

**Comment by MystiPanda** [comment]
我无法复现，卸载重装一下试试

**Comment by morii-water** [comment]
> 我无法复现，卸载重装一下试试

我所有代理软件开tun模式都没有创建新的虚拟网卡，不知道为什么

**Comment by wonfen** [comment]
如果你用管理员模式运行，可以不用开服务器模式安装虚拟网卡。
服务模式的作用是安装虚拟网卡，可以不用管理员模式运行tun模式。

**Comment by wonfen** [comment]
无更多反馈，关闭。
