### ISSUE TITLE
[BUG] macOS 菜单图标出现在电脑屏幕左上角挡住了系统苹果图标

### ISSUE THREAD

**Issue by Chihpin** [clash-verge-rev/clash-verge-rev#2192]
### 问题描述 / Describe the bug

<img width="143" alt="截屏2024-11-29 10 25 48" src="https://github.com/user-attachments/assets/1225bff5-c719-4bea-b385-9de660d8b26e">

### 软件版本 / Verge Version

最新版 2.0.2

### 复现步骤 / To Reproduce

安装完一启动就是这样

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS Sequoia 15.1.1

### 日志 / Log

无

**Comment by wonfen** [comment]
看文档，常见问题。

**Comment by Tychristine** [comment]
https://www.clashverge.dev/faq/macos.html#macos_1
