### ISSUE TITLE
[BUG] 在Mac 下2.0和2.0.1软件订阅下来没有任何节点

### ISSUE THREAD

**Issue by cheneyxx** [clash-verge-rev/clash-verge-rev#2193]
### 问题描述 / Describe the bug

在Mac 下2.0和2.0.1软件订阅下来没有任何节点 好多台Mac都是这样 1.7.7版本不会这样
![WechatIMG89](https://github.com/user-attachments/assets/3610d41c-91c7-4c2d-a213-37338ee4f72b)

### 软件版本 / Verge Version

Clash.Verge_2.0.1

### 复现步骤 / To Reproduce

重新安装Clash.Verge_2.0.1 订阅成功还是不显示任何节点

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Ventura 13.x

### 日志 / Log

xxx

**Comment by wonfen** [comment]
联系我tg远程看看 https://t.me/wonfen_bot

**Comment by cheneyxx** [comment]
> 联系我tg远程看看 https://t.me/wonfen_bot

这个是妹纸的电脑 已经换回1.7.7版本解决了 但我自己的Mac 使用2.0.1版本订阅下来是正常的 如果我自己的不行到是方便远程

**Comment by Eternal-a** [comment]
缺少文件“clash设置=>应用目录=>**Country.mmdb**”，部分版本自动生成国家ip文件存在bug，该文件可以从1.77版本的相同目录拷贝过来。这里提供一份https://www.123865.com/s/hTvtVv-oecgH供下载。把Country.mmdb放在“clash设置=>应用目录”下即可解决问题。

       Missing file "clash Settings => Application directory =>** country.mmdb **", there is a bug in some versions automatically generating Country ip file, this file can be copied from the same directory in version 1.77. Provide a https://www.123865.com/s/hTvtVv-oecgH for download here. Put Country.mmdb under "clash Settings => App directory" to solve the problem.

**Comment by Eternal-a** [comment]
缺少文件“clash设置=>应用目录=>**Country.mmdb**”，部分版本自动生成国家ip文件存在bug，该文件可以从1.77版本的相同目录拷贝过来。这里提供一份   “https://www.123865.com/s/hTvtVv-oecgH“   供下载。把Country.mmdb放在“clash设置=>应用目录”下即可解决问题。

**Comment by xiaolin2004** [comment]
在设置中，你会发现你的clash内核条目为空，将这个设置之后就会恢复正常。

**Comment by wonfen** [comment]
打开设置-->配置目录 备份 后 删除所有文件 尝试是否正常
