### ISSUE TITLE
[BUG] 导入订阅地址后，代理页面空白

### ISSUE THREAD

**Issue by shuohao** [clash-verge-rev/clash-verge-rev#2194]
### 问题描述 / Describe the bug

导入订阅地址后，代理页面空白
按之前已关闭的issue里的方法，配置目录全部删掉，重装都无法解决

### 软件版本 / Verge Version

2.0.1 2.0.2

### 复现步骤 / To Reproduce

安装就复现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 24H2

### 日志 / Log

日志等级调整debug重启verge，日志等级又回到INFO

这个是service目录下的日志
time="2024-11-29T11:25:41.9584271+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-29T11:25:41.9674139+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-11-29T11:25:41.9674139+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-11-29T11:25:41.9964571+08:00" level=info msg="Initial configuration complete, total time: 33ms"
time="2024-11-29T11:25:41.9972036+08:00" level=error msg="External controller listen error: listen tcp 127.0.0.1:9097: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2024-11-29T11:25:41.9988482+08:00" level=info msg="Sniffer is closed"
time="2024-11-29T11:25:41.9994003+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7897"
time="2024-11-29T11:25:42.0123979+08:00" level=info msg="Start initial Compatible provider 🌏 国内媒体"
time="2024-11-29T11:25:42.0123979+08:00" level=info msg="Start initial Compatible provider SteamGame"
time="2024-11-29T11:25:42.0123979+08:00" level=info msg="Start initial Compatible provider 📲 电报信息"
time="2024-11-29T11:25:42.0123979+08:00" level=info msg="Start initial Compatible provider 🌍 国外媒体"
time="2024-11-29T11:25:42.0123979+08:00" level=info msg="Start initial Compatible provider 🍎 苹果服务"
time="2024-11-29T11:25:42.0123979+08:00" level=info msg="Start initial Compatible provider 🎯 本地直连"
time="2024-11-29T11:25:42.0123979+08:00" level=info msg="Start initial Compatible provider ♻️ 自动选择"
time="2024-11-29T11:25:42.0123979+08:00" level=info msg="Start initial Compatible provider 🔰 节点选择"
time="2024-11-29T11:25:42.0129281+08:00" level=info msg="Start initial Compatible provider default"
time="2024-11-29T11:25:42.0129281+08:00" level=info msg="Start initial Compatible provider 🐟 漏网之鱼"
time="2024-11-29T11:25:42.0140094+08:00" level=info msg="Start initial Compatible provider openAI"
time="2024-11-29T11:25:42.0140094+08:00" level=info msg="Start initial Compatible provider Ⓜ️ 微软服务"

2024-11-29 11:25:41 INFO - try to run core in service mode
2024-11-29 11:25:41 INFO - start service: {"config_dir": "C:\\Users\\shuohao\\AppData\\Roaming\\io.github.clash-verge-rev.clash-verge-rev", "config_file": "C:\\Users\\shuohao\\AppData\\Roaming\\io.github.clash-verge-rev.clash-verge-rev\\clash-verge.yaml", "log_file": "C:\\Users\\shuohao\\AppData\\Roaming\\io.github.clash-verge-rev.clash-verge-rev\\logs\\service\\2024-11-29-1125.log", "bin_path": "C:\\Users\\shuohao\\AppData\\Local\\Programs\\Clash Verge\\verge-mihomo.exe", "core_type": "verge-mihomo"}
2024-11-29 11:25:41 ERROR - runtime error: failed to receive message from webview

**Comment by wonfen** [comment]
说明你的配置有问题啊，用我们推荐的机场订阅试试。

**Comment by shuohao** [comment]
> > 说明你的配置有问题啊，用我们推荐的机场订阅试试。
> 
> 问题是1.7.7版本就是正常的 2.0 2.0.1 部分Mac订阅下来节点也是一片空白

我之前1.7.7用的一直好好的，然后升级到2.0再降回1.7.7也不行了

**Comment by wonfen** [comment]
> > 说明你的配置有问题啊，用我们推荐的机场订阅试试。
> 
> 问题是1.7.7版本就是正常的 2.0 2.0.1 部分Mac订阅下来节点也是一片空白

1.7和2.0没有可比性，1.7没有安装服务。联系我tg 远程看看 https://t.me/wonfen_bot

**Comment by shuohao** [comment]
> > > 说明你的配置有问题啊，用我们推荐的机场订阅试试。
> > 
> > 
> > 问题是1.7.7版本就是正常的 2.0 2.0.1 部分Mac订阅下来节点也是一片空白
> 
> 1.7和2.0没有可比性，1.7没有安装服务。联系我tg 远程看看 https://t.me/wonfen_bot

没有tg，注册不上   其他的远程软件可以么

**Comment by lifei6671** [comment]
看下你的规则部分是不是没有用双引号括起来，我的就是规则部分有问题。

**Comment by travisbikkle** [comment]
同样的问题

版本：2.0.2
操作系统：fedora 41

![image](https://github.com/user-attachments/assets/25fae226-05c7-416e-b843-31576ab27514)

**Comment by wonfen** [comment]
> 同样的问题
> 
> 版本：2.0.2 操作系统：fedora 41
> 
> ![image](https://private-user-images.githubusercontent.com/15191577/391107001-25fae226-05c7-416e-b843-31576ab27514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4OTk4MjYsIm5iZiI6MTczMjg5OTUyNiwicGF0aCI6Ii8xNTE5MTU3Ny8zOTExMDcwMDEtMjVmYWUyMjYtMDVjNy00MTZlLWI4NDMtMzE1NzZhYjI3NTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDE2NTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzODU3MGEyODYwMjllNTliMjc0MWMyZWY5OWQ2ZDMxYThhMTQ4NDE5Y2MyMzkyMmJmMjBkNTMyMjUzZTM4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QW18QO1LvWiZIYXJmRS_-zxqCLWKviuLI-PkfVgW3XQ)

使用出现异常的，打开设置-->配置目录 备份 后 删除所有文件 尝试是否正常

**Comment by pmkm** [comment]
我在昨天修改了外部控制器监听地址，今天出现了类似的问题。修改回来后恢复正常了。

**Comment by Tychristine** [comment]
@pmkm GUI需要`external-controller` 与内核通信，因此它的值必须始终为"9097"

**Comment by Eternal-a** [comment]
缺少文件“clash设置=>应用目录=>Country.mmdb”，部分版本自动生成国家ip文件存在bug，该文件可以从1.77版本的相同目录拷贝过来。这里提供一份 “[https://www.123865.com/s/hTvtVv-oecgH“](https://www.123865.com/s/hTvtVv-oecgH%E2%80%9C) 供下载。把Country.mmdb放在“clash设置=>应用目录”下即可解决问题

**Comment by shuohao** [comment]
> 缺少文件“clash设置=>应用目录=>Country.mmdb”，部分版本自动生成国家ip文件存在bug，该文件可以从1.77版本的相同目录拷贝过来。这里提供一份 “[https://www.123865.com/s/hTvtVv-oecgH“](https://www.123865.com/s/hTvtVv-oecgH%E2%80%9C) 供下载。把Country.mmdb放在“clash设置=>应用目录”下即可解决问题

牛啊，解决了

**Comment by shuohao** [comment]
Eternal-a 大神说的是正解

**Comment by yepGreat** [comment]
Eternal-a 大佬nb！
我来说说我的情况，ubuntu22.04lts 一直用1.7.7版本没问题，但不知道怎么突然抽风了，代理页面空白，重启电脑也不行，按照大佬所说替换掉这个文件就恢复正常了！再次感谢大佬！

**Comment by Frank-Jiajun-SUN** [comment]
> 缺少文件“clash设置=>应用目录=>Country.mmdb”，部分版本自动生成国家ip文件存在bug，该文件可以从1.77版本的相同目录拷贝过来。这里提供一份 “[https://www.123865.com/s/hTvtVv-oecgH“](https://www.123865.com/s/hTvtVv-oecgH%E2%80%9C) 供下载。把Country.mmdb放在“clash设置=>应用目录”下即可解决问题

现在的分享链接显示失效了，大神是否可以再分享一下
