### ISSUE TITLE
[BUG] macos开机启动项的软件名称是‘won fen'

### ISSUE THREAD

**Issue by wjx0912** [clash-verge-rev/clash-verge-rev#2196]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/20504fde-8263-4f9b-a684-71b8e16ef9fe)

折腾了半天才知道是clash。希望能改成clash名称

### 软件版本 / Verge Version

如图

### 复现步骤 / To Reproduce

如图

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.7

### 日志 / Log

如图

**Comment by wonfen** [comment]
改不了，这是mac开发者账号注册的时候固定下来的。
