### ISSUE TITLE
实验性支持开源的clash-rs内核

### ISSUE THREAD

**Issue by Jordan-Haidee** [clash-verge-rev/clash-verge-rev#2199]
### 功能描述 / Feature description

在内核选择配置中，提供可选的clash-rs开源内核支持。

### 使用场景 / Use case

clash已经不再维护，继任者mihomo不再开源，透明性和安全性让人担忧，支持使用开源的内核可选项，如clash-rs，可以改善这个状况。

经过长时间的发展，clash-rs已经支持了Shadowsocks/Trojan/Vmess，可以满足日常场景的使用。

**Comment by BBplux** [comment]
mihomo不再开源是哪里来的消息

**Comment by Jordan-Haidee** [comment]
> mihomo不再开源是哪里来的消息
> 

Github上的mihomo放的好像只是一个壳子和releases，没有源码

**Comment by Tychristine** [comment]
@Jordan-Haidee 逆天，源码不是在Alpha branch吗

**Comment by Jordan-Haidee** [comment]
不好意思没注意到哈哈，藏的挺深😂
