### ISSUE TITLE
[BUG] 新版2.01在macos下会让host失效，host管理软件为switchhosts，即使设置了dns enable 为false

### ISSUE THREAD

**Issue by yongjieding** [clash-verge-rev/clash-verge-rev#2200]
### 问题描述 / Describe the bug

host管理软件为switchhosts，在v1.7的clash verge下就没有这个问题，正常切换host都正常。2.01就不行。

### 软件版本 / Verge Version

v2.0.1

### 复现步骤 / To Reproduce

switchhosts设置host，v2.01的verge编辑订阅文件信息，将dns下的enable设置为false

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1 (24B91)

### 日志 / Log

日志缺失，回退了版本

**Comment by wonfen** [comment]
检查当前配置dns下中是否有 
use-system-hosts: false

**Comment by wonfen** [comment]
无反馈，关闭。有新问题重发issue
