### ISSUE TITLE
[BUG] win11升级软件报错：Update.install called before Update.download

### ISSUE THREAD

**Issue by windExplorer** [clash-verge-rev/clash-verge-rev#2201]
### 问题描述 / Describe the bug

无法更新软件。
在更新界面点击更新会报错：Update.install called before Update.download
![image](https://github.com/user-attachments/assets/34e008f1-c94e-4dff-9311-0577fe22e7c9)

### 软件版本 / Verge Version

v2.0.0-rc.5
![image](https://github.com/user-attachments/assets/76ed588e-1efe-4014-a3cb-5047f20e1066)

### 复现步骤 / To Reproduce

1. 发现左上角logo有个new标记，点击new打开更新面板
2. 点击面板右下角更新
3. 右上角弹出错误信息
4. 重启多次，包括管理员启动再操作也是一样。开关代理服务操作也是一样。
![image](https://github.com/user-attachments/assets/0a539cce-720e-43b6-9ffd-ae5ab858d279)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11专业版, 24H2, 26120.2415

### 日志 / Log

[2024-11-29-1541 - 副本.zip](https://github.com/user-attachments/files/17955918/2024-11-29-1541.-.zip)

**Comment by Tychristine** [comment]
@windExplorer 请阅读发行说明

**Comment by windExplorer** [comment]
原来如此，2.0.1修复了
