### ISSUE TITLE
[BUG] 【TUN 模式虚拟网卡】共享网络【热点网卡】网速慢

### ISSUE THREAD

**Issue by ArsenicX** [clash-verge-rev/clash-verge-rev#2205]
### 问题描述 / Describe the bug

【TUN 模式虚拟网卡】共享网络【热点网卡】网速慢

其实有两个问题

问题 1. 【TUN 模式虚拟网卡】和【热点网卡】同时开启会导致其中后开启的网卡失效无法联网。但是可以通过[这条回复](https://github.com/clash-verge-rev/clash-verge-rev/issues/335#issuecomment-1998778438)不能算解决，感觉像是避开了这个问题

问题 2. 然后就导致了第二个问题，将【TUN 模式虚拟网卡】共享网络给【热点网卡】网速会慢很多。<br>家里面是 100M 的网，win11 开 TUN 模式的速度和不开 TUN 分享热点给其他设备后其他设备的速度都能跑满，但是通过[这条回复](https://github.com/clash-verge-rev/clash-verge-rev/issues/335#issuecomment-1998778438)操作之后，连接 win11 热点的其他设备的速度就只有 不到30M 了

### 软件版本 / Verge Version

Clash Verge：v2.0.1

### 复现步骤 / To Reproduce

问题 1 步骤：
win11 开启了 tun 模式之后可以正常上网，再开启热点共享网络出去，连接热点的设备无法上网；反之依然，先把热点共享出去，连接热点的设备可以上网，再开 tun 模式本机无法上网（全局直连模式下，不被配置影响）

问题 2 步骤：
先开启tun模式，然后共享热点，然后把 tun 网卡分享给热点网卡，本机和连接热点的设备都可以上网，连接热点的设备的流量也能被 clash 接管。但是网速很慢（全局直连模式下，不被配置影响）

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 Pro 23H2

### 日志 / Log

⁡

**Comment by Tychristine** [comment]
这是GUI问题还是Mihomo内核问题？

**Comment by ArsenicX** [comment]
> 这是GUI问题还是Mihomo内核问题？

具体我不太懂，不知道...
我猜测应该不是 GUI 的问题

**Comment by wonfen** [comment]
建议检查一下路由规则，不懂最好就不要用这种特殊场景。

**Comment by ArsenicX** [comment]
> 建议检查一下路由规则，不懂最好就不要用这种特殊场景。

大佬，我检查了路由表，是正常的没有发现问题。
之所以采用这种特殊连接是因为公司打印机和网线一个网段，Wi-Fi设备没办法使用；然后多台设备又有互相访问的需求，设备连了打印机有会导致和其他设备网段不同没法访问，很麻烦...

所以才不得不请教下，我的这个使用方式，削减网速是正常现象还是其他原因😭

**Comment by psk107520** [comment]
出现一样的问题了，win11开启热点后，直接就断网
