### ISSUE TITLE
[BUG] prepend-rules语法规则无效

### ISSUE THREAD

**Issue by SammySnake-d** [clash-verge-rev/clash-verge-rev#2206]
### 问题描述 / Describe the bug

使用prepend-rules设置前置规则，规则不生效

![image](https://github.com/user-attachments/assets/9b71b942-afa6-408b-b192-257e0e3a3e46)

![image](https://github.com/user-attachments/assets/6a43475a-4531-4eda-af24-51f333e1a074)

规则日志中没有adobe.com,reject规则。

查看了使用文档，发现prepend-rules规则还未弃用

![image](https://github.com/user-attachments/assets/33ff09a3-ea5f-4873-96bb-73770342bf25)

### 软件版本 / Verge Version

v2.01版本

### 复现步骤 / To Reproduce

配置prepend-rules；

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

不需要日志

**Comment by Tychristine** [comment]
不再支持**历史功能**，已更新到**Global Extend Config**与**Global Extend Script**

**Comment by SammySnake-d** [comment]
> 不再支持**历史功能**，已更新到**Global Extend Config**与**Global Extend Script**

@Tychristine 您好，那么我如果想全局使用除了在global config里面复制完整rules的情况下再前面添加新rules
或者给每一个订阅都手动进行图形化导入是吗？

**Comment by Tychristine** [comment]
@SammySnake-d 
Yes.
