### ISSUE TITLE
[BUG] 所有节点全部显示error

### ISSUE THREAD

**Issue by NereeScarlet** [clash-verge-rev/clash-verge-rev#2207]
### 问题描述 / Describe the bug

如题，在导入订阅之后，所有节点全部显示error，且无法使用。
![image](https://github.com/user-attachments/assets/574d6dc4-f587-436a-aebe-b153b71f6d1c)
相同订阅下clash tor win中节点全部正常，因此可以确定并非是订阅、节点本身的问题。
![image](https://github.com/user-attachments/assets/a05c2a34-5862-4147-bfce-bbafdd50f6f0)

### 软件版本 / Verge Version

稳定版2.0.1以及alpha版本2.0.2全部都尝试过了，都有着相同的问题。

### 复现步骤 / To Reproduce

导入订阅，前往节点页面，所有节点全部error

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

[2024-11-29-2247.log](https://github.com/user-attachments/files/17960653/2024-11-29-2247.log)
[2024-11-29-2247.log](https://github.com/user-attachments/files/17960657/2024-11-29-2247.log)
[2024-11-29-2246.log](https://github.com/user-attachments/files/17960661/2024-11-29-2246.log)
[2024-11-29-2242.log](https://github.com/user-attachments/files/17960662/2024-11-29-2242.log)
[2024-11-29-2246.log](https://github.com/user-attachments/files/17960663/2024-11-29-2246.log)
[2024-11-29-2242.log](https://github.com/user-attachments/files/17960664/2024-11-29-2242.log)

**Comment by Tychristine** [comment]
@NereeScarlet 配置写太烂

**Comment by NereeScarlet** [comment]
> @NereeScarlet 配置写太烂

抱歉我有点没听明白。
是说我这边问题提交的不够详细，缺了什么需要提的信息。
还是说机场提供的订阅本身有问题呀

**Comment by Tychristine** [comment]
@NereeScarlet 单纯是你的配置没写好，甚至日志都只提供无用的GUI日志

**Comment by NereeScarlet** [comment]
> @NereeScarlet 单纯是你的配置没写好，甚至日志都只提供无用的GUI日志

哦哦哦，我的错误。请问配置是指这个部分吗？
`port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: false
mode: Rule
log-level: info
ipv6: false
hosts:
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  use-hosts: true
  default-nameserver:
    - 119.28.28.28
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
  nameserver:
    - 119.28.28.28
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
  fallback:
    - https://dns.pub/dns-query
    - https://doh.pub/dns-query
    - https://doh.apad.pro/dns-query
    - https://dns.alidns.com/dns-query
    - tls://dns.pub:853
    - tls://dot.pub:853
    - tls://dns.alidns.com:853
    - 119.28.28.28
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 233.252.0.0/24
      - 240.0.0.0/4
      - 255.255.255.255/32
      - ::/128
      - ::1/128
      - fc00::/7
      - fe80::/10
      - ff00::/8
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - stun.*.*
    - stun.*.*.*
    - swscan.apple.com
    - mesu.apple.com
    - music.163.com
    - '*.music.163.com'
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - y.qq.com
    - '*.y.qq.com'
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - localhost.ptlogin2.qq.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - music.migu.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - '*.*.*.srv.nintendo.net'
    - '*.*.stun.playstation.net'
    - xbox.*.*.microsoft.com
    - '*.*.xboxlive.com'
    - '*.ipv6.microsoft.com'
    - teredo.*.*.*
    - teredo.*.*
    - speedtest.cros.wr.pvp.net
    - +.jjvip8.com
    - www.douyu.com
    - activityapi.huya.com
    - activityapi.huya.com.w.cdngslb.com
    - www.bilibili.com
    - api.bilibili.com
    - a.w.bilicdn1.com
external-controller: 127.0.0.1:9090
clash-for-android:
  append-system-dns: false
profile:
  tracing: true
sniffer:
  sniff:
    TLS: {ports: [0-65535], override-destination: true}
    HTTP: {ports: [0-65535], override-destination: true}
    QUIC: {ports: [0-65535], override-destination: true}
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
 `

**Comment by NereeScarlet** [comment]
> @NereeScarlet 单纯是你的配置没写好，甚至日志都只提供无用的GUI日志

日志的话请问是‘service’文件夹里面的那部分文件吗？
我是按照日志那栏的说明将日志目录之中的文件以及该文件夹中‘service’文件夹内的文件提交了

**Comment by NereeScarlet** [comment]
> @NereeScarlet缺点是你的配置没写好，甚至日志都只提供无用的GUI日志

万分抱歉，我对这方面不是很了解orz

**Comment by Tychristine** [comment]
@NereeScarlet DNS解析不到代理域名导致的

**Comment by NereeScarlet** [comment]
> @NereeScarlet DNS解析不到代理域名导致的

那请问这种情况下我应该做些什么呢。
非常抱歉，我对于网络确实不是很了解QAQ

**Comment by Henry-Sky** [comment]
我也遇到一样的问题了，KDE Debian12 安装clash-verge amd64 2.0.2 .deb，用和另一台windows笔记本上clash for windows一样的配置文件，windows电脑的clash for windows可以正常ping通节点，这台debian的电脑用clash-verge就不行。
