### ISSUE TITLE
[BUG]windows的问题

### ISSUE THREAD

**Issue by lxtx528** [clash-verge-rev/clash-verge-rev#221]
### Describe the bug

在软件里更新新版本后订阅就没有了，无法覆盖，需要重新导入，mac没有这个问题。

### To Reproduce

在软件里更新新版本后订阅就没有了，无法覆盖，需要重新导入，mac没有这个问题。

### Platform

Windows

### System Version

win10

### Software Version

w in10

**Comment by Skywol** [comment]
我也出现这个问题，我还以为是用的便携版本，更新后默认安装C盘，读取不到原始配置的原因。

**Comment by MystiPanda** [comment]
便携版不支持应用内更新

**Comment by wonfen** [comment]
便携版请直接下载覆盖。
