### ISSUE TITLE
google chrome翻译不好用, 怎么解决?    我已经增加了配置项,  一直不好用

### ISSUE THREAD

**Issue by sxstd001** [clash-verge-rev/clash-verge-rev#2211]
### 功能描述 / Feature description

google chrome翻译不好用, 怎么解决?    我已经增加了配置项,  一直不好用
![屏幕截图 2024-11-30 001057](https://github.com/user-attachments/assets/bc4f943a-3409-4ad1-81bf-9f317b777118)

### 使用场景 / Use case

建议把google chrome翻译默认加入代理中, 这个是常用功能,.

**Comment by Tychristine** [comment]
#1217

**Comment by Tychristine** [comment]
#2209

**Comment by sxstd001** [comment]
> #2209

thanks, 已解决!
