### ISSUE TITLE
[Feature] 希望自定义托盘图标能区分黑色和白色

### ISSUE THREAD

**Issue by asakimio** [clash-verge-rev/clash-verge-rev#2213]
### 功能描述 / Feature description

我使用Mac版本。新版中似乎开放了托盘图标自定义功能，但Mac状态栏是会改变白或黑色的，希望自定义图标能区分托盘白色或黑色主题。

### 使用场景 / Use case

但我也想到，Mac的状态栏的黑白色是根据壁纸改变的，而不是系统的主题设定，可能需要单独的实现逻辑。
实际上我的需求是比较喜欢1.5版本的托盘图标，希望能有选项可以直接更换为经典图标。

**Comment by wonfen** [comment]
非核心功能不准备实现，目前已经满足了所以壁纸变换黑白的功能

**Comment by wonfen** [comment]
已完成。
