### ISSUE TITLE
[Feature] 订阅文件配置详细报错

### ISSUE THREAD

**Issue by ryan-web-dev** [clash-verge-rev/clash-verge-rev#2214]
### 功能描述 / Feature description

配置文件错误时可以具体提示错误，和之前版本一致，而不是返回status 400

### 使用场景 / Use case

编辑配置文件后，使用配置文件，提示失败 status 400，但是不知道在哪里报错，不好定位。之前的版本有这个功能。

**Comment by Tychristine** [comment]
右键编辑文件，查看语法错误。
或者使用Microsoft Visual Studio Code安装YAML扩展，直接检查语法错误

**Comment by sususu98** [comment]
遇到了相同的问题，希望从新打开这个issue
我最后是通过直接从命令行启动内核定位到的问题，可以考虑报错的时候带相应的error报错（或者可以从service的log中看到对应的报错）。
> level=fatal msg="Parse config error: loop is detected in ProxyGroup, please check following ProxyGroups: [xxx yyy zzz]"

**Comment by Tychristine** [comment]
@sususu98 
你的问题也是自己的配置写错，一般情况下照抄[内核文档](https://wiki.metacubex.one/config/general)给的字段都不太可能错误
 
### 关于你说的展示相应的报错信息
[Clash Mihomo](https://wiki.metacubex.one/api/#configs)没有提供这个功能
API `/configs?force=ture`
Response Head : http code `400`
Response Body:
```json
{
  "message": "Body invalid"
}
```

**Comment by sususu98** [comment]
是的，确实是我的配置写错了，但是具体的错误是出现了loop，一般这种问题写配置的时候不容易被发现。。。
Clash Mihomo的API确实没有提供相应的接口。我想表达的意思是，Clash Verge Rev在启动的内核的时候，应该能够拿到对应的报错，比如我的启动命令是这样的
```shell
 .\verge-mihomo.exe -d C:\Users\sususu\Downloads\
time="2024-12-23T10:47:09.4443295+08:00" level=info msg="Start initial configuration in progress"
time="2024-12-23T10:47:09.4527481+08:00" level=fatal msg="Parse config error: loop is detected in ProxyGroup, please check following ProxyGroups: [jp1 cfproxy 节点选择]"
```
这样会有 `fatal` 级别的报错信息，如果Clash Verge Rev 可以把这样的log记录一下，感觉出错了的话比较容易定位问题。

**Comment by wonfen** [comment]
> 是的，确实是我的配置写错了，但是具体的错误是出现了loop，一般这种问题写配置的时候不容易被发现。。。 Clash Mihomo的API确实没有提供相应的接口。我想表达的意思是，Clash Verge Rev在启动的内核的时候，应该能够拿到对应的报错，比如我的启动命令是这样的
> 
> ```shell
>  .\verge-mihomo.exe -d C:\Users\sususu\Downloads\
> time="2024-12-23T10:47:09.4443295+08:00" level=info msg="Start initial configuration in progress"
> time="2024-12-23T10:47:09.4527481+08:00" level=fatal msg="Parse config error: loop is detected in ProxyGroup, please check following ProxyGroups: [jp1 cfproxy 节点选择]"
> ```
> 
> 这样会有 `fatal` 级别的报错信息，如果Clash Verge Rev 可以把这样的log记录一下，感觉出错了的话比较容易定位问题。

试试2.0.3，应该会在UI提示；如果没有请反馈下

**Comment by wkABXY** [comment]
真的好难排查 ，语法也没错啊，

**Comment by Tychristine** [comment]
@wkABXY 在dev分支最新版本中新增了对重载配置文件"400"时响应更多信息

**Comment by sususu98** [comment]
> 真的好难排查 ，语法也没错啊，
如果不想用dev分支，你也可以试试直接用内核调用对应的配置文件，能看到报错更详细的信息。
