### ISSUE TITLE
[BUG] google浏览器不开启Tun模式无法访问外网

### ISSUE THREAD

**Issue by erxiaoouba** [clash-verge-rev/clash-verge-rev#2218]
### 问题描述 / Describe the bug

只开启系统代理无法连接外网, 只有开启Tun模式才行, 但是点击测试google是可以的

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

选择代理, 然后开启系统代理
再选择Tun模式开启

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows10 22H2

### 日志 / Log

time="2024-11-30T14:41:43.3821781+08:00" level=info msg="[TCP] 198.18.0.1:4318 --> hqnac.cofco.com:80 match Match using ⭕ proxinode[US_speednode_0032]"
time="2024-11-30T14:41:45.2119306+08:00" level=warning msg="[TCP] dial DIRECT (match IPCIDR/10.0.0.0/8) 198.18.0.1:4300 --> 10.25.8.3:6788 error: connect failed: dial tcp 10.25.8.3:6788: i/o timeout"
time="2024-11-30T14:41:45.2550445+08:00" level=info msg="[UDP] 198.18.0.1:55324 --> 10.8.255.1:36533 match IPCIDR(10.0.0.0/8) using DIRECT"
time="2024-11-30T14:41:47.2638086+08:00" level=warning msg="[TCP] dial DIRECT (match IPCIDR/10.0.0.0/8) 198.18.0.1:4310 --> 10.8.255.1:37527 error: connect failed: dial tcp 10.8.255.1:37527: i/o timeout"
time="2024-11-30T14:41:48.5537175+08:00" level=info msg="[TCP] 198.18.0.1:4322 --> checkappexec.microsoft.com:443 match DomainSuffix(microsoft.com) using DIRECT"
time="2024-11-30T14:41:49.3000923+08:00" level=info msg="[TCP] 198.18.0.1:4335 --> hqnac.cofco.com:80 match Match using ⭕ proxinode[US_speednode_0032]"
time="2024-11-30T14:41:52.3068411+08:00" level=warning msg="[TCP] dial DIRECT (match IPCIDR/10.0.0.0/8) 198.18.0.1:4320 --> 10.8.255.1:37527 error: connect failed: dial tcp 10.8.255.1:37527: i/o timeout"
time="2024-11-30T14:41:54.8658744+08:00" level=warning msg="[TCP] dial DIRECT (match IPCIDR/10.0.0.0/8) 198.18.0.1:4339 --> 10.25.8.3:5688 error: connect failed: dial tcp 10.25.8.3:5688: i/o timeout"
time="2024-11-30T14:41:55.7011521+08:00" level=info msg="[TCP] 198.18.0.1:4345 --> hqnac.cofco.com:80 match Match using ⭕ proxinode[US_speednode_0032]"
time="2024-11-30T14:41:57.3707434+08:00" level=warning msg="[TCP] dial DIRECT (match IPCIDR/10.0.0.0/8) 198.18.0.1:4341 --> 10.8.255.1:37527 error: connect failed: dial tcp 10.8.255.1:37527: i/o timeout"
time="2024-11-30T14:41:58.120187+08:00" level=info msg="[UDP] 198.18.0.1:57590 --> 10.8.255.1:36533 match IPCIDR(10.0.0.0/8) using DIRECT"
time="2024-11-30T14:42:00.8089763+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-30T14:42:00.8125063+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-11-30T14:42:00.8125063+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-11-30T14:42:00.8264592+08:00" level=info msg="Initial configuration complete, total time: 17ms"
time="2024-11-30T14:42:00.8287843+08:00" level=info msg="Sniffer is closed"
time="2024-11-30T14:42:01.0432429+08:00" level=info msg="Start initial Compatible provider default"
time="2024-11-30T14:42:01.0432429+08:00" level=info msg="Start initial Compatible provider ♻️ automatic"
time="2024-11-30T14:42:01.0432429+08:00" level=info msg="Start initial Compatible provider ⭕ proxinode"
time="2024-11-30T14:42:01.5908017+08:00" level=warning msg="[TCP] dial DIRECT (match IPCIDR/10.0.0.0/8) 198.18.0.1:4355 --> 10.25.8.3:6788 error: connect failed: dial tcp 10.25.8.3:6788: i/o timeout"
time="2024-11-30T14:42:01.6587283+08:00" level=warning msg="[TCP] dial DIRECT (match IPCIDR/10.0.0.0/8) 198.18.0.1:4357 --> 10.25.8.3:6788 error: connect failed: dial tcp 10.25.8.3:6788: i/o timeout"
time="2024-11-30T14:42:02.4227881+08:00" level=warning msg="[TCP] dial DIRECT (match IPCIDR/10.0.0.0/8) 198.18.0.1:4359 --> 10.8.255.1:37527 error: connect failed: dial tcp 10.8.255.1:37527: i/o timeout"
time="2024-11-30T14:42:03.3183374+08:00" level=warning msg="[TCP] dial DIRECT (match IPCIDR/10.0.0.0/8) 198.18.0.1:4361 --> 10.25.8.3:6788 error: connect failed: dial tcp 10.25.8.3:6788: i/o timeout"
time="2024-11-30T14:42:03.6799945+08:00" level=warning msg="[TCP] dial DIRECT (match IPCIDR/10.0.0.0/8) 198.18.0.1:4367 --> 10.25.8.3:6788 error: connect failed: dial tcp 10.25.8.3:6788: i/o timeout"
time="2024-11-30T14:42:04.7982627+08:00" level=warning msg="[TCP] dial DIRECT (match IPCIDR/10.0.0.0/8) 198.18.0.1:4369 --> 10.25.8.3:6788 error: connect failed: dial tcp 10.25.8.3:6788: i/o timeout"
time="2024-11-30T14:42:05.6964253+08:00" level=warning msg="[TCP] dial DIRECT (match IPCIDR/10.0.0.0/8) 198.18.0.1:4375 --> 10.25.8.3:6788 error: connect failed: dial tcp 10.25.8.3:6788: i/o timeout"
time="2024-11-30T14:42:14.2409769+08:00" level=info msg="[TCP] 127.0.0.1:2709 --> clientservices.googleapis.com:443 match DomainKeyword(google) using ⭕ proxinode[US_speednode_0032]"
time="2024-11-30T14:42:29.7294797+08:00" level=info msg="[TCP] 127.0.0.1:2731 --> go.microsoft.com:443 match DomainSuffix(microsoft.com) using DIRECT"
time="2024-11-30T14:42:43.0599659+08:00" level=info msg="[TCP] 127.0.0.1:2753 --> www.apple.com:443 match DomainSuffix(apple.com) using DIRECT"
time="2024-11-30T14:42:44.1350962+08:00" level=info msg="[TCP] 127.0.0.1:2755 --> www.google.com:443 match DomainKeyword(google) using ⭕ proxinode[US_speednode_0032]"
time="2024-11-30T14:43:14.6340865+08:00" level=info msg="[TCP] 127.0.0.1:2788 --> clients4.google.com:443 match DomainKeyword(google) using ⭕ proxinode[US_speednode_0032]"
time="2024-11-30T14:43:50.6449769+08:00" level=info msg="[TCP] 127.0.0.1:2840 --> go.microsoft.com:443 match DomainSuffix(microsoft.com) using DIRECT"

**Comment by wonfen** [comment]
检查代理设置
