### ISSUE TITLE
[Feature] 能不能增加不带GUI界面的版本。想部署在树莓派上。

### ISSUE THREAD

**Issue by J-Sai** [clash-verge-rev/clash-verge-rev#2219]
### 功能描述 / Feature description

在无界面的树莓派服务器版本的树莓派上部署。

### 使用场景 / Use case

树莓派或Linux服务器使用

**Comment by WenzeJin** [comment]
可以直接使用 clash-for-linux

**Comment by iaw-dlay** [comment]
#1696
