### ISSUE TITLE
[BUG] 每次更新完都会出现一个版本，并没有替换掉旧版本

### ISSUE THREAD

**Issue by hunshimowang6** [clash-verge-rev/clash-verge-rev#2220]
### 问题描述 / Describe the bug

[BUG] 每次更新完都会出现一个版本，并没有替换掉旧版本

### 软件版本 / Verge Version

旧版 1.7.7
新版 2.0.1

### 复现步骤 / To Reproduce

下载旧版本后更新即可触发

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11

### 日志 / Log

...

**Comment by wonfen** [comment]
手动完全删除1.7，再安装新版。
