### ISSUE TITLE
[BUG]  Clash Verge窗口关闭后，WebView2管理器仍在运行，若开启流量图显，将一直占用小部分cpu、gpu利用率

### ISSUE THREAD

**Issue by siadlu** [clash-verge-rev/clash-verge-rev#2221]
### 问题描述 / Describe the bug

2.0版本打开Clash Verge窗口再关闭后，在任务管理器里能看到WebView2管理器仍在运行，我在1.7版本没有遇到。
同时若在界面设置里开启流量图显，WebView2管理器会在后台一直占用小部分cpu、gpu利用率。

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

同上

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

24H2

### 日志 / Log

.

**Comment by Tychristine** [comment]
# 发行说明
## NOTICE
- 因 Tauri 2.0 底层 bug，关闭窗口后保留webview进程，优点是再次打开面板更快，缺点是内存使用略有增加

**Comment by varnbu** [comment]
> # 发行说明
> ## NOTICE
> * 因 Tauri 2.0 底层 bug，关闭窗口后保留webview进程，优点是再次打开面板更快，缺点是内存使用略有增加

有什么办法临时关闭吗
