### ISSUE TITLE
[BUG] 扩展配置下：1. dns模块ipv6: false不生效、2. 重写rule-provides，会和机场的追加在一起，而不是重写

### ISSUE THREAD

**Issue by ttyy33** [clash-verge-rev/clash-verge-rev#2222]
### 问题描述 / Describe the bug

tun模式下（扩展配置重写）：
1. dns模块ipv6: false不生效，查看配置文件ipv6还是为true
2. 重写rule-provides，会和机场的追加在一起，而不是重写

### 软件版本 / Verge Version

v2.0.1

### 复现步骤 / To Reproduce

打开扩展配置
1. dns模块重写ipv6: false
2. rule-provides重写

重新激活订阅，查看运行配置文件：
1. dns模块下的ipv6 还是为 true
2. 自己写的rule- provides规则，会在机场的最后面

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Microsoft Windows [版本 10.0.22631.4460]

### 日志 / Log

/

**Comment by wonfen** [comment]
2.0.2修复了
