### ISSUE TITLE
[BUG] 测试界面添加的网站显示timeout，实际可以连接该网站

### ISSUE THREAD

**Issue by meihus** [clash-verge-rev/clash-verge-rev#2223]
### 问题描述 / Describe the bug

https://chatgpt.com/在测试界面加上这个网站，测试的时候显示timeout，实际上可以连接该网站；

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

新建测试地址https://chatgpt.com/，点击测试显示为timeout，实际chorme可以打开正常使用；

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 Version 22H2

### 日志 / Log

[Uploading 2024-11-28-2140.log…]()

**Comment by wonfen** [comment]
什么都没有
