### ISSUE TITLE
[BUG] 升级到 V2.0.1 后状态栏图标缺少开启代理的显示

### ISSUE THREAD

**Issue by YorKKnight** [clash-verge-rev/clash-verge-rev#2224]
### 问题描述 / Describe the bug

[BUG] 升级到 V2.0.1 后状态栏图标缺少开启代理的显示。
平台：Windows、macOS
详细问题：老版本开启系统代理后，猫猫头🐱图标会在额头上出现一个 S，升级到最新版后，这个特征反而丢失了，导致不能一眼看出当前代理的启动状态。

### 软件版本 / Verge Version

V2.0.1 Mac 和 Win 双平台

### 复现步骤 / To Reproduce

老版本开启系统代理后，猫猫头🐱图标会在额头上出现一个 S，升级到最新版后，这个特征反而丢失了，导致不能一眼看出当前代理的启动状态。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows10

### 日志 / Log

无

**Comment by Tychristine** [comment]
Try version 2.0.2
