### ISSUE TITLE
[BUG] macos系统下v2.0.1 托盘图标无法配置为单色

### ISSUE THREAD

**Issue by zhuyjan** [clash-verge-rev/clash-verge-rev#2228]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/91f24c34-45ca-4265-96a1-b76615a11bc8)
![image](https://github.com/user-attachments/assets/ebe0114b-b7cf-459c-94d1-abcc17d8b77c)

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

设置 ---> 界面设置 ---> 托盘图标：单色图标 ---> 常规托盘图标、系统代理托盘图标、Tun模式托盘图标：选择作者仓库给定的 PNG 图标
上一版本征程，更新后只能显示为黑色。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

macOS 15.0.1

### 日志 / Log

无

**Comment by kowyo** [comment]
v2.0.2 仍然存在此问题

![image](https://github.com/user-attachments/assets/dfacd41d-9f7f-4d7d-a16f-1b30d5b0e96e)

**Comment by zhuyjan** [comment]
更新到2.0.2已解决
![image](https://github.com/user-attachments/assets/f6e51431-cf70-4ae6-861f-f1363ab9a76b)

**Comment by kowyo** [comment]
@zhuyjan 可以提供你的 png 给我测试吗
