### ISSUE TITLE
[BUG] V2 编辑规则功能不能使用，代理策略仅有DIRECT选项

### ISSUE THREAD

**Issue by rnylx** [clash-verge-rev/clash-verge-rev#2230]
### 问题描述 / Describe the bug

编辑规则功能不能使用，代理策略仅有DIRECT选项

### 软件版本 / Verge Version

v2.0.1 v2.0.2

### 复现步骤 / To Reproduce

![屏幕截图 2024-12-01 115205](https://github.com/user-attachments/assets/a86ef070-66d2-40e8-a6b5-1575869bf0c9)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

**Comment by yslin1995** [comment]
![Image](https://github.com/user-attachments/assets/360704b6-140b-4f19-bb44-7e19559e6d5b)

Verge版本 v2.4.2 问题依然存在 @rnylx

**Comment by Dragon1573** [comment]
@yslin1995 尝试升级 [`v2.4.3+autobuild`](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/autobuild) 。

<img width="768" height="485" alt="Image" src="https://github.com/user-attachments/assets/5168612a-32d4-4d1c-b34a-b78268bb2dc4" />

```log
System Name: Windows
System Version: Windows 11 Pro
System kernel Version: 26100
System Arch: x86_64
Verge Version: 2.4.3+autobuild.0924.b608a38
Running Mode: Service
Is Admin: false
```

**Comment by yslin1995** [comment]
升级后无效，且2.4.3新版本容易卡死。
