### ISSUE TITLE
[Feature] 可重新排列左侧菜单栏顺序

### ISSUE THREAD

**Issue by wyf9** [clash-verge-rev/clash-verge-rev#2231]
### 功能描述 / Feature description

一个小功能：
添加可以在窗口左侧的菜单栏 右键 或 按钮 来重新排列菜单项的顺序
> 灵感来源于 Clash for Windows：
![image](https://github.com/user-attachments/assets/069c4929-ae67-4cc1-89b9-63a93a63e272)
![image](https://github.com/user-attachments/assets/147e4dba-e71e-43bc-9f3f-70dc9cffd9d4)

### 使用场景 / Use case

用户可以重新排列左侧菜单栏项目的顺序，使其更加符合使用习惯

**Comment by wonfen** [comment]
没有计划
