### ISSUE TITLE
[BUG] 不开tun模式无法上网（windows）

### ISSUE THREAD

**Issue by yhgalaxy** [clash-verge-rev/clash-verge-rev#2234]
### 问题描述 / Describe the bug

更新到2.0.2后，只打开软件不开tun模式，无法上任何网站，和2之前的版本表现一致；只有2.0.1一切正常；打开tun模式后这几个版本都能上网。怀疑为一打开软件并未开启tun模式时dns就被劫持到fakeip。

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

打开软件，不开代理和tun模式，ping一个网站，显示192开头的fakeip，浏览器上不了网。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

2024-12-01 16:32:26 INFO - try to run core in service mode
2024-12-01 16:32:26 INFO - start service: {"config_dir": "...AppData\\Roaming\\io.github.clash-verge-rev.clash-verge-rev", "core_type": "verge-mihomo", "bin_path": "C:\\Program Files\\Clash Verge\\verge-mihomo.exe", "log_file": "...AppData\\Roaming\\io.github.clash-verge-rev.clash-verge-rev\\logs\\service\\2024-12-01-1632.log", "config_file": "...AppData\\Roaming\\io.github.clash-verge-rev.clash-verge-rev\\clash-verge.yaml"}

**Comment by Tychristine** [comment]
把内核日志中表现无法上网的日志复制来看看吧

**Comment by yhgalaxy** [comment]
日志等级调成debug也就是开始这两条，没有别的，重启重装都试过，开系统代理倒是能上网，只开软件不开任何模式的话就会完全上不了网。
2.0.1在我这是都好的

**Comment by wonfen** [comment]
检查配置文件，发内核日志

**Comment by yhgalaxy** [comment]
> 检查配置文件，发内核日志

time="2024-12-06T11:59:31.587018+08:00" level=info msg="Start initial configuration in progress"
time="2024-12-06T11:59:31.6077213+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-12-06T11:59:31.6077213+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-12-06T11:59:31.6093379+08:00" level=info msg="Initial configuration complete, total time: 2ms"
time="2024-12-06T11:59:31.6099305+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9097"
time="2024-12-06T11:59:31.6120369+08:00" level=info msg="Sniffer is closed"
time="2024-12-06T11:59:31.6120369+08:00" level=info msg="DNS server listening at: 127.0.0.1:53"
time="2024-12-06T11:59:31.6136546+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7897"
time="2024-12-06T11:59:31.6152415+08:00" level=info msg="Start initial Compatible provider PROXY"

后面就是一些healthcheck，关键是不开系统代理的时候没有dns tcp相关消息，也没有报错，开了系统代理是可以上网的

time="2024-12-06T12:01:26.2424923+08:00" level=debug msg="[DNS] www.baidu.com --> [220.181.38.150 220.181.38.149] A from udp:// "
time="2024-12-06T12:01:26.2424923+08:00" level=debug msg="[DNS] www.baidu.com --> [220.181.38.150 220.181.38.149] A from udp:// "
time="2024-12-06T12:01:26.2476485+08:00" level=debug msg="[DNS] pss.bdstatic.com --> [150.138.248.36] A from udp:// "
time="2024-12-06T12:01:26.2476485+08:00" level=debug msg="[DNS] pss.bdstatic.com --> [150.138.248.36] A from udp:// "
time="2024-12-06T12:01:26.2476485+08:00" level=debug msg="[DNS] nav-edge.smartscreen.microsoft.com --> [40.119.213.159] A from udp:// "
time="2024-12-06T12:01:26.2476485+08:00" level=info msg="[TCP] 127.0.0.1:4476 --> www.baidu.com:443 match DomainSuffix(baidu.com) using DIRECT"
time="2024-12-06T12:01:26.2482122+08:00" level=info msg="[TCP] 127.0.0.1:4477 --> www.baidu.com:443 match DomainSuffix(baidu.com) using DIRECT"

这就导致了不需要代理的时候挂着软件上不了网，而且只开系统代理的时候，不采用系统代理配置的应用上不了网。就像前面说的ping不通一样。
正在 Ping www.baidu.com [**198.18.0.8**] 具有 32 字节的数据:
请求超时。
请求超时。

**Comment by wonfen** [comment]
启动软件，关闭tun模式，关闭系统代理；在设置菜单 找到”当前配置“ 点开截图看看 dns 部分的设置

加我下tg https://t.me/wonfen_bot 远程看下也可以

**Comment by yhgalaxy** [comment]
> 启动软件，关闭tun模式，关闭系统代理；在设置菜单 找到”当前配置“ 点开截图看看 dns 部分的设置
> 
> 加我下tg https://t.me/wonfen_bot 远程看下也可以

dns:
  enable: true
  listen: 127.0.0.1:53
  enhanced-mode: fake-ip
  nameserver:
  - xxx
  - xxx
  ipv6: false
  fake-ip-range: 198.18.0.1/16
 
一直是fake-ip，改扩展也没用；2.0.1会显示redir-host，就能上。

**Comment by wonfen** [comment]
> > 启动软件，关闭tun模式，关闭系统代理；在设置菜单 找到”当前配置“ 点开截图看看 dns 部分的设置
> > 加我下tg https://t.me/wonfen_bot 远程看下也可以
> 
> ```
> dns:
>   enable: true
>   listen: 127.0.0.1:53
>   enhanced-mode: fake-ip
>   nameserver:
>   - xxx
>   - xxx
>   ipv6: false
>   fake-ip-range: 198.18.0.1/16
> ```
> 
> 一直是fake-ip，改扩展也没用；2.0.1会显示redir-host，就能上。

理论上fakeip应该也能正常工作才对啊；你本地有其他网络软件在占用这个`198.18.0.1/16` Ip段吗？

**Comment by yhgalaxy** [comment]
> > > 启动软件，关闭tun模式，关闭系统代理；在设置菜单 找到”当前配置“ 点开截图看看 dns 部分的设置
> > > 加我下tg https://t.me/wonfen_bot 远程看下也可以
> > 
> > 
> > ```
> > dns:
> >   enable: true
> >   listen: 127.0.0.1:53
> >   enhanced-mode: fake-ip
> >   nameserver:
> >   - xxx
> >   - xxx
> >   ipv6: false
> >   fake-ip-range: 198.18.0.1/16
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 一直是fake-ip，改扩展也没用；2.0.1会显示redir-host，就能上。
> 
> 理论上fakeip应该也能正常工作才对啊；你本地有其他网络软件在占用这个`198.18.0.1/16` Ip段吗？

确实是这个问题，把easyconnect卸载就好了。
