### ISSUE TITLE
[BUG] 2.0.2默认启用dns

### ISSUE THREAD

**Issue by qhy040404** [clash-verge-rev/clash-verge-rev#2235]
### 问题描述 / Describe the bug

dns默认启用导致dns查询基本全部失败，在扩展配置中设置
```yaml
dns:
  enable: false
```
无法覆盖，最后仍然是
```yaml
dns:
  enable: true
```

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

1. 任意未包含dns的配置文件
2. 全局扩展配置和此配置文件的扩展配置中设置dns.enable = false
3. 查看当前配置仍然是true

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26120.2415

### 日志 / Log

12-01 17:07:07warning
[TCP] dial 🎯 全球直连 (match DomainSuffix/msftconnecttest.com) 127.0.0.1:46592 --> www.msftconnecttest.com:80 error: dns resolve failed: couldn't find ip
12-01 17:07:07warning
[TCP] dial 🎯 全球直连 (match DomainSuffix/msftconnecttest.com) 127.0.0.1:46595 --> ipv6.msftconnecttest.com:80 error: dns resolve failed: couldn't find ip

**Comment by wy353208214** [comment]
+1
退回2.0.1正常

**Comment by hahaer2** [comment]
+1

**Comment by juechenshiai** [comment]
扩展中配置无法覆盖，直接编辑文件可以，回退2.0.1了

**Comment by fatsheepER** [comment]
同样的问题，macOS 15.1.1
在全局拓展配置中禁用 dns 无效，直接编辑订阅文件禁用 dns 是可以的，但更新一下就会重置。

**Comment by ppmoon** [comment]
遇到了相同的问题。利用脚本覆盖。config["dns"]["enable"] = false;没有生效。

**Comment by Sunshine92** [comment]
macos同，更新到2.0.3alpha也未解决。回退2.0.1解决
