### ISSUE TITLE
[BUG] 似乎不能开机自启

### ISSUE THREAD

**Issue by he529406** [clash-verge-rev/clash-verge-rev#2237]
### 问题描述 / Describe the bug

是我自己的问题吗，请大佬测试下

### 软件版本 / Verge Version

2.02

### 复现步骤 / To Reproduce

win11家庭版

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11家庭版

### 日志 / Log

no

**Comment by Tychristine** [comment]
![image](https://github.com/user-attachments/assets/3601b82a-d2c1-444f-89e0-94052a7a1419)
# 打开自动启动以后自行去管理系统启动项

**Comment by seth-shi** [comment]
设置了还是不行
