### ISSUE TITLE
[BUG] Clash开机自启过慢导致断网的解决方法（已解决）

### ISSUE THREAD

**Issue by 2575757** [clash-verge-rev/clash-verge-rev#2238]
### 问题描述 / Describe the bug

因Clash自启过慢&关机时不关闭代理，导致所有早于Clash启动的应用都将断网，以下为解决方法：
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
注册表定位到第一条路径（用户登录后再启动），复制clash的数据并删除
定位到第二条路径（不登录也启动，优先级高），创建字符串，粘贴数据确定
重启后应该就可以观察到Clash的启动速度显著加快，断网问题基本解决

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

每次开机

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

24h2

### 日志 / Log

无

**Comment by liangbonet** [comment]
路径1无clash的值，Clash已设置开机自启，任务管理器已启动自启，软件也正常自启。

**Comment by Astraeus11** [comment]
我也是，没有找到clash的值

**Comment by mlmk6698** [comment]
确实，在"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run"设置Clash值后，开机自启动优先级靠前。同时Clash的高优先级启动，也加快了其他依赖Clash代理的开机自启App启动
