### ISSUE TITLE
[BUG]tun模式无法访问网页

### ISSUE THREAD

**Issue by aLIEz-xue** [clash-verge-rev/clash-verge-rev#224]
### Describe the bug

M1 Mac，14.2.1，clash verge 1.4.6，clash内核已授权，内核、应用、电脑均重启过。
1.Mac开启tun后，无法使用浏览器（Chrome、edge、Safari）访问网页，但是通过系统代理可以访问。tun模式下可以正常使用TG软件。
2.tun开启后，再开启系统代理，然后如果先关闭tun，再关闭系统代理，系统代理实际未关闭。必须在开启tun后，先关闭系统代理才生效。并且这样做后，系统代理单独开启无效，先开启系统代理再开tun也无效，只有在tun开启的情况下再开启系统代理才有效！！！！

### To Reproduce

1.开启tun，使用浏览器（Chrome、edge、Safari）访问网页www.google.com，失败。关闭tun，使用系统代理，成功。
2.开启tun，开启系统代理，关闭tun，关闭系统代理，打开网络设置，发现代理界面http、https、socks5均是打开状态。再次打开tun，打开系统代理，关闭系统代理，打开网络设置，发现代理界面http、https、socks5均是关闭状态了，然后关闭tun，再次打开系统代理，发现http、https、socks5均是关闭状态，此功能失效。除非先打开tun，再打开系统代理，可恢复正常。

### Platform

MacOS

### System Version

14.2.1

### Software Version

1.4.6

**Comment by aLIEz-xue** [comment]
<img width="756" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/59567929/2986e916-48e7-4387-861c-5deed8556ec1">
tun网卡是启动状态

**Comment by Firekylinxiang** [comment]
m2同样的问题

**Comment by mortence** [comment]
> m2同样的问题

M2 Pro 没问题。

**Comment by wonfen** [comment]
试试最新版，现在还有问题么？

**Comment by aLIEz-xue** [comment]
> 试试最新版，现在还有问题么？

现在连系统代理都开不开了，完全使用不了，Tun的话看着有接管一些流量（Telegram等），但是就是访问不了google，找不到原因。内核都授权过，切换过，重启过。看了日志没发现有报错。还有就是内核授权成功后能否显示已授权，一直显示授权搞不清自己授权了没有（还是说我这边就是没授权成功呢）。

<img width="800" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/59567929/d0629958-e543-40d5-89aa-e8c9830ae1d0">
<img width="800" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/59567929/46e1ef14-f5dc-4c77-a2bc-bf8601e43464">
<img width="800" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/59567929/3bde1c35-c415-4207-9b50-c972344a6cea">
