### ISSUE TITLE
[BUG] macOS 中 v2.0.2 托盘图标无法配置为单色

### ISSUE THREAD

**Issue by kowyo** [clash-verge-rev/clash-verge-rev#2242]
### 问题描述 / Describe the bug

我已阅读相似issue #2228 

如图所示，版本号为 2.0.2，图标未显示为单色

![image](https://github.com/user-attachments/assets/e6000a3a-69e7-4dcf-847e-4cea65d3fb7a)

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

设置 ---> 界面设置 ---> 托盘图标：单色图标 ---> 常规托盘图标、系统代理托盘图标、Tun模式托盘图标：选择作者仓库给定的 PNG/ICO 图标

图标的下载地址为 https://github.com/zzzgydi/clash-verge/tree/main/src/assets/image

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS 15.1.1

### 日志 / Log

[2024-12-02-1042.log](https://github.com/user-attachments/files/17971958/2024-12-02-1042.log)

**Comment by wonfen** [comment]
你都自定义了，当然就是已你自定义的图标来显示咯
