### ISSUE TITLE
[BUG] 疑似内存泄漏

### ISSUE THREAD

**Issue by itlaohui** [clash-verge-rev/clash-verge-rev#2246]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/88f86540-f2b7-4d61-b9a0-1f6834fbd386)

请看VCR，电脑内存占用过高，看了下任务管理器，发现clash界面占用了2000多M，原因未知

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

无法复现，日常使用

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 x64 家庭中文版 23H2

### 日志 / Log

暂无

**Comment by wonfen** [comment]
重启再观察观察，找到能稳定复现的方法，是不是用了大量的自定义图标之类的？

**Comment by Xuu6770** [comment]
很久没用了，看到正式版一直停在 1.7.7 ，今天回来看看发现正式版已经更新到 2.0.2 了就下载回来体验一下，安装好以后导入订阅，开了个 TUN 看了会儿 YouTube ，再回到面板一看内存占用约 270MB（还在持续走高），遂重启 Clash 内核，这一次什么都不干，系统代理也不开，TUN 也不开，也没有用端口进行代理的程序，就放在那，内存占用都在持续升高，最终停在 130 MB 。

操作系统是 macOS 15.1.1 。

**Comment by itlaohui** [comment]
![image](https://github.com/user-attachments/assets/e8c9c262-c3c8-4b9b-8b20-815031882f07)
这个问题好像无法准确复现，不过可以提供的思路是：
在昨天晚上下班之前把clash关闭又重新打开了，没有做任何操作，然后就锁屏下班了，电脑日常情况下是不关机的状态，直到今天早上解锁电脑后，看到内存占用又到2900多M了，日志记录功能是WARRING级别，没有日志弹出。
现在猜测最大的可能是WebView的漏洞，也可能是Win11的漏洞，因为除了clash相关问题以外，Win11暴露的问题还是蛮多的

**Comment by Nioy** [comment]
什么鬼，Tauri2.0这么多问题吗

**Comment by lovitus** [comment]
mac 几天漏了400G. 

win还有图形界面冻住的情况, 网络正常, 需要右击托盘重启app

**Comment by lovitus** [comment]
windows 多台机器也漏的厉害, 暂时只能回1.7.7等更新了

**Comment by itlaohui** [comment]
> windows 多台机器也漏的厉害, 暂时只能回1.7.7等更新了


我现在已经回退到1.7.7了，这个版本一切正常，奇怪的是我家里的电脑，虽然有32g的运行内存，但是在2.0以上版本并没有发现内存泄露的问题。有点玄学的感觉了

**Comment by wonfen** [comment]
试试最新的2.0.3版本，尝试修了一些可能导致内存泄露的地方，还有问题发新issue
