### ISSUE TITLE
[BUG] Ubuntu 20.04 无法安装 V2.0.2

### ISSUE THREAD

**Issue by Kazfyx** [clash-verge-rev/clash-verge-rev#2248]
### 问题描述 / Describe the bug

Ubuntu 20.04 无法安装 V2.0.2，提示缺少依赖libwebkit2gtk-4.1-0

### 软件版本 / Verge Version

V2.0.2

### 复现步骤 / To Reproduce

下载Clash.Verge_2.0.2_amd64.deb，使用apt或gdebi安装

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu 20.04.6 LTS GNOME 3.36.8 X11

### 日志 / Log

无

**Comment by zhiwu111** [comment]
我的是unbuntu24.04，安装后启动，显示     已中止 (核心已转储)  
但是上一个2.0.1版本刚开始安装上能运行，今天启动显示 已中止 (核心已转储) ，遂卸载，安装这个2.0.2版本，同样出现  已中止 (核心已转储)

**Comment by zhiwu111** [comment]
现在发现sudo clash-verge能成功，但会显示
failed to commit changes to dconf: 执行子进程“dbus-launch”失败（没有那个文件或目录）

(process:36393): dconf-WARNING **: 18:22:04.384: failed to commit changes to dconf: 执行子进程“dbus-launch”失败（没有那个文件或目录）

(process:36398): dconf-WARNING **: 18:22:04.387: failed to commit changes to dconf: 执行子进程“dbus-launch”失败（没有那个文件或目录）

(clash-verge:36319): libayatana-appindicator-WARNING **: 18:22:04.399: Unable to get the session bus: 执行子进程“dbus-launch”失败（No such file or directory）

(clash-verge:36319): LIBDBUSMENU-GLIB-WARNING **: 18:22:04.399: Unable to get session bus: 执行子进程“dbus-launch”失败（No such file or directory）
closing window...
quit

(process:36506): dconf-WARNING **: 18:22:27.353: failed to commit changes to dconf: 执行子进程“dbus-launch”失败（没有那个文件或目录）

(process:36511): dconf-WARNING **: 18:22:27.356: failed to commit changes to dconf: 执行子进程“dbus-launch”失败（没有那个文件或目录）

(process:36516): dconf-WARNING **: 18:22:27.359: failed to commit changes to dconf: 执行子进程“dbus-launch”失败（没有那个文件或目录）

**Comment by klxiaoniu** [comment]
> 我的是unbuntu24.04，安装后启动，显示 已中止 (核心已转储) 但是上一个2.0.1版本刚开始安装上能运行，今天启动显示 已中止 (核心已转储) ，遂卸载，安装这个2.0.2版本，同样出现 已中止 (核心已转储)

这不是同一个问题，如有需要可以单开一个issue

可以尝试apt purge之后再安装

**Comment by klxiaoniu** [comment]
https://www.clashverge.dev/faq/linux.html#ubuntu-2404

这里的文档是否有帮助？

**Comment by jersonal** [comment]
> https://www.clashverge.dev/faq/linux.html#ubuntu-2404
> 
> 这里的文档是否有帮助？

没用，文档中的版本还是4.0.37，ubuntu20.04  24.04安装4.0.37后还是不行，提示依赖 4.1，但是4.1又安装不上。

**Comment by tl123987** [comment]
@EattingLemon relaea下面有
