### ISSUE TITLE
Pycharm 出现 ValueError: check_hostname requires server_hostname

### ISSUE THREAD

**Issue by lonely06** [clash-verge-rev/clash-verge-rev#225]
开启 Clash Verge 后，在 Pycharm 中发送 HTTP 请求，Pycharm 会出现一个报错 “ValueError: check_hostname requires server_hostname”

关闭 Clash Verge 后，Pycharm 就可以正常发送 HTTP 请求。

**Comment by MystiPanda** [comment]
请规范你的issue，描述清楚问题，Pycharm中发送http是指用python发送http还是在pycharm中配置代理后下载插件之类的，如果是python给出必要的代码片段，这个issue关了，请重新按照指定格式提交issue。
