### ISSUE TITLE
[BUG] ubuntu24.10 x11 2.0.2版本 面板默认位置不居中

### ISSUE THREAD

**Issue by klxiaoniu** [clash-verge-rev/clash-verge-rev#2252]
### 问题描述 / Describe the bug

每次启动面板，位置总是在偏向于左上角的位置（但不一定是最左上角），而非居中。移到到中间后关闭窗口，再次从托盘打开，又会在左上角出现。

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

从托盘启动面板

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

ubuntu 24.10, x11, GNOME 47.0

### 日志 / Log

[2024-12-02-1739.log](https://github.com/user-attachments/files/17975870/2024-12-02-1739.log)

**Comment by wonfen** [comment]
已知问题，等上游窗口记忆插件修复。
