### ISSUE TITLE
[BUG] 在卸载了clash-verge-rev后，程序EdgeWebView2Runtime被删除了，没有办法进行更新或者调整。

### ISSUE THREAD

**Issue by ChenXu-Huang** [clash-verge-rev/clash-verge-rev#2254]
### 问题描述 / Describe the bug

在卸载了clash-verge-rev后，程序EdgeWebView2Runtime被删除了，没有办法进行更新或者调整。

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

安装后卸载，通过winget查看了EdgeWebView2Runtime是否存在，结果不在了，通过winget安装不了了。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 Pro

### 日志 / Log

>winget install Microsoft.EdgeWebView2Runtime --source winget
已找到 Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] 版本 131.0.2903.70
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
已成功验证安装程序哈希
正在启动程序包安装...
安装程序失败，退出代码为: 2147747880

**Comment by Tychristine** [comment]
你是怎么卸载的？

**Comment by ChenXu-Huang** [comment]
就是调用了程序自己的卸载程序。

**Comment by wfs997** [comment]
啊...这，那不是大 bug 了？

https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/?form=MA13LH 下载安装可以？

**Comment by wonfen** [comment]
程序里自带的卸载程序不会删除webview。
