### ISSUE TITLE
[BUG] ubuntu arm64 tun error

### ISSUE THREAD

**Issue by y0IkE** [clash-verge-rev/clash-verge-rev#2256]
### 问题描述 / Describe the bug

ip rule

RTNETLINK answers: Operation not supported
Dump terminated

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

always

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Jetson Orin NX Jetpack 6.1  Linux ubuntu 5.15.148-tegra #1 SMP PREEMPT

### 日志 / Log

time="2024-12-02T19:20:17.399570321+08:00" level=error msg="Start TUN listening error: configure tun interface: cleanup rules: operation not supported"

**Comment by wonfen** [comment]
检查配置文件，怎么又一个 cleanup rules: 的操作？

**Comment by afcafcafc** [comment]
Same problem
