### ISSUE TITLE
[BUG] 进行fetch时会出现20s自动中断

### ISSUE THREAD

**Issue by SheldonLiu0412** [clash-verge-rev/clash-verge-rev#2257]
### 问题描述 / Describe the bug

在规则模式+tun模式开启情况下，终端里curl或者网页的fetch等服务都会在20s时中断。举例1：调用大模型API进行生成，一旦超过20s还未生成结束，就会自动报错重试，如此循环往复。举例2:浏览网页时如果出现长时间fetch的服务，比如等待生成或文件返回，超出20s也会终止，控制台显示fetch failed。关闭clash verge以上会恢复正常。

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

写一段调用大模型的代码，给到20K左右的上下文和复杂prompt，生成时间大概率就会超过20s，此时会看到重试和报错，详细的错误是连接中断，fetch failed。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

MacOS 15.1

### 日志 / Log

12-02 19:49:00DEBUG
[DNS] hijack udp:223.6.6.6:53 from 198.18.0.1:50844
12-02 19:49:00DEBUG
[Rule] use default rules
12-02 19:49:00DEBUG
[DNS] cache hit v3.ksrd.xyz --> [223.111.122.201] A, expire at 2024-12-02 19:51:42
12-02 19:49:00DEBUG
[DNS] cache hit v3.ksrd.xyz --> [] AAAA, expire at 2024-12-02 19:56:02
12-02 19:49:01DEBUG
[Rule] use default rules
12-02 19:49:03DEBUG
[DNS] hijack udp:223.6.6.6:53 from 198.18.0.1:53230
12-02 19:49:03DEBUG
[DNS] hijack udp:223.6.6.6:53 from 198.18.0.1:61211
12-02 19:49:03DEBUG
[Rule] use default rules
貌似没有什么特别信息

**Comment by SheldonLiu0412** [comment]
> ```yaml
> keep-alive-interval
> ```

系统信息：
net.inet.tcp.keepidle: 7200000    
net.inet.tcp.keepintvl: 75000     
net.inet.tcp.keepcnt: 8   
这里应该是2小时

**Comment by Tychristine** [comment]
@SheldonLiu0412 
你所使用的Clash Mihomo的配置文件，尤其是运行时配置
设置-> Verge设置->当前配置
搜索字段 `keep-alive-interval`

**Comment by SheldonLiu0412** [comment]
> @SheldonLiu0412 你所使用的Clash Mihomo的配置文件，尤其是运行时配置 设置-> Verge设置->当前配置 搜索字段 `keep-alive-interval`

clash-verge.yaml中找到了这个变量，是1800，我想可能就是它导致的，我可以手动修改延长吗？后面它还会不会自己变回来？

**Comment by SheldonLiu0412** [comment]
> 查一下你用的节点或者机场有没有超时配置？

谢谢，应该找到原因了

> clash-verge.yaml中找到了这个变量，是1800，我想可能就是它导致的，我可以手动修改延长吗？后面它还会不会自己变回来？

我尝试修改，然后重启calsh它又恢复1800了

**Comment by SheldonLiu0412** [comment]
> 查一下你用的节点或者机场有没有超时配置？

我看了下这个超时配置的确来自机场

**Comment by Tychristine** [comment]
@SheldonLiu0412 
请在Global Extend Config中直接覆写它
直接将查到的这一行，复制过去
将值修改为5-10左右，观察现象是否有改善

**Comment by SheldonLiu0412** [comment]
> @SheldonLiu0412 请在Global Extend Config中直接覆写它 直接将查到的这一行，复制过去 将值修改为5-10左右，观察现象是否有改善

您好请问Global Extend Config在哪里

**Comment by Tychristine** [comment]
@SheldonLiu0412 中文语言下，配置页，全局扩展配置

**Comment by SheldonLiu0412** [comment]
> @SheldonLiu0412 中文语言下，配置页，全局扩展配置

<img width="657" alt="image" src="https://github.com/user-attachments/assets/96668481-4f16-4052-b6f3-886a10cfc299">
请问是添加在profile下吗

**Comment by Tychristine** [comment]
@SheldonLiu0412 直接写，不要在头部留空格

**Comment by SheldonLiu0412** [comment]
我改为了5，仍然出现相同的报错连接中断，但是时间从20s变到了40s

> @SheldonLiu0412 直接写，不要在头部留空格

**Comment by SheldonLiu0412** [comment]
> @SheldonLiu0412 直接写，不要在头部留空格

我的反馈有误，没变化，仍然在20s连接中断
