### ISSUE TITLE
[BUG] 无法启用System模式的Tun虚拟网卡，只能使用GVisor

### ISSUE THREAD

**Issue by lanyuanxiaoyao** [clash-verge-rev/clash-verge-rev#2261]
### 问题描述 / Describe the bug

打开Tun虚拟网卡模式后，只能使用GVisor才能上网，切换另外两个模式均无法联网，之前使用1.7.7版本是正常的，我看通常都是使用System模式，不知道这算不算一个值得引起注意的问题，但我感觉有时候访问网页时候反应有些慢，有时候浏览器总是要失败一次后再重新加载才能正常访问

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

打开Tun虚拟网卡模式后，只能使用GVisor才能上网，切换另外两个模式均无法联网

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11 24H2

### 日志 / Log

[2024-12-02-2255.log](https://github.com/user-attachments/files/17979692/2024-12-02-2255.log)
[2024-12-02-2255.log](https://github.com/user-attachments/files/17979691/2024-12-02-2255.log)

**Comment by leafsoul365** [comment]
你的防火墙阻挡了Verge mihomo.exe访问网络。打开你的“防火墙和网络保护” - “允许应用通过防火墙”，看下是否有“sing-tun（C:\Program Files\Clash Verge\Verge mihomo.exe）”或类似Verge mihomo.exe的项，如有，看下它的公网和专网是否全部都打勾允许了。如果无这一项，可参考你自己的安装路径，手动添加Verge mihomo.exe项并打勾允许。

**Comment by lanyuanxiaoyao** [comment]
由于某些原因，重新安装了，卸载的时候已经把相关配置文件和service都清掉，并且防火墙规则也检查了，但发生了同样的问题（只有GVisor模式可以使用）

### 日志
[2025-02-06-2123.log](https://github.com/user-attachments/files/18690609/2025-02-06-2123.log)
[service 2025-02-06-2123.log](https://github.com/user-attachments/files/18690631/2025-02-06-2123.log)

### 防火墙
![Image](https://github.com/user-attachments/assets/2c822774-83d2-44c7-94c0-08ac97746917)
![Image](https://github.com/user-attachments/assets/57098a8d-60dd-4b0a-88bb-9a08db49f29e)

**Comment by lanyuanxiaoyao** [comment]
> 由于某些原因，重新安装了，卸载的时候已经把相关配置文件和service都清掉，并且防火墙规则也检查了，但发生了同样的问题（只有GVisor模式可以使用）
> 
> ### 日志
> [2025-02-06-2123.log](https://github.com/user-attachments/files/18690609/2025-02-06-2123.log) [service 2025-02-06-2123.log](https://github.com/user-attachments/files/18690631/2025-02-06-2123.log)
> 
> ### 防火墙
> ![Image](https://github.com/user-attachments/assets/2c822774-83d2-44c7-94c0-08ac97746917) ![Image](https://github.com/user-attachments/assets/57098a8d-60dd-4b0a-88bb-9a08db49f29e)

@leafsoul365 @wonfen
