### ISSUE TITLE
[BUG] 使用快捷键时，设置界面“系统代理”的开关图标不能及时更新

### ISSUE THREAD

**Issue by inaku-Gyan** [clash-verge-rev/clash-verge-rev#2262]
### 问题描述 / Describe the bug

设置了开启/关闭系统代理的快捷键（Alt+P）
使用快捷键可以正常打开/关闭系统代理，但是设置界面的“系统代理”的开关图标不会跟随变化。
只有当从设置界面切换到其他界面再切回设置后，“系统代理”的开关图标才被刷新。
下图中可以看到按下快捷键后，系统托盘图标发生变化，但是设置界面的开关没有刷新。
![PixPin_2024-12-03_09-35-15](https://github.com/user-attachments/assets/bfbb7537-8494-4b86-b2ed-a46634845ee6)

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

1. 设置快捷键（我设置的是 Alt+P)
![image](https://github.com/user-attachments/assets/c3556ece-b0f5-48e2-b0c9-f40d1b7b9b77)
2. 打开软件设置面板
3. 使用快捷键
4. 可以看到设置面板上的“系统代理”开关图标没有正常显示开启/关闭
![image](https://github.com/user-attachments/assets/15aea8d0-2610-4426-90bf-9fef15ada29d)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

前端错误，无需日志

**Comment by wonfen** [comment]
无法复现。我这边一切正常
