### ISSUE TITLE
[BUG] 升级到2.0.2后，每次开机，系统托盘区域没有clash verge的图标

### ISSUE THREAD

**Issue by figozhu** [clash-verge-rev/clash-verge-rev#2264]
### 问题描述 / Describe the bug

2.0.1左上角出现升级提示后，点击升级到2.0.2，但每次开机后，系统托盘区域没有图标（但程序是在运行的，代理是生效的），双击桌面的快捷方式，才会出现clash verge的界面

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

2.0.1左上角出现升级提示后，点击升级到2.0.2，但每次开机后，系统托盘区域没有图标（但程序是在运行的，代理是生效的），双击桌面的快捷方式，才会出现clash verge的界面

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

...

**Comment by West-Pavilion** [comment]
我也发现了，任务管理器里已经没有clash verge的开机启动项了

**Comment by WayyneYan** [comment]
我这也是

**Comment by liuxingguo9349** [comment]
我也是

**Comment by boredwithnaming** [comment]
我也是，我还以为没开呢

**Comment by wfs997** [comment]
是有这个问题，昨天看了注册表，没有 clash 这个开机启动。不懂安装哪个版本把注册表中的开机自启删了

解决方式就是开机启动关闭再打开一下
![image](https://github.com/user-attachments/assets/6dd609fa-94cc-4a11-9bf3-48a8551a2790)

**Comment by Vbsan** [comment]
一样的情况

**Comment by figozhu** [comment]
> 是有这个问题，昨天看了注册表，没有 clash 这个开机启动。不懂安装哪个版本把注册表中的开机自启删了
> 
> 解决方式就是开机启动关闭再打开一下 ![image](https://private-user-images.githubusercontent.com/184329089/392199583-6dd609fa-94cc-4a11-9bf3-48a8551a2790.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNjY2NzQsIm5iZiI6MTczMzM2NjM3NCwicGF0aCI6Ii8xODQzMjkwODkvMzkyMTk5NTgzLTZkZDYwOWZhLTk0Y2MtNGExMS05YmYzLTQ4YTg1NTFhMjc5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwMjM5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjMwY2UyN2VlYWQ3NGNjMWJkN2JmYzk4MDlkMTRkYzM2OWM2MTkzNDRiZDk4NDkxMGYwOWMwMGYxY2QzNzRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WetKC_673E2Pl6OnS_FP7nGhEUjraTTqp89gxqocWEg)

这个方法有效
