### ISSUE TITLE
{Bug}The global shortcut keys (Ctrl + Alt + Q) cannot be used to control the on/off switch of the system proxy.

### ISSUE THREAD

**Issue by LQZ77** [clash-verge-rev/clash-verge-rev#2265]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/1518fa6f-6285-49b0-bd39-9a5bde1ddc70)
The global shortcut keys (Ctrl + Alt + Q) cannot be used to control the on/off switch of the system proxy.

### 软件版本 / Verge Version

2.02

### 复现步骤 / To Reproduce

The global shortcut keys (Ctrl + Alt + Q) cannot be used to control the on/off switch of the system proxy.

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

The global shortcut keys (Ctrl + Alt + Q) cannot be used to control the on/off switch of the system proxy.

**Comment by Tychristine** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/2258#issuecomment-2511868488
