### ISSUE TITLE
[BUG] 苹果2022款M1 pro芯片，clash verge 已损坏无法打开

### ISSUE THREAD

**Issue by cheerss** [clash-verge-rev/clash-verge-rev#227]
### Describe the bug

Thanks for your great tool. After I download the dmg file for aarch (e.g., Clash.Verge_1.4.7_aarch64) and drop it into Application folder, the program cannot be opened with the following error.

I try the 1.4.7/1.4.2 and the 1.3.8 version, and all of them report the same error.

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/15375071/f10c817a-f6b9-4497-9e51-488472921624)

### To Reproduce

Download the dmg image on a Macbook pro with an M1 pro chip and open the application

### Platform

MacOS

### System Version

13.5.1 (22G90)

### Software Version

1.4.2, 1.4.7 and 1.3.8

**Comment by Tanselc** [comment]
谷歌有教程

**Comment by wonfen** [comment]
看文档： https://clash-verge-rev.github.io/faq.html
