### ISSUE TITLE
[BUG] 设置过程中的操作会诱发蓝屏问题

### ISSUE THREAD

**Issue by leafsoul365** [clash-verge-rev/clash-verge-rev#2274]
### 问题描述 / Describe the bug

某些操作，诸如代理页面点击“规则、全局“等切换按钮、点击tun设置页面的“保存”按钮、点击订阅页面的“重新激活订阅”按钮等等，会概率性诱发蓝屏。尝试了下复现条件，我连续多次点击这些按钮，比如多次点击代理页的“规则”按钮，基本三五次或十次内必然诱发蓝屏。日常使用中可能不一定哪次一点击就蓝屏了。
蓝屏提示的失败操作是：NETIO.SYS
未看到其他人反馈这个问题，我自身也卸载重装了软件，问题依旧存在。2.0.1时应该也有，我记得也蓝屏过一次。
![IMG_20241203_080007](https://github.com/user-attachments/assets/8a5289f6-ab24-48f0-9b2b-91766db252c6)

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

比如连续多次点击代理页的“规则”按钮，基本三五次或十次内必然诱发蓝屏

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11 23H2

### 日志 / Log

time="2024-12-03T08:01:42.1751194+08:00" level=info msg="Start initial configuration in progress"
time="2024-12-03T08:01:42.1947667+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-12-03T08:01:42.1947667+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-12-03T08:01:42.1987556+08:00" level=info msg="Initial configuration complete, total time: 12ms"
time="2024-12-03T08:01:42.1987556+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9097"
time="2024-12-03T08:01:42.2030359+08:00" level=info msg="Sniffer is closed"
time="2024-12-03T08:01:42.2040341+08:00" level=info msg="DNS server listening at: [::]:1053"
time="2024-12-03T08:01:42.2040341+08:00" level=warning msg="Failed to start Redir UDP Listener: not supported on current platform"
time="2024-12-03T08:01:42.2050301+08:00" level=info msg="Redirect proxy listening at: 127.0.0.1:7892"
time="2024-12-03T08:01:42.2050301+08:00" level=error msg="Start Redir server error: not supported on current platform"
time="2024-12-03T08:01:42.2050301+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7897"
time="2024-12-03T08:01:42.2627444+08:00" level=warning msg="[TUN] default interface changed by monitor,  => 以太网"
time="2024-12-03T08:01:42.9398739+08:00" level=info msg="[TUN] Tun adapter listening at: Meta([198.18.0.1/30],[]), mtu: 9000, auto route: true, auto redir: false, ip stack: Mixed"
time="2024-12-03T08:01:42.944853+08:00" level=info msg="Start initial Compatible provider 🐹 OpenAI"
time="2024-12-03T08:01:42.944853+08:00" level=info msg="Start initial Compatible provider 🎬 iQiyi"
time="2024-12-03T08:01:42.944853+08:00" level=info msg="Start initial Compatible provider Nexitally"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 📺 Disney"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider China-Websites"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 📲 Telegram"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 📟 Twitter"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 🎵 Tiktok"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 🖥 Microsoft"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 🌐 Google"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 📺 Netflix"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider Hijacking"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 📺 HBO"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 🎬 myTVSUPER"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider ♻️ Auto"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 📲 LineTV"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 🎬 Emby"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 🎬 YouTube"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 🍎 Apple"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider Final"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 🖥 Learning"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider China-Media"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider 🎬 Bilibili"
time="2024-12-03T08:01:42.9450925+08:00" level=info msg="Start initial Compatible provider default"
time="2024-12-03T08:01:42.9495164+08:00" level=info msg="Load MMDB file: C:\\Users\\tobe3\\AppData\\Roaming\\io.github.clash-verge-rev.clash-verge-rev/Country.mmdb"

time="2024-12-03T08:07:19.0803082+08:00" level=debug msg="Health Checking, proxy: 🇰🇷 Korea 04, url: http://www.google.com/generate_204, id: {9559aa0f-8455-468c-8935-a2fa6938c0f7}"
time="2024-12-03T08:07:19.0803082+08:00" level=debug msg="[DNS] cache hit 911d500.mifgfs.xyz --> [198.18.0.4] A, expire at 2024-12-03 08:07:19"
time="2024-12-03T08:07:19.0803082+08:00" level=debug msg="[DNS] resolve 911d500.mifgfs.xyz A from udp://119.29.29.29:53"
time="2024-12-03T08:07:19.0803082+08:00" level=debug msg="[DNS] resolve 911d500.mifgfs.xyz A from udp://223.5.5.5:53"
time="2024-12-03T08:07:19.0957858+08:00" level=debug msg="[DNS] 911d500.mifgfs.xyz --> [163.177.58.244] A from udp://223.5.5.5:53"
time="2024-12-03T08:07:19.2857721+08:00" level=debug msg="Health Checked, proxy: 🇭🇰 Hong Kong 20 [Premium], url: http://www.google.com/generate_204, alive: false, delay: 65535 ms uid: {9559aa0f-8455-468c-8935-a2fa6938c0f7}"
time="2024-12-03T08:07:19.2857721+08:00" level=debug msg="Health Checking, proxy: 🇯🇵 Japan 21, url: http://www.google.com/generate_204, id: {9559aa0f-8455-468c-8935-a2fa6938c0f7}"
time="2024-12-03T08:07:19.2862879+08:00" level=debug msg="[DNS] cache hit 911d500.mifgfs.xyz --> [163.177.58.244] A, expire at 2024-12-03 08:08:24"
time="2024-12-03T08:07:19.4145117+08:00" level=debug msg="Health Checked, proxy: 🇭🇰 Hong Kong 21 [Premium], url: http://www.google.com/generate_204, alive: false, delay: 65535 ms uid: {9559aa0f-8455-468c-8935-a2fa6938c0f7}"
time="2024-12-03T08:07:19.4145117+08:00" level=debug msg="Health Checking, proxy: 🇹🇷 Turkey 01, url: http://www.google.com/generate_204, id: {9559aa0f-8455-468c-8935-a2fa6938c0f7}"
time="2024-12-03T08:07:19.4145117+08:00" level=debug msg="[DNS] cache hit 911d500.mifgfs.xyz --> [163.177.58.244] A, expire at 2024-12-03 08:08:24"
time="2024-12-03T08:07:19.4155529+08:00" level=debug msg="Health Checked, proxy: 🇭🇰 Hong Kong 22 [Premium], url: http://www.google.com/generate_204, alive: false, delay: 65535 ms uid: {9559aa0f-8455-468c-8935-a2fa6938c0f7}"
time="2024-12-03T08:07:19.4155529+08:00" level=debug msg="Health Checking, proxy: 🇭🇺 Hungary 01, url: http://www.google.com/generate_204, id: {9559aa0f-8455-468c-8935-a2fa6938c0f7}"
time="2024-12-03T08:07:19.4155529+08:00" level=debug msg="[DNS] cache hit 911d500.mifgfs.xyz --> [163.177.58.244] A, expire at 2024-12-03 08:08:24"

**Comment by wonfen** [comment]
看到有讨论说是adguard 设置里网络有个wfp网络驱动程序 https://github.com/clash-verge-rev/clash-verge-rev/issues/1475#issuecomment-2510712826

**Comment by leafsoul365** [comment]
> 看到有讨论说是adguard 设置里网络有个wfp网络驱动程序 [#1475 (comment)](https://github.com/clash-verge-rev/clash-verge-rev/issues/1475#issuecomment-2510712826)

我还真没用这个adguard。未见其他反馈的，这小冲突找起来就要命了。。
