### ISSUE TITLE
[Feature] 可以考虑在2.0之后的版本添加便携版

### ISSUE THREAD

**Issue by lee88688** [clash-verge-rev/clash-verge-rev#2275]
### 功能描述 / Feature description

使用scoop的persist可以很好的管理app的额外数据，[有一个scoop的bucket](https://github.com/chawyehsu/dorado/blob/master/bucket/clash-verge-rev.json)添加了persist，在各个版本升级时可以很好的保留数据，在迁移的时候也可以很好的迁移过去。不知道2.0版本还能提供便携版吗？

当然如果不提供便携版也可以通过官方的exe解压出来安装，但不知道这种方式可以支持便携版的加载本地的数据吗？

### 使用场景 / Use case

使用scoop管理版本和数据

**Comment by Tychristine** [comment]
不看文档

**Comment by Tychristine** [comment]
已经在我的分支上构建 https://github.com/Tychristine/clash-verge-rev/releases/tag/alpha

**Comment by gengjiawen** [comment]
> 已经在我的分支上构建 [Tychristine/clash-verge-rev@`alpha` (release)](https://github.com/Tychristine/clash-verge-rev/releases/tag/alpha)

Release页面没看到有portable的二进制，目前需要自己构建吗？

**Comment by Tychristine** [comment]
> > 已经在我的分支上构建 [Tychristine/clash-verge-rev@`alpha` (release)](https://github.com/Tychristine/clash-verge-rev/releases/tag/alpha)
> 
> Release页面没看到有portable的二进制，目前需要自己构建吗？

删了，可以自己按文档里的方法构建，执行快速构建只需要8分钟，打包脚本也修复了，运行即可
