### ISSUE TITLE
[BUG] 修改fake ip range不生效。

### ISSUE THREAD

**Issue by mam15mon** [clash-verge-rev/clash-verge-rev#2276]
### 问题描述 / Describe the bug

修改falk ip range 不生效，现已回退到1.7.7版本。

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

修改全局扩展配置 或配置文件
profile:
  store-selected: true

dns:
  use-system-hosts: false
  fake-ip-range: 192.19.0.1/16
 
 这个时候ping 域名，可以看到返回的还是192.18.0.1/16中的地址

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windwos 11

### 日志 / Log

已经回退到1.7.7

**Comment by Tychristine** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/blob/dev/src-tauri/src/enhance/tun.rs

**Comment by frankYoY** [comment]
@Tychristine 软件覆写的，再说这个改不改没啥区别

**Comment by mam15mon** [comment]
我还有一个atrust，所以。他俩的fake ip冲突了

**Comment by frankYoY** [comment]
@mam15mon 1.77版可以，2.0开始cvr会覆写这部分内容

**Comment by dhay3** [comment]
我觉得这个设计是不太合理的

假设你公司有一段网络是 198.18.0.0/24，因为性能问题你并不想让这段网络里的流量过 Clash，那么你就需要如下配置

```
tun:
  route-exclude-address:
  - 198.18.0.0/24
```

因为 2.x Clash-verge-rev 覆写的逻辑导致 fake-ip-range 固定为 `198.18.0.1/16`。那么当 Clash 将一个公网域名映射到 198.18.0.0/24 这个段里的时候，因为 PBR 的原因，这个报文会发送到你公司的服务器上，这显然是有问题的

**Comment by Tychristine** [comment]
> 我觉得这个设计是不太合理的
> 
> 假设你公司有一段网络是 198.18.0.0/24，因为性能问题你并不想让这段网络里的流量过 Clash，那么你就需要如下配置
> 
> ```yaml
> tun:
>   route-exclude-address:
>   - 198.18.0.0/24
> ```
> 
> 因为 2.x Clash-verge-rev 覆写的逻辑导致 fake-ip-range 固定为 198.18.0.1/16。那么当 Clash 将一个公网域名映射到 198.18.0.0/24 这个段里的时候，因为 PBR 的原因，后续的报文就会发送到你公司的服务器上，这显然是有问题的
> 
> PS. 在 release v2.0.2 source code 中 fake-ip-range 固定为 198.18.0.1/16

@dhay3 0e3b631 版本中的fake-ip-range不是`198.18`段

**Comment by dhay3** [comment]
@Tychristine 我看的是 CI [v2.0.2 release](https://github.com/clash-verge-rev/clash-verge-rev/archive/refs/tags/v2.0.2.tar.gz) 里的源码
