### ISSUE TITLE
[Feature] 希望可以支持配置文件修改 fake ip range

### ISSUE THREAD

**Issue by mam15mon** [clash-verge-rev/clash-verge-rev#2277]
### 功能描述 / Feature description

现在fake ip range没有从配置文件中读取，希望可以支持，而不是固定写成 
 revise!(dns_val, "fake-ip-range", "198.18.0.1/16");

if enable {
    revise!(dns_val, "enable", true);
    revise!(dns_val, "ipv6", ipv6_val);
    revise!(dns_val, "enhanced-mode", "fake-ip");
    // 从原始配置读取 fake-ip-range
    revise!(
        dns_val,
        "fake-ip-range",
        origin_dns_val
            .get("fake-ip-range")
            .and_then(|v| v.as_str())
            .unwrap_or("198.18.0.1/16")
    );

    #[cfg(target_os = "macos")]
    {
        crate::utils::resolve::restore_public_dns().await;
        crate::utils::resolve::set_public_dns("223.6.6.6".to_string()).await;
    }
}

### 使用场景 / Use case

因为我使用了深信服的atrust，所以发生了fake-ip-range冲突

**Comment by EddyLee88** [comment]
![image](https://github.com/user-attachments/assets/9ac0b293-64d3-460b-9e7b-b3ccb100561e)
包括类似的扩展配置, 也无法生效, 望支持(v1.7.7是可以支持的)

**Comment by wonfen** [comment]
alpha版本修复了，请下载测试 ( https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha )，如果还有问题，请新开issue
