### ISSUE TITLE
[Feature] 关于局域网连接的使用问题

### ISSUE THREAD

**Issue by 344089386** [clash-verge-rev/clash-verge-rev#2279]
### 问题描述 / Describe the bug

我在windows10虚拟机(192.168.56.101) 打开了clash-verge，并且启用了 局域网连接，我在宿主机通过telnet 可以连通 虚拟机的7897端口，虚拟机里面使用了一个VPN软件（公司的，有监控功能），然后我在系统 代理里面 配置了  虚拟机的IP和端口，此时可以通过网页访问公司的网站，但是拉取代码等操作不行。
是clash-verge 的局域网连接只能代理HTTP吗？但是我看是有SOCKS5协议的，按理不应该，我应该怎么做，才能代理所有的协议呢？
我的需求：
1、虚拟机安装公司VPN
2、虚拟机开启代理端口
3、宿主机连接虚拟机的代理端口 实现所有的请求都走代理

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

1、安装windows10  Oracle VirtualBox虚拟机 使用  NAT网络协议+ Host-Only 协议
2、安装特定的VPN软件
3、宿主机可以访问特定VPN软件的网络环境

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows10

### 日志 / Log

无

**Comment by wonfen** [comment]
命令行使用需要复制环境变量。
其他问题检查防火墙、网络设置等。

**Comment by 344089386** [comment]
已经可以了。是我自己搞错了，我搭好之后git拉不了代码 是因为要设置git的代理，设置一下就可以了
