### ISSUE TITLE
[BUG]MacOS 14.2 M1 下无法上网

### ISSUE THREAD

**Issue by heikeyuhuajia** [clash-verge-rev/clash-verge-rev#228]
### Describe the bug

系统信息：macos版本 14.2；最新的clash verge rev版本1.4.7；
问题：
打开之后，可以成功的订阅，但是**点击连通的节点后**并且**开启系统代理**后仍然不能访问谷歌学术以及其他相关网站；
但是当我**授权内核、开启Tun模式**后就可以访问。

### To Reproduce

1.下载最新版 clash verge
2.订阅中 导入 订阅文件链接
3.在代理中选择通的网络节点、开启系统代理
4.访问谷歌学术、youtube无法访问

### Platform

MacOS

### System Version

MacOS 14.2

### Software Version

1.4.7

### Log

<img width="453" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/101233597/4aa33527-ae86-4a18-beb8-a8342f090be5">

**Comment by wonfen** [comment]
找找你机场、节点、配置的问题。
