### ISSUE TITLE
[BUG] 启动项目，多了一个 won fen

### ISSUE THREAD

**Issue by peiliu0408** [clash-verge-rev/clash-verge-rev#2280]
### 问题描述 / Describe the bug

在更新v2.0.2后，启动项目多了一项，请问是此次更新导致的吗？

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

<img width="498" alt="截屏2024-12-03 20 13 04" src="https://github.com/user-attachments/assets/96425356-c653-473d-84e8-5165abf2f250">

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log

无

**Comment by Tychristine** [comment]
@peiliu0408 请不要提交重复的issue

**Comment by wonfen** [comment]
因为是apple开发者账号是我
