### ISSUE TITLE
[BUG] 开启 TUN 模式后 curl --ipv6 解析失败

### ISSUE THREAD

**Issue by Leskur** [clash-verge-rev/clash-verge-rev#2282]
### 问题描述 / Describe the bug

开启 TUN 模式后，curl --ipv6 命令解析失败

关闭 TUN 模式的示例（正常）
```
curl --ipv6 https://ys.mihoyo.com

<!doctype html> ...《原神》 ...
```

开启 TUN 的示例（异常）
```
curl --ipv6 https://ys.mihoyo.com/

curl: (6) Could not resolve host: ys.mihoyo.com
```

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

开启/关闭 TUN 模式后，分别在命令行运行 curl --ipv6 https://ys.mihoyo.com

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

Clash Verge 日志等级设置为 ALL，curl 指定 --ipv6 参数时，Clash Verge 无日志输出。

**Comment by wonfen** [comment]
面板打开ipv6了吗？

**Comment by Leskur** [comment]
> 面板打开ipv6了吗？

是的，ipv6 处于开启状态，网页也能通过 ipv6 访问。

**Comment by wonfen** [comment]
fakeip 模式下应该不会处理 ipv6的地址信息。

**Comment by Leskur** [comment]
但是开启 TUN 模式后，无法将 `dns` 的 `enhanced-mode` 设置为 `redir-host`

全局拓展/订阅拓展配置均无效，配置：

```
dns:
  enhanced-mode: redir-host
```

配置后重启应用，再查看当前配置：

```
dns:
  use-system-hosts: false
  enhanced-mode: fake-ip
  enable: true
  ipv6: true
  fake-ip-range: 198.18.0.1/16
```
没有正常覆盖  `enhanced-mode`

在 [mihomo-party](https://github.com/pompurin404/mihomo-party) 中可以覆盖并正常工作，但是我更喜欢 [clash-verge-rev](https://github.com/clash-verge-rev/clash-verge-rev)
