### ISSUE TITLE
[BUG] v2.0.2点击系统托盘图标不显示窗口

### ISSUE THREAD

**Issue by wonly211** [clash-verge-rev/clash-verge-rev#2283]
### 问题描述 / Describe the bug

当将clash verge窗口最小化后，点击系统托盘图标时，clash verge窗口无法唤出

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

实施操作：
1、最小化clash verge窗口；
2、点击系统托盘clash verge图标
预期结果：
clash verge窗口唤出并处于激活状态
实际结果：
clash verge窗口依然处于最小化状态

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26100.2454

### 日志 / Log

不涉及

**Comment by wfs997** [comment]
应该是 app 死了，任务管理器打开结束进程，再打开 app 就好了。概率极低，从2.x测试版开始用，到现在出现过两次。

**Comment by wfs997** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/2164#issuecomment-2508171836

都是人才，issue 不先搜索一下。

**Comment by Tychristine** [comment]
@NNName1 你说得对，但是最小化和关闭按钮是同一个按钮(发行说明当中有解释)

**Comment by wonfen** [comment]
最小化是到任务栏，应该从任务栏点击打开吧

**Comment by yixiuge301** [comment]
我有印象提过这个问题，正常应该是预期行为。

**Comment by wonfen** [comment]
2.0.3 alpha修复了
