### ISSUE TITLE
[Feature] 备份更多选择

### ISSUE THREAD

**Issue by seth-shi** [clash-verge-rev/clash-verge-rev#2284]
### 功能描述 / Feature description

备份增加一个本地备份, 直接导出一个  zip 包就行 (使用场景, 当如有异常需要清除干净, 这时候只用备份到 zip, 然后重新安装导入 zip)

备份是否可以增加更多, (自定义图标, 快捷键) 
提个小建议, 任务栏是否可以默认为黑色的(代理没开, ) 不然开没开代理通过任务栏没办法区分

### 使用场景 / Use case

如上

**Comment by yixiuge301** [comment]
+1
本地备份，每次更新一般会卸载已安装的app+清除数据，这样再安装新版app后，直接导入就好。
