### ISSUE TITLE
希望以后更新能不清除订阅

### ISSUE THREAD

**Issue by JJJY5** [clash-verge-rev/clash-verge-rev#229]
### Is your feature request related to a problem? Please describe.

这次1.4.7更新以后，我的订阅直接全部被清除了

### Describe the solution you'd like

像以前的clash一样，能直接更新，不用进入setup安装步骤，估计就可以不清除订阅了。

### Describe alternatives you've considered

1

**Comment by MystiPanda** [comment]
更新并不会清除订阅，如果你用的是便携版，不要用应用内的更新，新版本已经禁用了应用内更新。

**Comment by wonfen** [comment]
看下发布说明： https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.4.3

从1.4.3版本以后不会清除订阅信息了。
