### ISSUE TITLE
[BUG] 当且仅当同时启用tunnel和dialer-proxy的时候，任意节点（无论是自建的还是机场的）的dialer-proxy才能生效，此时才能拉取配置文件

### ISSUE THREAD

**Issue by SavooyT** [clash-verge-rev/clash-verge-rev#2291]
### 问题描述 / Describe the bug

**因为不知道是mihomo内核的问题，还是clash-verge-rev的问题，所以我在两边都提一下issue。**

**问题描述：**
   当我对某个节点启用dialer-proxy时，无论该节点是否是机场提供的节点还是自建的节点，必须要同时启用一个tunnel配置才能让其他的dialer-proxy配置生效（此处的生效指的是可以成功地拉取配置文件），**如果没有任意设置一个tunnel，那么其他所有的dialer-proxy配置都会失效。**

### 软件版本 / Verge Version

**正式版 2.0.2**

### 复现步骤 / To Reproduce

**1.使用以下同时具有dialer-proxy和tunnel的配置，无问题，可拉取配置，所有的节点按预期正常工作（见第一幅图）：**

`mode: rule
log-level: info
allow-lan: true
tcp-concurrent: true
profile:
  store-selected: true
  store-fake-ip: true
find-process-mode: strict
external-controller: :9090

dns:
  enabled: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
  prefer-h3: true 
  respect-rules: true
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query 
  direct-nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query  
  direct-nameserver-follow-policy: true

proxies:
  // 自建节点启用dialer-proxy的方式进行链式代理
  - {name: 🇸🇬 Singapore WAP, server: xx.xx.xx.xx, port: 12334, type: ss, cipher: aes-128-gcm, password: xxxx, tfo: true, udp: true, dialer-proxy: 🇸🇬（SSRDOG）Singapore}
  // 自建节点启用tunnel的方式进行链式代理
  - {name: 🇸🇬 SG WAP（tunnel）, server: 127.0.0.1, port: 7801, type: ss, cipher: aes-128-gcm, password: xxxx, tfo: true, udp: true}
  
tunnels:
- network: [tcp, udp]
  address: 127.0.0.1:7801
  target: xx.xx.xx.xx:12334
  proxy: 🇸🇬（SSRDOG）Singapore

// 代理组自动测速选择通用配置
URLTEST: &URLTEST
  type: url-test
  url: 'http://www.apple.com/library/test/success.html'
  interval: 300
// 代理组
proxy-groups:
  // 香港
  - name: 🇭🇰（SSRDOG）Hong Kong
    <<: *URLTEST
    use:
      - SSRDOG_HK
    tolerance: 3
  // 新加坡
  - name: 🇸🇬（SSRDOG）Singapore
    <<: *URLTEST
    use: 
      - SSRDOG_SG
    tolerance: 4
  // 日本
  - name: 🇯🇵（SSRDOG）Japan
    <<: *URLTEST
    use:
      - SSRDOG_JP
    tolerance: 6
  - name: 🇯🇵（JMS）Japan
    type: select
    use:
      - JMS_JP
  // 台湾
  - name: 🇹🇼（SSRDOG）Taiwan
    <<: *URLTEST
    use:
      - SSRDOG_TW

// 第一个机场（引用模式）
SSRDOG: &SSRDOG
  ...
// 第二个机场（引用模式）
JMS: &JMS
  ...
// 机场配置合集
proxy-providers:
  // 香港
  SSRDOG_HK: 
    <<: *SSRDOG 
    filter: 🇭🇰 Hong Kong
  // 新加坡
  SSRDOG_SG: 
    <<: *SSRDOG 
    filter: 🇸🇬 Singapore 
 // 台湾 🇹🇼
  SSRDOG_TW: 
    <<: *SSRDOG 
    filter: Taiwan
//-----机场分割线-----//           
  JMS_JP:
    <<: *JMS 
    filter: s4
    override:
      tfo: true
      dialer-proxy: 🇭🇰（SSRDOG）Hong Kong           

// 一些规则集的默认配置（引用模式）
RULE_DEFAULT: &R_D  
  type: http
  interval: 3600
  behavior: classical
// 规则集
rule-providers:  
  Gemini:
    <<: *R_D
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini_No_Resolve.yaml"
  OpenAI:
    <<: *R_D
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml"
  Claude:
    <<: *R_D
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude_No_Resolve.yaml"

rules:
  // 其他规则
  - DOMAIN-SUFFIX,tw,🇹🇼（SSRDOG）Taiwan
  - DOMAIN-KEYWORD,tecent,🇭🇰（SSRDOG）Hong Kong
  - DOMAIN-SUFFIX,tencent-cloud.cn,🇭🇰（SSRDOG）Hong Kong
  // OpenAI 强制走SG节点
  - RULE-SET,OpenAI,🇸🇬（SSRDOG）Singapore
  // Gemini 强制走SG节点
  - RULE-SET,Gemini,🇸🇬（SSRDOG）Singapore
  // Claude 强制走SG节点
  - RULE-SET,Claude,🇸🇬（SSRDOG）Singapore
  // 兜底规则
  - MATCH,🇭🇰（SSRDOG）Hong Kong
  
experimental:
  quic-go-disable-gso: false
  quic-go-disable-ecn: false`

![11](https://github.com/user-attachments/assets/8041db99-aa82-41ee-9ac2-100cf4c315c8)

----------------------------------------------------
----------------------------------------------------

**2.修改1中有关dialer-proxy和tunnel的配置，当不保留tunnel的配置，但保留自建节点和机场提供节点的dialer-proxy配置时（下列代码加粗部分），整个配置文件无法拉取（见第二幅图）：**

`
mode: rule
...

dns:
  ...

**proxies:**
  **// 自建节点启用dialer-proxy的方式进行链式代理**
  **- {name: 🇸🇬 Singapore WAP, server: xx.xx.xx.xx, port: 12334, type: ss, cipher: aes-128-gcm, password: xxxx, tfo: true, udp: true, dialer-proxy: 🇸🇬（SSRDOG）Singapore}**

**// 此处删去tunnels配置的部分**

// 代理组自动测速选择通用配置
URLTEST: &URLTEST
  ...
// 代理组
proxy-groups:
  ...

// 第一个机场（引用模式）
SSRDOG: &SSRDOG
  ...
// 第二个机场（引用模式）
JMS: &JMS
  ...
// 机场配置合集
**proxy-providers:
  ...   
//-----机场分割线-----//            
  JMS_JP:
    <<: *JMS 
    filter: s4
    override:
      tfo: true
      dialer-proxy: 🇭🇰（SSRDOG）Hong Kong**         

// 一些规则集的默认配置（引用模式）
RULE_DEFAULT: &R_D  
  ...
// 规则集
rule-providers:  
  ...

rules:
  ...
  
experimental:
  ...
`

![00](https://github.com/user-attachments/assets/03394768-58d6-4031-9bce-db42b0c45129)

----------------------------------------------------
----------------------------------------------------

**3.修改1中有关dialer-proxy和tunnel的配置，当只保留机场节点的dialer-proxy的配置时（下列代码加粗部分），整个配置文件依旧无法拉取（报错依旧见第二幅图）：**

`
mode: rule
...

dns:
  ...

**// 此处同时删去 proxies 和 tunnels 配置的部分**

// 代理组自动测速选择通用配置
URLTEST: &URLTEST
  ...
// 代理组
proxy-groups:
  ...

// 第一个机场（引用模式）
SSRDOG: &SSRDOG
  ...
// 第二个机场（引用模式）
JMS: &JMS
  ...
// 机场配置合集
**proxy-providers:
  ...   
//-----机场分割线-----//            
  JMS_JP:
    <<: *JMS 
    filter: s4
    override:
      tfo: true
      dialer-proxy: 🇭🇰（SSRDOG）Hong Kong**         

// 一些规则集的默认配置（引用模式）
RULE_DEFAULT: &R_D  
  ...
// 规则集
rule-providers:  
  ...

rules:
  ...
  
experimental:
  ...
`

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Beta 22635.4515

### 日志 / Log

因为是无法拉取配置文件的报错，所以没有日志。

**Comment by wonfen** [comment]
简单描述下你的问题，没听懂

是链式代理不生效，还是无法获取订阅？

**Comment by SavooyT** [comment]
> 简单描述下你的问题，没听懂
> 
> 是链式代理不生效，还是无法获取订阅？

是后者，当要使用dialer-proxy的时候，如果不额外配置tunnel，就会出现上面图2的报错，直接无法拉取任何订阅。

**Comment by SavooyT** [comment]
> > 简单描述下你的问题，没听懂
> > 是链式代理不生效，还是无法获取订阅？
> 
> 是后者，当要使用dialer-proxy的时候，如果不额外配置tunnel，就会出现上面图2的报错，直接无法拉取任何订阅。

再深入补充，且看下图配置：
![image](https://github.com/user-attachments/assets/33d522e3-bf98-472a-a2f3-699f6762e393)

此时有dialer-proxy和tunnel，此时无问题，所有订阅可正常拉取。

**Comment by SavooyT** [comment]
> > > 简单描述下你的问题，没听懂
> > > 是链式代理不生效，还是无法获取订阅？
> > 
> > 
> > 是后者，当要使用dialer-proxy的时候，如果不额外配置tunnel，就会出现上面图2的报错，直接无法拉取任何订阅。
> 
> 再深入补充，且看下图配置： ![image](https://private-user-images.githubusercontent.com/111339371/393323447-33d522e3-bf98-472a-a2f3-699f6762e393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDE2NzUsIm5iZiI6MTczMzUwMTM3NSwicGF0aCI6Ii8xMTEzMzkzNzEvMzkzMzIzNDQ3LTMzZDUyMmUzLWJmOTgtNDcyYS1hMmYzLTY5OWY2NzYyZTM5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNjA5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTMxZjE3M2QwOThlNjY1YjIxMjViOTEyMzI5MzUxOTk5Y2EwMTUxNjQ5MTY4Mjg2YTI3NWU4Y2IzZTEzYjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2v4MdLt4HXWE16iaR4AJzKyXmzWKA7XcRJEeg861d-Y)
> 
> 此时有dialer-proxy和tunnel，此时无问题，所有订阅可正常拉取。

继续，如果对刚刚提到的配置，只保留dialer-proxy，删去tunnel的配置，且看下图：
![image](https://github.com/user-attachments/assets/9edd7612-7106-445f-a84a-45eb4d8e69e2)

此时就会报错，报错同上所述，整个配置的所有订阅都无法拉取。

**Comment by SavooyT** [comment]
> > > > 简单描述下你的问题，没听懂
> > > > 是链式代理不生效，还是无法获取订阅？
> > > 
> > > 
> > > 是后者，当要使用dialer-proxy的时候，如果不额外配置tunnel，就会出现上面图2的报错，直接无法拉取任何订阅。
> > 
> > 
> > 再深入补充，且看下图配置： ![image](https://private-user-images.githubusercontent.com/111339371/393323447-33d522e3-bf98-472a-a2f3-699f6762e393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDE2NzUsIm5iZiI6MTczMzUwMTM3NSwicGF0aCI6Ii8xMTEzMzkzNzEvMzkzMzIzNDQ3LTMzZDUyMmUzLWJmOTgtNDcyYS1hMmYzLTY5OWY2NzYyZTM5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNjA5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTMxZjE3M2QwOThlNjY1YjIxMjViOTEyMzI5MzUxOTk5Y2EwMTUxNjQ5MTY4Mjg2YTI3NWU4Y2IzZTEzYjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2v4MdLt4HXWE16iaR4AJzKyXmzWKA7XcRJEeg861d-Y)
> > 此时有dialer-proxy和tunnel，此时无问题，所有订阅可正常拉取。
> 
> 继续，如果对刚刚提到的配置，只保留dialer-proxy，删去tunnel的配置，且看下图： ![image](https://private-user-images.githubusercontent.com/111339371/393324358-9edd7612-7106-445f-a84a-45eb4d8e69e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDE4MzMsIm5iZiI6MTczMzUwMTUzMywicGF0aCI6Ii8xMTEzMzkzNzEvMzkzMzI0MzU4LTllZGQ3NjEyLTcxMDYtNDQ1Zi1hODRhLTQ1ZWI0ZDhlNjllMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNjEyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTRmNTJmOGIxYjY4YTY3OTMzMTY1N2IyNTk1M2Q3NmQwYTc2OGRlMWY0MGJhM2YyMjdjOTVkNGUwMmU0MWE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i2_rvKGHZTh2TsfM7OJRQEoXheVgseZZi4lLIpXZoww)
> 
> 此时就会报错，报错同上所述，整个配置的所有订阅都无法拉取。（此节点为自建节点）

再继续，如果把这里的自建节点的dialer-proxy和tunnel都删去，只留下某个订阅机场的节点，见下图：
![image](https://github.com/user-attachments/assets/3ff90517-7ab7-4828-9458-5eac71c0ee8b)
![image](https://github.com/user-attachments/assets/d6c50c9c-eeb6-491a-aa8b-883c1c9d9c21)
此时，一样报错（报错内容同上），无法拉取订阅。

**Comment by wonfen** [comment]
贴下内核日志和app日志

**Comment by SavooyT** [comment]
> 贴下内核日志和app日志
> 
> 试试核心加载你的配置文件是否正常
> 
> 到安装文件夹跑 .\verge-mihomo.exe -f .\path\to\clash.yaml

按照你发的命令运行了一下，发现最后确实是我这边的问题，不好意思哈，是我没排查清楚，浪费您时间了，向您道歉orz。
