### ISSUE TITLE
[BUG] 有的网站不能访问 ，拼后发现域名 解析到了 198.18.0.78  但是打不开

### ISSUE THREAD

**Issue by jackysuy** [clash-verge-rev/clash-verge-rev#2292]
### 问题描述 / Describe the bug

有的网站不能访问 ，拼后发现域名 解析到了 198.18.0.78  但是打不开

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

比如 https://js.cyfk.cc/

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

12-04 23:57:49debug
[DNS] cache hit js.cyfk.cc --> [221.228.32.13] A, expire at 2024-12-05 00:01:21
12-04 23:57:49debug
[DNS] cache hit js.cyfk.cc --> [::1] AAAA, expire at 2024-12-05 00:01:53
12-04 23:57:49debug
[DNS] js.cyfk.cc --> 221.228.32.13
12-04 23:57:49debug
[DNS] cache hit js.cyfk.cc --> [221.228.32.13] A, expire at 2024-12-05 00:01:21
12-04 23:57:49debug
[DNS] cache hit js.cyfk.cc --> [::1] AAAA, expire at 2024-12-05 00:01:53
12-04 23:57:54warning
[TCP] dial 🌏 国内网站 (match IPCIDR/221.224.0.0/13) 198.18.0.1:58039(msedge.exe) --> js.cyfk.cc:443 error: connect failed: dial tcp 221.228.32.13:443: i/o timeout connect failed: dial tcp [::1]:443: connectex: No connection could be made because the target machine actively refused it.

**Comment by frankYoY** [comment]
@jackysuy 打开tun，ping出来的是fake ip，正常的

**Comment by jackysuy** [comment]
> @jackysuy 打开tun，ping出来的是fake ip，正常的

问题是 ，她不能打开网站了 ，似乎解析到本地了

**Comment by Tychristine** [comment]
@jackysuy 
你这网站一点就打开了呀，看日志都是分流的直连。

**Comment by jackysuy** [comment]
> @jackysuy 你这网站一点就打开了呀，看日志都是分流的直连。

你好，我确实打不开 ，似乎解析到我本机的 localhost了 ，证书都是用的我本机的。我一开始以为是机场问题，换了几个机场依旧。但是用nekoray  就能打开

**Comment by Tychristine** [comment]
@jackysuy 如果解析到127.0.0.1，那你应该检查系统可能存在被篡改
如果解析到198.18.0.0/16 这是正常的fake-ip网段
关闭你的浏览器安全DNS设置

**Comment by jackysuy** [comment]
> @jackysuy 如果解析到127.0.0.1，那你应该检查系统可能存在被篡改 如果解析到198.18.0.0/16 这是正常的fake-ip网段 关闭你的浏览器安全DNS设置

好，我用的 edge，  我看看 哪里关闭  安全DNS设置

**Comment by jackysuy** [comment]
> @jackysuy 如果解析到127.0.0.1，那你应该检查系统可能存在被篡改 如果解析到198.18.0.0/16 这是正常的fake-ip网段 关闭你的浏览器安全DNS设置

不知道哪里该浏览器DNS
就是这样的
![image](https://github.com/user-attachments/assets/6088483c-c206-45f9-81ec-ff7959fa64d4)

**Comment by frankYoY** [comment]
@jackysuy  一般在安全里可以改，仔细找找

**Comment by Edwardsakura** [comment]
> > @jackysuy 如果解析到127.0.0.1，那你应该检查系统可能存在被篡改 如果解析到198.18.0.0/16 这是正常的fake-ip网段 关闭你的浏览器安全DNS设置
> 
> 不知道哪里该浏览器DNS 就是这样的 ![image](https://private-user-images.githubusercontent.com/115638043/392636660-6088483c-c206-45f9-81ec-ff7959fa64d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MTE0MzcsIm5iZiI6MTczMzQxMTEzNywicGF0aCI6Ii8xMTU2MzgwNDMvMzkyNjM2NjYwLTYwODg0ODNjLWMyMDYtNDVmOS04MWVjLWZmNzk1OWZhNjRkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQxNTA1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGFjODk4YzM2NzQzYjIzOGZmYTkzMWUwZjUwNzM3NzQ5MTQzZGNjYjYzN2Q0N2Q0OTRlNTMwMTg3OThmZmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Mkj08gyjd50Vl6uMX8LXD6XngK6aRYUOc0-tll75qrg)
> 
> 我本机安装了IIS，也就是说 他解析到了我本机了。当然，我卸载了IIS也不管用的

参考本链接https://zhuanlan.zhihu.com/p/620272854

**Comment by wonfen** [comment]
先学习了解一下什么是fakeip吧

**Comment by huankong233** [comment]
我也遇到了这个问题，但是我已经把DOH功能关闭了

**Comment by huankong233** [comment]
> 我也遇到了这个问题，但是我已经把DOH功能关闭了

![image](https://github.com/user-attachments/assets/c3baba39-45ad-4e02-bc81-ea21a2f898c4)
