### ISSUE TITLE
建议变更系统代理和TUN开关的位置

### ISSUE THREAD

**Issue by lyc0826** [clash-verge-rev/clash-verge-rev#2293]
### 功能描述 / Feature description

建议把系统代理和TUN的开关放在主界面，而不是在设置里面，那样操作起来更方便点。这两个开关经常要切换的。

### 使用场景 / Use case

全部场景

**Comment by Tychristine** [comment]
@lyc0826 隔壁有个项目叫 Mihomo Party

**Comment by wonfen** [comment]
有计划
