### ISSUE TITLE
[BUG] 2.02版本隐藏托盘还是有大量内存占用

### ISSUE THREAD

**Issue by linghanwu-code** [clash-verge-rev/clash-verge-rev#2296]
### 问题描述 / Describe the bug

1.7版本 的
如果不隐藏到托盘:
![image](https://github.com/user-attachments/assets/acd6a9b2-f6d6-4ca4-996b-ea24e92000c0)

如果隐藏到托盘
就没有了webview2的占用
![image](https://github.com/user-attachments/assets/d855af71-4142-4fe7-b142-f94108aba2de)

![image](https://github.com/user-attachments/assets/de4d5119-23bc-4226-b85a-7ce23d83f83a)
这样内存占用很少
但是2.02版本的无论如何都会有webview2的占用
![QQ20241205-110041](https://github.com/user-attachments/assets/cb4e9ee9-a174-4f4b-a86e-9a79e94be7af)

### 软件版本 / Verge Version

2.0.2

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

**Comment by ruiy326** [comment]
版本发布已经写了，这个是 tauri 2.0 的底层 bug，而 Clash Verge 2.0.2 基于 tauri 2.0 构建，所以关闭按钮实际上是最小化功能，因此"使用内存略有增加"。
