### ISSUE TITLE
[BUG] 从睡眠模式唤醒后tun模式浏览器连不上网

### ISSUE THREAD

**Issue by alan42521** [clash-verge-rev/clash-verge-rev#2298]
### 问题描述 / Describe the bug

电脑从睡眠模式回复后，mihomo显示连上了internet，而浏览器无法连上网络，但是如telegram、qq等应用似乎能连上网络，尝试关闭tun模式，关闭clash，进入飞行模式再退出重新连接网络，再打开clash打开tun模式，浏览器仍然无法连接网络，不过如果同时打开系统代理模式，则浏览器便可连上网络，并且在打开一段时间后，关闭系统代理，此时浏览器仍然能正常连接网络，即便关闭tun再打开也正常，但必须要一段时间，打开系统代理后马上关闭仍然无法上网

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

1.保持tun模式开启令电脑进睡眠模式
2.一段时间后，将电脑从睡眠模式唤醒

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 专业版 22H2

### 日志 / Log

[2024-12-05-1630.log](https://github.com/user-attachments/files/18019968/2024-12-05-1630.log)

**Comment by wonfen** [comment]
截图看看你的tun模式堆栈？
<img width="671" alt="image" src="https://github.com/user-attachments/assets/6872d382-ddc1-47e1-81f3-9c2b6cfeb427">

**Comment by alan42521** [comment]
![image](https://github.com/user-attachments/assets/24949155-2787-4150-b92e-88e1a94ba6e9)

**Comment by alan42521** [comment]
![image](https://github.com/user-attachments/assets/f4d50393-80a6-46d9-a183-0c975cd6d0a5)

**Comment by alan42521** [comment]
![image](https://github.com/user-attachments/assets/e10eaa48-821e-4a27-aba1-4d600fff76dc)

**Comment by wonfen** [comment]
无法稳定复现，如果休眠恢复以后路由表没问题，那只有可能是内核没有处理链接请求了。建议到内核那边反馈一下。

**Comment by alan42521** [comment]
这个以前也不会呀

**Comment by Drom1145** [comment]
> 以前这个1.几个版本的时候也不会呀

2开始框架都不一样了当然要重新写，完全是两个程序

**Comment by minortex** [comment]
复现了同样的问题。系统是iot ltsc 2024，尝试了更换了旧版的1.8.10尝试问题依旧，我的电脑是s3睡眠的，在另一台s0睡眠的电脑没有复现此问题，我有时间找找另一台s3的电脑试试

---

更新：目前使用了无线，发现好像问题没有复现了？不过我尝试更改了dns的配置，不确定是不是这个的原因

---

二更，使用redir-host似乎没有这个问题，目前没有使用gui而是使用裸核，从未遇到此问题。

**Comment by necan** [comment]
我也遇到了这个问题，用的是 v2.4.0+autobuild.0819.e93846d

**Comment by liangxiaodong2020-dev** [comment]
遇到了这个问题  打开了 DNS覆写  然后将增强模式改为了redir-host  解决了这个问题  现在我用最新的版本仍然有这个问题  不知道是否只针对某些设备  或者不知道还有没有其他解决方法

**Comment by rickywei** [comment]
> 遇到了这个问题 打开了 DNS覆写 然后将增强模式改为了redir-host 解决了这个问题 现在我用最新的版本仍然有这个问题 不知道是否只针对某些设备 或者不知道还有没有其他解决方法

相同问题，睡眠后tun模式没有网，系统代理有网，切换redir-host后访问都dns都有问题
