### ISSUE TITLE
更新时会提示“无法打开要写入的文件”

### ISSUE THREAD

**Issue by Kiania-1** [clash-verge-rev/clash-verge-rev#230]
### Describe the bug

安装路径为默认的appdata，应用内更新与新下载安装包(以管理员身份运行）
更新均会在更新时提示“无法打开要写入的文件xxx”
xxx为clash-meta.exe、Clash Verge.exe

### Platform

Windows

### System Version

23H2

### Software Version

1.4.7

**Comment by wxdjs** [comment]
先退出verge，然后用管理员权限打开，就可以正常更新了

**Comment by Kia678** [comment]
> 先退出verge，然后用管理员权限打开，就可以正常更新了

即使用管理员权限打开，也没法安装。另外安装包为什么不直接在双击运行的时候直接调用管理员权限弹窗提示？

**Comment by MystiPanda** [comment]
和管理员权限没关系，这个问题在1.4.5的时候已经修复了，服务模式卸载重装一次就好了。
