### ISSUE TITLE
[BUG] TUN模式下无法访问一些网站，关闭clash verge正常访问

### ISSUE THREAD

**Issue by Edwardsakura** [clash-verge-rev/clash-verge-rev#2300]
### 问题描述 / Describe the bug

TUN模式下法访问一些网站，目前发现都是是判断走直连的网站
退出clash verge可以正常访问，或开全局模式国外节点也可以访问

![telegram-cloud-photo-size-5-6237979319704078146-y](https://github.com/user-attachments/assets/560e6aae-f4ac-47e4-b2e3-03c8a55cd879)

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

以某网站举例
meetingroombooking.nottingham.edu.cn，关闭clash verge 直连正常访问
打开clash verge，规则模式，判定直连，无法访问
切换全局模式，国外节点，可访问

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

151

### 日志 / Log

<img width="1151" alt="image" src="https://github.com/user-attachments/assets/768d75e9-0127-45df-b0d0-deab8b47ccaf">
[2024-12-05-1803_副本.log](https://github.com/user-attachments/files/18021353/2024-12-05-1803_.log)

**Comment by Edwardsakura** [comment]
补充
_环境为：eduroam WPA2企业级_
开启cvr，打开某一网站，该网站走的也是直连的规则，但无法访问，退出cvr或切换全局或走国外节点可正常访问。
_切换网络环境为其他，如流量。_
无论是否开启cvr均能正常进入网站
怀疑是否是校园网和cvr之间某些设置不兼容？

**Comment by wonfen** [comment]
检查配置文件的问题

**Comment by Edwardsakura** [comment]
目前试了好几个不同的配置，群友推荐的，都不可行诶。可提供配置文件，万分感谢。
有的时候也会出现无法访问夸克云盘的情况。
无法打开网站的情况主要出现在走直连的网站或软件

**Comment by wonfen** [comment]
大概原因是配置文件里指定的dns无法对特定网站解析，估计需要手动指定解析这些网站的dns

**Comment by Edwardsakura** [comment]
明白 我去尝试一下 谢谢开发者大佬

目前猜测是

Clash Verge 的 `enhanced-mode: fake-ip `在 TUN 模式下导致 `.cn` 域名通过虚拟 IP 路由，而校园网络（eduroam）的内部 DNS 和路由机制无法正确处理这些虚拟 IP，导致连接超时错误。

校园网络：fake-ip 模式与内部 DNS 和路由冲突，阻碍了对特定 `.cn `网站的访问。
非校园网络：公共 DNS 和开放路由环境使得 `fake-ip` 模式正常工作，网站访问无碍。

**Comment by BANG404** [comment]
你先去查看校园网默认给你分配的 dns 地址，然后修改 dns 配置文件改成校园网分配的地址

**Comment by qylh29** [comment]
兄弟 我最近也出现了这个问题 想问你怎么解决的
