### ISSUE TITLE
[BUG] 如何快速绕过某些网址和应用不使用代理？

### ISSUE THREAD

**Issue by Vane798** [clash-verge-rev/clash-verge-rev#2306]
### 问题描述 / Describe the bug

因为某些特殊需求，我不清楚clashverge会不会让我（hosts中屏蔽的域名ip）和（防火墙屏蔽的exe规则）失效？
我是使用的git中某些大佬的订阅转换，其中有些规则会让我一些软件暴露。我想能否有简洁明了的方式让我一键绕过某些网址或者应用通过clashverge？

### 软件版本 / Verge Version

v1.7.7

### 复现步骤 / To Reproduce

我在系统代理里面绕过设置中加入ip无法绕过代理

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

no

**Comment by Vane798** [comment]
就是我如果要绕过：www.111.com or 3.3.3.3 or 123.exe这三种如何添加规则呢？语法我看了那个手册，完全不懂

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1887
