### ISSUE TITLE
[BUG] 第一次下载安装并导入订阅节点后可以正常使用，重启后软件卡住

### ISSUE THREAD

**Issue by FionnZhu** [clash-verge-rev/clash-verge-rev#2307]
### 问题描述 / Describe the bug

刚下载完毕后功能正常，但是重启电脑后代理页面就会变成空白，并且软件的系统代理和tun模式功能点击都无反应，并且会卡住；
把配置目录里的文件全部删掉重启，再倒入节点后就正常了，但是重启电脑后又用不了了。

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

描述有

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

24h2，26100.2314版本

### 日志 / Log

重启后才能复现，显示不出日志

**Comment by Tychristine** [comment]
因为配置文件有错误，导致内核启动失败自动关闭。
# 检查你的配置文件
