### ISSUE TITLE
[BUG] 重写rule-provides规则集无效

### ISSUE THREAD

**Issue by ttyy33** [clash-verge-rev/clash-verge-rev#2310]
### 问题描述 / Describe the bug

自己重写rule-provides规则，如果机场也存在rule-provides规则，自己的机场rule-provides规则会追加在机场提供的rule-provides规则后面，而不是我自己完完全全的重写整个rule-provides规则

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

1.前提机场订阅文件中有自己的rule-provides规则集
2.自己在扩展配置文件中重写rule-provides规则集（只写了扩展配置文件中的，其他的默认默认配置，未在其他文件中更改rule-provides规则集）
3.刷新配置，机场提供的rule-provides规则集如果存在问题，会在日志中看到一堆的warinning记录

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Microsoft Windows [版本 10.0.22631.4460]

### 日志 / Log

/

**Comment by Tychristine** [comment]
怎么个无效法，我写出来就是有效的

**Comment by ttyy33** [comment]
我写的很清楚。可以自己重新按照我写的issue，在机场订阅中存在rule-provides的前提下，自己在在扩展配置中写rule-provides，刷新配置后，自己写的rule-provides会追加在机场的rule-provides后面。而不是重写，如果对“重写”这个两个字理解不了，换个词叫“覆盖”，如果对覆盖不理解，在举个例子：把原来东西全部都清除之后，放上新的东西。
我是来提bug的，而不是来讨论“追加”和“重写”这两个词是什么意思，之间存在什么区别的。

**Comment by wonfen** [comment]
截图看看你是怎么重写的？

**Comment by ttyy33** [comment]
![image](https://github.com/user-attachments/assets/d8917870-1d57-49a0-89ce-1e2801403375)
![image](https://github.com/user-attachments/assets/bcd8268b-b65f-430a-970b-e39fc2bd61f5)
![image](https://github.com/user-attachments/assets/81337038-18ab-4c1b-bb28-92e17c32d088)
![image](https://github.com/user-attachments/assets/cacdf926-d308-4ed6-bef8-df19aeef1ed8)

**Comment by wonfen** [comment]
给我发下你的覆写规则和机场订阅 https://t.me/wonfen_bot

**Comment by wonfen** [comment]
参考一下这里： https://github.com/clash-verge-rev/clash-verge-rev/issues/1437#issuecomment-2395050752
是否能解决你的问题？

**Comment by baian1** [comment]
想要的是把原来的rule-providers删掉吧，用scripts
```js
function main(config, profileName) {
  config['rule-providers'] = {
     // 写你的 rule-provides
     // 比如 
    "reject": {
      "type": "http",
      "behavior": "domain",
      "url": "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt",
      "path": "./ruleset/reject.yaml",
      "interval": 86400
    },
  };
  return config;
}
```

**Comment by n1nja88888** [comment]
是不是用merge方式只能做到追加写而不是重写？想要重写只能用script方式：
![image](https://github.com/user-attachments/assets/e39c8b4c-5461-4d92-9e36-b07d018dd78b)

**Comment by wonfen** [comment]
仔细看了下，你要复写的话，需要把新的键值名称改为和已有键值名称一样才会覆盖。
