### ISSUE TITLE
[Feature] 能否提供更改或隐藏app内小猫样式的功能？

### ISSUE THREAD

**Issue by ChisakaKanako** [clash-verge-rev/clash-verge-rev#2312]
### 功能描述 / Feature description

<img width="148" alt="截屏2024-12-06 晚上10 18 06" src="https://github.com/user-attachments/assets/81bdb522-3c0f-4f88-b6f0-db845a82cdd8">
<img width="148" alt="截屏2024-12-06 晚上10 17 31" src="https://github.com/user-attachments/assets/9e4311b2-8b3e-402a-bd8c-397df58c2479">

希望可以改成像ClashX一样的风格

### 使用场景 / Use case

<img width="377" alt="截屏2024-12-06 晚上10 19 45" src="https://github.com/user-attachments/assets/b51dec58-7e20-49dc-8ba1-9c77dcd8d983">

Mac可以通过替换图标样式将app图标和托盘图标改为ClashX样式，喜欢ClashX的小猫

附上一下ClashX解包的app图标和托盘图标：

[归档.zip](https://github.com/user-attachments/files/18039314/default.zip)

顺便提一下在设置中替换了解包的托盘图标后，图标显示比一般图标稍大：

<img width="133" alt="截屏2024-12-06 晚上10 23 45" src="https://github.com/user-attachments/assets/157e17cd-21c0-44f0-996c-375762a7b3b6">

左：ClashX，右：Clash Verge

**Comment by wonfen** [comment]
暂无计划
