### ISSUE TITLE
[BUG] 菜单栏图标重复且错误显示

### ISSUE THREAD

**Issue by ZHIBAI000** [clash-verge-rev/clash-verge-rev#2313]
### 问题描述 / Describe the bug

老师！这个软件图标在菜单栏经常重复显示 看左上苹果图标那里 想问一下有办法解决吗 我目前只有重启电脑可以处理 但是打开几次app又这样了啊啊啊啊啊
<img width="900" alt="截屏2024-12-07 00 33 28" src="https://github.com/user-attachments/assets/ea6976af-123e-4ff8-84b0-9b61ec0216ab">

### 软件版本 / Verge Version

V2.0.2
<img width="775" alt="截屏2024-12-07 00 35 06" src="https://github.com/user-attachments/assets/2e6a8f65-0f35-4190-aa04-aaf152a87184">

### 复现步骤 / To Reproduce

启动app时

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Sequoia 15.1.1

### 日志 / Log

[2024-12-07-0037.log](https://github.com/user-attachments/files/18041062/2024-12-07-0037.log)

**Comment by wonfen** [comment]
https://www.clashverge.dev/faq/macos.html#macos_1
