### ISSUE TITLE
[Feature] 在 Proxies/代理 页面中, 顶部的工具栏做成固定的.

### ISSUE THREAD

**Issue by foobarjohnny** [clash-verge-rev/clash-verge-rev#2316]
### 功能描述 / Feature description

跟 Profiles 页面一样, 在 Proxies 页面中, 顶部的工具栏也是固定的, 不随着鼠标滚轮而移动.

### 使用场景 / Use case

所有场景

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/792
