### ISSUE TITLE
[BUG] 开发者您好，2.0.0版本退出程序组合键为alt+q，2.0.1之后改为ctrl+q，但是alt+q仍被占用

### ISSUE THREAD

**Issue by Sliver-Ash** [clash-verge-rev/clash-verge-rev#2320]
### 问题描述 / Describe the bug

开发者您好，2.0.0版本退出程序组合键为alt+q，2.0.1之后改为ctrl+q，但是alt+q仍被占用，我在热键设置alt+q为开启/关闭代理不能生效，设置其他组合键例如alt+s可以。

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

在热键设置alt+q无法生效

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows10

### 日志 / Log

.

**Comment by wonfen** [comment]
快捷键里不要有ctrl 和 q
