### ISSUE TITLE
[BUG] 导入链接成功但是系统找不到文件

### ISSUE THREAD

**Issue by Fuxuan-CN** [clash-verge-rev/clash-verge-rev#2321]
### 问题描述 / Describe the bug

我用clash链接导入代理后显示了导入成功后，然后显示系统找不到文件，选择栏有但是选不上，一选就是系统找不到文件！

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

只需要导入链接就可以

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

none

**Comment by Fuxuan-CN** [comment]
问题

**Comment by Fuxuan-CN** [comment]
![issue](https://github.com/user-attachments/assets/514e895a-ff27-4710-a85b-883aeeb341c6)

**Comment by wonfen** [comment]
看文档： https://www.clashverge.dev/faq/other.html#os-error
