### ISSUE TITLE
[BUG] Windows 版的主界面不能记住窗口的大小

### ISSUE THREAD

**Issue by foobarjohnny** [clash-verge-rev/clash-verge-rev#2322]
### 问题描述 / Describe the bug

Windows 版的主界面不能记住窗口的大小

### 软件版本 / Verge Version

2.0.3-alpha

### 复现步骤 / To Reproduce

step 1 : 启动 ClashVergeRev
step 2 : 调整主界面窗口的大小到非常大
step 3 : 退出
step 4 : 再次启动 ClashVergeRev

expect : 主界面窗口是上次退出时的大小
actual : 默认大小

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10

### 日志 / Log

无

**Comment by wonfen** [comment]
已知问题
