### ISSUE TITLE
[BUG] Mac 托盘图标在最左侧与 Apple 标志重叠

### ISSUE THREAD

**Issue by adavak** [clash-verge-rev/clash-verge-rev#2326]
### 问题描述 / Describe the bug

Mac 托盘图标在最左侧与 Apple 标志重叠

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

随意开机启动即可。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log

<img width="594" alt="2024-12-08 14 55 15" src="https://github.com/user-attachments/assets/0f610b4a-88c5-49ef-bd69-044cbab82b4d">

**Comment by Tychristine** [comment]
[常见问题-MacOS](https://www.clashverge.dev/faq/macos.html#macos_1)

**Comment by bullhe4d** [comment]
软件版本 / Verge Version
2.1.2

复现步骤 / To Reproduce
随意开机启动即可。

操作系统 / OS
MacOS

操作系统版本 / OS Version
15.2

按照官方文档无效
问题原因: macOS Sonoma 的系统 BUG。
解决方案: 系统偏好设置 -> 显示器，调整一下显示器分辨率，然后再调回去

自己摸索出来的方法：
点击任意窗口全屏再退出全屏。

<img width="103" alt="Image" src="https://github.com/user-attachments/assets/2961d7f8-7a3f-4028-b731-52140cdcf6a1" />
