### ISSUE TITLE
[BUG] 设置了开机启动，但是每次都不成功

### ISSUE THREAD

**Issue by keny2198** [clash-verge-rev/clash-verge-rev#2328]
### 问题描述 / Describe the bug

系统，win11Pro，前面的版本都很正常，但是更新到2.02后，每次重启，软件都不能正常自动启动，还要手动。

### 软件版本 / Verge Version

V2.0.2

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11Pro 专业版26100.2454

### 日志 / Log

重启电脑不自动启动

**Comment by Tychristine** [comment]
新版与旧版的注册表中的键值对应不上导致的。自己重开一下启动项
![image](https://github.com/user-attachments/assets/910581d6-3a94-4ff7-8bc5-b6f0cb93e3f6)
确保Windows系统启动项中的`Clash Verge`正确的指向了新版`clash-vegre.exe`

**Comment by QianYuan1437** [comment]
@Tychristine 请问这个任务管理器是哪个软件啊？感觉界面要比微软自带的要简洁好多

**Comment by QianYuan1437** [comment]
@Tychristine 请问这个任务管理器是哪个软件啊？感觉界面要比微软自带的要简洁好多

**Comment by kiddingbaby** [comment]
我的台式 Windows 11 也是这个问题，更新 24h2 重启后就这样了（但是我的 Windows 11 笔记本也是 24h2，却没这个问题）
![image](https://github.com/user-attachments/assets/66390b51-0755-4ff3-a59f-e8c5586cf71f)
![image](https://github.com/user-attachments/assets/6180567d-04d2-4ac2-a5ae-e1e75f322443)
![image](https://github.com/user-attachments/assets/3a5e1e60-2375-44d7-ad8a-6f0781e02f0c)

**Comment by Tychristine** [comment]
> @Tychristine 请问这个任务管理器是哪个软件啊？感觉界面要比微软自带的要简洁好多

Windows11 24H2的任务管理器

**Comment by kiddingbaby** [comment]
尝试过 2.0.2 卸载重装，开机启动选项 打开再关闭再打开，依旧无效。有没有可能是权限问题？唯一区别就是，我的另外一台 Windows 11 的 clash 装在了 D 盘，这台机器只有 C 盘系统盘。

**Comment by KUYE-OLG** [comment]
备份配置 卸载干净重装试试？

**Comment by RightJoy** [comment]
我是这样解决的：可以手动添加启动项
https://answers.microsoft.com/zh-hans/windows/forum/all/windows11%E6%97%A0%E6%B3%95%E4%BB%A5%E7%AE%A1/7f2ec19d-7682-4c00-99f3-ecaf9990130e
