### ISSUE TITLE
[BUG] 将本地ip和端口映射到公网后无法访问Web UI

### ISSUE THREAD

**Issue by lichi7887** [clash-verge-rev/clash-verge-rev#2332]
### 问题描述 / Describe the bug

我将本地的127.0.0.1:9097映射到公网后，在公网访问映射的ip可以显示{"hello":"mihomo"}证明打穿成功
但加上域名后访问不了

### 软件版本 / Verge Version

V2.0.2

### 复现步骤 / To Reproduce

软件开启TUN模式 开启局域网连接 其余设置没有动过
映射127.0.0.1:9097到公网，访问映射后的地址可以显示{"hello":"mihomo"}说明隧道打通了
但是加上Web UI的域名后
即https://yacd.metacubex.one/?hostname=我映射的公网域名&port=端口&secret=
无法访问Web UI
浏览器Chrome 关闭Https保护
![PixPin_2024-12-09_03-45-25](https://github.com/user-attachments/assets/c1dd108c-4cd7-4bc6-86a1-6b554e8ff5f1)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

[2024-12-09-0355.log](https://github.com/user-attachments/files/18053810/2024-12-09-0355.log)

**Comment by wonfen** [comment]
非gui问题
