### ISSUE TITLE
[BUG] 开启系统代理后，云之家PC软件无法访问网络

### ISSUE THREAD

**Issue by zdw2014** [clash-verge-rev/clash-verge-rev#2333]
### 问题描述 / Describe the bug

软件：云之家，进程名CloudHub.exe
1、未开启系统代理，软件正常使用
2、开启ssr、v2ray系统代理，软件正常使用
3、开启clash-verge系统代理，规则、直连不能访问网络，全局可以
4、已尝试开启process-name和process-path，查看日志也发现进程名规则已生效
5、另外，为什么新版的clash-verge日志界面没有任何信息显示了（日志文件中有）

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

1、开启系统代理（规则或直连模式）
2、再开启云之家软件（无需账号，启动页面有扫码登录，二维码显示不出来）

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows10企业版LTSC（21H2）。操作系统内部版本：19044.5131

### 日志 / Log

[2024-12-09-0903.log](https://github.com/user-attachments/files/18054954/2024-12-09-0903.log)

**Comment by wonfen** [comment]
非GUI问题
