### ISSUE TITLE
[BUG]  mac  intel芯片  16寸 2019款， mac OS 14.7.1版本 ，2.0.2版本闪退

### ISSUE THREAD

**Issue by workforwy** [clash-verge-rev/clash-verge-rev#2334]
### 问题描述 / Describe the bug

闪退太快，录不了屏，每次启动，都需要输入密码，然后进入闪一下，就没了，然后其他代理都失效了

### 软件版本 / Verge Version

2.0.2，release 

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.7.1

### 日志 / Log

无

**Comment by wonfen** [comment]
看文档，原因是服务没有成功安装 
https://www.clashverge.dev/faq/macos.html#osascript

如果不是文档上的原因，联系我远程看看 https://t.me/woonfen_bot

**Comment by manyangyangl** [comment]
@wonfen  大佬，电脑没有won fen咋整

**Comment by manyangyangl** [comment]
> 提一句。2020款，13，15.1.1可以正常使用

大佬，这个问题你解决了嘛

**Comment by manyangyangl** [comment]
> 看文档，原因是服务没有成功安装 https://www.clashverge.dev/faq/macos.html#osascript
> 
> 如果不是文档上的原因，联系我远程看看 https://t.me/woonfen_bot

大佬，电脑没有 won fen  咋办啊

**Comment by wonfen** [comment]
> @wonfen 已按照文档操作，没有限制安装，且没有 won fen启动项 ，电报显示无此联系人
上面打错字了
https://t.me/wonfen_bot

**Comment by wonfen** [comment]
> @wonfen 大佬，电脑没有won fen咋整

联系我tg https://t.me/wonfen_bot

**Comment by wonfen** [comment]
远程看了，原因： https://www.clashverge.dev/faq/macos.html

**Comment by wonfen** [comment]
> [@wonfen](https://github.com/wonfen) 大佬，我安装了 2.0.3 版本，在软件内部看到了日志，你看你那有用不

之前不就帮你看过了，是这个原因啊  https://www.clashverge.dev/faq/macos.html
