### ISSUE TITLE
[BUG]  手机端小火箭测速正常， pc用 clash verge 测速就显示 error

### ISSUE THREAD

**Issue by gofunbox** [clash-verge-rev/clash-verge-rev#2335]
### 问题描述 / Describe the bug

[BUG]  手机端小火箭测速正常， pc用 clash verge 测速就个别节点显示 error，难受了不知道为啥 求解～～感恩
![ PC 端](https://github.com/user-attachments/assets/08fb9b63-1c8f-4ec6-b1e2-e33ad26c6c89)
![手机端](https://github.com/user-attachments/assets/cbb933a9-bac9-444f-bbc9-66a6a9c8f459)

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

一直有

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log

用这两个 error 节点访问就报错，其他节点正常～

12-06 11:39:44WARNING
[TCP] dial MY—SELECT (match DomainSuffix/binance.com) 127.0.0.1:49402 --> [www.binance.com:443](http://www.binance.com:443/) error: c17s4.portablesubmarines.com:27181 connect error: connect failed: dial tcp 23.106.131.232:27181: connect: connection refused

[TCP] dial MY—SELECT (match DomainSuffix/binance.com) 127.0.0.1:49581 --> [www.binance.com:443](http://www.binance.com:443/) error: c17s5.portablesubmarines.com:27181 connect error: connect failed: dial tcp 162.248.78.106:27181: connect: connection refused

12-06 11:40:49INFO
[TCP] 127.0.0.1:49654 --> [www.binance.com:443](http://www.binance.com:443/) match DomainSuffix(binance.com) using MY—SELECT[jms-s1]

**Comment by wonfen** [comment]
排查配置文件
