### ISSUE TITLE
[BUG] 机场节点在clash无法使用

### ISSUE THREAD

**Issue by lingfeng01** [clash-verge-rev/clash-verge-rev#2337]
### 问题描述 / Describe the bug

我机场节点在clash上无法使用，v2ray核心的都可以用，节点没有问题，
![image](https://github.com/user-attachments/assets/ed02d4f7-9f4e-461e-b581-3bfc9befdb66)
![image](https://github.com/user-attachments/assets/848708eb-510e-4cd8-9654-630cb0bc3dd7)

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

导入订阅，打开代理，打开google显示www.google.com 意外终止了连接。ERR_CONNECTION_CLOSED

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 专业版19045.5131

### 日志 / Log

[2024-12-09-1611.log](https://github.com/user-attachments/files/18058295/2024-12-09-1611.log)

**Comment by lingfeng01** [comment]
![image](https://github.com/user-attachments/assets/1fb06252-33bf-4f47-acc4-7a430a60f860)

**Comment by Tychristine** [comment]
非GUI问题，提供一下内核日志

**Comment by lingfeng01** [comment]
![image](https://github.com/user-attachments/assets/f9851ca8-abb9-420c-a9b2-75368786de30)

**Comment by lingfeng01** [comment]
> GUI非问题，提供一下内核日志

[2024-12-09-1611.log](https://github.com/user-attachments/files/18058418/2024-12-09-1611.log)

**Comment by Tychristine** [comment]
> time="2024-12-09T16:11:36.6668877+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/google) 127.0.0.1:12856(chrome.exe) --> www.google.com:443 error: acd2e55a7c28a486.cdn.jiashule.com:48776 connect error: dns resolve failed: couldn't find ip"
```txt
dns resolve failed
```
客户端配置问题，自行检查

**Comment by lingfeng01** [comment]
> > time="2024-12-09T16:11:36.6668877+08:00" level=warning msg="[TCP] 拨号 🚀 节点选择 (match DomainKeyword/google) 127.0.0.1:12856(chrome.exe) --> [www.google.com:443](http://www.google.com:443)错误：acd2e55a7c28a486.cdn.jiashule.com:48776 连接错误：dns 解析失败：找不到 ip"
> 
> ```
> dns resolve failed
> ```
> 
> 客户端配置问题，自行检查

我使用的是默认的配置，这边是校园网

**Comment by lingfeng01** [comment]
> > time="2024-12-09T16:11:36.6668877+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/google) 127.0.0.1:12856(chrome.exe) --> [www.google.com:443](http://www.google.com:443) error: acd2e55a7c28a486.cdn.jiashule.com:48776 connect error: dns resolve failed: couldn't find ip"
> 
> ```
> dns resolve failed
> ```
> 
> 客户端配置问题，自行检查

无法解决，不知道客户端需要在哪里设置，电脑是自动获取ip和dns。
