### ISSUE TITLE
[Feature] Releases里提供的sig文件校验需要新的minisign公钥，或者提供shasum校验文件

### ISSUE THREAD

**Issue by goddaneel** [clash-verge-rev/clash-verge-rev#234]
### Is your feature request related to a problem? Please describe.

clash-verge-rev从clash-verge分支之后，原有项目的minisign公钥已经失效

### Describe the solution you'd like

能否提供新的minisign公钥，以保证校验

### Describe alternatives you've considered

如果可以的话，能否为release里发布的二进制文件提供类似sha512的shasum校验文件，以防止篡改

**Comment by goddaneel** [comment]
前脚刚发完，我后脚就自己找到了。。。

https://github.com/clash-verge-rev/clash-verge-rev/blob/98efc93610af67791071ef59067f88c473a2228f/src-tauri/tauri.conf.json#L37

参考 https://github.com/zzzgydi/clash-verge/discussions/304 进行转换校验


不过依旧希望可以提供shasum文件，更简单一些

**Comment by MystiPanda** [comment]
release里面的sig文件是给升级的时候验证签名用的

**Comment by goddaneel** [comment]
我是看没有提供别的校验方式就用这个了，如果有sha512这类的校验文件就不需要这个了，我只是手动安装而已
