### ISSUE TITLE
win10 旧版本开始出现的问题，打开后自动闪退。卸载后更新到最新2.0.2后打开任务栏有图标能操控，但是无法打开主界面

### ISSUE THREAD

**Issue by l2301397375** [clash-verge-rev/clash-verge-rev#2340]

**Comment by Richar618** [comment]
我也遇到同样的情况。

**Comment by pan0624** [comment]
重新安装最新版本貌似解决了此问题

**Comment by kiriya893soudayo** [comment]
你有没有使用 geek 这类软件删除 edge webview2？Clash Verge GUI 使用的 Tauri 框架就是基于 edge webview 的，我之前也是想删除 edge，搜索得到的回答是 webview2 没什么用就一起删了。这个情况下 Clash Verge 就会变成小图标可以操作，但点击图标无法呼出 GUI。（刚删掉 webview2 的时候就是像你说的一样出来后闪退，后面就是直接无法呼出。）我不懂代码所以可能说的没什么用，但希望能帮到你。
