### ISSUE TITLE
[BUG] 指纹如何设置？connect error: REALITY is based on uTLS, please set a client-fingerprint

### ISSUE THREAD

**Issue by xia0sheng** [clash-verge-rev/clash-verge-rev#2341]
### 问题描述 / Describe the bug

配置好服务端和客户端后，在clash verge测试延迟的时候，就会报错connect error: REALITY is based on uTLS, please set a client-fingerprint
我测试了下用小火箭，可以正常连接使用 服务器配置的vpn

请问clash verge 如何设置指纹？下面设置正确吗

  "reality-opts": {
        "public-key": "GWPTbc9V19ZPZZre2jUpViQyiXyv7cVHRS1PV27RC3k",
        "short-id": "a1b2c3d4e5f6a7b8",
        "client-fingerprint": "chrome"
      }

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

客户端配置
{
    "name": "Azure",
    "type": "vless",
    "server": "xxxx",
    "port": 10086,
    "uuid": "xxxxx",
    "network": "tcp",
    "tls": true,
    "udp": true,
    "flow": "xtls-rprx-vision",
    "reality-opts": {
        "public-key": "GWPTbc9V19ZPZZre2jUpViQyiXyv7cVHRS1PV27RC3k",
        "short-id": "a1b2c3d4e5f6a7b8",
        "client-fingerprint": "chrome"
      }
    }
    

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

connect error: REALITY is based on uTLS, please set a client-fingerprint

**Comment by wonfen** [comment]
非GUI问题

**Comment by xia0sheng** [comment]
解决了，应该是少了个servername参数，和一些参数位置存放
clash verge 全局扩展脚本的正确配置如下：
{
    "name": "Azure_Vless",
    "type": "vless",
    "server": "IP",
    "port": 10086,
    "uuid": "uuid",
    "network": "tcp",
    "tls": true,
    "udp": true,
    "tfo": false,
    "flow": "xtls-rprx-vision",
    "skip-cert-verify": false,
    "reality-opts": {
        "public-key": "public-key",
        "short-id": "short-id"        
      },
    "client-fingerprint": "chrome",
    "servername": "www.bing.com"
    }
