### ISSUE TITLE
[BUG] 【偶现】突然所有的节点都测速不通，且无法切换规则/全局/直连，也不能切换到其它订阅

### ISSUE THREAD

**Issue by figozhu** [clash-verge-rev/clash-verge-rev#2344]
### 问题描述 / Describe the bug

偶现，突然所有节点都测速不通；
然后也不能切换到其它节点，报错：
error sending request for url
(http://127.0.0.1:9097/configs?
force=true)

![image](https://github.com/user-attachments/assets/08301064-ecb3-4163-907a-130c2b18ea36)

代理组界面也不能切换规则状态，当前处于【规则】下，但点击【直连】无反应

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

暂时不知道如何复现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win 10

### 日志 / Log

...

**Comment by Dudengtai** [comment]
2020 intel mac安装上就是这个现象，现在已经去用clash x了

**Comment by Tychristine** [comment]
GUI使用9097端口和内核通信，出现无法连接内核就是内核崩溃了。
查看日志目录里的service目录寻找内核崩溃的原因。

**Comment by nowanti** [comment]
闹麻了。issue列表的新版问题，遇到了好几个，覆盖了 x86 ubuntu，x86 MacOS，Apple M1 MBP。
- 无法自启动
- 无法切换订阅/测速全部Error/外部控制连不上
- 删配置重启/重装/装旧版，均无效

唉。

**Comment by figozhu** [comment]
> 闹麻了。issue列表的新版问题，遇到了好几个，覆盖了 x86 ubuntu，x86 MacOS，Apple M1 MBP。
> 
> * 无法自启动
> * 无法切换订阅/测速全部Error/外部控制连不上
> * 删配置重启/重装/装旧版，均无效
> 
> 唉。

估计还是tauri的锅，看推上写OpenAI Translator的大佬疯狂吐槽tauri的各种bug。

**Comment by wonfen** [comment]
使用出现异常的，打开设置-->配置目录 备份 后 删除所有文件 尝试是否正常

**Comment by XJF2332** [comment]
> GUI使用9097端口和内核通信，出现无法连接内核就是内核崩溃了。
> 查看日志目录里的service目录寻找内核崩溃的原因。

同样的问题，报错是External controller listen error: listen tcp 127.0.0.1:9097: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by wonfen** [comment]
> > GUI使用9097端口和内核通信，出现无法连接内核就是内核崩溃了。
> > 查看日志目录里的service目录寻找内核崩溃的原因。
> 
> 同样的问题，报错是External controller listen error: listen tcp 127.0.0.1:9097: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

又是一个不看文档的 https://www.clashverge.dev/faq/other.html#_5

**Comment by dyfromnil** [comment]
同force=true的问题，mac mini M4
