### ISSUE TITLE
[BUG] macos 2.0.2版本无法开启tun模式

### ISSUE THREAD

**Issue by manjaoe** [clash-verge-rev/clash-verge-rev#2348]
### 问题描述 / Describe the bug

macos 2.0.2版本，开启tun模式，没有看到授权
![image](https://github.com/user-attachments/assets/cdc00800-7c50-4cb2-b35c-ba235e412ec2)

![image](https://github.com/user-attachments/assets/2875b2fa-1215-41c6-880a-5cd712dc630b)

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macos 15.1.1 

### 日志 / Log

无

**Comment by wonfen** [comment]
2.0版本自动安装服务模式，无需再安装和授权了。在面板打开tun即可。
