### ISSUE TITLE
[Feature] 可以让每次打开的位置和窗口大小自定义吗？

### ISSUE THREAD

**Issue by thornboo** [clash-verge-rev/clash-verge-rev#2353]
### 功能描述 / Feature description

能够在设置中自定义窗口打开位置和窗口大小。对于大屏幕和特别小的屏幕来说比较好一些。

### 使用场景 / Use case

现在如果在30寸以上的显示器使用程序的话，每次打开程序都会显示在左上角，并且窗口大小被重置了。

**Comment by Tychristine** [comment]
发行说明，known issue
