### ISSUE TITLE
[Feature] 如何额外追加本地SOCKS代理

### ISSUE THREAD

**Issue by HaiTang-8** [clash-verge-rev/clash-verge-rev#2360]
### 功能描述 / Feature description

工作场景需求要使用深信服的vpn，我使用docker启用，映射我本地的端口，提供SOCKS服务，但是不能和clash一起使用，如何在机场的订阅中追加本地的SOCKS，并且配置某些IPv4地址使用这个本地的socks呢

### 使用场景 / Use case

工作场景需求要使用深信服的vpn，我使用docker启用，映射我本地的端口，提供SOCKS服务，但是不能和clash一起使用，如何在机场的订阅中追加本地的SOCKS，并且配置某些IPv4地址使用这个本地的socks呢

**Comment by yixiuge301** [comment]
是PC同时使用 vpn 和 clash 吗？是的话，有试过直接开启深信服vpn 和 clash 没，可能这俩不冲突。用过山石网科和启明星辰，没遇到问题，我的环境都不冲突。

**Comment by HaiTang-8** [comment]
> 是PC同时使用 vpn 和 clash 吗？是的话，有试过直接开启深信服vpn 和 clash 没，可能这俩不冲突。用过山石网科和启明星辰，没遇到问题，我的环境都不冲突。

我的深信服是跑在docker里面的，只映射了端口出来，然后我连接数据库或者在浏览器都是用插件或者app本身里面自带的网络代理使用的，我想的是clash从源头上配置，把固定的URI使用本地的SOCKS，其他的用机场的配置

**Comment by HaiTang-8** [comment]
> > > 是PC同时使用 vpn 和 clash 吗？是的话，有试过直接开启深信服vpn 和 clash 没，可能这俩不冲突。用过山石网科和启明星辰，没遇到问题，我的环境都不冲突。
> > 
> > 
> > 我的深信服是跑在docker里面的，只映射了端口出来，然后我连接数据库或者在浏览器都是用插件或者app本身里面自带的网络代理使用的，我想的是clash从源头上配置，把固定的URI使用本地的SOCKS，其他的用机场的配置
> 
> If you are using local SOCKS proxy, you can simply specify that socks proxy as a node using a merge config file like in the [documentation](https://wiki.metacubex.one/en/config/proxies/socks/#socks) here, then create a rule group for your URIs that you want to go through that proxy through it as [documented here](https://wiki.metacubex.one/en/config/rules/?h=rules#routing-rules).



> > > 是PC同时使用 vpn 和 clash 吗？是的话，有试过直接开启深信服vpn 和 clash 没，可能这俩不冲突。用过山石网科和启明星辰，没遇到问题，我的环境都不冲突。
> > 
> > 
> > 我的深信服是跑在docker里面的，只映射了端口出来，然后我连接数据库或者在浏览器都是用插件或者app本身里面自带的网络代理使用的，我想的是clash从源头上配置，把固定的URI使用本地的SOCKS，其他的用机场的配置
> 
> If you are using local SOCKS proxy, you can simply specify that socks proxy as a node using a merge config file like in the [documentation](https://wiki.metacubex.one/en/config/proxies/socks/#socks) here, then create a rule group for your URIs that you want to go through that proxy through it as [documented here](https://wiki.metacubex.one/en/config/rules/?h=rules#routing-rules).

<img width="1128" alt="image" src="https://github.com/user-attachments/assets/25d37292-f9de-49bf-8fed-28ee458549b9" />
Thank you for your reply, but I have already switched to cfw's parsers. There is too little documentation for this project. I hope you can do better and better.
