### ISSUE TITLE
[BUG] 建议修改‘verge-mihomo’进程的端口策略，它占用了ADB服务默认端口5037

### ISSUE THREAD

**Issue by shushu789** [clash-verge-rev/clash-verge-rev#2362]
### 问题描述 / Describe the bug

我经常会使用[ADB服务](https://developer.android.com/tools/adb?hl=zh-cn#:~:text=%E6%B3%A8%E6%84%8F%EF%BC%9A%E6%89%80%E6%9C%89%20adb%20%E5%AE%A2%E6%88%B7%E7%AB%AF,5037%20%E4%B8%8E%20adb%20%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%80%9A%E4%BF%A1%E3%80%82)，它的默认端口是5037，但是有时候重启电脑后，这个端口会被**verge-mihomo**进程占用，以下是终端排查时的结果：
PS C:\Users\admin> netstat -ano | findstr "5037"
  TCP    192.168.1.11:5037      117.xxx.xxx.xxx:18135   ESTABLISHED     13436

这就导致我我无法正常使用ADB服务，我必须重启系统或者结束**verge-mihomo**进程，这显然多少影响使用，我不知道这个端口策略是什么，但如果可以，建议调整为其他范围
  
 **该进程ID13436 在任务管理器进程中如图**

![image](https://github.com/user-attachments/assets/71a4ab88-0d70-4c7b-8059-d455171893c9)

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

启动clash-verge-rev，都可能随机发生

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows10

### 日志 / Log

无日志

**Comment by wonfen** [comment]
verge的运行不需要使用这个端口，检查其他被占用的原因

**Comment by HosamaJJF** [comment]
我今天也遇上了这种情况，但是verge设置里也找不到相关的端口设置，在verge里重启内核就好了。可能是个小概率随机事件，但是总之还是希望有办法设置避免不希望被占用的端口。。。

**Comment by Ahaohaohao** [comment]
> 我今天也遇上了这种情况，但是verge设置里也找不到相关的端口设置，在verge里重启内核就好了。可能是个小概率随机事件，但是总之还是希望有办法设置避免不希望被占用的端口。。。

没有占用此类端口
