### ISSUE TITLE
[BUG]树莓派 花屏no

### ISSUE THREAD

**Issue by fyhssg** [clash-verge-rev/clash-verge-rev#237]
### Describe the bug

树莓派无法正常打开

### To Reproduce

.

### Platform

Windows

### System Version

Debian bookworm

### Software Version

1.4.5

### Log

![IMG_9752](https://github.com/clash-verge-rev/clash-verge-rev/assets/56507386/0323c34f-f7ef-471c-8f27-df55e64d4399)

**Comment by SunnyCloudYang** [comment]
手动调整窗口大小之后可以正常显示，但是每一次打开都会花屏（所以千万不要最大化，不知道什么时候就找不到关闭按钮和边框了，像我现在一样🥲）

**Comment by kaCVanime** [comment]
ran into same issue after install nvidia driver on arch linux.
`export LIBGL_ALWAYS_SOFTWARE=1` won't work.

**Comment by sekwah41** [comment]
I've not personally experienced this issue but we had the same thing reported on Pomatez. After we upgraded the electron version we didn't seem to see the issue again but we never got a confirmation that it fixed it from the original poster.
