### ISSUE TITLE
[BUG] 新建订阅，这两个选项保存不了

### ISSUE THREAD

**Issue by jameouni** [clash-verge-rev/clash-verge-rev#2370]
### 问题描述 / Describe the bug

新建订阅，这两个选项保存不了
![image](https://github.com/user-attachments/assets/db6a27e4-ddcd-4e26-85a8-9d62694bb287)

保存后，再打开这个订阅，还是关闭的

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

新建配置
打开那两个选项
保存
打开新建的订阅，那两个选项还是关闭的

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10

### 日志 / Log

按复现步骤操作，每次都保存不了

**Comment by wonfen** [comment]
就是这么设计的，默认不会打开选项

**Comment by jameouni** [comment]
> 就是这么设计的，默认不会打开选项

可是这个是我新建订阅的时候设置打开的，为啥不保存一下呢。不然不是新建订阅保存了之后，再选这个订阅的编辑信息给他设置一下么？
