### ISSUE TITLE
[Feature] 延迟测试按钮常驻画面

### ISSUE THREAD

**Issue by YiGenCuiHuangGua** [clash-verge-rev/clash-verge-rev#2376]
### 功能描述 / Feature description

将延迟测试按钮常驻在代理页，像Clash一样，无需上滑到顶部即可测试延迟

### 使用场景 / Use case

代理选项太多，需上滑到顶部才能测试延迟

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/2385
