### ISSUE TITLE
[BUG] 后台 CPU、GPU 占用

### ISSUE THREAD

**Issue by ajtn123** [clash-verge-rev/clash-verge-rev#2378]
### 问题描述 / Describe the bug

第一次打开 Clash Verge 面板后，即使关闭，WebView2 管理器也会持续占用 CPU、GPU 资源。如果静默启动，且从未打开过面板，则不会出现占用。
![屏幕截图 2024-12-15 141015](https://github.com/user-attachments/assets/c47ad288-4cc1-4a7a-ba43-59853a04831a)

### 软件版本 / Verge Version

在 v2.0.2 发现。升级到 24/12/15 14:10 下载的 alpha 版本后仍然存在。

### 复现步骤 / To Reproduce

启动 Clash Verge，关闭面板。
或静默启动 Clash Verge，打开面板后关闭。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 24H2 26100.2605

### 日志 / Log

[Verge.log](https://github.com/user-attachments/files/18139150/2024-12-15-1419.log)
[Service.log](https://github.com/user-attachments/files/18139151/2024-12-15-1419.log)

**Comment by Tychristine** [comment]
@ajtn123 
有占用才是正常的，因为关闭按钮就是最小化按钮
这一点在版本发行说明【NOTICE】当中也有提到  https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v2.0.2

**Comment by ajtn123** [comment]
> 因 Tauri 2.0 底层 bug，关闭窗口后保留webview进程，优点是再次打开面板更快，缺点是内存使用略有增加

并不只是内存呃。

**Comment by Tychristine** [comment]
@ajtn123 
![image](https://github.com/user-attachments/assets/9215b9dd-c33e-4a7b-9852-d1e3ccf11b28)
这是我关闭流量图显后的占用

**Comment by ajtn123** [comment]
@Tychristine 我这边的占用上面有发，看来内存占用更少，但是有持续的cpu、gpu占用。

**Comment by Tychristine** [comment]
@ajtn123 
还是那个原因，因为Tauri的窗口问题，verge的行为并不会实际关闭窗口，只会藏在后台。
CPU/GPU占用应该是从流量图形显示和实时流量速率显示这两个地方来的.
*或许还有一点点优化空间*

**Comment by ajtn123** [comment]
关闭流量图显之后就几乎完全没有占用了...或许应该把这个功能在修复之前默认关闭。

**Comment by Honghe** [comment]
> @ajtn123 有占用才是正常的，因为关闭按钮就是最小化按钮 这一点在版本发行说明【NOTICE】当中也有提到 https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v2.0.2

> 因 Tauri 2.0 底层 bug，关闭窗口后保留webview进程 ...

@Tychristine  Which bug of Tauri?

**Comment by Tychristine** [comment]
@Honghe 
Hi, thanks for your attention.
In this commit 545ea16 the developer described that 
> fix: change the window close to minimize the window.
there is currently an error in the tauri library.

In an earlier historical version, probably after close the window and it will not restart WebView2 Window when re-open dashboard.
