### ISSUE TITLE
[Feature]有的机场不提供yaml

### ISSUE THREAD

**Issue by bingmatv** [clash-verge-rev/clash-verge-rev#2379]
### 功能描述 / Feature description

机场不提供yaml，自动转换为yaml

### 使用场景 / Use case

https://xbsj9728.space 不提供yaml，不知道什么格式（在提完issue之后找到了西部世界有yaml，但还是希望添加一下自动转换。）

**Comment by Tychristine** [comment]
Clash Mihomo的Provider可以接受URL/Base64<URL>/YAML
