### ISSUE TITLE
macOS下系统代理开关和守卫不起作用

### ISSUE THREAD

**Issue by SkyYkb** [clash-verge-rev/clash-verge-rev#238]
### Describe the bug

在 macOS 14.3 Beta (23D5051b) 上运行的 Clash Verge Rev 无法通过应用内开关切换系统代理状态，守卫功能也不起作用。

### To Reproduce

None

### Platform

MacOS

### System Version

macOS 14.3 Beta (23D5051b)

### Software Version

1.4.7

**Comment by wonfen** [comment]
需要更多信息。

**Comment by krwu** [comment]
遇到同样的问题。

系统：Intel Macbook 14.2.1 (23C71)
Clash Verge Dev v1.4.10
内核：v1.18.0 Meta（换内核也试过）

症状：
1. 只开启系统代理
2. Wifi 的设置里代理全都是关闭的，上网也没有走代理。
3. 观察软件的托盘菜单或者主界面设置页，会看到系统代理开关隔一小会儿就开启单立刻就关闭（菜单是打勾，立刻就取消）。
4. 设置系统代理守卫与不设置症状一样。


设置 TUN 模式，系统代理关闭：可以走代理上网，但菜单栏的“系统代理”依然会间断性地打勾，然后就取消掉。但是系统代理始终都是没有的。

**Comment by wonfen** [comment]
在某些特定的mac系统环境下会出现这样的问题，还未找到原因。

楼上出现问题的，能否提供详细的日志？

**Comment by Akiyama2408** [comment]
同样的问题，按了系统代理，但是还是没走代理上网，有大佬知道啥问题不？

**Comment by wonfen** [comment]
新版本添加了日志输出，请安装最新版，在“设置”菜单中，打开“应用目录”，文本编辑器编辑verge.yaml文件，把app_log_level: 修改为 app_log_level: debug

**Comment by wonfen** [comment]
> 遇到同样的问题。
> 
> 系统：Intel Macbook 14.2.1 (23C71) Clash Verge Dev v1.4.10 内核：v1.18.0 Meta（换内核也试过）
> 
> 症状：
> 
> 1. 只开启系统代理
> 2. Wifi 的设置里代理全都是关闭的，上网也没有走代理。
> 3. 观察软件的托盘菜单或者主界面设置页，会看到系统代理开关隔一小会儿就开启单立刻就关闭（菜单是打勾，立刻就取消）。
> 4. 设置系统代理守卫与不设置症状一样。
> 
> 设置 TUN 模式，系统代理关闭：可以走代理上网，但菜单栏的“系统代理”依然会间断性地打勾，然后就取消掉。但是系统代理始终都是没有的。

目前发现大概率是因为没有授权导致的，终端执行下面命令：

`sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app`

**Comment by freejool** [comment]
MacOS ARM64 14.3.1 
Clash Verge 1.5.3
出现同样问题。

没有不过遇到
> 3. 观察软件的托盘菜单或者主界面设置页，会看到系统代理开关隔一小会儿就开启单立刻就关闭（菜单是打勾，立刻就取消）。

运行了`sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app`问题依旧

日志等级设为trace后
```
2024-02-23 09:50:58 TRACE [tao::platform_impl::platform::window_delegate] - Triggered `windowDidBecomeKey:`
2024-02-23 09:50:58 TRACE [tao::platform_impl::platform::window_delegate] - Completed `windowDidBecomeKey:`
2024-02-23 09:50:58 TRACE [delay_timer::timer::timer_core] - second_hand: 364, timestamp: 1708653058, task_ids: []
2024-02-23 09:50:59 DEBUG [sysproxy::macos] - Use network service: Wi-Fi
2024-02-23 09:50:59 DEBUG [sysproxy::macos] - Setting SOCKS proxy
2024-02-23 09:50:59 DEBUG [sysproxy::macos] - Setting HTTP proxy
2024-02-23 09:50:59 DEBUG [sysproxy::macos] - Setting HTTPS proxy
2024-02-23 09:50:59 DEBUG [sysproxy::macos] - Setting bypass domains
2024-02-23 09:50:59 TRACE [delay_timer::timer::timer_core] - second_hand: 365, timestamp: 1708653059, task_ids: []
2024-02-23 09:51:00 TRACE [tao::platform_impl::platform::window_delegate] - Triggered `windowDidResignKey:`
2024-02-23 09:51:00 TRACE [tao::platform_impl::platform::window_delegate] - Completed `windowDidResignKey:`
2024-02-23 09:51:00 TRACE [delay_timer::timer::timer_core] - second_hand: 366, timestamp: 1708653060, task_ids: []
```

**Comment by wonfen** [comment]
> MacOS ARM64 14.3.1 Clash Verge 1.5.3 出现同样问题。
> 
> 没有不过遇到
> 
> > 3. 观察软件的托盘菜单或者主界面设置页，会看到系统代理开关隔一小会儿就开启单立刻就关闭（菜单是打勾，立刻就取消）。
> 
> 运行了`sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app`问题依旧
> 
> 日志等级设为trace后
> 
> ```
> 2024-02-23 09:50:58 TRACE [tao::platform_impl::platform::window_delegate] - Triggered `windowDidBecomeKey:`
> 2024-02-23 09:50:58 TRACE [tao::platform_impl::platform::window_delegate] - Completed `windowDidBecomeKey:`
> 2024-02-23 09:50:58 TRACE [delay_timer::timer::timer_core] - second_hand: 364, timestamp: 1708653058, task_ids: []
> 2024-02-23 09:50:59 DEBUG [sysproxy::macos] - Use network service: Wi-Fi
> 2024-02-23 09:50:59 DEBUG [sysproxy::macos] - Setting SOCKS proxy
> 2024-02-23 09:50:59 DEBUG [sysproxy::macos] - Setting HTTP proxy
> 2024-02-23 09:50:59 DEBUG [sysproxy::macos] - Setting HTTPS proxy
> 2024-02-23 09:50:59 DEBUG [sysproxy::macos] - Setting bypass domains
> 2024-02-23 09:50:59 TRACE [delay_timer::timer::timer_core] - second_hand: 365, timestamp: 1708653059, task_ids: []
> 2024-02-23 09:51:00 TRACE [tao::platform_impl::platform::window_delegate] - Triggered `windowDidResignKey:`
> 2024-02-23 09:51:00 TRACE [tao::platform_impl::platform::window_delegate] - Completed `windowDidResignKey:`
> 2024-02-23 09:51:00 TRACE [delay_timer::timer::timer_core] - second_hand: 366, timestamp: 1708653060, task_ids: []
> ```

目前已经发现问题的原因了；你mac电脑之前是不是删除过网络配置，然后新加了一个。导致2个名称不一样。正在想办法修复。

**Comment by freejool** [comment]
请问哪里可以看到网络配置的名称，我有办法手动修复吗？

**Comment by wonfen** [comment]
> 请问哪里可以看到网络配置的名称，我有办法手动修复吗？

等我们后续更新，现在你可以手动在网络设置里配置代理。或者用浏览器的代理插件。

**Comment by fan2** [comment]
macOS 下可以保存脚本 networksetup_proxy.sh，在命令行导入后调用函数，查看/设置/启用系统代理。

```Shell
#!/bin/bash

################################################################################
# macOS 上调用 scutil --proxy 查看网络代理；调用 networksetup 设置系统全局代理
# Usage：
#   1. 在命令行 source 导入该脚本，调用相关函数查看、设置、启用、禁用代理
#   2. 请按需自行修改网络服务名（networkservice）、domain 和 port
################################################################################

networkservice='Wi-Fi'

# 查看代理状态
show_proxy() {
    echo '----------------------------------------'
    echo 'scutil --proxy:'
    scutil --proxy
    echo '----------------------------------------'
    echo '1. http proxy:'
    networksetup -getwebproxy $networkservice
    echo '----------------------------------------'
    echo '2. https proxy:'
    networksetup -getsecurewebproxy $networkservice
    echo '----------------------------------------'
    echo '3. socks proxy:'
    networksetup -getsocksfirewallproxy $networkservice
    # cat /Library/Preferences/SystemConfiguration/preferences.plist
}

# 设置系统代理，默认自动启动
# 或只在命令行设定代理：export http_proxy=http://127.0.0.1:7890 https_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
set_proxy() {
    # for Clash
    sudo networksetup -setwebproxy $networkservice 127.0.0.1 7890
    sudo networksetup -setsecurewebproxy $networkservice 127.0.0.1 7890
    sudo networksetup -setsocksfirewallproxy $networkservice 127.0.0.1 7890
    scutil --proxy
}

# 启动代理
enable_proxy() {
    sudo networksetup -setwebproxystate $networkservice on
    sudo networksetup -setsecurewebproxystate $networkservice on
    sudo networksetup -setsocksfirewallproxystate $networkservice on
    scutil --proxy
}

# 停止代理
disable_proxy() {
    sudo networksetup -setwebproxystate $networkservice off
    sudo networksetup -setsecurewebproxystate $networkservice off
    sudo networksetup -setsocksfirewallproxystate $networkservice off
    scutil --proxy
}
```

**Comment by wonfen** [comment]
1.5.10及以后版本修复了这个问题了，再试试。
