### ISSUE TITLE
[Feature] 代理功能按钮位置建议调整一下

### ISSUE THREAD

**Issue by sigeshuo** [clash-verge-rev/clash-verge-rev#2385]
### 功能描述 / Feature description

![image](https://github.com/user-attachments/assets/0a8c9a92-597d-4cb7-a91b-f05962092449)

### 使用场景 / Use case

当节点比较多的时候，定位到在用的节点之后再想测速，就得滚到最上面。要多测几次就得滚好几次。建议优化一下，这一排的按钮，不要跟着列表走。

**Comment by wonfen** [comment]
不会修改，节点连通性测试只是作为节点是否联通的测试参考，不是用来经常点的
