### ISSUE TITLE
[BUG] 开启tun之后ping域名都会返回内网ip

### ISSUE THREAD

**Issue by wdmhydw** [clash-verge-rev/clash-verge-rev#2387]
### 问题描述 / Describe the bug

开启tun之后ping域名都会返回内网ip，导致无法连上我自己的webdav服务器，需要单独对域名添加直连规则才可以正常访问

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

开启tun
开启webdav
无法连接
添加域名直链规则
连接成功

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

22635.4655

### 日志 / Log

[2024-12-17-0914.log](https://github.com/user-attachments/files/18159017/2024-12-17-0914.log)

**Comment by wonfen** [comment]
建议先了解下什么是fakeip
