### ISSUE TITLE
[BUG] Proxies 一片空白

### ISSUE THREAD

**Issue by Barmaid1076** [clash-verge-rev/clash-verge-rev#2389]
### 问题描述 / Describe the bug

Proxies 一片空白
![image](https://github.com/user-attachments/assets/1925fa12-2167-4934-b36a-eba304d8da90)

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

![image](https://github.com/user-attachments/assets/b17621c1-7f30-41a4-bd0b-2e273bb38212)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 10

### 日志 / Log

[2024-12-17-1144.log](https://github.com/user-attachments/files/18159782/2024-12-17-1144.log)

**Comment by wonfen** [comment]
打开设置-->配置目录 备份 后 删除所有文件，重启软件，试试看。估计是内核载入了错误的配置文件启动失败了。

**Comment by Barmaid1076** [comment]
好像重启电脑就可以了
