### ISSUE TITLE
[BUG] 局域网代理功能异常

### ISSUE THREAD

**Issue by dangpengsong** [clash-verge-rev/clash-verge-rev#2390]
### 问题描述 / Describe the bug

软件自带的局域网代理功能异常，相关测试情况如下：
我的电脑ip为192.168.3.254，开放10809端口给局域网电脑使用截图如下
![image](https://github.com/user-attachments/assets/c6fccd6f-e78e-4e70-b17d-160cacd446fc)
![image](https://github.com/user-attachments/assets/4981eba3-69dc-4af4-8646-8fac9e677450)
![image](https://github.com/user-attachments/assets/cad8643a-6bf1-4413-b03d-003432527bc0)
同事电脑ip为192.168.3.140，首先使用命令行测试端口是否开放，然后设置系统代理，截图如下
![image](https://github.com/user-attachments/assets/d2f067e5-e224-4489-a427-b4c89c1885a3)
![image](https://github.com/user-attachments/assets/c173dd74-f324-40a5-b3fa-efde696d5fda)
![image](https://github.com/user-attachments/assets/b3bd2708-5a85-416d-b40f-323eaf5cdcf1)
vmware虚拟机测试亦此
![image](https://github.com/user-attachments/assets/4b5144c0-5f32-4f31-bfe0-b6139a1b2dba)

### 软件版本 / Verge Version

Clash Verge Rev Alpha
![image](https://github.com/user-attachments/assets/84d7f48f-93f5-4156-af81-b0cc120914ad)
Clash Verge Rev v2.0.2

### 复现步骤 / To Reproduce

功能异常，无需特殊设置，即可复现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

版本：win10专业工作站版 版本号：22H2 操作系统内部版本：19045.3803

### 日志 / Log

[2024-12-17-1146.log](https://github.com/user-attachments/files/18159786/2024-12-17-1146.log)

**Comment by wonfen** [comment]
无法复现，我这里一切正常，这个帖子就是用局域网代理给你回复的。

**Comment by dangpengsong** [comment]
> 无法复现，我这里一切正常，这个帖子就是用局域网代理给你回复的。

🤣这..........，我这是要用回1.x版本的节奏吗，1.x版本是正常的

**Comment by wonfen** [comment]
> > 无法复现，我这里一切正常，这个帖子就是用局域网代理给你回复的。
> 
> 🤣这..........，我这是要用回1.x版本的节奏吗，1.x版本是正常的

有可能是内核配置问题，检查下配置，也可以尝试把1.x的内核替换到2.0里尝试。

**Comment by dangpengsong** [comment]
> > > 无法复现，我这里一切正常，这个帖子就是用局域网代理给你回复的。
> > 
> > 
> > 🤣这..........，我这是要用回1.x版本的节奏吗，1.x版本是正常的
> 
> 有可能是内核配置问题，检查下配置，也可以尝试把1.x的内核替换到2.0里尝试。

好的，我试试谢谢
