### ISSUE TITLE
[BUG] 加密订阅url不支持

### ISSUE THREAD

**Issue by LiKai5412** [clash-verge-rev/clash-verge-rev#2391]
### 问题描述 / Describe the bug

使用加密内容的订阅url导入是报"the remote profile data is invalid yaml"错误，用clashX和v2rayNG客户端是可以正常导入节点的,不确定这是bug还是新功能
<img width="927" alt="image" src="https://github.com/user-attachments/assets/0a4be7cb-2b7d-470b-9748-4e824916141f" />

<img width="1426" alt="image" src="https://github.com/user-attachments/assets/314639bd-244a-4296-adaa-999188b9a9bd" />

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

导入加密内容的订阅url

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

sonoma 14.6.1

**Comment by wonfen** [comment]
订阅连接必须是合法的yaml clash配置文件。
机场是通过UA请求投来判断是什么软件获取的订阅。
找你机场的问题吧

**Comment by miaozilong** [comment]
能支持加密吗？

**Comment by Dragon1573** [comment]
> 能支持加密吗？

大概不能，Clash Verge Rev 只是 GUI ，实际功能均由 Mihomo 内核提供，或许 Mihomo 也不会受理这个需求。

如果愿意的话，可以把你的订阅 URL 过一遍 GPG 加密提供给我们进行测试，通过 `https://github.com/<username>.gpg` 这个格式的链接能获取我们的公钥。

> [!TIP]
> 
> 需要说明，图中的那一段内容极大概率不是「加密」，那大概只是一段 Base64 而已。

**Comment by miaozilong** [comment]
不能加密就算了  我想办法在cloudflare的worker里用user-agent来进行判断，我的密码放在user-agent里

**Comment by Dragon1573** [comment]
> 我想办法在cloudflare的worker里用user-agent来进行判断，我的密码放在user-agent里

不建议这样用，`User-Agent` 字面意思是用户代理，这些东西的命名是有规范的。

GitHub RESTful API 和 GraphQL API 在使用 Fine-granted Access Token 或 Classic Personal Access Token 时，是将获取到的 FGAT / CPAT 放到 Headers 的 `Authentication` 字段中，写作 `Authentication: Bearer <access_token>` 的形式[^1]。

个人建议可以仿照这样的形式，用类似 `X-Workers-Authentication` 这样的自定义字段来配置密码。

-----

又或者和面板的通用做法类似，将区分用户的 token 以参数形式直接附加在链接末尾，形如 `/api/v1/subscribe?token=` 。

[^1]: 参见 [对 REST API 进行身份验证 - GitHub 文档](https://docs.github.com/zh/rest/authentication/authenticating-to-the-rest-api?apiVersion=2022-11-28)
