### ISSUE TITLE
[BUG] 安装以后提示 VCRUNTIME140.dll 不存在

### ISSUE THREAD

**Issue by cqh963852** [clash-verge-rev/clash-verge-rev#2392]
### 问题描述 / Describe the bug

我清空磁盘安装了系统。在安装 2.0.2 版本时。会提示正在连接，然后快速闪过去。

启动时候

1. 先弹出来 uninstall-service.exe 的运行提示。

2. 再弹出来 install-service.exe 的运行提示

系统版本如下

版本	Windows 11 专业版
版本号	24H2
安装日期	‎2024/‎12/‎17
操作系统版本	26100.2033
体验	Windows Feature Experience Pack 1000.26100.23.0

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

安装最新 win11 专业版 24h2
再安装 clash-verge 2.0.2

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26100.2033

### 日志 / Log

![屏幕截图 2024-12-17 123815](https://github.com/user-attachments/assets/6b7b43ad-3a8e-4566-b169-10045b5909e4)

![屏幕截图 2024-12-17 123804](https://github.com/user-attachments/assets/d50b4888-0f9a-4e64-91ad-9e4bc2646c6c)

**Comment by cqh963852** [comment]
看起来是因为缺少对应模块。https://answers.microsoft.com/zh-hant/windows/forum/all/vcruntime140dii/e99dbbce-6d1e-44c1-aad1-3e3f28edf227

不确定是否是软件必须运行时。

**Comment by Tychristine** [comment]
https://www.clashverge.dev/faq/windows.html
