### ISSUE TITLE
1.7.5 升级2.0.2后应用打不开

### ISSUE THREAD

**Issue by xiwanglr** [clash-verge-rev/clash-verge-rev#2397]
### 问题描述 / Describe the bug

win10 64位，无管理员权限。
1.7.5 升级2.0.2后应用打不开

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

1.7.5升级到2.0.2

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 专业版  22H2

### 日志 / Log

2024-12-17 15:48:06 INFO - reinstall service
2024-12-17 15:48:06 ERROR - failed to install service with status 1

**Comment by Tychristine** [comment]
```shell
2024-12-17 15:48:06 ERROR - failed to install service with status 1
# 安装服务失败
```
以管理员身份运行安装引导程序，或者手动以管理员身份运行`~/resources/install-service.exe`

**Comment by Tychristine** [comment]
## 如果系统实在不适合用CVR
可以直接用命令行运行
```shell
#查看帮助
verge-mihomo.exe -h
#运行
verge-mihomo.exe -d <指定数据目录>
```

**Comment by xiwanglr** [comment]
嗯，看到安装说明了。没管理员权限。继续用1版本的吧
