### ISSUE TITLE
[BUG] 打开tun模式一段时间后浏览器无法上网

### ISSUE THREAD

**Issue by Purewhiter** [clash-verge-rev/clash-verge-rev#2398]
### 问题描述 / Describe the bug

tun模式打开一段时间后浏览器无法上网，命令行无法ping通域名，但是可以ping通对应的ip地址。此时再同时打开系统代理，浏览器能正常上午，但是命令行依然无法ping通域名。

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

1

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

23H2

### 日志 / Log

time="2024-12-17T18:47:48.8442582+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:47:48.9008221+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:47:49.2840785+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:39221(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:47:49.3334991+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:47:49.5392826+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:39221(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:47:50.3335137+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:47:50.5400228+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:39221(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:47:50.6560783+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:16.6467227+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-17T18:48:16.6472284+08:00" level=debug msg="[DNS] cache hit yes.mojcn.com --> [116.162.172.55] A, expire at 2024-12-17 18:47:32"
time="2024-12-17T18:48:16.6477538+08:00" level=debug msg="[DNS] resolve yes.mojcn.com A from https://dns.alidns.com:443/dns-query"
time="2024-12-17T18:48:16.6477538+08:00" level=debug msg="[DNS] resolve yes.mojcn.com A from tls://223.5.5.5:853"
time="2024-12-17T18:48:16.6477538+08:00" level=debug msg="[DNS] resolve yes.mojcn.com A from tls://223.6.6.6:853"
time="2024-12-17T18:48:16.6477538+08:00" level=debug msg="[DNS] resolve yes.mojcn.com A from https://doh.pub:443/dns-query"
time="2024-12-17T18:48:16.6477538+08:00" level=debug msg="[DNS] resolve dns.alidns.com A from udp://119.29.29.29:53"
time="2024-12-17T18:48:16.6477538+08:00" level=debug msg="[DNS] resolve dns.alidns.com A from udp://223.5.5.5:53"
time="2024-12-17T18:48:16.6477538+08:00" level=debug msg="[DNS] resolve dns.alidns.com A from udp://114.114.114.114:53"
time="2024-12-17T18:48:16.6477538+08:00" level=debug msg="[DNS] resolve doh.pub A from udp://119.29.29.29:53"
time="2024-12-17T18:48:16.6477538+08:00" level=debug msg="[DNS] resolve doh.pub A from udp://223.5.5.5:53"
time="2024-12-17T18:48:16.6477538+08:00" level=debug msg="[DNS] resolve doh.pub A from udp://114.114.114.114:53"
time="2024-12-17T18:48:16.8109939+08:00" level=debug msg="[DNS] resolve doh.pub A from udp://119.29.29.29:53"
time="2024-12-17T18:48:16.8109939+08:00" level=debug msg="[DNS] resolve dns.alidns.com A from udp://119.29.29.29:53"
time="2024-12-17T18:48:16.8109939+08:00" level=debug msg="[DNS] resolve doh.pub A from udp://223.5.5.5:53"
time="2024-12-17T18:48:16.8109939+08:00" level=debug msg="[DNS] resolve dns.alidns.com A from udp://114.114.114.114:53"
time="2024-12-17T18:48:16.8109939+08:00" level=debug msg="[DNS] resolve dns.alidns.com A from udp://223.5.5.5:53"
time="2024-12-17T18:48:16.8109939+08:00" level=debug msg="re-creating the http client due to requesting https://doh.pub:443/dns-query: Get \"https://doh.pub:443/dns-query?dns=AAABAAABAAAAAAAAA3llcwVtb2pjbgNjb20AAAEAAQ\": dns resolve failed: all DNS requests failed, first error: connect failed: dial udp 119.29.29.29:53: connect: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:16.8109939+08:00" level=debug msg="[https://doh.pub:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-12-17T18:48:16.8109939+08:00" level=debug msg="re-creating the http client due to requesting https://dns.alidns.com:443/dns-query: Get \"https://dns.alidns.com:443/dns-query?dns=AAABAAABAAAAAAAAA3llcwVtb2pjbgNjb20AAAEAAQ\": dns resolve failed: all DNS requests failed, first error: connect failed: dial udp 223.5.5.5:53: connect: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:16.8109939+08:00" level=debug msg="[https://dns.alidns.com:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-12-17T18:48:16.8109939+08:00" level=debug msg="[DNS] resolve doh.pub A from udp://114.114.114.114:53"
time="2024-12-17T18:48:17.7362056+08:00" level=debug msg="[DNS] yes.mojcn.com --> [116.162.172.55] A from tls://223.5.5.5:853"
time="2024-12-17T18:48:19.0544581+08:00" level=info msg="[TCP] 198.18.0.1:59368(svchost.exe) --> 23.204.80.230:80 match Match using 节点选择[新加坡-优化]"
time="2024-12-17T18:48:44.2143554+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-17T18:48:44.2331833+08:00" level=debug msg="[Process] find process error for 66.90.98.98: process not found"
time="2024-12-17T18:48:44.2331833+08:00" level=debug msg="[DNS] cache hit yes.mojcn.com --> [116.162.172.55] A, expire at 2024-12-17 18:48:18"
time="2024-12-17T18:48:44.2336959+08:00" level=debug msg="[DNS] resolve yes.mojcn.com A from https://dns.alidns.com:443/dns-query"
time="2024-12-17T18:48:44.2336959+08:00" level=debug msg="[DNS] resolve yes.mojcn.com A from tls://223.6.6.6:853"
time="2024-12-17T18:48:44.2336959+08:00" level=debug msg="[DNS] resolve yes.mojcn.com A from https://doh.pub:443/dns-query"
time="2024-12-17T18:48:44.2337728+08:00" level=debug msg="[DNS] resolve doh.pub A from udp://119.29.29.29:53"
time="2024-12-17T18:48:44.2336959+08:00" level=debug msg="[DNS] resolve yes.mojcn.com A from tls://223.5.5.5:853"
time="2024-12-17T18:48:44.2337728+08:00" level=debug msg="[DNS] resolve doh.pub A from udp://223.5.5.5:53"
time="2024-12-17T18:48:44.2337728+08:00" level=debug msg="[DNS] resolve dns.alidns.com A from udp://223.5.5.5:53"
time="2024-12-17T18:48:44.2337728+08:00" level=debug msg="[DNS] resolve dns.alidns.com A from udp://119.29.29.29:53"
time="2024-12-17T18:48:44.2337728+08:00" level=debug msg="[DNS] resolve dns.alidns.com A from udp://114.114.114.114:53"
time="2024-12-17T18:48:44.2337728+08:00" level=debug msg="[DNS] resolve doh.pub A from udp://114.114.114.114:53"
time="2024-12-17T18:48:44.3764571+08:00" level=debug msg="[DNS] resolve doh.pub A from udp://119.29.29.29:53"
time="2024-12-17T18:48:44.3769794+08:00" level=debug msg="[DNS] resolve dns.alidns.com A from udp://114.114.114.114:53"
time="2024-12-17T18:48:44.3764571+08:00" level=debug msg="[DNS] resolve doh.pub A from udp://223.5.5.5:53"
time="2024-12-17T18:48:44.3764571+08:00" level=debug msg="re-creating the http client due to requesting https://doh.pub:443/dns-query: Get \"https://doh.pub:443/dns-query?dns=AAABAAABAAAAAAAAA3llcwVtb2pjbgNjb20AAAEAAQ\": dns resolve failed: all DNS requests failed, first error: connect failed: dial udp 119.29.29.29:53: connect: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:44.3764571+08:00" level=debug msg="[DNS] resolve doh.pub A from udp://114.114.114.114:53"
time="2024-12-17T18:48:44.3769794+08:00" level=debug msg="[https://doh.pub:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-12-17T18:48:44.3769794+08:00" level=debug msg="[DNS] resolve dns.alidns.com A from udp://223.5.5.5:53"
time="2024-12-17T18:48:44.3769794+08:00" level=debug msg="re-creating the http client due to requesting https://dns.alidns.com:443/dns-query: Get \"https://dns.alidns.com:443/dns-query?dns=AAABAAABAAAAAAAAA3llcwVtb2pjbgNjb20AAAEAAQ\": dns resolve failed: all DNS requests failed, first error: connect failed: dial udp 119.29.29.29:53: connect: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:44.3769794+08:00" level=debug msg="[https://dns.alidns.com:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-12-17T18:48:44.3764571+08:00" level=debug msg="[DNS] resolve dns.alidns.com A from udp://119.29.29.29:53"
time="2024-12-17T18:48:45.0849197+08:00" level=debug msg="[DNS] yes.mojcn.com --> [116.162.172.55] A from tls://223.6.6.6:853"
time="2024-12-17T18:48:46.7401616+08:00" level=info msg="[UDP] 198.18.0.1:10003 --> 66.90.98.98:9993 match Match using 节点选择[新加坡-优化]"
time="2024-12-17T18:48:50.7739275+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-17T18:48:50.7739275+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-17T18:48:50.788687+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:50.7912921+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:39221(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:50.7995781+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:50.801939+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:39221(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:50.8149581+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:50.8181189+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:39221(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:50.8419905+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:39221(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:50.8441502+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:50.862038+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:50.881724+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:39221(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:50.9178033+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:39221(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:51.0011815+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:51.0865326+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:51.1323621+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:51.1909525+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:39221(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:51.5588447+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:39221(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:52.1326767+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:52.3032113+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:39221(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:52.5664701+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:39221(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
time="2024-12-17T18:48:53.1331506+08:00" level=warning msg="[UDP] dial DIRECT (match GeoIP/cn) 198.18.0.1:9993(zerotier-one_x64.exe) --> 114.245.33.144:33811 error: listen udp :0: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."

**Comment by wonfen** [comment]
https://stackoverflow.com/questions/4415175/an-operation-on-a-socket-could-not-be-performed-because-the-system-lacked-suffi

系统问题

**Comment by Purewhiter** [comment]
更新24H2后正常了
