### ISSUE TITLE
[BUG] 单击状态栏图标后出现显示bug

### ISSUE THREAD

**Issue by CaiBai-Fish** [clash-verge-rev/clash-verge-rev#2399]
### 问题描述 / Describe the bug

将托盘点击事件修改为系统代理后，点击图标开关系统代理时会在上方留有一个小方框
![屏幕截图 2024-12-17 205047](https://github.com/user-attachments/assets/959bc7a7-d0be-4049-8e3f-0c69ef05d99f)

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

将托盘点击行为设置为系统代理，然后在点击图标时出现一个无法关闭的小方框
![image](https://github.com/user-attachments/assets/2c002c9e-0215-4225-b803-3711f5eddc94)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 23H2

### 日志 / Log

无相关日志

**Comment by wonfen** [comment]
无法复现，排查系统和webview的问题
