### ISSUE TITLE
导入自建网盘内的配置文化时，提示证书无效，如何导入证书

### ISSUE THREAD

**Issue by flingbird122** [clash-verge-rev/clash-verge-rev#240]
导入网盘内的配置文件，提示证书无效，我把网站证书文件放到应用目录，配置目录，都不行，导入到系统信任证书还是不行，应该放在哪里呢？
![Honeyview_286542956-804998e4-bd7d-4d65-9382-792f8ce257f3](https://github.com/clash-verge-rev/clash-verge-rev/assets/88576440/c769cbfe-2dd8-4c49-8fe3-10767d10857d)

**Comment by MystiPanda** [comment]
更新软件

**Comment by MystiPanda** [comment]
请规范issue格式

**Comment by flingbird122** [comment]
软件已经是最新版本了

**Comment by wonfen** [comment]
你试试能用浏览器正常打开配置文件么？

**Comment by flingbird122** [comment]
> 你试试能用浏览器正常打开配置文件么？

浏览器可以打开
