### ISSUE TITLE
[BUG] Win10中打开面板窗口右侧和底面有白边

### ISSUE THREAD

**Issue by eryaozm** [clash-verge-rev/clash-verge-rev#2403]
### 问题描述 / Describe the bug

Win10中打开面板窗口右侧和底面有白边
![屏幕截图 2024-12-18 094421](https://github.com/user-attachments/assets/4f3ae2ae-028b-4e08-ad53-d5a34edcf75a)

### 软件版本 / Verge Version

2.0.2正式版

### 复现步骤 / To Reproduce

在win10 22h2下重启verge或电脑启动后打开面板会出现截图显示的情况

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10 22h2 build19045.5247

### 日志 / Log

[2024-12-18-0950.log](https://github.com/user-attachments/files/18173549/2024-12-18-0950.log)

**Comment by Tychristine** [comment]
# 请不要重复提交
