### ISSUE TITLE
[BUG] 开机启动顺序太晚，导致钉钉、qq等一系列需要自启动软件无法连接网络

### ISSUE THREAD

**Issue by HalfWater** [clash-verge-rev/clash-verge-rev#2404]
### 问题描述 / Describe the bug

关机时设置了系统代理，设置开机启动后，clash verge的启动顺序晚于qq，钉钉等应用程序，导致每次启动之后，钉钉、qq等程序无法连接网络。

### 软件版本 / Verge Version

win10
clash verge2.0.2

### 复现步骤 / To Reproduce

关机时设置了系统代理，设置开机启动即可。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10 

### 日志 / Log

暂无。

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1822
