### ISSUE TITLE
[BUG] 内存堆积,无法释放

### ISSUE THREAD

**Issue by Rooil** [clash-verge-rev/clash-verge-rev#2406]
### 问题描述 / Describe the bug

在使用脚本的情况下,切换订阅会导致左下角内存一直在上涨,不会得到释放!
切换的次数够多,内存的占用就会越多.但是log里面没有报错

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

在订阅栏,配置全局脚本之后,在两个订阅之间一直切换,会导致内存堆积!

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Sonoma 14.7.1

### 日志 / Log

<img width="929" alt="截屏2024-12-18 10 35 22" src="https://github.com/user-attachments/assets/5260d94f-f7b2-4b6a-a58a-edc1399d686d" />

**Comment by frankYoY** [comment]
@Rooil 有同样的问题，正常切换使用就好，别搞压力测试，一般不会崩

**Comment by Tychristine** [comment]
@Rooil 请问你描述的是谁的内存？是`Clash Verge REV`还是`Clash Mihomo` ?

**Comment by frankYoY** [comment]
内核问题占大头，图1 是打开后正常使用，图2 是多次切换订阅后内存占用增多。
平时正常使用不会如此频繁的切换订阅，别搞极限测试就好
![01](https://github.com/user-attachments/assets/1df2e991-c1f4-4c61-a2df-a264d04b6ae0)
![02](https://github.com/user-attachments/assets/de6e92ba-2218-4e71-acad-cb6802dc9bb6)

**Comment by o88369** [comment]
切换配置好像不会重启内核，是热重载配置文件就会这样~

**Comment by wonfen** [comment]
试试2.0.3 alpha版本，修了一些内存泄露的问题；还有问题发新issue
