### ISSUE TITLE
[Feature] 在系统代理模式下如何设置IPv6绕过

### ISSUE THREAD

**Issue by HenryLuoCN** [clash-verge-rev/clash-verge-rev#2407]
### 功能描述 / Feature description

在有些运营商限制了ZeroTier系统分配的IPv4地址访问，想使用IPv6地址穿透访问家里的设备，目前测试不使用Clash代理可以通过IPv6访问，IPv4被电信网络禁用了，移动还可以访问。
现在就想在clash里面设置IPv6绕过，但是设置后不起作用。

### 使用场景 / Use case

按照IPv6的要求，用[]将IPv6地址括起来，在clash里面语法报错，不能保存，去掉括号可以保存，但是不能工作，请问这个功能是否支持，或者正确的格式是怎么写，是否还有其他配置项。

**Comment by Tychristine** [comment]
@HenryLuoCN 
```yaml
- IP-CIDR6,2409:8c5c:110:73::302a/128,DIRECT,no-resolve
```

**Comment by Tychristine** [comment]
https://wiki.metacubex.one/config/rules

**Comment by HenryLuoCN** [comment]
![截图](https://github.com/user-attachments/assets/636f504b-fa22-487a-9902-0c17b7cfc7ee)
我想在这个界面添加IPv6。
机场支持订阅，有yaml文件，是不是在这个全局配置这里加IPv6？但是好像不起作用，而且导致所有的代理都没了，请问是在哪里可以单独添加一个IPv6的绕过代理规则？谢谢
![扩展](https://github.com/user-attachments/assets/863010a4-6539-42f5-929b-47e8a88fb9ce)

**Comment by Tychristine** [comment]
### 单独添加扩展配置[规则]？
右键配置选项卡，edit rules，添加IP-CIDR规则,
> 注意事项：填写的IP地址，必须写完整掩码，如上图所示就是写错的. 正确填写 `240e:111:222:333:444:55:66:b06b/128`   

并勾选 `no-resolve`
填写好后点击`PREPPEND RULE`添加前置规则.

**Comment by HenryLuoCN** [comment]
> ### 单独添加扩展配置[规则]？
> 右键配置选项卡，edit rules，添加IP-CIDR6规则,
> 
> > 注意事项：填写的IP地址，必须写完整掩码，如上图所示就是写错的. 正确填写 `240e:111:222:333:444:55:66:b06b/128`
> 
> 并勾选 `no-resolve` 填写好后点击`PREPPEND RULE`添加前置规则.

解决了，非常感谢，又get新技能了。
