### ISSUE TITLE
[BUG] 使用 UWP工具 保存时提示: failed to set IsolationExemptu AppContrainers;call retruned 0x57

### ISSUE THREAD

**Issue by iAsuma** [clash-verge-rev/clash-verge-rev#2415]
### 问题描述 / Describe the bug

使用 UWP工具 点击save changes，提示错误   failed to set IsolationExemptu AppContrainers;call retruned 0x57
[](url)
![errr](https://github.com/user-attachments/assets/f17cbba5-d465-4a15-ac0e-df0564424957)

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

1. 打开 UWP工具 
2. 点击 exempt ALL 

3. 点击Save changes

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

。。。

**Comment by iAsuma** [comment]
错误截图

**Comment by wonfen** [comment]
这个是工具的报错，检查系统问题

**Comment by fangzc1** [comment]
> 这个是工具的报错，检查系统问题

请问检查系统什么问题，即使我使用管理员启动的软件，也遇到了这个问题

**Comment by buzzed12** [comment]
> > 这个是工具的报错，检查系统问题
> 
> 请问检查系统什么问题，即使我使用管理员启动的软件，也遇到了这个问题

可以全选之后逐一unchecked不同的uwp应用，直到保存时不再弹出这个弹窗。

**Comment by person2217** [comment]
回复一下，我找到是这个

![Image](https://github.com/user-attachments/assets/07167e7b-8997-45b6-b585-f28ab3cbba99)

**Comment by gaoqiangks** [comment]
同样的问题。 记录一下，帮别人节省一些时间。 我的是onedrive， 把onedrive取消选中后可以了

**Comment by chnzzy** [comment]
+1 但我的是这个

![Image](https://github.com/user-attachments/assets/c38d2625-66da-4c3e-bc63-bd2001772f30)

**Comment by ximohhtl** [comment]
现在一些应用好像走系统代理了，就会报错这个，我的是netflix报错，也是走系统代理了不用开uwp应用回环

**Comment by ReikoMari** [comment]
我的是手机连接

**Comment by sharesk** [comment]
<img width="1044" height="333" alt="Image" src="https://github.com/user-attachments/assets/6887b2dd-67de-4196-8a1b-fcf40588f5d5" />
我的是这个，补充一下

**Comment by AsahiLove** [comment]
<img width="242" height="41" alt="Image" src="https://github.com/user-attachments/assets/cc71f8da-9185-49b3-b770-ed6c48fe6f91" />

**Comment by SuperYuJi** [comment]
<img width="719" height="316" alt="Image" src="https://github.com/user-attachments/assets/77296864-16a0-4f2a-994a-3400b203fc16" />

我的是这个，补充一下

**Comment by OWow666** [comment]
<img width="759" height="231" alt="Image" src="https://github.com/user-attachments/assets/589d15f2-5002-4194-8c25-c64ef38b2174" />
我的是这个补充一下

**Comment by hellowind777** [comment]
我的竟然是XBOX，取消勾选应用后，关闭软件再重新打开又可以勾选了

**Comment by LyonWu21** [comment]
<img width="761" height="232" alt="Image" src="https://github.com/user-attachments/assets/0d3b6711-4dc8-4525-bf55-acead30d5dfd" />
我的是这个

**Comment by Anling20** [comment]
<img width="761" height="382" alt="Image" src="https://github.com/user-attachments/assets/fcc6c6ec-e38c-43ea-8c8c-c17092c8a305" />
my

**Comment by gyc123456-1** [comment]
我的是这个
<img width="237" height="47" alt="Image" src="https://github.com/user-attachments/assets/77b740a4-08d8-4b68-82b5-1074d056bcb0" />
