### ISSUE TITLE
[UI Optimization] Keep the group header bar fixed to the top when the user scrolls past this group. Like CFW does.

### ISSUE THREAD

**Issue by Kane-Kuroneko** [clash-verge-rev/clash-verge-rev#2418]
### 功能描述 / Feature description

Keep the group header bar fixed to the top when the user scrolls past this group. Like CFW does.
![image](https://github.com/user-attachments/assets/8f4fb993-4860-4e94-a25d-c1c0a4293dbc)

### 使用场景 / Use case

It's inconvenient when testing a long group, as I have to scroll up repeatedly to reach the top of the group.

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/792
