### ISSUE TITLE
[BUG] steam下载游戏，系统代理关闭下载仍然是走的代理

### ISSUE THREAD

**Issue by G-yukun** [clash-verge-rev/clash-verge-rev#2419]
### 问题描述 / Describe the bug

在开启代理使用steam下载游戏时关闭系统代理，下载流量依然走的是机场

### 软件版本 / Verge Version

Verge版本v2.0.2，内核版本v1.19.0 Mihomo

### 复现步骤 / To Reproduce
1，使用代理登录steam
2，steam下载地区选择香港（在使用clash代理香港节点登录，下载地区会自动变为香港）
3，打开系统代理
4，开始下载
5，关闭系统代理

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版24H2

### 日志 / Log

[2024-12-20-2127.log](https://github.com/user-attachments/files/18212186/2024-12-20-2127.log)

**Comment by G-yukun** [comment]
> ### 问题描述 / Describe the bug
> 在开启代理使用steam下载游戏时关闭系统代理，下载流量依然走的是机场
> 
> ### 软件版本 / Verge Version
> Verge版本v2.0.2，内核版本v1.19.0 Mihomo
> 
> ### 复现步骤 / To Reproduce
> 1，使用系统代理登录steam2，steam下载地区选择香港（在使用clash代理香港节点登录，下载地区会自动变为香港） 3，打开系统代理 4，开始下载 5，关闭系统代理
> 
> ### 操作系统 / OS
> Windows
> 
> ### 操作系统版本 / OS Version
> Windows 11 专业版24H2
> 
> ### 日志 / Log
> [2024-12-20-2127.log](https://github.com/user-attachments/files/18212186/2024-12-20-2127.log)

**Comment by G-yukun** [comment]
> ### 问题描述 / Describe the bug
> 在开启代理使用steam下载游戏时关闭系统代理，下载流量依然走的是机场
> 
> ### 软件版本 / Verge Version
> Verge版本v2.0.2，内核版本v1.19.0 Mihomo
> 
> ### 复现步骤 / To Reproduce
> 1，使用系统代理登录steam2，steam下载地区选择香港（在使用clash代理香港节点登录，下载地区会自动变为香港） 2，打开系统代理 3，开始下载 4，关闭系统代理
> 
> ### 操作系统 / OS
> Windows
> 
> ### 操作系统版本 / OS Version
> Windows 11 专业版24H2
> 
> ### 日志 / Log
> [2024-12-20-2127.log](https://github.com/user-attachments/files/18212186/2024-12-20-2127.log)

**Comment by Tychristine** [comment]
1.关闭代理，但已有的TCP连接没有释放
2.自己用规则分流SteamCDN可永久避免
3.规则配置参考教程 realiti.me
