### ISSUE TITLE
[Feature] Keep the last selected tab when clicking the tray icon

### ISSUE THREAD

**Issue by istanb84** [clash-verge-rev/clash-verge-rev#242]
### Is your feature request related to a problem? Please describe.

Sometimes I want to know which connection is currently using data traffic，but when I clicking the tray icon to open the interface,  it always returned to the "Proxies" tab, kind of annoying.

### Describe the solution you'd like

When clicking the tray icon to open the interface, keep the last selected tab's state instead of returning to the "Proxies" tab every time. 

### Describe alternatives you've considered

Maybe add a selection in "Settings -> Tray Click Event", "Last Tab"?

Thanks in advanced!

**Comment by wonfen** [comment]
看下这个是你要的功能吗？
https://github.com/clash-verge-rev/clash-verge-rev/commit/15e88946141ee1bc8613451d90109a772c3eb1d6

**Comment by istanb84** [comment]
> 看下这个是你要的功能吗？ [15e8894](https://github.com/clash-verge-rev/clash-verge-rev/commit/15e88946141ee1bc8613451d90109a772c3eb1d6)

It's not exactly what I'm referring to, but it works for me in some way.

I mean, if someone wants to switch to another tab, they will need to go to settings every time.
But it's ok for me now.
