### ISSUE TITLE
[BUG] 不知从哪个版本开始快捷键不起作用了

### ISSUE THREAD

**Issue by 764069075** [clash-verge-rev/clash-verge-rev#2422]
### 问题描述 / Describe the bug

设置界面设置完毕热键，不起作用

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

1.设置界面
2.热键设置
3.设置快捷键Ctrl+Alt+D
4.使用快捷键

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 专业工作站版

### 日志 / Log

[2024-12-21-0720.log](https://github.com/user-attachments/files/18217677/2024-12-21-0720.log)

**Comment by wonfen** [comment]
无法复现
![image](https://github.com/user-attachments/assets/55dc6d3c-7346-4c77-b9cf-398745a15942)

**Comment by fantasywolf** [comment]
热键完全无效
