### ISSUE TITLE
[Feature] 代理不可用通知一下

### ISSUE THREAD

**Issue by wugeyou** [clash-verge-rev/clash-verge-rev#2424]
### 功能描述 / Feature description

代理不可用时，弹窗通知一下

### 使用场景 / Use case

鉴于种种原因，代理组没更新或者有时候需要更新等，导致代理全部 ERROR。这时候能不能弹窗通知一下（代理节点都会定时健康检查），好切换代理或者手动更新订阅？

**Comment by wonfen** [comment]
没有计划
