### ISSUE TITLE
[BUG] Tauri 2.0 在 win10 下的边框显示问题

### ISSUE THREAD

**Issue by LuiScreaMed** [clash-verge-rev/clash-verge-rev#2425]
### 问题描述 / Describe the bug

更新到 Tauri 2.0 的 Clash Verge，由于 Tauri 2.0 本身的 bug，在 win10 中会出现边框问题（出现了本不应该出现的一个像素的边框）：

![Snipaste_2024-12-22_15-37-08](https://github.com/user-attachments/assets/b4ce30f0-8205-4292-b976-06f0ce4ef11d)

根据 [该issue中的评论](https://github.com/tauri-apps/tauri/issues/11654#issuecomment-2524996207) 和 [该issue中的评论](https://github.com/tauri-apps/tauri/issues/11088#issuecomment-2367920670)，禁用窗口的 shadow 可解决。

是个细枝末节的小问题。

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

在 win10 22H2 中，开启 Clash Verge v2.0.2，在开启的窗口可以看到出现边框问题

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

版本	Windows 10 企业版 版本号	22H2 安装日期	‎2024/‎10/‎6 操作系统内部版本	19045.5131 体验	Windows Feature Experience Pack 1000.19060.1000.0

### 日志 / Log

[2024-12-22-1544.log](https://github.com/user-attachments/files/18221126/2024-12-22-1544.log)

**Comment by wonfen** [comment]
修了 https://github.com/clash-verge-rev/clash-verge-rev/issues/2425

**Comment by LuiScreaMed** [comment]
开发人员已提交修复，所以关闭此issue
