### ISSUE TITLE
[Feature] 2.0版本后clash-service会和Apex Legends的反作弊冲突

### ISSUE THREAD

**Issue by iGnoramu4** [clash-verge-rev/clash-verge-rev#2430]
### 功能描述 / Feature description

希望可以在关闭程序后自动结束clash-service。或者跟respawn联系解除对clash-service的屏蔽？后者似乎不太现实。

### 使用场景 / Use case

因为2.0版本后即便关闭程序，clash-service依然会在后台运行，而Apex Legends的宏软件屏蔽把这个程序认为是一个可能作弊的程序。需要手动进入任务管理器结束进程才能打开游戏。
![MVIMG_20241217_183103](https://github.com/user-attachments/assets/f87d16a9-f8b9-473a-8118-786ff2b64de9)

**Comment by wonfen** [comment]
给游戏开发商反馈
