### ISSUE TITLE
[BUG] 在关闭程序的界面后，后台仍然在运行UI

### ISSUE THREAD

**Issue by bolieriniefu** [clash-verge-rev/clash-verge-rev#2431]
### 问题描述 / Describe the bug

![QQ截图20241222231200](https://github.com/user-attachments/assets/0404d205-3031-4279-94e2-8749da6dfc59)
如果程序是静默启动，则后台没有这个webview2，打开界面再关闭界面，后台这个webview2就一直存在，请问是windows11的问题还是什么问题呢？

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

打开界面，关闭界面，查看CPU占用

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

没有log捏

**Comment by wonfen** [comment]
就是这样设计的
