### ISSUE TITLE
[BUG]  请问我该 如何选择虚拟网卡模式 达到性能最佳

### ISSUE THREAD

**Issue by Super1Windcloud** [clash-verge-rev/clash-verge-rev#2432]
### 问题描述 / Describe the bug

![图片](https://github.com/user-attachments/assets/53fda220-186e-4b46-94f4-fee1ae02fdd1)

### 软件版本 / Verge Version

.

### 复现步骤 / To Reproduce

.

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

.

**Comment by Super1Windcloud** [comment]
##  并且我有一点小问题, 恳切希望各位大佬为我指点迷津 ,    

###  System 模式是默认全局吗  ?  此时,  代理界面的规则模式是否还有作用?  

###  gVisor 这种沙箱环境是否支持 规则和全局之间的切换 ? 

### mixed 指定的是TCP 使用 system 模式，UDP 使用 gVisor 模式吗   ,  还是默认使用的代理规则模式(国内直连, 国外代理)?

**Comment by wonfen** [comment]
参考内核文档： https://wiki.metacubex.one/config/inbound/tun/#stack
