### ISSUE TITLE
[BUG] deepin 23 下 v2.0.2版本  托盘显示两个 

### ISSUE THREAD

**Issue by MangerLe** [clash-verge-rev/clash-verge-rev#2434]
### 问题描述 / Describe the bug

deepin 23 下 v2.0.2版本  托盘显示两个 
![image](https://github.com/user-attachments/assets/b875dcd1-faa9-42cb-8fa0-0a5040da6efc)

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

启动服务就行

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

deepin 23

### 日志 / Log

没有错误日志

**Comment by Zheng-Shuo** [comment]
一样的问题
![1735004419995](https://github.com/user-attachments/assets/dac4677c-84bb-4bdb-bda3-51299c3960e9)
![1735004505286](https://github.com/user-attachments/assets/e83040e0-a4e7-40cc-9921-32790034dd56)
![1735004537563](https://github.com/user-attachments/assets/9e78f761-28af-4582-b558-473480675371)

**Comment by Tychristine** [comment]
@Zheng-Shuo 
我真心建议你搜一下[常见问题](https://www.clashverge.dev/faq/macos.html#macos_1)再问

**Comment by Zheng-Shuo** [comment]
@Tychristine 试了并没有什么效果
