### ISSUE TITLE
[BUG] Debian无法正常启动v2.0.x

### ISSUE THREAD

**Issue by SkyEye-FAST** [clash-verge-rev/clash-verge-rev#2435]
### 问题描述 / Describe the bug

直到更新至v1.7.7都一切正常。
![image](https://github.com/user-attachments/assets/2722a1d9-5c1f-480f-bb55-9bcf6d0ef5ae)

但是安装v2.0.x的任意版本，都会无法启动：
![image](https://github.com/user-attachments/assets/1de4a7b2-fa3a-4505-91b8-30b6994649a2)
```
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/sh' as the super user
Authenticating as: skyeyefast
Password: 
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
```

使用`sudo`或者`sudo su`启动报错如下：
![image](https://github.com/user-attachments/assets/4d0f85b2-53c8-40eb-b2ec-4e93c2bc6fae)
```
No protocol specified


(clash-verge:20159): Gtk-WARNING **: 16:33:37.629: cannot open display: :0
```
已知输入密码正确，且pkttyagent正常情况应如下：
![image](https://github.com/user-attachments/assets/e52e59c9-58e8-41c6-b816-7bf12149f286)

### 软件版本 / Verge Version

v2.0.x

### 复现步骤 / To Reproduce

- `sudo dpkg -i ./Clash.Verge_2.0.2_amd64.deb`
- `clash-verge`

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Debian bookworm 12.8 x86_64, Wayland

### 日志 / Log

无法正常启动，不存在日志。

**Comment by wonfen** [comment]
发issue前建议问下AI

这个错误显示是 PolicyKit 认证失败的问题。从错误信息来看，主要有以下几点：

1. 系统试图以超级用户权限运行 `/usr/bin/sh`
2. 使用 `skyeyefast` 用户进行认证
3. 出现 "No session for cookie" 的 PolicyKit 守护进程错误
4. 认证最终失败，提示 "Not authorized"

要解决这个问题，你可以尝试以下方法：

1. 确保你的用户属于正确的组（通常是 sudo 组）：
```bash
sudo usermod -aG sudo skyeyefast
```

2. 重新安装或重置 PolicyKit：
```bash
sudo apt-get install --reinstall policykit-1
```

3. 检查并修复 PolicyKit 配置：
```bash
sudo mkdir -p /etc/polkit-1/localauthority
sudo chmod 750 /etc/polkit-1/localauthority
```

4. 重启 PolicyKit 服务：
```bash
sudo systemctl restart polkit
```

5. 如果还是不行，可以尝试注销后重新登录，或直接重启系统

如果以上方法都不能解决问题，建议检查：
- 系统日志以获取更详细的错误信息：`journalctl -xe`
- PolicyKit 的权限配置文件
- 确认你的用户账户状态是否正常

你是在执行什么操作时遇到这个错误的？这可能会帮助我提供更具体的解决方案。
