### ISSUE TITLE
[Feature] 是否提供Docker镜像？

### ISSUE THREAD

**Issue by oyontalas** [clash-verge-rev/clash-verge-rev#2437]
### 功能描述 / Feature description

是否提供可供下载的Docker镜像？

### 使用场景 / Use case

可用于隔离的环境，一键安装使用。

**Comment by Tychristine** [comment]
这是客户端软件

**Comment by wonfen** [comment]
docker安装后代理docker内的网络？

**Comment by 3213778453** [comment]
> docker安装后代理docker内的网络？

是也不是，可能是因为没有GUI才想要docker，说实在我也想要docker版的。

**Comment by wonfen** [comment]
运行在docker内的代理如何代理外部网络？

**Comment by oyontalas** [comment]
已解决：https://hub.docker.com/r/metacubex/mihomo

**Comment by ouyang-yuxuan** [comment]
> 已解决：https://hub.docker.com/r/metacubex/mihomo

怎么用，没端口说明

**Comment by rebecca554owen** [comment]
@ouyang-yuxuan 参考mihomo配置

**Comment by ouyang-yuxuan** [comment]
> [@ouyang-yuxuan](https://github.com/ouyang-yuxuan) 参考mihomo配置

谢谢老哥，大过年的，新年快乐
