### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 1825016156** [clash-verge-rev/clash-verge-rev#2439]
### 问题描述 / Describe the bug

![屏幕截图 2024-12-24 095037](https://github.com/user-attachments/assets/abc494af-f09b-48a0-8282-310339f32388)
这情况不正常吧，“*:\******\ClashVerge\verge-mihomo.exe" -d C:\******\*****\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev -f C:\******\*******\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev\clash-verge.yaml

### 软件版本 / Verge Version

V2.0.2

### 复现步骤 / To Reproduce

无，直接就被攻击

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 24H2

### 日志 / Log

作者可以联系一下我，我可以给你完整的火绒日志

**Comment by Tychristine** [comment]
@1825016156 
给火绒官方报告误杀现象，提交误杀样本
