### ISSUE TITLE
[BUG] Tun模式启动后无法连接外网，在适配器里勾选再取消网络共享后恢复正常。

### ISSUE THREAD

**Issue by sleftt** [clash-verge-rev/clash-verge-rev#244]
### Describe the bug

开机第一次开Tun模式时无法联网，日志报错 error: dns resolve failed: couldn't find ip。
打开Tun模式后再在网络适配器的Tun网卡或主网卡的共享设置中勾选“允许其他网络用户通过此计算机的internet连接来连接”并确定，再打开共享设置把刚才勾的选项去掉后，Tun模式正常运作。
只要不关机，操作过一次后重启Clash也能直接打开Tun模式正常使用。

### To Reproduce

开机，打开Clash，打开tun模式，无法连接网络。
打开控制面板-网络和Internet-网络连接，选择主网卡或Tun的虚拟网卡设置勾选“允许其他网络用户通过此计算机的internet连接来连接”并确定。
打开刚才选择的网卡设置，把“允许其他网络用户通过此计算机的internet连接来连接”选项的勾去掉并保存。
Tun模式开始正常运作

### Platform

Windows

### System Version

Windows10 22H2

### Software Version

1.4.8

### Log

mode: rule
mixed-port: 7897
allow-lan: true
log-level: info
secret: ''
external-controller: 127.0.0.1:9097
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 8.8.8.8
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - tls://1.1.1.1:853
  - tls://1.0.0.1:853
  - 101.6.6.6:5353
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
  fake-ip-filter:
  - dns.msftncsi.com
  - www.msftncsi.com
  - www.msftconnecttest.com
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - any:53
  auto-route: true
  interface: 以太网
  auto-detect-interface: true
bind-address: '*'

### Additional Information

用CFW的时候也出现过一样的问题，网上搜到的tun模式问题的dns设置都尝试过了。
https://blog.csdn.net/dededev/article/details/132597018 这个情况比较符合我的问题。电脑设置过SMB局域网共享文件夹到ipad和手机上，不知道是不是因为这个原因。请问这种情况有什么解决办法吗？

**Comment by sleftt** [comment]
2.58打开tun模式，3.00勾选，取消共享设置，随后恢复正常运行。
![1](https://github.com/clash-verge-rev/clash-verge-rev/assets/61189015/d48b40eb-cc0b-48a5-9a74-83ae8931402a)
![2](https://github.com/clash-verge-rev/clash-verge-rev/assets/61189015/783f66d4-4a3f-41a0-883b-18a30673d4af)
![3](https://github.com/clash-verge-rev/clash-verge-rev/assets/61189015/1a5d3855-9dd8-4069-a4e9-7a885ebe9889)

操作前后ipconfig信息对比只有实体网卡的租约时间发生了变化
![4](https://github.com/clash-verge-rev/clash-verge-rev/assets/61189015/09cad286-f1a4-427a-91ef-7304af556497)
![5](https://github.com/clash-verge-rev/clash-verge-rev/assets/61189015/c2f5cf08-8ccf-4e12-afd7-b0c9cd59b9af)

**Comment by svohoyzvozyvs** [comment]
俺也一样

**Comment by Bazinga960825** [comment]
唉我也是这样，每次都要重新勾选取消好麻烦啊

**Comment by sleftt** [comment]
> 唉我也是这样，每次都要重新勾选取消好麻烦啊

只能一个一个排查了，我用老笔记本默认clash配置用tun就没问题，无论是wifi还是连有线网，只能排查自己系统设置了

**Comment by iven13465** [comment]
我也是，最新的1.5.1，前几天使用tun模式还是正常的

**Comment by sleftt** [comment]
> 我也是，最新的1.5.1，前几天使用tun模式还是正常的

如果重启物理网卡能解决，就写个开机自启的批处理文件直接开机重启一遍物理网卡得了。我现在就是这么处理的。

**Comment by 1guts1** [comment]
俺也一样，有个临时的解决方案还好吧

**Comment by 1guts1** [comment]
> > 我也是，最新的1.5.1，前几天使用tun模式还是正常的
> 
> 如果重启物理网卡能解决，就写个开机自启的批处理文件直接开机重启一遍物理网卡得了。我现在就是这么处理的。

唉，为什么用重启物理网卡就没效果呢

**Comment by sleftt** [comment]
> > > 我也是，最新的1.5.1，前几天使用tun模式还是正常的
> > 
> > 
> > 如果重启物理网卡能解决，就写个开机自启的批处理文件直接开机重启一遍物理网卡得了。我现在就是这么处理的。
> 
> 唉，为什么用重启物理网卡就没效果呢

不知道你的情况，我搜了几天同样症状的问题的解决办法我的机器也不适用，

**Comment by 1guts1** [comment]
感谢你给出的方案



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月27日(周二) 下午4:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [clash-verge-rev/clash-verge-rev] [BUG] Tun模式启动后无法连接外网，在适配器里勾选再取消网络共享后恢复正常。 (Issue #244)




 
同样的问题, 我临时写了个脚本自动重置它:
  
首先安装这个module : https://github.com/loxia01/PSInternetConnectionSharing
 
保存下面的脚本, 并且把"WIFI" 改成你的Net Adaptor名字:
  $counter = 0 while ($true) {     $icsConnections = Get-Ics -AllConnections     if ($icsConnections -match "meta") {         Set-Ics Meta 'WIFI'         Disable-Ics         Write-Host "Success!"         break     }     else {         Write-Host "Not Found meta netadaptor."         $counter++     }     if ($counter -ge 500) {         Write-Host "Exiting script after 500 unsuccessful checks."         break     }     Start-Sleep -Seconds 1 }   
在Task scheduler中添加一个task让脚本开机启动
 Program/script 填 powershell
 Add arguments 中填 -NoProfile -ExecutionPolicy Bypass -File D:\clashmeta-TUNnetadaptor-startup.ps1", 路径要换成你自己的
 security option 按下面图2 填
 enable task后重启即可
 1.png (view on web)
  
2.png (view on web)

**Comment by MJRT** [comment]
> 同样的问题, 我临时写了个脚本自动重置它:
> 

把TUN stack 切换到`GVisor` 后我的问题消失了

**Comment by MJRT** [comment]
这个issue可以在我的win11上稳定复现:
- 找到WiFi 的net adapter名称 `Get-NetAdapter`
- admin下执行 ` netsh int ipv4 set interface "WLAN 2" forwarding=enable`  (WLAN2是你的NetAdapter Name)
然后TUN模式下所有的proxy 就都是 ERROR了.
执行上述开启再关闭网络共享的方法就能恢复正常.

**Comment by sczheng189** [comment]
这个问题我也出现了,不知道是系统的问题还是clash的问题,难受

**Comment by mw418** [comment]
同样有此现象
