### ISSUE TITLE
[Feature] 添加对vscode copilot插件的支持

### ISSUE THREAD

**Issue by kyao777** [clash-verge-rev/clash-verge-rev#2440]
### 功能描述 / Feature description

打开vscode时，copilot插件右侧对话功能无法正常使用；
必须关闭系统代理后才能使用；
通过全局，规则，直连都无法连接，只有在设置中关闭系统代理后才可以使用，在uwp中也没有找到对应的选项。

### 使用场景 / Use case

在windows11环境中使用vscode的copilot插件功能

**Comment by wonfen** [comment]
用tun模式试试；
先了解一下copilot插件是否遵循系统代理
