### ISSUE TITLE
[BUG] windows11家庭版tun模式打开无效，已找到解决办法

### ISSUE THREAD

**Issue by dayejiejie** [clash-verge-rev/clash-verge-rev#2443]
### 问题描述 / Describe the bug

换了2.0x和1.6，1.7的版本，发现不管怎么样打开tun mode 都不能联网，于是上网搜索，发现需要手动把mihomo添加到运行通过的防火墙列表

### 软件版本 / Verge Version

V2.0.X

### 复现步骤 / To Reproduce

重装，只打开tun，虚拟网卡启动成功，但是无法联网，手动把mihomo添加到运行通过的防火墙列表，可以联网

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11

### 日志 / Log

无

**Comment by dayejiejie** [comment]
![Uploading PixPin_2024-12-24_16-10-00.png…]()

**Comment by Tychristine** [comment]
Clash Mihomo 文档上有标注该问题和解决办法: https://wiki.metacubex.one/config/inbound/tun/#stack
