### ISSUE TITLE
[Feature] clash-verge-service.exe和Apex Legends的反作弊冲突

### ISSUE THREAD

**Issue by iGnoramu4** [clash-verge-rev/clash-verge-rev#2444]
### 功能描述 / Feature description

Apex会把clash-verge-service.exe标记为可能的作弊程序，导致游戏无法运行。根据报错内容推断，冲突的是Apex的软件屏蔽，而非EAC反作弊。目前2.0.2版本程序关闭后，clash-verge-service.exe依然会在后台运行，希望可以在关闭程序时自动结束进程。或者以开发者名义向EA或respawn工作室联系，请求加入白名单。不过感觉不太现实，除非和他们内部人员认识。而且其他游戏也有可能出现反作弊冲突的问题。
![微信图片_20241224193957](https://github.com/user-attachments/assets/0d1061d0-2557-46ae-9b55-27405643e2ac)

### 使用场景 / Use case

运行游戏时不必再去任务管理器手动结束clash-verge-service.exe

**Comment by Tychristine** [comment]
请向司马のEA反馈
