### ISSUE TITLE
[BUG] Deepin23每次开机启动都要输入密码

### ISSUE THREAD

**Issue by nickolboy** [clash-verge-rev/clash-verge-rev#2447]
### 问题描述 / Describe the bug

每次开机启动都会卸载服务再安装服务，要输入两遍密码

![Snipaste_2024-12-25_09-24-24](https://github.com/user-attachments/assets/54544629-f03b-45f0-b079-bd3351b0ff84)
![Snipaste_2024-12-25_09-24-35](https://github.com/user-attachments/assets/3c92be83-82a0-4ff6-aad2-63bb35cd2722)

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

开机启动

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

deepin23

### 日志 / Log

/

**Comment by qif580231** [comment]
升级最新版本后就这样了，之前的版本没问题。

**Comment by wonfen** [comment]
需要安装服务，看下是不是每次安装后被禁用或者卸载了？

**Comment by nickolboy** [comment]
看了一下，是系统启动时，服务启动比较慢，过一会儿再启动clash-verge-rev，就不会弹
