### ISSUE TITLE
[BUG] 系统代理显示不一致

### ISSUE THREAD

**Issue by wx-dev** [clash-verge-rev/clash-verge-rev#2448]
### 问题描述 / Describe the bug

![image](https://github.com/user-attachments/assets/cdf9ea3d-aa1f-48ed-8e8b-57bdf8e091eb)
![image](https://github.com/user-attachments/assets/78ab398c-3b9a-4149-927e-7a2c5cd01b11)
![image](https://github.com/user-attachments/assets/23e3de6c-60fd-4ebb-9876-726eb90df473)

软件设置里面是打开的但是状态栏显示关闭

### 软件版本 / Verge Version

v2.0.3 alpha 

### 复现步骤 / To Reproduce

打开设置，打开图标面板对比

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

window10

### 日志 / Log

无

**Comment by wonfen** [comment]
无法复现，重启下软件试试，估计是GUI卡了
