### ISSUE TITLE
[BUG] Start TUN listening error: configure tun interface: There was no match for the specified key in the index.

### ISSUE THREAD

**Issue by z-soulx** [clash-verge-rev/clash-verge-rev#2449]
### 问题描述 / Describe the bug

Start TUN listening error: configure tun interface: There was no match for the specified key in the index.
![image](https://github.com/user-attachments/assets/98cdc7fe-b8c5-497f-9c66-6b4ea824c61b)

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

star tun

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 Pro

### 日志 / Log

12-25 11:04:05warning
Start Tun interface timeout: There was no match for the specified key in the index. [retrying 1/3]
12-25 11:04:20warning
Start Tun interface timeout: There was no match for the specified key in the index. [retrying 2/3]
12-25 11:04:35warning
Start Tun interface timeout: There was no match for the specified key in the index. [retrying 3/3]
12-25 11:04:36error
Start TUN listening error: configure tun interface: There was no match for the specified key in the index.
12-25 11:04:36info
Start initial Compatible provider Auto
12-25 11:04:36info
Start initial Compatible provider Proxy
12-25 11:04:36debug
Start New Health Checking {f70b8723-cb6b-4d50-8c38-b96fda19cd41}

**Comment by wonfen** [comment]
发到内核那边问下吧，不知道原因

**Comment by gamma6ray** [comment]
這個問題是因Window 己裝的WinTun Driver 出現Conflict. 我是因為裝了 Wireguard, 只uninstall Wireguard 是不夠的。

要用Window command (admin right) 移除驅動程式


使用以下命令將表格表格中嘅驅動程式清單匯出去文字檔案：
dism /online /get-drivers /format:table > c:\drivers.txt


喺清單入面搵 wintun 或者 wireguard ，然後記低「發佈名稱」 "Published Name"， i.e.

oemXX.inf  , XX stand for Number 


用以下命令移除驅動程式：
pnputil.exe /d oemXX.inf

e.g. pnputil.exe /d oem159.inf
