### ISSUE TITLE
[BUG] 开启tun后无法连接b站直播间网页版

### ISSUE THREAD

**Issue by Ptilopsis01** [clash-verge-rev/clash-verge-rev#2452]
### 问题描述 / Describe the bug

在tun模式开启时，b站网页版直播间无法访问，报错如下图（b站为直连）
将其中的域名以及b站域名均加入到fake-ip-filter中时，可以加载出部分页面元素，但仍然无法加载出直播源
尝试了开关ipv6和严格路由，均无效
![image](https://github.com/user-attachments/assets/c0e5bb3c-a055-42ab-9f3e-861dc331a8fe)

### 软件版本 / Verge Version

2.0.3-alpha

### 复现步骤 / To Reproduce

如上

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26100.2605

### 日志 / Log

[2024-12-25-2244.zip](https://github.com/user-attachments/files/18246585/2024-12-25-2244.zip)

**Comment by wonfen** [comment]
关闭浏览器安全dns，检查配置文件

**Comment by Ptilopsis01** [comment]
前者根本没开，后者部分配置如下：
``
dns:
  use-system-hosts: true
  prefer-h3: true
  default-nameserver:
  - 180.184.1.1
  - 119.29.29.29
  - 223.5.5.5
  ipv6: true
  fake-ip-filter:
  - '*.n.n.srv.nintendo.net'
  - +.stun.playstation.net
  - xbox.*.*.microsoft.com
  - '*.msftncsi.com'
  - '*.msftconnecttest.com'
  - WORKGROUP
  - '*.lan'
  - localhost.ptlogin2.qq.com
  - stun.*.*.*
  - stun.*.*
  - time.windows.com
  - time.nist.gov
  - time.apple.com
  - time.asia.apple.com
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - time1.cloud.tencent.com
  - time.ustc.edu.cn
  - pool.ntp.org
  - ntp.ubuntu.com
  - '*.*.xboxlive.com'
  - speedtest.cros.wr.pvp.net
  - ntp.sjtu.edu.cn
  nameserver:
  - tls://223.5.5.5:853
  - https://223.6.6.6/dns-query
  - https://120.53.53.53/dns-query
  - https://1.1.1.1/dns-query
  nameserver-policy:
    +.tmall.com: 223.5.5.5
    +.taobao.com: 223.5.5.5
    +.alicdn.com: 223.5.5.5
    +.aliyun.com: 223.5.5.5
    +.alipay.com: 223.5.5.5
    +.alibaba.com: 223.5.5.5
    +.bilibili.com: 119.29.29.29
    +.qq.com: 119.29.29.29
    +.tencent.com: 119.29.29.29
    +.weixin.com: 119.29.29.29
    +.qpic.cn: 119.29.29.29
    +.jd.com: 119.29.29.29
    +.hdslb.com: 119.29.29.29
    +.163.com: 119.29.29.29
    +.126.com: 119.29.29.29
    +.126.net: 119.29.29.29
    +.127.net: 119.29.29.29
    +.netease.com: 119.29.29.29
    +.baidu.com: 223.5.5.5
    +.bdstatic.com: 223.5.5.5
    +.bilivideo.+: 119.29.29.29
    +.iqiyi.com: 119.29.29.29
    +.douyinvod.com: 180.184.1.1
    +.douyin.com: 180.184.1.1
    +.douyincdn.com: 180.184.1.1
    +.douyinpic.com: 180.184.1.1
    +.feishu.cn: 180.184.1.1
    +.nexusmods.com: 1.1.1.1
  fallback:
  - https://101.101.101.101/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://208.67.220.220/dns-query
  - tls://1.0.0.1:853
  proxy-server-nameserver:
  - https://doh.pub/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - +.google.com
    - +.facebook.com
    - +.youtube.com
    - +.githubusercontent.com
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 172.29.0.1/16
tun:
  auto-detect-interface: true
  auto-route: true
  device: Clash_verge
  dns-hijack:
  - any:53
  mtu: 1500
  stack: mixed
  strict-route: false
  enable: true
``

**Comment by Ptilopsis01** [comment]
此外，我刚刚尝试回退到2.0.2版本，可以正常访问，因此肯定是2.0.3版本出现了问题

**Comment by wonfen** [comment]
> 此外，我刚刚尝试回退到2.0.2版本，可以正常访问，因此肯定是2.0.3版本出现了问题

把2.0.2的内核替换到2.0.3里，2.0.3都是在修复一些bug；更本没动tun相关的配置

**Comment by Ptilopsis01** [comment]
我刚尝试了给2.02升级1.19.0的内核，仍然是能够正常访问的，只有在2.0.3下无论使用1.19.0还是1.18.10的内核均无法正常加载

**Comment by Ptilopsis01** [comment]
我观察了一下，似乎默认的fake-ip-range这个配置从198.18.0.1/16被修改成了172.29.0.1/16（2.0.2->2.0.3alpha），不知道是不是这个的影响

**Comment by wonfen** [comment]
> 我观察了一下，似乎默认的fake-ip-range这个配置从198.18.0.1/16被修改成了172.29.0.1/16（2.0.2->2.0.3alpha），不知道是不是这个的影响

你的网络环境中有这个ip吗？

**Comment by Ptilopsis01** [comment]
不太清楚，我记得这个ip不是虚拟网卡的ip吗

**Comment by Ptilopsis01** [comment]
那应该是没有的，而且这个问题只在访问b站直播的时候有，b站本身我也是直连的

**Comment by wonfen** [comment]
tg联系我远程看看 https://t.me/wonfen_bot

**Comment by Ptilopsis01** [comment]
碰到这个问题的可以尝试清除一下cookies，大概率可以解决
