### ISSUE TITLE
[BUG] Unable to use PROXY in rule configurations of Global Extended Config/Script

### ISSUE THREAD

**Issue by iliya-pro** [clash-verge-rev/clash-verge-rev#2454]
### 问题描述 / Describe the bug

Unable to use PROXY rule setting in Global Extended Config or Script. Only DIRECT and REJECT are working.

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

1. Open Global Extended Config with any profile;
2. Add the following:
```
rules:
    — DOMAIN-SUFFIX,bilibili.com,PROXY
```
3. Click "SAVE";
4. An error is shown: 
> failed to put configs with status "400"

and no rules added;

5. Open Global Extended Config again;
6. Replace "PROXY" to "DIRECT" or "REJECT":
```
rules:
    — DOMAIN-SUFFIX,bilibili.com,DIRECT
```
7. No errors, all works perfectly: rule for bilibili.com added into the Rules list.

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

13.7.2 (22H313)

### 日志 / Log

12-26 03:09:49DEBUG
[Rule] use default rules
12-26 03:09:49DEBUG
[DNS] cache hit imap.gmail.com --> [173.194.73.108 173.194.73.109] A, expire at 2024-12-26 03:10:11
12-26 03:09:49DEBUG
[DNS] cache hit imap.gmail.com --> [2a00:1450:4010:c1e::6c 2a00:1450:4010:c1e::6d] AAAA, expire at 2024-12-26 03:14:46
12-26 03:09:49DEBUG
[DNS] imap.gmail.com --> 173.194.73.109
12-26 03:09:49DEBUG
[DNS] cache hit imap.gmail.com --> [173.194.73.108 173.194.73.109] A, expire at 2024-12-26 03:10:11
12-26 03:09:49DEBUG
[DNS] cache hit imap.gmail.com --> [2a00:1450:4010:c1e::6c 2a00:1450:4010:c1e::6d] AAAA, expire at 2024-12-26 03:14:46
12-26 03:09:49DEBUG
[Rule] use default rules
12-26 03:09:49DEBUG
[DNS] cache hit imap.gmail.com --> [173.194.73.108 173.194.73.109] A, expire at 2024-12-26 03:10:11
12-26 03:09:49DEBUG
[DNS] cache hit imap.gmail.com --> [2a00:1450:4010:c1e::6c 2a00:1450:4010:c1e::6d] AAAA, expire at 2024-12-26 03:14:46

**Comment by Tychristine** [comment]
@iliya-pro Do you have a group named 'PROXY'?

**Comment by iliya-pro** [comment]
@Tychristine No. It seems, I was needed to use GLOBAL, instead of PROXY, or some proxy name. Thank you for your help!
