### ISSUE TITLE
[BUG] prepend-rules 无效

### ISSUE THREAD

**Issue by halcat** [clash-verge-rev/clash-verge-rev#2455]
### 问题描述 / Describe the bug

prepend-rules: [
  "DOMAIN-SUFFIX,bilibili.com,DIRECT"
]

按文档写的这条配置没有效果，重启过了，还是走代理

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows

### 日志 / Log

无

**Comment by RJSackville** [comment]
prepend: 
  - 'DOMAIN-SUFFIX,bilibili.com,DIRECT'

格式改成这样试一下
最新版gui里面在订阅上右键-编辑规则，有编辑器UI，也可以在这直接填，填完了不会被更新订阅覆盖

**Comment by Tychristine** [comment]
历史功能已被废弃
在`v2.0.x`中你可以使用鼠标右键配置选项卡，编辑规则，图形化编辑并添加前置规则.
你还可以在`Global Extend Script`中编辑脚本，覆写`mian`函数,入参为`config`和`profileName`
为conifg对象中的`rules`数组追加前置规则.

**Comment by 954-Ivory** [comment]
> 历史功能已被废弃 在`v2.0.x`中你可以使用鼠标右键配置选项卡，编辑规则，图形化编辑并添加前置规则. 你还可以在`Global Extend Script`中编辑脚本，覆写`main`函数,入参为`config`和`profileName` 为conifg对象中的`rules`数组追加前置规则.

v2.0.2版本，用图形化编辑和 Profile 都不生效

**Comment by kn007** [comment]
也就是全局扩展配置的意义减少很多啊，本来就是通用写法，免去用脚本模式。
现在这样，只能靠全局扩展脚本，使用合并数组方式来添加规则。

**Comment by 954-Ivory** [comment]
> 也就是全局扩展配置的意义减少很多啊，本来就是通用写法，免去用脚本模式。 现在这样，只能靠全局扩展脚本，使用合并数组方式来添加规则。

佬，`合并数组方式` 有没有 demo 参考下？

**Comment by kn007** [comment]
@954-Ivory 参考文档
https://www.clashverge.dev/guide/script.html

一个获取现有规则的常量origRules，一个新规则的常量，比如附加在前面的，如prependRules。
let newRules = prependRules.concat(origRules);
替换现有规则就行了

**Comment by kn007** [comment]
可以理解官方担心新手，随意乱复制配置，添加进全局，因为不同订阅可能不存在特定的proxy group导致异常。改成这样，增加学习成本。但是对于老手实在是不方便。。。
我翻了issue，看到有其他类似保姆行为，虽然也有吃书改回来的。
但我觉得大家说得对，为啥要因为新手而改变现有既定原则。如果真的是保姆，应该加个开关供选择。。
