### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by BLI2233** [clash-verge-rev/clash-verge-rev#2456]
### 问题描述 / Describe the bug

打开tun模式后，部分网站无法打开（例如：Google）
![image](https://github.com/user-attachments/assets/3bf96ba5-4d3a-4c48-8cad-8f977d3edceb)
在系统代理模式下，都能正常访问，就tun不行
![image](https://github.com/user-attachments/assets/d9d856b5-8541-4a07-8668-2e4fee92bbbd)

### 软件版本 / Verge Version

v2.2.3-alpha

### 复现步骤 / To Reproduce

打开tun模式

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 Version 23H2

### 日志 / Log

[2024-12-26-1730.log](https://github.com/user-attachments/files/18251664/2024-12-26-1730.log)

**Comment by Tychristine** [comment]
@BLI2233 问题无关GUI，请不要上传GUI日志。
上传Clash Mihomo的有关WARNING级别部分。否则该issue会被关闭

**Comment by wonfen** [comment]
检查配置文件和Host文件
