### ISSUE TITLE
[Feature] 2.x版本求一个AppImage格式的编译版本

### ISSUE THREAD

**Issue by kazutod** [clash-verge-rev/clash-verge-rev#2461]
### 功能描述 / Feature description

由于使用的steamos(steamdeck)，但是平时也用桌面模式，所以希望出一个appImage的版本直接能用。

### 使用场景 / Use case

SteamDeck科学上网

**Comment by Tychristine** [comment]
?
https://www.clashverge.dev/install.html#__tabbed_2_3

**Comment by kazutod** [comment]
> ? https://www.clashverge.dev/install.html#__tabbed_2_3

SteamOS用这个这个其实是有问题的，不过我已经解决了，希望能帮到遇到同样问题的人

1.修改配置文件

sudo vim /etc/pacman.conf

#国内镜像源
[archlinuxcn]
Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch

2.生成签名key

sudo pacman -Syy && sudo pacman -S archlinuxcn-keyring

3.安装paru/yay(二选一即可)

安装fakeroot

注意：最新版yay需要依赖pacman 6.1.0, steamdeck已经无法安装,建议使用paru

sudo pacman -S paru
sudo pacman -S yay

sudo pacman -S fakeroot

4.附上安装clash-verge命令

paru -S clash-verge-rev-bin
