### ISSUE TITLE
[BUG] tun模式下无法访问google、steam

### ISSUE THREAD

**Issue by 15631076392** [clash-verge-rev/clash-verge-rev#2462]
### 问题描述 / Describe the bug

tun模式下无法访问google、steam，但是可以访问youtube、openai等网站
更改为系统代理可正常访问外网
![PixPin_2024-12-28_14-45-15](https://github.com/user-attachments/assets/9f4eed6a-0615-4747-9158-97df29bf150d)
![PixPin_2024-12-28_14-45-21](https://github.com/user-attachments/assets/3496f1d9-e560-49cd-8006-89e5520c5564)
![PixPin_2024-12-28_14-25-26](https://github.com/user-attachments/assets/1323891b-db72-4c46-8086-5503617a1114)
日志：
![PixPin_2024-12-28_14-26-45](https://github.com/user-attachments/assets/f3474170-c98d-47e1-b833-28a36dd57401)
自建节点，配置：
![PixPin_2024-12-28_14-29-58](https://github.com/user-attachments/assets/5212277e-2e54-4d60-95d8-9d029c6739fd)

尝试过修改DNS配置信息，无效

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

打开TUN模式 访问google、steam或直接打开steam
网站拒绝访问
连接系统代理模式
刷新搜索页面即可正常使用

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

版本	Windows 11 家庭中文版 版本号	23H2 安装日期	‎2024/‎1/‎25 操作系统版本	22631.4317 体验	Windows Feature Experience Pack 1000.22700.1041.0

### 日志 / Log

[2024-12-28-1450.log](https://github.com/user-attachments/files/18265326/2024-12-28-1450.log)

**Comment by Tychristine** [comment]
@15631076392 你ping google为什么会返回127.0.0.1的回环地址，而不是fake-ip地址？
检查你的系统环境，是否有其它应用已经代理google

**Comment by 15631076392** [comment]
> @15631076392 你ping google为什么会返回127.0.0.1的回环地址，而不是fake-ip地址？ 检查你的系统环境，是否有其它应用已经代理google

已经确认没有其他代理程序或进程在运行，依然无法访问

**Comment by wonfen** [comment]
检查host文件

**Comment by Jaffoo** [comment]
> 是否有其它应用已经代理google

我也出现这个问题，代理后反而访问不到网站，后来我是发现stream有个服务端口和此软件默认的端口是一致的导致代理端口被占用，我是换了个端口才好的

**Comment by r6hk** [comment]
> 检查host文件

谢谢你！！排查了一个半小时的网络问题，最后发现是山寨网游加速器改了我的 Hosts 文件😭😭😭😭
