### ISSUE TITLE
[BUG] 发送url请求时出错

### ISSUE THREAD

**Issue by Drom1145** [clash-verge-rev/clash-verge-rev#2474]
### 问题描述 / Describe the bug

在clash verge中用url方式添加新的订阅，报错发送url请求时出错

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11

### 日志 / Log

2024-12-29 17:09:10 ERROR - error sending request for url

**Comment by Tychristine** [comment]
@Drom1145 ?

**Comment by Drom1145** [comment]
> @Drom1145？

请问是哪里有疑问吗，本人从Linux转Windows还不太熟悉，还需大佬指点
附上日志照片
![IMG_0279](https://github.com/user-attachments/assets/a1f18128-d24a-4c84-b60b-37a1e6fbe9e0)

**Comment by Tychristine** [comment]
@Drom1145 
将出站模式设置为直连，或者选择一个能用的节点
再者，不要使用一键订阅，而是在Clash VergeREV上新建配置，勾选**允许不安全证书** 即可(我试过了你这个订阅的SSL证书过期了)
(btw，把图片删了，你订阅漏了)

**Comment by Drom1145** [comment]
> @Drom1145 将出站模式设置为直连，或者选择一个能用的节点 再者，不要使用一键订阅，而是在Clash VergeREV上新建配置，勾选**允许不安全证书**即可（我试过了你这个订阅安全）的 SSL 证书过期了） （顺便说一句，把图片删了，你订阅漏了）

非常帮助。第一次急着要上传图片第二次已经更改，感谢提醒
