### ISSUE TITLE
[Feature] 希望繼續提供portable版

### ISSUE THREAD

**Issue by shandrive** [clash-verge-rev/clash-verge-rev#2475]
### 功能描述 / Feature description

 希望繼續提供portable版

### 使用场景 / Use case

經常重裝系統, 每次裝完都要安裝一次clash verge和搞一次設置文件, 現在仍在用1.7.7portable

**Comment by Tychristine** [comment]
@shandrive 
麻烦提交issue之前先搜一下相同的
https://github.com/clash-verge-rev/clash-verge-rev/issues/2183#issuecomment-2544403210

**Comment by yzfycz** [comment]
可以把%appdata%\下的io.github.clash-verge-rev.clash-verge-rev目录保存一份到别的目录，装完系统装好软件把文件放回来就能用了，或者装系统之前用一下webdav同步

**Comment by MetaverseMan** [comment]
能分享下 1.7.7portable 版本吗
