### ISSUE TITLE
[BUG] 页面重合问题

### ISSUE THREAD

**Issue by fangyucun** [clash-verge-rev/clash-verge-rev#2479]
### 问题描述 / Describe the bug

代理页面想下滚动, `展开按钮`和`回到顶部`重合, 滚动到底部继续 滚动 会出现页面抖动

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

-

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

页面问题, 必现.

**Comment by Tychristine** [comment]
@fangyucun 什么页面，哪个按钮，有截图吗

**Comment by Tychristine** [comment]
@fangyucun 不用点什么展开按钮，那是个状态表示。
点击整个分组栏就是`展开`和`收起`

**Comment by fangyucun** [comment]
> @fangyucun 不用点什么展开按钮，那是个状态表示。 点击整个分组栏就是`展开`和`收起`

操作上是没问题, 但是ui上是不是可以优化下.

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/792
