### ISSUE TITLE
[Feature] 添加Rule-providers页面，实现手动更新规则文件

### ISSUE THREAD

**Issue by OcrSu** [clash-verge-rev/clash-verge-rev#248]
### Is your feature request related to a problem? Please describe.

当我更新我自己手搓的订阅时，clash verge rev无法同时更新Rule-providers存储在的应用目录下的规则文件。
当我想更新Rule-providers存储在的应用目录下的规则文件时，必须手动打开clash verge rev应用目录，然后删除所有存储的规则文件，最后再次点击更新订阅才能实现 更新Rule-providers规则文件。

### Describe the solution you'd like

更新订阅时同时能够 更新Rule-providers规则文件，也能有手动单独更新Rule-providers规则文件的交互按钮。
这样我也可以通过这个交互页面 查看规则是否生效，是否更新到最新。

### Describe alternatives you've considered

直接仿照clash-nyanpasu所提供的样式进行开发。:(

### Additional context

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/75876201/c5556813-68e0-4baf-88ce-cecbba8aae76)

**Comment by Inside-yourself** [comment]
这功能meta控制面板里有

**Comment by OcrSu** [comment]
> 这功能在meta控制面板里有

谢谢提醒，我没了解过控制面板这个东西，但我个人感觉直接集成在主程序UI上很方便。 特别是对于一点也不懂的人来说，机场客服，朋友等 只需要让他截个图就可以快速得知哪里出问题了。

**Comment by MystiPanda** [comment]
已添加
