### ISSUE TITLE
[Feature] 将订阅界面的删除逻辑修改为移动至回收站

### ISSUE THREAD

**Issue by howdareyo** [clash-verge-rev/clash-verge-rev#251]
### Is your feature request related to a problem? Please describe.

在编辑订阅的时候我习惯用自己的编辑器, 同时"打开文件"的相邻项是"删除", 在极少数情况下会点到删除, 导致文件被删除且无法找回

### Describe the solution you'd like

希望删除的操作是可以被撤销或者需要更多次确认的

### Describe alternatives you've considered

希望在点击"删除"时跳出一个二次确认的窗口

### Additional context

![Screenshot_20240117_185421](https://github.com/clash-verge-rev/clash-verge-rev/assets/91058390/c2e8d238-92fc-4155-bd4c-392641d1a66d)

**Comment by MarkIvory2973** [comment]
不如将它改成移动至回收站？删除了能找回，也不需要点击二次确认的窗口。
