### ISSUE TITLE
[Feature] 希望可以隐藏托盘图标

### ISSUE THREAD

**Issue by youthcould** [clash-verge-rev/clash-verge-rev#252]
### Is your feature request related to a problem? Please describe.

none

### Describe the solution you'd like

希望可以隐藏托盘图标，让其更像一个后台解决网络的服务，大部分时候大部分人都不需要经常去改变设置，需要改变的时候，重新双击启动程序显示窗口就好
这个功能之前被提过，希望rev可以实现，参考这个：https://github.com/zzzgydi/clash-verge/issues/722

### Describe alternatives you've considered

none

**Comment by MystiPanda** [comment]
放在托盘就是正常的后台运行的模式，不考虑

**Comment by PekingJam** [comment]
建议直接用核心+webui的方式
