### ISSUE TITLE
[BUG] 应用退出并未断开虚拟网卡

### ISSUE THREAD

**Issue by CODE-7z** [clash-verge-rev/clash-verge-rev#253]
### Describe the bug

在退出CV之后，meta虚拟网卡并未断开代理链接
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/49109184/3a5b7cea-9634-43f5-977a-09ecf7b8e1ae)

### To Reproduce

启动CV
退出CV

### Platform

Windows

### System Version

10.0.19045.3930 22H2

### Software Version

1.4.

**Comment by wonfen** [comment]
影响正常上网吗？
