### ISSUE TITLE
[BUG]verge去除了配置文件中的引号导致DNS 经过代理查询失效

### ISSUE THREAD

**Issue by MQMQgo** [clash-verge-rev/clash-verge-rev#258]
### Describe the bug

依据[clash meta的说明文档](https://wiki.metacubex.one/config/dns/#dns)，配置DNS 经过代理查询时书写规范应带引号，以防出现特殊字符，例如
```
nameserver:
  - 'tls://dns.google#proxy'
```
 但是在查看运行配置时会发现verge去除了其中的引号，导致#proxy变成了注释
```
nameserver:
  - tls://dns.google#proxy
```

### To Reproduce

在dns字段中nameserver部分配置的DNS 服务器前后加上引号

### Platform

Windows

### System Version

Windows 11 23H2

### Software Version

22631.3007

### Log

这是我配置文件的dns规则
![我的配置](https://github.com/clash-verge-rev/clash-verge-rev/assets/144528295/153fd551-ea08-4229-b2d9-3bf6a4170cb9)

这是查看当前运行的配置
![当前运行配置](https://github.com/clash-verge-rev/clash-verge-rev/assets/144528295/d4890d48-0114-4978-b719-2d4462b6bb22)

**Comment by wonfen** [comment]
配置文件是直接交由内核处理；meta配置文件中也没有引号：
https://github.com/MetaCubeX/mihomo/blob/Meta/docs/config.yaml

**Comment by MQMQgo** [comment]
哦哦，好的谢谢，我再看一下。另外请问为什么当前配置里引号会消失了？

**Comment by wonfen** [comment]
> 哦哦，好的谢谢，我再看一下。另外请问为什么当前配置里引号会消失了？

说明内核就是这样处理的呀。没有引号才是正确的配置。建议到meta那边再问下。

**Comment by MQMQgo** [comment]
这样啊，谢谢回答
