### ISSUE TITLE
[Feature]希望增加一键更新rule-providers功能

### ISSUE THREAD

**Issue by shitouuuuu** [clash-verge-rev/clash-verge-rev#259]
### Is your feature request related to a problem? Please describe.

自建配置文件中，使用proxy-providers并且在代理界面有provider，点击后可以刷新proxy-providers，希望可以增加功能，在此处列出配置文件的rule-providers，并支持一键更新。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/55572093/9e18a4fb-0191-4186-8cbf-cb9b5d4ba22f)

### Describe the solution you'd like

希望可以增加功能，在此处列出配置文件的rule-providers，并支持一键更新。

### Describe alternatives you've considered

希望可以增加功能，在此处列出配置文件的rule-providers，并支持一键更新。

### Additional context

希望可以增加功能，在此处列出配置文件的rule-providers，并支持一键更新。

**Comment by MystiPanda** [comment]
#248
