### ISSUE TITLE
ui界面问题

### ISSUE THREAD

**Issue by dzyx67** [clash-verge-rev/clash-verge-rev#260]
### Is your feature request related to a problem? Please describe.

1.meger订阅表格处下面的时间可以去掉吗？
2.remote订阅表格下面的网址可以去掉吗？
![photo_2024-01-18_18-52-19](https://github.com/clash-verge-rev/clash-verge-rev/assets/104540843/fc0b5e1e-297e-450e-adbf-40fa93cbd3db)
![photo_2024-01-18_18-53-42](https://github.com/clash-verge-rev/clash-verge-rev/assets/104540843/f183c925-ef97-4649-b0df-d5dc31581379)

### Describe the solution you'd like

1.将meger订阅表格处下面的时间可以去掉。
2.将remote订阅表格下面的网址替换为描述的内容。

### Describe alternatives you've considered

2.将remote订阅表格下面的网址弄成空白也行。

**Comment by wonfen** [comment]
原因是？

**Comment by wonfen** [comment]
无反馈，关闭。
