### ISSUE TITLE
TUN 模式启动之后连接不了墙内的网但可以连墙外的网[BUG]

### ISSUE THREAD

**Issue by lincolnlyj** [clash-verge-rev/clash-verge-rev#261]
### Describe the bug

有两个问题：
1. TUN 模式启动之后，可以连接外网，但不能连接 DIRECT 的网址
![WeChatbada96341490b1e69529be7c3ab3b82a](https://github.com/clash-verge-rev/clash-verge-rev/assets/65395808/705a10ac-9828-4820-9490-3fcb10bcc6ee)

2. 复制环境变量到终端之后，curl ifconfig.co/country 显示的是美国，但仍然无法访问 github ，可是网页端就没问题
![WeChat70193d44359c014384d7767cb91c04c4](https://github.com/clash-verge-rev/clash-verge-rev/assets/65395808/f10442e5-18ce-40f4-ae91-90f705fd3309)

这两个问题很有可能不是软件的bug，我使用 V2rayU 和 Shadowrockets 都会出现，但我实在找不到解决方案了，重装软件，重置网络的方法我也试过了都没法解决，只好来这里问一下。

### To Reproduce

第一个问题开起 TUN mode 就会出现，刚开始下载 clash-verge 的时候还没有问题，用一段时间就出现了，Shadowrockets也是同样的问题。
第二个问题就是开启代理，复制环境变量到终端之后， ping github.com 一直显示 timeout ，clone 或者 push 仓库都毫无反应，也是最近才出现的问题。

### Platform

MacOS

### System Version

macOS 14.2.1

### Software Version

1.4.9

**Comment by wonfen** [comment]
“总是运行一段时间出现问题” 会不会是你节点阻断了？

**Comment by a39908646** [comment]
开启tun模式会自动添加dns劫持
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 8.8.8.8
  fallback: []
  fake-ip-filter:
  - dns.msftncsi.com
  - www.msftncsi.com
  - www.msftconnecttest.com
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
但这会导致部分cdn服务出现问题，比如epic的下载就会被指向境外的下载节点
