### ISSUE TITLE
[非BUG] 希望能美化UI

### ISSUE THREAD

**Issue by toyo2333** [clash-verge-rev/clash-verge-rev#263]
### Describe the bug

如同，verge当初的一大亮点就是好看。希望你们在辛苦更新功能的同时，不要忘记这个最早的出发点之一。

现在的windows上的UI布局实在不美观。

### To Reproduce

如同，verge当初的一大亮点就是好看。希望你们在辛苦更新功能的同时，不要忘记这个最早的出发点之一。

现在的windows上的UI布局实在不美观。

### Platform

Windows

### System Version

最新

### Software Version

最新

**Comment by wonfen** [comment]
比原版优化了很多细节啊，哪里不美观了？

**Comment by 21campfire** [comment]
我感觉可以了，大部分时间都在后台工作

**Comment by junlongzzz** [comment]
简约点也行，毕竟定位为GUI，Clash核心正常无Bug的运行才是第一位

**Comment by toyo2333** [comment]
> 比原版优化了很多细节啊，哪里不美观了？

可能审美每个人不同吧。我说几个我觉得不好的点吧：
- 右侧内容区和左侧菜单区的配色不同了，之前是一体化的。现在里面像是内嵌了一个网页白色的
- 字号大小：顶部“比如：代理组”，左侧菜单项目，以及右侧内容区内的文字，字号都不一样，没有规律，
- 新增的测试页面：
   - 里面的项目是“卡片”式设计，和软件整体的扁平化设计是冲突的
   - 卡片也就罢了，结果搞成“立体”的（阴影在下方），非要用卡片你可以搞成平面的啊，参考：https://ipcheck.ing/
   - 卡片上的大图标太丑了，那个图标不是重点，你要么弄错小图标如上面这个，要么就纯文字，参考：https://ip.skk.moe/
   - 测试功能我建议你们好好规划下，如果要做，可以考虑：
      - 区分国内外IP，以便测试分流后的结果
      - 考虑加上服务解锁检测，比如流媒体或ChatGPT解锁
      - DNS出口检测，等等吧。我觉得这一块单独都是一个产品，你们要做就做出特色，把UI交互和功能做好，要不就算了。我上面给的2个网站在测试这一块以及满足全部需求了。根本不需要代理工作再做这一块。我不知道其他人怎么看，反正新版本我看到测试这个模块的时候觉得很奇怪。
 - 和楼上那位说的一样，本来定位是个GUI，核心是GUI才对，不然，我用一个web面板不一样么？

以上是我初步的感受，请多指教。

**Comment by MystiPanda** [comment]
测试页面是有计划设计出一个包含多种信息的看板的

**Comment by MystiPanda** [comment]
订阅页面的卡片也是阴影在下方啊，测试页面就是拿订阅页面改的

**Comment by MystiPanda** [comment]
标题栏和菜单栏的文字大小为什么要一样

**Comment by MystiPanda** [comment]
菜单栏和内容区域颜色不一样是很正常的设计，不知道你为什么会有内嵌网页的感觉。

**Comment by MystiPanda** [comment]
关于扁平化和卡片式的冲突，看了下应该是对代理组页面样式修改不太合适，让代理组页面也是卡片式的就好了。

**Comment by toyo2333** [comment]
我都说了，审美是个人偏好。所以我只是提一下，你认不认同无所谓。

**Comment by Lnncoco** [comment]
从for windows切过来，UI细节感觉确实还需要打磨，这个挺废时间的，都在后台挂着不怎么影响功能使用

**Comment by Calm-er** [comment]
如有需要我可以参与提供 UI 设计稿

**Comment by wonfen** [comment]
> 如有需要我可以参与提供 UI 设计稿

好啊，欢迎，如何联系？

**Comment by Amnesiash** [comment]
> > 如有需要我可以参与提供 UI 设计稿
> 
> 好啊，欢迎，如何联系？

私信联系

**Comment by Aira-Sakuranomiya** [comment]
万恶之源，新 UI 丑爆了。
