### ISSUE TITLE
manjaro下无法工作。[BUG]

### ISSUE THREAD

**Issue by dzhanghz** [clash-verge-rev/clash-verge-rev#264]
### Describe the bug

windows下运行正常，linux manjaro下无论gnome还是kde无法工作，设置与windows完全相同。

### To Reproduce

windows下运行正常，linux manjaro下无论gnome还是kde无法工作，设置与windows完全相同。

### Platform

Windows

### System Version

manjaro kde 新版

### Software Version

1.4.7

**Comment by wonfen** [comment]
日志？

**Comment by dzhanghz** [comment]
Author，您好：

    附件奉上日志。问题式在manjaro无论KDE和GNOM均连不上(windows采用同样设置可以正常工作)，按面板上的测试可以短暂连通(从曲线看是这样)，从节点延迟的显示看延迟时间正常的。但面版上连接页一片空白。

     非常感谢！！！


发件人: wonfen ***@***.***>
发送时间: 2024年1月19日 11:41
收件人: clash-verge-rev/clash-verge-rev ***@***.***>
抄送: dzhanghz ***@***.***>; Author ***@***.***>
主题: Re: [clash-verge-rev/clash-verge-rev] manjaro下无法工作。[BUG] (Issue #264)


日志？
