### ISSUE TITLE
[Feature]在Windows平台添加以管理员身份自启动的选项

### ISSUE THREAD

**Issue by CCC121** [clash-verge-rev/clash-verge-rev#265]
### Is your feature request related to a problem? Please describe.

我的Clash Verge是使用TUN模式工作的，但如果我的Clash Verge没有以管理员权限启动，那么TUN网卡将无法被正常安装导致无法正常工作。但是软件提供的自启动选项只能以普通权限自启动而非管理员权限。这就导致自启动后的Clash Verge无法正常工作，我必须在启动电脑后手动以管理员权限启动Clash Verge以保证其能正常工作。

### Describe the solution you'd like

希望可以添加以管理员权限自启动的选项。

### Describe alternatives you've considered

我曾经尝试直接在应用程序属性中设置让该应用以管理员权限运行，但这直接导致Clash Verge不自启动；后来我又尝试使用Windows的任务计划程序来启动Clash Verge，但任务计划程序并不工作（与此同时我用相同的配置为另一个应用设定自启动可以正常工作，而我使用同样方法为Clash Verge自启动则无法自启动，我无法判断其原因，因此暂时放弃该方案）。

**Comment by MystiPanda** [comment]
不需要管理员权限启动，开启服务模式就行

**Comment by CCC121** [comment]
> 不需要管理员权限启动，开启服务模式就行

好的，感谢您的回复，我的问题得以被解决。
