### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by machinecatzmusa** [clash-verge-rev/clash-verge-rev#266]
### Is your feature request related to a problem? Please describe.

subscription tab switches, the content on the right cannot be dragged & dropped.   
![nZ9EjXNJZz](https://github.com/clash-verge-rev/clash-verge-rev/assets/134985542/07b811a4-293d-4b4d-9ef8-ed3926cab414)

### Describe the solution you'd like

Sub-windows can be arranged again.  I can assign their orders by date through by the file names.

### Describe alternatives you've considered

Like Old version clash for windows , its function has that one drag & drop there
Thanks a lot.

**Comment by wonfen** [comment]
左上角那6个点就可以拖动排序啊

**Comment by machinecatzmusa** [comment]
I got it , Thanks a lot very very very much
