### ISSUE TITLE
[BUG]更新时有文件无法写入

### ISSUE THREAD

**Issue by xiangyi-wang** [clash-verge-rev/clash-verge-rev#267]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/22881957/58a5eb7d-66ea-404e-96db-974a25f3fd09)

### To Reproduce

更新版本

### Platform

Windows

### System Version

win11

### Software Version

1.4.8-1.4.10

**Comment by netshowers** [comment]
只需要去任务管理器找到该进程然后结束再点击retry即可正常安全。

**Comment by xiangyi-wang** [comment]
> 只需要去任务管理器找到该进程然后结束再点击retry即可正常安全。

好的谢谢 下次更新试下

**Comment by lonelam** [comment]
试了下，这个应该是只要一点左上角logo上那个更新按钮就一定会出现的……因为安装程序只杀了Clash Verge没杀clash-meta.exe……
