### ISSUE TITLE
[BUG]软件开启之后苹果徽标处出现一个意外的软件图标

### ISSUE THREAD

**Issue by io-oss** [clash-verge-rev/clash-verge-rev#268]
### Describe the bug

<img width="486" alt="图像" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/25923473/b44b4d93-3815-4294-8991-aea9027e5b00">

如图黑框部分所示，点击之后效果与点击托盘图标的效果一样

### To Reproduce

启动软件即可看到

### Platform

MacOS

### System Version

14.2.1 (23C71)

### Software Version

v1.4.10

**Comment by zjno108** [comment]
+1

**Comment by wonfen** [comment]
重复： https://github.com/clash-verge-rev/clash-verge-rev/issues/122
