### ISSUE TITLE
mac os M1pro 配置之后代理无法显示节点列表

### ISSUE THREAD

**Issue by Elllllllvin** [clash-verge-rev/clash-verge-rev#269]
<img width="800" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/100711005/b03e452f-319b-4679-a467-73c34866294e">
mac os M1pro 使用clash verge， 在配置之后代理无法显示节点列表，请问要如何解决呢？

**Comment by hxy8241** [comment]
新版本的bug。更新后我也是这样。
日志里只有一句。
ERROR - Permission denied (os error 13)

**Comment by Elllllllvin** [comment]
> 新版本的bug。更新后我也是这样。暂时用1.4.9就好。 日志里只有一句。 ERROR - Permission denied (os error 13)

我重新下载了一次1.4.10，目前已经正常显示了
