### ISSUE TITLE
[Feature]希望右下角托盘的“复制环境变量”增加二级菜单[bash/cmd/powershell]

### ISSUE THREAD

**Issue by lakevilladom** [clash-verge-rev/clash-verge-rev#271]
### Is your feature request related to a problem? Please describe.

目前对于复制环境变量略显不便捷,先要设置"复制环境变量类型"，然后托盘复制环境变量，对于既要代理Windows,又要代理linux虚机的情况就比较繁琐

### Describe the solution you'd like

1、希望设盘的“复制环境变量”增加二级菜单[bash/cmd/powershell]
2、目前复制的地址里面都是127.0.0.1，希望这个地址也能可配置,对于这个地址可配置，可以是：

-  文本类型，允许用户配置成任何IP
-  直接读取网卡IP,从这些范围中选取(当然也包含127.0.0.1)

### Describe alternatives you've considered

1、希望设盘的“复制环境变量”增加二级菜单[bash/cmd/powershell]
2、目前复制的地址里面都是127.0.0.1，希望这个地址也能可配置,对于这个地址可配置，可以是：

-  文本类型，允许用户配置成任何IP
-  直接读取网卡IP,从这些范围中选取(当然也包含127.0.0.1)

**Comment by lonelam** [comment]
很难找出一种适合所有人的环境变量配置方案：既要代理Windows又要代理linux虚拟机的情况通常ip和端口都不固定。

**Comment by lakevilladom** [comment]
我的win和linux虚拟机网络互通，linux直接使用windows的代理，ip和端口都固定

**Comment by wonfen** [comment]
从设置中选取即可。
