### ISSUE TITLE
[BUG]软件更新时，进程无法覆盖安装。

### ISSUE THREAD

**Issue by dzyx67** [clash-verge-rev/clash-verge-rev#274]
### Describe the bug

1.当软件里面更新软件时候，如果内核与服务进程处于后台，则无法覆盖安装。（暂无图片）
2.界面的普通窗口过大，并且没有记忆上次普通窗口位置与尺寸的功能。

### To Reproduce

1.当软件安装过程中，自动或者手动选择关闭服务与内核进程，覆盖安装完成后，自动或者手动重新启动软件。
2.调小界面窗口，或者记忆上次窗口位置与尺寸。

### Platform

Windows

### System Version

win 11

### Software Version

v1.4.10

**Comment by lonelam** [comment]
duplicated with https://github.com/clash-verge-rev/clash-verge-rev/issues/272

fixed in the PR https://github.com/clash-verge-rev/clash-verge-rev/pull/273

The updater should be able to close all processes in the next release if there's no other problems about the PR.

**Comment by dzyx67** [comment]
ok, very glad to see the bug to be resolved.
