### ISSUE TITLE
请问规则模式是绕过大陆还是只代理大陆地址啊

### ISSUE THREAD

**Issue by freedomspiritJohn** [clash-verge-rev/clash-verge-rev#275]
我之前使用的是v2rayn，对clash不太熟悉。还有怎么自定义一个网址让他走代理或者是直连啊。

**Comment by S-T-eve** [comment]
是根据订阅的配置文件里的规则字段来代理，参考[https://wiki.metacubex.one/config/rules/](https://wiki.metacubex.one/config/rules/)

**Comment by freedomspiritJohn** [comment]
> 是根据订阅的配置文件里的规则字段来代理，参考https://wiki.metacubex.one/config/rules/

您的意思是如果配置好了一个文件，换代理后还得重新配置吗。没有那种全局规则配置吗

**Comment by S-T-eve** [comment]
> > 是根据订阅的配置文件里的规则字段来代理，参考https://wiki.metacubex.one/config/rules/
> 
> 您的意思是如果配置好了一个文件，换代理后还得重新配置吗。没有那种全局规则配置吗

有这功能，就是Mixin/Merge配置，参考[https://clash-verge-rev.github.io/faq.html#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86](https://clash-verge-rev.github.io/faq.html#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86)
