### ISSUE TITLE
[BUG] 系统代理/tun在 kde 下无效

### ISSUE THREAD

**Issue by awsl1414** [clash-verge-rev/clash-verge-rev#276]
### Describe the bug

1、archlinux kde(x11) 和 kde unstable(wayland) 环境下，系统代理和tun功能无效，同环境 gnome45(wayland) 正常
2、手动修改 kde 代理为 127.0.0.1:7897 时，代理组变成空白，代理生效

### To Reproduce

1、打开clash-verge-rev
2、打开系统代理

### Platform

Linux

### System Version

archlinux; kernel:6.7.0; plasma 5.27.10

### Software Version

1.4.10

### Log

无

### Additional Information

![Image_1705677708342](https://github.com/clash-verge-rev/clash-verge-rev/assets/95275520/6d67090f-164c-448c-a95e-06e1fcce31d8)
![Image_1705677696431](https://github.com/clash-verge-rev/clash-verge-rev/assets/95275520/465e141f-a453-462c-a9f6-6a19cc1143b9)

**Comment by vybfi** [comment]
在zorin17中也出现了这个问题, 桌面环境为gnome43.9, 基于Ubuntu 22.04 LTS

**Comment by detiam** [comment]
同复现 clash-verge v1.5.1 archlinux rolling kde 5.27.10

**Comment by shenmo7192** [comment]
同复现 clash-verge v1.5.1 kubuntu 23.10 kde

**Comment by zerodegress** [comment]
同复现 clash-verge v1.5.1 archlinux kde plasma
