### ISSUE TITLE
[BUG]更新订阅不会更新provider

### ISSUE THREAD

**Issue by feileb** [clash-verge-rev/clash-verge-rev#277]
### Describe the bug

#248 写的已支持，最新版本中没有看到相关功能，而且更新订阅也不会更新provider文件

### To Reproduce

订阅中点击更新

### Platform

Windows

### System Version

win11 22h2

### Software Version

1.4.10

### Log

查看nginx日志，只更新了主配置文件

**Comment by MystiPanda** [comment]
provider的更新是单独的页面

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/152463842/d058fed1-ae04-4504-ab86-1e2cbeb007c9)

**Comment by feileb** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/10227741/897f8b19-4f4a-4306-96f4-ae4128f8b495)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/10227741/14c81a3f-cc75-4a14-ad67-2fa417f4deaf)
奇怪了，我这怎么没有这个，我是点的自动更新升级到1.4.10版本的
