### ISSUE TITLE
[BUG]队列已满

### ISSUE THREAD

**Issue by okami-chen** [clash-verge-rev/clash-verge-rev#278]
### Describe the bug

更新订阅提示队列已满

### To Reproduce

更新订阅提示队列已满

### Platform

Windows

### System Version

11

### Software Version

1.4.10

**Comment by wonfen** [comment]
截图和日志

**Comment by okami-chen** [comment]
> 截图和日志

由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作

**Comment by wonfen** [comment]
> error sending request for url (http://127.0.0.1:9097/configs): error trying to connect: tcp bind local error: 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。 (os error 10055)

系统问题，参考： https://cloud.tencent.com/developer/article/1850776
