### ISSUE TITLE
[BUG]这延续版也太不靠谱了

### ISSUE THREAD

**Issue by ruzztok** [clash-verge-rev/clash-verge-rev#279]
### Describe the bug

更新后系统代理开关无反应

### To Reproduce

1111111111111

### Platform

Windows

### System Version

1111111111111

### Software Version

1111111111111

**Comment by ruzztok** [comment]
以为天天更新、修复，其实天天制造bug，弃了弃了

**Comment by ruzztok** [comment]
原版好好的一个系统代理设置，硬是搞的不能用了

**Comment by MystiPanda** [comment]
你爱用不用，只有你求我更的份，谁也没求着你用。

**Comment by ruzztok** [comment]
删都删了，原版只是不更新了而已，但windows版功能都正常，你这个更新完，最基本的代理开关都干废了，我还求着你更新。。。。。。。。。。。。。。。。。你更新来更新去也没加啥好功能吧，就tun开启时托盘图标变个色，这是我下载你这延续版的唯一理由
