### ISSUE TITLE
[BUG] Direct延迟很高

### ISSUE THREAD

**Issue by exitNA** [clash-verge-rev/clash-verge-rev#280]
### Describe the bug

Direct测试延迟，基本都在400ms左右，是否不正常？
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/5160007/1fd9eeec-94a7-4c16-808a-2c21b74c2a2d)

### To Reproduce

点解DIRECT上的测试延迟按钮

### Platform

Windows

### System Version

windows 11

### Software Version

1.4.10

**Comment by MystiPanda** [comment]
默认测速链接http://1.1.1.1直连延迟确实高，正常的

**Comment by exitNA** [comment]
> 默认测速链接 http://1.1.1.1 直连延迟确实高，正常的

如何自定义测速的链接吗？

**Comment by wonfen** [comment]
在杂项设置里。
