### ISSUE TITLE
无法加载共享库libjxl.so.9

### ISSUE THREAD

**Issue by yufeng-arc** [clash-verge-rev/clash-verge-rev#281]
### Describe the bug

clash-verge: error while loading shared libraries: libjxl.so.0.9: cannot open shared object file: No such file or directory
![06ffdae7-d476-49f4-9060-0c1f75f6549f](https://github.com/clash-verge-rev/clash-verge-rev/assets/117905556/50cc5a1d-fc4b-405c-b0b2-863019eb22a1)

### To Reproduce

桌面图标点击后无反应
命令行执行clash-verge后提示无法加载共享库

### Platform

Linux

### System Version

ArchLinux Rolling

### Software Version

1.4.10

**Comment by wonfen** [comment]
缺少依赖，搜索一下这个库安装。
