### ISSUE TITLE
[Feature]希望增加UWP Loopback功能

### ISSUE THREAD

**Issue by Dudengtai** [clash-verge-rev/clash-verge-rev#283]
### Is your feature request related to a problem? Please describe.

没有UWP loopback，win电脑上微软的一些服务无法正常使用

### Describe the solution you'd like

Clash Verge rev直接集成UWP loopback功能。

### Describe alternatives you've considered

使用fiddle自带的功能进行设置

**Comment by MarkIvory2973** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/114793567/ab3d8890-5dc9-4f90-aacc-65427d4aa234)
已经集成了
