### ISSUE TITLE
[BUG]-Apple M处理器(arm64)安装异常无法打开App

### ISSUE THREAD

**Issue by Kia678** [clash-verge-rev/clash-verge-rev#285]
### Describe the bug

Apple M处理器(arm64)安装异常无法打开App
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/85081567/d4a56c58-337a-4972-a1ff-3a3f8349e210)

### To Reproduce

在Apple M处理器下，无法安装到 Applications，打开显示应用已损坏

### Platform

MacOS

### System Version

macOS 12.6

### Software Version

1.4.10

### Log

none

**Comment by Elllllllvin** [comment]
原因是mac软件包没有经过开发者签名，请运到终端行命令授权：
sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app

**Comment by zjplab** [comment]
find /Applications/Clash\ Verge.app -exec xattr -d com.apple.quarantine {} \;
