### ISSUE TITLE
[Feature]希望增加PAC代理模式

### ISSUE THREAD

**Issue by Alie-72PRO** [clash-verge-rev/clash-verge-rev#286]
### Is your feature request related to a problem? Please describe.

希望能增加clash for windows的PAC代理模式

### Describe the solution you'd like

增加PAC代理模式，并且支持系统代理守卫（部分游戏加速器会强制关闭设置过的代理）

### Describe alternatives you've considered

同上

**Comment by Kinvy66** [comment]
希望PAC代理模式的功能尽快完成，目前对于微软的一切服务（微软的一系列网站，vscode和vs的插件商店等）在开启代理情况下都不能使用，必须关闭clash veger的系统代理。现在解决的方法是需要自己手动在系统设置中添加PAC代理模式的配置脚本地址。

**Comment by Zxis233** [comment]
> 希望PAC代理模式的功能尽快完成，目前对于微软的一切服务（微软的一系列网站，vscode和vs的插件商店等）在开启代理情况下都不能使用，必须关闭clash veger的系统代理。现在解决的方法是需要自己手动在系统设置中添加PAC代理模式的配置脚本地址。

这是为什么？是分流的问题还是节点的问题？？我让Microsoft的网站走代理是正常的

**Comment by Kinvy66** [comment]
> > 希望PAC代理模式的功能尽快完成，目前对于微软的一切服务（微软的一系列网站，vscode和vs的插件商店等）在开启代理情况下都不能使用，必须关闭clash veger的系统代理。现在解决的方法是需要自己手动在系统设置中添加PAC代理模式的配置脚本地址。
> 
> 这是为什么？是分流的问题还是节点的问题？？我让Microsoft的网站走代理是正常的

不是节点的问题，就是代理模式的问题，clash for windows 在设置中是有代理模式的选择的（http/pac)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/20577729/8cdd3551-db06-4d31-be70-57b1611553de)

你访问微软的网站正常，你是不是之前用过clash for windows并且设置代理模式为PAC。如果是这样的话，那你的系统中会有clash for windows 添加的PAC配置。所以换到clash  verge 也是可以正常访问的，如果把clash for windows 生成的PAC配置删除，那么微软的服务也不能访问。

**Comment by Zxis233** [comment]
> 你访问微软的网站正常，你是不是之前用过clash for windows并且设置代理模式为PAC。如果是这样的话，那你的系统中会有clash for windows 添加的PAC配置。所以换到clash verge 也是可以正常访问的，如果把clash for windows 生成的PAC配置删除，那么微软的服务也不能访问。

并没有，我在Windows上使用的Clash系前端只有Clash Verge一个，而且此前也从未使用过PAC代理。
不知道你能否看一下Clash输出的日志，看看microsoft的网站是否正确被分流了。

**Comment by Kinvy66** [comment]
这是打开微软网站时的日志信息
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/20577729/c885098f-b210-4e73-9582-b5fb266cbcfd)

**Comment by Zxis233** [comment]
> 这是打开微软网站时的日志信息

COnnection Refused说明你的节点IP被微软拉黑了吧
我使用Azure HK，一切正常

**Comment by Kinvy66** [comment]
> > 这是打开微软网站时的日志信息
> 
> COnnection Refused说明你的节点IP被微软拉黑了吧 我使用Azure HK，一切正常

好吧，好像是我的节点被微软拉黑了，我更换了另一个节点可以正常访问
