### ISSUE TITLE
[Feature] “测试”页改进

### ISSUE THREAD

**Issue by MarkIvory2973** [clash-verge-rev/clash-verge-rev#287]
### Is your feature request related to a problem? Please describe.

1. 虽然网站测速的图标能够更改，但想要获取图标还是有点麻烦的。

### Describe the solution you'd like

1. 当Icon字段为空时，则获取网站的图标使用，比如：爬取`favicon.ico`或在`<head>`标签中找、爬取`manifest.json`中的图标，实在没有就变成灰色互联网图标。

### Describe alternatives you've considered

NULL

### Additional context

NULL

**Comment by MystiPanda** [comment]
#257
