### ISSUE TITLE
[BUG]1.4.10退出程序后系统代理部自动禁用.

### ISSUE THREAD

**Issue by xengine-qyt** [clash-verge-rev/clash-verge-rev#290]
### Describe the bug

win11 23h2.
关闭程序后系统代理没有自动关闭.还开启的,导致网络异常.

### To Reproduce

1.打开系统代理
2.关闭程序

### Platform

Windows

### System Version

win11 23h2

### Software Version

1.4.10

**Comment by wonfen** [comment]
关闭软件前先关闭系统代理；或者把verge设为开启启动。

**Comment by MystiPanda** [comment]
正常退出是会自动关闭系统代理的，直接关机的话软件无法进行相关操作。
