### ISSUE TITLE
[BUG] 需判断设备是否已安装适用于 Visual Studio 2015、2017、2019 和 2022 的 Microsoft Visual C++ 可再发行程序包

### ISSUE THREAD

**Issue by botch6402** [clash-verge-rev/clash-verge-rev#292]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/156065390/d147be48-dd9e-4ec2-a095-91417b77dc5c)

安装服务时发生错误：“由于找不到 VCRUNTIME140.dll，无法继续执行代码”。

### To Reproduce

1. 全新安装的 Windows 11 操作系统
2. 安装 clash-verge-rev
3. 安装服务

### Platform

Windows

### System Version

Windows 11, version 23H2

### Software Version

1.4.10

### Additional Information

体系结构 | 链接 | 说明
-- | -- | --
ARM64 | https://aka.ms/vs/17/release/vc_redist.arm64.exe | 最新受支持 ARM64 版本的永久链接
X86 | https://aka.ms/vs/17/release/vc_redist.x86.exe | 最新受支持 x86 版本的永久链接
X64 | https://aka.ms/vs/17/release/vc_redist.x64.exe | 最新受支持 x64 版本的永久链接。 X64 可再发行程序包包含 ARM64 和 X64 二进制文件。 当 X64 可再发行程序包安装在 ARM64 设备上时，可以通过此包轻松安装所需的 Visual C++ ARM64 二进制文件。

https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist#visual-studio-2015-2017-2019-and-2022

**Comment by wonfen** [comment]
win10以上应该是默认安装vs软件包的，你的系统是不是某些精简版？
