### ISSUE TITLE
[BUG] macOS mojave (10.14.6) 打开面板不显示内容

### ISSUE THREAD

**Issue by dutry** [clash-verge-rev/clash-verge-rev#293]
### Describe the bug

打开面板后，一片空白，不显示内容

### To Reproduce

在macOS mojave上下载intel版本，安装后打开面板

### Platform

MacOS

### System Version

macOS 10.14.6

### Software Version

1.4.10

**Comment by wonfen** [comment]
升级 macos 到 11 以上。

**Comment by wonfen** [comment]
无反馈，关闭。
