### ISSUE TITLE
必须同时打开tun和系统代理，单独打开系统代理无法上网

### ISSUE THREAD

**Issue by aofly** [clash-verge-rev/clash-verge-rev#294]
### Describe the bug

<img width="582" alt="微信图片_20240122163608" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/129035806/b175f094-d6ca-41a6-bf33-353d91951cd8">
如图所示，必须同时打开tun和系统代理，单独打开系统代理无法上网
按照教程打开服务模式和tun也无法上网
只打开系统代理也不行

### To Reproduce

必须同时打开tun和系统代理，单独打开系统代理无法上网
按照教程打开服务模式和tun也无法上网
只打开系统代理也不行

### Platform

Windows

### System Version

22631.3007

### Software Version

1.4.10

**Comment by gitgitgithut** [comment]
日志里的错误`Start TUN listening error: configure tun interface: Access is denied.`

**Comment by wonfen** [comment]
看置顶FAQ，用管理员模式运行。
