### ISSUE TITLE
[BUG] 自动更新出错

### ISSUE THREAD

**Issue by fpfeng** [clash-verge-rev/clash-verge-rev#295]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/2508212/5c916adc-b018-4cc3-9ac2-3108a9d3456c)

### To Reproduce

点更新之后出错，重启之后已经完成更新

### Platform

MacOS

### System Version

12.4 monterey

### Software Version

1.4.10

**Comment by wonfen** [comment]
应该只是偶发网络问题。

**Comment by wonfen** [comment]
无更多反馈，关闭。
