### ISSUE TITLE
[Feature] Does it support proxy in https://localhost:7897?

### ISSUE THREAD

**Issue by zaaztt** [clash-verge-rev/clash-verge-rev#296]
### Is your feature request related to a problem? Please describe.

I can't `curl -x https://localhost:7897 https://www.google.com/` in https protocol, which returns 
`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:7897`

 but it is OK in http or socks5.

### Describe the solution you'd like

Please tell me the reason

### Describe alternatives you've considered

Above

**Comment by womeimingzi11** [comment]
> > 本地http代理为啥要加s ?
> 
> http代理是可以的，它支持本地https代理吗？

在需要 https 代理的地方，直接用 http 代理也是可以的
