### ISSUE TITLE
[BUG] 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作

### ISSUE THREAD

**Issue by okami-chen** [clash-verge-rev/clash-verge-rev#297]
### Describe the bug

error trying to connect: tcp bind local error: 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。 (os error 10055)

### To Reproduce

error trying to connect: tcp bind local error: 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。 (os error 10055)

### Platform

Windows

### System Version

11

### Software Version

1.4.10

### Log

error trying to connect: tcp bind local error: 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。 (os error 10055)

**Comment by wonfen** [comment]
这种问题建议自己先搜索一下： https://cloud.tencent.com/developer/article/1850776
