### ISSUE TITLE
[Feature] 时间同步警告

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [clash-verge-rev/clash-verge-rev#299]
### Is your feature request related to a problem? Please describe.

电脑送修后导致时间慢了 导致我这的部分节点就因为时间不同步失效 且一时半会就突然很难想到原因

### Describe the solution you'd like

发现后到设置里手动同步时间

### Describe alternatives you've considered

是否可以添加一个时间不同步的警告 可以请求 time.is 或其他任意网址并使用 Header 里的 Date 来判断远程服务器的时间 并与本地客户端的时间比较 当差值过大时进行警告

**Comment by wonfen** [comment]
没有计划，非核心功能，加入这类功能只会导致软件越来越臃肿，越来越难以维护。
建议自己设置系统时间同步。
