### ISSUE TITLE
[BUG] 在Arch Linux 或 Manjaro Linux下不能正常解析订阅

### ISSUE THREAD

**Issue by alex012A** [clash-verge-rev/clash-verge-rev#300]
### Describe the bug

在最新Manjaro Linux和Arch Linux 中，均有很大概率无法解析订阅，具体表现为添加或刷新订阅后代理组为空白或者只有Direct和Reject,日志也无任何异常，无论是Appimage还是AUR编译，在Ubuntu 22.04中无此问题

### To Reproduce

-

### Platform

Linux

### System Version

Manjaro 23.1.3 Vulcan

### Software Version

1.4.10

**Comment by wonfen** [comment]
日志？

**Comment by wonfen** [comment]
无进一步反馈，关闭。
