### ISSUE TITLE
[BUG]tun模式和tinc组网同时使用时，tinc网络不稳定

### ISSUE THREAD

**Issue by caiqy** [clash-verge-rev/clash-verge-rev#301]
### Describe the bug

tun模式和tinc组网同时使用时，tinc网络不稳定
连续ping其他节点出现了丢包，ping tinc的网关不会有丢包
而使用ClashForWindows的tun模式则不存在这个问题

### To Reproduce

同时使用tun模式和tinc组网服务

### Platform

Windows

### System Version

win11

### Software Version

1.4.10

**Comment by wonfen** [comment]
建议到meta那边反馈，非GUI问题。
