### ISSUE TITLE
cf的vless节点在延迟测试为Error[BUG]

### ISSUE THREAD

**Issue by wcgXi** [clash-verge-rev/clash-verge-rev#302]
### Describe the bug

cf的vless节点在延迟测试为Error,但是节点是正常的。

### To Reproduce

cf的vless节点在延迟测试为Error,但是节点是正常的

### Platform

Windows

### System Version

clash Meta内核

### Software Version

---

### Log

![1](https://github.com/clash-verge-rev/clash-verge-rev/assets/131251682/b96d87af-299f-413b-b24d-16f8b8294940)

### Additional Information

![1](https://github.com/clash-verge-rev/clash-verge-rev/assets/131251682/5f041341-f7a0-44cc-9f21-ab1cfda43634)

**Comment by wonfen** [comment]
在杂项设置里换一个延迟测试地址试试看
