### ISSUE TITLE
[BUG] Ubuntu: high CPU and Memory usage for GUI caused by WebKitWebProcess

### ISSUE THREAD

**Issue by GitatHub** [clash-verge-rev/clash-verge-rev#304]
Update: below has been solved by rebooting the system. 
But a high CPU/Memory usage problem from WebKitWebProcess still exists (see the following comments).

### Describe the bug

clash-verge_1.4.10_amd64.AppImage runs into errors without GUI. Details are in “To Reproduce".

### To Reproduce

1. Download and set executable permission for clash-verge_1.4.10_amd64.AppImage
2. Run ./clash-verge_1.4.10_amd64.AppImage in command line from terminal
3. see a tray icon on the task bar of Ubuntu Gnome Desktop
4. click on the tray icon but only see an empty window
5. Cannot configure the app because there is no GUI but only an empty Window

### Platform

Linux

### System Version

Ubuntu 22.04.3 LTS

### Software Version

clash-verge_1.4.10_amd64.AppImage

### Log

/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

(clash-verge:1142613): GLib-GObject-WARNING **: 21:31:40.710: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

(WebKitWebProcess:1142700): Gtk-WARNING **: 21:31:40.833: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(WebKitWebProcess:1142700): Gtk-WARNING **: 21:31:40.834: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(WebKitWebProcess:1142700): Gtk-WARNING **: 21:31:40.835: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

(WebKitWebProcess:1142700): GLib-GObject-WARNING **: 21:31:40.886: g_object_set_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'

(WebKitWebProcess:1142700): Gdk-ERROR **: 21:31:41.063: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 211 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

### Additional Information

System:
Description:	Ubuntu 22.04.3 LTS
Linux  6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wonfen** [comment]
缺少相关依赖，把相关报错复制到google里搜索寻找方案。

**Comment by GitatHub** [comment]
Thanks a lot. I reboot my Ubuntu and now the AppImage runs but just runs.
There is a **high CPU** and **Memory** usage problem for the GUI, which is caused by **WebKitWebProcess**.
Here is the output of top
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
8793 user      20   0   90.2g 411192 172520 S  1545   0.3  22:10.34 WebKitWebProces
```
If I close the GUI, the high-CPU problem disappears. 
This is also seen in many other applications (we will see if we search the web with keywords "WebKitWebProcess high CPU")
Below are the logs when starting the GUI:
```
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

(WebKitWebProcess:9460): Gtk-WARNING **: 11:11:29.416: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(WebKitWebProcess:9460): Gtk-WARNING **: 11:11:29.417: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(WebKitWebProcess:9460): Gtk-WARNING **: 11:11:29.418: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name

(WebKitWebProcess:9460): GLib-GObject-WARNING **: 11:11:29.448: g_object_set_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
```



> 缺少相关依赖，把相关报错复制到google里搜索寻找方案。
