### ISSUE TITLE
[Feature] mac 系统上的菜单栏栏增强

### ISSUE THREAD

**Issue by Amnesiash** [clash-verge-rev/clash-verge-rev#305]
### Is your feature request related to a problem? Please describe.

目前 macos 上的菜单栏功能较弱，需要每次打开面板操作
<img width="409" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/44333360/fd6410d3-2858-49b3-bc4d-319fe4e26951">

### Describe the solution you'd like

可参考 clashx 加入增强版菜单栏
<img width="352" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/44333360/707f65ab-2d47-4d7d-9198-48855e126b5c">

### Describe alternatives you've considered

none

**Comment by chao921125** [comment]
如果参考 clash for windows 的那个操作逻辑感觉还是不错的。

**Comment by wonfen** [comment]
在计划了。
