### ISSUE TITLE
[Feature]关闭 gui 时同步杀除后台 gui

### ISSUE THREAD

**Issue by Calm-er** [clash-verge-rev/clash-verge-rev#306]
### Is your feature request related to a problem? Please describe.

clash gui 面板非 clash 核心功能，该程序持续占用内存
<img width="1251" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/44333360/50f0156f-a412-4af2-8695-ee186fb44780">

### Describe the solution you'd like

可以考虑在关闭面板时关闭程序，且并不会影响 clash.meta 核心功能，减少内存占用
<img width="819" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/44333360/0d644d21-234d-4364-a20e-8b3d85f3afd0">

### Describe alternatives you've considered

none

**Comment by wonfen** [comment]
有意思的想法，那要打开GUI的时候呢？

**Comment by Calm-er** [comment]
逻辑上类似柠檬清理的关闭主面板，只保留状态栏
<img width="1000" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/44333360/78ec2219-f708-4cfb-89cf-05c5345935ee">

**Comment by wonfen** [comment]
mac的一些什么机制导致webview进程就是关不掉，所以干脆就不关了。后续研究吧。

**Comment by wonfen** [comment]
试试最新版1.4.11，加了相关功能。

**Comment by Calm-er** [comment]
<img width="819" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/44333360/c1b7cf6e-2b83-4cae-9b61-2745c3c3b21c">
很强，大幅度降低了内存占用

**Comment by Calm-er** [comment]
<img width="819" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/44333360/c1b7cf6e-2b83-4cae-9b61-2745c3c3b21c">
很强，大幅度降低了内存占用
