### ISSUE TITLE
clash verge 订阅无法选择，点击出现一个红框 [BUG]

### ISSUE THREAD

**Issue by 187286834** [clash-verge-rev/clash-verge-rev#307]
### Describe the bug

mac book pro 最新系统 intel 处理器 订阅链接无法使用，内核授权也没用，代理里面是空的，哪怕订阅链接更新了
<img width="786" alt="截屏2024-01-25 15 21 01" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/63722302/fd6ff03d-05ef-4860-9af9-0e028322dbfe">
<img width="788" alt="截屏2024-01-25 15 21 10" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/63722302/ec8a51cf-6b7a-44ad-af69-13aa03e3bd50">

### To Reproduce

不能用
![Uploading 截屏2024-01-25 15.21.01.png…]()

### Platform

MacOS

### System Version

mac os14.3

### Software Version

1.4.10

**Comment by wonfen** [comment]
日志？

**Comment by wonfen** [comment]
无反馈，关闭。

**Comment by 187286834** [comment]
> 日志？

怎么看日志，不好意思，刚收到邮件

**Comment by 187286834** [comment]
> 日志？

ThisPROGRAM
can only be run on AMD64 processors with v3 microarchitecture support.

**Comment by wonfen** [comment]
> > 日志？
> 
> ThisPROGRAM can only be run on AMD64 processors with v3 microarchitecture support.

版本下错了啊...根据你的芯片下载正确的版本。
