### ISSUE TITLE
[Feature]支持Parsers对订阅规则进行修改

### ISSUE THREAD

**Issue by wangxiaodong1021** [clash-verge-rev/clash-verge-rev#308]
### Is your feature request related to a problem? Please describe.

类似于clash for Windows中，Parsers功能，能够自定义规则，对下载的订阅规则进行二次修改。

### Describe the solution you'd like

无

### Describe alternatives you've considered

无

**Comment by glaughlee** [comment]
支持支持，之前11月份clash事件之前的1.3版本时，在订阅-新建-Merge类型的配置，每次一更新订阅链接或者重启软件，那些自定义的字段（也包括自定义规则）好像就失效了，实在不方便，而clash for windows的Parsers个人认为又要比Diff好用

**Comment by zjplab** [comment]
实现一个parser其实不难，在rust这边我不太会，但是我自己在cloud function上自己的实现可供参考：
```javascript
const functions = require('@google-cloud/functions-framework');
const yaml = require('js-yaml');
functions.http('helloHttp', async (req, res) => {
// res.send(`Hello ${req.query.name || req.body.name || 'World'}!`);

let script=await fetch('YourParserURL');
let raw_script=await script.text();
var fun_str=("(raw)"+raw_script.split("(raw, { yaml, console })")[1]).replace("yaml.parse", "yaml.load").replace("yaml.stringify", "yaml.dump");
var fun=eval(fun_str);
// let configUrl = (pathname.slice(3));
let configUrl = req.query.name || req.body.name
console.log(configUrl)
let resp = await fetch(configUrl);
let rawConfig = await resp.text();
let configStr = fun(rawConfig);
res.send(String(configStr))
});
```

**Comment by abrclano** [comment]
这是我用JS实现的类似clash for windows的Parsers的处理方案，随意切换订阅都是使用的这一套规则，自己可以照着改一下https://github.com/abrclano/Meandering.Path/blob/main/Clash.verge/Rules.js

**Comment by abrclano** [comment]
> 是实现转订阅类似的分组吗 内核可以做 https://wiki.metacubex.one/example/conf/ [filter](https://wiki.metacubex.one/config/proxy-groups/?h=filter#filter)和[exclude-filter](https://wiki.metacubex.one/config/proxy-groups/?h=filter#exclude-filter)我觉得更方便

我主要是不想用proxy-providers,每次换订阅还要去改proxy-providers的链接，Parsers的话就只用把链接导入clash verge就行了，他自动就把规则替换掉了。
e.g
![2024-02-01-112656](https://github.com/clash-verge-rev/clash-verge-rev/assets/80184979/8d31e420-2241-4211-89d4-96d52fd6c2ee)

**Comment by alrcatraz** [comment]
支持！

我在使用verge的时候遇到了部分网站无法正常代理的问题 [Win11开启代理后仍只有直连效果，测试连接Github和Google均超时](https://github.com/clash-verge-rev/clash-verge-rev/issues/332#issue-2115150827) ，可以用parsers对订阅的规则做针对网址或进程的修改，作为临时解决方案。此外，有时对时钟、spotify等软件做单独设定也很方便！

**Comment by 250king** [comment]
顶一个
现在Adobe会联网验证，导致时不时弹出盗版警告。虽然可以通过hosts修改和关闭梯子来屏蔽，但不开梯子很影响日常使用（即一时P图必须关掉梯子，然后要科学上网又要开梯子，有点麻烦）
以前Clash的Parsers可以自定义规则把Adobe域名进行屏蔽，实现科学上网和P图两无误

**Comment by Stephenzero** [comment]
支持，自定义订阅规则非常需要！！！！！！！

**Comment by reeedirect** [comment]
智齿

**Comment by MiangChen** [comment]
顶一顶

**Comment by MystiPanda** [comment]
不是，merge 和 script 做不到吗

**Comment by 250king** [comment]
部分网站不能走Clash使用的DNS，要用内网DNS才能正常解析。就有时候在学校网络做作业，提交作业必须关梯子，但去GitHub搜东西又要开梯子，非常不方便，强力推进Parsers的实现

**Comment by 250king** [comment]
> 不是，merge 和 script 做不到吗

但订阅一更新不就会把原来自己写的script给覆盖掉了吗？那也不是很麻烦？

**Comment by abrclano** [comment]
你先看一下使用文档再提问吧，merge 和 script
是不会覆盖的
耀 ***@***.***>于2024年3月20日 周三15:20写道：
