### ISSUE TITLE
[BUG]macOS tun模式下，obsidian 这个软件的插件仓库无法加载，而系统代理模式下就可以加载，两个模式都打开也可以加载

### ISSUE THREAD

**Issue by hpc-iOS** [clash-verge-rev/clash-verge-rev#309]
### Describe the bug

macOS  tun模式下，obsidian 这个软件的插件仓库无法加载，而系统代理模式下就可以加载，两个模式都打开也可以加载

### To Reproduce

打开软件，开启 tun 模式，打卡 obsidain 插件仓库，加载失败

### Platform

MacOS

### System Version

macOS 12.7.2

### Software Version

1.4.10

**Comment by hpc-iOS** [comment]
日志

**Comment by wonfen** [comment]
检查下你的配置文件问题。GUI并不负责处理这部分内容。

**Comment by hpc-iOS** [comment]
> 检查下你的配置文件问题。GUI并不负责处理这部分内容。

找到原因了在这，https://github.com/MetaCubeX/mihomo/issues/895
这里面说了在开启 tun 模式的时候系统的 DNS 没有被改成192.18.0.2，确实是这样的，我试了将 DNS 手动修改可以解决这个问题，我试过使用clashx meta，在同样的配置文件下不会出现这个问题，希望 GUI 能加一个自动修改 dns 的功能
