### ISSUE TITLE
[BUG] 左上角菜单栏有黑色图标残留 MACOS

### ISSUE THREAD

**Issue by tiancool** [clash-verge-rev/clash-verge-rev#31]
MACOS反馈：
1. 新的版本左上角菜单栏有黑色图标残留
2. 是否可增加在 特定的Wi-Fi下 暂停使用？情景是回来后有软路由，不用手动退出软件了。

**Comment by wonfen** [comment]
截图看看你说的是哪里？

**Comment by shikkoku** [comment]
1.4.2图标又改回原版的了，感觉没那么好看。
