### ISSUE TITLE
[BUG] MacOS 14 M1，菜单栏图标消失

### ISSUE THREAD

**Issue by chao921125** [clash-verge-rev/clash-verge-rev#310]
### Describe the bug

MacOS 14
菜单栏没有图标了

### To Reproduce

正常使用步骤
![WX20240126-225548@2x](https://github.com/clash-verge-rev/clash-verge-rev/assets/8566819/11082b68-9632-4c32-8855-f13ed6284e53)

### Platform

MacOS

### System Version

14.2.1

### Software Version

1.4.10

**Comment by wonfen** [comment]
参考：https://github.com/clash-verge-rev/clash-verge-rev/issues/122
