### ISSUE TITLE
如何指定webview2的环境，已下载并解压了固定版本的webview2[Feature]

### ISSUE THREAD

**Issue by aeneask** [clash-verge-rev/clash-verge-rev#311]
### Is your feature request related to a problem? Please describe.

下载了portable版本的clash verge，但是启动时闪退，经查是需要webview2环境，但是不太想在电脑上安装webview2，只想部署绿色版本的webview2，怎么办才能让verge找到这个已解压的webview2？

### Describe the solution you'd like

希望给出一个办法，使verge能找到已解压的webview2文件夹

### Describe alternatives you've considered

也许可以考虑发布一个包含webview2 runtime环境的verge portable版本

**Comment by MystiPanda** [comment]
去看tauri的文档，自己编译，这种无厘头需求我不理解
