### ISSUE TITLE
请问能不能针对单击 任务栏 就可以打开窗口单出一个设置？

### ISSUE THREAD

**Issue by kshq1996** [clash-verge-rev/clash-verge-rev#312]
### Is your feature request related to a problem? Please describe.

针对单击 任务栏 就可以打开窗口单出一个设置，使用了 clash X / clash X Pro 以及 clash verge 都是单击打开选项，然后二次点击打开窗口，操作可能有点不习惯

### Describe the solution you'd like

针对单击 任务栏 就可以打开窗口单出一个设置，使用了 clash X / clash X Pro 以及 clash verge 都是单击打开选项，然后二次点击打开窗口，操作可能有点不习惯

### Describe alternatives you've considered

针对单击 任务栏 就可以打开窗口单出一个设置，使用了 clash X / clash X Pro 以及 clash verge 都是单击打开选项，然后二次点击打开窗口，操作可能有点不习惯

### Additional context

针对单击 任务栏 就可以打开窗口单出一个设置，使用了 clash X / clash X Pro 以及 clash verge 都是单击打开选项，然后二次点击打开窗口，操作可能有点不习惯

**Comment by wonfen** [comment]
点鼠标右键打开选项，习惯可以慢慢适应。

**Comment by wonfen** [comment]
无更多反馈，关闭。
