### ISSUE TITLE
[BUG]Tun 模式异常

### ISSUE THREAD

**Issue by cheneyxx** [clash-verge-rev/clash-verge-rev#313]
### Describe the bug

在 Mac 系统下使用 clash verge rev 打开 bing.com 会跳转国内的必应 打开 netflix.com 提示 Not Available

### To Reproduce

但是在 Win 系统下使用 clash verge rev 正常 更换 clashx pro 测试增强模式访问 bing 和 netflix 都正常

### Platform

MacOS

### System Version

Sonoma 14.3

### Software Version

1.4.10

**Comment by wonfen** [comment]
非GUI处理内容。检查你的配置文件。

**Comment by wonfen** [comment]
无更多反馈，关闭。
