### ISSUE TITLE
[BUG]启动速度过慢

### ISSUE THREAD

**Issue by obaica** [clash-verge-rev/clash-verge-rev#314]
### Describe the bug

每次启动时间过长，需要1-2min才弹出来界面。

### To Reproduce

每次启动时间过长，需要1-2min才弹出来界面。

### Platform

Windows

### System Version

11

### Software Version

1.4.10

**Comment by wonfen** [comment]
日志？

**Comment by wonfen** [comment]
无反馈，关闭。
