### ISSUE TITLE
[Feature] 希望能支持临时策略

### ISSUE THREAD

**Issue by you-hengh** [clash-verge-rev/clash-verge-rev#315]
### Is your feature request related to a problem? Please describe.

surge有个功能就是添加临时策略, 应用重启后或者退出后失效

这个功能挺方便的, 

### Describe the solution you'd like

希望clash-verge也可以添加这个功能 希望有个快捷键呼出窗口 便捷的添加当前网址的分流策略

### Describe alternatives you've considered

surge 可以很方便的监视到当前浏览器访问的域名 并自动填写到临时分流策略的窗口 用户只需要指定分流策略即可

**Comment by wonfen** [comment]
其实这个功能可以通过浏览器插件来完成。
如果只是配置代理绕过具体网址，可以在系统代理下配置。

**Comment by you-hengh** [comment]
![2024-01-31_13-59-12](https://github.com/clash-verge-rev/clash-verge-rev/assets/34816426/01a8ef25-e9ad-4714-a2f1-f9ea5f594a49)

没事了 通过热键切换代理模式 可以解决这个问题了
