### ISSUE TITLE
如何实现在WSL2中用梯子？

### ISSUE THREAD

**Issue by hyjforesight** [clash-verge-rev/clash-verge-rev#316]
### Is your feature request related to a problem? Please describe.

Clash Verge v1.4.10，在windows里开启全局模式可以正常访问google和github，但是在WSL2里面跑’export https_proxy=http://127.0.0.1:7897 http_proxy=http://127.0.0.1:7897 all_proxy=socks5://127.0.0.1:7897‘后，运行一下代码需要拉取Github源，出现error
```linux
ProxyError: HTTPSConnectionPool(host='nf-co.re', port=443): Max retries exceeded with url: /pipelines.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd4e5961550>: Failed to establish a 
new connection: [Errno 111] Connection refused')))
```
请问该如何解决，谢谢！

### Describe the solution you'd like

能够在WSL2中用梯子

### Describe alternatives you've considered

没有

**Comment by wonfen** [comment]
用tun模式试试？

**Comment by abrclano** [comment]
在环境变量设置中添加
```
export hostip=$(cat /etc/resolv.conf |grep -oP '(?<=nameserver\ ).*')
export https_proxy="http://${hostip}:7897"
export http_proxy="http://${hostip}:7897"
```
然后打开Clash Verge中的Allow LAN

**Comment by wafarm** [comment]
如果你使用的是 Windows 11 22H2 及以后的系统，根据[文档](https://learn.microsoft.com/en-us/windows/wsl/networking)，可以在 `C:\Users\<your_user>\.wslconfig` 中添加如下配置

```
[wsl2]
networkingMode = mirrored
autoproxy = true
```

再启动 WSL2 环境变量应该就自动设置好了

**Comment by favefan** [comment]
使用TUN模式应该就可以了

**Comment by lainbo** [comment]
TUN 请~
