### ISSUE TITLE
macOS 开启 tun 模式不能自动修改系统 dns 为192.18.0.2导致没有网络，希望像 clashx meta 一样能增加一下这个功能

### ISSUE THREAD

**Issue by hpc-iOS** [clash-verge-rev/clash-verge-rev#317]
### Describe the bug

macOS 开启 tun 模式不能自动修改 dns 为192.18.0.2导致没有网络
原因：https://github.com/MetaCubeX/mihomo/issues/895#issuecomment-1905429350
希望能像 clashx meta 一样在开启 tun 模式时自动修改系统dns，关闭 tun 模式时恢复 dns

### To Reproduce

开启 tun 模式

### Platform

MacOS

### System Version

12.7.2

### Software Version

1.4.10

**Comment by wangwei2-ola** [comment]
为什么是192.18.0.2，不是别的？配置文件里也没这个地址啊

**Comment by hpc-iOS** [comment]
> 为什么是192.18.0.2，不是别的？配置文件里也没这个地址啊

不太清楚
