### ISSUE TITLE
[BUG] windows 打开Tun模式报错

### ISSUE THREAD

**Issue by renkx** [clash-verge-rev/clash-verge-rev#318]
### Describe the bug

<img width="1039" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/26194193/28d1113e-d111-40b6-8a94-acaff9c9298a">

### To Reproduce

打开Tun模式，右上角就弹窗报错

### Platform

Windows

### System Version

windows 11

### Software Version

1.4.10

**Comment by wonfen** [comment]
日志？
