### ISSUE TITLE
[Feature] 能否增加一个附加规则

### ISSUE THREAD

**Issue by NOWorEVER** [clash-verge-rev/clash-verge-rev#319]
### Is your feature request related to a problem? Please describe.

是的，代理自带的规则并不能满足我的需求，我需要额外的进行增加规则，但是每次刷新都会清除我已经添加的规则

### Describe the solution you'd like

增加一个附加规则

### Describe alternatives you've considered

禁用代理进行更新

**Comment by Long0x0** [comment]
使用Merge配置或Script配置，参考文档 https://clash-verge-rev.github.io/guide.html
