### ISSUE TITLE
[Feature] 右键菜单深色模式适配

### ISSUE THREAD

**Issue by I-love-study** [clash-verge-rev/clash-verge-rev#320]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/39652142/220a17f0-f49e-4718-88f6-34324a210850)

如图，这个右键菜单并没有适配深色模式，希望能够适配深色模式

### Describe the solution you'd like

None

### Describe alternatives you've considered

None

**Comment by leic4u** [comment]
+1 希望添加支持
