### ISSUE TITLE
[Feature]TUN模式下开启和关闭系统代理时任务栏可以显示不同的图标或颜色以示区分

### ISSUE THREAD

**Issue by Arowa-Z** [clash-verge-rev/clash-verge-rev#322]
### Is your feature request related to a problem? Please describe.

目前在不开启TUN模式时，开启或关闭系统代理后任务栏会显示不同颜色的图标，但在开启TUN模式后，开启或关闭系统代理任务栏图标不会变化，无法直观区分出当前代理开启状态

### Describe the solution you'd like

为TUN模式下，开启和关闭系统代理时任务栏图标设置不同的颜色

### Describe alternatives you've considered

为TUN模式下，设置图标形状的变化，以区分是否开启TUN模式，以图标颜色的变化区分是否开启系统代理

**Comment by wonfen** [comment]
win下是以颜色区分的，mac下是以图标区分的。
