### ISSUE TITLE
[Feature] 为TUN模式增加更详细的参数配置项

### ISSUE THREAD

**Issue by and0rw** [clash-verge-rev/clash-verge-rev#324]
### Is your feature request related to a problem? Please describe.

公司内网有安全检测，开启DNS劫持后通讯会被阻断，因开启TUN模式时会自动加入DNS劫持餐食，导致本地无法使用TUN模式进行全局代理

### Describe the solution you'd like

在设置中为TUN模式增加更详细的配置菜单，允许主动关闭DNS劫持参数

### Describe alternatives you've considered

在设置中为TUN模式增加更详细的配置菜单，允许主动关闭DNS劫持参数

**Comment by a39908646** [comment]
附议
强制dns劫持会导致epic等平台的下载服务器被解析到境外，导致下载缓慢。
个人认为dns设置完全可以单列出一个功能项。
