### ISSUE TITLE
服务模式安装失败

### ISSUE THREAD

**Issue by dxh8286239** [clash-verge-rev/clash-verge-rev#325]
### Describe the bug

服务模式安装失败
![1](https://github.com/clash-verge-rev/clash-verge-rev/assets/10695558/2b962127-af1a-483c-a12c-3af660d485af)

### To Reproduce

![1](https://github.com/clash-verge-rev/clash-verge-rev/assets/10695558/64975c94-e55e-4705-9f9b-2150f16f9401)

### Platform

Windows

### System Version

11

### Software Version

1.4.10

**Comment by wonfen** [comment]
看置顶问答，先卸载服务模式再安装。

**Comment by dxh8286239** [comment]
谢谢，已解决
