### ISSUE TITLE
[Feature] 给Tun模式添加更详细的配置，例如mtu、dns等

### ISSUE THREAD

**Issue by Walker-Chao** [clash-verge-rev/clash-verge-rev#329]
### Is your feature request related to a problem? Please describe.

新版的wsl2里面支持网络镜像模式，但是这个模式下使用clash-verge-rev的tun模式会导致wls里面没有办法访问网络，原因可能是因为tun默认给的mtu为9000

### Describe the solution you'd like

可以允许启动tun时设置mtu，这样可以修改为1500，测试这个配置wsl可以正确使用网络

### Describe alternatives you've considered

在知乎上看到临时的解决方案https://zhuanlan.zhihu.com/p/672040301

### Additional context

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/82486481/e73d77ea-2711-4dd3-9449-168c16e8bd4b)

**Comment by wonfen** [comment]
参考这个方法试试 https://github.com/clash-verge-rev/clash-verge-rev/issues/316

**Comment by Walker-Chao** [comment]
> 参考这个方法试试 #316

昨天有一个新版本更新，我看到开发者已经在clash-verge.yaml里写了默认配置
tun: 
    mtu: 1500
现在可以正常代理了

**Comment by Wangcheng1923** [comment]
> > 参考这个方法试试 #316
> 
> 昨天有一个新版本更新，我看到开发者已经在clash-verge.yaml里写了默认配置 tun: mtu: 1500 现在可以正常代理了

老哥问一下怎么设置的 我这没这行😭

**Comment by Walker-Chao** [comment]
> > > 参考这个方法试试 #316
> > 
> > 
> > 昨天有一个新版本更新，我看到开发者已经在clash-verge.yaml里写了默认配置 tun: mtu: 1500 现在可以正常代理了
> 
> 老哥问一下怎么设置的 我这没这行😭 手动在文件里添加 没有作用重启模式文件又会重置

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/82486481/bcf91e4b-6f7d-4576-8dfa-ff23f45e37bd)
需要更新到1.4.11版本，卸载之前的版本再安装。启动后点击图片里的应用目录
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/82486481/43cbc6f6-ff76-43e4-b6e3-e5b1b0337d45)
这里有个clash-verge.yaml的配置文件，打开这个配置文件，可以搜索到tun，我现在是启动tun的状态，103行里面包含了mtu：1500
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/82486481/454aa8d2-ee4a-4189-a1e1-80218079094a)

**Comment by Chefback** [comment]
看了下1.14.11的tun配置，没有这个mtu

**Comment by MystiPanda** [comment]
我并没有加过相关设置，需要添加的话使用merge功能自己添加即可。

**Comment by MengNianxiaoyao** [comment]
> 我并没有加过相关设置，需要添加的话使用merge功能自己添加即可。

merge功能是不是直接在config.yaml文件里写配置就行了？

**Comment by MystiPanda** [comment]
看官网文档

**Comment by dxdw233** [comment]
直接在Tun模式设置里将最大输出单元，也就是mtu从9000改为1500就好了
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/51281549/56f66fe6-f223-4695-b026-3e09fbb6e505)
