### ISSUE TITLE
[Feature] tun 模式下是否支持内网DNS

### ISSUE THREAD

**Issue by rikopudding** [clash-verge-rev/clash-verge-rev#331]
### Is your feature request related to a problem? Please describe.

公司内网DNS为 10.0.0.11 和 10.0.0.11，不开tun走自带的DNS是可以使用的
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/22855571/e342916d-c8b1-4746-ae22-6040638eb23b)
开启tun之后无法解析
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/22855571/89fdb8f9-f1b0-4ad9-b8f2-416f0f27de25)

我发现 xxx.net 内网域名都是可以正常使用，但 xxx.us   xxx.fi  这种给员工分配的域名就会报错

### Describe the solution you'd like

我是否能修改TUN配置中解决这个问题

### Describe alternatives you've considered

或者有没有其他方法让公司域名不经过tun的dns解析

**Comment by S-T-eve** [comment]
自行添加Merge规则，写上dns字段或hosts，具体参考[https://clash-verge-rev.github.io/guide.html](https://clash-verge-rev.github.io/guide.html)  [https://wiki.metacubex.one/config/dns/](https://wiki.metacubex.one/config/dns/)

**Comment by wzrzt** [comment]
我参考了这个教程开启TUN模式，且按文章中的两个DNS泄漏检测网站的结果看，效果达到了。
https://lainbo.com/article/clash-config
此教程中的TUN模式步骤操作3，那个脚本里面有定义一个 trustDnsList，我在不代理的模式下看局域网wifi的DNS，复制到trustDnsList变量列表中，然后重新启用这个规则脚本，解决了内网DNS无法正常解析的问题。希望有所帮助。
<img width="739" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/12440644/5310a0bf-e9e8-485c-8449-1508248764de">
