### ISSUE TITLE
[BUG]1.4.11 Win11开启代理后仍只有直连效果，测试连接Github和Google均超时

### ISSUE THREAD

**Issue by alrcatraz** [clash-verge-rev/clash-verge-rev#332]
### Describe the bug

使用了相同的订阅链接，在Clash for Windows中可以正常代理，但当使用Clash Verge时则虽然开启规则模式，却如同没有发生代理般，bing跳转到cn.bing，谷歌和GitHub无法打开

### To Reproduce

导入订阅连接（飞鸟机场）
启用系统代理
测试

### Platform

Windows

### System Version

Windows11

### Software Version

1.4.11

**Comment by alrcatraz** [comment]
> 检查下系统代理的开启状态，点系统代理旁边的齿轮。

全部都开启且正常的。

我几分钟前再次尝试了一下，发现clash for windows代理时大部分节点均可访问Google和github，但verge只有极少数节点可以访问，而github则全部无法连接

**Comment by wonfen** [comment]
感觉是你机场或者配置文件的问题。用我们首页aff的机场试试。

**Comment by alrcatraz** [comment]
如果是机场的问题的话就没办法了，不过在clash for windows能用，但在verge不好用就蛮怪的，我先去试试看，一会看看效果

**Comment by alrcatraz** [comment]
用免费的订阅链接试了一下，狗狗能上github，但好像也有少数网站打开不太顺利，在verge自带的测试里，所有翻墙网站链接依然是超时。

而且不知道是不是免费订阅的原因，不能自己选择特定节点。

我刚刚看了一眼，还有一个老哥也遇到了github无法访问的问题：[github无法连接](https://github.com/clash-verge-rev/clash-verge-rev/issues/333#issue-2116182251)

**Comment by hsiayuchih** [comment]
> 用免费的订阅链接试了一下，狗狗能上github，但好像也有少数网站打开不太顺利，在verge自带的测试里，所有翻墙网站链接依然是超时。
> 
> 而且不知道是不是免费订阅的原因，不能自己选择特定节点。
> 
> 我刚刚看了一眼，还有一个老哥也遇到了github无法访问的问题：[github无法连接](https://github.com/clash-verge-rev/clash-verge-rev/issues/333#issue-2116182251)

很奇怪的，我这边只是github不能访问，其他都是正常的...

**Comment by alrcatraz** [comment]
> > 用免费的订阅链接试了一下，狗狗能上github，但好像也有少数网站打开不太顺利，在verge自带的测试里，所有翻墙网站链接依然是超时。
> > 而且不知道是不是免费订阅的原因，不能自己选择特定节点。
> > 我刚刚看了一眼，还有一个老哥也遇到了github无法访问的问题：[github无法连接](https://github.com/clash-verge-rev/clash-verge-rev/issues/333#issue-2116182251)
> 
> 很奇怪，我这边只是github不能访问，其他都是正常的...

我这谷歌有少量节点能连，github是全部都连不上

**Comment by alrcatraz** [comment]
问了机场的客服，他们说是没问题的，如果有问题就用Clash for Windows，不要用Clash Verge……我大受震撼

**Comment by hsiayuchih** [comment]
> 问了机场的客服，他们说是没问题的，如果有问题就用Clash for Windows，不要用Clash Verge……我大受震撼

😂客服有没有说为什么不要用verge

**Comment by alrcatraz** [comment]
> > 问了机场的客服，他们说是没问题的，如果有问题就用Clash for Windows，不要用Clash Verge……我大受震撼
> 
> 😂客服有没有说为什么不要用verge

🫠他没说，语气有点强硬，大概意思就是他们的链接用clash for Windows一定不会有问题，虽然这个软件不维护了，但不代表不能用了，你别在各个平台上用他们指定的clash以外的clash，就一定不会有问题

感觉对修bug的参考意义不大

**Comment by MystiPanda** [comment]
杂项设置中把clash字段过滤关了试试

**Comment by alrcatraz** [comment]
> 杂项设置中把clash字段过滤关了试试

没啥用，我试过关clash字段之后才报issue的

**Comment by wonfen** [comment]
检查浏览器的代理设置。是否使用了中文的pppoe拨号？

**Comment by wonfen** [comment]
无进一步反馈，关闭。

**Comment by alrcatraz** [comment]
没有，而且同样的设置在clash没问题，clash verge就有问题

________________________________
