### ISSUE TITLE
[BUG] 只有github无法连接是什么原因？

### ISSUE THREAD

**Issue by hsiayuchih** [clash-verge-rev/clash-verge-rev#333]
### Describe the bug

![QQ截图20240203120456](https://github.com/clash-verge-rev/clash-verge-rev/assets/21278771/b14bbaf2-72bb-4bb5-a76f-410b707b427d)
开启代理后其他外网都能正常访问，唯独github是超时，然后也无法连接。用之前的那个已经存档的旧版本是没有这个问题的，今天找到了这个rev版本的就更新了下试试，然后就发现了这个问题

### To Reproduce

导入订阅连接
启用系统代理
测试

### Platform

Windows

### System Version

Windows11

### Software Version

1.4.11

**Comment by hsiayuchih** [comment]
@wonfen

**Comment by hsiayuchih** [comment]
> @wonfen 大佬帮忙看看是啥原因呢

**Comment by hiwanz** [comment]
我第一次覆盖升级的时候也遇到这个情况，后面就好了

**Comment by hsiayuchih** [comment]
> 我MacOS下第一次覆盖升级的时候也遇到这个情况，后面就好了，做过的操作就是重新开启下系统代理，不知道是否跟这个有关

我这边的情况是和这个issue一样的： #298

**Comment by SomeBottle** [comment]
我这边是在清除了系统 `hosts` 中关于 github.com 的配置后，重启系统代理就解决了。

**Comment by hsiayuchih** [comment]
> 我这边是在清除了系统 `hosts` 中关于 github.com 的配置后，重启系统代理就解决了。

使用其他内核版本的包括之前已经归档的旧版本clash-verge就不会有这个问题，不知道为什么现在这个rev版会这样

**Comment by hsiayuchih** [comment]
> 我这边是在清除了系统 `hosts` 中关于 github.com 的配置后，重启系统代理就解决了。

主要是我这边用的有其他反代软件，涉及到不少其他的域名，全部清了还是挺麻烦的。以前的旧版本都没这个情况的，hosts文件和代理互不干扰的

**Comment by hsiayuchih** [comment]
> 我MacOS下第一次覆盖升级的时候也遇到这个情况，后面就好了，做过的操作就是重新开启下系统代理，不知道是否跟这个有关

试过了，没有效果。我这边测试情况是使用其他内核版本，以及之前已经归档的旧版本就不会有这个问题，不知道为什么现在这个rev版会这样
