### ISSUE TITLE
[BUG] TUN模式下，Meta Tunnel虚拟网卡与移动热点功能冲突

### ISSUE THREAD

**Issue by laffylaffyla** [clash-verge-rev/clash-verge-rev#335]
### Describe the bug

服务模式开启状态下，Meta Tunnel虚拟网卡与移动热点功能所生成的Microsoft Wi-Fi Direct Virtual Adapter虚拟网卡冲突，无法正常开启TUN模式。同样操作在CFW中可以无冲突正常工作。

### To Reproduce

1. 安装服务模式并开启
2. 打开Tun模式，此时网络适配器中新增Meta Tunnel虚拟网卡，Tun模式正常工作
3. 开启Windows移动热点(WLAN)功能，此时网络适配器中新增Microsoft Wi-Fi Direct Virtual Adapter虚拟网卡，Meta Tunnel虚拟网卡消失，电脑断网

### Platform

Windows

### System Version

Windows 11 Pro 23H2 22631.3085

### Software Version

1.4.11

**Comment by laffylaffyla** [comment]
> 尝试用管理员模式运行。
> 注意：服务模式的唯一作用就是为了可以不用管理员模式启用tun。
> 
> 另外换一台电脑试试能否复现这个问题。

使用管理员模式运行依旧存在此问题；
财力有限，目前仅有一台电脑

**Comment by Walker-Chao** [comment]
> > 尝试用管理员模式运行。
> > 注意：服务模式的唯一作用就是为了可以不用管理员模式启用tun。
> > 另外换一台电脑试试能否复现这个问题。
> 
> 使用管理员模式运行依旧存在此问题； 财力有限，目前仅有一台电脑
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/82486481/06c625e8-e352-4986-b4f9-75863cfc8045)
没有消失，但是断网了，可以重现

**Comment by KinComet** [comment]
管理员模式下重现，开启热点后tun没有消失，meta回环
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/111748332/a3b18a35-f344-4c65-902e-9c41fce6b25e)

**Comment by KinComet** [comment]
添加 Script 脚本，启用 `endpoint-independent-nat` 后解决了我的问题。
```js
function main(config) {
  if (!config.tun) {
    config.tun = {}
  }
  config.tun.stack = "mixed"
  config.tun["endpoint-independent-nat"] = true // Add this
  return config
}
```

**Comment by Shadowmirror** [comment]
你可以右键你的 Meta 虚拟网卡 属性 -> 共享 -> 允许其他网络用户通过此计算机的 Internet 连接来连接 -> 家庭网络连接选择你的网卡分享的热点网卡就 ok 了，上面有张图就是那个本地连接2

**Comment by QiWu666** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/46865888/0494a313-30a6-4938-820e-cfc5e8124c5e)
我的开启tun模式，再开热点也会环路
