### ISSUE TITLE
[BUG]1.4.11 版本流量信息错讹

### ISSUE THREAD

**Issue by weineo** [clash-verge-rev/clash-verge-rev#337]
### Describe the bug

更新1.4.11版本后，因为无法使用之前版本的profile信息，我只能全部重新导入了一遍，发现订阅界面所有机场的总流量信息都是0B。打开profiles.yaml文件后，发现所有导入的订阅，其“extra-total”的信息都是0，应该是这个版本的bug。

### To Reproduce

安装1.4.11版本，导入订阅

### Platform

Windows

### System Version

win11

### Software Version

1.4.11

**Comment by wonfen** [comment]
订阅连接发给我看看 tg: @wonfen_bot

**Comment by weineo** [comment]
哈哈，谢谢大家。再次重装并重启后解决了。
