### ISSUE TITLE
[BUG]打不开面板

### ISSUE THREAD

**Issue by ShiJie137** [clash-verge-rev/clash-verge-rev#338]
### Describe the bug

开机自启，想开面板更新一下配置，点击之后托盘自动退出，任务管理器里GUI退出了，但是meta以及服务模式都还在，代理也能用，开的tun模式，用的便携版

### To Reproduce

手动退出任务管理器中的meta核服务模式再开也还是不行

![QQ截图20240204101852](https://github.com/clash-verge-rev/clash-verge-rev/assets/66241216/412c1873-8071-4e35-9c27-f1987d816e86)
开另一个Nyanpasu便携版的时候出现如图，不知道能不能作参考

### Platform

Windows

### System Version

W11 23H2 22635.3139

### Software Version

1.4.11

**Comment by wonfen** [comment]
卸载重装下试试。

**Comment by ShiJie137** [comment]
> 卸载重装下试试。

虽然不知道发生了什么，但是它自己好了( ﾟ∀。)

**Comment by ShiJie137** [comment]
> 卸载重装下试试。

虽然不知道发生了什么，但是它自己好了( ﾟ∀。)
