### ISSUE TITLE
[BUG]Tun服务模式无法安装

### ISSUE THREAD

**Issue by JJJY5** [clash-verge-rev/clash-verge-rev#339]
### Describe the bug

安装时提示failed to intall with status 1

### To Reproduce

1.4.11更新以后我卸载了1.4.10版本并重新安装了1.4.11版本，1.4.10版本我已经安装了服务模式，而1.4.11提示我未安装，并且安装时提示安装失败

### Platform

Windows

### System Version

22H2 19045.3930

### Software Version

1.4.11

**Comment by wonfen** [comment]
看置顶faq，卸载服务模式重新安装一次。

**Comment by JJJY5** [comment]
> 看置顶faq，卸载服务模式重新安装一次。

我手动卸载服务以后再重新安装已经成功。
