### ISSUE TITLE
clash-verge tauri CPU高占用问题

### ISSUE THREAD

**Issue by poneding** [clash-verge-rev/clash-verge-rev#340]
<img width="1056" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/33922888/1e503e8a-9ca1-4cf5-a22c-456e676ab13c">

启动 Clash Verge 一段时间后，电脑一些操作开始变得卡顿，查看资源使用情况，发现 tauri://localhost 有较高的 CPU 占用，退出 Clash Verge 卡顿情况消失。

机器：Macbook Pro 14 M1 Pro
系统：MacOS Ventura

**Comment by klacee** [comment]
你试试把日志文件改为error

**Comment by poneding** [comment]
改成 error 也没有效果
<img width="1308" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/33922888/343bf41a-49fa-4ba6-a90a-cbbcc3e68dc3">

**Comment by Nephren-Ruq-Insania** [comment]
尝试关闭流量图表

**Comment by wonfen** [comment]
无近一步反馈，关闭。
