### ISSUE TITLE
Mac 打开应用一直没有响应

### ISSUE THREAD

**Issue by ElayneC** [clash-verge-rev/clash-verge-rev#342]
### Describe the bug

应用安装后打开，无法响应
<img width="192" alt="截屏2024-02-05 00 09 29" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/145306386/e8d5f400-b559-4fba-9c67-33d642735b95">

### To Reproduce

按FAQ里的指引执行了命令
sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app

但是再在启动台里打开应用，一直都是没有响应。卸载重装几次仍然这样

### Platform

MacOS

### System Version

macOS 13.4

### Software Version

1.4.11

**Comment by wonfen** [comment]
无进一步反馈，关闭。

**Comment by ElayneC** [comment]
之前按指示查看日志过没有安装错，后来翻找了一下，把原来下过的clashX全部删除了，再下载clash-verge，可以正常使用。感谢。
