### ISSUE TITLE
[BUG] 监听端口不为 * 或 127.0.0.1 时系统代理不生效

### ISSUE THREAD

**Issue by lslqtz** [clash-verge-rev/clash-verge-rev#344]
### Describe the bug

已在 Log 处附上 netstat 及 curl 测试.

另:
若启动局域网连接, 且 “bind-address” 为 * 时, 会同时监听到广域网地址 (IPv6), 这个应该是合理的行为.
但即使 “bind-address” 为 0.0.0.0 时, 仍会监听 IPv6 地址, 此为上游特性或问题吗? 用途是希望其为局域网内所有设备提供服务, 但由于监听 IPv6 公网的原因, 不得不降级为主动监听为局域网地址, 随后即触发此 bug.

### To Reproduce

1. 在订阅内设置 bind-address 为局域网地址 (如 192.168.253.253);
2. 启动 “局域网连接” 及 “IPv6” 选项, Clash 字段勾选 “bind-address“;
3. 设置系统代理, 使用浏览器访问网页及 curl 访问代理, 观察系统代理被设置为 127.0.0.1:7890;

### Platform

Windows

### System Version

Windows Server 2022

### Software Version

21H2 20348.2031

### Log

```
C:\Users\lslqtz>netstat -ano|findstr 7890
  TCP    192.168.253.253:7890   0.0.0.0:0              LISTENING       7104
  UDP    192.168.253.253:7890   *:*                                    7104

C:\Users\lslqtz>curl 127.0.0.1:7890
curl: (7) Failed to connect to 127.0.0.1 port 7890 after 2001 ms: Couldn't connect to server

C:\Users\lslqtz>curl 192.168.253.253:7890 -I
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 0
```

**Comment by Long0x0** [comment]
报错400似乎是节点的问题？
verge目前对于局域网ip的兼容性不是很好， #92 。
上游clash的`lan-allowed-ips`好像也不能正常工作 https://github.com/MetaCubeX/mihomo/issues/1010 。
可以不设置`bind-address`，关闭`allow-lan`，用 [`listeners`](https://wiki.metacubex.one/config/inbound/listeners/) 加一个端口：
```yaml
listeners: # 开启字段
  - name: mixed-2
    type: mixed
    port: 7890
    listen: 192.168.253.253
```

**Comment by lslqtz** [comment]
> 报错400似乎是节点的问题？ verge目前对于局域网ip的兼容性不是很好， #92 。 上游clash的`lan-allowed-ips`好像也不能正常工作 [MetaCubeX/mihomo#1010](https://github.com/MetaCubeX/mihomo/issues/1010) 。 可以不设置`bind-address`，关闭`allow-lan`，用 [`listeners`](https://wiki.metacubex.one/config/inbound/listeners/) 加一个端口：
> 
> ```yaml
> listeners: # 开启字段
>   - name: mixed-2
>     type: mixed
>     port: 7890
>     listen: 192.168.253.253
> ```

报错 400 是正常的, 因为我使用的是 curl 进行测试, 并没有发起向任何域名的代理请求. 测试只是证明其监听地址可达 (也可用), 但 127.0.0.1 或 localhost 是不可达的, 而系统代理默认设置为后者.

**Comment by canoziia** [comment]
> 报错400似乎是节点的问题？ verge目前对于局域网ip的兼容性不是很好， #92 。 上游clash的`lan-allowed-ips`好像也不能正常工作 [MetaCubeX/mihomo#1010](https://github.com/MetaCubeX/mihomo/issues/1010) 。 可以不设置`bind-address`，关闭`allow-lan`，用 [`listeners`](https://wiki.metacubex.one/config/inbound/listeners/) 加一个端口：
> 
> ```yaml
> listeners: # 开启字段
>   - name: mixed-2
>     type: mixed
>     port: 7890
>     listen: 192.168.253.253
> ```

目前最新mihomo alpha应该已修复lan-allowed-ips问题

**Comment by wonfen** [comment]
> verge目前对于局域网ip的兼容性不是很好， #92 。

这个问题早修复了。

**Comment by Long0x0** [comment]
> > verge目前对于局域网ip的兼容性不是很好， #92 。
> 
> 这个问题早修复了。

刚刚测试了最新版，external-controller设为局域网ip还是会崩溃
