### ISSUE TITLE
[BUG]Ubuntu下系统代理只能作用于Firefox？

### ISSUE THREAD

**Issue by fotia72** [clash-verge-rev/clash-verge-rev#346]
### Describe the bug

开系统代理之后，Firefox能翻墙但在其他软件失效。

### To Reproduce

在clash中开启系统代理。用firefox可以正常访问谷歌等被墙网站，但在其他平台无法访问。

- 终端`ping www.google.com`全部丢包。
- Brave浏览器，网站无法打开，`ERR_CONNECTION_CLOSED`。
- Visual Studio Code用Github登录会出错。

只要我没开firefox，以上过程中clash流量图表就是一条直线，0B/s，日志上也没有出现访问的域名。同一机场的代理在其他平台没有出现异常。

### Platform

Linux

### System Version

Ubuntu 22.04.3 LTS & Zorin OS Lite 16.3

### Software Version

1.4.11

**Comment by MystiPanda** [comment]
Linux下的软件走系统代理的本来就没有几个，不同桌面环境也有差异，这不是clash的问题，各大发行版的wiki应该都有说的
