### ISSUE TITLE
[BUG]更新至1.5.0之后Script失效

### ISSUE THREAD

**Issue by IntangibleW** [clash-verge-rev/clash-verge-rev#347]
### Describe the bug

Script不能对Remote获取到的文件进行修改

### To Reproduce

编写Script(见下)并激活后，配置文件中没有出现“香港”、“美国”等代理组

### Platform

Windows

### System Version

Windows 10

### Software Version

1.5.0

### Additional Information

Script file:

function main(params) {

    // 香港代理组
    const hongKongRegex = /香港|HK|Hong Kong/;
    const hongKongProxies = params.proxies
      .filter((e) => hongKongRegex.test(e.name))
      .map((e) => e.name);
    const HongKong = {
      name: "香港",
      type: "fallback",
      proxies: hongKongProxies.length > 0 ? hongKongProxies : ["DIRECT"],
      url: "http://www.gstatic.com/generate_204",
      interval: 300,
      lazy: true
    };
    // 台湾代理组
    const taiwanRegex = /台湾|TW|Taiwan/;
    const taiwanProxies = params.proxies
      .filter((e) => taiwanRegex.test(e.name))
      .map((e) => e.name);
    const TaiWan = {
      name: "台湾",
      type: "fallback",
      proxies: taiwanProxies.length > 0 ? taiwanProxies : ["DIRECT"],
      url: "http://www.gstatic.com/generate_204",
      interval: 300,
      lazy: true
    };
    // 新加坡代理组
    const singaporeRegex = /新加坡|SG|Singapore/;
    const singaporeProxies = params.proxies
      .filter((e) => singaporeRegex.test(e.name))
      .map((e) => e.name);
    const Singapore = {
      name: "新加坡",
      type: "fallback",
      proxies: singaporeProxies.length > 0 ? singaporeProxies : ["DIRECT"],
      url: "http://www.gstatic.com/generate_204",
      interval: 300,
      lazy: true
    };
    // 日本代理组
    const japanRegex = /日本|JP|Japan/;
    const japanProxies = params.proxies
      .filter((e) => japanRegex.test(e.name))
      .map((e) => e.name);
    const Japan = {
      name: "日本",
      type: "fallback",
      proxies: japanProxies.length > 0 ? japanProxies : ["DIRECT"],
      url: "http://www.gstatic.com/generate_204",
      interval: 300,
      lazy: true
    };
    // 美国代理组
    const americaRegex = /美国|US|United States/;
    const americaProxies = params.proxies
      .filter((e) => americaRegex.test(e.name))
      .map((e) => e.name);
    const America = {
      name: "美国",
      type: "fallback",
      proxies: americaProxies.length > 0 ? americaProxies : ["DIRECT"],
      url: "http://www.gstatic.com/generate_204",
      interval: 300,
      lazy: true
    };
  
    
    const groups = params["proxy-groups"];
    groups.push(HongKong, TaiWan, Singapore, Japan, America);
  
  
    return params;
  }

**Comment by MystiPanda** [comment]
感谢反馈，确实有可能不小心动到某些代码了，我大概知道是哪里的问题了，今天再检查修复一下。

**Comment by MystiPanda** [comment]
已修复，重新下载安装即可
