### ISSUE TITLE
怎样能像clash那样分组节点，然后自定义规则走什么节点啊

### ISSUE THREAD

**Issue by flylj999** [clash-verge-rev/clash-verge-rev#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jmui114** [comment]
想倒腾的话，可以直接去研究虚空终端的文档：
https://wiki.metacubex.one/

不香倒腾的话，直接去订阅转换，逐步挑一个适合你的模板
