### ISSUE TITLE
[Feature]建议修改设置中的mixed port

### ISSUE THREAD

**Issue by ForestL18** [clash-verge-rev/clash-verge-rev#350]
### Is your feature request related to a problem? Please describe.

看到最新的1.5.0的更新日志，发现可以设置http和socks端口，但是找了一圈没发现，最后发现合并在mixed port里面

### Describe the solution you'd like

鉴于1.5.0的更新，建议修改将设置中的mixed port修改为ports setting，避免引起歧义

### Describe alternatives you've considered

同上

**Comment by MystiPanda** [comment]
没注意到，下个版本修改
