### ISSUE TITLE
滚动条可以稍微大一点，有点难点到

### ISSUE THREAD

**Issue by studentluo** [clash-verge-rev/clash-verge-rev#353]
### Is your feature request related to a problem? Please describe.

反正我是150% 挺难准确点到滚动条上的  老是出现箭头

### Describe the solution you'd like

同上

### Describe alternatives you've considered

同上

**Comment by wonfen** [comment]
用滚轮啊。

**Comment by studentluo** [comment]
滚动条速度平滑一些看着舒服，滚轮有点晃眼睛👀


________________________________

**Comment by wonfen** [comment]
还是用滚轮吧，滚动条加宽也不符合现代设计理念。
