### ISSUE TITLE
[Feature] 请求恢复字段过滤功能

### ISSUE THREAD

**Issue by cesaryuan** [clash-verge-rev/clash-verge-rev#354]
### Is your feature request related to a problem? Please describe.

字段过滤功能最近在1.5.0中被删掉了，这导致无法控制那些字段可以应用在clash-verge中，不太方便。

删除掉字段过滤功能后，我无法应用我的 dns, external-ui, unified-delay, sub-rules 设置，不知道作者是如何考虑的呢，为什么新版本中删掉了这个功能呀？😂

### Describe the solution you'd like

恢复字段过滤功能

### Describe alternatives you've considered

无

**Comment by wonfen** [comment]
因为可以在配置中定义字段。
字段过滤（不勾选字段）的功能是忽略配置文件中的字段。

**Comment by MengNianxiaoyao** [comment]
> 因为可以在配置中定义字段。 字段过滤（不勾选字段）的功能是忽略配置文件中的字段。

我这里是有的订阅需要字段过滤来忽略配置文件中的字段，不然tun模式无法上网

**Comment by MystiPanda** [comment]
merge和script都可以实现

**Comment by MengNianxiaoyao** [comment]
> ### Is your feature request related to a problem? Please describe.
> 字段过滤功能最近在1.5.0中被删掉了，这导致无法控制那些字段可以应用在clash-verge中，不太方便。
> 
> 删除掉字段过滤功能后，我无法应用我的 dns, external-ui, unified-delay, sub-rules 设置，不知道作者是如何考虑的呢，为什么新版本中删掉了这个功能呀？😂
> 
> ### Describe the solution you'd like
> 恢复字段过滤功能
> 
> ### Describe alternatives you've considered
> 无
> 
> ### Additional context
> _No response_

找到处理字段的方法了，新建订阅，类型为merge或者script（个人觉得merge更好写），然后写配置就行了

**Comment by cesaryuan** [comment]
现在是默认启用clash配置里面的所有字段是吗？

**Comment by MystiPanda** [comment]
是的
