### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iFly0523** [clash-verge-rev/clash-verge-rev#355]
### Describe the bug

能安装上，但是启动不了。主要原因是GLiBC版本太低，在Ubuntu18.04上面该内核版本是2.27.但貌似最低要求不能低于2.28。请问有无大佬解决了这个问题。

### To Reproduce

nothing

### Platform

Linux

### System Version

Ubuntu18.04

### Software Version

1.4.3/1.5.0

**Comment by wonfen** [comment]
升级clibc版本。

**Comment by MystiPanda** [comment]
仓库的自动构建使用debian buster编译，已经尽可能地支持低版本glibc了，你这个版本实在是太低了，我的建议是升级系统，或者你可以看文档手动编译。

**Comment by org-den** [comment]
可以根据CONTRIBUTING.md配置环境进行编译：安装RUST和Node.js（Ubuntu 18.04下安装[17.9.1版本](https://nodejs.org/dist/v17.9.1/node-v17.9.1-linux-x64.tar.xz)），
