### ISSUE TITLE
[BUG]版本v1.5.0更新后，proxy-providers和rule-providers下载不了，也无提示

### ISSUE THREAD

**Issue by dongchengjie** [clash-verge-rev/clash-verge-rev#356]
### Describe the bug

**应用内猫咪图标按钮**点击更新后，providers链接的资源没有下载，尤其是rule-providers用的是可以**直连**的CDN链接，也无法将文件下载下来。
导致没有任何节点和规则，**回退版本到v1.4.11后恢复正常**。
另外，两个Provider面板的刷新按钮点击后无论成功与否均**无任何提示**。

### To Reproduce

我有两个订阅A、B。A为机场订阅，B为providers集成订阅。由于B中的providers地址在外网，v1.4.11可以在启用订阅A的前提下，右键订阅B使用，然后开始加载B中的providers，正常把B中的订阅下载下来。
升级版本v1.5.0后，如此操作便无法正常下载了。
其次，规则集也无法下载，即使可以直连访问，https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
回退版本后恢复正常，规则条数正常显示，应用目录也可找到对应文件

另外提个Feature
在providers面板点击“刷新”按钮，**无任何提示**，能不能加个提示
规则面板中Provider起码显示了规则的条数，代理面板中的Provider能不能显示**节点的个数**？因为proxy-providers是给use的吧，总节点的个数与原订阅中proxy-groups什么的没什么关系吧

### Platform

Windows

### System Version

windows10 21H1

### Software Version

v1.5.0

**Comment by MystiPanda** [comment]
我无法复现，我这边provider一切正常

**Comment by wonfen** [comment]
无近一步反馈，关闭。
