### ISSUE TITLE
[BUG]1.5.0版本script类型订阅无效

### ISSUE THREAD

**Issue by enximi** [clash-verge-rev/clash-verge-rev#358]
### Describe the bug

1.5.0版本script类型订阅无效，不报错。1.4.11正常。

### To Reproduce

使用1.5.0版本，建一个script订阅。

### Platform

Windows

### System Version

Windows 11 23H2

### Software Version

1.5.0

**Comment by wonfen** [comment]
已经修复了。重新下载安装下。
