### ISSUE TITLE
[BUG]tun模式无法访问google

### ISSUE THREAD

**Issue by yxmyxmyyy** [clash-verge-rev/clash-verge-rev#359]
### Describe the bug

节点是搭建在workers上的vless，不支持udp，原来clash-verge使用tun模式没问题，换成这个后使用tun模式google显示ERR_SSL_VERSION_OR_CIPHER_MISMATCH，配置已经关闭udp，规则用的ACL4SSR_Online_Mini，tun模式下，几乎所有流量都走了漏网之鱼，也就是match，没有走域名规则

### To Reproduce

02-08 23:43:26INFO
[TCP] [fdfe:dcba:9876::1]:24347(chrome.exe) --> [2607:f8b0:4005:80d::2004]:443 match Match using 🐟 漏网之鱼[🇺🇸 美国-cf]
这是日志，访问www.google.com

### Platform

Windows

### System Version

11

### Software Version

1.50

**Comment by wonfen** [comment]
检查你的配置文件和host，规则部分由内核处理，和GUI没关系。

**Comment by yxmyxmyyy** [comment]
关闭了clash设置中的ipv6，可以正常访问了，但是我服务器都是支持ipv6的。而且关闭ipv6使用tun模式，用查询ip网站查询ipv4是国外，ipv6是国内，可能还是tun模式有问题

**Comment by Jerry0527** [comment]
@yxmyxmyyy , 最新的1.5.1好像修复tun模式问题了，我这里卸载后重装正常了

**Comment by yxmyxmyyy** [comment]
> > 关闭了clash设置中的ipv6，可以正常访问了，但是我服务器都是支持ipv6的。而且关闭ipv6使用tun模式，用查询ip网站查询ipv4是国外，ipv6是国内，可能还是tun模式有问题
> 
> 这么明显，你的规则有问题，ipv6没有匹配到规则全部走了“漏网之鱼”。

我用的是域名规则，gfw和国外常见域名都走的是代理，- DOMAIN-SUFFIX,google.com,🚀 节点选择 谷歌也是走代理，系统代理模式下ipv6没问题，看连接也是域名匹配，但是tun模式就全走漏网之鱼了

**Comment by WuJunkai2004** [comment]
同样是google无法访问，
显示 www.google.com:443 doesn't match any rule using DIRECT
但是我漏网之鱼也是导向节点选择的，它也没有走节点

**Comment by cytown** [comment]
> 关闭了clash设置中的ipv6，可以正常访问了，但是我服务器都是支持ipv6的。而且关闭ipv6使用tun模式，用查询ip网站查询ipv4是国外，ipv6是国内，可能还是tun模式有问题

我没有设置ipv6也是这样，tun模式下传输到clash verge上的url只有ip和端口，没有域名信息。
