### ISSUE TITLE
[BUG]系统找不到指定文件os error 2

### ISSUE THREAD

**Issue by dreampowers** [clash-verge-rev/clash-verge-rev#36]
电脑win11
软件版本：1.4.1
安装后能正常打开，但是无法使用，添加订阅后点击更新订阅，也会更新，但是就是不显示任何节点，点击订阅链接选项框，以及很多操作都是直接报错这个，请看图片！已经重装无效，清理注册表重装也无效果！
![Snipaste_2023-11-30_16-21-40](https://github.com/wonfen/clash-verge-rev/assets/60321644/6ca7f9d6-d87e-4a54-9fbe-19de0638fd0e)

**Comment by wonfen** [comment]
尝试删除配置文件试试。
“设置”-> 拉倒最下面点开“应用目录”，删除里面的所有文件

**Comment by lebron8dong** [comment]
请问解决了么
