### ISSUE TITLE
[BUG].在Mac代理下如何使用翻译服务

### ISSUE THREAD

**Issue by DataSailor** [clash-verge-rev/clash-verge-rev#360]
### Describe the bug

我注意到在使用Clash代理时无法使用Apple系统所提供的翻译服务。
经查询，这是由于Apple翻译服务当检测到任何代理行为（即使derect）即拒绝服务。
我查询到了CFW下的解决方案如：https://github.com/ripperhe/Bob/issues/405
即将
```
"sequoia.apple.com"
"seed-sequoia.siri.apple.com"
```
两个地址加入bypass字段即可。

但我尝试将这两个网址加入到`系统代理-代理绕过`发现是无效的。同时，这个操作也导致原来此字段有的一些地址（似乎是127.0.0.1等）不存在了。
<img width="836" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/39119487/afabb662-3f64-4104-b29d-2b55c26639d5">

因此有两个问题：

- 在CVR中，应该如何将两个地址加入到bypass字段？
- 如何恢复代理绕过中原有的地址，或是不恢复有什么影响？

### To Reproduce

无

### Platform

Windows

### System Version

macOS 14.3.0

### Software Version

1.5.0

**Comment by wonfen** [comment]
mac系统的代理绕过规则是逗号隔开的，这样写即可：
127.0.0.1,www.bing.com,*.bing.com

**Comment by rjys365** [comment]
似乎代理绕过的原设定只能查看无法复制，希望也能修复一下
