### ISSUE TITLE
[BUG]没法适配最新的Windows 11 24H2

### ISSUE THREAD

**Issue by ColorAWA** [clash-verge-rev/clash-verge-rev#361]
### Describe the bug

更新Dev频道的Build 26052 后，无法更新最新的1.5.0，手动卸载更新后打开此应用会出现以下内容：
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/99065905/b27540b0-f5b0-4046-b3c4-47f8f47c8992)

### To Reproduce

卸载Clash Verge v1.4.11
安装Clash Verge 1.5.0
打开Clash Verge

### Platform

Windows

### System Version

Windows 11 24H2 26052

### Software Version

1.5.0

### Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/99065905/bca18ed9-d103-4c2e-b617-d57e124b8f68)

### Additional Information

请快速修复

**Comment by MystiPanda** [comment]
下载错了，请下载x64版本
