### ISSUE TITLE
[Feature]合并文件

### ISSUE THREAD

**Issue by tangwenlongNO1** [clash-verge-rev/clash-verge-rev#362]
### Is your feature request related to a problem? Please describe.

![QQ截图20240210150219](https://github.com/clash-verge-rev/clash-verge-rev/assets/106858241/9be8462d-41ed-4467-8494-4469fa3f261f)
像cfw有合并文件的功能diff

### Describe the solution you'd like

加入diff功能

### Describe alternatives you've considered

配置更新自动覆盖

**Comment by MystiPanda** [comment]
去官网看看merge怎么用
