### ISSUE TITLE
[Feature]Add optional auto-scrolling to logging and connection screens

### ISSUE THREAD

**Issue by Ffffffffchopin** [clash-verge-rev/clash-verge-rev#363]
### Is your feature request related to a problem? Please describe.

I'm often bothered by the fact that I have to keep manually scrolling down in the connection screen to keep up with the constantly refreshing connection history.

![屏幕截图 2024-02-10 221836](https://github.com/clash-verge-rev/clash-verge-rev/assets/97517883/98eefb4f-9526-450c-921b-c66ee4d65f2b)

### Describe the solution you'd like

With an optional auto-scroll feature, the interface automatically scrolls to the latest connection history when turned on for a quick overview of current connections, and when turned off for a closer look at previous connections.

### Describe alternatives you've considered

There is a similar auto-scroll option in VSCode's output interface for reference

![屏幕截图 2024-02-10 222242](https://github.com/clash-verge-rev/clash-verge-rev/assets/97517883/ee839d0b-8956-48ce-ab8d-d34665b6df39)

### Additional context

因为有时候代理设置不正确的话流量就会飞快地跑，为了监视流量的情况要用Connection界面，但每次都要手动滑到底太麻烦了，所以建议做一个自动滚动的功能。

**Comment by wonfen** [comment]
右上角切换显示方法，另外可以筛选你想查看的条目。
