### ISSUE TITLE
[BUG] 内核无法授权

### ISSUE THREAD

**Issue by AmazonXYZ** [clash-verge-rev/clash-verge-rev#365]
### Describe the bug

按照 #125 要求开启TUN模式，在内核授权时，正常弹出提权窗口，输入后报错：
`Failed to set capabilities on file '/tmp/.mount_Clashxxxxx/usr/bin/clash-meta: Permission denied.`

### To Reproduce

正常启动软件，在设置页选择内核设置，并尝试授权。

### Platform

Linux

### System Version

Manjaro-rolling-20240211

### Software Version

1.5.0-AppImage

**Comment by MystiPanda** [comment]
不要用appimage

**Comment by wonfen** [comment]
无进一步反馈，关闭。
