### ISSUE TITLE
调用msedgewebview2.exe，占用GPU 40%？？？？？？？？？？？？？？？

### ISSUE THREAD

**Issue by kakapas** [clash-verge-rev/clash-verge-rev#366]
### Describe the bug

一个代理软件，调用msedgewebview2.exe，和dwm.exe一起占用GPU 40%，到底在做什么？？？
clash原版不会调用msedgewebview2.exe

![clash](https://github.com/clash-verge-rev/clash-verge-rev/assets/125766482/3b996e05-59a0-47df-9619-547e15fb6c52)

![clash2](https://github.com/clash-verge-rev/clash-verge-rev/assets/125766482/d3d377cb-2c4b-4ba1-86f9-9057798d5e48)

### To Reproduce

每次启动软件都会调用msedgewebview2.exe，占用GPU

### Platform

Windows

### System Version

win10

### Software Version

1.51

**Comment by MystiPanda** [comment]
clash verge rev使用tauri框架开发，依赖于系统webview，调用webview2是很正常的，至于dwm.exe,看看[这里](https://zh.wikipedia.org/wiki/%E6%A1%8C%E9%9D%A2%E8%A6%96%E7%AA%97%E7%AE%A1%E7%90%86%E5%93%A1)

**Comment by kakapas** [comment]
> clash verge rev使用tauri框架开发，依赖于系统webview，调用webview2是很正常的，至于dwm.exe,看看[这里](https://zh.wikipedia.org/wiki/%E6%A1%8C%E9%9D%A2%E8%A6%96%E7%AA%97%E7%AE%A1%E7%90%86%E5%93%A1)

请问GPU占用率，能否优化一下？

**Comment by MystiPanda** [comment]
在界面设置中把流量图显关了

**Comment by kakapas** [comment]
> 在界面设置中把流量图显关了

谢谢，瞬间就舒畅了，哈哈~
