### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by litianjun05090** [clash-verge-rev/clash-verge-rev#367]
### Is your feature request related to a problem? Please describe.

为什么自动测试功能没有了呀，以前点击测试会自动开始测试，很省事。现在还要手动点击一次，操作成本高了好多。。。

### Describe the solution you'd like

自动测试功能没有了

### Describe alternatives you've considered

自动测试功能没有了

**Comment by wonfen** [comment]
考虑下个版本加回去

**Comment by Amnesiash** [comment]
> 考虑下个版本加回去

其实看用户习惯，可能有些用户不会喜欢，可以的话最好发起个投票，当然也可以花点开发资源增加一个开关
