### ISSUE TITLE
[BUG] 任务栏图标呈现出非预期效果

### ISSUE THREAD

**Issue by shikkoku** [clash-verge-rev/clash-verge-rev#368]
### Describe the bug

任务栏图标呈现出非预期效果，背景有明显的黑块
![Screenshot 2024-02-12 160317](https://github.com/clash-verge-rev/clash-verge-rev/assets/4697177/0c2b197e-8e2d-49f4-8dfe-5c53a161749d)

### To Reproduce

更新到1.5.1后出现此现象，步骤：打开主界面，检视任务栏图标（1920x1080 100%缩放）。

### Platform

Windows

### System Version

Microsoft Windows 10 Enterprise LTSC 10.0.17763 N/A Build 17763

### Software Version

1.5.1

**Comment by wonfen** [comment]
感觉像win的显示bug；重启电脑试试看？

**Comment by shikkoku** [comment]
> 感觉像win的显示bug；重启电脑试试看？

可能是，现在正常了，那我先关了吧。
