### ISSUE TITLE
[Feature] 连接界面信息优化

### ISSUE THREAD

**Issue by KinComet** [clash-verge-rev/clash-verge-rev#370]
### Is your feature request related to a problem? Please describe.

现在的连接详细界面不太简洁直观，不利于快速获取想要的信息，执行需要的操作(CLOSE)

### Describe the solution you'd like

希望可调整列长度、持久化列隐藏偏好及过滤条件，添加Chains的简化版（只显示最终Proxy）

### Describe alternatives you've considered

对于每个连接，多行显示所有启用的列元素，以免去需要横向拖动的问题，也可能是一个不错的方案。

### Additional context

已知有简单界面，但其中不包含Proxy名称。我关闭了切换时自动打断，故有查看需求。

**Comment by wonfen** [comment]
画个图看看你说的是什么设计要求？只看描述看不明白。

**Comment by KinComet** [comment]
多行显示吗？我指的是类似这样的界面
![150f9b39-35fb-4a69-9ee0-6208bcef1e26](https://github.com/clash-verge-rev/clash-verge-rev/assets/111748332/b949a1d4-20be-4c80-8766-51eac268a5f9)

**Comment by wonfen** [comment]
右上角可以切换显示方法，和你上图这个一样：
<img width="892" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/96291150/a88f71c5-8dfc-4572-bbc0-2c3ded8e2761">

**Comment by KinComet** [comment]
> 右上角可以切换显示方法，和你上图这个一样：

是的，如 Additional context 所述，切换后的这个界面里面不包含 Proxy 名称(以及其它后续可能需要的信息)，以这个方面着手也可以解决使用需要，但本 issue 针对的是表格界面提出的。
