### ISSUE TITLE
[Feature] 代理界面记录滚动位置

### ISSUE THREAD

**Issue by KinComet** [clash-verge-rev/clash-verge-rev#371]
### Is your feature request related to a problem? Please describe.

从其他界面回到代理界面时不会自动回到上次滚动位置，在代理数量大、页面长时不便于快速切换节点

### Describe the solution you'd like

切换页面时回到上次的滚动位置

### Describe alternatives you've considered

N/A

**Comment by wonfen** [comment]
好提议
