### ISSUE TITLE
[Feature] 增强连接搜索

### ISSUE THREAD

**Issue by KinComet** [clash-verge-rev/clash-verge-rev#374]
### Is your feature request related to a problem? Please describe.

目前连接的过滤条件似乎不支持检索 Process 和 代理组，目前有针对这两个检索并打断全部的需求，希望添加这些支持。

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

**Comment by wonfen** [comment]
“目前有针对这两个检索并打断全部的需求”
这句话没看懂

**Comment by KinComet** [comment]
> “目前有针对这两个检索并打断全部的需求” 这句话没看懂

检索代理组或Process，然后手动关闭该检索条件下的所有连接，而不是用Verge自带的自动打断连接
