### ISSUE TITLE
[BUG]After the latest version, the sleep mode of the laptop does not work

### ISSUE THREAD

**Issue by Maneeha1234SL** [clash-verge-rev/clash-verge-rev#375]
### Describe the bug

After the latest version, the sleep mode of the laptop does not work
This happens when using TUN mode.

### To Reproduce

This happens when using TUN mode.

### Platform

Windows

### System Version

Edition	Windows 11 Home Single Language Version	23H2 Installed on	‎1/‎23/‎2024 OS build	22631.3085 Experience	Windows Feature Experience Pack 1000.22684.1000.0

### Software Version

1.5.1

**Comment by wonfen** [comment]
what do you mean by "the sleep mode of the laptop does not work"?

**Comment by wonfen** [comment]
无进一步反馈，关闭。
