### ISSUE TITLE
[Feature] 提供pre_release安装包

### ISSUE THREAD

**Issue by gs507** [clash-verge-rev/clash-verge-rev#377]
### Is your feature request related to a problem? Please describe.

cmfa和mihomo都有pre release给大众预览功能和debug

### Describe the solution you'd like

希望跟进，每次更改都更新个exe出来，有问题也可及时回馈，不会让bug遗留到正式版本

### Describe alternatives you've considered

-

**Comment by wonfen** [comment]
已经采纳
