### ISSUE TITLE
可不可以在右下角加一个启动通知

### ISSUE THREAD

**Issue by eight8eggs** [clash-verge-rev/clash-verge-rev#378]
### Is your feature request related to a problem? Please describe.

..

### Describe the solution you'd like

一个很小的想法，可不可以在打开的时候右下角弹一个通知。之前选择静默通知，没有右下角弹窗感觉有些分不清是否启动。一点小建议。

### Describe alternatives you've considered

..

### Additional context

..

**Comment by wonfen** [comment]
没听明白需要通知什么内容？

**Comment by eight8eggs** [comment]
emmm……大概就是提示一下软件已经启动了这样？总之就是在静默启动的时候可以在弹出一个通知提醒一下？
一点小建议。😊

**Comment by MystiPanda** [comment]
不考虑
