### ISSUE TITLE
[BUG]卸载软件时自动清空了安装目录

### ISSUE THREAD

**Issue by lishidegit** [clash-verge-rev/clash-verge-rev#379]
### Describe the bug

1.5.1arm64setup无法在64位win11上使用，使用自带的卸载程序卸载时，自动清空了安装目录

### To Reproduce

安装软件后打开，弹出蓝色对话框，提示不能使用，使用软件自带的卸载程序，对话框标题是在卸载程序，实际在删除安装目录的文件

### Platform

Windows

### System Version

windows11 22H2 22621.2861

### Software Version

1.5.1

**Comment by wonfen** [comment]
你的win系统是arm构架的cpu吗？

**Comment by lishidegit** [comment]
> 你的win系统是arm构架的cpu吗？

抱歉，我装错软件了
