### ISSUE TITLE
无法取消自动切换节点

### ISSUE THREAD

**Issue by JasonxlxCharles** [clash-verge-rev/clash-verge-rev#380]
### Describe the bug

我之前一直固定使用一个节点，自从更新了最新版本之后，发现每隔一段时间就会自动切换到默认的速度最快的那个节点，之前还可以通过Clash字段修改，但是最新版本已经移除了这个设置选项了，请问现在该咋办？

### To Reproduce

。

### Platform

Windows

### System Version

Windows10

### Software Version

1.5.1

**Comment by wonfen** [comment]
截图看看你的节点页面，你怎么选的节点？大概率猜到是选了分组的节点，这个分组属于URL-test

**Comment by Mosklia** [comment]
![图片](https://github.com/clash-verge-rev/clash-verge-rev/assets/38348444/cc162f5c-576c-44cc-8010-7213415a7cf3)
我这边也有类似问题，代理这边一个节点都不显示。但是我记得刚装好的时候是可以显示的，不知道什么情况。

**Comment by wonfen** [comment]
> ![图片](https://private-user-images.githubusercontent.com/38348444/305355235-cc162f5c-576c-44cc-8010-7213415a7cf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDgxOTgsIm5iZiI6MTcwODEwNzg5OCwicGF0aCI6Ii8zODM0ODQ0NC8zMDUzNTUyMzUtY2MxNjJmNWMtNTc2Yy00NGNjLTgwMTAtNzIxMzQxNWE3Y2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE4MjQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkM2RiNzcxZTE4ZjY5OTBlMGRhMWJmZTM3NGFmZjc0MTM1YzM1OTFjYWRmZDAwMDAwYTY5OWM4MzM1YWQ0N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CJ0JAR8dglTgl0BLvtWntLE9_nAGSQuCzLC_QogGwkQ) 我这边也有类似问题，代理这边一个节点都不显示。但是我记得刚装好的时候是可以显示的，不知道什么情况。
> 
> 补充一下电脑信息 ![图片](https://private-user-images.githubusercontent.com/38348444/305357649-a833a187-0bc9-4640-a3af-0942c2ea3639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDgxOTgsIm5iZiI6MTcwODEwNzg5OCwicGF0aCI6Ii8zODM0ODQ0NC8zMDUzNTc2NDktYTgzM2ExODctMGJjOS00NjQwLWEzYWYtMDk0MmMyZWEzNjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE4MjQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YWE5MWJkN2M2ZjAwNDQ2MmY5MDI5NGVmNTU5MWExMDQyODBlNzU0OTkxNmViMWE4NTc3NDBjOWRjMDY2ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4x1AtQhvqfUfcAIA14E7hucO5WsTXyZq3vfL888MhWk)

日志？

**Comment by Mosklia** [comment]
> > ![图片](https://private-user-images.githubusercontent.com/38348444/305355235-cc162f5c-576c-44cc-8010-7213415a7cf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDgxOTgsIm5iZiI6MTcwODEwNzg5OCwicGF0aCI6Ii8zODM0ODQ0NC8zMDUzNTUyMzUtY2MxNjJmNWMtNTc2Yy00NGNjLTgwMTAtNzIxMzQxNWE3Y2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE4MjQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkM2RiNzcxZTE4ZjY5OTBlMGRhMWJmZTM3NGFmZjc0MTM1YzM1OTFjYWRmZDAwMDAwYTY5OWM4MzM1YWQ0N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CJ0JAR8dglTgl0BLvtWntLE9_nAGSQuCzLC_QogGwkQ) 我这边也有类似问题，代理这边一个节点都不显示。但是我记得刚装好的时候是可以显示的，不知道什么情况。
> > 补充一下电脑信息 ![图片](https://private-user-images.githubusercontent.com/38348444/305357649-a833a187-0bc9-4640-a3af-0942c2ea3639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDgxOTgsIm5iZiI6MTcwODEwNzg5OCwicGF0aCI6Ii8zODM0ODQ0NC8zMDUzNTc2NDktYTgzM2ExODctMGJjOS00NjQwLWEzYWYtMDk0MmMyZWEzNjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE4MjQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YWE5MWJkN2M2ZjAwNDQ2MmY5MDI5NGVmNTU5MWExMDQyODBlNzU0OTkxNmViMWE4NTc3NDBjOWRjMDY2ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4x1AtQhvqfUfcAIA14E7hucO5WsTXyZq3vfL888MhWk)
> 
> 日志？

[Pastebin](https://pastebin.com/m5YaaTeB)
无法将日志模式切换到除 info 以外的模式，提示说“Network Error”.
![图片](https://github.com/clash-verge-rev/clash-verge-rev/assets/38348444/38706b2b-2cfd-4f81-be28-168e07c89da1)
