### ISSUE TITLE
[BUG] No root permission to enable TUN mode on macOS/Linux

### ISSUE THREAD

**Issue by 31core** [clash-verge-rev/clash-verge-rev#381]
### Describe the bug

When I turn on TUN mode, the application shows `Refresh clash config`, however the ERRER log says: `Start TUN listening error: configure tun interface: Connect: operation not permitted`

<img width="912" alt="截屏2024-02-15 00 54 47" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/49990217/55090793-f1f9-4b91-a3d9-2508bcec6769">

### To Reproduce

Turn on TUN mode on macOS or Linux platforms.

### Platform

MacOS

### System Version

14.3.1 (23D60)

### Software Version

v1.5.1

**Comment by wonfen** [comment]
为什么不看文档，不看置顶faq

**Comment by wangwei2-ola** [comment]
> 为什么不看文档，不看置顶faq

看了，没用，执行了也不行，不执行不能启动软件。执行后能启动，但是不能tun
