### ISSUE TITLE
[BUG]1.5.0、1.5.1版本启用TUN模式后无互联网访问权限

### ISSUE THREAD

**Issue by PrimeDeng** [clash-verge-rev/clash-verge-rev#382]
### Describe the bug

1.5.0、1.5.1版本安装服务并启用TUN模式后（客户端在此阶段全程无报错），虽系统内非UWP应用能正常使用，但UWP应用和系统应用无法访问网络（如Microsoft Store报错0x800704cf），且任务栏网络图标未被Meta Tunnel替换。
1.4.11版本无此问题，Windows 11似乎也无此问题。

### To Reproduce

Windows 10系统下1.5.0或1.5.1版本客户端内安装服务并启用TUN模式

### Platform

Windows

### System Version

Windows 10 Pro 19045.3803

### Software Version

1.5.0、1.5.1

**Comment by wonfen** [comment]
注意：服务模式的唯一作用就是为了可以不用管理员模式启用tun。
尝试卸载重新安装。

**Comment by Sovy0** [comment]
我的电脑是 win10，TUN 也模式无法联网，降到 1.4.11 就可以了，不知道是哪里的问题。

**Comment by PrimeDeng** [comment]
> 注意：服务模式的唯一作用就是为了可以不用管理员模式启用tun。 尝试卸载重新安装。

显而易见的是，已经尝试过卸载重新安装，这也是为什么前面提到了1.4.11版本无此问题。在我的设备上只有1.5.0和1.5.1版本存在此问题。
该问题应为1.5.0、1.5.1版本的Tun模式本身的问题，1.4.11版本即便服务模式为关Tun模式也能正常使用。

**Comment by wonfen** [comment]
> > 注意：服务模式的唯一作用就是为了可以不用管理员模式启用tun。 尝试卸载重新安装。
> 
> 显而易见的是，已经尝试过卸载重新安装，这也是为什么前面提到了1.4.11版本无此问题。在我的设备上只有1.5.0和1.5.1版本存在此问题。 该问题应为1.5.0、1.5.1版本的Tun模式本身的问题，1.4.11版本即便服务模式为关Tun模式也能正常使用。

因为1.5.0升级了meta内核。
试试这个方法：
打开tun模式以后，进入“设置”菜单，找到“应用目录”，文本编辑器编辑clash-verge.yaml文件，找到tun配置部分，在tun配置的下面一行加上mtu: 1500。
```
tun:
  mtu: 1500
```
设置方法参考[这个回复](https://github.com/clash-verge-rev/clash-verge-rev/issues/329#issuecomment-1925513999)

**Comment by Sovy0** [comment]
> > > 注意：服务模式的唯一作用就是为了可以不用管理员模式启用tun。 尝试卸载重新安装。
> > 
> > 
> > 显而易见的是，已经尝试过卸载重新安装，这也是为什么前面提到了1.4.11版本无此问题。在我的设备上只有1.5.0和1.5.1版本存在此问题。 该问题应为1.5.0、1.5.1版本的Tun模式本身的问题，1.4.11版本即便服务模式为关Tun模式也能正常使用。
> 
> 因为1.5.0升级了meta内核。 试试这个方法： 打开tun模式以后，进入“设置”菜单，找到“应用目录”，文本编辑器编辑clash-verge.yaml文件，找到tun配置部分，在tun配置的下面一行加上mtu: 1500。
> 
> ```
> tun:
>   mtu: 1500
> ```
> 
> 设置方法参考[这个回复](https://github.com/clash-verge-rev/clash-verge-rev/issues/329#issuecomment-1925513999)
> 
> 记得反馈是否生效

试了下这个方法，发现还是不能用，然后我试着把 1.5.1 版本的新内核替换掉 1.4.11 的旧内核，发现可以正常使用，所以应该不是内核的原因。

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/120722648/048d86eb-63b7-4fd0-8b73-4f1b4e3fb374)

**Comment by PrimeDeng** [comment]
> > > 注意：服务模式的唯一作用就是为了可以不用管理员模式启用tun。 尝试卸载重新安装。
> > 
> > 
> > 显而易见的是，已经尝试过卸载重新安装，这也是为什么前面提到了1.4.11版本无此问题。在我的设备上只有1.5.0和1.5.1版本存在此问题。 该问题应为1.5.0、1.5.1版本的Tun模式本身的问题，1.4.11版本即便服务模式为关Tun模式也能正常使用。
> 
> 因为1.5.0升级了meta内核。 试试这个方法： 打开tun模式以后，进入“设置”菜单，找到“应用目录”，文本编辑器编辑clash-verge.yaml文件，找到tun配置部分，在tun配置的下面一行加上mtu: 1500。
> 
> ```
> tun:
>   mtu: 1500
> ```
> 
> 设置方法参考[这个回复](https://github.com/clash-verge-rev/clash-verge-rev/issues/329#issuecomment-1925513999)
> 
> 记得反馈是否生效

生效了。
自1.4.11升级到1.5.1并按照链接中的方法添加"mtu: 1500"后，现在TUN启用后Microsoft Store之类的系统应用可以正常通过Clash联网而不是报错（如0x800704cf）。
奇怪的是，这个问题在Windows 11（26040.1000）似乎并不存在，即便配置中没有"mtu: 1500"Microsoft Store之类的应用也可以通过Clash正常联网。

**Comment by Sovy0** [comment]
我的现在也可以了，简单描述一下过程，如果有人遇到一样的情况可以参考一下：

我是用 scoop 安装的，使用 `update` 命令更新后，直接从开始菜单打开软件，无法连接互联网，Log 界面空白无任何信息；

使用 `reset` 命令回退到 1.4.11 版本后，从开始菜单打开软件，一切正常，切换回 1.5.1，还是不能用，只有切换到 1.4.11 可以用；

今天无意中关闭 1.4.11 版本，找到安装路径直接从文件夹中打开了 1.5.1 版本，发现可以使用了，然后使用 scoop reset 到 1.5.1 版本，尝试重启电脑，一切正常；再关闭软件，直接从开始菜单打开软件，也一切正常。

**结论：** 如果是用 scoop 安装的话，更新后第一次使用需要从安装目录打开一次软件。

具体原因不清楚，也可能只是个例，仅供参考。
