### ISSUE TITLE
[Feature]能否在左侧栏或者代理组页面加一个系统代理开关

### ISSUE THREAD

**Issue by yll007007** [clash-verge-rev/clash-verge-rev#383]
### Is your feature request related to a problem? Please describe.

系统代理开关比较重要，但是位置太深，可否放在左侧栏或者在代理组界面加一个开关，这样选择完节点就能直接开启代理，也不用再右键托盘图标开启，比较方便

### Describe the solution you'd like

可否放在左侧栏或者在代理组界面加一个开关

### Describe alternatives you've considered

无

**Comment by wonfen** [comment]
没想好如何布局，这个一直都想改善

**Comment by rainbowflesh** [comment]
> 没想好如何布局，这个一直都想改善

加在代理页的右上角, 放代理规则模式旁边?
