### ISSUE TITLE
能否根据事件线列出流量的使用情况[Feature]

### ISSUE THREAD

**Issue by Ffffffffchopin** [clash-verge-rev/clash-verge-rev#384]
### Is your feature request related to a problem? Please describe.

目前的连接页面中只有自启动后总的流量数据，如果能根据时间和域名自动计算流量数据的话会更方便看出哪些网站消耗流量比较大

### Describe the solution you'd like

目前的连接页面中只有自启动后总的流量数据，如果能根据时间和域名自动计算流量数据的话会更方便看出哪些网站消耗流量比较大

### Describe alternatives you've considered

目前的连接页面中只有自启动后总的流量数据，如果能根据时间和域名自动计算流量数据的话会更方便看出哪些网站消耗流量比较大

### Additional context

目前的连接页面中只有自启动后总的流量数据，如果能根据时间和域名自动计算流量数据的话会更方便看出哪些网站消耗流量比较大

**Comment by wonfen** [comment]
你这个需求可以通过连接菜单下切换显示方法实现。
<img width="1037" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/96291150/711ca5ef-bf11-438a-b491-3e17327617b4">

**Comment by wonfen** [comment]
无进一步反馈，关闭。
