### ISSUE TITLE
[Feature]可以添加批量导入和导出“订阅”的功能嘛？

### ISSUE THREAD

**Issue by geekoutnet** [clash-verge-rev/clash-verge-rev#385]
### Is your feature request related to a problem? Please describe.

就是每次重装系统都需要全部重新挨个导入订阅，比较麻烦

### Describe the solution you'd like

在订阅集合页面添加导入和导出按钮，可以批量或者选择导出，然后可以在另一台机器批量导入这种功能

### Describe alternatives you've considered

有考虑过自己看源码开发，但是时间不充足啊

**Comment by wonfen** [comment]
备份你的订阅目录，设置打开“应用目录”下备份profiles
