### ISSUE TITLE
[BUG] Apple LOGO 旁边会出现App LOGO

### ISSUE THREAD

**Issue by nanjingsunallen** [clash-verge-rev/clash-verge-rev#386]
### Describe the bug

开启App的时候，在左上角Apple LOGO处会有App LOGO出现
![Bug 截图](https://github.com/clash-verge-rev/clash-verge-rev/assets/83351864/8815d426-9d7a-4697-83b2-437a46737f8d)

### To Reproduce

打开App就会有这个BUG

### Platform

MacOS

### System Version

14.3.1

### Software Version

1.5.1

**Comment by wonfen** [comment]
系统版本？是否用了任何任务栏插件？

**Comment by wonfen** [comment]
重复： https://github.com/clash-verge-rev/clash-verge-rev/issues/122

**Comment by nanjingsunallen** [comment]
> 系统版本？是否用了任何任务栏插件？

macOS 14.3.1，没有使用任务栏插件

**Comment by biggding** [comment]
出现了相同的鬼影。

**Comment by jkhuangfu** [comment]
啥时候能修复啊，好难受
