### ISSUE TITLE
[Feature]能否为便携版加上更新功能

### ISSUE THREAD

**Issue by Fatty911** [clash-verge-rev/clash-verge-rev#387]
### Is your feature request related to a problem? Please describe.

我不懂typescript和rust，能看懂python和Java，用AI工具python写了个更新程序，但是在Windows下".\Clash Verge.exe" -v不显示版本号，希望作者可以考虑这个想法把这个功能加进去

### Describe the solution you'd like

import os
import platform
import subprocess
import requests
import zipfile

# 获取本机操作系统
def get_os():
    if platform.system() == "Windows":
        return "windows"
    elif platform.system() == "Linux":
        return "linux"
    elif platform.system() == "Darwin":
        return "macos"
    else:
        raise Exception("Unsupported OS")

# 获取本地ClashVergeRev版本
def get_local_version():
    os_type = get_os()
    try:
        if os_type == "windows":
            p = subprocess.Popen(["Clash Verge.exe", "-v"], stdout=subprocess.PIPE)
        elif os_type == "linux" or os_type == "macos":
            p = subprocess.Popen(["./clash-meta", "-v"], stdout=subprocess.PIPE)
        else:
            raise Exception("不支持的操作系统")
        output, err = p.communicate()
        if err:
            raise Exception(err)
        return output.decode("utf-8").strip()
    except Exception as e:
        raise Exception("获取本地ClashVergeRev版本失败: %s" % e)

# 获取GitHub上最新的ClashVergeRev版本
def get_latest_version():
    url = "https://api.github.com/repos/clash-verge-rev/clash-verge-rev/releases/latest"
    response = requests.get(url)
    if response.status_code != 200:
        raise Exception("获取GitHub上最新ClashVergeRev版本失败")
    data = response.json()
    return data["tag_name"]

# 下载最新版本
def download_latest_version(os):
    url = "https://github.com/clash-verge-rev/clash-verge-rev/releases/download/%s/Clash.Verge_%s_%s_portable.zip" % (
        get_latest_version(),
        get_latest_version(),
        os,
    )
    response = requests.get(url, stream=True)
    if response.status_code != 200:
        raise Exception("下载最新版本失败")
    with open("Clash.Verge_%s_%s_portable.zip" % (get_latest_version(), os), "wb") as f:
        for chunk in response.iter_content(chunk_size=1024):
            f.write(chunk)

# 结束ClashVergeRev进程
def kill_clashverge():
    if platform.system() == "Windows":
        try:
            subprocess.Popen(["taskkill", "/F", "/IM", "Clash Verge.exe"])
        except Exception as e:
            raise Exception("结束ClashVergeRev进程失败: %s" % e)
    elif platform.system() == "Linux" or platform.system() == "Darwin":
        try:
            subprocess.Popen(["killall", "clash-meta"])
        except Exception as e:
            raise Exception("结束ClashVergeRev进程失败: %s" % e)

# 解压并覆盖旧文件
def extract_and_overwrite():
    with zipfile.ZipFile("Clash.Verge_%s_%s_portable.zip" % (get_latest_version(), get_os())) as z:
        z.extractall()

# 启动ClashVergeRev
def start_clashverge():
    if platform.system() == "Windows":
        subprocess.Popen(["Clash Verge.exe"])
    elif platform.system() == "Linux" or platform.system() == "Darwin":
        subprocess.Popen(["./clash-meta"])

# 主函数
def main():
    # 获取本机操作系统
    os = get_os()

    # 获取本地ClashVergeRev版本
    local_version = get_local_version()

    # 获取GitHub上最新的ClashVergeRev版本
    latest_version = get_latest_version()

    # 版本号是否匹配
    if local_version != latest_version:
        print("本地版本: %s, 最新版本: %s, 正在更新..." % (local_version, latest_version))

        # 下载最新版本
        download_latest_version(os)

        # 结束ClashVergeRev进程
        kill_clashverge()

        # 解压并覆盖旧文件
        extract_and_overwrite()

        # 启动ClashVergeRev
        start_clashverge()

        print("更新成功!")
        os.system("pause")
    else:
        print("已经是最新版本")
        os.system("pause")

if __name__ == "__main__":
    main()

### Describe alternatives you've considered

便携版点击更新按钮后，调用python脚本更新

**Comment by wonfen** [comment]
搞不懂为何你们那么执着于便携版？

**Comment by Fatty911** [comment]
> 搞不懂为何你们那么执着于便携版？

多硬盘多系统，也包括多个Windows系统，所有软件能用绿色我就用绿色的，哪个系统崩了之后不用重新下软件安装了，创建个桌面快捷方式就行了

**Comment by wonfen** [comment]
我觉得软件还是保持精简高效的好，各种小众的功能不断加入，只会让软件越来越臃肿。
既然都用便携版了，定期来看看是否有新版发布不也可以。

**Comment by MystiPanda** [comment]
我们不推荐便携版，也不会提供任何关于便携版的功能实现。
