### ISSUE TITLE
[Feature]能否在“订阅”模块里增加手动排序功能，包括订阅和merge，以及增加订阅和maerge的关联功能

### ISSUE THREAD

**Issue by zuixiangsi** [clash-verge-rev/clash-verge-rev#389]
### Is your feature request related to a problem? Please describe.

想把一些经常用的订阅以及merge放在尽量靠前的地方，但是有的订阅和merge是后来才添加的，想通过手动排序到前面，否则切换的时候比较麻烦。

另外，能否添加订阅和maerge的关联，我为每个订阅增加了不同的规则和分组。每次切换订阅需要手动禁止原来的maerge并启动相对应的maerge，这样特别麻烦，如果能对每个订阅和maerge进行手动关联，切换机场的时候就比较丝滑了。

### Describe the solution you'd like

如上

### Describe alternatives you've considered

如上

**Comment by wonfen** [comment]
说实话没听懂你的需求是什么

**Comment by zuixiangsi** [comment]
1、“订阅”里的机场订阅可以手动拖拽进行排序
2、可以对机场订阅与merge进行关联，不用需要在手动进行切换。

比如：

我通过merge为A机场添加了额外规则和分组，这个merge我命名为A1
我通过merge为B机场添加了额外规则和分组，这个merge我命名为B1
我通过merge为C机场添加了额外规则和分组，这个merge我命名为C1

当我从A机场切换成C机场，需要先禁用A1，在启动C1。

能否直接增加一个关联功能，我直接把A机场和A1关联，B机场和B1关联，C机场和C1关联。

这样我切换机场的时候不需要去禁用当前的merge在去启动另一个merge。

就是这个意思，不知道这次我讲明白了吗。

**Comment by wonfen** [comment]
1.本来就可以拖动排序（订阅显示卡左上角6个点）
2.关联功能没想好如何实现（配置文件用什么条件进行关联？）

**Comment by zuixiangsi** [comment]
拖动排序以前真没发现，疏忽了……可否为merge也增加个排序功能。

关联的话，我觉得可以通过名字，例如编辑机场订阅里面，增加一个“关联”按钮，点开关联按钮后弹出菜单，在菜单里显示已经创建的merge，通过勾选进行关联。

**Comment by sususu98** [comment]
#427 感觉你在说这件事情。
