### ISSUE TITLE
[Feature] 如何在linux 终端启动一个代理服务，不使用图形化界面

### ISSUE THREAD

**Issue by sunjiabin17** [clash-verge-rev/clash-verge-rev#390]
### Is your feature request related to a problem? Please describe.

can not start a proxy service in linux terminal without graphical interface, and does it support auto update subscription?

### Describe the solution you'd like

exec one specific cmd to start up a proxy service

### Describe alternatives you've considered

--

**Comment by wonfen** [comment]
使用内核调用配置文件。具体方法请自行搜搜。

**Comment by sunjiabin17** [comment]
@wonfen 我用之前的clash终端工具不能用狗狗代理，之前问客服说是啥不支持，不支持hy协议
