### ISSUE TITLE
[BUG] 高分屏字体重叠问题

### ISSUE THREAD

**Issue by s-chance** [clash-verge-rev/clash-verge-rev#391]
### Describe the bug

在3456x2160分辨率下，打开软件正常大小显示时部分字体重叠。可以通过全屏进行缓解，但是编辑文件打开小界面时又会出现字体部分重叠的现象，但不算严重，还能辨识。

### To Reproduce

打开软件，在订阅的部分显示的字体是这样的(未使用全屏放大)

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/91258620/f4c7f4ba-2a28-46fb-ab40-23699ceb365a)

全屏时，编辑文件的小界面是这样的

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/91258620/124dd02e-c4b2-4aff-93da-c05a2c1192ce)

### Platform

Linux

### System Version

Kernel: 6.7.4-zen1-1-zen    Release: Arch Linux x86_64

### Software Version

1.5.1

**Comment by MystiPanda** [comment]
我也是KDE用户，说实话我觉得这是KDE的系统缩放实现的锅，跟软件没有关系

**Comment by s-chance** [comment]
> 我也是KDE用户，说实话我觉得这是KDE的系统缩放实现的锅，跟软件没有关系

我也在 Hyprland 中测试过，一样有这个问题。我已经归结为硬件先天问题了。
