### ISSUE TITLE
Alpha 内核升级 [BUG]

### ISSUE THREAD

**Issue by AsenHu** [clash-verge-rev/clash-verge-rev#392]
### Describe the bug

升级内核因为权限问题用不了。

### To Reproduce

我使用 apt install ./clashverge.deb 的方式安装的软件包。
在设置页点击升级内核时，程序报错 没有权限创建 /usr/bin/meta-update 目录
如果手动创建好这个目录，并配置好目录的权限后再运行
程序会报错 目录已存在

### Platform

Linux

### System Version

Debian 11 sid gnome 46 wayland

### Software Version

1.5.1

**Comment by wonfen** [comment]
又是wayland...

**Comment by AsenHu** [comment]
> 又是wayland...

这个问题和 wayland 无关吧
只是单纯的操作没有权限的目录 导致的问题吧

**Comment by MystiPanda** [comment]
点击内核授权可以解决问题吗

**Comment by AsenHu** [comment]
> 点击内核授权可以解决问题吗

不能，授权后升级，报错依旧是无权选创建目录
