### ISSUE TITLE
[Feature] 设定延迟测试超时时间

### ISSUE THREAD

**Issue by KinComet** [clash-verge-rev/clash-verge-rev#393]
### Is your feature request related to a problem? Please describe.

在节点数量多时，如果大量节点离线，会大幅增加测速耗时。一般节点延迟不可能超过2000ms，而目前的超时等待时间似乎过于保守了，且不支持调整超时等待时间。

### Describe the solution you'd like

在杂项设置中添加 默认超时等待

### Describe alternatives you've considered

代理组下也可添加，在每个代理组测试链接不同的情况下(例如连接不同地区的服务器或有安全措施的服务器)，延迟(超时延迟)也可能会有不同。

**Comment by wonfen** [comment]
考虑把延迟测试的逻辑修改修改。
