### ISSUE TITLE
[BUG]无法找到任何节点

### ISSUE THREAD

**Issue by Jerry-hyl** [clash-verge-rev/clash-verge-rev#396]
### Describe the bug

导入yaml文件后无法看到任何节点

### To Reproduce

在按照官网方式安装后出现该问题

### Platform

Windows

### System Version

win10

### Software Version

1.5.1

### Log

![屏幕截图 2024-02-18 110021](https://github.com/clash-verge-rev/clash-verge-rev/assets/86762065/515af476-9bae-408d-ad4a-0e52d62fbb9d)

### Additional Information

在代理界面也找不到任何添加的节点

**Comment by nQrChao** [comment]
同问，一样的情况

**Comment by MystiPanda** [comment]
麻烦加群把订阅发我一下

**Comment by wonfen** [comment]
请检查配置文件是否正确，是否用了订阅转换。切换其他机场尝试。

**Comment by wonfen** [comment]
无进一步反馈，关闭。
