### ISSUE TITLE
[Feature] 是否考虑禁用自动更新的编译模式，以迎合某些linux发行版(弱弱的问问

### ISSUE THREAD

**Issue by Kiri2002** [clash-verge-rev/clash-verge-rev#398]
### Is your feature request related to a problem? Please describe.

在Archlinux等linux发行版中，一般是用包管理器来升级包。
由于依赖可能变动，所以单独升级某包会有风险（炸依赖）。
因此在Archlinuxcn仓库中，clash-verge(-rev)在编译时，打了[补丁](https://github.com/archlinuxcn/repo/blob/0d324148d68e3443c3fcc5665b000a2e4143724d/archlinuxcn/clash-verge/001-disable-updater.patch)以禁用自动更新。原理是把src-tauri/src/main.rs中的以下三行删除掉：
```
        tauri::RunEvent::Updater(tauri::UpdaterEvent::Downloaded) => {
            resolve::resolve_reset();
            api::process::kill_children();
        }
```
因为这个补丁是diff生成的，所以一但main.rs有改动，这个补丁要重生成一次。
于是在这里厚着脸皮问问，有没有一种可能，可以考虑有禁用自动更新的编译模式。
以方便偷懒（

### Describe the solution you'd like

增加禁用自动更新的编译配置。
使编译后自动更新功能不可用。

### Describe alternatives you've considered

如果不好实现的话，那俺还是老实打patch(

**Comment by MystiPanda** [comment]
非appimage包都是无法进行应用内更新的，没有必要手动去禁用，你删除的那三行代码是在更新前关闭子进程的，跟禁用跟新没有任何关系。

**Comment by Kiri2002** [comment]
嗷，感谢大佬！！！
