### ISSUE TITLE
[BUG]undefined symbol: fribidi_get_par_embedding_levels_ex

### ISSUE THREAD

**Issue by ArKee** [clash-verge-rev/clash-verge-rev#399]
### Describe the bug

当前使用Ubuntu1804版本OS，并通过clash-verge_1.5.1_amd64.AppImage启动应用。在更新完libc（2.28）之后，出现一下错误：
clash-verge: symbol lookup error: /tmp/.mount_clash-UgrTxL/usr/lib/libpango-1.0.so.0: undefined symbol: fribidi_get_par_embedding_levels_ex

### To Reproduce

1、启动应用
./clash-verge_1.5.1_amd64.AppImage

2、出现报错
clash-verge: symbol lookup error: /tmp/.mount_clash-UgrTxL/usr/lib/libpango-1.0.so.0: undefined symbol: fribidi_get_par_embedding_levels_ex

### Platform

Linux

### System Version

Ubuntu 18.04

### Software Version

1.5.1

### Log

clash-verge: symbol lookup error: /tmp/.mount_clash-UgrTxL/usr/lib/libpango-1.0.so.0: undefined symbol: fribidi_get_par_embedding_levels_ex

**Comment by MystiPanda** [comment]
这些还是系统依赖导致的问题，要么自己编译，要么升级系统。
