### ISSUE TITLE
[BUG]老版卸载后不能联网

### ISSUE THREAD

**Issue by shiguangliuguo** [clash-verge-rev/clash-verge-rev#400]
### Describe the bug

老版任务管理器直接卸载，然后不能联网了，怎么办？

### To Reproduce

卸载老版

### Platform

Windows

### System Version

windows

### Software Version

window10

**Comment by lmmqxyx404** [comment]
重置下系统网络设置。 可能是网络代理没有关闭。这不该是BUG

**Comment by wonfen** [comment]
看FAQ手动卸载服务。关闭系统代理。
