### ISSUE TITLE
[BUG]【Linux】无法启动TUN模式

### ISSUE THREAD

**Issue by JIEDI84777** [clash-verge-rev/clash-verge-rev#402]
### Describe the bug

在Linux Mint 21.3（对应Ubuntu 22.04 LTS Jammy Jellyfish） KDE桌面环境下无法启动TUN模式
Clash Verge为deb版本，非Appimage

====版本信息====
Verge版本: v1.5.1
Clash内核版本: v1.18.1 Meta
系统版本: Linux Mint 21.3 （对应Ubuntu 22.04 LTS）
桌面环境: KDE Plasma (kde-standard) 
KDE Plasma版本: 5.24.7

### To Reproduce

1.在Linux Mint上安装Clash Verge
2.在应用程序启动器（开始菜单）中启动Clash Verge
3.开启TUN模式

### Platform

Linux

### System Version

Linux Mint 21.3

### Software Version

v1.5.1

### Log

02-19 00:30:17 [INFO]
Start initial configuration in progress

02-19 00:30:17 [INFO]
Geodata Loader mode: memconservative

02-19 00:30:17 [INFO]
Geosite Matcher implementation: succinct

02-19 00:30:17 [INFO]
Initial configuration complete, total time: 0ms

02-19 00:30:17 [INFO]
Sniffer is closed

02-19 00:30:17【WARNING】
[TUN] default interface changed by monitor, => wlp1s0

02-19 00:30:17【ERROR】
Start TUN listening error: configure tun interface: operation not permitted

02-19 00:30:17 [INFO]
Start initial Compatible provider default

**Comment by wonfen** [comment]
内核那里点授权了么？

**Comment by wonfen** [comment]
无进一步反馈，关闭。
