### ISSUE TITLE
[BUG]【Linux】在KDE桌面环境中程序内无法启动系统代理

### ISSUE THREAD

**Issue by JIEDI84777** [clash-verge-rev/clash-verge-rev#403]
### Describe the bug

无论使用root权限运行还是普通用户权限运行，在KDE Plasma桌面环境中无法启动系统代理（在程序内）
若要启动系统代理，必须要在设置中手动设置系统代理
经测试，GNOME桌面环境下没有这个问题

====版本信息====
Verge版本: v1.5.1
Clash内核版本: v1.18.1 Meta
系统版本: Linux Mint 21.3 （对应Ubuntu 22.04 LTS）
桌面环境: KDE Plasma (kde-standard)
KDE Plasma版本: 5.24.7

### To Reproduce

1.安装deb包版本的Clash Verge
2.正常从应用程序启动器中启动Clash Verge
3.开启系统代理

### Platform

Linux

### System Version

Linux Mint 21.3

### Software Version

v1.5.1

### Log

none

**Comment by roshou** [comment]
我的archlinux kde同样不能设置系统代理
kde 的系统代理配置文件为:" ~/.config/kioslaverc"
```
cat ~/.config/kioslaverc
ProxyUrlDisplayFlags=0

[Proxy Settings]
NoProxyFor=
Proxy Config Script=
ProxyType=0
ReversedException=false
ftpProxy=http://127.0.0.1 7897
httpProxy=http://127.0.0.1 7897
httpsProxy=http://127.0.0.1 7897
socksProxy=http://127.0.0.1 7897

```

设置系统代理：
```
sed -i 's/ProxyType=0/ProxyType=1/' ~/.config/kioslaverc


```
取消系统代理
```
sed -i 's/ProxyType=1/ProxyType=0/' ~/.config/kioslaverc

---
希望作者可以将kde的系统代理优化下。

```

**Comment by gvenusleo** [comment]
KDE Neon 也有同样的问题，期待优化！
