### ISSUE TITLE
[BUG]启用局域网链接另外一台电脑连接代理失败

### ISSUE THREAD

**Issue by xengine-qyt** [clash-verge-rev/clash-verge-rev#404]
### Describe the bug

WINDOWS启用局域网链接服务代理
UBUNTU22 使用proxychains 配置代理链接到windows的clash程序上面

windows ip 192.168.31.128
ubuntu ip   192.168.31.109
然后报错日志.
dial DIRECT (match IPCIDR/192.168.0.0/16) 192.168.31.128:61266 --> 192.168.31.128:7890 error: reject loopback connection to: 192.168.31.128:7890

下面是Ubuntu的日志
ubuntu@ubuntu-virtual-machine:~/ff$ proxychains curl www.google.com
ProxyChains-3.1 (http://proxychains.sf.net)
|DNS-request| www.google.com 
|S-chain|-<>-192.168.31.128:7890-<>-192.168.31.128:7890-<>-192.168.31.128:7890-<><>-4.2.2.2:53-<--timeout
|S-chain|-<>-192.168.31.128:7890-<>-192.168.31.128:7890-<>-192.168.31.128:7890-<><>-4.2.2.2:53-<--timeout
|S-chain|-<>-192.168.31.128:7890-<>-192.168.31.128:7890-<>-192.168.31.128:7890-<><>-4.2.2.2:53-<--timeout
|DNS-response|: www.google.com does not exist
curl: (6) Could not resolve host: www.google.com

### To Reproduce

如上

### Platform

Windows

### System Version

win11 23h2

### Software Version

1.5.1

**Comment by wonfen** [comment]
勾选局域网访问了没？

**Comment by xengine-qyt** [comment]
> 勾选局域网访问了没？

勾选了
