### ISSUE TITLE
[BUG]关于同时使用其他内核时也会获取到访问记录

### ISSUE THREAD

**Issue by Amnesiash** [clash-verge-rev/clash-verge-rev#405]
### Describe the bug

同时使用 cfw 时 cv 的 webui 读取到cfw 的内核与日志<img width="1308" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/44333360/c935e6d2-1b1b-4968-8db7-66a15e2df496">

### To Reproduce

这是设计如此还是未考虑相关方面，是否需要进行阻断

### Platform

MacOS

### System Version

sonoma 14.3.1

### Software Version

1.5.1

**Comment by MystiPanda** [comment]
外部控制的端口改为其他端口即可，默认端口9097跟cfw是不同的
