### ISSUE TITLE
[BUG] TUN 模式正常开启, 但是右下角显示断网小地球, 而且微软的服务都用不了

### ISSUE THREAD

**Issue by MJRT** [clash-verge-rev/clash-verge-rev#406]
### Describe the bug

TUN开启后右下角断网, onedrive 无法自动同步, 微软商店也连接不上且登录失败

### To Reproduce

1. 打开clash verge
2. 打开服务模式
3. 打开TUN

### Platform

Windows

### System Version

win11

### Software Version

1.5.1

### Additional Information
![PixPin_2024-02-19_13-48-23](https://github.com/clash-verge-rev/clash-verge-rev/assets/17826582/8ef5d471-6133-4afd-8b42-3d3df112a76c)

**Comment by wonfen** [comment]
检查你自己的网络设置吧

**Comment by MJRT** [comment]
> 检查你自己的网络设置吧

我没有手动修改过网络, 要检查哪些网络设置呢?

**Comment by StarsEnd33A2D17** [comment]
我这边是在Dev频道的Windows 11 Insider Preview 10.0.26058.1100 (ge_release)后出现这种情况，多台机子可以复现，不确定这个更新对哪里做了修改，没找到变更的设置（与非预览的对比）

**Comment by StarsEnd33A2D17** [comment]
> 我这边是在Dev频道的Windows 11 Insider Preview 10.0.26058.1100 (ge_release)后出现这种情况，多台机子可以复现，不确定这个更新对哪里做了修改，没找到变更的设置（与非预览的对比）

补充：根据微软[build 26058](https://blogs.windows.com/windows-insider/2024/02/14/announcing-windows-11-insider-preview-build-26058-canary-and-dev-channels/)的Known issues说明，已经有了：
[NEW] Some Insiders may experience an issue where the network icon in the system tray shows they do not have an internet connection when connected to some VPNs even though the internet connection is working. Some apps might also think there isn’t an internet connection when there really is.

**Comment by LiXiaYu** [comment]
同样遇到了这个问题，也是Insider Preview，关闭tun或者服务模式后断网小地球回消失，但微软的服务还是会报错0x800704cf

**Comment by sf467** [comment]
> > 我这边是在Dev频道的Windows 11 Insider Preview 10.0.26058.1100 (ge_release)后出现这种情况，多台机子可以复现，不确定这个更新对哪里做了修改，没找到变更的设置（与非预览的对比）
> 
> 补充：根据微软[build 26058](https://blogs.windows.com/windows-insider/2024/02/14/announcing-windows-11-insider-preview-build-26058-canary-and-dev-channels/)的Known issues说明，已经有了： [NEW] Some Insiders may experience an issue where the network icon in the system tray shows they do not have an internet connection when connected to some VPNs even though the internet connection is working. Some apps might also think there isn’t an internet connection when there really is.

还真是微软的问题，除此之外，我这里还出现了另一种情况，就是刚刚开启tun的时候，tun网卡显示没有internet连接，但是托盘图标显示正常的wifi图标，一些依赖网络连通性的系统服务也能正常运行

**Comment by mgqlfc** [comment]
我也是insider26058，关闭clash设置里的ipv6就能正常显示网络连接了，先这么凑活着用吧

**Comment by MJRT** [comment]
今天莫名奇妙就好了, 想了一下可能下面的一些操作导致的:
1. 组策略关闭NCSI -> 重启 -> 打开NCSI
2. 清理系统垃圾, 用了 dism++, win11的存储感知, 火绒, 手动清理了一些缓存和垃圾文件
3. 删除了一些不用的app, 其中包括很多微软的app, 比如Microsoft365 和 Mail 等等

因为要用wsl2, 所有也没关闭ipv6, 微软商店, onedrive 等也都能正常登录使用了, 右下角小地图也没了, Meta网卡也显示Connected.
供大家参考

**Comment by StarsEnd33A2D17** [comment]
> > > 我这边是在Dev频道的Windows 11 Insider Preview 10.0.26058.1100 (ge_release)后出现这种情况，多台机子可以复现，不确定这个更新对哪里做了修改，没找到变更的设置（与非预览的对比）
> > 
> > 
> > 补充：根据微软[build 26058](https://blogs.windows.com/windows-insider/2024/02/14/announcing-windows-11-insider-preview-build-26058-canary-and-dev-channels/)的Known issues说明，已经有了： [NEW] Some Insiders may experience an issue where the network icon in the system tray shows they do not have an internet connection when connected to some VPNs even though the internet connection is working. Some apps might also think there isn’t an internet connection when there really is.
> 
> 还真是微软的问题，除此之外，我这里还出现了另一种情况，就是刚刚开启tun的时候，tun网卡显示没有internet连接，但是托盘图标显示正常的wifi图标，一些依赖网络连通性的系统服务也能正常运行

再次补充：根据微软[build-26058-canary-and-dev-channels](https://blogs.windows.com/windows-insider/2024/02/14/announcing-windows-11-insider-preview-build-26058-canary-and-dev-channels/)的已知问题说明，如果你是build 26058，这不是你的设置问题；进一步参考，[build-26063-canary-channel](https://blogs.windows.com/windows-insider/2024/02/22/announcing-windows-11-insider-preview-build-26063-canary-channel/)，已经出现在了对已知问题的修复中，但是只提供canary-channel，还没有给dev-channel推送。但是如果你的build很低，不在windows-11-insider-preview，很可能是你的设置问题，请参考其他人提供的参考内容。
顺便一提，问题来源大概就是错误的检测导致所谓的“断网小地球”，而所有使用了WindowsAPI来获取设备是否联网的软件都会认为已经断开连接，而不使用该方案的软件则不受影响。基于windows blogs的猜测。
再次提醒，如果你的版本与这次的build-26058无关，那么很可能是你的问题，请参考其他人提供的其他参考内容。

**Comment by sf467** [comment]
> > > > 我这边是在Dev频道的Windows 11 Insider Preview 10.0.26058.1100 (ge_release)后出现这种情况，多台机子可以复现，不确定这个更新对哪里做了修改，没找到变更的设置（与非预览的对比）
> > > 
> > > 
> > > 补充：根据微软[build 26058](https://blogs.windows.com/windows-insider/2024/02/14/announcing-windows-11-insider-preview-build-26058-canary-and-dev-channels/)的Known issues说明，已经有了： [NEW] Some Insiders may experience an issue where the network icon in the system tray shows they do not have an internet connection when connected to some VPNs even though the internet connection is working. Some apps might also think there isn’t an internet connection when there really is.
> > 
> > 
> > 还真是微软的问题，除此之外，我这里还出现了另一种情况，就是刚刚开启tun的时候，tun网卡显示没有internet连接，但是托盘图标显示正常的wifi图标，一些依赖网络连通性的系统服务也能正常运行
> 
> 再次补充：根据微软[build-26058-canary-and-dev-channels](https://blogs.windows.com/windows-insider/2024/02/14/announcing-windows-11-insider-preview-build-26058-canary-and-dev-channels/)的已知问题说明，如果你是build 26058，这不是你的设置问题；进一步参考，[build-26063-canary-channel](https://blogs.windows.com/windows-insider/2024/02/22/announcing-windows-11-insider-preview-build-26063-canary-channel/)，已经出现在了对已知问题的修复中，但是只提供canary-channel，还没有给dev-channel推送。但是如果你的build很低，不在windows-11-insider-preview，很可能是你的设置问题，请参考其他人提供的参考内容。 顺便一提，问题来源大概就是错误的检测导致所谓的“断网小地球”，而所有使用了WindowsAPI来获取设备是否联网的软件都会认为已经断开连接，而不使用该方案的软件则不受影响。基于windows blogs的猜测。 如果你遇到微软的服务报错0x800704cf，可以尝试使用设置中的UWP工具（lookback tool）、重置设置、重置host等操作，详细请自行搜索。 再次提醒，如果你的版本与这次的build-26058无关，那么很可能是你的问题，请参考其他人提供的其他参考内容。

欸这不巧了吗，我正好就是dev频道 build 26058。
已经等了好几个星期了都没推送新版本
~~于是这几天我安装了archlinux~~

**Comment by charliez0** [comment]
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet\EnableActiveProbing
一气之下直接把这个检测给砍了，记得重启

**Comment by LiXiaYu** [comment]
canary的小地球恢复正常了，但是微软bing的新闻网页打开没有图片，可能这是我自己的问题？还是后遗症。。。
