### ISSUE TITLE
[BUG]mac上无法开启tun，局域网节点无法连接

### ISSUE THREAD

**Issue by KelvinF97** [clash-verge-rev/clash-verge-rev#407]
### Describe the bug

clash verge客户端开启tun，无法连接局域网com节点。关闭tun可以连接局域网com节点。
```bash
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: silent
external-controller: '0.0.0.0:9090'
secret: ''
proxies:
  - 
    name: 'com'
    server: 10.211.55.13
    port: 5555
    uuid: 7123f321-d666-4611-99df-2024f016a12c
    alterId: 0
    cipher: auto
    udp: true
  -
    name: 'us_fk'
    ...
```
其他节点都是公网节点，开启tun和不开启tun都能正常访问。

com节点开启tun之后测速为Error，其他节点正常
<img width="791" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37264681/26b67b88-3efa-44c7-8013-abeb075ffd35">
com节点不开启tun之后测速为306，其他节点正常
<img width="783" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37264681/6c9aedd9-bb71-46d4-84fa-f7fc4fe779c8">

目前搭建方式为：

clash verge在mac系统上，mac为m1pro
然后在parallels desktop上安装了windows11建立了局域网，使用v2ray做转发。Windows11与远程其他机器搭建局域网，局域网内有v2ray服务器。

所以就是将parallels desktop的windows作为跳板机连接局域网v2ray服务器。

目前采用clash for windows开启tun是能成功，但是用clash verge和clashx pro开启tun就会失败。

请神佬们，帮忙看看，谢谢！

### Platform

MacOS

### System Version

14.2.1 (23C71)

### Software Version

1.5.1

**Comment by wonfen** [comment]
内核那里点授权了么？日志？

**Comment by KelvinF97** [comment]
内核授权了啊，上面的图就是对比，公网节点一点问题都没有，就是局域网节点测速不行，也无法访问

**Comment by KelvinF97** [comment]
> 内核那里点授权了么？日志？

内核授权了啊，上面的图就是对比，公网节点一点问题都没有，就是局域网节点测速不行，也无法访问

**Comment by wonfen** [comment]
打开tun模式后局域网不能访问需要检查下你局域网的设备在tun模式的路由下是否可达。

**Comment by wonfen** [comment]
无进一步反馈，关闭。
