### ISSUE TITLE
[BUG]无法使用tun模式 以及无法代理google等小部分网站

### ISSUE THREAD

**Issue by Aftertea123** [clash-verge-rev/clash-verge-rev#408]
### Describe the bug

启动tun以及服务模式 之后无法使用google以及steam 但是其它绝大部分网站都正常 (有可能是内核的问题 我换成老版本并使用clash内核问题消失 但是换成meta内核却出现相同的问题）

### To Reproduce

打开clash verge
打开服务模式
打开TUN

### Platform

Windows

### System Version

windows10

### Software Version

1.5.1

### Additional Information

![QQ截图20240219202112](https://github.com/clash-verge-rev/clash-verge-rev/assets/160494176/265c09dd-e59c-42ab-b222-f8cfb09c18c8)

**Comment by wonfen** [comment]
是否修改过Host？

**Comment by Aftertea123** [comment]
> 是否修改过Host？

我应该没有修改过host 然后我现在还重置host 顺带发现了一个奇异的问题 我现在能通过百度搜索谷歌引擎 然后正常用谷歌搜索 但是直接在地址栏搜索就显示了上图的情况 以及discord也出现了无法连接的情况

**Comment by MUTED64** [comment]
same issue here

**Comment by wonfen** [comment]
换个节点，换个机场试试看；感觉是你的机场或者配置文件的问题。

**Comment by wonfen** [comment]
无进一步反馈，关闭。
