### ISSUE TITLE
[BUG]内核重启后，节点选择恢复初始状态

### ISSUE THREAD

**Issue by nightrain01** [clash-verge-rev/clash-verge-rev#409]
### Describe the bug

1.5.1，重启之后在“代理”一栏里选择的的节点就会恢复到初始的默认状态。1.4.11没有这个问题。

### To Reproduce

打开clash verge，在“代理”一栏中选择非默认节点
重启内核或者应用
“代理”一栏中的选择恢复初始状态

### Platform

Windows

### System Version

win11 23h2

### Software Version

1.5.1

### Log

[2024-02-20-1021.log](https://github.com/clash-verge-rev/clash-verge-rev/files/14338646/2024-02-20-1021.log)
[2024-02-20-1022.log](https://github.com/clash-verge-rev/clash-verge-rev/files/14338647/2024-02-20-1022.log)

**Comment by MUTED64** [comment]
same issue here

**Comment by MystiPanda** [comment]
无法复现

**Comment by Cyenoch** [comment]
确实存在

**Comment by nightrain01** [comment]
找到问题了：
```ymal
profile:
  store-selected: false
```
store-selected要设置为true，我机场拉下来默认是false
之前版本的clash verge在最终提交给内核的配置里，profile字段大概是直接丢弃了
1.5.0之后把profile字段也加上了，导致了这个问题

**Comment by Cyenoch** [comment]
也许可以在新增订阅的时候添加一个选项
决定是否需要 遵循远程配置文件的 profile.store-selected 属性
