### ISSUE TITLE
[BUG] 直接重启后，Verge 无法正确关闭系统代理

### ISSUE THREAD

**Issue by Bush2021** [clash-verge-rev/clash-verge-rev#410]
### Describe the bug

重启系统前未关闭 Verge 的系统代理，导致重启后 Verge 无法控制系统代理状态（始终为开启状态），需手动进入系统设置关闭代理。

### To Reproduce

启动 Verge 并启用系统代理
直接重启
启动 Verge 并关闭系统代理
退出 Verge
打开系统设置，发现系统代理仍然处于开启状态
无法正常上网
反复启动 Verge 并尝试关闭系统代理仍然无效

### Platform

Windows

### System Version

Windows 11 23H2

### Software Version

1.5.1

### Log

![2024-02-19_223613](https://github.com/clash-verge-rev/clash-verge-rev/assets/79072750/9b0f9c61-1c25-457a-8f85-fbefd688a3bc)
![2024-02-19_223638](https://github.com/clash-verge-rev/clash-verge-rev/assets/79072750/a9e9a81c-3f73-453d-83a9-4a8322a19b07)

**Comment by wonfen** [comment]
在设置里手动开关几次可以关闭吗？

**Comment by Bush2021** [comment]
> 在设置里手动开关几次可以关闭吗？

在 Verge 设置里手动开关吗？不可以的。
