### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by drydddd** [clash-verge-rev/clash-verge-rev#412]
### Describe the bug

连接选项卡无任何数据

### To Reproduce

连接选项卡无任何数据，日志页面显示正常

### Platform

Windows

### System Version

23H2

### Software Version

1.5.1

### Log

![Snipaste_2024-02-20_13-41-35](https://github.com/clash-verge-rev/clash-verge-rev/assets/56291669/6e831007-5c3f-40f3-912c-d9900587b144)
![Snipaste_2024-02-20_13-42-55](https://github.com/clash-verge-rev/clash-verge-rev/assets/56291669/d4d5e62e-d3ef-4cee-8e56-f02ec06ec345)

**Comment by wonfen** [comment]
无进一步反馈，关闭。
