### ISSUE TITLE
[BUG]设置界面tun选项中的子选项显示错误

### ISSUE THREAD

**Issue by ForestL18** [clash-verge-rev/clash-verge-rev#417]
### Describe the bug

在1.5.2版本中，un选项关闭状态下，设置tun选项中的子选项（如取消勾选strict route）并保存后。开启tun或者重启clash verge，之前在tun中做的设置会显示错误，设置未勾选的选项会显示已勾选。
但是在runtime confing中该选项确实显示的是false，故而应该是显示错误。

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/45709305/d720e085-9dd8-430d-9b50-99e7193ea7a3)

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/45709305/fc6a1bd5-2d49-40ce-a453-684834bbc142)

### To Reproduce

同上

### Platform

Windows

### System Version

Windows 10

### Software Version

1.5.2

**Comment by MystiPanda** [comment]
测试了一下，只有strict-route有问题，初步排查好像是内核的问题，内核api返回的内容中没有strict-route字段，所以导致重启后显示的是默认值。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/152463842/6cc29821-8b4d-4c6a-a5af-fcae9f43a633)

**Comment by MystiPanda** [comment]
已修复，请下载最新[alpha](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha)版本测试
