### ISSUE TITLE
为何实际代理已经走了7897-7899端口，但是yaml里还显示的7890端口

### ISSUE THREAD

**Issue by lixiangtiandashen** [clash-verge-rev/clash-verge-rev#418]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/39831228/44c6104f-e4b7-4772-a12b-40c75f6ee05d)
这个地方显示的7890端口。
我去.local里找了下，下面那些yaml里都是7897没错。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/39831228/11358924-7ed5-4cdd-9674-3caa250ecdbc)
但是profile子文件夹里的这个yaml却显示的7890，跟软件图形界面显示的一样。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/39831228/5ac98ca3-ac83-44ad-bd6c-e9d1869f2a3b)

### To Reproduce

如上图

### Platform

Linux

### System Version

ubuntu20.04

### Software Version

1.5.2

**Comment by MystiPanda** [comment]
这里的yaml是你机场拉下来的原始配置，verge是不会修改这个文件的，最终给内核的也不是这个文件
