### ISSUE TITLE
[Feature]希望能增加CFW有的配置文件预处理parsers功能

### ISSUE THREAD

**Issue by ikun2020** [clash-verge-rev/clash-verge-rev#419]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/22858309/836669f0-a9a5-48d3-953a-1e4c6e87dc9f)

### Describe the solution you'd like

预设的配置在更新订阅的时候不会被覆盖掉

### Describe alternatives you've considered

/

**Comment by MystiPanda** [comment]
看文档
