### ISSUE TITLE
[BUG]最新alpha版本启动项重复问题

### ISSUE THREAD

**Issue by ForestL18** [clash-verge-rev/clash-verge-rev#424]
### Describe the bug

安装最新alpha版本后，在启用开启自启选项后，在任务管理器可以看到有两个clash verge启动项。
排查一下发现在`计算机\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`和`计算机\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run`里都存在clash verge项，所以导致出现两个相同启动项。

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/45709305/6d88ca37-4242-466e-b1bc-e38cd2a668aa)

刚开始怀疑是覆盖安装问题，在完全卸载后重新安装后仍出现上述现象。

### To Reproduce

同上

### Platform

Windows

### System Version

Windows 10

### Software Version

1.5.2

**Comment by MystiPanda** [comment]
好像是应用内更新的时候安装器有提权的操作，安装完成后直接启动应用就相当于管理员权限启动了。
