### ISSUE TITLE
[BUG]通过一层公司代理之后，有些服务器连接不上

### ISSUE THREAD

**Issue by gelandesprung** [clash-verge-rev/clash-verge-rev#430]
### Describe the bug

系统是linux，网络环境是公司网络，需要代理访问互联网，我自备一个路由，装了一openclash代理公司的代理服务器。现在使用的clash verge版本是1.4.2，有一些服务器能连接上，有一些不能。升级到1.5.3之后那些能连接上的服务器也连接不上了。

### To Reproduce

这个环境我无法模拟

### Platform

Linux

### System Version

ubuntu 23

### Software Version

1.5.3

**Comment by wonfen** [comment]
无从排查。1.5.3升级了最新版的内核。
既然都用openclash了，为啥还要用verge？

**Comment by wonfen** [comment]
无进一步反馈，关闭。
