### ISSUE TITLE
[Feature]如何在Linux下命令行启动

### ISSUE THREAD

**Issue by leviome** [clash-verge-rev/clash-verge-rev#431]
### Is your feature request related to a problem? Please describe.

我目前用的Linux系统是没有界面，能否支持命令行启动

### Describe the solution you'd like

增加命令行启动

### Describe alternatives you've considered

增加命令行启动

**Comment by MystiPanda** [comment]
这是gui软件，命令行直接跑内核就行，不需要该软件
