### ISSUE TITLE
[BUG]流量图显失效

### ISSUE THREAD

**Issue by soratanmer** [clash-verge-rev/clash-verge-rev#432]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/23238799/bc0e49d1-0735-4afc-a818-ab58287f7464)

流量图显失效，内存会变化，但是流量一直是0。

### To Reproduce

设置-界面设置-打开流量图显和内存使用。

### Platform

Windows

### System Version

Windows 11 22631.3155

### Software Version

1.5.3

**Comment by MystiPanda** [comment]
tun设置打开重置一下设置

**Comment by soratanmer** [comment]
> tun设置打开重置一下设置

重置tun设置不行，但是重启电脑就好了，谢谢。
