### ISSUE TITLE
[BUG]更新后出现两个clash verge

### ISSUE THREAD

**Issue by ibin7777** [clash-verge-rev/clash-verge-rev#433]
### Describe the bug

<img width="752" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/64576479/abf0f7eb-fe4d-4761-9822-d30be5955c0f">
如图，老的在appdata里，新的在program files里
请问手动卸载旧版本会不会对新版有影响？

### To Reproduce

。

### Platform

Windows

### System Version

11

### Software Version

1.4.5 to 1.5.3

**Comment by MystiPanda** [comment]
建议都卸载后手动下载安装，这是1.4.11版本的break change导致的，可以看看1.4.11版本的更新日志

**Comment by ibin7777** [comment]
> 建议都卸载后手动下载安装，这是1.4.11版本的break change导致的，可以看看1.4.11版本的更新日志

明白，感谢答复
