### ISSUE TITLE
[Feature]自定义图标功能

### ISSUE THREAD

**Issue by ibin7777** [clash-verge-rev/clash-verge-rev#434]
### Is your feature request related to a problem? Please describe.

请考虑为verge添加更换自定义图标的选项，对于经常需要公开展示电脑桌面的人来说是刚需

### Describe the solution you'd like

基础：更换单一图标
进阶：为不同模式分别设置单独图标（全局/非全局，tun开/关等）

### Describe alternatives you've considered

service mode也挺好，但是需要经常性调整设置就有些麻烦

**Comment by MystiPanda** [comment]
这个理由不错，有时间想办法弄一下
