### ISSUE TITLE
[BUG]通过Merge配置rule-providers启动后内存暴增

### ISSUE THREAD

**Issue by lovelytan** [clash-verge-rev/clash-verge-rev#435]
### Describe the bug

通过Merge配置rule-providers启动后内存暴增

<img width="808" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/17985841/7fe7cd69-e3b0-412a-9535-8393d4d5fdf8">

### To Reproduce

1. 通过script将rules清空，并启用
2. 通过merge重写rule-providers
3. 启用merge配置，ruleset目录下载成功，软件左下角内存占用显示从25MB暴增到170MB
4. 一段时间后稳定在40~50MB

### Platform

MacOS

### System Version

Mac OS Monterey 12.6.5

### Software Version

1.5.3

**Comment by wonfen** [comment]
左下角显示的是内核的内存占用；建议到meta那边提。

**Comment by MystiPanda** [comment]
我觉得是正常的，添加那么多规则，内核不得解析吗，解析的时候占这点内存我觉得是正常行为
