### ISSUE TITLE
[Feature]可否让软件也带一份规则

### ISSUE THREAD

**Issue by Http-200** [clash-verge-rev/clash-verge-rev#436]
### Is your feature request related to a problem? Please describe.

在使用软件的过程中，我发现如果想要新增规则，只能通过修改订阅里的规则，使用起来不是很方便。

### Describe the solution you'd like

我希望软件也可以带一份规则，软件带的这份规则可以选择**覆盖**或**不覆盖**原订阅中的规则

### Describe alternatives you've considered

就像是v2rayN中的**预定义规则**

**Comment by parrotevan** [comment]
在订阅中新建 Local,Merge,Script 类型的订阅可以实现。

**Comment by Http-200** [comment]
> 在订阅中新建 Local,Merge,Script 类型的订阅可以实现。

谢谢！！！
