### ISSUE TITLE
[Feature]新增Remote订阅时，新增一个忽略证书错误的选项

### ISSUE THREAD

**Issue by V4n1sh** [clash-verge-rev/clash-verge-rev#438]
### Is your feature request related to a problem? Please describe.

经常用到自己搭建的subconverter，由于没有域名，只能使用自签名ssl证书，但是在 clash verge 中新增remote订阅时会报错：unknown certificate issuer 等ssl证书相关错误

### Describe the solution you'd like

新增remote类型的订阅时，新增一个勾选框，“跳过SSL证书校验”，默认为关，有需要时自行勾选

### Describe alternatives you've considered

或者在设置中新增一个选项，考虑到安全性，这个选项可以隐藏的深一点，放在二级甚至三级设置菜单中

**Comment by wonfen** [comment]
已经添加实现： https://github.com/clash-verge-rev/clash-verge-rev/commit/e29ce93d325f7b4bcb42abd68af4d2a59d0708cf

**Comment by V4n1sh** [comment]
> 已经添加实现： [e29ce93](https://github.com/clash-verge-rev/clash-verge-rev/commit/e29ce93d325f7b4bcb42abd68af4d2a59d0708cf)

十分感谢！
