### ISSUE TITLE
[Feature]热键设置中新增【切换界面显示】选项

### ISSUE THREAD

**Issue by V4n1sh** [clash-verge-rev/clash-verge-rev#439]
### Is your feature request related to a problem? Please describe.

新增一个【切换界面显示】选项，按下热键后，如果主界面已打开，则关闭，如果主界面已关闭，则打开。类似【切换系统代理】，目前的【打开面板】只能实现打开，当按下热键打开后，需要手动关闭，程序一致性和操作性方面可以改善

![Snipaste_2024-02-23_10-04-00](https://github.com/clash-verge-rev/clash-verge-rev/assets/10967857/ec26c624-9eb3-4042-b670-fef8e5302b26)

### Describe the solution you'd like

新增一个【切换界面显示】选项，或者直接修改【打开面板】逻辑为此

### Describe alternatives you've considered

暂无

**Comment by MystiPanda** [comment]
下个版本改成“打开/关闭面板”
