### ISSUE TITLE
[Feature] 希望可以和 cfw 一样通过托盘右键菜单切换节点

### ISSUE THREAD

**Issue by Vixb1122** [clash-verge-rev/clash-verge-rev#440]
### Is your feature request related to a problem? Please describe.

目前切换节点步骤有些繁琐，右击托盘图标，点击打开面板，然后选择节点，最后关闭面板。
因为打开面板的响应过于缓慢，导致这个步骤更加繁琐。

### Describe the solution you'd like

和 cfw 一样，根据订阅的不同，在托盘右键菜单上更新对应的节点列表，方便切换

### Describe alternatives you've considered

没有

**Comment by wonfen** [comment]
有此计划，不过是在升级到Tauri v2以后再实施。
