### ISSUE TITLE
[BUG]开启系统代理后，无法通过任务栏和桌面快捷方式等正确打开应用

### ISSUE THREAD

**Issue by thouser8** [clash-verge-rev/clash-verge-rev#441]
### Describe the bug

在打开系统代理之后，点击状态栏的图标/桌面快捷方式不能正确打开应用主窗口，而是出现另一个新的进程并马上消失；
使用各种网站的代理“一键导入到clash”功能也会出现此问题

### To Reproduce

1.开启系统代理
2.双击桌面快捷方式或点击状态栏快捷方式
3.应用主界面没有被打开，而是出现另一个进程并马上消失

https://github.com/clash-verge-rev/clash-verge-rev/assets/83090571/8d9aa698-dd25-4a78-961b-5a59f2f3928d

### Platform

Windows

### System Version

Windows 11 23H2

### Software Version

1.5.3；1.5.2；1.5.1

**Comment by MystiPanda** [comment]
在系统代理bypass里面排除一下127.0.0.1

**Comment by thouser8** [comment]
> 在系统代理bypass里面排除一下127.0.0.1

<img width="413" alt="391ace5be4e186315d34f38cd5c92320" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/83090571/9cda92a0-2ca5-4674-9c2a-98663900501a">
请问是这样设置吗？但是没有效果
