### ISSUE TITLE
clash verge rev 里有类似 cfw-bypass 这样的功能吗？

### ISSUE THREAD

**Issue by Dichlorphos** [clash-verge-rev/clash-verge-rev#442]
我想在用 clash verge rev 时过滤一个本地域名，让它走直连，于是在 merge 中配置：
prepend-rules:
- 'DOMAIN,[jenkins.xxxx.com](http://jenkins.xxxx.com/),DIRECT'
- 'DOMAIN-KEYWORD,jenkins,DIRECT'
但这样是无效的，log 中会提示：
[TCP] dial DIRECT (match Domain/[jenkins.xxxx.com](http://jenkins.xxxx.com/)) 127.0.0.1:60766 --> [jenkins.xxxx.com:80](http://jenkins.xxxx.com/) error: dns resolve failed: couldn't find ip

以前在 clash for windows 中有一个 bypass domain/ipnet 设置可用
bypass:
- localhost
- 127.*
- 10.*
- 172.16.*

请问 clash verge rev 里有任何解决的办法吗

**Comment by lovelytan** [comment]
设置-系统代理-绕过

支持域名，IP，每条英文逗号分隔
