### ISSUE TITLE
[BUG]用一段时间之后就会卡住，无法通过代理进行连接

### ISSUE THREAD

**Issue by oodzchen** [clash-verge-rev/clash-verge-rev#445]
### Describe the bug

不知道是不是这个客户端的问题，我这里用一段时间就无法打开翻墙网页，测试梯子连接是正常的，测速正常，手动关闭全部连接，再刷新网页也还是无法走代理，墙内网站不受影响，可以直连。

### To Reproduce

1. 导入ss+obfs类型的节点
2. 选择并启用其中一个节点
3. 使用规则模式，不开启TUN和系统代理
4. 在浏览器使用SwitchOmega配置代理
5. 浏览器需要翻墙的网页一个小时或以上

预期：
正常打开网页

结果：
一段时间后境外网站无法建立连接，境内网站正常使用，节点测速正常，有时候需要等几分钟才能正常翻墙。重启客户端也能恢复翻墙。

### Platform

Linux

### System Version

OpenSUSE Tumbleweed

### Software Version

1.5.3

### Additional Information

我一般会在后台运行telegram，日志里面有大量telegram相关连接，不知道跟这个有没有关系

**Comment by wonfen** [comment]
无从排查，可能出现问题的地方多了；内核，协议，机场，节点，设备。
建议换一家机场试试。

**Comment by we6288815** [comment]
我也遇到过，长时间打开代理的情况下，偶现不能翻墙，重启应用后就可以了

**Comment by wonfen** [comment]
无近一步反馈，关闭。
