### ISSUE TITLE
[BUG]修改GUI日志显示级别，app_log_level: 不起作用

### ISSUE THREAD

**Issue by aylz10** [clash-verge-rev/clash-verge-rev#448]
### Describe the bug

编辑verge.yaml文件，修改 app_log_level: debug  无效, GUI日志不显示调试信息（已重启过APP）

### To Reproduce

编辑verge.yaml文件，修改 app_log_level: debug

### Platform

Windows

### System Version

win10 22H2 19045.4046

### Software Version

1.5.4

**Comment by wonfen** [comment]
请修改为 trace

**Comment by wonfen** [comment]
就是这样，没有在GUI的日志里输出app的日志。
