### ISSUE TITLE
[Feature]希望可以增加单击托盘切换模式的反馈功能

### ISSUE THREAD

**Issue by FaintGhost** [Clash-Verge-rev/clash-verge-rev#45]
**Is your feature request related to a problem? Please describe.**
目前使用单击图标开关TUN的功能，但是点击后没有任何反馈让用户知道是否成功切换。

**Describe the solution you'd like**
希望可以可以弹出提示，或者使图标变色来提示用户模式已经切换了。感谢开发者

**Comment by Pylogmon** [comment]
- #33

**Comment by FaintGhost** [comment]
> * [feat: Set different tray icon on tun mode #33](https://github.com/Clash-Verge-rev/clash-verge-rev/pull/33)

原来已经实现了，感谢！静待release！
