### ISSUE TITLE
希望能够加入pac模式

### ISSUE THREAD

**Issue by lxmwwl** [clash-verge-rev/clash-verge-rev#451]
### Is your feature request related to a problem? Please describe.

每次电脑自动启动应用的时候，有些需要翻墙验证的软件先于clash先启动了就陷入了要验证的不断循环中

### Describe the solution you'd like

希望能够加入pac模式，之前cfw中通过这个模式可以避免这个问题

### Describe alternatives you've considered

无

**Comment by wonfen** [comment]
pac模式到底是个什么原理？谁来和我说说。

**Comment by wonfen** [comment]
无近一步反馈，关闭。
