### ISSUE TITLE
[BUG] 树莓派4B 打开主程序无法显示

### ISSUE THREAD

**Issue by uniartisan** [clash-verge-rev/clash-verge-rev#452]
### Describe the bug

树莓派4B在最近的更新版本中，打开主程序，首页代理组显示为空白。

### To Reproduce

正常打开主程序，选择左侧代理即可复现。

### Platform

Linux

### System Version

Debian GNU/Linux 12 (bookworm)

### Software Version

1.5.4

### Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/31544054/36d62b26-35fc-491c-b8f4-bad6e6fa03d1)

### Additional Information

怀疑是GPU渲染等问题，可以考虑在aarch64版本的程序中全部走软件渲染。

相关issue： https://github.com/clash-verge-rev/clash-verge-rev/issues/237

**Comment by Cyenoch** [comment]
> If you are running it on Linux `export LIBGL_ALWAYS_SOFTWARE=1` may work.

_Originally posted by @sekwah41 in https://github.com/tauri-apps/tauri/issues/4438#issuecomment-1225968600_
