### ISSUE TITLE
[BUG]mac客户端经常卡住

### ISSUE THREAD

**Issue by zstoday2** [clash-verge-rev/clash-verge-rev#454]
### Describe the bug

客户端经常卡住，鼠标点击没有反应。

### To Reproduce

鼠标不能点击。

### Platform

MacOS

### System Version

macos 13.6.3

### Software Version

一直以来

### Log

没有

### Additional Information

没有

**Comment by wonfen** [comment]
无法复现。需要更多信息。

**Comment by wonfen** [comment]
无近一步反馈，关闭。
