### ISSUE TITLE
[BUG]Windows下触摸相关问题

### ISSUE THREAD

**Issue by CuteKims** [clash-verge-rev/clash-verge-rev#456]
### Describe the bug

1. 使用触摸/触笔拖动窗口标题栏时，窗口无法被拖动
2. 使用触摸/触笔在窗口上左/右滑动时，会触发Edge WebView2的前进/后退手势操作

### To Reproduce

见描述

### Platform

Windows

### System Version

Windows 11

### Software Version

1.5.4

### Additional Information

已知在`tauri.conf.json`的`"tauri"`->`"windows"`中添加
`"additionalBrowserArgs": "--enable-features=msWebView2EnableDraggableRegions"`，
并在可拖拽区域的CSS中添加`app-region: drag`
可以解决触摸无法拖动窗口的问题
照顾一下可怜的Surface用户吧球球了QwQ

**Comment by MystiPanda** [comment]
请下载最新alpha测试

**Comment by CuteKims** [comment]
安装Alpha版本之后Verge版本还显示1.5.4，Bug还在

**Comment by awarson2233** [comment]
> 请下载最新alpha测试

目前alpha版本可以触摸窗口内的控件，但无法拖动窗口。

而在稳定版中触摸操作仅能最大/小化

**Comment by MystiPanda** [comment]
麻烦下载alpha版本试试

**Comment by awarson2233** [comment]
> 麻烦下载alpha版本试试

更新1.5.7版本，窗口内控件无问题，左右拖动（包括标题栏），仍是触发webview的手势操作

**Comment by CuteKims** [comment]
问题依旧（悲
我就是这样写的 为什么就可以用呢（

> > 请下载最新alpha测试
> 
> 目前alpha版本可以触摸窗口内的控件，但无法拖动窗口。
> 
> 而在稳定版中触摸操作仅能最大/小化
> 
> 设备时matebook e go

我倒是从一开始就仅有触摸无法拖动窗口/无法调整窗口大小的问题，设备为Surface Pro 8 Windows 11

**Comment by MystiPanda** [comment]
麻烦下载alpha版本测试

**Comment by CuteKims** [comment]
现在是可以拖动了，但是出现了新的bug
但是好像 左侧整个菜单栏+顶部包含规则/全局/直连按钮的部分 都被标记了drag region导致无法点击
---
还有就是 现在用触摸点击窗口内部有时会导致窗口大小鬼畜，同时触摸拖拽窗口边缘无法调整窗口大小
不过这个属于window-shadows的bug，要修复可以考虑更新tauri2beta版 tauri2关闭window decoration之后还会保留窗口边框跟阴影，就不需要window-shadows了
