### ISSUE TITLE
[BUG]win10 无反应

### ISSUE THREAD

**Issue by a224327780** [clash-verge-rev/clash-verge-rev#459]
### Describe the bug

右下角图标点击无反应

webview2 已安装

### To Reproduce

右下角图标点击无反应

webview2 已安装

### Platform

Windows

### System Version

win10

### Software Version

22H2

**Comment by wonfen** [comment]
看FAQ，2个解决思路：

### verge无法正常启动
修复、卸载，重新安装webview2 https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download

### 有系统图标，主界面点不开
使用win7兼容模式，参考： https://github.com/zzzgydi/clash-verge/issues/717

**Comment by wonfen** [comment]
无近一步反馈，关闭。
