### ISSUE TITLE
[BUG] 对于DIRECT配置延迟测试结果不正确？

### ISSUE THREAD

**Issue by psychelzh** [clash-verge-rev/clash-verge-rev#460]
### Describe the bug

如下图，全球直连应该直接用

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/13306020/4c2c3344-1d5d-4b5f-acec-ba38d058b563)

### To Reproduce

总是如此，无需额外步骤

### Platform

Windows

### System Version

Windows 11

### Software Version

1.5.4

**Comment by MystiPanda** [comment]
默认测速链接是http://1.1.1.1，error正常
