### ISSUE TITLE
[BUG]钉钉连不上

### ISSUE THREAD

**Issue by laobanbiefangcu** [clash-verge-rev/clash-verge-rev#462]
### Describe the bug

开clash verge，钉钉连接不上，显示timeout

### To Reproduce

开clash verge，钉钉连接不上，显示timeout

### Platform

Windows

### System Version

Windows

### Software Version

11

### Log

一直报这个错误
02-26 14:29:21WARNING
[Metadata] not valid: &constant.Metadata{NetWork:0, Type:1, SrcIP:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffff7f000001}, z:(*intern.Value)(0xc0000060a8)}, DstIP:netip.Addr{addr:netip.uint128{hi:0x0, lo:0x0}, z:(*intern.Value)(nil)}, SrcPort:0x1f3d, DstPort:0x1bb, InIP:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffff7f000001}, z:(*intern.Value)(0xc0000060a8)}, InPort:0x1ed9, InName:"DEFAULT-MIXED", InUser:"", Host:"", DNSMode:0, Uid:0x0, Process:"", ProcessPath:"", SpecialProxy:"", SpecialRules:"", RemoteDst:"", DSCP:0x0, RawSrcAddr:net.Addr(nil), RawDstAddr:net.Addr(nil), SniffHost:""}
02-26 14:29:22WARNING
[Metadata] not valid: &constant.Metadata{NetWork:0, Type:1, SrcIP:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffff7f000001}, z:(*intern.Value)(0xc0000060a8)}, DstIP:netip.Addr{addr:netip.uint128{hi:0x0, lo:0x0}, z:(*intern.Value)(nil)}, SrcPort:0x1f3e, DstPort:0x1bb, InIP:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffff7f000001}, z:(*intern.Value)(0xc0000060a8)}, InPort:0x1ed9, InName:"DEFAULT-MIXED", InUser:"", Host:"", DNSMode:0, Uid:0x0, Process:"", ProcessPath:"", SpecialProxy:"", SpecialRules:"", RemoteDst:"", DSCP:0x0, RawSrcAddr:net.Addr(nil), RawDstAddr:net.Addr(nil), SniffHost:""}
02-26 14:29:24WARNING
[Metadata] not valid: &constant.Metadata{NetWork:0, Type:1, SrcIP:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffff7f000001}, z:(*intern.Value)(0xc0000060a8)}, DstIP:netip.Addr{addr:netip.uint128{hi:0x0, lo:0x0}, z:(*intern.Value)(nil)}, SrcPort:0x1f41, DstPort:0x1bb, InIP:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffff7f000001}, z:(*intern.Value)(0xc0000060a8)}, InPort:0x1ed9, InName:"DEFAULT-MIXED", InUser:"", Host:"", DNSMode:0, Uid:0x0, Process:"", ProcessPath:"", SpecialProxy:"", SpecialRules:"", RemoteDst:"", DSCP:0x0, RawSrcAddr:net.Addr(nil), RawDstAddr:net.Addr(nil), SniffHost:""}

**Comment by wonfen** [comment]
无近一步反馈，关闭。
