### ISSUE TITLE
[BUG] 静默启动失效

### ISSUE THREAD

**Issue by ghost** [clash-verge-rev/clash-verge-rev#466]
### Describe the bug

将启动页面设置为“连接”后，静默启动失效

### To Reproduce

启用静默启动
将启动页面设置为“连接”

### Platform

Windows

### System Version

Windows 11 23H2

### Software Version

1.5.4

**Comment by ExcellentHzj** [comment]
设成“代理”也失效，感觉就是静默启动坏了。

**Comment by MystiPanda** [comment]
如果出现任务管理器中有两个启动项，或者开机启动时静默启动失效，请用管理员权限启动软件后开关一次开机启动设置，即可删除多余的启动项，如果平时一直是使用管理员权限运行的软件，那就用普通用户权限运行软件后开关一次开机启动设置，删除多余启动项后后续不会再出现这个问题。

**Comment by MystiPanda** [comment]
参考 #423 #424
