### ISSUE TITLE
希望可以和 cfw 一样使用一个快捷键来开启/关闭代理

### ISSUE THREAD

**Issue by WhaleGe** [clash-verge-rev/clash-verge-rev#469]
### Is your feature request related to a problem? Please describe.

目前占用的快捷键有点多，希望能减少一点，这样也好记

### Describe the solution you'd like

和 开启/关闭面板 一样，只用一个快捷键

### Describe alternatives you've considered

无

**Comment by MystiPanda** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/152463842/65f3b9ff-3821-4422-9830-3b4f18185130)
