### ISSUE TITLE
[BUG] Update GEO databases failed

### ISSUE THREAD

**Issue by Jenichia** [clash-verge-rev/clash-verge-rev#470]
### Describe the bug

Can't save MMDB database file.

The requested operation cannot be performed on a file with a user-mapped section open.

### To Reproduce

Click **Update GeoData** button

### Platform

Windows

### System Version

Windows 11 22H2 (22621.3155)

### Software Version

1.5.4

### Log

**ERROR**
[REST-API] update GEO databases failed: can't save MMDB database file: open `C:\Users\Username\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev/Country.mmdb`: The requested operation cannot be performed on a file with a user-mapped section open.

### Additional Information

N/A

**Comment by MystiPanda** [comment]
最新alpha内核已修复
