### ISSUE TITLE
hysteria2端口跳跃

### ISSUE THREAD

**Issue by QeHaxdCp** [clash-verge-rev/clash-verge-rev#472]
### Is your feature request related to a problem? Please describe.

你好，因h2协议的UDP被限制或限速
请问能否支持hysteria2端口跳跃的功能呢，我在软件里没有找到端口跳跃的设置。
如果支持请问需要怎设置软件来支持hysteria2端口跳跃呢？
如果不支持，请问后续有计划支持这个功能吗？

### Describe the solution you'd like

h2协议定时自动切换UDP端口防止被限制或限速

### Describe alternatives you've considered

无

**Comment by wonfen** [comment]
请到meta那边提这个需求，是内核控制的
https://github.com/MetaCubeX/mihomo/issues

**Comment by wonfen** [comment]
无近一步反馈，关闭。
