### ISSUE TITLE
在任务栏添加网络使用情况

### ISSUE THREAD

**Issue by kylewen7** [clash-verge-rev/clash-verge-rev#473]
### Is your feature request related to a problem? Please describe.

非问题。

### Describe the solution you'd like

希望可以和以前的Clash一样增加在状态栏小猫的旁边展示网络上下行速度，有助于快速查看网络状态。

### Describe alternatives you've considered

没有啦。

**Comment by UntaggedRui** [comment]
+1 我也挺喜欢这个功能的，虽然在软件左下角也有，但是在任务栏感觉更爽

**Comment by WangEn** [comment]
+1 投一票

**Comment by WEAKwind** [comment]
+1

**Comment by Felix8029** [comment]
+1

**Comment by wxupjack** [comment]
+1 此外，也希望能加上 Enhanced Tray，可以用脚本定制tray显示的内容

**Comment by MystiPanda** [comment]
#576
