### ISSUE TITLE
[BUG]no such file or directory (os error2)

### ISSUE THREAD

**Issue by lebron8dong** [clash-verge-rev/clash-verge-rev#477]
### Describe the bug

![1](https://github.com/clash-verge-rev/clash-verge-rev/assets/73160333/ad275a01-3c17-4706-a5b4-6d26c15f30ba)

### To Reproduce

导入yaml文件之后，显示上述错误

### Platform

Linux

### System Version

22.04

### Software Version

1.5.4amd

**Comment by wonfen** [comment]
尝试卸载重装，赋予权限等操作。另外日志？
