### ISSUE TITLE
[BUG]win11系统 clash_verge_rev 在不打开tun模式的情况下直连显示dns解析失败

### ISSUE THREAD

**Issue by fengz63** [clash-verge-rev/clash-verge-rev#478]
### Describe the bug

clash_verge_rev软件在不打开tun模式时，国内直接连接的网站dns解析总是失败，日志如下
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/26649267/15cf8709-6959-491a-a770-326487506fb4)

其中软件对应的设置：
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/26649267/c5fe2560-b0dd-4cc4-a1e3-cbd37ec247e4)

### To Reproduce

打开clash_verge_rev，不开启tun模式，此时用浏览器打开国内网站就会出现打不开的情况

### Platform

Windows

### System Version

win11

### Software Version

1.5.4

**Comment by wonfen** [comment]
检查你的配置文件吧。这部分由内核处理。

**Comment by IcedWatermelonJuice** [comment]
原来不止我一个人是这样啊。不开tun，我用的推荐的狗狗加速，手动merge一个配置文件用来直连学校网站，结果也是dns解析失败。

**Comment by volcanolin** [comment]
我也是这个问题，自己建的节点用订阅转换网站转换成订阅后导入到clash verge rev里，在我的电脑上，不开tun模式的话大部分直连的国内网站都打不开，包括百度、知乎等，但是同一个订阅链接在别的电脑上不开tun的情况下打开国内网站是没有问题的。

**Comment by volcanolin** [comment]
刚刚从别的issue找到了解决方法，更改配置文件dns设置就可以了，分享给大家：[#599](https://github.com/clash-verge-rev/clash-verge-rev/issues/559#issuecomment-1988196599)

**Comment by fengz63** [comment]
> 刚刚从别的issue找到了解决方法，更改配置文件dns设置就可以了，分享给大家：[#599](https://github.com/clash-verge-rev/clash-verge-rev/issues/559#issuecomment-1988196599)

请教一下，手动修改这个配置的话，是不是重启后就会没了？还是说我修改的地方不对

**Comment by volcanolin** [comment]
> > 刚刚从别的issue找到了解决方法，更改配置文件dns设置就可以了，分享给大家：[#599](https://github.com/clash-verge-rev/clash-verge-rev/issues/559#issuecomment-1988196599)
> 
> 请教一下，手动修改这个配置的话，是不是重启后就会没了？还是说我修改的地方不对

你是说重启软件吗，我不懂开发，按我的使用经验来说修改配置后重启软件的话应该不会对修改过的配置有影响，除非你更新这个配置的订阅链接。我是自己建的节点转的clash订阅，不需要更新，所以我将从订阅链接里获取的yaml文件修改了dns配置另存了，使用clash verge rev的local模式加载的本地文件，这样配置文件就不会变了。

**Comment by volcanolin** [comment]
> > 刚刚从别的issue找到了解决方法，更改配置文件dns设置就可以了，分享给大家：[#599](https://github.com/clash-verge-rev/clash-verge-rev/issues/559#issuecomment-1988196599)
> 
> 请教一下，手动修改这个配置的话，是不是重启后就会没了？还是说我修改的地方不对

你是说重启软件吗，我不懂开发，按我的使用经验来说修改配置后重启软件的话不会对修改过的配置有影响，除非你更新这个配置的订阅链接。我是自己建的节点转的clash订阅，不需要更新，所以我将从订阅链接里获取的yaml文件修改了dns配置后另存了，使用clash verge rev的local模式加载了这个yaml文件，这样配置文件就不会变了。你如果用的机场的订阅链接的话，是每次都需要在更新订阅后修改配置文件的dns配置的。这是我一个外行人全凭经验的想法，供你参考。

**Comment by fengz63** [comment]
> > > 刚刚从别的issue找到了解决方法，更改配置文件dns设置就可以了，分享给大家：[#599](https://github.com/clash-verge-rev/clash-verge-rev/issues/559#issuecomment-1988196599)
> > 
> > 
> > 请教一下，手动修改这个配置的话，是不是重启后就会没了？还是说我修改的地方不对
> 
> 你是说重启软件吗，我不懂开发，按我的使用经验来说修改配置后重启软件的话不会对修改过的配置有影响，除非你更新这个配置的订阅链接。我是自己建的节点转的clash订阅，不需要更新，所以我将从订阅链接里获取的yaml文件修改了dns配置后另存了，使用clash verge rev的local模式加载了这个yaml文件，这样配置文件就不会变了。你如果用的机场的订阅链接的话，是每次都需要在更新订阅后修改配置文件的dns配置的。这是我一个外行人全凭经验的想法，供你参考。

感觉你说的是对的，我是从机场导入的订阅链接，重启软件/订阅更新后就没了

**Comment by volcanolin** [comment]
> > > > 刚刚从别的issue找到了解决方法，更改配置文件dns设置就可以了，分享给大家：[#599](https://github.com/clash-verge-rev/clash-verge-rev/issues/559#issuecomment-1988196599)
> > > 
> > > 
> > > 请教一下，手动修改这个配置的话，是不是重启后就会没了？还是说我修改的地方不对
> > 
> > 你是说重启软件吗，我不懂开发，按我的使用经验来说修改配置后重启软件的话不会对修改过的配置有影响，除非你更新这个配置的订阅链接。我是自己建的节点转的clash订阅，不需要更新，所以我将从订阅链接里获取的yaml文件修改了dns配置后另存了，使用clash verge rev的local模式加载了这个yaml文件，这样配置文件就不会变了。你如果用的机场的订阅链接的话，是每次都需要在更新订阅后修改配置文件的dns配置的。这是我一个外行人全凭经验的想法，供你参考。
> 
> 感觉你说的是对的，我是从机场导入的订阅链接，重启软件/订阅更新后就没了

我是把那个issue里的dns设置保存到本地了一份，以便出现这个问题时可以随时更改配置文件。建议你可以增加订阅更新的间隔，以减少手动改配置的频率。我还不知道这个问题的根源是什么，同样的订阅链接在别的电脑上没问题，在我这就不行，找到问题根源可能就能彻底解决了

**Comment by fengz63** [comment]
> > > > > 刚刚从别的issue找到了解决方法，更改配置文件dns设置就可以了，分享给大家：[#599](https://github.com/clash-verge-rev/clash-verge-rev/issues/559#issuecomment-1988196599)
> > > > 
> > > > 
> > > > 请教一下，手动修改这个配置的话，是不是重启后就会没了？还是说我修改的地方不对
> > > 
> > > 
> > > 你是说重启软件吗，我不懂开发，按我的使用经验来说修改配置后重启软件的话不会对修改过的配置有影响，除非你更新这个配置的订阅链接。我是自己建的节点转的clash订阅，不需要更新，所以我将从订阅链接里获取的yaml文件修改了dns配置后另存了，使用clash verge rev的local模式加载了这个yaml文件，这样配置文件就不会变了。你如果用的机场的订阅链接的话，是每次都需要在更新订阅后修改配置文件的dns配置的。这是我一个外行人全凭经验的想法，供你参考。
> > 
> > 
> > 感觉你说的是对的，我是从机场导入的订阅链接，重启软件/订阅更新后就没了
> 
> 我是把那个issue里的dns设置保存到本地了一份，以便出现这个问题时可以随时更改配置文件。建议你可以增加订阅更新的间隔，以减少手动改配置的频率。我还不知道这个问题的根源是什么，同样的订阅链接在别的电脑上没问题，在我这就不行，找到问题根源可能就能彻底解决了

我还有个问题就是我电脑关机的话，再开机，配置就失效了，我再看看有没有别的解决方案吧
