### ISSUE TITLE
[BUG]使用触控操作时无法拖动窗口

### ISSUE THREAD

**Issue by LOGYT-Eberk** [clash-verge-rev/clash-verge-rev#479]
### Describe the bug

正常的Windows窗口可通过按住窗口标题栏并拖动来移动窗口，但clash verge的窗口却无法通过触控操作拖动。
在下面的动图中，可以看到，edge的窗口可以被正常拖动，但clash vergr却不行
![Uploading 屏幕录制 2024-02-28 203304 (1).gif…]()

### To Reproduce

在支持触控的屏幕上，按住应用窗口标题栏并拖动，窗口无反应

### Platform

Windows

### System Version

Windows 11 22635.3140

### Software Version

1.54

**Comment by wonfen** [comment]
已修正：https://github.com/clash-verge-rev/clash-verge-rev/commit/1117e28b2e42ddf5e0a9bc1ad16189c9d3c18212
