### ISSUE TITLE
[BUG]M系列芯片，14.1.2系统下tun模式无效

### ISSUE THREAD

**Issue by wyylzy** [clash-verge-rev/clash-verge-rev#48]
-作業系統：macOS14.1.2 -衝突邊緣版本：1.4.1 -衝突核心：衝突元tun模式失效，仍旧需要设置代理代理IP和端口才能使用，希望修复，谢谢！

**Comment by wonfen** [comment]
参考：https://github.com/clash-verge-rev/clash-verge-rev/issues/43
