### ISSUE TITLE
[Feature] 能使用数字键切换左侧的选项卡 Be able to use the number keys to switch between the tabs on the left.

### ISSUE THREAD

**Issue by ydnkw** [clash-verge-rev/clash-verge-rev#480]
### Is your feature request related to a problem? Please describe.

No, it's not.

### Describe the solution you'd like

能使用数字键切换左侧的选项卡。
Be able to use the number keys to switch between the tabs on the left.
![](https://github.com/clash-verge-rev/clash-verge-rev/assets/104975004/f8c519ef-d438-45d1-8f0c-62094297e321)

### Describe alternatives you've considered

切换将各个选项卡放入热键设置中供用户自行设置。
Add a setting to the hot key settings about the tabs on the left.

**Comment by wonfen** [comment]
非核心功能，以后再说吧。
