### ISSUE TITLE
[BUG]软件自启，开机自启按钮无效The software starts automatically, and the boot auto-start button is invalid

### ISSUE THREAD

**Issue by iehtian** [clash-verge-rev/clash-verge-rev#481]
### Describe the bug

电脑开机后软件自启，即使关掉自启按钮仍然会自启
The software will start automatically after the computer is turned on, even if you turn off the auto-start button, it will still start on itself

### To Reproduce

电脑开机即自启，无法取消
The computer starts automatically when it is turned on and cannot be canceled

### Platform

Windows

### System Version

windows11 23H2

### Software Version

1.54

**Comment by wonfen** [comment]
应该是之前的一个已知bug，把留存的自动启动删了。

**Comment by MystiPanda** [comment]
- #466 
- #423 
- #424
