### ISSUE TITLE
[BUG]win11下打不开面板

### ISSUE THREAD

**Issue by Obsidian99** [clash-verge-rev/clash-verge-rev#482]
### Describe the bug

无法打开软件面板

### To Reproduce

任务栏点击或者右键选择打开面板，图标就消失，但代理仍然可用

### Platform

Windows

### System Version

WIN11 23H2

### Software Version

1.5.4

**Comment by dragc8** [comment]
我问题和你类似 ，只是打开代理页是空的 ，其他正常。 换了几个版本一样。我的win11 是dev版本，怀疑是webview版本太高造成的。

**Comment by Obsidian99** [comment]
我把webview卸载了，安装回来解决了
