### ISSUE TITLE
[BUG] clash-verge-rev start crashed in waylland 

### ISSUE THREAD

**Issue by GengYage** [clash-verge-rev/clash-verge-rev#486]
### Describe the bug

clash-verge-rev start crashed in waylland 

### To Reproduce

start clash-verge-rev on niri 

### Platform

Linux

### System Version

Linux archlinux 6.7.7-zen1-1-zen

### Software Version

1.5.4

### Log

RUST_BACKTRACE=full clash-verge
thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.3/src/lib.rs:2021:55:
called `Result::unwrap()` on an `Err` value: Unknown { .. } - "Unknown error while interacting with the clipboard: Display parsing error"
stack backtrace:
   0:     0x59c4d7ed5eaa - std::backtrace_rs::backtrace::libunwind::trace::hdc4233b41dc1b9cd
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x59c4d7ed5eaa - std::backtrace_rs::backtrace::trace_unsynchronized::h120e68387b28a22e
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x59c4d7ed5eaa - std::sys_common::backtrace::_print_fmt::ha2c8f57bdb4df8b5
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x59c4d7ed5eaa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h29fd9f59e5b156f6
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x59c4d7d23fb0 - core::fmt::rt::Argument::fmt::he2faf549fd7f6050
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/fmt/rt.rs:142:9
   5:     0x59c4d7d23fb0 - core::fmt::write::hb003a2722f32aba9
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/fmt/mod.rs:1120:17
   6:     0x59c4d7e9ebdc - std::io::Write::write_fmt::h5f2291dd5789d9ad
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/io/mod.rs:1810:15
   7:     0x59c4d7ed787f - std::sys_common::backtrace::_print::hc72c414d550b4638
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x59c4d7ed787f - std::sys_common::backtrace::print::h7bda25037860cb99
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x59c4d7ed70f3 - std::panicking::default_hook::{{closure}}::hae510b2efd1217a7
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:272:22
  10:     0x59c4d7ed8089 - std::panicking::default_hook::h67e28ed4cf565cf3
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:292:9
  11:     0x59c4d7ed8089 - std::panicking::rust_panic_with_hook::h340d3254c4a80530
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:779:13
  12:     0x59c4d7ed7bc0 - std::panicking::begin_panic_handler::{{closure}}::h20aebccdeba64ffc
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:657:13
  13:     0x59c4d7ed7b16 - std::sys_common::backtrace::__rust_end_short_backtrace::hfacd59953039e580
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x59c4d7ed7b0f - rust_begin_unwind
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/panicking.rs:645:5
  15:     0x59c4d7b555d4 - core::panicking::panic_fmt::h3b0fc9e47c437efe
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/panicking.rs:72:14
  16:     0x59c4d7b55b42 - core::result::unwrap_failed::h36d2e720ec9c5dcb
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/result.rs:1649:5
  17:     0x59c4d7bc42ab - core::result::Result<T,E>::unwrap::hbafafa2fd1bcb911
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/result.rs:1073:23
  18:     0x59c4d7bc42ab - tauri_runtime_wry::Wry<T>::init::h0ddc1de57545735b
                               at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.3/src/lib.rs:2021:38
  19:     0x59c4d7c0e97e - tauri::app::Builder<R>::build::h3f978b8a4e4017be
  20:     0x59c4d7cd7046 - clash_verge::main::h5b98117fb3e0243b
                               at /usr/src/debug/clash-verge/clash-verge-1.5.4/src-tauri/src/main.rs:103:15
  21:     0x59c4d7bd52c7 - core::ops::function::FnOnce::call_once::hfe0a4e7fb13170b7
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/ops/function.rs:250:5
  22:     0x59c4d7bd52c7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1fb81b5c9dd620d7
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:155:18
  23:     0x59c4d7cecc3e - main
  24:     0x76fa43957cd0 - <unknown>
  25:     0x76fa43957d8a - __libc_start_main
  26:     0x59c4d7b75bc5 - _start
  27:                0x0 - <unknown>
[1]    44893 IOT instruction (core dumped)  RUST_BACKTRACE=full clash-verge

**Comment by wonfen** [comment]
使用appimage试试：
https://github.com/clash-verge-rev/clash-verge-rev/issues/321
