### ISSUE TITLE
[BUG] Windows 驻留后台无法开启代理问题

### ISSUE THREAD

**Issue by gitlayzer** [clash-verge-rev/clash-verge-rev#487]
### Describe the bug

当 Clash Verge 长时间驻留在后台之后无法打开系统代理或者 TUN 模式，反之长时间打开这两个模式的任意一个的时候也是无法关闭，此问题是一个长期问题

### To Reproduce

........

### Platform

Windows

### System Version

10

### Software Version

latest

**Comment by MystiPanda** [comment]
长时间是指多长呢，我这边驻留四五个小时并没有复现

**Comment by gitlayzer** [comment]
> 长时间是指多长呢，我这边驻留四五个小时并没有复现

我这里两三个小时，就会出现这个问题，甚至一个小时就会出现这样的问题，导致我不得不退出软件重新打开，然后就自动打开了代理，我不知道是不是系统问题
