### ISSUE TITLE
[BUG]Windows内存泄漏问题

### ISSUE THREAD

**Issue by lishangyi** [clash-verge-rev/clash-verge-rev#488]
### Describe the bug

长时间将本软件放在后台运行，会吃掉大量的内存，目前在Windows10和Windows11都碰到过。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/56777446/8b5e9f7e-0f02-4173-8a09-e65beb23fe41)

### To Reproduce

放在后台一晚上即可触发。

### Platform

Windows

### System Version

Windows10

### Software Version

22H2

**Comment by MystiPanda** [comment]
给内核提 issue
