### ISSUE TITLE
无法导入订阅[BUG]

### ISSUE THREAD

**Issue by Redweff** [clash-verge-rev/clash-verge-rev#489]
### Describe the bug

无法导入与更新订阅，已经一个星期没更新了

### Platform

Windows

### System Version

x64

### Software Version

15.4

**Comment by wonfen** [comment]
你这网络不通；看看有没有被杀毒软件拦截了verge的网络访问。

**Comment by Redweff** [comment]
我退出了火绒还是不行，大佬快救救我

**Comment by yz1639** [comment]
兄弟， 你订阅地址泄漏了，顺便吐槽一下

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/44149984/71ec47e4-2c6b-46c9-aee9-0f7909a6fd74)
你这机场延迟也太高了  难怪叫慈善机场
