### ISSUE TITLE
[BUG]Clash verge在TUN模式下会导致email客户端出现“证书错误”情况

### ISSUE THREAD

**Issue by Stephenzero** [clash-verge-rev/clash-verge-rev#491]
### Describe the bug

Clash verge在TUN模式下会导致email客户端出现“证书错误”情况，email客户端这里指的是：MS outlook, Mozilla thunderbird,等软件，在收取发送的过程中都会显示“证书错误”

### To Reproduce

Clash verge在TUN模式下会导致email客户端出现“证书错误”情况，email客户端这里指的是：MS outlook, Mozilla thunderbird,等软件，在收取发送的过程中都会显示“证书错误”

### Platform

Windows

### System Version

11

### Software Version

outlook thunderbird

**Comment by wonfen** [comment]
需要更多信息，截图、日志等等。
另外GUI不处理这部分内容，建议检查配置文件，节点，机场的问题。

**Comment by Stephenzero** [comment]
> 需要更多信息，截图、日志等等。 另外GUI不处理这部分内容，建议检查配置文件，节点，机场的问题。

谢谢 best wishes
