### ISSUE TITLE
Debian GNU/Linux 怎么安装clash-verge呢？？

### ISSUE THREAD

**Issue by allrot** [clash-verge-rev/clash-verge-rev#492]
Debian GNU/Linux 怎么安装clash-verge呢？？

CPU架构一台是armv7l和另一台是X86_64

那个可以安装clash-verge

会的大哥给指点指点下。。感谢！

**Comment by allrot** [comment]
cpu架构是armv7l

**Comment by IceSniperring** [comment]
x86的建议直接使用AppImage，arm的应该也能使用

**Comment by parheliamm** [comment]
sudo dpkg -i XXXX.deb
