### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ardin963** [clash-verge-rev/clash-verge-rev#494]
### Describe the bug

Clash verge rev 的订阅文件，设置的更新时间为1440mins，但是过了一天时间之后还是不会自动更新，需要手动更新

### To Reproduce

Clash verge rev 的订阅文件，设置的更新时间为1440mins，但是过了一天时间之后还是不会自动更新，需要手动更新

### Platform

Windows

### System Version

Windows10

### Software Version

1.5.4

**Comment by wonfen** [comment]
是按软件运行时间计算的。
