### ISSUE TITLE
[BUG]Clash Verge开启tun模式软件可以访问Google，浏览器无法访问，国内网站访问正常

### ISSUE THREAD

**Issue by Ardin963** [clash-verge-rev/clash-verge-rev#495]
### Describe the bug

Clash Verge授予内核权限并开启tun模式的情况下，电报等软件可以上网，浏览器可以访问大陆网站，无法访问Google等网站。

但是开启tun模式的同时，开启系统代理，就可以正常访问，此时关闭系统代理保持tun模式开启，也能正常使用

### To Reproduce

1. Clash Verge intel 的Mac版本，授予meta内核权限，开启tun模式（浏览器无法访问）
2. 保持tun模式开启，开启系统代理（浏览器正常访问）
3. 保持tun模式开启，关闭系统代理（浏览器正常访问）

### Platform

MacOS

### System Version

10.15.7

### Software Version

1.5.4

**Comment by Ardin963** [comment]
Safari和Chrome都是一样的情况

**Comment by Ardin963** [comment]
更正一下：
Clash Verge intel 的Mac版本，授予meta内核权限，开启tun模式（浏览器无法访问）
保持tun模式开启，开启系统代理（浏览器正常访问）
保持tun模式开启，关闭系统代理（浏览器无法访问）

**Comment by ooh-ooh** [comment]
same issue

**Comment by wonfen** [comment]
非bug，使用问题。
tun模式和系统代理只用开一个。看下开启tun模式后是否有日志报错。

**Comment by Adobe94** [comment]
使用360路由器，默认安装verge，导入节点订阅后开启系统代理无法使用任何节点，表现为测试全error，开启系统代理并开启tun后才可以正常使用。
切换路由器，仅开启系统代理可使用。
不知道是不是和路由器有关系。路由器已经看过没有设置什么特别的。手机用surfboard连360的路由器wifi是可以使用代理的。

**Comment by ooh-ooh** [comment]
> 非bug，使用问题。 tun模式和系统代理只用开一个。看下开启tun模式后是否有日志报错。

mac 
clash meta 闪退， 
 clash meta alpha  success 还是不工作

**Comment by wonfen** [comment]
> > 非bug，使用问题。 tun模式和系统代理只用开一个。看下开启tun模式后是否有日志报错。
> 
> mac clash meta 闪退， clash meta alpha success 还是不工作

mac系统版本和CPU型号？

**Comment by Ardin963** [comment]
> 非bug，使用问题。
> tun模式和系统代理只用开一个。看下开启tun模式后是否有日志报错。

今天又试了一下，问题复现，但是日志里面没有error 都是WARNING和info

**Comment by Ardin963** [comment]
(Retina, 15-inch, Mid 2015) 
版本： intel macos 10.15.7
CPU: 2.2 GHz Quad-Core Intel Core i7
clash verge : v1.5.4
clash core: v1.18.1 Meta

**Comment by Ardin963** [comment]
> > > > 非bug，使用问题。 tun模式和系统代理只用开一个。看下开启tun模式后是否有日志报错。
> > > 
> > > 
> > > mac clash meta 闪退， clash meta alpha success 还是不工作
> > 
> > 
> > mac系统版本和CPU型号？
> 
> 版本： 12.7.3 (21H1015) mac os Monterey CPU: 2.2 GHz Quad-Core Intel Core i7 clash verge : v1.5.4 clash core: v1.18.1 Meta

我们是同一款吗，你的系统版本比我高，我用Catalina没有闪退，但是tun不正常

**Comment by ooh-ooh** [comment]
> > > > > 非bug，使用问题。 tun模式和系统代理只用开一个。看下开启tun模式后是否有日志报错。
> > > > 
> > > > 
> > > > mac clash meta 闪退， clash meta alpha success 还是不工作
> > > 
> > > 
> > > mac系统版本和CPU型号？
> > 
> > 
> > 版本： 12.7.3 (21H1015) mac os Monterey CPU: 2.2 GHz Quad-Core Intel Core i7 clash verge : v1.5.4 clash core: v1.18.1 Meta
> 
> 我们是同一款吗，你的系统版本比我高，我用Catalina没有闪退，但是tun不正常

同款，只是mac os 不同

**Comment by ooh-ooh** [comment]
03-12 11:28:33WARNING
[TUN] Unsupported tunName(Meta) in darwin, force regenerate by ourselves.
03-12 11:28:33WARNING
[TUN] default interface changed by monitor, => en0


新版本 1.5.7 警告

**Comment by Lovening** [comment]
我也是这个问题，就很烦，开代理每个软件都要配置，开tun 浏览器无法上网，每次都是把tun和代理都打开

**Comment by Ardin963** [comment]
03-13 20:33:58WARNING
replace fallback-filter.geosite with nameserver-policy, it will be removed in the future
03-13 20:33:58WARNING
[TUN] Unsupported tunName(Meta) in darwin, force regenerate by ourselves.
03-13 20:33:58WARNING
[TUN] default interface changed by monitor, => en0

03-13 20:33:59WARNING
[TCP] dial Bypassed (match Match/) 198.18.0.1:50983(com.apple.WebKit.Networking) --> 140.82.112.26:443 error: connect failed: dial udp 23.169.184.99:50010: connect: network is unreachable

后面好多类似的unreachable

然后是
03-13 20:34:01WARNING
To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+

03-13 20:34:01WARNING
replace fallback-filter.geosite with nameserver-policy, it will be removed in the future

**Comment by ooh-ooh** [comment]
1.5.8 tun fixed
