### ISSUE TITLE
[BUG] 新建订阅表单BUG

### ISSUE THREAD

**Issue by dongchengjie** [clash-verge-rev/clash-verge-rev#499]
### Describe the bug

已知名称是**非必填项**，但是无论类型选择哪一个，名称**永远都是**“Remote file”，即使类型和名称对不上
而且，**当删除内容不填时，保存后却根据类型给了默认值**？例如：Remote --> remote file，Local --> local file，Script --> script file,Merge --> merge file
为什么不一开始就给默认值或者placeholder呢？
**想改名字的，得人工删除一遍再改名**😰
**不想改名字的，不删就是Remote file牛头不对马嘴，要么还是得删除才是正确的默认值**👿

建议“名称”一栏使用placeholder提示"remote file"、“local file”之类，或者干脆直接空着。真正需要改名直接开始填入就行，无需删除后再填入。不打算起名字的就不管，根据类型决定默认名称

另外一个小bug就是，订阅Tab中订阅文件链接输入框右边的icon，在行业内很明显是**Copy**,而不是**Paste**吧😅
这是Copy:<img width="24" height="24" src="https://img.icons8.com/material-rounded/24/copy.png" alt="copy"/>
这才是Paste:<img width="24" height="24" src="https://img.icons8.com/material-outlined/24/paste.png" alt="paste"/>

### To Reproduce

订阅Tab-->新增按钮，选择不同的类型，名称永远不变。且手动删除保持为空后，根据类型给了默认值

### Platform

Windows

### System Version

windows 21H2

### Software Version

1.5.4

**Comment by wonfen** [comment]
> 订阅Tab中订阅文件链接输入框右边的icon，在行业内很明显是**Copy**,而不是**Paste**吧😅

paste的图标只有这个，不太符合用户认知习惯：
<img width="930" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/96291150/122610af-9abf-463c-be4b-431ecd0d61fa">

**Comment by wonfen** [comment]
> 为什么不一开始就给默认值或者placeholder呢？

默认值就是Remote file，感觉无伤大雅。

Paste的图标改了。
