### ISSUE TITLE
[BUG] MAC下无法上网

### ISSUE THREAD

**Issue by liuxiyang641** [clash-verge-rev/clash-verge-rev#5]
我的macos版本是10.15.7，使用最新的clash verge rev版本1.4.0
打开之后，可以成功的订阅，但是无法正确的启动对本机的代理
<img width="782" alt="image" src="https://github.com/wonfen/clash-verge-rev/assets/38466943/57dc608e-1ae5-4a52-ad4b-1824d201c148">
左下角上传与下载的流量一直是0，重复启动电脑，开启和关闭系统代理，切换监听port均无法解决这个问题

**Comment by wonfen** [comment]
请提供更多信息，这边无法复现。

**Comment by liuxiyang641** [comment]
<img width="501" alt="image" src="https://github.com/wonfen/clash-verge-rev/assets/38466943/713458c2-9b71-4e98-abac-0e39813b6944">

clash内核选择的是clash meta
然后系统代理显示开启失败..
有什么更详细的日志文件可以让我提供吗？

**Comment by liuxiyang641** [comment]
在找到的log文件里，会一直显示下面的debug信息：
`2023-11-24 09:28:42 DEBUG - try to guard the system proxy`
而在软件里，测试订阅相关节点的速度时，是可以连接通不同节点的。

**Comment by donald-ning** [comment]
目前此软件只能通过自己设置系统代理，才可以。无法通过软件自动开启系统代理。包括tun模式也无法连接。可能是内核的原因，只能等内核作者去实现了。

**Comment by liuxiyang641** [comment]
@donald-ning 你好，非常感谢你的回复。
也就是说，需要我手动通过`Proxy SwitchyOmega`这类的浏览器代理插件，才能够实现代理是吧？
我尝试使用`Proxy SwitchyOmega`插件去代理，结果可以成功的访问google了。

**Comment by donald-ning** [comment]
是的。

**Comment by wonfen** [comment]
试试点任务栏图标，然后点"复制环境变量(sh)"，到终端中粘贴执行，看看能否解决成功配置代理？

**Comment by liuxiyang641** [comment]
尝试了，仍然无法成功。
用命令行检查了端口，我的是监听1080端口，确定只有clash verge在占用：
```
  COMMAND     PID        FD   TYPE             DEVICE SIZE/OFF NODE NAME
  clash-met 67028        8u  IPv4 0xd7c7612bd211d21f      0t0  TCP localhost:socks (LISTEN)
  clash-met 67028        9u  IPv4 0xd7c7612ba61f4257      0t0  UDP localhost:socks
```

**Comment by wonfen** [comment]
试试最新版1.4.2

**Comment by liuxiyang641** [comment]
非常感激你的新版本！
我安装了最新版的release之后，发现系统代理仍然无法启动。但是如果切换为开启TUN模式，则可以成功上网

**Comment by bosco8833** [comment]
clash verge在mac上用， 需要先运行三行命令，才能正常上网

**Comment by liuxiyang641** [comment]
> clash verge在mac上用， 需要先运行三行命令，才能正常上网

你好 请问是哪三行命令呢？

**Comment by liuxiyang641** [comment]
另外，我发现需要首先选择点击clash内核，点击授权；之后开启TUN模式，才可成功上网

**Comment by bosco8833** [comment]
> > clash verge在mac上用， 需要先运行三行命令，才能正常上网
> 
> 你好 请问是哪三行命令呢？

你注册下 狗狗加速， 登录进去，里面有clash verge的mac说明

**Comment by liuxiyang641** [comment]
我试了，仍然不能启动系统代理...只有使用TUN模式的时候，软件起作用

**Comment by wonfen** [comment]
你升级系统到11试试看，我们都没有macos10的环境可以调试；估计是系统版本太老，开关系统代理的功能没有生效。
