### ISSUE TITLE
[BUG]windows系统手动设置绕过代理的地址，重新打开clash后设置被覆盖

### ISSUE THREAD

**Issue by redwolf1996** [clash-verge-rev/clash-verge-rev#501]
### Describe the bug

1. 在地址后面新增一个 172.19.*， 让它绕过clash代理
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/9690393/2b1d829c-abf4-4ee9-b0e9-c8a436c22211)
2. 重新机器或者重新启动clash后设置被覆盖，新增的172.19.* 不见了
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/9690393/fa04f385-6a12-4503-8c4e-07c0089bfdea)

### To Reproduce

请问这个情况是clash自动设置的吗，能否有入口可以自定义？

### Platform

Windows

### System Version

Windows 11 专业工作站版

### Software Version

1.5.4

**Comment by dongchengjie** [comment]
`设置`->`系统代理`这几个字的右边有个**小齿轮**，点开里面有“**代理绕过**“输入框可以配置

**Comment by redwolf1996** [comment]
> `设置`->`系统代理`这几个字的右边有个**小齿轮**，点开里面有“**代理绕过**“输入框可以配置，下方有”当前绕过“

额，原来是这样，解决了 3Q  ：）
