### ISSUE TITLE
[BUG] Merge配置了规则，指定域名使用GLOBAL，但是还是使用了DIRECT，GLOBAL未生效

### ISSUE THREAD

**Issue by weareware** [clash-verge-rev/clash-verge-rev#505]
### Describe the bug

Issue：已经启用了Merge，但是还是走了DIRECT。
我想要在访问 coze.com 时使用GLOBAL代理，但是使用merge规则后还是使用了DIRECT，使用的是GLOBAL[DIRECT]，而不是GLOBAL

clash配置：Tun模式，规则

（1）访问coze时日志如下：
03-07 14:47:46INFO
[TCP] 198.18.0.1:9449 --> www.coze.com:443 match DomainSuffix(coze.com) using GLOBAL[DIRECT]
03-07 14:47:47INFO
[TCP] 198.18.0.1:9455 --> sf-coze-web-cdn.coze.com:443 match DomainSuffix(coze.com) using GLOBAL[DIRECT]

（2）我的merge文件如下
# Merge Template for clash verge
# The `Merge` format used to enhance profile

prepend-rules:
    - DOMAIN-SUFFIX,coze.com,GLOBAL
    - DOMAIN-SUFFIX,ciciai.com,GLOBAL
    - DOMAIN-SUFFIX,mcs-sg.coze.com,GLOBAL

prepend-proxies:

prepend-proxy-groups:

append-rules:

append-proxies:

append-proxy-groups:

（3）目前的解决办法
使用全局访问coze成功之后，再切换为规则模式，就能使用GLOBAL

### To Reproduce

使用我的配置文件访问coze.com，即使merge已经启用还是会使用
[TCP] 198.18.0.1:9449 --> www.coze.com:443 match DomainSuffix(coze.com) using GLOBAL[DIRECT]

### Platform

Windows

### System Version

win 10

### Software Version

1.54

### Log

03-07 14:47:46INFO
[TCP] 198.18.0.1:9449 --> www.coze.com:443 match DomainSuffix(coze.com) using GLOBAL[DIRECT]
03-07 14:47:47INFO
[TCP] 198.18.0.1:9455 --> sf-coze-web-cdn.coze.com:443 match DomainSuffix(coze.com) using GLOBAL[DIRECT]

**Comment by MystiPanda** [comment]
GLOBAL是全局模式代理组，你在全局模式下选择的是direct，那么你所描述的就是正常行为，并没有Bug，你要实现分流应该指定规则模式下的其他代理组。

**Comment by weareware** [comment]
太感谢了，明白了，是我的问题
