### ISSUE TITLE
[BUG]左上角图标无法隐藏、拖动

### ISSUE THREAD

**Issue by jkhuangfu** [clash-verge-rev/clash-verge-rev#506]
### Describe the bug

<img width="108" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/20948189/e63a2837-dc21-4461-a0d5-1ac8a01677fc">
左上角图标无法隐藏、拖动

### To Reproduce

启动后就在左上角霸占着位置

### Platform

MacOS

### System Version

14.2

### Software Version

1.5.4

**Comment by PelikanM400** [comment]
同样遇到这个bug。据说是tauri的问题。

**Comment by PelikanM400** [comment]
其他使用tauri开发的客户端也有类似的问题，参考：
https://github.com/LibNyanpasu/clash-nyanpasu/issues/62
https://github.com/tauri-apps/tauri/issues/8570
https://github.com/tauri-apps/tray-icon/issues/90

**Comment by jkhuangfu** [comment]
> 其他使用tauri开发的客户端也有类似的问题，参考： [LibNyanpasu/clash-nyanpasu#62](https://github.com/LibNyanpasu/clash-nyanpasu/issues/62) [tauri-apps/tauri#8570](https://github.com/tauri-apps/tauri/issues/8570) [tauri-apps/tray-icon#90](https://github.com/tauri-apps/tray-icon/issues/90)

现在啥也没动，图标又莫名其妙的自动消失了

**Comment by PelikanM400** [comment]
> > 其他使用tauri开发的客户端也有类似的问题，参考： [LibNyanpasu/clash-nyanpasu#62](https://github.com/LibNyanpasu/clash-nyanpasu/issues/62) [tauri-apps/tauri#8570](https://github.com/tauri-apps/tauri/issues/8570) [tauri-apps/tray-icon#90](https://github.com/tauri-apps/tray-icon/issues/90)
> 
> 现在啥也没动，图标又莫名其妙的自动消失了

我的还在，没有消失。我记得早些时候clash工具都还没有删库那会，我用原版的clash verge，也有过这个问题。

**Comment by jkhuangfu** [comment]
> > > 其他使用tauri开发的客户端也有类似的问题，参考： [LibNyanpasu/clash-nyanpasu#62](https://github.com/LibNyanpasu/clash-nyanpasu/issues/62) [tauri-apps/tauri#8570](https://github.com/tauri-apps/tauri/issues/8570) [tauri-apps/tray-icon#90](https://github.com/tauri-apps/tray-icon/issues/90)
> > 
> > 
> > 现在啥也没动，图标又莫名其妙的自动消失了
> 
> 我的还在，没有消失。我记得早些时候clash工具都还没有删库那会，我用原版的clash verge，也有过这个问题。

tauri官方的bug，等fixed吧
