### ISSUE TITLE
在节点选择页面加代理开关

### ISSUE THREAD

**Issue by gxx2778** [clash-verge-rev/clash-verge-rev#510]
### Is your feature request related to a problem? Please describe.

在节点选择页面加代理开关，这样操作会更方便一些
![iShot_2024-03-08_11 02 02](https://github.com/clash-verge-rev/clash-verge-rev/assets/130665334/2e99adea-b463-4568-9cb9-31aa491b8e64)

### Describe the solution you'd like

在节点选择页面加代理开关

### Describe alternatives you've considered

无

**Comment by dongchengjie** [comment]
不是有托盘图标吗，正常使用都是”静默启动“放后台，然后右键托盘小猫咪图标切换模式吧
