### ISSUE TITLE
[BUG] 运行一段时间后，内存占用过高

### ISSUE THREAD

**Issue by we6288815** [clash-verge-rev/clash-verge-rev#511]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/8169722/f6d5e54e-8d63-47d4-884b-7f7b288b0cfa)
软件运行一段时间后，内存占用过高，重启应用后内存占用恢复正常
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/8169722/f19c86e1-7ce6-4046-b9c6-802d171b9154)

### To Reproduce

软件持续运行

### Platform

Windows

### System Version

Windows 10

### Software Version

Verge V1.5.4 Clash 内核 v1.18.1 Meta

**Comment by wonfen** [comment]
正常的。这个是内核在处理代理。如果要反馈建议贴出配置文件到meta那边反馈。
