### ISSUE TITLE
能否自动记住上次「订阅」和「节点」界面滚动条的位置，而不是每次重新加载？

### ISSUE THREAD

**Issue by Null404bad** [clash-verge-rev/clash-verge-rev#512]
### Is your feature request related to a problem? Please describe.

每次切出然后切回节点或订阅界面**默认回到首行**，但是当订阅文件和节点分组比较多时，我每次都需要再次滚动界面，找到已经选中并正在使用的节点分组或者订阅

### Describe the solution you'd like

1. 记住「**订阅**」界面上一次的滚动位置
2. 记住当前已选中订阅的「**节点**」界面上一次的滚动位置，而对于未选中订阅的节点界面信息，可以不进行缓存

### Describe alternatives you've considered

希望我描述清楚了我的问题，也希望您可以采纳这个意见。
我相信这对我和其他用户都很重要，非常感谢！

**Comment by KinComet** [comment]
[Feature] 代理界面记录滚动位置 #371

**Comment by Jorathan** [comment]
> ### Is your feature request related to a problem? Please describe.
> 每次切出然后切回节点或订阅界面**默认回到首行**，但是当订阅文件和节点分组比较多时，我每次都需要再次滚动界面，找到已经选中并正在使用的节点分组或者订阅
> 
> ### Describe the solution you'd like
> 1. 记住「**订阅**」界面上一次的滚动位置
> 2. 记住当前已选中订阅的「**节点**」界面上一次的滚动位置，而对于未选中订阅的节点界面信息，可以不进行缓存
> 
> ### Describe alternatives you've considered
> 希望我描述清楚了我的问题，也希望您可以采纳这个意见。 我相信这对我和其他用户都很重要，非常感谢！
> 
> ### Additional context
> _No response_

赞同
