### ISSUE TITLE
[BUG] 开启 TUN 后无法使用 Zerotier VPN 下的节点

### ISSUE THREAD

**Issue by KinComet** [clash-verge-rev/clash-verge-rev#513]
### Describe the bug

Zerotier网段：192.168.8.0/24
设备A使用Clash Verge；设备B使用3proxy软件进行socks代理，监听192.168.8.7(设备B IP)
设备A添加设备B 3proxy作为节点
设备A开启TUN时，无法使用Zerotier连接3proxy代理，测速显示Error；未开启TUN时，可以连接，正常测速。

### To Reproduce

1. 两台设备同时配置Zerotier
2. 一台设备安装3proxy或其它代理
3. 另一台设备开启TUN后连接代理

### Platform

Windows

### System Version

Windows 11

### Software Version

1.5.4

### Additional Information

可能为mihomo的问题。

**Comment by wonfen** [comment]
tun模式就是虚拟网卡，估计和VPN的虚拟网卡冲突了。

**Comment by KinComet** [comment]
> tun模式就是虚拟网卡，估计和VPN的虚拟网卡冲突了。

已经设置
`config.tun["endpoint-independent-nat"] = true` 尝试 `exclude-interface` 和 `inet4-route-exclude-address` 排除没能解决。
此外使用 Zerotier 接口进行的 parsec/RDP 连接极其不稳定。

**Comment by CheeseUnknown** [comment]
一样的问题，设置了tun后zerotier连接变得极不稳定，经常断开
