### ISSUE TITLE
[Feature]选择节点时候没有clash for Windows一样有个一键收起的功能

### ISSUE THREAD

**Issue by xiaoqun666** [clash-verge-rev/clash-verge-rev#514]
### Is your feature request related to a problem? Please describe.

![QQ截图20240308175236](https://github.com/clash-verge-rev/clash-verge-rev/assets/46390717/e8e8d64a-6de5-43a8-baf9-254dc802584d)
![QQ截图20240308175306](https://github.com/clash-verge-rev/clash-verge-rev/assets/46390717/4f3c277b-9f7f-4c08-a0f9-54e0afd9a729)
 

### Describe the solution you'd like

选择节点时候没有clash for Windows一样有个一键收起的功能，建议添加

### Describe alternatives you've considered

添加一个功能 可以进行一键收起，

**Comment by dongchengjie** [comment]
确实，节点太多的时候，group的combobox滚到顶部看不到了，应该滚动到顶部粘住，行业内叫**Sticky scroll**。
Sticky scroll（粘性滚动）是一种网页设计技术，它允许页面元素在滚动时保持固定位置。
通常情况下，当用户滚动页面时，页面上的元素会相应地移动或消失。但使用粘性滚动技术，某些元素（如导航栏或广告条）可以在用户滚动页面时保持固定在屏幕的特定位置，直到用户滚动到特定位置或特定条件满足时才消失或改变位置。

**Comment by leic4u** [comment]
+1 希望添加支持
