### ISSUE TITLE
proxy-providers里的机场订阅,如果订阅内有HY2节点,那么就无法转换过来[BUG]

### ISSUE THREAD

**Issue by RichFun8023** [clash-verge-rev/clash-verge-rev#515]
### Describe the bug

在订阅栏单独添加有hy2机场,就可以在代理栏正常显示HY2节点
但是如果配置文件多机场订阅,proxy-providers添加一个含hy2节点的机场,那么代理界面就无法显示和爬取到hy2节点.
望解决,或者有大佬解答一下有什么解决办法吗?

### To Reproduce

暂无

### Platform

Windows

### System Version

windows11

### Software Version

1.5.4

**Comment by MystiPanda** [comment]
配置文件添加:

```yml
global-ua: clash-verge/v1.5.4
```

**Comment by RichFun8023** [comment]
> 配置文件添加:
> 
> ```yaml
> global-ua: clash-verge/v1.5.4
> ```

没有效果 还是转换不过来

**Comment by RichFun8023** [comment]
> 配置文件添加:
> 
> ```yaml
> global-ua: clash-verge/v1.5.4
> ```

感谢已解决,非常感谢
