### ISSUE TITLE
[Feature] 连接页面过滤条件支持 port 筛选

### ISSUE THREAD

**Issue by hunshcn** [clash-verge-rev/clash-verge-rev#517]
### Is your feature request related to a problem? Please describe.

目前只有 host 和 ip 搜索，port 无法进行选择

### Describe the solution you'd like

支持 port 搜索，或者更丰富的语法？比如类似 tcpdump 的

### Describe alternatives you've considered

.

**Comment by dongchengjie** [comment]
程序有好多地方有”过滤条件“输入框，看起来你指的应该是”连接“中的搜索框

**Comment by hunshcn** [comment]
> 程序有好多地方有”过滤条件“输入框，看起来你指的应该是”连接“中的搜索框

是的
