### ISSUE TITLE
[BUG] 开启 TUN 模式后，导致规则失效（升级 macOS14.4 后）

### ISSUE THREAD

**Issue by youngerruan** [clash-verge-rev/clash-verge-rev#519]
### Describe the bug

（升级 macOS14.4 后），开启 TUN 模式后，连接里面显示的所有网络连接，均从网址，变为解析的 IP，导致配置文件里面按照网址写的规则失效，大量规则通过漏网之鱼这个配置组走（漏网之鱼是自己设置的，final 组）。macOS 14.3 时 tun 模式正常（没留意是 ip 还是域名，但是分流正常），代理模式还是正常的，代理模式是域名，可以正常分流。

### To Reproduce

升级系统为 macOS Sonoma 14.4，然后打开tun 模式设置，重置为默认，给内核授权，开启 tun 模式。system 或 gviser 都是这个 bug。

### Platform

MacOS

### System Version

macOS 14.4

### Software Version

1.5.4

**Comment by wonfen** [comment]
检查你的规则配置文件。

**Comment by youngerruan** [comment]
> 检查你的规则配置文件。

您好，方便告知一下可能的配置文件哪里有问题吗？我对照着 clash wiki，检查了好久，不知道哪里出错了。因为我用系统代理模式，是完全没问题的，规则都能正常分流。但是用 tun 模式后，我查看连接，显示的都是 ip，然后就没有匹配的项目，就走了 match（就是 final 组）。如果是系统代理模式，连接那块就是显示的域名，不是 ip，就能正常匹配到我写的规则，比如 sciencedirect.com（domain-suffix）。
