### ISSUE TITLE
[BUG]此应用无法在你的电脑上运行

### ISSUE THREAD

**Issue by zxyacg** [clash-verge-rev/clash-verge-rev#520]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/76837288/7b7fa144-8412-4545-b2ed-b04e3eefab33)

### To Reproduce

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/76837288/1c0fa1ee-7373-4b14-8295-091f7dd58b3f)

### Platform

Windows

### System Version

win11新版

### Software Version

新版

### Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/76837288/fe16f0b8-1e55-42bf-923d-b090cd54c480)

### Additional Information

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/76837288/915e2f1e-6308-458d-9eac-6b8d23dcaf99)

**Comment by Otis0227** [comment]
请检查安装的应用版本

**Comment by liao666brant** [comment]
请提供安装的软件版本与电脑的cpu型号信息

**Comment by dongchengjie** [comment]
下载前：amd64、amd64、amd64...😃
下载后：F**k! arm64😅

**Comment by zxyacg** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/76837288/c27cea68-7e18-4e12-87ff-1a7982647848)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/76837288/b5678c3f-01b5-4594-9201-db2aa585a21c)

**Comment by MystiPanda** [comment]
基于 x64 看不到吗，你下载 x64 啊，下载 arm64 干什么
