### ISSUE TITLE
[Feature]重启电脑时，Clash退出前，自动关闭“使用代理服务器”

### ISSUE THREAD

**Issue by ZhuangQu** [clash-verge-rev/clash-verge-rev#523]
### Is your feature request related to a problem? Please describe.

有时候，一旦重启电脑，我就无法上网。经过艰苦地排查，原因是这样的：
（1）Clash启用系统代理，打开了`使用代理服务器`（如下图所示）。
（2）如果手动退出Clash，`使用代理服务器`会随之关闭，一切正常。但是，如果重启电脑，`使用代理服务器`仍然保持开启。
（3）电脑重启之后，Clash没有运行，而`使用代理服务器`开启，使得我无法正常上网。

### Describe the solution you'd like

我希望重启电脑时，Clash在退出之前，能自动关闭`使用代理服务器`，就像手动退出Clash时一样。

### Describe alternatives you've considered

让Clash保持开机自启可以解决（相当于把A情形变为B情形），但这会增大系统负担。
| 情形 | Clash | 使用代理服务器 | 上网 |
| :-: | :-: | :-: | :-: |
| A | 不运行 | 关闭 | 正常 |
| B | 运行 | 开启 | 正常 |
| C | 不运行 | 开启 | 异常 |

### Additional context

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/89310792/d0259521-90cf-41f5-8df6-166f6f4a6ccf)

**Comment by lbcake** [comment]
> ### Is your feature request related to a problem? Please describe.
> 有时候，一旦重启电脑，我就无法上网。经过艰苦地排查，原因是这样的： （1）Clash启用系统代理，打开了`使用代理服务器`（如下图所示）。 （2）如果手动退出Clash，`使用代理服务器`会随之关闭，一切正常。但是，如果重启电脑，`使用代理服务器`仍然保持开启。 （3）电脑重启之后，Clash没有运行，而`使用代理服务器`开启，使得我无法正常上网。
> 
> ### Describe the solution you'd like
> 我希望重启电脑时，Clash在退出之前，能自动关闭`使用代理服务器`，就像手动退出Clash时一样。
> 
> ### Describe alternatives you've considered
> 让Clash保持开机自启可以解决（相当于把A情形变为B情形），但这会增大系统负担。
> 
> 情形	Clash	使用代理服务器	上网
> A	不运行	关闭	正常
> B	运行	开启	正常
> C	不运行	开启	异常
> ### Additional context
> ![image](https://private-user-images.githubusercontent.com/89310792/311443852-d0259521-90cf-41f5-8df6-166f6f4a6ccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5OTY3MTcsIm5iZiI6MTcwOTk5NjQxNywicGF0aCI6Ii84OTMxMDc5Mi8zMTE0NDM4NTItZDAyNTk1MjEtOTBjZi00MWY1LThkZjYtMTY2ZjZmNGE2Y2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE1MDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MmJhNGIxNDM3MWEzMjg5MWJhNDNlYjVjYWI1ZTg1YTRlODhlNjRmN2U4M2U3Y2FkODI3ZmQyYTExNjRhMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S0vxi-ucK3ftrtJExm000JmejYMnNn0TlDbCJqhjrz8)

记得每次打开clash关闭即可。  或者不打开clash  去代理选项 取消掉代理

**Comment by liao666brant** [comment]
使用tun模式不使用系统代理即可

**Comment by dongchengjie** [comment]
系统确实有相应事件回调（注销、重启、关机），但是意外关机（蓝屏、断电之类的）还是解决不了。因为程序没有被通知，还是得老老实实开机后打开clash一遍或者去设置里关掉。
我反正是习惯了，一发现没网就知道发生了什么😅

**Comment by ZhuangQu** [comment]
> 系统确实有相应事件回调（注销、重启、关机），但是意外关机（蓝屏、断电之类的）还是解决不了。因为程序没有被通知，还是得老老实实开机后打开clash一遍或者去设置里关掉。 我反正是习惯了，一发现没网就知道发生了什么😅 另外，我发现系统代理**偶尔**主动退出软件都清除不掉，得跑去开启/关闭一遍”系统代理守卫“，然后再退出才能清除，也不知道啥毛病

你说得对，蓝屏、断电确实没办法，但重启、关机仍是可以避免的。

**Comment by ZhuangQu** [comment]
> 使用tun模式不使用系统代理即可

我不知道该如何配置tun模式，采用默认配置，无法上网QAQ

**Comment by Bush2021** [comment]
v2rayN 实现过，不知道开发者愿不愿意移植过来：https://github.com/2dust/v2rayN/issues/1549
