### ISSUE TITLE
[BUG] debian Linux 11 unable to run clash-verge, and unable to install libcrypto.so.3

### ISSUE THREAD

**Issue by javenhmh** [clash-verge-rev/clash-verge-rev#53]
**Describe the bug**
[A clear and concise description of what the bug is.]
clash-verge: error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory)

**To Reproduce**

1. dpkg -i clash-verge_1.4.2_amd64.deb
2. run clash-verge
3. See error
4. unable to install libcrypto.so.3

**Expected behavior**
$ clash-verge
clash-verge: error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory

**Screenshots**

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/12635249/bcaf0e69-d2d4-45a9-86a6-fb0bc3017827)

**Information**

- OS: [e.g. Debian linux 11]
- Clash Verge Version: [e.g. 1.4.2]
- Clash Core: [e.g. Clash or Clash Meta]

**Additional context**

**Comment by handsomexdd1024** [comment]
hmm... I suppose the first thing is to check if libcrypto.so.3 is included in the deb package?

**Comment by MystiPanda** [comment]
使用apt安装最新版试试
