### ISSUE TITLE
[Feature] Web UI设置中预设一些常用面板

### ISSUE THREAD

**Issue by dongchengjie** [clash-verge-rev/clash-verge-rev#530]
## 描述
`设置`->`Clash设置`->`Web UI`中可以预设一些**常见的UI面板**，萌新第一使用的时候简直摸不着头脑，输入框里到底要填什么😅
```
https://yacd.haishan.me/?host=%host&port=%port&secret=%secret
https://clash.razord.top/?host=%host&port=%port&secret=%secret#/proxies
https://clash.metacubex.one/?host=%host&port=%port&secret=%secret#/proxies
```
另外一个小问题，这个页面”新建“操作后的内容居然排在前面，正常思维应该的追加到列表尾部吧
## 面板预览图
<img width="1250" alt="yacd" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/250e5d95-5614-46bc-92d7-9cceaa870ab3">
<img width="1234" alt="ra" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/4d7ac1b8-2735-4a1c-afb0-4a8c2c282f20">
<img width="1240" alt="cube" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/027bbd9c-eee6-4929-8242-243bb9ee03b2">

### Describe the solution you'd like

1. 预设一些常见面板
2. 按照新建的内容排在列表末尾

### Describe alternatives you've considered

无

**Comment by wonfen** [comment]
好议题。

**Comment by wonfen** [comment]
已添加。
