### ISSUE TITLE
UI设置

### ISSUE THREAD

**Issue by ZT-Y** [clash-verge-rev/clash-verge-rev#531]
### Is your feature request related to a problem? Please describe.

可以换回1.5.4的UI界面吗，1.5.5感觉好丑啊

### Describe the solution you'd like

感觉1.5.4的UI设计更简洁，更美观，请求下个版本返回到1.5.4的UI设计

### Describe alternatives you've considered

无

### Additional context

无

**Comment by dongchengjie** [comment]
人家毕竟工作都做了，删了不是白干了？😅可以搞成两套主题吧

**Comment by MystiPanda** [comment]
换个软件不就好了

**Comment by zmaplex** [comment]
Material 风格更耐看些，毕竟人家是专业的设计师团队来整的视觉方案，这个新版 UI 风格也不错就是了，但是字体不和谐以及看久了容易视觉疲劳，希望能改进下字体。

**Comment by MystiPanda** [comment]
字体调整了，下载 alpha 版本
