### ISSUE TITLE
[BUG]代理订阅无法更新一直转圈圈

### ISSUE THREAD

**Issue by wuenci666** [clash-verge-rev/clash-verge-rev#532]
### Describe the bug

代理订阅无法更新一直转圈圈

### To Reproduce

每次只要更新代理订阅就一直转圈圈

### Platform

Windows

### System Version

windows10

### Software Version

1.5.5

**Comment by dongchengjie** [comment]
刚更新完，特地不开代理更新订阅测试了一下，并不会一直转圈，超时时间大概15秒左右吧，最多转圈这么久然后弹出错误信息，说明你的链接真的上不去

**Comment by Null404bad** [comment]
> 刚更新完，特地不开代理更新订阅测试了一下，并不会一直转圈，超时时间大概15秒左右吧，最多转圈这么久然后弹出错误信息，说明你的链接真的上不去，你可以右键选择更新（代理）按钮试一试

我也是一样，无论开代理、不开代理、全局/规则模式，都不能更新订阅。但是按理来说，全局模式下，更新订阅应该也是走代理啊，为啥要选择「更新（代理）」模式就可以更新了？

**Comment by Null404bad** [comment]
我也是一样，无论开代理、不开代理、全局/规则模式，都不能更新订阅。但是按理来说，全局模式下，更新订阅应该也是走代理啊，为啥要选择「更新（代理）」模式就可以更新了？

**Comment by Jorathan** [comment]
我也是一样，无论开代理、不开代理、全局/规则模式，都不能更新订阅。但是按理来说，全局模式下，更新订阅应该也是走代理啊，为啥要选择「更新（代理）」模式就可以更新了？

**Comment by MystiPanda** [comment]
很多机场的订阅域名都是可以直连的，甚至不允许挂代理更新，所以默认是直连更新的。
