### ISSUE TITLE
[BUG]首页实时流量图BUG

### ISSUE THREAD

**Issue by wuenci666** [clash-verge-rev/clash-verge-rev#533]
### Describe the bug

只要一开启服务模式或者Tun模式，流量图就直接罢工不统计了，啥数据都没有了！

### To Reproduce

只要一开启服务模式或者Tun模式，流量图就直接罢工不统计了，啥数据都没有了！

### Platform

Windows

### System Version

windows10

### Software Version

1.5.5

**Comment by wonfen** [comment]
重启下软件试试。

**Comment by Amnesiash** [comment]
在设置页面进行内核授权

**Comment by Ffffffffchopin** [comment]
> 在设置页面进行内核授权

能请问一下具体怎么做才能 给内核授权吗，我也碰到了这个问题服务模式下流量图一直为0

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/97517883/c68b1855-e45b-4098-ac2d-07e39029426c)
