### ISSUE TITLE
[BUG] 哥，这次更新的UI太丑了，跪求回退UI

### ISSUE THREAD

**Issue by YUANJIXX** [clash-verge-rev/clash-verge-rev#535]
### Describe the bug

 哥，这次更新的UI太丑了，跪求回退UI

### To Reproduce

 哥，这次更新的UI太丑了，跪求回退UI

### Platform

Windows

### System Version

 哥，这次更新的UI太丑了，跪求回退UI

### Software Version

 哥，这次更新的UI太丑了，跪求回退UI

### Log

 哥，这次更新的UI太丑了，跪求回退UI

### Additional Information

 哥，这次更新的UI太丑了，跪求回退UI

**Comment by Aira-Sakuranomiya** [comment]
同感，原本好好的 Material Design 招惹谁了？
