### ISSUE TITLE
[feature]UI界面改进的提议

### ISSUE THREAD

**Issue by sle1008** [clash-verge-rev/clash-verge-rev#536]
**1 ：希望把左侧选项栏的间隔调小一点

2 ：希望图中2处所框出来的这些可以不随节点的滚动而滚动，也就是冻结在首行。否则节点较多时得上下来回翻。**

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/39543446/df1b50d2-3d6a-4be5-96b4-e7bc00745bf2)

**Comment by wonfen** [comment]
1已经改进，2以后再说。

**Comment by betaxab** [comment]
希望能将侧栏上的字体字重调为正常字重，而不是加粗，这样看起来不舒服，也不现代化。

<img width="692" alt="Snipaste_2024-03-10_11-13-42" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/30405429/947fecdb-3fd2-44ab-a924-8bb366387a09">

我这没更好的截图举例，就拿 windows 资源管理器来对比吧，这样看起来很舒服。

<img width="531" alt="Snipaste_2024-03-10_11-14-07" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/30405429/5dc19754-784e-40f0-b6a1-26a29e2a7684">

**Comment by sle1008** [comment]
其实改版之前的UI就挺好的~现在是加了拟物风格的icon，字体变大间距变大。但是好像最近这些年更流行扁平化和极简化风格？不过这都是小事，功能没大问题就行

**Comment by cikichen** [comment]
> 1已经改进，2以后再说。

啥时候把mac下surge的菜单功能抄一下就完美了

**Comment by OrzMiku** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/42781101/e7fa68ce-59aa-4a3b-b331-2d739c6e3453)
我觉得这里的线可以去掉，看起来会简约一点

**Comment by YUANJIXX** [comment]
这次UI改的太花里胡哨了，希望加入以前的UI模型，可在客户端自行切换

**Comment by YUANJIXX** [comment]
![微信图片_20240310123152](https://github.com/clash-verge-rev/clash-verge-rev/assets/128463893/4791d31f-5af3-4b9c-b91b-913bbc72553a)
尤其是这一排图标，配色太非主流了。。
