### ISSUE TITLE
[Feature] v1.5.5 新UI中文界面字体

### ISSUE THREAD

**Issue by Furton-Leo** [clash-verge-rev/clash-verge-rev#537]
### Is your feature request related to a problem? Please describe.

平台：windows10

我感觉这个字体有点奇怪，但是我又说不上来(⊙﹏⊙)

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/57217960/f6cb3747-5063-48d9-8360-d48a85fda703)

### Describe the solution you'd like

添加一个选择字体功能

### Describe alternatives you've considered

想换成自己的字体

**Comment by dongchengjie** [comment]
一直以来就可以切换字体啊，`设置`->`主题设置`->`Font family`，填入字体名称就行了
<img width="644" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/711b63e2-f842-4865-9250-ec9aa91bf185">

**Comment by MystiPanda** [comment]
调整了
