### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dregen-Yor** [clash-verge-rev/clash-verge-rev#539]
### Describe the bug

我发现在使用过程中，如果从在代理页面中，从规则切换到全局后，会无法修改代理选项，之后点击“规则”或者”直连“选项都没有任何反应，重新加载后代理页面会为空，
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/54179862/072413a0-75bd-4804-a459-fa91b21c16fe)
且一直卡在这个页面。使用其他机场也会出现这种问题

### To Reproduce

从规则模式切换为全局模式

### Platform

Linux

### System Version

Arch Linux 6.7.6

### Software Version

1.5.5

**Comment by cikichen** [comment]
今天的版本好像有问题，会导致正常直连的网站都响应超时，我出现了几次，继续观察下

**Comment by Dregen-Yor** [comment]
补充一下，通过面板上代理页面的规则与全局按钮无法正常切换，但是右键小托盘时通过显示的规则模式与全局模式可以正常切换。

**Comment by wonfen** [comment]
日志？

**Comment by Dregen-Yor** [comment]
> 日志？

点击按钮后没有日志生成，也没有其他变化。

**Comment by wonfen** [comment]
无日志不知道问题所在。
