### ISSUE TITLE
[Feature]关于快捷键打开/关闭面板显示

### ISSUE THREAD

**Issue by Coffeemeta** [clash-verge-rev/clash-verge-rev#540]
### Is your feature request related to a problem? Please describe.

在使用快捷键呼出面板的时候会有明显的卡顿感 关闭面板时没有问题

### Describe the solution you'd like

希望作者带佬可以改善下

### Describe alternatives you've considered

希望作者带佬可以改善下

**Comment by MystiPanda** [comment]
tauri启动webview需要时间
