### ISSUE TITLE
[Feature] 关于CSS注入（CSS Injection）的优化方案

### ISSUE THREAD

**Issue by Yanstory** [clash-verge-rev/clash-verge-rev#542]
### Is your feature request related to a problem? Please describe.

虽然CSS注入是以前就有的功能，但就目前的现有资料来看，这个功能上手难度过高，包括但不限于无法定位目标元素、无法调试等，难以发挥这个功能的实际效果

### Describe the solution you'd like

#530 中提到可以为Web UI预置部分模板，我认为可以沿用到主程序上

此外还希望能够支持CSS调试以自订CSS，或者增添一些常规模块的CSS指定

### Describe alternatives you've considered

None

**Comment by dongchengjie** [comment]
如何在不下载源码的情况下拿到querySelectotr啊，Ctrl+Shift+I也呼不出Console，想体验下这个Feature来着也没机会
其实知道CSS Injection这个功能的，就已经算半个开发者了。对于这批用户上手应该还是没有难度的，就像给Typora写主题一样，提供个呼出开发者工具的就好了
