### ISSUE TITLE
[BUG]新UI节点延迟看不清

### ISSUE THREAD

**Issue by OrzMiku** [clash-verge-rev/clash-verge-rev#544]
### Describe the bug

新UI节点延迟看不清

### To Reproduce

首先是默认配色的Success Color，在延迟显示这里与背景的对比度很低。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/42781101/62a9cbd4-d5e6-4a5f-a32c-1e53a6f91ec9)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/42781101/6640ca5a-51b4-49a7-9864-58cd1d1792db)

然后就是字重太低，字太小，即使换了颜色，也有点看不清的感觉。

### Platform

Windows

### System Version

Windows11

### Software Version

1.5.6

**Comment by MystiPanda** [comment]
调整了，稍等编译完成之后可以下载alpha版本测试
