### ISSUE TITLE
[Feature]cfw与verge双开的可行性？

### ISSUE THREAD

**Issue by ibin7777** [clash-verge-rev/clash-verge-rev#546]
### Is your feature request related to a problem? Please describe.

非技术，不懂底层原理，单纯好奇想问下cfw(或者其他相似套壳) 和verge同时开启会不会有冲突？
正在从cfw过渡到verge，经常需要两个轮换更新订阅、设置啥的，故想到这回事。

### Describe the solution you'd like

。

### Describe alternatives you've considered

。

**Comment by Amnesiash** [comment]
设置不同端口，只要不同时开启tun模式就行，系统代理后一个开启的会覆盖前一个

**Comment by ibin7777** [comment]
谢谢解答。
