### ISSUE TITLE
[BUG]Windows11浅色模式下托盘图标难以看清

### ISSUE THREAD

**Issue by lainbo** [clash-verge-rev/clash-verge-rev#55]
**Describe the bug**
在Windows11系统下，主题为浅色，托盘图标和背景颜色过于接近

**To Reproduce**

1. 使用Windows11的浅色主题
2. 打开Clash Verge Rev

**Expected behavior**
期望能使用一个能够看的清楚的颜色

**Screenshots**
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/46062895/dd93f267-a67f-496e-95dc-d0d7b80569c7)

**Information**

- OS: Windows11 23H2
- Clash Verge Version: 1.4.2
- Clash Core: Clash Meta

**Additional context**
可以参考这个色彩设计网站
https://color.review/
这个网站可以指导在某种背景色下，应该使用什么颜色的文字能让用户看得清楚，比如在我反馈的这个情况中，在该网站显示的前景背景对比度只有1.2，而托盘图标应该达到4.5
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/46062895/30f188fd-914e-4ecb-8f9d-3cf0ed896946)

**Comment by wonfen** [comment]
下个版本换个颜色。

**Comment by MystiPanda** [comment]
改了
