### ISSUE TITLE
[BUG] 无法启动系统代理

### ISSUE THREAD

**Issue by Soyoline** [clash-verge-rev/clash-verge-rev#551]
### Describe the bug

导入订阅链接后可以正常ping节点以及使用测试功能，但是系统代理始终无法开启
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/110441053/b401de2d-3d29-407f-ab17-9d4c811e6326)
即使在图形化界面中或者任务栏右键点击中重复开关也无法开启系统代理，在设置中始终显示为False

### To Reproduce

正常开关系统代理即是

### Platform

Windows

### System Version

Win11 23H2

### Software Version

1.5.6

**Comment by wonfen** [comment]
检查是否有杀毒软件阻止了。

**Comment by fenggeg** [comment]
> 检查是否有杀毒软件阻止了。

我也存在这个问题，和杀毒软件没关系，我使用普通的热点和宽带能正常开启系统代理，在公司我需要用vpdn联网，这个时候无法开启系统代理（cfw是能正常开启的）

**Comment by Eileem** [comment]
> > 检查是否有杀毒软件阻止了。
> 
> 我也存在这个问题，和杀毒软件没关系，我使用普通的热点和宽带能正常开启系统代理，在公司我需要用vpdn联网，这个时候无法开启系统代理（cfw是能正常开启的）

是的，我也是通过校园网客户端联网，似乎这种情况下就无法开启系统代理，同样在CFW那边可以正常开启
