### ISSUE TITLE
[BUG]今天的新版本一直出现timeout

### ISSUE THREAD

**Issue by cikichen** [clash-verge-rev/clash-verge-rev#552]
### Describe the bug

过一会就会出现全部的策略timeout

### To Reproduce

必现，出现问题时日志里面所有的请求都是timeout。关闭代理后网络恢复

### Platform

Windows

### System Version

11

### Software Version

1.5.6

### Log

03-10 17:09:43WARNING
[TCP] dial 🚀 节点选择 (match DomainKeyword/github) 127.0.0.1:5786(Clash Verge.exe) --> github.com:443 error: china3.one.edu.kg:12035 connect error: dns resolve failed: lookup china3.one.edu.kg on 192.168.8.1:53: read udp 192.168.8.100:59864->192.168.8.1:53: i/o timeout
03-10 17:09:44WARNING
[TCP] dial 🚀 节点选择 (match DomainKeyword/github) 127.0.0.1:5786(Clash Verge.exe) --> github.com:443 error: china3.one.edu.kg:12035 connect error: dns resolve failed: lookup china3.one.edu.kg: i/o timeout
03-10 17:09:49WARNING
[TCP] dial 🎯 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:5815(WeChat.exe) --> wxapp.tc.qq.com:80 error: dns resolve failed: lookup wxapp.tc.qq.com: i/o timeout

### Additional Information
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/1478821/70409dcb-4683-487a-af98-1c70383f8349)

**Comment by wonfen** [comment]
alpha内核已知bug，切换为稳定版1.18.1

**Comment by cikichen** [comment]
> alpha内核已知bug，切换为稳定版1.18.1

用的是稳定版
