### ISSUE TITLE
[意见] 新UI让人失望，当年那个清爽、优雅、简洁的产品彻底没了么？

### ISSUE THREAD

**Issue by toyo2333** [clash-verge-rev/clash-verge-rev#553]
### Describe the bug

对于之前版本的UI问题和感受，表达过看法： https://github.com/clash-verge-rev/clash-verge-rev/issues/263
  但今天看到新版本UI后，让我大受震感。

### To Reproduce

是的，我装了之后，马上卸载了。现在已经切换到 clash-nyanpasu （虽然也不怎么好看）

这个事情的本质是在于：

1、核心开发组的对于产品界面UI的审美肯是不合格的， 他们对于旧版本存在的问题看不出来 https://github.com/clash-verge-rev/clash-verge-rev/issues/263  ，然后自然对于新版的UI问题在哪里估计也是搞不清楚头绪。

2、这个项目的前身叫 clash-verge ，它曾经以 **清爽、优雅、简洁**（请记住这3个形容词）的UI风格著称，加上对meta的支持大受欢迎。而如今的 “UI风格” 或者说 “设计理念” 已经和当初那个clash-verge 已经完全不搭边了。当然你要硬说这是两个不同的产品，老子想怎么改都可以，那我也无话可说。

3、一款工具型产品，绝不是堆叠一堆功能。好的 UI交互 肯定是一块不可或缺非常重要的要素。如果只是用功能，我使用内核+一个web页面也可以用（后面我可能打算就这么用了，如果这些GUI产品的水平都如此失准的话）。

另外，仓库里加广告也能理解，毕竟谁也不能要求别人永远为爱发电。但因为上述1、2、3的情况下，再看到广告，着实让我感觉不太舒服。

没有恶意，就是希望一个好产品它的重生和延续能走出新的高度和段位，而不是是仅仅把流量接过来后赚广告费。

### Platform

Windows

### System Version

11

### Software Version

最新

**Comment by MystiPanda** [comment]
所以呢，给我一个不close的理由，说那么多有一句有用的吗？

**Comment by MystiPanda** [comment]
审美合不合格不是你说了算的，大可不必那么自以为是，也没见你给我出个设计稿啊

**Comment by MystiPanda** [comment]
牛逼

**Comment by MystiPanda** [comment]
第一，我不是仓库所有者，广告不是我挂的，我更新这个破b软件我拿不到一分钱
第二，我要为了赚点广告费我何必在这更新，旧版本的界面我何必去动他，我大可那这1.3.8的界面在这说我在维护，借着clash-verge的流量慢慢赚，大可不必用你那恶心的思想来恶意揣测
第三，人家@Amnesiash连续两三天大半夜的跟我一起讨论细节的设计，你除了在这放屁你还能干什么
第四，`他们对于旧版本存在的问题看不出来 https://github.com/clash-verge-rev/clash-verge-rev/issues/263 ，然后自然对于新版的UI问题在哪里估计也是搞不清楚头绪。` 既然你能看出你所谓的存在的问题，你为什么不出个设计稿来修改呢，不求你对项目有一丁点的贡献，就算具体的指出问题你都做不到。

**Comment by yanDebug** [comment]
ui挺好看的啊，而且没规定开源项目不能打广告吧。
“核心开发组的对于产品界面UI的审美肯是不合格的”这是一句不尊重和具有攻击性的话。

**Comment by zhaobudaomingzi** [comment]
> 别啊，这就破防了？ 不至于不至于。

是你得不到其他人的认同，从而破防了吧。
觉得UI不好看可以自己fork一份开发自己的主题，让别人看看你的实力呗😆

**Comment by Amnesiash** [comment]
> > > 别啊，这就破防了？ 不至于不至于。
> > 
> > 
> > 是你得不到其他人的认同，从而破防了吧。
> > 觉得UI不好看可以自己fork一份来开发自己的主题，让别人看看你的实力呗😆
> 
> 我不会写代码。我就是个用户。对用户要求不用太高。你觉得你产品牛逼不想我用了后吐槽 你就去搞有限授权发行，或者付费。但我觉得他们搞付费还不如打广告简单来钱快。至于你说的认同论，我觉得可以试一试 把这个issue reopen了，然后看看是不是真的没有人认同，让群众评判下嘛。不过，我觉得恐怕开发组不敢open。哈哈。他们心里连自己这一关都过不了，更不愿意公开讨论了。虚呗，我心里虚，我也close。要理解开发者嘛 😄

额，我就是为了好看，自己fork自学react调主题的，开发找我合并到主分支是后来的事，本来我觉的自娱自乐一下挺好，你大可不必有这么多意见，难道开源项目还需要做个市场调研吗

**Comment by PctAIGM** [comment]
开源软件，爱用就用，没人求你用。觉得不好就自己fork出来改，开发者没有顺着你要求改的义务，啥都要人惯着你，整一个巨婴似的，看着就恶心。

**Comment by leic4u** [comment]
看完前因后果，想问一下楼主多大了，巨婴心态这么严重，还没断奶吧？字里行间流露出颐指气使的态度，不知道是在哪学的。

还「没有恶意」，哦确实没有恶意，因为你是纯恶心。

**Comment by YBxbxxz** [comment]
经典用免费的东西,还一堆屁事的巨婴

**Comment by sf467** [comment]
傻逼巨婴

**Comment by NAME76** [comment]
新版ui确实丑

**Comment by sf467** [comment]
作为一个冒着危险维护这么一个开源项目的人来说，确实有足够的权力完全凭着自己的喜好来维护这个项目，也确实有足够的权力不采纳任何建议。

**Comment by yecheng0324** [comment]
只能说是经典言论，我白嫖我站在道德顶点

**Comment by MrCloudyGod** [comment]
免费的东西在这高高在上指点确实挺乐的，哪怕人真有广告又咋地，你又不掏钱赞助你嫌弃你别用呗
之前几个退出江湖的大佬都是被这种睿智巨婴气走的

**Comment by tomthenpc** [comment]
这个UI其实不错的

**Comment by lxtx528** [comment]
我喜欢这个软件，不喜欢的人不要用哦。

**Comment by lonercci** [comment]
笑死我了，不喜欢就不要用，没人逼着求你说用用吧求求了

**Comment by NuoFang6** [comment]
逆天🤡

**Comment by zhangde2333** [comment]
> > > > > 别啊，这就破防了？ 不至于不至于。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 是你得不到其他人的认同，从而破防了吧。
> > 
> > 
> > > > 觉得UI不好看可以自己fork一份来开发自己的主题，让别人看看你的实力呗 😆
> > 
> > 
> > > 
> > 
> > 
> > > 我不会写代码。我就是个用户。对用户要求不用太高。你觉得你产品牛逼不想我用了后吐槽 你就去搞有限授权发行，或者付费。但我觉得他们搞付费还不如打广告简单来钱快。至于你说的认同论，我觉得可以试一试 把这个issue reopen了，然后看看是不是真的没有人认同，让群众评判下嘛。不过，我觉得恐怕开发组不敢打开。哈哈。他们心里连自己这一关都过不了，更不愿意公开讨论了。虚呗，我心里虚，我也close。要理解开发者嘛 😄
> > 
> > 
> > 道德绑架了哈哈，issue是干这个的？
> 
> 我的建议是close效率再提高点，闷声发大财嘛！祝大卖！

你这个逼娘养的是真离谱。

**Comment by heinu123** [comment]
起手xhs风格，给不出明确设计方案被点破楼主就死咬一个他认为的“污点”疯狂阴阳怪气。
楼主也没有给出你认为更好的解决方案 而是在单纯的拉踩并没有想解决问题的意思

 毫无意义的issues还恶心人 我感觉点个举报都没有问题

**Comment by RiverFlowsInUUU** [comment]
很喜欢黄章的一句话，不喜欢就滚，人云亦云。🤡

**Comment by yanyao2333** [comment]
看不惯就自己 fork 一份改到顺眼自己用就得了，想证明自己比 core developer 牛逼就把你改完的 pr 过来，让带伙评价下🤣

**Comment by long45343** [comment]
> > > > > 别啊，这就破防了？ 不至于不至于。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 是你得不到其他人的认同，从而破防了吧。
> > 
> > 
> > > > 觉得UI不好看可以自己fork一份来开发自己的主题，让别人看看你的实力呗 😆
> > 
> > 
> > > 
> > 
> > 
> > > 我不会写代码。我就是个用户。对用户要求不用太高。你觉得你产品牛逼不想我用了后吐槽 你就去搞有限授权发行，或者付费。但我觉得他们搞付费还不如打广告简单来钱快。至于你说的认同论，我觉得可以试一试 把这个issue reopen了，然后看看是不是真的没有人认同，让群众评判下嘛。不过，我觉得恐怕开发组不敢打开。哈哈。他们心里连自己这一关都过不了，更不愿意公开讨论了。虚呗，我心里虚，我也close。要理解开发者嘛 😄
> > 
> > 
> > 道德绑架了哈哈，issue是干这个的？
> 
> 我的建议是close效率再提高点，闷声发大财嘛！祝大卖！

除了阴阳怪气你还会干什么啊？

**Comment by Just-Prog** [comment]
CN开源社蛆经典

**Comment by funcdfs** [comment]
> > > 别啊，这就破防了？ 不至于不至于。
> > 
> > 
> > 是你得不到其他人的认同，从而破防了吧。
> > 觉得UI不好看可以自己fork一份来开发自己的主题，让别人看看你的实力呗😆
> 
> 我不会写代码。我就是个用户。对用户要求不用太高。你觉得你产品牛逼不想我用了后吐槽 你就去搞有限授权发行，或者付费。但我觉得他们搞付费还不如打广告简单来钱快。至于你说的认同论，我觉得可以试一试 把这个issue reopen了，然后看看是不是真的没有人认同，让群众评判下嘛。不过，我觉得恐怕开发组不敢open。哈哈。他们心里连自己这一关都过不了，更不愿意公开讨论了。虚呗，我心里虚，我也close。要理解开发者嘛 😄

不会写代码就别他妈在github开吠。臭脑残滚去用局域网

**Comment by harennie** [comment]
能明白cfw的作者为什么会删库走人了

**Comment by zcmi** [comment]
> > 觉得做的不好可以自己提pr或者fork一份自己开发，实在是不理解自己用着免费的产品然后还来发牢骚。
> 
> 别啊，这就破防了？ 不至于不至于。
> 
> 算了，还是给你们提个更“实质性”意见吧：你们可以在关键环节设置一个“丢包”逻辑，然后“适时”弹出机场广告，这样转化率会更高。
> 
> 再往后可以接多个机场的广告，谁给得高，丢包率就低。
> 
> 这样甲方爸爸也满意，你们也开心，皆大欢喜。
> 
> 我都祝你们大卖特卖了！放过我吧：）
> 
> 到此为止啦。结帖。

在其他软件是不是得私信骂再拉黑，一击脱离呀，小丑

**Comment by 15Shell** [comment]
> > > > > 别啊，这就破防了？ 不至于不至于。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 是你得不到其他人的认同，从而破防了吧。
> > 
> > 
> > > > 觉得UI不好看可以自己fork一份来开发自己的主题，让别人看看你的实力呗 😆
> > 
> > 
> > > 
> > 
> > 
> > > 我不会写代码。我就是个用户。对用户要求不用太高。你觉得你产品牛逼不想我用了后吐槽 你就去搞有限授权发行，或者付费。但我觉得他们搞付费还不如打广告简单来钱快。至于你说的认同论，我觉得可以试一试 把这个issue reopen了，然后看看是不是真的没有人认同，让群众评判下嘛。不过，我觉得恐怕开发组不敢打开。哈哈。他们心里连自己这一关都过不了，更不愿意公开讨论了。虚呗，我心里虚，我也close。要理解开发者嘛 😄
> > 
> > 
> > 道德绑架了哈哈，issue是干这个的？
> 
> 我的建议是close效率再提高点，闷声发大财嘛！祝大卖！

小丑一个，什么都不会做的巨婴，伸手发现拿不到自己想要的东西就开始喷粪了哈哈😄

**Comment by czm180** [comment]
> > > > > 别啊，这就破防了？ 不至于不至于。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 是你得不到其他人的认同，从而破防了吧。
> > 
> > 
> > > > 觉得UI不好看可以自己fork一份来开发自己的主题，让别人看看你的实力呗 😆
> > 
> > 
> > > 
> > 
> > 
> > > 我不会写代码。我就是个用户。对用户要求不用太高。你觉得你产品牛逼不想我用了后吐槽 你就去搞有限授权发行，或者付费。但我觉得他们搞付费还不如打广告简单来钱快。至于你说的认同论，我觉得可以试一试 把这个issue reopen了，然后看看是不是真的没有人认同，让群众评判下嘛。不过，我觉得恐怕开发组不敢打开。哈哈。他们心里连自己这一关都过不了，更不愿意公开讨论了。虚呗，我心里虚，我也close。要理解开发者嘛 😄
> > 
> > 
> > 道德绑架了哈哈，issue是干这个的？
> 
> 我的建议是close效率再提高点，闷声发大财嘛！祝大卖！

一个若智觉得自己审美十分优越但是自己又没有脑子写出自己想要的ui，觉得人家写的符合大众审美的免费ui不对自己胃口的同时还想着让人家给他当黑奴来定制适合他的东西，一只地沟里的老鼠吃了点细糠把自己当人上人了来这里喷粪了是吧，下水道里的底层生物进化成了屁眼和嘴巴对调的生物的表现大抵就是您这样了吧。在开源项目提个issue就为了展示自己那发育不健全的大脑和反人类的艺术感，实在是让人大开眼界。

**Comment by Zxis233** [comment]
也中issue

**Comment by ikun2020** [comment]
傻逼一个

**Comment by CuteKims** [comment]
不会敲代码？没问题
来来来 Figma Xd Illustrator画几笔 整个原型 给大伙秀一手

**Comment by BLxcwg666** [comment]
你玩原神吗

**Comment by Zpcola** [comment]
我的评价是,多说无益
所以,你🐎什么时候死啊

**Comment by SAFEluren** [comment]
废物

**Comment by Adachi-Git** [comment]
joker里的顶梁柱，哥谭市里的大客户，麦当劳的吉祥物，扑克牌里的最大数。

**Comment by AlyssaChia2017** [comment]
开源项目  不感谢作者也就算了  满嘴喷粪确实难以理解   有毒

**Comment by gebederry** [comment]
慕名而来，围观

**Comment by nibazshab** [comment]
傻逼东西，老子操烂你妈的逼。

**Comment by AllForLandlord** [comment]
话说我搞不明白为什么楼主觉得Closed的issue其他人就不能回复了，现在不是还是可以回复的吗？
顺便说一句，楼主傻逼~

**Comment by mirai-MIC** [comment]
> > 看了其他几个已经被close掉的issues，五味杂陈。我估计这个issues应该很快也会被close掉。
> > 
> > 就这样把：）
> 
> 符合剧情发展。
> 
> 换位思考下，也能理解，说到痛处了，尤其是广告这个被揭短，换谁都难顶。
> 
> 就这个问题的吐槽，到此为止。
> 
> 祝你们大卖特卖~😄
> 
> 
> 
> 

事实胜于雄辩，但雌辨胜于事实，脂肪 压迫了声道，大脑连接了欢乐豆，一动 脑就爽死了，银地链接大脑，高朝代 替思考，摘蘑菇没洗手我看是扣出幻觉 了，读的书叠起来没有音醇厚，下回发 言之前把紫色心情调最大档插脑子里震 震，也算是说话前动了脑了

**Comment by mirai-MIC** [comment]
> > 
> > 
> > 
> > 
> > 
> > 
> > > > > 别啊，这就破防了？ 不至于不至于。
> > 
> > > > 
> > 
> > > > 
> > 
> > > > 是你得不到其他人的认同，从而破防了吧。
> > 
> > > > 觉得UI不好看可以自己fork一份来开发自己的主题，让别人看看你的实力呗 😆
> > 
> > > 
> > 
> > > 我不会写代码。我就是个用户。对用户要求不用太高。你觉得你产品牛逼不想我用了后吐槽 你就去搞有限授权发行，或者付费。但我觉得他们搞付费还不如打广告简单来钱快。至于你说的认同论，我觉得可以试一试 把这个issue reopen了，然后看看是不是真的没有人认同，让群众评判下嘛。不过，我觉得恐怕开发组不敢打开。哈哈。他们心里连自己这一关都过不了，更不愿意公开讨论了。虚呗，我心里虚，我也close。要理解开发者嘛 😄
> > 
> > 
> > 
> > 道德绑架了哈哈，issue是干这个的？
> 
> 我的建议是close效率再提高点，闷声发大财嘛！祝大卖！


事实胜于雄辩，但雌辨胜于事实，脂肪 压迫了声道，大脑连接了欢乐豆，一动 脑就爽死了，银地链接大脑，高朝代 替思考，摘蘑菇没洗手我看是扣出幻觉 了，读的书叠起来没有音醇厚，下回发 言之前把紫色心情调最大档插脑子里震 震，也算是说话前动了脑了

**Comment by d3ara1n** [comment]
我很喜欢这个新ui，让人眼前一亮。以及楼主说话的语气像巨婴，自言自语高高在上，感觉没必要从娘胎肚子里出来

**Comment by LanChangrong** [comment]
让我免费用你家女性，我就觉得你喷的对✅，给你点赞

**Comment by tangwenlongNO1** [comment]
真的不管啥圈子都有这sb玩意

**Comment by mirai-MIC** [comment]
6

**Comment by LanChangrong** [comment]
> > 觉得做的不好可以自己提pr fork一份自己开发，实在是不明白自己用着免费的产品然后还来发牢骚。
> 
> 别啊，这就破了？ 不至于不至于。
> 
> 算了，还是给你们提个更“合适”的意见吧：你们可以在关键环节设置一个“丢包”逻辑，然后“适时”弹出机场广告，这样转化率会更高。
> 
> 再往后可以接多个机场的广告，谁给得高，丢包率就低。
> 
> 这样甲方爸爸也满意，你们也开心，皆大欢喜。
> 
> 我都祝你们大卖特卖了！放过我吧：）
> 
> 到此结局啦。结帖。

让我免费用你家女性，我就觉得你喷的对✅，给你点赞

**Comment by Jenichia** [comment]
这么的吧，你去考美术学校。考上的话等你学成归来用专业知识给大家伙说说新旧 UI 之优劣，到那时开发团队应该会参考你的意见的。没考上你就在这里新建一个啤酒馆仓库，然后发表大量你的这些观点，把认同你意见的人召集起来，苦心经营一段时间然后直接一个集中力量拿下 clash-verge-rev，大幅调整修改 UI 界面，再把 README.md 中广告部分替换成几张现时的 UI 截图搞一个颓废艺术展。

以上内容纯属玩笑。

对 UI 成见那么大就去用命令行吧，直接没有 UI，没有 UI 就没这么多破事，省的天天看着 UI 给自己找不高兴。什么？你不会命令行？那就学啊，比起数理化要简单得多，就算学得慢一周也能速成。要么你就学我，我对命令行可谓深恶痛绝，因为我看到这东西就生理不适，所以我只能用 GUI 产品。设计符合我审美的也用过，不符合我审美的也用过，只要功能不出问题都一样用。主打的就是一个温水煮青蛙但水是自己放的火候是自己调的只不过水不会变烫，习惯了也就好了。自我麻痹有时候很有效果，至少很多事能看开，不用一直为了一些并不重要的破事为难自己，除非是有被害妄想症。

广告嘛，有钱为什么不赚？就算人家给开发团队广告费也不是希望这软件能做更好，而是希望他们自己的产品能卖更好，你见过那个广告主宣传 AD 是为了让广告商业绩更好的？
