### ISSUE TITLE
[BUG]只能通过代理方式更新订阅

### ISSUE THREAD

**Issue by zhm-github** [clash-verge-rev/clash-verge-rev#554]
### Describe the bug

不打开系统代理情况下，到订阅栏，然后更新，一直报错。弹窗：远程主机强迫关闭了一个现有的连接。 (os error 10054)
只能在打开系统代理情况下，通过更新（代理）才能更新订阅。
同理，不打开系统代理情况下，也无法通过url导入机场地址。

### To Reproduce

在不打开系统代理下，无法更新订阅，无法通过url导入机场地址。

### Platform

Windows

### System Version

win10 22h2

### Software Version

v1.5.6

### Log

远程主机强迫关闭了一个现有的连接。 (os error 10054)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/53134593/eabbf2e6-0e1e-4e75-a962-e1873b438ba6)

**Comment by MystiPanda** [comment]
这是你机场的问题，给你机场客服反馈

**Comment by zhm-github** [comment]
> 这是你机场的问题，给你机场客服反馈

不是机场的问题，我用clash，v2ray都能在不开代理情况下，直接更新订阅。

**Comment by MystiPanda** [comment]
那你把ua改成跟cfw的一样试试

**Comment by zhm-github** [comment]
> 那你把ua改成跟cfw的一样试试

请问clash verge是在哪里修改user agent

**Comment by dearyyjjpp** [comment]
楼主，我也遇到此问题，无法更新，请问解决了吗，如何解决这个问题

**Comment by dearyyjjpp** [comment]
<img width="371" alt="Snipaste_2024-03-15_09-45-30" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/63941905/6929ffca-997d-40cf-8506-ce6673622d5b">

**Comment by dearyyjjpp** [comment]
![图片](https://github.com/clash-verge-rev/clash-verge-rev/assets/63941905/66fe9fc0-5ccf-4fad-944d-edbb2e02d7fd)

**Comment by zhm-github** [comment]
> 楼主，我也遇到此问题，无法更新，请问解决了吗，如何解决这个问题

没有解决。我先用着其他客户端。

**Comment by dearyyjjpp** [comment]
> > 楼主，我也遇到此问题，无法更新，请问解决了吗，如何解决这个问题
> 
> 没有解决。我先用着其他客户端。

楼主，我倒是发现如果使用是rev 1.5.8的话，重新安装，不升级的话，倒是能稳定一些，能正常的进行更新，升级以后，就出现远程主机无法访问
