### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Fyg369** [clash-verge-rev/clash-verge-rev#555]
### Describe the bug

Windows窗口只能拖动和移动clash verge窗口，其它菜单无法点击，双击菜单功能窗口只能被放大，貌似就和图片一样只能放大缩小和移动，其它所有菜单都无法点击

### To Reproduce

![1](https://github.com/clash-verge-rev/clash-verge-rev/assets/142138034/33706ed1-f04a-459e-8a17-6a06f5350656)

### Platform

Windows

### System Version

Windows 11 专业版   版本号：22631.3085

### Software Version

v1.5.6

**Comment by munan56** [comment]
same error。
version ：Clash.Verge_1.5.6_x64_portable

**Comment by wonfen** [comment]
重装下webview2试试。

**Comment by Fyg369** [comment]
> 重装下webview2试试。

重新安装也是一样，用原作者不维护的就没问题

**Comment by Fyg369** [comment]
> webview2

问题解决了，卸载webview2重新安装，重启电脑后就可以了
