### ISSUE TITLE
[Feature] UI 改进建议及我的 UI 设计稿

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [clash-verge-rev/clash-verge-rev#560]
新的 UI 几乎没有 Material Design 味了，Clash Verge 作为一个使用了 Material Design UI 库的软件，新的改动令很多人失望了，希望可以在使用 Material Design 的基础上进行改进，这样皆大欢喜。

以下为我的 UI 设计稿**初版**，是 Figma 制作的。其他页面待制作，我认为想要改进 UI 是可以继续使用 Material Design 的。

<img width="776" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/45261195/e6a711f1-1637-4c17-b9db-0fd4543bb6aa">

**Comment by YUANJIXX** [comment]
新的UI真的太丑了，我不知道创作者的审美受到到了什么刺激

**Comment by MystiPanda** [comment]
新的UI采用扁平化设计，并没有计划采用 Material Design，两种风格，各有特色罢了

**Comment by MystiPanda** [comment]
> 新的UI真的太丑了，我不知道创作者的审美受到到了什么刺激

别用了，卸载了吧，算我求你了

**Comment by MystiPanda** [comment]
确实存在的一些不太和谐的细节alpha版本已经进行了多次调整，你可以下载alpha版本看看

**Comment by Amnesiash** [comment]
言之有无

> 新的 UI 几乎没有 Material Design 味了，Clash Verge 作为一个 Material Design 软件，新的改动令很多人失望了，希望可以在使用 Material Design 的基础上进行改进。
> 
> 以下为我的 UI 设计稿**初版**，是 Figma 制作的。其他页面待制作，我认为想要改进 UI 是可以继续使用 Material Design 的。
> 
> <img alt="image" width="776" src="https://private-user-images.githubusercontent.com/45261195/311509907-e6a711f1-1637-4c17-b9db-0fd4543bb6aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzYzODksIm5iZiI6MTcxMDA3NjA4OSwicGF0aCI6Ii80NTI2MTE5NS8zMTE1MDk5MDctZTZhNzExZjEtMTYzNy00YzE3LWI5ZGItMGZkNDU0M2JiNmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDEzMDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNWI4MmQ0MTU4MjhlMjJiOWM1YzQzNjIyYmY4NjI3NzYyNmJhMTAzMGMwMTY5NWYxYzIzNjZkM2ZlMDRkZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nzxBKTLWemMJH45K5w6WopmgVN4qTIm6pIsglh8-1ts">

言之有物，先点个赞，首先我自己这边是准备走appledesign的新扁平风格，其次的话，建议你可以看看google新版的Material Design 3，他们也已经弃用大量阴影，采用更明亮的色彩规则卡片化
https://m3.material.io/components

**Comment by zhaobudaomingzi** [comment]
首先，我觉得软件本身有多套UI可用，将选择权交给用户是好的。我本人也喜欢Material Design这种风格（没有不喜欢扁平化的意思）
然后，我觉得在你的初稿中，小猫图标和软件顶部的标题有些过大了。如果能调小一些，UI界面应该会更和谐。希望能继续改进~

**Comment by YUANJIXX** [comment]
> > 新的UI真的太丑了，我不知道创作者的审美受到到了什么刺激
> 
> 别用了，卸载了吧，算我求你了

大哥首先感谢你的无私奉献，我不是再攻击你，我只是作为用户提一些小建议！ 可能用你的产品时间久了风格突然大改一时半会接受不了。可以保留原始UI吗？ 用户可以在客户端里自行切换

**Comment by Aira-Sakuranomiya** [comment]
现在所采用的界面框架是 MUI 的 Material UI，我认为既然用了这个框架，那就应该用 Material Design。

本人自己就是很喜欢 macOS 的人，同时也会做 Apple 风格的设计，不是不喜欢 Apple 的设计风格。

现在这样强行尝试将框架里的组件魔改到 Apple 的风格会让设计有种诡异感，因为 Material Design 和 Apple 的设计风格相容性很差（跟 Microsoft 的 Fluent Design 倒是还好）。除非能真的保证所有细节都能彻底改到，但是这样做会导致升级框架容易出现各种界面小问题。

比如现在界面里会出现完全没有阴影但是样式还是 Material Design 的 Select 组件。

综上所述，我认为这个项目最适合使用 Material Design，若想要改为 Apple 的设计风格应该重新弄界面框架，现在这样的半成品看上去是很奇怪的。

**Comment by luowei729** [comment]
各位，我觉得让gpt4评判一下2个UI哪个美观

**Comment by luowei729** [comment]
> 各位，我觉得让gpt4评判一下2个UI哪个美观

下面的是claude3的主观评价
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/10611605/57160d8b-3eb3-4ac9-a753-1e03159a89d8)

**Comment by Aira-Sakuranomiya** [comment]
> > 各位，我觉得让gpt4评判一下2个UI哪个美观
> 
> 下面的是claude3的主观评价

你是来搞笑的吗？

仔细看看它说的文字，采用了浅色的青绿？进度条？状态指示灯？

我觉得新 UI 的设计者看了你这 AI 结论也会觉得这是搞笑。

**Comment by kitawa1981** [comment]
不知道Clash Verge有相关css injection的说明文档吗？希望有更多的通过css来调整界面的方法以及详细的说明，比如各个部位的字体样式，大小，颜色等等。
其次希望在托盘菜单加入像clashx pro这样的节点列表和延迟测速，这样就不必打开主界面了
<img width="462" alt="截屏2024-03-10 下午10 43 03" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/129429050/bde5fe49-bf0a-43f5-a440-eff5c087bd59">

**Comment by Amnesiash** [comment]
> > 各位，我觉得让gpt4评判一下2个UI哪个美观
> 
> 下面的是claude3的主观评价 ![image](https://private-user-images.githubusercontent.com/10611605/311517463-57160d8b-3eb3-4ac9-a753-1e03159a89d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwODc1ODEsIm5iZiI6MTcxMDA4NzI4MSwicGF0aCI6Ii8xMDYxMTYwNS8zMTE1MTc0NjMtNTcxNjBkOGItM2ViMy00YWM5LWE3NTMtMWUwMzE1OWE4OWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDE2MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMDY4NWRjNjNiYTk1MzNhYmIwYjM1NmFjZmYwNjViNTk5YzVmMjZkODUzNjM3ZTI1OGM2OTRiZWM5YjA5NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4pl0eSNA_0BXZOnBoxe60S91sFWaYrQorOxRtxqNX8Y)

还是尊重一下别人的成果，不要轻易去下定论， @Aira-Sakuranomiya 的想法是好的，然后这个😂其实我没出过稿子，毕竟出稿子沉没成本有点高，基本是想到哪里改哪里（源代码上直接上手改）,也没有很好的规划

**Comment by Aira-Sakuranomiya** [comment]
> > > 各位，我觉得让gpt4评判一下2个UI哪个美观
> > 
> > 
> > 下面的是claude3的主观评价 ![image](https://private-user-images.githubusercontent.com/10611605/311517463-57160d8b-3eb3-4ac9-a753-1e03159a89d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwODc1ODEsIm5iZiI6MTcxMDA4NzI4MSwicGF0aCI6Ii8xMDYxMTYwNS8zMTE1MTc0NjMtNTcxNjBkOGItM2ViMy00YWM5LWE3NTMtMWUwMzE1OWE4OWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDE2MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMDY4NWRjNjNiYTk1MzNhYmIwYjM1NmFjZmYwNjViNTk5YzVmMjZkODUzNjM3ZTI1OGM2OTRiZWM5YjA5NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4pl0eSNA_0BXZOnBoxe60S91sFWaYrQorOxRtxqNX8Y)
> 
> 还是尊重一下别人的成果，不要轻易去下定论， @Aira-Sakuranomiya 的想法是好的，然后这个😂其实我没出过稿子，毕竟出稿子沉没成本有点高，基本是想到哪里改哪里（源代码上直接上手改）,也没有很好的规划

想到哪改到哪这不好吧，如果我放下尊重说难听点的，现在真的整个 UI 原本完好的一致性被毁了......

**Comment by MystiPanda** [comment]
我倒是觉得原本的界面异常混乱，现在的界面就是往一致化的方向在调整，整体全部使用扁平化的风格，也调整了许多不协调的细节。

**Comment by Aira-Sakuranomiya** [comment]
那就这样吧，我们审美差距太大了，之后有空我自己 fork。

**Comment by luowei729** [comment]
> 各位，我觉得让gpt4评判一下2个UI哪个美观

下面的是 gemini的回答
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/10611605/1f94d379-4a80-46bd-a3be-4636f5289436)

**Comment by LNKLEO** [comment]
> 那就这样吧，我有些强迫症，我们的态度和审美差别太大了。
> 
> 之后有空我自己 fork。

老哥搞好之后ping我一下。这版UI。。。真的太割裂了。跟Windows XP倒是比较搭，感觉一下回到了07 08年那阵用的迅雷的感觉。
维护者还蜜汁自信，还扁平化。。。。这叫啥扁平化啊。。。。实在不行去apple store看看iPad/iPhone样机，学学啥叫扁平化也行啊。谁表示一下不如旧UI，直接就破防了还。。。。无语。。。

找替代去了，没有合适的替代就等老哥你的fork了

**Comment by MystiPanda** [comment]
那您来教教我什么才叫扁平化

**Comment by canoziia** [comment]
个人意见，新ui确实不好看，一个是背景颜色太脏，另外providers的数量用亮黄色根本看不见，建议减少亮黄色使用，把背景颜色色调调的偏蓝一点点。这个ui吓得我连夜装回旧版了

**Comment by MashiroYui** [comment]
个人感觉，确实丑+1

**Comment by shikkoku** [comment]
我选用单色图标的方案看上去挺好的，默认的圆形彩色图标还是比较难接受。
