### ISSUE TITLE
[BUG]无法启动clash verge

### ISSUE THREAD

**Issue by xy-cloud-cn** [clash-verge-rev/clash-verge-rev#561]
### Describe the bug

我也很迷惑这个bug，因为我找不到任何这个bug产生的原因
在今天1点左右，我启动了电脑，使用sharex的截图截了几张verge的图，并且关闭了verge，使用了约1小时之后，我关闭了电脑，此时我并没有更新verge的1.5.6版本，应该是1.5.4版本，当时还可以正常使用
在晚8点，我重新启动了电脑，发现verge没有主动弹出（我设置了开机自启动），尝试多次并重启电脑后，我来到github界面，发现有新版本，卸载并重装，但是仍然无法启动
后来我查看FAQ，尝试修复了webview2，但是仍然无法启动，但同时，我一直都可以正常启动其他tauri的程序
我尝试使用管理员启动也无效

在我尝试时，托盘并未出现verge图标，任务管理器无verge进程，尝试win7,win8兼容性模式均无法启动

2024/3/10 22:41 修正：我尝试了删除所有配置，仍然无法启动

### To Reproduce

无法复现，因为我到现在都没法正常启动

### Platform

Windows

### System Version

Windows 11 专业版 22631.3235

### Software Version

1.5.6

### Log

请问日志在哪，这个我不太清楚

**Comment by wonfen** [comment]
3个排查方向：

1.安装verge后，修改配置文件 C:\Users\你的用户名\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev\verge.yaml
把app_log_level: null修改为app_log_level: trace 然后启动verge进入log目录：
C:\Users\你的用户名\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev\log

2.尝试启动verge，进入windows的事件查看器(运行，输入 eventvwr )查看是否有verge启动失败的日志信息。

3.排查是否安装了ip guard之类的安全软件。

**Comment by xy-cloud-cn** [comment]
更新最新消息，更新到1.5.8版本仍无法启动

**Comment by xy-cloud-cn** [comment]
解决方法：安装KB5035853更新，使系统版本更新到22631.3296
