### ISSUE TITLE
[Feature]增加订阅页面列数设置

### ISSUE THREAD

**Issue by choi006** [clash-verge-rev/clash-verge-rev#565]
### Is your feature request related to a problem? Please describe.

名称过长时会显示省略号
希望能自定义列数
隔壁cfw固定2列

### Describe the solution you'd like

增加订阅页面列数设置

### Describe alternatives you've considered

宽度变大

**Comment by leic4u** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/32786903/13a87247-3e83-4818-818a-96dfeec65b27)

**Comment by choi006** [comment]
@leic4u 是订阅页面列数设置.不是代理页面
