### ISSUE TITLE
[Feature] 希望能直接编辑rule provider

### ISSUE THREAD

**Issue by MJRT** [clash-verge-rev/clash-verge-rev#567]
### Is your feature request related to a problem? Please describe.

-

### Describe the solution you'd like

类似clash for windows, 添加一个编辑按钮, 可以直接编辑rule provider, 保存并刷新. 现在想编辑的话只能手动找到文件进行编辑, 然后回到app刷新, 比较麻烦
![PixPin_2024-03-10_23-36-50](https://github.com/clash-verge-rev/clash-verge-rev/assets/17826582/baea7391-ef3a-4b55-afac-8036ebe62c67)
![PixPin_2024-03-10_23-41-58](https://github.com/clash-verge-rev/clash-verge-rev/assets/17826582/dbad9cfb-ad66-46ed-a197-c84a60de7242)

### Describe alternatives you've considered

-

**Comment by leic4u** [comment]
这样添加的随着 Rule provider 更新就没了，你是想实现添加自定义规则，并保存下来吧？

我想你可能是需要添加规则的功能？

类似 CFW 的这个：

https://docs.gtk.pw/contents/ui/profiles/rules.html
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/32786903/03ff2bf8-93be-42e3-8588-3fefad53f6d0)

**Comment by MJRT** [comment]
> 这样添加的随着 Rule provider 更新就没了，你是想实现添加自定义规则，并保存下来吧？
> 
> 我想你可能是需要添加规则的功能？
> 
> 类似 CFW 的这个：
> 

本地添加的rule provider 不会随着订阅更新消失的, 比如在merge或script 中添加的rule provider.
我想要的就是cfw中provider 的编辑功能.

**Comment by leic4u** [comment]
> > 这样添加的随着 Rule provider 更新就没了，你是想实现添加自定义规则，并保存下来吧？
> > 我想你可能是需要添加规则的功能？
> > 类似 CFW 的这个：
> 
> 本地添加的rule provider 不会随着订阅更新消失的, 比如在merge或script 中添加的rule provider. 我想要的就是cfw中provider 的编辑功能.

rule provider 不会消失，但你在这个 provider 里面添加的 rules 会被更新没了。这个更新是覆盖式更新。

你想保留你自己添加的规则，不应该在 provider 里面添加，而是在 provider 外添加。类似于这样：

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/32786903/918685f2-fc5d-4881-8eea-74345a549e82)

**Comment by MJRT** [comment]
> > > 这样添加的随着 Rule provider 更新就没了，你是想实现添加自定义规则，并保存下来吧？
> > > 我想你可能是需要添加规则的功能？
> > > 类似 CFW 的这个：
> > 
> > 
> > 本地添加的rule provider 不会随着订阅更新消失的, 比如在merge或script 中添加的rule provider. 我想要的就是cfw中provider 的编辑功能.
> 
> rule provider 不会消失，但你在这个 provider 里面添加的 rules 会被更新没了。这个更新是覆盖式更新。
> 
> 你想保留你自己添加的规则，不应该在 provider 里面添加，而是在 provider 外添加。类似于这样：
> 

provider里面的rules 也不会消失, 因为它们也都是本地的, 这个已经在clash verger 和 cfw 都验证过了.

**Comment by choi006** [comment]
> 这样添加的随着 Rule provider 更新就没了，你是想实现添加自定义规则，并保存下来吧？
> 
> 我想你可能是需要添加规则的功能？
> 
> 类似 CFW 的这个：
> 
> https://docs.gtk.pw/contents/ui/profiles/rules.html ![image](https://private-user-images.githubusercontent.com/32786903/313454549-03ff2bf8-93be-42e3-8588-3fefad53f6d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NjkwNzIsIm5iZiI6MTcxMDY2ODc3MiwicGF0aCI6Ii8zMjc4NjkwMy8zMTM0NTQ1NDktMDNmZjJiZjgtOTNiZS00MmUzLTg1ODgtM2ZlZmFkNTNmNmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDA5NDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMWRiNjMzOTU5ZjVhZjMyYWE5MmEzYzc0N2RmNDBiYTc3YmM0Y2E0MDYxNzljMGI1MWFmMWRhYTZhOTRhNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FRcsT0Z54RSfymVJNudVmQbVc7hHllzcFZ_S4K3Uhzk)

我的cfw怎么没有这个页面。这个页面显示的是订阅😶

**Comment by leic4u** [comment]
> provider里面的rules 也不会消失, 因为它们也都是本地的, 这个已经在clash verger 和 cfw 都验证过了.
> 
> 你应该用append-rule-providers或者prepend-rule-providers 处理它们

实测了下，直接在 Provider 里添加的自定义规则，是会被更新掉的。

如果写到 prepend-rules 或者 append-rules 里，那改 provider 的意义是啥？

**Comment by leic4u** [comment]
> 我的cfw怎么没有这个页面。这个页面显示的是订阅😶

Clash For Windows 才行，对订阅点右键有选项可以管理规则。

**Comment by MJRT** [comment]
> > provider里面的rules 也不会消失, 因为它们也都是本地的, 这个已经在clash verger 和 cfw 都验证过了.
> > 你应该用append-rule-providers或者prepend-rule-providers 处理它们
> 
> 实测了下，直接在 Provider 里添加的自定义规则，是会被更新掉的。
> 
> 如果写到 prepend-rules 或者 append-rules 里，那改 provider 的意义是啥？

😅我一直都在用的, 你配置是不是直接修改订阅的配置了?  cfw要用parsers去mix in, clash verge 要用 merge或者script配置. 具体参考下双方的文档吧,
[cfw-wiki](https://docs.gtk.pw/contents/parser.html#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E9%A2%84%E5%A4%84%E7%90%86)
[clash-verge-wiki](https://clash-verge-rev.github.io/guide.html#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86)

而且你这个截图也有问题不是在rule里面改, cfw是在provider里面改

**Comment by leic4u** [comment]
> > 实测了下，直接在 Provider 里添加的自定义规则，是会被更新掉的。
> > 如果写到 prepend-rules 或者 append-rules 里，那改 provider 的意义是啥？
> 
> 😅我一直都在用的, 你配置是不是直接修改订阅的配置了? cfw要用parsers去mix in, clash verge 要用 merge或者script配置. 具体参考下双方的文档吧
> 
> 而且你这个截图也有问题不是在rule里面改, cfw是在provider里面改

我知道你的意思，我也知道使用  prepend-rules 或者 append-rules 可以实现对主配置文件的修改。

我的问题是既然你想直接在 provider 里修改规则，但是 provider 又会在下次更新时被远程文件覆盖掉，那你修改 provider 的规则干啥？

另外我截图的那个是放的修改 profile 的规则的界面，不是修改 provider 的规则，界面不一样。
