### ISSUE TITLE
[Feature]希望可以加一个订阅分享的二维码功能，方便在手机端直接扫码添加订阅

### ISSUE THREAD

**Issue by flylj999** [clash-verge-rev/clash-verge-rev#569]
### Is your feature request related to a problem? Please describe.

方便在手机端直接扫码添加订阅

### Describe the solution you'd like

希望可以加一个订阅分享的二维码功能

### Describe alternatives you've considered

希望可以加一个订阅分享的二维码功能

**Comment by MystiPanda** [comment]
哪个 App 支持扫码添加，格式是什么样的🧐

**Comment by wonfen** [comment]
我们又没有手机app。不理解你这个需求的意义何在？

**Comment by iTanken** [comment]
> 哪个 App 支持扫码添加，格式是什么样的🧐

他的意思可能是用这种格式的内容生成二维码吧：

```
clash://install-config?url=https%3A%2F%2Fexample.com
```

**Comment by dongchengjie** [comment]
现在的手机端用的多数是Clash.Meta吧，这个软件也不支持扫码啊

**Comment by almostless** [comment]
估计是想小火箭那样的，支持扫码和url分享
