### ISSUE TITLE
为何么这么占内存啊

### ISSUE THREAD

**Issue by zxyacg** [clash-verge-rev/clash-verge-rev#571]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/76837288/e14f0d8a-15c5-4dfb-98b3-2930ad84e14c)

### Describe the solution you'd like

。

### Describe alternatives you've considered

。

### Additional context

。

**Comment by xy-cloud-cn** [comment]
这还算占内存...你开一个网页比这还多

**Comment by dragove** [comment]
因为图形界面是基于webview实现的，算是一个网页，webview 相比浏览器内存占用会少点，但是依然摆脱不了要运行一个能渲染 html/css 的引擎以及一个js解释器。

你这个内存占用只在打开界面时会占用这么多，关闭窗口，只有托盘时内存占用是很小的。

**Comment by dongchengjie** [comment]
因为这是Tauri写的，比Electron已经好不少了
你可以搜一下你电脑上有多少swiftshader目录，什么迅雷、微信、飞书、QQ、Typora都是Electron写的，浏览器内核套壳，打开就是开了一个网页😅
