### ISSUE TITLE
[Feature] 希望可以增加一个导出导入测试连接的功能, 方便不同机器使用

### ISSUE THREAD

**Issue by seth-shi** [clash-verge-rev/clash-verge-rev#572]
### Is your feature request related to a problem? Please describe.

[Feature] 希望可以增加一个导出导入测试连接的功能, 方便不同机器使用

### Describe the solution you'd like

[Feature] 希望可以增加一个导出导入测试连接的功能, 方便不同机器使用

### Describe alternatives you've considered

[Feature] 希望可以增加一个导出导入测试连接的功能, 方便不同机器使用

### Additional context

[Feature] 希望可以增加一个导出导入测试连接的功能, 方便不同机器使用

**Comment by wonfen** [comment]
软件越来越复杂，功能越来越冗余。
自己动手丰衣足食
