### ISSUE TITLE
1.56首次安装打开会卡住无法操作点击[BUG]

### ISSUE THREAD

**Issue by wwwwkl77** [clash-verge-rev/clash-verge-rev#573]
### Describe the bug

重新退出重新打开就好了，希望改进一下

### To Reproduce

安装 第一次打开软件

### Platform

Windows

### System Version

win10

### Software Version

1.56

**Comment by lydlovezjr** [comment]
同样的bug,我也遇到了,win10 ltsc系统

**Comment by wonfen** [comment]
修改GUI日志显示级别，用于debug
打开软件clash verge菜单“设置”-> 拉倒最下面点开“应用目录”，文本编辑器编辑verge.yaml文件，把app_log_level: 修改为 app_log_level: trace

**Comment by lucienshawls** [comment]
> 修改GUI日志显示级别，用于debug 打开软件clash verge菜单“设置”-> 拉倒最下面点开“应用目录”，文本编辑器编辑verge.yaml文件，把app_log_level: 修改为 app_log_level: trace

我也遇到了这个问题。我使用的Windows 11系统用的setup安装（上午安装的，当时用的1.5.7版本），下午我将改软件推荐给了同学，他用的Windows10并使用了便携版软件。我们都遇到了同样的问题，第一次启动程序后，无法与窗口的任何元素交互，右上角的关闭按钮也点不了，只能在任务栏右键关闭窗口，再打开时就正常使用。我下午更新了软件，也重启过电脑，问题没有再次出现。

而您建议的修改日志级别可能难以做到，这是因为第一次打开软件的时候无法与软件交互，无法调整设置；第二次及以后打开软件时问题消失，日志也将不能提示问题所在。

目前我们没有尝试过卸载软件重新安装，所以不知道这个问题是否在每次安装时都会出现，还是每个设备上只出现一次。

**Comment by novaeye** [comment]
> > 修改GUI日志显示级别，用于debug 打开软件clash verge菜单“设置”-> 拉倒最下面点开“应用目录”，文本编辑器编辑verge.yaml文件，把app_log_level: 修改为 app_log_level: trace
> 
> 我也遇到了这个问题。我使用的Windows 11系统用的setup安装（上午安装的，当时用的1.5.7版本），下午我将改软件推荐给了同学，他用的Windows10并使用了便携版软件。我们都遇到了同样的问题，第一次启动程序后，无法与窗口的任何元素交互，右上角的关闭按钮也点不了，只能在任务栏右键关闭窗口，再打开时就正常使用。我下午更新了软件，也重启过电脑，问题没有再次出现。
> 
> 而您建议的修改日志级别可能难以做到，这是因为第一次打开软件的时候无法与软件交互，无法调整设置；第二次及以后打开软件时问题消失，日志也将不能提示问题所在。
> 
> 目前我们没有尝试过卸载软件重新安装，所以不知道这个问题是否在每次安装时都会出现，还是每个设备上只出现一次。

这个问题看上去是因为 verge.yaml 配置文件中的 app_log_level 配置项的初始值是 null 导致的, 这个文件的位置在安装目录下的 .config/io.github.clash-verge-rev.clash-verge-rev/ 子目录中, 文本编辑器打开手工把 app_log_level 的值从 null 改成 info/debug/trace 中的一个值就可以了.

**Comment by htyjswf** [comment]
> > > 修改GUI日志显示级别，用于debug 打开软件clash verge菜单“设置”-> 拉倒最下面点开“应用目录”，文本编辑器编辑verge.yaml文件，把app_log_level: 修改为 app_log_level: trace
> > 
> > 
> > 我也遇到了这个问题。我使用的Windows 11系统用的setup安装（上午安装的，当时用的1.5.7版本），下午我将改软件推荐给了同学，他用的Windows10并使用了便携版软件。我们都遇到了同样的问题，第一次启动程序后，无法与窗口的任何元素交互，右上角的关闭按钮也点不了，只能在任务栏右键关闭窗口，再打开时就正常使用。我下午更新了软件，也重启过电脑，问题没有再次出现。
> > 而您建议的修改日志级别可能难以做到，这是因为第一次打开软件的时候无法与软件交互，无法调整设置；第二次及以后打开软件时问题消失，日志也将不能提示问题所在。
> > 目前我们没有尝试过卸载软件重新安装，所以不知道这个问题是否在每次安装时都会出现，还是每个设备上只出现一次。
> 
> 这个问题看上去是因为 verge.yaml 配置文件中的 app_log_level 配置项的初始值是 null 导致的, 这个文件的位置在安装目录下的 .config/io.github.clash-verge-rev.clash-verge-rev/ 子目录中, 文本编辑器打开手工把 app_log_level 的值从 null 改成 info/debug/trace 中的一个值就可以了.

改成info,trace，都试了，还是不行

# Clash Verge Config

app_singleton_port: null
app_log_level: trace
language: zh
theme_mode: dark
tray_event: null
env_type: cmd
start_page: /
startup_script: null
traffic_graph: true
enable_memory_usage: true
………………

**Comment by htyjswf** [comment]
救命，软件主界面只能双击放大全屏或还原大小，啥也点击不了
卸载，重启，都不行
任务栏右下角右键是可以
但是不能导入机场链接了

**Comment by wonfen** [comment]
已稳定复现。正在查找原因。

**Comment by wonfen** [comment]
1.5.9已经修复。
