### ISSUE TITLE
[Feature]托盘图标更改应该支持ico图标文件

### ISSUE THREAD

**Issue by din1028** [clash-verge-rev/clash-verge-rev#574]
### Is your feature request related to a problem? Please describe.

托盘图标更改应该支持ico图标文件，请求支持！

### Describe the solution you'd like

托盘图标更改应该支持ico图标文件，请求支持！

### Describe alternatives you've considered

托盘图标更改应该支持ico图标文件，请求支持！

**Comment by leic4u** [comment]
你可以试试这个功能是否满足你的需求。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/32786903/d5e94c56-b71a-4d17-ae02-f890fb19758f)

**Comment by dongchengjie** [comment]
> 你可以试试这个功能是否满足你的需求。

他指的是这个意思，只能选择png类型的图片
<img width="616" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/da5e17c4-a007-4c19-bb17-28d5de22d866">
