### ISSUE TITLE
[BUG]linux下tun模式不生效

### ISSUE THREAD

**Issue by Joackk** [clash-verge-rev/clash-verge-rev#575]
### Describe the bug

再linux下，是用系统代理正常，但是用tun模式没有生效

### To Reproduce

运行clash，试用tun模式

### Platform

Linux

### System Version

kali2022

### Software Version

1.5.6

### Additional Information

是需要什么特殊设置吗？用root启动会无法正常使用

**Comment by Joackk** [comment]
给内核授权会提示这个
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/45162558/5dc38bcf-1d35-4843-8d2b-9735e4ae5b95)

**Comment by MystiPanda** [comment]
不要用 appimage

**Comment by Joackk** [comment]
> 不要用 appimage

那linux下用哪个？deb吗？

**Comment by MystiPanda** [comment]
是的

**Comment by Joackk** [comment]
> 是的

感谢，用deb倒是可以正常授权
