### ISSUE TITLE
[Feature]希望可以在状态栏显示实时速度, 如clash meta或者clashx一样

### ISSUE THREAD

**Issue by zhangfurun** [clash-verge-rev/clash-verge-rev#576]
### Is your feature request related to a problem? Please describe.

rt

### Describe the solution you'd like

rt

### Describe alternatives you've considered

rt

**Comment by Felix8029** [comment]
+1

**Comment by wuai1024** [comment]
+1

**Comment by MystiPanda** [comment]
并不是核心功能，而且Win和Linux无法实现，不考虑实现。
