### ISSUE TITLE
[BUG]error sending request for url (http://127.0.0.1:9097/configs): error trying to connect: tcp connect error: Connection refused (os error 61)

### ISSUE THREAD

**Issue by boa-z** [clash-verge-rev/clash-verge-rev#577]
### Describe the bug

error sending request for url (http://127.0.0.1:9097/configs): error trying to connect: tcp connect error:
Connection refused (os error 61)
This error happened after update to 1.5.7.
I can't choose to subscribe to a file or even modify the settings.

### To Reproduce

I have no idea.

### Platform

MacOS

### System Version

macOS 14.4

### Software Version

1.5.7

### Log

<img width="316" alt="Screenshot 2024-03-11 at 17 44 35" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/42885162/8ea4a1bf-5a8f-418e-9646-0444580f6cba">

**Comment by molamooo** [comment]
Same issue on 1.5.7. Downgrade to 1.5.6 may avoid this issue.

**Comment by DanielZWX** [comment]
me too

**Comment by JinYuCai21** [comment]
Same issue

**Comment by ounasi** [comment]
same，mac os

**Comment by ryanhel** [comment]
Deactivate the TUN mode and then restart. It's beneficial on my MAC.

**Comment by MystiPanda** [comment]
修复了，请下载 alpha 版本尝试

**Comment by Tanselc** [comment]
What has been updated? I downgraded the version and it still gives me an error, but the error message is empty.

**Comment by LANchangrong** [comment]
me too.

**Comment by zhyine** [comment]
same issue

**Comment by MystiPanda** [comment]
别再发same issue了，有什么用，说了下载alpha版本测试你测试了吗？人家上面给你的解决办法你尝试了吗？你跟着回复一个能给我提供什么有效的排查信息吗？

**Comment by DanielZWX** [comment]
> 别再发same issue了，有什么用，说了下载alpha版本测试你测试了吗？人家上面给你的解决办法你尝试了吗？你跟着回复一个same issue能给我提供什么有效的排查信息吗？

下载试了alpha版本（点击安装覆盖），解决了。

**Comment by zhyine** [comment]
> @boa-z @DanielZWX @molamooo @JinYuCai21 @Tanselc @ounasi @ryanhel try this:
> 
> 1. backup your remote files and etc.
> 2. download the latest version from github releases
> 3. quit verge
> 4. execute this in your terminal, it will completely remove the old one on your mac:
> 
> ```shell
> sudo rm -rf /Applications/Clash\ Verge.app ~/Library/Application Support/io.github.clash-verge-rev.clash-verge-rev ~/Library/Caches/io.github.clash-verge-rev.clash-verge-rev ~/Library/Preferences/io.github.clash-verge-rev.clash-verge-rev.plist ~/Library/Saved Application State/io.github.clash-verge-rev.clash-verge-rev.savedState ~/Library/WebKit/io.github.clash-verge-rev.clash-verge-rev
> ```
> 
> 5. install the new one

Solved by this. So sorry for taking your time.
