### ISSUE TITLE
[Feature]请求作者添加一个，版本更新提醒开关设置功能

### ISSUE THREAD

**Issue by dreampowers** [clash-verge-rev/clash-verge-rev#58]
毫无疑问1.4.2是一个很完美的版本，各方面很好没有什么问题，但是这个强制更新让人很不舒服，就像以前的clash每次都在头部提醒更新，让人挺不舒服的，作为个软件，他不需要经常性的更新，好用就行了，希望作者能加入一个更新提醒开关设置，而不是在头部强制提醒所有人更新！希望作者能考虑下加入这个功能，太多人需要这个关闭更新功能了，或者设置个默认不提示更好啊......

**Comment by MystiPanda** [comment]
现在的更新提醒也不是强提醒吧

**Comment by dreampowers** [comment]
> 现在的更新提醒也不是强提醒吧

现在会在头部猫咪哪里出现醒目红色NEWS提示啊..............，和以前的clash几乎差不多...好多人特意去去除更新.......有些版本好用，不想升级，不想被强迫看到更新提醒..........，，出个更新提醒开关吧大神们，不要直接有新版本就直接提示.....希望能加入开关，跪谢了！！！

**Comment by wonfen** [comment]
保持更新是软件使用的基本习惯，请随时保持更新。
