### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 91qxs** [clash-verge-rev/clash-verge-rev#581]
### Describe the bug

昨天晚上更新了都还能用，今天晚上就打不开了，更新了1.5.7还是打不开，右下角出现图标几秒钟自动就消失了

### To Reproduce

反复尝试也没用，重启电脑还是无法打开

### Platform

Windows

### System Version

19045.4046

### Software Version

1.5.7

**Comment by wonfen** [comment]
日志？

**Comment by 91qxs** [comment]
已解决问题

wonfen ***@***.***> 于 2024年3月12日周二 05:28写道：
