### ISSUE TITLE
1.5.7的图标没有之前的好看

### ISSUE THREAD

**Issue by lxtx528** [clash-verge-rev/clash-verge-rev#582]
### Is your feature request related to a problem? Please describe.

希望能换回上个版本的图标

### Describe the solution you'd like

希望能换回上个版本的图标。

### Describe alternatives you've considered

希望能换回上个版本的图标。

### Additional context

谢谢

**Comment by MystiPanda** [comment]
界面设置选择彩色图标

**Comment by lxtx528** [comment]
收到

MystiPanda ***@***.***> 于 2024年3月11日周一 22:40写道：
