### ISSUE TITLE
[BUG]占用内存过大

### ISSUE THREAD

**Issue by gxggxl** [clash-verge-rev/clash-verge-rev#583]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/41374599/e8418ee1-4f7c-4d08-8689-463dbeed8c19)

### To Reproduce

-

### Platform

MacOS

### System Version

12.6.2

### Software Version

v1.5.6

**Comment by wonfen** [comment]
罕见故障，重启软件。
