### ISSUE TITLE
[BUG] 选择静默模式自启动时，仍然弹出程序界面。

### ISSUE THREAD

**Issue by liuhl666** [clash-verge-rev/clash-verge-rev#584]
### Describe the bug

选择静默模式自启动时，在系统重启后仍然弹出程序界面。

### To Reproduce

选择自动启动，选择静默启动，重启操作系统，本软件启动，但是会弹出界面。

### Platform

Windows

### System Version

Windows 11 专业版 22631.3235

### Software Version

所有版本

**Comment by CyunNaam** [comment]
我也有同样的问题，Windows 11家庭版

**Comment by MystiPanda** [comment]
- #423
- #424
- #548

**Comment by win2333** [comment]
同样的问题 WIN10家庭版
版本V1.5.8 问题依然存在

**Comment by MystiPanda** [comment]
看回复好不好，我说我修了吗，我不会修的，只能你手动干预，不想看那你就放着吧，看他啥时候能好

**Comment by liuhl666** [comment]
在任务管理器里去掉一个启动项就行了。

**Comment by liuhl666** [comment]
同志们，在任务管理器里去掉一个启动项就可以了。
