### ISSUE TITLE
[BUG]winPC使用电脑自带的LTE网络的tun模式无法连接网络

### ISSUE THREAD

**Issue by xingbyte** [clash-verge-rev/clash-verge-rev#587]
### Describe the bug

winPC使用电脑自带的LTE网络，tun模式无法连接网络，但是用手机热点没有问题，网卡是intel xmm 7560R+ LTE-A pro ，不知道这个算不算bug，已经尝试过重装驱动，共享网络，更改dns，都不行。

### To Reproduce

不知道其他LTE网卡会不会有这个问题。

### Platform

Windows

### System Version

win11 23H2

### Software Version

1.5.6

**Comment by wonfen** [comment]
没有测试条件，需要更多信息。
尝试打开服务模式，用管理员模式运行软件等等。
