### ISSUE TITLE
[BUG] 是不是不能手动更新GeoData？

### ISSUE THREAD

**Issue by liuhl666** [clash-verge-rev/clash-verge-rev#588]
### Describe the bug

[REST-API] update GEO databases failed: can't save MMDB database file: open C:\Users\liuhl\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev/Country.mmdb: The requested operation cannot be performed on a file with a user-mapped section open.

### To Reproduce

在设置里点击“更新 GeoData”后，日志里打印错误：
[REST-API] update GEO databases failed: can't save MMDB database file: open C:\Users\liuhl\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev/Country.mmdb: The requested operation cannot be performed on a file with a user-mapped section open.

### Platform

Windows

### System Version

Windows 11 专业版 22631.3235

### Software Version

1.5.7

**Comment by MystiPanda** [comment]
软件内的按钮也是通过RESTFUL API来更新的，alpha内核应该已经修复了这个问题。
