### ISSUE TITLE
[BUG] 在主界面切换为连接分页后，关闭窗口，从托盘点击重新打开主界面，会默认为代理分页

### ISSUE THREAD

**Issue by Caligogo** [clash-verge-rev/clash-verge-rev#59]
RT。
且切换分页的刷新动画略显冗余。
日志的部分显示字符缺失，如：
[33mWARN[0m[2023-12-04T16:24:13.7627353+08:00]TO
use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+

**Comment by wonfen** [comment]
动画不挺好看么....
`在主界面切换为连接分页后，关闭窗口，从托盘点击重新打开主界面，会默认为代理分页`
应该之前就是这样设计的。
字符缺失问题还在研究。

**Comment by Caligogo** [comment]
> 动画不挺好看么.... `在主界面切换为连接分页后，关闭窗口，从托盘点击重新打开主界面，会默认为代理分页` 应该之前就是这样设计的。 字符缺失问题还在研究。

目前的动画时长略久，会有不顺畅的感觉。（个人观感）
我是刚换的目前版本的verge，以前不是这样设计的。

**Comment by MystiPanda** [comment]
动画砍了

关闭窗口后再打开回到主页是正常行为
