### ISSUE TITLE
[Feature] 希望在mac系统能够支持cmd + tab切换到clash-verge-dev应用

### ISSUE THREAD

**Issue by sunjiabin17** [clash-verge-rev/clash-verge-rev#592]
### Is your feature request related to a problem? Please describe.

cmd + tab切换app不能切换到clash-verge-dev

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by raymao9** [comment]
同求，目前只能暂时用设置热键解决，毕竟它也不在 dock 显示，每次只能到状态栏点击打开主窗口

**Comment by MystiPanda** [comment]
请下载alpha版本测试

**Comment by raymao9** [comment]
> 请下载alpha版本测试

下载了 alpha 1.5.8，有 dock 图标了，能够 Tab 切换，不过要是点击 X 关闭窗口的话，再次点击 dock 图标或者 Tab 切换就不能显示了，但是在 dock 图标右键选择隐藏的话，就不影响，希望 X 的动作也可以 = 隐藏窗口。辛苦谢谢开发者愿意考虑此需求。

**Comment by MystiPanda** [comment]
其他平台都是关闭窗口，为什么Mac这么特殊
