### ISSUE TITLE
[Feature] Linux 下 tun模式的开启的简化

### ISSUE THREAD

**Issue by Mixlining** [clash-verge-rev/clash-verge-rev#597]
### Is your feature request related to a problem? Please describe.

[前提] 已经在面板中对内核授权
在ubuntu开启tun 模式时,每次都会弹出3次授权页面,授权进行dns(还有另外两个操作,忘了具体名字了)操作.

### Describe the solution you'd like

能否跟内核一下,实现一次授权,后续能够直接点击开启tun?而不是每次开启tun都需要输入3次密码?

### Describe alternatives you've considered

或许对clash verge本身的运行文件进行永久提权可以解决?(不太懂这方面的知识)

**Comment by wonfen** [comment]
可以设置免密，具体方法自行google

**Comment by ilovetaimei** [comment]
怎么

> > 可以设置免密，具体方法自行google
> 
> 您好,请问方便提供一下关键词或者相关的链接吗?(搜索 clash 免密 tun等关键词没有找到)以及提权应该对哪个执行文件提权免密?

找到方法了吗

**Comment by xishang0128** [comment]
@ilovetaimei 编辑sudores文件,将用户组设置为nopasswd: all
