### ISSUE TITLE
提问：用clashvg之后Microsoft store打不开怎么办？

### ISSUE THREAD

**Issue by talent0819** [clash-verge-rev/clash-verge-rev#599]
之前用的clash，有应用助手设置，最近换了vg，不知道是我没找到还是需要怎么样设置，希望大佬百忙之中抽空解答一下，3q。

**Comment by AquaSimulacra** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/98635189/c8796c5e-6f5c-4799-a66b-8d37ec56dd37)
使用这个工具
[enableLoopback.zip](https://github.com/clash-verge-rev/clash-verge-rev/files/14576169/enableLoopback.zip)
或者使用这个应用程序（两个方法用到的程序完全一样）

**Comment by talent0819** [comment]
> ![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/98635189/c8796c5e-6f5c-4799-a66b-8d37ec56dd37)
> 使用这个工具
> [enableLoopback.zip](https://github.com/clash-verge-rev/clash-verge-rev/files/14576169/enableLoopback.zip)
> 或者使用这个应用程序（两个方法用到的程序完全一样）
> 打开工具后全选并应用。

感谢大佬
