### ISSUE TITLE
[Feature] 通用CLASH訂閱格式的鏈接吊起此項目的CLASH VERGE

### ISSUE THREAD

**Issue by forjustice** [clash-verge-rev/clash-verge-rev#6]
**Describe the bug**
通用CLASH訂閱格式的鏈接在機場導入後無法吊起此項目的Windows CLASH VERGE

**To Reproduce**
1. 在機場網頁點擊導入（使用的是通用的clash://格式）
2. 網頁提示是否打開clash，選是
3. 但無法吊起此項目的Windows CLASH VERGE軟體（電腦未安裝除此外的其他翻牆軟體）

**Information**
- OS: Windows 11
- Clash Verge Version:1.4.0
- Clash Core:  自帶Clash Meta

**Comment by betaxab** [comment]
不是 BUG，是 feature request。Clash Verge 从始至终就没有链接唤醒功能，我倒是希望后继开发者能加入这个功能。
