### ISSUE TITLE
[BUG]订阅界面无法显示机场订阅的总计流量

### ISSUE THREAD

**Issue by istek** [clash-verge-rev/clash-verge-rev#60]
**Describe the bug**
订阅界面无法显示机场订阅的总计流量

**To Reproduce**

1. 点击 '订阅'
2. 粘贴 订阅链接 ，点击 导入 按钮
3. 订阅信息，仅显示已用流量，合计流量显示0b，我试着导入了三个不同的订阅链接，均如此。

**Expected behavior**
应该展示正确的 合计流量，而不是0b。

**Screenshots**
![1701679126280](https://github.com/clash-verge-rev/clash-verge-rev/assets/8424803/1c0d7759-c5ce-41b5-a651-6a1bd1e020cd)

**Information**

- OS: win 10
- Clash Verge Version: 1.4.2
- Clash Core: 1.17.0 clash meta

**Additional context**
无

**Comment by wonfen** [comment]
这边排查后并无问题，估计是你用的机场bug了。请换家机场试试。

**Comment by dycwuxing** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/44988562/eaf17e87-b9cb-462e-bf87-0efc741a363b)
我的多家机场也是,都不显示总量

**Comment by Caligogo** [comment]
> 这边排查后并无问题，估计是你用的机场bug了。请换家机场试试。

我本来也是正常的，但由于1.4.3的更新建议是卸载旧版、重新安装并导入配置。
所以，我照做后复现了这个问题。

**Comment by wonfen** [comment]
群里私聊给个机场订阅试试。

**Comment by wonfen** [comment]
用了lz给的订阅，无法复现。
