### ISSUE TITLE
[BUG]退出后重新打开报错

### ISSUE THREAD

**Issue by joeykini** [clash-verge-rev/clash-verge-rev#601]
### Describe the bug

error sending request for url(http://127.0.0.1:9097/configs):errortrying to connect: tcp connect error:Connection refused (os error 61)

### To Reproduce

退出后重新打开，提示报错

### Platform

MacOS

### System Version

14.4 m1

### Software Version

1.5.7

### Log

![WX20240313-100928@2x](https://github.com/clash-verge-rev/clash-verge-rev/assets/73977767/fc9388c7-cf72-4a82-ba82-528c8a9fa346)
![WX20240313-100944@2x](https://github.com/clash-verge-rev/clash-verge-rev/assets/73977767/5cc75d0d-78c0-45ed-9af5-e7b49e9e18df)
![WX20240313-100955@2x](https://github.com/clash-verge-rev/clash-verge-rev/assets/73977767/dbdd435b-9b31-4a34-94a6-4171fe54cd96)

**Comment by immadolf** [comment]
同样遇到了，无论是升级到 1.5.7，还是重新安装 1.5.7，都是这个现象

**Comment by wonfen** [comment]
使用最新版应该已经修复了

**Comment by immadolf** [comment]
> 使用最新版应该已经修复了

是的，升级到 1.5.8 后好了，谢谢
