### ISSUE TITLE
[Feature]界面UI能不能改回之前的小清新风

### ISSUE THREAD

**Issue by tyrantGXY** [clash-verge-rev/clash-verge-rev#602]
### Is your feature request related to a problem? Please describe.

新版本的UI突然浓眉大眼起来，有点无法接受啊。之前清新风格很好看啊

### Describe the solution you'd like

能不能改回之前的UI风格，或者延续之前的风格做修改

### Describe alternatives you've considered

血书求改回去

**Comment by mashirozx** [comment]
附议，果味太浓了

**Comment by wonfen** [comment]
不能。
