### ISSUE TITLE
[BUG]无法访问www.google.com

### ISSUE THREAD

**Issue by AkiZZZZZ** [clash-verge-rev/clash-verge-rev#604]
### Describe the bug

谷歌所有服务都能访问，gmail，play store什么全都正常，唯独www.google.com无法访问，日志内显示
`www.google.com:443 match IPCIDR(127.0.0.1/32) using REJECT`
![Snipaste_2024-03-13_12-01-37](https://github.com/clash-verge-rev/clash-verge-rev/assets/112164340/7f2c8c75-7ac4-4989-b122-6f6cf47b1493)

未修改过任何配置文件。

### To Reproduce

使用谷歌浏览器访问www.google.com

### Platform

Windows

### System Version

10

### Software Version

22H2

**Comment by wonfen** [comment]
问你的机场。
