### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rivheroius** [clash-verge-rev/clash-verge-rev#606]
### Describe the bug

![微信截图_20240313153332](https://github.com/clash-verge-rev/clash-verge-rev/assets/36510971/4189ffce-ed04-450e-b30c-450f3d6d8c24)

### To Reproduce

更新订阅就发生这样的情况

### Platform

Windows

### System Version

22631.3296

### Software Version

1.5.8

**Comment by wonfen** [comment]
一般重启电脑或者重新安装就好了

**Comment by wonfen** [comment]
无进一步反馈，关闭
