### ISSUE TITLE
[Feature]winget

### ISSUE THREAD

**Issue by kingyue737** [clash-verge-rev/clash-verge-rev#607]
### Is your feature request related to a problem? Please describe.

cfw 和 clash verge 都能从winget安装，非常的方便。
这个安装包是不是也考虑发布到winget呢？

### Describe the solution you'd like

ignore

### Describe alternatives you've considered

ignore

**Comment by dragove** [comment]
可以考虑使用 scoop 包管理器，比winget/chocolatey干净好用，唯一问题是搜索性能问题，可以安装 scoop-search 解决。clash-verge-rev 在 scoop-extras 仓库中可以找到

**Comment by MystiPanda** [comment]
这些包不都是社区在维护吗，需要使用的话自己去给 winget-pkg PR 不就好了，活都让我干了，我不得累死。scoop 的包也不是我在维护啊。

**Comment by kingyue737** [comment]
礼貌提一嘴可不可以而已，嘴那么臭干嘛...

**Comment by MystiPanda** [comment]
@kingyue737 ？
