### ISSUE TITLE
[BUG] MacOs14.4 无法打开系统代理

### ISSUE THREAD

**Issue by guanpeijia** [clash-verge-rev/clash-verge-rev#608]
### Describe the bug

<img width="800" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/31607259/018014c5-6e43-41c5-ba6b-951bee1e29ce">
<img width="800" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/31607259/59cd3e76-b340-47f2-b552-698b1f3327cd">
<img width="670" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/31607259/13d369a1-3d27-401b-9b49-4aab2eb683e3">

### To Reproduce

MacOs14.4 打开系统代理，测试可以访问，浏览器无法打开网页，打开网络可以看见并没有开启代理

### Platform

MacOS

### System Version

14.4 (23E214)

### Software Version

14.4 (23E214)

**Comment by wonfen** [comment]
之前是不是删除过网络配置？
这样会导致系统中出现两个网络名称；
已知不完善，将在后续改进

**Comment by guanpeijia** [comment]
> 之前是不是删除过网络配置？ 这样会导致系统中出现两个网络名称； 已知不完善，将在后续改进

好像删过一次，修改什么配置能打开代理吗？

**Comment by wonfen** [comment]
> > 之前是不是删除过网络配置？ 这样会导致系统中出现两个网络名称； 已知不完善，将在后续改进
> 
> 好像删过一次，修改什么配置能打开代理吗？

在网络设置下手动设置代理。
