### ISSUE TITLE
[BUG] Wayland 平台窗口边框显示错误

### ISSUE THREAD

**Issue by gvenusleo** [clash-verge-rev/clash-verge-rev#609]
### Describe the bug

新版本 v1.5.8 在使用 Wayland 协议的 Linux 电脑上，原生的窗口边框无法隐藏。建议添加一个开关，自定义是否使用原生窗口边框。

![屏幕截图_20240313_164518](https://github.com/clash-verge-rev/clash-verge-rev/assets/79075347/18741070-d416-44cb-b8ab-f93f7eaa6078)

### To Reproduce

使用基于 Wayland 显示协议的 Linux 系统。

### Platform

Linux

### System Version

KDE Neon 6.0

### Software Version

1.5.8

**Comment by MystiPanda** [comment]
tauri的隐藏标题栏在KDE Wayland下不生效，手动设置窗口规则就好了

**Comment by gvenusleo** [comment]
> tauri的隐藏标题栏在KDE Wayland下不生效，手动设置窗口规则就好了

那我手动设置吧！
