### ISSUE TITLE
[Feature] 开启Tun模式后，openvpn无法启动

### ISSUE THREAD

**Issue by wuai1024** [clash-verge-rev/clash-verge-rev#610]
### Is your feature request related to a problem? Please describe.

我在开启了Tun模式后，openvpn就直接断开连接了。

经查询资料发现openvpn也是使用的Tun网卡连接的。

### Describe the solution you'd like

我希望都能同时使用，互不影响。

### Describe alternatives you've considered

目前是关闭了Tun模式，改为了系统代理，openvpn才能正常使用

**Comment by MystiPanda** [comment]
@wuai1024 ？

**Comment by wuai1024** [comment]
@MystiPanda 就如上面描述的那样，我在clash-verge开启Tun模式后，openvpn-client 就断开了。

**Comment by lucienshawls** [comment]
是否存在抢网卡的情况？可以考虑手动为openvpn和clash-verge-rev分别指定不同的网卡；

是否存在循环代理的情况？可以考虑在clash-verge-rev中基于`PROCESS-NAME`的规则让openvpn的程序流量直连

**Comment by wuai1024** [comment]
应该是存在了抢网卡的行为，测试发现，这2个应用都是用最后那个tun网卡，一个先启动，另外一个就报错了。
