### ISSUE TITLE
[BUG]About the auto-configured DNS for system network adapter (like Wifi) when enabling tun mode on MacOS

### ISSUE THREAD

**Issue by ForgottenR** [clash-verge-rev/clash-verge-rev#611]
update: The specific problem i had can be resolved by using `dhcp://en0` as dns nameserver in a "merge" type profile. Closing the issue.

### Describe the bug

Currently the auto-configured dns for system network adapter is 223.5.5.5, which doesn't really make sense since this configuration will make requests not going through fake-ip at all. It also breaks custom merge/script which overrides dns configuration, such as custom dns servers to resolve internal domains.

### To Reproduce

enable the TUN mode

### Platform

MacOS

### System Version

14.3.1

### Software Version

1.5.8
(1.5.6 is fine)

**Comment by xishang0128** [comment]
The "tun" mode requires the configuration of an address within the tun routing range for proper DNS hijack. Therefore, a public DNS has been set up for hijacking purposes.

**Comment by xishang0128** [comment]
Most devices receive DNS servers from DHCP, and these servers are typically located at the router gateway with private addresses. This can prevent the proper hijacking of DNS in tun mode, resulting in difficulties in restoring domain names and preventing DNS pollution.

**Comment by ForgottenR** [comment]
> This won't affect the internal DNS of the software, as the internal DNS is controlled by the configuration file.

I used "system" for overwriting the tun dns to be able to resolve some internal domains of my company (using system instead of a static ip because I'm afraid it might be dynamic). It worked fine previously. This behaviour is now broken. Is there a way to make it work again? I assume recording the previous value(s) before setting the dns, and providing a special identifier/variable for the merge/script mode might do the work? I understand it may conflict with what format of dns clash.meta supports, but I'm think there can be a way around with something like a new scheme?

**Comment by ForgottenR** [comment]
> The "tun" mode requires the configuration of an address within the tun routing range for proper DNS hijack. Therefore, a public DNS has been set up for hijacking purposes.

BTW, thanks for the explanation, I see that this makes sense now. Although I still want a feature request as I described above.
