### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by botch6402** [clash-verge-rev/clash-verge-rev#613]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/156065390/7f995588-4d8f-46b4-bebf-0dc561dc533e)

https://www.virustotal.com/gui/file/5fdc6f3d150e1aed29121b06e8395cc14ae9b721c84abba4faa1710f3bd34ece

**Comment by wonfen** [comment]
误报，忽略即可
