### ISSUE TITLE
[Feature]建议不要将Windows TUN的虚拟网卡接口跃点数强制设置为0

### ISSUE THREAD

**Issue by AquaSimulacra** [clash-verge-rev/clash-verge-rev#614]
### Is your feature request related to a problem? Please describe.

笔记本开启虚拟网卡后wifi信号就不显示了

### Describe the solution you'd like

不要将Windows TUN的虚拟网卡接口跃点数强制设置为0

### Describe alternatives you've considered

/

**Comment by hahach** [comment]
把tun网卡的名字改成z开头的试一试？

**Comment by AquaSimulacra** [comment]
没用，每次一开机虚拟网卡就会重新创建。

**Comment by hahach** [comment]
> 没用，每次一开机虚拟网卡就会重新创建。

怎么可能没用，tun网卡的名字这是clash配置管理的东西。verge如果接管了tun的设置，就在设置里面的tun的设置相关里。

名字改成z开头后，显示优先级就会降低，影响显示无线网络了

**Comment by AquaSimulacra** [comment]
显示顺序不是看名字的好吗。。。

**Comment by hahach** [comment]
> 显示顺序不是看名字的好吗。。。

我不清楚你这个是不是和我说的一个问题。我回答的是，meta默认创建的tun网卡会显示为有线网络，从而使笔记本wifi显示优先级降低。
这个问题的我几个月前从meta的tg群里从某个管理员处获得的解答，并且我这里是有效的，改成z开头的名字，WiFi图标就会恢复显示。如果你的问题和我说的不是一回事，那你当我没说就是了

**Comment by dongchengjie** [comment]
你说的是图标变成小地球的吧？
这是clash使用fake-ip模式导致的，而微软的认为DNS被劫持了，所以认为没网
把连通性测试的域名排除就好了
```
dns:
  fake-ip-filter:
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
```

**Comment by AquaSimulacra** [comment]
> 你说的是图标变成小地球的吧？ 这是clash使用fake-ip模式导致的，而微软的认为DNS被劫持了，所以认为没网 把连通性测试的域名排除就好了
> 
> ```
> dns:
>   fake-ip-filter:
>     - '+.msftconnecttest.com'
>     - '+.msftncsi.com'
> ```

我不是这个意思
