### ISSUE TITLE
[Feature] 发布使用Appcontainer的msix版本

### ISSUE THREAD

**Issue by oppressor1761** [clash-verge-rev/clash-verge-rev#615]
### Is your feature request related to a problem? Please describe.

与传统exe包相比，.msix的[Appcontainer](https://learn.microsoft.com/en-us/windows/msix/msix-container) 在Windows上能提供系统隔离、权限管理等安全好处，希望能发布使用Appcontainer的msix版本。

### Describe the solution you'd like

直接[build](https://learn.microsoft.com/en-us/windows/msix/desktop/source-code-overview) MSIX 或把EXE[打包](https://learn.microsoft.com/en-us/windows/msix/packaging-tool/create-an-msix-overview)成MSIX，且设置为使用Appcontainer

### Describe alternatives you've considered

虚拟机、sandboxie plus等

**Comment by MystiPanda** [comment]
@oppressor1761 不考虑，tauri 内置的打包器只支持 msi 和 exe，msi 不支持 arm，应用内更新又不可能根据你安装的时候选择的包来确定下载哪个包，所以只能选择一个，只支持 exe
