### ISSUE TITLE
[BUG]日志无法更改等级的问题

### ISSUE THREAD

**Issue by Ardin963** [clash-verge-rev/clash-verge-rev#616]
### Describe the bug

配置文件是
log-level: error
设置中
日志等级：error

客户端日志界面还是日志：all

日志目录找日志文件，打开发现还是包含info信息

### To Reproduce

无论更改这几个为error，都不会生效，都是info等级的日志

### Platform

MacOS

### System Version

10.15.7

### Software Version

1.5.8

**Comment by Ardin963** [comment]
在杂项设置，app日志等级中更改为error之后日志文件不再有info部分信息
希望这几个设置日志等级的地方能够统一为一处

**Comment by MystiPanda** [comment]
内核设置部分的level对应修改你配置文件中的log-level，杂项设置中的level才是app控制 往文件里面写入的日志level，这是有区别的。

**Comment by Ardin963** [comment]
感觉可以把内核日志和app日志统一设置，或者放在相近的地方
