### ISSUE TITLE
[Feature]Linux/Debian部分界面文字模糊优化

### ISSUE THREAD

**Issue by Dragon-Lu** [clash-verge-rev/clash-verge-rev#617]
### Is your feature request related to a problem? Please describe.

部分界面的文字（如左侧选项卡）笔画较粗，影响美观，是字重太大了吗？同一界面的其他文字显示正常
软件版本v1.5.8  
Debian12 2560*1440@165Hz，200%缩放。GNOME 43.9，Wayland。

![2024-03-14_11-12](https://github.com/clash-verge-rev/clash-verge-rev/assets/51150060/4eebe241-b1b7-4b6a-9a6d-0ff4be2fab82)

### Describe the solution you'd like

希望调整字体让笔画细一点

### Describe alternatives you've considered

更改字重

**Comment by MystiPanda** [comment]
能系统字体使用的什么字体，你这个字体似乎对粗体很不友好

**Comment by MystiPanda** [comment]
应该还是你的设置问题，我使用 `Noto Sans CJK SC` 没有这个问题。

**Comment by Dragon-Lu** [comment]
> 这是因为每个程序中可以设置不同的默认字体，比如 Arial 或者 Tahoma，而这些字体的属性由 [fontconfig](https://wiki.archlinuxcn.org/wiki/Fontconfig) 控制，其使用顺序是据地区代码以 A-Z 字母表顺序成默认排序，由于 ja-JP 在 zh_{CN,HK,SG,TW} 之前，故优先显示日文字形。

查到了这个问题的说明，的确是我设置的问题，只安装简体中文的变体包解决了。非常感谢你的帮助！
