### ISSUE TITLE
[BUG]升级内核时报错 Permission Denied: mkdir /usr/bin/meta-update

### ISSUE THREAD

**Issue by kuonji-arisu** [clash-verge-rev/clash-verge-rev#618]
### Describe the bug

安装方式为aur中的clash-verge-rev-bin包
在切换到alpha内核后，点击升级内核，提示权限不足

建议在执行特权操作i时，可以像旁边的内核授权功能一样，弹出要求升级特权的密码输入窗口

### To Reproduce

1. 使用aur安装clash-verge-rev-bin
2. 切换到alpha内核
3. 点击升级内核

### Platform

Linux

### System Version

archlinux latest wayland

### Software Version

1.5.8

**Comment by jemselindol** [comment]
aur安装，升级也要用aur，用包管理器就贯彻到底
