### ISSUE TITLE
[Feature]关于一些更新的问题

### ISSUE THREAD

**Issue by ForestL18** [clash-verge-rev/clash-verge-rev#619]
### Is your feature request related to a problem? Please describe.

1.在关闭service mode的情况下，在GUI内更新内核会显示创建目录失败，这是因为权限不足导致的。想问下这是预期行为吗？如果是的话可以在更新的地方加一个tips（个人建议，开发者可以酌情选择）。

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/45709305/601fff1d-b2a9-4f91-b2b9-59ead6e05d2b)

2.在开启service mode的情况下，更新内核后，不管是重启还是直接退出GUI再打开，再任务管理器都可以看到会出现两个`clash-meta-alpha.exe`内核进程，这是否是由于旧版本内核进程未关闭的缘故（不能关闭或无法关闭）。

3.在更新GUI后，service mode会失效，需要手动重新安装，这是预期的行为吗？

### Describe the solution you'd like

开发者可以针对上述情况进行一些优化

### Describe alternatives you've considered

无

**Comment by wonfen** [comment]
无法复现，看下是不是权限问题。

**Comment by MystiPanda** [comment]
前两个确实存在，还没想好怎么解决，第三个不应该出现，我修了之后我这边没有再发生过。
