### ISSUE TITLE
关于静默启动功能失效[BUG]

### ISSUE THREAD

**Issue by Joseph-Hamilton** [clash-verge-rev/clash-verge-rev#620]
### Describe the bug

我打开了开机自启与静默启动, 起初一切正常, 但在一次更新后, 每次启动电脑Clash Verge的UI界面都会自动跳出. 我尝试过关闭静默启动再重新打开, 似乎并没有效果.

具体哪一次更新后出现这个问题我记得不太清楚, 但是那一次更新内容里有关于"静默启动"一项的更新, 奇怪的是之前我都没有问题, 在那一次更新后这一功能对我却一直失效了. 后来的几次更新也没有解决这个问题.

### To Reproduce

打开 开机自启 和 静默启动
重启电脑
软件UI界面自动跳出

### Platform

Windows

### System Version

Windows 11 23H2

### Software Version

1.5.8

### Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/82088930/36bdf3db-1683-4994-ae32-aa109efa1408)

**Comment by MystiPanda** [comment]
翻一翻issue
