### ISSUE TITLE
【BUG】intel的macos下无法显示可用节点

### ISSUE THREAD

**Issue by happyangel721** [clash-verge-rev/clash-verge-rev#624]
### Describe the bug

macos 10.15.7 下测试了1.5.3以后的所有版本，无法显示可用节点，如图
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/163412780/84dc704b-03a1-42c3-870c-d148796cb276)
在朋友机器上测试过高版本macos没有问题，1.3.8可以正常显示
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/163412780/b25e1900-118f-49bc-8a5a-4e11b9f20f9d)

### To Reproduce

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/163412780/926b4900-3980-4d57-9c45-fbca562e9b49)
切换全局，规则按钮也没有反应。

### Platform

MacOS

### System Version

macos 10.15.7

### Software Version

1.5.8

**Comment by xishang0128** [comment]
@happyangel721 请确保CPU支持AVX2,新内核在x86架构的编译是AMD64v3,所以需求AVX2

**Comment by wonfen** [comment]
截图看看日志

**Comment by happyangel721** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/163412780/114f8175-f730-4326-92a8-8f226d29c72d)
我想xishang0128说的是对的

> 截图看看日志
