### ISSUE TITLE
[Feature] 在更新页增加前往下载地址的[详情]按钮

### ISSUE THREAD

**Issue by CrayonSSR** [clash-verge-rev/clash-verge-rev#625]
## Is your feature request related to a problem? Please describe.

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/93774795/54b30149-96ef-4211-919a-b5e5030af935)

**出于解压即用，以及后续可以随时换安装位置考虑，我安装了`portable`版本。**

**显然`portable`的特性，让它比相比setup安装的版本，更新操作会显得冗余的多：**
```text
收到更新->打开浏览器->找到书签/输入网址->网页跳转->切换到releases地址->【下载安装】
```

## Describe the solution you'd like

**一般开源软件的更新弹窗，都会带有一个类似【详情】、【查看更多】之类的按钮。**

**功能设计为：点击会调用浏览器，跳转到releases页提示更新的那个包，一般是`releases/latest`**
<br>

## Describe alternatives you've considered

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/93774795/a43334f7-7333-4a5d-99cc-222173498807)

**我的想法草稿类似上图，在【更新弹窗】的底部加额外的跳转按钮**

**参考地址：** https://github.com/clash-verge-rev/clash-verge-rev/releases/latest

**Comment by choi006** [comment]
【设置】页面右上角有个github图标。你点一下就会跳转了
