### ISSUE TITLE
[Feature]希望可以为connection选项中添加更多的筛选方式

### ISSUE THREAD

**Issue by 123456qewret** [clash-verge-rev/clash-verge-rev#626]
### Is your feature request related to a problem? Please describe.

目前connection下筛选条件较少

### Describe the solution you'd like

![compare](https://github.com/clash-verge-rev/clash-verge-rev/assets/57819273/c47ff535-9236-43be-9217-d022d03476dc)
希望可以像CFW一样添加多种筛选条件。

### Describe alternatives you've considered

非常感谢！

**Comment by Paulgudring** [comment]
右上角选择另一个视图，在close all旁边

**Comment by lucienshawls** [comment]
目前cvr也可以进行筛选，可筛选的条件有12个。如果仍然觉得不够，你可以指出你额外需要的key，或许作者会加进来。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/82591976/d39c8a98-6e69-47ef-9f02-56483c2c527e)

**Comment by 123456qewret** [comment]
非常感谢您的解答，我已经找到了。
在我使用中发现，manage columns的操作并不会被保存。例如我关闭了source destination列，当我点击了左侧的代理，再返回这个界面，source destination列又被启用了。不知道是否为bug？
![manage](https://github.com/clash-verge-rev/clash-verge-rev/assets/57819273/0ca8e4ae-12c3-42ba-9c25-ec089072d684)

**Comment by 123456qewret** [comment]
> 目前cvr也可以进行筛选，可筛选的条件有12个。如果仍然觉得不够，你可以指出你额外需要的key，或许作者会加进来。 ![image](https://private-user-images.githubusercontent.com/82591976/313207942-d39c8a98-6e69-47ef-9f02-56483c2c527e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDk2NTMsIm5iZiI6MTcxMDUwOTM1MywicGF0aCI6Ii84MjU5MTk3Ni8zMTMyMDc5NDItZDM5YzhhOTgtNmU2OS00N2VmLTlmMDItNTY0ODNjMmM1MjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDEzMjkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZjUxYzM5ZTFmZmNjNjJkNzkyYjc5MzhiODM5NWE2OWYxZDY3ZGYyNDRjZGIwOTc1MGZlMDE0ODdiMGQwYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NUjmiBCvRUAnKIQ98_pAm5QlK0J7aT7RIDn-OVAa0I4)

谢谢，我找到了。希望未来可以对这些列进行手动排序。
