### ISSUE TITLE
[BUG]无论怎么退出，代理服务器拒绝连接！

### ISSUE THREAD

**Issue by martjay** [clash-verge-rev/clash-verge-rev#627]
### Describe the bug

代理服务器拒绝连接

连接到 www.zhihu.com 时发生错误。

    请检查浏览器的代理服务器设置是否正确。
    请联系您的网络管理员以确认代理服务器工作正常。

### To Reproduce

在上一个版本并没有这个问题，现在托盘区图标右键取消系统代理没有用，选到直连再取消系统代理也没用，退出clash软件直接联网失败，所有网站都上不去，我快疯了！求解决~

### Platform

Windows

### System Version

Win11

### Software Version

1.5.8

**Comment by martjay** [comment]
不对劲，上一个安装版也有这个问题，我在1.5.8安装版前装的是便携版，因为不给我更新换到了安装版，1.5.7也有这个问题

**Comment by martjay** [comment]
忽然又好了，我发现问题是这个，前面这两个东西没有同步进行，估计就是这问题，反应慢了还是怎么的，但是我的电脑属于中高配。

![111111](https://github.com/clash-verge-rev/clash-verge-rev/assets/44982189/033d72e3-519e-49d3-aa26-3e10029ad20e)
![222222](https://github.com/clash-verge-rev/clash-verge-rev/assets/44982189/104ade11-def4-40b2-abe1-64ee801871fd)

**Comment by wonfen** [comment]
检查下端口，默认应该是7897

**Comment by raymao9** [comment]
Mac 上有一样的问题，无论什么模式、有没有关闭系统代理才退出 Clash，系统里的 Socks 代理/ 网页代理那些都还是打开的，我需要另外运行终端机命令解决
