### ISSUE TITLE
[BUG]Clash Verge Rev v1.5.8首次安装界面卡住无法点击

### ISSUE THREAD

**Issue by cheneyxx** [clash-verge-rev/clash-verge-rev#628]
### Describe the bug

Clash Verge Rev v1.5.8首次安装界面卡住无法点击 需退出重新启动恢复正常

### To Reproduce

win10 win11 系统安装都如此

### Platform

Windows

### System Version

win10 win11 专业版

### Software Version

1.5.8

**Comment by lucienshawls** [comment]
最近几个版本似乎一直都有这个bug：#573

话说，以前的版本有这个bug吗？

**Comment by cheneyxx** [comment]
以前的没有哈

Lucien Shaw ***@***.***> 于2024年3月15日周五 10:13写道：

**Comment by ttxz** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/12383775/e4fefe07-ca72-4dc1-9140-d04e93c59602)
不行，我的退出，重启系统，都不能点击，只有右侧启动的初始面板可以点击

**Comment by yunygo** [comment]
我退出应用，系统重启，也没用

**Comment by wonfen** [comment]
已稳定复现。正在查找原因。

**Comment by wonfen** [comment]
1.5.9已经修复。
