### ISSUE TITLE
[Feature] 建议新增自定义规则

### ISSUE THREAD

**Issue by Jason8996** [clash-verge-rev/clash-verge-rev#629]
### Is your feature request related to a problem? Please describe.

手动添加自定义规则，更新订阅后会失效。

### Describe the solution you'd like

建议在规则那一栏新增个自定义规则的功能，这样如果有些规则在默认的订阅配置文件里面不支持的话，我也可以自行进行手动新增，并且也可以在每次订阅更新后得以保留。不然每次我去改订阅后的配置文件，只要以更新订阅配置，原来自己手动添加上去的规则就又失效了，很烦！

### Describe alternatives you've considered

无

**Comment by dongchengjie** [comment]
新建Merge配置，CFW不也是这样的吗，只是那边放在右键diff了
<img width="639" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/a5a0a15a-a62c-4744-99ef-5a4c1b1532af">
