### ISSUE TITLE
[Feature]希望增加节点测速功能

### ISSUE THREAD

**Issue by TanxiangCode** [clash-verge-rev/clash-verge-rev#630]
### Is your feature request related to a problem? Please describe.

希望在测试延时旁边增加功能按钮，用于测试节点下载速度，可使用调用https://speed.cloudflare.com/ 的接口来测试

### Describe the solution you'd like

延时和下载速度同样重要

### Describe alternatives you've considered

无

**Comment by zhouxinghong** [comment]
其实这个功能只是噱头，根本没有什么卵用。如果你想要这个功能可以去用 V2rayN 它有您所想要的功能，但是都是花拳绣腿。clash 还是保持最核心最重要的延迟测试就很足够了，太多不重要的功能只会增加开发与维护成本且破坏软件功能的稳定性，得不偿失，因此请慎重考虑！

**Comment by dongchengjie** [comment]
https://speed.cloudflare.com/ 每天有**全网总流量限制**。[6](https://github.com/XIU2/CloudflareSpeedTest/issues/6) 、 [168](https://github.com/XIU2/CloudflareSpeedTest/issues/168)
每天晚些时候就不可用了，我都换成steam测速，真要测速最好还是自建😅
另外测速其实就图一乐真的
