### ISSUE TITLE
远程配置文件自动更新不工作

### ISSUE THREAD

**Issue by ldh1983** [clash-verge-rev/clash-verge-rev#631]
### Describe the bug

开启tun，远程配置文件并不会自动更新。实际上在之前的verge版本不是现在的verge-rev版本，我还专门用了几天系统代理模式，那几天配置文件也没有自动更新。clash-verge版本系统代理模式下远程配置文件能不能自动更新没有测试。

### To Reproduce

希望系统自动更新能够正常工作。比如每天自动更新一次，就可以知道上一天用掉了多少机场流量。目前要看流量的最新情况需要手动更新一次。每天自动更新这个功能很用用的，不知为何这么久没人提这个问题。

### Platform

Windows

### System Version

win11

### Software Version

1.5.8

**Comment by wonfen** [comment]
自动更新时间是以软件运行时间计算的。测试无问题。

**Comment by ldh1983** [comment]
比如我设置了1440分钟，软件必须连续开启1440分钟以上才自动更新？我设置的1440分钟，如果按照累积时间算，我这已经三天了，这三天的累积使用时间肯定超过了1440分钟。

**Comment by wonfen** [comment]
试一下设置更短的时间呢，比如1分钟

**Comment by ldh1983** [comment]
我看到我有个设置为360分钟的自动更新了。
