### ISSUE TITLE
[BUG] 默认 User Agent 错误

### ISSUE THREAD

**Issue by lslzl3000** [clash-verge-rev/clash-verge-rev#633]
### Describe the bug

经后端查看，如果订阅里默认不设置 User Agent，则使用 `Go-http-client/1.1` 作为默认 UA 发送请求，无法匹配 clash 相关协议。这里应该是默认使用 `clash-verge/v1.x.x` 才对吧，希望尽快修复

### Platform

MacOS

### System Version

mac os 14.2.1

### Software Version

1.5.8

**Comment by MystiPanda** [comment]
不存在这问题，自己找原因

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/152463842/d5264682-70a9-4f90-973c-c740ac2ddca2)

**Comment by lslzl3000** [comment]
… 自己试验一下？后端 log 又不会骗人，所以才是bug，哪里出了问题

**Comment by xishang0128** [comment]
@lslzl3000 verge-rev没有一点用go写的东西,Go-http-client怎么可能是verge-rev产生的ua?

**Comment by lslzl3000** [comment]
> @lslzl3000 verge-rev没有一点用go写的东西,Go-http-client怎么可能是verge-rev产生的ua?

clash 是 go 写的呀，包括新的 meta 内核，我也想知道为什么UA 没应用，反而是 go 的 ua

**Comment by xishang0128** [comment]
> > @lslzl3000 verge-rev没有一点用go写的东西,Go-http-client怎么可能是verge-rev产生的ua?
> 
> clash 是 go 写的呀，包括新的 meta 内核，我也想知道为什么UA 没应用，反而是 go 的 ua

verge-rev又不能控制golang编译产物用什么ua,这和verge-rev一点关系都没有

**Comment by MystiPanda** [comment]
@xishang0128 估计配置都让人爬完了，还在这怀疑verge呢

**Comment by lslzl3000** [comment]
> > > @lslzl3000 verge-rev没有一点用go写的东西,Go-http-client怎么可能是verge-rev产生的ua?
> > 
> > 
> > clash 是 go 写的呀，包括新的 meta 内核，我也想知道为什么UA 没应用，反而是 go 的 ua
> 
> verge-rev又不能控制golang编译产物用什么ua,这和verge-rev一点关系都没有

~ 你看懂了没？我这里说的是如果不在设置里手动填写 ua ，它就会默认用go的 ua，不是问如何改 go 的 ua， 还是说为什么留空默认不是 verge-rev 自己的 ua

<img width="395" alt="Screenshot 2024-03-15 at 17 19 13" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/3398981/2f938bfe-49f6-4d98-b913-d5509dc2e234">

这里ua 留空按理应该是默认 verge 的 ua， 但后端确实只能接受到 go 的ua
<img width="323" alt="Screenshot 2024-03-15 at 17 19 00" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/3398981/8cbdb01d-4885-48e1-b18f-72e689f4b0a5">


必须手动填 `clash-verge/v1.5.8` 才会收到 verge 的ua，这肯定是bug

**Comment by MystiPanda** [comment]
你有没有使用代理更新

**Comment by dongchengjie** [comment]
经测试，你说的情况不存在。无论是为空还是自定义UA，都正常
<img width="438" alt="1" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/2e1c5f78-4086-49b8-bea8-12330c1edd6f">
<img width="634" alt="2" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/96f62585-295d-4e8e-85ad-819d7cb6375e">
<img width="1280" alt="3" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/2c093cc0-dc4c-44ff-92f1-a0209abf2ac3">
<img width="724" alt="4" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/5b71acde-4605-411a-8d19-ce4c093cd1a6">

**Comment by lslzl3000** [comment]
本地一个简单的 http server，录了一段简单测试
![313158754-a450633d-950c-4203-ae98-4a150d9188dd-ezgif com-video-to-gif-converter](https://github.com/clash-verge-rev/clash-verge-rev/assets/3398981/721122a0-f79f-45d9-9193-15f80671dad8)

用本地 node 虽然没有发现 go 的 ua，但 ua 也是空的
之前服务器上的 ua log，出现 go 的 ua 可能是因为发过来的 ua 为空，前置服务器代理加了自己的 ua

**Comment by MystiPanda** [comment]
> 出现 go 的 ua 可能是因为发过来的 ua 为空，前置服务器代理加了自己的 ua

没错，我觉得是

**Comment by lslzl3000** [comment]
> > 出现 go 的 ua 可能是因为发过来的 ua 为空，前置服务器代理加了自己的 ua
> 
> 没错，我觉得是

那出现空 ua 也不是正常的值吧，这里应该是 verge 默认 ua 才对

**Comment by MystiPanda** [comment]
你不改的话确实是默认ua，你改了的话就会给你改了的ua，包括你改个空串，我刚刚处理了一下，以后不会给空串了。
