### ISSUE TITLE
[Feature] 建议替换rquickjs库，使用boa_engine 替代

### ISSUE THREAD

**Issue by pengdaCN** [clash-verge-rev/clash-verge-rev#634]
### Is your feature request related to a problem? Please describe.

rquickjs 库依赖quickjs，在windows环境不太好配置编译环境，目前看源码中，对quickjs的使用也不多，boa_engine 是rust写的，跨平台性好

### Describe the solution you'd like

使用boa_engine，替代，boa_engine可以实现我们需要用到的功能

### Describe alternatives you've considered

没有

**Comment by MystiPanda** [comment]
需要配什么环境

**Comment by MystiPanda** [comment]
看起来不错，换了，下载alpha版本试试
