### ISSUE TITLE
Mac 订阅更新后，会自动覆盖电脑手动设置的DNS地址

### ISSUE THREAD

**Issue by suyanjun1987** [clash-verge-rev/clash-verge-rev#636]
### Describe the bug

电脑网络ethernet的IP地址和DNS为手动设置，每次更新订阅后，手动设置的DNS地址都会被覆盖为空。请问该如何不让软件自动覆盖DNS地址。没有开启TUN模式。

### To Reproduce

电脑网络ethernet的IP地址和DNS为手动设置，每次更新订阅后，手动设置的DNS地址都会被覆盖为空。请问该如何不让软件自动覆盖DNS地址。没有开启TUN模式。

### Platform

Windows

### System Version

macOS 14.3.1

### Software Version

1.5.8

**Comment by wonfen** [comment]
用merge，看文档。

**Comment by suyanjun1987** [comment]
> 用merge，看文档。

感谢回答。但是Merge不是不覆写规则么。我现在是一点击更新订阅后，电脑物理网卡自己填写的DNS服务器地址会被删除。不是规则文件中的设置。

**Comment by jjqper** [comment]
> > 用 merge，看文档。
> 
> 感谢回答。但是 Merge 不是不覆写规则么。我现在是一点击更新订阅后，电脑物理网卡自己填写的 DNS 服务器地址会被删除。不是规则文件中的设置。

我是一打开 Clash Verge，网络 -> 以太网 -> DNS 服务器地址 就自动被删除了

**Comment by MystiPanda** [comment]
确实存在问题，还没想好怎么解决

**Comment by suyanjun1987** [comment]
> > > 用 merge，看文档。
> > 
> > 
> > 感谢回答。但是 Merge 不是不覆写规则么。我现在是一点击更新订阅后，电脑物理网卡自己填写的 DNS 服务器地址会被删除。不是规则文件中的设置。
> 
> 我是一打开 Clash Verge，网络 -> 以太网 -> DNS 服务器地址 就自动被删除了



> > > 用 merge，看文档。
> > 
> > 
> > 感谢回答。但是 Merge 不是不覆写规则么。我现在是一点击更新订阅后，电脑物理网卡自己填写的 DNS 服务器地址会被删除。不是规则文件中的设置。
> 
> 我是一打开 Clash Verge，网络 -> 以太网 -> DNS 服务器地址 就自动被删除了
这个应该是因为打开clash verge会自动更新订阅。

**Comment by suyanjun1987** [comment]
> 确实存在问题，还没想好怎么解决

期待更新解决这个问题~
