### ISSUE TITLE
[BUG] 当多个订阅中有相同的节点名称时，显示错误

### ISSUE THREAD

**Issue by goxq** [clash-verge-rev/clash-verge-rev#638]
### Describe the bug

当我用两家provider提供的节点并且它们的节点名称相同时，界面显示错误，如下图所示：
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/58415702/c8543fb0-38e2-409c-8c85-565c08256d7d)
上图的两个节点是来自两家provider的，协议分别是shadowrocks和trojan，名称相同，但现在的Clash把他们的协议类型都标成了shadowrocks并且都为选中状态。

### To Reproduce

如上

### Platform

Linux

### System Version

Ubuntu 22.04.3 LTS

### Software Version

1.5.8

**Comment by goxq** [comment]
@RoyalCiCi 设置了前缀没有用诶，还是照常

**Comment by Moriarty6086** [comment]
`    override:
      additional-prefix: "provider1 prefix |"
      additional-suffix: "| provider1 suffix"`
这样改了确实没用，override有开关吗？

**Comment by xishang0128** [comment]
> @RoyalCiCi 设置了前缀没有用诶，还是照常

仅alpha支持,release内核尚未支持

**Comment by goxq** [comment]
@xishang0128 alpha 从哪里下载呢

**Comment by xishang0128** [comment]
@goxq 内核切换

**Comment by goxq** [comment]
Thx
