### ISSUE TITLE
[BUG] 深色模式从托盘启动会闪一下白屏

### ISSUE THREAD

**Issue by pheotry** [clash-verge-rev/clash-verge-rev#639]
### Describe the bug

深色模式从托盘启动大概率会闪一下白屏，但是从开始菜单启动就没有问题

### To Reproduce

双击托盘图标，启动软件

### Platform

Windows

### System Version

win11 22635.3350

### Software Version

1.5.8

**Comment by wonfen** [comment]
不理解是什么情况，录个视频看看。

**Comment by pheotry** [comment]
> 不理解是什么情况，录个视频看看。
如果是双击托盘图标打开软件的话大概率会白屏一下，托盘右键菜单打开面板和从开始菜单启动则基本不会出现
https://github.com/clash-verge-rev/clash-verge-rev/assets/43376740/d427cc20-8b2f-4abf-9616-91a98c6e2310
