### ISSUE TITLE
TUN listening error: configure tun interface: operation not permitted

### ISSUE THREAD

**Issue by leonevilred** [clash-verge-rev/clash-verge-rev#64]
**Describe the bug**
archlinux 6.6.3 Gnome 45.2滚更后tun模式起不来

**To Reproduce**
同上

**Expected behavior**

**Screenshots**
![截图 2023-12-04 22-03-38](https://github.com/clash-verge-rev/clash-verge-rev/assets/67174702/1d0259ef-d180-439b-be91-7868e5772ab1)

**Information**

- OS:archlinux 6.6.3 Gnome 45.2 wayland
- Clash Verge Version: 1.4.2
- Clash Core: clash meta

**Additional context**

**Comment by wonfen** [comment]
去内核选择的地方点下“授权”
