### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by ZengProgrammer** [clash-verge-rev/clash-verge-rev#640]
Error A public key has been found, but no private key. Make sure to set `TAURI_PRIVATE_KEY` environment variable.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by raymao9** [comment]
生成你自己的公私钥就解决了

**Comment by ZengProgrammer** [comment]
> 生成你自己的公私钥就解决了

感谢，编译好了，还有个小坑Windows cmd设置私钥环境变量值不能加“”号
