### ISSUE TITLE
[BUG]每次开电脑都会提醒更新

### ISSUE THREAD

**Issue by lucacham** [clash-verge-rev/clash-verge-rev#641]
### Describe the bug

每次开机后，软件都会提醒更新
我以为是软件频繁在更新，直到昨天开机后打开软件我发现UI又回到了以前1.4的设计。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/25399625/72141721-990b-4ff0-a842-fa88756951d1)

### To Reproduce

每次提醒更新后，我都会更新。但是重新开机，又会是旧的版本。
软件我设置的开机自动启动。

### Platform

Windows

### System Version

windows11 23H2   22631.3235

### Software Version

1.5.8 （我其实每天在更新新的版本）

**Comment by MystiPanda** [comment]
@lucacham 电脑内存在多个版本，全部卸载干净然后重装就好了

**Comment by lucacham** [comment]
> @lucacham 电脑内存在多个版本，全部卸载干净然后重装就好了

确实有2个版本，我全部卸载了。重新开机重新安装后，发现设置还是以前的。
我之前颜色设置有问题，浅色下文字全看不清楚，我不知道如何将颜色全部恢复到初始设置

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/25399625/d48783d9-86da-42fd-8800-92ceae897ee3)

**Comment by MystiPanda** [comment]
1. 托盘图标右键 - 打开应用目录
2. 关闭clash-verge
3. 编辑 `verge.yml`文件，把theme-setting部分全部删除，保存
4. 启动clash-verge

**Comment by lucacham** [comment]
> 1. 托盘图标右键 - 打开应用目录
> 2. 关闭clash-verge
> 3. 编辑 `verge.yml`文件，把theme-setting部分全部删除，保存
> 4. 启动clash-verge

学习了。
已解决，谢谢。
