### ISSUE TITLE
[Feature] 菜单栏图标能见性与菜单栏菜单支持键盘快捷键

### ISSUE THREAD

**Issue by TerminaD** [clash-verge-rev/clash-verge-rev#642]
### Is your feature request related to a problem? Please describe.

菜单栏图标在系统代理打开/关闭的情况下差别不大，不易分辨；菜单栏 drop down menu 不支持键盘快捷键，操作略有不便。

### Describe the solution you'd like

使菜单栏图标在系统代理打开/关闭的情况下差别更大，参考 ClashX；菜单栏 drop down menu 支持快捷键。

### Describe alternatives you've considered

无

**Comment by dongchengjie** [comment]
纠正一下，“菜单栏”应该指的是“状态栏”吧，“图标”指的是Tray托盘图标吧（紫黄绿三个颜色），“drop down menu”说的是托盘的ContextMenu吧
