### ISSUE TITLE
[BUG]win64版本系统菜单及导航栏菜单点击无效

### ISSUE THREAD

**Issue by silentchild** [clash-verge-rev/clash-verge-rev#643]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/29771808/ca35b898-6335-450e-90ec-88e05b858101)
如图所示，右侧的固定 最小化 最大化 关闭均不可点击，下方的右侧操作菜单如：规则全局直连也不可点击（所有页面这个位置的按钮均不可点击）

### To Reproduce

正常打开就这样  重启也不行

### Platform

Windows

### System Version

23H2 22631.3296

### Software Version

1.5.8

**Comment by silentchild** [comment]
Clash.Verge_1.5.8_x64-setup
这个包

**Comment by ShaXiaozhu** [comment]
同样系统、同样版本、同样问题。

**Comment by MystiPanda** [comment]
@ShaXiaozhu 是alpha版本的bug，你装的应该是alpha版本。刚刚修了。

**Comment by ShaXiaozhu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
