### ISSUE TITLE
[BUG] macOS Ventura  启动clash会弹窗 ，申请【隐私与安全性】自动化，System Events

### ISSUE THREAD

**Issue by makelove** [clash-verge-rev/clash-verge-rev#644]
### Describe the bug

为什么第一次启动没有申请权限？
第二次就要申请？

一打开App就出现弹窗
macOS Ventura 无法关闭弹窗，导致卡死
重启也不行。

![截屏2024-03-16 21 02 03](https://github.com/clash-verge-rev/clash-verge-rev/assets/6279340/5e7c3f29-86aa-4d8b-b852-b8967e3c27e1)
我把权限打开，然后再启动App
还是卡死！

![截屏2024-03-16 21 07 31](https://github.com/clash-verge-rev/clash-verge-rev/assets/6279340/f70717a7-5f9c-41e5-bee2-b0ef291f7a10)

电脑
Mac mini 2023 m2芯片
系统
macOS Ventura 13.4
App
最新的
Clash.Verge_1.5.2_aarch64.dmg

### To Reproduce

一打开App就出现弹窗
macOS Ventura 无法关闭弹窗，导致卡死
重启也不行。

### Platform

MacOS

### System Version

macOS Ventura 13.4

### Software Version

Clash.Verge_1.5.2_aarch64.dmg

**Comment by MystiPanda** [comment]
软件不会申请这种权限，你从哪里下载的软件

**Comment by Youngmiyo** [comment]
> 软件不会申请这种权限，你从哪里下载的软件

我发现我的也有这个权限，我给了，我100%是在github下载的
<img width="463" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/27180765/1349b1d3-5c43-4ff4-b11f-dbef4f1a2448">

**Comment by makelove** [comment]
100%是在github下载的
不然怎么会找到这里？
![截屏2024-03-18 16 24 08](https://github.com/clash-verge-rev/clash-verge-rev/assets/6279340/e18fc406-2639-423a-b5da-c108a7a6688e)

**Comment by makelove** [comment]
![截屏2024-03-18 16 31 13](https://github.com/clash-verge-rev/clash-verge-rev/assets/6279340/05ebe949-1b2a-4d0d-a87b-b4b60e2042ba)

之前在涂鸦智能下载过

**Comment by huangzhuohua** [comment]
发现安装第一次打开确实需要权限
<img width="305" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/3843091/cbd4eab4-7a3d-46ee-9e33-34e4749d83f6">
