### ISSUE TITLE
[BUG]Mac左上角多出个奇怪的图标

### ISSUE THREAD

**Issue by Gongjiangege** [clash-verge-rev/clash-verge-rev#645]
### Describe the bug

Mac左上角多出个奇怪的图标
![1710598110796](https://github.com/clash-verge-rev/clash-verge-rev/assets/8636531/8c85cd5e-1e58-404c-83fe-ff27978c3347)

### To Reproduce

与苹果的图标相重叠，请去除这个多余的图标。

### Platform

MacOS

### System Version

macOS 14.3.1 (23D60)

### Software Version

v1.5.8

**Comment by PelikanM400** [comment]
同样出现此问题。
应该是tauri的问题，导致用tauri写的程序都有类似的bug。详见
https://github.com/LibNyanpasu/clash-nyanpasu/issues/62
https://github.com/LibNyanpasu/clash-nyanpasu/issues/97
https://github.com/tauri-apps/tauri/issues/8570
https://github.com/tauri-apps/tray-icon/issues/90
clash verge rev也有人报过类似的错误：
https://github.com/clash-verge-rev/clash-verge-rev/issues/506#issuecomment-1998891410
这bug其实挺烦人的，期待能早日修复。

**Comment by lllzy040620** [comment]
是的，我mba m2也出了这种情况。应该是共性问题了

**Comment by PelikanM400** [comment]
> 是的，我mba m2也出了这种情况。应该是共性问题了

这bug真的很有历史了。我没记错的话（在别的地方也说过），早些时候原版clash verge没有归档的时候我用原版verge就出现过这个问题。不知道为啥这么久了上游的tauri还没有修复。

**Comment by lllzy040620** [comment]
我刚将系统更新到Sonoma 14.4后，惊奇地发现似乎问题解决了？有点快哈，但是真的很神奇

**Comment by PelikanM400** [comment]
> 我刚将系统更新到Sonoma 14.4后，惊奇地发现似乎问题解决了？有点快哈，但是真的很神奇

我的一直是14.4的系统，一直有这个bug。这点也很奇怪，kan大家反馈的bug，有的人同样的系统环境就没有这个bug，不知道为什么。

**Comment by lllzy040620** [comment]
> > 我刚将系统更新到Sonoma 14.4后，惊奇地发现似乎问题解决了？有点快哈，但是真的很神奇
> 
> 我的一直是14.4的系统，一直有这个bug。这点也很奇怪，kan大家反馈的bug，有的人同样的系统环境就没有这个bug，不知道为什么。

你要不检查一下“设置”->“通用”->“软件更新”？我是今天下午收到更新推送后才进行更新的，更新后发现问题解决了

**Comment by lllzy040620** [comment]
我目前显示的是macOS Sonoma 14.4 (23E214)，你可以在“设置”->“通用”->“软件更新”中核查一下？

**Comment by PelikanM400** [comment]
> 我目前显示的是macOS Sonoma 14.4 (23E214)，你可以在“设置”->“通用”->“软件更新”中核查一下？

更加奇怪的是，昨天晚上我和别人开了一个线上会议，别的什么都没干，会议结束我发现那个错误的图标就没了😂

**Comment by tongjiann** [comment]
我之前出现过这个 bug，然后我就不用这个软件了，后来有一次打开发现这个图标没有就继续用了，今天更新到 1.5.9 之后发现又出现了，烦人
<img width="318" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/45749358/bb28e88c-1ce2-4252-8db4-63a347897c5d">
