### ISSUE TITLE
[BUG]如何在软件更新后保持使用自定义的Country.mmdb?

### ISSUE THREAD

**Issue by you-hengh** [clash-verge-rev/clash-verge-rev#647]
### Describe the bug

我使用了这个仓库下的[Country.mmdb](https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb) 只有330kb 我希望在软件版本升级的时候,保留我自己使用的
Country.mmdb

### To Reproduce

软件版本更新后 Country.mmdb 变为5MB大小

### Platform

Windows

### System Version

win11 专业版 23H2

### Software Version

1.5.8

### Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/34816426/32152fc4-9978-4d21-808e-9c6342dd3af4)

**Comment by dongchengjie** [comment]
为什么偏爱Lite版的，我还闲数据集太小判不准呢😅
这个貌似是内核控制的吧，verge只负责调用API更新吧
你试试这个[自定 GEO 下载地址](https://wiki.metacubex.one/config/general/#geo_2)]

**Comment by you-hengh** [comment]
> 为什么偏爱Lite版的，我还闲数据集太小判不准呢😅 这个貌似是内核控制的，verge只负责调用API更新吧，貌似内核更新GEO的API还有BUG 你试试这个[自定 GEO 下载地址](https://wiki.metacubex.one/config/general/#geo_2)]

能讲一下具体如何操作吗? 我不希望因为clash-verge的升级每次重新操作这些数据库, 配置要写在哪里呢?

新建配置选择什么呢 ?

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/34816426/b1169845-d7fb-4e6f-bab4-6addf2c118f3)

建立好文件后 里面该如何配置呢 我不太懂这个, 能给个demo看看吗 辛苦了
