### ISSUE TITLE
[BUG]安装后打不开，一打开就闪退。。。

### ISSUE THREAD

**Issue by dscvse** [clash-verge-rev/clash-verge-rev#649]
### Describe the bug

卸载重装后，随机启动不能静默启动，总是自动打开主界面，需要手动关闭，嫌麻烦就卸载清理了注册表。。。

### To Reproduce

再重新安装就出现了打不开软件，直接闪退。。。请问有什么办法解决？？？

### Platform

Windows

### System Version

win11

### Software Version

1.5.9

**Comment by wonfen** [comment]
参考这个解决方法： https://github.com/clash-verge-rev/clash-verge-rev/issues/561

**Comment by wonfen** [comment]
无进一步反馈，关闭。
