### ISSUE TITLE
[BUG]切换全局模式后再切回规则模式无效，全部都走代理了

### ISSUE THREAD

**Issue by Youngmiyo** [clash-verge-rev/clash-verge-rev#650]
### Describe the bug

我今天早上在1.5.8版本切换了全局之后，再切回规则时发现全部都在走代理，查看连接里面全是走的代理，百度一下ip都是代理的ip不是本地ip，我尝试了更新软件到1.5.9还有重装以前的版本，重启Mac甚至更新Mac系统都没解决
<img width="866" alt="Snipaste_2024-03-17_13-21-13" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/27180765/f6274f95-e6a7-464a-a143-a275470f4eae">
<img width="1512" alt="Snipaste_2024-03-17_13-19-42" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/27180765/42e6f865-1122-4f9d-bbcd-6699819b37bb">

### To Reproduce

规则模式下切换全局模式，过几分钟再切回规则模式，然后去百度一下ip

### Platform

MacOS

### System Version

MacOS 13.6.5

### Software Version

1.5.9

### Log

<img width="1512" alt="Snipaste_2024-03-17_13-20-21" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/27180765/c91a2f15-a691-48d9-8631-91f6a0bfe0a4">

### Additional Information

我使用其它软件是正常的，在手机端使用其它软件是正常的

**Comment by wonfen** [comment]
测试无问题，检查你的配置规则问题。

从你截图来看这规则模式下，你走的是Main Node链；并没有走Gobal链；所以当前是在规则模式下。

**Comment by Youngmiyo** [comment]
> 测试无问题，检查你的配置规则问题。
> 
> 从你截图来看这规则模式下，你走的是Main Node链；并没有走Gobal链；所以当前是在规则模式下。

好的，问了是它们引用的规则集网站炸了，感谢！
