### ISSUE TITLE
[Feature] 不要常驻 Dock 栏

### ISSUE THREAD

**Issue by tbuggx** [clash-verge-rev/clash-verge-rev#651]
### Is your feature request related to a problem? Please describe.

macOS 上 1.5.9 之前的版本有个问题，Dock 栏不显示程序图标，使用 Command+Tab 切换也看不到，1.5.9 版本修复了，但是却变成了常驻不能隐藏。

### Describe the solution you'd like

建议点击主窗口关闭按钮，可以从 Dock 栏移除。

### Describe alternatives you've considered

无。

**Comment by wonfen** [comment]
当前版本的tarui对dock的支持还不完善，下个版本将移除dock图标。

**Comment by kratos9394** [comment]
确实挺碍眼，同mac

**Comment by ShiraishiMa1** [comment]
而且关闭面板后，点击dock栏的图标，面板还点不出来

**Comment by djhcod** [comment]
希望修复这个问题

**Comment by wonfen** [comment]
> 希望修复这个问题

不是说了么，下个版本移除dock
