### ISSUE TITLE
[BUG]Translation is unavailable at the moment. Try again at a later time. on macOS 14.2 Sonoma

### ISSUE THREAD

**Issue by AlanSmith111** [clash-verge-rev/clash-verge-rev#652]
### Describe the bug

It seems that the reason why you can't use the integrated translation tool in macOS 14.2 is that it has been detected as a proxy, and it seems that "the new system has imposed a new restriction on the system translation service in the shortcut commands, so as long as there is a proxy behavior in the system when accessing the translation service, the translation service in the shortcut commands will definitely fail to be executed, and a series of functions that use the system translation service, such as Safari webpage translation, will not be able to be used." Safari webpage translation and other functions that use the system translation service will also not work. The "Safari" feature will also be disabled.

Translated with www.DeepL.com/Translator (free version)
like this https://github.com/ripperhe/Bob/issues/405

### To Reproduce

Open this tool and try to translate use this integrated translation tool in macOS 13+

### Platform

MacOS

### System Version

macOS 14.3.1

### Software Version

1.5.9

### Log

![Screenshot 2024-03-16 at 10 46 00 PM](https://github.com/clash-verge-rev/clash-verge-rev/assets/92530778/5348d441-b7ee-4889-9712-d7e904d19067)

**Comment by wonfen** [comment]
检查你的规则配置文件。一天bugbug的，要被你们气死。

**Comment by xishang0128** [comment]
@AlanSmith111 Make sure you use the same inbound
