### ISSUE TITLE
[Feature]支持自定义 Profiles 配置文件路径

### ISSUE THREAD

**Issue by leic4u** [clash-verge-rev/clash-verge-rev#653]
### Is your feature request related to a problem? Please describe.

已知该文件路径放的是远程订阅配置文件，或导入的本地手搓配置文件。

目前我是手搓配置，改一次配置文件后，我需要在五台设备上都去手动修改一遍，这有点太难受了。

### Describe the solution you'd like

如果可以自定义 Profiles 目录（目前在 .config/io.github.clash-verge-rev.clash-verge-rev/profiles 路径下），我可以把手搓文件放到一个同步目录下，每台设备的 Clash-Verge-Rev 只需要配置一次，将 profiles 目录指向同步目录即可。

类似于 Clash For Windows 的这个功能：

https://docs.gtk.pw/contents/profilespath.html

### Describe alternatives you've considered

暂无

**Comment by choi006** [comment]
把你的手搓配置放到云端。用订阅的方式导入不就行了

**Comment by studentluo** [comment]
用订阅的形式  走到哪儿定到哪儿 手机也能用

**Comment by leic4u** [comment]
> 把你的手搓配置放到云端。用订阅的方式导入不就行了

问题是每改一次，就得每台设备手动操作导入一次。五台设备就得手动操作五次，有点繁琐。

**Comment by zhouxinghong** [comment]
> 把你的手搓配置放到云端。用订阅的方式导入不就行了

+1

**Comment by leic4u** [comment]
各位说的做成在线订阅的方式我不是没考虑过，但对我来说有 2 个问题。
1. 因为要测试配置文件的有效性，所以都是在 Clash-Verge-Rev 的编辑器里修改，然后手动刷新配置，然后再去配置文件目录，找到自己刚刚手搓的文件，然后复制下来，再传到托管网站做成订阅链接。

2. 得先找一个能用且安全的托管站点，安全这个事情要做起来要做的就太多太专业了，感觉目前按我的能力我还没法保证一定程度上的订阅安全，所以我才没有把手搓文件搞成订阅链接。
