### ISSUE TITLE
[BUG]之前配置文件只放proxies和rules，访问全部正常。现在必须要把DNS写上，否则【当前配置】缺少dns网络访问会异常

### ISSUE THREAD

**Issue by studentluo** [clash-verge-rev/clash-verge-rev#654]
### Describe the bug

配置文件中缺少【DNS】项目时网络异常
我之前在配置文件中只写【peoxies】和【rules】都能运行正常   而且我使用的某个机场他也不写【dns】 然后我的网络就炸了
请问现在就是这样设计的 不改了吗 还是bug

### To Reproduce

-.-

### Platform

Windows

### System Version

Windows11

### Software Version

1.5.9

**Comment by wonfen** [comment]
建议阅读meta的文档 https://wiki.metacubex.one/config/
