### ISSUE TITLE
Ubuntu启用Tun后还是无法ping Google

### ISSUE THREAD

**Issue by Lancer907** [clash-verge-rev/clash-verge-rev#655]
### Describe the bug

系统是Ubuntu，Clash 1.5.9。内核已授权，Tun打开，弹出提示要求输入密码4次，无报错。检查网关也有“Meta”。浏览器可以正常访问google，但是打开命令窗口ping ww.google.com仍然无结果。查看网关流量为0。不知道该怎么搞了。另外，在Ubuntu上启用了“局域网连接”，在另一台Win11上也是无法ping google，浏览器访问正常。

### To Reproduce

系统是Ubuntu，Clash 1.5.9。内核已授权，Tun打开，弹出提示要求输入密码4次，无报错。检查网关也有“Meta”。但是打开命令窗口ping ww.google.com仍然无结果。

### Platform

Linux

### System Version

Ubuntu 22.04.4 LTS

### Software Version

Clash Verge Rev 1.5.9

### Log

![Uploading Snipaste_2024-03-17_21-15-40.png…]()

**Comment by xishang0128** [comment]
@Lancer907 代理软件不会代理ping,google ip本来就是不通的,只有vpn才能代理ping

**Comment by AprilGrimoire** [comment]
@Lancer907 ping使用icmp协议，不会被TUN代理。建议使用wget或curl测试连通性。
