### ISSUE TITLE
[BUG] Start Redir server error: protocol not available

### ISSUE THREAD

**Issue by AprilGrimoire** [clash-verge-rev/clash-verge-rev#656]
### Describe the bug

![Screenshot_2024-03-17_21-51-20](https://github.com/clash-verge-rev/clash-verge-rev/assets/47601131/6f6a6ebd-0801-47fa-b6f8-83f1e67014ac)

I have already clicked on 'Authorize'（授权） and granted root permission. I can bypass GFW right now, but it seems laggy sometimes. Don't know why this error message appears.

### To Reproduce

Not sure

### Platform

Linux

### System Version

Archlinux: Linux AprilGrimoire-HONOR-laptop 6.6.22-1-lts #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 06:20:33 +0000 x86_64 GNU/Linux

### Software Version

1.5.9, with core 1.18.1 meta

**Comment by wonfen** [comment]
检查你的配置文件写法。这个是内核报错，和GUI无关。
