### ISSUE TITLE
常规网站网络异常[BUG]

### ISSUE THREAD

**Issue by fuyongzk** [clash-verge-rev/clash-verge-rev#657]
### Describe the bug

开启规则模式代理之后，经常导致一些常规的网站无网络，如百度、抖音等。关闭clash verge之后正常。之前没有这种状况。
<img width="960" alt="搜狗截图20240317221531" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/120019530/2518415f-7b61-4e2f-80c0-2ad43a2d8c59">

### To Reproduce

开启规则代理之后，访问常规的网站显示无法访问，关闭clash verge之后恢复正常。升级到了1.5.9才出现的问题，之前没有这种状况。

### Platform

Windows

### System Version

win11 23H2

### Software Version

1.5.9

**Comment by wonfen** [comment]
检查你的机场规则，在连接菜单下查看代理链。

**Comment by fuyongzk** [comment]
> 查看您的机场规则，在连接菜单下查看代理链。

大佬，受我一拜
