### ISSUE TITLE
[BUG]Alpha内核无法升级

### ISSUE THREAD

**Issue by hsiayuchih** [clash-verge-rev/clash-verge-rev#658]
### Describe the bug

升级内核提示获取版本失败。
**上个星期提过一次issue #612 ，但是问题没有解决就被关闭了**，后续的回复也没人理...

### To Reproduce

![312425937-650699ab-0c8e-4861-a10a-eda7f89e2019](https://github.com/clash-verge-rev/clash-verge-rev/assets/21278771/7f5052af-95a5-435c-85e8-1caa8a16db4e)

### Platform

Windows

### System Version

windows11

### Software Version

1.5.8

**Comment by wonfen** [comment]
检查你的网络到github的连接性

**Comment by hsiayuchih** [comment]
> 检查你的网络到github的连接性

我开着代理的，正常访问是没问题的

**Comment by hsiayuchih** [comment]
升级到最新版后貌似可以正常更新了
