### ISSUE TITLE
[Feature] 在1.5.9版本中新增了【MacOS Dock 栏不显示图标】-希望可以新增一个可以隐藏dock图标的功能

### ISSUE THREAD

**Issue by tang-zack** [clash-verge-rev/clash-verge-rev#659]
### Is your feature request related to a problem? Please describe.

在1.5.9版本中新增了【MacOS Dock 栏不显示图标】-希望新增一个可以隐藏或者打开的按钮，上一个版本都没有 ，目前新的版本MacOS Dock 栏一直存在希望还是可以隐藏

**Comment by tkizm1** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/651 需求重复了

**Comment by wonfen** [comment]
下个版本去掉。

**Comment by tang-zack** [comment]
好的&nbsp; &nbsp;感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "clash-verge-rev/clash-verge-rev"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月20日(星期三) 上午9:48
***@***.***&gt;;
抄送:&nbsp;"放纵° ***@***.******@***.***&gt;;
主题:&nbsp;Re: [clash-verge-rev/clash-verge-rev] [Feature] 在1.5.9版本中新增了【MacOS Dock 栏不显示图标】-希望可以新增一个可以隐藏dock图标的功能 (Issue #659)





 
下个版本去掉。
