### ISSUE TITLE
[BUG]Mac 1.5.9 版本在程序坞中一直存在，程序坞退出无法后台运行

### ISSUE THREAD

**Issue by chao921125** [clash-verge-rev/clash-verge-rev#660]
### Describe the bug

1.5.9 之前的版本，程序坞中不会出现，现在只要打开程序运行，便会在程序坞中一直停留，且程序坞中退出之后无法在后台继续运行。

### To Reproduce

不保留程序坞中，在程序坞中退出后可以后台运行。

### Platform

MacOS

### System Version

14.4

### Software Version

1.5.9

**Comment by itlaosiji** [comment]
同样发现了这个BUG

**Comment by wonfen** [comment]
下个版本就去掉。
