### ISSUE TITLE
mac运行1分钟左右会自动断开

### ISSUE THREAD

**Issue by YuanHong071** [clash-verge-rev/clash-verge-rev#661]
### Describe the bug

mac运行1分钟左右会自动断开，系统14.4。但打开面板就不会。奇怪的现象，好像从1.54开始就出现了。
<img width="793" alt="截屏2024-03-18 11 32 32" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/63335802/3e73c731-8a33-48a3-afd2-58e299a6dda8">

### To Reproduce

希望能找找什么原因，谢谢！

### Platform

MacOS

### System Version

14.4

### Software Version

1.5.9

**Comment by wonfen** [comment]
什么叫断开？哪里断开？日志？

**Comment by YuanHong071** [comment]
[image: 截屏2024-03-19 12.31.08.png][image: 截屏2024-03-19 12.15.06.png][image:
截屏2024-03-19 12.14.01.png]
你好，我也是个小白，只是以前使用你发布的一直都好好的，连更新了3次版本后就开始出现这种情况了，希望对你有用。还有非常谢谢你的付出！

wonfen ***@***.***> 于2024年3月19日周二 01:57写道：

**Comment by YuanHong071** [comment]
补充下，使用Clash.Nyanpasu_1.5.0_x64就没发生上述情况。

**Comment by wonfen** [comment]
> 补充下，使用Clash.Nyanpasu_1.5.0_x64就没发生上述情况。

用nya的时候你用的内核是什么？

**Comment by MystiPanda** [comment]
@wonfen 这种废话有必要补充吗

**Comment by YuanHong071** [comment]
楼上MystiPanda ， Github是个开放共享区，如实描述问题，请教问题很正常。你要来我行业的领域，你连补充话题都找不到！

**Comment by MystiPanda** [comment]
又看了一下，你的图片应该没有上传成功，我没有看到任何有用的信息，麻烦重新发一下图片。
