### ISSUE TITLE
建议添加新增节点的功能

### ISSUE THREAD

**Issue by pei92** [clash-verge-rev/clash-verge-rev#665]
### Is your feature request related to a problem? Please describe.

建议添加类似CFW那样新增节点/规则的功能

### Describe the solution you'd like

具体如下图：
![clash](https://github.com/clash-verge-rev/clash-verge-rev/assets/21659514/e1a63ed0-e59e-4489-8978-64f43a928cf3)
![proxy](https://github.com/clash-verge-rev/clash-verge-rev/assets/21659514/6e5eded8-9ceb-4357-b7e7-f29e547d8cd4)

### Describe alternatives you've considered

无

**Comment by dongchengjie** [comment]
premium内核原来支持的协议这么少吗，trojan、vless、hy、hy2、quic都没见着
