### ISSUE TITLE
[Feature] 正常右键单击图标是正常的，左键单击后，会先弹出右键菜单，再打开主界面

### ISSUE THREAD

**Issue by wuai1024** [clash-verge-rev/clash-verge-rev#666]
### Is your feature request related to a problem? Please describe.

<img width="160" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/13379708/21dc2c76-2ff8-4c8b-98e6-0875e8699339">

1、右键单击图标，正常弹出右键菜单
2、左键单击图标，会先弹出来右键菜单，然后再打开主界面

交互有点奇怪

### Describe the solution you'd like

希望在左键单击的时候，能直接打开主界面，而不需要 先弹出右键菜单，再一闪而逝。然后再打开主界面

### Describe alternatives you've considered

目前的临时解决方案

我在菜单中设置了，单击图标，开启关闭 代理。

这样就不用先弹出来，然后显示了。但是还是希望，能正常交互

**Comment by wonfen** [comment]
设置下的托盘点击事件可以修改。

**Comment by wuai1024** [comment]
可能你还没明白我的意思。

设置了托盘点击事件为 【显示主窗口】

这时候我点击的时候应该直接显示，不需要再弹出 右键菜单

**Comment by awds888** [comment]
+1，另外建议软件初始的设定就直接应该设定为：显示主窗口。很少有人有这个需求左键单击是控制系统代理的，有点反人类的设定啊

**Comment by sunheyi6** [comment]
@wuai1024 @wuai1024  我安装的1.5.9版本的，效果就是你俩说的这样的，我也没自己设置过托盘点击事件
