### ISSUE TITLE
[BUG] clash doesn't work

### ISSUE THREAD

**Issue by InvokerMing** [clash-verge-rev/clash-verge-rev#668]
### Describe the bug

Can't visit internet by system proxy. (The proxy works. I can use it by Clash for Windows)
打开系统代理以后无法正常连接互联网，代理没问题，clash for windows可以正常访问。
log shows "Start Redir server error: not supported on current platform"(I don't know if it is relevant.)
![微信截图_20240318150757](https://github.com/clash-verge-rev/clash-verge-rev/assets/31062896/4db2203d-b6f6-4f2d-9cc6-1d0d3d392d7e)

### To Reproduce

我第一次用clash verge，导入规则，打开系统代理后就不能访问互联网了。

### Platform

Windows

### System Version

Windows11 23H2

### Software Version

1.5.9 x64

### Log

![rz](https://github.com/clash-verge-rev/clash-verge-rev/assets/31062896/e90b6140-c49f-4b51-90aa-23d642ea11e2)

**Comment by wonfen** [comment]
检查你的配置文件的问题。
cfw的配置文件不一定和meta内核通用。

**Comment by InvokerMing** [comment]
> 检查你的配置文件的问题。 cfw的配置文件不一定和meta内核通用。

这样吗，我不太了解这方面，那我该怎么修改文件？（另外这个配置文件我用clash meta for android是可以用的，这方面有什么可以参考的吗。
