### ISSUE TITLE
[BUG]windows下，更新时，目录变更为C:\Program Files

### ISSUE THREAD

**Issue by RungePei** [clash-verge-rev/clash-verge-rev#669]
### Describe the bug

安装时可修改安装目录，但更新时，目录又会变为C:\Program Files下

### To Reproduce

安装时指定目录到D盘，根据提示更新，会安装在C盘下

### Platform

Windows

### System Version

Windows 10 2009

### Software Version

v1.5.8

**Comment by wonfen** [comment]
不要使用便携版。

**Comment by wonfen** [comment]
无进一步反馈，关闭。
