### ISSUE TITLE
[Feature] 使 urltest 类型支持手动选择

### ISSUE THREAD

**Issue by howdareyo** [clash-verge-rev/clash-verge-rev#674]
### Is your feature request related to a problem? Please describe.

某些节点突然不稳定时, 对策略组测速并不会及时切换代理, 所以需要手动切换.
在 webgui 中, 即使策略组类型是 urltest, 也依旧可以手动选择并切换, 但在 verge 中点击 urltest 类型中的节点是没有反应的.
webgui 中的切换也会立刻反应到  verge 上, 即节点被切换了.

### Describe the solution you'd like

使 urltest 类型也支持手动选择

### Describe alternatives you've considered

或者在对某个策略组进行测速之后立刻切换到最快的节点

**Comment by utopeadia** [comment]
这个需要去内核提issus，但完全没必要，需要手选为什么不用select呢？urltest设计就不允许手选的，如果想更灵敏的切换可以修改配置文件或者覆写测试间隔时间和灵敏度。（另外什么webui能手选urltesl啊，我避个雷）

**Comment by utopeadia** [comment]
> > 这个需要去内核提issus，但完全没必要，需要手选为什么不用select呢？urltest设计就不允许手选的，如果想更灵敏的切换可以修改配置文件或者覆写测试间隔时间和灵敏度。（另外什么webui能手选urltesl啊，我避个雷）
> 
> 先说一下误区 webgui 为官方的 https://d.metacubex.one/ 其次, 这个能否切换并不是 gui 决定的, 是由内核本身 api 的 /proxies/:name 的 PUT 方法支持的. 如果内核不支持, gui 翻天了也不可能切换. 换言之, 这是一个内核已经实现的 feature, 而不是一个需要由我提出的 issus.
> 
> 最后, 这不是更加灵敏切换的问题, 我的场景是, 我突然发现 urltest 所选的节点断开, 或者说, 红了, 我不可能慢慢等到下一次测速自动选择, 我也不可能把测速间隔改成一分钟, 这对机场和测速网站都是不道德的. 当然也可以单独分出一个有 select 和 urltest 的策略组, 在我红了的时候手动从 urltest 切换到 select, 但我觉得这很异常.

有道理，针对手动urltest->select我这个我觉得有一个方案就是设置fallback组，然后配置自动和手动
