### ISSUE TITLE
Intel macOS版 更新到最新的1.5.9后，打开后程序坞出现app图标，如何跟旧版本那样，打开后只在最上方的状态栏显示图标

### ISSUE THREAD

**Issue by laibabaifei** [clash-verge-rev/clash-verge-rev#676]
### Is your feature request related to a problem? Please describe.

Intel macOS版 更新到最新的1.5.9后，打开后程序坞出现app图标，如何跟旧版本那样，打开后只在最上方的状态栏显示图标

### Describe the solution you'd like

跟旧版本那样，打开后只在最上方的状态栏显示图标

### Describe alternatives you've considered

无

**Comment by roaminlove** [comment]
刚像提问, 发现已经有了
macbook pro M2 版本的要是出现了无法隐藏程序坞图标,仅保留工具栏的

**Comment by wonfen** [comment]
下个版本去掉。
