### ISSUE TITLE
[BUG]远程订阅栏字体显示不正常，出现重影

### ISSUE THREAD

**Issue by xbdh** [clash-verge-rev/clash-verge-rev#679]
### Describe the bug

![截图 2024-03-19 12-22-27](https://github.com/clash-verge-rev/clash-verge-rev/assets/16819507/653b6524-dc9e-48f5-8dcd-317f2dd458e7)

### To Reproduce

无

### Platform

Linux

### System Version

Fedora39

### Software Version

1.5.9

### Additional Information

使用了gnome-tweak ，设置里1.5倍字体，跟这有关系吗？
![截图 2024-03-19 12-25-59](https://github.com/clash-verge-rev/clash-verge-rev/assets/16819507/a52cb71d-94d7-4fd8-b1e9-2609de93f997)

**Comment by MystiPanda** [comment]
这是你系统缩放的问题，只调整字体 dpi 就会这样
