### ISSUE TITLE
[Not BUG] 请问一下，UWP tool 出现这个弹窗是什么意思？

### ISSUE THREAD

**Issue by MMMMMoris** [clash-verge-rev/clash-verge-rev#682]
### Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/63332824/fe2f3eee-8ba2-4d11-beea-f827222b7187)
有什么办法可以避免这个弹窗？

### To Reproduce

我不知道这个问题是否广泛存在，反正我的是打开 UWP tool 就出现了这个弹窗

### Platform

Windows

### System Version

Windows 23H2 22631.3296

### Software Version

1.5.9

**Comment by wonfen** [comment]
没遇到过，到用UWP+弹窗关键词搜索一下。
