### ISSUE TITLE
[BUG]macOS ARM退出軟體後不會自動取消代理

### ISSUE THREAD

**Issue by FeiFei-SS** [clash-verge-rev/clash-verge-rev#683]
### Describe the bug

透過頂部欄選擇退出，不會自動清空系統代理，導致退出後整個系統沒有網路。
<img width="780" alt="Screen Shot 2024-03-19 at 3 05 20 PM" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/45664529/1367dcd2-2daa-4fb4-9f18-8012c7bf4e5b">

### To Reproduce

Clash 原版以及其他軟體均有此功能，希望加入！

### Platform

MacOS

### System Version

12.7.3

### Software Version

1.5.9.

**Comment by xuyanshi** [comment]
I have the same problem.
