### ISSUE TITLE
[BUG] macOS ARM 更新 v1.5.9之后Dock栏的图标关不掉

### ISSUE THREAD

**Issue by danielluvmjy** [clash-verge-rev/clash-verge-rev#684]
### Describe the bug

[BUG] macOS ARM 更新 v1.5.9之后Dock栏的图标关不掉

### To Reproduce

点击左上角的x关掉后，Dock栏图标不会消失

### Platform

MacOS

### System Version

macOS 14.4

### Software Version

1.5.9

**Comment by MaoGT** [comment]
the same

**Comment by Fangtang74** [comment]
一样的

**Comment by LUDA0831** [comment]
一样的

**Comment by krzhck** [comment]
same

**Comment by charley008** [comment]
+1
