### ISSUE TITLE
[BUG] youtube，谷歌邮箱 不能正常访问，github这些是可以正常访问的

### ISSUE THREAD

**Issue by topmkx** [clash-verge-rev/clash-verge-rev#687]
### Describe the bug

03-19 20:03:09INFO
[TCP] 127.0.0.1:49362(Clash Verge.exe) --> www.youtube.com:443 match DomainKeyword(youtube) using 狗狗加速.com[11美国-全网优化(hy2)]

看日志应该是正常的，但是我在google浏览器上访问不通，我通过clash verge 的测试功能，报的超时

### To Reproduce

03-19 20:03:09INFO
[TCP] 127.0.0.1:49362(Clash Verge.exe) --> www.youtube.com:443 match DomainKeyword(youtube) using 狗狗加速.com[11美国-全网优化(hy2)]

看日志应该是正常的，但是我在google浏览器上访问不通，我通过clash verge 的测试功能，报的超时；我已经不知道怎么去排查问题了

### Platform

Windows

### System Version

win 10

### Software Version

1.5.9

**Comment by chao921125** [comment]
你可以换一些节点试试

**Comment by topmkx** [comment]
我在mac，和手机上都可以正常访问，我换了节点也不行，就很奇怪；感觉是不是因为系统某些设置问题；

hc precog ***@***.***> 于2024年3月19日周二 20:49写道：

**Comment by wonfen** [comment]
检查你的host文件是否被其他加速器修改。

**Comment by topmkx** [comment]
> 检查你的host文件是否被其他加速器修改。

还真的是这问题，感谢
