### ISSUE TITLE
[BUG]设置了只保留7天的日志，但超过7天的日志没有被自动清理

### ISSUE THREAD

**Issue by leic4u** [clash-verge-rev/clash-verge-rev#689]
### Describe the bug

在杂项设置中选择了最短的那个「保留 7 天」。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/32786903/b3cefdb8-f3f9-4a51-b70a-454cbdb5e183)

但是日志目录中仍然存在 7 天之前的日志。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/32786903/f22a3906-f8db-4853-b14e-fa3e96d6df67)

### To Reproduce

在杂项设置中设置自动清理日志为「保留 7 天」，7 天后查看日志目录。

### Platform

Windows

### System Version

windows 11

### Software Version

1.5.9

**Comment by wonfen** [comment]
重启一下clash verge试试。

**Comment by leic4u** [comment]
> 重启一下clash verge试试。

重启应用，重启 Clash，退出（再手动打开 exe）。这几个都试过了，还是没有删除日志。

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/32786903/ce7bb665-b29a-4a79-834a-6504c43e3b96)

我是用的 protable 版，不知道是不是这个原因。
