### ISSUE TITLE
[BUG]1.4.3版本，链接不上metacubexd，是clash api有问题吗

### ISSUE THREAD

**Issue by yanghl9898** [clash-verge-rev/clash-verge-rev#69]
![bdbab9a2be5ae55f1c19fda26e0a86e](https://github.com/clash-verge-rev/clash-verge-rev/assets/137973391/df980d75-39cb-48bd-a537-67619386ce8f)

**Comment by MystiPanda** [comment]
去设置里面外部控制查看Extemal Controller的地址是否正确

**Comment by yanghl9898** [comment]
可以了，初始化的是127.0.0.1:9098
