### ISSUE TITLE
[BUG] MacOS 上使用 `Command+Q` 退出不会自动清理网络配置中的代理

### ISSUE THREAD

**Issue by icefery** [clash-verge-rev/clash-verge-rev#690]
### Describe the bug

MacOS 上使用 `Command+Q` 退出不会自动清理网络配置中的代理，必须要右键打开托盘中的退出选项点击，才能清理系统网盘配置中的代理。
<img width="670" alt="iShot_2024-03-20_08 21 25" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/61737634/bfba9b20-b5a6-4fc1-84e5-7300fdf07d23">

### To Reproduce

1. 使用 `Command + Q` 退出；
2. 使用右键托盘点击退出选项退出；
3. 查看系统网络配置；

### Platform

MacOS

### System Version

macOS 14.4

### Software Version

1.5.9

**Comment by wonfen** [comment]
程序都被你强制退出了，怎么清理代理啊

**Comment by flyflas** [comment]
还是用tun模式吧。
