### ISSUE TITLE
[公告] 统一关闭所有 issue

### ISSUE THREAD

**Issue by MystiPanda** [clash-verge-rev/clash-verge-rev#694]
感谢大家一直以来对该项目的支持和喜爱。近期，我们发现仓库中存在大量重复和无意义的issue，这不仅降低了开发效率，也给开发者带来很大的心智负担，还给issue的处理和跟进带来了困难。为了解决这一问题，我们将仓库中所有的issue进行了统一关闭处理。同时，我们完善了issue提交模板，以规范化issue的提交内容和格式。

从即日起，所有新提交的issue必须严格按照模板的要求填写内容，提供必要的信息，如问题描述、复现步骤、日志信息等。不符合模板要求的issue将会被直接关闭，恕不另行通知。

我们相信，通过这一举措，能够有效提高issue的质量，减少无效问题的干扰，让开发者可以更加专注于解决真正有价值的问题。同时，也希望大家在提交issue之前，先搜索一下是否已经有相同或类似的问题被提出，避免重复提交。

此前统一关闭的issue将被标记`old`标签并锁定，这其中如果存在仍未解决的问题，烦请重新提交新的issue，必要时请带上原issue中讨论的有效信息，感谢大家的理解与配合。

**Comment by Stephenzero** [comment]
呵呵
