### ISSUE TITLE
[Feature] 支持自定义 Profiles 配置文件目录

### ISSUE THREAD

**Issue by leic4u** [clash-verge-rev/clash-verge-rev#696]
### 功能描述 / Feature description

该文件目录（ .config\io.github.clash-verge-rev.clash-verge-rev\profiles ）放的是远程订阅配置文件，或导入的本地手搓配置文件。

目前我是手搓配置，改一次配置文件后，我需要在五台设备上都去手动修改一遍，这有点太难受了。

如果可以自定义 Profiles 目录（目前在 .config/io.github.clash-verge-rev.clash-verge-rev/profiles 目录下），我可以把手搓文件放到一个同步目录下，每台设备的 Clash-Verge-Rev 只需要配置一次，将 profiles 目录指向同步目录即可。

类似于 Clash For Windows 的这个功能：

https://docs.gtk.pw/contents/profilespath.html

### 使用场景 / Use case

多台设备使用同一份手搓配置时，可以将 Profiles 指向如 Onedrive 等同步目录，使手搓配置能够在不同设备间自动同步。

**Comment by leic4u** [comment]
前序讨论：#653

**Comment by lucienshawls** [comment]
我提出一个暂时的workaround办法：软链接

简单来说，是：
1. 选择一个同步目录`$env:userprofile\Onedrive\clash\clash-verge-rev\profiles`，在其中存储配置文件
2. 移除cvr原本的`profiles`目录
3. 在cvr识别的路径建立名为`profiles`的软链接，指向同步目录的`profiles`。具体来说，管理员运行PowerShell（或开启开发者模式）并执行：
```ps
New-Item -Path "$env:userprofile\.config\io.github.clash-verge-rev.clash-verge-rev\profiles" -ItemType SymbolicLink -Value "$env:userprofile\Onedrive\clash\clash-verge-rev\profiles"
```

**Comment by leic4u** [comment]
> 我提出一个暂时的workaround办法：软链接
> 
> 简单来说，是：
> 
> 1. 选择一个同步目录`$env:userprofile\Onedrive\clash\clash-verge-rev\profiles`，在其中存储配置文件
> 2. 移除cvr原本的`profiles`目录
> 3. 在cvr识别的路径建立名为`profiles`的软链接，指向同步目录的`profiles`。具体来说，管理员运行PowerShell（或开启开发者模式）并执行：
> 
> ```postscript
> New-Item -Path "$env:userprofile\.config\io.github.clash-verge-rev.clash-verge-rev\profiles" -ItemType SymbolicLink -Value "$env:userprofile\Onedrive\clash\clash-verge-rev\profiles"
> ```

感谢，这是一个不错的办法。

**Comment by leic4u** [comment]
> 可以使用 Github Gist 功能实现多端配置同步，Gist 默认是只有知道链接的人才能访问到文件

感谢，做成订阅的方式我也考虑过，gist 可能一定程度上可以保证安全性。不过这个问题还有一个点，就是每次配置文件修改后都得手动往 gist 里复制一遍，还是稍微繁琐了点。

**Comment by MystiPanda** [comment]
这个无法支持，Tauri的各种api都有限制访问范围的选项，没有指定的目录是无权访问的，所以无法指定任意目录来作为应用目录。

**Comment by leic4u** [comment]
> 这个无法支持，Tauri的各种api都有限制访问范围的选项，没有指定的目录是无权访问的，所以无法指定任意目录来作为应用目录。

nyanpasu 已经支持自定义应用目录了。

**Comment by leic4u** [comment]
我好像无法 reopen 这个 issue 了 😂

**Comment by MystiPanda** [comment]
支持了之后后续使用 tauriapi 会各种受限，rev 不打算支持。

**Comment by you-hengh** [comment]
> ### 功能描述 / Feature description
> 该文件目录（ .config\io.github.clash-verge-rev.clash-verge-rev\profiles ）放的是远程订阅配置文件，或导入的本地手搓配置文件。
> 
> 目前我是手搓配置，改一次配置文件后，我需要在五台设备上都去手动修改一遍，这有点太难受了。
> 
> 如果可以自定义 Profiles 目录（目前在 .config/io.github.clash-verge-rev.clash-verge-rev/profiles 目录下），我可以把手搓文件放到一个同步目录下，每台设备的 Clash-Verge-Rev 只需要配置一次，将 profiles 目录指向同步目录即可。
> 
> 类似于 Clash For Windows 的这个功能：
> 
> https://docs.gtk.pw/contents/profilespath.html
> 
> ### 使用场景 / Use case
> 多台设备使用同一份手搓配置时，可以将 Profiles 指向如 Onedrive 等同步目录，使手搓配置能够在不同设备间自动同步。

国内不是有坚果云可以做同步吗 或者局域网同步软件也很多啊 有免费的 有付费的 这里就不推荐了 自行谷歌
