### ISSUE TITLE
[Feature] 代理组图标使用固定大小+缩放，以适应非等宽高图标的展示效果

### ISSUE THREAD

**Issue by dongchengjie** [clash-verge-rev/clash-verge-rev#697]
### 功能描述 / Feature description

由于分组图标只给了height:32px，而未对宽度和缩放进行控制
在**多数场景下**，图标的比例为**1:1**，多为一些App、服务商的logo
但是，有一种图标不是**1:1**的，或者1:1展示起来很丑，那就是**国旗**，采用**4:3**
**1:1**的国旗会显示不全，而**4:3**的会将分组名称挤到右边去，导致分组名称水平尺对不齐
直接上效果图吧，如图所示（下列采用的均为**SVG**）
<img width="897" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/bca6e205-630d-4337-bc85-065d4b07ae9e">

### 使用场景 / Use case

建议对宽度也进行样式控制，并加以样式缩放
这样对现有正常1:1的图标不会有影响，而对非等宽高比例的图标也能展示完整

**Comment by MystiPanda** [comment]
这里就应该只支持1:1的图标，只限制宽度进行缩放的话高度不一致也不合适

**Comment by dongchengjie** [comment]
> 这里就应该只支持1:1的图标，只限制宽度进行缩放的话高度不一致也不合适，限制宽度相比于限制高度影响又小一些，还是限制宽度吧。

嗯，我的意思就是这里限制为等宽等高，非等宽的就会缩放回到1:1，而对现有的1:1图标也不产生影响
