### ISSUE TITLE
[BUG] clash-verge-rev  设置代理后无法访问网络

### ISSUE THREAD

**Issue by laterdayi** [clash-verge-rev/clash-verge-rev#699]
### 问题描述 / Describe the bug

设置代理后无法访问网络
在原本的 clash 中，我端口设置的 7890
但 clash-verge-rev 中，我将端口都设置为 7890 ，则无法访问网络

如何能像 clash 统一设置为 7890

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/122137647/8f7933f5-9f08-41a0-973e-303dee7b728a)

### 复现步骤 / To Reproduce

设置代理后无法访问网络
在原本的 clash 中，我端口设置的 7890
但 clash-verge-rev 中，我将端口都设置为 7890 ，则无法访问网络

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/122137647/8f7933f5-9f08-41a0-973e-303dee7b728a)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

*

### 日志 / Log

*

**Comment by MystiPanda** [comment]
三个端口不能重复，把mixed设置为7890就可以了

**Comment by laterdayi** [comment]
@MystiPanda   
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/122137647/ea4c7067-7eeb-4dbe-8b03-1e6364aa9c98)
设置了mixined port 无法访问网络， 只有 socket 设置7890 才有效， 是有什么区别吗
