### ISSUE TITLE
[Feature]请求支持自定义配置文件目录

### ISSUE THREAD

**Issue by leic4u** [clash-verge-rev/clash-verge-rev#70]
看到 v1.4.3 将配置目录更改到安装文件夹下了，希望能把订阅文件（包括 rule-set 和 proxy-provider ）独立出来，支持自定义订阅文件存放目录。这样的话就可以把这个目录改到 Onedrive 等网盘的同步目录下，而不需要放整个 Protable 版本了，大大节省网盘空间（主要日志存这里实在太大了，占了我本就只有 5G 空间里的 500M。。。）

**Comment by wonfen** [comment]
日志可以设置启动清理。你说的独立出来是独立到哪里？没听懂。

**Comment by leic4u** [comment]
> 日志可以设置启动清理。你说的独立出来是独立到哪里？没听懂。

就是自定义一个文件目录，用来放订阅文件（包括 rule-set 文件和 proxy-provider 文件）。

因为我是手搓的本地订阅文件，想要每一次修改后，不用手动去同步一次。目前的方案就是把整个 protable 安装目录放到网盘里。

---

当前的配置文件与安装目录放到一起，有助于干净卸载，我个人认为是很赞的。

但希望能再把订阅文件单独支持下自定义目录，这样就可以只把手搓的本地订阅文件放到网盘去同步了。

**Comment by wonfen** [comment]
需求太小众，实现代价太高（主要是没空研究）。
建议在网盘直接配置需要同步的目录，把目录指向你的配置文件目录就行了。

**Comment by randyho** [comment]
配置存储目录能改成 clash-verge-rev 吗，现在是 io.github.clash-verge-rev.clash-verge-rev，有点太长了，强迫症难受。

**Comment by leic4u** [comment]
> 需求太小众，实现代价太高（主要是没空研究）。 建议在网盘直接配置需要同步的目录，把目录指向你的配置文件目录就行了。

不好搞，目前订阅文件分成了几个部分：

当前使用情况文件：`./profiles.yaml`
手搓订阅文件：`./profiles/aaa.yaml`
远端规则清单：`./ruleset/*.yaml`
远端订阅文件：`./bbb.yaml`
设置文件：`./verge.yaml`
以及 Clash-verge 生成的最终配置：`./clash-verge.yaml`

手动去给网盘指定同步的比较复杂，而且有些网盘对指定目录有数量限制，甚至像 Onedrive 好像还没法指定多个自定义目录。

我现在可以先同步整个 `.config` 目录，设置下日志只保留 7 天先用着。
但是期望大佬后续能把这个纳入计划，可以不着急，慢慢弄就行。
