### ISSUE TITLE
[BUG] macOS 使用 command + Q 快捷键退出后代理未被正确关闭

### ISSUE THREAD

**Issue by KKKayleX** [clash-verge-rev/clash-verge-rev#701]
### 问题描述 / Describe the bug

macOS 上使用  `command + Q` 快捷键退出 Clash Verge 时，系统网络配置中的代理未被正确关闭，必须在系统托盘或 Clash Verge 内部的设置中点击退出才能够关闭系统网络配置中的代理

### 复现步骤 / To Reproduce

1、正常开启 Clash Verge
2、使用 `command + Q` 快捷键退出
3、查看 macOS 系统设置 - 网络 - 详细信息 - 代理

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Sonoma 14.2

**Comment by KKKayleX** [comment]
慢了一拍，登记 issue 过程中有人提交了相同问题 #700

**Comment by MystiPanda** [comment]
点击退出就是正常操作，command+Q应该属于非常规退出，软件无法进行相关操作。

**Comment by FeiFei-SS** [comment]
> 点击退出就是正常操作，command+Q应该属于非常规退出，软件无法进行相关操作。
@MystiPanda 我在顶部栏点击的退出也不会清空代理

**Comment by MystiPanda** [comment]
> 必须在系统托盘或 Clash Verge 内部的设置中点击退出才能够关闭系统网络配置中的代理

他说可以

**Comment by FeiFei-SS** [comment]
我m1 arm macOS Monterey 12.7.3不得行，是最新版本。开启系统代理+tun（已授权meta内核）

**Comment by MystiPanda** [comment]
问题不一样就去开新issue，不要在关闭的issue里边说

**Comment by FeiFei-SS** [comment]
> 问题不一样就去开新issue，不要在关闭的issue里边说

我不久前刚刚开issue，你关闭了

**Comment by MystiPanda** [comment]
自己想想为什么关闭了
