### ISSUE TITLE
[Feature] 添加透明代理端口配置支持

### ISSUE THREAD

**Issue by Seidko** [clash-verge-rev/clash-verge-rev#702]
### 功能描述 / Feature description

添加[透明代理端口](https://wiki.metacubex.one/config/inbound/port/#_2)配置项支持。

### 使用场景 / Use case

在 Linux 下我想要使用 clash verge 管理 clash 透明代理及代理组。

我愿意为此 issue 提出 pr。

**Comment by MystiPanda** [comment]
我正在添加😄

**Comment by Seidko** [comment]
好的，那我不打扰了，感谢您的工作🙇

**Comment by Seidko** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/blob/af93e33e81d347364f2ad146d89aae6dbe97be47/src-tauri/src/config/clash.rs#L43-L48
tproxy 和 redir 端口应该默认禁用会好一点？

一个题外话，默认情况下开启 mixed 端口已经足够了，监听太多端口我认为不是一个好选择。

**Comment by MystiPanda** [comment]
> https://github.com/clash-verge-rev/clash-verge-rev/blob/af93e33e81d347364f2ad146d89aae6dbe97be47/src/components/setting/mods/clash-port-viewer.tsx#L121
> 
> 
> 这里 `setMixedPort` 写错了吧

是写错了，改了

**Comment by marsjane** [comment]
不知道可否具体介绍下如何用clash verge进行透明代理？一直想找到这方面的相关指南 此前我只看到一些用单独clash配合iptables的办法 要是clash verge可以直接做到那就太好了
