### ISSUE TITLE
[Feature] 防止误删除配置文件

### ISSUE THREAD

**Issue by howdareyo** [clash-verge-rev/clash-verge-rev#703]
### 功能描述 / Feature description

我有两个方案
1. 在删除时进行二次确认
2. 将删除的逻辑修改为移动至回收站, 这样可以找回 (我不清楚 linux 的各种桌面对此是否友好)

### 使用场景 / Use case

订阅界面的 打开文件 和 删除 选项是非常靠近的
在编辑自己配置文件时, 我会使用打开文件, 但有时会选中删除. 这项操作无法撤销, 且文件无法被找回

**Comment by MystiPanda** [comment]
感觉没必要，红色警示一下就可以了
