### ISSUE TITLE
[Feature] urltest 组所选节点断开时改进

### ISSUE THREAD

**Issue by howdareyo** [clash-verge-rev/clash-verge-rev#704]
### 功能描述 / Feature description

我有两个方案
1. 在手动测速后立刻强制选择测速最快的节点. (这个有时可以有时不可以, 似乎是存在一个最小的时间间隔)
2. 能够手动切换 urltest 组的节点. (在官方的 webgui 中可以实现, 这种切换是临时的, 到下次自动测速的时间依旧会切换到自动测速所测最快的节点)

### 使用场景 / Use case

urltest 组在所选节点突然断开时切换比较繁琐
例如 rule A 走 urltest 组 B , B 选中了节点 C, 节点 C 由于网络波动断开时, 那就必须使 A 走一个其他的策略组, 等下次 B 自动测速选择了最快的, 再切换为 B, 我觉得较为繁琐
在官方的 webgui 中, 即便节点 C 断开, 我也可以手动选择到节点 D, 然后等下次测速时再自动选择测速最快的

**Comment by MystiPanda** [comment]
#840
