### ISSUE TITLE
[BUG] 延迟测试动画消失

### ISSUE THREAD

**Issue by ngo5** [clash-verge-rev/clash-verge-rev#705]
### 问题描述 / Describe the bug

切换clash verge非代理界面延迟测试动画消失。

### 复现步骤 / To Reproduce

代理界面切换到其他界面（如设置界面），再回到代理界面点击“延迟测试”，此时延迟测试动画消失。

要恢复延迟测试动画需要收回节点列表或者最小化clash verge。

视频演示：https://pixeldrain.com/u/bAtmVqAx

先前反馈：https://github.com/clash-verge-rev/clash-verge-rev/issues/142

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows10 22H2

### 日志 / Log

[2024-03-21-0251.log](https://github.com/clash-verge-rev/clash-verge-rev/files/14671426/2024-03-21-0251.log)

**Comment by wonfen** [comment]
最新的PR修复了，请测试alpha版本。

**Comment by ngo5** [comment]
> 最新的PR修复了，请测试alpha版本。

alpha没这个问题了。
