### ISSUE TITLE
[Feature] edge web-view dependency

### ISSUE THREAD

**Issue by APT-ZERO** [clash-verge-rev/clash-verge-rev#706]
### 功能描述 / Feature description

Currently clash-verge need windows edge browser's web view
Is it possible for you to remove this dependency?

### 使用场景 / Use case

so we can use it on modified windows 10/11

**Comment by MystiPanda** [comment]
It is impossible.

**Comment by MystiPanda** [comment]
Yes, I know, but I don't want to do that. If you need to, please compile it yourself.

**Comment by MystiPanda** [comment]
@APT-ZERO I don't even want to provide a portable version at all.
