### ISSUE TITLE
[Feature] 希望UI界面中的“日志”查看能支持正则

### ISSUE THREAD

**Issue by Troray** [clash-verge-rev/clash-verge-rev#707]
### 功能描述 / Feature description

![Snipaste_2024-03-21_09-16-52](https://github.com/clash-verge-rev/clash-verge-rev/assets/16841721/be2f08e8-68ce-4c6e-961a-aaf53ff1b096)
如上图位置，希望能支持正则匹配，哪怕是最基础的类似 `abc.*123|123.*abc` 这样的也可以。

### 使用场景 / Use case

方便从众多日志中快速筛选出想要查看的条目。

**Comment by dongchengjie** [comment]
支持一下，交互按钮可以参考下面这样子，然后可以考虑把过滤框封装成Component
![a_waifu2x_16x_png](https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/f8ba50a0-4f7b-4c33-8f29-e310a622b12b)
