### ISSUE TITLE
[BUG] 流量信息图在开关代理后停止更新(TUN模式 or 系统代理)

### ISSUE THREAD

**Issue by EllisWw** [clash-verge-rev/clash-verge-rev#708]
### 问题描述 / Describe the bug

流量信息图在开关代理后停止更新(TUN模式 or 系统代理)

使用版本 [Clash Verge Rev v1.5.9](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.5.9)

### 复现步骤 / To Reproduce

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/163995435/21602937-6530-4d15-b8ca-3a76df132424)
1.关闭系统代理 or TUN模式
2.再次打开系统代理 or TUN模式，此时会发现流量信息图不再更新
3.需要重启应用后才会再次更新

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

该问题与机场无关

**Comment by Paulgudring** [comment]
btw, 更新内核之后，内核重启也会如此。没有流量信息、没有日志。

**Comment by TGSAN** [comment]
这个问题我也有遇到，但是我是TUN模式下电脑锁屏再解锁会出现流量信息不更新，重启内核没用，需要重启应用
