### ISSUE TITLE
UI设定建议(程序埠及托盘)

### ISSUE THREAD

**Issue by pscchiang** [clash-verge-rev/clash-verge-rev#711]
### 功能描述 / Feature description

程序埠：
1. 建议程序埠是否显示图标改为可选项目。
2. 最小化窗口后隐藏程序埠图标

托盘：
1. 建议调整初始设定图标： 
      - 无代理:线框
      - 系统代理: 实色加字P
      - Tun代理：实色加T
       以下一些示例，颜色忽略：
![C2](https://github.com/clash-verge-rev/clash-verge-rev/assets/87739315/f599197d-8b6b-4c9c-9ceb-977cb567c12e)

![C1](https://github.com/clash-verge-rev/clash-verge-rev/assets/87739315/285f2f07-9e8b-4d62-aa61-c2ce9e908d4e)

![c3](https://github.com/clash-verge-rev/clash-verge-rev/assets/87739315/043c0603-732f-4656-b83c-2f5ff57d09e7)

### 使用场景 / Use case

N/A

**Comment by MystiPanda** [comment]
1. 程序坞图标已经删了，装过alpha再来提issue
2. 托盘图标可以自定义

**Comment by DullJZ** [comment]
删去程序坞图标的同时，使用Command+Tab切换窗口的feature也消失了

如果不能同时保留两个feature，建议提供选项开关，由用户自行决定使用哪个feature

**Comment by MystiPanda** [comment]
窗口关闭的情况下就应该无法使用command+tab切换

**Comment by DullJZ** [comment]
现在的情况是，即使窗口没有关闭，command+tab也没有verge的图标

**Comment by molamooo** [comment]
> 现在的情况是，即使窗口没有关闭，command+tab也没有verge的图标

我用第三方的窗口切换软件（如AltTab）可以在删去程序坞图标，且窗口打开的情况下进行cmd+tab切换。使用macos默认的窗口切换确实无法切到clash verge，不过可以用spotlight/alfred等方式唤醒。
