### ISSUE TITLE
[Feature] GUI的实时日志给出更多级别的产出

### ISSUE THREAD

**Issue by Paulgudring** [clash-verge-rev/clash-verge-rev#712]
### 功能描述 / Feature description

目前的日志管理有些混乱。首先对于用户而言有三个可调节的日志级别：

1. 配置文件中的`log-level`键，对应的是控制台输出，跑裸核的命令行可见。
2. clash setting，也即GUI设置左侧这一排，用于覆写配置文件，log level覆写的是上面这个，作为跑起verge后的输出；然而我都用GUI了，也不用再开个命令行看这部分输出了吧。
3. verge setting，这是控制gui app的设置。`Miscellaneous` 下的 `app log level` 对应的应是GUI界面的日志输出、app目录下写入log文件。

对应地，日志产出来源有以下几种：

1. 命令行输出，跑裸核可以见，或者使用api `curl -H http://${controller-api}/logs`。由配置文件的`log-level`和覆写控制。
2. GUI的日志。理论上应该由`Miscellaneous` - `app log level` 限制最高输出级别，然而并没有，仍然仅输出info级别。
3. 写入app目录的log文件，由`Miscellaneous` - `app log level` ，这一部分是能做到的。

这些问题在 #448 #616 有所反馈。期待第②输出可以改进，使之对应、以及提供比`info`更高级别的日志。

### 使用场景 / Use case

日常使用需要Debug。现在我一边使用verge，一边用metacubexd的webui来debug

1. 这样的做法，相当于verge仅仅拿来跑核、隐藏windows跑裸核的命令行。
2. webui的渲染效率很低，debug的条目一多就非常卡。
3. 如果看app目录下的log，不够实时、方便。

**Comment by wonfen** [comment]
已经完成。
