### ISSUE TITLE
[BUG] 关闭clash verge后clash-verge-service服务依旧运行

### ISSUE THREAD

**Issue by fuyongzk** [clash-verge-rev/clash-verge-rev#713]
### 问题描述 / Describe the bug

关闭clash verge后clash-verge-service服务依旧运行

### 复现步骤 / To Reproduce

关闭clash verge后clash-verge-service服务依旧运行

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 23h2

### 日志 / Log

不会

**Comment by fuyongzk** [comment]
<img width="483" alt="搜狗截图20240321134842" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/120019530/11f47d93-1c31-489d-b1e1-91c6f80f93ed">

**Comment by MystiPanda** [comment]
@fuyongzk 正常的，不是bug，service是开机启动的

**Comment by Chasing-Aurora** [comment]
虚拟网卡，系统代理，开机自启，静默启动 先四个全关闭
然后在 services.msc中关闭Clash Verge Service
在任务管理器“详细信息”关闭下面三个：
clash-verge.exe
clash-verge-service.exe
verge-mihomo.exe
就可以啦⭐
