### ISSUE TITLE
[BUG] DOH共存问题

### ISSUE THREAD

**Issue by waterrr** [clash-verge-rev/clash-verge-rev#714]
### 问题描述 / Describe the bug

无法与Adguard共存，国内直连无法进行DNS解析，国外域名正常
系统使用Adguard的DOH进行dns查询，发现与软件会发生冲突（断网），开不开TUN都一样，想问一下有什么办法能够共存？
我不知道如何设置

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Apple M1 14.4 (23E214)

### 日志 / Log

03-21 15:09:27WARNING
[TCP] dial 🎯 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:58535(firefox) --> h.trace.qq.com:443 error: dns resolve failed: lookup h.trace.qq.com on 192.168.3.1:53: server misbehaving
03-21 15:09:27WARNING
[TCP] dial 🎯 全球直连 (match DomainSuffix/cn) 127.0.0.1:58540(firefox) --> sqt.gtimg.cn:443 error: dns resolve failed: lookup sqt.gtimg.cn on 192.168.3.1:53: server misbehaving
03-21 15:09:27WARNING
[TCP] dial 🎯 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:58545(firefox) --> i.news.qq.com:443 error: dns resolve failed: lookup i.news.qq.com on 192.168.3.1:53: server misbehaving
03-21 15:09:27WARNING
[TCP] dial 🎯 全球直连 (match DomainSuffix/cn) 127.0.0.1:58540(firefox) --> sqt.gtimg.cn:443 error: dns resolve failed: lookup sqt.gtimg.cn on 192.168.3.1:53: server misbehaving
03-21 15:09:28WARNING
[TCP] dial 🎯 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:58545(firefox) --> i.news.qq.com:443 error: dns resolve failed: lookup i.news.qq.com on 192.168.3.1:53: server misbehaving

**Comment by Jenichia** [comment]
不要用 AdGuard 的 DoH，要改你在浏览器里面或者 Clash 配置文件里面改，AdGuard 的 DNS 功能在电脑上用意义不大。

另外你把 AdGuard 的 DNS 功能关掉看看还能不能共存，说不定是你自己设置有问题。

**Comment by Steven52065** [comment]
发现了类似的问题
系统为Windows11，更新到最新
clash-verge最新版
在Windows的设置里给网络设置上doh后会导致clash无法正常解析dns，表现为clash连接中只有ip，没有域名信息，分流也会受到影响
将Windows设置中的doh关掉后一切恢复正常

之前一直使用着Windows的doh一直正常，或许是使用了easyconnect或者更新系统的缘故，在昨天出现了这个问题
