### ISSUE TITLE
[Feature] 可以向winget和homebrew中添加包吗？

### ISSUE THREAD

**Issue by zippozeng** [clash-verge-rev/clash-verge-rev#718]
### 功能描述 / Feature description

通过平台包管理器安装clash-verge-rev

### 使用场景 / Use case

在windows中通过winget安装clash-verge-rev
在mac中通过homebrew安装clash-verge-rev
linux中的pacman、apt安装clash-verge-rev

**Comment by Meng5in** [comment]
winget的你可以自己写，不难，之前clash-verge是有的。

**Comment by xishang0128** [comment]
@zippozeng archlinux的archlinuxcn源一直都有verge-bin,自行配置,官方源是进不了的,至于apt也是一样,官方源没法进
