### ISSUE TITLE
[BUG] 测速模块自定义网站 Favicon.ico 缓存问题

### ISSUE THREAD

**Issue by niehui** [clash-verge-rev/clash-verge-rev#719]
### 问题描述 / Describe the bug

添加新的测速网站和 Favicon 时，程序还会自动调用最初的 Favicon 文件，更新了两个版本之后还是存在，不随重新启动软件或开关机变化。

朴素的经验判定是文件缓存名的问题，几乎所有网站 Favicon 大家都是这个名字，是否需要给他们随机一个本地储存名。

https://www.youtube.com/favicon.ico
https://www.cloudflare.com/favicon.ico
https://www.google.com/favicon.ico

![WX20240321-191416@2x](https://github.com/clash-verge-rev/clash-verge-rev/assets/33514748/d9aa12f4-bcc2-4b0b-b4cc-fb7af609778a)

### 复现步骤 / To Reproduce

N/A

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

13.6.1 (22G313)

### 日志 / Log

N/A

**Comment by MystiPanda** [comment]
fixed

**Comment by choi006** [comment]
微软图标：https://www.microsoft.com/favicon.ico?v2
@MystiPanda 哈哈。得处理一下这种情况

**Comment by MystiPanda** [comment]
@choi006 不考虑了
