### ISSUE TITLE
[BUG] 在HY节点，youtube无法播放

### ISSUE THREAD

**Issue by bosco8833** [clash-verge-rev/clash-verge-rev#72]
在mac平台，当clash verge选择hysteria节点的时候，无法播放youtube，google首页也被block。但是在mac平台上用clashx meta，选择hy节点的时候， 没这个问题。Mac OS 版本是 Ventura 13.6.1. 从clash verge从1.3.8到1.4.2都有这个问题。

**Comment by wonfen** [comment]
你可以试试 https://verge.狗狗加速.com/#/register?code=oaxsAGo6
他家也是hy节点，我这边并没有这个问题。

**Comment by bosco8833** [comment]
测试了狗狗加速的HY节点，一样的问题，无法播放youtube.  Mac上的clashx pro,  clashx meta, sing-box上HY节点都可以正常播放youtube。

**Comment by MystiPanda** [comment]
把应用目录下的文件全部删除之后再次导入订阅测试
