### ISSUE TITLE
[Feature] 重写功能去广告和更多玩法

### ISSUE THREAD

**Issue by Ardin963** [clash-verge-rev/clash-verge-rev#720]
### 功能描述 / Feature description

以后会出类似于quantumult x的重写功能吗？这样就可以去广告和解锁tiktok之类的

### 使用场景 / Use case

去广告
解锁tiktok
更多玩法

**Comment by MystiPanda** [comment]
要提需求就描述清楚，我又没用过quantumult x，我不知道什么叫重写功能。

**Comment by MystiPanda** [comment]
你连字都懒的打，那我也只能是懒得做。

**Comment by choi006** [comment]
quanX去广告看了源码就是一堆reject规则而已

**Comment by choi006** [comment]
tiktok在PC端直接分流到对应地区就行。也没有必要

**Comment by pheotry** [comment]
不就是reject吗。就服你们这种iOS，总是起新名字

**Comment by wuyanjiuce** [comment]
可以出想像tash一样内置rewrite和mitm功能吗,因为现有方法不能很好的去广告

**Comment by Dragon1573** [comment]
> 像 Stash 一样内置 Rewrite 和 MITM 功能

Clash Verge Rev 使用 Mihomo Core 作为内核，内核侧没有这一类功能。
