### ISSUE TITLE
[BUG] 特定的网站无法访问

### ISSUE THREAD

**Issue by Seth2333** [clash-verge-rev/clash-verge-rev#721]
### 问题描述 / Describe the bug

无法访问nikke-jp.com

### 复现步骤 / To Reproduce

开启tun模式下，其他网站不论国内外访问均正常，打开nikke-jp.com的时候浏览器报错ERR_CONNECTION_CLOSED

同一订阅同一节点开启全局模式可以正常访问，在手机端走同样的规则可以正常访问。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

WIN11 23H2 22635.3350

### 日志 / Log

[TCP] dial China-Websites (match IPCIDR/127.0.0.0/8) 198.18.0.1:2748(msedge.exe) --> nikke-jp.com:443 error: connect failed: dial tcp 127.0.0.1:443: connectex: No connection could be made because the target machine actively refused it.

**Comment by MystiPanda** [comment]
这种个别网站访问不了不可能是软件的问题，自己找原因。
