### ISSUE TITLE
测试页样式按钮问题[BUG] 

### ISSUE THREAD

**Issue by yangcore** [clash-verge-rev/clash-verge-rev#723]
### 问题描述 / Describe the bug

<img width="800" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/20217483/bb478502-045f-4d46-bd7a-40717cb4cdea">

### 复现步骤 / To Reproduce

打开就是

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

10.15.7 (19H2026)

### 日志 / Log

打开就是

**Comment by MystiPanda** [comment]
看起来是系统版本太低了，webview不支持某些现代css语法，升级系统吧，不会专门做适配。
