### ISSUE TITLE
[Feature] URL Schema支持订阅响应头profile-web-page-url

### ISSUE THREAD

**Issue by dongchengjie** [clash-verge-rev/clash-verge-rev#725]
### 功能描述 / Feature description

多数鸡场的订阅都提供了**profile-web-page-url**这个响应头，一般是需要发送带有clash字样的UA（至少我使用过的多家鸡场都支持）
前面几个URL Schema都已经支持了，唯独**profile-web-page-url**暂未实现
<img width="977" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/20d06425-d8ef-432a-a054-3906a838c34d">
CFW就有现成的例子，右键profile，如果有profile-web-page-url则context-menu多出一个menu-item
<img width="467" alt="无标题2" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/00a04895-b902-414b-a3e0-38a1be6f40a4">

### 使用场景 / Use case

最主要的使用场景就是，鸡场的账户和订阅使用两套系统，账户频繁换域名，没书签就可能不能及时续费导致失联，而订阅服务只提供接口较为隐蔽，可以通过订阅返回的主页找到鸡场

**Comment by wonfen** [comment]
挺好的提议。
