### ISSUE TITLE
导入链接不行，直接进入cmd

### ISSUE THREAD

**Issue by msd5m1988** [clash-verge-rev/clash-verge-rev#726]
### 问题描述 / Describe the bug

![QQ截图20240322080800](https://github.com/clash-verge-rev/clash-verge-rev/assets/124551564/5c7e758e-0915-43fb-801a-9e75e7d2fa90)

### 复现步骤 / To Reproduce

![QQ截图20240322080856](https://github.com/clash-verge-rev/clash-verge-rev/assets/124551564/725fa81d-2b9f-4a18-997a-3cc1c2086b01)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

没有看

**Comment by dongchengjie** [comment]
这个调用的是[url-scheme](https://docs.gtk.pw/contents/urlscheme.html#url-scheme)实现的，相当于请求了链接
```
clash://install-config?url=<encoded URI>
```

**Comment by MystiPanda** [comment]
好一个没有看，你爱看不看
