### ISSUE TITLE
win10 1.5.9版本 左上角New升级按钮点击没反应

### ISSUE THREAD

**Issue by glIrving** [clash-verge-rev/clash-verge-rev#728]
### 问题描述 / Describe the bug

升级到1.5.9 后 左上角New升级按钮点击没反应

### 复现步骤 / To Reproduce

省略

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows10

### 日志 / Log

省略

**Comment by dongchengjie** [comment]
兄弟把你的[BUG] Label加上帖别被删了
这个情况属实，我也是到设置里手动点击“检查更新”弹出changelog页面才更新到1.5.10的

**Comment by MystiPanda** [comment]
修过了
