### ISSUE TITLE
[Feature] dashboard无法连接

### ISSUE THREAD

**Issue by jiyuxiang01** [clash-verge-rev/clash-verge-rev#729]
### 功能描述 / Feature description

在线的仪表盘中无法连接到电脑后端

### 使用场景 / Use case

我有一台小主机，我需要控制里面的节点切换，操作系统是windows 10，我在我的电脑下，无法通过局域网IP和公网IP访问后端，我的小主机是全暴露在公网情况下，只能在小手机的浏览器中本地访问

**Comment by dongchengjie** [comment]
首先，你的Label加错了，你提交的不是BUG吗
另外，你说的dashboard是WEB UI吧，访问不了有两种情况：
1. 访问的电脑与clash是同一台机器，考虑浏览器的广告拦截器，我的就被uBlock Origin给拦截了，手动添加忽略
2. 访问的电脑与clash是不是一台机器，检查external-controller。注意是软件设置里的external-controller，不是配置文件里的。默认给的是127.0.0.1:9097，也就是说其他机器是连不上的

**Comment by jiyuxiang01** [comment]
> 首先，你的Label加错了，你提交的不是BUG吗 另外，你说的dashboard是WEB UI吧，访问不了有两种情况：
> 
> 1. 访问的电脑与clash是同一台机器，考虑浏览器的广告拦截插件（adguard、adblock、uBlock Origin之类的）。我的就被uBlock Origin给拦截了，手动将其忽略
> 2. 访问的电脑与clash是不是一台机器，检查external-controller。注意是软件设置里的external-controller，不是配置文件里的，软件会覆写。`设置`->`外部控制`，默认给的是127.0.0.1:9097，也就是说非**127.0.0.1**是连不上的，改成0.0.0.0就是任意ip都可以连接
> 
> 很明显你大概率是情况2，解决了就自行关闭吧

你说的我知道，还是无法访问，浏览器打开ip加端口显示这个，{"message":"Unauthorized"}，密码我自己设置的还是没法连接

**Comment by dongchengjie** [comment]
我试了一下，发现无法设置成0.0.0.0，你点击保存后，再打开又变成127.0.0.1
我有点印象貌似设置成0.0.0.0有BUG，所以限制了不让这么设置
你配置文件里0.0.0.0，然后内核裸连试一下吧
再者，可以在你的小主机里配置端口转发，这样就是本机访问本机了

**Comment by jiyuxiang01** [comment]
> 

> 我试了一下，发现无法设置成0.0.0.0，你点击保存后，再打开又变成127.0.0.1 我有点印象貌似设置成0.0.0.0有BUG，所以限制了不让这么设置 你配置文件里0.0.0.0，然后内核裸连试一下吧 再者，可以在你的小主机里配置端口转发，这样就是本机访问本机了

这一点应该是有点问题，设置以后，他在那个设置里面，应该可以找到一个当前配置文件你可以发现里面是改了，我的最终实现目的是向openclash实现公网访问，因为我是有公网IP的

**Comment by dongchengjie** [comment]
> 这一点应该是有点问题，设置以后，他在那个设置里面，应该可以找到一个当前配置文件你可以发现里面是改了，我的最终实现目的是向openclash实现公网访问，因为我是有公网IP的

覆写后配置的在这里看
<img width="605" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/894b440d-3cf9-4fbe-b3a6-e5d4697316f7">
看样子只能内核启动或者端口转发了，你有公网IP的话应该有服务商的控制台，配个端口转发应该不难

**Comment by jiyuxiang01** [comment]
> > 这一点应该是有点问题，设置以后，他在那个设置里面，应该可以找到一个当前配置文件你可以发现里面是改了，我的最终实现目的是向openclash实现公网访问，因为我是有公网IP的
> 
> 覆写后配置的在这里看 <img alt="无标题" width="605" src="https://private-user-images.githubusercontent.com/37543964/315877847-894b440d-3cf9-4fbe-b3a6-e5d4697316f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODE1MzIsIm5iZiI6MTcxMTA4MTIzMiwicGF0aCI6Ii8zNzU0Mzk2NC8zMTU4Nzc4NDctODk0YjQ0MGQtM2NmOS00ZmJlLWIzYTYtZTVkNDY5NzMxNmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA0MjAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMjdiNDc4YTE4MjM0NmI2YTYxOTEzNGViYjI1ZWU3NGQ4ODIzMGM4YjZmOWNlNzQxNTFiMmJhNThlY2EwZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._H6R321uM3sZriXU7ygIacSn7uUIYTiMT5CpdpCwrxg"> 看样子只能内核启动或者端口转发了，你有公网IP的话应该有服务商的控制台，配个端口转发应该不难
> 
> 完蛋完蛋，我算是知道为什么不让配置成0.0.0.0了，因为verge本身也是一个WEB UI 貌似只判定了不让写成0.0.0.0，我乱改一通改成0.0.0.1，改成功的瞬间就崩了，连不上controller，重启也还是一样😭😭😭
> 
> <img alt="无标题" width="663" src="https://private-user-images.githubusercontent.com/37543964/315879308-db45f26f-8fae-4cc0-9422-2954326ce385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODE1MzIsIm5iZiI6MTcxMTA4MTIzMiwicGF0aCI6Ii8zNzU0Mzk2NC8zMTU4NzkzMDgtZGI0NWYyNmYtOGZhZS00Y2MwLTk0MjItMjk1NDMyNmNlMzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA0MjAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NDUxNjBmNjNhNDc1NTFhNzQ5N2MyMzIwOThlNDY2MDVjZTNkMGRkM2U5ZmE0NDRlMzAwNzA0M2U4ZjhmMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0RhoxO9p2AKsd1jo24nKpbVaYCtXFlkxvxx8-yL2_0I">
> 后续，好了我改回来了，修改%userprofile%\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev\config.yaml里面的配置
> 
> 我用我的云服务试了下，控制台启用端口9097端口，发现即使配置成127.0.0.1也可以连的上啊，你用的啥UI面板
> 
> <img alt="无标题" width="1280" src="https://private-user-images.githubusercontent.com/37543964/315883726-54437400-0dd0-4ab0-818f-413b3a037563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODE1MzIsIm5iZiI6MTcxMTA4MTIzMiwicGF0aCI6Ii8zNzU0Mzk2NC8zMTU4ODM3MjYtNTQ0Mzc0MDAtMGRkMC00YWIwLTgxOGYtNDEzYjNhMDM3NTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA0MjAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMmFmYTY2MWZhNWQ3ZTcyZThmYTJkMGM3MzRiYTZhMjk2MjM3NWU0YzMwYjhhMjRmODE4NmQ5MjA3NTk0MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DOGl2M5deW5mS_LOxbLnvty_OlUdoW5Y8lzKfsZqC3M">

全部都试过一遍，都不行，你的云服务也是window系统吗？

**Comment by dongchengjie** [comment]
> 全部都试过一遍，都不行，你的云服务也是window系统吗？

淦，原来是面板有缓存，连上了我本地的服务，要手动选择切换后端，发现连不上，正在找原因😅
<img width="203" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/8c720900-d49e-49d7-a005-b06f9224f6b5">

**Comment by jiyuxiang01** [comment]
> > 全部都试过一遍，都不行，你的云服务也是window系统吗？
> 
> 淦，原来是面板有缓存，连上了我本地的服务，要手动选择切换后端，发现连不上，也是{"message":"Unauthorized"}，正在找原因😅
> 
> <img alt="无标题" width="203" src="https://private-user-images.githubusercontent.com/37543964/315885238-8c720900-d49e-49d7-a005-b06f9224f6b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODE4OTUsIm5iZiI6MTcxMTA4MTU5NSwicGF0aCI6Ii8zNzU0Mzk2NC8zMTU4ODUyMzgtOGM3MjA5MDAtZDQ5ZS00OWQ3LWEwMDUtYjA2ZjkyMjRmNmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA0MjYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MWE3ZDBkZDY0MWE5ZGFjNDdlNWQwOGVkMTA2MjUxNTRiNGQ3YmQyZTBlOWM1YmI2MjcyMjhhNzkxNWJiNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jQbAgo5oWD7smndJpQIV1f1IIKm2in03nEtGH7ev3S0"> <img alt="无标题" width="801" src="https://private-user-images.githubusercontent.com/37543964/315885567-cf0ef0f5-230a-4d2c-8e9d-b7e07eff4600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODE4OTUsIm5iZiI6MTcxMTA4MTU5NSwicGF0aCI6Ii8zNzU0Mzk2NC8zMTU4ODU1NjctY2YwZWYwZjUtMjMwYS00ZDJjLThlOWQtYjdlMDdlZmY0NjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA0MjYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNGQ1ZDM4YTAzMWVmMzk3MGNjODY1YzIwZmIwMGQxNjRiZjMyN2RmNWUyZGJmZDM2MjkyMDFhNDcyNzk1NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PcXkOCUmT7ocDAQe7WrgrrakHCnZXOXpUm5r8Fuz8wA">

跟我一样的问题

**Comment by dongchengjie** [comment]
> 跟我一样的问题

发现原因了，是浏览器的安全策略导致的，请求压根就没发出去。
Mixed Content: The page at 'https://d.metacubex.one/#/setup' was loaded over HTTPS, but requested an insecure resource 'http://xxxxxxxxx:9097/'. This request has been blocked; the content must be served over HTTPS.
这个错误是由浏览器安全策略引起的。它发生在网页加载期间，因为网页使用了HTTPS协议加载，但同时试图请求一个非安全的资源（HTTP协议）。浏览器通常会拒绝加载这样的非安全资源，以确保用户的安全和隐私。

SSL得开443端口，HTTPS协议要求使用域名，我没有测试不了😅

**Comment by xishang0128** [comment]
@dongchengjie https可以使用ip证书,不需要域名

**Comment by jiyuxiang01** [comment]
> > 跟我一样的问题
> 
> 发现原因了，是浏览器的安全策略导致的，**请求压根就没发出去**。 Mixed Content: The page at 'https://d.metacubex.one/#/setup' was loaded over HTTPS, but requested an insecure resource 'http://xxxxxxxxx:9097/'. This request has been blocked; the content must be served over HTTPS. 这个错误是由浏览器安全策略引起的。它发生在网页加载期间，因为网页使用了HTTPS协议加载，但同时试图请求一个非安全的资源（HTTP协议）。浏览器通常会拒绝加载这样的非安全资源，以确保用户的安全和隐私。
> 
> SSL得开443端口，HTTPS协议要求使用域名，我没有测试不了😅 倒是还有一个解决办法，WEB UI是开源的，把代码下载下来本地跑静态html估计可以

请问大佬，有什么办法能直接跑在本地吗？我就想用http访问，搞证书我觉得有点麻烦

**Comment by dongchengjie** [comment]
@xishang0128 配起来太麻烦了，又是买CA，又是下载证书文件，还得启服务器，玩不来😅

**Comment by jiyuxiang01** [comment]
> @xishang0128 配起来太麻烦了，又是买CA，又是下载证书文件，还得启服务器，玩不来😅

对头，要买域名还要买证书

**Comment by jiyuxiang01** [comment]
> > > 跟我一样的问题
> > 
> > 
> > 发现原因了，是浏览器的安全策略导致的，**请求压根就没发出去**。 Mixed Content: The page at 'https://d.metacubex.one/#/setup' was loaded over HTTPS, but requested an insecure resource 'http://xxxxxxxxx:9097/'. This request has been blocked; the content must be served over HTTPS. 这个错误是由浏览器安全策略引起的。它发生在网页加载期间，因为网页使用了HTTPS协议加载，但同时试图请求一个非安全的资源（HTTP协议）。浏览器通常会拒绝加载这样的非安全资源，以确保用户的安全和隐私。
> > SSL得开443端口，HTTPS协议要求使用域名，我没有测试不了😅 倒是还有一个解决办法，WEB UI是开源的，把代码下载下来本地跑静态html估计可以
> 
> 请问大佬，有什么办法能直接跑在本地吗？我就想用http访问，搞证书我觉得有点麻烦

网络上基本是linux搭建

**Comment by dongchengjie** [comment]
> 请问大佬，有什么办法能直接跑在本地吗？我就想用http访问，搞证书我觉得有点麻烦

找到一个可以用的本地面板，但是你要启动web容器，使用使用file://协议会关联不上js文件
https://github.com/haishanh/yacd/releases/tag/v0.3.8
我已经测试过了，可以脸上远程
<img width="1203" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/9b427e52-2a2b-41f8-a962-79f59c6acee3">

**Comment by jiyuxiang01** [comment]
> > 请问大佬，有什么办法能直接跑在本地吗？我就想用http访问，搞证书我觉得有点麻烦
> 
> 找到一个可以用的本地面板，但是你要启动web容器，使用使用file://协议会关联不上js文件 https://github.com/haishanh/yacd/releases/tag/v0.3.8 我已经测试过了，可以脸上远程 <img alt="无标题" width="1203" src="https://private-user-images.githubusercontent.com/37543964/315890290-9b427e52-2a2b-41f8-a962-79f59c6acee3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODM3MDksIm5iZiI6MTcxMTA4MzQwOSwicGF0aCI6Ii8zNzU0Mzk2NC8zMTU4OTAyOTAtOWI0MjdlNTItMmEyYi00MWY4LWE5NjItNzlmNTljNmFjZWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA0NTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OGI4YmIxMDRkNGU2Y2ZhYWM4YmI4NWY4NGU1YmRmNjYwZjk0OTEyNTQzMTk0NTQ3MGFlM2Y2NzQ0ZWNiNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i8LXl8vyloKqWWNE5svlr95TdTDvP_3l9Y6kc3E351A">

你好，有教程吗？

**Comment by dongchengjie** [comment]
> 你好，有教程吗？

https://github.com/MetaCubeX/metacubexd/releases/download/v1.136.0/compressed-dist.tgz
https://github.com/haishanh/yacd/releases/download/v0.3.8/yacd.tar.xz
这两个都可以，推荐第一个，第二个停更了

最简单的办法就是nignx启动个web容器，不想下载软件的话windows本地好像有个IIS服务也能反向代理吧

**Comment by jiyuxiang01** [comment]
> > 你好，有教程吗？
> 
> https://github.com/MetaCubeX/metacubexd/releases/download/v1.136.0/compressed-dist.tgz https://github.com/haishanh/yacd/releases/download/v0.3.8/yacd.tar.xz 这两个都可以，推荐第一个，第二个停更了
> 
> 最简单的办法就是nignx启动个web容器，不想下载软件的话windows本地好像有个IIS服务也能反向代理吧
> 
> @jiyuxiang01 简单描述一下IIS吧：
> 
> 1. 打开控制面板。打开“控制面板” -> “程序和功能” -> “打开或关闭Windows功能”。勾选“Internet Information Services”，保存。
> 2. Win+S搜索IIS,打开
> 3. 右键网站，添加网站吗，如图：端口自己随便，物理路径指向index.html所在路径
> 
> <img alt="无标题" width="880" src="https://private-user-images.githubusercontent.com/37543964/315893806-760c7a2d-e727-4527-9669-869f3743c068.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTU5NzAsIm5iZiI6MTcxMTA5NTY3MCwicGF0aCI6Ii8zNzU0Mzk2NC8zMTU4OTM4MDYtNzYwYzdhMmQtZTcyNy00NTI3LTk2NjktODY5ZjM3NDNjMDY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA4MjExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNTY0ODRiZDdiMzI5MDdhYTEyOWY4MTYzMDY2YzczZThjZmEyNDczZjhlNmUxOTY3YTg1YTE0NDBmNTQ2ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.81QaVh3QhJ_yftqUtlyx0PEZoX3f3CRRP8YpCdp91U0"> 4. 保存就可以访问了 5. 打开配置的地址:端口，就好了。如果打开有页面但是没内容，ctrl+f5强制刷新一下。选择切换后端，或者直接访问/setup <img alt="无标题" width="1192" src="https://private-user-images.githubusercontent.com/37543964/315893930-a850a27e-7789-404e-8121-ca691efa7610.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTU5NzAsIm5iZiI6MTcxMTA5NTY3MCwicGF0aCI6Ii8zNzU0Mzk2NC8zMTU4OTM5MzAtYTg1MGEyN2UtNzc4OS00MDRlLTgxMjEtY2E2OTFlZmE3NjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA4MjExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNDI3MTEzYWRmOTVhM2I2NjkwZDIxOWFiYWUyMzhjZTIyNjg1YTlmZmI5OGRlMDRjMjIwOTZlODhiNWI0OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kiE5r9vT0xusRyxNX4d1gg-Qk94s2p3EjuOGCcc_jfA">

非常感谢，搭建过程发生好多问题，思路是没错的，我也成功搭建了，谢谢大佬

**Comment by Long0x0** [comment]
Allows running static webpage resources (such as Clash-dashboard) on Clash API, path is **API address/ui**.
```
external-ui: /path/to/ui/folder
```

https://wiki.metacubex.one/en/config/general/#external-user-interface

**Comment by tanmoumou252** [comment]
局域网内设备浏览器挂上这台运行clash设备的http/sock5代理,设备浏览器代理取消忽略127.0.0.1  
那么浏览器访问的127.0.0.1,实际上是正在运行clash的设备的localhost  
至于能不能V4公网访问就不清楚了,我的浏览器用的代理插件似乎解析不了纯V6的域名

**Comment by jiyuxiang01** [comment]
> 局域网内设备浏览器挂上这台运行clash设备的http/sock5代理,设备浏览器代理取消忽略127.0.0.1 那么浏览器访问的127.0.0.1,实际上是正在运行clash的设备的localhost 至于能不能V4公网访问就不清楚了,我的浏览器用的代理插件似乎解析不了纯V6的域名

现在代理基本都有忽略本机地址，不然很容易造成回环代理，我的问题很清楚解决了，就是https和http协议之间的问题

**Comment by DorBlack** [comment]
把浏览器的安全策略关了就行。
在浏览器地址栏输入：
`chrome://flags/#block-insecure-private-network-requests //将 "Block insecure private network requests" 由 'Defualt' 改为 'Disabled';`

**Comment by LennoC** [comment]
遇到同样的问题，关闭浏览器安全策略无效。
最后发现只要简单的在hostname那里加上`http://`就能连上了。
#1200

**Comment by bGZo** [comment]
hello, 我还能提供一个思路，在 https 下请求局域网 http 不成功的情况，chrome 系的浏览器允许网站设置允许不安全连接，edge 如下：
![图片](https://github.com/user-attachments/assets/f0727207-6be9-4430-8d87-2906a089e69e)
这对我而已可以正常运作
![图片](https://github.com/user-attachments/assets/83da72ba-ff1c-450f-b3be-fe55ebad893d)

**Comment by jiyuxiang01** [comment]
> hello, 我还能提供一个思路，在 https 下请求局域网 http 不成功的情况，chrome 系的浏览器允许网站设置允许不安全连接，edge 如下： ![图片](https://private-user-images.githubusercontent.com/57313137/369670747-f0727207-6be9-4430-8d87-2906a089e69e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5OTY0NzcsIm5iZiI6MTcyNjk5NjE3NywicGF0aCI6Ii81NzMxMzEzNy8zNjk2NzA3NDctZjA3MjcyMDctNmJlOS00NDMwLThkODctMjkwNmEwODllNjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDA5MDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NjY3NGNkNWM2OTRiYWQ5YjczMzA3YjU5YWU5ZGQ2NDI2NjM5OWE4YzZjMDMxNjg2NzkyNjA5MjJlN2Y0OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3wjNMBaeVZ6ZKeCWNpgEbFeCd06ZGdsF9RLDvh_jfbw) 这对我而已可以正常运作 ![图片](https://private-user-images.githubusercontent.com/57313137/369670831-83da72ba-ff1c-450f-b3be-fe55ebad893d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5OTY0NzcsIm5iZiI6MTcyNjk5NjE3NywicGF0aCI6Ii81NzMxMzEzNy8zNjk2NzA4MzEtODNkYTcyYmEtZmYxYy00NTBmLWIzYmUtZmU1NWViYWQ4OTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDA5MDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NzhmODU1YmNlNDUxY2ZmZTc3NzdlNjAwMjFkOGQ1Yjc3OTdjYTM4ODc4ZjhmN2Q3YjE5ZDRjNWU2ZTcyZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AG1c00I3baUHcihto0jiGlfWIvu95Zu5PmJ6XTK4nX4)

可以的，前面有人提过

**Comment by zhuziyi1989** [comment]
就是一个跨域问题，在内网访问时一般较为安全，可放弃使用`https`协议访问前端。

1. 在软件配置文件夹找到文件`config.yaml`，如图以 MacOS 为例

<img width="641" height="483" alt="Image" src="https://github.com/user-attachments/assets/5180e940-ad83-45a7-a022-8591cd3f1427" />

2. 尝试将 `allow-origins`改成如下配置

```
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - tauri://localhost
  - http://tauri.localhost
  - http://yacd.metacubex.one
  - http://metacubex.github.io
  - http://board.zash.run.place
  - https://yacd.metacubex.one
  - https://metacubex.github.io
  - https://board.zash.run.place
```

3. 尝试将`external-controller`改成`0.0.0.0`监听所有的 IPV4

```
external-controller: 0.0.0.0:9097
```

4. 最后重启软件，并使用`http`协议访问前端即可。

> 参考：[Access-Control-Allow-Origin](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Reference/Headers/Access-Control-Allow-Origin)

**Comment by suibianzai** [comment]
> ### 功能描述 / Feature description
> 在线的仪表盘中无法连接到电脑后端
> 
> ### 使用场景 / Use case
> 我有一台小主机，我需要控制里面的节点切换，操作系统是windows 10，我在我的电脑下，无法通过局域网IP和公网IP访问后端，我的小主机是全暴露在公网情况下，只能在小手机的浏览器中本地访问



> > 首先，你的Label加错了，你提交的不是BUG吗 另外，你说的dashboard是WEB UI吧，访问不了有两种情况：
> > 
> > 1. 访问的电脑与clash是同一台机器，考虑浏览器的广告拦截插件（adguard、adblock、uBlock Origin之类的）。我的就被uBlock Origin给拦截了，手动将其忽略
> > 2. 访问的电脑与clash是不是一台机器，检查external-controller。注意是软件设置里的external-controller，不是配置文件里的，软件会覆写。`设置`->`外部控制`，默认给的是127.0.0.1:9097，也就是说非**127.0.0.1**是连不上的，改成0.0.0.0就是任意ip都可以连接
> > 
> > 很明显你大概率是情况2，解决了就自行关闭吧
> 
> 你说的我知道，还是无法访问，浏览器打开ip加端口显示这个，{"message":"Unauthorized"}，密码我自己设置的还是没法连接

和你一样的问题，局域网面板打不开，可以试试用在线面板。在”设置“界面选“网页界面”，里面有各个面板的地址，直接选一个面板的网址，点右边的跳转按钮就能打开了，比如我选的zash面板，点下面这个按钮，浏览器自动会跳转到面板的外网地址（不知道是不是这么说）

<img width="930" height="714" alt="Image" src="https://github.com/user-attachments/assets/df7bf896-7482-41ad-a8c2-2cf077d4e498" />

<img width="1052" height="718" alt="Image" src="https://github.com/user-attachments/assets/6cb8a381-0ca2-4cc2-9b42-f5571c5fe907" />

打开之后地址栏的地址是https://board.zash.run.place/#/proxies
