### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Caligogo** [clash-verge-rev/clash-verge-rev#73]
系统为win11 22H2，卸载旧版，安装1.4.3（解压方式）。

在杂项设置中修改默认测试链接为[Google 的gstatic网络联通性测试地址](https://www.gstatic.com/generate_204)后，测试节点的延迟不正常。
美西直连节点竟然也能237ms，其他节点也不合理，概不赘述。

**Comment by wonfen** [comment]
并无问题，了解下clash的 unifed-delay。
