### ISSUE TITLE
[BUG] 程序最大化/最小化不会切换图标BUG

### ISSUE THREAD

**Issue by dongchengjie** [clash-verge-rev/clash-verge-rev#730]
### 问题描述 / Describe the bug

双击程序窗体顶部（或者右键选择最大化），右上角的最大化/最小化按钮不会切换成“最小化”
应用最大化有三种方式，其中**方式2**和**方式3**不会切换右上角的最大化/最小化图标（关闭按钮左边的按钮）
1. 点击右上角最大化按钮
2. 双击窗体顶部
3. 右键窗体，选择“最大化”

### 复现步骤 / To Reproduce

双击窗体使程序最大化(或者右键选择最大化)，可以发现右上角的按钮图标没有toggle
而点击最大化按钮的方式则会正常toggle

<img width="1280" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/2d82d62d-28b2-4948-b1d8-dd5c9d7ec001">

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 21h2

### 日志 / Log

GUI相关，无log

**Comment by MystiPanda** [comment]
这个问题确实存在，有时间我修一下

**Comment by dongchengjie** [comment]
> 这个问题确实存在，有时间我修一下

好的，另外还有几率出现右键后“最大化”那一个选项置灰不可点击，重新点击空白处再右键才能恢复的BUG

**Comment by wonfen** [comment]
已修复，下载最新alpha试试。

**Comment by lucienshawls** [comment]
最新的1.6.0虽然解决了这两种情况下最大化按钮的显示错误，但是没有解决另一种情况导致的错误，即：

在上一次主程序窗口被关闭之前处于最大化模式的前提下，通过点击任务栏图标、或右击任务栏图标并打开面板时，窗口会最大化显示，但是相应按钮仍然显示为最大化图标而不是向下还原图标。

此时若点击此图标或双击窗口，窗口实际会向下还原，按钮保持最大化图标不变。若保持窗口不关闭，则在此之后，无论如何最大化或向下还原窗口，按钮显示的图标均正确；但是一旦在最大化显示状态下关闭窗口，则下次打开窗口时按钮图标显示不正确。

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/82591976/de50c4e0-ee34-4646-888a-d1189824c70c)
