### ISSUE TITLE
火狐加载新网页总是报错

### ISSUE THREAD

**Issue by ENIAC1729** [clash-verge-rev/clash-verge-rev#731]
### 问题描述 / Describe the bug

在火狐加载新网页的时候总是出现诸如
{
建立安全连接失败

连接到 domain.com 时发生错误。PR_END_OF_FILE_ERROR

错误代码：PR_END_OF_FILE_ERROR

    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。
}
但是利用CFW则不会出现该问题
在论坛上得到的答案有
1.DNS污染（但是我用CFW就没事）
2.加密协议对不上

### 复现步骤 / To Reproduce

点开一个新的网页，火狐就会弹出错误代码：PR_END_OF_FILE_ERROR，但是刷新后就可以正常加载

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10

### 日志 / Log

03-22 10:52:00INFO
[TCP] 127.0.0.1:4673(firefox.exe) --> zh.wikipedia.org:443 match Match using 节点选择[日本-优化-GPT]
下面是py发送request请求中出现的报错
{requests.exceptions.SSLError: HTTPSConnectionPool(host='inboxes-com.p.rapidapi.com', port=443): Max retries exceeded with url: /inboxes/[kryptos42@replyloop.com](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))}

**Comment by ENIAC1729** [comment]
![2024-03-22_10-57-36](https://github.com/clash-verge-rev/clash-verge-rev/assets/108004193/1117b7cd-593c-469a-a78a-d14a79fa07c0)

**Comment by wonfen** [comment]
看下是不是火狐指定了单独的dns服务器？导致没有使用clash的dns解析。

**Comment by ENIAC1729** [comment]
> 看下是不是火狐指定了单独的dns服务器？导致没有使用clash的dns解析。
我之前在一些论坛也问过，一些人也指出了DNS的问题，但是本人小白，不太懂如何修改
火狐以及clash的DNS,
另外我在写一个api调用脚本的时候也会出现equests.exceptions.SSLError: HTTPSConnectionPool(host='inboxes-com.p.rapidapi.com', port=443): Max retries exceeded with url: /inboxes/kryptos42@replyloop.com (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))}
但是关掉梯子就没事了(可能是我节点的问题)

**Comment by ENIAC1729** [comment]
> 这个问题我也遇到过，怎么解决的呢？我换机场换协议节点，关闭tun模式，就好了。火狐默认dns是关闭的。所以不用管的。 希望对你有用。
结案了，火狐的DNS关了就没事了，虽然不知道他有啥用

**Comment by Stephenzero** [comment]
证书问题，我是Outlook会报错

**Comment by ENIAC1729** [comment]
> 证书问题，我是Outlook会报错

啥意思，我用clash会缓解一下，但是也会出问题

**Comment by atbug** [comment]
好像我开着clash-verge-rev（规则或者全局模式）都没法打开这个：
https://www.libtorrent.org/

用直连模式就正常。

**Comment by rubbit233** [comment]
一样啊，已经关闭火狐的proxy以及doh，在tun的规则模式下还是会有这个报错，这时候开一次全局，刷新一下就好了，然后再切换到规则，也是能访问网页了，之后指不定啥时候又会出现这个报错，很烦啊，

**Comment by Albresky** [comment]
> 这个问题我也遇到过，怎么解决的呢？我换机场换协议节点，关闭tun模式，就好了。火狐默认dns是关闭的。所以不用管的。 希望对你有用。

换一个节点就好了

**Comment by hdulsh** [comment]
> > 这个问题我也遇到过，怎么解决的呢？我换机场换协议节点，关闭tun模式，就好了。火狐默认dns是关闭的。所以不用管的。 希望对你有用。
> 
> 换一个节点就好了

我也是遇到这情况，换一个节点就好了，请问这是节点的问题吗

**Comment by kwdiwt** [comment]
> > 这个问题我也遇到过，怎么解决的呢？我换机场换协议节点，关闭tun模式，就好了。火狐默认dns是关闭的。所以不用管的。 希望对你有用。
> 
> 结案了，火狐的DNS关了就没事了，虽然不知道他有啥用

dns关了还是不行

**Comment by Dragon1573** [comment]
> 好像我开着clash-verge-rev（规则或者全局模式）都没法打开这个： https://www.libtorrent.org/
> 
> 用直连模式就正常。

还要看你订阅审计，一些场会封 torrent ，连这个 qBittorrent 之类的官网都进不去，更不要提实际使用 BT 传输了

**Comment by mdogwoop** [comment]
有没有办法可以使火狐的dns和clash tun共存?

**Comment by handsomelittledong** [comment]
<img width="441" height="64" alt="Image" src="https://github.com/user-attachments/assets/cdd15660-6d7c-42ad-afde-8398d570391d" />

把这个关了就行了

**Comment by m4rsquake** [comment]
仍然没有办法解决吗

**Comment by langzigyq** [comment]
> 一样啊，已经关闭火狐的proxy以及doh 在tun的规则模式下还是会有这个报错，这时候开一次全局，刷新一下就好了，然后再切换到规则，也是能访问网页了，之后指不定啥时候又会出现这个报错 有时候换个节点就好了 很烦啊

谢谢，有用，开一次全局就好了
