### ISSUE TITLE
[Feature] 图标显示异常

### ISSUE THREAD

**Issue by Noostop** [clash-verge-rev/clash-verge-rev#734]
### 功能描述 / Feature description

启动之后图标遮挡住苹果 logo
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/41714012/a6d37be7-10e2-406a-bbf9-078731e37fcf)

### 使用场景 / Use case

mac m1

**Comment by MystiPanda** [comment]
这是bug不是feature
