### ISSUE TITLE
[Feature] 通过Proxy-provider添加的代理集合订阅能否增加“通过代理更新”的设置

### ISSUE THREAD

**Issue by KKFantasy** [clash-verge-rev/clash-verge-rev#736]
### 功能描述 / Feature description

对于通过Proxy-provider添加的代理集合订阅，可以选择“直连更新”或者“通过代理更新”。

### 使用场景 / Use case

部分机场订阅链接需要通过代理更新。

**Comment by dongchengjie** [comment]
貌似verge更新订阅是直接调用内核的[API](https://wiki.metacubex.one/api/#_12)，并不负责下载？只有profile导入那部分才是可以控制的？

**Comment by KKFantasy** [comment]
> 貌似verge更新订阅是直接发送PUT请求调用内核的[API](https://wiki.metacubex.one/api/#_12)，并不负责下载？只有profile导入那部分才是可以控制的？

好吧，如果是这样的话，那我就去内核那边提个issue

**Comment by MystiPanda** [comment]
内核对于provider好像默认是通过代理更新的，你在provider界面点击更新之后可以在日志里面看到相关的请求的，如果没有走代理你添加相关的规则就行。
