### ISSUE TITLE
[Feature] 代理排序建议

### ISSUE THREAD

**Issue by DrZhang1208** [clash-verge-rev/clash-verge-rev#737]
### 功能描述 / Feature description

使用默认排序，不能快速看到延迟最低的节点；按延迟排序容易找不到“自动选择”等功能性节点，建议可以固定显示这些功能性节点，或者允许用户自定义置顶节点选项。

### 使用场景 / Use case

节点选择更加快速

**Comment by MystiPanda** [comment]
没必要
