### ISSUE TITLE
[BUG] 开启 Proxifier 导致 clash verge crash

### ISSUE THREAD

**Issue by NatsuGaOwatta** [clash-verge-rev/clash-verge-rev#738]
### 问题描述 / Describe the bug

开启 Proxifier 导致 clash verge crash

### 复现步骤 / To Reproduce

1. start Proxifier.exe
2. open clash verge dashboard and crash :(

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Version 22H2 (OS Build 22621.3296)

### 日志 / Log

not found...

**Comment by MystiPanda** [comment]
@NatsuGaOwatta 什么他妈的叫 not found， 没日志滚蛋，自己修去，右键菜单的日志目录你是瞎了？
