### ISSUE TITLE
[Feature] 测速时自动清理上次的记录

### ISSUE THREAD

**Issue by houzixiashanxiedaima** [clash-verge-rev/clash-verge-rev#74]
希望能在每次测速时，自动清理节点上次测速的记录，方便及时查看本次测速的结果。

**Comment by wonfen** [comment]
不知道你说的是什么测速？

**Comment by houzixiashanxiedaima** [comment]
> 不知道你说的是什么测速？

就是一键测试节点延迟的时候

<img width="841" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/15197429/a640d799-adce-43f3-b72d-497ffa9b6888">
