### ISSUE TITLE
[Feature] 希望添加启动时默认是否打开代理与记录上一次打开状态可选

### ISSUE THREAD

**Issue by CyanHwang** [clash-verge-rev/clash-verge-rev#741]
### 功能描述 / Feature description

希望设置中添加一个按钮，启动时默认打开或关闭系统代理或记录上一次打开状态。

### 使用场景 / Use case

系统代理打开的情况下直接关机，而开机的时候没有自动启动clash，所有网页都会打不开，再次打开clash恢复正常。

可不是每次启动都想打开代理模式（因为上一次打开时是开启状态，这次打开只是想解决打不开网页的问题）

因此希望增加该可选项。

望采纳，多谢！

**Comment by MystiPanda** [comment]
现在是会记住上次的状态的，软件关闭时也会自动关闭系统代理，但是直接关机，软件属于非正常关闭，无法执行关闭软件前的操作，所以这个没有办法。
