### ISSUE TITLE
[BUG] 测试页面添加的测试网站的图标大部分都变成微软的图标了

### ISSUE THREAD

**Issue by volcanolin** [clash-verge-rev/clash-verge-rev#744]
### 问题描述 / Describe the bug

我在测试页面添加了一些网站用于测试连接延迟，之前的版本网站图标都是正常的，从1.5.9版本开始大部分图标都变成微软的图标了。
![Snipaste_2024-03-23_19-47-28](https://github.com/clash-verge-rev/clash-verge-rev/assets/36153325/5388d457-43dc-42b8-8dca-071412905dee)
![Snipaste_2024-03-23_19-47-20](https://github.com/clash-verge-rev/clash-verge-rev/assets/36153325/48928238-98d9-42e9-86bf-0d7061f7462f)
![Snipaste_2024-03-23_19-47-10](https://github.com/clash-verge-rev/clash-verge-rev/assets/36153325/8a5fffcc-b07d-45fe-a995-fdf06ed9c4a6)
![Snipaste_2024-03-23_19-46-57](https://github.com/clash-verge-rev/clash-verge-rev/assets/36153325/1c5ad105-c19e-49c0-847d-4bf84adb74d4)
![Snipaste_2024-03-23_19-46-27](https://github.com/clash-verge-rev/clash-verge-rev/assets/36153325/0e6a0269-e617-4ea9-b966-1a9dfaa2da1b)

### 复现步骤 / To Reproduce

我尝试新建了一些测试网站，图标又是正常的，把那些图标不正常的网站删除再重建，图标还是微软的。
![Snipaste_2024-03-23_20-00-29](https://github.com/clash-verge-rev/clash-verge-rev/assets/36153325/504fce2c-fe2b-4d45-b36b-a2a2bde8c309)
![Snipaste_2024-03-23_20-00-35](https://github.com/clash-verge-rev/clash-verge-rev/assets/36153325/d15ff27c-5a82-4555-a7db-5dd73b4f5502)
![Snipaste_2024-03-23_20-00-18](https://github.com/clash-verge-rev/clash-verge-rev/assets/36153325/f3e124b5-2091-421a-bb27-58173a849069)
![Snipaste_2024-03-23_20-00-51](https://github.com/clash-verge-rev/clash-verge-rev/assets/36153325/3567e26d-2b22-4d7c-aeba-fe70b9b5e684)
![Snipaste_2024-03-23_20-00-56](https://github.com/clash-verge-rev/clash-verge-rev/assets/36153325/ed0941f5-86db-4008-94b4-c1d0257cf956)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 23H2

### 日志 / Log

没有找到测试网站的相关日志

**Comment by MystiPanda** [comment]
@volcanolin 修过了，alpha版本试试

**Comment by volcanolin** [comment]
> @volcanolin 修过了，alpha版本试试

好嘞，收到，谢谢
