### ISSUE TITLE
[BUG] Arch上clash开启TUN模式后存在问题

### ISSUE THREAD

**Issue by Kyereach** [clash-verge-rev/clash-verge-rev#746]
### 问题描述 / Describe the bug

环境ArchLinux ， 采用AUR稳定版安装。

Clash开启Tun模式后，点击 ”重启应用“ ，或者 ”系统注销或重启“ 后，面板显示空白，更改任何设置都会报错 “无法连接” 。
需要手动点击 “重启内核” 后才可以正常启动，推测是clash内核没有正确启动有关。

经过尝试，不开启tun模式不会存在这个问题。

另外,发现clash gui 绘制有小问题，存在两排 “最小化/最大化/关闭” 的选项卡，注意看图3标注位置

以下是错误时的截图：
![屏幕截图_20240324_113704](https://github.com/clash-verge-rev/clash-verge-rev/assets/104889995/f60fb6a3-8241-43e5-ab42-15e40c1de12b)
![屏幕截图_20240324_113746](https://github.com/clash-verge-rev/clash-verge-rev/assets/104889995/2041018c-472c-4167-8887-fefd214e6f6b)
![屏幕截图_20240324_113747](https://github.com/clash-verge-rev/clash-verge-rev/assets/104889995/c4ba4f25-c8b8-4b6e-a9a2-ee9c1b888920)

下方上传了 重启应用 &重启内核 全过程的log 

### 复现步骤 / To Reproduce

开启TUNmode，点击clash “更多 > 重启应用” 选项，等待面板打开，（有几率复现）
 

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

ArchLinux

### 日志 / Log

[2024-03-24-1121.log](https://github.com/clash-verge-rev/clash-verge-rev/files/14734263/2024-03-24-1121.log)

**Comment by xiao-k233** [comment]
而且我用着一打开ui就非常卡
纯wayland环境

**Comment by jinzhongjia** [comment]
目前使用archlinuxcn版本打包一切正常，wayland环境下（非xwayland）

**Comment by Kyereach** [comment]
我是在官方的aur源下载的，不是cn源，希望至少能解决下ui问题。我的桌面环境是plasma（wayland）

**Comment by Sisyphe42** [comment]
同样问题及环境，看启动日志发现症结并解决了，不知是否类似：pacman -S appmenu-gtk-module

**Comment by witt-bit** [comment]
> 我是在官方的aur源下载的，不是cn源，希望至少能解决下ui问题。我的桌面环境是plasma（wayland）

Manjaro 在X11环境下不存在标题栏问题，使用了全局菜单

**Comment by whuailin** [comment]
archlinux 现在还是有这个问题
