### ISSUE TITLE
[提问]请问Script里调用console.log会在哪里打印呢？

### ISSUE THREAD

**Issue by bling-yshs** [clash-verge-rev/clash-verge-rev#749]
### 功能描述 / Feature description

[提问]请问Script里调用console.log会在哪里打印呢？
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/41812674/e0a6ca58-ca15-4679-ae1c-e00f4dcbb477)

### 使用场景 / Use case

[提问]请问Script里调用console.log会在哪里打印呢？

**Comment by dongchengjie** [comment]
盲猜一波会在控制台打印，而不是日志页面，现在可以在设置里打开DEV工具了

**Comment by bling-yshs** [comment]
没事了，我已经知道了，这个params就是整个config，我像操作js对象一样修改config就行了，例如
```
delete params["proxy-providers"] //就是删除整个proxy-providers
```
所以打不打印什么的已经不重要了

**Comment by MystiPanda** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/152463842/0486e6d7-04df-4b26-9f30-8a67621b3647)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/152463842/36af01e8-f872-4221-93f7-b1dc6d1e091a)

**Comment by young-3303** [comment]
打印不了main方法的参数，导致啥也看不到

**Comment by Dragon1573** [comment]
```javascript
function main(config, profileName) {
  console.info(`当前配置：${profileName}`);
    return config;
}
```

<img width="1375" height="790" alt="Image" src="https://github.com/user-attachments/assets/0ce8fddb-34f7-4da6-9e9d-8f16921caefc" />

Oh really?

**Comment by young-3303** [comment]
> function main(config, profileName) {
>   console.info(`当前配置：${profileName}`);
>     return config;
> }
> <img alt="Image" width="1375" height="790" src="https://private-user-images.githubusercontent.com/49941141/579237824-0ce8fddb-34f7-4da6-9e9d-8f16921caefc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzY0MTAzNjAsIm5iZiI6MTc3NjQxMDA2MCwicGF0aCI6Ii80OTk0MTE0MS81NzkyMzc4MjQtMGNlOGZkZGItMzRmNy00ZGE2LTllOWQtOGYxNjkyMWNhZWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDE3VDA3MTQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MTA4YTY4YTZjMDM3ODZhZTgzZWIzMGEyZTgxOGQ5MzRkMDk5Yjc2YWNjNjVkNDcxNmQzYjc3YjVhZWY1ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.r83M-SI8T8F11UlhDGrXO-zL7bovfcjJ3s5y6-S1MsI">
> Oh really?

它只能接受一个参数，

<img width="558" height="117" alt="Image" src="https://github.com/user-attachments/assets/93b4b541-79e3-42ae-8813-741923a85f00" />

<img width="312" height="126" alt="Image" src="https://github.com/user-attachments/assets/3a8d1213-7642-4ae8-b0b3-655586b73a34" />

**Comment by JasonMing** [comment]
> ![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/152463842/0486e6d7-04df-4b26-9f30-8a67621b3647) ![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/152463842/36af01e8-f872-4221-93f7-b1dc6d1e091a)

我去。。。在这个地方。。。这是真的蚌埠住。。。
