### ISSUE TITLE
[Feature]自动更新后安装到默认地址

### ISSUE THREAD

**Issue by purwindisagoodman** [clash-verge-rev/clash-verge-rev#75]
第一次安装时选择了自定义地址。运行后检测后更新，然后就自动安装到了系统盘默认路径下。为什么不会安装到上次安装的自定义目录中呢？
1.4.2升级1.4.3.

**Comment by MystiPanda** [comment]
因为appid有变动，所以更新日志里面说了，这个版本建议卸载重装。

**Comment by wonfen** [comment]
卸载再重装就行了。
