### ISSUE TITLE
[BUG] 配置开机自启往启动项添加的文件路径不支持符号链接

### ISSUE THREAD

**Issue by Vixb1122** [clash-verge-rev/clash-verge-rev#750]
### 问题描述 / Describe the bug

使用 scoop 安装的 clash-verge-rev 会使用符号链接。生成的开机自启项不支持符号链接。

### 复现步骤 / To Reproduce

1. 使用 scoop 包管理器安装 clash-verge-rev。该包管理器会使用符号链接将 current 目录链接到对应版本的目录。
```
❯❯ clash-verge-rev  ls

    Directory: D:\Scoop\apps\clash-verge-rev

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           2024/3/22     8:27                1.5.10
l-r--           2024/3/22     8:27                current -> D:\Scoop\apps\clash-verge-rev\1.5.10
```
2. 打开软件，启用开机自启开关
3. 查看启动项注册表，发现生成的地址不支持符号链接
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/17810492/6f6507d0-346d-4e02-aa9d-bc391876aa88)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 23H2，22631.3296

### 日志 / Log

添加自启项，无 log。
1. 我看同样使用 tauri 开发的 [pot](https://github.com/pot-app/pot-desktop) 使用的官方自启插件 [tauri-plugin-autostart](https://github.com/tauri-apps/tauri-plugin-autostart) 是支持符号链接的。
2. 可能本项目使用的 [auto-launch](https://github.com/zzzgydi/auto-launch) 不支持，或者使用错误？

**Comment by MystiPanda** [comment]
tauri-plugin-autostart用的也是auto-launch

**Comment by Vixb1122** [comment]
简单看了下代码，发现 tauri-plugin-authstart 获取 app_path 的方式不太一样。
##### tauri-plugin-authstart
https://github.com/tauri-apps/tauri-plugin-autostart/blob/a8455f120ad801d828f91528f1b4ca47d00c8ba3/src/lib.rs#L111-L112
```Rust
#[cfg(windows)]
builder.set_app_path(&current_exe.display().to_string());
```
##### clash-verge-rev
https://github.com/clash-verge-rev/clash-verge-rev/blob/68691b91ef37d303496701f5a6484579a0d2632a/src-tauri/src/core/sysopt.rs#L158-L162
