### ISSUE TITLE
[BUG] 日志显示问题

### ISSUE THREAD

**Issue by xp9477** [clash-verge-rev/clash-verge-rev#751]
### 问题描述 / Describe the bug

'clash设置-日志等级'调整为Warn，'Verge设置-杂项设置-App日志等级'调整为Warn后，日志显示界面还是在输出INFO

### 复现步骤 / To Reproduce

1

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

1

**Comment by dongchengjie** [comment]
clash配置里的日志级别是覆写配置文件的，杂项里的日志级别是过滤获取到的内核日志的
日志页面的信息应该是调用[/logs](https://wiki.metacubex.one/api/#logs)方法直接向内核获取的，估计获取回来后没有进行filter
