### ISSUE TITLE
[BUG] 在i3wm下界面无法显示

### ISSUE THREAD

**Issue by zouyonghe** [clash-verge-rev/clash-verge-rev#752]
### 问题描述 / Describe the bug

在i3wm下右键打开面板无法显示界面

### 复现步骤 / To Reproduce

启动软件，打开界面

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

arch_rolling

### 日志 / Log

(clash-verge:24622): Gdk-CRITICAL **: 09:09:50.695: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

** (clash-verge:24622): WARNING **: 09:09:58.011: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

**Comment by Aloxaf** [comment]
将 webkit2gtk 从 2.44.0-1 降级到 2.42.5-2 后恢复正常

**Comment by zouyonghe** [comment]
脑壳疼，先用AppImageLauncher吧

**Comment by marsjane** [comment]
我也遇到了…请教一下我现在用appimage 怎么让它自动在后台运行啊 用命令的话还占用一个终端窗口

**Comment by zouyonghe** [comment]
建议先安装旧版吧，因为我发现也有不少其他软件收这个依赖影响无法使用。
https://archive.archlinux.org/packages/w/webkit2gtk/webkit2gtk-2.42.5-1-x86_64.pkg.tar.zst
然后在/etc/pacman.conf里面加个IgnorePkg=webkit2gtk

**Comment by marsjane** [comment]
啊 你是指哪个旧版啊？yay -S clash-verge-rev-bin=xxx 么？（话说我试过旧的1.3.8也不行）还是说webkit2git 但是我不会安装这玩意…我不会降级==

在 2024年3月27日，16:20，邹永赫 ***@***.***> 写道：

﻿

建议先安装旧版吧，因为我发现也有不少其他软件收这个依赖影响无法使用。
https://archive.archlinux.org/packages/w/webkit2gtk/webkit2gtk-2.42.5-1-x86_64.pkg.tar.zst
然后在/etc/pacman.conf里面加个IgnorePkg=webkit2gtk

**Comment by marsjane** [comment]
> 建议先安装旧版吧，因为我发现也有不少其他软件收这个依赖影响无法使用。 https://archive.archlinux.org/packages/w/webkit2gtk/webkit2gtk-2.42.5-1-x86_64.pkg.tar.zst 然后在/etc/pacman.conf里面加个IgnorePkg=webkit2gtk

哦哦好 我试试看 以前的版本不用管 直接安装你发的这个版本就行是吗

**Comment by zouyonghe** [comment]
安装依赖的旧版，因为它的依赖因为升级导致的问题，所以安装旧版依赖，wget或者curl下来，然后paru -U ./webkit2gtk-2.42.5-1-x86_64.pkg.tar.zst 就可以了

**Comment by zouyonghe** [comment]
其他的软件，clash-verge-rev-bin或者别的受影响的软件都没关系，用最新版就ok，依赖用旧版，暂时ignore掉不升级，等它稳定了再说升级的事情

**Comment by marsjane** [comment]
多谢多谢！！

**Comment by marsjane** [comment]
我按照你建议的操作以后，直接打不开了哎，我试了命令直接运行，报错缺失一个lib，然后我就用pacman装了一下， 好像没有用…我也尝试安装的时候做cleanbuild，不过好像也是一样，还是报这个错
```
clash-verge 
clash-verge: error while loading shared libraries: libjxl.so.0.9: cannot open shared object file: No such file or directory
```

**Comment by zouyonghe** [comment]
https://archive.archlinux.org/packages/w/webkit2gtk/webkit2gtk-2.42.5-2-x86_64.pkg.tar.zst
装这个包试试？

**Comment by marsjane** [comment]
哇可以了，牛的！

**Comment by a937983423** [comment]
> Arch KDE6 下观察到同样的行为，比较奇怪的是原先是没问题的。 降级后也无法使用，但 AppImage 版能正常使用，怀疑是依赖炸了。
> 
> 确实是依赖问题，将 webkit2gtk 从 2.44.0-1 降级到 2.42.5-2 后恢复正常，这个 bug 好像比较新，都搜不到任何相关信息，先这么凑合用着吧。是

因为tauri框架不能设置代理的问题，不能设置代理然后tauri就会不显示界面，archlinux就是那样的，要手动设置代理

**Comment by yai-dev** [comment]
ArchLinux with Gnome 46 has same issue, downgrade webkit2gtk to 2.42.5 is working :)

**Comment by q234rty** [comment]
请问各位使用什么显卡？我怀疑和 nvidia 有关。/ Please post your video card info as I suspect this is related to nvidia.
请同时尝试将 `WEBKIT_DISABLE_DMABUF_RENDERER=1` 环境变量写入 `/etc/environment`. / Please try adding `WEBKIT_DISABLE_DMABUF_RENDERER=1` into `/etc/environment`.

**Comment by zouyonghe** [comment]
> 请问各位使用什么显卡？我怀疑和 nvidia 有关。/ Please post your video card info as I suspect this is related to nvidia. 请同时尝试将 `WEBKIT_DISABLE_DMABUF_RENDERER=1` 环境变量写入 `/etc/environment`. / Please try adding `WEBKIT_DISABLE_DMABUF_RENDERER=1` into `/etc/environment`.

通过修改环境变量解决了吗？我是4090

**Comment by q234rty** [comment]
> 通过修改环境变量解决了吗？我是4090

有 nvidia 用户回报说修改环境变量解决了其问题。

**Comment by yai-dev** [comment]
> 请问各位使用什么显卡？我怀疑和 nvidia 有关。/ Please post your video card info as I suspect this is related to nvidia. 请同时尝试将 `WEBKIT_DISABLE_DMABUF_RENDERER=1` 环境变量写入 `/etc/environment`. / Please try adding `WEBKIT_DISABLE_DMABUF_RENDERER=1` into `/etc/environment`.

NVIDIA 3060 Ti，驱动版本为：550.67

**Comment by Horange321** [comment]
export WEBKIT_DISABLE_DMABUF_RENDERER=1
nv3090 550.67 cuda 12.4
已解决

**Comment by zouyonghe** [comment]
使用/etc/environment写入WEBKIT_DISABLE_DMABUF_RENDERER=1，同样已解决
