### ISSUE TITLE
[BUG] 关闭开机自启动后，重新启动windows，还是会自动打开

### ISSUE THREAD

**Issue by rwerplus** [clash-verge-rev/clash-verge-rev#753]
### 问题描述 / Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/48611415/390d8e96-2457-4cb6-acc9-659976e17f62)
gr关闭了开机自启动后还是会在开机的

### 复现步骤 / To Reproduce

关闭开机自启动后，重新启动windows，还是会自动打开

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11

### 日志 / Log

无

**Comment by RedStronger** [comment]
静默启动是无效的，开机启动后还是会显示主面板

**Comment by dongchengjie** [comment]
开机自启+静默启动好使啊，没有弹出弹窗，甚至都没有闪烁
你甚至用的都不是最新版本

**Comment by MystiPanda** [comment]
https://clash-verge-rev.github.io/faq/windows.html#_4
