### ISSUE TITLE
[Feature] TUN 授权提示 / 失败告警

### ISSUE THREAD

**Issue by hunshcn** [clash-verge-rev/clash-verge-rev#754]
### 功能描述 / Feature description

windows 和 arm macos 下都遇到问题。
在默认场景（非管理员权限下），启用 tun 会出现无权限问题，仅在日志可查询，界面无提示，并且按钮仍显示开启状态，违反直觉。

windows 需要以管理员权限运行，mac 需要内核授权，理应作为前置检查。
同时希望在启动失败时能有 error 并把失败的状态同步到按钮上。

relate to https://github.com/clash-verge-rev/clash-verge-rev/issues/623

### 使用场景 / Use case

-

**Comment by wonfen** [comment]
请使用2.0版本。
