### ISSUE TITLE
[Feature] 是否可以添加类似与预处理配置功能 以便融合远程ACL4SSR_Online_Full规则 与 自己分流规则

### ISSUE THREAD

**Issue by felix-klk** [clash-verge-rev/clash-verge-rev#756]
### 功能描述 / Feature description

是否可以添加类似与预处理配置功能 以便融合远程ACL4SSR_Online_Full规则 与 自己分流规则
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/52670643/6fc2fdc9-cba0-4aac-a3c8-c47a77a05359)

可以更加方便分流  或者直接新增加一个添加在线分流规则 自己添加gist也好

### 使用场景 / Use case

以便融合远程ACL4SSR_Online_Full规则 与 自己分流规则

**Comment by dongchengjie** [comment]
`订阅`->`新建`，类型选择Merge就是你要的，可以配置rule和rule-providers
```
prepend-rules:
prepend-rule-providers:
append-rules:
append-rule-providers:
```

**Comment by felix-klk** [comment]
prepend-rules:
 - DOMAIN-KEYWORD,tiktok,🇯🇵 日本节点
 - PROCESS-NAME,com.spotify.music,🇭🇰 香港节点
 想请教下这个添加的格式是怎末样的尼 试验了单纯这样的好像不生效
 DOMAIN-KEYWORD,tiktok,🇯🇵 日本节点

**Comment by felix-klk** [comment]
> `订阅`->`新建`，类型选择Merge就是你要的，可以配置rule和rule-providers 本地写rule用rule，远程写gist用rule-providers 再复杂点的话，虽然没有叫parser的东西，但是可以写script自己合
> 
> ```
> prepend-rules:
> prepend-rule-providers:
> append-rules:
> append-rule-providers:
> ```

看教程里面没有模板有点懵

**Comment by felix-klk** [comment]
prepend-rules:
  - DOMAIN-KEYWORD,tiktok,🇯🇵 日本节点
  - PROCESS-NAME,com.spotify.music,🇭🇰 香港节点
  
  懂了懂了 是这个格式 有需要的兄弟可以参考  谢谢大哥解答

**Comment by felix-klk** [comment]
> `订阅`->`新建`，类型选择Merge就是你要的，可以配置rule和rule-providers 本地写rule用rule，远程写gist用rule-providers 再复杂点的话，虽然没有叫parser的东西，但是可以写script自己合
> 
> ```
> prepend-rules:
> prepend-rule-providers:
> append-rules:
> append-rule-providers:
> ```

> `订阅`->`新建`，类型选择Merge就是你要的，可以配置rule和rule-providers 本地写rule用rule，远程写gist用rule-providers 再复杂点的话，虽然没有叫parser的东西，但是可以写script自己合
> 
> ```
> prepend-rules:
> prepend-rule-providers:
> append-rules:
> append-rule-providers:
> ```

想请教一下远程配置那个 到底是.yaml 结尾还是.list

远程配置文件里面开头是什么格式尼
payload:
  - DOMAIN-SUFFIX,12306.cn,🇭🇰 香港节点
  - DOMAIN-SUFFIX,95306.cn,🇭🇰 香港节点
  - DOMAIN-SUFFIX,95572.com,🇭🇰 香港节点  例如这样吗
