### ISSUE TITLE
[BUG]  meta内核情况下局域网连接不上

### ISSUE THREAD

**Issue by werq1185** [clash-verge-rev/clash-verge-rev#757]
### 问题描述 / Describe the bug

在使用clash meta内核正式版时，使用 电脑开热点的方式 让手机设置手动代理连接时显示无网络连接，不可使用。但在切换至alpha版本内核后，手机网络正常使用，过程中没有改变其他设置。

### 复现步骤 / To Reproduce

先使用meta内核让手机进行连接，之后再切换到alpha内核。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11 23H2

### 日志 / Log

打开Debug级日志后未发现切换内核拥有日志。

**Comment by MystiPanda** [comment]
@werq1185 这不就说明正式版内核有问题，alpha版本已经修复了吗，你用alpha版本不就好了。

**Comment by werq1185** [comment]
但是alpha版本有bug，节点每隔几分钟就断30秒，用不了一点
