### ISSUE TITLE
[BUG] 静默启动失效，开机后仍会弹出主页面

### ISSUE THREAD

**Issue by yangyangxi666** [clash-verge-rev/clash-verge-rev#758]
### 问题描述 / Describe the bug

[BUG] 静默启动失效，开机后仍会弹出主页面

### 复现步骤 / To Reproduce

每次开机

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win 11

### 日志 / Log

暂无

**Comment by verve91** [comment]
我也有这个问题

**Comment by khvarenah** [comment]
有同样问题

**Comment by MystiPanda** [comment]
翻一翻历史issue至少有五个
