### ISSUE TITLE
[BUG] macOS菜单栏左上角图标重叠错误 macOS menu bar icon overlapping error

### ISSUE THREAD

**Issue by PelikanM400** [clash-verge-rev/clash-verge-rev#759]
### 问题描述 / Describe the bug

正常安装启动软件后，macos左上角图标错误的出现重叠。详见图片。
After installing and launching the software normally, an error occurs where the macOS menu bar icon overlaps. See the image for details.

### 复现步骤 / To Reproduce

安装软件，启动，正常使用，即可见错误。
Install the software, launch it, and use it normally to see the error.

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS 14.4

**Comment by wonfen** [comment]
已知问题，估计是tarui的bug。没有找到原因。

**Comment by MystiPanda** [comment]
像是Sonoma的bug，有人反馈 mac设置-显示器-里面调整一下分辨率再调回去就好了，可以试试。

**Comment by PelikanM400** [comment]
> 像是Sonoma的bug，有人反馈 mac设置-显示器-里面调整一下分辨率再调回去就好了，可以试试。

Many thanks!
