### ISSUE TITLE
[BUG] DNS 和 TCP 日志条目的时间显示可能存在问题

### ISSUE THREAD

**Issue by usklsvg** [clash-verge-rev/clash-verge-rev#76]
**Describe the bug**
DNS 和部分 TCP 显示是 “[36mINFO[0m[2023-12-05T20:09:50.7065455+08:00][TCP]”，
没有显示成 "12-05 20:10:07 INFO"。

**To Reproduce**

日志等级“Debug”，日志展示“ALL”

**Expected behavior**
DNS 及 TCP 条目应该显示成 "12-05 20:09:50 INFO" 

**Screenshots**

![图片](https://github.com/clash-verge-rev/clash-verge-rev/assets/152701112/8cd8183d-a28f-4b50-9469-f0fbfb1e1b3c)

**Information**

- OS: [Win 11]
- Clash Verge Version: [1.4.3]
- Clash Core: [v1.17.0 Meta]

**Comment by charley008** [comment]
+1

**Comment by usklsvg** [comment]
> **Describe the bug** DNS 和 TCP 显示是 “�[36mINFO�[0m[2023-12-05T20:09:50.7065455+08:00][TCP]”， 不像 INFO 那样，显示是"12-05 20:10:07 INFO"。
> 
> **To Reproduce**
> 
> 日志等级“Debug”，日志展示“ALL”
> 
> **Expected behavior** DNS 及 TCP 条目的时间展示与 INFO 相似，显示是"12-05 20:09:50 TCP" 或 "12-05 20:09:50 DNS"
> 
> **Screenshots**
> 
> ![图片](https://private-user-images.githubusercontent.com/152701112/288035706-8cd8183d-a28f-4b50-9469-f0fbfb1e1b3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3OTI3MDIsIm5iZiI6MTcwMTc5MjQwMiwicGF0aCI6Ii8xNTI3MDExMTIvMjg4MDM1NzA2LThjZDgxODNkLWEyOGYtNGI1MC05NDY5LWYwZmJmYjFlMWIzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxNjA2NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjhkMDYxNzQ1N2ZiNmFlMmZiNDBhM2E5M2Q4NGY0YzhlN2FkMjJiMjhhZDJiNjhmYjkwODJkODE3N2IwZDFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PblTnhQyCo1pdGCTiUgXy-ygAdKrdw_iNVUH6ls3vjM)
> 
> **Information**
> 
>     * OS: [Win 11]
> 
>     * Clash Verge Version: [1.4.3]
> 
>     * Clash Core: [v1.17.0 Meta]

而且进一步发现生成的日志文件每一条开头也有着相同的奇怪字符：

![图片](https://github.com/clash-verge-rev/clash-verge-rev/assets/152701112/19700303-524b-4a6a-8394-acf9480b1309)

**Comment by MystiPanda** [comment]
看了代码，界面上的代码是通过内核的api获取的，和文件中的字符没有关系，看起来好像是meta内核自己解析错了日志。
