### ISSUE TITLE
[Feature] 有大佬可以分享下使用proxy-providers合并多个订阅链接的完整yml文件吗？

### ISSUE THREAD

**Issue by xueli12** [clash-verge-rev/clash-verge-rev#762]
### 功能描述 / Feature description

有大佬可以分享下使用proxy-providers合并多个订阅链接的完整yml文件吗？如题，不是很懂规则怎么写，球球了

### 使用场景 / Use case

有大佬可以分享下使用proxy-providers合并多个订阅链接的完整yml文件吗？如题

**Comment by MystiPanda** [comment]
滚远点行不行

**Comment by rebecca554owen** [comment]
# Clash 配置文件
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: info

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

proxy-providers:
  provider1:
    type: http
    url: "http://example.com/sub1.yaml"
    path: ./provider1.yaml
    interval: 3600
  provider2:
    type: http
    url: "http://example.com/sub2.yaml"
    path: ./provider2.yaml
    interval: 3600
  provider3:
    type: http
    url: "http://example.com/sub3.yaml"
    path: ./provider3.yaml
    interval: 3600

proxies:
  - name: "Proxy1"
    type: http
    server: server1
    port: 1234
    username: username1
    password: password1

rules:
  - 'MATCH,Provider=provider1,provider2,provider3'

# 配置文件结束
