### ISSUE TITLE
连接页面最新内容置顶[Feature] 

### ISSUE THREAD

**Issue by fuyongzk** [clash-verge-rev/clash-verge-rev#764]
### 功能描述 / Feature description

现在连接页面更新的内容在最下面，每次查看都要往下滑才能看到，为何不直接把最新的内容更新在顶部
<img width="611" alt="photo12" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/120019530/8c3ce3e8-3bef-404c-afa2-abdd4b88ab74">

### 使用场景 / Use case

连接页面最新内容更新在顶部，这样查看连接页面内容可以一眼看到，而不用往下滑才能看到

**Comment by MystiPanda** [comment]
这是可操作的表格，你以时间排序不就好了

**Comment by fuyongzk** [comment]
> 这是可操作的表格，你以时间排序不就好了

老哥教我，怎么操作，谢谢，我小白
