### ISSUE TITLE
[BUG] 无法安装，已尝试命令行无效

### ISSUE THREAD

**Issue by Karlin-Z** [clash-verge-rev/clash-verge-rev#765]
### 问题描述 / Describe the bug

无法安装

### 复现步骤 / To Reproduce

m1 macbook air，安装提示文件损坏，按照官网qa使用命令提示xattr: No such file: /Applications/Clash Verge.ap

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.4.1

### 日志 / Log

无

**Comment by wonfen** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/96291150/43c039be-5bbd-4d7e-b979-8073738fc019)
这也要教？

**Comment by MystiPanda** [comment]
看你的回复你的命令没有复制全
