### ISSUE TITLE
[BUG]连接界面排序不正确

### ISSUE THREAD

**Issue by studentluo** [clash-verge-rev/clash-verge-rev#77]
![012](https://github.com/clash-verge-rev/clash-verge-rev/assets/68803942/9912f250-eff1-4887-a463-c640aa07b0be)
如图位置所示 多种排序方式皆不正确

ver1.4.2  ver1.4.3

**Comment by wonfen** [comment]
数据是动态刷新的，点击排序后以当前数据排序。
