### ISSUE TITLE
[Feature] 希望能够增加对于使用l2tp时的Windows系统代理设置

### ISSUE THREAD

**Issue by co-knight** [clash-verge-rev/clash-verge-rev#771]
### 功能描述 / Feature description

由于历史遗留问题，Windows系统有着多份系统代理设置，在使用l2tp VPN拨号上网时clash-verge-rev不会修改VPN的代理设置，此时流量只会走VPN而不会走clash，不能实现代理，此时会出现如下情况
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/66869072/d1cd4cca-a696-4e24-a43d-168e2cac22a1)
此时若手动开启VPN代理设置那么代理能够正常实现，如图设置
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/161312612/1b478d5c-a8d4-481f-910e-5a23ac795b5b)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/161312612/2c8e85df-1682-49ae-b663-bfc7c074da7a)
此时代理正常。
希望能够添加功能能够自动修改VPN代理设置
在clash-verge中已经有人反馈过相关问题，但由于种种原因项目终止
参考 [clash-verge/issues#833](https://github.com/zzzgydi/clash-verge/issues/833)
   [windows-proxy](https://myth.cx/p/windows-proxy/#%E6%8B%A8%E5%8F%B7%E8%BF%9E%E6%8E%A5%E5%8F%88%E6%9D%A5%E4%B8%80%E4%BB%BD%E8%AE%BE%E7%BD%AE)
[use winapi instead of registry](https://github.com/zzzgydi/sysproxy-rs/pull/3)

### 使用场景 / Use case

在某些内网环境下，上网必须通过l2tp有线网，如果可以实现这个功能那么在l2tp下使用代理会更简单

**Comment by wonfen** [comment]
2.0已实现。
