### ISSUE TITLE
关闭软件自带标题栏

### ISSUE THREAD

**Issue by aaddmin1122345** [clash-verge-rev/clash-verge-rev#775]
### 功能描述 / Feature description

如何关闭软件自带的标题栏,改用使用系统自带的,我是Archlinux wayland kde

### 使用场景 / Use case

有两个标题栏不协调,关闭系统的标题栏倒是可以,但是这样会和其它软件标题栏显得不一样,有点别扭

**Comment by dsw676676** [comment]
Hope to get this improvement, it is really not convenient.

**Comment by MystiPanda** [comment]
已经设置了隐藏系统标题栏，但是这个设置在KDE Wayland下无效，需要自己手动添加窗口规则来隐藏系统标题栏。

**Comment by witt-bit** [comment]
> 已经设置了隐藏系统标题栏，但是这个设置在KDE Wayland下无效，需要自己手动添加窗口规则来隐藏系统标题栏。

更期望的是能关闭软件的标题栏，保留系统标题栏

**Comment by MystiPanda** [comment]
@witt-bit 系统标题栏不同桌面环境下样式各不相同，无法跟软件主题相匹配，使用自绘的标题栏可以在全平台下统一样式。如果实在不想要，软件也有css注入功能，可以自己取消。
