### ISSUE TITLE
系统关机后没有关闭代理操作，导致系统重启后，在代理软件不打开的情况下，浏览器没法访问页面[BUG] 

### ISSUE THREAD

**Issue by xuhuanghuang** [clash-verge-rev/clash-verge-rev#776]
### 问题描述 / Describe the bug

代理软件使用过程中，如果中途直接强制关机或者重启， 然后去打开浏览器，页面都无法访问

### 复现步骤 / To Reproduce

1.打开代理软件
2.关机
3.开机
4.打开谷歌浏览器
5.网页无法访问

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

window/macos

### 日志 / Log

暂无

**Comment by GubbaNndRahkah** [comment]
非常经典的bug，应该有几年了

**Comment by xishang0128** [comment]
关机状态下,软件会被强制关闭,无法处理系统代理的关闭,软件也没法预知你将要关机提前关闭,这是无意义的反馈,请关闭这个issues

**Comment by Nelson0213** [comment]
就算没开代理退出软件也会断网 搞不懂

**Comment by SyunSS** [comment]
经典bug 你直接关机没有把Windows系统的http代理的开关关闭 导致不开软件的时候就会一直访问不存在的http代理导致访问出错
最简单解决的办法就是用tun模式
![QQ截图20240328110907](https://github.com/clash-verge-rev/clash-verge-rev/assets/85484130/2597eb7b-c147-400f-8380-a3c3522227b5)

**Comment by RealSubstantiality** [comment]
关于这个问题我想到了一个可能的解决方法，抛砖引玉一下。事先声明一下本人纯小白啊，我的操作是把以下代码复制到一个新建txt中，改后缀名为.vbs，然后放到Windows启动项文件夹里。
Set WshShell = CreateObject("WScript.Shell")
WshShell.Run "cmd /c reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings"" /v ProxyEnable /t REG_DWORD /d 0 /f", 0, True
我的想法是设置一个开机启动项，这个启动项可以将代理设置关闭。每次开机都会运行这个启动项，如果不需要clash则可以上网，需要clash的话打开clash的时候会自动开启代理设置，所以解决了这个问题也没有什么副作用。我找到了关闭代理设置的reg命令，然后找了一下如何让他运行的时候不弹出cmd窗口，最后整合出来是这个代码。因为我也不会编程，所以不知道这个方法有没有什么别的未知问题，希望懂的人能帮忙看一下。
顺便一说，之前的clash for windows如果把http模式切换成pac模式的话确实可以避免重启之后上不了网的问题，不知道这边能不能加入这个功能。

**Comment by RealSubstantiality** [comment]
哦对了，我这个还有一个问题是可能开机后1/2秒才能运行，所以刚开机立刻开浏览器还是不行，不过刷新一下就可以了。我试过组策略和任务计划程序等其它方式设置为开机自启，发现都没有效果了，所以只能用Windows启动文件夹。不知道有没有大神可以改进一下

**Comment by peasoft** [comment]
似乎不管是 tauri 还是 electron 都有这个问题？[这里](https://github.com/docmirror/dev-sidecar/issues/109) 有一些解决方案，还是加脚本或程序，这是唯一的解决办法了。

楼上脚本没作用是因为脚本修改的是 `HKCU`，即当前用户的设置。组策略和计划任务运行脚本时使用的是系统用户，而非你的用户。如果在计划任务中选择“仅在用户登录时运行”，应该就可以了。

**Comment by fuwuqi298** [comment]
早年 cfw 也有这个问题，但后面没遇到了。最开始用的 ss 小飞机那个客户端也有这个问题。

**Comment by kvbops** [comment]
这个 看上去不想解决了。。自己解决其实也简单，，就是把代理做成sevice ，关闭程序不关闭代理 服务 ，，或者代理服务检测到程序关了就停止代理服务

**Comment by wonfen** [comment]
> 这个 看上去不想解决了。。自己解决其实也简单，，就是把代理做成sevice ，关闭程序不关闭代理 服务 ，，或者代理服务检测到程序关了就停止代理服务

是个思路，cfw是把系统代理做成服务了吗？

**Comment by kvbops** [comment]
> > 这个 看上去不想解决了。。自己解决其实也简单，，就是把代理做成sevice ，关闭程序不关闭代理 服务 ，，或者代理服务检测到程序关了就停止代理服务
> 
> 是个思路，cfw是把系统代理做成服务了吗？

这个不知道，但我想我回去做，第一个版本我会先尝试进程守护的方式，这个是最简单的。第二个版本改成用service来提供服务，tuari仅仅只做一个webview展示，通过clash api进行通讯，而不是通过tuari 注入然后再到rust里调用clash api 通讯。
现在 tuari 有问题  在mac 上 dock 菜单是无法控制的，退出就是强制退出  dock上的菜单也没法管理，希望tuari v2版本早点出正式版看看有无改进。

**Comment by kvbops** [comment]
我已经解决这个问题了。macos上要建立 plist文件 启动一个服务 监听进程但要pkg安装  windows 要修改nsis打包，添加service的nsis插件 安装服务，我还剥离了clash内核放到服务里，tauri就仅仅展示ui就行了，还删了很多额外功能 打包后就十几M，这个原来的包里集成了两个内核 一个 meat一个alpha 我只集成了meta就好了，另外服务里新加了进程守护 在关了进程后 就自动停止内核和代理节约节点流量，连ping的流量就省下了，还在server里创建了服务 可以通过http协议实现ui和服务的通讯 这样ui想做什么只需要调用http接口就好了。。现在的缺点就是 安装权限比之前更高要启动系统服务 还有就是没有实现它原本的混合端口， 这个是因为我写了混合端口还要保存到文件，添加额外的结构体 额外的功能，，懒得写了。 我直接用50000以上的端口。现在已经完全满足我的需求了

**Comment by kvbops** [comment]
如果有需求的 可以按照我这个思路去搞。。。但我不开源。。开源这玩意的应该会被蜀黍上门

**Comment by wonfen** [comment]
> 我已经解决这个问题了。macos上要建立 plist文件 启动一个服务 监听进程但要pkg安装 windows 要修改nsis打包，添加service的nsis插件 安装服务，我还剥离了clash内核放到服务里，tauri就仅仅展示ui就行了，还删了很多额外功能 打包后就十几M，这个原来的包里集成了两个内核 一个 meat一个alpha 我只集成了meta就好了，另外服务里新加了进程守护 在关了进程后 就自动停止内核和代理节约节点流量，连ping的流量就省下了，还在server里创建了服务 可以通过http协议实现ui和服务的通讯 这样ui想做什么只需要调用http接口就好了。。现在的缺点就是 安装权限比之前更高要启动系统服务 还有就是没有实现它原本的混合端口， 这个是因为我写了混合端口还要保存到文件，添加额外的结构体 额外的功能，，懒得写了。 我直接用50000以上的端口。现在已经完全满足我的需求了

欢迎PR

**Comment by kvbops** [comment]
> > 我已经解决这个问题了。macos上要建立 plist文件 启动一个服务 监听进程但要pkg安装 windows 要修改nsis打包，添加service的nsis插件 安装服务，我还剥离了clash内核放到服务里，tauri就仅仅展示ui就行了，还删了很多额外功能 打包后就十几M，这个原来的包里集成了两个内核 一个 meat一个alpha 我只集成了meta就好了，另外服务里新加了进程守护 在关了进程后 就自动停止内核和代理节约节点流量，连ping的流量就省下了，还在server里创建了服务 可以通过http协议实现ui和服务的通讯 这样ui想做什么只需要调用http接口就好了。。现在的缺点就是 安装权限比之前更高要启动系统服务 还有就是没有实现它原本的混合端口， 这个是因为我写了混合端口还要保存到文件，添加额外的结构体 额外的功能，，懒得写了。 我直接用50000以上的端口。现在已经完全满足我的需求了
> 
> 欢迎PR

这个。。没法提。。我几乎修改了整个代码。tauri部分仅剩下展示部分。 代理功能全部写到了另一个rust项目中，这个项目集成clash内核。我的目录结构是 main(tauri项目展示ui)。service(服务项目集成clash)，pkg(打包配置)，还额外正价了tauri的nsis插件。。。。并且 这个修改是为了我的需求修改的 打开我的ui是我自己专用ui， 另外还有个顾虑。。。这个项目 会不会有风险，，我都是小号。。。

**Comment by kvbops** [comment]
我在 clash-verge-rev的仓库中看到了https://github.com/clash-verge-rev/clash-verge-service 这个项目。。。应该是也有做到服务中的想法。。。不过这里面的安装 启动服务的功能我直接用nsis代替了 专注与服务本身功能的开发

**Comment by Mr-Wang-YourNeighbor** [comment]
进入Windows系统Internet选项
点击Internet选项界面顶部连接选项卡，点击局域网设置，取消勾选为LAN使用代理服务器(这些设置不用于拨号或VPN连接)，确定。
点击Internet选项界面顶部高级选项卡，勾选使用HTTP 1.1”“使用HTTP 2”两项，并取消勾选“通过代理连接使用HTTP 1.1，确定。
尝试是否能正常上网，或者重新启动电脑生效。

**Comment by Mr-Wang-YourNeighbor** [comment]
@echo off
rem 检查代理是否已经关闭
reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyEnable | find "0x0"
if %errorlevel%==0 (
    echo 代理已经关闭，脚本不会做任何修改。
) else (
    rem 关闭代理
    reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyEnable /t REG_DWORD /d 0 /f
    echo 代理已关闭。
)做了这个脚本然后设置每次登录系统都启动一次按 Win + R，输入 taskschd.msc 打开任务计划程序。
在右侧的“操作”面板中，点击 创建任务。
