### ISSUE TITLE
局域网连接问题

### ISSUE THREAD

**Issue by blackandwhite996** [clash-verge-rev/clash-verge-rev#777]
### 问题描述 / Describe the bug

电脑开启局域网连接后，iPad上设置代理，同一网络下，网络显示：无互联网连接，请尝试重新启动调制解调器和路由器，或者联系isp。使用手机尝试同样如此，电脑上的网络访问正常。在另一台室友的电脑上同样步骤依旧如此，但是使用cfw却连接正常，可以访问网站。端口使用的7897

### 复现步骤 / To Reproduce

开启电脑端局域网连接，移动设备连接至同一网络，调试移动设备网络代理，浏览器访问互联网失败。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11，Win10

### 日志 / Log

WARNING
【TCP】dial DIRECT（match IPCIDR/192.168.0.0/16）198.18.0.1:5167-->192.168.1.110:7680 error: connect failed: dail tcp 192.168.1.110:7680: i/o timeout

**Comment by wonfen** [comment]
telent端口通吗？能否ping通？

**Comment by blackandwhite996** [comment]
> telent端口通吗？能否ping通？
<img width="247" alt="Snipaste_2024-03-29_14-39-17" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/131672144/4622f427-f4f9-489a-b8a4-7182d3c700fb">
这个吗？

**Comment by hsulei** [comment]
之前好像就有问题， 我用ip访问我局域网里的数据库，连接不上。

**Comment by 250king** [comment]
同，我家和店铺使用iKuai的SD-WAN互联，在关闭TUN模式可以正常访问店里的路由器管理界面，但一旦开启TUN模式就不行

**Comment by blackandwhite996** [comment]
> 同，我家和店铺使用iKuai的SD-WAN互联，在关闭TUN模式可以正常访问店里的路由器管理界面，但一旦开启TUN模式就不行

我刚刚试了一下，关了tun手机可以连上Google官网，youtube可以，telegram不行，开了之后，google就不行了，然后又关了一次，谷歌就变成
404. That’s an error.

The requested URL /m was not found on this server. That’s all we know.
这样了，开或者不开，telegram都连接不上，好像是某些网站能访问，有些不能。

**Comment by talkshowsonmute** [comment]
局域网连接没有加防火墙设置吧。。。我手动加了就能连了

**Comment by hsulei** [comment]
> 局域网连接没有加防火墙设置吧。。。我手动加了就能连了

我用clash for windows就一点问题也没有， 不用设置任何防火墙

**Comment by blackandwhite996** [comment]
> 局域网连接没有加防火墙设置吧。。。我手动加了就能连了

但是不知道为啥，加了之后，别的倒能访问了，✈️连接不上

**Comment by mContext** [comment]
俺也一样

**Comment by mContext** [comment]
> > 局域网连接没有加防火墙设置吧。。。我手动加了就能连了
> 
> 但是不知道为啥，加了之后，别的倒能访问了，✈️连接不上

我这边加了防火墙也是全都连不了~

**Comment by Sipoon** [comment]
同样的设置，用旧版的Clash Verge就可以连局域网，这个rev版的就是不行

**Comment by rebecca554owen** [comment]
@Sipoon 防火墙规则，允许应用通过防火墙，删除旧的mihomo，再添加新位置的mihomo。

**Comment by Sipoon** [comment]
> @Sipoon 防火墙规则，允许应用通过防火墙，删除旧的mihomo，再添加新位置的mihomo。

好的，谢谢你，我重新在防火墙添加新版的clash-mate就可以了

**Comment by mContext** [comment]
防火墙关掉都连不上~

**Comment by dotSpecs** [comment]
我也偶尔遇到这个问题

**Comment by MC-cookies** [comment]
我也是局域网共享不上
关防火墙无法解决
换meta 和 mtea alpha内核都不行
但是我去用了clash for windows没有问题

**Comment by mContext** [comment]
1.7.2  windows + Ubuntu版本  依旧不行

**Comment by Carolove7** [comment]
cfw有一个Clash Core Service服务，关闭再用verge试试

**Comment by mContext** [comment]
> cfw有一个Clash Core Service服务，关闭再用verge试试

Ubuntu新装的系统，没装CFW ...

**Comment by mContext** [comment]
> cfw有一个Clash Core Service服务，关闭再用verge试试

Windows版本，关掉了Clash Core Service服务，也是共享不上·

**Comment by mContext** [comment]
> > cfw有一个Clash Core Service服务，关闭再用verge试试
> 
> Windows版本，关掉了Clash Core Service服务，也是共享不上·
停掉了Clash Core Service, 能共享了, 然后重启电脑,又共享不上了,看了下服务里面有个Clash verge service ,关掉了 也还是共享不了~

**Comment by Carolove7** [comment]
> > cfw有一个Clash Core Service服务，关闭再用verge试试
> 
> 停掉了Clash Core Service, 过了几分钟突然能共享了, 然后重启电脑,又共享不上了,看了下服务里面有个Clash verge service ,关掉了 也还是共享不了~

计算机管理→任务计划程序里关闭Clash Core的启动项

**Comment by mContext** [comment]
> > > > > cfw有一个Clash Core Service服务，关闭再用verge试试
> > > > 
> > > > 
> > > > 停掉了Clash Core Service, 过了几分钟突然能共享了, 然后重启电脑,又共享不上了,看了下服务里面有个Clash verge service ,关掉了 也还是共享不了~
> > > 
> > > 
> > > 计算机管理→任务计划程序里禁用Clash Core的启动项
> > 
> > 
> > 计算机管理→任务计划程序里 没找到Clash相关的计划任务 msconfig 系统配置的服务里倒是看到一个Clash Verge Service
> 
> 如果你以前cfw自启过就有（即使现在关闭自启），verge当然要打开

目前是没有了, 但依旧不能局域网共享~

**Comment by mContext** [comment]
改防护墙没用的话可以试试 **订阅-->全局扩展配置** 里面把几个默认的配置覆盖一下 ,目前我的是这样修好的`
``` config
# Profile Enhancement Merge Template for Clash Verge
port: 7890
socks-port: 9920
allow-lan: true
bind-address: 0.0.0.0
mode: rule
log-level: silent
external-controller: 127.0.0.1:9090
profile:
  store-selected: true

dns:
  use-system-hosts: false
```

**Comment by ArmyCAC** [comment]
> 改防护墙没用的话可以试试 **订阅-->全局扩展配置** 里面把几个默认的配置覆盖一下 ,目前我的是这样修好的`
> 
> ```
> # Profile Enhancement Merge Template for Clash Verge
> port: 7890
> socks-port: 9920
> allow-lan: true
> bind-address: 0.0.0.0
> mode: rule
> log-level: silent
> external-controller: 127.0.0.1:9090
> profile:
>   store-selected: true
> 
> dns:
>   use-system-hosts: false
> ```

按照你的操作还是没用，你这端口直接改成7980了，默认是7987

**Comment by ArmyCAC** [comment]
window防火墙打开，把内核程序加进去
![image](https://github.com/user-attachments/assets/58837680-700d-4cbd-a1f4-dc2537d64168)

**Comment by yi-shengfeng** [comment]
> window防火墙打开，把内核程序加进去 ![image](https://private-user-images.githubusercontent.com/14289215/352995753-58837680-700d-4cbd-a1f4-dc2537d64168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTkzMTAsIm5iZiI6MTcyMzU1OTAxMCwicGF0aCI6Ii8xNDI4OTIxNS8zNTI5OTU3NTMtNTg4Mzc2ODAtNzAwZC00Y2JkLWExZjQtZGMyNTM3ZDY0MTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE0MjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMTFiMTU1Nzc2Yjc4N2FmYzg1YmY3YWZkMGE3NGQxZWRkYzVhMDkwZDMzYzIxZWE3ZmM4NzZiYWJjMzgzMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Fin_kSMXjXz-Zkc8jQUm5MA0LbMceU3Woiizq5KodQ)

遇到了同样的问题，通过这个设置解决了，多谢！

**Comment by bujinbufa** [comment]
> window防火墙打开，把内核程序加进去 ![image](https://private-user-images.githubusercontent.com/14289215/352995753-58837680-700d-4cbd-a1f4-dc2537d64168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0ODkyNTgsIm5iZiI6MTcyNDQ4ODk1OCwicGF0aCI6Ii8xNDI4OTIxNS8zNTI5OTU3NTMtNTg4Mzc2ODAtNzAwZC00Y2JkLWExZjQtZGMyNTM3ZDY0MTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDA4NDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZjQ1MjFiNjhlY2IzMDliZjBiODZhOWY0MWRhNTgzODRjN2ZmNDY0MGU0MzBkMmJhNjA2ZjUxNjNkY2U0ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aK7wt1s6ffVhOqx9YlwOt9-L8fMx0BJye8TKjbLBJRQ)

有用，谢谢

**Comment by banjunxiao** [comment]
> window防火墙打开，把内核程序加进去 ![image](https://private-user-images.githubusercontent.com/14289215/352995753-58837680-700d-4cbd-a1f4-dc2537d64168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjU5MTgsIm5iZiI6MTcyNjc2NTYxOCwicGF0aCI6Ii8xNDI4OTIxNS8zNTI5OTU3NTMtNTg4Mzc2ODAtNzAwZC00Y2JkLWExZjQtZGMyNTM3ZDY0MTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE3MDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZTJmNjExMTUxZGQyYTgyYTQwNjg4YThlNzFhZTY2YmMwNWJmMDAyMjExODVlMjRhODAxYTM0NDgxOGI2MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AN2I_CKDi0qLbgcnlf1amxfgP8U7oLw-f_Z7DGF246Q)

问题解决了，感谢！

**Comment by laughtLOOL** [comment]
![image](https://github.com/user-attachments/assets/7b6c9752-e462-48e4-8417-dbb398c48f97)
目前更奇葩了，我按照前面方法做完还是不行，版本是1.7.7
由于我也有在openclash，当电脑不用软路由（ip哪里网关非软路由地址2.1）也就是只用verge的时候，电脑能够上网，手机（2.1）不能上网包括国内，电脑自身可以用系统代理上网
当我电脑接入了软路由（网关是软路由2.2）verge也开的情况下手机（一直2.1）就能上了，不知道是什么原理。。。可能是网关不同？但是不应该跨网关反而能上，跨了网关反而能开tun然后使用openclash间接上网（openclash 选节点 verge选 direct）或者使用verge直接上网（openclash 选direct verge选节点），关tun无网，真是奇怪了。。。

现在我的解决方法是tun和系统代理全开然后使用adguard客户端的代理宽口上网，希望早点解决这个局域网设备连接，我发现设备是能够连接的，但是设备没有权限上网一样

**Comment by laughtLOOL** [comment]
目前还有一个方法回退到https://github.com/clash-verge-rev/clash-verge-rev/issues/1383 1.7.3之前

**Comment by chzhongsending** [comment]
谢谢说防火墙的哥们，已经解决。

界面上能不能加一个按钮，来配置防火墙啊。
我到了 Windows 防火墙高级设置界面，看到了相关规则，但处于未启用的状态。
推测是程序已经配了规则但由于种种原因没有启用或者配置妥当。

顺带一说，我处于域环境下。配置防火墙没用的，考虑到高级防火墙设置把公共、私有、域网络的选项都勾上。

**Comment by junxian-li-hpc** [comment]
win11 之前用的cfw，更换为clash verge，然后局域网不能访问google，可以weixin发消息。
不知道以上评论哪个步骤起了作用：卸载了cfw的服务模式，verge重新安装了，然后手机连接的时候代理ip写的是另一个：
verge里只有一个以太网2，cmd 通过ipconfig还有一个本地连接2，（cfw的局域网连接也是能看到本地连接2的，但是verge没有）
![image](https://github.com/user-attachments/assets/92a0e1b4-1f86-4632-a291-14197e1e1d40)
![image](https://github.com/user-attachments/assets/8449f1ec-3bff-4f46-a69a-cc2906202844)
然后代理写的本地连接2，手机可以访问google。

**Comment by lismc33** [comment]
> window防火墙打开，把内核程序加进去 ![图像](https://private-user-images.githubusercontent.com/14289215/352995753-58837680-700d-4cbd-a1f4-dc2537d64168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNTQyMjMsIm5iZiI6MTczMjM1MzkyMywicGF0aCI6Ii8xNDI4OTIxNS8zNTI5OTU3NTMtNTg4Mzc2ODAtNzAwZC00Y2JkLWExZjQtZGMyNTM3ZDY0MTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDA5MjUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZTcwMzM1MWM0MWI5Yzg5NWNmYjQ2MGJiMjBlNjI1M2E4YjExMzBjMDJmMzI4MDliYTg0ZDg2MTFjYThmNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6gC2E4_9ldgxWZHQGXz6nD69TB24-dLYuCc0dw-V34c)

感谢，更新2.0版本后局域网也需要从新添加防火墙吧

**Comment by cx0v0** [comment]
> window防火墙打开，把内核程序加进去 ![image](https://private-user-images.githubusercontent.com/14289215/352995753-58837680-700d-4cbd-a1f4-dc2537d64168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNjYyOTUsIm5iZiI6MTczMzA2NTk5NSwicGF0aCI6Ii8xNDI4OTIxNS8zNTI5OTU3NTMtNTg4Mzc2ODAtNzAwZC00Y2JkLWExZjQtZGMyNTM3ZDY0MTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE1MTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZTg5Y2RiODExYmQzMDljNWMwZTBlMjkwMzQ5ZDYzMGFmY2MyZGZhNGI0YjA0ZmJiM2JlODEwMzljMGM3MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TuHERLy2DHp3t6Ali76V0euAKyLx-AZebQc-TP0ZY0M)

谢谢！这问题困扰了我好久

**Comment by once375ml** [comment]
> @Sipoon 防火墙规则，允许应用通过防火墙，删除旧的mihomo，再添加新位置的mihomo。

谢谢了，拯救了折腾了1个礼拜的我。现在可以了局域网共享机场了

**Comment by flying318** [comment]
> window防火墙打开，把内核程序加进去 ![image](https://private-user-images.githubusercontent.com/14289215/352995753-58837680-700d-4cbd-a1f4-dc2537d64168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MzczMDksIm5iZiI6MTczMzYzNzAwOSwicGF0aCI6Ii8xNDI4OTIxNS8zNTI5OTU3NTMtNTg4Mzc2ODAtNzAwZC00Y2JkLWExZjQtZGMyNTM3ZDY0MTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDA1NTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmNGRmNmRmZDgyZmIxNGY2MWY3Zjc4MTQ5ZTNiNzhkNDZhNDM3NjE3ODI2Nzg3MThhZDc1NDc4ZTEyZmEzN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IohFcJIgyfst93wGzrDCGcJ8Gq6vhfP5Xh1t6c2JTPI)
 @ArmyCAC 这个有用，谢谢兄弟，困扰两天的问题终于解决了:+1:

**Comment by Thundor404** [comment]
谢谢兄弟，改防火墙有用！

**Comment by kimooxx** [comment]
> 改防护墙没用的话可以试试 **订阅-->全局扩展配置** 里面把几个默认的配置覆盖一下 ,目前我的是这样修好的`
> 
> ```
> # Profile Enhancement Merge Template for Clash Verge
> port: 7890
> socks-port: 9920
> allow-lan: true
> bind-address: 0.0.0.0
> mode: rule
> log-level: silent
> external-controller: 127.0.0.1:9090
> profile:
>   store-selected: true
> 
> dns:
>   use-system-hosts: false
> ```

谢谢，有用。我是先改了防火墙，添加了我的混合端口入站规则，这时能手机SOCKS PING通了电脑的端口了。但手机还是无法翻墙。
然后我把内核verge-mihomo-alpha.exe 和 verge-mihomo.exe 都添加到防火墙放行，结果还是没解决。
最后，我进行了上面这个操作，然后就可以了。感谢。

**Comment by konosubakonoakua** [comment]
> 改防护墙没用的话可以试试 **订阅-->全局扩展配置** 里面把几个默认的配置覆盖一下 ,目前我的是这样修好的`
> 
> ```
> # Profile Enhancement Merge Template for Clash Verge
> port: 7890
> socks-port: 9920
> allow-lan: true
> bind-address: 0.0.0.0
> mode: rule
> log-level: silent
> external-controller: 127.0.0.1:9090
> profile:
>   store-selected: true
> 
> dns:
>   use-system-hosts: false
> ```

这个有用，目前版本2.2.0验证有效

**Comment by microka** [comment]
刚重装了 Windows 11 24H2，安装 Clash-Verge-Rev 2.2.2，开启局域网连接实际没生效，还是需要在 Windows 防火墙手动添加 verge-mihomo.exe 允许其通过 Windows Defender 防火墙进行通信，才能正常工作。

**Comment by once375ml** [comment]
> 刚重装了 Windows 11 24H2，安装 Clash-Verge-Rev 2.2.2，开启局域网连接实际没生效，还是需要在 Windows 防火墙手动添加 verge-mihomo.exe 允许其通过 Windows Defender 防火墙进行通信，才能正常工作。

估计要右键，“以管理员权限运行”，Clash才能有权限创建防火墙规则

**Comment by r4496618** [comment]
改防火墙是有效果的，要把出站和入站都允许就好了。

**Comment by xwpwx** [comment]
> [@Sipoon](https://github.com/Sipoon) 防火墙规则，允许应用通过防火墙，删除旧的mihomo，再添加新位置的mihomo。

非常感谢，可以用了

**Comment by kkrootl** [comment]
试过了 不行

**Comment by yanzhichao** [comment]
如果开启了防火墙没有用，还需要允许入栈

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/f59f1699-a3ba-4c4a-b928-20db089578f2" />

将所有的verge-mihomo都设置为允许

**Comment by martixjohn** [comment]
点击设置/当前配置，如果bind-address为127.0.0.1，在订阅处右键全局扩展覆写配置，添加一行
`bind-address: 0.0.0.0`

**Comment by kvchoi** [comment]
> 点击设置/当前配置，如果bind-address为127.0.0.1，在订阅处右键全局扩展覆写配置，添加一行 `bind-address: 0.0.0.0`

正解

**Comment by JoinNico** [comment]
> 如果开启了防火墙没有用，还需要允许入栈
> 
> <img alt="Image" width="1920" height="1080" src="https://private-user-images.githubusercontent.com/16754580/488814844-f59f1699-a3ba-4c4a-b928-20db089578f2.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODU0MTUzMTUsIm5iZiI6MTc4NTQxNTAxNSwicGF0aCI6Ii8xNjc1NDU4MC80ODg4MTQ4NDQtZjU5ZjE2OTktYTNiYS00YzRhLWI5MjgtMjBkYjA4OTU3OGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNzMwVDEyMzY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMWYwMWY4MDMwZmQwZmVhOGMzMmYxMTc1MTY0ZDNlMTQwNTFmZmQxZGU5N2EwYWQ4Y2VkMzBjYmIxMTA4Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.0iqzjxQzSOY3rf5HgrdgR_vH1z45bCoBjHt6iMBFUBg">
> 将所有的verge-mihomo都设置为允许

确实有用，我用管理员运行clash verge后，switch2成功连接了局域网，代理转发了流量
