### ISSUE TITLE
[BUG] 使用远程订阅转换url中如果包含外部url无法订阅，报远程500错误代码。

### ISSUE THREAD

**Issue by yyxida** [clash-verge-rev/clash-verge-rev#778]
### 问题描述 / Describe the bug

最新的[1.5.10](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.5.10)版本下，使用远程订阅配置，如果订阅链接中的“url=”项包含远程配置连接（比如机场的）就会提示`failed to fetch remote profile with status 500 Internal Server Error`。如果只是vmess://或者ss://的base64配置信息的话不会影响。经过测试1.5.10版本下有这个问题，退回到1.5.8可以正常订阅，再次升级到1.5.10又会出现500错误，可以复现。其他客户端如stash，cfa，cfameta没有这个问题。

### 复现步骤 / To Reproduce

1,订阅 https://sub.aaa.com/subsub?target=clash&new_name=true&url=https://jicang.jichang.com/aaaa 这种包含机场节点url的订阅转换
2，报错`failed to fetch remote profile with status 500 Internal Server Error`

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

2024-03-27 22:28:35 ERROR - failed to fetch remote profile with status 500 Internal Server Error

**Comment by xuewlcn** [comment]
还是有这个问题

**Comment by gskuerhgsjhbg** [comment]
我也是有同样的问题，mac和win都有这个问题，版本：1.7.5

**Comment by hongfu110** [comment]
解决了么
