### ISSUE TITLE
[BUG] 高分屏下200%缩放,deb包安装后的程序界面显示异常

### ISSUE THREAD

**Issue by i-bugmaker** [clash-verge-rev/clash-verge-rev#779]
### 问题描述 / Describe the bug

电脑配的4K显示器，操作系统是Linux Mint 21.3 x86_64，打开了200%缩放。安装deb包，打开程序，界面显示异常。运行AppImage程序无异常。
![neofetch](https://github.com/clash-verge-rev/clash-verge-rev/assets/26687639/8abcca62-c0c3-4767-8676-75a6cc964751)
![clash-verge界面显示异常](https://github.com/clash-verge-rev/clash-verge-rev/assets/26687639/694670cc-ffff-4e03-94ae-6b172b7dff9c)

### 复现步骤 / To Reproduce

1.下载deb包clash-verge_1.5.10_amd64.deb
2.安装sudo dpkg -i clash-verge_1.5.10_amd64.deb
3.启动clash-verge
4.观察程序界面

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Linux Mint 21.3 x86_64

### 日志 / Log

无log

**Comment by MystiPanda** [comment]
这应该是你系统设置的问题，Linux各个桌面环境的缩放实现都不一样，建议看看发行版的wiki
