### ISSUE TITLE
[BUG]The program doesn't boot on win 11 22631

### ISSUE THREAD

**Issue by taswsz** [clash-verge-rev/clash-verge-rev#78]
Os version: windows 11 22631.2715
Clash verge rev version: 1.43 and 1.42

Bug description: No response after double clicking, main dashboard doesn't pop up, there is only a tray icon, and no response right clicking or left clicking the tray icon. Seconds later the tray icon disappears.
any idea ? 

双击图标后仪表板不弹出，只有托盘图标，左键右键单击均无反应。几秒后托盘图标也消失。

**Comment by wonfen** [comment]
排查下电脑是否安装了IP Guard之类的软件： https://github.com/zzzgydi/clash-verge/issues/717
