### ISSUE TITLE
[Feature] 期望增加托盘点击事件绑定选项

### ISSUE THREAD

**Issue by YusCoding** [clash-verge-rev/clash-verge-rev#780]
### 功能描述 / Feature description

以前使用clashx、shadowcosks之类工具时候的交互动作觉得可以考虑下：mac端点击菜单栏图标时候仅展示下拉菜单，打开面板的话需要二次点击“打开面板”按钮才会打开面板页面，个人觉得一般点击菜单图标并非都是想打开面板页面，更多的会是想打开下拉菜单切换系统代理开关以及进行规则/全局的切换操作
<img width="199" alt="截屏2024-03-27 23 04 42" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/33707489/2ea6727a-6589-4aff-8b12-d70b88745e3f">

### 使用场景 / Use case

目前可以进行菜单图标点击事件的功能更改，这样自然是好的，但是如果加上点击事件选择为仅展示下拉菜单不弹出面板，或许能给更多人更自由的操作需求：
1.想要临时关闭系统代理功能(某些软件运行时不可有代理)，之后再重新开启系统代理。这样可避免只是做简单切换操作时还需要在弹出面板后在面板设置tab栏选择开启或关闭系统代理，或是再次点击图标在下拉菜单点击勾选/取消勾选
2.想要切换代理规则为规则/全局，操作逻辑同上

**Comment by lvdongxiao** [comment]
设置里面有（托盘点击事件）设置，设置禁用

**Comment by YusCoding** [comment]
> 设置里面有（托盘点击事件）设置，设置禁用

啊。。。原来是我不会用！感谢！打扰啦！
