### ISSUE TITLE
Mac无法开启Tun模式

### ISSUE THREAD

**Issue by mn868** [clash-verge-rev/clash-verge-rev#784]
### 问题描述 / Describe the bug

intel芯的Mac无法开启Tun模式，内核已经授权

### 复现步骤 / To Reproduce

*

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Son14.4.1 

### 日志 / Log

<img width="573" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/55569820/0dfd0d6d-00ad-4d6e-8093-ef66cb231882">

**Comment by wonfen** [comment]
检查下你的网络权限。

**Comment by mn868** [comment]
> 检查下您的网络权限。

不是很明确，我并没有设置任何权限，同样的网络，我在虚拟机的win系统里是好用的

**Comment by GZTimeWalker** [comment]
same here:

```bash
.rwsr-sr-x 24M root   admin 28 Mar 12:10 clash-meta
.rwxr-xr-x 24M gztime admin 28 Mar 12:10 clash-meta-alpha
.rwxr-xr-x 17M gztime admin 28 Mar 12:18 Clash Verge
```

<img width="636" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/28180262/a7279c18-2ad2-4af4-a0c3-df63c7ca0a6f">

how to fix:

Rename `Meta` in `TUN Mode` into something like `utun16`

**Comment by fuyongzk** [comment]
我也是，win电脑同样开启tun模式无效，开了和没开一样
