### ISSUE TITLE
[BUG] 几种订阅都无法使用 vs code 以及默认编辑器打开

### ISSUE THREAD

**Issue by marioplus** [clash-verge-rev/clash-verge-rev#789]
### 问题描述 / Describe the bug

几种订阅都无法使用 vs code 打开，也无法使用默认程序打开，只能使用程序默认编辑器打开。
Verge 版本：v1.5.11

### 复现步骤 / To Reproduce

1. 新建任何一种订阅
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/26264731/150cfcf6-a20b-4c8b-ae37-6bccbe600194)
2. 右键任何一种订阅
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/26264731/c27a0ce7-e6d3-4d8b-be34-cf12e16c2a04)
3. 点击打开文件
4. 没有任何反应

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 / 23H2 / 22631.3296 / Windows Feature Experience Pack 1000.22687.1000.0

### 日志 / Log

# 日志设置
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/26264731/789dce0c-a119-45a0-9b74-64c2de0b2420)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/26264731/1c640e37-f64c-41fb-af8c-d2f8e4b17537)

# 日志目录中的文件
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/26264731/fb1777c2-023d-454e-aea1-434759dbd1b9)
- 2024-03-28-2021.log
```
2024-03-28 22:53:55 ERROR - Can't find VScode `unknown program name: code`
2024-03-28 22:54:06 ERROR - failed to connect to the Clash Verge Service
```

**Comment by marioplus** [comment]
vs code 已经安装
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/26264731/b58353d6-2218-4f5e-b653-13773af2f570)

**Comment by marioplus** [comment]
> 在cmd或powershell中，输入 `code .` 看看能不能唤起vscode？
> 
> 如果不能唤起，可能是vscode没添加到环境变量中。

vscode 确实没有添加到环境变量中，手动添加后，可以直接从 powershell 使用 `code .`打开。但还是不行。和日志和之前的一样。我有2两台电脑都出现了这个问题。

**Comment by marioplus** [comment]
> 有没有一种可能；修改"yaml"类型的文件默认打开程序为"Visual Studio Code"。 换一种说法，Visual Studio Code 关联文件格式?

设置 vscode 为 yaml 默认打开程序后可以打开 remote 类型订阅，设置 vscode 为 js 默认打开程序后可以打开 script 类型订阅。

**Comment by marioplus** [comment]
> @marioplus 这个使用的是系统默认打开方式，你环境变量怎么设置都不影响。 主要yaml格式文件确认设置vsc为默认打开方式了吗

[使用指南](https://clash-verge-rev.github.io/guide.html)中的“默认编辑器”指的是系统默认编辑器，还是clash-verge默认编辑器。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/26264731/5053e247-9025-4e59-960f-03881d894b38)

**Comment by marioplus** [comment]
我尝试将yaml的默认打开方式设置为 vscode/windows notepad/fleet 编辑器时可以正常打开，而设置为我的默认编辑器 [BowPad](https://github.com/stefankueng/BowPad)时，无法打开。

**Comment by dongchengjie** [comment]
是tauri插件版本问题
熊猫提过issue[How to get a Program instance when using tauri-plugin-shell](https://github.com/tauri-apps/plugins-workspace/issues/934#ref-commit-e856adc)
不清楚现在解决了没

**Comment by ziluepan** [comment]
可能是之前的默认打开vscode路径失效了，你只要在默认应用里选择在电脑上选择应用选择你vscode的exe文件打开就可以了
