### ISSUE TITLE
[BUG] Ubuntu22.04安装deb无法打开面板

### ISSUE THREAD

**Issue by Frost-Mactavish** [clash-verge-rev/clash-verge-rev#790]
### 问题描述 / Describe the bug

使用AppImage可以打开面板，使用deb安装打不开，但是可以使用代理
目前只使用了1.5.11版本

### 复现步骤 / To Reproduce

Ubuntu22.04，内核更新至最新，NVIDIA驱动版本550-server
[clash-verge_1.5.11_amd64.AppImage]
[clash-verge_1.5.11_amd64.deb]

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu22.04

### 日志 / Log

无

**Comment by Aloxaf** [comment]
是否是 https://github.com/clash-verge-rev/clash-verge-rev/issues/752 的原因？

**Comment by ly7ngf** [comment]
更改快捷方式的execcmd也许可以解决此问题，我的系统是lubuntu23.10,lxqt桌面,方法来源自原项目的这个issue
https://github.com/zzzgydi/clash-verge/issues/847#issuecomment-1791876185

**Comment by gebilxs** [comment]
问题出现甚至nvidia驱动安装步骤都一样，同样出现这样的问题

**Comment by busiqiao** [comment]
ubuntu22.04.3 内核版本在6.5.0无法显示面板，降级内核到6.2.0之后显示正常，应该就是内核问题

**Comment by busiqiao** [comment]
> ubuntu22.04.3 内核版本在6.5.0无法显示面板，降级内核到6.2.0之后显示正常，应该就是内核问题

内核升级到6.5.0了，奇怪的是这次竟然正常了
