### ISSUE TITLE
提一点意见吧，这个主体图形基于tauri，但是tauri默认是不设置代理的自己编译会有小问题，这个问题麻烦点也能解决

### ISSUE THREAD

**Issue by a937983423** [clash-verge-rev/clash-verge-rev#791]
### 问题描述 / Describe the bug

然后就是API过期等等小问题希望修复

### 复现步骤 / To Reproduce

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  VITE v5.0.11  ready in 233 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
        Info Watching /home/debian/桌面/clash-verge-rev-1.5.11/src-tauri for changes...
   Compiling clash-verge v1.5.11 (/home/debian/桌面/clash-verge-rev-1.5.11/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 13.72s

** (clash-verge:72731): WARNING **: 10:40:56.925: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.

API过时等几个小问题希望后续版本修复下

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

archlinux

### 日志 / Log

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  VITE v5.0.11  ready in 233 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
        Info Watching /home/debian/桌面/clash-verge-rev-1.5.11/src-tauri for changes...
   Compiling clash-verge v1.5.11 (/home/debian/桌面/clash-verge-rev-1.5.11/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 13.72s

** (clash-verge:72731): WARNING **: 10:40:56.925: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.

**Comment by wonfen** [comment]
欢迎PR
