### ISSUE TITLE
[BUG] 软件在后台时有概率不进行代理

### ISSUE THREAD

**Issue by zczhendev** [clash-verge-rev/clash-verge-rev#793]
### 问题描述 / Describe the bug

软件在后台是有概率不走代理，需要打开软件窗口才能代理

### 复现步骤 / To Reproduce

将软件长期放置后台（关闭UI界面或者重启后自动启动），进入需要代理的界面或者下载任务
此时进入网页缓慢，然后点击打开面板，发现面板上的网速图表开始有代理流量

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

03-29 18:31:25INFO
[TCP] 127.0.0.1:63958(msedge.exe) --> edge.microsoft.com:443 match DomainSuffix(microsoft.com) using DIRECT
03-29 18:31:26INFO
[TCP] 127.0.0.1:63974(chrome.exe) --> counter.yadro.ru:443 match Match using 狗狗加速.com[自动最优线路(hy2)-网址: dg1.top]
03-29 18:31:26INFO
[TCP] 198.18.0.1:63994(WeChat.exe) --> 183.47.121.104:80 match GeoIP(cn) using DIRECT
03-29 18:31:26INFO
[TCP] 198.18.0.1:63993(WeChat.exe) --> 14.116.242.216:80 match GeoIP(cn) using DIRECT
03-29 18:31:26INFO
[TCP] 198.18.0.1:63991(WeChat.exe) --> 123.151.48.193:80 match GeoIP(cn) using DIRECT
03-29 18:31:26INFO
[TCP] 127.0.0.1:63997(chrome.exe) --> content-autofill.googleapis.com:443 match DomainKeyword(google) using 狗狗加速.com[自动最优线路(hy2)-网址: dg1.top]
03-29 18:31:26INFO
[TCP] 127.0.0.1:64007(chrome.exe) --> zh.z-library.se:443 match Match using 狗狗加速.com[自动最优线路(hy2)-网址: dg1.top]
03-29 18:31:27INFO
[TCP] 127.0.0.1:64013(chrome.exe) --> s3proxy.cdn-zlib.se:443 match Match using 狗狗加速.com[自动最优线路(hy2)-网址: dg1.top]
03-29 18:31:27INFO
[TCP] 127.0.0.1:64030(chrome.exe) --> mtalk.google.com:5228 match DomainKeyword(google) using 狗狗加速.com[自动最优线路(hy2)-网址: dg1.top]
03-29 18:31:28INFO
[TCP] 127.0.0.1:64031(msedge.exe) --> prod-eastasia.access-point.cloudmessaging.edge.microsoft.com:443 match DomainSuffix(microsoft.com) using DIRECT
03-29 18:31:28INFO
[TCP] 198.18.0.1:64058(svchost.exe) --> www.msftconnecttest.com:80 match Match using 狗狗加速.com[自动最优线路(hy2)-网址: dg1.top]
03-29 18:31:28INFO
[TCP] 198.18.0.1:64059(OSDService.exe) --> update.pc.mi.com:443 match DomainSuffix(mi.com) using DIRECT

**Comment by wonfen** [comment]
无法复现，看着像内核bug；切换alpha内核并升级最新内核试试。
