### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TurnOffNOD** [clash-verge-rev/clash-verge-rev#794]
### 问题描述 / Describe the bug

debian下用dpkg安装了deb的方式安装了clash-verge-rev，安装之后无法打开界面，有托盘图标。

### 复现步骤 / To Reproduce

使用debian发行版。
1. 下载deb安装文件，dpkg -i安装，用apt install -f安装相关依赖；
2. 在开始菜单中找到图标，点击打开，此时无法打开界面，有托盘图标，截图如下：
![Screenshot_20240329_183536](https://github.com/clash-verge-rev/clash-verge-rev/assets/2140029/cbc865ab-b240-4c76-a7fc-bd4497151359)
4. 在命令行中使用clash-verge打开，同样无法打开界面，并且验证了内核clash-meta两个版本都能正常启动，截图如下：
![Screenshot_20240329_183858](https://github.com/clash-verge-rev/clash-verge-rev/assets/2140029/2ae99679-5e40-478c-b745-6e7311e9bb02)

这个问题在原版clash-verge也有，不过原版是白屏，提交的issue为：zzzgydi/clash-verge#808

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

debian sid，发帖时apt update并且dist-upgrade过了

### 日志 / Log

```
$ clash-verge 
src/nv_gbm.c:288: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

src/nv_gbm.c:288: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 800x642: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 800x642: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 800x642: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
```

**Comment by wonfen** [comment]
搜一下日志中的那一堆 permission deny是怎么回事？

**Comment by Current-River** [comment]
> 1.6.2版可以用了，面板能打开了。

ubuntu有1.6.2？哪里呀

**Comment by TurnOffNOD** [comment]
> > 1.6.2版可以用了，面板能打开了。
> 
> ubuntu有1.6.2？哪里呀

这位网友你的反射弧是不是长了一点……

直接看最新版吧，别纠结1.6.2这个版本了。
