### ISSUE TITLE
[BUG] Linux 打开界面是花屏，resize之后正常显示

### ISSUE THREAD

**Issue by wencan** [clash-verge-rev/clash-verge-rev#795]
### 问题描述 / Describe the bug

https://github.com/clash-verge-rev/clash-verge-rev/issues/237
跟上面的问题应该一致

![Screenshot from 2024-03-29 19-05-15](https://github.com/clash-verge-rev/clash-verge-rev/assets/1072917/8d77c123-0541-4113-b45b-7df7cc9e8008)

Fedora Linux 39 (Workstation Edition) x86_64 
Clash Verge Rev v1.5.11 
Alpha版和非Alpha版都存在这个问题

### 复现步骤 / To Reproduce

直接打开，就可以看到花屏

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Fedora Linux 39 (Workstation Edition) x86_64 

### 日志 / Log

OS: Fedora Linux 39 (Workstation Edition) x86_64 
Kernel: 6.7.10-200.fc39.x86_64 
Uptime: 42 mins 
Packages: 2237 (rpm), 47 (flatpak) 
Shell: bash 5.2.26 
Resolution: 2560x1440 
DE: GNOME 45.5 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 1800X (16) @ 3.600GHz 
GPU: NVIDIA GeForce GTX 1080 Ti 
Memory: 4507MiB / 15892MiB

**Comment by RexLeeGrey** [comment]
测试后，其不支持x11，只支持wayland。x11下resize无效，wayland下拖动后可以成功显示。

**Comment by JohananLee** [comment]
WEBKIT_DISABLE_COMPOSITING_MODE=1 同F39，这样启动就好了

**Comment by RexLeeGrey** [comment]
> WEBKIT_DISABLE_COMPOSITING_MODE=1 同F39，这样启动就好了

啥意思啊？不太懂

**Comment by RexLeeGrey** [comment]
> WEBKIT_DISABLE_COMPOSITING_MODE=1 同F39，这样启动就好了

感谢
