### ISSUE TITLE
[BUG]  AppImage 无法输入

### ISSUE THREAD

**Issue by Cirno9-dev** [clash-verge-rev/clash-verge-rev#796]
### 问题描述 / Describe the bug

运行 AppImage 后，在界面中输入无响应，也没有办法复制和粘贴。

### 复现步骤 / To Reproduce

1. 运行 clash-verge_1.5.11.AppImage
2. 在订阅 url 处输入无响应
3. 也不能复制粘贴

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

archlinux 6.8.2-arch2-1 hyprland

### 日志 / Log

** (clash-verge:7032): WARNING **: 21:53:15.467: atk-bridge: get_device_events_reply: unknown signature
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so

(WebKitWebProcess:7714): GLib-GObject-WARNING **: 21:55:38.076: g_object_set_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
/usr/lib/libproxy/libpxbackend-1.0.so: undefined symbol: g_strv_builder_unref
Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
/usr/lib/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiognomeproxy.so
/tmp/.mount_clash-OLkFr9/usr/lib/libgnutls.so.30: version `GNUTLS_3_7_4' not found (required by /usr/lib/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/gio/modules/libgiognutls.so

**Comment by wonfen** [comment]
看不懂是什么问题，需要帮助

**Comment by Cirno9-dev** [comment]
例如，我需要填写我的订阅链接，但是输入框中无法输入任何字符。

**Comment by MystiPanda** [comment]
不要用appimage，想考虑把appimage删了

**Comment by Cirno9-dev** [comment]
今天莫名奇妙可以输入了，应该是某些库的问题。
