### ISSUE TITLE
[BUG] merge文件 怎么没法启用了，之前用的好好的

### ISSUE THREAD

**Issue by flylj999** [clash-verge-rev/clash-verge-rev#805]
### 问题描述 / Describe the bug

merge文件 怎么没法启用了，之前用的好好的

### 复现步骤 / To Reproduce

merge文件 怎么没法启用了，之前用的好好的

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

merge文件 怎么没法启用了，之前用的好好的

**Comment by wonfen** [comment]
日志？
