### ISSUE TITLE
[BUG] 使用vless只使用系统代理测速全红

### ISSUE THREAD

**Issue by woshinibb66** [clash-verge-rev/clash-verge-rev#806]
### 问题描述 / Describe the bug

使用vless只使用系统代理测速全红 开启 tun 测速正常  然而换另一个机场的ssr的节点 只使用系统代理却能正常使用

### 复现步骤 / To Reproduce

使用vless只使用系统代理测速全红 开启 tun 测速正常  然而换另一个机场的ssr的节点 只使用系统代理却能正常使用

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

使用vless只使用系统代理测速全红

**Comment by fuyongzk** [comment]
遇到同样的问题

**Comment by wonfen** [comment]
日志？

**Comment by KomeijiReimu** [comment]
> Collaborator

@wonfen 
 遇见同样的问题，对于订阅转换的规则ping不通，解决办法只有更换内核，重启内核无效。不过这并不表明是内核问题，问题的解决与使用哪个版本的内核没有关联，只是因为关闭了一个内核后重新打开了一个新内核。对于新打开的内核，重启verge后也会遇到相同的问题。日志没有任何内容，除了一行 `INFO - reset proxy to the original proxy `

**Comment by qppq54s** [comment]
1.7.0版本更新后，测速全红，日志为 `2024-07-03 08:59:03 ERROR - failed to get the profile item "uid:"`
