### ISSUE TITLE
[BUG] icon 无法正常加载

### ISSUE THREAD

**Issue by vzyw** [clash-verge-rev/clash-verge-rev#808]
### 问题描述 / Describe the bug
icon 无法正常显示
<img width="159" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/13702483/7ed90449-1794-48c3-9d9f-4d8465fc228a">

### 复现步骤 / To Reproduce

在配置文件中
<img width="642" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/13702483/18cc9de0-8210-4bbd-8f5b-0351d556fbd4">

icon 链接为 https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Area.png 可以正常显示
icon 链接为 https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Area.png 则无法显示
### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.4.1

### 日志 / Log

<img width="1256" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/13702483/6f4e8362-5b80-4a74-aac5-7dea06e26fde">

**Comment by dongchengjie** [comment]
现在的图片是先下载下来到本地，存放到`io.github.clash-verge-rev.clash-verge-rev\icons\cache`，然后将其转为`base64`merge到运行时配置，点击右上角可以查看
你可以去检测文件下载下来了没有，再去看merge成功没有
从assets://协议来看，像是文件没找到。我估计呐，十有八九是镜像下载失败的原因（有的镜像只能直连开代理反倒连不上，而恰好你又没配置直连规则）
1、换图床
2、换镜像，mirror.ghproxy.com这个我感觉最可靠
```
https://mirror.ghproxy.com/
```
3、一开始就手动[转成base64](https://www.jyshare.com/front-end/59/)，走到哪都可以正常显示
<img width="632" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/d6e1408e-eee2-4f91-b6a3-4492a16e50d5">

**Comment by ivensfor** [comment]
圖標已經緩存到了本地，但是在策略組中依然不顯示。在配置中 `icon` 是填寫圖標的 url，啟用後在 `當前配置` 中查看並沒有轉為 base64。
