### ISSUE TITLE
[BUG] 后台占用CPU，时间放的越久占用越多。

### ISSUE THREAD

**Issue by shum-elli** [clash-verge-rev/clash-verge-rev#809]
### 问题描述 / Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/79710429/e3fe9037-4bde-449d-adda-c5a92e8bd34a)
将Clash 调出然后最小化即可复现，时间越长占用越多，最高能到20%。 5800h笔记本。
任务管理器看是webview占用，建议如果是meta内核占用就别发在这了。

### 复现步骤 / To Reproduce

将Clash 调出然后最小化即可复现，时间越长占用越多，最高能到20%。 5800h笔记本

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 23h2

### 日志 / Log

无

**Comment by neo-fan** [comment]
同样问题 i5-13500H也遇到

**Comment by wkf16** [comment]
同样的问题12600kf，最高30%

**Comment by wkf16** [comment]
![pig](https://github.com/clash-verge-rev/clash-verge-rev/assets/147919460/4ba8c7b3-57a9-4d44-a60b-173df7f7d1c1)

**Comment by shum-elli** [comment]
> ![pig](https://private-user-images.githubusercontent.com/147919460/318349643-4ba8c7b3-57a9-4d44-a60b-173df7f7d1c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTExMzYsIm5iZiI6MTcxMTk1MDgzNiwicGF0aCI6Ii8xNDc5MTk0NjAvMzE4MzQ5NjQzLTRiYThjN2IzLTU3YTktNGQ0NC1hNjBiLTE3M2RmN2Y3ZDFjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwNTUzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmU4NjY1ZWUyY2UwODAyNWYwYTA3ZTY5ZWI4YThmNmMzMzA3ODdlMWNjMDEzZDQzNDk0MTAyMDE3MWMxZjM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eLeYizuYpPWsW7NWtY4GyvqCJMuWv12g60XC_OBeqEM)

你这个貌似会我不一样，你是meta内核的占用，我这个看起来是前端的问题

**Comment by neo-fan** [comment]
> 同样问题 i5-13500H也遇到

开启clash 使用dege观看虎牙直播 直接卡死。关闭clash后正常

**Comment by fuyongzk** [comment]
<img width="371" alt="ph345" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/120019530/e75bbca1-9d92-414d-9627-bc53e7f3f8c1">
我的更疯狂

**Comment by fuyongzk** [comment]
绝了
<img width="379" alt="搜狗截图20240401151019" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/120019530/520c71b9-4117-4eb0-996d-e3d5bdbbd40f">
<img width="371" alt="ph345" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/120019530/96747243-328c-4485-9055-88318ddf2905">

**Comment by shum-elli** [comment]
> 实测开启tun模式后断开网络会触发，也奇怪，设置的自动更新订阅24小时，一看3天没更新了，断网又检测更新。 ![PixPin_2024-04-01_13-07-52](https://private-user-images.githubusercontent.com/68383493/318405457-dcdcc833-f6f7-43ef-acc9-a2e485419818.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5Njc2NTgsIm5iZiI6MTcxMTk2NzM1OCwicGF0aCI6Ii82ODM4MzQ5My8zMTg0MDU0NTctZGNkY2M4MzMtZjZmNy00M2VmLWFjYzktYTJlNDg1NDE5ODE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEwMjkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYWQ4NTlhODI0NWFhOGE0ZThjZWNmNDM0MjM3Nzc1ZDM3MmRkYzA2ODEyNDViYmI5YjQ0NDFjMTFhZmIyN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D3PEPQtb2vWhs50ly2w0lUjR4QZzYi9F07XyRVxLqro) ![PixPin_2024-04-01_13-34-03](https://private-user-images.githubusercontent.com/68383493/318405487-2df0b804-f4f6-44a4-8b15-3d5bc89df10e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5Njc2NTgsIm5iZiI6MTcxMTk2NzM1OCwicGF0aCI6Ii82ODM4MzQ5My8zMTg0MDU0ODctMmRmMGI4MDQtZjRmNi00NGE0LThiMTUtM2Q1YmM4OWRmMTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEwMjkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNWRiOGRkYmI0Y2RiZTQxN2EwNzFmNmM2MDFkODc1OGY4OWE0ZDg2NjNiOTFkNDZlZTQyZGRiZWMwZmI0YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cHs04TbO6DhPJ5yKGeGPviGen365mBCc_tXAOc4NiDk)

这是meta内核啊，去meta内核那边去提issue

**Comment by gt-sun** [comment]
mac 上面也同样 CPU 占用一打开之后就很高，看到进程是 clash verge web content。

**Comment by Chasing66** [comment]
跟进一下，最近两个版本开始遇到这个问题，CPU一度吃满到90%，搞得我都换hiddfy了
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/32839114/85e3bbe2-b714-4eb1-8001-8dbfc81c8c05)

**Comment by shum-elli** [comment]
补一张图  ubuntu22上的 更离谱了
![747db8cd8207c4a49cab694063043f5b](https://github.com/clash-verge-rev/clash-verge-rev/assets/79710429/f7723c7f-f685-4e3d-8223-b4f0eeb24bcc)

**Comment by Vincent-ZHENG-008** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/22773392/076d0878-5741-42bc-8ad1-c2470aa183b4)
Same on Archlinux

**Comment by chen2438** [comment]
Same on R7 5800H + Windows 11
