### ISSUE TITLE
[Feature] 添加全局可忽略的域名

### ISSUE THREAD

**Issue by zhangfurun** [clash-verge-rev/clash-verge-rev#810]
### 功能描述 / Feature description

如  我希望*.baidu.com不走代理, 这部分可以参考 clash系列的更多设置中

### 使用场景 / Use case

如  我希望*.baidu.com不走代理

**Comment by dongchengjie** [comment]
啊？！配置规则啊
如果是机场的订阅，刷新会覆盖，就写merge啊
<img width="622" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/fd1219f6-61bf-4d08-bb1b-00d979d3097d">

**Comment by zhangfurun** [comment]
![截屏2024-04-01 15 12 08](https://github.com/clash-verge-rev/clash-verge-rev/assets/16497944/08240d06-dc3f-4cab-a4f3-87ed68efc127)
![截屏2024-04-01 15 12 15](https://github.com/clash-verge-rev/clash-verge-rev/assets/16497944/ac1277c7-ce60-4ed8-b6f1-6b393470caaa)
类似这种的, 可以全局设置, 这样比较方便, 对于一些内网访问或者固定ip访问比较好

**Comment by SeaSpring17** [comment]
请问下，这个域名要怎么设置（https://api-ipv6.ip.sb/ip）
我试着添加了 以下几个，都生效不了
  - DOMAIN,api-ipv6.ip.sb,DIRECT
  - DOMAIN,api-ipv6.ip.sb/ip,DIRECT
  - DOMAIN-KEYWORD,api-ipv6,DIRECT
  
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/66456697/8f8f299d-e188-4876-ace9-edbfc98cbbc7)

**Comment by dongchengjie** [comment]
@SeaSpring17  好使的啊，Merge配置目前**必须右键**才能启用，别是没有激活吧
```
prepend-rules:
  - DOMAIN,api-ipv6.ip.sb,全局直连
```
<img width="611" alt="无标题2" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/cf00d19e-20cc-4dc9-b82f-209c857d2d1f">

<img width="636" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/6caa4b92-20be-4c0f-b506-96793a14f59c">

**Comment by dongchengjie** [comment]
@zhangfurun 这个也有的，在`设置`->`系统代理`**左边的小齿轮**，代理绕过
> 类似这种的, 可以全局设置, 这样比较方便, 对于一些内网访问或者固定ip访问比较好

**Comment by SeaSpring17** [comment]
> @SeaSpring17 好使的啊，Merge配置目前**必须右键**才能启用，别是没有激活吧 **-**前面必须两个空格，不能是tab
> 
> ```
> # 这里的直连是我的代理组，DIRECT就是直连
> prepend-rules:
>   - DOMAIN,api-ipv6.ip.sb,全局直连
> ```
> 
> <img alt="无标题2" width="611" src="https://private-user-images.githubusercontent.com/37543964/318437061-cf00d19e-20cc-4dc9-b82f-209c857d2d1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjIxMjksIm5iZiI6MTcxMjAyMTgyOSwicGF0aCI6Ii8zNzU0Mzk2NC8zMTg0MzcwNjEtY2YwMGQxOWUtMjBjYy00ZGM5LWI4MmYtMjA5Yzg1N2QyZDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDAxMzcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNjQxNGMxMjhhMjM2NTk3ZTdkYjYzNzc4ZWQxYjIxZDZmNDVmMWQ3NDMxN2M5ZDRiMjIzMjY3MjJlYTU1YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ehuh7HLnGCr8bfKBKkjEL8RFo4dKXOkgVJPKaKX9suk"> <img alt="无标题" width="636" src="https://private-user-images.githubusercontent.com/37543964/318436440-6caa4b92-20be-4c0f-b506-96793a14f59c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjIxMjksIm5iZiI6MTcxMjAyMTgyOSwicGF0aCI6Ii8zNzU0Mzk2NC8zMTg0MzY0NDAtNmNhYTRiOTItMjBiZS00YzBmLWI1MDYtOTY3OTNhMTRmNTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDAxMzcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YTYzMWQyNWNmMTYxYWJmMzA4MTQ4ZmIxMzdmMjA5NjY1MTYzOWFmZjEyYTVhNmRlYzU0Y2ZhNDFkYjZjMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7htRp4PNKkmjZIJ45Vy3eCKbwfQ1Muw7TRQgqPeswsA">

非常感谢！解决了~

**Comment by SeaSpring17** [comment]
@dongchengjie 非常感谢，问题解决了！

**Comment by QingYu626** [comment]
> > 类似这种的, 可以全局设置, 这样比较方便, 对于一些内网访问或者固定ip访问比较好
> 
> @zhangfurun 这个也有的，在`设置`->`系统代理`**左边的小齿轮**，代理绕过

请问，这个代理绕过的填写规则是什么呢？麻烦教一下呗，谢谢您

**Comment by dongchengjie** [comment]
@QingYu626 那个页面滚轮往下拉，有当前绕过的例子，依葫芦画瓢

**Comment by helloogq** [comment]
> > 类似这种的, 可以全局设置, 这样比较方便, 对于一些内网访问或者固定ip访问比较好
> 
> @zhangfurun 这个也有的，在`设置`->`系统代理`**左边的小齿轮**，代理绕过

完美解决了，非常感谢

**Comment by work-demo-alt** [comment]
> @SeaSpring17 好使的啊，Merge配置目前**必须右键**才能启用，别是没有激活吧 **-**前面必须两个空格，不能是tab
> 
> ```
> # 这里的直连是我的代理组，DIRECT就是直连
> prepend-rules:
>   - DOMAIN,api-ipv6.ip.sb,全局直连
> ```
> 
> <img alt="无标题2" width="611" src="https://private-user-images.githubusercontent.com/37543964/318437061-cf00d19e-20cc-4dc9-b82f-209c857d2d1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTgzMjUsIm5iZiI6MTcyNzMxODAyNSwicGF0aCI6Ii8zNzU0Mzk2NC8zMTg0MzcwNjEtY2YwMGQxOWUtMjBjYy00ZGM5LWI4MmYtMjA5Yzg1N2QyZDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDAyMzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4OTcyMWUzMDU0NjRmMjVkMmY5YTBjZGQ3NTMzZGQwZTYzZDFiNWZiYjNkNGNkMmE2MGMyYzM4YTgwZmJkNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cYGP8Rz3kDnvw3baKBtSAOE20MpWRtZCpJnWzYU6blE"> <img alt="无标题" width="636" src="https://private-user-images.githubusercontent.com/37543964/318436440-6caa4b92-20be-4c0f-b506-96793a14f59c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTgzMjUsIm5iZiI6MTcyNzMxODAyNSwicGF0aCI6Ii8zNzU0Mzk2NC8zMTg0MzY0NDAtNmNhYTRiOTItMjBiZS00YzBmLWI1MDYtOTY3OTNhMTRmNTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDAyMzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4Mzk0ZDNjYWYzMjJlZTVlMDllYTI2NjBmZWQ3Njk2NzA3MDJlNDhmNjE5NzZmZjU0OWI5NzgwNzExYWYxNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aCLLq_H0jwPb0RP9mGMXM-p3jz3tRpDur0jP5auRJ1w">

这里的要注意正确的格式是这样的, 不要漏掉SUFFIX:
-- DOMAIN-SUFFIX,网址,DIRECT
![image](https://github.com/user-attachments/assets/0b839b62-d357-4bc3-8cf5-517b42719de5)

**Comment by bolee** [comment]
如果该域名已经在规则里面，怎么添加自定义规则，优先走我设置的规则，比如raw.githubusercontent.com，这个github的下载域名系统匹配的GeoIP走的是全球直连规则，但是我想让他走代理。目前添加了前置规则无效，依然走的是的是全球直连规则，无法匹配到我增加的规则

**Comment by LiMao00** [comment]
> 啊？！配置规则啊，想自建规则集就rule-provider啊 如果是机场的订阅，刷新会覆盖，就写merge啊 <img alt="无标题" width="622" src="https://private-user-images.githubusercontent.com/37543964/318354903-fd1219f6-61bf-4d08-bb1b-00d979d3097d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY3NjU1MDcsIm5iZiI6MTc0Njc2NTIwNywicGF0aCI6Ii8zNzU0Mzk2NC8zMTgzNTQ5MDMtZmQxMjE5ZjYtNjFiZi00ZDA4LWJiMWItMDBkOTc5ZDMwOTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTA5VDA0MzMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NThlMWJiMThlZjBiY2U2OWQwNWUyZGY4MjQ2YTczOTM4MGNkYzMxYTliMDRkYzlkNDYxYjZkOTBiMWUyOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xiT8mwgWKxJdm4GXpobshe2RpnPLPDVeXmUoU_tvbHg">

那怎么反过来？就是所有域名都忽略，然后指定的域名才可以使用代理

**Comment by 2416210017** [comment]
> > 类似这种的, 可以全局设置, 这样比较方便, 对于一些内网访问或者固定ip访问比较好
> 
> [@zhangfurun](https://github.com/zhangfurun) 这个也有的，在`设置`->`系统代理`**左边的小齿轮**，代理绕过

更新版本又变了？这里编辑不了呀，大佬
<img width="1920" height="1001" alt="Image" src="https://github.com/user-attachments/assets/40cfea89-30ac-4123-b72b-8c6898864bff" />

**Comment by 2416210017** [comment]
> > > 类似这种的, 可以全局设置, 这样比较方便, 对于一些内网访问或者固定ip访问比较好
> > 
> > 
> > [@zhangfurun](https://github.com/zhangfurun) 这个也有的，在`设置`->`系统代理`**左边的小齿轮**，代理绕过
> 
> 更新版本又变了？这里编辑不了呀，大佬 <img alt="Image" width="1920" height="1001" src="https://private-user-images.githubusercontent.com/52597892/590173646-40cfea89-30ac-4123-b72b-8c6898864bff.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzg0NjU1NDcsIm5iZiI6MTc3ODQ2NTI0NywicGF0aCI6Ii81MjU5Nzg5Mi81OTAxNzM2NDYtNDBjZmVhODktMzBhYy00MTIzLWI3MmItOGM2ODk4ODY0YmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNTExVDAyMDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNjNlZTk2N2JiZjU0MTA0ZDM4ZmFjZDU2MzI3NjMyMDI3NWI2ODMwOGE5OTFiN2QzOTNlN2E5MDgxOGZhZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.lWbmiE1w2bAPXov52AZofcCKbxXwxeuUQiCj_n-Rot4">

找到了，需要把<始终使用默认绕过>这里取消勾选。

<img width="1920" height="1001" alt="Image" src="https://github.com/user-attachments/assets/d57af5e4-6d02-4b82-b615-3476f5810169" />

**Comment by helloint** [comment]
> 啊？！配置规则啊，想自建规则集就rule-provider啊 如果是机场的订阅，刷新会覆盖，就写merge啊 <img alt="无标题" width="622" src="https://private-user-images.githubusercontent.com/37543964/318354903-fd1219f6-61bf-4d08-bb1b-00d979d3097d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODY2NzU4NDIsIm5iZiI6MTc4NjY3NTU0MiwicGF0aCI6Ii8zNzU0Mzk2NC8zMTgzNTQ5MDMtZmQxMjE5ZjYtNjFiZi00ZDA4LWJiMWItMDBkOTc5ZDMwOTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODE0VDAyNDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MzA5NGQyYzg1ZTU5N2MxMzIyN2U1ZTUwNGJjYWZkNGY5ZTQ3ZWViZGRhZmM5YjExMjljMmMwMmJmMTUyZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.0DrCeePiaeRlBwMzmH4bYpkYDgwHJzY8qZD9jRqOM14">

请问这个Merge Template是怎么点出来的？

<img width="179" alt="Image" src="https://github.com/user-attachments/assets/0d7d3976-e53b-40fb-8640-ecf0d4ef0640" />
