### ISSUE TITLE
希望能添加系统代理状态和TUN模式的全局弹窗[Feature] 

### ISSUE THREAD

**Issue by Ffffffffchopin** [clash-verge-rev/clash-verge-rev#811]
### 功能描述 / Feature description

目前在窗口中改变TUN模式状态时会提示"Refresh clash config"，希望能添加类似的弹窗在全局的窗口中，即在关闭Clash窗口之后在别的应该中也会在右上角弹窗告知TUN模式或系统代理的状态

### 使用场景 / Use case

这样就不需要每次开关系统的代理的时候都要切换到Clash界面中

**Comment by wonfen** [comment]
是否启用tun模式有不同的任务栏图标区分。
