### ISSUE TITLE
[Feature] 再提交一下：mac 系统上的菜单栏增强

### ISSUE THREAD

**Issue by Amnesiash** [clash-verge-rev/clash-verge-rev#812]
### 功能描述 / Feature description

参考 clashx 加入增强版菜单栏
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/44333360/6bdc3144-9481-4bba-bb78-8d4a1cf6cb7f)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/44333360/1c61c408-a1b6-49f6-a9be-18de7b6943a2)

### 使用场景 / Use case

快速进行节点切换、延迟测速

**Comment by wonfen** [comment]
对性能有比较大的影响，等v2出来再看看。

**Comment by logicr** [comment]
> 对性能有比较大的影响，等v2出来再看看。

加个显示网速呗 🤧

**Comment by cikichen** [comment]
这功能啥时候能更新？
