### ISSUE TITLE
[BUG] 更新至1.5.11 后 Socks5 代理连接不上

### ISSUE THREAD

**Issue by COREPanda777** [clash-verge-rev/clash-verge-rev#817]
### 问题描述 / Describe the bug

[BUG] 更新至1.5.11 后 Socks5 代理连接不上 而http代理是正常的
<img width="567" alt="截屏2024-04-01 17 05 11" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/43985195/0fc116e7-f86d-4fa2-8b33-f6db80f05412">
<img width="567" alt="截屏2024-04-01 17 08 12" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/43985195/03407044-b5d2-40ff-8a4e-7c21fcf7aa74">

### 复现步骤 / To Reproduce

无，看问题描述

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Sonoma 14.4.1 

### 日志 / Log

无

**Comment by dongchengjie** [comment]
7890是mixed端口吗

**Comment by wonfen** [comment]
软件默认是7897端口

**Comment by COREPanda777** [comment]
回复一下，抱歉，我自己傻了！  我自己手动改过端口     我把Http和socks的端口改成一样的了    导致端口冲突，使用混合端口也不行，我已经解决了，是我自己SB了 哈哈哈 打扰了
