### ISSUE TITLE
[BUG] macOS 启用 tun 后，命令行依然无法与 google 建立 https 连接

### ISSUE THREAD

**Issue by sainnhe** [clash-verge-rev/clash-verge-rev#82]
**Describe the bug**
1. 我的配置不包含 tun 相关字段
2. 这套配置在 ClashX Pro 中启用“增强模式”后，可以在不设置环境变量的情况下，在 iTerm2 中用 curl 或 w3m 与 google 建立连接
3. 同样一套配置，在 Clash Verge Rev 中启用 tun 模式并在设置中对 Clash Meta 内核进行授权后，可以 ping 通 google.com，但无法用 curl 或 w3m 建立 https 连接

**To Reproduce**

1. 开启 tun 模式
2. 在设置中对 Clash Meta 内核进行授权
3. 在 Shell 中执行 `ping www.google.com` 显示可以通
4. 在 Shell 中执行 `curl -v https://www.google.com` 无法建立连接

```text
~
❯ ping www.google.com
PING www.google.com (199.59.150.40): 56 data bytes
64 bytes from 199.59.150.40: icmp_seq=0 ttl=64 time=0.533 ms
64 bytes from 199.59.150.40: icmp_seq=1 ttl=64 time=0.596 ms
64 bytes from 199.59.150.40: icmp_seq=2 ttl=64 time=0.471 ms
64 bytes from 199.59.150.40: icmp_seq=3 ttl=64 time=0.534 ms
^C
--- www.google.com ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.471/0.534/0.596/0.044 ms

~
❯ curl -v https://www.google.com
*   Trying 199.59.150.40:443...
* Connected to www.google.com (199.59.150.40) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /opt/local/share/curl/curl-ca-bundle.crt
*  CApath: none
^C
```

**Expected behavior**
curl 能正常建立连接

**Screenshots**

**Information**

- OS: macOS 14.1.2
- Clash Verge Version: v1.4.3
- Clash Core: Clash Meta

**Additional context**

**Comment by bosco8833** [comment]
我也有类似的问题，我是hy节点， google和youtube连不上。 vless节点正常，没问题。

**Comment by sainnhe** [comment]
我的是 Trojan 节点，没法连上

**Comment by llity** [comment]
Auth failed from 127.0.0.1
怎么没法代理呢

**Comment by JACK-THINK** [comment]
这是在原版Clash-Verge for MacOS中就存在的[Bug](https://github.com/zzzgydi/clash-verge/issues/82#issuecomment-1328742285)，直到项目被存档，此Bug也没被修复……

**Comment by BigBen12138** [comment]
我也遇到了这样的情况，可以ping通，但是不能http访问，并且日志里显示的全部都是ip，不是域名。
我的解决方法是把tun字段下的stack: "gvisor"改成了stack: "mixed"，就可以正常使用了。不知道能不能帮助到你。
