### ISSUE TITLE
[BUG] windows无法安装服务模式

### ISSUE THREAD

**Issue by NeonBubbles** [clash-verge-rev/clash-verge-rev#820]
### 问题描述 / Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/43613294/e5ff250c-09e1-430a-8d37-132fdfe44536)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/43613294/689b5202-7aae-486d-9253-b9e51061160b)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/43613294/4b505047-6040-4b35-b108-4f00a09cbe59)

- verge里安装服务模式提示与64位系统不兼容
- 在文件夹中手动点击运行installer-service.exe 直接提示此应用无法在你的电脑上运行
- 使用管理员模式运行installer-service.exe，会提示”Windows找不到文件'C:\Program Files\Clash Verge\resources\install--service.exe'。请确定文件名是否正确后，再试一次。“
- 文件夹中直接卸载uninstall-service.exe没什么反应，之后再去安装服务模式还是会遇到上面的问题

### 复现步骤 / To Reproduce

verge设置里点击安装服务模式

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows10企业版LTSC

### 日志 / Log

无

**Comment by NeonBubbles** [comment]
即使无法安装服务模式似乎也不影响tun的使用，虽然我在文档里就看到服务模式的作用就是不用管理员就能直接使用tun，但在verge的tun模式感叹号图标那里，还是提示使用tun前先打开服务模式

**Comment by JokingAboutLife** [comment]
估计是服务模式的安装脚本下载错了，等待这个PR #822 合并后再试吧

**Comment by JasonLam90** [comment]
没有阿，我文件夹中直接双击运行uninstall-service.exe，之后再去安装服务模式不会遇到上面的问题，能正常安装的

**Comment by UselessWater** [comment]
![image](https://github.com/user-attachments/assets/5ee8729f-5f5d-4329-96ce-1125f51d6fb4)
```
/*
这个麻烦修复一下，应该不是很困难嘛
*/
```

**Comment by UselessWater** [comment]
# 这个版本内置的服务模块安装包有问题，我把之前电脑上存留的1.3.8版本的服务模块复制过去，发现可以安装并且正常使用，麻烦作者改一下。谢谢
