### ISSUE TITLE
新版本无法更新订阅

### ISSUE THREAD

**Issue by lxtx528** [clash-verge-rev/clash-verge-rev#823]
### 问题描述 / Describe the bug

相同订阅链接之前都能更新，但是更新到最新版后无法更新了。

### 复现步骤 / To Reproduce

其他clash系列app都可以更新。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Mac OS10.15.7和11.7.10

### 日志 / Log

无

**Comment by ansemz** [comment]
应该是clash verge对ipv6的支持有问题

**Comment by wonfen** [comment]
日志？

**Comment by undosh77** [comment]
1.5.11版本，我也是这个问题，无法远程更新。
显示：error sending request for url (https://xxxxxxx) client error (Connect)
1.5.10版本，可以远程更新

操作系统 MacOS 14.4.1

*PS. Windows11 系统下 1.5.11版本 远程更新 Reflesh clash config 没有问题。问题只在Mac系统下发生。

**Comment by wonfen** [comment]
无法复现，检查你们的网络问题。

**Comment by HenryLuoCN** [comment]
我是1.5.11，Mac14.2，确认能更新订阅，没开IPV6和TUN

**Comment by ansemz** [comment]
windows11+clash verge rev 1.5.11，刚才又测试了一下。可以正常更新了。
可能是dns缓存的原因。

> 应该是clash verge对ipv6的支持有问题.。 我最近启用了ipv6，更新raw.githubusercontent.com的订阅的时候，一直是链接错误。 但是用浏览器测试是正确的。
