### ISSUE TITLE
[Feature] 希望能增加预处理/parser功能

### ISSUE THREAD

**Issue by w51fa651g6ag** [clash-verge-rev/clash-verge-rev#824]
### 功能描述 / Feature description

类似cfw的预处理功能

### 使用场景 / Use case

自定义各种功能且能随时更新新需求

**Comment by ypwcharles** [comment]
同样想要这个功能

**Comment by w51fa651g6ag** [comment]
> 请 https://clash-verge-rev.github.io/guide.html#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86

感谢,之前没找到原来在这里
