### ISSUE TITLE
忽略吧

### ISSUE THREAD

**Issue by qinpeihe** [clash-verge-rev/clash-verge-rev#825]
### 功能描述 / Feature description

能否增加“修改配置文件”的功能？目前为“只读”状态

### 使用场景 / Use case

有一些网站需要过滤

**Comment by wzlee** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/4182865/7629cc64-dd7b-43d8-91a7-106b20696dcf)
点这个图标可以设置bypass
