### ISSUE TITLE
[Feature] 深色模式下的任务栏右键界面

### ISSUE THREAD

**Issue by Jeremy-yjl** [clash-verge-rev/clash-verge-rev#826]
### 功能描述 / Feature description

深色模式下任务栏右键窗口仍为浅色
![屏幕截图 2024-04-03 153931](https://github.com/clash-verge-rev/clash-verge-rev/assets/136414552/d8a9a9e7-1bcb-4b24-b5f0-a0c2af38a053)

### 使用场景 / Use case

任务栏

**Comment by dongchengjie** [comment]
估计得等Tauri v2版本，现在还是beta版
https://github.com/tauri-apps/tauri/issues/6645#issuecomment-1676615439

**Comment by wonfen** [comment]
2.0已实现。
