### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by VinsonFather** [clash-verge-rev/clash-verge-rev#827]
### 问题描述 / Describe the bug

1，有概率出现点击延迟测速无反应
2，有概率全error，再次进行延迟测速便恢复正常

### 复现步骤 / To Reproduce

第一个问题：
-1，关闭Clash Verge
-2，打开clash verge
-3，立即进行测速
第二个问题：
-1，关闭Clash Verge
-2，打开clash verge
-3，多次进行测速

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS 12.7.4

### 日志 / Log

no

**Comment by lbcake** [comment]
测试无反应 是需要所有节点都测出来结果 才能再次测速 （不支持 第一次点击测速 所有节点还没出结果 就立刻重置第一次，不能立刻下一次测速） 这个前端易用性问题现在超级多   很多无缝的显示功能现在全都有问题。

另外你测速 页面完全无变化 你需要先点去其他页面  然后在点回来  达到刷新的目的。

**Comment by lbcake** [comment]
并且现在代理组页面   小功能有6个    没有隐藏timeout节点，只显示连通节点的功能。

**Comment by wonfen** [comment]
> ### 问题描述 / Describe the bug
> 1，有概率出现点击延迟测速无反应 2，有概率全error，再次进行延迟测速便恢复正常
> 
> ### 复现步骤 / To Reproduce
> 第一个问题： -1，关闭Clash Verge -2，打开clash verge -3，立即进行测速 第二个问题： -1，关闭Clash Verge -2，打开clash verge -3，多次进行测速
> 
> ### 操作系统 / OS
> MacOS
> 
> ### 操作系统版本 / OS Version
> macOS 12.7.4
> 
> ### 日志 / Log
> no

无法复现，换不同版本内核看看是不是内核bug。也有可能是特定协议的bug，我这边用hy协议无法复现。



> 测试无反应 是需要所有节点都测出来结果 才能再次测速 （不支持 第一次点击测速 所有节点还没出结果 就立刻重置第一次，不能立刻下一次测速） 这个前端易用性问题现在超级多 很多无缝的显示功能现在全都有问题。

就是这样设计的；反复多次全局测试会给服务器带来压力；不是好的设计。如果你要测具体节点，直接点要测试的节点即可。

> 另外你测速 页面完全无变化 你需要先点去其他页面 然后在点回来 达到刷新的目的。

当前页面的测试结果全部出来才能下达下一次的测试，才能看到新的结果。
