### ISSUE TITLE
[Feature] 希望内置订阅转换功能

### ISSUE THREAD

**Issue by MarkIvory2973** [clash-verge-rev/clash-verge-rev#828]
### 功能描述 / Feature description

Why?
1. 使用别人的订阅转换器不太安全
2. 要在网络上找或者打开另一个软件，不方便

这是Clash.Net的一个功能，但我希望这个功能能够搬到这里来。

### 使用场景 / Use case

1. 当你只有非Clash/Clash.Meta的订阅时
2. 当你信不过别人的订阅转换时
3. 当你不想再打开多一个网页/软件时

**Comment by dongchengjie** [comment]
subConverter都停更多久了，老协议和参数还行，新的协议支持性都不太行。几十个节点进去，几个节点出来😅
目前规则写的比较好的是[v2rayse](https://v2rayse.com/clash-convert/)，然鹅不是开源的

**Comment by wonfen** [comment]
> 这个可以延后 现在连最基本的易用性显示功能 到处都是问题。
什么问题？

**Comment by lbcake** [comment]
> > 这个可以延后 现在连最基本的易用性显示功能 到处都是问题。
> > 什么问题？

https://github.com/clash-verge-rev/clash-verge-rev/issues/556

https://github.com/clash-verge-rev/clash-verge-rev/issues/827

**Comment by wonfen** [comment]
> #556
慢慢改进。
> #827
已经在那边回答了。

**Comment by lwd-temp** [comment]
可能有帮助：https://github.com/SubConv/SubConv

**Comment by jackyzonewen** [comment]
直接用私有gists就可以了~

**Comment by sjhsbhqf** [comment]
> 直接用私有gists就可以了~

如何配置，方便出一个教程吗？？？谢谢大佬

**Comment by CberYellowstone** [comment]
https://github.com/asdlokj1qpi23/subconverter 这个分支可以完美支持

**Comment by wonfen** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/2270
