### ISSUE TITLE
[BUG]更新到1.4.2及1.4.3后开启和关闭系统代理会有数秒的操作延迟

### ISSUE THREAD

**Issue by thouser8** [clash-verge-rev/clash-verge-rev#83]
**Describe the bug**
更新到1.4.2及1.4.3后，开启和关闭系统代理会有数秒的操作延迟
**To Reproduce**
1. 打开应用
2. 点击系统代理
3. 系统代理并未开启
4. 6~10s后，系统代理才开启

**Expected behavior**
1.4.1版本并未出现此问题，希望后续版本能解决

**Screenshots**

https://github.com/clash-verge-rev/clash-verge-rev/assets/83090571/45f127f8-2ee3-46f5-ae85-af64056a3301

**Information**

- OS: [Windows11 23H2]
- Clash Verge Version: [1.3.4]
- Clash Core: [Clash Meta&Clash Meta Alpha]

**Comment by wonfen** [comment]
看下的代理页面选节点了没？

**Comment by thouser8** [comment]
> 看下的代理页面选节点了没？

选了的

**Comment by wonfen** [comment]
试试最新版还有这个问题吗？

**Comment by MystiPanda** [comment]
试试1.4.7有没有这个问题

**Comment by thouser8** [comment]
> 试试1.4.7有没有这个问题

 刚刚测试了下已经没有这个问题了，感谢

**Comment by thouser8** [comment]
最新的1.4.9又出现了此问题…

**Comment by MystiPanda** [comment]
在系统代理中打开使用注册表

**Comment by MystiPanda** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/152463842/08e875d5-ffe5-44ad-9a46-868ab855cf16)

**Comment by wonfen** [comment]
> 最新的1.4.9又出现了此问题… 刚刚看到1.4.8的发布里有写Windows 开启/关闭系统代理延迟(使用注册表即可)，请问具体如何操作？

请帮忙测试下这个版本： https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/sys_proxy_test

优化了系统代理的相关代码，看看是否还会卡顿。

**Comment by thouser8** [comment]
> > 最新的 1.4.9 又出现了此问题… 刚刚看到 1.4.8 的发布里有写 Windows 开启 / 关闭系统代理延迟 (使用注册表即可)，请问具体如何操作？
> 
> 请帮忙测试下这个版本： https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/sys_proxy_test
> 
> 优化了系统代理的相关代码，看看是否还会卡顿。 上图的 “使用注册表” 请保持关闭。
我使用了一下，已经不会卡顿了
