### ISSUE TITLE
[BUG] 应用托盘图标

### ISSUE THREAD

**Issue by xuqiangwinter** [clash-verge-rev/clash-verge-rev#830]
### 问题描述 / Describe the bug

Mac的M系列处理器，左上角也会显示一个白色的应用托盘图标

### 复现步骤 / To Reproduce

软件启动就有

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.4.1

### 日志 / Log

04-04 22:25:09INFO
[TCP] 127.0.0.1:64427 --> p209-caldav.icloud.com.cn:443 match DomainSuffix(icloud.com.cn) using 🍎 苹果服务[SSR]
04-04 22:25:09INFO
[TCP] 127.0.0.1:64431 --> p209-caldav.icloud.com.cn:443 match DomainSuffix(icloud.com.cn) using 🍎 苹果服务[SSR]
04-04 22:25:09INFO
[TCP] 127.0.0.1:64429 --> calendars.icloud.com:443 match DomainSuffix(icloud.com) using 🍎 苹果服务[SSR]
04-04 22:25:11INFO
[TCP] 127.0.0.1:64433 --> p209-caldav.icloud.com.cn:443 match DomainSuffix(icloud.com.cn) using 🍎 苹果服务[SSR]
04-04 22:25:18INFO
[TCP] 127.0.0.1:64437(QQLive) --> acc.qq.com:443 match GeoIP(cn) using 🎯 全球直连[DIRECT]
04-04 22:25:18INFO
[TCP] 127.0.0.1:64442 --> otheve.beacon.qq.com:443 match DomainSuffix(beacon.qq.com) using 🛑 全球拦截[REJECT]
04-04 22:25:21INFO
[TCP] 127.0.0.1:64443 --> www.google.com:443 match DomainKeyword(google) using 🔰 节点选择[SSR]
04-04 22:25:36INFO
[TCP] 127.0.0.1:64445 --> android.clients.google.com:443 match DomainKeyword(google) using 🔰 节点选择[SSR]

**Comment by wonfen** [comment]
已知tarui的某种bug，不知道出发原因，暂无修复方案。

**Comment by MystiPanda** [comment]
#759
