### ISSUE TITLE
[BUG]  卸载真的是脑残设计

### ISSUE THREAD

**Issue by Jacob-pixil** [clash-verge-rev/clash-verge-rev#831]
### 问题描述 / Describe the bug

安装包不会自建自带软件名的文件夹， 卸载的时候把我还有各种软件的目录全给卸载了， 傻逼设计

### 复现步骤 / To Reproduce

安装包不会自建自带软件名的文件夹， 卸载的时候把我还有各种软件的目录全给卸载了， 傻逼设计

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

22h2

### 日志 / Log

安装包不会自建自带软件名的文件夹， 卸载的时候把我还有各种软件的目录全给卸载了， 傻逼设计

**Comment by wonfen** [comment]
注意看发布记录，这个问题在1.5.11已经修复了：
https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.5.11
