### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Esdrin** [clash-verge-rev/clash-verge-rev#832]
### 问题描述 / Describe the bug

断网之后过几分钟高cpu占用，连网之后也还是会高CPU占用，以及速度显示不正确（和任务管理器不一致）（谁家好人上传100MB多）
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/97580517/dcb8077d-ce4d-4273-ac47-b57b90e405d8)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/97580517/d195cdd4-88fc-44fc-a464-16ccb0d6dd1f)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/97580517/b358fe42-56a2-4a58-8303-2d4077400d78)

### 复现步骤 / To Reproduce

1、电脑断网
2、等待

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业工作站版 23H2 22631.3296

### 日志 / Log

04-05 14:20:33INFO
[TCP] 198.18.0.1:14530 --> cdn1.ime.sogou.com:80 match DomainSuffix(sogou.com) using DIRECT
04-05 14:20:33INFO
[TCP] 198.18.0.1:14539 --> get.sogou.com:443 match DomainSuffix(sogou.com) using DIRECT
04-05 14:20:35INFO
[TCP] 198.18.0.1:14547 --> msedge.b.tlu.dl.delivery.mp.microsoft.com:80 match DomainSuffix(microsoft.com) using 性价比机场[🇸🇬 新加坡2 (移动联通>电信)]
04-05 14:21:31INFO
[TCP] 198.18.0.1:14596 --> api.github.com:443 match DomainKeyword(github) using 性价比机场[🇸🇬 新加坡2 (移动联通>电信)]
04-05 14:21:31INFO
[TCP] 198.18.0.1:14595 --> github.com:443 match DomainKeyword(github) using 性价比机场[🇸🇬 新加坡2 (移动联通>电信)]
04-05 14:21:34INFO
[TCP] 198.18.0.1:14601 --> github-production-user-asset-6210df.s3.amazonaws.com:443 match DomainKeyword(amazon) using 性价比机场[🇸🇬 新加坡2 (移动联通>电信)]

**Comment by Esdrin** [comment]
断网之后重新联网故障依旧存在

**Comment by wonfen** [comment]
内核问题请到meta那边反馈
https://github.com/MetaCubeX/mihomo
