### ISSUE TITLE
关于tun模式，双网卡

### ISSUE THREAD

**Issue by AnisJiang** [clash-verge-rev/clash-verge-rev#833]
我的电脑在公司一个物理网口连接内部网络，用内部ip dns服务器解析，一个是wifi连接外网，tun模式应该如何配置，我配置指定域名指定dns，经常ping失败，可能的问题是内网的ip走向了wifi外网了。如何解决这个问题呢？

**Comment by AnisJiang** [comment]
在之前我是用win下得router指定内网ip走物理网卡，外网走wifi接口

**Comment by dongchengjie** [comment]
TUN相当于新开一张网卡，接管了流量
可以先配置分流规则让`内网网段`走直连，然后配置route让内网网段走物理网卡，估计能成
```
- IP-CIDR,10.11.12.0/24,DIRECT,no-resolve
```

**Comment by MurphyZX** [comment]
┌───────────────────────┐
│  软件 (应用程序)       │
└──────────┬────────────┘
           │ 所有流量
           ▼
┌───────────────────────┐
│  Clash TUN 虚拟网卡    │
│  （接管全局流量）      │
└──────────┬────────────┘
           │
    ┌──────┴───────────────────────────────────────┐
    │ Clash 规则匹配                                │
    │-----------------------------------------------│
    │ 1. 命中内网规则                               │
    │    - 例: IP-CIDR,10.11.12.0/24,DIRECT         │
    │    → 放行到系统路由表                         │
    │                                               │
    │ 2. 其他规则（走代理/其他直连）                 │
    │    - 继续由 Clash 决定出口                     │
    └──────────────────────────────────────────────┘
           │
           ▼
┌───────────────────────┐
│ 系统路由表（OS Route） │
│   - 静态路由匹配       │
│     route add 10.11.12.0 ... if Wi-Fi             │
└──────────┬────────────┘
           │
     ┌─────┴──────────┐
     │                │
     ▼                ▼
Wi-Fi 网卡       光纤网卡
(内网流量)       (其他流量)
