### ISSUE TITLE
[Feature] 请问是否存在日志文件，或者能否通过节点配置文件来设置日志文件地址？ 

### ISSUE THREAD

**Issue by li-yongyu** [clash-verge-rev/clash-verge-rev#834]
### 功能描述 / Feature description

请问是否存在日志文件，或者能否通过节点配置文件来设置日志文件地址？ 

### 使用场景 / Use case

开启代理之后无限被扫描，想通过配置fail2ban来配置监听日志，动态将IP地址封禁

**Comment by wonfen** [comment]
看FAQ

**Comment by li-yongyu** [comment]
> 看FAQ
并没有说明，只看到GUI日志设置，还是windows的，我的服务器是linux，没有可视化界面、

**Comment by wonfen** [comment]
自己研究meta文档
https://wiki.metacubex.one/config/
