### ISSUE TITLE
[建议可以启动多个实例] 

### ISSUE THREAD

**Issue by freeisok** [clash-verge-rev/clash-verge-rev#835]
### 功能描述 / Feature description

建议可以启动多个实例，用户上网可以选择某个具体的实例。

### 使用场景 / Use case

为了灵活的实现不同浏览器选择不同的vpn。

**Comment by wonfen** [comment]
这个需求可以用自定义规则实现。不同网站指定不同的节点即可。

**Comment by lhj5426** [comment]
我举个更具体的例子 自定义规则无法实现的比如
在国外网站下资源

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/30548000/86685c4e-955b-446f-9f23-3c8d464ea00f)
唯一能用的就是这个盘
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/30548000/215d0665-1ebe-4e74-b9d2-bf274c82974b)

这个盘有个限制 一个IP几个小时内只能下载一次

可以通过切换IP来规避这个限制
但是 下载的时候还下载器也要链接代理
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/30548000/df2fb0cf-8865-4390-8bce-78b4f05875d1)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/30548000/fcc99c10-9a0d-4185-a8dc-50d690f1ae72)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/30548000/c5fb61ca-d5f4-46f1-bcd0-e6b256faf773)
这种情况下 自定义规则就无法使用了 
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/30548000/ea55b1a1-2491-4d93-bacf-167b27576607)
 因为要多节点同时连接一个网站

**Comment by B-22** [comment]
可以试试负载均衡，负载均衡每次一个新连接使用一个新节点
比如，以前用ssr的时候，能够同时使用多个节点下载同一个连接，绕过ip限制，能够跑满网速，
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/68846704/3e8bcbd9-b5af-4245-b784-2ea66d56c704)
