### ISSUE TITLE
无法运行程序

### ISSUE THREAD

**Issue by li-yongyu** [clash-verge-rev/clash-verge-rev#836]
### 问题描述 / Describe the bug

cannot open display
本项目只能运行在界面系统吗？

### 复现步骤 / To Reproduce

克隆项目
安装环境
运行

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu 22.04 LTS (GNU/Linux 5.15.0-94-generic x86_64)

### 日志 / Log

(base) root@VM-12-8-ubuntu:/clash/clash-verge-rev# pnpm dev:diff

> clash-verge@1.5.11 dev:diff /clash/clash-verge-rev
> tauri dev -f verge-dev

     Running BeforeDevCommand (`pnpm run web:dev`)

> clash-verge@1.5.11 web:dev /clash/clash-verge-rev
> vite

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  VITE v5.0.11  ready in 278 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
        Info Watching /clash/clash-verge-rev/src-tauri for changes...
   Compiling clash-verge v1.5.11 (/clash/clash-verge-rev/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 50.16s

(clash-verge:136739): Gtk-WARNING **: 03:02:45.577: cannot open display: 
 ELIFECYCLE  Command failed with exit code 1.

**Comment by wonfen** [comment]
本项目就算GUI，当然只能图形运行了。

**Comment by shen774411223d** [comment]
> 本项目就算GUI，当然只能图形运行了。

我是在远程服务器上安装的，这种情况是安装一个gui还是去安装clash的命令行版本呢？
