### ISSUE TITLE
[BUG] wireguard节点连不上

### ISSUE THREAD

**Issue by laobanbiefangcu** [clash-verge-rev/clash-verge-rev#837]
### 问题描述 / Describe the bug

- {name: 🇨🇳 unraid, type: wireguard, server: 域名, port: 51820, ip: 192.168.2.3, private-key: ******, public-key: *****, AllowedIPs = ::/0, 0.0.0.0/0, dns: [119.29.29.29], udp: true}
- {name: 🇨🇳 ubuntu1, type: wireguard, server: 域名, port: 51821, ip: 192.168.3.2, private-key: ****, public-key: ****, preshared-key: *****, AllowedIPs = ::/0, 0.0.0.0/0, dns: [119.29.29.29], udp: true}

都是wireguard，一个带preshared-key参数，连不上，一个不带preshared-key参数，能连上，是啥原因，我用stash可以连上两个wg'节点

### 复现步骤 / To Reproduce

同上

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

失败日志：
04-07 12:54:30WARNING
[TCP] dial 🏠 家庭组网 (match IPCIDR/192.168.1.0/24) 127.0.0.1:8437 --> 192.168.1.1:80 error: context deadline exceeded
04-07 12:54:35WARNING
[TCP] dial 🏠 家庭组网 (match IPCIDR/192.168.1.0/24) 127.0.0.1:8505 --> 192.168.1.1:80 error: context deadline exceeded
04-07 12:54:40WARNING
[TCP] dial 🏠 家庭组网 (match IPCIDR/192.168.1.0/24) 127.0.0.1:8506 --> 192.168.1.1:80 error: context deadline exceeded
04-07 12:54:45WARNING
[TCP] dial 🏠 家庭组网 (match IPCIDR/192.168.1.0/24) 127.0.0.1:8507 --> 192.168.1.1:80 error: context deadline exceeded

**Comment by laobanbiefangcu** [comment]
成功日志：
04-07 12:57:26INFO
[TCP] 127.0.0.1:5152 --> 192.168.1.131:1329 match IPCIDR(192.168.1.0/24) using 🏠 家庭组网[🇨🇳 unraid]
04-07 12:57:36INFO
[TCP] 127.0.0.1:5152 --> 192.168.1.131:1329 match IPCIDR(192.168.1.0/24) using 🏠 家庭组网[🇨🇳 unraid]

**Comment by laobanbiefangcu** [comment]
是内核不支持preshared-key参数的原因原因

**Comment by wuying2021** [comment]
你的presharedkey写错了，是pre-shared-key
