### ISSUE TITLE
MacOS代理绕过功能无法在命令行及tun模式下使用 [BUG] 

### ISSUE THREAD

**Issue by zhengyongtao** [clash-verge-rev/clash-verge-rev#838]
### 问题描述 / Describe the bug

系统：MacOS 14.4.1
问题描述：设置了代理绕过，在tun模式下无法生效。另外使用复制环境变量，在终端里粘贴后发现绕过也是无法生效的，只能自己添加no_proxy字段

### 复现步骤 / To Reproduce

1. 在设置-系统设置-系统代理中配置代理绕过
2. 开启tun模式
3. 尝试访问绕过的域名，浏览器显示DNS_PROBE_FINISHED_NXDOMAIN，在日志中找不到请求记录
4. 右键复制环境变量，粘贴到终端执行
5. 使用curl访问代理绕过的域名，在日志中可以发现访问记录，但使用了代理节点，并没有绕过

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.4.1

### 日志 / Log

2024-04-07 14:16:40 INFO - [clash]: time="2024-04-07T14:16:40.110389+08:00" level=info msg="[TCP] 127.0.0.1:59982 --> resource.xxx.com:80 match Match using ⚓️其他流量[香港 油尖旺御金·国峯 名氣通電訊 C03]"

**Comment by xishang0128** [comment]
@zhengyongtao 代理绕过是针对系统代理的,其他模式和直接发给代理端口当然不生效

**Comment by zhengyongtao** [comment]
> @zhengyongtao 代理绕过是针对系统代理的,其他模式和直接发给代理端口当然不生效

但这样就有很多问题了啊，等于代理绕过并不能在tun模式下生效啊，之前cfw是实现了这个功能的，在cfw中只要配置了bybass，不论是否是tun模式都是可以的。
