### ISSUE TITLE
[Feature] Remove copy cmd and PowerShell env from right-click menu on platforms other than Windows

### ISSUE THREAD

**Issue by Anasmusculus** [clash-verge-rev/clash-verge-rev#84]
**Is your feature request related to a problem? Please describe.**
When using an OS other than Windows, the options to copy proxy settings for cmd and PowerShell still exists, while their contents are the same as that of sh. I think these options are duplicated and make the right-click menu a bit messy.

**Describe the solution you'd like**
Remove `Copy Env (cmd)` and `Copy Env (ps)` from tray right-click menu releases not intended for Windows.

**Comment by wonfen** [comment]
看到了，但是还没想好应该怎么改。
