### ISSUE TITLE
[BUG] 银河麒麟操作系统无法显示面板

### ISSUE THREAD

**Issue by yuzhaoshi** [clash-verge-rev/clash-verge-rev#842]
### 问题描述 / Describe the bug

华为出品的arm64架构电脑，默认安装的是银河麒麟v10，直接安装clash-verge_1.5.11_arm64.deb包，安装完无法打卡面板。试过安装1.4.8版本，打开面板显示一片空白。
![微信图片_20240408095636](https://github.com/clash-verge-rev/clash-verge-rev/assets/1179497/aa0d9b3e-5fc6-40da-93b6-e49d338fe0c7)

### 复现步骤 / To Reproduce

打开软件后只显示右下角图标，右键打开菜单选择显示面板，无法显示界面

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

银河麒麟v10

### 日志 / Log

[2024-04-08-0957.log](https://github.com/clash-verge-rev/clash-verge-rev/files/14899968/2024-04-08-0957.log)

**Comment by wonfen** [comment]
没有看到GUI的启动日志，看下FAQ把，GUI的日志调整为trace

**Comment by yuzhaoshi** [comment]
> 没有看到GUI的启动日志，看下FAQ把，GUI的日志调整为trace

请问在哪里调整呢？

**Comment by yuzhaoshi** [comment]
> 没有看到GUI的启动日志，看下FAQ把，GUI的日志调整为trace

是修改config.yaml文件吗？改完日志多了一些，显示[clash]: time="2024-04-09T09:11:35.820727783+08:00" level=fatal msg="Parse config error: invalid mode"



[2024-04-09-0910.log](https://github.com/clash-verge-rev/clash-verge-rev/files/14912263/2024-04-09-0910.log)

[2024-04-09-0908.log](https://github.com/clash-verge-rev/clash-verge-rev/files/14912264/2024-04-09-0908.log)

**Comment by yuzhaoshi** [comment]
> 没有看到GUI的启动日志，看下FAQ把，GUI的日志调整为trace

刚试了使用终端打开，出现以下错误提示：
error: XDG_RUNTIME_DIR not set in the environment.
EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)

**Comment by yuzhaoshi** [comment]
终于解决了，参考https://github.com/clash-verge-rev/clash-verge-rev/issues/818

WEBKIT_DISABLE_COMPOSITING_MODE=1 clash-verge ,添加了这个环境变量以后就可以正常显示了
实测国产银河麒麟操作系统，对所有tauri的项目都有这个问题，只能添加这个环境变量才能正常显示。

**Comment by kynali** [comment]
实测，ubuntu 20.04 x64 电脑 ssh -X 到 ubuntu 20.04 arm 开发板，也可以用此命令图形化运行

**Comment by zuiyiweiyuanzui** [comment]
> 终于解决了，参考#818
> 
> WEBKIT_DISABLE_COMPOSITING_MODE=1 clash-verge ,添加了这个环境变量以后就可以正常显示了 实测国产银河麒麟操作系统，对所有tauri的项目都有这个问题，只能添加这个环境变量才能正常显示。

老哥好，能请教个问题吗？我这个也是麒麟系统，想安装这个软件，一直提示我libwekit2gtk这个依赖没有，我下载了，但是无法安装，能问下你遇到过这个问题吗？
