### ISSUE TITLE
关于规则模式的直连问题

### ISSUE THREAD

**Issue by z1298808165** [clash-verge-rev/clash-verge-rev#843]
### 问题描述 / Describe the bug

在使用微信的时候图片和视频等资源会加载比较慢，然后查看了下日志，发现不是直连，这几个ip是腾讯的但是归属地却不在国内，为什么不是连接国内的呢？请问该怎么设置直连呢？
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/25720725/23285517-868b-4dec-aaa7-df670d5da3fb)

### 复现步骤 / To Reproduce

微信，点击图片进行加载

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/25720725/23285517-868b-4dec-aaa7-df670d5da3fb)

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/25720725/d4d80b8b-e981-4617-ba23-041b524277fc)

**Comment by dongchengjie** [comment]
[路由规则](https://wiki.metacubex.one/config/rules/)
如果是机场订阅，刷新后规则会覆盖。新增按钮，添加到**Merge**配置里，然后**右键启用**
```
prepend-rules:
  - IP-CIDR,101.33.17.0/24,DIRECT,no-resolve
```

**Comment by z1298808165** [comment]
> [路由规则](https://wiki.metacubex.one/config/rules/) 如果是机场订阅，刷新后规则会覆盖。新增按钮，添加到**Merge**配置里，然后**右键启用**
> 
> ```
> prepend-rules:
>   - IP-CIDR,101.33.17.0/24,DIRECT,no-resolve
> ```

好的，谢谢！

**Comment by z1298808165** [comment]
> [路由规则](https://wiki.metacubex.one/config/rules/) 如果是机场订阅，刷新后规则会覆盖。新增按钮，添加到**Merge**配置里，然后**右键启用**
> 
> ```
> prepend-rules:
>   - IP-CIDR,101.33.17.0/24,DIRECT,no-resolve
> ```

我这边添加了规则“DIRECT,no-resolve”，日志中也确实不走代理了，但是微信加载图片和视频还是很慢，然后我切换成系统代理模式了，返现系统代理模式下加载不会缓慢，但是切换回Tun模式加载就又开始慢了

**Comment by z1298808165** [comment]
不好意思，应该是我配置有问题，导致国内的访问也都是经过代理，现在用了[clash-rules](https://github.com/Loyalsoldier/clash-rules/issues)规则解决了，抱歉打扰了~

**Comment by freshgeek** [comment]
@dongchengjie  请问下，mac 环境下 版本1.6.6 内核1.18.5   访问alicdn 国内的直连还是很慢呢，这边已经配了规则看面板已经走了直连 ，然后把clash
 关掉就秒开了 ，是走直连还是会有性能问题 还是 面板的显示不准？
<img width="1199" alt="image" src="https://github.com/user-attachments/assets/0590c7aa-811c-434c-b594-c2283670da40">

**Comment by freshgeek** [comment]
开了代理模式 ，开启系统代理
![image](https://github.com/user-attachments/assets/725a9320-aeca-4530-91e5-017bcf6bb497)
关掉系统代理
![image](https://github.com/user-attachments/assets/3d692303-ff7f-49ba-b060-7604e47c98ac)

**Comment by dongchengjie** [comment]
> @dongchengjie 请问下，mac 环境下 版本1.6.6 内核1.18.5 访问alicdn 国内的直连还是很慢呢，这边已经配了规则看面板已经走了直连 ，然后把clash 关掉就秒开了 ，是走直连还是会有性能问题 还是 面板的显示不准？ <img alt="image" width="1199" src="https://private-user-images.githubusercontent.com/20513615/348152918-0590c7aa-811c-434c-b594-c2283670da40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MjUzMTMsIm5iZiI6MTcyMDgyNTAxMywicGF0aCI6Ii8yMDUxMzYxNS8zNDgxNTI5MTgtMDU5MGM3YWEtODExYy00MzRjLWI1OTQtYzIyODM2NzBkYTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDIyNTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMjc2ZDhlYTMxNzhjYWYxZGZjOWU5ZDlkZGM1YzJjMzE5N2ZkZGZiYjg5MzY3YmVjMTc1MzJiYjExYTEyYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6VW7Q8aSSvrRtvVK49rYbg_1slr9uqTfmdhnS3PVFpk">

CDN直连也得看地理位置，寻找离你最近的节点。有的是通过你的IP确定地理位置权衡得出，有的是通过不同地域的DNS服务器解析到最近的机器。你图上的资源的域名一致，大概率是后者方式实现。
