### ISSUE TITLE
clash开启系统代理后便无法访问ipv6网站[BUG] 

### ISSUE THREAD

**Issue by hurd-git** [clash-verge-rev/clash-verge-rev#844]
### 问题描述 / Describe the bug

问题出现在：我的clash打开系统代理后（无论clash有没有开启ipv6），电脑的ipv6功能似乎受到了一定的影响。
与此同时，电脑出现了以下的情形：
- 网络从ipv6优先转变为ipv4优先。
- 电脑仍然可以获取到ipv6地址，并且接受ipv6的连接
- ipv6测试网站无法检测到电脑的ipv6地址，并且浏览器无法再访问任何ipv6网站
按照理想情况，打开了ipv6的clash不应该影响电脑对于ipv6网络的正常访问。想问下上面的情况是否是clash的bug？

### 复现步骤 / To Reproduce

（clash中ipv6选项是否打开没有任何影响）
关闭clash的系统代理，打开https://ipw.cn/ping 查询，发现网络ipv6优先，进入https://test-ipv6.com 进行测试，发现一切正常，同时ipv6网站正常访问。
随后打开clash的系统代理，打开https://ipw.cn/ping 查询，发现网络ipv4优先，进入https://test-ipv6.com 进行测试，无法找到电脑的ipv6地址（尽管ipconfig可以查询到），同时ipv6网站无法访问。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 23H2

### 日志 / Log

/

### 小建议 / Suggestion

希望clash能够内置一些经典的托盘图标（比如clash for windows）:)

**Comment by leafsoul365** [comment]
刚看了下，我这在测试时，看起来是正常的。
![Snipaste2024-04-08_125030](https://github.com/clash-verge-rev/clash-verge-rev/assets/46679575/cc313278-929d-4fe9-a81c-2b2df0b5762a)
![Snipaste2024-04-08_124938](https://github.com/clash-verge-rev/clash-verge-rev/assets/46679575/cbfc4e94-501b-4f4c-b301-e5920d10fa77)

**Comment by wuying2021** [comment]
https://ipw.cn/ping、https://test-ipv6.com/ 你的规则设定好了吗，是本地ip吗？

**Comment by hurd-git** [comment]
> [https://ipw.cn/ping、https://test-ipv6.com/](https://ipw.cn/ping%E3%80%81https://test-ipv6.com/) 你的规则设定好了吗，是本地ip吗？

就是，我的两台电脑都是有这个问题。没有设定任何额外的规则，clash的ipv6模式正常开启，只要开启了系统代理，就会这样。无论是直连、规则还是全局。ip是本地的，只是clash代理之后ipv6访问不了了

**Comment by hurd-git** [comment]
这是正常时候的![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/135419400/22a16566-320d-48dc-b6ce-fed510cec2bb)

**Comment by yyy123zc** [comment]
需要机场的节点支持IPv6.
当前节点不支持IPv6
![1](https://github.com/clash-verge-rev/clash-verge-rev/assets/16403129/f3250585-33e4-4cbc-9e90-bddee4f4f373)
当前节点支持IPv6
![2](https://github.com/clash-verge-rev/clash-verge-rev/assets/16403129/12d6eb7a-a591-48ef-8dc5-03da35a8b9c2)

**Comment by wuying2021** [comment]
无法复现，麻烦关闭issue把，也没有log

**Comment by yyy123zc** [comment]
> > 需要机场的节点支持IPv6. 当前节点不支持IPv6 ![1](https://private-user-images.githubusercontent.com/16403129/320731666-f3250585-33e4-4cbc-9e90-bddee4f4f373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTM4ODEsIm5iZiI6MTcxMjY1MzU4MSwicGF0aCI6Ii8xNjQwMzEyOS8zMjA3MzE2NjYtZjMyNTA1ODUtMzNlNC00Y2JjLTllOTAtYmRkZWU0ZjRmMzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA5MDYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4Y2EzMGM5MWY5MTBiOTFhMjUyZWNjYWU4NmM5ZGM4YjY1NDQ5MzdmNjc0YzViMjcwMTc2YzU4NzY4YjBmNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8jq_C3YOyXVbnsrXO_hBURSbClJon7VGvYXQZQPP_Pk) 当前节点支持IPv6 ![2](https://private-user-images.githubusercontent.com/16403129/320731734-12d6eb7a-a591-48ef-8dc5-03da35a8b9c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTM4ODEsIm5iZiI6MTcxMjY1MzU4MSwicGF0aCI6Ii8xNjQwMzEyOS8zMjA3MzE3MzQtMTJkNmViN2EtYTU5MS00OGVmLThkYzUtMDNkYTM1YThiOWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA5MDYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMWVkZTE2NDBhMzNkM2Y3YmE1NTVlNmJkZTJmOGNiOGQ1ZDJiMjRhZmZiY2RjZDM1YWUxZTM2NzgyNGU4NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nUFijOZt1VIiGP-m1Dlu36qiJnzc0ScAT50tG25Ql4Y)
> 
> 不，我说了，在直连的时候也是这样。 没有导入任何url，在空白的时候也是这样

直连但不关闭系统代理，网络使用的DNS和hosts文件还是使用机场的配置，非Windows原始DNS和hosts文件。

**Comment by freestyledash** [comment]
同样的问题，经过排查，发现是dns的问题。
修改clash的 config文件，加入ipv6的dns，还是无法解决
关闭代理就恢复

**Comment by DUXING130** [comment]
> > 需要机场的节点支持IPv6. 当前节点不支持IPv6 ![1](https://private-user-images.githubusercontent.com/16403129/320731666-f3250585-33e4-4cbc-9e90-bddee4f4f373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTM4ODEsIm5iZiI6MTcxMjY1MzU4MSwicGF0aCI6Ii8xNjQwMzEyOS8zMjA3MzE2NjYtZjMyNTA1ODUtMzNlNC00Y2JjLTllOTAtYmRkZWU0ZjRmMzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA5MDYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4Y2EzMGM5MWY5MTBiOTFhMjUyZWNjYWU4NmM5ZGM4YjY1NDQ5MzdmNjc0YzViMjcwMTc2YzU4NzY4YjBmNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8jq_C3YOyXVbnsrXO_hBURSbClJon7VGvYXQZQPP_Pk) 当前节点支持IPv6 ![2](https://private-user-images.githubusercontent.com/16403129/320731734-12d6eb7a-a591-48ef-8dc5-03da35a8b9c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTM4ODEsIm5iZiI6MTcxMjY1MzU4MSwicGF0aCI6Ii8xNjQwMzEyOS8zMjA3MzE3MzQtMTJkNmViN2EtYTU5MS00OGVmLThkYzUtMDNkYTM1YThiOWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA5MDYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMWVkZTE2NDBhMzNkM2Y3YmE1NTVlNmJkZTJmOGNiOGQ1ZDJiMjRhZmZiY2RjZDM1YWUxZTM2NzgyNGU4NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nUFijOZt1VIiGP-m1Dlu36qiJnzc0ScAT50tG25Ql4Y)
> 
> 不，我说了，在直连的时候也是这样。没有导入任何url，在空白的时候也是这样

请检查配置文件中，配置文件中，是否确实启用了IPv6，由于yaml的问题，你要完全启用并正常使用IPv6功能，配置文件应如下：
# port of HTTP
#port: 7890
# port of SOCKS5
#socks-port: 7891
#允许局域网连接
#allow-lan: true
# Rule / Global/ DIRECT (default is Rule)
mode: rule
# set log level to stdout (default is info)
# info / warning / error / debug
log-level: info
#是否启用IPv6连接
ipv6: true

# A RESTful API for clash
external-controller: 127.0.0.1:9090
#Clash UI路径
external-ui: ./UI
# Secret for RESTful API (Optional)
secret: ""

# DNS 服务设置
# 此部分是可选的. 当不存在时, DNS 服务将被禁用.
dns:
  enable: true
  listen: 127.0.0.1:53
  ipv6: true # 当为 false 时, AAAA 查询的响应将为空

  # 这些域名服务器(nameservers) 用于解析下列 DNS 域名服务器主机名.
  # 仅指定 IP 地址
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP 地址池 CIDR
  # use-hosts: true # 查找 hosts 并返回 IP 记录

然后请使用TUN模式进行测试，如果能连接正常，说明系统代理设定为127.0.0.1:7890时，系统无法接收IPv6流量

**Comment by kylo1020** [comment]
同样的问题，只要一开就无法访问ipv6网站，后面发现是因为代理节点不支持ipv6，后来找了个支持的节点，又出现新问题，就是ipv6优先变成了ipv4优先，而且我是在配置文件里面关了ipv6的功能的，这样在tun模式下ipv6流量应该是不走clash内核的啊

**Comment by Tychristine** [comment]
@kylo1020 分流是直连就走自己的IP链接；分流是代理才是节点IP；不过我测试的只要是双栈网络下v4优先

**Comment by Tychristine** [comment]
> > 分流是直连就走自己的IP链接;分流是代理才是节点IP;不过我测试的只要是双栈网络下v4优先
> 
> @Tychristine ,对，这才是我最无法理解的地方，我是关掉了clash的ipv6功能的，但是他还是把我的ipv6流量劫持走了，以前我是一直没有发现，然后前几坛找了直播源，是ipv6的，我怎么都打不开，才发现

解决方案：运行的配置文件*.yaml 中 "proxies"项加入"ip-version"，填写值为"ipv6-prefer"
```yaml
ip-version: ipv6-prefer
```
双栈网络下iPv6优先
参考链接：https://wiki.metacubex.one/config/proxies/#ip-version

**Comment by wow198712** [comment]
> > 分流是直连就走自己的IP链接;分流是代理才是节点IP;不过我测试的只要是双栈网络下v4优先
> 
> @Tychristine ,对，这才是我最无法理解的地方，我是关掉了clash的ipv6功能的，但是他还是把我的ipv6流量劫持走了，以前我是一直没有发现，然后前几坛找了直播源，是ipv6的，我怎么都打不开，才发现

问题解决了吗，我也遇到这个问题了，感觉是IPV6 DNS的问题

**Comment by BIGwangqz** [comment]
> > > 分流是直连就走自己的IP链接;分流是代理才是节点IP;不过我测试的只要是双栈网络下v4优先
> > 
> > 
> > @Tychristine ,对，这才是我最无法理解的地方，我是关掉了clash的ipv6功能的，但是他还是把我的ipv6流量劫持走了，以前我是一直没有发现，然后前几坛找了直播源，是ipv6的，我怎么都打不开，才发现
> 
> 解决方案：运行的配置文件*.yaml 中 "proxies"项加入"ip-version"，填写值为"ipv6-prefer"
> 
> ```yaml
> ip-version: ipv6-prefer
> ```
> 
> 双栈网络下iPv6优先 参考链接：https://wiki.metacubex.one/config/proxies/#ip-version

确实能够解决问题，赞！！！

**Comment by LULULUDIA** [comment]
我也是遇到同样的问题,求解

**Comment by AntisKong** [comment]
首先，设置那里的Ipv6打开
然后，在订阅那，右键编辑文件，把ipv6:true改成false

**Comment by wwp-max** [comment]
<img width="814" height="405" alt="Image" src="https://github.com/user-attachments/assets/5f911e5a-e362-4b54-b551-bd9b3918428e" />
添加这个前置规则可以解决

**Comment by Nixie24** [comment]
> > > 分流是直连就走自己的IP链接;分流是代理才是节点IP;不过我测试的只要是双栈网络下v4优先
> > 
> > 
> > [@Tychristine](https://github.com/Tychristine) ,对，这才是我最无法理解的地方，我是关掉了clash的ipv6功能的，但是他还是把我的ipv6流量劫持走了，以前我是一直没有发现，然后前几坛找了直播源，是ipv6的，我怎么都打不开，才发现
> 
> 解决方案：运行的配置文件*.yaml 中 "proxies"项加入"ip-version"，填写值为"ipv6-prefer"
> 
> ip-version: ipv6-prefer
> 双栈网络下iPv6优先 参考链接：https://wiki.metacubex.one/config/proxies/#ip-version

我写了一个Global Script
```javascript
// Define main function (script entry)

function main(config, profileName) {
  for (let i = 0; i < config.proxies.length; i++)
    config.proxies[i]["ip-version"] = "ipv6-prefer";
  return config;
}

```

**Comment by yoyo837** [comment]
> > > 分流是直连就走自己的IP链接;分流是代理才是节点IP;不过我测试的只要是双栈网络下v4优先
> > 
> > 
> > [@Tychristine](https://github.com/Tychristine) ,对，这才是我最无法理解的地方，我是关掉了clash的ipv6功能的，但是他还是把我的ipv6流量劫持走了，以前我是一直没有发现，然后前几坛找了直播源，是ipv6的，我怎么都打不开，才发现
> 
> 解决方案：运行的配置文件*.yaml 中 "proxies"项加入"ip-version"，填写值为"ipv6-prefer"
> 
> ip-version: ipv6-prefer
> 双栈网络下iPv6优先 参考链接：https://wiki.metacubex.one/config/proxies/#ip-version

直接在顶层添加 ipv6: true好像就可以了

**Comment by dasoumao** [comment]
> <img alt="Image" width="814" height="405" src="https://private-user-images.githubusercontent.com/71917664/474644053-5f911e5a-e362-4b54-b551-bd9b3918428e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODc1Nzc5MTgsIm5iZiI6MTc4NzU3NzYxOCwicGF0aCI6Ii83MTkxNzY2NC80NzQ2NDQwNTMtNWY5MTFlNWEtZTM2Mi00YjU0LWI1NTEtYmQ5YjM5MTg0MjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODI0VDEzMjAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNzA1ZDk0ODNiNGU4NGNkNDNhZTE5YzQ2NzA1MjhhODUzNmRlYTUwZmUwYjc5ZmJkODQ5NjllNTU2NmY1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.__G2XoZflryP0W5G6TcjjD5ItTeH_QbakpRP5VvHX5U"> 添加这个前置规则可以解决

确实解决了，综合看下来应该不是dns或者clash设置里ipv6的问题，而是分流到的出口对ipv6支持的问题了
