### ISSUE TITLE
[BUG] Tun模式下虚拟网卡Meta无ipv4和ipv6的网络访问权限

### ISSUE THREAD

**Issue by Lec16sf** [clash-verge-rev/clash-verge-rev#849]
### 问题描述 / Describe the bug

<img width="279" alt="Snipaste_2024-04-09_18-09-05" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/114462209/408cd417-0f86-44c4-946f-02f601adfa80">
版本：1.5.11
<img width="411" alt="Snipaste_2024-04-09_18-12-26" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/114462209/faad0943-30df-4c5b-bc83-6cd00ca3e3d9">

### 复现步骤 / To Reproduce

安装服务模式后先打开服务模式，后打开tun模式。在clash for windows下可以正常使用。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

WIn11

### 日志 / Log

无相关日志

**Comment by wonfen** [comment]
检查配置文件。

**Comment by Lec16sf** [comment]
> 检查配置文件。

请问是订阅文件吗？其他配置应该是没讲过的

**Comment by Lec16sf** [comment]
> 检查配置文件。

请问是订阅文件吗？其他的配置应该是没改过
