### ISSUE TITLE
[BUG] failed to install service with status 1

### ISSUE THREAD

**Issue by watchingfun** [clash-verge-rev/clash-verge-rev#85]
**Describe the bug**
无法安装服务

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/22067924/2904c212-8c74-48da-8808-b20f86002028)

**Information**

- OS: win11 23H2
- Clash Verge Version: 1.4.3
- Clash Core: 1.17.0.meta

**Additional context**

**Comment by elevencd** [comment]
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\clash_verge_service\ 里把 ImagePath 的值改成目前的 clash-verge-service.exe 的路径即可

**Comment by chzzfly** [comment]
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\clash_verge_service\ 里把 ImagePath 的值改成目前的 clash-verge-service.exe 的路径即可

感谢，成功解决。可能是后面安装换个位置。

**Comment by supermansaga** [comment]
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\clash_verge_service\ 里把 ImagePath 的值改成目前的 clash-verge-service.exe 的路径即可

感谢。我1.4.5没遇到这个问题，1.4.6却出现了。注册表地址却是1.4.0.

**Comment by supermansaga** [comment]
v1.4.11还是有这个问题，但的确注册表改了地址后就可以用了。谢谢

**Comment by sskkcc** [comment]
完全找不到这个注册表地址
