### ISSUE TITLE
[BUG] The CPU usage is too high

### ISSUE THREAD

**Issue by Chenhui-Guo** [clash-verge-rev/clash-verge-rev#852]
### 问题描述 / Describe the bug

My Verge version is v1.5.11, and Clash core is v1.18.2 Meta.

When I open the dashboard, htop can see that the WebKitWebProces process is using more than 1000% of the cpu!

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/72130032/29fd8f30-2525-4f31-a482-56fe293d48b6)

### 复现步骤 / To Reproduce

Just open the Clash Verge Rev dashboard

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu 20.04

### 日志 / Log

No bug information in the log

**Comment by Chenhui-Guo** [comment]
When I close the traffic graph, it seems to be normal, what's going on?

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/72130032/3c95065f-bebd-4cf5-bb30-f9edca487e6e)

**Comment by dongchengjie** [comment]
这个就建立了一个webSocket连接而已，发送message的主动权在内核那边，又不轮询。且你说只关闭这一个就好了，内存也是同样的方式获取的内容，应该可以排除ws请求的问题。
绘图逻辑貌似是手写的，一堆计算X,Y不好说

**Comment by sulliwane** [comment]
Had the same issue, seems like switching off Traffic chart indeed fixed the issue.
