### ISSUE TITLE
[BUG] tun模式开了连网都没有

### ISSUE THREAD

**Issue by lzalzalza** [clash-verge-rev/clash-verge-rev#853]
### 问题描述 / Describe the bug

tun模式开了连网都没有怎么办，wifi显示已连接，但是右下角却有地球图标
![73177ba802a72fdcae8a77b62cdfe49](https://github.com/clash-verge-rev/clash-verge-rev/assets/109899958/6df51895-ff68-480f-bf10-fa2e78785a67)

### 复现步骤 / To Reproduce

关闭tun模式后，右下角显示WiFi图标，且可以上网

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

操作系统版本：22631.3447，win11专业版

### 日志 / Log

无相关日志

**Comment by wonfen** [comment]
检查你的配置文件。

**Comment by lzalzalza** [comment]
> 日志？

日志名称:          System
来源:            NetBT
日期:            2024/4/12 10:59:52
事件 ID:         4311
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           LAPTOP-LZA
描述:
由于无法创建驱动程序设备，初始化失败。 使用字符串“000000000100320000000000D71000C013010000250200C000000000000000000000000000000000”识别初始化失败的 接口。如果 NetBT 无法从全局唯一接口标识符(GUID) 映射到 MAC 地址，则该接口表示已失败接口 或 GUID 的 MAC 地址。如果 MAC 地址或 GUID 都 不可用，字符串表示群集设备名称。 
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="NetBT" />
    <EventID Qualifiers="49152">4311</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-04-12T02:59:52.6754902Z" />
    <EventRecordID>52713</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="1856" />
    <Channel>System</Channel>
    <Computer>LAPTOP-LZA</Computer>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>
    <Binary>000000000100320000000000D71000C013010000250200C000000000000000000000000000000000</Binary>
  </EventData>
</Event>

**Comment by lzalzalza** [comment]
> ### 问题描述 / Describe the bug
> tun模式开了连网都没有怎么办，wifi显示已连接，但是右下角却有地球图标 ![73177ba802a72fdcae8a77b62cdfe49](https://private-user-images.githubusercontent.com/109899958/321325711-6df51895-ff68-480f-bf10-fa2e78785a67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTEyMTEsIm5iZiI6MTcxMjg5MDkxMSwicGF0aCI6Ii8xMDk4OTk5NTgvMzIxMzI1NzExLTZkZjUxODk1LWZmNjgtNDgwZi1iZjEwLWZhMmU3ODc4NWE2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwMzAxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjBmM2UzNDRiNDUxNWM5M2QxODM0YjBiMjQwZmRhY2MxZmEwNTk2ZTgzMjE0ZWRhYTljMjJmOWQ1ZDBkYjhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9jJ0RfCrw_Sxw8CdcFOufx01O5CdHwykeZ_vxIZhitc)
> 
> ### 复现步骤 / To Reproduce
> 关闭tun模式后，右下角显示WiFi图标，且可以上网
> 
> ### 操作系统 / OS
> Windows
> 
> ### 操作系统版本 / OS Version
> 操作系统版本：22631.3447，win11专业版
> 
> ### 日志 / Log
> 由于无法创建驱动程序设备，初始化失败。 使用字符串“000000000100320000000000D71000C013010000250200C000000000000000000000000000000000”识别初始化失败的 接口。如果 NetBT 无法从全局唯一接口标识符(GUID) 映射到 MAC 地址，则该接口表示已失败接口 或 GUID 的 MAC 地址。如果 MAC 地址或 GUID 都 不可用，字符串表示群集设备名称。

**Comment by lzalzalza** [comment]
软件上的日志报错：
[TCP] dial Mainland (match GeoIP/cn) 192.168.4.37:61328(clash-meta.exe) --> 119.147.19.113:80 error: reject loopback connection to: 119.147.19.113:80
[TCP] dial Global (match GeoSite/Github) 198.18.0.1:61331(msedge.exe) --> github.com:443 error: ppg-hk.05vr9nyqg5.download:10801 connect error: dns resolve failed: all DNS requests failed, first error: requesting https://doh.pub:443/dns-query?dns=AAABAAABAAAAAAAABnBwZy1oawowNXZyOW55cWc1CGRvd25sb2FkAAABAAE: Get "https://doh.pub:443/dns-query?dns=AAABAAABAAAAAAAABnBwZy1oawowNXZyOW55cWc1CGRvd25sb2FkAAABAAE": context deadline exceeded
