### ISSUE TITLE
[BUG]Clash Verge Rev Alpha m系芯片Mac服务模式无法启用

### ISSUE THREAD

**Issue by wyylzy** [clash-verge-rev/clash-verge-rev#859]
### 问题描述 / Describe the bug

安装的是刚发布的这个版本Created at Fri Apr 12 01:33:20 CST 2024.

### 复现步骤 / To Reproduce

无法启用服务模式,电极install安装报错,日志内无体现.安装的是刚发布的这个版本Created at Fri Apr 12 01:33:20 CST 2024.
![截屏2024-04-12 02 34 30](https://github.com/clash-verge-rev/clash-verge-rev/assets/61929738/dadc9d81-1262-4da8-a69b-6621bad96c98)

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS 14.4.1

### 日志 / Log

日志无体现

**Comment by maiqingqiang** [comment]
日志只看到这个
```
2024-04-12 14:37:44 ERROR - failed to install service with status 1
2024-04-12 14:37:44 ERROR - failed to connect to the Clash Verge Service
2024-04-12 14:38:15 ERROR - failed to install service with status 1
2024-04-12 14:38:15 ERROR - failed to connect to the Clash Verge Service
```

**Comment by wonfen** [comment]
已知问题，暂未找到有效解决方案

**Comment by LOVECHEN** [comment]
同？ 上个版本没问题

**Comment by Mangoyap** [comment]
同样是这个问题

**Comment by plutosherry** [comment]
the same error!!!

**Comment by GOWxx** [comment]
same error 🥹

**Comment by Ballen2270** [comment]
waiting for update

**Comment by logicr** [comment]
同，cy，更新了踢我下

**Comment by GOWxx** [comment]
> same error 🥹 同样的错误🥹

Update:

In my case, just enabling TUN mode is enough.
Turn off system proxy, enable TUN mode, no need to enable service mode, and you can have global proxy. It can proxy applications that do not support system proxy.

**Comment by GOWxx** [comment]
> what's your version

Core version: V1.18.1 Meta
Verge version: 1.6.0

**Comment by Ballen2270** [comment]
This problem was been fixed with the new update !

**Comment by logicr** [comment]
> This problem has been fixed with the new update !

thx😘

**Comment by tayadwx** [comment]
Great! THX

**Comment by Logiase** [comment]
Same problem with v1.6.5
macOS 14.5

**Comment by CodeIdeal** [comment]
Same problem with v1.6.6
M1 macOS 14.5

**Comment by CodeIdeal** [comment]
Same problem with v1.6.6
M1 macOS 14.5

**Comment by Ballen2270** [comment]
> Same problem with v1.6.6 M1 macOS 14.5
try v1.6.2  may help

**Comment by wonfen** [comment]
用最新的alpha版。开服务模式。
