### ISSUE TITLE
[BUG]macOS版本刚开机Meta核心会占用大量内存

### ISSUE THREAD

**Issue by wyylzy** [clash-verge-rev/clash-verge-rev#86]
- OS:macOS 14.1.2arm
- Clash Verge Version:1.4.3
- Clash Core: Clash Meta 1.17.0
- clash verge rev已设置tun模式,且设置了开机自动运行.
macOS刚开机的时候Meta核心占用了大概1.2GB的内存,且此时verge是没在代理的,在verge里面选择重启clash核心之后问题解决.望早日修复此问题!

![截圖 2023-12-06 19 34 18](https://github.com/clash-verge-rev/clash-verge-rev/assets/61929738/6f570aaf-f948-4947-bd72-a1db81659e09)
![截圖 2023-12-06 19 34 51](https://github.com/clash-verge-rev/clash-verge-rev/assets/61929738/eea0db7b-20a8-447f-803b-50b12654b4cb)
![截圖 2023-12-06 19 35 28](https://github.com/clash-verge-rev/clash-verge-rev/assets/61929738/debb5d61-df17-4a41-952a-34d75c5e08e8)
![截圖 2023-12-06 19 36 47](https://github.com/clash-verge-rev/clash-verge-rev/assets/61929738/e4bfe24f-8ffb-4767-b9eb-13d09614fb21)

**Comment by wonfen** [comment]
这个问题请向meta内核那边反馈
https://github.com/MetaCubeX/mihomo
