### ISSUE TITLE
[BUG] TUN模式下， 断开WIFI后CPU/内存占用率过高

### ISSUE THREAD

**Issue by Mingtha** [clash-verge-rev/clash-verge-rev#860]
### 问题描述 / Describe the bug

只要在运行clash的情况下（TUN模式）， 关闭WIFI，也就是脱机状态，  clash的CPU占用率逐渐100%， 内存占用也越来越大， 得重新连接wifi， 然后更新一下订阅才能恢复
![捕获](https://github.com/clash-verge-rev/clash-verge-rev/assets/95164579/fc5e6d90-5725-406c-98e0-21a6faaf3e70)

### 复现步骤 / To Reproduce

- 运行clash-verge-rev
- 打开tun模式
- 关闭wifi链接，（我是笔记本，拔网线应该也有同样的效果）
- 可以看到CPU占用逐渐升高

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win 10 LTSC 2021

### 日志 / Log

04-12 11:17:56WARNING
[TCP] dial DIRECT (match GeoIP/cn) 198.18.0.1:55647(clash-meta.exe) --> 116.162.172.120:16617 error: reject loopback connection to: 116.162.172.120:16617
04-12 11:17:56WARNING
[TCP] dial DIRECT (match GeoIP/cn) 198.18.0.1:56605(clash-meta.exe) --> 116.162.172.120:16617 error: reject loopback connection to: 116.162.172.120:16617
04-12 11:17:56WARNING
[TCP] dial DIRECT (match GeoIP/cn) 198.18.0.1:55829(clash-meta.exe) --> 116.162.172.120:16617 error: reject loopback connection to: 116.162.172.120:16617
04-12 11:17:56WARNING
[TCP] dial DIRECT (match GeoIP/cn) 198.18.0.1:55534(clash-meta.exe) --> 116.162.172.120:16617 error: reject loopback connection to: 116.162.172.120:16617
04-12 11:17:56WARNING
[TCP] dial DIRECT (match GeoIP/cn) 198.18.0.1:56569(clash-meta.exe) --> 116.162.172.120:16617 error: reject loopback connection to: 116.162.172.120:16617
04-12 11:17:56WARNING
[TCP] dial DIRECT (match GeoIP/cn) 198.18.0.1:56655(clash-meta.exe) --> 183.232.142.46:16628 error: reject loopback connection to: 183.232.142.46:16628

**Comment by Mingtha** [comment]
![捕获](https://github.com/clash-verge-rev/clash-verge-rev/assets/95164579/e413de57-e1f1-4b4b-b29a-6ee4ac2e2950)

**Comment by Mingtha** [comment]
![0e3fe177-52b3-459f-a59d-16a9e7e6aec1](https://github.com/clash-verge-rev/clash-verge-rev/assets/95164579/d9712c2a-f2da-4a45-9b72-f56916069764)

**Comment by wuying2021** [comment]
切换alpha内核，不用发bug了

**Comment by Mingtha** [comment]
> 切换alpha内核，不用发bug了

alpha内核同样的问题
![捕获](https://github.com/clash-verge-rev/clash-verge-rev/assets/95164579/1b65cc38-7fd8-4750-85e2-f76271dea4ca)

**Comment by dongchengjie** [comment]
内核alpha修了[#1178](https://github.com/MetaCubeX/mihomo/issues/1178)
