### ISSUE TITLE
[BUG] 拨号上网环境下无法使用任何模式上网

### ISSUE THREAD

**Issue by rEco1LLLL** [clash-verge-rev/clash-verge-rev#861]
### 问题描述 / Describe the bug

拨号上网环境下无法使用任何模式上网

### 复现步骤 / To Reproduce

之前用v2rayn和nekoray可以正常使用 使用clash-verge与clash-nyanpasu都无法正常上网

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10 22h2

### 日志 / Log

1

**Comment by shino111** [comment]
拨号上网环境下上传下载都是0，换成热点就能连了，有没有办法

**Comment by rEco1LLLL** [comment]
> 拨号上网环境下上传下载都是0，换成热点就能连了，有没有办法
目前还没找到方法来解决 似乎是内核的问题

**Comment by SoHugePenguin** [comment]
对的，我也这个问题。没人修吗？

**Comment by lucienshawls** [comment]
老bug了，推测是meta内核的问题#550

**Comment by GBooy** [comment]
试过1.4.10版本的可用，1.4.11就报错了。只能先将就着用了

**Comment by SoHugePenguin** [comment]
> 试过1.4.10版本的可用，1.4.11就报错了。只能先将就着用了

好的，感谢告知。

**Comment by amazy2596** [comment]
> 拨号上网环境下上传下载都是0，换成热点就能连了，有没有办法

和我的一摸一样

**Comment by Charlotte4177** [comment]
众筹才能快点修吗

**Comment by SoHugePenguin** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1850

找到一个简单的办法 (在座的应该都是vless和电信受害者吧XD)
