### ISSUE TITLE
[Feature] 重启电脑后clash verge开机自启动优先级比较低，verge没启动完成电脑会没网，要多等几秒才能操作电脑有点烦，有大佬有解决办法不

### ISSUE THREAD

**Issue by studentluo** [clash-verge-rev/clash-verge-rev#862]
### 功能描述 / Feature description

同上

### 使用场景 / Use case

同上

**Comment by Well2333** [comment]
考虑到用户如果使用有线连接则不会出现这个问题，请问是否可以添加一个选项或保留一个方式，可以让软件以高优先级的方式启动呢？

**Comment by AnyWAT** [comment]
Win 系统试试用休眠代替关机，即使掉电断网，一旦上电驻留程序立马恢复正常。

**Comment by Well2333** [comment]
clash verge rev 手动开机自启动（高优先级）

1. 找到应用的可执行程序路径 ![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/40534114/89228b73-c4cd-4064-8c7a-fd821b9eb868)
2. win+r 输入 `taskschd.msc` ，创建基本任务 
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/40534114/7ed30cf5-3758-424b-b8a1-dbb9e3326e54)
3.  触发器选择 `当前用户登录时`，操作选择 `启动程序`，启动程序中选择步骤1中的可执行程序路径
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/40534114/e290209c-23c8-4761-a7a8-372de0491070)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/40534114/fb21bd7a-e454-4ba9-84bc-fd88d515b21d)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/40534114/5c9f144e-235b-46f8-a837-1db7c66aaa37)
4. 完成上述操作后，记得关掉程序自身的开机自启动，静默启动对此启动方式也可以生效

**Comment by 1298345095** [comment]
> clash verge rev 手动开机自启动（高优先级）
> 
> 1. 找到应用的可执行程序路径 ![image](https://private-user-images.githubusercontent.com/40534114/340919343-89228b73-c4cd-4064-8c7a-fd821b9eb868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTQzMTEsIm5iZiI6MTcyMTI5NDAxMSwicGF0aCI6Ii80MDUzNDExNC8zNDA5MTkzNDMtODkyMjhiNzMtYzRjZC00MDY0LThjN2EtZmQ4MjFiOWViODY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA5MTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNTgyMDEwNzM1MmIxOGI2ZDg4ZTU1YmJjYTBkMTZlODE0NGYxMGFhMWY2MTM0OTMwZmYzN2YyYmEwODIzZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5zu96dW8LN5dPYsfac1yerVBOq_v00gvGQJfCzQrkf0)
> 2. win+r 输入 `taskschd.msc` ，创建基本任务
>    ![image](https://private-user-images.githubusercontent.com/40534114/340920415-7ed30cf5-3758-424b-b8a1-dbb9e3326e54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTQzMTEsIm5iZiI6MTcyMTI5NDAxMSwicGF0aCI6Ii80MDUzNDExNC8zNDA5MjA0MTUtN2VkMzBjZjUtMzc1OC00MjRiLWI4YTEtZGJiOWUzMzI2ZTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA5MTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NzU2NWJlNmM0ZjVlOGZkYjQ1NzQ1MWVhMWZhOWVkMTAyMWExMjM0MmE5NjQzNmNjZjNhZGZmYWJjYWNjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rl6LCXOLjyd4doIJHO52YFBtkPAreZQS0tOacOcIjsg)
> 3. 触发器选择 `当前用户登录时`，操作选择 `启动程序`，启动程序中选择步骤1中的可执行程序路径
>    ![image](https://private-user-images.githubusercontent.com/40534114/340921603-e290209c-23c8-4761-a7a8-372de0491070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTQzMTEsIm5iZiI6MTcyMTI5NDAxMSwicGF0aCI6Ii80MDUzNDExNC8zNDA5MjE2MDMtZTI5MDIwOWMtMjNjOC00NzYxLWE3YTgtMzcyZGUwNDkxMDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA5MTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NjFmMzBiMmRhMzU0NzEyN2M1OTIxN2FkNTlmYTZiNDIxYjIxZmQ1OThiMzVhY2Y3NjY5OWZmMDllYjliMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9GiaUNKbkAoTdpnHzoP1bemNcKuyeaTheV-wslJCs-A)
>    ![image](https://private-user-images.githubusercontent.com/40534114/340921685-fb21bd7a-e454-4ba9-84bc-fd88d515b21d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTQzMTEsIm5iZiI6MTcyMTI5NDAxMSwicGF0aCI6Ii80MDUzNDExNC8zNDA5MjE2ODUtZmIyMWJkN2EtZTQ1NC00YmE5LTg0YmMtZmQ4OGQ1MTViMjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA5MTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MDhiYjA3Mzk0NDA4MGQ0OWQ3ZjMxZWEzZDljYzZkMjBjNmNmMjQ4ZjhkNjM0NDY0OWJlOGZmNTNjNDFmZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.39u6FmlakGoVU4wtGhfe4KlFW1e0c6Mnz1MuiVDLDAY)
>    ![image](https://private-user-images.githubusercontent.com/40534114/340922441-5c9f144e-235b-46f8-a837-1db7c66aaa37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTQzMTEsIm5iZiI6MTcyMTI5NDAxMSwicGF0aCI6Ii80MDUzNDExNC8zNDA5MjI0NDEtNWM5ZjE0NGUtMjM1Yi00NmY4LWE4MzctMWRiN2M2NmFhYTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA5MTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMzJiZjFiODhhM2UyNmQ2NTI4N2E5YjJkODk0YjExOWJhNmRiYTAxNjFhYzVlNmJkOTQ3YzRkNmQ0NDgyMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7qIpBU4REgq-ZS_wKdAy2UbdPlu2l6BqRPHTAFD_TLY)
> 4. 完成上述操作后，可以在任务列表中找到你刚刚添加的计划任务，双击打开，并在常规中勾选 `使用最高权限运行`
>    ![image](https://private-user-images.githubusercontent.com/40534114/340932097-4dd43300-4ec5-44b3-87c5-ed908bd4abc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTQzMTEsIm5iZiI6MTcyMTI5NDAxMSwicGF0aCI6Ii80MDUzNDExNC8zNDA5MzIwOTctNGRkNDMzMDAtNGVjNS00NGIzLTg3YzUtZWQ5MDhiZDRhYmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA5MTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YjgyODYwNmJlYjQ5NTQyYTIyY2EzZjg4YjFjZTExY2ExY2U5MzY4ZGJlMzlkYTE1ZDEwNzIxMDU0ZjI4ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DuRs_Wret_9upw4UX84bRwpT642qAfGFy3vkfl9s_3s)
> 
> 注意：
> 
> 1. 记得关掉程序自身的开机自启动，静默启动对此启动方式也可以生效
> 2. 如果不在最后一步勾选 `使用最高权限运行` 则可能导致 TUN 无法正常启动
>    ![image](https://private-user-images.githubusercontent.com/40534114/340933240-dbfc4c6d-5757-4d2c-a6bf-e01b2b574356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTQzMTEsIm5iZiI6MTcyMTI5NDAxMSwicGF0aCI6Ii80MDUzNDExNC8zNDA5MzMyNDAtZGJmYzRjNmQtNTc1Ny00ZDJjLWE2YmYtZTAxYjJiNTc0MzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA5MTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNTMyMGM4NGZlZjI2ZjViMmFlNmE4ZTI4NzdjMTc3YmMyNTBhMzQzNGQ4YTQ2ZjQ0ODQ0MjRmYzdmM2MzMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qvNB8zcVSsnOmCsVw60sknsivNthHQURbMxqoBoLhWw)

在我这里静默启动无效。。。
