### ISSUE TITLE
已经给站点、IP配置DIRECT的情况下，还是会请求超时或被拒绝连接

### ISSUE THREAD

**Issue by z1298808165** [clash-verge-rev/clash-verge-rev#864]
### 问题描述 / Describe the bug

日志显示如下，
```
04-13 22:40:39WARNING
[TCP] dial DIRECT (match DomainKeyword/wlcdn) 198.18.0.1:57743 --> cdn.wlcdn99.com:777 error: connect failed: dial tcp 127.0.0.1:777: connectex: No connection could be made because the target machine actively refused it.
```

```
04-13 22:40:39WARNING
[TCP] dial DIRECT (match RuleSet/cncidr) 198.18.0.1:57729(wpscloudsvr.exe) --> 61.130.196.21:61639 error: connect failed: dial tcp 61.130.196.21:61639: i/o timeout
```
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/25720725/409b1aa5-b518-4c89-9ff9-cefcb70737bd)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/25720725/c4c9339a-74ad-4e4c-9761-48ea27f03708)

### 复现步骤 / To Reproduce

开启代理发起请求就会出现

cdn.wlcdn99.com是zyplayer中播放卧龙资源视频时请求的，wpscloudsvr.exe是WPS Office主要负责管理和同步云端的

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/25720725/d98264e9-9d20-43fc-b82a-99963ef4da4d)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

```
04-13 22:40:39WARNING
[TCP] dial DIRECT (match DomainKeyword/wlcdn) 198.18.0.1:57743 --> cdn.wlcdn99.com:777 error: connect failed: dial tcp 127.0.0.1:777: connectex: No connection could be made because the target machine actively refused it.
```

```
04-13 22:40:39WARNING
[TCP] dial DIRECT (match RuleSet/cncidr) 198.18.0.1:57729(wpscloudsvr.exe) --> 61.130.196.21:61639 error: connect failed: dial tcp 61.130.196.21:61639: i/o timeout
```

**Comment by CleanC0der** [comment]
我在epic下载游戏的时候也碰到这个问题了，你是咋解决的
