### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by VinsonFather** [clash-verge-rev/clash-verge-rev#865]
### 问题描述 / Describe the bug

在macOS下的Clash Verge图标过大，之前的图标大小没那么大

### 复现步骤 / To Reproduce

-
<img width="224" alt="截屏2024-04-13 22 51 07" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/103871292/a18a5425-301e-47c3-a91b-596c573c7f30">
更新最新版本Clash Verge

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS 12.7.4

### 日志 / Log

no

**Comment by wonfen** [comment]
此问题已修复 https://github.com/clash-verge-rev/clash-verge-rev/commit/c5d7c29f3d5bc6baf6183b2f442584917c2fb754
下载alpha版本试试。
