### ISSUE TITLE
[BUG] can't install in ubuntu 24.04

### ISSUE THREAD

**Issue by jalenzz** [clash-verge-rev/clash-verge-rev#866]
### 问题描述 / Describe the bug

clash verge depends on libwebkit2gtk-4.0-37, which can't be installed on Ubuntu 24.04.

Ubuntu 24.04 can only install libwebkit2gtk-4.1-0.

#850 notice this, but was closed.

### 复现步骤 / To Reproduce

Install clash verge on Ubuntu 24.04

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu 24.04

### 日志 / Log

clash-verge depend libwebkit2gtk-4.0-37, which can not be install

**Comment by MystiPanda** [comment]
刚刚看了24.04也还有 `libwebkit2gtk-4.0-37` 包啊 https://packages.ubuntu.com/search?keywords=libwebkit2gtk-4.0-37&searchon=names&suite=noble&section=all

**Comment by jalenzz** [comment]
但是在 apt 中只有 4.1

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/57910033/6ffdb6a6-a54d-4cbb-bd8d-05b361641475)

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/57910033/b8aeb918-792c-463e-a94e-595666097c3f)

**Comment by kenzo-tm** [comment]
https://answers.launchpad.net/ubuntu/noble/amd64/libwebkit2gtk-4.0-37/2.43.3-1
https://answers.launchpad.net/ubuntu/noble/amd64/libjavascriptcoregtk-4.0-18/2.43.3-1

可以在这里现在到两个相关的依赖包，dpkg 安装上之后就可以装 clash verge 了。

**Comment by jalenzz** [comment]
@MystiPanda @kenzo-tm https://answers.launchpad.net/ubuntu/noble/amd64/libwebkit2gtk-4.0-37/2.43.3-1 这里面显示的 Status 已经是 Deleted 了

**Comment by li88iioo** [comment]
> @MystiPanda @kenzo-tm https://answers.launchpad.net/ubuntu/noble/amd64/libwebkit2gtk-4.0-37/2.43.3-1 这里面显示的 Status 已经是 Deleted 了

https://drive.google.com/drive/folders/15LgYsvn8RyCmytmI9YBjUHpcSeTuqS4n?usp=sharing

**Comment by TianJunfeng** [comment]
> > @MystiPanda @kenzo-tm https://answers.launchpad.net/ubuntu/noble/amd64/libwebkit2gtk-4.0-37/2.43.3-1 这里面显示的 Status 已经是 Deleted 了
> 
> https://drive.google.com/drive/folders/15LgYsvn8RyCmytmI9YBjUHpcSeTuqS4n?usp=sharing

手动安装依赖后，能正常安装，但是安装完成后，启动控制面板界面，无法显示

**Comment by machenme** [comment]
并不会吧。哪怕装上了这两个之后。能运行但是UI界面是无法显示出来的

**Comment by MystiPanda** [comment]
> 并不会吧。哪怕装上了这两个之后。能运行但是UI界面是无法显示出来的

这是另外的问题，翻翻issue

**Comment by MystiPanda** [comment]
https://clash-verge-rev.github.io/faq/install.html#ubuntu-2404

**Comment by yuhonny** [comment]
> https://clash-verge-rev.github.io/faq/install.html#ubuntu-2404
> 
> 缺失依赖包在 https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/dependencies 下载

it's working,thanks!

**Comment by xiaguangbo** [comment]
debian 

> Same error here. Trying to manually dpkg install raise a depedency error on `libicu70`.
> 
> ```
> Selecting previously unselected package libwebkit2gtk-4.0-37:amd64.
> (Reading database ... 148235 files and directories currently installed.)
> Preparing to unpack libkit.deb ...
> Unpacking libwebkit2gtk-4.0-37:amd64 (2.44.0-0ubuntu0.22.04.1) ...
> dpkg: dependency problems prevent configuration of libwebkit2gtk-4.0-37:amd64:
>  libwebkit2gtk-4.0-37:amd64 depends on libjavascriptcoregtk-4.0-18 (= 2.44.0-0ubuntu0.22.04.1); however:
>   Package libjavascriptcoregtk-4.0-18 is not installed.
>  libwebkit2gtk-4.0-37:amd64 depends on libicu70 (>= 70.1-1~); however:
>   Package libicu70 is not installed.
> 
> dpkg: error processing package libwebkit2gtk-4.0-37:amd64 (--install):
>  dependency problems - leaving unconfigured
> Processing triggers for libc-bin (2.39-0ubuntu8) ...
> Errors were encountered while processing:
>  libwebkit2gtk-4.0-37:amd64
> ```
> 
> Thanks for the help :)

I have the same issue

**Comment by znygithub** [comment]
> https://clash-verge-rev.github.io/faq/install.html#ubuntu-2404
> 
> 缺失依赖包在 https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/dependencies 下载

装了这两个依赖，但是clash 前端没有任何内容。
ubuntu24 x86电脑，有英伟达独显
![WechatIMG213](https://github.com/clash-verge-rev/clash-verge-rev/assets/98650439/c76159ba-fcf4-4a2b-8f5f-d3460865331b)

**Comment by S16201512** [comment]
I also get this error, somebody have worked on arm64?

**Comment by S16201512** [comment]
> I also get this error, somebody have worked on arm64?

https://clash-verge-rev.github.io/faq/linux.html#__tabbed_1_2

Nice！Version！Version！Version！

**Comment by bangbangmushroom** [comment]
it didn't work  even if I load that package the gui have problem.

**Comment by hellocaoziyi** [comment]
still doesn't work in Ubuntu 2024:
dpkg: dependency problems prevent configuration of clash-verge:
 clash-verge depends on libwebkit2gtk-4.0-37; however:
  Package libwebkit2gtk-4.0-37 is not installed.
and libwebkit2gtk-4.0-37 can not be installed by apt
