### ISSUE TITLE
[BUG] 在只开启只开启TUN模式和服务模式，没有开启系统代理的情况下，无法访问claude

### ISSUE THREAD

**Issue by ShaneLee-9** [clash-verge-rev/clash-verge-rev#867]
### 问题描述 / Describe the bug

![ip](https://github.com/clash-verge-rev/clash-verge-rev/assets/30720287/338f1585-a098-44ee-8799-909ebd95e509)
![setting](https://github.com/clash-verge-rev/clash-verge-rev/assets/30720287/34cf3f46-6e97-4111-9806-e20b70af2f61)
ip检测是美国，能访问 google、youtube，但是访问 claude，显示不在支持的地区。只有在开启系统代理时，才能正常访问 claude

### 复现步骤 / To Reproduce

设置中关闭系统代理，只开 TUN 模式和服务模式

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 23H2 22631.3447

### 日志 / Log

无

**Comment by LeanC0de** [comment]
我的Windows 11开启tun模式后无论怎么操作都显示小地球（无法连接互联网），大部分软件正常上网但是OneDrive这类软件（通过系统判断是否联网的软件？）无法联网，铁铁你的会这样嘛。

**Comment by ShaneLee-9** [comment]
> 我的Windows 11开启tun模式后无论怎么操作都显示小地球（无法连接互联网），大部分软件正常上网但是OneDrive这类软件（通过系统判断是否联网的软件？）无法联网，铁铁你的会这样嘛。

我这边除了我提出的这个问题，其他的都没问题

**Comment by bling-yshs** [comment]
我也遇到了

**Comment by bling-yshs** [comment]
> 我也遇到了

tun模式里开启严格路由解决了

**Comment by ShaneLee-9** [comment]
> > 我也遇到了
> 
> tun模式里开启严格路由解决了

我这边测试，在配置文件中，把每个代理的UDP设置为true就可以了

**Comment by dev4mobile** [comment]
我也遇到过，这是为啥？
