### ISSUE TITLE
[Feature] 类似clash，增加订阅的homeweb字段

### ISSUE THREAD

**Issue by lanceyliao** [clash-verge-rev/clash-verge-rev#870]
### 功能描述 / Feature description

类似clash，增加订阅的homeweb字段。
  - time: ********.yml
    name: ********
    url: ********
    selected: []
    interval: 24
    subInfo:
      upload: 114505
      download: 243677
      total: 53687091200
      expire: 1715661221
    homeWeb: 机场主页
    cron: ""
    headers: ""

### 使用场景 / Use case

从订阅链接找不到机场主页

**Comment by MystiPanda** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/152463842/93d32d42-9187-4813-9eda-e8e5df0b7de1)

**Comment by lanceyliao** [comment]
> ![image](https://private-user-images.githubusercontent.com/152463842/322274436-93d32d42-9187-4813-9eda-e8e5df0b7de1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDM3OTksIm5iZiI6MTcxMzE0MzQ5OSwicGF0aCI6Ii8xNTI0NjM4NDIvMzIyMjc0NDM2LTkzZDMyZDQyLTkxODctNDgxMy05ZWRhLWU4ZTVkZjBiN2RlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwMTExMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2UyYjI0YmQ4M2IxNjE3M2UyNTdlNjU5ZGZiNzJlZjIzM2VhN2ZkOWRlMmQ5ZGQ4NjlhNzA2ZjA4Nzc5ZTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S0oBB0Kppr53aYysOg2iYIJ1wWFF8VLNNHZfKwnemNA)

请问这个是alpha版本吗？latest版本没看到
