### ISSUE TITLE
[BUG] 无法更新proxy provider

### ISSUE THREAD

**Issue by Ardin963** [clash-verge-rev/clash-verge-rev#871]
### 问题描述 / Describe the bug

在新的电脑上用1.5.11版本配置订阅，订阅文件成功下载到订阅，但是无法使用，发现是proxy provider里面没有成功订阅到代理节点，在配置文件打开proxy provider的链接，也能正常打开

### 复现步骤 / To Reproduce

选中该配置文件，订阅provider多次都无法成功，数量显示为0

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10专业版 / 1.5.11

### 日志 / Log

[tcp] mihomo gitlab.com 443 match match using bypassed [compatible]

**Comment by wonfen** [comment]
不显示数据，请检查机场是否下发了相关数据。
