### ISSUE TITLE
[BUG] 导入配置部分不支持，在之前的clash是可以正常的

### ISSUE THREAD

**Issue by jacksonjim** [clash-verge-rev/clash-verge-rev#873]
### 问题描述 / Describe the bug

这个连接导入不了，会报错
https://clashgithub.com/wp-content/uploads/rss/20240415.yml

### 复现步骤 / To Reproduce

这个连接导入不了，会报错
https://clashgithub.com/wp-content/uploads/rss/20240415.yml

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 10

### 日志 / Log

the remote profile data is invalid yaml
wp-content/uploads/rss/

**Comment by MystiPanda** [comment]
问题很清楚啊，yaml格式不正确

**Comment by wbbo** [comment]
```
&quot;,
```
`&quot;`  和 `,`  连起来了, &quot; 应该是引号吧. 试了下文件下载下来本地导入可以导入
