### ISSUE TITLE
[Feature] 建议系统代理绕过参考 clash_for_windows 默认添加如下规则

### ISSUE THREAD

**Issue by MurphyZX** [clash-verge-rev/clash-verge-rev#878]
### 功能描述 / Feature description

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/61101985/7d30d9c2-843e-46b6-ba4e-087087ce6050)

localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*

### 使用场景 / Use case

不知道合理不

**Comment by milton4code** [comment]
希望能增加自定义域名绕过功能类似clash中 
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/13265817/b1451798-9e57-4fe8-a85a-b292235c8fbd)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/13265817/bea20703-447f-4dcd-b7fc-ac92035c12ba)

**Comment by raohuiyong** [comment]
什么时候能新增自定义规则？

**Comment by MurphyZX** [comment]
> @MurphyZX“不知道合理不”说明你自己都节日自己的需求，就别瞎提了，相当于完全了这是可习俗的。 @milton4code @raohuiyong 自定义规则重复说无数遍了，还有不要在别人的问题上发不相关的问题。 [https://clash-verge-rev.github.io/guide.html#merge-%E5%90%88% E5%B9%B6%E5%A4%84%E7%90%86](https://clash-verge-rev.github.io/guide.html#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86)

客气一下不行 b嘴巴这么臭啊？
