### ISSUE TITLE
[BUG]  clash-meta.exe 被360识别为木马

### ISSUE THREAD

**Issue by milton4code** [clash-verge-rev/clash-verge-rev#879]
### 问题描述 / Describe the bug

如标题所示,clash-verge-rev 1.5.11 被360识别为木马

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/13265817/23758833-0724-4201-88bb-8d32bf52945d)

### 复现步骤 / To Reproduce

使用360进行木马查杀,发现clash-meta.exe 识别为木马

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

无

**Comment by wonfen** [comment]
你知道360是GFW的承包商之一吗？

**Comment by ruhtrujyi** [comment]
Trojan协议字段触发了杀毒软件的特征检测，正常现象。
