### ISSUE TITLE
[Feature] 有支持mixin的计划吗, 在内网有内置的DNS解析需要直连, 会和订阅的规则冲突

### ISSUE THREAD

**Issue by chenjiangui** [clash-verge-rev/clash-verge-rev#88]
有支持mixin的计划吗, 在内网有内置的DNS解析需要直连, 会和订阅的规则冲突

**Comment by S-T-eve** [comment]
订阅里新建Merge，和Mixin用法一样，Merge里的字段会覆盖原始订阅的相同字段，除了那几个特殊的能在某几个字段的前后非覆盖添加

**Comment by chenjiangui** [comment]
> 订阅里新建Merge，和Mixin用法一样，Merge里的字段会覆盖原始订阅的相同字段，除了那几个特殊的能在某几个字段的前后非覆盖添加

我尝试添加了一条rule, 启用后不生效, 直接修改订阅后的文件是生效的, 是我使用的方式不对吗?
![图片](https://github.com/clash-verge-rev/clash-verge-rev/assets/18565140/2eff100c-f361-4119-9bdf-5da77274eaf2)

**Comment by S-T-eve** [comment]
修改完保存之后要点右上角火焰标来刷新，刷新成功会有系统通知，然后可以点旁边的书页标看看有没有添加进去

**Comment by chenjiangui** [comment]
> 修改完保存之后要点右上角火焰标来刷新，刷新成功会有系统通知，然后可以点旁边的书页标看看有没有添加进去

我确认已经启用了, 而且在规则的那栏可以过滤出规则
