### ISSUE TITLE
[BUG]  error: dns resolve failed: couldn't find ip

### ISSUE THREAD

**Issue by ansoncloud8** [clash-verge-rev/clash-verge-rev#882]
### 问题描述 / Describe the bug

1、开始clash verge 
2、开始内网vpn
3、打开内网vpn的域名，就会出现
error: dns resolve failed: couldn't find ip
但直接ip访问是正常的

### 复现步骤 / To Reproduce

1、开始clash verge 
2、开始内网vpn
3、打开内网vpn的域名，就会出现
error: dns resolve failed: couldn't find ip
但直接ip访问是正常的

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10

### 日志 / Log

[TCP] dial 👉 例外网站 (match Match/) 127.0.0.1:65071(chrome.exe) --> xx.com:443 error: dns resolve failed: couldn't find ip

**Comment by dongchengjie** [comment]
你内网的域名(主机名)如果不是公开的，你就算去DNS根服务器lookup也查不到啊
你应该使用你们内网的DNS服务器，自行配置[nameserver-policy](https://wiki.metacubex.one/config/dns/#nameserver-policy)

**Comment by yzgolden86** [comment]
我也出现了同样的问题，我这边未开启tunl，访问的也是公网的网站，但是却也出现了 dns resolve failed: couldn't find ip
不开代理的情况下直接访问是没问题的。请问可能是什么问题。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/56377040/29cf4a58-5c3a-457a-87a7-11a1ef9ad65c)

**Comment by yzgolden86** [comment]
> @yzgolden86 上面回复你没看懂吗，使用[nameserver-policy](https://wiki.metacubex.one/config/dns/#nameserver-policy)配置你内外网dns

好的，有点小白，开始没看明白，我现在试一下，感谢

**Comment by banjuer** [comment]
> > @yzgolden86 上面回复你没看懂吗，使用[nameserver-policy](https://wiki.metacubex.one/config/dns/#nameserver-policy)配置你内外网dns
> 
> 好的，有点小白，开始没看明白，我现在试一下，感谢

请问你怎么配置的，解决了没有

**Comment by dongchengjie** [comment]
> 请问你怎么配置的，解决了没有

https://clash-verge-rev.github.io/faq/other.html#_4

**Comment by banjuer** [comment]
> > > > @yzgolden86 上面回复你没看懂吗，使用[nameserver-policy](https://wiki.metacubex.one/config/dns/#nameserver-policy)配置你内外网dns
> > > 
> > > 
> > > 好的，有点小白，开始没看明白，我现在试一下，感谢
> > 
> > 
> > 请问你怎么配置的，解决了没有
> 
> 修改配置文件，添加 nameserver-policy配置，将域名改为指定的dns服务器就好了，我是直接指定为阿里的“223.5.5.5”

可我几乎所有的国内网站都是这个异常，不只是某个域名🤣

**Comment by LevineWoo** [comment]
> 我也出现了同样的问题，使用的是最新版v1.6.0，win11系统。我这边未开启tun，访问的也是公网的网站，但是却也出现了 dns resolve failed: couldn't find ip 不开代理的情况下直接访问是没问题的。请问可能是什么问题。 ![image](https://private-user-images.githubusercontent.com/56377040/325093455-29cf4a58-5c3a-457a-87a7-11a1ef9ad65c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODAxNTcsIm5iZiI6MTcxNjc3OTg1NywicGF0aCI6Ii81NjM3NzA0MC8zMjUwOTM0NTUtMjljZjRhNTgtNWMzYS00NTdhLTg3YTctMTFhMWVmOWFkNjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAzMTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMWE1ZmNiYjZjOTczYjVjMjc5OGVhOTI3ZDM5ZDIwZjNhMzExM2JlY2U1MmFhY2FkOWVlYTNiZGY1ZWZkYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pPnTMg9gsxsU_9w6ybVeXckNx6m1f3Awn4mWIuHRcoo)

重启一下clash核心就正常了。应该是clash的dns缓存时，刚好那时网络问题没有解析到正确的ip

**Comment by AlmostFamous1992** [comment]
我也遇到了类似的问题，访问b站等国内网站也经常出现访问迟缓甚至无法访问，访问xbox经常出问题。我记得旧版本不会有这个问题，怎么新版本v1.7.7要手动配置dns了呢？

**Comment by zhaoaaaaa5** [comment]
> > 请问你怎么配置的，解决了没有
> 
> https://clash-verge-rev.github.io/faq/other.html#_4 配置成可以正确解析你要的域名的权威服务器，如果是内网一般找网关解析

这个 url 里面的网关定义可能需要改下，我们公司默认网关是一个ip，dns服务器又是另一个ip，我直接使用默认网关的ip无法解析dns，后面换成了dns服务器里的ip才可以正确解析，应该加个说明，如果默认网关和dns服务器ip一致使用默认网关，如果大公司或者复杂网络，请注意默认网关和dns服务器是否一致。
![image](https://github.com/user-attachments/assets/2bf7740b-9e37-46da-97eb-9991a03fa7c1)

这里我贴一段csdn上找到的文章 https://blog.csdn.net/Dontla/article/details/139699127 可以仔细看下 1 和 4
![image](https://github.com/user-attachments/assets/9900e87e-5d95-4514-97f0-c9cfa268d949)

**Comment by LevineWoo** [comment]
另外还有可能是dns限速造成不解析的情况。

**Comment by zhaoaaaaa5** [comment]
> 另外还有可能是dns限速造成不解析的情况。

限速的话要怎么解决呢？ 刷新clash内核？

**Comment by LevineWoo** [comment]
> > 另外还有可能是dns限速造成不解析的情况。
> 
> 限速的话要怎么解决呢？ 刷新clash内核？

如果确定是限速的话，换不限速的dns就好了。我目前遇到的是刷小视频的时候，能瞬间并发1秒内请求上百次dns，这个是在阿里付费版dns（免费套餐）后台看的，后来我换运营商dns了。mihomo做了dns防泄漏的配置，大陆域名走运营商dns，其他域名走1111和8888的长连接doh请求

**Comment by zhaoaaaaa5** [comment]
> > > 另外还有可能是dns限速造成不解析的情况。
> > 
> > 
> > 限速的话要怎么解决呢？ 刷新clash内核？
> 
> 如果确定是限速的话，换不限速的dns就好了。我目前遇到的是刷小视频的时候，能瞬间并发1秒内请求上百次dns，这个是在阿里付费版dns（免费套餐）后台看的，后来我换运营商dns了。mihomo做了dns防泄漏的配置，大陆域名走运营商dns，其他域名走1111和8888的长连接doh请求

懂了 懂了 感谢指导

**Comment by LeadsiftAI** [comment]
我的之前也一直有问题，通过 @dongchengjie 大佬的回复，找到了相关的配置文件，最终通过修改 `全局扩展配置` 里的 `dns.fake-ip-filter:` 这个配置解决了

```yaml
dns:
  fake-ip-filter:
    - '+.local'
```

**Comment by nerd4me** [comment]
我的之前也一直有问题，通过 @dongchengjie 大佬的回复，找到了相关的配置文件，最终通过修改 全局扩展配置 里的 `dns.fake-ip-filter` 这个配置解决了

```yaml
dns:
  fake-ip-filter:
    - '+.local'
```

**Comment by mouhong** [comment]
我也碰到了这个问题，不过针对我自己的场景，直接把 dns 模块关掉就可以了（Verge 1.7.7, Clash 内核 v1.18.7）：

```
dns:
  enable: false
```

**Comment by troublewind** [comment]
> > > > > @yzgolden86 上面回复你没看懂吗，使用[nameserver-policy](https://wiki.metacubex.one/config/dns/#nameserver-policy)配置你内外网dns
> > > > 
> > > > 
> > > > 好的，有点小白，开始没看明白，我现在试一下，感谢
> > > 
> > > 
> > > 请问你怎么配置的，解决了没有
> > 
> > 
> > 修改配置文件，添加 nameserver-policy配置，将域名改为指定的dns服务器就好了，我是直接指定为阿里的“223.5.5.5”
> 
> 可我几乎所有的国内网站都是这个异常，不只是某个域名🤣
用'geosite:cn'

**Comment by kbill4345** [comment]
> 我也碰到了这个问题，不过针对我自己的场景，直接把 dns 模块关掉就可以了（Verge 1.7.7, Clash 内核 v1.18.7）：
> 
> ```
> dns:
>   enable: false
> ```

内网解决

**Comment by hanuxxx** [comment]
有同样的问题，域名在公共DNS上是可以正常解析的，用软件里默认的tls://223.5.5.5解析不出来，改成223.5.5.5就没问题了，测试了各个公共DNS解析都是正常的，另外手动测试了tls的223.5.5.5也是正常的

**Comment by ronysun** [comment]
> 我也碰到了这个问题，不过针对我自己的场景，直接把 dns 模块关掉就可以了（Verge 1.7.7, Clash 内核 v1.18.7）：
> 
> ```
> dns:
>   enable: false
> ```

用这个办法解决的，同时还要关闭TUN模式
