### ISSUE TITLE
[BUG] github无法正常访问

### ISSUE THREAD

**Issue by MoysMoys** [clash-verge-rev/clash-verge-rev#885]
### 问题描述 / Describe the bug

在使用ClashVerge时，无论使用什么模式，均无法打开github(测试中也是timeout)(但其余都正常)
同样的订阅链接，换到v2ray，打开github是正常的

### 复现步骤 / To Reproduce

1.https://github.com

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

[TCP] 127.0.0.1:41665(Clash Verge.exe) --> www.github.com:443 match DomainSuffix(github.com) using 节点选择[Hong Kong 06]

**Comment by CoolLoong** [comment]
无法复现

**Comment by MoysMoys** [comment]
> 无法复现

那请问我怎么联系你呢，可以远程看一下吗

**Comment by czz404** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/298

**Comment by MoysMoys** [comment]
> logs开debug发完整日志
> 无法复现

debug日志在这里：
[Uploading 2024-04-20-2136.log…]()

**Comment by NotGeekAtAll** [comment]
我也出现了，github打不开，现在换clash for windows就可以打开了

**Comment by DjyBrandon** [comment]
For clash-verge v2.0.3, `ping alive.github.com` can obtain the ip, then add the ip to `C:\Windows\System32\drivers\etc\hosts` file as cmd administrator is OK.

```
ping alive.github.com
cd C:\Windows\System32\drivers\etc
notepad hosts
ping github.com
```

**Comment by ClaytonWang** [comment]
我是 mac 系统，我也出现同样的问题，其他都能打开，唯独github。com 浏览器打不开，但能 ping 。我换sing-box就没问题。

**Comment by Neihan2020** [comment]
记录一个过程，我也遇到了楼主描述的问题，然后开始排查，发现是自己电脑上安装了一个名叫Watt Toolkit的软件导致出现的这个问题，这个软件会修改host文件，添加自己的内容，但是我平时没有使用Watt Toolkit，我运行了Watt Toolkit想要在软件设置中修改Watt Toolkit有关修改host的设置，但没有找到，就关闭了该软件，又阅读了host文件，关闭，但是这是我发现又可以访问Github了

**Comment by Neihan2020** [comment]
我并不清楚解决的原因，有相同情况的可以借鉴

**Comment by Tychristine** [comment]
@Neihan2020 💬 New comment on clash-verge-rev#885 [BUG] github无法正常访问
by @Neihan2020

你并不清楚解决的原因，有相同情况的可以借鉴

Reply to this message to post a comment on GitHub.

**Comment by N2022062** [comment]
Clash meta rev 也有此问题
