### ISSUE TITLE
1.4.3服务模式无法安装[BUG]

### ISSUE THREAD

**Issue by 130fanhuan** [clash-verge-rev/clash-verge-rev#89]
![Snipaste_2023-12-07_09-16-36](https://github.com/clash-verge-rev/clash-verge-rev/assets/33874956/77f530f5-7265-4cfe-9640-26b645ac71dd)
1.4.3安装服务模式报错

**Comment by jmui114** [comment]
我也遇到过几次，后来发现电脑重启之后再来安装就可以了

**Comment by 130fanhuan** [comment]
重启也没法安装

**Comment by wonfen** [comment]
这个问题已经修复了，卸载重新下载安装。

**Comment by 130fanhuan** [comment]
> 这个问题已经修复了，卸载重新下载安装。

重新下载还是一样，我发现文件没有更新，文件的SHA256码和昨天下的文件一样: df8a538d01cbcb60fed061be37da560706d32c526dabd95e13f052ff3d927851
