### ISSUE TITLE
[Feature] 代理类型没有 cfw 对应的 http 和 pac 吗？

### ISSUE THREAD

**Issue by saodis** [clash-verge-rev/clash-verge-rev#896]
### 功能描述 / Feature description

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/51149477/537676d7-64a2-4078-8b9c-19de245f556d)

pac 可以设置规则
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/51149477/d48504df-1f34-47b6-a568-c08ce69e645f)

这个 pac
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/51149477/c391b5af-072c-4133-be54-dff7c27e55c2)

### 使用场景 / Use case

系统 pip 安装库要pac的方式，不然安装不了。tun 估计也行，没试过，一直用pac

**Comment by wonfen** [comment]
一直没搞懂pac到底是个什么模式？底层逻辑是什么？是什么原理？

**Comment by junlongzzz** [comment]
> 一直没搞懂pac到底是个什么模式？底层逻辑是什么？是什么原理？

https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file

就一个 `js` 脚本文件

**Comment by saodis** [comment]
作者有计划出这个小功能么，clash 用习惯了，有些规则想直接迁移过来。还有这个预处理也蛮好用的
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/51149477/ee61d4ad-d8c1-40b2-9eaf-433dcd79d918)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/51149477/08b87c52-1f5a-4233-99b6-0bd7a969929b)

**Comment by dongchengjie** [comment]
https://clash-verge-rev.github.io/guide/script.html

**Comment by fuwuqi298** [comment]
@dongchengjie @wonfen 有计划增加这个代理类型？很需要这个
