### ISSUE TITLE
[BUG] 开启tun模式后，下载文件时候监测到clash占用大量上传，但是clash显示没有这个上传

### ISSUE THREAD

**Issue by lige47** [clash-verge-rev/clash-verge-rev#898]
### 问题描述 / Describe the bug

开启tun模式，服务模式，关闭系统代理，用idm下载文件或者tg下载视频的时候，下载速度正常显示，但是火绒监测到上传带宽也很大，普通代理模式正常，clash左下角不显示那个异常的上传的速度

### 复现步骤 / To Reproduce

开启tun模式，服务模式，关闭系统代理，用idm下载文件或者tg下载视频的时候，下载速度正常显示，但是火绒监测到上传带宽也很大，普通代理模式正常，clash左下角不显示那个异常的上传的速度

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows10  21H2  clash verge 1.5.11

### 日志 / Log

![PixPin_2024-04-19_16-39-59](https://github.com/clash-verge-rev/clash-verge-rev/assets/97075835/e2510863-e86b-424f-89c9-91911d70322c)
![PixPin_2024-04-19_16-40-26](https://github.com/clash-verge-rev/clash-verge-rev/assets/97075835/93814d1e-ec69-41ce-9827-46956a658638)
![PixPin_2024-04-19_16-50-37](https://github.com/clash-verge-rev/clash-verge-rev/assets/97075835/29acfb82-d3cb-4f3a-a92e-8a511f8e3d8b)
![PixPin_2024-04-19_16-50-52](https://github.com/clash-verge-rev/clash-verge-rev/assets/97075835/6ad12655-06e0-49f7-bb0b-75c3ad252945)

**Comment by dongchengjie** [comment]
你没注意到上行和下行带宽相等吗？
TUN从网络下载东西，就是下行带宽，然后移交给程序，不就是上行吗

**Comment by lige47** [comment]
当然发现了，但是我在使用clash for Windows 、v2rayN这两款软件的过程中，同样开启的tun模式，他们就没有显示上传，所以是实现的逻辑不一样吗？

**Comment by wonfen** [comment]
显示有什么问题吗？

**Comment by lbcake** [comment]
> 显示有什么问题吗？

wofen 什么时候大更新啊？

**Comment by lige47** [comment]
> 显示有什么问题吗？

只是感觉很难受而已，因为其他软件不显示习惯了
