### ISSUE TITLE
macos使用tun模式增加自动修改dns的功能

### ISSUE THREAD

**Issue by xingyue52077** [clash-verge-rev/clash-verge-rev#90]
macos使用tun模式，需要手动设置dns 为192.18.0.2，希望可以添加自动功能，在原仓库未关闭前已有开发者 贡献了pr 但没有merge，希望可以添加此功能。

原仓库pr：
https://github.com/zzzgydi/clash-verge/pull/850

**Comment by wonfen** [comment]
不懂为何要手动设置dns？

**Comment by yanghui421837** [comment]
> 不懂为何要手动设置dns？
因为Macos 下使用tun 模式不起作用, 上不了网.  需要手动设置, 所以最好在gui里面集成这个 命令networksetup -setdnsservers Wi-Fi 198.18.0.2

**Comment by wonfen** [comment]
tun模式需要授权，看下FAQ： https://github.com/clash-verge-rev/clash-verge-rev/issues/125

**Comment by JACK-THINK** [comment]
> tun模式需要授权，看下FAQ： #125

这Bug**不是授权能解决的**。授权仅修改了clash内核的权限，并不能自动修改系统DNS使其指向Fake-ip，这才是导致MacOS下TUN模式不可用的根本原因。 @xingyue52077 的解决方法是正确的，请添加此功能。
