### ISSUE TITLE
[BUG] 在UI界面中，删除配置文件的“更新间隔”出bug

### ISSUE THREAD

**Issue by Troray** [clash-verge-rev/clash-verge-rev#907]
### 问题描述 / Describe the bug

v1.5.11

在“订阅”选项卡“中，不管是本地配置文件，还是导入在线配置，”更新间隔“如果原来就留空，那么修改其他任意项都可以正常保存。
![K8QtiUpjK0](https://github.com/clash-verge-rev/clash-verge-rev/assets/16841721/a89f681f-7d3c-4dda-b8be-82713d3998fe)

但是，如果配置文件中包含更新间隔时间，或者自行输入后，再清空本项内容，则报错。
![Clash_Verge_LQJtD9VTIR](https://github.com/clash-verge-rev/clash-verge-rev/assets/16841721/23f909c5-ef68-4def-866c-3926febdc533)

### 复现步骤 / To Reproduce

1、填写”更新间隔“ 
2、清空”更新间隔“，保存报错

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

-

**Comment by dongchengjie** [comment]
还真是
