### ISSUE TITLE
[Feature]ARM架构的银河麒麟系统无法正常使用

### ISSUE THREAD

**Issue by relaxxu** [clash-verge-rev/clash-verge-rev#91]
能够安装成功，但无法打开使用。
查看了一下，可能是内核版本太低的缘故，显示glibc版本不够。

**Comment by MystiPanda** [comment]
#93

**Comment by relaxxu** [comment]
谢谢你的快速回复，期待大佬的更新！

**Comment by relaxxu** [comment]
银河麒麟版本太低，还是用不了😂



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月07日 17:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [clash-verge-rev/clash-verge-rev] [Feature]ARM架构的银河麒麟系统无法正常使用 (Issue #91) |

已经更新，可以下载最新的1.4.3版本

**Comment by MystiPanda** [comment]
银河的glibc版本是多少？

**Comment by relaxxu** [comment]
银河最高的glibc版本显示是2.23。运行verge显示缺2.25、2.27、2.28



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月11日 13:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [clash-verge-rev/clash-verge-rev] [Feature]ARM架构的银河麒麟系统无法正常使用 (Issue #91) |

银河的glibc版本是多少？

**Comment by MystiPanda** [comment]
2.23这个版本说实话太低了，nodejs最低都只支持2.28，这我没办法之前，你可以考虑自己手动编译。

**Comment by relaxxu** [comment]
如果我有这个能力就不会求教大佬你了😂



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月12日 09:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [clash-verge-rev/clash-verge-rev] [Feature]ARM架构的银河麒麟系统无法正常使用 (Issue #91) |

2.23这个版本说实话太低了，nodejs最低都只支持2.28，这我没办法之前，你可以考虑自己手动编译。
