### ISSUE TITLE
[小建议]自定义任务栏托盘图标增加ico类型

### ISSUE THREAD

**Issue by shawlj** [clash-verge-rev/clash-verge-rev#910]
### 功能描述 / Feature description

目前clash-verge托盘自定义图标只有一种png格式，png并不适合作为图标来使用。以前clash-for-windows支持ico等多种类型图标，完美适配托盘图标，png格式托盘图标因分辨率问题，呈现锯齿状
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/19167342/6e06c374-517f-4e08-b575-2a40e19a1dae)

### 使用场景 / Use case

增加自定义任务栏托盘ico类型图标，不仅限于png格式。
![优效截图20240422140148](https://github.com/clash-verge-rev/clash-verge-rev/assets/19167342/d16010af-c432-4d70-84f8-23e3a63ae199)

**Comment by dongchengjie** [comment]
verge rev的老版是verge，不是CFW😅
cfw是electron Node.js写的，verge是tauri用rust写的，框架都不一样
