### ISSUE TITLE
[BUG] 1.6.0版本 additional-suffix 配置失效

### ISSUE THREAD

**Issue by Sakana520** [clash-verge-rev/clash-verge-rev#913]
### 问题描述 / Describe the bug

override: {additional-suffix: ""}，给节点添加自定义名称的配置在更新到1.6.0版本不起作用，老版本无此问题

### 复现步骤 / To Reproduce

同样的配置文件，在1.5.11版本可以正常显示自定义名称，在1.6.0版本不起作用

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows10

### 日志 / Log

无

**Comment by dongchengjie** [comment]
1.6的内核回退到了1.18.1，1.18.3内核有BUG

**Comment by Sakana520** [comment]
先换成alpha内核用着先
