### ISSUE TITLE
[BUG] Unable to turn on service mode on Linux

### ISSUE THREAD

**Issue by clash-verge-rev-issues** [clash-verge-rev/clash-verge-rev#914]
### 问题描述 / Describe the bug

I'm using `clash-verge_1.6.0_amd64.AppImage` and I tried to turn on the `service mode`. However, I failed.

I tried to install service by clicking the `install` bottom and entered my root password, but it turned out that I cannot install it.
![图片](https://github.com/clash-verge-rev/clash-verge-rev/assets/167855268/cbd3ff0c-44cf-4935-8885-93e98415b1c5)

I also tried to install this module manually, but my terminal told me that I cannot run this command with root permission. and this is the output. 
```
  /tmp/.mount_clash7LKRHh/usr/lib/clash-verge/resources ─────────────────────────────────  base  16:00:40
❯ ll
总计 26M
-rwxr-xr-x 1 root root 3.0M  4月23日 14:48 clash-verge-service
-rw-r--r-- 1 root root 5.5M  4月23日 14:48 Country.mmdb
-rw-r--r-- 1 root root  11M  4月23日 14:48 geoip.dat
-rw-r--r-- 1 root root 3.0M  4月23日 14:48 geosite.dat
-rwxr-xr-x 1 root root 2.0M  4月23日 14:48 install-service
-rw-r--r-- 1 root root  448  4月23日 14:48 set_dns.sh
-rwxr-xr-x 1 root root 2.0M  4月23日 14:48 uninstall-service
-rw-r--r-- 1 root root  415  4月23日 14:48 unset_dns.sh

  /tmp/.mount_clash7LKRHh/usr/lib/clash-verge/resources ─────────────────────────────────  base  16:00:41
❯ sudo ./install-service    
sudo: ./install-service：找不到命令

  /tmp/.mount_clash7LKRHh/usr/lib/clash-verge/resources ─────────────────────────────────  base  16:00:44
❯ sudo su               
localhost:/tmp/.mount_clash7LKRHh/usr/lib/clash-verge/resources # ls
ls: cannot open directory '.': Permission denied
localhost:/tmp/.mount_clash7LKRHh/usr/lib/clash-verge/resources # 
```

### 复现步骤 / To Reproduce

Just click the `install` bottom and enter my root password as the picture i provided. 

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

openSUSE Tumbleweed 20240419

### 日志 / Log

```bash
(clash-verge:20065): GLib-GObject-WARNING **: 15:39:46.568: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'

(WebKitWebProcess:20154): Gtk-WARNING **: 15:39:46.616: Theme parsing error: gtk.css:3376:25: 'font-feature-settings' is not a valid property name

(WebKitWebProcess:20154): GLib-GObject-WARNING **: 15:39:46.669: g_object_set_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
/usr/bin/sh: 行 1: /tmp/.mount_clash7LKRHh/usr/lib/clash-verge/resources/install-service: 权限不够

** (clash-verge:20065): WARNING **: 15:40:07.525: atk-bridge: get_device_events_reply: unknown signature
/usr/bin/sh: 行 1: /tmp/.mount_clash7LKRHh/usr/lib/clash-verge/resources/install-service: 权限不够
/usr/bin/sh: 行 1: /tmp/.mount_clash7LKRHh/usr/lib/clash-verge/resources/install-service: 权限不够
```

**Comment by IF-tiger** [comment]
me too

**Comment by MystiPanda** [comment]
不支持appimage

**Comment by IF-tiger** [comment]
下载deb包解压，继续解压control和data,进入usr/lib/clash-verge/resources/运行相关sh即可，

**Comment by rongusantuai** [comment]
i have the same problem but mistake with status 1 , mac os m1

**Comment by clash-verge-rev-issues** [comment]
> i have the same problem but mistake with status 1 , mac os m1

Duplicate with [issue 859](https://github.com/clash-verge-rev/clash-verge-rev/issues/859)?

**Comment by IF-tiger** [comment]
obs已经有clash-verge-rev for rpm,不过我安装了有很多问题，
1：代理界面空白（可以通过任务栏图标右击切换规则模式），
2：内核动不动读取失败（手动开关tun开关），
3：切换代理模式点击无效（通过外部webgui切换代理模式），
4：希望可以让窗口继承kde自带的窗口模式
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/60809013/b349d9c5-b202-4c37-bda0-91d057e5cc70)

**Comment by notavaliablename** [comment]
> obs已经有clash-verge-rev for rpm,不过我安装了有很多问题， 1：代理界面空白（可以通过任务栏图标右击切换规则模式）， 2：内核动不动读取失败（手动开关tun开关）， 3：切换代理模式点击无效（通过外部webgui切换代理模式）， 4：希望可以让窗口继承kde自带的窗口模式 ![image](https://private-user-images.githubusercontent.com/60809013/326189487-b349d9c5-b202-4c37-bda0-91d057e5cc70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MzU5MDMsIm5iZiI6MTcxNDUzNTYwMywicGF0aCI6Ii82MDgwOTAxMy8zMjYxODk0ODctYjM0OWQ5YzUtYjIwMi00YzM3LWJkYTAtOTFkMDU3ZTVjYzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDAzNTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNTYxMmVlYjI4M2YyZmJjZjM3M2YxNjU1NmI2MTUwZDlhOTZjYmY0MWUzZWY5NDAxMjk5Nzg2MWY1NzdlNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LHZYqBIoAe6SlWlkvYaH_kjlfu-QZdhCmtyELrUB51E)

继承kde窗口的问题在kubuntu deb版也有，可以右键kde窗口，选择特殊操作，配置特殊应用程序设置，在弹出的窗口中选择添加属性，在外观和修正中找到无标题栏和边框，点击添加并开启，点击确定关闭窗口，重启Clash Verge就可以了。
