### ISSUE TITLE
[BUG] 系统托盘出现重复图标，无法通过任务栏打开主界面

### ISSUE THREAD

**Issue by ch3NzZxM** [clash-verge-rev/clash-verge-rev#915]
### 问题描述 / Describe the bug

不知是什么原因导致的，当设置托盘点击事件为系统代理，并打开系统代理时，点击任务栏图标，系统托盘出现重复图标，无法通过任务栏打开主界面
<img width="600" alt="Snipaste_2024-04-23_18-21-21" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/122508685/8b1dcf86-8a35-402a-88b7-2ae616250276">
<img width="66" alt="Snipaste_2024-04-23_18-21-34" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/122508685/c1177592-de7d-43aa-b9c1-6648412e9ba9">
<img width="600" alt="Snipaste_2024-04-23_18-21-46" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/122508685/8aeda087-c61c-48ec-b9b7-a844103d1437">

### 复现步骤 / To Reproduce

如上所述

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11/22H2，22621.3447

### 日志 / Log

<img width="600" alt="Snipaste_2024-04-23_18-32-03" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/122508685/8474aec2-1a6d-4057-b13c-c753069f259f">

**Comment by zhaobudaomingzi** [comment]
设置托盘点击事件为显示主窗口时也有相同的bug
此时通过托盘打开主窗口会发现节点排序与之前不一样，应该是软件重启了
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/54617500/a1d15bcc-7e5b-48e6-8344-c8175d5aeb7d)

**Comment by ch3NzZxM** [comment]
> 设置托盘点击事件为显示主窗口时也有相同的bug 此时通过托盘打开主窗口会发现节点排序与之前不一样，应该是软件重启了 ![image](https://private-user-images.githubusercontent.com/54617500/325150010-a1d15bcc-7e5b-48e6-8344-c8175d5aeb7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTAwNTAsIm5iZiI6MTcxNDEwOTc1MCwicGF0aCI6Ii81NDYxNzUwMC8zMjUxNTAwMTAtYTFkMTViY2MtN2U1Yi00OGU2LTgzNDQtYzgxNzVkNWFlYjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA1MzU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMmYzODI3M2M0YzQ4NGMxZWM2NGMzNWNjODhjNGQyMGNhN2MwMmUwM2JiYjEyNWIwN2YzNThjZjE5N2ExMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.po2kZZosRoUenA6MqTvsfqUP2yx7gKhTtdhffxkb4pc)

感觉是这样，但是这个bug跟ipv6的设置有关，看我最后一张图日志报错

**Comment by ch3NzZxM** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/122508685/214ea801-92a8-4de4-9b9a-af540a35abea)
新版依旧，报错如下
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/122508685/8e44f8dd-6ee0-4e8b-b2c3-520bce382c7c)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/122508685/37d64b93-00e8-4248-a578-4d566897c02b)

**Comment by ch3NzZxM** [comment]
如果是设置问题，烦请告知操作，感谢

**Comment by ch3NzZxM** [comment]
app重启，请关注
