### ISSUE TITLE
[BUG] Linux Service Mode:  installer not found!

### ISSUE THREAD

**Issue by lutianen** [clash-verge-rev/clash-verge-rev#916]
### 问题描述 / Describe the bug

# Linux Service installer not found!
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/61954994/168c0174-609b-4eea-b256-dcda77a55d86)

### 复现步骤 / To Reproduce

Guess the reason: **Because the download address in the Linux platform is not parsed correctly or there is a logic bug in the function as shown below**:

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/61954994/aa244b25-06cd-4c77-89f7-1cf424abb08c)

---

The relevant screenshots of the key logic part are as follows:

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/61954994/02e756fe-9b1d-40a9-af24-44272ce8c8ae)

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/61954994/ac86297f-8952-4399-a13d-fcfd7e0d002a)

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/61954994/727fda22-f628-4990-997e-ee2b4f46a8be)

---

The service naming format is as follows:

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/61954994/2df58f92-f511-42ca-b967-2234ffae1e56)

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Linux arch 6.6.28-1-lts

### 日志 / Log

2024-04-23 22:42:00 ERROR - installer not found
2024-04-23 22:42:00 ERROR - failed to connect to the Clash Verge Service

**Comment by hustler-not-chatty** [comment]
Can you check the content of `/usr/lib/clash-verge/resources/`?

**Comment by awsl1414** [comment]
安装 clash-verge-rev-bin 这个包

**Comment by lutianen** [comment]
> Can you check the content of `/usr/lib/clash-verge/resources/`?

Relevant content of /usr/lib/clash-verge/resources/` is as follows:

```sh
~ $ ls -al /usr/lib/clash-verge/resources/
total 3052
drwxr-xr-x 2 root root    4096 Apr 24 11:50 ./
drwxr-xr-x 3 root root    4096 Apr  8 12:33 ../
-rw-r--r-- 1 root root 3116224 Apr 12 10:10 clash-verge-service
lrwxrwxrwx 1 root root      23 Apr 24 04:23 Country.mmdb -> /etc/clash/Country.mmdb
```

---

After updating clash-verge v1.6.0-2 (`yay -S clash-verge`), the `installer not found` problem still exist.

**Comment by lutianen** [comment]
> 安装 clash-verge-rev-bin 这个包

When I try to install clash-verge-rev-bin, the OS feedback conflicts with the installed clash-verge.

```Bash
:: clash-verge-rev-bin-1.6.0-1 and clash-verge-1.6.0-2 are in conflict. Remove clash-verge? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: clash-verge-rev-bin-1.6.0-1 and clash-verge-1.6.0-2 are in conflict
```

Then, I uninstall `clash-verge` and try to install `clash-verge-rev-bin` again. It works.

I don't know where the problem is? Hope it helps you.

**Thanks ^_^**

**Comment by awsl1414** [comment]
yay -S clash-verge
sudo pacman -Rscn clash-verge
yay -S clash-verge-rev-bin
如果还是报错，试试 paru -S clash-verge-rev-bin

**Comment by hustler-not-chatty** [comment]
Turns out that `clash-verge` from AUR didn't pack any required component for service mode. Arch users should use `clash-verge-rev-bin` instead.

**Comment by kenzo-tm** [comment]
到 https://github.com/clash-verge-rev/clash-verge-service 下载三个 service 文件，然后放到 `/usr/lib/clash-verge/resources/` 目录下，给上执行权限
