### ISSUE TITLE
[BUG] KDE 下系统代理仍然无效

### ISSUE THREAD

**Issue by awsl1414** [clash-verge-rev/clash-verge-rev#918]
## 过程
我看了 V1.6.0 更新日志，看到 KDE 系统代理已经得到修复，但在我的电脑上，这个问题仍然存在
我尝试过 [clash-verge-rev-bin](https://aur.archlinux.org/packages/clash-verge-rev-bin)， 、appimgae版本，也尝试过自己编译运行，但是问题都存在。

### 复现步骤 / To Reproduce

1、打开clash-verge-rev-bin
2、导入订阅
3、授权内核
4、授权服务模式
5、打开系统代理
6、问题出现：系统代理不生效
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/95275520/e97dca4f-b035-417f-a0ea-657ea2c433c9)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/95275520/8aa8fd6d-8a6c-495e-a5b0-5cf493a5ad88)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/95275520/f0f0cfd3-c1c9-4fa3-b1a9-ae094ec10c35)

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

操作系统： Arch Linux  KDE /Plasma 版本： 6.0.4 /KDE 程序框架版本： 6.1.0 Qt 版本： 6.7.0 /内核版本： 6.8.7-zen1-1-zen (64 位) /图形平台： Wayland

### 日志 / Log

❯ pnpm dev

> clash-verge@1.6.0 dev /home/arch/Desktop/clash-verge-rev
> tauri dev

     Running BeforeDevCommand (`pnpm run web:dev`)

> clash-verge@1.6.0 web:dev /home/arch/Desktop/clash-verge-rev
> vite

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  VITE v5.2.9  ready in 88 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
        Info Watching /home/arch/Desktop/clash-verge-rev/src-tauri for changes...
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s

**Comment by awsl1414** [comment]
我在另外一台电脑上又没问题，我自己再排查一下问题吧

**Comment by JokingAboutLife** [comment]
@wonfen 需要更新 sysproxy 依赖库来刷新 `Cargo.lock` 文件
``` shell
cargo update sysproxy
```

**Comment by awsl1414** [comment]
```shell
cargo update -p sysproxy
error: could not find `Cargo.toml` in `/home/arch` or any parent directory
------------------------------------------------------------------------------------------------------------
cargo update -p sysproxy
error: could not find `Cargo.toml` in `/home/arch/.local/share/io.github.clash-verge-rev.clash-verge-rev` or any parent directory
```
请问我应在在那个目录执行这个命令

**Comment by awsl1414** [comment]
> @wonfen 需要更新 sysproxy 依赖库来刷新 `Cargo.lock` 文件
> 
> ```shell
> cargo update -p sysproxy
> ```

```shell
cargo update -p sysproxy
error: could not find `Cargo.toml` in `/home/arch` or any parent directory
------------------------------------------------------------------------------------------------------------
cargo update -p sysproxy
error: could not find `Cargo.toml` in `/home/arch/.local/share/io.github.clash-verge-rev.clash-verge-rev` or any parent directory
```
请问我应该在哪个目录执行这个命令

**Comment by JokingAboutLife** [comment]
> 请问我应该在那个目录执行这个命令

src-tauri 目录下

KDE很多软件是不走系统代理的，我是比较推荐使用 tun 模式

**Comment by awsl1414** [comment]
> > 请问我应该在那个目录执行这个命令
> 
> src-tauri 目录下
> 
> KDE很多软件是不走系统代理的，我是比较推荐使用 tun 模式

谢谢，我明白了，但是通过 aur 安装的怎么解决这个问题

**Comment by JokingAboutLife** [comment]
aur我不太清楚，应该需要等仓库更新重新打包后，aur那边再重新打包上传吧

**Comment by ACGNworld** [comment]
确实，kde下好多都不走系统代理了，gnome下就没这个问题。而且我用tun有时候dns解析就崩了
