### ISSUE TITLE
[BUG] Linux环境 Hysteria2 协议无法使用

### ISSUE THREAD

**Issue by zhengxiongzhao** [clash-verge-rev/clash-verge-rev#919]
### 问题描述 / Describe the bug

Linux 环境 Hysteria2 协议无法使用

### 复现步骤 / To Reproduce

Linux x11桌面环境， 打开clash-verge_1.5.X_amd64.AppImage包， ， Hysteria2节点显示Error ，其他协议正常显示延迟速率

### 操作系统 / OS

Linux amd64.

### 操作系统版本 / OS Version

AlmaLinux release 8.9 (Midnight Oncilla)

### 日志 / Log

1. 启动后日志显示错误： 
    Start Redir server error: operation not permitted
    Start TProxy server error: operation not permitted
2. 节点状态显示: 
    Error
4. 选择Error的节点后显示： 
    error: CRYPTO_ERROR 0x12a (local): tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by xishang0128** [comment]
错误1很明显是没有足够的权限,错误3是常见的证书错误,请检查证书

**Comment by wonfen** [comment]
错误3:请使用全链证书
