### ISSUE TITLE
[BUG] 修改external-controller后应用崩溃

### ISSUE THREAD

**Issue by Long0x0** [clash-verge-rev/clash-verge-rev#92]
**Describe the bug**
修改 external-controller 为 10.0.10.3:9098 后应用崩溃，窗口透明

**Screenshots**
![Snipaste_2023-12-07_11-11-51](https://github.com/clash-verge-rev/clash-verge-rev/assets/51022287/1e691fa1-d300-434b-827e-3f902efb2cc8)

- OS: Windows
- Clash Verge Version: 1.4.3
- Clash Core: Clash Meta

**Additional context**
可以打开devtools吗，这样方便调试和自定义UI

**Comment by wonfen** [comment]
从提示来看是你的 10.0.10.3:9098 启用了 https，所以无法载入

**Comment by Long0x0** [comment]
> 从提示来看是你的 10.0.10.3:9098 启用了 https，所以无法载入

并没有，https是另外一项 https://wiki.metacubex.one/config/general/#api
配置之后只是UI崩溃了，用yacd可以正常连接http://10.0.10.3:9098

**Comment by MystiPanda** [comment]
问题在于Tauri通过https来加载页面，或许把ws://改为wss://可以解决问题，我正在尝试修复。

**Comment by MystiPanda** [comment]
> > 从提示来看是你的 10.0.10.3:9098 启用了 https，所以无法载入
> 
> 并没有，https是另外一项 [wiki.metacubex.one/config/general/#api](https://wiki.metacubex.one/config/general/#api) 配置之后只是UI崩溃了，用yacd可以正常连接http://10.0.10.3:9098

你说你用yacd可以正常连接，你使用的是自己部署的yacd吗，我尝试使用https://yacd.metacubex.one/，因为页面启用了https，也是无法连接到内核。

**Comment by MystiPanda** [comment]
另外请问什么情况下需要填写10.0.10.3这种地址呢，0.0.0.0可以满足需求吗？

**Comment by Long0x0** [comment]
> > > 从提示来看是你的 10.0.10.3:9098 启用了 https，所以无法载入
> > 
> > 
> > 并没有，https是另外一项 [wiki.metacubex.one/config/general/#api](https://wiki.metacubex.one/config/general/#api) 配置之后只是UI崩溃了，用yacd可以正常连接http://10.0.10.3:9098
> 
> 你说你用yacd可以正常连接，你使用的是自己部署的yacd吗，我尝试使用https://yacd.metacubex.one/ 因为页面启用了https，也是无法连接到内核。

本地部署的yacd和metacubexd都可以正常连接

**Comment by Long0x0** [comment]
> 另外请问什么情况下需要填写10.0.10.3这种地址呢，0.0.0.0可以满足需求吗？

这是我的局域网ip，因为不想把接口暴露在公网上

**Comment by Long0x0** [comment]
https://github.com/tauri-apps/tauri/issues/3007 设置`dangerousUseHttpScheme`或许可以解决问题
