### ISSUE TITLE
[Feature] 希望全局模式下订阅添加和更新后默认选择REJECT或随机选择一个节点

### ISSUE THREAD

**Issue by QijYooRytowYum** [clash-verge-rev/clash-verge-rev#920]
### 功能描述 / Feature description

切换机场订阅后，默认选择DIRECT，未加载完或自动重连的网站通过DIRECT连接，导致真实ip泄露。
希望机场订阅添加或更新后默认选择REJECT或随机选择一个节点。

### 使用场景 / Use case

防止隐私泄露，防止黑名单。

**Comment by PctAIGM** [comment]
这个按理应该去内核反馈，GUI处理不了吧

**Comment by QijYooRytowYum** [comment]
> 这个按理应该去内核反馈，GUI处理不了吧

刚才mihomo议题中有人回复了我，内容如下：
mihomo并没有"订阅"功能,且默认记住选择的节点,除非配置文件更改,导致已选择的节点不存在,会恢复默认选择

**Comment by zid99825** [comment]
> > 这个按理应该去内核反馈，GUI处理不了吧
> 
> 刚才mihomo议题中有人回复了我，内容如下： mihomo并没有"订阅"功能,且默认记住选择的节点,除非配置文件更改,导致已选择的节点不存在,会恢复默认选择

默认选择的是节点列表第一个，有特殊需求的话，merge自己追加一个prepend-proxies就好了吧
