### ISSUE TITLE
[BUG] 开启流量图显设置后,GPU占用很高

### ISSUE THREAD

**Issue by lijunlin0** [clash-verge-rev/clash-verge-rev#927]
### 问题描述 / Describe the bug

开启流量图显设置后,软件在前台时GPU占用在20%以上

### 复现步骤 / To Reproduce

none

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows11

### 日志 / Log

none

**Comment by wonfen** [comment]
非bug，系统性能不行。高就关闭。
