### ISSUE TITLE
日志丢失以及hysteria2连接失败问题[BUG] 

### ISSUE THREAD

**Issue by yenaNs** [clash-verge-rev/clash-verge-rev#928]
### 问题描述 / Describe the bug

clash GUI开启tun模式，关闭系统代理。服务端使用sing-box1.9.0搭建hysteria2入站。服务端配置完成后，nekobox、clashmeta手机端均可正常连接使用。clash verge无法连接。错误信息：context deadline exceeded（确认发送给新配置的服务器）。后单独写配置文件防止分流影响判断，单独添加时可正常使用。几次更换订阅以后，日志丢失。GUI网速为0，和流量没经过核心效果一样。流量经过tun模式虚拟网卡可以正常代理，退出后虚拟网卡消失无法代理。重启软件后GUI问题依旧。

图片：YouTube打开视频正常使用，GUI无网速日志无记录。
![屏幕截图(57)](https://github.com/clash-verge-rev/clash-verge-rev/assets/153361513/ba6aa32b-fab5-4f6c-af9b-55e60ba723ca)

### 复现步骤 / To Reproduce

1.多次切换订阅后，GUI无法正常工作。
2.singbox1.9.0在服务端新搭建hysteria2入站。
3.客户端正常导入，开启了跳过ssl证书验证。无法联通。
可能无法稳定复现

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows10 22h2 内部版本19045.3803

### 日志 / Log

NO LOGS

**Comment by wonfen** [comment]
看下你的meta内核版本？
疑似内核bug
建议到内核那边反馈下，这里有几个类似的issue
https://github.com/MetaCubeX/mihomo/issues/1222
https://github.com/MetaCubeX/mihomo/issues/1197
https://github.com/MetaCubeX/mihomo/issues/993
https://github.com/MetaCubeX/mihomo/issues/997

**Comment by yenaNs** [comment]
> 看下你的meta内核版本？ 疑似内核bug 建议到内核那边反馈下，这里有几个类似的issue [MetaCubeX/mihomo#1222](https://github.com/MetaCubeX/mihomo/issues/1222) [MetaCubeX/mihomo#1197](https://github.com/MetaCubeX/mihomo/issues/1197) [MetaCubeX/mihomo#993](https://github.com/MetaCubeX/mihomo/issues/993) [MetaCubeX/mihomo#997](https://github.com/MetaCubeX/mihomo/issues/997)

好的alpha-b2280c8 Meta我去看看

**Comment by wonfen** [comment]
试试最新的alpha内核，应该修复了。
