### ISSUE TITLE
[BUG]在ubuntu18.04上安装1.2.0/1.2.1/1.3.8/1.4.3的deb文件启动时都出现了

### ISSUE THREAD

**Issue by pppyyyqqq** [clash-verge-rev/clash-verge-rev#93]
clash-verge
clash-verge: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

**Comment by MystiPanda** [comment]
后续我改成用debian10编译就可以了

**Comment by MystiPanda** [comment]
已经更新，下载最新的1.4.3版本即可。
