### ISSUE TITLE
mac端上端图标中能否加上网速的显示

### ISSUE THREAD

**Issue by wangzhishang02** [clash-verge-rev/clash-verge-rev#931]
### 功能描述 / Feature description

为了方便查看流量被无意中大量被大量流失，能否在上方状态栏中添加网速的显示

### 使用场景 / Use case

为了方便查看流量被无意中大量被大量流失，能否在上方状态栏中添加网速的显示

**Comment by agassiz** [comment]
很支持加上这个功能，能像 clash pro 那样，自己勾选是否在 mac托盘图标中显示实时速率
<img width="198" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/46200126/131421c4-b820-4c3f-a4e6-51fb66c7961a">

**Comment by logicr** [comment]
附议

**Comment by lly-ke** [comment]
+1

**Comment by mela93** [comment]
Mac需要这个功能

**Comment by z-hhh** [comment]
附议

**Comment by nxpxp** [comment]
+1

**Comment by MystiPanda** [comment]
not planned！看不看得懂，已经close了就别再回了。
