### ISSUE TITLE
[BUG] win10系统安装clash verge无法打开

### ISSUE THREAD

**Issue by qianchuyu** [clash-verge-rev/clash-verge-rev#933]
### 问题描述 / Describe the bug

win10系统安装clash verge无法打开，点开图标就闪退，不知道是不是系统更新的原因不兼容，之前用的好，现在无论下什么版本都打不开

### 复现步骤 / To Reproduce

1.win10正常使用clash
2.安装Hiddify，更新电脑系统
3.点开clash1.50包闪退
4.安装1.60也一样
5.安装1.38老版本也闪退

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

版本	Windows 10 专业版 版本号	22H2 安装日期	‎2024/‎4/‎21 操作系统内部版本	19045.4291 体验	Windows Feature Experience Pack 1000.19056.1000.0

### 日志 / Log

1.win10正常使用clash
2.安装Hiddify，更新电脑系统
3.点开clash1.50包闪退
4.安装1.60也一样
5.安装1.38老版本也闪退

**Comment by wonfen** [comment]
看faq。重装webview2试试。

**Comment by qianchuyu** [comment]
谢谢
