### ISSUE TITLE
[BUG] 连接页面不显示下载速度

### ISSUE THREAD

**Issue by XinSSS** [clash-verge-rev/clash-verge-rev#936]
### 问题描述 / Describe the bug

进行下载的过程中，clash的连接中看不到速率显示统计

### 复现步骤 / To Reproduce

进行大量下载，连接页面按DL Speed进行排序观察结果

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11 22H2

### 日志 / Log

![Snipaste_2024-04-27_12-20-12](https://github.com/clash-verge-rev/clash-verge-rev/assets/30732527/37e851fe-3097-4599-adac-55de168a60c6)
如上图所示，无论是TrafficMonitor， clash面板左下角还是steam界面，都可以看到目前正在进行下载，但在连接界面中按照DL Speed排序竟然看不到任何速度显示， 这个是不正常的

**Comment by KaranocaVe** [comment]
我也有相同的问题，很好奇为什么这么久了都没有修复
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/39995482/45b25745-f7db-40bb-89d3-bf611d8cdd51)
