### ISSUE TITLE
ubuntu24.04缺少依赖，难以安装

### ISSUE THREAD

**Issue by tungchiahui** [clash-verge-rev/clash-verge-rev#939]
### 问题描述 / Describe the bug

ubuntu24.04缺少依赖libwebkit2gtk-4.0-37。

### 复现步骤 / To Reproduce

安装时缺少依赖libwebkit2gtk-4.0-37，手动下载该依赖，发现该依赖又缺一大堆依赖。

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

kubuntu24.04

### 日志 / Log

无

**Comment by poneding** [comment]
+1

**Comment by asakimio** [comment]
+1
