### ISSUE TITLE
[Feature] RPM package support

### ISSUE THREAD

**Issue by sky96111** [clash-verge-rev/clash-verge-rev#941]
### 功能描述 / Feature description

原issue被统一关闭 https://github.com/clash-verge-rev/clash-verge-rev/issues/215 ，此处继续讨论。

请求支持RPM打包格式，以支持Cent OS、Fedora、openSUSE等RPM发行版。
Tauri v2 BundleType已正式支持rpm，可能需要等待Tauri v2正式发布
https://v2.tauri.app/references/config/#bundletype

### 使用场景 / Use case

目前没有RPM二进制文件，Appimage不适用service mode，无法开启tun https://github.com/clash-verge-rev/clash-verge-rev/issues/914

**Comment by nimbold** [comment]
Yes please.

**Comment by nimbold** [comment]
Yes please.

**Comment by sky96111** [comment]
supported in v1.6.5
https://github.com/clash-verge-rev/clash-verge-rev/commit/13babbf3303c4837ba96c830afa2981a475f53b3
