### ISSUE TITLE
Windows平台程序无法启动问题 

### ISSUE THREAD

**Issue by muzhi-hac** [clash-verge-rev/clash-verge-rev#944]
### 问题描述 / Describe the bug

平台：Windows 11 22H2 
OS版本号：22621.3447
一次重启后，无法打开，clash verge闪退
重新安装1.5.11之后仍无法打开

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

OS版本号：22621.344

### 日志 / Log

错误应用程序名称: Clash Verge.exe，版本: 1.5.11.0，时间戳: 0x66265d9c
错误模块名称: Clash Verge.exe，版本: 1.5.11.0，时间戳: 0x66265d9c
异常代码: 0xc0000409
错误偏移量: 0x00000000005fbb76
错误进程 ID: 0x0x35A0
错误应用程序启动时间: 0x0x1DA994A078E42F0
错误应用程序路径: C:\Program Files\Clash Verge\Clash Verge.exe
错误模块路径: C:\Program Files\Clash Verge\Clash Verge.exe
报告 ID: 274d5538-a262-4feb-81c8-206716c517e7
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by dongchengjie** [comment]
https://www.makeuseof.com/fix-the-software-exception-0xc0000409-error-in-windows/

**Comment by muzhi-hac** [comment]
重装webview2有效

**Comment by muzhi-hac** [comment]
新bug，输入框无法输入，就是键盘无法输入，无法复制粘贴

**Comment by dongchengjie** [comment]
你用的alpha版吗，不久才修改的

**Comment by muzhi-hac** [comment]
谢谢提醒，版本回退为1.5.11即可解决
