### ISSUE TITLE
TUN模式启动报错

### ISSUE THREAD

**Issue by Tefive** [clash-verge-rev/clash-verge-rev#945]
### 问题描述 / Describe the bug

每次启动TUN模式都会提示这个错误，打开clash软件，默认开启TUN模式，需要等待很久才可以连上网络，并且日志会弹出这个错误

### 复现步骤 / To Reproduce

打开clash软件，每次都会报这个错误

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

WIN10 21H2

### 日志 / Log

04-28 17:23:07WARNING
Start Tun interface timeout: Cannot create a file when that file already exists. [retrying 1/3]

**Comment by Lsyx-Good** [comment]
这是由于上次关闭没有正确关闭释放适配器的原因

**Comment by Tefive** [comment]
请教我该如何正确操作

**Comment by Lsyx-Good** [comment]
程序是通过kill关闭的，好像避免不了？别频繁操作开关就好

**Comment by dongchengjie** [comment]
试试最新的[alpha](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha)版本
