### ISSUE TITLE
[BUG] m2芯片的macos 下载后提示文件损坏，FAQ404了

### ISSUE THREAD

**Issue by panchao0716** [clash-verge-rev/clash-verge-rev#946]
### 问题描述 / Describe the bug

1

### 复现步骤 / To Reproduce

1

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.2

### 日志 / Log

1

**Comment by MystiPanda** [comment]
https://clash-verge-rev.github.io/faq/file/

**Comment by panchao0716** [comment]
已收到，谢谢！
