### ISSUE TITLE
[BUG] clash meta占用cpu100%

### ISSUE THREAD

**Issue by haibara-brownie** [clash-verge-rev/clash-verge-rev#947]
### 问题描述 / Describe the bug

在使用clash meta内核时（标准版meta，不是alpha版），打开tun模式和服务模式，启动个人电脑热点，会导致meta内核占用cpu达到100%

### 复现步骤 / To Reproduce

clash verge版本1.6.0
meta版本1.18.1
开启tun模式和服务模式后，启动电脑个人热点，电脑会十分卡顿，打开任务管理器，clash meta会占用剩余的全部cpu

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 23H2 Windows Feature Experience Pack 1000.22700.1003.0

### 日志 / Log

日志如下图
![~_GBA{GKGS0ATH0~BTXMF`P](https://github.com/clash-verge-rev/clash-verge-rev/assets/71000573/29561b3c-c05b-48ad-b36e-a7a582d47dee)

**Comment by dongchengjie** [comment]
日志去日志目录找

**Comment by haibara-brownie** [comment]
这个是Service目录下的日志文件
[2024-04-29-1351.log](https://github.com/clash-verge-rev/clash-verge-rev/files/15145545/2024-04-29-1351.log)

**Comment by 66xiaoge** [comment]
看这哥的文档
https://github.com/snakem982/Pandora-Box/blob/main/README-CN.md#为什么不支持tunnel模式
如果只是浏览网页，关闭Tun模式会比较稳定

**Comment by Alexius66** [comment]
#https://github.com/MetaCubeX/mihomo/issues/1178
这是内核bug，切换到alpha能解决问题。
