### ISSUE TITLE
[BUG] operation not permitted

### ISSUE THREAD

**Issue by tendrillion** [clash-verge-rev/clash-verge-rev#948]
### 问题描述 / Describe the bug

配置代理后，测试栏显示正常，但是无法联网。
日志显示错误：
Start Redir server error: operation not permitted
Start TProxy server error: operation not permitted

使用sudo启动，问题依旧。

### 复现步骤 / To Reproduce

ubuntu 22.04桌面环境
安装clash-verge_1.6.0_amd64.deb
配置代理后，测试正常，但是无法连接外网。

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

ubuntu22.04

### 日志 / Log

04-29 15:04:34INFO
Start initial configuration in progress
04-29 15:04:34INFO
Geodata Loader mode: memconservative
04-29 15:04:34INFO
Geosite Matcher implementation: succinct
04-29 15:04:34INFO
Initial configuration complete, total time: 3ms
04-29 15:04:34INFO
RESTful API listening at: 127.0.0.1:9097
04-29 15:04:34INFO
Sniffer is closed
04-29 15:04:34INFO
HTTP proxy listening at: 127.0.0.1:7899
04-29 15:04:34INFO
SOCKS proxy listening at: 127.0.0.1:7898
04-29 15:04:34WARNING
Failed to start Redir UDP Listener: operation not permitted
04-29 15:04:34INFO
Redirect proxy listening at: 127.0.0.1:7895
04-29 15:04:34ERROR
Start Redir server error: operation not permitted
04-29 15:04:34ERROR
Start TProxy server error: operation not permitted

**Comment by wonfen** [comment]
内核赋予权限了吗？

**Comment by LM-Tang** [comment]
> 内核赋予权限了吗？

请问内核赋予权限需要怎么操作？我在Rocky Linux上也遇到了这个问题

**Comment by QuestionMark001** [comment]
> > 内核赋予权限了吗？
> 
> 请问内核赋予权限需要怎么操作？我在Rocky Linux上也遇到了这个问题

openSUSE也有这个问题😂

**Comment by Sellaris** [comment]
> 内核赋予权限

赋了没用
