### ISSUE TITLE
[Feature] 求个ubuntu snap打包的版本

### ISSUE THREAD

**Issue by jibejb** [clash-verge-rev/clash-verge-rev#949]
### 功能描述 / Feature description

希望将来有Ubuntu SNAP的打包版本以解决"https://github.com/clash-verge-rev/clash-verge-rev/issues/866"这个issue的问题

### 使用场景 / Use case

Ubuntu 24.04没有libwebkit2gtk4.0，所以无法用deb版本。tauri打的包又必须依赖libwebkit2gtk4.0，所以将来支持Ubuntu24.04也无望，希望有snap版的打包。

**Comment by zbc258** [comment]
这个包可以手动下的，下完安上就能装了

**Comment by notavaliablename** [comment]
打包成snap还不如打包成flatpak，打包成snap肯定会出一大堆bug，而且snap安装包体积巨大。我自己用ubuntu的话肯定会第一时间卸载snap，然后改装flatpak。

**Comment by burnedout1024** [comment]
snap has shockingly bad performance issue
