### ISSUE TITLE
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

### ISSUE THREAD

**Issue by tungchiahui** [clash-verge-rev/clash-verge-rev#951]
### 问题描述 / Describe the bug

AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
![df2e5060-4411-415a-b39e-5a4149053880](https://github.com/clash-verge-rev/clash-verge-rev/assets/93080615/64246dc3-852b-47dc-9cee-c470a5b4562d)

### 复现步骤 / To Reproduce

打开clash-verge

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

kubuntu24.04

### 日志 / Log

AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

**Comment by xishang0128** [comment]
@tungchiahui 添加变量  WEBKIT_DISABLE_DMABUF_RENDERER=1

**Comment by tungchiahui** [comment]
> @tungchiahui 添加变量  WEBKIT_DISABLE_DMABUF_RENDERER=1

可以啦，厉害👍🏻谢谢啦
