### ISSUE TITLE
[BUG] Cannot install on Ubuntu 24.04

### ISSUE THREAD

**Issue by mcwindy** [clash-verge-rev/clash-verge-rev#956]
### 问题描述 / Describe the bug

Cannot install on Ubuntu 24.04

### 复现步骤 / To Reproduce

Download `https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v1.6.0/clash-verge_1.6.0_amd64.deb` and install via apt.

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu 24.04

### 日志 / Log

➜  sudo apt install ./clash-verge_1.6.0_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'clash-verge' instead of './clash-verge_1.6.0_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 clash-verge : Depends: libwebkit2gtk-4.0-37 but it is not installable
E: Unable to correct problems, you have held broken packages.

➜  apt search libwebkit2gtk
Sorting... Done
Full Text Search... Done
libwebkit2gtk-4.0-doc/noble 2.44.0-2 all
  WebKitGTK documentation (transitional dummy package)

libwebkit2gtk-4.1-0/noble,now 2.44.0-2 amd64 [installed,automatic]
  Web content engine library for GTK

libwebkit2gtk-4.1-dev/noble 2.44.0-2 amd64
  Web content engine library for GTK - development files

**Comment by mcwindy** [comment]
Duplicated #955

**Comment by kaizhuanren** [comment]
How to  address it?

**Comment by mcwindy** [comment]
@kaizhuanren 

https://github.com/clash-verge-rev/clash-verge-rev/issues/866#issuecomment-2094205677
