### ISSUE TITLE
[Feature] Linux下任务栏右键菜单新增“服务模式”切换

### ISSUE THREAD

**Issue by tjw123hh** [clash-verge-rev/clash-verge-rev#958]
### 功能描述 / Feature description

![图片](https://github.com/clash-verge-rev/clash-verge-rev/assets/56749271/a59d62f1-bf5f-4e3b-9852-0f2db9ab9598)

在此处添加“服务模式”切换按钮

### 使用场景 / Use case

便于切换模式，且与TUN模式、系统代理一致

**Comment by MystiPanda** [comment]
@tjw123hh 服务模式并不是和系统代理、tun模式同类型的功能，它不需要频繁切换。
