### ISSUE TITLE
[BUG]x64 portable can't work

### ISSUE THREAD

**Issue by SpaceMarch777** [clash-verge-rev/clash-verge-rev#96]
OS: Windows11 23h2
Ver: Clash.Verge_1.4.3_x64_portable
Iuuses: x86 portable works fine, but x64 can't import subs links and error when setting.
![2023-12-07 155845](https://github.com/abbodi1406/vcredist/assets/95964302/3eb5aec5-0d37-44ff-b45d-d8d87495178d)
![2023-12-07 160558](https://github.com/abbodi1406/vcredist/assets/95964302/c1958133-ea92-480c-b07f-ac4cc01d5850)

**Comment by MystiPanda** [comment]
If you want to use the portable version, please do not put it in a directory that requires high permissions. `Clash Verge` running directly does not have permission to write data under `C:\Program Files\` directory.

**Comment by SpaceMarch777** [comment]
Thx, when file directory was changed to under Users\XXXX\AppData\Roaming, everything was solved!
