### ISSUE TITLE
[Feature] 切换代理模式时立即刷新当前配置（clash-verge.yaml）

### ISSUE THREAD

**Issue by letsky192** [clash-verge-rev/clash-verge-rev#960]
### 功能描述 / Feature description

在`代理`页面切换`全局`或`规则`，不会刷新`clash-verge.yaml`。
希望能改为切换模式时立即刷新。

### 使用场景 / Use case

现在这样，有时会导致，切换模式之后，过一会又恢复为`clash-verge.yaml`中`mode`。

**Comment by dongchengjie** [comment]
`mode`并不是保存在`clash-verge.yaml`，而是`config.yaml`，且切换模式会刷新`config.yaml`
`clash-verge.yaml`是运行时的临时文件
