### ISSUE TITLE
[Feature] 根据 浅色 / 深色 主题模式保存主题设置

### ISSUE THREAD

**Issue by detiam** [clash-verge-rev/clash-verge-rev#961]
### 功能描述 / Feature description

根据“主题模式”是浅色或者深色分别保存“主题设置”的设置。

### 使用场景 / Use case

当前“主题设置”不根据主题模式分别保存，如果在深色模式更改 Primary Color 为亮色（比如 #fff），切换到浅色模式后 Primary Color 依然为亮色，导致可读性差。

**Comment by skymagician** [comment]
还有希望可以增加一套深色模式下的自定义系统托盘图标。我现在自定义的图标是黑色的，系统切换到深色模式下就看不清了。
