### ISSUE TITLE
[Feature]  求RPM包！或者直接提供程序的tar.gz

### ISSUE THREAD

**Issue by notavaliablename** [clash-verge-rev/clash-verge-rev#966]
### 功能描述 / Feature description

Appimage打包的Clash Verge不支持开启TUN模式，一些程序并不能使用系统代理  
求提供RPM包以支持RHEL，Fedora等Red Hat系Linux  
或者干脆直接提供程序的tar.gz  

系统：Fedora 40  
桌面环境：Plasma 6.0.4

### 使用场景 / Use case

开启TUN模式

**Comment by hustler-not-chatty** [comment]
你可以直接下载 AppImage，并用 `--appimage-extract` 提取出内容来使用，还省下了装依赖的功夫。

**Comment by Rickxiaoxin** [comment]
@hustler-not-chatty 你好，我在fedora中使用clash verge rev 1.6.2，打开系统代理后开启状态是false，测试中可以连接google，但是通过firefox无法连接google。
![图片](https://github.com/clash-verge-rev/clash-verge-rev/assets/87167211/6b04a942-0e19-4a65-8aa9-2635c615b728)
这是为什么呢？怎么解决这个问题呢
