### ISSUE TITLE
[BUG] 使用rdp远程连接windows10电脑时，被控端电脑的各协议代理服务 socks http 无法启动

### ISSUE THREAD

**Issue by huayuprophet** [clash-verge-rev/clash-verge-rev#967]
### 问题描述 / Describe the bug

使用微软自带rdp远程连接windows10电脑时，被控端电脑的socks代理无法正常工作，无法连接到代理服务

### 复现步骤 / To Reproduce

复现比较简单，就是装个windows系统，我这是win10，不清楚其他版本会不会有相同问题。
然后先用rdp连接此电脑，打开clash verge，就行了，出现bug，无法连接socks代理
而且不仅仅是socks连不上，http代理也连不上
tun和系统代理未测试，但初步推测应该也是不能用的

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 10

### 日志 / Log

没有日志

**Comment by linchangyi** [comment]
same question.

**Comment by wonfen** [comment]
已经测试，无法复现。估计是你系统的问题。
