### ISSUE TITLE
[BUG] 通过URL Scheme下载配置，丢失&flag

### ISSUE THREAD

**Issue by vstar37** [clash-verge-rev/clash-verge-rev#970]
### 问题描述 / Describe the bug

即便加上&flag=meta，下载后的配置中的Subscription URL中仍然没有&flag=meta

### 复现步骤 / To Reproduce

通过clash://install-config?url="subscrption URL"&flag=meta 下载订阅配置 (脱敏)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

none

**Comment by MystiPanda** [comment]
我这边没问题

**Comment by dongchengjie** [comment]
`&flag=meta`要放在url里面，使用[URI编码](https://tool.chinaz.com/tools/urlencode.aspx)

**Comment by vstar37** [comment]
> `&flag=meta`要放在url里面，使用[URI编码](https://tool.chinaz.com/tools/urlencode.aspx)

是编码的问题
