### ISSUE TITLE
[Feature] 新增启动界面选项，在软件启动时不打开任何界面的选项

### ISSUE THREAD

**Issue by yiluoe** [clash-verge-rev/clash-verge-rev#971]
### 功能描述 / Feature description

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/144141994/982596c4-3f3e-456c-bb5a-7b1c67419b96)
在软件自动启动时总会打开至少任意一个界面，希望新增一个软件启动时不打开任何界面的选项。

### 使用场景 / Use case

很多时候用户可能希望在启动系统时让clash verge在后台静默启动，而不展示任何界面，省去冗余的重复关闭ui的操作。

**Comment by yiluoe** [comment]
@RoyalCiCi 感谢您的回答，按照您提供的方式解决了我的问题。

**Comment by xiaoQQya** [comment]
> @RoyalCiCi 系统启动后的第一次clash verge运行时(开机启动)静默启动选项会失效，而退出软件再重新打开时是正常的。

参考 https://clash-verge-rev.github.io/faq/service.html#_3

**Comment by yiluoe** [comment]
@xiaoQQya 谢谢问题已解决。
