### ISSUE TITLE
[BUG] 界面无法显示

### ISSUE THREAD

**Issue by zbc258** [clash-verge-rev/clash-verge-rev#972]
### 问题描述 / Describe the bug

在最新的Ubuntu24.04 LTS版本中，使用deb包安装clash-verge-rev1.61版本，有概率遇到界面无法显示的问题，即无法进入图形化界面，但代理服务本身运行正常。

### 复现步骤 / To Reproduce

安装deb包，首次启动并配置订阅、全局代理、服务模式等功能均正常，重启后无法进入图形化界面，但任务栏按钮操作正常。
已经尝试过按照帮助文档中提到的“在环境变量中设置WEBKIT_DISABLE_COMPOSITING_MODE=1“，但未能解决问题。
推测问题出在libwebkit2gtk依赖上，之前系统并未自带这个包，我从仓库手动下载安装了这个包才安装成功。

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Ubuntu24.04 LTS

### 日志 / Log

[logs.zip](https://github.com/clash-verge-rev/clash-verge-rev/files/15190054/logs.zip)

**Comment by zbc258** [comment]
尝试卸载了新的libwebkit2gtk-4.1，只保留了libwebkit2gtk-4.0-37，但问题仍然存在。

**Comment by zbc258** [comment]
目前暂时的解决方案：
1.在确保系统中安装了libwebkit2gtk-4.0-37的前提下，卸载libwebkit2gtk-4.1-0 （如果一个不留的话进不了桌面，还得用命令行装）
2.不要在环境变量中设置WEBKIT_DISABLE_COMPOSITING_MODE=1，如果已经设置就删掉并重新加载环境变量。
目前暂时可以显示了，但不知道什么时候问题会再出现。

**Comment by JiakaiYang** [comment]
一样的空白界面无法操作。
尝试和你一样解决问题，失败。重装依赖再重装clash verge 都是空白界面



PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by Dragon1573** [comment]
> 重装依赖

当前 `v2.4.4` 与 `v2.4.5+autobuild` 应该已经切换到 `libwebkit2gtk-4.1-0` 。

同时，请确认你使用的 WM 和 Backend ，前序 Issues 有提到 Clash Verge Rev + Wayland 组合可能有问题。可以尝试一下 [文档中的解决方案](https://www.clashverge.dev/faq/linux.html?h=wayland) 。
