### ISSUE TITLE
[BUG] 代理界面异常不显示任何内容

### ISSUE THREAD

**Issue by LOGYT-Eberk** [clash-verge-rev/clash-verge-rev#973]
### 问题描述 / Describe the bug

打开主界面后，代理界面显示空白。无法切换结点。但依然可从托盘图标启动系统代理，且代理功能正常可用
![屏幕截图 2024-05-03 105219](https://github.com/clash-verge-rev/clash-verge-rev/assets/117907349/4d3cfe38-b0aa-4399-acad-40a64c219fdd)

### 复现步骤 / To Reproduce

打开应用，即会复现问题。重启应用无法解决问题。重新安装应用也无法解决问题。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 23H2 22631.3527

### 日志 / Log

[2024-05-03-1044.log](https://github.com/clash-verge-rev/clash-verge-rev/files/15195847/2024-05-03-1044.log)

**Comment by dongchengjie** [comment]
可能是端口9097被占用了。使用“随机端口”试试，`Clash设置`->`端口设置`字样旁边的双叉按钮，使用任意的可用端口

**Comment by LOGYT-Eberk** [comment]
> 可能是端口9097被占用了。手动改一下端口 `外部控制`，将127.0.0.1:9097改成其他127.0.0.1:端口

谢谢。问题已经解决

**Comment by swRains** [comment]
附加一下，如果外部控制的秘钥中带中文字符也会造成此类问题

**Comment by dongchengjie** [comment]
> 附加一下，如果外部控制的秘钥中带中文字符也会造成此类问题

确实，alpha已修改

**Comment by xiaozhao2000** [comment]
为什么我手动更改了端口，代理页面还是没有展示内容
clash verge版本V1.7.6
![image](https://github.com/user-attachments/assets/32878519-b719-4f8f-a0a3-0912eed028d0)
![image](https://github.com/user-attachments/assets/772686d9-63b6-45df-a30d-6e2d580f449c)
