### ISSUE TITLE
[Feature] 支持端口号自定义

### ISSUE THREAD

**Issue by rtspideriki** [clash-verge-rev/clash-verge-rev#976]
### 功能描述 / Feature description

设置栏目中的端口设置只能采样随机的端口分配，这个端口的优先级是不是高于订阅链接配置文件中的端口设定，如何高于的话，可以提供一下自定义配置文件设置，打开系统配置文件，只显示可读模式欸

### 使用场景 / Use case

需要配置端口的应用程序

**Comment by MystiPanda** [comment]
@rtspideriki 随机难道不是你自己开的吗
