### ISSUE TITLE
[BUG]代理组白屏，无法选择节点

### ISSUE THREAD

**Issue by shifengbin** [clash-verge-rev/clash-verge-rev#98]
**Describe the bug**
代理组白屏，无法选择节点

**To Reproduce**
目前不清楚，第二天打开软件发现点击节点无法选中，然后刷新了一下订阅链接，代理组所有节点都消失

**Expected behavior**
可以正常选择
**Screenshots**
![截图 2023-12-08 10-08-29](https://github.com/clash-verge-rev/clash-verge-rev/assets/14366712/d0b3cf4e-a0d4-4880-bbf2-3e1f0d1feb49)

**Information**

- OS: Ubuntu 22.04
- Clash Verge Version:1.4.3

**Comment by wonfen** [comment]
非bug，看看日志是不是端口冲突了。
