### ISSUE TITLE
【BUG】图标错乱

### ISSUE THREAD

**Issue by gxx2778** [clash-verge-rev/clash-verge-rev#980]
### 问题描述 / Describe the bug

图标错乱，两个显示器，在MAC的屏幕上会有图标黑影和最左侧的Apple logo有重叠，<img width="1128" alt="iShot_2024-05-06_20 50 52" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/130665334/6a56699a-d764-41af-9e4c-b3339f2988b4">正常。

### 复现步骤 / To Reproduce

在此前的版本上也出现过，但之前重启APP后就正常了。这次重启APP后依旧有这个问题。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.4.1

### 日志 / Log

无

**Comment by dongchengjie** [comment]
~~是特性呢~~😅#734

**Comment by MystiPanda** [comment]
#759

**Comment by JokerSuyan2801** [comment]
v1.6.4 mac版本14.5 问题依旧，左右各一个图标，按左边的图标右边图标产生反应，重启也没有修复。
![Uploading WX20240527-171129@2x.png…]()
