### ISSUE TITLE
[BUG] 订阅更新不了

### ISSUE THREAD

**Issue by tonycody** [clash-verge-rev/clash-verge-rev#981]
### 问题描述 / Describe the bug

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/6773121/c70c2acd-d571-4663-bb00-ecbff91ab146)
升级到 1.6.1 之后，订阅链接一更新就报错。基本上无法使用了！

### 复现步骤 / To Reproduce

刷新订阅地址

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26040.1000

### 日志 / Log

无法提供日志，因为日志里面居然没有对订阅地址做过滤处理，提供了日志。等于把自己所有的订阅链接都提供了！

**Comment by wonfen** [comment]
你这个不是明摆着机场订阅出问题了吗？

**Comment by tonycody** [comment]
这个不稳定，每次一更新就有点问题。反馈第一怀疑是使用人有问题。换其它工具了
