### ISSUE TITLE
[BUG] 微软 TODO

### ISSUE THREAD

**Issue by tonycody** [clash-verge-rev/clash-verge-rev#982]
### 问题描述 / Describe the bug

一但开启了代理，微软的TODO或其它微软服务就不可用。怎么样能过滤掉微软的走直连？看改 config.yaml 配置文件的规则部分可以实现，但问题是。订阅一更新，不又没了？

而且当有多个订阅链接的时候，每个订阅里面都得配。好麻烦，为什么规则不单独拧出来呢？通过 app 级别来配置，和订阅链接无关掉。

### 复现步骤 / To Reproduce

开启系统代理，微软TODO无法同步，其它微软服务可能也不可用。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26040.1000

### 日志 / Log

无

**Comment by wonfen** [comment]
看文档使用merge

**Comment by tonycody** [comment]
不稳定，换别的工具了
