### ISSUE TITLE
[BUG] 单独覆写use-system-hosts会影响其他dns配置

### ISSUE THREAD

**Issue by SakuraSayaka** [clash-verge-rev/clash-verge-rev#983]
### 问题描述 / Describe the bug

使用Merge或者其他某些方法覆写配置时单独写入use-system-hosts会导致其他的dns配置也被修改（疑似）

### 复现步骤 / To Reproduce

新建Merge规则，写入
dns:
  use-system-hosts: false
导致DNS无效

### 操作系统 / OS
Clash Verge V1.6.1
Clash 内核 alpha-5dd883e Meta
Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

time="2024-05-07T22:17:45.0807213+08:00" level=info msg="Start initial configuration in progress"
time="2024-05-07T22:17:45.0868887+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-05-07T22:17:45.0868887+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-05-07T22:17:45.0904759+08:00" level=info msg="Initial configuration complete, total time: 4ms"
time="2024-05-07T22:17:45.0920139+08:00" level=info msg="Sniffer is closed"
time="2024-05-07T22:17:45.10278+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9097"
time="2024-05-07T22:17:45.1032928+08:00" level=info msg="HTTP proxy listening at: [::]:7899"
time="2024-05-07T22:17:45.1043173+08:00" level=info msg="SOCKS proxy listening at: [::]:7898"
time="2024-05-07T22:17:45.1048282+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:7897"
time="2024-05-07T22:17:45.1053536+08:00" level=info msg="Start initial Compatible provider XFLTD"
time="2024-05-07T22:17:45.1053536+08:00" level=info msg="Start initial Compatible provider default"
time="2024-05-07T22:17:45.1053536+08:00" level=info msg="Start initial Compatible provider 故障转移"
time="2024-05-07T22:17:45.1053536+08:00" level=info msg="Start initial Compatible provider 自动选择"
time="2024-05-07T22:17:50.1331183+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:14868 --> 140.82.112.26:443 error: cn1.one.edu.kg:12006 connect error: dns resolve failed: lookup cn1.one.edu.kg: i/o timeout"
time="2024-05-07T22:17:50.3833391+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:14867 --> 140.82.112.26:443 error: cn1.one.edu.kg:12006 connect error: dns resolve failed: lookup cn1.one.edu.kg: i/o timeout"
time="2024-05-07T22:17:55.0328418+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:14917 --> 140.82.112.26:443 error: cn1.one.edu.kg:12006 connect error: dns resolve failed: lookup cn1.one.edu.kg: i/o timeout"
time="2024-05-07T22:17:55.1338166+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:14918 --> 140.82.112.26:443 error: cn1.one.edu.kg:12006 connect error: dns resolve failed: lookup cn1.one.edu.kg: i/o timeout"
time="2024-05-07T22:17:55.3845996+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:14922 --> 140.82.112.26:443 error: cn1.one.edu.kg:12006 connect error: connect failed: dial tcp 91.199.84.57:12006: i/o timeout"
time="2024-05-07T22:18:00.5513217+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:14930 --> 142.251.130.14:443 error: cn1.one.edu.kg:12006 connect error: context deadline exceeded"
time="2024-05-07T22:18:00.6582536+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:14934 --> 140.82.112.26:443 error: cn1.one.edu.kg:12006 connect error: context deadline exceeded"
time="2024-05-07T22:18:00.6718175+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:14929 --> 173.222.146.99:443 error: cn1.one.edu.kg:12006 connect error: context deadline exceeded"
time="2024-05-07T22:18:03.2330145+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:14980 --> 140.82.112.26:443 error: cn1.one.edu.kg:12006 connect error: dns resolve failed: lookup cn1.one.edu.kg: i/o timeout"
time="2024-05-07T22:18:08.4961141+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:14989 --> 173.222.146.99:443 error: cn1.one.edu.kg:12006 connect error: context deadline exceeded"
time="2024-05-07T22:18:08.5026369+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:14987 --> 142.251.130.14:443 error: cn1.one.edu.kg:12006 connect error: context deadline exceeded"
time="2024-05-07T22:18:08.5091712+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:1053 --> 140.82.112.26:443 error: cn1.one.edu.kg:12006 connect error: context deadline exceeded"
time="2024-05-07T22:18:11.4364951+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:1064 --> 142.250.157.188:443 error: cn1.one.edu.kg:12006 connect error: context deadline exceeded"
time="2024-05-07T22:18:14.6582954+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:1088 --> 140.82.112.26:443 error: cn1.one.edu.kg:12006 connect error: context deadline exceeded"
time="2024-05-07T22:18:16.7360571+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:1096 --> 142.250.157.188:443 error: cn1.one.edu.kg:12006 connect error: context deadline exceeded"
time="2024-05-07T22:18:19.9651279+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:1107 --> 140.82.112.26:443 error: cn1.one.edu.kg:12006 connect error: context deadline exceeded"
time="2024-05-07T22:18:21.7375584+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:1113 --> mtalk.google.com:443 error: cn1.one.edu.kg:12006 connect error: dns resolve failed: lookup cn1.one.edu.kg: i/o timeout"

**Comment by MystiPanda** [comment]
Merge 里面写的除了prepend、append那几个，其他都是直接覆盖的。

**Comment by dongchengjie** [comment]
alpha版已修改merge逻辑，未打算merge的配置的`其他部分配置项`会保持不变
