### ISSUE TITLE
[BUG] 启用流量图显GPU占用过高

### ISSUE THREAD

**Issue by Tunglies** [clash-verge-rev/clash-verge-rev#984]
### 问题描述 / Describe the bug

启用流量图显GPU占用过高
![QQ截图20240508073530](https://github.com/clash-verge-rev/clash-verge-rev/assets/77394545/1c3431e3-f6bb-4826-a00b-529a40aa1dc7)

![QQ截图20240508073545](https://github.com/clash-verge-rev/clash-verge-rev/assets/77394545/53121413-f08a-46cc-ab83-bb3013330770)

### 复现步骤 / To Reproduce

点开关

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

无需LOG

**Comment by wonfen** [comment]
已经修复 https://github.com/clash-verge-rev/clash-verge-rev/commit/e520be80c0fa6d08f8857c437d2644496f969ff3

请尝试最新alpha版。

**Comment by Tunglies** [comment]
> 已经修复 [e520be8](https://github.com/clash-verge-rev/clash-verge-rev/commit/e520be80c0fa6d08f8857c437d2644496f969ff3)
> 
> 请尝试最新alpha版。

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/77394545/cd4e1cc7-f4a5-4e30-be10-2e0d26bd43a3)
感谢，改善了很多。

**Comment by Little1Git** [comment]
3060 12G显卡16%占用
