### ISSUE TITLE
[BUG] 导入某个订阅后，软件崩溃、电脑蓝屏，重启后所有订阅不见了，无法导入历史存在本地的yaml订阅

### ISSUE THREAD

**Issue by lige47** [clash-verge-rev/clash-verge-rev#985]
### 问题描述 / Describe the bug

如题，存在于本地目录C:\Users\Tokyo\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev\profiles下的所有的yaml的订阅无法通过拖动的方式导入到verge中，但是可以导入原版clash，

### 复现步骤 / To Reproduce

![recording](https://github.com/clash-verge-rev/clash-verge-rev/assets/97075835/716a9f46-2f7d-47f9-81e5-b6c96b9d776f)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows10  21H2  clash verge 1.6.1

### 日志 / Log

[2024-05-08-0903.log](https://github.com/clash-verge-rev/clash-verge-rev/files/15242689/2024-05-08-0903.log)

**Comment by lige47** [comment]
只能用过右上角新建里面的本地文件，但是拖动既然有加号，逻辑上就应该是可以导入

**Comment by MystiPanda** [comment]
本地拖动导入是alpha版本的新加的功能
