### ISSUE TITLE
[BUG]  mac 设置托盘点击事件，点击托盘图标无效

### ISSUE THREAD

**Issue by iarjian** [clash-verge-rev/clash-verge-rev#987]
### 问题描述 / Describe the bug

mac 设置托盘点击事件，点击托盘图标无效

### 复现步骤 / To Reproduce

mac 设置托盘点击事件，点击托盘图标无效

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.4.1

### 日志 / Log

无log

**Comment by senwong** [comment]
左键还是右键？右键可以触发设置的事件

**Comment by iarjian** [comment]
右键是可以出发事件的  记得是最近两个版本才点的左键一直无效  逻辑好像改了  不好意思还以为是一个bug

**Comment by MystiPanda** [comment]
@iarjian 之前的逻辑是Bug
