### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by CrazyJasonwell** [clash-verge-rev/clash-verge-rev#989]
### 功能描述 / Feature description

macosx下菜单栏图标是否可以跟Windows一样根据状态变换颜色或不同的图标显示，更加方便。

### 使用场景 / Use case

macosx下菜单栏图标是否可以跟Windows一样根据状态变换颜色或不同的图标显示，更加方便。

**Comment by wonfen** [comment]
请尝试最新alpha版本，已经添加不同图标。另外mac下的任务栏图标均为单色，使用颜色区分不好看。
