### ISSUE TITLE
[BUG] 安装服务模式 无法打开“io.github.clashverge.helper”

### ISSUE THREAD

**Issue by bajiuqier** [clash-verge-rev/clash-verge-rev#992]
### 问题描述 / Describe the bug

 安装服务模式 无法打开“io.github.clashverge.helper”，因为Apple无法检查是否包含恶意软件。
此软件需要更新。请联系开发者了解更多信息。

### 复现步骤 / To Reproduce

服务模式->安装->输入密码

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS Sonoma 14.4.1

### 日志 / Log

![截屏2024-05-09 00 15 22](https://github.com/clash-verge-rev/clash-verge-rev/assets/88549423/3cc65f10-018c-4d66-a027-c5944fe4ece5)

**Comment by 925-Studio** [comment]
Just installed the latest version of Clash Verge Rev v1.6.2, the problem remains on Ventura 13.6.7. Please Help!
